define(
	 ({
		header: {
			start: "ã_start___Ç",
			searchStories: "ã_Search your stories________Ç...",
			filter: "ã_Filter___Ç",
			sort: "ã_Sort__Ç",
			sortColon: "ã_Sort___Ç:",
			numResults: "ã_Results: {{NUM_RESULTS}}________Ç",
			sortBy: "ã_Sort by___Ç",
			dateModified: "ã_Date modified_____Ç",
			title: "ã_Title___Ç",
			type: "ã_Type__Ç",
			views: "ã_Views___Ç",
			errors: "ã_Errors___Ç",
			filterBy: "ã_Filter by____Ç",
			filterItems: "ã_Filter Items_____Ç",
			apps: "ã_Apps__Ç",
			sharing: "ã_Sharing___Ç",
			clearAll: "ã_Clear all____Ç",
			clearSearch: "ã_Clears the search______Ç",
			logOut: "ã_Log Out___Ç",
			mainQuote: "ã_Storytelling is the most powerful way to put ideas into the world today_______________________Ç.",
			quoteSource: "ã_Robert McKee_____Ç",
			checkYourStories: "ã_Check Stories_____Ç",
			createStory: "ã_Create Story_____Ç",
			totalStories: "ã_Total stories: {{NUM_STORIES}}__________Ç",
			noIssues: "ã_All good___Ç",
			userStories: "ã_Stories of {{USER_NAME}}________Ç",
			headerDisabledTooltip: "ã_Please wait while we work some magic_____________Ç...",
			notOnTouch: "ã_Not available on touch devices__________Ç",
		},
		deleteModal: {
			title: "ã_Confirm Delete_____Ç",
			warningText: "ã_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________Ç.",
			deleteText: "ã_Delete___Ç",
			cancel: "ã_Cancel___Ç"
		},
		loading: {
			loadingText: "ã_Loading your stories________Ç..."
		},
		cantFindStories: {
			whereAreStories: "ã_Not seeing your story________Ç?",
			notSeeExplanation: "ã_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________Ç.",
			faq: "ã_FAQ__Ç",
			followingStoriesToUpdate: "ã_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________Ç:",
			gettingStories: "ã_Searching for stories created with early versions of our applications that need to be updated______________________________Ç...",
			title: "ã_Title___Ç",
			typeOfStoryMap: "ã_Type__Ç",
			lastModified: "ã_Last modified_____Ç",
			allUpToDate: "ã_No stories created with early versions of our applications need to be updated________________________Ç.",
			updateAll: "ã_Update All____Ç",
			errorScanningForStories: "ã_There was an error searching your stories______________Ç.",
			close: "ã_Close___Ç",
			updates: "ã_Updates___Ç",
			updatingNumberOfNumber: "ã_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________Ç",
			updatingNumberOfNumberAlt: "ã_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________Ç",
			updateSucceeded: "ã_Update succeeded______Ç!",
			reloadingStories: "ã_Reloading your stories_________Ç...",
			errorUpdatingStories: "ã_There was an error updating your stories_____________Ç.",
			partialUpdateMessage: "ã_Stories updated successfully: {{NUM_UPDATED}}_______________Ç"
		},
		signIn: {
			signInTitle: "ã_Sign in to Story Maps_______Ç",
			signInTo: "ã_Sign in with your existing ArcGIS Online account to_________________Ç:",
			explanationOne: "ã_Create compelling story maps to tell your stories________________Ç.",
			explanationTwo: "ã_Use your maps and data from ArcGIS Online in your story maps___________________Ç.",
			explanationThree: "ã_Manage your story maps and check the status of their content___________________Ç.",
			dontHaveAccount: "ã_Don't have an ArcGIS Online account? Sign up for a________________Ç:",
			publicAccount: "ã_Free non-commercial public account___________Ç",
			orgAccount: "ã_Free trial ArcGIS subscription__________Ç",
			timeExpired: "ã_Your sign-in expired. Sign in again to pick up where you left off_____________________Ç.",
			apiDidntLoad: "ã_Something isn't loading correctly. Try refreshing the page___________________Ç.",
			needAccount: "ã_Need an account______Ç?",
			letsGo: "ã_Let's go____Ç!"
		},
		sharingLevel: {
			publicMessage: "ã_Public___Ç",
			privateMessage: "ã_Private___Ç",
			organization: "ã_Organization_____Ç",
			changedSharing: "ã_Changed sharing level________Ç.",
			unableToChange: "ã_Unable to change sharing_________Ç.",
			partOfMap: "ã_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________Ç.",
			storyPublicContentOrg: "ã_Your story is public, so its content can't be shared only with your organization_________________________Ç",
			storyPublicContentPrivate: "ã_Your story is public, so its content can't be private_________________Ç",
			mapOrg: "ã_Sharing your map to your organization would break your story___________________Ç",
			layerOrg: "ã_Sharing your layer to your organization would break your story____________________Ç",
			mapPrivate: "ã_Making your map private would break your story_______________Ç",
			layerPrivate: "ã_Making your layer private would break your story_______________Ç"
		},
		collectionList: {
			advocacy: "ã_Advocacy and Outreach_______Ç",
			architecture: "ã_Architecture and Design________Ç",
			conservation: "ã_Conservation and Sustainability__________Ç",
			culture: "ã_Culture___Ç",
			destinations: "ã_Destinations and Tourism________Ç",
			disasters: "ã_Disasters and Recovery________Ç",
			economy: "ã_Economy and Development________Ç",
			entertainment: "ã_Entertainment_____Ç",
			history: "ã_History___Ç",
			infrastructure: "ã_Infrastructure_____Ç",
			marketing: "ã_Marketing____Ç",
			nature: "ã_Nature and Environment________Ç",
			news: "ã_News and Events______Ç",
			oceans: "ã_Oceans___Ç",
			parks: "ã_Parks and Recreation_______Ç",
			people: "ã_People and Society______Ç",
			planning: "ã_Planning and Analysis_______Ç",
			publicArt: "ã_Public Art____Ç",
			science: "ã_Science and Technology________Ç",
			sport: "ã_Sport___Ç",
			travelogues: "ã_Travelogues____Ç"
		},
		types: {
			custom: "ã_Custom___Ç",
			notSpecified: "ã_Type not specified______Ç"
		},
		storyMap: {
			shared: "ã_Shared___Ç",
			saveFailed: "ã_Error saving_____Ç",
			numViews: "ã_Views: {{NUM_VIEWS}}_______Ç",
			editStory: "ã_Edit Story____Ç",
			viewLive: "ã_View Live____Ç",
			preview: "ã_Preview___Ç",
			deleteButton: "ã_Delete___Ç",
			modified: "ã_Modified {{DATE}}______Ç",
			summary: "ã_Summary___Ç",
			loading: "ã_Loading____Ç...",
			collapse: "ã_collapse___Ç",
			close: "ã_close___Ç",
			hide: "ã_hide__Ç",
			notAvailableWhenBroken: "ã_Your story has issues below_________Ç",
			cantBeDeleted: "ã_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________Ç",
			shareDialog: {
				title: "ã_Share your story with the world___________Ç!",
				notPublicWarning: "ã_Your story is shared with your organization. Only members of your organization will be able to view it________________________________Ç.",
				embedStory: "ã_Embed your story______Ç",
				shortLink: "ã_Shortlink____Ç",
				hideHeaderBar: "ã_Hide header bar______Ç",
				copied: "ã_Copied___Ç",
				small: "ã_small___Ç",
				medium: "ã_medium___Ç",
				large: "ã_large___Ç",
				custom: "ã_custom___Ç",
				widthAbbreviation: "ã_w_Ç",
				heightAbbreviation: "ã_h_Ç",
				emptyDimension: "ã_Enter a dimension______Ç.",
				seeExample: "ã_Preview your embed______Ç",
				removeHeader: "ã_Hide application header________Ç"
			},
			maps: {
				unableRetrieveTitle: "ã_Unable to retrieve maps________Ç",
				unableRetrieveDescription: "ã_We weren't able to retrieve maps for this story map_________________Ç."
			},
			images: {
				unableRetrieveTitle: "ã_Unable to retrieve images_________Ç",
				unableRetrieveDescription: "ã_We weren't able to retrieve images for this story map_________________Ç."
			},
			tags: {
				tags: "ã_Tags__Ç",
				collectionTags: "ã_Subject___Ç",
				selectASubject: "ã_Select a subject______Ç",
				save: "ã_Save__Ç",
				saved: "ã_Saved___Ç",
				errorSaving: "ã_Error saving_____Ç",
				tagTip: "ã_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________Ç."
			},
			submitToGallery: {
				gallerySubmission: "ã_Story Maps Gallery______Ç",
				canSubmitIf: "ã_You can nominate your story to the gallery if it contains the following_______________________Ç:",
				hasOwnImage: "ã_Custom thumbnail______Ç",
				chosenSubject: "ã_A subject and some tags________Ç",
				chosenSubjectAlt: "ã_A {{SUBJECT}} and some tags_________Ç",
				storyMapTopicSubject: "ã_subject___Ç",
				sharedPublicly: "ã_Shared publicly______Ç",
				noBrokenContent: "ã_No broken content______Ç",
				nominateToGallery: "ã_Nominate to Gallery_______Ç",
				comingSoon: "ã_Coming soon_____Ç!",
				submitted: "ã_Submitted____Ç",
				errorSubmitting: "ã_Error submitting______Ç",
				ourGallery: "ã_The Story Maps gallery________Ç",
				galleryTip: "ã_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________Ç."
			},
			placeholders: {
				noSummary: "ã_No summary, click to add one__________Ç."
			},
			errors: {
				cantDeleteStory: "ã_Unable to delete story________Ç.",
				unableToFind: "ã_Unable to find content________Ç",
				unableToRetrieve: "ã_We weren't able to retrieve the content for this story map___________________Ç."
			},
			socialSharing: {
				availableWhenPublic: "ã_This option will be available when your story is public__________________Ç"
			},
			dialog: {
				back: "ã_Back__Ç",
				close: "ã_Close___Ç",
				cancel: "ã_Cancel___Ç"
			},
			imagePicker: {
				changeDefault: "ã_Change the default image________Ç",
				changeImage: "ã_Change thumbnail______Ç",
				uploadImage: "ã_Upload thumbnail______Ç",
				chooseImage: "ã_Choose thumbnail______Ç",
				chooseAnImage: "ã_Choose an Image______Ç",
				notInIEVersion: "ã_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________Ç.",
				or: "ã_Or__Ç",
				uploadAnImage: "ã_Upload an Image______Ç",
				supportedFileTypes: "ã_Supports .png, .jpg, .gif_________Ç",
				imageSizeMessage: "ã_Your image needs to be at least 286 px wide by 190 px tall___________________Ç.",
				minimumDimensions: "ã_Minimum: 286 x 190px_______Ç",
				imagesLoading: "ã_Loading images______Ç...",
				noImages: "ã_This story has no images________Ç",
				errorLoading: "ã_Unable to retrieve the images in this story______________Ç",
				clickBelowTip: "ã_Click the button below to upload an image______________Ç.",
				dragAndDrop: "ã_Drag and Drop_____Ç",
				cropImage: "ã_Crop Image____Ç",
				saveImage: "ã_Save Image____Ç",
				save: "ã_Save__Ç",
				savingImage: "ã_Saving your image_______Ç...",
				saved: "ã_Saved___Ç!",
				errorSaving: "ã_Unable to save your image_________Ç.",
				skipAndCrop: "ã_Skip and Crop for me_______Ç",
				wrongFormat: "ã_This file type is not supported___________Ç.",
				noCropWarning: "ã_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________Ç."
			}
		},
		content: {
			media: {
				maps: "ã_Maps__Ç",
				images: "ã_Images___Ç",
				videos: "ã_Videos___Ç",
				webpages: "ã_Webpages___Ç",
				tags: "ã_Tags__Ç",
				gallery: "ã_Gallery___Ç"
			},
			headers: {
				status: "ã_Status___Ç",
				source: "ã_Source___Ç",
				name: "ã_Name__Ç",
				shared: "ã_Shared___Ç"
			},
			component: {
				mapTour: "ã_Point Number_____Ç",
				bullet: "ã_Bullet___Ç",
				tab: "ã_Tab__Ç",
				accordion: "ã_Section___Ç",
				mapJournal: "ã_Section___Ç"
			},
			titleType: {
				mapTour: "ã_Caption___Ç",
				mapJournal: "ã_URL__Ç",
				mapSeries: "ã_URL__Ç"
			},
			actions: {
				viewMap: "ã_View Map___Ç",
				editMap: "ã_Edit Map___Ç",
				fix: "ã_Fix__Ç",
				viewLayer: "ã_View Layer____Ç"
			},
			contentType: {
				mainStage: "ã_main stage action______Ç",
				sidePanel: "ã_description____Ç"
			},
			notification: {
				refreshExplanation: "ã_Check your story again________Ç",
				checking: "ã_Checking____Ç...",
				foundSomeIssues: "ã_We found some issues_______Ç",
				noIssuesFound: "ã_No issues found______Ç",
				storyPublic: "ã_Your story is now public________Ç",
				storyOrg: "ã_Your story is now shared to your organization_______________Ç",
				storyPrivate: "ã_Your story is now private_________Ç",
				mapPublic: "ã_Your map is now public________Ç",
				mapOrg: "ã_Your map is now shared to your organization______________Ç",
				mapPrivate: "ã_Your map is now private________Ç",
				layerPublic: "ã_Your layer is now public________Ç",
				layerOrg: "ã_Your layer is now shared to your organization_______________Ç",
				layerPrivate: "ã_Your layer is now private_________Ç",
				contentPublic: "ã_Your content is now public_________Ç",
				contentOrg: "ã_Your content is now shared to your organization_______________Ç",
				contentPrivate: "ã_Your content is now private_________Ç",
				storyAndContentPublic: "ã_Your story and its content are now public_____________Ç",
				storyAndContentOrg: "ã_Your story and its content are now shared to your organization____________________Ç",
				storyAndContentPrivate: "ã_Your story and its content are now private______________Ç",
				shareBulkPrompt: "ã_Do you want to share your storyâ€™s content accordingly__________________Ç?",
				layersPublic: "ã_Some layers have also been shared publicly______________Ç",
				layersOrg: "ã_Some layers have also been shared with your organization__________________Ç",
				layersPrivate: "ã_Some layers have also been made private_____________Ç",
				mapsPublic: "ã_Some maps have also been shared publicly_____________Ç",
				mapsOrg: "ã_Some maps have also been shared with your organization_________________Ç",
				mapsPrivate: "ã_Some maps have also been made private____________Ç",
				layersAndMapsPublic: "ã_Some maps and layers have also been shared publicly________________Ç",
				layersAndMapsOrg: "ã_Some maps and layers have also been shared with your organization_____________________Ç",
				layersAndMapsPrivate: "ã_Some maps and layers have also been made private_______________Ç",
				yes: "ã_Yes__Ç",
				no: "ã_No__Ç",
				premiumPublicSuccess: "ã_Your premium content is now publicly accessible_______________Ç",
				subscriptionPublicSuccess: "ã_Your subscription content is now publicly accessible_________________Ç"
			},
			errors: {
				publicDisabled: "ã_Sharing publicly has been disabled by the Administrator__________________Ç",
				noMapName: "ã_Could Not Retrieve Map Name_________Ç",
				notPublic: "ã_NOT PUBLIC____Ç",
				inaccessible: "ã_INACCESSIBLE_____Ç",
				deleted: "ã_DELETED___Ç",
				cantAccessVideo: "ã_Could Not Access Video________Ç",
				noStoriesFound: "ã_We could not find any Story Maps in your content________________Ç.",
				cantShowStories: "ã_Unable to show your story maps. Please try again later__________________Ç.",
				consolationSearch: "ã_We couldn't find any stories__________Ç.",
				notCompatibleWithBrowser : "ã_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________Ç.",
				pleaseUpdateBrowser: "ã_Please update your browser_________Ç.",
				searchTip: "ã_Try and simplify it a bit_________Ç.",
				consolationNoStories: "ã_Welcome to My Stories________Ç!",
				noStoriesTip: "ã_To make your first story map, check out the Apps page_________________Ç.",
				letsGo: "ã_Let's Go___Ç",
				cantChangeSharingLevel: "ã_Unable to change sharing level__________Ç",
				cantChangeSharingLevels: "ã_Unable to change sharing levels__________Ç",
				errorUpdatingTitle: "ã_Error updating title_______Ç",
				errorUpdatingSummary: "ã_Error updating summary________Ç",
				noEmptyTitle: "ã_Title cannot be empty_______Ç",
				cantUpdatePremiumContent: "ã_Unable to update premium content___________Ç",
				cantUpdateSubscriptionContent: "ã_Unable to update subscription content____________Ç",
				createFirstStory: "ã_Create My First Story_______Ç"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "ã_Map has been deleted_______Ç",
				layerHasBeenDeleted: "ã_Layer has been deleted________Ç",
				mapIsInaccessible: "ã_Map is inaccessible_______Ç",
				layerIsInaccessible: "ã_Layer is inaccessible_______Ç",
				mapNotYoursNotAccessible: "ã_Map is owned by someone else and isn't accessible________________Ç",
				layerServiceOkItemNot: "ã_Layer was added as an item that is deleted or inaccessible__________________Ç",
				layerNotYoursNotAccessible: "ã_Layer is owned by someone else and isn't accessible________________Ç",
				mapOthersSharedBelowLevel: "ã_Map is not owned by you and is not public_____________Ç",
				layerOthersSharedBelowLevel: "ã_Layer is not owned by you and is not public______________Ç",
				noMapNoDetails: "ã_Without the map details, we can't tell you anything about the layers_____________________Ç",
				mapIsPrivate: "ã_Map is private_____Ç",
				mapIsOrg: "ã_Map is only shared in your organization_____________Ç",
				layerIsPrivate: "ã_Layer is private______Ç",
				layerIsOrg: "ã_Layer is only shared in your organization_____________Ç",
				imageInaccessible: "ã_This image is inaccessible_________Ç",
				videoInaccessible: "ã_This video is inaccessible_________Ç",
				webpageInaccessible: "ã_This web page is inaccessible__________Ç",
				layerSecureService: "ã_Layer is a secure service_________Ç",
				mapSecureService: "ã_Map is a secure service________Ç",
				layerConsumesCredits: "ã_Layer is premium content and consumes credits_______________Ç",
				layerSubscriptionContent: "ã_Layer is subscription content__________Ç",
				mapConsumesCredits: "ã_Map is premium content and consumes credits______________Ç",
				mapSubscriptionContent: "ã_Map is subscription content_________Ç"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "ã_We're not able to check this type of layer______________Ç",
				cantScanThisType: "ã_Layer is not a type of layer we can check_____________Ç",
				webpageNotScanned: "ã_Webpages are not checked for issues____________Ç"
			},
			scanningErrors: {
				deletedMap: "ã_Deleted content______Ç",
				inaccessibleMap: "ã_Inaccessible map content________Ç",
				notYoursNotAccessible: "ã_Content not owned by you and not public_____________Ç",
				serviceOkItemNot: "ã_Working layers but inaccessible items____________Ç",
				someContentNotPublic: "ã_Content not shared publicly_________Ç",
				someContentPrivate: "ã_Private content______Ç",
				othersSharedBelowLevel: "ã_Content not owned by you and not public_____________Ç",
				premiumContent: "ã_Premium content______Ç",
				subscriptionContent: "ã_Subscription content_______Ç",
				secureService: "ã_Secure services______Ç",
				inaccessibleImage: "ã_Inaccessible images_______Ç",
				inaccessibleVideo: "ã_Inaccessible videos_______Ç",
				inaccessibleWebpage: "ã_Inaccessible webpages_______Ç"
			},
			scanningErrorTips: {
				deletedMapTip: "ã_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________Ç.",
				inaccessibleMapTip: "ã_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________Ç.",
				notYoursNotAccessibleTip: "ã_Tip: Open the web map and remove the layer or map from the story_____________________Ç.",
				serviceOkItemNotTip: "ã_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________Ç.",
				ignore: "ã_Ignore___Ç",
				fix: "ã_Fix__Ç",
				clickToShareOrg: "ã_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________Ç.",
				clickToSharePublic: "ã_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________Ç.",
				shareOrg: "ã_Share to your org______Ç",
				sharePublicly: "ã_Share publicly_____Ç",
				othersSharedBelowLevelTip: "ã_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________Ç.",
				secureServiceTip: "ã_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________Ç.",
				blogArticle: "ã_here__Ç",
				premiumContentTip: "ã_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________Ç.",
				premiumContentPublicTip: "ã_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________Ç.",
				subscriptionContentTip: "ã_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________Ç.",
				agolCredits: "ã_ArcGIS Online credits_______Ç",
				credits: "ã_credits___Ç",
				makePublic: "ã_Make public____Ç",
				confirm: "ã_Confirm___Ç",
				inaccessibleImageTip: "ã_Tip: Provide the missing image or remove the reference to it___________________Ç.",
				inaccessibleVideoTip: "ã_Tip: Provide the missing video or remove the reference to it___________________Ç.",
				inaccessibleWebpageTip: "ã_Tip: Provide the missing web page or remove the reference to it____________________Ç."
			},
			removeLayer: {
				title: "ã_Fix Layer Issue______Ç",
				layersWithIssue: "ã_Layers with this issue: {{NUM_WITH_ISSUE}}______________Ç",
				issueExplanation: "ã_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________Ç.",
				issueSolution: "ã_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________Ç:",
				editMap: "ã_Edit Your Map_____Ç",
				clickBelowWhenDone: "ã_When you have finished editing, click the button below__________________Ç:",
				rescanAndClose: "ã_Rescan And Close______Ç"
			},
			info: {
				ownedBy: "ã_This item is owned by {{USER_NAME}}____________Ç",
				unknownUser: "ã_someone else_____Ç",
				untitledSection: "ã_(Untitled section)______Ç",
				introRecord: "ã_Introduction_____Ç"
			},
			layers: {
				layersHeader: "ã_Layers___Ç",
				noLayers: "ã_(No Layers)____Ç",
				basemapParens: "ã_(basemap)____Ç"
			},
			images: {
				thumbnails: "ã_Thumbnails____Ç",
				thumbnail: "ã_Thumbnail____Ç",
				thumbnailParens: "ã_(thumbnail)____Ç"
			},
			general: {
				noTitle: "ã_(no title)____Ç",
				loading: "ã_Loading____Ç..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "ã_sections___Ç",
				secondTitle: "ã_style___Ç",
				secondValueA: "ã_side panel____Ç",
				secondValueB: "ã_floating panel_____Ç",
				thirdTitle: "ã_maps__Ç"
			},
			mapTour: {
				firstTitle: "ã_tour points____Ç",
				secondTitle: "ã_style___Ç",
				secondValueA: "ã_integrated____Ç",
				secondValueB: "ã_three-panel____Ç",
				thirdTitle: "ã_basemap___Ç",
				thirdValueLoading: "ã_Loading____Ç...",
				thirdValueUnknown: "ã_unknown___Ç"
			},
			mapSeries: {
				firstTitleA: "ã_bullets___Ç",
				firstTitleB: "ã_sections___Ç",
				firstTitleC: "ã_tabs__Ç",
				secondTitle: "ã_style___Ç",
				secondValueA: "ã_bulleted___Ç",
				secondValueB: "ã_side accordion_____Ç",
				secondValueC: "ã_tabbed___Ç",
				thirdTitle: "ã_maps__Ç"
			},
			swipeSpyglass: {
				firstTitle: "ã_points of interest______Ç",
				secondTitle: "ã_style___Ç",
				secondValueA: "ã_swipe___Ç",
				secondValueB: "ã_spyglass___Ç",
				thirdTitle: "ã_maps__Ç"
			}
		},
		progress: {
			checkingStories: "ã_Checking your stories for issues____________Ç...",
			stop: "ã_Stop__Ç",
			exit: "ã_Exit__Ç",
			dismiss: "ã_Dismiss___Ç",
			done: "ã_Done___Ç.",
			noStoriesWithIssuesLower: "ã_No issues found______Ç!",
			storiesErrorFree: "ã_Looks like your stories are error-free____________Ç",
			scanAllError: "ã_Unable to scan -- we couldn't retrieve one or more of your stories_____________________Ç",
			scanProgress: "ã_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________Ç",
			scanStopped: "ã_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________Ç",
			storiesWithIssues: "ã_Stories with issues: {{NUM_STORIES}}____________Ç"
		}
    })
);