define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Wprowadź odległość",
                    "layerName": "Wprowadź tutaj nazwę warstwy"
                },
                "message": {
                    "analysisFailed": "Analiza nie powiodła się.",
                    "errorOccurred": "Wystąpił błąd.",
                    "layerAdded": "Warstwa dodana pomyślnie. ",
                    "enrichLayerNameError": "Nazwa warstwy wynikowej nie może zawierać niedozwolonych znaków" + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Trwa tworzenie usługi... ",
                    "starting": "Uruchamianie",
                    "performingAnalysis": "Wykonanie analizy",
                    "checkLayerName": "Sprawdzanie nazwy warstwy.. ",
                    "addingLayer": "Dodawanie warstwy do mapy internetowej ",
                    "layerNameExist": "Nazwa warstwy już istnieje.",
                    "clickOnSave": " Kliknij przycisk 'Zapisz', żeby ponownie wczytać aplikację.",
                    "clickOnOk": " Kliknij przycisk 'OK', żeby spróbować ponownie.",
                    "enterNumbersOnly": "Wprowadzone wartości nie są prawidłowe",
                    "nofeatures": "Brak obiektów w bieżącym zasięgu",
                    "selectData": "Wybierz dane do wzbogacenia warstwy.",
                    "resetVariableMessage": "Czy na pewno chcesz zresetować zmienną?",
                    "emptyTextFieldLayerName": "Wprowadź nazwę warstwy wynikowej",
                    "createService":"Nie utworzono warstwy.",
                    "sharingLayer":"Share layer",
                    "updateItemFailed": "Aktualizacja nie powiodła się. Spróbuj ponownie.",
                    "geoEnrichFailed": "Wzbogacanie warstwy nie powiodło się. Spróbuj ponownie.",
                    "shareFailed": "Udostępnienie wzbogaconej warstwy nie powiodło się. Spróbuj ponownie.",
                    "refreshServiceFailed": "Odświeżenie warstwy nie powiodło się. Spróbuj ponownie.",
                    "layerJsonFailed": "Utworzenie JSON dla warstwy nie powiodło się. Spróbuj ponownie.",
                    "addToWebmapFailed": "Dodanie warstwy do mapy internetowej nie powiodło się. Spróbuj ponownie.",
                    "bufferAreaHelpText": "Wprowadź wartość mniejszą niż ",
                    "invalidBufferInput": "Wprowadzona wartość nie jest prawidłowa.",
                    "emptyBufferInput": "Podaj właściwą wartość."
                },
                "populationText": "Populacja",
                "housingText": "Gospodarstwa",
                "businessText": "Biznes",
                "variableListText": " zmienne są wymienione tutaj:",
                "countrySelectTitle": "1. Wybierz lokalizację danych",
                "unitedStates": "United States",
                "global": "Global",
                "geoenrichDialogText": "Zmienne wzbogacania danych geograficznych",
                "viewVariablestext": "Wyświetl zmienne",
                "backButtonText":"Powrót",
                "customizeVariables": "Dostosuj zmienne",
                "resetVariables": "Resetuj",
                "defineAreaTitle": "3. Zdefiniuj obszar do wzbogacenia",
                "currentMapExtent": "Użyj zasięgu bieżącej mapy,",
                "enrichLayerName": "4. Nazwa warstwy wynikowej",
                "lineDistanceText": "Odległość w linii prostej",
                "drivingTime": "Czas przejazdu",
                "enrichButtonText": "Enrich Layer",
                "selectDataText": "2. Wybierz dane",
                "showCreditsText": "Pokaż udostępniającego zasoby",
                "variableCount": "Całkowita liczba zmiennych ",
                "totalRecords": "Total Records:",
                "cost": "Koszt",
                "showCreditsDialogText": "Pokaż udostępniającego zasoby",
                "nextButtonText": "Dalej",
                "prevButtonText": "Wstecz",
                "saveButtonText": "Zapisz",
                "ok": "OK"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 