define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Przejdź do trybu kreatora",
                "exitBuilderButtonText": "Opuść tryb kreatora",
                "enterBuilderModeHelpText": "Przejdź do trybu kreatora, aby skonfigurować aplikację.",
                "builderModeHelpText": "Tryb kreatora szablonów",
                "webmapCaption": "Mapa",
                "selectMapMessage": "Aktualnie: ${displaying} <b>${webmapTitle}</b><br/>Kliknij przycisk Wybierz mapę, aby wybrać inną mapę internetową.",
                "loadMapMessage": "Aktualnie wybrane <b>${webmapTitle}</b><br/>Kliknij przycisk Zapisz, aby użyć tej mapy internetowej.",
                "changeWebmap": "Wybierz mapę",
                "saveButtonText": "Zapisz",
                "webmapNextButtonText": "Dalej ->",
                "previousButtonText":"Wstecz",
                "layerLabelText": "Warstwa",
                "noLayerFoundText": "Nie znaleziono żadnych warstw",
                "selectLayer": "Wybierz warstwę",
                "applicationSettingText": "Ustawienia aplikacji",
                "summaryAttrAscendingOrderTooltip": "Rosnąco",
                "onStartLabel": "Na ekranie początkowym",
                "selectVariableText": "Wybierz zmienną",
                "selectVariableDropdown": "Wybierz zmienną",
                "label":"Etykieta",
                "sourceLinkText":"Łącze do źródła",
                "selectSubVariableText":"Wybierz zmienne podrzędne",
                "subVariablePanelButtonText":"GOTOWE",
                "onButtonLabel":"Włączone",
                "offButtonLabel":"Wyłączone",
                "appSettingsSaveCloseButtonText": "ZAPISZ I ZAMKNIJ",
                "appSettingsTitleText":"Tytuł aplikacji",
                "appSettingsDescriptionText": "Opis aplikacji",
                "appSetingsRendererAreaText":"Obszar renderowania",
                "shareText":"Udostępnij",
                "popupText": "ł_Popup_ą",
                "basemapText":"Mapa bazowa",
                "cancel": "ł_Cancel_ą",
                "theme": "ł_Theme_ą",
                "zoomLevel": "ł_Zoom Level_ą",
                "existingValue": "ł_Use existing values_ą",
                "enrichLayer": "ł_Enrich Layer_ą",
                "imageLabel": "ł_How does this work_ą ?",
                "clearData": "ł_Clear Data_ą",
                "basemapSelectionText":"Wybór mapy bazowej",
                "secondaryBasemapText":"Pomocnicza mapa bazowa",
                "defaultBasemapText": "Domyślna mapa bazowa",
                "entireAreaButton": "Cały obszar",
                "entireAreaOnStartButton": "Cały obszar na ekranie początkowym",
                "aboutPanel": "Informacje o panelu",
                "legendPanel": "Panel Legenda",
                "layersPanel": "Panel Warstwy",
                "dataConfigurationButtonText": "Konfiguracja danych",
                "savingChangesMessage": "Zapisywanie zmian...",
                "nextButtonText": "Dalej",
                "prevButtonText": "Wstecz",
                "enterLabelText": "Wprowadź etykietę",
                "SelectedFeatureText": "Wybrany obiekt",
                "layerHelpTextMessage": "W tej aplikacji wymagana jest warstwa z polami numerycznymi.",
                "alertMessage": {
                    "resetVariableMessage": "Czy na pewno chcesz zresetować zmienną?",
                    "emptyAppTitleMessage": "Pole Tytuł aplikacji nie może być puste.",
                    "emptyDescriptionMessage": "Pole Opis nie może być puste.",
                    "maxVariableSelection": "Nie można wybrać więcej niż 25 zmiennych podrzędnych.",
                    "signInFail" : "Logowanie nie powiodło się",
                    "itemUpdateMessage": "Element został zaktualizowany",
                    "unsavedChangesMessage": "Niezapisane zmiany",
                    "failMessage": "Nie można pomyślnie zaktualizować elementu.",
                    "saveChangesAlert": "Czy chcesz zapisać zmiany?",
                    "variableLabelValidation": "Pole Etykieta zmiennej nie może być puste.",
                    "subVariableLabelValidation": "Pole Etykieta zmiennej podrzędnej nie może być puste."
                    }
            }
        }
    })
);