define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "أدخل المسافة",
                    "layerName": "أدخل اسم الطبقة هنا"
                },
                "message": {
                    "analysisFailed": "فشل التحليل.",
                    "errorOccurred": "حدث خطأ ما.",
                    "layerAdded": "تم إضافة الطبقة بنجاح. ",
                    "enrichLayerNameError": "لا يجوز أي يحتوي اسم الطبقة الناتجة على حروف غير صحيحة " + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "جارِ إنشاء الخدمة... ",
                    "starting": "بدء",
                    "performingAnalysis": "جارِ تنفيذ التحليل..",
                    "checkLayerName": "جارِ التحقق من اسم الطبقة... ",
                    "addingLayer": "إضافة طبقة إلى خريطة ويب ",
                    "layerNameExist": "اسم الطبقة موجود بالفعل.",
                    "clickOnSave": " انقر على زر حفظ لإعادة تحميل التطبيق.",
                    "clickOnOk": " انقر على زر موافق لإعادة المحاولة.",
                    "enterNumbersOnly": "القيم المُدخلة غير صحيحة",
                    "nofeatures": "لا توجد معالم في المدى الحالي",
                    "selectData": "يرجى تحديد البيانات لتحسين الطبقة.",
                    "resetVariableMessage": "هل تريد بالتأكيد إعادة تعيين المتغير؟",
                    "emptyTextFieldLayerName": "أدخل اسم الطبقة الناتجة",
                    "createService":"لم يتم إنشاء الطبقة.",
                    "sharingLayer":"جارِ مشاركة الطبقة..",
                    "updateItemFailed": "فشل التحديث. يرجى إعادة المحاولة.",
                    "geoEnrichFailed": "فشل تحسين الطبقة. يرجى إعادة المحاولة.",
                    "shareFailed": "فشل مشاركة الطبقة المُحسّنة. يرجى إعادة المحاولة.",
                    "refreshServiceFailed": "فشل تحديث الطبقة. يرجى إعادة المحاولة.",
                    "layerJsonFailed": "فشل إنشاء JSON للطبقة. يرجى إعادة المحاولة.",
                    "addToWebmapFailed": "فشل إضافة الطبقة إلى خريطة الويب. يرجى إعادة المحاولة.",
                    "bufferAreaHelpText": "يرجى إدخال القيمة أقل من ",
                    "invalidBufferInput": "القيمة المُدخلة غير صحيحة.",
                    "emptyBufferInput": "يرجى إدخال قيمة صحيحة."
                },
                "populationText": "عدد السكان",
                "housingText": "أجهزة كهربائية",
                "businessText": "أعمال",
                "variableListText": " المتغيرات مُدرجة هنا:",
                "countrySelectTitle": "1. حدد موقع البيانات",
                "unitedStates": "الولايات المتحدة",
                "global": "عالمي",
                "geoenrichDialogText": "متغيرات الإثراء الجغرافي",
                "viewVariablestext": "عرض المتغيرات",
                "backButtonText":"السابق",
                "customizeVariables": "تخصيص المتغيرات",
                "resetVariables": "إعادة تعيين",
                "defineAreaTitle": "3. قم بتعريف المنطقة المُراد تحسينها",
                "currentMapExtent": "استخدام مدى الخريطة الحالي",
                "enrichLayerName": "4. اسم الطبقة الناتجة",
                "lineDistanceText": "مسافة الخط",
                "drivingTime": "زمن القيادة",
                "enrichButtonText": "تحسين الطبقة",
                "selectDataText": "2. حدد البيانات",
                "showCreditsText": "إظهار الاعتمادات",
                "variableCount": "إجمالي عدد المتغيرات ",
                "totalRecords": "إجمالي السجلات:",
                "cost": "تكلفة:",
                "showCreditsDialogText": "إظهار الاعتمادات",
                "nextButtonText": "التالي",
                "prevButtonText": "السابق",
                "saveButtonText": "حفظ",
                "ok": "موافق"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 