define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Unesite udaljenost",
        "layerName": "Ovdje unesite naziv sloja"
      },
      "message": {
        "analysisFailed": "Analiza nije uspjela.",
        "errorOccurred": "Dogodila se pogreška.",
        "layerAdded": "Sloj je uspješno dodan. ",
        "enrichLayerNameError": "Polje „Naziv sloja rezultata” ne smije sadržavati sljedeće znakove \" + \"(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Izrada usluge... ",
        "starting": "Pokretanje",
        "performingAnalysis": "Analiziranje...",
        "checkLayerName": "Provjera naziva sloja... ",
        "addingLayer": "Dodavanje sloja web-karti ",
        "layerNameExist": "Naziv sloja već postoji.",
        "clickOnSave": " Kliknite na gumb „Spremi” za ponovno učitavanje aplikacije.",
        "clickOnOk": " Kliknite na gumb „U redu” i pokušajte ponovno.",
        "enterNumbersOnly": "Unesena vrijednost nije valjana",
        "nofeatures": "U trenutačnom obuhvatu nisu prisutne značajke",
        "selectData": "Odaberite podatke za obogaćivanje sloja.",
        "resetVariableMessage": "Jeste li sigurni da želite ponovo postaviti varijablu?",
        "emptyTextFieldLayerName": "Unesite naziv sloja rezultata",
        "createService": "Sloj nije izrađen.",
        "sharingLayer": "Dijeljenje sloja...",
        "updateItemFailed": "Ažuriranje nije uspjelo. Pokušajte ponovno.",
        "geoEnrichFailed": "Obogaćivanje sloja nije uspjelo. Pokušajte ponovno.",
        "shareFailed": "Dijeljenje obogaćenog sloja nije uspjelo. Pokušajte ponovno.",
        "refreshServiceFailed": "Osvježavanje sloja nije uspjelo. Pokušajte ponovno.",
        "layerJsonFailed": "Izrađivanje JSON-a za sloj nije uspjelo. Pokušajte ponovno.",
        "addToWebmapFailed": "Dodavanje sloja web-karti nije uspjelo. Pokušajte ponovno.",
        "bufferAreaHelpText": "Unesite vrijednost manju od ",
        "invalidBufferInput": "Unesena vrijednost nije valjana.",
        "emptyBufferInput": "Unesite valjanu vrijednost."
      },
      "populationText": "Stanovništvo",
      "housingText": "Kućanstvo",
      "businessText": "Poduzeće",
      "variableListText": " varijable su navedene ovdje:",
      "countrySelectTitle": "1. Odaberite lokaciju podataka",
      "unitedStates": "SAD",
      "global": "Globalno",
      "geoenrichDialogText": "Varijable za obogaćivanje karte",
      "viewVariablestext": "Prikaz varijabli",
      "backButtonText": "Natrag",
      "customizeVariables": "Prilagodi varijable",
      "resetVariables": "Vrati izvorno",
      "defineAreaTitle": "3. Odredite područje za obogaćivanje",
      "currentMapExtent": "Upotrijebi trenutačni obuhvat karte",
      "enrichLayerName": "4. Naziv sloja rezultata",
      "lineDistanceText": "Linijska udaljenost",
      "drivingTime": "Vrijeme vožnje",
      "enrichButtonText": "Obogati sloj",
      "selectDataText": "2. Odaberite podatke",
      "showCreditsText": "Prikaži kredite",
      "variableCount": "Ukupan broj varijabli ",
      "totalRecords": "Ukupno zapisa:",
      "cost": "Trošak:",
      "showCreditsDialogText": "Prikaži kredite",
      "nextButtonText": "Sljedeće",
      "prevButtonText": "Prethodno",
      "saveButtonText": "Spremi",
      "ok": "U redu"
    }
  }
});