define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Uđi u sastavljač",
                "exitBuilderButtonText": "Izađi iz sastavljača",
                "enterBuilderModeHelpText": "Uđite u način rada sastavljača da biste konfigurirali aplikaciju",
                "builderModeHelpText": "Način sastavljača predložaka",
                "webmapCaption": "Karta",
                "selectMapMessage": "Trenutačno ${displaying} <b>${webmapTitle}</b><br/>Kliknite na Odaberi kartu za odabir druge web-karte",
                "loadMapMessage": "Trenutačno odabrano <b>${webmapTitle}</b><br/>Kliknite na Spremi za upotrebu web-karte",
                "changeWebmap": "Odaberi kartu",
                "saveButtonText": "Spremi",
                "webmapNextButtonText": "Sljedeće",
                "previousButtonText":"Prethodno",
                "layerLabelText": "Sloj",
                "noLayerFoundText": "Sloj nije pronađen",
                "selectLayer": "Odabir sloja",
                "applicationSettingText": "Postavke aplikacije",
                "summaryAttrAscendingOrderTooltip": "Uzlazno",
                "onStartLabel": "Na početku",
                "selectVariableText": "Odabir varijable",
                "selectVariableDropdown": "Odabir varijable",
                "label":"Oznaka",
                "sourceLinkText":"Izvorna poveznica",
                "selectSubVariableText":"Odaberite podvarijable",
                "subVariablePanelButtonText":"GOTOVO",
                "onButtonLabel":"Uključeno",
                "offButtonLabel":"Isključeno",
                "appSettingsSaveCloseButtonText": "SPREMI I ZATVORI",
                "appSettingsTitleText":"Naslov appa",
                "appSettingsDescriptionText": "Opis aplikacije",
                "appSetingsRendererAreaText":"Prikazano područje",
                "shareText":"Podijeli",
                "popupText": "Skočni prozor",
                "basemapText":"Kartografska podloga",
                "cancel": "Odustani",
                "theme": "Tema",
                "zoomLevel": "Razina uvećanja",
                "existingValue": "Upotrijebi postojeće vrijednosti",
                "enrichLayer": "Obogati sloj",
                "imageLabel": "Kako ovo radi?",
                "clearData": "Očisti podatke",
                "basemapSelectionText":"Odabir kartografske podloge",
                "secondaryBasemapText":"Sekundarna kartografska podloga",
                "defaultBasemapText": "Zadana kartografska podloga",
                "entireAreaButton": "Čitavo područje",
                "entireAreaOnStartButton": "Čitavo područje na početku",
                "aboutPanel": "O ploči",
                "legendPanel": "Ploča legende",
                "layersPanel": "Ploča slojeva",
                "dataConfigurationButtonText": "Konfiguracija podataka",
                "savingChangesMessage": "Spremanje promjena...",
                "nextButtonText": "Sljedeće",
                "prevButtonText": "Prethodno",
                "enterLabelText": "Unesite oznaku",
                "SelectedFeatureText": "Odabrani geoobjekt",
                "layerHelpTextMessage": "Ova aplikacija zahtijeva sloj s brojčanim poljima",
                "alertMessage": {
                    "resetVariableMessage": "Jeste li sigurni da želite ponovo postaviti varijablu?",
                    "emptyAppTitleMessage": "Naslov aplikacije ne može biti prazan",
                    "emptyDescriptionMessage": "Opis ne može biti prazan",
                    "maxVariableSelection": "Ne možete odabrati više od 25 podvarijabli",
                    "signInFail" : "Prijava nije uspjela",
                    "itemUpdateMessage": "Stavka je ažurirana",
                    "unsavedChangesMessage": "Nespremljene promjene",
                    "failMessage": "Učitavanje stavke nije uspjelo",
                    "saveChangesAlert": "Želite li spremiti promjene?",
                    "variableLabelValidation": "Oznaka varijable ne može biti prazna",
                    "subVariableLabelValidation": "Oznaka podvarijable ne može biti prazna"
                    }
            }
        }
    })
);