define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Åpne verktøy",
                "exitBuilderButtonText": "Avslutt verktøy",
                "enterBuilderModeHelpText": "Åpne verktøymodus for å konfigurere program",
                "builderModeHelpText": "Malverktøymodus",
                "webmapCaption": "Kart",
                "selectMapMessage": "For øyeblikket ${displaying} <b>${webmapTitle}</b><br/>Klikk på Velg kart for å velge et annet webkart",
                "loadMapMessage": "<b>${webmapTitle}</b><br/> er valgt. Klikk på Lagre for å bruke dette webkartet",
                "changeWebmap": "Velg kart",
                "saveButtonText": "Lagre",
                "webmapNextButtonText": "Neste ->",
                "previousButtonText":"Forrige",
                "layerLabelText": "Lag",
                "noLayerFoundText": "Fant ingen lag",
                "selectLayer": "Velg lag",
                "applicationSettingText": "Applikasjonsinnstillinger",
                "summaryAttrAscendingOrderTooltip": "Stigende",
                "onStartLabel": "Ved start",
                "selectVariableText": "Velg en variabel",
                "selectVariableDropdown": "Velg en variabel",
                "label":"Etikett",
                "sourceLinkText":"Kildekobling",
                "selectSubVariableText":"Velg undervariabler",
                "subVariablePanelButtonText":"FERDIG",
                "onButtonLabel":"På",
                "offButtonLabel":"Av",
                "appSettingsSaveCloseButtonText": "LUKK OG LAGRE",
                "appSettingsTitleText":"Programtittel",
                "appSettingsDescriptionText": "Programbeskrivelse",
                "appSetingsRendererAreaText":"Opptegnet område",
                "shareText":"Del",
                "popupText": "Sprettoppvindu",
                "basemapText":"Bakgrunnskart",
                "cancel": "Avbryt",
                "theme": "Tema",
                "zoomLevel": "Zoomnivå",
                "existingValue": "Bruk eksisterende verdier",
                "enrichLayer": "Berik Lag",
                "imageLabel": "Hvordan fungerer dette?",
                "clearData": "Fjern data",
                "basemapSelectionText":"Bakgrunnskartutvalg",
                "secondaryBasemapText":"Sekundært bakgrunnskart",
                "defaultBasemapText": "Standard bakgrunnskart",
                "entireAreaButton": "Hele området",
                "entireAreaOnStartButton": "Hele området ved start",
                "aboutPanel": "Om panelet",
                "legendPanel": "Panelet Tegnforklaring",
                "layersPanel": "Lag-panelet",
                "dataConfigurationButtonText": "Datakonfigurasjon",
                "savingChangesMessage": "Lagrer endringer...",
                "nextButtonText": "Neste",
                "prevButtonText": "Forrige",
                "enterLabelText": "Angi etikett",
                "SelectedFeatureText": "Valgt geoobjekt",
                "layerHelpTextMessage": "Dette programmet krever et lag med numeriske felter",
                "alertMessage": {
                    "resetVariableMessage": "Er du sikker på at du vil nullstille variabelen?",
                    "emptyAppTitleMessage": "Tittel på applikasjonen kan ikke være tom",
                    "emptyDescriptionMessage": "Beskrivelse kan ikke være tom",
                    "maxVariableSelection": "Du kan ikke velge mer enn 25 undervariabler",
                    "signInFail" : "Pålogging mislyktes",
                    "itemUpdateMessage": "Elementet er oppdatert",
                    "unsavedChangesMessage": "Ulagrede endringer",
                    "failMessage": "Oppdateringen av elementet mislyktes",
                    "saveChangesAlert": "Vil du lagre endringene?",
                    "variableLabelValidation": "Variabelpåskriften kan ikke være tom",
                    "subVariableLabelValidation": "Undervariabelpåskriften kan ikke være tom"
                    }
            }
        }
    })
);