define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Mapa web",
				lblLocation: "Ubicación",
				lblContent: "Contenido",
				lblPopup: "Menú emergente",
				lblControls: "Extras",
				lblOverview: "Mapa de vista general",
				lblLegend: "Leyenda",
				loadingTitle: "Cargando título",
				entry: "Entrada",
				entries: "Entradas",
				section: "Sección",
				sections: "Secciones",
				and: "y",
				action: "Acción en sección",
				actions: "Acción en secciones",
				originalWebmap: "Mapa web utilizado para publicar %TPL_NAME%",
				browseMaps: "Buscar mapas",
				current: "Mapa web actual",
				select: "Seleccionar un mapa web",
				newMap: "Mapa web que se acaba de seleccionar",
				webmapDefault: "Valor por defecto de mapa web",
				customCfg: "Configuración personalizada",
				tooltipLocation: "Define la ubicación que mostrará este mapa.",
				tooltipContent: "Define las capas visibles.",
				tooltipPopup: "Elige una ventana emergente que se abrirá cuando se muestre este mapa.",
				tooltipOverview: "Muestra un pequeño mapa de vista general junto con el mapa principal.",
				tooltipLegend: "Muestra la leyenda en el mapa, algo que resulta útil cuando el mapa tiene muchos símbolos y capas.",
				mapCfgInvite: "Usa estos controles para configurar el mapa",
				lblLocationAlt: "Heredado del primer mapa",
				tooltipLocationAlt: "La ubicación de este mapa está sincronizada con el primer mapa de la serie. Para cambiar este comportamiento en tu serie, entra en Configuración > Opciones del mapa."
			},
			configure: {
				btnReset: "Reiniciar",
				btnCancel: "Cancelar",
				tocTitle: "Contenido del mapa",
				tocExplain: "Selecciona las capas que se mostrarán.",
				tocNoData: "No se puede configurar ninguna capa.",
				tocSave: "Guardar contenido del mapa",
				extentTitle: "Ubicación del mapa",
				extentExplain: "Desplázate y haz zoom por el mapa para definir cómo lo verán los lectores.",
				extentSave: "Guardar ubicación del mapa",
				popupTitle: "Ventana emergente del mapa",
				popupExplain: "Haz clic en una entidad para abrir la ventana emergente que deseas mostrar.",
				popupSave: "Guardar la configuración de la ventana emergente",
				hintNavigation: "La navegación del mapa se ha deshabilitado."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "Mi organización",
					onlineLabel: "ArcGIS Online",
					contentLabel: "Mi contenido",
					favoritesLabel: "Mis favoritos"
				},
				title: "Seleccionar mapa web",
				searchTitle: "Buscar",
				ok: "Aceptar",
				cancel: "Cancelar",
				placeholder: "Introducir término de búsqueda o Id. del mapa web..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
