define(
	 ({
		header: {
			start: "بيت_start___لاحقة",
			searchStories: "بيت_Search your stories________لاحقة...",
			filter: "بيت_Filter___لاحقة",
			sort: "بيت_Sort__لاحقة",
			sortColon: "بيت_Sort___لاحقة:",
			numResults: "بيت_Results: {{NUM_RESULTS}}________لاحقة",
			sortBy: "بيت_Sort by___لاحقة",
			dateModified: "بيت_Date modified_____لاحقة",
			title: "بيت_Title___لاحقة",
			type: "بيت_Type__لاحقة",
			views: "بيت_Views___لاحقة",
			errors: "بيت_Errors___لاحقة",
			filterBy: "بيت_Filter by____لاحقة",
			filterItems: "بيت_Filter Items_____لاحقة",
			apps: "بيت_Apps__لاحقة",
			sharing: "بيت_Sharing___لاحقة",
			clearAll: "بيت_Clear all____لاحقة",
			clearSearch: "بيت_Clears the search______لاحقة",
			logOut: "بيت_Log Out___لاحقة",
			mainQuote: "بيت_Storytelling is the most powerful way to put ideas into the world today_______________________لاحقة.",
			quoteSource: "بيت_Robert McKee_____لاحقة",
			checkYourStories: "بيت_Check Stories_____لاحقة",
			createStory: "بيت_Create Story_____لاحقة",
			totalStories: "بيت_Total stories: {{NUM_STORIES}}__________لاحقة",
			noIssues: "بيت_All good___لاحقة",
			userStories: "بيت_Stories of {{USER_NAME}}________لاحقة",
			headerDisabledTooltip: "بيت_Please wait while we work some magic_____________لاحقة...",
			notOnTouch: "بيت_Not available on touch devices__________لاحقة",
		},
		deleteModal: {
			title: "بيت_Confirm Delete_____لاحقة",
			warningText: "بيت_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________لاحقة.",
			deleteText: "بيت_Delete___لاحقة",
			cancel: "بيت_Cancel___لاحقة"
		},
		loading: {
			loadingText: "بيت_Loading your stories________لاحقة..."
		},
		cantFindStories: {
			whereAreStories: "بيت_Not seeing your story________لاحقة?",
			notSeeExplanation: "بيت_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________لاحقة.",
			faq: "بيت_FAQ__لاحقة",
			followingStoriesToUpdate: "بيت_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________لاحقة:",
			gettingStories: "بيت_Searching for stories created with early versions of our applications that need to be updated______________________________لاحقة...",
			title: "بيت_Title___لاحقة",
			typeOfStoryMap: "بيت_Type__لاحقة",
			lastModified: "بيت_Last modified_____لاحقة",
			allUpToDate: "بيت_No stories created with early versions of our applications need to be updated________________________لاحقة.",
			updateAll: "بيت_Update All____لاحقة",
			errorScanningForStories: "بيت_There was an error searching your stories______________لاحقة.",
			close: "بيت_Close___لاحقة",
			updates: "بيت_Updates___لاحقة",
			updatingNumberOfNumber: "بيت_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________لاحقة",
			updatingNumberOfNumberAlt: "بيت_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________لاحقة",
			updateSucceeded: "بيت_Update succeeded______لاحقة!",
			reloadingStories: "بيت_Reloading your stories_________لاحقة...",
			errorUpdatingStories: "بيت_There was an error updating your stories_____________لاحقة.",
			partialUpdateMessage: "بيت_Stories updated successfully: {{NUM_UPDATED}}_______________لاحقة"
		},
		signIn: {
			signInTitle: "بيت_Sign in to Story Maps_______لاحقة",
			signInTo: "بيت_Sign in with your existing ArcGIS Online account to_________________لاحقة:",
			explanationOne: "بيت_Create compelling story maps to tell your stories________________لاحقة.",
			explanationTwo: "بيت_Use your maps and data from ArcGIS Online in your story maps___________________لاحقة.",
			explanationThree: "بيت_Manage your story maps and check the status of their content___________________لاحقة.",
			dontHaveAccount: "بيت_Don't have an ArcGIS Online account? Sign up for a________________لاحقة:",
			publicAccount: "بيت_Free non-commercial public account___________لاحقة",
			orgAccount: "بيت_Free trial ArcGIS subscription__________لاحقة",
			timeExpired: "بيت_Your sign-in expired. Sign in again to pick up where you left off_____________________لاحقة.",
			apiDidntLoad: "بيت_Something isn't loading correctly. Try refreshing the page___________________لاحقة.",
			needAccount: "بيت_Need an account______لاحقة?",
			letsGo: "بيت_Let's go____لاحقة!"
		},
		sharingLevel: {
			publicMessage: "بيت_Public___لاحقة",
			privateMessage: "بيت_Private___لاحقة",
			organization: "بيت_Organization_____لاحقة",
			changedSharing: "بيت_Changed sharing level________لاحقة.",
			unableToChange: "بيت_Unable to change sharing_________لاحقة.",
			partOfMap: "بيت_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________لاحقة.",
			storyPublicContentOrg: "بيت_Your story is public, so its content can't be shared only with your organization_________________________لاحقة",
			storyPublicContentPrivate: "بيت_Your story is public, so its content can't be private_________________لاحقة",
			mapOrg: "بيت_Sharing your map to your organization would break your story___________________لاحقة",
			layerOrg: "بيت_Sharing your layer to your organization would break your story____________________لاحقة",
			mapPrivate: "بيت_Making your map private would break your story_______________لاحقة",
			layerPrivate: "بيت_Making your layer private would break your story_______________لاحقة"
		},
		collectionList: {
			advocacy: "بيت_Advocacy and Outreach_______لاحقة",
			architecture: "بيت_Architecture and Design________لاحقة",
			conservation: "بيت_Conservation and Sustainability__________لاحقة",
			culture: "بيت_Culture___لاحقة",
			destinations: "بيت_Destinations and Tourism________لاحقة",
			disasters: "بيت_Disasters and Recovery________لاحقة",
			economy: "بيت_Economy and Development________لاحقة",
			entertainment: "بيت_Entertainment_____لاحقة",
			history: "بيت_History___لاحقة",
			infrastructure: "بيت_Infrastructure_____لاحقة",
			marketing: "بيت_Marketing____لاحقة",
			nature: "بيت_Nature and Environment________لاحقة",
			news: "بيت_News and Events______لاحقة",
			oceans: "بيت_Oceans___لاحقة",
			parks: "بيت_Parks and Recreation_______لاحقة",
			people: "بيت_People and Society______لاحقة",
			planning: "بيت_Planning and Analysis_______لاحقة",
			publicArt: "بيت_Public Art____لاحقة",
			science: "بيت_Science and Technology________لاحقة",
			sport: "بيت_Sport___لاحقة",
			travelogues: "بيت_Travelogues____لاحقة"
		},
		types: {
			custom: "بيت_Custom___لاحقة",
			notSpecified: "بيت_Type not specified______لاحقة"
		},
		storyMap: {
			shared: "بيت_Shared___لاحقة",
			saveFailed: "بيت_Error saving_____لاحقة",
			numViews: "بيت_Views: {{NUM_VIEWS}}_______لاحقة",
			editStory: "بيت_Edit Story____لاحقة",
			viewLive: "بيت_View Live____لاحقة",
			preview: "بيت_Preview___لاحقة",
			deleteButton: "بيت_Delete___لاحقة",
			modified: "بيت_Modified {{DATE}}______لاحقة",
			summary: "بيت_Summary___لاحقة",
			loading: "بيت_Loading____لاحقة...",
			collapse: "بيت_collapse___لاحقة",
			close: "بيت_close___لاحقة",
			hide: "بيت_hide__لاحقة",
			notAvailableWhenBroken: "بيت_Your story has issues below_________لاحقة",
			cantBeDeleted: "بيت_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________لاحقة",
			shareDialog: {
				title: "بيت_Share your story with the world___________لاحقة!",
				notPublicWarning: "بيت_Your story is shared with your organization. Only members of your organization will be able to view it________________________________لاحقة.",
				embedStory: "بيت_Embed your story______لاحقة",
				shortLink: "بيت_Shortlink____لاحقة",
				hideHeaderBar: "بيت_Hide header bar______لاحقة",
				copied: "بيت_Copied___لاحقة",
				small: "بيت_small___لاحقة",
				medium: "بيت_medium___لاحقة",
				large: "بيت_large___لاحقة",
				custom: "بيت_custom___لاحقة",
				widthAbbreviation: "بيت_w_لاحقة",
				heightAbbreviation: "بيت_h_لاحقة",
				emptyDimension: "بيت_Enter a dimension______لاحقة.",
				seeExample: "بيت_Preview your embed______لاحقة",
				removeHeader: "بيت_Hide application header________لاحقة"
			},
			maps: {
				unableRetrieveTitle: "بيت_Unable to retrieve maps________لاحقة",
				unableRetrieveDescription: "بيت_We weren't able to retrieve maps for this story map_________________لاحقة."
			},
			images: {
				unableRetrieveTitle: "بيت_Unable to retrieve images_________لاحقة",
				unableRetrieveDescription: "بيت_We weren't able to retrieve images for this story map_________________لاحقة."
			},
			tags: {
				tags: "بيت_Tags__لاحقة",
				collectionTags: "بيت_Subject___لاحقة",
				selectASubject: "بيت_Select a subject______لاحقة",
				save: "بيت_Save__لاحقة",
				saved: "بيت_Saved___لاحقة",
				errorSaving: "بيت_Error saving_____لاحقة",
				tagTip: "بيت_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________لاحقة."
			},
			submitToGallery: {
				gallerySubmission: "بيت_Story Maps Gallery______لاحقة",
				canSubmitIf: "بيت_You can nominate your story to the gallery if it contains the following_______________________لاحقة:",
				hasOwnImage: "بيت_Custom thumbnail______لاحقة",
				chosenSubject: "بيت_A subject and some tags________لاحقة",
				chosenSubjectAlt: "بيت_A {{SUBJECT}} and some tags_________لاحقة",
				storyMapTopicSubject: "بيت_subject___لاحقة",
				sharedPublicly: "بيت_Shared publicly______لاحقة",
				noBrokenContent: "بيت_No broken content______لاحقة",
				nominateToGallery: "بيت_Nominate to Gallery_______لاحقة",
				comingSoon: "بيت_Coming soon_____لاحقة!",
				submitted: "بيت_Submitted____لاحقة",
				errorSubmitting: "بيت_Error submitting______لاحقة",
				ourGallery: "بيت_The Story Maps gallery________لاحقة",
				galleryTip: "بيت_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________لاحقة."
			},
			placeholders: {
				noSummary: "بيت_No summary, click to add one__________لاحقة."
			},
			errors: {
				cantDeleteStory: "بيت_Unable to delete story________لاحقة.",
				unableToFind: "بيت_Unable to find content________لاحقة",
				unableToRetrieve: "بيت_We weren't able to retrieve the content for this story map___________________لاحقة."
			},
			socialSharing: {
				availableWhenPublic: "بيت_This option will be available when your story is public__________________لاحقة"
			},
			dialog: {
				back: "بيت_Back__لاحقة",
				close: "بيت_Close___لاحقة",
				cancel: "بيت_Cancel___لاحقة"
			},
			imagePicker: {
				changeDefault: "بيت_Change the default image________لاحقة",
				changeImage: "بيت_Change thumbnail______لاحقة",
				uploadImage: "بيت_Upload thumbnail______لاحقة",
				chooseImage: "بيت_Choose thumbnail______لاحقة",
				chooseAnImage: "بيت_Choose an Image______لاحقة",
				notInIEVersion: "بيت_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________لاحقة.",
				or: "بيت_Or__لاحقة",
				uploadAnImage: "بيت_Upload an Image______لاحقة",
				supportedFileTypes: "بيت_Supports .png, .jpg, .gif_________لاحقة",
				imageSizeMessage: "بيت_Your image needs to be at least 286 px wide by 190 px tall___________________لاحقة.",
				minimumDimensions: "بيت_Minimum: 286 x 190px_______لاحقة",
				imagesLoading: "بيت_Loading images______لاحقة...",
				noImages: "بيت_This story has no images________لاحقة",
				errorLoading: "بيت_Unable to retrieve the images in this story______________لاحقة",
				clickBelowTip: "بيت_Click the button below to upload an image______________لاحقة.",
				dragAndDrop: "بيت_Drag and Drop_____لاحقة",
				cropImage: "بيت_Crop Image____لاحقة",
				saveImage: "بيت_Save Image____لاحقة",
				save: "بيت_Save__لاحقة",
				savingImage: "بيت_Saving your image_______لاحقة...",
				saved: "بيت_Saved___لاحقة!",
				errorSaving: "بيت_Unable to save your image_________لاحقة.",
				skipAndCrop: "بيت_Skip and Crop for me_______لاحقة",
				wrongFormat: "بيت_This file type is not supported___________لاحقة.",
				noCropWarning: "بيت_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________لاحقة."
			}
		},
		content: {
			media: {
				maps: "بيت_Maps__لاحقة",
				images: "بيت_Images___لاحقة",
				videos: "بيت_Videos___لاحقة",
				webpages: "بيت_Webpages___لاحقة",
				tags: "بيت_Tags__لاحقة",
				gallery: "بيت_Gallery___لاحقة"
			},
			headers: {
				status: "بيت_Status___لاحقة",
				source: "بيت_Source___لاحقة",
				name: "بيت_Name__لاحقة",
				shared: "بيت_Shared___لاحقة"
			},
			component: {
				mapTour: "بيت_Point Number_____لاحقة",
				bullet: "بيت_Bullet___لاحقة",
				tab: "بيت_Tab__لاحقة",
				accordion: "بيت_Section___لاحقة",
				mapJournal: "بيت_Section___لاحقة"
			},
			titleType: {
				mapTour: "بيت_Caption___لاحقة",
				mapJournal: "بيت_URL__لاحقة",
				mapSeries: "بيت_URL__لاحقة"
			},
			actions: {
				viewMap: "بيت_View Map___لاحقة",
				editMap: "بيت_Edit Map___لاحقة",
				fix: "بيت_Fix__لاحقة",
				viewLayer: "بيت_View Layer____لاحقة"
			},
			contentType: {
				mainStage: "بيت_main stage action______لاحقة",
				sidePanel: "بيت_description____لاحقة"
			},
			notification: {
				refreshExplanation: "بيت_Check your story again________لاحقة",
				checking: "بيت_Checking____لاحقة...",
				foundSomeIssues: "بيت_We found some issues_______لاحقة",
				noIssuesFound: "بيت_No issues found______لاحقة",
				storyPublic: "بيت_Your story is now public________لاحقة",
				storyOrg: "بيت_Your story is now shared to your organization_______________لاحقة",
				storyPrivate: "بيت_Your story is now private_________لاحقة",
				mapPublic: "بيت_Your map is now public________لاحقة",
				mapOrg: "بيت_Your map is now shared to your organization______________لاحقة",
				mapPrivate: "بيت_Your map is now private________لاحقة",
				layerPublic: "بيت_Your layer is now public________لاحقة",
				layerOrg: "بيت_Your layer is now shared to your organization_______________لاحقة",
				layerPrivate: "بيت_Your layer is now private_________لاحقة",
				contentPublic: "بيت_Your content is now public_________لاحقة",
				contentOrg: "بيت_Your content is now shared to your organization_______________لاحقة",
				contentPrivate: "بيت_Your content is now private_________لاحقة",
				storyAndContentPublic: "بيت_Your story and its content are now public_____________لاحقة",
				storyAndContentOrg: "بيت_Your story and its content are now shared to your organization____________________لاحقة",
				storyAndContentPrivate: "بيت_Your story and its content are now private______________لاحقة",
				shareBulkPrompt: "بيت_Do you want to share your storyâ€™s content accordingly__________________لاحقة?",
				layersPublic: "بيت_Some layers have also been shared publicly______________لاحقة",
				layersOrg: "بيت_Some layers have also been shared with your organization__________________لاحقة",
				layersPrivate: "بيت_Some layers have also been made private_____________لاحقة",
				mapsPublic: "بيت_Some maps have also been shared publicly_____________لاحقة",
				mapsOrg: "بيت_Some maps have also been shared with your organization_________________لاحقة",
				mapsPrivate: "بيت_Some maps have also been made private____________لاحقة",
				layersAndMapsPublic: "بيت_Some maps and layers have also been shared publicly________________لاحقة",
				layersAndMapsOrg: "بيت_Some maps and layers have also been shared with your organization_____________________لاحقة",
				layersAndMapsPrivate: "بيت_Some maps and layers have also been made private_______________لاحقة",
				yes: "بيت_Yes__لاحقة",
				no: "بيت_No__لاحقة",
				premiumPublicSuccess: "بيت_Your premium content is now publicly accessible_______________لاحقة",
				subscriptionPublicSuccess: "بيت_Your subscription content is now publicly accessible_________________لاحقة"
			},
			errors: {
				publicDisabled: "بيت_Sharing publicly has been disabled by the Administrator__________________لاحقة",
				noMapName: "بيت_Could Not Retrieve Map Name_________لاحقة",
				notPublic: "بيت_NOT PUBLIC____لاحقة",
				inaccessible: "بيت_INACCESSIBLE_____لاحقة",
				deleted: "بيت_DELETED___لاحقة",
				cantAccessVideo: "بيت_Could Not Access Video________لاحقة",
				noStoriesFound: "بيت_We could not find any Story Maps in your content________________لاحقة.",
				cantShowStories: "بيت_Unable to show your story maps. Please try again later__________________لاحقة.",
				consolationSearch: "بيت_We couldn't find any stories__________لاحقة.",
				notCompatibleWithBrowser : "بيت_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________لاحقة.",
				pleaseUpdateBrowser: "بيت_Please update your browser_________لاحقة.",
				searchTip: "بيت_Try and simplify it a bit_________لاحقة.",
				consolationNoStories: "بيت_Welcome to My Stories________لاحقة!",
				noStoriesTip: "بيت_To make your first story map, check out the Apps page_________________لاحقة.",
				letsGo: "بيت_Let's Go___لاحقة",
				cantChangeSharingLevel: "بيت_Unable to change sharing level__________لاحقة",
				cantChangeSharingLevels: "بيت_Unable to change sharing levels__________لاحقة",
				errorUpdatingTitle: "بيت_Error updating title_______لاحقة",
				errorUpdatingSummary: "بيت_Error updating summary________لاحقة",
				noEmptyTitle: "بيت_Title cannot be empty_______لاحقة",
				cantUpdatePremiumContent: "بيت_Unable to update premium content___________لاحقة",
				cantUpdateSubscriptionContent: "بيت_Unable to update subscription content____________لاحقة",
				createFirstStory: "بيت_Create My First Story_______لاحقة"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "بيت_Map has been deleted_______لاحقة",
				layerHasBeenDeleted: "بيت_Layer has been deleted________لاحقة",
				mapIsInaccessible: "بيت_Map is inaccessible_______لاحقة",
				layerIsInaccessible: "بيت_Layer is inaccessible_______لاحقة",
				mapNotYoursNotAccessible: "بيت_Map is owned by someone else and isn't accessible________________لاحقة",
				layerServiceOkItemNot: "بيت_Layer was added as an item that is deleted or inaccessible__________________لاحقة",
				layerNotYoursNotAccessible: "بيت_Layer is owned by someone else and isn't accessible________________لاحقة",
				mapOthersSharedBelowLevel: "بيت_Map is not owned by you and is not public_____________لاحقة",
				layerOthersSharedBelowLevel: "بيت_Layer is not owned by you and is not public______________لاحقة",
				noMapNoDetails: "بيت_Without the map details, we can't tell you anything about the layers_____________________لاحقة",
				mapIsPrivate: "بيت_Map is private_____لاحقة",
				mapIsOrg: "بيت_Map is only shared in your organization_____________لاحقة",
				layerIsPrivate: "بيت_Layer is private______لاحقة",
				layerIsOrg: "بيت_Layer is only shared in your organization_____________لاحقة",
				imageInaccessible: "بيت_This image is inaccessible_________لاحقة",
				videoInaccessible: "بيت_This video is inaccessible_________لاحقة",
				webpageInaccessible: "بيت_This web page is inaccessible__________لاحقة",
				layerSecureService: "بيت_Layer is a secure service_________لاحقة",
				mapSecureService: "بيت_Map is a secure service________لاحقة",
				layerConsumesCredits: "بيت_Layer is premium content and consumes credits_______________لاحقة",
				layerSubscriptionContent: "بيت_Layer is subscription content__________لاحقة",
				mapConsumesCredits: "بيت_Map is premium content and consumes credits______________لاحقة",
				mapSubscriptionContent: "بيت_Map is subscription content_________لاحقة"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "بيت_We're not able to check this type of layer______________لاحقة",
				cantScanThisType: "بيت_Layer is not a type of layer we can check_____________لاحقة",
				webpageNotScanned: "بيت_Webpages are not checked for issues____________لاحقة"
			},
			scanningErrors: {
				deletedMap: "بيت_Deleted content______لاحقة",
				inaccessibleMap: "بيت_Inaccessible map content________لاحقة",
				notYoursNotAccessible: "بيت_Content not owned by you and not public_____________لاحقة",
				serviceOkItemNot: "بيت_Working layers but inaccessible items____________لاحقة",
				someContentNotPublic: "بيت_Content not shared publicly_________لاحقة",
				someContentPrivate: "بيت_Private content______لاحقة",
				othersSharedBelowLevel: "بيت_Content not owned by you and not public_____________لاحقة",
				premiumContent: "بيت_Premium content______لاحقة",
				subscriptionContent: "بيت_Subscription content_______لاحقة",
				secureService: "بيت_Secure services______لاحقة",
				inaccessibleImage: "بيت_Inaccessible images_______لاحقة",
				inaccessibleVideo: "بيت_Inaccessible videos_______لاحقة",
				inaccessibleWebpage: "بيت_Inaccessible webpages_______لاحقة"
			},
			scanningErrorTips: {
				deletedMapTip: "بيت_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________لاحقة.",
				inaccessibleMapTip: "بيت_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________لاحقة.",
				notYoursNotAccessibleTip: "بيت_Tip: Open the web map and remove the layer or map from the story_____________________لاحقة.",
				serviceOkItemNotTip: "بيت_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________لاحقة.",
				ignore: "بيت_Ignore___لاحقة",
				fix: "بيت_Fix__لاحقة",
				clickToShareOrg: "بيت_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________لاحقة.",
				clickToSharePublic: "بيت_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________لاحقة.",
				shareOrg: "بيت_Share to your org______لاحقة",
				sharePublicly: "بيت_Share publicly_____لاحقة",
				othersSharedBelowLevelTip: "بيت_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________لاحقة.",
				secureServiceTip: "بيت_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________لاحقة.",
				blogArticle: "بيت_here__لاحقة",
				premiumContentTip: "بيت_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________لاحقة.",
				premiumContentPublicTip: "بيت_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________لاحقة.",
				subscriptionContentTip: "بيت_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________لاحقة.",
				agolCredits: "بيت_ArcGIS Online credits_______لاحقة",
				credits: "بيت_credits___لاحقة",
				makePublic: "بيت_Make public____لاحقة",
				confirm: "بيت_Confirm___لاحقة",
				inaccessibleImageTip: "بيت_Tip: Provide the missing image or remove the reference to it___________________لاحقة.",
				inaccessibleVideoTip: "بيت_Tip: Provide the missing video or remove the reference to it___________________لاحقة.",
				inaccessibleWebpageTip: "بيت_Tip: Provide the missing web page or remove the reference to it____________________لاحقة."
			},
			removeLayer: {
				title: "بيت_Fix Layer Issue______لاحقة",
				layersWithIssue: "بيت_Layers with this issue: {{NUM_WITH_ISSUE}}______________لاحقة",
				issueExplanation: "بيت_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________لاحقة.",
				issueSolution: "بيت_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________لاحقة:",
				editMap: "بيت_Edit Your Map_____لاحقة",
				clickBelowWhenDone: "بيت_When you have finished editing, click the button below__________________لاحقة:",
				rescanAndClose: "بيت_Rescan And Close______لاحقة"
			},
			info: {
				ownedBy: "بيت_This item is owned by {{USER_NAME}}____________لاحقة",
				unknownUser: "بيت_someone else_____لاحقة",
				untitledSection: "بيت_(Untitled section)______لاحقة",
				introRecord: "بيت_Introduction_____لاحقة"
			},
			layers: {
				layersHeader: "بيت_Layers___لاحقة",
				noLayers: "بيت_(No Layers)____لاحقة",
				basemapParens: "بيت_(basemap)____لاحقة"
			},
			images: {
				thumbnails: "بيت_Thumbnails____لاحقة",
				thumbnail: "بيت_Thumbnail____لاحقة",
				thumbnailParens: "بيت_(thumbnail)____لاحقة"
			},
			general: {
				noTitle: "بيت_(no title)____لاحقة",
				loading: "بيت_Loading____لاحقة..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "بيت_sections___لاحقة",
				secondTitle: "بيت_style___لاحقة",
				secondValueA: "بيت_side panel____لاحقة",
				secondValueB: "بيت_floating panel_____لاحقة",
				thirdTitle: "بيت_maps__لاحقة"
			},
			mapTour: {
				firstTitle: "بيت_tour points____لاحقة",
				secondTitle: "بيت_style___لاحقة",
				secondValueA: "بيت_integrated____لاحقة",
				secondValueB: "بيت_three-panel____لاحقة",
				thirdTitle: "بيت_basemap___لاحقة",
				thirdValueLoading: "بيت_Loading____لاحقة...",
				thirdValueUnknown: "بيت_unknown___لاحقة"
			},
			mapSeries: {
				firstTitleA: "بيت_bullets___لاحقة",
				firstTitleB: "بيت_sections___لاحقة",
				firstTitleC: "بيت_tabs__لاحقة",
				secondTitle: "بيت_style___لاحقة",
				secondValueA: "بيت_bulleted___لاحقة",
				secondValueB: "بيت_side accordion_____لاحقة",
				secondValueC: "بيت_tabbed___لاحقة",
				thirdTitle: "بيت_maps__لاحقة"
			},
			swipeSpyglass: {
				firstTitle: "بيت_points of interest______لاحقة",
				secondTitle: "بيت_style___لاحقة",
				secondValueA: "بيت_swipe___لاحقة",
				secondValueB: "بيت_spyglass___لاحقة",
				thirdTitle: "بيت_maps__لاحقة"
			}
		},
		progress: {
			checkingStories: "بيت_Checking your stories for issues____________لاحقة...",
			stop: "بيت_Stop__لاحقة",
			exit: "بيت_Exit__لاحقة",
			dismiss: "بيت_Dismiss___لاحقة",
			done: "بيت_Done___لاحقة.",
			noStoriesWithIssuesLower: "بيت_No issues found______لاحقة!",
			storiesErrorFree: "بيت_Looks like your stories are error-free____________لاحقة",
			scanAllError: "بيت_Unable to scan -- we couldn't retrieve one or more of your stories_____________________لاحقة",
			scanProgress: "بيت_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________لاحقة",
			scanStopped: "بيت_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________لاحقة",
			storiesWithIssues: "بيت_Stories with issues: {{NUM_STORIES}}____________لاحقة"
		}
    })
);