define(
	 ({
		header: {
			start: "بدء",
			searchStories: "البحث عن الحكايات...",
			filter: "تصفية",
			sort: "فرز",
			sortColon: "الفرز:",
			numResults: "النتائج: {{NUM_RESULTS}}",
			sortBy: "فرز بواسطة",
			dateModified: "تاريخ التعديل",
			title: "العنوان",
			type: "النوع",
			views: "عروض",
			errors: "أخطاء",
			filterBy: "تصفية بواسطة",
			filterItems: "تصفية العناصر",
			apps: "تطبيقات",
			sharing: "مشاركة",
			clearAll: "Clear all",
			clearSearch: "مسح البحث",
			logOut: "تسجيل الخروج",
			mainQuote: "يعتبر سرد الحكايات هو أفضل الطرق لوضع الأفكار في العالم الحالي.",
			quoteSource: "روبرت ماكي",
			checkYourStories: "تحقق من الحكايات",
			createStory: "إنشاء قصة",
			totalStories: "إجمالي الحكايات: {{NUM_STORIES}}",
			noIssues: "جميع",
			userStories: "الحكايات الجديدة من {{USER_NAME}}",
			headerDisabledTooltip: "يرجى الانتظار أثناء عمل بعض الإجراءات...",
			notOnTouch: "غير متوفر بالأجهزة باللمس",
		},
		deleteModal: {
			title: "تاكيد الحذف",
			warningText: "هل أنت متأكد من حذف الحكاية Â؟ لن تستطيع استرجاعه.",
			deleteText: "حذف",
			cancel: "إلغاء الأمر"
		},
		loading: {
			loadingText: "تحميل الحكايات..."
		},
		cantFindStories: {
			whereAreStories: "هل ترى الحكاية؟",
			notSeeExplanation: "تًدرج الحكايات الخرائط المستضافة في ArcGIS Online فقط التي تم إنشائها مع تطبيقات {{STORY_MAP_TOUR}} و {{JOURNAL}} و {{MAP_SERIES}} و {{SWIPE_SPYGLASS}}. راجع الأسئلة المتداولة لمزيد من المعلومات.",
			faq: "الأسئلة المتداولة",
			followingStoriesToUpdate: "تم إنشاء الحكايات التالية مع الإصدارات السابقة للتطبيقات التي تحتاج تحديث ليتم إدراجها في الحكايات:",
			gettingStories: "البحث عن الحكايات التالية مع الإصدارات السابقة للتطبيقات التي تحتاج التحديث...",
			title: "العنوان",
			typeOfStoryMap: "النوع",
			lastModified: "آخر تعديل",
			allUpToDate: "لن يتم إنشاء الحكايات مع إصدارات سابقة مع التطبيقات التي تحتاج التحديث.",
			updateAll: "تحديث الكل",
			errorScanningForStories: "هناك خطأ أثناء البحث عن الحكايات.",
			close: "إغلاق",
			updates: "عمليات التحديث",
			updatingNumberOfNumber: "تحديث {{CURRENT_NUMBER}} لـ {{TOTAL}}",
			updatingNumberOfNumberAlt: "تحديث {{CURRENT_NUMBER}} / {{TOTAL}}",
			updateSucceeded: "تم نجاح التحديث!",
			reloadingStories: "إعادة تحميل الحكايات...",
			errorUpdatingStories: "هناك خطأ أثناء تحديث الحكايات.",
			partialUpdateMessage: "تم تحديث الحكايات بنجاح: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "تسجيل الدخول إلى خرائط القصة",
			signInTo: "تسجيل الدخول باستخدام حساب ArcGIS Online الحالي على:",
			explanationOne: "إنشاء خرائط قصص مُقنعة للتعبير عن القصص التي تريد التعبير عنها.",
			explanationTwo: "استخدم الخرائط والبيانات من ArcGIS Online في خرائط القصة.",
			explanationThree: "إدارة خرائط القصص وفحص حالة المحتوى الخاص بها.",
			dontHaveAccount: "هل لا يوجد لديك حساب على ArcGIS Online؟ اشترك:",
			publicAccount: "حساب عام مجاني للاستخدام غير التجاري",
			orgAccount: "اشتراك ArcGIS التجريبي المجاني",
			timeExpired: "انتهت صلاحية تسجيل دخولك. سجل الدخول مجددًا للاستمرار حيث انتهيت.",
			apiDidntLoad: "لم يتم تحميل بعض العناصر بشكل صحيح. حاول تحديث الصفحة مرة أخرى.",
			needAccount: "هل تريد حسابًا؟",
			letsGo: "هيا بنا!"
		},
		sharingLevel: {
			publicMessage: "عام",
			privateMessage: "خاص",
			organization: "مؤسسة",
			changedSharing: "تم تغيير مستوى المشاركة.",
			unableToChange: "يتعذر تغيير المشاركة.",
			partOfMap: "ينقل العنصر الحالي للخريطة. لتغيير مستوى المشاركة، يجب تغيير مستوى المشاركة للخريطة.",
			storyPublicContentOrg: "يعتبر الحكاية عامة، فلا يمكن مشاركة المحتوى فقط في المؤسسة",
			storyPublicContentPrivate: "يعتبر الحكاية عامة، فلا يمكن أن يكون المحتوى خاص",
			mapOrg: "قد تقوم مشاركة الخريطة في المؤسسة بوقف الحكاية",
			layerOrg: "قد تقوم مشاركة الطبقة في المؤسسة بوقف الحكاية",
			mapPrivate: "قد يقوم عمل الخريطة خاصة بوقف الحكاية",
			layerPrivate: "قد يقوم عمل الطبقة خاصة بوقف الحكاية"
		},
		collectionList: {
			advocacy: "دعم وتجاوز",
			architecture: "بنية والتصميم",
			conservation: "الصيانة والاستدامة",
			culture: "ثقافة",
			destinations: "وجهات وسياحة",
			disasters: "كوارث واسترجاع",
			economy: "اقتصاد وتطوير",
			entertainment: "ترفيه",
			history: "المحفوظات",
			infrastructure: "البنية الأساسية",
			marketing: "التسويق",
			nature: "الطبيعة والبيئة",
			news: "أخبار وأحداث",
			oceans: "محيطات",
			parks: "المتنزهات وإعادة الإنشاء",
			people: "أشخاص ومجتمع",
			planning: "التخطيط والتحليل",
			publicArt: "الفن العام",
			science: "العلوم والتكنولوجيا",
			sport: "الرياضة",
			travelogues: "حكايات السفر"
		},
		types: {
			custom: "تخصيص",
			notSpecified: "لم يتم تحديد النوع"
		},
		storyMap: {
			shared: "مشترك",
			saveFailed: "حدث خطأ في الحفظ",
			numViews: "عروض: {{NUM_VIEWS}}",
			editStory: "تحرير الحكاية",
			viewLive: "عرض مباشر",
			preview: "معاينة",
			deleteButton: "حذف",
			modified: "تم تعديل {{DATE}}",
			summary: "الملخص",
			loading: "جارِ التحميل...",
			collapse: "طي",
			close: "إغلاق",
			hide: "إخفاء",
			notAvailableWhenBroken: "تحتوي القصة على المشكلات التالية",
			cantBeDeleted: "قامت الحكاية الحالية بحذف تمكين الحماية، اعرض صفحة العنصر في ArcGIS Online للتعطيل",
			shareDialog: {
				title: "مشاركة الحكاية في العالم!",
				notPublicWarning: "تم مشاركة الحكاية مع المؤسسة. سيكون أعضاء المؤسسة فقط قادرين على عرضه.",
				embedStory: "تضمين الحكاية",
				shortLink: "رابط قصير",
				hideHeaderBar: "إخفاء شريط الرأس",
				copied: "تم النسخ",
				small: "صغير",
				medium: "متوسط",
				large: "كبير",
				custom: "مخصص",
				widthAbbreviation: "w",
				heightAbbreviation: "ساعة",
				emptyDimension: "ادخل البعد",
				seeExample: "مراجعة التضمين",
				removeHeader: "إخفاء رأس التطبيق"
			},
			maps: {
				unableRetrieveTitle: "تعذر استعادة الخرائط",
				unableRetrieveDescription: "لم نتمكن من استعادة الخرائط لخريطة الحكاية."
			},
			images: {
				unableRetrieveTitle: "تعذر استعادة الصور",
				unableRetrieveDescription: "لم نتمكن من استعادة الصور لخريطة الحكاية."
			},
			tags: {
				tags: "علامات",
				collectionTags: "الموضوع",
				selectASubject: "تحديد الموضوع",
				save: "حفظ",
				saved: "تم الحفظ",
				errorSaving: "حدث خطأ في الحفظ",
				tagTip: "ملاحظة: تساعد علامات تبويب الأشخاص للبحث عن حكاية في ArcGIS Online. تعتبر علامات التبويب الأكثر صلة أعلى رؤية سيستلمها العمل."
			},
			submitToGallery: {
				gallerySubmission: "معرض خرائط الحكاية",
				canSubmitIf: "يمكنك تعيين الحكاية للمعرض إذا كانت تحتوي على التالي:",
				hasOwnImage: "صورة مصغرة مخصصة",
				chosenSubject: "موضوع وبعض علامات التبويب",
				chosenSubjectAlt: "{{SUBJECT}} وبعض علامات التبويب",
				storyMapTopicSubject: "موضوع",
				sharedPublicly: "تمت المشاركة مع العامة",
				noBrokenContent: "بيت_No issues____لاحقة",
				nominateToGallery: "تعيين المعرض",
				comingSoon: "قريبًا!",
				submitted: "تم الإرسال",
				errorSubmitting: "خطأ أثناء التعيين",
				ourGallery: "معرض خرائط الحكاية",
				galleryTip: "يعتبر {{THE_GALLERY}} مجمعة خاضعة للإشراف من خرائط الحكاية والتي تعرض بعض حالات الأمثلة الأفضل. إذا تم اختيار حكايتك، سيتم إضافتها خلال 10 أيام من الإرسال. وبسبب عدد الترشيحات، فلا يمكن الوعد بإضافة الحكاية."
			},
			placeholders: {
				noSummary: "لا يوجد ملخص، انقر لإضافة واحد."
			},
			errors: {
				cantDeleteStory: "يتعذر حذف الحكاية.",
				unableToFind: "يتعذر البحث عن المحتوى",
				unableToRetrieve: "لم نتمكن من استعادة المحتوى لخريطة الحكاية."
			},
			socialSharing: {
				availableWhenPublic: "سيتوفر الخيار الحالي عندما تكون الحكاية عامة"
			},
			dialog: {
				back: "الخلف",
				close: "إغلاق",
				cancel: "إلغاء الأمر"
			},
			imagePicker: {
				changeDefault: "تغيير الصورة الافتراضية",
				changeImage: "تغيير الصورة المُصغرة",
				uploadImage: "تحميل الصورة المصغرة",
				chooseImage: "اختيار مصغرة كبيرة",
				chooseAnImage: "اختيار صورة",
				notInIEVersion: "لا تتوفر الميزة الحالية في Internet Explorer {{VERSION_NUMBER}}.",
				or: "أو",
				uploadAnImage: "تحميل صورة",
				supportedFileTypes: "يدعم .png، و .jpg، و .gif",
				imageSizeMessage: "تحتاج الصورة أن تكون على الأقل 286 بكسل للعرض في 190 بكسل للطول.",
				minimumDimensions: "الحد الأدنى: 286 x 190px",
				imagesLoading: "جارِ تحميل الصور...",
				noImages: "لا تحتوي الحكاية الحالية على صور",
				errorLoading: "تعذر استعادة الصور في الحكاية الحالية",
				clickBelowTip: "انقر على زر بالأسفل لتحميل الصورة.",
				dragAndDrop: "سحب وإفلات",
				cropImage: "قص الصورة",
				saveImage: "حفظ الصورة",
				save: "حفظ",
				savingImage: "جارِ حفظ الصورة...",
				saved: "تم الحفظ!",
				errorSaving: "تعذر حفظ الصورة.",
				skipAndCrop: "تخطي وقص",
				wrongFormat: "نوع الملف غير مدعوم.",
				noCropWarning: "لا يمكن قص الصورة، ولكن لازال يمكن حفظه باعتباره صورة المصغرة للحكاية مع أبعاد أصلية ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)."
			}
		},
		content: {
			media: {
				maps: "خرائط",
				images: "الصور",
				videos: "الفيديو",
				webpages: "صفحات الويب",
				tags: "علامات",
				gallery: "معرض الصور"
			},
			headers: {
				status: "الحالة",
				source: "مصدر",
				name: "الاسم",
				shared: "مشترك"
			},
			component: {
				mapTour: "عدد النقاط",
				bullet: "رمز نقطي",
				tab: "علامة تبويب",
				accordion: "قسم",
				mapJournal: "قسم"
			},
			titleType: {
				mapTour: "تسمية وضيحية",
				mapJournal: "عنوان URL",
				mapSeries: "عنوان URL"
			},
			actions: {
				viewMap: "عرض الخريطة",
				editMap: "تحرير الخريطة",
				fix: "تصحيح",
				viewLayer: "عرض الطبقة"
			},
			contentType: {
				mainStage: "إجراء الخطوة الأساسية",
				sidePanel: "الوصف"
			},
			notification: {
				refreshExplanation: "تحقق من الحكاية مرة أخرى",
				checking: "جارِ التحقق...",
				foundSomeIssues: "تم العثور على بعض المشكلات",
				noIssuesFound: "لم يتم العثور على موضوعات",
				storyPublic: "الحكاية الآن عامة",
				storyOrg: "تم مشاركة القصة في المؤسسة",
				storyPrivate: "الحكاية الآن خاصة",
				mapPublic: "الخريطة الآن عامة",
				mapOrg: "تم مشاركة الخريطة في المؤسسة",
				mapPrivate: "الخريطة الآن خاصة",
				layerPublic: "الطبقة الآن عامة",
				layerOrg: "تم مشاركة الطبقة في المؤسسة",
				layerPrivate: "الطبقة الآن خاصة",
				contentPublic: "المحتوى الآن عام",
				contentOrg: "تم مشاركة المحتوى في المؤسسة",
				contentPrivate: "المحتوى الآن خاص",
				storyAndContentPublic: "الحكاية ومحتواها الآن عام",
				storyAndContentOrg: "تم مشاركة الحكاية ومحتواها في المؤسسة",
				storyAndContentPrivate: "الحكاية ومحتواها الآن خاص",
				shareBulkPrompt: "هل تود مشاركة محتوى storyâ€™s وفقَا لذلك؟",
				layersPublic: "تم مشاركة بعض الطبقات للعامة",
				layersOrg: "تم مشاركة بعض الطبقات مع المؤسسة",
				layersPrivate: "اصبحت بعض الطبقات خاصة",
				mapsPublic: "تم مشاركة بعض الخرائط للعامة",
				mapsOrg: "تم مشاركة بعض الخرائط مع المؤسسة",
				mapsPrivate: "أصبحت بعض الخرائط خاصة",
				layersAndMapsPublic: "تم مشاركة بعض الخرائط والطبقات للعامة",
				layersAndMapsOrg: "تم مشاركة بعض الخرائط والطبقات مع المؤسسة",
				layersAndMapsPrivate: "اصبحت بعض الخرائط والطبقات خاصة",
				yes: "نعم",
				no: "لا",
				premiumPublicSuccess: "أصبح المحتوى المتميز قابل للوصول من الجميع",
				subscriptionPublicSuccess: "أصبح الاشتراك المتميز قابل للوصول من الجميع"
			},
			errors: {
				publicDisabled: "قام المسئول بتعطيل المشاركة العامة",
				noMapName: "لا يمكن استعادة اسم الخريطة",
				notPublic: "خاص",
				inaccessible: "غير قابل للوصول",
				deleted: "تم الحذف",
				cantAccessVideo: "يتعذر الوصول إلى مقطع الفيديو",
				noStoriesFound: "لا يمكن العثور على خرائط الحكاية في المحتوى.",
				cantShowStories: "تعذر عرض خرائط الحكاية. يرجى المحاولة مرة أخرى لاحقًا.",
				consolationSearch: "لا يمكن العثور على أي حكايات.",
				notCompatibleWithBrowser : "الحكايات غير مدعومة في Internet Explorer بالإصدار السابق لـ {{VERSION_NUMBER}}.",
				pleaseUpdateBrowser: "الرجاء تحديث المستعرض.",
				searchTip: "حاول وقم بتلخيصه قليلاً.",
				consolationNoStories: "مرحبًا بك في الحكايات!",
				noStoriesTip: "لعمل أول خريطة حكاية، تحقق من صفحة التطبيقات.",
				letsGo: "هيا بنا",
				cantChangeSharingLevel: "يتعذر تغيير مستوى المشاركة.",
				cantChangeSharingLevels: "يتعذر تغيير مستويات المشاركة.",
				errorUpdatingTitle: "خطأ أثناء تحديث العنوان",
				errorUpdatingSummary: "خطأ أثناء تحديث الملخص",
				noEmptyTitle: "لا يمكن أن يكون العنوان فارغ",
				cantUpdatePremiumContent: "يتعذر تحديث المحتوى المتميز",
				cantUpdateSubscriptionContent: "يتعذر تحديث المحتوى الاشتراك",
				createFirstStory: "إنشاء القصة الأولى"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "تم حذف الخريطة",
				layerHasBeenDeleted: "تم حذف الطبقة",
				mapIsInaccessible: "خريطة غير قابلة للوصول",
				layerIsInaccessible: "طبقة غير قابلة للوصول",
				mapNotYoursNotAccessible: "يمتلك الخريطة شخص آخر وغير قابلة للوصول",
				layerServiceOkItemNot: "تم إضافة الطبقة باعتبارها عنصر تم حذفه أو غير قابل للوصول",
				layerNotYoursNotAccessible: "يمتلك الطبقة شخص آخر وغير قابلة للوصول",
				mapOthersSharedBelowLevel: "أنت لا تمتلك الخرية وليست للعامة",
				layerOthersSharedBelowLevel: "أنت لا تمتلك الطبقة وليست للعامة",
				noMapNoDetails: "لا يمكننا سرد أي شيء حول الطبقات بدون تفاصيل الخريطة",
				mapIsPrivate: "الخريطة خاصة",
				mapIsOrg: "تم مشاركة الخريطة في المؤسسة فقط",
				layerIsPrivate: "الطبقة خاصة",
				layerIsOrg: "تم مشاركة الطبقة في المؤسسة فقط",
				imageInaccessible: "الصورة الحالية غير قابلة للوصول",
				videoInaccessible: "مقطع الفيديو الحالي غير قابلة للوصول",
				webpageInaccessible: "صفحة الويب الحالية غير قابلة للوصول",
				layerSecureService: "الطبقة خدمة آمنة",
				mapSecureService: "الخريطة خدمة آمنة",
				layerConsumesCredits: "الطبقة محتوى متميز واستهلاك للأرصدة",
				layerSubscriptionContent: "الطبقة هي محتوى الاشتراك",
				mapConsumesCredits: "الخريطة محتوى متميز واستهلاك للأرصدة",
				mapSubscriptionContent: "الخريطة هي محتوى الاشتراك"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "لا يمكننا التحقق من نوع الطبقة الحالي",
				cantScanThisType: "الطبقة ليست نوع طبقة يمكن التحقق منه",
				webpageNotScanned: "لم يتم التحقق من صفحات الويب للموضوعات"
			},
			scanningErrors: {
				deletedMap: "تم حذف المحتوى",
				inaccessibleMap: "محتوى خريطة غير قابل للوصول",
				notYoursNotAccessible: "أنت لا تمتلك محتوى وليست للعامة",
				serviceOkItemNot: "الطبقات تعمل ولكنها ليست عناصر قابلة للوصول",
				someContentNotPublic: "محتوى غير مٌشارك مع العامة",
				someContentPrivate: "محتوى خاص",
				othersSharedBelowLevel: "أنت لا تمتلك محتوى وليست للعامة",
				premiumContent: "المحتوى المتميز",
				subscriptionContent: "محتوى الاشتراك",
				secureService: "تأمين الخدمات",
				inaccessibleImage: "صور غير قابلة للوصول",
				inaccessibleVideo: "مقاطع فيديو غير قابلة للوصول",
				inaccessibleWebpage: "صفحات ويب غير قابلة للوصول"
			},
			scanningErrorTips: {
				deletedMapTip: "بيت_Tip: Edit your web map and remove the broken content, or remove the web map from your story_____________________________لاحقة.",
				inaccessibleMapTip: "بيت_Tip: Edit your web map and remove the broken content, or remove the web map from your story_____________________________لاحقة.",
				notYoursNotAccessibleTip: "بيت_Tip: Edit your web map and remove the layer, or remove the web map from your story__________________________لاحقة.",
				serviceOkItemNotTip: "تم إضافة الطبقات باعتبارها عناصر قابلة للوصول أو تم حذفها. الطبقات تعمل، ولكنها قد تؤثر على الخريطة (النوافذ المنبثقة، الرمزية).",
				ignore: "تجاهل",
				fix: "تصحيح",
				clickToShareOrg: "انقر على الزر لمشاركة جميع المحتويات في المؤسسة، او قم بتغيير كل عنصر يدويًا عن طريق النقر على أزرار المشاركة.",
				clickToSharePublic: "انقر على الزر لمشاركة جميع المحتويات مع العامة، او قم بتغيير كل عنصر يدويًا عن طريق النقر على أزرار المشاركة.",
				shareOrg: "شارك مع مؤسستك",
				sharePublicly: "مشاركتها بشكل عام",
				othersSharedBelowLevelTip: "ملاحظة: يمتلك {{USER_NAME}} بعض محتويات الحكاية، وآخرين ممكن قاموا بعرض الحكاية قد لا يستطيعون رؤيتها.",
				secureServiceTip: "ملاحظة: احذف خدمة التأمين من الحكاية Â او اتبع الإجراءات التالية الموضحة {{HERE}}.",
				blogArticle: "هنا",
				premiumContentTip: "تحتوي الحكاية على محتوى متميز يستهلك {{CREDITS}} لعمله عام. تأكد من ان الحكاية عامة واتابع أو احذف الطبقات من الحكاية.",
				premiumContentPublicTip: "تحتوي الحكاية على محتوى متميز يستهلك {{CREDITS}} لجعل العام متوفر. تأكد من ان الطبقات عامة واتابع أو احذف الطبقات من الحكاية.",
				subscriptionContentTip: "تعتبر حكاية محتوى الاشتراك متوفرة تلقائيًا. تأكد من عمل الطبقات عامة (لن يستهلك أية أرصدة)، أو احذف الطبقات من الحكاية.",
				agolCredits: "أرصدة ArcGIS Online.",
				credits: "اعتمادات",
				makePublic: "يصبح عام",
				confirm: "تأكيد",
				inaccessibleImageTip: "ملاحظة: قم بتوفير الصورة المفقودة أو احذف المرجع.",
				inaccessibleVideoTip: "ملاحظة: قم بتوفير مقطع الفيديو المفقودة أو احذف المرجع.",
				inaccessibleWebpageTip: "ملاحظة: قم بتوفير صفحة الويب المفقودة أو احذف المرجع."
			},
			removeLayer: {
				title: "اصلح مشكلة الطبقة",
				layersWithIssue: "طبقات مع الموضوع الحالي: {{NUM_WITH_ISSUE}}",
				issueExplanation: "تم إضافة الطبقة باعتبارها عنصر قابل للوصول أو محذوف. الطبقة تعمل، ولكنها قد تؤثر على الخريطة (النوافذ المنبثقة، الرمزية). لا يمكننها السرد إذا لم يكن العنصر هام في الحكاية.",
				issueSolution: "لإصلاح المشكلة، يمكنك تحرير الخريطة، وحذف الطبقة، وإضافة طبقة للخريطة باستخدام عنوان URL التالي:",
				editMap: "تحرير الخريطة",
				clickBelowWhenDone: "عند الانتهاء من التحرير، انقر على الزر التالي:",
				rescanAndClose: "إعادة المسح والغلق"
			},
			info: {
				ownedBy: "يمتلك {{USER_NAME}} العنصر الحالي",
				unknownUser: "شخص آخر",
				untitledSection: "(قسم غير مسمى)",
				introRecord: "مقدمة"
			},
			layers: {
				layersHeader: "الطبقات",
				noLayers: "(لا توجد أي طبقات)",
				basemapParens: "(خريطة الأساس)"
			},
			images: {
				thumbnails: "مصغرات",
				thumbnail: "صورة مصغرة",
				thumbnailParens: "(الصورة المصغرة)"
			},
			general: {
				noTitle: "(بدون عنوان)",
				loading: "جارِ التحميل..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "الأقسام",
				secondTitle: "النمط",
				secondValueA: "لوحة جانبية",
				secondValueB: "لوحة عائمة",
				thirdTitle: "خرائط"
			},
			mapTour: {
				firstTitle: "نقاط الجولة",
				secondTitle: "النمط",
				secondValueA: "تكامل",
				secondValueB: "لوحة ثلاثية",
				thirdTitle: "خريطة الأساس",
				thirdValueLoading: "جارِ التحميل...",
				thirdValueUnknown: "غير معروف"
			},
			mapSeries: {
				firstTitleA: "نقاط",
				firstTitleB: "الأقسام",
				firstTitleC: "علامات التبويب",
				secondTitle: "النمط",
				secondValueA: "نقاط",
				secondValueB: "لوحة تحكم متحركة جانبية",
				secondValueC: "مبوبة",
				thirdTitle: "خرائط"
			},
			swipeSpyglass: {
				firstTitle: "نقاط الاهتمام",
				secondTitle: "النمط",
				secondValueA: "سحب",
				secondValueB: "العسة المُكبرة",
				thirdTitle: "خرائط"
			}
		},
		progress: {
			checkingStories: "بحث في الحكايات عن مشكلات...",
			stop: "إيقاف",
			exit: "خروج",
			dismiss: "تجاهل",
			done: "تم.",
			noStoriesWithIssuesLower: "لم يتم العثور على موضوعات!",
			storiesErrorFree: "تبدو حكايات بدون أخطاء",
			scanAllError: "يتعذر المسح -- لا يمكن استعادة قصة أو أكثر",
			scanProgress: "{{NUM_SCANNED}} من {{NUM_TOTAL}}",
			scanStopped: "تم مسح الحكايات: {{NUM_SCANNED}}، حكايات ذات مشكلات: {{ISSUE_STORIES}}",
			storiesWithIssues: "حكايات ذات مشكلات: {{NUM_STORIES}}"
		}
    })
);
