define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Afstand invoeren",
                    "layerName": "Hier laagnaam invoeren"
                },
                "message": {
                    "analysisFailed": "Analyse mislukt.",
                    "errorOccurred": "Fout opgetreden.",
                    "layerAdded": "Laag met succes toegevoegd. ",
                    "enrichLayerNameError": "De \'Resultaatlaagnaam\' mag geen ongeldige tekens bevatten" + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Service maken... ",
                    "starting": "Begin",
                    "performingAnalysis": "Analyse uitvoeren",
                    "checkLayerName": "Controleren op laagnaam. ",
                    "addingLayer": "Laag toevoegen aan webmap ",
                    "layerNameExist": "Laagnaam bestaat al.",
                    "clickOnSave": " Klik op de knop \'Save\' om de applicatie opnieuw te laden.",
                    "clickOnOk": " Klik op de knop \'OK\' om het opnieuw te proberen.",
                    "enterNumbersOnly": "De ingevoerde waarden zijn niet geldig",
                    "nofeatures": "Er zijn geen objecten in het huidige bereik",
                    "selectData": "Selecteer data om de laag te verrijken.",
                    "resetVariableMessage": "Weet u zeker dat u de variabele wilt opnieuw instellen?",
                    "emptyTextFieldLayerName": "Voer naam resultaatlaag in",
                    "createService":"Geen laag gemaakt.",
                    "sharingLayer":"Share layer",
                    "updateItemFailed": "Update mislukt. Probeer het nogmaals.",
                    "geoEnrichFailed": "Kan laag niet verrijken. Probeer het later nogmaals.",
                    "shareFailed": "Kan verrijkte laag niet delen. Probeer het later nogmaals.",
                    "refreshServiceFailed": "Kan laag niet vernieuwen. Probeer het later nogmaals.",
                    "layerJsonFailed": "Kan geen JSON maken voor laag. Probeer het later nogmaals.",
                    "addToWebmapFailed": "Kan geen laag toevoegen. Probeer het later nogmaals.",
                    "bufferAreaHelpText": "Voer een waarde in kleiner dan ",
                    "invalidBufferInput": "De ingevoerde waarde is niet geldig.",
                    "emptyBufferInput": "Geef een geldige waarde op."
                },
                "populationText": "Bevolking",
                "housingText": "Huishoudens",
                "businessText": "Economie",
                "variableListText": " variabelen worden hier vermeld:",
                "countrySelectTitle": "1. Selecteer datalocatie",
                "unitedStates": "United States",
                "global": "Global",
                "geoenrichDialogText": "GeoEnrichment variabelen",
                "viewVariablestext": "Variabelen bekijken",
                "backButtonText":"Vorige",
                "customizeVariables": "Variabelen aanpassen",
                "resetVariables": "Opnieuw instellen",
                "defineAreaTitle": "3. Gebied definiëren om te verrijken",
                "currentMapExtent": "Huidige extent van de kaart gebruiken",
                "enrichLayerName": "4. Naam resultaatlaag",
                "lineDistanceText": "Lijnafstand",
                "drivingTime": "Reistijd",
                "enrichButtonText": "Laag verrijken",
                "selectDataText": "2. Data selecteren",
                "showCreditsText": "Credits tonen",
                "variableCount": "Totaal aantal variabelen ",
                "totalRecords": "Total Records:",
                "cost": "Kosten",
                "showCreditsDialogText": "Credits tonen",
                "nextButtonText": "Volgende",
                "prevButtonText": "Vorige",
                "saveButtonText": "Opslaan",
                "ok": "OK"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 