define(
({
		viewer: {
			loading: {
				step1: "APPLICATIE LADEN",
				step2: "GEGEVENS LADEN",
				step3: "DE TOUR INITIALISEREN",
				loadBuilder: "OMSCHAKELEN NAAR BUILDERMODUS",
				redirectSignIn: "OMLEIDEN NAAR AANMELDINGSPAGINA",
				redirectSignIn2: "(na het aanmelden wordt u naar hier omgeleid)",
				fail: "De Kaart Tour kon niet worden geladen",
				failButton: "Opnieuw proberen"
			},
			errors: {
				boxTitle: "Er is een fout opgetreden",
				portalSelf: "Onherstelbare fout: Kan de portaalconfiguratie niet ophalen",
				invalidConfig: "Onherstelbare fout: ongeldige configuratie",
				invalidConfigOwner: "Onherstelbare fout: ongeldige configuratie (gemachtigde eigenaar vereist)",
				invalidConfigNoWebmap: "Onherstelbare fout: ongeldige configuratie (webmap- of applicatie-id niet opgegeven in index.html)",
				createMap: "Kan kaart niet maken",
				invalidApp: "Onherstelbare fout: de applicatie kan niet worden geladen",
				noLayer: "De webmap bevat geen geldige gegevenslaag voor de Kaart Tour.",
				noLayerMobile: "Welkom bij de webapplicatie Kaart Tour. De applicatie is niet geconfigureerd. De builder voor de Kaart Tour wordt niet ondersteund op mobiele apparaten.",
				noLayerView: "Welkom bij de webapplicatie Kaart Tour.<br />De applicatie is nog niet geconfigureerd.",
				appSave: "Fout bij het opslaan van de webapplicatie",
				mapSave: "Fout bij het opslaan van de webmap",
				featureServiceLoad: "Fout bij het laden van de featureservice",
				notAuthorized: "U bent niet gemachtigd om deze applicatie te openen",
				oldBrowserTitle: "Browser niet volledig ondersteund",
				noBuilderIE8: "De Kaart Tour-builder wordt niet ondersteund in oudere versies van Internet Explorer dan versie 9.",
				ie10Win7Explain: "De Kaart Tour interactieve builder wordt niet ondersteund op Internet Explorer 10 op Windows 7 als de gegevensbron een Featureservice met bijlagen is. Om een Featureservice met bijlagen te gebruiken, moet u <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>de documentmodus handmatig forceren volgens Internet Explorer 9-standaarden</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgraden naar Internet Explorer 9</a> of upgraden naar Windows 8.",
				oldBrowserExplain: "Deze browser biedt geen ondersteuning voor de automatische generatie van miniaturen vanaf afbeeldingen die u in uw kaart tour uploadt. U kunt een kaart tour maken met behulp van deze browser, maar u moet een afzonderlijke miniatuurafbeelding opgeven voor elk van de afbeeldingen die u uploadt.",
				oldBrowserExplain2: "Voor een betere ervaring voert u een <a href='http://browsehappy.com/' target='_blank'>upgrade van uw browser</a> uit of <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activeert u Google Chrome Frame voor Internet Explorer</a>.",
				oldBrowserExplain3: "De Kaart Tour builder werkt niet met Internet Explorer 10 op Windows XP.",
				oldBrowserClose: "Sluiten"
			},
			mobileHTML: {
				showIntro: "TITEL WEERGEVEN",
				hideIntro: "TITEL VERBERGEN",
				navList: "Lijst",
				navMap: "Kaart",
				navInfo: "Media",
				introStartBtn: "Start"
			},
			desktopHTML: {
				storymapsText: "Een kaartverhaal",
				builderButton: "Omschakelen naar buildermodus",
				bitlyTooltip: "Een korte koppeling naar de applicatie maken",
				bitlyStartIndex: "Koppeling naar huidige plaats"
			},
			builderHTML: {
				panelHeader: "APPLICATIECONFIGURATIE",
				buttonSave: "OPSLAAN",
				buttonSettings: "Instellingen",
				buttonShare: "Ĳ_Share_ä",
				buttonView: "Weergavemodus",
				buttonItem: "Het webapplicatie-item openen",
				buttonHelp: "Help",
				buttonOrganize: "Rangschikken",
				buttonAdd: "Toevoegen",
				buttonImport: "Importeren",
				buttonImportDisabled: "Importeren is niet beschikbaar bij gebruik van een Featureservice met bijlagen",
				dataEditionDisabled: "Het bewerken van gegevens is uitgeschakeld op de CSV-gegevensbron",
				dataSourceWarning: "De Kaartour-gegevenslaag is gewijzigd. Als de object-id\'s niet identiek zijn, moet u de volgorde en de verborgen punten opnieuw instellen via <b>Rangschikken</b>. Als de naam van de velden verschilt, moet u de instellingen van de velden opnieuw instellen onder het <b>gegevenstabblad in Instellingen</b>.",
				organizeWarning: "Een of meer punten die buiten de interactieve builder zijn toegevoegd, zijn verborgen.",
				dataPicError0a: "Deze tour bevat <b>%NB%</b> niet-conforme afbeeldings-URL\'s.",
				dataPicError0b: "Deze tour bevat mogelijk <b>%NB%</b> niet-conforme afbeeldings-URL\'s.",
				dataPicError1: "Kaarttours vereisen nu dat een afbeeldings-URL op een van de volgende extensies eindigt: .jp(e)g, .png, .gif of .bmp.",
				dataPicError2: "Deze vereiste heeft geen invloed op uw bestaande gepubliceerde Kaarttour. Om echter de interactieve builder te kunnen gebruiken, moet u het probleem met de URL eerst oplossen door een van deze twee handelingen uit te voeren:",
				dataPicError3: "URL\'s bewerken",
				dataPicError4: "Hiermee voegt u <i>#isImage</i> toe aan het einde van niet-ondersteunde afbeeldings-URL\'s. De meeste servers ondersteunen URL-toevoegingen. Zodra u echter deze handeling hebt uitgevoerd, moet u controleren of de bijgewerkte afbeeldings-URL\'s functioneren door naar uw punten te navigeren. Als alle afbeeldingen zijn geladen, kunt u de Kaarttour nu opslaan. Als <b>de afbeeldingen gebroken zijn, slaat u de Kaarttour niet op</b>. Laad in plaats daarvan de builder opnieuw en voer de tweede handeling uit.",
				dataPicError5: "De tour beperken tot afbeeldingen",
				dataPicError6: "Met deze optie worden alle URL\'s beschouwd als afbeeldingen, maar u kunt geen video\'s toevoegen met de interactieve builder. Deze handeling is omkeerbaar zodat u later nog kunt beslissen om video toe te voegen.",
				dataPicError7: "Uw Kaarttour is beperkt tot afbeeldingen. Er kunnen geen video\'s worden gebruikt. Als u deze beperking wilt opheffen, controleert u of uw afbeeldingen nog steeds correct worden geladen voordat u de Kaarttour opslaat. U kunt deze beperking later herstellen als dat nodig is.",
				dataPicError8: "Afbeeldingsbeperking verwijderen",
				dataPicError9: "Als deze URL\'s verwijzen naar video\'s, kunt u deze waarschuwing negeren. Als ze verwijzen naar afbeeldingen, moet u een van deze twee handelingen uitvoeren:",
				modalCancel: "Annuleren",
				modalApply: "Toepassen",
				organizeHeader: "De tour rangschikken",
				organizeGeneralCaption: "Gebruik slepen en neerzetten om de punten op de tour te sorteren",
				organizeDelete: "Verwijderen",
				organizeHide: "Verbergen",
				organizeReset: "Volgorde en verborgen punten opnieuw instellen",
				addMaxPointReached: "U hebt het maximumaantal punten bereikt dat door de pictogrammenset is toegestaan en u kunt geen extra punt op de tour toevoegen.<br /><br />Als u bestaande punten verwijdert, moet u de applicatie opnieuw laden.",
				addMaxPointReachedMobile: "Het maximaal toegestane aantal punten is bereikt, u kunt deze afbeelding niet toevoegen.",
				addClose: "Sluiten",
				addHeader: "Een nieuw punt op de tour toevoegen",
				addTabPicture: "Media",
				addTabInformation: "Informatie",
				addTabLocation: "Locatie",
				addSelectCaption: "Afbeelding selecteren of neerzetten",
				addNoteVideo: "Raadpleeg de Help voor instructies over het gebruik van video\'s",		
				addSelectCaptionNoFileReader: "Afbeelding selecteren",	
				addChangePhoto: "Afbeelding en thumbnail wijzigen",
				addPictureResolutionIntro: "De resolutie van de afbeelding is hoger dan vereist:",
				addPictureResolutionOldBrowser: "De resolutie van de afbeelding is hoger dan vereist. Optimaliseer de Kaart Tour door een lagere resolutie dan %RECOMMENDED_RES% op te geven.",
				addPictureResolutionResize: "Resolutie van afbeelding wijzigen in %RESOLUTION%",
				addPictureResolutionKeep: "De originele resolutie van %RESOLUTION% behouden",
				addSelectThumbnail: "Miniatuur selecteren",
				addNoThumbSelected: "Geen miniatuur geselecteerd",
				addThumbSelected: "Geselecteerd",
				addCameraSettingsHeader: "CAMERA-INSTELLINGEN",
				addThumbnailHeader: "MINIATUUR",
				addLabelPicUrl: "Afbeelding",
				addLabelThumbUrl: "Thumbnail",
				addTextPlaceholderUrl: "Voer een afbeeldings-URL in",
				addTextPlaceholderUrl2: "Ĳ_Enter a Youtube page URL_ä",
				addTextPlaceholderUrl3: "Voer de URL van een Vimeo-pagina in",
				addTextPlaceholderUrl4: "Voer de URL van een ingebedde video in",
				addLabelVideo: "Video",
				addMediaVideoOther: "Overige",
				addMediaVideoHelp: "Controleer de URL en haal de standaardthumbnail op",
				addMediaVideoHelpTooltip1: "Controle geslaagd",
				addMediaVideoHelpTooltip2: "Controle mislukt",
				addMediaVideoHelpTooltip4: "Zoek naar de optie om de video in te bedden en kopieer de URL van de video die aanwezig is in de code",
				addLabelName: "Naam",
				addLabelDescription: "Bijschrift",
				addTextPlaceholder: "Typ iets",
				addLocatePlaceholder: "Zoek naar een adres of plaats",
				addPinColor: "Kleur",
				addLatitude: "Breedtegraad",
				addLongitude: "Lengtegraad",
				addLatitudePlaceholder: "bv. 34.056",
				addLongitudePlaceholder: "bv. -117.195",
				addUploading: "Punt op de tour uploaden",
				addSave: "Punt op de tour toevoegen",
				addMobileUploading: "Afbeelding uploaden",
				addMobileName: "Voer een naam in",
				addMobileNameMandatory: "Fout. Voer een naam in.",
				addMobileError: "Er is een fout opgetreden",
				settingsHeader: "Applicatie-instellingen",
				settingsTabLayout: "Lay-out",
				settingsTabColor: "Kleuren",
				settingsTabLogo: "Koptekst",
				settingsTabFields: "Gegevens",
				settingsTabExtent: "Extent",
				settingsTabZoom: "Zoomniveau",
				settingsLayoutExplain: "Selecteer de gewenste applicatielay-out.",
				settingsLayoutProfessional: "Lay-out met drie deelvensters",
				settingsLayoutModern: "Geïntegreerde lay-out",
				settingsLayoutSelected: "Geselecteerde lay-out",
				settingsLayoutSelect: "Selecteer deze lay-out",
				settingsLayoutNote: "Merk op dat, op punten die video\'s gebruiken, de markering altijd onder de video zal worden geplaatst, zelfs als die optie niet is ingeschakeld.",
				settingsLayoutLocBtn: "Ĳ_Display a locate button on supported browser_ä",
				settingsLayoutLocBtnHelp: "Deze functionaliteit wordt ondersteund op de meeste mobiele apparaten en desktopbrowsers (Internet Explorer 9).",
				settingsColorExplain: "Verander het uiterlijk door een vooraf gedefinieerd thema te kiezen of door uw eigen thema te kiezen.",
				settingsLabelColor: "Kleuren van koptekst, inhoud en voettekst",
				settingsLogoExplain: "Pas het logo van de koptekst aan (het maximum is 250 x 50px).",
				settingsLogoEsri: "Esri-logo",
				settingsLogoNone: "Geen logo",
				settingsLogoCustom: "Aangepast logo",
				settingsLogoCustomPlaceholder: "Afbeeldings-URL",
				settingsLogoCustomTargetPlaceholder: "Doorklikkoppeling",
				settingsLogoSocialExplain: "Pas de koppeling in de rechterbovenhoek van de koptekst aan.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Koppeling",
				settingsLogoSocialDisabled: "Deze functie is uitgeschakeld door de beheerder",
				settingsDataFieldsExplain: "Selecteer de velden voor de naam van de foto, het bijschrift en de kleur.",
				settingsDataFieldsError: "De applicatie kan de juiste gegevens voor de naam, het bijschrift en de kleur niet bepalen. Selecteer de velden die hier moeten worden gebruikt. Deze instellingen kunnen later worden gewijzigd.",
				settingsFieldsLabelName: "Naam",
				settingsFieldsLabelDescription: "Bijschrift",
				settingsFieldsLabelColor: "Kleur",
				settingsFieldsReset: "Selectie van velden opnieuw instellen",
				settingsExtentExplain: "Stel het oorspronkelijke extent van de Kaart Tour in op de onderstaande interactieve kaart.",
				settingsExtentExplainBottom: "Het extent dat u definieert, zal het oorspronkelijke extent van de webmap wijzigen. Merk op dat dit extent niet wordt gebruikt als het het eerste punt van de tour niet bevat. In dat geval wordt de tour geopend met het eerste punt in het midden.",
				settingsExtentDateLineError: "Het extent mag niet op de meridiaan van 180° lengtegraad zijn",
				settingsExtentDateLineError2: "Fout bij het berekenen van het extent",
				settingsExtentDrawBtn: "Een nieuw extent tekenen",
				settingsExtentModifyBtn: "Het extent bewerken",
				settingsExtentApplyBtn: "Voorbeeld weergeven op Kaarttour",
				settingsExtentUseMainMap: "Extent van kaarttour gebruiken",
				settingsZoomExplain: "Stel het zoomniveau in voor de verhaalpunten volgens de inleiding (optioneel).",
				settingsLabelZoom: "Schaal/niveau",
				settingsZoomFirstValue: "Geen",
				settingsFieldError: "Selecteer een veld in elke lijst",
				dataTitle: "ArcGIS Online-hosting",
				dataExplain: "Ĳ_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._ä",
				dataNameLbl: "Servicenaam",
				dataFolderListLbl: "Folder",
				dataFolderListFetching: "Folders ophalen...",
				dataRootFolder: "Hoofdmap",
				dataNameError: "Voer een naam in voor de featureservice",
				dataFolderError: "Selecteer een geldige folder",
				dataSrcContainsInvalidChar: "De naam van de featureservice bevat een of meer ongeldige tekens (-, <, >, #, %, :, ", ?, &, +, /, of ).",
				dataSrvAlreadyExistsError: "Er bestaat al een service met deze naam in de organisaties. Kies een andere naam.",
				dataBtnSave: "De service maken",
				dataFooterProgress: "Wordt gemaakt",
				dataFooterSucceed: "Het maken is gelukt. Bezig met laden",
				dataFooterError: "Het maken is mislukt. Probeer het opnieuw",
				tabError: "Controleer alle tabbladen op fouten",
				introRecordBtn: "Inleiding",
				introRecordActivate: "Gebruik het eerste punt als een inleiding (verschijnt niet in carousel)"
			},
			addPopupJS: {
				uploadingPicture: "Afbeelding uploaden",
				uploadSuccess: "Uploaden gelukt",
				uploadError: "Fout bij het uploaden van de afbeelding",
				uploadError2: "Fout bij het toevoegen van het object (ongeldige HTML-tag)",
				notJpg: "Kies een JPEG-foto om te uploaden",
				errorNoPhoto: "Kies een afbeelding om te uploaden",
				errorNoThumbnail: "Kies een miniatuur om te uploaden",
				errorInvalidPicUrl: "Voer een geldige afbeelding in (begint met http(s)://, eindigt op jpg, png, gif of bmp). U kunt de URL laten eindigen op \'#isImage\' om die regel te negeren.",
				errorInvalidThumbUrl: "Voer een geldige miniatuur in (begint met http(s)://, eindigt op jpg, png, gif of bmp).",
				errorInvalidVideoUrl: "Voer een geldige video-URL in (begint met http(s)://)",
				errorNoName: "Voer een naam in voor dit punt van de tour",
				errorNoDescription: "Voer een bijschrift in voor dit punt van de tour",
				errorNoLocation: "Selecteer een locatie voor dit punt van de tour"
			},
			builderJS: {
				noPendingChange: "Geen niet-opgeslagen wijziging",
				unSavedChangeSingular: "1 niet-opgeslagen wijziging",
				unSavedChangePlural: "niet-opgeslagen wijzigingen",
				shareStatus1: "Ĳ_Tour is not saved_ä",
				shareStatus2: "Ĳ_Tour is shared publicly_ä",
				shareStatus3: "Ĳ_Tour is shared within the organization_ä",
				shareStatus4: "Ĳ_Tour is not shared_ä",
				popoverDiscard: "Weet u zeker dat u eventuele niet-opgeslagen wijzigingen wilt negeren?",
				yes: "Ja",
				no: "Nee",
				popoverLoseSave: "Door de viewer te openen gaan eventuele niet-opgeslagen wijzigingen verloren",
				ok: "OK",
				popoverSaveWhenDone: "Vergeet uw werk niet op te slaan wanneer u klaar bent",
				closeWithPendingChange: "Weet u zeker dat u de actie wilt bevestigen? Uw wijzigingen gaan verloren.",
				gotIt: "OK",
				savingApplication: "Applicatie opslaan",
				saveSuccess: "Applicatie opgeslagen",
				saveError: "Opslaan mislukt, probeer het opnieuw",
				saveError2: "Opslaan is mislukt vanwege een ongeldige HTML-tag in een naam of beschrijving",
				saveError3: "De titel mag niet leeg zijn",
				dragColorPicker: "Wijzig mijn positie<br />of verander mijn kleur",
				dataWarningExtent: "U beschikt over gegevens buiten het webmapextent. Deze gegevens worden niet gebruikt als punten voor de tour. Wijzig het kaartextent als u deze toch wilt gebruiken.",
				dataWarningVisibi: "Uw laag Kaart Tour is niet zichtbaar op het huidige webmapextent. Controleer of uw laag Kaart Tour zichtbaar is met een kaart die %MAPSIZE% groot is.",
				dataWarningEdit: "Webmap bewerken",
				dataWarningClose: "Sluiten",
				signIn: "Meld u aan met een account op",
				signInTwo: "om de applicatie op te slaan.",
				switchBM: "Basiskaart wijzigen"
			},
			organizePopupJS: {
				messageStart: "U hebt gekozen om het volgende te verwijderen",
				messageSinglePoint: "één punt van de tour",
				messageMultiPoint: "punten van de tour",
				messagePermantRemove: "Hiermee verwijdert u permanent",
				messageRecord: "record",
				messageRecordPlural: "records",
				messageConfirm: "uit uw database. Wilt u doorgaan?",
				labelButtonShow: "Weergeven",
				labelButtonHide: "Verbergen"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Hierdoor worden de afbeelding en de thumbnail definitief verwijderd",
				popoverDeleteWarningThumb: "Hierdoor wordt de thumbnail definitief verwijderd",
				popoverUploadingPhoto: "Afbeelding en miniatuur uploaden",
				popoverUploadingThumbnail: "Miniatuur uploaden",
				popoverUploadSuccessful: "Uploaden gelukt",
				popoverUploadError: "Uploaden mislukt, probeer het opnieuw",
				changePicAndThumb: "Afbeelding wijzigen",
				changeThumb: "Miniatuur wijzigen",
				selectPic: "Media wijzigen",
				selectThumb: "Miniatuur wijzigen",
				uploadPicAndThumb: "Toepassen"
			},
			headerJS:{
				editMe: "Bewerk me!",
				templateTitle: "Titel voor template instellen",
				templateSubtitle: "Subtitel voor template instellen"
			},
			crossFaderJS:{
				setPicture: "Titel voor afbeelding instellen",
				setCaption: "Bijschrift voor afbeelding instellen"
			},
			importPopup: {
				title: "Importeren",
				prevBtn: "Vorige",
				nextBtn: "Volgende"
			},
			importPopupHome: {
				header: "Waar zijn uw afbeeldingen opgeslagen?"
			},
			onlinePhotoSharingCommon: {
				pictures: "afbeeldingen",
				videos: "video's",
				disabled: "Deze functie is uitgeschakeld door de beheerder",
				disabledPortal: "Deze functie is uitgeschakeld op Portal for ArcGIS",
				header1: "Uw afbeeldingen moeten openbaar worden gedeeld.",
				header2: "Het importeren wordt beperkt tot de eerste %NB1% %MEDIA%.",
				emptyDataset: "Fout, geen afbeeldingen gevonden",
				footerImport: "Importeren",
				selectAlbum: "Selecteer een openbaar album",
				selectAlbum2: "Selecteer een album",
				pleaseChoose: "Maak een keuze",
				userLookup: "Opzoeken",
				userLookingup: "Bezig met opzoeken",
				csv: "Verwijzing in een CSV",
				advanced: "Geavanceerde opties",
				advancedScratchLbl: "Ĳ_Start a new Tour_ä",
				advancedScratchTip: "Ĳ_Create an empty Tour that you will be able populate manually using a wizard._ä",
				advancedCSVLbl: "Ĳ_Import Tour data from a CSV file_ä",
				advancedCSVTip: "Ĳ_Import your Tour content from a CSV file._ä",
				advancedCommonTip: "Ĳ_It requires that your images and videos are already online._ä",
				select: "Maak een keuze",
				locUse: "Gebruik de geografische locatie van de afbeeldingen",
				locExplain: "Ĳ_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._ä",
				locExplain2: "Ĳ_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._ä"
			},
			viewFlickr: {
				title: "Importeren van Flickr",
				header: "Ĳ_Enter your Flickr user name and select a Photo Set or a Tag to be imported._ä",
				userInputLbl: "Typ een gebruikersnaam",
				signInMsg2: "Gebruiker niet gevonden",
				selectSet: "Selecteer een Fotoset",
				selectTag: "of selecteer een label",
				footerImportTag: "Importeer het geselecteerde label",
				footerImportSet: "Importeer de geselecteerde set"
			},
			viewFacebook: {
				title: "Importeren van Facebook",
				header: "Ĳ_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._ä",
				leftHeader: "Facebook-gebruiker",
				rightHeader: "Facebook-pagina",
				pageExplain: "Een Facebook-pagina is een openbaar merk/product of beroemdheid zoals <b>esrigis</b>. U vindt de naam van de pagina achter de eerste  '/' in de URL van de pagina.",
				pageInputLbl: "Een paginanaam invoeren",
				lookupMsgError: "Pagina niet gevonden"
			},
			viewPicasa: {
				title: "Importeren van Picasa/Google+",
				header: "Ĳ_Enter your email address or the ID of your Picasa or Google+ account._ä",
				userInputLbl: "Typ een e-mailadres of ID",
				signInMsg2: "Account niet gevonden",
				howToFind: "Zoeken naar een Picasa- of Google+-account-ID",
				howToFind2: "Kopieer getallen tussen de eerste en tweede '/' van een pagina van Picasa of G+"
			},
			viewCSV: {
				title: "Importeren van CSV",
				uploadBtn: "Selecteer of sleep een CSV-bestand",
				resultHeaderEmpty: "Het CSV-bestand is leeg",
				resultHeaderSuccess: "Laden van %NB_POINTS% punten is gelukt",
				resultHasBeenLimited: "Importeren is beperkt tot de eerste %VAL1% punten van %VAL2% om rekening te houden met de limiet van %VAL3% punten per tour",
				browserSupport: "Uw browser wordt niet ondersteund, om een CSV te gebruiken, moet u <a href='http://browsehappy.com/' target='_blank'>uw browser upgraden</a> of de ArcGIS.com webmapviewer gebruiken (zie Help).",
				errorLatLng: "Geen velden gevonden voor lengte- en breedtegraad. Mogelijke waarden voor breedtegraad zijn <i>%LAT%</i> en voor lengtegraad: <i>%LONG%</i>.",
				errorFieldsExplain: "Laden is mislukt omdat de volgende verplichte velden niet zijn gevonden",
				errorFieldsName: "<b>Naam</b> Mogelijke waarden zijn: %VAL%",
				errorFieldsDesc: "<b>Omschrijving</b> Mogelijke waarden zijn: %VAL%",
				errorFieldsUrl: "<b>Afbeeldings-URL</b> Mogelijke waarden zijn: %VAL%",
				errorFieldsThumb: "<b>Miniatuur-URL</b> Mogelijke waarden zijn: %VAL%",
				errorFields2Explain: "Laden is mislukt omdat het CSV-bestand niet dezelfde attributen gebruikt als de laag voor de volgende attributen",
				errorFields2Name: "<b>Naam</b> gebruik %VAL1% in plaats van %VAL2%",
				errorFields2Desc: "<b>Omschrijving</b> gebruik %VAL1% in plaats van %VAL2%",
				errorFields2Url: "<b>Afbeeldings-URL</b> gebruik %VAL1% in plaats van %VAL2%",
				errorFields2Thumb: "<b>Miniatuur-URL</b> gebruik %VAL1% in plaats van %VAL2%",
				resultFieldsAll: "Alle attributen zijn geïmporteerd",
				resultFieldsNotAll: "De volgende attributen zijn niet geïmporteerd omdat ze niet voorkomen in de kaartlaag",
				resultFieldsNotAll2: "De volgende attributen zijn geïmporteerd",
				footerNextBtnResult: "Importeren in de webmap",
				footerProgress: "Bezig met importeren",
				footerSucceed: "Importeren geslaagd. Bezig met laden"
			},
			viewYoutube: {
				title: "Importeren van YouTube",
				header: "Voer een YouTube-gebruikersnaam in om te zoeken naar openbaar gedeelde video's.",
				pageInputLbl: "Ĳ_Enter a Youtube user name_ä",
				lookupMsgError: "Gebruiker niet gevonden",
				howToFind: "Ĳ_How to find a Youtube user name_ä",
				howToFind2: "Gebruikersnaam wordt weergegeven onder video\'s",
				found: "Gevonden",
				noData: "Geen openbare video\'s gevonden"
			},
			viewGeoTag: {
				title: "Ĳ_Select and locate your images/videos_ä",
				header: "Klik of tik op de afbeeldingen die u wilt importeren om ze te lokaliseren.",
				headerMore: "Waarom zijn mijn afbeeldingen/video's niet geografisch gelokaliseerd?",
				headerExplain: "Ĳ_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._ä",
				leftPanelTab1: "Lokaliseren",
				leftPanelTab2: "Gelokaliseerd",
				clickOrTap: "Klik of tik op de kaart om te lokaliseren",
				clearLoc: "Ĳ_Clear locations_ä",
				clickDrop: "Niet importeren",
				footerImport: "Importeren",
				footerProgress: "Bezig met importeren",
				footerSucceed: "Importeren geslaagd. Bezig met laden...",
				loading: "Laden",
				error: "Importeren van geografische locatie van afbeeldingen mislukt, geografische locaties zijn genegeerd."
			},
			initPopup: {
				title: "Welkom bij de Kaart Tour Builder",
				prevBtn: "Vorige",
				nextBtn: "Volgende"
			},
			initPopupHome: {
				header1: "Waar zijn uw afbeeldingen of video's?",
				header2: "Deze assistent helpt u bij het samenstellen van een Kaart Tour met afbeeldingen die al online zijn opgeslagen, of het importeert deze in uw ArcGIS Online for Organizations-account.",
				title1: "Ze zijn al online",
				title2: "Ik moet mijn afbeeldingen uploaden",
				hostedFSTooltip: "Gebruik ArcGIS Online om uw afbeeldingen te hosten (geen ondersteuning voor video's).",
				hostedFsNA: "Alleen beschikbaar voor gebruikers van ArcGIS for Organizations met de rol van Publisher en Beheerder",
				footer1: "Als u klaar bent, moet u niet vergeten om uw Kaart Tour te delen met uw publiek via de applicatie-itempagina.",
				footer3: "De CSV-template downloaden",
				footer4: "\"Opslaan als\" wanneer het niet is gedownload",
				footer4bis: "Klik met de rechtermuisknop en gebruik \"Opslaan als\" als het downloaden niet wordt gestart",
				footer5: "Meer weten",
				footerProgress: "Wordt gemaakt",
				footerSucceed: "Aangemaakt. Bezig met laden...."
			},
			helpPopup: {
				title: "Help",
				close: "Sluiten",
				tab1: {
					title: "Inleiding",
					div1: "Ĳ_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._ä",
					div2: "Ĳ_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_ä",
					div4: "Ĳ_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._ä",
					div42: "Ĳ_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._ä",
					div5: "Ĳ_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._ä"
				},
				tab2: {
					title: "Gegevens",
					div1: "Het voornaamste element waarmee u rekening moet houden bij het samenstellen van een Kaarttour is kiezen waar uw afbeeldingen zullen worden opgeslagen. Een Kaarttour kan afbeeldingen gebruiken die zijn opgeslagen in belangrijke services voor het delen van foto\'s, op een webserver of als bijlagen bij een featureservice.",
					div1a: "Raadpleeg de laatste sectie van dit tabblad voor meer informatie over ondersteunde afbeeldingsindelingen en video\'s.",
					div2: "De interactieve builder biedt twee opties voor het in de Kaart Tour verwerken van afbeeldingen:",
					div3: "<ul><li>U kunt <b>foto\'s gebruiken die al online staan</b>, zoals afbeeldingen die zijn opgeslagen op een site voor het delen van foto\'s, zoals Flickr, of afbeeldingen die op uw eigen website zijn opgeslagen. Naar deze afbeeldingen wordt in de Kaarttour verwezen via de URL.</li><li>U kunt ook <b>foto\'s uploaden vanaf uw computer</b> rechtstreeks naar uw Kaarttour. Voor deze uploadoptie hebt u een ArcGIS Online-abonnement nodig en publisher- of beheersmachtigingen, omdat dit automatisch een gehoste featureservice voor u maakt waarin de foto\'s als bijlagen worden opgeslagen.</li></ul>",
					div4: "De voornaamste gebruikersvoorbeelden zijn:",
					div4b: "<b>Uw foto\'s worden nog niet gehost</b> en u hebt een ArcGIS Online-abonnement: uw beste optie is het gebruik van een gehoste featureservice. Net als bij diensten voor het openbaar delen van foto\'s optimaliseren we uw foto\'s zodat ze snel geladen kunnen worden en u hebt toegang tot alle beheers- en gegevensbeheermogelijkheden van het ArcGIS-platform.",
					div5: "<b>U bent geen lid van een organisatie</b>: u moet uw foto\'s eerst uploaden naar een website voor het delen van foto\'s of naar uw eigen webserver. De builder helpt u bij het gebruiken van deze afbeeldingen die op hun oorspronkelijke locatie gehost blijven.",
					div6: "<b>U wilt een bestaande Featureservice opnieuw gebruiken</b> waarin uw afbeeldingen als bijlagen zijn opgeslagen of die naar externe afbeeldingen verwijst: zie de uitgebreide sectie hierna.",
					div7: "<b>U gebruikt een eerdere versie</b> van de Kaarttour-template en beschikt al over uw CSV-bestand met een verwijzing naar uw afbeeldingen en miniaturen: u kunt deze importeren en uw gegevens verfijnen. De builder ondersteunt alleen CSV-bestanden met lengte- en breedtegraadvelden. Op adressen gebaseerde CSV-bestanden kunt u blijven gebruiken via uw webmap (zie de sectie hierna).",
					div8: "Importeren uit online diensten voor het delen van foto\'s",
					div9: "Bij het importeren wordt naar reeds gehoste afbeeldingen verwezen door de URL\'s op te slaan in een webmapverzameling. De afbeeldingen worden niet opgeslagen in ArcGIS Online. Als de gehoste afbeeldingen niet kunnen worden geopend, zijn ze niet beschikbaar in de Kaarttour en wordt een afbeelding \'Afbeelding niet beschikbaar\' weergegeven. Afhankelijk van de fotoserviceprovider importeert de Kaarttour al dan niet de naam, beschrijving en locatie van de afbeeldingen. Die attributen worden opgeslagen in de webmap en bewerkingen in de onlinediensten zijn niet zichtbaar in de Kaarttour.",
					div10: "De afbeeldingen opslaan op een webserver",
					div11: "Als u ervoor kiest om de afbeeldingen zelf te hosten, moet u handmatig miniaturen van uw foto\'s maken. Het gebruik van de volledige afbeeldingen voor miniaturen levert slechte prestaties op. Daarom raden we sterk aan om een onlinedienst voor het delen van foto\'s te gebruiken of een featureservice die dat voor u doet.",
					div12: "Een bestaande Featurservice of Shapefile gebruiken",
					div13: "Elke puntfeatureservice of shapefile is bruikbaar als gegevensbron voor een Kaarttour. U hoeft deze alleen toe te voegen als laag in de webmap met de ArcGIS.com-map viewer. Als de applicatie de verwachte attributen in de laag aantreft, zijn alle mogelijkheden van de builder beschikbaar.",
					div14: "Ĳ_The possible values for fields name are (case insensitive):_ä",
					div151: "Naam",
					div152: "Beschrijving",
					div153: "Afbeelding",
					div154: "Thumbnail",
					div155: "Ĳ_Color_ä ",
					div16: "Ĳ_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._ä",
					div162: "Als u een featureservice gebruikt die de afbeeldingen opslaat als bijlagen, <b>worden alleen de objecten met twee bijlagen gebruikt</b>. De eerste bijlage bepaalt de hoofdafbeelding en de tweede bijlage bepaalt de miniatuur.",
					div17: "De velden voor afbeelding en miniatuur zijn verplicht voor featureservices zonder bijlagen en optioneel (maar sterk aanbevolen) voor featureservices met bijlagen. Als in uw service bijlagen zijn ingeschakeld, laat de builder u afbeeldingen als bijlagen uploaden. Anders kunt u alleen de URL\'s voor de afbeelding en miniatuur bewerken.",
					div172: "Indien aanwezig, worden de velden voor afbeelding en miniatuur altijd gebruikt en worden er geen query\'s uitgevoerd op de featureservicebijlagen.",
					div173: "Voorbeelden van CSV-bestanden en shapefiles kunnen worden gedownload van",
					div18: "Gehoste Featureservices maken van een CSV of shapefile",
					div19: "Als u een gehoste featureservice maakt van een CSV of shapefile, worden de bijlagen standaard niet ingeschakeld. Om ze in te schakelen, opent u de pagina met details van de featureservice. Klik op het pijltje op het laaggedeelte en de optie verschijnt. Daarna blijft de Kaarttour de afbeeldingen en miniaturen gebruiken waarnaar u hebt verwezen via attributen. Of als u uw afbeeldingen wilt uploaden als featureservicebijlagen, kunt u dat doen met twee knoppen in het afbeeldingenvenster (\'Afbeelding wijzigen\' en \'Miniatuur wijzigen\').",
					div20: "Ondersteunde afbeeldingsindelingen en video\'s",
					div21: "Ondersteunde afbeeldingsindelingen zijn: <b>.jpg, .jpeg, .png, .gif en .bmp</b>. Als uw media niet eindigt op deze extensie, beschouwt de Kaarttour deze als een video, behalve wanneer u een featureservice gebruikt (zie hieronder).",
					div22: "De Kaarttour-template bevat geen videospeler. U moet de externe videospeler gebruiken die wordt geleverd door uw favoriete videohostservice (zoek naar de optie om de video in te bedden en kopieer de URL die aanwezig is in de opgegeven code). Als u de video zelf wilt hosten, kunt u een HTML-pagina maken die een videospeler bevat zoals <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "De interactieve builder biedt geen dialoogvenster om video op te nemen als featureservices met bijlagen worden gebruikt, maar het is wel mogelijk om dit te doen door uw gegevens buiten de interactieve builder te bewerken. Als u in de ArcGIS.com-map viewer de afbeeldingsvelden verandert zodat deze naar een externe video verwijzen en u een speciale parameter toevoegt aan het einde van uw URL (#isVideo), dan zal uw media als een video worden beschouwd.",
					div24: "Houd er rekening mee dat u nog steeds twee geldige afbeeldingsbijlagen nodig hebt omdat de punten anders niet worden gebruikt. Het is niet mogelijk om video\'s te gebruiken wanneer u featureservicebijlagen gebruikt zonder de velden voor afbeelding en miniatuur."
				},
				tab3: {
					title: "Aanpassen",
					div1: "De builder bevat meerdere opties voor aanpassingen die ingesteld kunnen worden met de knop INSTELLINGEN in het bovenste venster. Als u de verwachte optie niet kunt vinden, bieden we tevens een downloadbare versie aan die u op uw webserver kunt draaien en naar uw wensen aanpassen.",
					div2: "We raden aan om de gehoste versie te gebruiken tenzij:",
					div3: "<li>Deze niet de aanpassing voor de gebruikersinterface biedt die u nodig hebt, zoals het gebruik van een achtergrondafbeelding in de kop.</li><li>U ontwikkelaar bent en u de applicatie wilt uitbreiden.</li>",
					div4: "De downloadbare versie kan worden geconfigureerd via een webmap-id of een webmapapplicatie-id. De belangrijkste gebruiksvoorbeelden zijn:",
					div41: "U bouwt uw kaarttour met de interactieve builder in de gehoste omgeving en configureert de template met de webmapapplicatie-id. De instellingen die u met de interactieve builder hebt gedefinieerd, zullen worden toegepast.",
					div42: "U bouwt uw webmap buiten de interactieve builder en configureert de template met de webmap-id. Lees de documentatie om te leren hoe u de template configureert.",
					div43: "Merk op dat de interactieve builder beschikbaar is in de downloadbare versie, maar dat er enkele technische beperkingen gelden voor browers zoals Internet Explorer ouder dan versie 10.",
					div5: "Ĳ_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._ä"
				},
				tab4: {
					title: "Tips",
					div0: "Ondersteunde browsers",
					div0a: "De Kaarttour-viewer wordt ondersteund op IE8+. De interactieve builder wordt ondersteund op IE9+. Wij voeren actief tests uit in alle belangrijke browsers, maar als u problemen ondervindt, raden wij u aan Chrome te gebruiken.",
					div0b: "Als u problemen ondervindt, laat het ons dan weten. Ondertussen kunt u uw Kaarttour bouwen met de CSV-template en zo uw interactie met de builderinterface minimaliseren.",
					div1: "Afbeeldingen",
					div2: "Ĳ_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._ä",
					div2a: "Ĳ_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._ä",
					div3: "Tekst opmaken met HTML-tags",
					div4: "De koptekst, en de titel en het bijschrift van de afbeelding kunnen HTML-tags bevatten voor de opmaak en de koppelingen. Deze code voegt bijvoorbeeld een gele koppeling toe:",
					div4a: "Ĳ_Write a good subtitle for your tour_ä",
					div4b: "Ĳ_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._ä",
					div5: "Ondersteunende lagen",
					div6: "U kunt extra ondersteunende lagen toevoegen om context aan de Kaarttour te geven. Deze lagen bevatten mogelijk andere geografische opties die de kaart moet weergeven naast de Kaarttour-punten, zoals een studiegebied, een wandel- of rijroute die de punten in uw tour met elkaar verbindt enzovoort. De Kaarttour-template geeft deze aanvullende ondersteunende lagen weer met de symbolen die u in de webmap opgeeft, maar de pop-ups zijn niet beschikbaar.",
					div7: "Houd de tour kort en aangenaam",
					div8: "Elke tour heeft een limiet van 99 punten. De meeste Kaarttours zijn uiteraard aanzienlijk korter dan dit. Verwacht niet dat uw publiek door teveel tourpunten zal willen stappen. U vindt uw onderwerp waarschijnlijk fascinerend, maar ga er niet vanuit dat anderen dat ook vinden.",
					div9: "Zie <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>de gedetailleerde gids</a> voor meer informatie.",
					div10: "Modus voor inbedden",
					div11: "Als u de template in een andere website wilt inbedden met behulp van een Iframe, zal door de optionele parameter \"&embed\" aan het einde van de URL toe te voegen, de koptekst worden verwijderd. Deze modus kan ook worden ingesteld in de downloadbare versie via het configuratiebestand.",
					div12: "Ĳ_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._ä" 
				},
				tab5: {
					title: "Publiceren",
					div1: "Ĳ_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._ä",
					div2a: "Ĳ_Sharing the Tour through the builder_ä",
					div2b: "Ĳ_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._ä",
					div2c: "Ĳ_Sharing the Tour through ArcGIS Online_ä",
					div2d: "Ĳ_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._ä",
					div3t: "Ĳ_Feature Service security_ä",
					div3a: "Als u een gehoste featureservice gebruikt die met de Kaarttour-builder is gemaakt, beheert de applicatie de beveiliging van de service voor u en behoudt u als enige de bewerkingsrechten, ook als u de service openbaar deelt.",
					div3t2: "Ĳ_Before sharing your Tour with your audience_ä",
					div3: "Ĳ_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._ä",
					div4: "Ĳ_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._ä",
					div5a: "Ĳ_Recommendation for search_ä",
					div5b: "Ĳ_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._ä"
				}
			},
			share: {
				firstSaveTitle: "Opslaan van Tour geslaagd",
				firstSaveHeader: "Ĳ_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._ä",
				firstSaveA1: "Als u niet vertrouwd bent met ArcGIS Online of u zoekt een snelle manier om toegang te krijgen tot de ontwerpinterface, kunt u de volgende koppeling opslaan: %LINK1%",
				firstSaveA1bis: "Ĳ_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._ä",
				firstSaveQ2: "Is mijn Tour gedeeld?",
				firstSaveA2: "Ĳ_Currently your Tour is not shared. To share it, use the SHARE button._ä",
				shareTitle: "Uw Tour opslaan",
				sharePrivateHeader: "Uw Tour wordt niet gedeeld. Wilt u deze delen?",
				sharePrivateBtn1: "Openbaar delen",
				sharePrivateBtn2: "Delen met Mijn Organisatie",
				sharePrivateProgress: "Delen wordt uitgevoerd...",
				sharePrivateErr: "Delen is mislukt. Probeer het opnieuw of",
				sharePrivateOk: "Delen is bijgewerkt. Bezig met laden...",
				sharePreviewAsUser: "Voorbeeld",
				shareHeader1: "Uw Tour is <strong>openbaar toegankelijk</strong>.",
				shareHeader2: "Uw Tour is toegankelijk voor de leden van uw organisatie (aanmelding is vereist).",
				shareLinkHeader: "De Tour delen met uw publiek",
				shareLinkOpen: "OPENEN",
				shareQ1Opt1: "Hoe houd ik de Tour privé?",
				shareQ1Opt2: "Ĳ_How do I keep the Tour private or share it publicly?_ä",
				shareA1: "Ĳ_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._ä",
				shareA1bis: "Ĳ_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._ä",
				shareQ2: "Ĳ_How do I edit the Tour later?_ä",
				shareQ2bis: "Ĳ_How do I get back to the authoring interface?_ä",
				shareA2div1: "Ĳ_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._ä",
				shareA2div2: "Als u bent aangemeld bij ArcGIS.com als de eigenaar van de applicatie, bevat de applicatie een knop om de interactieve builder te openen:",				
				shareQ3: "Waar zijn de gegevens opgeslagen?",
				shareA3: "De Tour-configuratie wordt opgeslagen in <a href='%LINK1%' target='_blank'>dit webmapitem</a> en <a href='%LINK2%' target='_blank'>dit webapplicatie-item</a>. Als u importeren van Flickr, Picasa, Facebook of YouTube hebt gebruikt, blijven uw afbeeldingen en video's daar opgeslagen en worden deze niet gedupliceerd in ArcGIS Online."
			}
        }
    })
);
