define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ã_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Ç",
            selectFieldsText:"ã_Select Form Fields_Ç",
            selectThemeText: "Escolher o Tema do Formulário",
            fieldLabelPlaceHolder: "Dê um rótulo a este campo",
            fieldDescPlaceHolder: "Descreva este campo",
            webmapText: "ã_1. Webmap_Ç",
            layerText: "ã_2. Layer_Ç",
            detailsText: "ã_3. Details_Ç",
            fieldsText: "ã_4. Fields_Ç",
            styleText: "ã_5. Style_Ç",
            previewText: "ã_6. Preview_Ç",
            publishText: "ã_7. Publish_Ç",
            titleText: "GeoForm Builder",
            descriptionText: "ã_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._Ç",
            btnPreviousText: "Anterior",
            btnNextText:"Seguinte",
            webmapTabTitleText: "Escolher um Mapa Web",
            btnSelectWebmapText:"Escolher Mapa Base",
            layerTabTitleText: "Escolher Camada Editável",
            selectLayerLabelText:"Camada",
            selectLayerDefaultOptionText:"Escolher Camada",
            detailsTabTitleText:"Detalhes do Formulário",
            detailTitleLabelText: "Título",
            detailLogoLabelText: "Imagem do Logo",
            detailDescriptionLabelText: "Descrição",
            fieldTabFieldHeaderText: "Campo",
            fieldTabLabelHeaderText: "Rótulo",
            fieldTabTypeHeaderText: "Tipo",
            fieldTabDescriptionHeaderText: "Descrição",
            previewApplicationText: "Pré-visualizar Aplicação",
            saveApplicationText: "Guardar Aplicação",
            saveText: "Guardar",
            toggleNavigationText: "ã_Toggle navigation_Ç",
            formPlaceholderText: "ã_My Form_Ç",
            imageLogoPlaceholderText: "ã_http://www.mysite.com/myimage.png_Ç",
            shareBuilderInProgressTitleMessage: "ã_Publishing GeoForm_Ç",
            shareBuilderProgressBarMessage:"ã_Please Wait..._Ç",
            shareBuilderTitleMessage: "ã_Your GeoForm has been updated & published!_Ç",
            shareBuilderTextMessage: "ã_You can start collecting information by sharing with others_Ç",
            shareDialogFormText: "ã_Form Link_Ç",
            geoformTitleText: "ã_Geo Form_Ç",
            layerTabText: "ã_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Ç",
            detailsTabText:"ã_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._Ç",
            fieldsTabText:"ã_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Ç",
            styleTabText: "ã_Style your GeoForm using the themes below based on your preference._Ç",
            publishTabText: "ã_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Ç"
        }
    })
);