define(
     ({
        map: {
            error: "Não foi possível criar o mapa"
        },
        onlineStatus: {
            offline: "De momento, está a trabalhar em modo offline. Submissões de formulários serão guardadas localmente até que possa ser estabelecida uma ligação com o servidor. until a connection to the server can be made.",
            reconnecting: "Reconectando&hellip;",
            pending: "${total} edições pendentes serão submetidas assim que seja restabelecida uma ligação à rede."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "A Organização",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "O Meu Conteúdo",
                    favoritesLabel: "Os Meus Favoritos"
                },
                title: "Selecionar Mapa Web",
                searchTitle: "Pesquisar",
                ok: "Ok",
                cancel: "Cancelar",
                placeholder: "Introduza termo de pesquisa"
            },
            groupdlg: {
                items: {
                    organizationLabel: "A Organização",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "O Meu Conteúdo",
                    favoritesLabel: "Os Meus Favoritos"
                },
                title: "Selecionar Grupo",
                searchTitle: "Pesquisar",
                ok: "Ok",
                cancel: "Cancelar",
                placeholder: "Introduza termo de pesquisa"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "ã_Here is a link to a GeoForm_Ç"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Northing",
            utm_easting: "Easting",
            utm_zone_number: "Número da Zona",
            geoFormGeneralTabText: "1. Introduzir Informação",
            locationInformationText: "2. Escolher Localização",
            submitInformationText: "3. Completar Formulário",
            submitInstructions: "Adicione estas informações ao mapa.",
            myLocationText: "Localização Atual",
            locationDescriptionForMoreThanOneOption: "ã_Specify the location for this entry by clicking/tapping the map or by using one of the following options_Ç.",
            locationDescriptionForOneOption: "ã_Specify the location for this entry by clicking/tapping the map or by using the following option_Ç.",
            locationDescriptionForNoOption: "ã_Specify the location for this entry by clicking/tapping the map_Ç.",
            addressText: "Pesquisar",
            geographic: "Lat/Lon",
            locationTabText: "Localização",
            locationPopupTitle: "Local",
            submitButtonText: "Submeter Entrada",
            submitButtonTextLoading: "A submeter&hellip;",
            formValidationMessageAlertText: "Os seguintes campos são necessários:",
            selectLocation: "ã_Please select a location for your submission_Ç.",
            emptylatitudeAlertMessage: "Por favor introduza a coordenada ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Por favor introduza a coordenada ${openLink}longitude${closeLink}.",
            shareUserTitleMessage: "Obrigado pela sua contribuição!",
            entrySubmitted: "A sua entrada foi submetida ao mapa.",
            shareThisForm: "Partilhar Este Formulário",
            shareUserTextMessage: "Diga a outros que contribuam utilizando as seguintes opções.",
            addAttachmentFailedMessage: "Impossível adicionar anexo à camada",
            addFeatureFailedMessage: "Impossível adicionar elemento à camada",
            noLayerConfiguredMessage: "ã_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_Ç.",
            placeholderLatitude: "Latitude (Y)",
            placeholderLongitude: "Longitude (X)",
            latitude: "Latitude",
            longitude: "Longitude",
            findMyLocation: "Localizem-me",
            finding: "A localizar&hellip;",
            backToTop: "Voltar ao topo",
            addressSearchText: "A sua submissão aparecerá aqui. Pode arrastar o alfinete para corrigir a localização.",
            shareModalFormText: "Ligação para o Formulário",
            close: "Fechar",
            locationNotFound: "A localização não pode ser encontrada.",
            setLocation: "Definir Localização",
            find: "Localizar endereço ou lugar",
            attachment: "Anexo",
            toggleDropdown: "Alternar lista dropdown",
            invalidString: "ã_Please enter valid value_Ç.",
            invalidSmallNumber: "ã_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_Ç.",
            invalidNumber: "ã_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_Ç.",
            invalidFloat: "ã_Please enter valid ${openStrong}floating point${closeStrong} value_Ç.",
            invalidDouble: "ã_Please enter valid ${openStrong}double${closeStrong} value_Ç.",
            invalidLatLong: "ã_Please enter valid latitude and longitude coordinates_Ç.",
            invalidUTM: "ã_Please enter valid UTM coordinates_Ç.",
            invalidUSNG: "ã_Please enter valid USNG coordinates_Ç.",
            invalidMGRS: "ã_Please enter valid MGRS coordinates_Ç.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Selecionar&hellip;",
            applyEditsFailedMessage: "Lamentamos mas a sua entrada não pode ser submetida. Por favor tente novamente.",
            requiredFields: "Existem alguns erros. Por favor corriga-os abaixo.",
            requiredField: "(necessário)",
            error: "Erro",
            textRangeHintMessage: "${openStrong}Dica:${closeStrong} Valor mínimo ${minValue} e Valor máximo ${maxValue}",
            dateRangeHintMessage: "${openStrong}Dica:${closeStrong} Data Mínima ${minValue} e Data Máxima ${maxValue}",
            remainingCharactersHintMessage: "ã_${value} characters remaining_Ç"
        },
        builder: {
            invalidUser: "Lamentamos, não tem permissão para visualizar este item",
            invalidWebmapSelectionAlert: "O mapa web selecionado não contém uma camada válida para utilizar. Por favor, adicione uma Camada de Elementos editável ao seu mapa web para continuar.",
            invalidWebmapSelectionAlert2: "Para mais informações, por favor consulte ${openLink}O que é um Serviço de Elementos?${closeLink}",
            selectFieldsText: "Selecionar Campos do Formulário",
            selectThemeText: "Escolher o Tema do Formulário",
            webmapText: "Mapa Web",
            layerText: "Camada",
            detailsText: "Detalhes",
            fieldsText: "Campos",
            styleText: "Estilo",
            optionText: "Parâmetros de Consulta",
            previewText: "Pré-Visualizar",
            publishText: "Publicar",
            optionsApplicationText: "Parâmetros de Consulta",
            titleText: "Builder",
            descriptionText: "ã_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_Ç.",
            btnPreviousText: "Anterior",
            btnNextText: "Seguinte",
            webmapTabTitleText: "Selecionar um Mapa Web",
            viewWebmap: "Visualizar Mapa Web",
            webmapDetailsText: "ã_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_Ç",
            btnSelectWebmapText: "Escolher Mapa Web",
            btnSelectWebmapTextLoading: "Carregando&hellip;",
            layerTabTitleText: "Escolher Camada Editável",
            selectLayerLabelText: "Camada",
            selectLayerDefaultOptionText: "Selecionar Camada",
            detailsTabTitleText: "Detalhes do Formulário",
            detailTitleLabelText: "Título",
            detailLogoLabelText: "Imagem do Logotipo",
            descriptionLabelText: "ã_Form Instructions & Details_Ç",
            fieldDescriptionLabelText: "ã_Help Text (optional)_Ç",
            fieldTabFieldHeaderText: "Campo",
            fieldTabLabelHeaderText: "Rótulo",
            fieldTabDisplayTypeHeaderText: "Exibir Como",
            fieldTabOrderColumnText: "ã_Order_Ç",
            fieldTabVisibleColumnText: "ã_Enabled_Ç",
            selectMenuOption: "Selecionar Menu",
            selectRadioOption: "Botão de Rádio",
            selectTextOption: "Texto",
            selectDateOption: "ã_Date Picker_Ç",
            selectRangeOption: "ã_Touch-Spinner_Ç",
            selectCheckboxOption: "Caixa de Seleção",
            selectMailOption: "Correio eletrónico",
            selectUrlOption: "URL",
            selectTextAreaOption: "ã_Text Area_Ç",
            previewApplicationText: "Pré-visualizar Aplicação",
            saveApplicationText: "Guardar Aplicação",
            saveText: "Guardar",
            toggleNavigationText: "Alternar navegação",
            formPlaceholderText: "O Meu Formulário",
            shareBuilderInProgressTitleMessage: "A publicar o GeoForm",
            shareBuilderProgressBarMessage: "Por favor, aguarde&hellip;",
            shareBuilderTitleMessage: "Sucesso! Item guardado",
            shareBuilderTextMessage: "Pode começar a recolher informações através da partilha",
            shareModalFormText: "Ligação para o Formulário",
            shareBuilderSuccess: "O seu GeoForm foi atualizado e publicado!",
            geoformTitleText: "Geo Form",
            layerTabText: "Esta é a camada a partir da qual o  GeoForm será construído. A camada tem de conter um serviço de elementos com edição ativada e com permissões de partilha apropriadas ao seu público.",
            detailsTabText: "Utilize as caixas de Detalhes de Formulário abaixo para personalizar o Título, adicionar um logótipo personalizado e fornecer uma descrição curta para o público do seu Geoform. Na descrição, pode adicionar ligações para outros recursos, informações de contacto e até indicar ao seu público uma aplicação de cartografia web com todos os dados colecionados com o GeoForm.",
            fieldsTabText: "Aqui pode selecionar que campos estarão visíveis ao público do seu GeoForm, editar os Rótulos que serão visíveis e adicionar uma descrição curta para ajudar na introdução de dados.",
            styleTabText: "Configure o estilo do seu GeoForm utilizando os temas abaixo com base nas suas preferências.",
            publishTabText: "Se terminou de configurar o seu GeoForm, guarde a aplicação e começe a partilhar com o seu públicos. Pode sempre regressar a este builder e continuar a personalizá-lo com base no feedback.",
            headerSizeLabel:"ã_Header Size_Ç",
            smallHeader: "Utilizar Cabeçalho Pequeno",
            bigHeader: "ã_Use Large Header_Ç",
            pushpinText: "Inserir alfinete",
            doneButtonText: "ã_Save and Exit_Ç",
            fieldTabPlaceHolderHeaderText: "Dica (opcional)",
            enableAttachmentLabelText: "ã_${openStrong}Enable Attachments${closeStrong}_Ç",
            enableAttachmentLabelHint: "ã_You can enable/disable the attachments here_Ç",
            attachmentIsRequiredLabelText: "ã_${openStrong}Attachment Required${closeStrong}_Ç",
            attachmentIsRequiredLabelHint: "ã_If necessary, users can be required to enter an attachment_Ç.",
            attachmentLabelText: "ã_Attachment Button Label_Ç",
            attachmentLabelHint: "ã_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_Ç",
            attachmentDescription: "Descrição do Anexo",
            attachmentHint: "Se necessário, pode fornecer instruções adicionais sobre anexos aqui.",
            jumbotronDescription: "ã_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_Ç",
            shareGeoformText: "Partilhar Geoform",
            shareDescription: "O painel de partilha torna mais fácil ao seu público a partilha do GeoForm com outros colaboradores após terem efetuado uma submissão - isto pode ser desativado a qualquer momento.",
            defaultMapExtent: "Extensão por Defeito do Mapa",
            defaultMapExtentDescription: "O mapa regressará à extensão padrão no seu mapa web após a submissão - isto pode ser desativado a qualquer momento.",
            pushpinOptionsDescription: "Escolha uma de várias cores para o alfinete do mapa, este deve ser diferente da simbologia do mapa para ajudar o utilizador a efetuar a sua submissão no mapa.",
            selectLocationText: "Selecionar Localização Por",
            myLocationText: "Meu Local",
            searchText: "Pesquisar",
            coordinatesText: "Coordenadas de Latitude e Longitude",
            usng: "Coordenadas USNG",
            mgrs: "Coordenadas MGRS",
            utm: "Coordenadas UTM",
            selectLocationSDescription: "Permitir aos utilizadores selecionar uma localização utilizando estes métodos.",
            dragTooltipText:"ã_Drag the field where you want it to appear_Ç",
            showHideLayerText:"ã_Show/Hide Layer_Ç",
            showHideLayerHelpText:"ã_You can configure the GeoForm to Show/Hide Layer_Ç"
        }
    })
);