define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Syötä etäisyys",
        "layerName": "Kirjoita karttatason nimi tähän"
      },
      "message": {
        "analysisFailed": "Analyysi epäonnistui.",
        "errorOccurred": "On ilmennyt joitakin virheitä.",
        "layerAdded": "Karttatason lisäys on onnistunut. ",
        "enrichLayerNameError": "Tulostason nimi ei saa sisältää virheellisiä merkkejä(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Palvelua luodaan... ",
        "starting": "Alkaen",
        "performingAnalysis": "Analyysia suoritetaan...",
        "checkLayerName": "Karttatason nimeä tarkistetaan... ",
        "addingLayer": "Karttatasoa lisätään Web-karttaan ",
        "layerNameExist": "Karttatason nimi on jo olemassa.",
        "clickOnSave": " Lataa sovellus uudelleen napsauttamalla Tallenna-painiketta.",
        "clickOnOk": " Yritä uudelleen napsauttamalla OK-painiketta.",
        "enterNumbersOnly": "Annetut arvot eivät kelpaa",
        "nofeatures": "Nykyisessä laajuudessa ei ole kohteita",
        "selectData": "Valitse karttatason rikastamisessa käytettävä aineisto.",
        "resetVariableMessage": "Haluatko varmasti nollata muuttujan?",
        "emptyTextFieldLayerName": "Kirjoita tuloskarttatason nimi",
        "createService": "Karttataso ei luotu.",
        "sharingLayer": "Karttatasoa jaetaan...",
        "updateItemFailed": "Päivitys epäonnistui. Yritä uudelleen.",
        "geoEnrichFailed": "Karttatason rikastaminen epäonnistui. Yritä uudelleen.",
        "shareFailed": "Rikastetun karttatason jakaminen epäonnistui. Yritä uudelleen.",
        "refreshServiceFailed": "Karttatason päivity epäonnistui. Yritä uudelleen.",
        "layerJsonFailed": "Karttatason JSON-objektin luonti epäonnistui. Yritä uudelleen.",
        "addToWebmapFailed": "Karttatason lisäys Web-karttaan epäonnistui. Yritä uudelleen.",
        "bufferAreaHelpText": "Anna arvo, joka on pienempi kuin ",
        "invalidBufferInput": "Annettu arvo ei kelpaa.",
        "emptyBufferInput": "Anna kelvollinen arvo."
      },
      "populationText": "Väestö",
      "housingText": "Kotitalous",
      "businessText": "Liiketoiminta",
      "variableListText": " muuttujat on lueteltu tässä:",
      "countrySelectTitle": "1. Valitse aineiston sijainti",
      "unitedStates": "Yhdysvallat",
      "global": "Globaali",
      "geoenrichDialogText": "GeoEnrichment-muuttujat",
      "viewVariablestext": "Näytä muuttujat",
      "backButtonText": "Takaisin",
      "customizeVariables": "Mukauta muuttujia",
      "resetVariables": "Palauta",
      "defineAreaTitle": "3. Määritä rikastettava alue",
      "currentMapExtent": "Käytä nykyisen kartan laajuutta.",
      "enrichLayerName": "4. Tulostason nimi",
      "lineDistanceText": "Viivan etäisyys",
      "drivingTime": "Ajoaika",
      "enrichButtonText": "Rikasta karttataso",
      "selectDataText": "2. Valitse aineisto",
      "showCreditsText": "Näytä krediitit",
      "variableCount": "Muuttujien kokonaismäärä ",
      "totalRecords": "Tietueet yhteensä:",
      "cost": "Kustannukset:",
      "showCreditsDialogText": "Näytä krediitit",
      "nextButtonText": "Seuraava",
      "prevButtonText": "Edellinen",
      "saveButtonText": "Tallenna",
      "ok": "OK"
    }
  }
});