define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Siirry luontitoimintoon",
                "exitBuilderButtonText": "Lopeta luontitoiminto",
                "enterBuilderModeHelpText": "Määritä sovellus siirtymällä luontitoimintoon",
                "builderModeHelpText": "Mallin luontitoiminnon tila",
                "webmapCaption": "Kartta",
                "selectMapMessage": "Tällä hetkellä ${displaying} <b>${webmapTitle}</b><br/>Valitse toinen Web-kartta napsauttamalla Valitse kartta",
                "loadMapMessage": "Tällä hetkellä valittu <b>${webmapTitle}</b><br/>Käytä tätä Web-karttaa napsauttamalla Tallenna",
                "changeWebmap": "Valitse kartta",
                "saveButtonText": "Tallenna",
                "webmapNextButtonText": "Seuraava ->",
                "previousButtonText":"Edellinen",
                "layerLabelText": "Karttataso",
                "noLayerFoundText": "Yhtään karttatasoa ei löytynyt",
                "selectLayer": "Valitse karttataso",
                "applicationSettingText": "Sovelluksen asetukset",
                "summaryAttrAscendingOrderTooltip": "Nouseva",
                "onStartLabel": "Aloituksessa",
                "selectVariableText": "Valitse muuttuja",
                "selectVariableDropdown": "Valitse muuttuja",
                "label":"Tunnusteksti",
                "sourceLinkText":"Lähdelinkki",
                "selectSubVariableText":"Valitse alimuuttujat",
                "subVariablePanelButtonText":"VALMIS",
                "onButtonLabel":"Käytössä",
                "offButtonLabel":"Poissa käytöstä",
                "appSettingsSaveCloseButtonText": "TALLENNA JA SULJE",
                "appSettingsTitleText":"Sovelluksen otsikko",
                "appSettingsDescriptionText": "Sovelluksen kuvaus",
                "appSetingsRendererAreaText":"Renderöity alue",
                "shareText":"Jaa",
                "popupText": "Å_Popup_ö",
                "basemapText":"Taustakartta",
                "cancel": "Å_Cancel_ö",
                "theme": "Å_Theme_ö",
                "zoomLevel": "Å_Zoom Level_ö",
                "existingValue": "Å_Use existing values_ö",
                "enrichLayer": "Å_Enrich Layer_ö",
                "imageLabel": "Å_How does this work_ö ?",
                "clearData": "Å_Clear Data_ö",
                "basemapSelectionText":"Taustakartan valinta",
                "secondaryBasemapText":"Toissijainen taustakartta",
                "defaultBasemapText": "Oletustaustakartta",
                "entireAreaButton": "Koko alue",
                "entireAreaOnStartButton": "Koko alue aloituksessa",
                "aboutPanel": "Tietoja ruudusta",
                "legendPanel": "Seliteruutu",
                "layersPanel": "Karttatasot-ruutu",
                "dataConfigurationButtonText": "Aineiston määritys",
                "savingChangesMessage": "Tallennetaan muutoksia...",
                "nextButtonText": "Seuraava",
                "prevButtonText": "Edellinen",
                "enterLabelText": "Anna tunnusteksti",
                "SelectedFeatureText": "Valittu kohde",
                "layerHelpTextMessage": "Tämä sovellus edellyttää numerokenttiä sisältävän karttatason",
                "alertMessage": {
                    "resetVariableMessage": "Haluatko varmasti nollata muuttujan?",
                    "emptyAppTitleMessage": "Sovelluksen otsikko ei voi olla tyhjä",
                    "emptyDescriptionMessage": "Kuvaus ei voi olla tyhjä",
                    "maxVariableSelection": "Voit valita enintään 25 alimuuttujaa",
                    "signInFail" : "Sisäänkirjautuminen epäonnistui",
                    "itemUpdateMessage": "Kohde on päivitetty",
                    "unsavedChangesMessage": "Tallentamattomat muutokset",
                    "failMessage": "Kohteen päivitys ei onnistunut",
                    "saveChangesAlert": "Haluatko tallentaa muutokset?",
                    "variableLabelValidation": "Muuttujan tunnusteksti ei voi olla tyhjä",
                    "subVariableLabelValidation": "Alimuuttujan tunnusteksti ei voi olla tyhjä"
                    }
            }
        }
    })
);