define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "הכנס לבונה",
                "exitBuilderButtonText": "צא מהבונה",
                "enterBuilderModeHelpText": "הכנס למוד בניה להגדרת האפלירציה",
                "builderModeHelpText": "תבנית מוד הבניה",
                "webmapCaption": "מפה",
                "selectMapMessage": "${displaying} נוכחי <b>${webmapTitle}</b><br/>לחץ בחר מפה לבחירת webmap אחר",
                "loadMapMessage": "הבחירה הנוכחית של  <b>${webmapTitle}</b><br/>לחץ על שמור כדי להשתמש ב- webmap הזה",
                "changeWebmap": "בחר מפה",
                "saveButtonText": "שמור",
                "webmapNextButtonText": "הבא ->",
                "previousButtonText":"קודם",
                "layerLabelText": "שכבה",
                "noLayerFoundText": "לא נמצאה שכבה",
                "selectLayer": "בחר שכבה",
                "applicationSettingText": "הגדרות אפליקציה",
                "summaryAttrAscendingOrderTooltip": "עולה",
                "onStartLabel": "כן_On Start_ש",
                "selectVariableText": "בחר משתנה",
                "selectVariableDropdown": "בחר משתנה",
                "label":"תווית",
                "sourceLinkText":"קישור למקור",
                "selectSubVariableText":"בחר תת משתנה",
                "subVariablePanelButtonText":"הסתיים",
                "onButtonLabel":"מופעל",
                "offButtonLabel":"כבוי",
                "appSettingsSaveCloseButtonText": "שמור & סגור",
                "appSettingsTitleText":"כותרת האפליקציה",
                "appSettingsDescriptionText": "תאור האפליקציה",
                "appSetingsRendererAreaText":"האזור ש-Rendered",
                "shareText":"שתף",
                "basemapText":"מפת בסיס",
                "basemapSelectionText":"בחירת מפת בסיס",
                "secondaryBasemapText":"מפת בסיס משנית",
                "defaultBasemapText": "מפת בסיס ברירת מחדל",
                "entireAreaButton": "כן_Entire Area_ש",
                "entireAreaOnStartButton": "כן_Entire Area on start_ש",
                "aboutPanel": "כן_About Panel_ש",
                "legendPanel": "כן_Legend Panel_ש",
                "layersPanel": "כן_Layers Panel_ש",
                "dataConfigurationButtonText": "תצורת המידע",
                "savingChangesMessage": "שומר שינויים...",
                "nextButtonText": "הבא",
                "prevButtonText": "קודם",
                "enterLabelText": "הוסף תווית",
                "layerHelpTextMessage": "אפליקציה זו דורשת שכבה עם שדות מספריים",
                "alertMessage": {
                    "resetVariableMessage": "האם אתה בטוח שברצונך לאתחל את המשתנים?",
                    "emptyAppTitleMessage": "כותרת האפליקציה לא יכולה להיות ריקה",
                    "emptyDescriptionMessage": "התיאור לא יכול להיות ריק",
                    "maxVariableSelection": "לא ניתן לבחור יותר מ-25 תתי משתנים",
                    "signInFail" : "ההתחברות נכשלה",
                    "itemUpdateMessage": "הפריט עודכן",
                    "unsavedChangesMessage": "שינויים שלא נשמרו",
                    "failMessage": "לא ניתן לעדכן את הפריט בהצלחה",
                    "saveChangesAlert": "האם ברצונך לשמור את השינויים?",
                    "variableLabelValidation": "תווית המשתנה לא יכולה להיות ריקה",
                    "subVariableLabelValidation": "תווית תת המשתנה לא יכולה להיות ריקה"
                    }
            }
        }
    })
});