define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Entrar no Builder",
                "exitBuilderButtonText": "Sair do Builder",
                "enterBuilderModeHelpText": "Entrar em Modo Builder para configurar a aplicação",
                "builderModeHelpText": "Modo Template Builder",
                "webmapCaption": "Mapa",
                "selectMapMessage": "Atualmente ${displaying} <b>${webmapTitle}</b><br/>Clique em Escolher mapa para escolher outro mapa base",
                "loadMapMessage": "Atualmente selecionado <b>${webmapTitle}</b><br/>Clique em Guardar para utilizar este mapa base",
                "changeWebmap": "Escolher mapa",
                "saveButtonText": "Guardar",
                "webmapNextButtonText": "Seguinte ->",
                "previousButtonText":"Anterior",
                "layerLabelText": "Camada",
                "noLayerFoundText": "Camada Não Encontrada",
                "selectLayer": "Escolher Camada",
                "applicationSettingText": "Definições da Aplicação",
                "summaryAttrAscendingOrderTooltip": "Ascendente",
                "onStartLabel": "Na Inicialização",
                "selectVariableText": "Escolher uma Variável",
                "selectVariableDropdown": "Escolher uma Variável",
                "label":"Rótulo",
                "sourceLinkText":"Ligação de Origem",
                "selectSubVariableText":"Selecionar Sub-Variáveis",
                "subVariablePanelButtonText":"TERMINADO",
                "onButtonLabel":"Ligar",
                "offButtonLabel":"Desligar",
                "appSettingsSaveCloseButtonText": "GUARDAR & FECHAR",
                "appSettingsTitleText":"Titulo da Aplicação",
                "appSettingsDescriptionText": "Descrição da Aplicação",
                "appSetingsRendererAreaText":"Área Processada",
                "shareText":"Partilhar",
                "popupText": "Janela pop-up",
                "basemapText":"Mapa Base",
                "cancel": "Cancelar",
                "theme": "Tema",
                "zoomLevel": "Nível de Zoom",
                "existingValue": "Utilizar valores existentes",
                "enrichLayer": "Enriquecer Camada",
                "imageLabel": "Como funciona ?",
                "clearData": "Limpar Dados",
                "basemapSelectionText":"Seleção de Mapas Base",
                "secondaryBasemapText":"Mapa base secundário",
                "defaultBasemapText": "Mapa Base Padrão",
                "entireAreaButton": "Área Total",
                "entireAreaOnStartButton": "Área Completa na inicialização",
                "aboutPanel": "Painel Sobre",
                "legendPanel": "Painel Legendas",
                "layersPanel": "Painel Camadas",
                "dataConfigurationButtonText": "Configuração de Dados",
                "savingChangesMessage": "Guardando Alterações...",
                "nextButtonText": "Seguinte",
                "prevButtonText": "Anterior",
                "enterLabelText": "Introduzir Rótulo",
                "SelectedFeatureText": "Elemento Selecionado",
                "layerHelpTextMessage": "Esta aplicação exige uma camada com campos numéricos",
                "alertMessage": {
                    "resetVariableMessage": "Tem a certeza de que pretende redefinir a variável ?",
                    "emptyAppTitleMessage": "O título da aplicação não pode estar vazio",
                    "emptyDescriptionMessage": "A descrição não pode estar vazia",
                    "maxVariableSelection": "Não pode escolher mais do que 25 variáveis",
                    "signInFail" : "Início de Sessão Falhou",
                    "itemUpdateMessage": "Item Atualizado",
                    "unsavedChangesMessage": "Alterações Não-Guardadas",
                    "failMessage": "Não foi possível atualizar o item",
                    "saveChangesAlert": "Pretende guardar as alterações?",
                    "variableLabelValidation": "O rótulo da variável não pode estar vazio",
                    "subVariableLabelValidation": "O rótulo da sub-variável não pode estar vazio"
                    }
            }
        }
    })
);