define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Pasirinktame internetiniame žemėlapyje nėra tinkamo naudoti sluoksnio. Norėdami tęsti, į internetinį žemėlapį pridėkite redaguojamą FeatureLayer.",
            selectFieldsText:"Pasirinkite formos laukus",
            selectThemeText: "Pasirinkite formos temą",
            fieldLabelPlaceHolder: "Apibūdinkite šį lauką",
            fieldDescPlaceHolder: "Aprašyti šį lauką",
            webmapText: "1. Internetinis žemėlapis",
            layerText: "2. Sluoksnis",
            detailsText: "3. Išsami informacija",
            fieldsText: "4. Laukai",
            styleText: "5. Stilius",
            previewText: "6. Peržiūra",
            publishText: "7. Publikuoti",
            titleText: "GeoForm kūrimo priemonė",
            descriptionText: "GeoForm – tai konfigūruojamas šablonas, skirtas <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>elementų paslaugos</a> redagavimui naudojant formas. Naudodami šią aplikaciją vartotojai gali įvesti duomenis per formas, o ne žemėlapio iškylančius langus, pasitelkdami <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>internetinio žemėlapio</a> ir redaguojamų elementų paslaugų galią. Naudokite šią kūrimo priemonę, kad adaptuotumėte ir įdiegtumėte GeoForm, atlikę kairėje pateiktus veiksmus.",
            btnPreviousText: "Ankstesnis",
            btnNextText:"Kitas",
            webmapTabTitleText: "Pasirinkite internetinį žemėlapį",
            btnSelectWebmapText:"Pasirinkti internetinį žemėlapį",
            layerTabTitleText: "Pasirinkti redaguojamą sluoksnį",
            selectLayerLabelText:"Sluoksnis",
            selectLayerDefaultOptionText:"Pasirinkti sluoksnį",
            detailsTabTitleText:"Išsami formos informacija",
            detailTitleLabelText: "Pavadinimas",
            detailLogoLabelText: "Logotipo paveikslėlis",
            detailDescriptionLabelText: "Aprašas",
            fieldTabFieldHeaderText: "Laukas",
            fieldTabLabelHeaderText: "Žymė",
            fieldTabTypeHeaderText: "Tipas",
            fieldTabDescriptionHeaderText: "Aprašas",
            previewApplicationText: "Peržiūrėti aplikaciją",
            saveApplicationText: "Išsaugoti aplikaciją",
            saveText: "Įrašyti",
            toggleNavigationText: "Perjungti navigaciją",
            formPlaceholderText: "Mano forma",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "GeoForm publikuojama",
            shareBuilderProgressBarMessage:"Palaukite...",
            shareBuilderTitleMessage: "Jūsų GeoForm atnaujinta ir publikuota!",
            shareBuilderTextMessage: "Galite pradėti rinkti informaciją bendrindami su kitais",
            shareDialogFormText: "Formos nuoroda",
            geoformTitleText: "Geoforma",
            layerTabText: "Tai sluoksnis, iš kurio bus sukurta GeoForm. Šis sluoksnis turi būti elementų paslauga, įgalinta redaguoti naudojant jūsų auditorijai tinkamą bendrinimo teisę.",
            detailsTabText:"Naudokite žemiau esančius formos išsamios informacijos laukus – adaptuokite pavadinimą, pridėkite adaptuotą logotipą ir pateikite trumpą aprašą auditorijai naudosiančiai GeoForm.",
            fieldsTabText:"Čia galite pasirinkti, kurie laukai bus matomi auditorijai naudosiančiai GeoForm, redaguoti jiems matomas žymes ir pridėti trumpą aprašą, kad būtų lengviau įvesti duomenis.",
            styleTabText: "Suteikite GeoForm pageidaujamą stilių, naudodami žemiau pateiktas temas.",
            publishTabText: "Jei baigėte adaptuoti GeoForm, įrašykite aplikaciją ir pradėkite bendrinti su auditorija. Visada galėsite grįžti į šią kūrimo priemonę ir toliau adaptuoti remdamiesi atsiliepimais."
        }
    })
);