define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Į_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._š",
            selectFieldsText:"Į_Select Form Fields_š",
            selectThemeText: "Pasirinkite formos temą",
            fieldLabelPlaceHolder: "Apibūdinkite šį lauką",
            fieldDescPlaceHolder: "Aprašyti šį lauką",
            webmapText: "Į_1. Webmap_š",
            layerText: "Į_2. Layer_š",
            detailsText: "Į_3. Details_š",
            fieldsText: "Į_4. Fields_š",
            styleText: "Į_5. Style_š",
            previewText: "Į_6. Preview_š",
            publishText: "Į_7. Publish_š",
            titleText: "GeoForm kūrimo priemonė",
            descriptionText: "Į_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._š",
            btnPreviousText: "Ankstesnis",
            btnNextText:"Kitas",
            webmapTabTitleText: "Pasirinkite internetinį žemėlapį",
            btnSelectWebmapText:"Pasirinkti internetinį žemėlapį",
            layerTabTitleText: "Pasirinkti redaguojamą sluoksnį",
            selectLayerLabelText:"Sluoksnis",
            selectLayerDefaultOptionText:"Pasirinkti sluoksnį",
            detailsTabTitleText:"Išsami formos informacija",
            detailTitleLabelText: "Pavadinimas",
            detailLogoLabelText: "Logotipo paveikslėlis",
            detailDescriptionLabelText: "Aprašas",
            fieldTabFieldHeaderText: "Laukas",
            fieldTabLabelHeaderText: "Žymė",
            fieldTabTypeHeaderText: "Tipas",
            fieldTabDescriptionHeaderText: "Aprašas",
            previewApplicationText: "Peržiūrėti aplikaciją",
            saveApplicationText: "Išsaugoti aplikaciją",
            saveText: "Įrašyti",
            toggleNavigationText: "Į_Toggle navigation_š",
            formPlaceholderText: "Į_My Form_š",
            imageLogoPlaceholderText: "Į_http://www.mysite.com/myimage.png_š",
            shareBuilderInProgressTitleMessage: "Į_Publishing GeoForm_š",
            shareBuilderProgressBarMessage:"Į_Please Wait..._š",
            shareBuilderTitleMessage: "Į_Your GeoForm has been updated & published!_š",
            shareBuilderTextMessage: "Į_You can start collecting information by sharing with others_š",
            shareDialogFormText: "Į_Form Link_š",
            geoformTitleText: "Į_Geo Form_š",
            layerTabText: "Į_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._š",
            detailsTabText:"Į_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._š",
            fieldsTabText:"Į_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._š",
            styleTabText: "Į_Style your GeoForm using the themes below based on your preference._š",
            publishTabText: "Į_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._š"
        }
    })
);