define(
   ({
    map: {
      error: "Į_Unable to create map_š"
    },
    onlineStatus: {
      offline: "Į_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_š.",
      reconnecting: "Į_Reconnecting&hellip;_š",
      pending: "Į_${total} pending edit(s) will be submitted when a network connection is re-established_š."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Į_My Organization_š",
          onlineLabel: "Į_ArcGIS Online_š",
          contentLabel: "Į_My Content_š",
          favoritesLabel: "Į_My Favorites_š"
        },
        title: "Į_Select Web Map_š",
        searchTitle: "Į_Search_š",
        ok: "Į_Ok_š",
        cancel: "Į_Cancel_š",
        placeholder: "Į_Enter search term_š"
      },
      groupdlg: {
        items: {
          organizationLabel: "Į_My Organization_š",
          onlineLabel: "Į_ArcGIS Online_š",
          contentLabel: "Į_My Content_š",
          favoritesLabel: "Į_My Favorites_š"
        },
        title: "Į_Select Group_š",
        searchTitle: "Į_Search_š",
        ok: "Į_Ok_š",
        cancel: "Į_Cancel_š",
        placeholder: "Į_Enter search term_š"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Į_Here is a link to a GeoForm_š"
      }
    },
    user: {
      mgrs: "Į_MGRS_š",
      usng: "Į_USNG_š",
      utm: "Į_UTM_š",
      utm_northing: "Į_Northing_š",
      utm_easting: "Į_Easting_š",
      utm_zone_number: "Į_Zone Number_š",
      selectLayerTabText: "Į_${formSection} Select Form_š",
      geoFormGeneralTabText: "Į_${formSection} Enter Information_š",
      locationInformationText: "Į_${formSection} Select Location_š",
      submitInformationText: "Į_${formSection} Complete Form_š",
      submitInstructions: "Į_Add this information to the map_š.",
      myLocationText: "Į_Current Location_š",
      locationDescriptionForMoreThanOneOption: "Į_Specify the location for this entry by clicking/tapping the map or by using one of the following options_š.",
      locationDescriptionForOneOption: "Į_Specify the location for this entry by clicking/tapping the map or by using the following option_š.",
      locationDescriptionForNoOption: "Į_Specify the location for this entry by clicking/tapping the map_š.",
      addressText: "Į_Search_š",
      geographic: "Į_Lat/Lon_š",
      locationTabText: "Į_Location_š",
      locationPopupTitle: "Į_Location_š",
      submitButtonText: "Į_Submit Entry_š",
      submitButtonTextLoading: "Į_Submitting&hellip;_š",
      formValidationMessageAlertText: "Į_The following fields are required_š:",
      selectLocation: "Į_Please select a location for your submission_š.",
      emptylatitudeAlertMessage: "Į_Please enter a ${openLink}latitude${closeLink} coordinate_š.",
      emptylongitudeAlertMessage: "Į_Please enter a ${openLink}longitude${closeLink} coordinate_š.",
      shareUserTitleMessage: "Į_Thank you for your contribution_š!",
      entrySubmitted: "Į_Your entry has been submitted to the map_š.",
      shareThisForm: "Į_Share This Form_š",
      shareUserTextMessage: "Į_Tell others to contribute using the following options_š.",
      addAttachmentFailedMessage: "Į_Unable to add attachment to layer_š",
      addFeatureFailedMessage: "Į_Unable to add feature to layer_š",
      noLayerConfiguredMessage: "Į_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_š.",
      placeholderLatitude: "Į_Latitude (Y)_š",
      placeholderLongitude: "Į_Longitude (X)_š",
      latitude: "Į_Latitude_š",
      longitude: "Į_Longitude_š",
      findMyLocation: "Į_Locate Me_š",
      finding: "Į_Locating&hellip;_š",
      backToTop: "Į_Back to top_š",
      addressSearchText: "Į_Your submission will appear here. You can drag the pin to correct the location_š.",
      shareModalFormText: "Į_Form Link_š",
      close: "Į_Close_š",
      locationNotFound: "Į_Location could not be found_š.",
      setLocation: "Į_Set Location_š",
      find: "Į_Find address or place_š",
      attachment: "Į_Attachment_š",
      toggleDropdown: "Į_Toggle Dropdown_š",
      invalidString: "Į_Please enter valid value_š.",
      invalidSmallNumber: "Į_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_š.",
      invalidNumber: "Į_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_š.",
      invalidFloat: "Į_Please enter valid ${openStrong}floating point${closeStrong} value_š.",
      invalidDouble: "Į_Please enter valid ${openStrong}double${closeStrong} value_š.",
      invalidLatLong: "Į_Please enter valid latitude and longitude coordinates_š.",
      invalidUTM: "Į_Please enter valid UTM coordinates_š.",
      invalidUSNG: "Į_Please enter valid USNG coordinates_š.",
      invalidMGRS: "Į_Please enter valid MGRS coordinates_š.",
      geoformTitleText: "Į_GeoForm_š",
      domainDefaultText: "Į_Select&hellip;_š",
      applyEditsFailedMessage: "Į_Sorry your entry cannot be submitted. Please try again_š.",
      requiredFields: "Į_There are some errors. Please correct them below_š.",
      requiredField: "Į_(required)_š",
      error: "Į_Error_š",
      textRangeHintMessage: "Į_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_š",
      dateRangeHintMessage: "Į_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_š",
      remainingCharactersHintMessage: "Į_${value} characters remaining_š",
      mapFullScreen: "Į_Full Screen_š",
      mapRestore: "Į_Restore_š",
      filterSelectEmptyText: "Į_Select_š",
      invalidLayerMessage: "Į_Form layer does not exist. Please configure the application and set the layer_š.",
      selectedLayerText: "Į_All_š",
      fileUploadStatus: "Į_File Upload Status_š",
      uploadingBadge: "Į_&nbsp;Uploading&hellip;_š",
      successBadge: "Į_&nbsp;Uploaded_š",
      retryBadge: "Į_Retry_š",
      errorBadge: "Į_Error uploading&nbsp;&nbsp;&nbsp;_š",
      fileTooLargeError: "Į_File too large to attach_š",
      exceededFileCountError: "Į_Exceeded maximum no. of attachments allowed_š",
      selectFileTitle: "Į_Select a file_š",
      btnViewSubmissions: "Į_View Submissions_š",
      dateFormat: "Į_MM/DD/YYYY h:mm a_š"
    },
    builder: {
      invalidUser: "Į_Sorry, you don't have permission to view this item_š",
      invalidWebmapSelectionAlert: "Į_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_š.",
      invalidWebmapSelectionAlert2: "Į_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_š",
      selectFieldsText: "Į_Select Form Fields_š",
      selectThemeText: "Į_Select Form Theme_š",
      webmapText: "Į_Webmap_š",
      layerText: "Į_Layer_š",
      detailsText: "Į_Details_š",
      fieldsText: "Į_Fields_š",
      styleText: "Į_Style_š",
      optionText: "Į_Options_š",
      previewText: "Į_Preview_š",
      publishText: "Į_Publish_š",
      optionsApplicationText: "Į_Options_š",
      titleText: "Į_Builder_š",
      descriptionText: "Į_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_š.",
      btnPreviousText: "Į_Previous_š",
      btnNextText: "Į_Next_š",
      webmapTabTitleText: "Į_Select a Webmap_š",
      viewWebmap: "Į_View webmap_š",
      webmapDetailsText: "Į_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_š",
      btnSelectWebmapText: "Į_Choose Webmap_š",
      btnSelectWebmapTextLoading: "Į_Loading&hellip;_š",
      layerTabTitleText: "Į_Select Editable Layer_š",
      selectLayerLabelText: "Į_Layer_š",
      selectLayerDefaultOptionText: "Į_Select Layer_š",
      defaultBasemap: "Į_Basemap Toggle_š",
      secondaryBasemap: "Į_Default Basemap_š",
      detailsTabTitleText: "Į_Form Details_š",
      detailTitleLabelText: "Į_Title_š",
      detailLogoLabelText: "Į_Logo Image_š",
      descriptionLabelText: "Į_Form Instructions & Details_š",
      fieldDescriptionLabelText: "Į_Help Text (optional)_š",
      fieldTabFieldHeaderText: "Į_Field_š",
      fieldTabLabelHeaderText: "Į_Label_š",
      fieldTabDisplayTypeHeaderText: "Į_Display As_š",
      fieldTabOrderColumnText: "Į_Order_š",
      fieldTabVisibleColumnText: "Į_Enabled_š",
      displayFieldText: "Į_Display Field_š",
      selectMenuOption: "Į_Select Menu_š",
      selectRadioOption: "Į_Radio Button_š",
      selectTextOption: "Į_Text_š",
      selectDateOption: "Į_Date Picker_š",
      selectRangeOption: "Į_Touch-Spinner_š",
      selectCheckboxOption: "Į_Checkbox_š",
      selectMailOption: "Į_Email_š",
      selectUrlOption: "Į_URL_š",
      selectTextAreaOption: "Į_Text Area_š",
      previewApplicationText: "Į_Preview Application_š",
      saveApplicationText: "Į_Save Application_š",
      saveText: "Į_Save_š",
      toggleNavigationText: "Į_Toggle navigation_š",
      formPlaceholderText: "Į_My Form_š",
      shareBuilderInProgressTitleMessage: "Į_Publishing GeoForm_š",
      shareBuilderProgressBarMessage: "Į_Please Wait&hellip;_š",
      shareBuilderTitleMessage: "Į_Success! Item saved_š",
      shareBuilderTextMessage: "Į_You can start collecting information by sharing with others_š",
      shareModalFormText: "Į_Form Link_š",
      shareBuilderSuccess: "Į_Your GeoForm has been updated & published_š!",
      geoformTitleText: "Į_Geo Form_š",
      layerTabText: "Į_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_š.",
      detailsTabText: "Į_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_š.",
      fieldsTabText: "Į_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_š.",
      styleTabText: "Į_Style your GeoForm using the themes below based on your preference_š.",
      publishTabText: "Į_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_š.",
      headerSizeLabel: "Į_Header Size_š",
      smallHeader: "Į_Use Small Header_š",
      bigHeader: "Į_Use Large Header_š",
      pushpinText: "Į_Push pin_š",
      doneButtonText: "Į_Save and Exit_š",
      fieldTabPlaceHolderHeaderText: "Į_Hint (optional)_š",
      enableAttachmentLabelText: "Į_${openStrong}Enable Attachments${closeStrong}_š",
      enableAttachmentLabelHint: "Į_You can enable/disable the attachments here_š",
      attachmentIsRequiredLabelText: "Į_${openStrong}Attachment Required${closeStrong}_š",
      attachmentIsRequiredLabelHint: "Į_If necessary, users can be required to enter an attachment_š.",
      attachmentLabelText: "Į_Attachment Button Label_š",
      attachmentLabelHint: "Į_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_š",
      attachmentDescription: "Į_Attachment Description_š",
      attachmentHint: "Į_If necessary, you can provide additional attachment instructions here_š.",
      jumbotronDescription: "Į_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_š",
      shareGeoformText: "Į_Share Geoform_š",
      shareDescription: "Į_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_š.",
      defaultMapExtent: "Į_Default Map Extent_š",
      defaultMapExtentDescription: "Į_The map will reset to the default extent in your web map after submission - this can be disabled at any time_š.",
      pushpinOptionsDescription: "Į_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_š",
      selectLocationText: "Į_Select Location By_š",
      myLocationText: "Į_My Location_š",
      searchText: "Į_Search_š",
      coordinatesText: "Į_Latitude & Longitude Coordinates_š",
      usng: "Į_USNG Coordinates_š",
      mgrs: "Į_MGRS Coordinates_š",
      utm: "Į_UTM Coordinates_š",
      selectLocationSDescription: "Į_Allow users to select a location using these methods_š.",
      dragTooltipText: "Į_Drag the field where you want it to appear_š",
      showHideLayerText: "Į_Show Layer_š",
      showHideLayerHelpText: "Į_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_š.",
      labelHelpMessage: "Į_Label_š",
      placeHolderHintMessage: "Į_Hint Text_š",
      placeHolderHelpMessage: "Į_Help Text_š",
      selectTextOptionValue: "Į_Filter Select_š",
      disableLogo: "Į_Disable Logo_š",
      disableLogoDescription: "Į_You can configure the GeoForm to Show/Hide the Logo in the form header_š",
      locateOnLoadText: "Į_Locate On Load_š",
      locateOnLoadDescription: "Į_You can configure the GeoForm to use the current location on page load_š",
      selectLayerFieldTabText: "Į_Select Layer_š",
      allLayerSelectOptionText: "Į_All_š",
      disableViewer: "Į_Disable Viewer_š",
      disableViewerDescription: "Į_You can configure the GeoForm to disable/enable Viewer_š",
      displayFieldHintText: "Į_Selected display field will be shown in viewerMode as title field_š"
    },
    viewer: {
      geocoderCancelText: "Į_Cancel_š",
      viewReportsTabText: "Į_Submissions_š",
      viewLegendTabText: "Į_Legend_š",
      viewAboutusTabText: "Į_About_š",
      viewMapTabText: "Į_Map_š",
      sortHeaderText: "Į_Sort By_š:",
      btnSubmitReportText: "Į_Submit a Report_š",
      geocoderPlaceholderText: "Į_Zip Code, city, etc_š.",
      noSearchResult: "Į_No result found_š",
      recordsTabTooltip: "Į_View Submissions_š",
      legendTabTooltip: "Į_Legend_š",
      aboutUsTabTooltip: "Į_AboutUs_š",
      mapTabTooltip: "Į_Map_š",
      appLoadingFailedMessage: "Į_ViewerMode is Unavailable_š",
      btnDescendingText: "Į_Desc_š",
      btnAscendingText: "Į_Asc_š",
      geometryUnavailableErrorMessage: "Į_Unable to find the geometry of the feature_š",
      infoPopupOffErrorMessage: "Į_InfoPopup is off_š",
      btnLoadMoreText: "Į_Load More_š",
      unavailableTitleText: "Į_Untitled_š",
      unavailableConfigMessage: "Į_Unable to load config_š"
    }
  })
);