define(
     ({
        map: {
            error: "Žemėlapio sukurti nepavyko"
        },
        onlineStatus: {
            offline: "Dabar dirbate atsijungę. Kol bus užmegztas ryšys su serveriu, formų turinys bus saugomas lokaliai.",
            reconnecting: "Prisijungiama iš naujo&hellip;",
            pending: "Atkūrus tinklo ryšį, bus pateikta laukiančių pakeitimų: ${total}."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organizacija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Turinys",
                    favoritesLabel: "Mėgstamiausi"
                },
                title: "Pasirinkite internetinį žemėlapį",
                searchTitle: "Ieškoti",
                ok: "Gerai",
                cancel: "Atšaukti",
                placeholder: "Įveskite paieškos terminą"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organizacija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Turinys",
                    favoritesLabel: "Mėgstamiausi"
                },
                title: "Pasirinkti grupę",
                searchTitle: "Ieškoti",
                ok: "Gerai",
                cancel: "Atšaukti",
                placeholder: "Įveskite paieškos terminą"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Į_Here is a link to a GeoForm_š"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Ilgumos poslinkis",
            utm_easting: "Platumos poslinkis",
            utm_zone_number: "Zonos numeris",
            geoFormGeneralTabText: "1. Įveskite informaciją",
            locationInformationText: "2. Pasirinkite vietą",
            submitInformationText: "3. Užpildykite formą",
            submitInstructions: "Įtraukite šią informaciją į žemėlapį.",
            myLocationText: "dabartinė vieta",
            locationDescriptionForMoreThanOneOption: "Į_Specify the location for this entry by clicking/tapping the map or by using one of the following options_š.",
            locationDescriptionForOneOption: "Į_Specify the location for this entry by clicking/tapping the map or by using the following option_š.",
            locationDescriptionForNoOption: "Į_Specify the location for this entry by clicking/tapping the map_š.",
            addressText: "Ieškoti",
            geographic: "Platuma / ilguma",
            locationTabText: "Vieta",
            locationPopupTitle: "Vieta",
            submitButtonText: "Pateikite įrašą",
            submitButtonTextLoading: "Pateikiama&hellip;",
            formValidationMessageAlertText: "Šie laukai privalomi:",
            selectLocation: "Į_Please select a location for your submission_š.",
            emptylatitudeAlertMessage: "Įveskite ${openLink}platumos${closeLink} koordinatę.",
            emptylongitudeAlertMessage: "Įveskite ${openLink}ilgumos${closeLink} koordinatę.",
            shareUserTitleMessage: "Dėkojame už prisidėjimą!",
            entrySubmitted: "Įrašas pateiktas žemėlapiui.",
            shareThisForm: "Bendrinkite šią formą",
            shareUserTextMessage: "Paskatinkite kitus prisidėti naudojant šias parinktis.",
            addAttachmentFailedMessage: "Prie sluoksnio pridėti priedo nepavyko",
            addFeatureFailedMessage: "Į sluoksnį elemento pridėti nepavyko",
            noLayerConfiguredMessage: "Į_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_š.",
            placeholderLatitude: "Platuma (Y)",
            placeholderLongitude: "Ilguma (X)",
            latitude: "Platuma",
            longitude: "Ilguma",
            findMyLocation: "Rasti mane",
            finding: "Randama&hellip;",
            backToTop: "Atgal į viršų",
            addressSearchText: "Čia bus rodomas jūsų pateikimas. Norėdami pataisyti vietą, vilkite smeigtuką.",
            shareModalFormText: "Formos nuoroda",
            close: "Užverti",
            locationNotFound: "Vietos surasti nepavyko.",
            setLocation: "Nustatyti vietą",
            find: "Surasti adresą arba vietą",
            attachment: "Priedas",
            toggleDropdown: "Perjungti išskleidimą",
            invalidString: "Į_Please enter valid value_š.",
            invalidSmallNumber: "Į_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_š.",
            invalidNumber: "Į_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_š.",
            invalidFloat: "Į_Please enter valid ${openStrong}floating point${closeStrong} value_š.",
            invalidDouble: "Į_Please enter valid ${openStrong}double${closeStrong} value_š.",
            invalidLatLong: "Į_Please enter valid latitude and longitude coordinates_š.",
            invalidUTM: "Į_Please enter valid UTM coordinates_š.",
            invalidUSNG: "Į_Please enter valid USNG coordinates_š.",
            invalidMGRS: "Į_Please enter valid MGRS coordinates_š.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Pasirinkti&hellip;",
            applyEditsFailedMessage: "Atsiprašome, tačiau įrašo pateikti nepavyko. Bandykite dar kartą.",
            requiredFields: "Yra kelios klaidos. Ištaisykite jas toliau.",
            requiredField: "(privalomas)",
            error: "Klaida",
            textRangeHintMessage: "${openStrong}Užuomina:${closeStrong} minimali vertė ${minValue} ir maksimali vertė ${maxValue}",
            dateRangeHintMessage: "${openStrong}Užuomina:${closeStrong} minimali data ${minValue} ir maksimali data ${maxValue}",
            remainingCharactersHintMessage: "Į_${value} characters remaining_š"
        },
        builder: {
            invalidUser: "Atsiprašome, tačiau neturite teisės peržiūrėti šį elementą",
            invalidWebmapSelectionAlert: "Pasirinktame internetiniame žemėlapyje nėra tinkamo naudoti sluoksnio. Norėdami tęsti, į internetinį žemėlapį pridėkite redaguojamą FeatureLayer.",
            invalidWebmapSelectionAlert2: "Norėdami gauti daugiau informacijos, žr. ${openLink}Kas yra elementų paslauga?${closeLink}",
            selectFieldsText: "Pasirinkite formos laukus",
            selectThemeText: "Pasirinkite formos temą",
            webmapText: "Internetinis žemėlapis",
            layerText: "Sluoksnis",
            detailsText: "Išsamiau",
            fieldsText: "Laukai",
            styleText: "Stilius",
            optionText: "Parinktys",
            previewText: "Peržiūra",
            publishText: "Publikuoti",
            optionsApplicationText: "Parinktys",
            titleText: "Kūrimo priemonė",
            descriptionText: "Į_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_š.",
            btnPreviousText: "Ankstesnis",
            btnNextText: "Kitas",
            webmapTabTitleText: "Pasirinkite internetinį žemėlapį",
            viewWebmap: "Žiūrėti internetinį žemėlapį",
            webmapDetailsText: "Į_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_š",
            btnSelectWebmapText: "Pasirinkite internetinį žemėlapį",
            btnSelectWebmapTextLoading: "Įkeliama&hellip;",
            layerTabTitleText: "Pasirinkti redaguojamą sluoksnį",
            selectLayerLabelText: "Sluoksnis",
            selectLayerDefaultOptionText: "Pasirinkti sluoksnį",
            detailsTabTitleText: "Išsami formos informacija",
            detailTitleLabelText: "Pavadinimas",
            detailLogoLabelText: "Logotipo paveikslėlis",
            descriptionLabelText: "Į_Form Instructions & Details_š",
            fieldDescriptionLabelText: "Į_Help Text (optional)_š",
            fieldTabFieldHeaderText: "Laukas",
            fieldTabLabelHeaderText: "Žymė",
            fieldTabDisplayTypeHeaderText: "Rodyti kaip",
            fieldTabOrderColumnText: "Į_Order_š",
            fieldTabVisibleColumnText: "Į_Enabled_š",
            selectMenuOption: "Pasirinkimo meniu",
            selectRadioOption: "Akutė",
            selectTextOption: "Tekstas",
            selectDateOption: "Į_Date Picker_š",
            selectRangeOption: "Į_Touch-Spinner_š",
            selectCheckboxOption: "Žymimasis langelis",
            selectMailOption: "El. paštas",
            selectUrlOption: "URL",
            selectTextAreaOption: "Į_Text Area_š",
            previewApplicationText: "Peržiūrėti aplikaciją",
            saveApplicationText: "Išsaugoti aplikaciją",
            saveText: "Įrašyti",
            toggleNavigationText: "Perjungti navigaciją",
            formPlaceholderText: "Mano forma",
            shareBuilderInProgressTitleMessage: "GeoForm publikuojama",
            shareBuilderProgressBarMessage: "Palaukite&hellip;",
            shareBuilderTitleMessage: "Pavyko! Elementas įrašytas",
            shareBuilderTextMessage: "Galite pradėti rinkti informaciją bendrindami su kitais",
            shareModalFormText: "Formos nuoroda",
            shareBuilderSuccess: "Jūsų GeoForm atnaujinta ir publikuota!",
            geoformTitleText: "Geoforma",
            layerTabText: "Tai sluoksnis, iš kurio bus sukurta GeoForm. Šis sluoksnis turi būti elementų paslauga, įgalinta redaguoti naudojant jūsų auditorijai tinkamą bendrinimo teisę.",
            detailsTabText: "Naudokite žemiau esančius formos išsamios informacijos laukus – adaptuokite pavadinimą, pridėkite adaptuotą logotipą ir pateikite trumpą aprašą auditorijai naudosiančiai GeoForm. Aprašyme galite pridėti nuorodų į kitus šaltinius, kontaktinę informaciją ir netgi nukreipti auditoriją į interneto žemėlapių aplikaciją, kurioje yra publikuojami duomenys, surinkti naudojant GeoForm.",
            fieldsTabText: "Čia galite pasirinkti, kurie laukai bus matomi auditorijai naudosiančiai GeoForm, redaguoti jiems matomas žymes ir pridėti trumpą aprašą, kad būtų lengviau įvesti duomenis.",
            styleTabText: "Suteikite GeoForm pageidaujamą stilių, naudodami žemiau pateiktas temas.",
            publishTabText: "Jei baigėte adaptuoti GeoForm, įrašykite aplikaciją ir pradėkite bendrinti su auditorija. Visada galėsite grįžti į šią kūrimo priemonę ir toliau adaptuoti remdamiesi atsiliepimais.",
            headerSizeLabel:"Į_Header Size_š",
            smallHeader: "Naudoti mažą antraštę",
            bigHeader: "Į_Use Large Header_š",
            pushpinText: "Smeigtukas",
            doneButtonText: "Į_Save and Exit_š",
            fieldTabPlaceHolderHeaderText: "Užuomina (nebūtina)",
            enableAttachmentLabelText: "Į_${openStrong}Enable Attachments${closeStrong}_š",
            enableAttachmentLabelHint: "Į_You can enable/disable the attachments here_š",
            attachmentIsRequiredLabelText: "Į_${openStrong}Attachment Required${closeStrong}_š",
            attachmentIsRequiredLabelHint: "Į_If necessary, users can be required to enter an attachment_š.",
            attachmentLabelText: "Į_Attachment Button Label_š",
            attachmentLabelHint: "Į_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_š",
            attachmentDescription: "Priedo aprašymas",
            attachmentHint: "Jeigu reikia, papildomas pridėjimo instrukcijas galite pateikti čia.",
            jumbotronDescription: "Į_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_š",
            shareGeoformText: "Bendrinti Geoform",
            shareDescription: "Atlikę pateikimą, bendrinimo skydelyje jūsų auditorija gali lengvai bendrinti GeoForm su kitais bendradarbiais. Šią funkciją galima bet kada išjungti.",
            defaultMapExtent: "Numatyta žemėlapio aprėptis",
            defaultMapExtentDescription: "Pateikus, internetiniame žemėlapyje bus nustatyta numatyta žemėlapio aprėptis. Tai galima bet kada išjungti.",
            pushpinOptionsDescription: "Žemėlapio smeigtuką rinkitės iš įvairių spalvų – jis turi išsiskirti iš žemėlapio simbolių, kad vartotojas galėtų padėti žemėlapyje savo pateiktį",
            selectLocationText: "Pasirinkite vietą pagal",
            myLocationText: "Mano vieta",
            searchText: "Ieškoti",
            coordinatesText: "Platumos ir ilgumos koordinatės",
            usng: "USNG koordinatės",
            mgrs: "MGRS koordinatės",
            utm: "UTM koordinatės",
            selectLocationSDescription: "Vartotojai gali pasirinkti vietą šiais būdais.",
            dragTooltipText:"Į_Drag the field where you want it to appear_š",
            showHideLayerText:"Į_Show/Hide Layer_š",
            showHideLayerHelpText:"Į_You can configure the GeoForm to Show/Hide Layer_š"
        }
    })
);