define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Ievadiet attālumu",
                    "layerName": "Ievadiet slāņa nosaukumu šeit"
                },
                "message": {
                    "analysisFailed": "Analīze neizdevās.",
                    "errorOccurred": "Radās kāda kļūda.",
                    "layerAdded": "Slānis sekmīgi pievienots. ",
                    "enrichLayerNameError": "Rezultātu slāņa nosaukums nedrīkst saturēt nederīgas rakstzīmes" + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Izveido servisu.. ",
                    "starting": "Startē",
                    "performingAnalysis": "Veic analīzi..",
                    "checkLayerName": "Pārbauda slāņa nosaukumu.. ",
                    "addingLayer": "Slāņa pievienošana tīmekļa kartē ",
                    "layerNameExist": "Slāņa nosaukums jau pastāv.",
                    "clickOnSave": " Noklikšķiniet uz pogas Saglabāt, lai pārlādētu lietotni.",
                    "clickOnOk": " Noklikšķiniet uz pogas Labi, lai mēģinātu vēlreiz.",
                    "enterNumbersOnly": "Ievadītās vērtības nav derīgas",
                    "nofeatures": "Pašreizējā pārklājumā nav neviena elementa",
                    "selectData": "Izvēlieties datus slāņa bagātināšanai.",
                    "resetVariableMessage": "Vai tiešām vēlaties atiestatīt mainīgo?",
                    "emptyTextFieldLayerName": "Ievadiet rezultātu slāņa nosaukumu",
                    "createService":"Slānis nav izveidots.",
                    "sharingLayer":"Kopīgo slāni..",
                    "updateItemFailed": "Neizdevās atjaunināt. Lūdzu, mēģiniet vēlreiz.",
                    "geoEnrichFailed": "Neizdevās bagātināt slāni. Lūdzu, mēģiniet vēlreiz.",
                    "shareFailed": "Neizdevās kopīgot bagātināto slāni. Lūdzu, mēģiniet vēlreiz.",
                    "refreshServiceFailed": "Neizdevās atjaunināt slāni. Lūdzu, mēģiniet vēlreiz.",
                    "layerJsonFailed": "Neizdevās slānim izveidot JSON. Lūdzu, mēģiniet vēlreiz.",
                    "addToWebmapFailed": "Neizdevās pievienot slāni tīmekļa kartē. Lūdzu, mēģiniet vēlreiz.",
                    "bufferAreaHelpText": "Ievadiet vērtību, mazāku nekā ",
                    "invalidBufferInput": "Ievadītā vērtība nav derīga.",
                    "emptyBufferInput": "Lūdzu, ievadiet derīgu vērtību."
                },
                "populationText": "Apdzīvotība",
                "housingText": "Mājsaimniecība",
                "businessText": "Uzņēmums",
                "variableListText": " mainīgie ir uzskaitīti šeit:",
                "countrySelectTitle": "1. Izvēlieties datu izvietojumu",
                "unitedStates": "Amerikas Savienotās valstis",
                "global": "Globāls",
                "geoenrichDialogText": "Ģeobagātināšanas mainīgie",
                "viewVariablestext": "Skatīt mainīgos",
                "backButtonText":"Atpakaļ",
                "customizeVariables": "Pielāgot mainīgos",
                "resetVariables": "Atiestatīt",
                "defineAreaTitle": "3. Definējiet bagātināmo zonu",
                "currentMapExtent": "Lieto pašreizējo kartes pārklājumu",
                "enrichLayerName": "4. Rezultātu slāņa nosaukums",
                "lineDistanceText": "Līnijas attālums",
                "drivingTime": "Braukšanas laiks",
                "enrichButtonText": "Bagātināt slāni",
                "selectDataText": "2. Izvēlieties datus",
                "showCreditsText": "Rādīt kredītus",
                "variableCount": "Mainīgo kopskaits ",
                "totalRecords": "Ierakstu kopskaits:",
                "cost": "Izmaksas:",
                "showCreditsDialogText": "Rādīt kredītus",
                "nextButtonText": "Tālāk",
                "prevButtonText": "Atpakaļ",
                "saveButtonText": "Saglabāt",
                "ok": "Labi"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 