define({
    root: ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Atvērt veidotāju",
                "exitBuilderButtonText": "Aizvērt veidotāju",
                "enterBuilderModeHelpText": "Atvērt veidotāja režīmu, lai konfigurētu aplikāciju",
                "builderModeHelpText": "Šablonu veidotāja režīms",
                "webmapCaption": "Karte",
                "selectMapMessage": "Pašreiz ${displaying} <b>${webmapTitle}</b><br/>Noklikšķiniet uz Atlasīt karti, lai izvēlētos citu web karti.",
                "loadMapMessage": "Pašreiz atlasīts <b>${webmapTitle}</b><br/>Noklikšķiniet uz Saglabāt, lai izmantotu šo web karti.",
                "changeWebmap": "Atlasīt karti",
                "saveButtonText": "Saglabāt",
                "webmapNextButtonText": "Tālāk ->",
                "previousButtonText":"Iepriekšējais",
                "layerLabelText": "Slānis",
                "noLayerFoundText": "Nav atrasts neviens slānis",
                "selectLayer": "Atlasīt slāni",
                "applicationSettingText": "Aplikācijas iestatījumi",
                "summaryAttrAscendingOrderTooltip": "Pieaugošs",
                "onStartLabel": "Sākot",
                "selectVariableText": "Atlasīt mainīgo",
                "selectVariableDropdown": "Atlasīt mainīgo",
                "label":"Kartes teksts",
                "sourceLinkText":"Avota saite",
                "selectSubVariableText":"Atlasīt papildu mainīgos",
                "subVariablePanelButtonText":"Pabeigts",
                "onButtonLabel":"Ieslēgt",
                "offButtonLabel":"Izslēgt",
                "appSettingsSaveCloseButtonText": "Saglabāt un aizvērt",
                "appSettingsTitleText":"Aplikācijas nosaukums",
                "appSettingsDescriptionText": "Aplikācijas apraksts",
                "appSetingsRendererAreaText":"Renderēts apgabals",
                "shareText":"Koplietot",
                "popupText": "Uznirstošais logs",
                "basemapText":"Pamatkarte",
                "cancel": "Atcelt",
                "theme": "Tēma",
                "zoomLevel": "Mērogmaiņas līmenis",
                "existingValue": "Lietot esošās vērtības",
                "enrichLayer": "Bagātināt slāni",
                "imageLabel": "Kā tas darbojas?",
                "clearData": "Notīrīt datus",
                "basemapSelectionText":"Pamatkartes atlasīšana",
                "secondaryBasemapText":"Sekundārā pamatkarte",
                "defaultBasemapText": "Noklusējuma pamatkarte",
                "entireAreaButton": "Viss laukums",
                "entireAreaOnStartButton": "Viss laukums sākot",
                "aboutPanel": "Par paneli",
                "legendPanel": "Leģendu panelis",
                "layersPanel": "Slāņu panelis",
                "dataConfigurationButtonText": "Datu konfigurācija",
                "savingChangesMessage": "Izmaiņu saglabāšana...",
                "nextButtonText": "Tālāk",
                "prevButtonText": "Iepriekšējais",
                "enterLabelText": "Ievadīt kartes aprakstu",
                "SelectedFeatureText": "Atlasītais elements",
                "layerHelpTextMessage": "Šai aplikācijai nepieciešams slānis ar ciparu laukiem",
                "alertMessage": {
                    "resetVariableMessage": "Vai tiešām vēlaties atiestatīt mainīgo?",
                    "emptyAppTitleMessage": "Aplikācijas nosaukums nevar būt tukšs",
                    "emptyDescriptionMessage": "Apraksts nevar būt tukšs",
                    "maxVariableSelection": "Nevarat atlasīt vairāk par 25 papildu mainīgajiem",
                    "signInFail" : "Pierakstīšanās neizdevās",
                    "itemUpdateMessage": "Vienība atjaunināta",
                    "unsavedChangesMessage": "Nesaglabātās izmaiņas",
                    "failMessage": "Nevarēja veiksmīgi atjaunināt vienību",
                    "saveChangesAlert": "Vai vēlaties saglabāt izmaiņas?",
                    "variableLabelValidation": "Mainīgais kartes apraksts nevar būt tukšs",
                    "subVariableLabelValidation": "Papildu mainīgais kartes apraksts nevar būt tukšs"
                    }
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});