define(
	 ({
		header: {
			start: "aloita",
			searchStories: "Hae tarinoitasi...",
			filter: "Suodata",
			sort: "Lajittele",
			sortColon: "Lajittele:",
			numResults: "Tulokset: {{NUM_RESULTS}}",
			sortBy: "Lajitteluperuste",
			dateModified: "Muokkauspäivämäärä",
			title: "Otsikko",
			type: "Tapahtui virhe",
			views: "Katselukerrat",
			errors: "Virheet",
			filterBy: "Suodatusperuste",
			filterItems: "Suodata kohteita",
			apps: "Sovellukset",
			sharing: "Jakaminen",
			clearAll: "Tyhjennä kaikki",
			clearSearch: "Tyhjentää haun",
			logOut: "Kirjaudu ulos",
			mainQuote: "Tarinankerronta on tehokkain tapa kertoa ideoista maailmalle nykyaikaisin keinoin.",
			quoteSource: "Robert McKee",
			checkYourStories: "Tarkista tarinat",
			createStory: "Luo tarina",
			totalStories: "Tarinoita yhteensä: {{NUM_STORIES}}",
			noIssues: "Kaikki hyvin",
			userStories: "Käyttäjän {{USER_NAME}} tarinat",
			headerDisabledTooltip: "Odota, kunnes olemme korjanneet ongelman...",
			notOnTouch: "Ei käytettävissä kosketuslaitteilla",
		},
		deleteModal: {
			title: "Vahvista poisto",
			warningText: "Haluatko varmasti poistaa tämän tarinan? Et voi palauttaa sitä.",
			deleteText: "Poista",
			cancel: "Peruuta"
		},
		loading: {
			loadingText: "Ladataan tarinoitasi..."
		},
		cantFindStories: {
			whereAreStories: "Etkö näe tarinaasi?",
			notSeeExplanation: "Omat tarinat -luettelossa näkyvät vain kartat, joita isännöidään ArcGISissa ja jotka on luotu sovelluksella {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} tai {{SWIPE_SPYGLASS}}. Lisätietoja on kohdassa {{FAQ}}.",
			faq: "Usein kysytyt kysymykset",
			followingStoriesToUpdate: "Seuraavat tarinat, jotka on luotu sovellusten aiemmilla versioilla, on päivitettävä, jotta ne näkyvät Omat tarinat -luettelossa:",
			gettingStories: "Etsitään tarinoita, jotka on luotu sovellusten aiemmilla versioilla ja jotka on päivitettävä...",
			title: "Otsikko",
			typeOfStoryMap: "Tapahtui virhe",
			lastModified: "Viimeksi muokattu",
			allUpToDate: "Yhtään päivitettävää, sovellusten aiemmilla versioilla luotua tarinaa ei löytynyt.",
			updateAll: "Päivitä kaikki",
			errorScanningForStories: "Tarinoiden haussa tapahtui virhe.",
			close: "Tallennettu",
			updates: "Päivitykset",
			updatingNumberOfNumber: "Päivitetään {{CURRENT_NUMBER}}/{{TOTAL}}",
			updatingNumberOfNumberAlt: "Päivitetään {{CURRENT_NUMBER}}/{{TOTAL}}",
			updateSucceeded: "Päivitys onnistui.",
			reloadingStories: "Ladataan tarinoita uudelleen...",
			errorUpdatingStories: "Tarinoiden päivityksessä tapahtui virhe.",
			partialUpdateMessage: "Tarinat on päivitetty: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "Kirjaudu Tarinakartat-sovellukseen",
			signInTo: "Kirjaudu sisään olemassa olevalla ArcGIS Online -tililläsi, kun haluat",
			explanationOne: "Luo karttapohjaisia tarinakarttoja tarinoittesi kertomiseen.",
			explanationTwo: "Käytä ArcGIS Onlinen karttoja ja aineistoa tarinakartoissasi.",
			explanationThree: "Hallitse tarinakarttojasi ja tarkista niiden sisältö.",
			dontHaveAccount: "Eikö sinulla ole ArcGIS Online -tiliä? Rekisteröidy:",
			publicAccount: "Ilmainen, muu kuin kaupallinen julkinen tili",
			orgAccount: "Ilmainen ArcGIS-kokeilutilaus",
			timeExpired: "Sisäänkirjautumisesi on vanhentunut. Kirjaudu sisään uudelleen jatkaaksesi siitä, mihin jäit.",
			apiDidntLoad: "Jokin ei lataudu oikein. Kokeile sivun päivitystä.",
			needAccount: "Tarvitsetko tilin?",
			letsGo: "Aloitetaan!"
		},
		sharingLevel: {
			publicMessage: "Julkinen",
			privateMessage: "Yksityinen",
			organization: "Organisaatio",
			changedSharing: "Jakamistasoa on muutettu.",
			unableToChange: "Jakamista ei voi muuttaa.",
			partOfMap: "Tämä kohde sijaitsee kartassa. Jos haluat muuttaa kohteen jakamistasoa, sinun on muutettava kartan jakamistasoa.",
			storyPublicContentOrg: "Tarinasi on julkinen, joten sen sisältöä ei voi jakaa vain organisaation kanssa",
			storyPublicContentPrivate: "Tarinasi on julkinen, joten sen sisältö ei voi olla yksityistä",
			mapOrg: "Kartan jakaminen organisaatiollesi katkaisee tarinasi",
			layerOrg: "Karttatason jakaminen organisaatiollesi katkaisee tarinasi",
			mapPrivate: "Kartan määrittäminen yksityiseksi katkaisee tarinasi",
			layerPrivate: "Karttatason määrittäminen yksityiseksi katkaisee tarinasi"
		},
		collectionList: {
			advocacy: "Edunvalvonta ja aktiivinen palvelutarjonta",
			architecture: "Arkkitehtuuri ja suunnittelu",
			conservation: "Luonnonsuojelu ja kestävä kehitys",
			culture: "Kulttuuri",
			destinations: "Kohteet ja turismi",
			disasters: "Katastrofit ja niistä toipuminen",
			economy: "Talous ja kehitys",
			entertainment: "Viihde",
			history: "Historia",
			infrastructure: "Infrastruktuuri",
			marketing: "Markkinointi",
			nature: "Luonto ja ympäristö",
			news: "Uutiset ja tapahtumat",
			oceans: "Oceans",
			parks: "Puistot ja virkistysalueet",
			people: "Ihmiset ja yhteiskunta",
			planning: "Suunnittelu ja analysointi",
			publicArt: "Julkinen taide",
			science: "Luonnontieteet ja tekniikka",
			sport: "Urheilu",
			travelogues: "Matkakertomukset"
		},
		types: {
			custom: "Virhe yhteyden muodostuksessa taustakarttapalveluun. Varmista, että SSL (HTTPS) -suojaus on käytössä palvelussa. Mahdolliset lisätiedot näkyvät alla.",
			notSpecified: "Tyyppiä ei ole määritetty"
		},
		storyMap: {
			shared: "Jaettu",
			saveFailed: "Virhe tallennettaessa",
			numViews: "Näkymät: {{NUM_VIEWS}}",
			editStory: "Muokkaa tarinaa",
			viewLive: "Näytä tarina",
			preview: "Esikatselu",
			deleteButton: "Poista",
			modified: "Muokattu: {{DATE}}",
			summary: "Yhteenveto",
			loading: "Ladataan...",
			collapse: "kutista",
			close: "sulje",
			hide: "piilota",
			notAvailableWhenBroken: "Tarinassasi on alla luetellut ongelmat",
			cantBeDeleted: "Poistosuojaus on käytössä tässä tarinassa. Jos haluat poistaa suojauksen käytöstä, siirry tarinan kohdesivulle ArcGISissa.",
			shareDialog: {
				title: "Jaa tarinasi kaikkien kanssa.",
				notPublicWarning: "Tarinasi on jaettu organisaation kanssa. Vain organisaation jäsenet voivat katsella sitä.",
				embedStory: "Upota tarinasi",
				shortLink: "Lyhyt linkki",
				hideHeaderBar: "Piilota otsikkopalkki",
				copied: "Kopioitu",
				small: "pieni",
				medium: "keskikokoinen",
				large: "suuri",
				custom: "mukautettu",
				widthAbbreviation: "l",
				heightAbbreviation: "k",
				emptyDimension: "Anna ulottuvuus.",
				seeExample: "Esikatsele upotusta",
				removeHeader: "Piilota sovelluksen ylätunniste"
			},
			maps: {
				unableRetrieveTitle: "Karttoja ei voi noutaa",
				unableRetrieveDescription: "Tämän tarinakartan karttojen nouto ei onnistunut."
			},
			images: {
				unableRetrieveTitle: "Kuvia ei voi noutaa",
				unableRetrieveDescription: "Tämän tarinakartan kuvien nouto ei onnistunut."
			},
			tags: {
				tags: "Valittu taustakartta ei ole Web-kartta, joten sitä ei voi käyttää Open Data -aineiston kanssa.",
				collectionTags: "Aihe",
				selectASubject: "Valitse aihe",
				save: "Tallenna",
				saved: "Tallennettu",
				errorSaving: "Virhe tallennettaessa",
				tagTip: "Vihje: Tunnisteiden avulla ihmiset löytävät tarinasi. Mitä enemmän asiaankuuluvia tunnisteita on, sitä enemmän näkyvyyttä työsi saa."
			},
			submitToGallery: {
				gallerySubmission: "Tarinakarttagalleria",
				canSubmitIf: "Voit ehdottaa tarinaasi galleriaan, jos se sisältää seuraavat tiedot:",
				hasOwnImage: "mukautetun pikkukuvan",
				chosenSubject: "aiheen ja joitakin tunnisteita",
				chosenSubjectAlt: "aiheen {{SUBJECT}} ja joitakin tunnisteita",
				storyMapTopicSubject: "aihe",
				sharedPublicly: "jaettu julkisesti",
				noBrokenContent: "Ei ongelmia",
				nominateToGallery: "Ehdota galleriaan",
				comingSoon: "Tulossa pian!",
				submitted: "Lähetetty",
				errorSubmitting: "Virhe lähetyksessä",
				ourGallery: "Tarinakarttagalleria",
				galleryTip: "Galleria {{THE_GALLERY}} on järjestetty tarinakarttojen joukko, joka esittelee joitakin parhaita esimerkkejä. Jos tarinasi valitaan, se lisätään kymmenen päivän kuluessa lähetyksestä. Saapuvien ehdotusten määrän takia, Esri ei voi luvata, että tarinasi lisätään."
			},
			placeholders: {
				noSummary: "Ei yhteenvetoa, lisää sellainen napsauttamalla."
			},
			errors: {
				cantDeleteStory: "Tarinaa ei voida poistaa.",
				unableToFind: "Sisältöä ei löydy",
				unableToRetrieve: "Tämän tarinakartan sisällön nouto ei onnistunut."
			},
			socialSharing: {
				availableWhenPublic: "Tämä vaihtoehto on käytettävissä, kun tarinasi on julkinen"
			},
			dialog: {
				back: "Takaisin",
				close: "Tallennettu",
				cancel: "Peruuta"
			},
			imagePicker: {
				changeDefault: "Muuta oletuskuvaa",
				changeImage: "Vaihda pikkukuva",
				uploadImage: "Lataa pikkukuva palvelimeen",
				chooseImage: "Valitse pikkukuva",
				chooseAnImage: "Valitse kuva",
				notInIEVersion: "Tämä ominaisuus ei ole käytettävissä Internet Explorerin versiossa {{VERSION_NUMBER}}.",
				or: "Tai",
				uploadAnImage: "Lataa kuva",
				supportedFileTypes: "Tukee kuvamuotoja .png, .jpg ja .gif",
				imageSizeMessage: "Kuvasi on oltava kooltaan vähintään 286 pikseliä leveä ja 190 pikseliä korkea.",
				minimumDimensions: "Vähimmäiskoko: 286 x 190 pikseliä",
				imagesLoading: "Ladataan kuvia...",
				noImages: "Tässä tarinassa ei ole kuvia",
				errorLoading: "Tämän tarinan kuvia ei voi noutaa",
				clickBelowTip: "Lataa kuva palvelimeen napsauttamalla alla olevaa painiketta.",
				dragAndDrop: "Vedä ja pudota",
				cropImage: "Rajaa kuva",
				saveImage: "Tallenna kuva",
				save: "Tallenna",
				savingImage: "Tallennetaan kuvaa...",
				saved: "Kuva on tallennettu.",
				errorSaving: "Kuvaa ei voi tallentaa.",
				skipAndCrop: "Ohita ja rajaa puolestani",
				wrongFormat: "Tiedostotyyppiä ei tueta.",
				noCropWarning: "Tätä kuvaa ei voi rajata, mutta voit silti tallentaa sen tarinasi pikkukuvaksi sen alkuperäisessä koossa ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}} pikseliä)."
			}
		},
		content: {
			media: {
				maps: "Maps",
				images: "Kuva-aineistot",
				videos: "Videot",
				webpages: "Web-sivut",
				tags: "Valittu taustakartta ei ole Web-kartta, joten sitä ei voi käyttää Open Data -aineiston kanssa.",
				gallery: "Galleria"
			},
			headers: {
				status: "Tila",
				source: "Lähde",
				name: "Nimi",
				shared: "Jaettu"
			},
			component: {
				mapTour: "Pistenumero",
				bullet: "Luettelomerkki",
				tab: "Sarkain",
				accordion: "Osa",
				mapJournal: "Osa"
			},
			titleType: {
				mapTour: "Seloste",
				mapJournal: "URL-osoite",
				mapSeries: "URL-osoite"
			},
			actions: {
				viewMap: "Näytä kartta",
				editMap: "Muokkaa karttaa",
				fix: "Korjaa",
				viewLayer: "Näytä karttataso"
			},
			contentType: {
				mainStage: "päävaiheen toiminto",
				sidePanel: "kuvaus"
			},
			notification: {
				refreshExplanation: "Tarkista tarinasi uudelleen",
				checking: "Tarkistetaan...",
				foundSomeIssues: "Joitakin ongelmia löytyi",
				noIssuesFound: "Yhtään ongelmaa ei löytynyt",
				storyPublic: "Tarinasi on nyt julkinen",
				storyOrg: "Tarinasi on nyt jaettu organisaation kanssa",
				storyPrivate: "Tarinasi on nyt yksityinen",
				mapPublic: "Karttasi on nyt julkinen",
				mapOrg: "Karttasi on nyt jaettu organisaation kanssa",
				mapPrivate: "Karttasi on nyt yksityinen",
				layerPublic: "Karttatasosi on nyt julkinen",
				layerOrg: "Karttatasosi on nyt jaettu organisaation kanssa",
				layerPrivate: "Karttatasosi on nyt yksityinen",
				contentPublic: "Sisältösi on nyt julkinen",
				contentOrg: "Sisältösi on nyt jaettu organisaation kanssa",
				contentPrivate: "Sisältösi on nyt yksityinen",
				storyAndContentPublic: "Tarinasi ja sen sisältö ovat nyt julkisia",
				storyAndContentOrg: "Tarinasi ja sen sisältö on nyt jaettu organisaation kanssa",
				storyAndContentPrivate: "Tarinasi ja sen sisältö ovat nyt yksityisiä",
				shareBulkPrompt: "Haluatko jakaa vastaavasti myös tarinasi sisällön?",
				layersPublic: "Jotkin karttatasot on myös jaettu julkisesti",
				layersOrg: "Jotkin karttatasot on myös jaettu organisaatiosi kanssa",
				layersPrivate: "Jotkin karttatasot on myös määritetty yksityisiksi",
				mapsPublic: "Jotkin kartat on myös jaettu julkisesti",
				mapsOrg: "Jotkin kartat on myös jaettu organisaatiosi kanssa",
				mapsPrivate: "Jotkin kartat on myös määritetty yksityisiksi",
				layersAndMapsPublic: "Jotkin kartat ja karttatasot on myös jaettu julkisesti",
				layersAndMapsOrg: "Jotkin kartat ja karttatasot on myös jaettu organisaatiosi kanssa",
				layersAndMapsPrivate: "Jotkin kartat ja karttatasot on myös määritetty yksityisiksi",
				yes: "Kyllä",
				no: "Ei",
				premiumPublicSuccess: "Premium-sisältö on nyt julkisesti saatavilla",
				subscriptionPublicSuccess: "Tilauksen sisältö on nyt julkisesti saatavilla"
			},
			errors: {
				publicDisabled: "Pääkäyttäjä on poistanut julkisen jakamisen käytöstä",
				orgDisabled: "Pääkäyttäjä on poistanut käytöstä jakamisen organisaation kanssa",
				noMapName: "Kartan nimen nouto ei onnistunut",
				notPublic: "EI JULKINEN",
				inaccessible: "EI KÄYTETTÄVISSÄ",
				deleted: "POISTETTU",
				cantAccessVideo: "Videon käyttö ei onnistunut",
				noStoriesFound: "Tarinakarttoja ei löytynyt sisällöstäsi.",
				cantShowStories: "Tarinakarttojasi ei voi näyttää. Yritä myöhemmin uudelleen.",
				consolationSearch: "Yhtään tarinaa ei löytynyt.",
				notCompatibleWithBrowser : "Omat tarinat -palvelua ei tueta Internet Explorerin versiota {{VERSION_NUMBER}} edeltävissä versioissa.",
				pleaseUpdateBrowser: "Päivitä selaimesi.",
				searchTip: "Kokeile ja yksinkertaista sitä hieman.",
				consolationNoStories: "Tervetuloa Omat tarinat -palveluun!",
				noStoriesTip: "Jos haluat luoda ensimmäisen tarinakarttasi, siirry Sovellukset-sivulle.",
				letsGo: "Aloitetaan",
				cantChangeSharingLevel: "Jakamistasoa ei voi muuttaa",
				cantChangeSharingLevels: "Jakamistasoja ei voi muuttaa",
				errorUpdatingTitle: "Otsikon päivityksessä tapahtui virhe",
				errorUpdatingSummary: "Yhteenvedon päivityksessä tapahtui virhe",
				noEmptyTitle: "Otsikko ei voi olla tyhjä",
				cantUpdatePremiumContent: "Premium-sisältöä ei voi päivittää",
				cantUpdateSubscriptionContent: "Tilauksen sisältöä ei voi päivittää",
				createFirstStory: "Luo ensimmäinen tarinani"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Kartta on poistettu",
				layerHasBeenDeleted: "Karttataso on poistettu",
				mapIsInaccessible: "Kartta ei ole käytettävissä",
				layerIsInaccessible: "Karttataso ei ole käytettävissä",
				mapNotYoursNotAccessible: "Joku muu omistaa kartan eikä sitä voi käyttää",
				layerServiceOkItemNot: "Karttataso on lisätty kohteena, joka on poistettu tai joka ei ole käytettävissä",
				layerNotYoursNotAccessible: "Joku muu omistaa karttatason eikä sitä voi käyttää",
				mapOthersSharedBelowLevel: "Et omista karttaa eikä se ole julkinen",
				layerOthersSharedBelowLevel: "Et omista karttatasoa eikä se ole julkinen",
				noMapNoDetails: "Ilman kartan tietoja karttatasoista ei voida kertoa mitään",
				mapIsPrivate: "Kartta on yksityinen",
				mapIsOrg: "Kartta on jaettu vain organisaation kanssa",
				layerIsPrivate: "Karttataso on yksityinen",
				layerIsOrg: "Karttataso on jaettu vain organisaation kanssa",
				imageInaccessible: "Tämä kuva ei ole käytettävissä",
				videoInaccessible: "Tämä video ei ole käytettävissä",
				webpageInaccessible: "Tämä Web-sivu ei ole käytettävissä",
				layerSecureService: "Karttataso on suojattu palvelu",
				mapSecureService: "Kartta on suojattu palvelu",
				layerConsumesCredits: "Karttataso on Premium-sisältöä ja kuluttaa krediittejä",
				layerSubscriptionContent: "Karttataso on tilauksen sisältöä",
				mapConsumesCredits: "Kartta on Premium-sisältöä ja kuluttaa krediittejä",
				mapSubscriptionContent: "Kartta on tilauksen sisältöä"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Tämäntyyppistä karttatasoa ei voi tarkistaa",
				cantScanThisType: "Karttatason tyyppi ei ole sellainen, jonka voi tarkistaa",
				webpageNotScanned: "Web-sivujen ongelmia ei tarkisteta",
				ignoredIssue: "Olet ohittanut tämän karttatason virheen. Tarkista virhe lataamalla sivu uudelleen ja valitsemalla tämä tarina uudelleen",
				ignoredIssueBuilder: "Olet ohittanut tämän karttatason virheen. Tarkista tämä virhe uudelleen lataamalla luontitoiminto uudelleen"
			},
			scanningErrors: {
				deletedMap: "Poistettu sisältö",
				inaccessibleMap: "Kartan sisältö ei ole käytettävissä",
				notYoursNotAccessible: "Et omista sisältöä eikä se ole julkista",
				serviceOkItemNot: "Karttatasot toimivat, mutta kohteita ei voi käyttää",
				someContentNotPublic: "Sisältöä ei ole jaettu julkisesti",
				someContentPrivate: "Yksityinen sisältö",
				othersSharedBelowLevel: "Et omista sisältöä eikä se ole julkista",
				premiumContent: "Premium-sisältö",
				subscriptionContent: "Tilauksen sisältö",
				secureService: "Suojatut palvelut",
				inaccessibleImage: "Kuvia ei voi käyttää",
				inaccessibleVideo: "Videoita ei voi käyttää",
				inaccessibleWebpage: "Web-sivuja ei voi käyttää"
			},
			scanningErrorTips: {
				deletedMapTip: "Vihje: muokkaa Web-karttaasi ja poista viallinen sisältö tai poista Web-kartta tarinastasi.",
				inaccessibleMapTip: "Vihje: muokkaa Web-karttaasi ja poista viallinen sisältö tai poista Web-kartta tarinastasi.",
				notYoursNotAccessibleTip: "Vihje: muokkaa Web-karttaasi ja poista karttataso tai poista Web-kartta tarinastasi.",
				serviceOkItemNotTip: "Karttatasot on lisätty kohteina, joita ei voi käyttää tai jotka on poistettu. Karttatasot toimivat, mutta tämä voi vaikuttaa karttasi toimintaan (ponnahdusikkunoihin ja symboleihin).",
				ignore: "Ohita",
				fix: "Korjaa",
				clickToShareOrg: "Jaa kaikki tämä sisältö organisaatiosi kanssa napsauttamalla painiketta tai muuta kutakin kohdetta manuaalisesti napsauttamalla sen jakamispainikkeita.",
				clickToSharePublic: "Jaa kaikki tämä sisältö julkisesti napsauttamalla painiketta tai muuta kutakin kohdetta manuaalisesti napsauttamalla sen jakamispainikkeita.",
				shareOrg: "Jaa organisaatiosi kanssa",
				sharePublicly: "Jaa julkisesti",
				othersSharedBelowLevelTip: "Vihje: {{USER_NAME}} omistaa osan tarinasi sisällöstä, ja muut tarinaasi katsovat eivät ehkä näe sitä.",
				secureServiceTip: "Vihje: poista suojattu palvelu tarinastasi tai noudata {{HERE}} kuvattuja ohjeita.",
				blogArticle: "täällä",
				premiumContentTip: "Tarinasi sisältää Premium-sisältöä, joka kuluttaa {{CREDITS}} krediittiä, kun se määritetään julkiseksi. Tee tarinastasi julkinen ja jatka tai poista karttatasot tarinastasi.",
				premiumContentPublicTip: "Tarinasi sisältää Premium-sisältöä, joka kuluttaa {{CREDITS}} krediittiä, kun se on julkisesti saatavilla. Tee näistä karttatasoista julkisia vahvistamalla tai poista karttatasot tarinastasi.",
				subscriptionContentTip: "Tarinasi sisältää tilauksen sisältöä, joka ei ole julkisesti saatavilla oletusarvoisesti. Vahvista, että haluat näiden karttatasojen olevan julkisesti saatavilla (yhtään krediittiä ei kulu), tai poista karttatasot tarinastasi.",
				credits: "krediitit",
				makePublic: "Määritä julkiseksi",
				confirm: "Vahvista",
				inaccessibleImageTip: "Vihje: määritä puuttuva kuva tai poista sen viite.",
				inaccessibleVideoTip: "Vihje: määritä puuttuva video tai poista sen viite.",
				inaccessibleWebpageTip: "Vihje: määritä puuttuva Web-sivu tai poista sen viite."
			},
			removeLayer: {
				title: "Korjaa karttatason ongelma",
				layersWithIssue: "Niiden karttatason määrä, joissa on tämä ongelma: {{NUM_WITH_ISSUE}}",
				issueExplanation: "Karttataso {{LAYER_NAME}} on lisätty kohteena, joka ei ole käytettävissä tai joka on poistettu. Karttataso toimii, mutta tämä voi vaikuttaa karttasi toimintaan (ponnahdusikkunoihin ja symboleihin). Siitä, oliko kohde tärkeä tarinasi kannalta, ei ole tietoa.",
				issueSolution: "Voit korjata ongelman muokkaamalla karttaa, poistamalla karttatason ja lisäämällä karttatason takaisin karttaan käyttämällä seuraavaa URL-osoitetta:",
				editMap: "Muokkaa karttaa",
				clickBelowWhenDone: "Kun olet lopettanut muokkaamisen, napsauta alla olevaa painiketta:",
				rescanAndClose: "Skannaa uudelleen ja sulje"
			},
			info: {
				ownedBy: "{{USER_NAME}} omistaa tämän kohteen",
				unknownUser: "joku muu",
				untitledSection: "(Nimetön osio)",
				introRecord: "Johdanto"
			},
			layers: {
				layersHeader: "Karttatasot",
				noLayers: "(Ei karttatasoja)",
				basemapParens: "(taustakartta)"
			},
			images: {
				thumbnails: "Pikkukuvat",
				thumbnail: "Pikkukuva",
				thumbnailParens: "(pikkukuva)"
			},
			general: {
				noTitle: "(ei otsikkoa)",
				loading: "Ladataan..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "osat",
				secondTitle: "tyyli",
				secondValueA: "sivupaneeli",
				secondValueB: "irrallinen ruutu",
				thirdTitle: "kartat"
			},
			mapTour: {
				firstTitle: "kierroksen pisteet",
				secondTitle: "tyyli",
				secondValueA: "integroitu",
				secondValueB: "kolme ruutua",
				thirdTitle: "peruskartta",
				thirdValueLoading: "Ladataan...",
				thirdValueUnknown: "tuntematon"
			},
			mapSeries: {
				firstTitleA: "luettelomerkit",
				firstTitleB: "osat",
				firstTitleC: "välilehdet",
				secondTitle: "tyyli",
				secondValueA: "luettelomerkkejä sisältävä",
				secondValueB: "sivuhaitari",
				secondValueC: "välilehtiin jaettu",
				thirdTitle: "kartat"
			},
			swipeSpyglass: {
				firstTitle: "kiinnostuksenkohde",
				secondTitle: "tyyli",
				secondValueA: "pyyhkäise",
				secondValueB: "kiikari",
				thirdTitle: "kartat"
			},
			crowdsource: {
				firstTitle: "lisäykset",
				secondTitle: "tyyli",
				secondValueA: "sivupaneeli",
				secondValueB: "pinottu",
				thirdTitle: "peruskartta",
				thirdValueLoading: "Ladataan...",
				thirdValueUnknown: "tuntematon"
			}
		},
		progress: {
			checkingStories: "Tarkistetaan, onko tarinoissa ongelmia...",
			stop: "Lopeta",
			exit: "Poistu",
			dismiss: "Dismiss",
			done: "Valmis.",
			noStoriesWithIssuesLower: "Yhtään ongelmaa ei löytynyt.",
			storiesErrorFree: "Näyttää siltä, ettei tarinoissasi ole ongelmia",
			scanAllError: "Skannaus ei onnistu – vähintään yhden tarinan nouto ei onnistunut",
			scanProgress: "{{NUM_SCANNED}}/{{NUM_TOTAL}}",
			scanStopped: "Skannatut tarinat: {{NUM_SCANNED}}, tarinat, joissa on ongelmia: {{ISSUE_STORIES}}",
			storiesWithIssues: "Tarinat, joissa on ongelmia: {{NUM_STORIES}}"
		},
		newStories: {
			newStoriesFound: "Näyttää siltä, että olet luonut uuden tarinan.",
			includeStories: "Päivitä tarinat",
			notWhileScanning: "Tämä toiminto on käytettävissä, kun tarkistus on tehty"
		}
    })
);
