define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Sisestage vahemaa",
                    "layerName": "Sisestage siia kihi nimi"
                },
                "message": {
                    "analysisFailed": "Analüüs nurjus.",
                    "errorOccurred": "Ilmnes tõrkeid.",
                    "layerAdded": "Kiht on lisatud. ",
                    "enrichLayerNameError": "Tulemkihi nimi ei tohi sisaldada sobimatuid märke" + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Teenuse loomine... ",
                    "starting": "Algus",
                    "performingAnalysis": "Analüüsimine..",
                    "checkLayerName": "Kihi nime kontrollimine... ",
                    "addingLayer": "Kihi lisamine veebikaardile ",
                    "layerNameExist": "Kihi nimi on juba olemas.",
                    "clickOnSave": " Rakenduse uuesti laadimiseks klõpsake nuppu Salvesta.",
                    "clickOnOk": " Uuesti proovimiseks klõpsake nuppu OK.",
                    "enterNumbersOnly": "Sisestatud väärtused ei sobi",
                    "nofeatures": "Praeguses ulatuses pole objekte",
                    "selectData": "Valige kihi rikastamiseks andmed.",
                    "resetVariableMessage": "Kas olete kindel, et soovite muutuja lähtestada?",
                    "emptyTextFieldLayerName": "Sisestage tulemikihi nimi",
                    "createService":"Kihti ei loodud.",
                    "sharingLayer":"Kihi jagamine..",
                    "updateItemFailed": "Uuendamine nurjus. Proovige uuesti.",
                    "geoEnrichFailed": "Kihi rikastamine nurjus. Proovige uuesti.",
                    "shareFailed": "Rikastatud kihi jagamine nurjus. Proovige uuesti.",
                    "refreshServiceFailed": "Kihi värskendamine nurjus. Proovige uuesti.",
                    "layerJsonFailed": "Kihi JSON-i loomine nurjus. Proovige uuesti.",
                    "addToWebmapFailed": "Kihi lisamine veebikaardile nurjus. Proovige uuesti.",
                    "bufferAreaHelpText": "Sisestage väärtus, mis on väiksem kui ",
                    "invalidBufferInput": "Sisestatud väärtus ei sobi.",
                    "emptyBufferInput": "Sisestage sobiv väärtus."
                },
                "populationText": "Rahvastik",
                "housingText": "Leibkond",
                "businessText": "Äriettevõtted",
                "variableListText": " muutujad on loetletud siin:",
                "countrySelectTitle": "1. Valige andmete asukoht",
                "unitedStates": "Ameerika Ühendriigid",
                "global": "Üldine",
                "geoenrichDialogText": "Georikastamise muutujad",
                "viewVariablestext": "Kuva muutujad",
                "backButtonText":"Tagasi",
                "customizeVariables": "Kohanda muutujaid",
                "resetVariables": "Lähtesta",
                "defineAreaTitle": "3. Määrake ala, mida soovite rikastada",
                "currentMapExtent": "Kasuta praeguse kaardi ulatust",
                "enrichLayerName": "4. Tulemikihi nimi",
                "lineDistanceText": "Joone vahemaa",
                "drivingTime": "Sõiduaeg",
                "enrichButtonText": "Rikasta kihti",
                "selectDataText": "2. Valige andmed",
                "showCreditsText": "Kuva krediidid",
                "variableCount": "Muutujate koguarv ",
                "totalRecords": "Kirjete koguarv:",
                "cost": "Maksumus:",
                "showCreditsDialogText": "Kuva krediidid",
                "nextButtonText": "Järgmine",
                "prevButtonText": "Eelmine",
                "saveButtonText": "Salvesta",
                "ok": "OK"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 