define({
    root: ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Sisene koostajasse",
                "exitBuilderButtonText": "Välju koostajast",
                "enterBuilderModeHelpText": "Sisene rakenduse seadistamiseks koostamisrežiimi",
                "builderModeHelpText": "Mallide koostamisrežiim",
                "webmapCaption": "Kaart",
                "selectMapMessage": "Hetkel kuvatav ${displaying} veebikaart <b>${webmapTitle}</b><br/>Muu veebikaardi valimiseks klikkige nuppu Vali kaart",
                "loadMapMessage": "Hetkel valitud veebikaart <b>${webmapTitle}</b><br/>Selle veebikaardi kasutamiseks klikkige nuppu Salvesta",
                "changeWebmap": "Vali kaart",
                "saveButtonText": "Salvesta",
                "webmapNextButtonText": "Järgmine ->",
                "previousButtonText":"Eelmine",
                "layerLabelText": "Kiht",
                "noLayerFoundText": "Kihti ei leitud",
                "selectLayer": "Vali kiht",
                "applicationSettingText": "Rakenduse seaded",
                "summaryAttrAscendingOrderTooltip": "Kasvav",
                "onStartLabel": "Käivitamisel",
                "selectVariableText": "Vali muutuja",
                "selectVariableDropdown": "Vali muutuja",
                "label":"Silt",
                "sourceLinkText":"Allika link",
                "selectSubVariableText":"Vali alammuutujad",
                "subVariablePanelButtonText":"VALMIS",
                "onButtonLabel":"Sees",
                "offButtonLabel":"Väljas",
                "appSettingsSaveCloseButtonText": "SALVESTA JA SULGE",
                "appSettingsTitleText":"Rakenduse nimi",
                "appSettingsDescriptionText": "Rakenduse kirjeldus",
                "appSetingsRendererAreaText":"Renderdatud ala",
                "shareText":"Jaga",
                "popupText": "Hüpikaken",
                "basemapText":"Aluskaart",
                "cancel": "Tühista",
                "theme": "Teema",
                "zoomLevel": "Suumimise tase",
                "existingValue": "Kasuta olemasolevaid väärtusi",
                "enrichLayer": "Rikasta kihti",
                "imageLabel": "Kuidas see töötab ?",
                "clearData": "Eemalda andmed",
                "basemapSelectionText":"Aluskaardi valik",
                "secondaryBasemapText":"Sekundaarne aluskaart",
                "defaultBasemapText": "Vaikimisi aluskaart",
                "entireAreaButton": "Kogu ala",
                "entireAreaOnStartButton": "Terve piirkond käivitamisel",
                "aboutPanel": "Teabepaneel",
                "legendPanel": "Legendipaneel",
                "layersPanel": "Kihipaneel",
                "dataConfigurationButtonText": "Andmete seadistus",
                "savingChangesMessage": "Muudatuste salvestamine...",
                "nextButtonText": "Järgmine",
                "prevButtonText": "Eelmine",
                "enterLabelText": "Sisesta märgis",
                "SelectedFeatureText": "Valitud objekt",
                "layerHelpTextMessage": "See rakendus nõuab numbriväljadega kihti",
                "alertMessage": {
                    "resetVariableMessage": "Kas olete kindel, et soovite muutuja lähtestada?",
                    "emptyAppTitleMessage": "Rakenduse nime väli ei saa olla tühi",
                    "emptyDescriptionMessage": "Kirjeldus ei saa olla tühi",
                    "maxVariableSelection": "Te ei saa valida rohkem kui 25 alammuutujat",
                    "signInFail" : "Sisselogimine ebaõnnestus",
                    "itemUpdateMessage": "Objekt uuendatud",
                    "unsavedChangesMessage": "Salvestamata muudatused",
                    "failMessage": "Objekti ei õnnestunud edukalt uuendada",
                    "saveChangesAlert": "Kas soovite muudatused salvestada ?",
                    "variableLabelValidation": "Muutuja märgis ei saa olla tühi",
                    "subVariableLabelValidation": "Alammuutuja märgis ei saa olla tühi"
                    }
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});