define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Sisene koostajasse",
                "exitBuilderButtonText": "Välju koostajast",
                "enterBuilderModeHelpText": "Sisene rakenduse seadistamiseks koostamisrežiimi",
                "builderModeHelpText": "Mallide koostamisrežiim",
                "webmapCaption": "Kaart",
                "selectMapMessage": "Hetkel kuvatav ${displaying} veebikaart <b>${webmapTitle}</b><br/>Muu veebikaardi valimiseks klikkige nuppu Vali kaart",
                "loadMapMessage": "Hetkel valitud veebikaart <b>${webmapTitle}</b><br/>Selle veebikaardi kasutamiseks klikkige nuppu Salvesta",
                "changeWebmap": "Vali kaart",
                "saveButtonText": "Salvesta",
                "webmapNextButtonText": "Järgmine ->",
                "previousButtonText":"Eelmine",
                "layerLabelText": "Kiht",
                "noLayerFoundText": "Kihti ei leitud",
                "selectLayer": "Vali kiht",
                "applicationSettingText": "Rakenduse seaded",
                "summaryAttrAscendingOrderTooltip": "Kasvav",
                "onStartLabel": "Käivitamisel",
                "selectVariableText": "Vali muutuja",
                "selectVariableDropdown": "Vali muutuja",
                "label":"Silt",
                "sourceLinkText":"Allika link",
                "selectSubVariableText":"Vali alammuutujad",
                "subVariablePanelButtonText":"VALMIS",
                "onButtonLabel":"Sees",
                "offButtonLabel":"Väljas",
                "appSettingsSaveCloseButtonText": "SALVESTA JA SULGE",
                "appSettingsTitleText":"Rakenduse nimi",
                "appSettingsDescriptionText": "Rakenduse kirjeldus",
                "appSetingsRendererAreaText":"Renderdatud ala",
                "shareText":"Jaga",
                "basemapText":"Aluskaart",
                "basemapSelectionText":"Aluskaardi valik",
                "secondaryBasemapText":"Sekundaarne aluskaart",
                "defaultBasemapText": "Vaikimisi aluskaart",
                "entireAreaButton": "Kogu ala",
                "entireAreaOnStartButton": "Terve piirkond käivitamisel",
                "aboutPanel": "Teabepaneel",
                "legendPanel": "Legendipaneel",
                "layersPanel": "Kihipaneel",
                "dataConfigurationButtonText": "Andmete seadistus",
                "savingChangesMessage": "Muudatuste salvestamine...",
                "nextButtonText": "Järgmine",
                "prevButtonText": "Eelmine",
                "enterLabelText": "Sisesta märgis",
                "SelectedFeatureText": "Valitud objekt",
                "layerHelpTextMessage": "See rakendus nõuab numbriväljadega kihti",
                "alertMessage": {
                    "resetVariableMessage": "Š_Are you sure you want to reset variable_ä?",
                    "emptyAppTitleMessage": "Rakenduse nime väli ei saa olla tühi",
                    "emptyDescriptionMessage": "Kirjeldus ei saa olla tühi",
                    "maxVariableSelection": "Te ei saa valida rohkem kui 25 alammuutujat",
                    "signInFail" : "Sisselogimine ebaõnnestus",
                    "itemUpdateMessage": "Objekt uuendatud",
                    "unsavedChangesMessage": "Salvestamata muudatused",
                    "failMessage": "Objekti ei õnnestunud edukalt uuendada",
                    "saveChangesAlert": "Kas soovite muudatused salvestada ?",
                    "variableLabelValidation": "Š_Variable label cannot be empty_ä",
                    "subVariableLabelValidation": "Š_Sub variable label cannot be empty_ä"
                    }
            }
        }
    })
);