define(
     ({
        map: {
            error: "Δεν είναι δυνατή η δημιουργία χάρτη"
        },
        onlineStatus: {
            offline: "Αυτή τη στιγμή εργάζεστε χωρίς σύνδεση. Οι υποβολές φόρμας θα αποθηκεύονται τοπικά μέχρι να είναι δυνατή η σύνδεση με το διακομιστή.",
            reconnecting: "Επανασύνδεση&hellip;",
            pending: "Θα υποβληθούν ${total} εκκρεμείς αλλαγές όταν αποκατασταθεί η σύνδεση δικτύου."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Ο Οργανισμός μου",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Το Περιεχόμενό μου",
                    favoritesLabel: "Τα Αγαπημένα μου"
                },
                title: "Επιλογή χάρτη web",
                searchTitle: "Αναζήτηση",
                ok: "OK",
                cancel: "Άκυρο",
                placeholder: "Εισαγάγετε όρο αναζήτησης"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Ο Οργανισμός μου",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Το Περιεχόμενό μου",
                    favoritesLabel: "Τα Αγαπημένα μου"
                },
                title: "Επιλογή ομάδας",
                searchTitle: "Αναζήτηση",
                ok: "OK",
                cancel: "Άκυρο",
                placeholder: "Εισαγάγετε όρο αναζήτησης"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Ακολουθεί μια σύνδεση σε ένα GeoForm"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Κατακόρυφη συντεταγμένη",
            utm_easting: "Οριζόντια συντεταγμένη",
            utm_zone_number: "Αριθμός ζώνης",
            selectLayerTabText: "Đ_${formSection} Choose Form_ớ",
            geoFormGeneralTabText: "Đ_${formSection} Enter Information_ớ",
            locationInformationText: "Đ_${formSection} Select Location_ớ",
            submitInformationText: "Đ_${formSection} Complete Form_ớ",
            submitInstructions: "Προσθέστε τις πληροφορίες αυτές στο χάρτη.",
            myLocationText: "Τρέχουσα τοποθεσία",
            locationDescriptionForMoreThanOneOption: "Καθορίστε την τοποθεσία για αυτή την καταχώριση κάνοντας κλικ / πατώντας στο χάρτη ή χρησιμοποιώντας μία από τις παρακάτω επιλογές.",
            locationDescriptionForOneOption: "Καθορίστε την τοποθεσία για αυτή την καταχώριση κάνοντας κλικ / πατώντας στο χάρτη ή χρησιμοποιώντας την παρακάτω επιλογή.",
            locationDescriptionForNoOption: "Καθορίστε την τοποθεσία για αυτή την καταχώριση κάνοντας κλικ / πατώντας στο χάρτη.",
            addressText: "Αναζήτηση",
            geographic: "Γεωγρ. πλάτος/μήκος",
            locationTabText: "Τοποθεσία",
            locationPopupTitle: "Τοποθεσία",
            submitButtonText: "Υποβολή καταχώρισης",
            submitButtonTextLoading: "Υποβολή&hellip;",
            formValidationMessageAlertText: "Τα παρακάτω πεδία είναι απαιτούμενα:",
            selectLocation: "Επιλέξτε μια τοποθεσία για την υποβολή σας.",
            emptylatitudeAlertMessage: "Εισαγάγετε μια συντεταγμένη ${openLink}γεωγραφικού πλάτους${closeLink}.",
            emptylongitudeAlertMessage: "Εισαγάγετε μια συντεταγμένη ${openLink}γεωγραφικού μήκους${closeLink}.",
            shareUserTitleMessage: "Σας ευχαριστούμε για τη συνεισφορά σας!",
            entrySubmitted: "Η καταχώρισή σας έχει υποβληθεί στο χάρτη.",
            shareThisForm: "Κοινοποιήστε αυτή τη φόρμα",
            shareUserTextMessage: "Πείτε σε άλλους να συνεισφέρουν χρησιμοποιώντας τις παρακάτω επιλογές.",
            addAttachmentFailedMessage: "Δεν είναι δυνατή η προσθήκη συνημμένου στο επίπεδο",
            addFeatureFailedMessage: "Δεν είναι δυνατή η προσθήκη του χαρακτηριστικού στο επίπεδο",
            noLayerConfiguredMessage: "Παρουσιάστηκε σφάλμα κατά τη φόρτωση ή την εύρεση ενός επεξεργάσιμου επιπέδου χαρακτηριστικών. Για να εμφανίσετε τη φόρμα και να αρχίσετε να συλλέγετε υποβολές, προσθέστε ένα επεξεργάσιμο επίπεδο χαρακτηριστικών στο χάρτη web.",
            placeholderLatitude: "Γεωγραφικό πλάτος (Y)",
            placeholderLongitude: "Γεωγραφικό μήκος (X)",
            latitude: "Γεωγραφικό πλάτος",
            longitude: "Γεωγραφικό μήκος",
            findMyLocation: "Εντοπισμός της θέσης μου",
            finding: "Εντοπισμός&hellip;",
            backToTop: "Επιστροφή στην κορυφή",
            addressSearchText: "Η υποβολή σας θα εμφανιστεί εδώ. Μπορείτε να σύρετε την καρφίτσα για να διορθώσετε την τοποθεσία.",
            shareModalFormText: "Σύνδεση φόρμας",
            close: "Κλείσιμο",
            locationNotFound: "Δεν ήταν δυνατή η εύρεση της τοποθεσίας.",
            setLocation: "Ορισμός τοποθεσίας",
            find: "Βρείτε μια διεύθυνση ή ένα μέρος",
            attachment: "Συνημμένο",
            toggleDropdown: "Εναλλαγή αναπτυσσόμενου πλαισίου",
            invalidString: "Εισαγάγετε μια έγκυρη τιμή.",
            invalidSmallNumber: "Εισαγάγετε μια έγκυρη ${openStrong}ακέραιη${closeStrong} τιμή μεταξύ -32768 και 32767.",
            invalidNumber: "Εισαγάγετε μια έγκυρη ${openStrong}ακέραιη${closeStrong} τιμή μεταξύ -2147483648 και 2147483647.",
            invalidFloat: "Εισαγάγετε μια έγκυρη τιμή ${openStrong}κινητής υποδιαστολής${closeStrong}.",
            invalidDouble: "Εισαγάγετε μια έγκυρη ${openStrong}διπλή${closeStrong} τιμή.",
            invalidLatLong: "Εισαγάγετε έγκυρες συντεταγμένες γεωγραφικού πλάτους και μήκους.",
            invalidUTM: "Εισαγάγετε έγκυρες συντεταγμένες UTM.",
            invalidUSNG: "Εισαγάγετε έγκυρες συντεταγμένες USNG.",
            invalidMGRS: "Εισαγάγετε έγκυρες συντεταγμένες MGRS.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Επιλέξτε&hellip;",
            applyEditsFailedMessage: "Λυπούμαστε, δεν είναι δυνατή η υποβολή της καταχώρισής σας. Δοκιμάστε ξανά.",
            requiredFields: "Υπάρχουν μερικά σφάλματα. Διορθώστε τα παρακάτω.",
            requiredField: "(απαιτούμενο)",
            error: "Σφάλμα",
            textRangeHintMessage: "${openStrong}Υπόδειξη:${closeStrong} ελάχιστη τιμή ${minValue} και μέγιστη τιμή ${maxValue}",
            dateRangeHintMessage: "${openStrong}Υπόδειξη:${closeStrong} ελάχιστη ημερομηνία ${minValue} και μέγιστη ημερομηνία ${maxValue}",
            remainingCharactersHintMessage: "Απομένουν ${value} χαρακτήρες",
            mapFullScreen: "Đ_Full Screen_ớ",
            mapRestore: "Đ_Restore_ớ",
            filterSelectEmptyText: "Đ_Select_ớ",
            invalidLayerMessage: "Đ_Form layer does not exist. Please configure the application and set the layer_ớ."
        },
        builder: {
            invalidUser: "Λυπούμαστε, δεν έχετε δικαίωμα προβολής αυτού του στοιχείου",
            invalidWebmapSelectionAlert: "Ο επιλεγμένος χάρτης web δεν περιέχει έγκυρο επίπεδο για χρήση. Προσθέστε ένα επεξεργάσιμο επίπεδο χαρακτηριστικών στο χάρτη web σας για να συνεχίσετε.",
            invalidWebmapSelectionAlert2: "Για περισσότερες πληροφορίες, ανατρέξτε στο άρθρο ${openLink}Τι είναι η υπηρεσία χαρακτηριστικών;${closeLink}",
            selectFieldsText: "Επιλογή πεδίων φόρμας",
            selectThemeText: "Επιλογή θέματος φόρμας",
            webmapText: "Χάρτης web",
            layerText: "Επίπεδο",
            detailsText: "Λεπτομέρειες",
            fieldsText: "Πεδία",
            styleText: "Στυλ",
            optionText: "Επιλογές",
            previewText: "Προεπισκόπηση",
            publishText: "Δημοσίευση",
            optionsApplicationText: "Επιλογές",
            titleText: "Εργαλείο δημιουργίας",
            descriptionText: "Το GeoForm είναι ένα πρότυπο με δυνατότητα διαμόρφωσης για επεξεργασία δεδομένων βάσει φόρμας μιας ${link1}υπηρεσίας χαρακτηριστικών${closeLink}. Η εφαρμογή αυτή επιτρέπει στους χρήστες να εισάγουν δεδομένα μέσω μιας φόρμας αντί ενός αναδυόμενου παραθύρου του χάρτη, αξιοποιώντας παράλληλα την ισχύ του ${link2}χάρτη web${closeLink} και των επεξεργάσιμων υπηρεσιών χαρακτηριστικών. Ακολουθήστε τα παρακάτω βήματα για να προσαρμόσετε και να υλοποιήσετε το GeoForm σας.",
            btnPreviousText: "Προηγούμενο",
            btnNextText: "Επόμενο",
            webmapTabTitleText: "Επιλέξτε έναν χάρτη web",
            viewWebmap: "Προβολή χάρτη web",
            webmapDetailsText: "Ο επιλεγμένος χάρτης web είναι ${webMapTitleLink}${webMapTitle}${closeLink}. Για να επιλέξετε έναν διαφορετικό χάρτη web, κάντε κλικ στο κουμπί \'Επιλογή χάρτη web\'",
            btnSelectWebmapText: "Επιλογή χάρτη web",
            btnSelectWebmapTextLoading: "Φόρτωση&hellip;",
            layerTabTitleText: "Επιλογή επεξεργάσιμου επιπέδου",
            selectLayerLabelText: "Επίπεδο",
            selectLayerDefaultOptionText: "Επιλογή επιπέδου",
            defaultBasemap: "Đ_Default Basemap_ớ",
            secondaryBasemap: "Đ_Secondary Basemap_ớ",
            detailsTabTitleText: "Λεπτομέρειες φόρμας",
            detailTitleLabelText: "Τίτλος",
            detailLogoLabelText: "Εικόνα λογοτύπου",
            descriptionLabelText: "Οδηγίες και λεπτομέρειες φόρμας",
            fieldDescriptionLabelText: "Κείμενο βοήθειας (προαιρετικό)",
            fieldTabFieldHeaderText: "Πεδίο",
            fieldTabLabelHeaderText: "Ετικέτα",
            fieldTabDisplayTypeHeaderText: "Εμφάνιση ως",
            fieldTabOrderColumnText: "Σειρά",
            fieldTabVisibleColumnText: "Ενεργοποιημένες",
            selectMenuOption: "Μενού επιλογής",
            selectRadioOption: "Κουμπί επιλογής",
            selectTextOption: "Κείμενο",
            selectDateOption: "Επιλογή ημερομηνίας",
            selectRangeOption: "Πλαίσιο αυξομείωσης αφής",
            selectCheckboxOption: "Πλαίσιο ελέγχου",
            selectMailOption: "Email",
            selectUrlOption: "URL",
            selectTextAreaOption: "Περιοχή κειμένου",
            previewApplicationText: "Προεπισκόπηση εφαρμογής",
            saveApplicationText: "Αποθήκευση εφαρμογής",
            saveText: "Αποθήκευση",
            toggleNavigationText: "Εναλλαγή πλοήγησης",
            formPlaceholderText: "Η φόρμα μου",
            shareBuilderInProgressTitleMessage: "Δημοσίευση του GeoForm",
            shareBuilderProgressBarMessage: "Περιμένετε&hellip;",
            shareBuilderTitleMessage: "Επιτυχία! Το στοιχείο αποθηκεύτηκε",
            shareBuilderTextMessage: "Μπορείτε να αρχίσετε να συλλέγετε πληροφορίες με κοινοποίηση σε άλλους",
            shareModalFormText: "Σύνδεση φόρμας",
            shareBuilderSuccess: "Το GeoForm σας έχει ενημερωθεί και δημοσιευτεί!",
            geoformTitleText: "GeoForm",
            layerTabText: "Αυτό είναι το επίπεδο από το οποίο θα δημιουργηθεί το GeoForm. Το επίπεδο πρέπει να είναι μια υπηρεσία χαρακτηριστικών που είναι ενεργοποιημένη για επεξεργασία με δικαιώματα κοινοποίησης κατάλληλα για το κοινό σας.",
            detailsTabText: "Χρησιμοποιήστε τα πλαίσια Λεπτομέρειες φόρμας παρακάτω για να προσαρμόσετε τον τίτλο, να προσθέσετε ένα προσαρμοσμένο λογότυπο και να καταχωρίσετε μια σύντομη περιγραφή για το κοινό του GeoForm σας. Στην περιγραφή μπορείτε να προσθέσετε συνδέσεις για άλλους πόρους, στοιχεία επικοινωνίας, ακόμη και να κατευθύνετε το κοινό σας σε μια εφαρμογή χαρτογράφησης web που παρουσιάζει όλα τα δεδομένα που συλλέγονται με το GeoForm.",
            fieldsTabText: "Εδώ μπορείτε να επιλέξετε ποια πεδία θα είναι ορατά στο κοινό του GeoForm σας, να επεξεργαστείτε τις ετικέτες που θα βλέπει και να προσθέσετε μια σύντομη περιγραφή για να διευκολύνετε την εισαγωγή δεδομένων.",
            styleTabText: "Διαμορφώστε το GeoForm σας χρησιμοποιώντας τα παρακάτω θέματα με βάση τις προτιμήσεις σας.",
            publishTabText: "Εάν έχετε ολοκληρώσει την προσαρμογή του GeoForm σας, αποθηκεύστε την εφαρμογή και αρχίστε να την κοινοποιείτε στο κοινό σας. Μπορείτε οποιαδήποτε στιγμή να επιστρέψετε σε αυτό το εργαλείο δημιουργίας και να συνεχίσετε την προσαρμογή με βάση τις παρατηρήσεις.",
            headerSizeLabel:"Μέγεθος κεφαλίδας",
            smallHeader: "Χρήση μικρής κεφαλίδας",
            bigHeader: "Χρήση μεγάλης κεφαλίδας",
            pushpinText: "Πινέζα",
            doneButtonText: "Αποθήκευση και έξοδος",
            fieldTabPlaceHolderHeaderText: "Υπόδειξη (προαιρετικά)",
            enableAttachmentLabelText: "${openStrong}Ενεργοποίηση συνημμένων${closeStrong}",
            enableAttachmentLabelHint: "Μπορείτε να ενεργοποιήσετε/απενεργοποιήσετε τα συνημμένα εδώ",
            attachmentIsRequiredLabelText: "${openStrong}Απαιτείται συνημμένο${closeStrong}",
            attachmentIsRequiredLabelHint: "Εάν χρειάζεται, μπορεί να ζητηθεί από τους χρήστες να εισαγάγουν ένα συνημμένο.",
            attachmentLabelText: "Ετικέτα κουμπιού Συνημμένο",
            attachmentLabelHint: "Αυτό είναι το κείμενο που θα εμφανίζεται δίπλα στο κουμπί Συνημμένο. Μπορείτε να χρησιμοποιήσετε αυτόν το χώρο για να περιγράψετε τι θέλετε να επισυνάψει το κοινό σας (φωτογραφία, βίντεο, έγγραφο κ.λπ.), τη μορφή αρχείου που ζητάτε (.jpeg, .png, .docx, .pdf κ.λπ.) και τυχόν πρόσθετες οδηγίες.",
            attachmentDescription: "Περιγραφή συνημμένου",
            attachmentHint: "Εάν χρειάζεται, μπορείτε να δώσετε πρόσθετες οδηγίες σχετικά με τα συνημμένα εδώ.",
            jumbotronDescription: "Χρησιμοποιήστε μεγάλη ή μικρή κεφαλίδα για τη φόρμα σας. Μια μεγάλη κεφαλίδα μπορεί να βοηθάει στον καθορισμό του σκοπού της εφαρμογής σας, αλλά καταλαμβάνει περισσότερο χώρο στην οθόνη σας",
            shareGeoformText: "Κοινοποίηση του GeoForm",
            shareDescription: "Το πλαίσιο κοινοποίησης διευκολύνει το κοινό σας να κοινοποιεί το GeoForm σε άλλους συνεργάτες αφού πραγματοποιήσουν μια υποβολή - αυτό μπορεί να απενεργοποιηθεί οποιαδήποτε στιγμή.",
            defaultMapExtent: "Προεπιλεγμένη έκταση χάρτη",
            defaultMapExtentDescription: "Θα γίνει επαναφορά του χάρτη στην προεπιλεγμένη έκταση στο χάρτη web σας μετά την υποβολή - αυτό μπορεί να απενεργοποιηθεί οποιαδήποτε στιγμή.",
            pushpinOptionsDescription: "Επιλέξτε από μια ποικιλία χρωμάτων για την πινέζα του χάρτη, θα πρέπει να διαφέρει από τα σύμβολα του χάρτη για να τοποθετεί εύκολα ο χρήστης την υποβολή του στο χάρτη",
            selectLocationText: "Επιλογή τοποθεσίας με βάση",
            myLocationText: "Η τοποθεσία μου",
            searchText: "Αναζήτηση",
            coordinatesText: "Συντεταγμένες γεωγραφικού πλάτους και μήκους",
            usng: "Συντεταγμένες USNG",
            mgrs: "Συντεταγμένες MGRS",
            utm: "Συντεταγμένες UTM",
            selectLocationSDescription: "Δώστε τη δυνατότητα στους χρήστες να επιλέξουν μια τοποθεσία χρησιμοποιώντας αυτές τις μεθόδους.",
            dragTooltipText:"Σύρετε το πεδίο εκεί που θέλετε να εμφανίζετε",
            showHideLayerText: "Đ_Show Layer_ớ",
            showHideLayerHelpText: "Μπορείτε να διαμορφώσετε το GeoForm ώστε να γίνεται εμφάνιση/απόκρυψη επιπέδου",
            labelHelpMessage: "Đ_Label_ớ",
            placeHolderHintMessage: "Đ_Hint Text_ớ",
            placeHolderHelpMessage: "Đ_Help Text_ớ",
            selectTextOptionValue: "Đ_Filter Select_ớ",
            disableLogo: "Đ_Disable Logo_ớ",
            disableLogoDescription: "Đ_You can configure the GeoForm to Show/Hide Logo in the form header_ớ",
            locateOnLoadText: "Đ_Locate On Load_ớ",
            locateOnLoadDescription: "Đ_You can configure the GeoForm to locate the current location on form load_ớ"
        }
    })
);