define({
  root: ({
    layer: "Đ_Layer___ớ",
    sort: "Đ_Sort by___ớ",
    order: "Đ_Order___ớ",
    desc: "Đ_Desc__ớ",
    asc: "Đ_Asc__ớ",
    loading: "Đ_loading&hellip;______ớ",
    search: "Đ_Search___ớ",
    searchPlaceholder: "Đ_Find reports_____ớ",
    noResults: "Đ_No results____ớ",
    ascending: "Đ_Ascending____ớ",
    descending: "Đ_Descending____ớ"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});