define(
     ({
        map: {
            error: "Không thể tạo bản đồ"
        },
        onlineStatus: {
            offline: "Bạn hiện đang làm việc ngoại tuyến. Biểu mẫu đã đệ trình sẽ được lưu cục bộ cho đến khi có kết nối tới máy chủ.",
            reconnecting: "Đang kết nối lại&hellip;",
            pending: "á»‡_${total} pending edit(s) will be submitted when a network connection is re-established_á»."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Tổ chức của tôi",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Nội dung của tôi",
                    favoritesLabel: "Yêu thích của tôi"
                },
                title: "Chọn Bản đồ Web",
                searchTitle: "Tìm kiếm",
                ok: "Ok",
                cancel: "Hủy",
                placeholder: "Nhập cụm từ tìm kiếm"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Tổ chức của tôi",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Nội dung của tôi",
                    favoritesLabel: "Yêu thích của tôi"
                },
                title: "Chọn Nhóm",
                searchTitle: "Tìm kiếm",
                ok: "Ok",
                cancel: "Hủy",
                placeholder: "Nhập cụm từ tìm kiếm"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "á»‡_Here is a link to a GeoForm_á»"
            }
        },
        user: {
            mgrs: "á»‡_MGRS_á»",
            usng: "á»‡_USNG_á»",
            utm: "á»‡_UTM_á»",
            utm_northing: "á»‡_Northing_á»",
            utm_easting: "á»‡_Easting_á»",
            utm_zone_number: "á»‡_Zone Number_á»",
            geoFormGeneralTabText: "á»‡_1. Enter Information_á»",
            locationInformationText: "á»‡_2. Select Location_á»",
            submitInformationText: "á»‡_3. Complete Form_á»",
            submitInstructions: "á»‡_Add this information to the map_á».",
            myLocationText: "á»‡_Current Location_á»",
            locationDescriptionForMoreThanOneOption: "á»‡_Specify the location for this entry by clicking/tapping the map or by using one of the following options_á».",
            locationDescriptionForOneOption: "á»‡_Specify the location for this entry by clicking/tapping the map or by using the following option_á».",
            locationDescriptionForNoOption: "á»‡_Specify the location for this entry by clicking/tapping the map_á».",
            addressText: "á»‡_Search_á»",
            geographic: "á»‡_Lat/Lon_á»",
            locationTabText: "á»‡_Location_á»",
            locationPopupTitle: "á»‡_Location_á»",
            submitButtonText: "á»‡_Submit Entry_á»",
            submitButtonTextLoading: "á»‡_Submitting&hellip;_á»",
            formValidationMessageAlertText: "á»‡_The following fields are required_á»:",
            selectLocation: "á»‡_Please select a location for your submission_á».",
            emptylatitudeAlertMessage: "á»‡_Please enter a ${openLink}latitude${closeLink} coordinate_á».",
            emptylongitudeAlertMessage: "á»‡_Please enter a ${openLink}longitude${closeLink} coordinate_á».",
            shareUserTitleMessage: "á»‡_Thank you for your contribution_á»!",
            entrySubmitted: "á»‡_Your entry has been submitted to the map_á».",
            shareThisForm: "á»‡_Share This Form_á»",
            shareUserTextMessage: "á»‡_Tell others to contribute using the following options_á».",
            addAttachmentFailedMessage: "á»‡_Unable to add attachment to layer_á»",
            addFeatureFailedMessage: "á»‡_Unable to add feature to layer_á»",
            noLayerConfiguredMessage: "á»‡_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_á».",
            placeholderLatitude: "á»‡_Latitude (Y)_á»",
            placeholderLongitude: "á»‡_Longitude (X)_á»",
            latitude: "á»‡_Latitude_á»",
            longitude: "á»‡_Longitude_á»",
            findMyLocation: "á»‡_Locate Me_á»",
            finding: "á»‡_Locating&hellip;_á»",
            backToTop: "á»‡_Back to top_á»",
            addressSearchText: "á»‡_Your submission will appear here. You can drag the pin to correct the location_á».",
            shareModalFormText: "á»‡_Form Link_á»",
            close: "á»‡_Close_á»",
            locationNotFound: "á»‡_Location could not be found_á».",
            setLocation: "á»‡_Set Location_á»",
            find: "á»‡_Find address or place_á»",
            attachment: "á»‡_Attachment_á»",
            toggleDropdown: "á»‡_Toggle Dropdown_á»",
            invalidString: "á»‡_Please enter valid value_á».",
            invalidSmallNumber: "á»‡_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_á».",
            invalidNumber: "á»‡_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_á».",
            invalidFloat: "á»‡_Please enter valid ${openStrong}floating point${closeStrong} value_á».",
            invalidDouble: "á»‡_Please enter valid ${openStrong}double${closeStrong} value_á».",
            invalidLatLong: "á»‡_Please enter valid latitude and longitude coordinates_á».",
            invalidUTM: "á»‡_Please enter valid UTM coordinates_á».",
            invalidUSNG: "á»‡_Please enter valid USNG coordinates_á».",
            invalidMGRS: "á»‡_Please enter valid MGRS coordinates_á».",
            geoformTitleText: "á»‡_GeoForm_á»",
            domainDefaultText: "á»‡_Select&hellip;_á»",
            applyEditsFailedMessage: "á»‡_Sorry your entry cannot be submitted. Please try again_á».",
            requiredFields: "á»‡_There are some errors. Please correct them below_á».",
            requiredField: "á»‡_(required)_á»",
            error: "á»‡_Error_á»",
            textRangeHintMessage: "á»‡_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_á»",
            dateRangeHintMessage: "á»‡_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_á»",
            remainingCharactersHintMessage: "á»‡_${value} characters remaining_á»"
        },
        builder: {
            invalidUser: "á»‡_Sorry, you dont have permission to view this item_á»",
            invalidWebmapSelectionAlert: "á»‡_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_á».",
            invalidWebmapSelectionAlert2: "á»‡_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_á»",
            selectFieldsText: "á»‡_Select Form Fields_á»",
            selectThemeText: "á»‡_Select Form Theme_á»",
            webmapText: "á»‡_Webmap_á»",
            layerText: "á»‡_Layer_á»",
            detailsText: "á»‡_Details_á»",
            fieldsText: "á»‡_Fields_á»",
            styleText: "á»‡_Style_á»",
            optionText: "á»‡_Options_á»",
            previewText: "á»‡_Preview_á»",
            publishText: "á»‡_Publish_á»",
            optionsApplicationText: "á»‡_Options_á»",
            titleText: "á»‡_Builder_á»",
            descriptionText: "á»‡_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_á».",
            btnPreviousText: "á»‡_Previous_á»",
            btnNextText: "á»‡_Next_á»",
            webmapTabTitleText: "á»‡_Select a Webmap_á»",
            viewWebmap: "á»‡_View webmap_á»",
            webmapDetailsText: "á»‡_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_á»",
            btnSelectWebmapText: "á»‡_Choose Webmap_á»",
            btnSelectWebmapTextLoading: "á»‡_Loading&hellip;_á»",
            layerTabTitleText: "á»‡_Select Editable Layer_á»",
            selectLayerLabelText: "á»‡_Layer_á»",
            selectLayerDefaultOptionText: "á»‡_Select Layer_á»",
            detailsTabTitleText: "á»‡_Form Details_á»",
            detailTitleLabelText: "á»‡_Title_á»",
            detailLogoLabelText: "á»‡_Logo Image_á»",
            descriptionLabelText: "á»‡_Form Instructions & Details_á»",
            fieldDescriptionLabelText: "á»‡_Help Text (optional)_á»",
            fieldTabFieldHeaderText: "á»‡_Field_á»",
            fieldTabLabelHeaderText: "á»‡_Label_á»",
            fieldTabDisplayTypeHeaderText: "á»‡_Display As_á»",
            fieldTabOrderColumnText: "á»‡_Order_á»",
            fieldTabVisibleColumnText: "á»‡_Enabled_á»",
            selectMenuOption: "á»‡_Select Menu_á»",
            selectRadioOption: "á»‡_Radio Button_á»",
            selectTextOption: "á»‡_Text_á»",
            selectDateOption: "á»‡_Date Picker_á»",
            selectRangeOption: "á»‡_Touch-Spinner_á»",
            selectCheckboxOption: "á»‡_Checkbox_á»",
            selectMailOption: "á»‡_Email_á»",
            selectUrlOption: "á»‡_URL_á»",
            selectTextAreaOption: "á»‡_Text Area_á»",
            previewApplicationText: "á»‡_Preview Application_á»",
            saveApplicationText: "á»‡_Save Application_á»",
            saveText: "á»‡_Save_á»",
            toggleNavigationText: "á»‡_Toggle navigation_á»",
            formPlaceholderText: "á»‡_My Form_á»",
            shareBuilderInProgressTitleMessage: "á»‡_Publishing GeoForm_á»",
            shareBuilderProgressBarMessage: "á»‡_Please Wait&hellip;_á»",
            shareBuilderTitleMessage: "á»‡_Success! Item saved_á»",
            shareBuilderTextMessage: "á»‡_You can start collecting information by sharing with others_á»",
            shareModalFormText: "á»‡_Form Link_á»",
            shareBuilderSuccess: "á»‡_Your GeoForm has been updated & published_á»!",
            geoformTitleText: "á»‡_Geo Form_á»",
            layerTabText: "á»‡_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_á».",
            detailsTabText: "á»‡_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_á».",
            fieldsTabText: "á»‡_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_á».",
            styleTabText: "á»‡_Style your GeoForm using the themes below based on your preference_á».",
            publishTabText: "á»‡_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_á».",
            headerSizeLabel:"á»‡_Header Size_á»",
            smallHeader: "á»‡_Use Small Header_á»",
            bigHeader: "á»‡_Use Large Header_á»",
            pushpinText: "á»‡_Push pin_á»",
            doneButtonText: "á»‡_Save and Exit_á»",
            fieldTabPlaceHolderHeaderText: "á»‡_Hint (optional)_á»",
            enableAttachmentLabelText: "á»‡_${openStrong}Enable Attachments${closeStrong}_á»",
            enableAttachmentLabelHint: "á»‡_You can enable/disable the attachments here_á»",
            attachmentIsRequiredLabelText: "á»‡_${openStrong}Attachment Required${closeStrong}_á»",
            attachmentIsRequiredLabelHint: "á»‡_If necessary, users can be required to enter an attachment_á».",
            attachmentLabelText: "á»‡_Attachment Button Label_á»",
            attachmentLabelHint: "á»‡_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_á»",
            attachmentDescription: "á»‡_Attachment Description_á»",
            attachmentHint: "á»‡_If necessary, you can provide additional attachment instructions here_á».",
            jumbotronDescription: "á»‡_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_á»",
            shareGeoformText: "á»‡_Share Geoform_á»",
            shareDescription: "á»‡_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_á».",
            defaultMapExtent: "á»‡_Default Map Extent_á»",
            defaultMapExtentDescription: "á»‡_The map will reset to the default extent in your web map after submission - this can be disabled at any time_á».",
            pushpinOptionsDescription: "á»‡_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_á»",
            selectLocationText: "á»‡_Select Location By_á»",
            myLocationText: "á»‡_My Location_á»",
            searchText: "á»‡_Search_á»",
            coordinatesText: "á»‡_Latitude & Longitude Coordinates_á»",
            usng: "á»‡_USNG Coordinates_á»",
            mgrs: "á»‡_MGRS Coordinates_á»",
            utm: "á»‡_UTM Coordinates_á»",
            selectLocationSDescription: "á»‡_Allow users to select a location using these methods_á».",
            dragTooltipText:"á»‡_Drag the field where you want it to appear_á»",
            showHideLayerText:"á»‡_Show/Hide Layer_á»",
            showHideLayerHelpText:"á»‡_You can configure the GeoForm to Show/Hide Layer_á»"
        }
    })
);