define(
	 ({
		header: {
			start: "æ_start___Â",
			searchStories: "æ_Search your stories________Â...",
			filter: "æ_Filter___Â",
			sort: "æ_Sort__Â",
			sortColon: "æ_Sort___Â:",
			numResults: "æ_Results: {{NUM_RESULTS}}________Â",
			sortBy: "æ_Sort by___Â",
			dateModified: "æ_Date modified_____Â",
			title: "æ_Title___Â",
			type: "æ_Type__Â",
			views: "æ_Views___Â",
			errors: "æ_Errors___Â",
			filterBy: "æ_Filter by____Â",
			filterItems: "æ_Filter Items_____Â",
			apps: "æ_Apps__Â",
			sharing: "æ_Sharing___Â",
			clearAll: "æ_Clear all____Â",
			clearSearch: "æ_Clears the search______Â",
			logOut: "æ_Log Out___Â",
			mainQuote: "æ_Storytelling is the most powerful way to put ideas into the world today_______________________Â.",
			quoteSource: "æ_Robert McKee_____Â",
			checkYourStories: "æ_Check Stories_____Â",
			createStory: "æ_Create Story_____Â",
			totalStories: "æ_Total stories: {{NUM_STORIES}}__________Â",
			noIssues: "æ_All good___Â",
			userStories: "æ_Stories of {{USER_NAME}}________Â",
			headerDisabledTooltip: "æ_Please wait while we work some magic_____________Â...",
			notOnTouch: "æ_Not available on touch devices__________Â",
		},
		deleteModal: {
			title: "æ_Confirm Delete_____Â",
			warningText: "æ_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________Â.",
			deleteText: "æ_Delete___Â",
			cancel: "æ_Cancel___Â"
		},
		loading: {
			loadingText: "æ_Loading your stories________Â..."
		},
		cantFindStories: {
			whereAreStories: "æ_Not seeing your story________Â?",
			notSeeExplanation: "æ_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________Â.",
			faq: "æ_FAQ__Â",
			followingStoriesToUpdate: "æ_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________Â:",
			gettingStories: "æ_Searching for stories created with early versions of our applications that need to be updated______________________________Â...",
			title: "æ_Title___Â",
			typeOfStoryMap: "æ_Type__Â",
			lastModified: "æ_Last modified_____Â",
			allUpToDate: "æ_No stories created with early versions of our applications need to be updated________________________Â.",
			updateAll: "æ_Update All____Â",
			errorScanningForStories: "æ_There was an error searching your stories______________Â.",
			close: "æ_Close___Â",
			updates: "æ_Updates___Â",
			updatingNumberOfNumber: "æ_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________Â",
			updatingNumberOfNumberAlt: "æ_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________Â",
			updateSucceeded: "æ_Update succeeded______Â!",
			reloadingStories: "æ_Reloading your stories_________Â...",
			errorUpdatingStories: "æ_There was an error updating your stories_____________Â.",
			partialUpdateMessage: "æ_Stories updated successfully: {{NUM_UPDATED}}_______________Â"
		},
		signIn: {
			signInTitle: "æ_Sign in to Story Maps_______Â",
			signInTo: "æ_Sign in with your existing ArcGIS Online account to_________________Â:",
			explanationOne: "æ_Create compelling story maps to tell your stories________________Â.",
			explanationTwo: "æ_Use your maps and data from ArcGIS Online in your story maps___________________Â.",
			explanationThree: "æ_Manage your story maps and check the status of their content___________________Â.",
			dontHaveAccount: "æ_Don't have an ArcGIS Online account? Sign up for a________________Â:",
			publicAccount: "æ_Free non-commercial public account___________Â",
			orgAccount: "æ_Free trial ArcGIS subscription__________Â",
			timeExpired: "æ_Your sign-in expired. Sign in again to pick up where you left off_____________________Â.",
			apiDidntLoad: "æ_Something isn't loading correctly. Try refreshing the page___________________Â.",
			needAccount: "æ_Need an account______Â?",
			letsGo: "æ_Let's go____Â!"
		},
		sharingLevel: {
			publicMessage: "æ_Public___Â",
			privateMessage: "æ_Private___Â",
			organization: "æ_Organization_____Â",
			changedSharing: "æ_Changed sharing level________Â.",
			unableToChange: "æ_Unable to change sharing_________Â.",
			partOfMap: "æ_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________Â.",
			storyPublicContentOrg: "æ_Your story is public, so its content can't be shared only with your organization_________________________Â",
			storyPublicContentPrivate: "æ_Your story is public, so its content can't be private_________________Â",
			mapOrg: "æ_Sharing your map to your organization would break your story___________________Â",
			layerOrg: "æ_Sharing your layer to your organization would break your story____________________Â",
			mapPrivate: "æ_Making your map private would break your story_______________Â",
			layerPrivate: "æ_Making your layer private would break your story_______________Â"
		},
		collectionList: {
			advocacy: "æ_Advocacy and Outreach_______Â",
			architecture: "æ_Architecture and Design________Â",
			conservation: "æ_Conservation and Sustainability__________Â",
			culture: "æ_Culture___Â",
			destinations: "æ_Destinations and Tourism________Â",
			disasters: "æ_Disasters and Recovery________Â",
			economy: "æ_Economy and Development________Â",
			entertainment: "æ_Entertainment_____Â",
			history: "æ_History___Â",
			infrastructure: "æ_Infrastructure_____Â",
			marketing: "æ_Marketing____Â",
			nature: "æ_Nature and Environment________Â",
			news: "æ_News and Events______Â",
			oceans: "æ_Oceans___Â",
			parks: "æ_Parks and Recreation_______Â",
			people: "æ_People and Society______Â",
			planning: "æ_Planning and Analysis_______Â",
			publicArt: "æ_Public Art____Â",
			science: "æ_Science and Technology________Â",
			sport: "æ_Sport___Â",
			travelogues: "æ_Travelogues____Â"
		},
		types: {
			custom: "æ_Custom___Â",
			notSpecified: "æ_Type not specified______Â"
		},
		storyMap: {
			shared: "æ_Shared___Â",
			saveFailed: "æ_Error saving_____Â",
			numViews: "æ_Views: {{NUM_VIEWS}}_______Â",
			editStory: "æ_Edit Story____Â",
			viewLive: "æ_View Live____Â",
			preview: "æ_Preview___Â",
			deleteButton: "æ_Delete___Â",
			modified: "æ_Modified {{DATE}}______Â",
			summary: "æ_Summary___Â",
			loading: "æ_Loading____Â...",
			collapse: "æ_collapse___Â",
			close: "æ_close___Â",
			hide: "æ_hide__Â",
			notAvailableWhenBroken: "æ_Your story has issues below_________Â",
			cantBeDeleted: "æ_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________Â",
			shareDialog: {
				title: "æ_Share your story with the world___________Â!",
				notPublicWarning: "æ_Your story is shared with your organization. Only members of your organization will be able to view it________________________________Â.",
				embedStory: "æ_Embed your story______Â",
				shortLink: "æ_Shortlink____Â",
				hideHeaderBar: "æ_Hide header bar______Â",
				copied: "æ_Copied___Â",
				small: "æ_small___Â",
				medium: "æ_medium___Â",
				large: "æ_large___Â",
				custom: "æ_custom___Â",
				widthAbbreviation: "æ_w_Â",
				heightAbbreviation: "æ_h_Â",
				emptyDimension: "æ_Enter a dimension______Â.",
				seeExample: "æ_Preview your embed______Â",
				removeHeader: "æ_Hide application header________Â"
			},
			maps: {
				unableRetrieveTitle: "æ_Unable to retrieve maps________Â",
				unableRetrieveDescription: "æ_We weren't able to retrieve maps for this story map_________________Â."
			},
			images: {
				unableRetrieveTitle: "æ_Unable to retrieve images_________Â",
				unableRetrieveDescription: "æ_We weren't able to retrieve images for this story map_________________Â."
			},
			tags: {
				tags: "æ_Tags__Â",
				collectionTags: "æ_Subject___Â",
				selectASubject: "æ_Select a subject______Â",
				save: "æ_Save__Â",
				saved: "æ_Saved___Â",
				errorSaving: "æ_Error saving_____Â",
				tagTip: "æ_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________Â."
			},
			submitToGallery: {
				gallerySubmission: "æ_Story Maps Gallery______Â",
				canSubmitIf: "æ_You can nominate your story to the gallery if it contains the following_______________________Â:",
				hasOwnImage: "æ_Custom thumbnail______Â",
				chosenSubject: "æ_A subject and some tags________Â",
				chosenSubjectAlt: "æ_A {{SUBJECT}} and some tags_________Â",
				storyMapTopicSubject: "æ_subject___Â",
				sharedPublicly: "æ_Shared publicly______Â",
				noBrokenContent: "æ_No broken content______Â",
				nominateToGallery: "æ_Nominate to Gallery_______Â",
				comingSoon: "æ_Coming soon_____Â!",
				submitted: "æ_Submitted____Â",
				errorSubmitting: "æ_Error submitting______Â",
				ourGallery: "æ_The Story Maps gallery________Â",
				galleryTip: "æ_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________Â."
			},
			placeholders: {
				noSummary: "æ_No summary, click to add one__________Â."
			},
			errors: {
				cantDeleteStory: "æ_Unable to delete story________Â.",
				unableToFind: "æ_Unable to find content________Â",
				unableToRetrieve: "æ_We weren't able to retrieve the content for this story map___________________Â."
			},
			socialSharing: {
				availableWhenPublic: "æ_This option will be available when your story is public__________________Â"
			},
			dialog: {
				back: "æ_Back__Â",
				close: "æ_Close___Â",
				cancel: "æ_Cancel___Â"
			},
			imagePicker: {
				changeDefault: "æ_Change the default image________Â",
				changeImage: "æ_Change thumbnail______Â",
				uploadImage: "æ_Upload thumbnail______Â",
				chooseImage: "æ_Choose thumbnail______Â",
				chooseAnImage: "æ_Choose an Image______Â",
				notInIEVersion: "æ_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________Â.",
				or: "æ_Or__Â",
				uploadAnImage: "æ_Upload an Image______Â",
				supportedFileTypes: "æ_Supports .png, .jpg, .gif_________Â",
				imageSizeMessage: "æ_Your image needs to be at least 286 px wide by 190 px tall___________________Â.",
				minimumDimensions: "æ_Minimum: 286 x 190px_______Â",
				imagesLoading: "æ_Loading images______Â...",
				noImages: "æ_This story has no images________Â",
				errorLoading: "æ_Unable to retrieve the images in this story______________Â",
				clickBelowTip: "æ_Click the button below to upload an image______________Â.",
				dragAndDrop: "æ_Drag and Drop_____Â",
				cropImage: "æ_Crop Image____Â",
				saveImage: "æ_Save Image____Â",
				save: "æ_Save__Â",
				savingImage: "æ_Saving your image_______Â...",
				saved: "æ_Saved___Â!",
				errorSaving: "æ_Unable to save your image_________Â.",
				skipAndCrop: "æ_Skip and Crop for me_______Â",
				wrongFormat: "æ_This file type is not supported___________Â.",
				noCropWarning: "æ_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________Â."
			}
		},
		content: {
			media: {
				maps: "æ_Maps__Â",
				images: "æ_Images___Â",
				videos: "æ_Videos___Â",
				webpages: "æ_Webpages___Â",
				tags: "æ_Tags__Â",
				gallery: "æ_Gallery___Â"
			},
			headers: {
				status: "æ_Status___Â",
				source: "æ_Source___Â",
				name: "æ_Name__Â",
				shared: "æ_Shared___Â"
			},
			component: {
				mapTour: "æ_Point Number_____Â",
				bullet: "æ_Bullet___Â",
				tab: "æ_Tab__Â",
				accordion: "æ_Section___Â",
				mapJournal: "æ_Section___Â"
			},
			titleType: {
				mapTour: "æ_Caption___Â",
				mapJournal: "æ_URL__Â",
				mapSeries: "æ_URL__Â"
			},
			actions: {
				viewMap: "æ_View Map___Â",
				editMap: "æ_Edit Map___Â",
				fix: "æ_Fix__Â",
				viewLayer: "æ_View Layer____Â"
			},
			contentType: {
				mainStage: "æ_main stage action______Â",
				sidePanel: "æ_description____Â"
			},
			notification: {
				refreshExplanation: "æ_Check your story again________Â",
				checking: "æ_Checking____Â...",
				foundSomeIssues: "æ_We found some issues_______Â",
				noIssuesFound: "æ_No issues found______Â",
				storyPublic: "æ_Your story is now public________Â",
				storyOrg: "æ_Your story is now shared to your organization_______________Â",
				storyPrivate: "æ_Your story is now private_________Â",
				mapPublic: "æ_Your map is now public________Â",
				mapOrg: "æ_Your map is now shared to your organization______________Â",
				mapPrivate: "æ_Your map is now private________Â",
				layerPublic: "æ_Your layer is now public________Â",
				layerOrg: "æ_Your layer is now shared to your organization_______________Â",
				layerPrivate: "æ_Your layer is now private_________Â",
				contentPublic: "æ_Your content is now public_________Â",
				contentOrg: "æ_Your content is now shared to your organization_______________Â",
				contentPrivate: "æ_Your content is now private_________Â",
				storyAndContentPublic: "æ_Your story and its content are now public_____________Â",
				storyAndContentOrg: "æ_Your story and its content are now shared to your organization____________________Â",
				storyAndContentPrivate: "æ_Your story and its content are now private______________Â",
				shareBulkPrompt: "æ_Do you want to share your storyâ€™s content accordingly__________________Â?",
				layersPublic: "æ_Some layers have also been shared publicly______________Â",
				layersOrg: "æ_Some layers have also been shared with your organization__________________Â",
				layersPrivate: "æ_Some layers have also been made private_____________Â",
				mapsPublic: "æ_Some maps have also been shared publicly_____________Â",
				mapsOrg: "æ_Some maps have also been shared with your organization_________________Â",
				mapsPrivate: "æ_Some maps have also been made private____________Â",
				layersAndMapsPublic: "æ_Some maps and layers have also been shared publicly________________Â",
				layersAndMapsOrg: "æ_Some maps and layers have also been shared with your organization_____________________Â",
				layersAndMapsPrivate: "æ_Some maps and layers have also been made private_______________Â",
				yes: "æ_Yes__Â",
				no: "æ_No__Â",
				premiumPublicSuccess: "æ_Your premium content is now publicly accessible_______________Â",
				subscriptionPublicSuccess: "æ_Your subscription content is now publicly accessible_________________Â"
			},
			errors: {
				publicDisabled: "æ_Sharing publicly has been disabled by the Administrator__________________Â",
				noMapName: "æ_Could Not Retrieve Map Name_________Â",
				notPublic: "æ_NOT PUBLIC____Â",
				inaccessible: "æ_INACCESSIBLE_____Â",
				deleted: "æ_DELETED___Â",
				cantAccessVideo: "æ_Could Not Access Video________Â",
				noStoriesFound: "æ_We could not find any Story Maps in your content________________Â.",
				cantShowStories: "æ_Unable to show your story maps. Please try again later__________________Â.",
				consolationSearch: "æ_We couldn't find any stories__________Â.",
				notCompatibleWithBrowser : "æ_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________Â.",
				pleaseUpdateBrowser: "æ_Please update your browser_________Â.",
				searchTip: "æ_Try and simplify it a bit_________Â.",
				consolationNoStories: "æ_Welcome to My Stories________Â!",
				noStoriesTip: "æ_To make your first story map, check out the Apps page_________________Â.",
				letsGo: "æ_Let's Go___Â",
				cantChangeSharingLevel: "æ_Unable to change sharing level__________Â",
				cantChangeSharingLevels: "æ_Unable to change sharing levels__________Â",
				errorUpdatingTitle: "æ_Error updating title_______Â",
				errorUpdatingSummary: "æ_Error updating summary________Â",
				noEmptyTitle: "æ_Title cannot be empty_______Â",
				cantUpdatePremiumContent: "æ_Unable to update premium content___________Â",
				cantUpdateSubscriptionContent: "æ_Unable to update subscription content____________Â",
				createFirstStory: "æ_Create My First Story_______Â"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "æ_Map has been deleted_______Â",
				layerHasBeenDeleted: "æ_Layer has been deleted________Â",
				mapIsInaccessible: "æ_Map is inaccessible_______Â",
				layerIsInaccessible: "æ_Layer is inaccessible_______Â",
				mapNotYoursNotAccessible: "æ_Map is owned by someone else and isn't accessible________________Â",
				layerServiceOkItemNot: "æ_Layer was added as an item that is deleted or inaccessible__________________Â",
				layerNotYoursNotAccessible: "æ_Layer is owned by someone else and isn't accessible________________Â",
				mapOthersSharedBelowLevel: "æ_Map is not owned by you and is not public_____________Â",
				layerOthersSharedBelowLevel: "æ_Layer is not owned by you and is not public______________Â",
				noMapNoDetails: "æ_Without the map details, we can't tell you anything about the layers_____________________Â",
				mapIsPrivate: "æ_Map is private_____Â",
				mapIsOrg: "æ_Map is only shared in your organization_____________Â",
				layerIsPrivate: "æ_Layer is private______Â",
				layerIsOrg: "æ_Layer is only shared in your organization_____________Â",
				imageInaccessible: "æ_This image is inaccessible_________Â",
				videoInaccessible: "æ_This video is inaccessible_________Â",
				webpageInaccessible: "æ_This web page is inaccessible__________Â",
				layerSecureService: "æ_Layer is a secure service_________Â",
				mapSecureService: "æ_Map is a secure service________Â",
				layerConsumesCredits: "æ_Layer is premium content and consumes credits_______________Â",
				layerSubscriptionContent: "æ_Layer is subscription content__________Â",
				mapConsumesCredits: "æ_Map is premium content and consumes credits______________Â",
				mapSubscriptionContent: "æ_Map is subscription content_________Â"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "æ_We're not able to check this type of layer______________Â",
				cantScanThisType: "æ_Layer is not a type of layer we can check_____________Â",
				webpageNotScanned: "æ_Webpages are not checked for issues____________Â"
			},
			scanningErrors: {
				deletedMap: "æ_Deleted content______Â",
				inaccessibleMap: "æ_Inaccessible map content________Â",
				notYoursNotAccessible: "æ_Content not owned by you and not public_____________Â",
				serviceOkItemNot: "æ_Working layers but inaccessible items____________Â",
				someContentNotPublic: "æ_Content not shared publicly_________Â",
				someContentPrivate: "æ_Private content______Â",
				othersSharedBelowLevel: "æ_Content not owned by you and not public_____________Â",
				premiumContent: "æ_Premium content______Â",
				subscriptionContent: "æ_Subscription content_______Â",
				secureService: "æ_Secure services______Â",
				inaccessibleImage: "æ_Inaccessible images_______Â",
				inaccessibleVideo: "æ_Inaccessible videos_______Â",
				inaccessibleWebpage: "æ_Inaccessible webpages_______Â"
			},
			scanningErrorTips: {
				deletedMapTip: "æ_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________Â.",
				inaccessibleMapTip: "æ_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________Â.",
				notYoursNotAccessibleTip: "æ_Tip: Open the web map and remove the layer or map from the story_____________________Â.",
				serviceOkItemNotTip: "æ_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________Â.",
				ignore: "æ_Ignore___Â",
				fix: "æ_Fix__Â",
				clickToShareOrg: "æ_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________Â.",
				clickToSharePublic: "æ_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________Â.",
				shareOrg: "æ_Share to your org______Â",
				sharePublicly: "æ_Share publicly_____Â",
				othersSharedBelowLevelTip: "æ_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________Â.",
				secureServiceTip: "æ_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________Â.",
				blogArticle: "æ_here__Â",
				premiumContentTip: "æ_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________Â.",
				premiumContentPublicTip: "æ_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________Â.",
				subscriptionContentTip: "æ_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________Â.",
				agolCredits: "æ_ArcGIS Online credits_______Â",
				credits: "æ_credits___Â",
				makePublic: "æ_Make public____Â",
				confirm: "æ_Confirm___Â",
				inaccessibleImageTip: "æ_Tip: Provide the missing image or remove the reference to it___________________Â.",
				inaccessibleVideoTip: "æ_Tip: Provide the missing video or remove the reference to it___________________Â.",
				inaccessibleWebpageTip: "æ_Tip: Provide the missing web page or remove the reference to it____________________Â."
			},
			removeLayer: {
				title: "æ_Fix Layer Issue______Â",
				layersWithIssue: "æ_Layers with this issue: {{NUM_WITH_ISSUE}}______________Â",
				issueExplanation: "æ_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________Â.",
				issueSolution: "æ_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________Â:",
				editMap: "æ_Edit Your Map_____Â",
				clickBelowWhenDone: "æ_When you have finished editing, click the button below__________________Â:",
				rescanAndClose: "æ_Rescan And Close______Â"
			},
			info: {
				ownedBy: "æ_This item is owned by {{USER_NAME}}____________Â",
				unknownUser: "æ_someone else_____Â",
				untitledSection: "æ_(Untitled section)______Â",
				introRecord: "æ_Introduction_____Â"
			},
			layers: {
				layersHeader: "æ_Layers___Â",
				noLayers: "æ_(No Layers)____Â",
				basemapParens: "æ_(basemap)____Â"
			},
			images: {
				thumbnails: "æ_Thumbnails____Â",
				thumbnail: "æ_Thumbnail____Â",
				thumbnailParens: "æ_(thumbnail)____Â"
			},
			general: {
				noTitle: "æ_(no title)____Â",
				loading: "æ_Loading____Â..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "æ_sections___Â",
				secondTitle: "æ_style___Â",
				secondValueA: "æ_side panel____Â",
				secondValueB: "æ_floating panel_____Â",
				thirdTitle: "æ_maps__Â"
			},
			mapTour: {
				firstTitle: "æ_tour points____Â",
				secondTitle: "æ_style___Â",
				secondValueA: "æ_integrated____Â",
				secondValueB: "æ_three-panel____Â",
				thirdTitle: "æ_basemap___Â",
				thirdValueLoading: "æ_Loading____Â...",
				thirdValueUnknown: "æ_unknown___Â"
			},
			mapSeries: {
				firstTitleA: "æ_bullets___Â",
				firstTitleB: "æ_sections___Â",
				firstTitleC: "æ_tabs__Â",
				secondTitle: "æ_style___Â",
				secondValueA: "æ_bulleted___Â",
				secondValueB: "æ_side accordion_____Â",
				secondValueC: "æ_tabbed___Â",
				thirdTitle: "æ_maps__Â"
			},
			swipeSpyglass: {
				firstTitle: "æ_points of interest______Â",
				secondTitle: "æ_style___Â",
				secondValueA: "æ_swipe___Â",
				secondValueB: "æ_spyglass___Â",
				thirdTitle: "æ_maps__Â"
			}
		},
		progress: {
			checkingStories: "æ_Checking your stories for issues____________Â...",
			stop: "æ_Stop__Â",
			exit: "æ_Exit__Â",
			dismiss: "æ_Dismiss___Â",
			done: "æ_Done___Â.",
			noStoriesWithIssuesLower: "æ_No issues found______Â!",
			storiesErrorFree: "æ_Looks like your stories are error-free____________Â",
			scanAllError: "æ_Unable to scan -- we couldn't retrieve one or more of your stories_____________________Â",
			scanProgress: "æ_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________Â",
			scanStopped: "æ_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________Â",
			storiesWithIssues: "æ_Stories with issues: {{NUM_STORIES}}____________Â"
		}
    })
);