define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Введите расстояние",
                    "layerName": "Введите имя слоя здесь"
                },
                "message": {
                    "analysisFailed": "Не удалось выполнить анализ.",
                    "errorOccurred": "Произошла некая ошибка.",
                    "layerAdded": "Слой успешно добавлен. ",
                    "enrichLayerNameError": "\'Имя слоя результата\' не должно содержать символы " + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Создание сервиса.. ",
                    "starting": "Начало",
                    "performingAnalysis": "Выполнение анализа..",
                    "checkLayerName": "Проверка имени слоя.. ",
                    "addingLayer": "Добавление слоя к веб-карте ",
                    "layerNameExist": "Имя слоя уже существует.",
                    "clickOnSave": " Щелкните кнопку \"Сохранить\", чтобы перезагрузить приложение.",
                    "clickOnOk": " Щелкните кнопку ОК, чтобы попробовать снова.",
                    "enterNumbersOnly": "Введенные значения некорректны",
                    "nofeatures": "В данном экстенте нет объектов",
                    "selectData": "Выберите данные для обогащения слоя.",
                    "resetVariableMessage": "Вы точно хотите сбросить переменную?",
                    "emptyTextFieldLayerName": "Введите имя слоя результата",
                    "createService":"Слой не создан.",
                    "sharingLayer":"Общий доступ к слою..",
                    "updateItemFailed": "Не удалось обновить. Попробуйте еще раз.",
                    "geoEnrichFailed": "Не удалось обогатить слой. Попробуйте еще раз.",
                    "shareFailed": "Не удалось настроить общий доступ к обогащенному слою. Попробуйте еще раз.",
                    "refreshServiceFailed": "Не удалось обновить слой. Попробуйте еще раз.",
                    "layerJsonFailed": "Не удалось создать JSON для слоя. Попробуйте еще раз.",
                    "addToWebmapFailed": "Не удалось добавить слой к карте. Попробуйте еще раз.",
                    "bufferAreaHelpText": "Введите значение меньше, чем ",
                    "invalidBufferInput": "Введенное значение некорректно.",
                    "emptyBufferInput": "Введите корректное значение."
                },
                "populationText": "Население",
                "housingText": "Домохозяйство",
                "businessText": "Бизнес",
                "variableListText": " переменные перечислены здесь:",
                "countrySelectTitle": "1. Выбрать расположение данных",
                "unitedStates": "США",
                "global": "Глобальные",
                "geoenrichDialogText": "Переменные для геообогащения",
                "viewVariablestext": "Посмотреть переменные",
                "backButtonText":"Назад",
                "customizeVariables": "Пользовательские переменные",
                "resetVariables": "Сбросить",
                "defineAreaTitle": "3. Определить область для обогащения",
                "currentMapExtent": "Использовать текущий экстент карты",
                "enrichLayerName": "4. Имя слоя результата",
                "lineDistanceText": "Линейное расстояние",
                "drivingTime": "Время в пути",
                "enrichButtonText": "Обогатить слой",
                "selectDataText": "2. Выбрать данные",
                "showCreditsText": "Показать кредиты",
                "variableCount": "Всего переменных ",
                "totalRecords": "Всего записей:",
                "cost": "Стоимость:",
                "showCreditsDialogText": "Показать кредиты",
                "nextButtonText": "Далее",
                "prevButtonText": "Предыдущий",
                "saveButtonText": "Сохранить",
                "ok": "OK"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 