define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Войти в Конструктор",
                "exitBuilderButtonText": "Выйти из Конструктора",
                "enterBuilderModeHelpText": "Войти в Режим конструктора для настройки приложения",
                "builderModeHelpText": "Режим шаблона конструктора",
                "webmapCaption": "Карта",
                "selectMapMessage": "Сейчас ${displaying} <b>${webmapTitle}</b><br/>Щелкните Выбрать карту, чтобы выбрать другую веб-карту",
                "loadMapMessage": "Выбрано <b>${webmapTitle}</b><br/>Щелкните Сохранить, чтобы использовать эту веб-карту",
                "changeWebmap": "Выбрать карту",
                "saveButtonText": "Сохранить",
                "webmapNextButtonText": "Далее ->",
                "previousButtonText":"Назад",
                "layerLabelText": "Слой",
                "noLayerFoundText": "Слой не найден",
                "selectLayer": "Выбрать слой",
                "applicationSettingText": "Настройки приложения",
                "summaryAttrAscendingOrderTooltip": "По возрастанию",
                "onStartLabel": "В начале",
                "selectVariableText": "Выбрать переменную",
                "selectVariableDropdown": "Выбрать переменную",
                "label":"Надпись",
                "sourceLinkText":"Ссылка на источник",
                "selectSubVariableText":"Выбрать суб-переменные",
                "subVariablePanelButtonText":"ГОТОВО",
                "onButtonLabel":"Вкл.",
                "offButtonLabel":"Выкл.",
                "appSettingsSaveCloseButtonText": "СОХРАНИТЬ И ЗАКРЫТЬ",
                "appSettingsTitleText":"Заголовок приложения",
                "appSettingsDescriptionText": "Описание приложения",
                "appSetingsRendererAreaText":"Отображаемая область",
                "shareText":"Общий доступ",
                "popupText": "Всплывающее окно",
                "basemapText":"Базовая карта",
                "cancel": "Отмена",
                "theme": "Тема",
                "zoomLevel": "Уровень масштаба",
                "existingValue": "Использовать существующие значения",
                "enrichLayer": "Обогатить слой",
                "imageLabel": "Как это работает ?",
                "clearData": "Очистить данные",
                "basemapSelectionText":"Выбор базовой карты",
                "secondaryBasemapText":"Вторичная базовая карта",
                "defaultBasemapText": "Базовая карта по умолчанию",
                "entireAreaButton": "Вся область",
                "entireAreaOnStartButton": "Вся область в начале",
                "aboutPanel": "Панель О программе",
                "legendPanel": "Панель Легенда",
                "layersPanel": "Панель Слои",
                "dataConfigurationButtonText": "Настройка данных",
                "savingChangesMessage": "Сохранение изменений...",
                "nextButtonText": "Далее",
                "prevButtonText": "Назад",
                "enterLabelText": "Введите надпись",
                "SelectedFeatureText": "Выбранный объект",
                "layerHelpTextMessage": "Приложению требуется слой с числовыми полями",
                "alertMessage": {
                    "resetVariableMessage": "Вы уверены, что хотите сбросить переменную?",
                    "emptyAppTitleMessage": "Заголовок приложения не может быть пустым",
                    "emptyDescriptionMessage": "Описание не может быть пустым",
                    "maxVariableSelection": "Вы не можете выбрать более 25 суб-переменных",
                    "signInFail" : "Войти не удалось",
                    "itemUpdateMessage": "Элемент обновлен",
                    "unsavedChangesMessage": "Несохраненные изменения",
                    "failMessage": "Не удалось обновить элемент",
                    "saveChangesAlert": "Сохранить изменения?",
                    "variableLabelValidation": "Надпись переменной не может быть пустой",
                    "subVariableLabelValidation": "Надпись суб-переменной не может быть пустой"
                    }
            }
        }
    })
);