define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Inserir distância",
                    "layerName": "Inserir nome da camada aqui"
                },
                "message": {
                    "analysisFailed": "Falha de análise.",
                    "errorOccurred": "Ocorreu algum erro.",
                    "layerAdded": "Camada adicionada com sucesso. ",
                    "enrichLayerNameError": "O \'nome da camada resultante\' não deve conter caracteres inválidos" + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Criando serviço.. ",
                    "starting": "Iniciando",
                    "performingAnalysis": "Executando análise..",
                    "checkLayerName": "Verificando por nome da camada.. ",
                    "addingLayer": "Adicionando camada ao mapa da web ",
                    "layerNameExist": "O nome da camada já existe.",
                    "clickOnSave": " Clique no botão \'Salvar\' para recarregar o aplicativo.",
                    "clickOnOk": " Clique no botão \'OK\' para tentar novamente.",
                    "enterNumbersOnly": "Os valores inseridos não são válidos",
                    "nofeatures": "Nenhuma feição está presente na extensão atual",
                    "selectData": "Selecione dados para enriquecer camada.",
                    "resetVariableMessage": "Tem certeza que deseja redefinir a variável?",
                    "emptyTextFieldLayerName": "Insira o nome da camada resultante",
                    "createService":"Camada não criada.",
                    "sharingLayer":"Compartilhando camada..",
                    "updateItemFailed": "Falha ao atualizar. Tente novamente.",
                    "geoEnrichFailed": "Falha ao enriquecer camada. Tente novamente.",
                    "shareFailed": "Falha ao compartilhar camada enriquecida. Tente novamente.",
                    "refreshServiceFailed": "Falha ao renovar camada. Tente novamente.",
                    "layerJsonFailed": "Falha ao criar JSON para camada. Tente novamente.",
                    "addToWebmapFailed": "Falha ao adicionar camada no mapa da web. Tente novamente.",
                    "bufferAreaHelpText": "Insira o valor menor que ",
                    "invalidBufferInput": "O valor inserido não é válido.",
                    "emptyBufferInput": "Insira um valor válido."
                },
                "populationText": "Preenchimento",
                "housingText": "Casa",
                "businessText": "Negócio",
                "variableListText": " as variáveis estão listadas aqui:",
                "countrySelectTitle": "1. Selecionar Local dos Dados",
                "unitedStates": "Estados Unidos",
                "global": "Global",
                "geoenrichDialogText": "Variáveis de Geoenriquecimento",
                "viewVariablestext": "Visualizar variáveis",
                "backButtonText":"Voltar",
                "customizeVariables": "Personalizar variáveis",
                "resetVariables": "Redefinir",
                "defineAreaTitle": "3. Definir área para enriquecer",
                "currentMapExtent": "Utilizar extensão de mapa atual",
                "enrichLayerName": "4. Nome da camada resultante",
                "lineDistanceText": "Distância da Linha",
                "drivingTime": "Tempo do Percurso",
                "enrichButtonText": "Enriquecer Camada",
                "selectDataText": "2. Selecionar Dados",
                "showCreditsText": "Mostrar créditos",
                "variableCount": "Contagem total de variável ",
                "totalRecords": "Total de Registros:",
                "cost": "Custo:",
                "showCreditsDialogText": "Mostrar Créditos",
                "nextButtonText": "Avançar",
                "prevButtonText": "Anterior",
                "saveButtonText": "Salvar",
                "ok": "OK"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 