define({
	root: ({
		signInDialog: {
			title: "Kirjaudu Tarinakartat-sovellukseen",
			subtitle: "Kirjaudu sisään olemassa olevalla ArcGIS Online -tililläsi, kun haluat",
			reasonOne: "Luo karttapohjaisia tarinakarttoja tarinoittesi kertomiseen.",
			reasonTwo: "Käytä ArcGIS Onlinen karttoja ja aineistoa tarinakartoissasi.",
			reasonThree: "Hallitse tarinakarttojasi ja tarkista niiden sisältö.",
			noAccountYet: "Eikö sinulla ole ArcGIS Online -tiliä? Rekisteröidy:",
			publicAccount: "Ilmainen, muu kuin kaupallinen julkinen tili",
			subscriptionAccount: "Ilmainen ArcGIS-kokeilutilaus",
			signInExpired: "Sisäänkirjautumisesi on vanhentunut. Kirjaudu sisään uudelleen jatkaaksesi siitä, mihin jäit.",
			somethingNotLoading: "Jokin ei lataudu oikein. Kokeile sivun päivitystä."
		},
		unavailableDialog: {
			title: "Sisäänkirjautuminen ei ole käytettävissä",
			explanation: "Valitettavasti tätä ei tueta pienessä näytössä. Avaa suuremmassa näytössä tai laitteessa.",
			close: "Tallennettu",
			returnButton: "Palauta" 
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 	
});