define({
	root: ({
		signInDialog: {
			title: "Logige sisse portaali Story Maps",
			subtitle: "Logige sisse oma olemasoleva ArcGIS Online kontoga.",
			reasonOne: "Saate luua oma lugude rääkimiseks haaravaid kaardilugusid.",
			reasonTwo: "Saate kasutada oma kaardilugudes enda kaarte ja ArcGIS Online andmeid.",
			reasonThree: "Saate hallata oma kaardilugusid ja vaadata nende sisu olekut.",
			noAccountYet: "Kas Teil pole veel ArcGIS Online kontot? Registreeruge kohe.",
			publicAccount: "Tasuta mitteärilistel eesmärkidel põhinev avalik konto",
			subscriptionAccount: "ArcGIS-i tellimuse tasuta prooviversioon",
			signInExpired: "Teie sisselogimisseanss aegus. Logige uuesti sisse, et jätkata poolelijäänud kohast.",
			somethingNotLoading: "Millegi laadimine ebaõnnestus. Proovige lehte värskendada."
		},
		unavailableDialog: {
			title: "Sisselogimine pole saadaval",
			explanation: "Kahjuks ei toetata seda väikesel ekraanil. Palun avage suuremal ekraanil või suuremas seadmes.",
			close: "Sulge",
			returnButton: "Tagasi" 
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 	
});