define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "De geselecteerde webkaart bevat geen geldige laag die gebruikt kan worden. Voeg een bewerkbare Featurelaag toe aan uw webkaart om verder te gaan.",
            selectFieldsText:"Vormvelden selecteren",
            selectThemeText: "Vormthema selecteren",
            fieldLabelPlaceHolder: "Label toevoegen aan dit veld",
            fieldDescPlaceHolder: "Dit veld beschrijven",
            webmapText: "1. Webkaart",
            layerText: "2. Laag",
            detailsText: "3. Details",
            fieldsText: "4. Velden",
            styleText: "5. Stijl",
            previewText: "6. Voorbeeld",
            publishText: "7. Publiceren",
            titleText: "GeoForm Builder",
            descriptionText: "Een geografisch formulier is een configureerbare template voor op formulieren gebaseerde gegevensbewerking van een <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Featureservice</a>. Met deze applicatie kunnen gebruikers gegevens invoeren met behulp van een formulier in plaats van de pop-up van een kaart en kunnen ze profiteren van de voordelen van de <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Webmap</a> en bewerkbare Featureservices. Gebruik deze builder om uw geografisch formulier aan te passen en te implementeren volgens de stappen die links worden weergegeven.",
            btnPreviousText: "Vorige",
            btnNextText:"Volgende",
            webmapTabTitleText: "Een webmap kiezen",
            btnSelectWebmapText:"Webmap selecteren",
            layerTabTitleText: "Bewerkbare kaartlaag selecteren",
            selectLayerLabelText:"Kaartlaag",
            selectLayerDefaultOptionText:"Kaartlaag selecteren",
            detailsTabTitleText:"Formulierdetails",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logoafbeelding",
            detailDescriptionLabelText: "Beschrijving",
            fieldTabFieldHeaderText: "Veld",
            fieldTabLabelHeaderText: "Label",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Beschrijving",
            previewApplicationText: "Voorbeeld van applicatie bekijken",
            saveApplicationText: "Applicatie opslaan",
            saveText: "Opslaan",
            toggleNavigationText: "Schakelen tussen navigatie",
            formPlaceholderText: "Mijn formulier",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "Geografisch formulier publiceren",
            shareBuilderProgressBarMessage:"Een moment geduld...",
            shareBuilderTitleMessage: "Uw geografische formulier is bijgewerkt en gepubliceerd!",
            shareBuilderTextMessage: "U kunt nu informatie verzamelen en met anderen delen.",
            shareDialogFormText: "Link formulier",
            geoformTitleText: "Geografisch formulier",
            layerTabText: "Dit is de laag waaruit het geografisch formulier wordt opgebouwd. De laag moet een featureservice zijn die is ingeschakeld voor bewerken met voor uw publiek geschikte deelmachtigingen.",
            detailsTabText:"Gebruik de vakken voor Formulierdetails hieronder om de titel en het logo aan te passen, en geef een korte omschrijving voor het publiek van uw geografisch formulier.",
            fieldsTabText:"Hier kunt u selecteren welke velden zichtbaar zijn voor het publiek van uw geografisch formulier, de labels bewerken die ze te zien krijgen en een korte beschrijving toevoegen om gegevensinvoer te vergemakkelijken.",
            styleTabText: "Bewerk u geografisch formulier naar eigen inzicht met behulp van onderstaande thema\'s.",
            publishTabText: "Als u uw geografisch formulier heeft aangepast, slaat u de applicatie op en begint u te delen met uw publiek. U kunt altijd terugkeren naar deze builder en doorgaan met aanpassen op basis van uw feedback."
        }
    })
);