define(
   ({
    map: {
      error: "Ĳ_Unable to create map_ä"
    },
    onlineStatus: {
      offline: "Ĳ_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_ä.",
      reconnecting: "Ĳ_Reconnecting&hellip;_ä",
      pending: "Ĳ_${total} pending edit(s) will be submitted when a network connection is re-established_ä."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Ĳ_My Organization_ä",
          onlineLabel: "Ĳ_ArcGIS Online_ä",
          contentLabel: "Ĳ_My Content_ä",
          favoritesLabel: "Ĳ_My Favorites_ä"
        },
        title: "Ĳ_Select Web Map_ä",
        searchTitle: "Ĳ_Search_ä",
        ok: "Ĳ_Ok_ä",
        cancel: "Ĳ_Cancel_ä",
        placeholder: "Ĳ_Enter search term_ä"
      },
      groupdlg: {
        items: {
          organizationLabel: "Ĳ_My Organization_ä",
          onlineLabel: "Ĳ_ArcGIS Online_ä",
          contentLabel: "Ĳ_My Content_ä",
          favoritesLabel: "Ĳ_My Favorites_ä"
        },
        title: "Ĳ_Select Group_ä",
        searchTitle: "Ĳ_Search_ä",
        ok: "Ĳ_Ok_ä",
        cancel: "Ĳ_Cancel_ä",
        placeholder: "Ĳ_Enter search term_ä"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Ĳ_Here is a link to a GeoForm_ä"
      }
    },
    user: {
      mgrs: "Ĳ_MGRS_ä",
      usng: "Ĳ_USNG_ä",
      utm: "Ĳ_UTM_ä",
      utm_northing: "Ĳ_Northing_ä",
      utm_easting: "Ĳ_Easting_ä",
      utm_zone_number: "Ĳ_Zone Number_ä",
      selectLayerTabText: "Ĳ_${formSection} Select Form_ä",
      geoFormGeneralTabText: "Ĳ_${formSection} Enter Information_ä",
      locationInformationText: "Ĳ_${formSection} Select Location_ä",
      submitInformationText: "Ĳ_${formSection} Complete Form_ä",
      submitInstructions: "Ĳ_Add this information to the map_ä.",
      myLocationText: "Ĳ_Current Location_ä",
      locationDescriptionForMoreThanOneOption: "Ĳ_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ä.",
      locationDescriptionForOneOption: "Ĳ_Specify the location for this entry by clicking/tapping the map or by using the following option_ä.",
      locationDescriptionForNoOption: "Ĳ_Specify the location for this entry by clicking/tapping the map_ä.",
      addressText: "Ĳ_Search_ä",
      geographic: "Ĳ_Lat/Lon_ä",
      locationTabText: "Ĳ_Location_ä",
      locationPopupTitle: "Ĳ_Location_ä",
      submitButtonText: "Ĳ_Submit Entry_ä",
      submitButtonTextLoading: "Ĳ_Submitting&hellip;_ä",
      formValidationMessageAlertText: "Ĳ_The following fields are required_ä:",
      selectLocation: "Ĳ_Please select a location for your submission_ä.",
      emptylatitudeAlertMessage: "Ĳ_Please enter a ${openLink}latitude${closeLink} coordinate_ä.",
      emptylongitudeAlertMessage: "Ĳ_Please enter a ${openLink}longitude${closeLink} coordinate_ä.",
      shareUserTitleMessage: "Ĳ_Thank you for your contribution_ä!",
      entrySubmitted: "Ĳ_Your entry has been submitted to the map_ä.",
      shareThisForm: "Ĳ_Share This Form_ä",
      shareUserTextMessage: "Ĳ_Tell others to contribute using the following options_ä.",
      addAttachmentFailedMessage: "Ĳ_Unable to add attachment to layer_ä",
      addFeatureFailedMessage: "Ĳ_Unable to add feature to layer_ä",
      noLayerConfiguredMessage: "Ĳ_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ä.",
      placeholderLatitude: "Ĳ_Latitude (Y)_ä",
      placeholderLongitude: "Ĳ_Longitude (X)_ä",
      latitude: "Ĳ_Latitude_ä",
      longitude: "Ĳ_Longitude_ä",
      findMyLocation: "Ĳ_Locate Me_ä",
      finding: "Ĳ_Locating&hellip;_ä",
      backToTop: "Ĳ_Back to top_ä",
      addressSearchText: "Ĳ_Your submission will appear here. You can drag the pin to correct the location_ä.",
      shareModalFormText: "Ĳ_Form Link_ä",
      close: "Ĳ_Close_ä",
      locationNotFound: "Ĳ_Location could not be found_ä.",
      setLocation: "Ĳ_Set Location_ä",
      find: "Ĳ_Find address or place_ä",
      attachment: "Ĳ_Attachment_ä",
      toggleDropdown: "Ĳ_Toggle Dropdown_ä",
      invalidString: "Ĳ_Please enter valid value_ä.",
      invalidSmallNumber: "Ĳ_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ä.",
      invalidNumber: "Ĳ_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ä.",
      invalidFloat: "Ĳ_Please enter valid ${openStrong}floating point${closeStrong} value_ä.",
      invalidDouble: "Ĳ_Please enter valid ${openStrong}double${closeStrong} value_ä.",
      invalidLatLong: "Ĳ_Please enter valid latitude and longitude coordinates_ä.",
      invalidUTM: "Ĳ_Please enter valid UTM coordinates_ä.",
      invalidUSNG: "Ĳ_Please enter valid USNG coordinates_ä.",
      invalidMGRS: "Ĳ_Please enter valid MGRS coordinates_ä.",
      geoformTitleText: "Ĳ_GeoForm_ä",
      domainDefaultText: "Ĳ_Select&hellip;_ä",
      applyEditsFailedMessage: "Ĳ_Sorry your entry cannot be submitted. Please try again_ä.",
      requiredFields: "Ĳ_There are some errors. Please correct them below_ä.",
      requiredField: "Ĳ_(required)_ä",
      error: "Ĳ_Error_ä",
      textRangeHintMessage: "Ĳ_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ä",
      dateRangeHintMessage: "Ĳ_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ä",
      remainingCharactersHintMessage: "Ĳ_${value} characters remaining_ä",
      mapFullScreen: "Ĳ_Full Screen_ä",
      mapRestore: "Ĳ_Restore_ä",
      filterSelectEmptyText: "Ĳ_Select_ä",
      invalidLayerMessage: "Ĳ_Form layer does not exist. Please configure the application and set the layer_ä.",
      selectedLayerText: "Ĳ_All_ä"
    },
    builder: {
      invalidUser: "Ĳ_Sorry, you dont have permission to view this item_ä",
      invalidWebmapSelectionAlert: "Ĳ_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_ä.",
      invalidWebmapSelectionAlert2: "Ĳ_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ä",
      selectFieldsText: "Ĳ_Select Form Fields_ä",
      selectThemeText: "Ĳ_Select Form Theme_ä",
      webmapText: "Ĳ_Webmap_ä",
      layerText: "Ĳ_Layer_ä",
      detailsText: "Ĳ_Details_ä",
      fieldsText: "Ĳ_Fields_ä",
      styleText: "Ĳ_Style_ä",
      optionText: "Ĳ_Options_ä",
      previewText: "Ĳ_Preview_ä",
      publishText: "Ĳ_Publish_ä",
      optionsApplicationText: "Ĳ_Options_ä",
      titleText: "Ĳ_Builder_ä",
      descriptionText: "Ĳ_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ä.",
      btnPreviousText: "Ĳ_Previous_ä",
      btnNextText: "Ĳ_Next_ä",
      webmapTabTitleText: "Ĳ_Select a Webmap_ä",
      viewWebmap: "Ĳ_View webmap_ä",
      webmapDetailsText: "Ĳ_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ä",
      btnSelectWebmapText: "Ĳ_Choose Webmap_ä",
      btnSelectWebmapTextLoading: "Ĳ_Loading&hellip;_ä",
      layerTabTitleText: "Ĳ_Select Editable Layer_ä",
      selectLayerLabelText: "Ĳ_Layer_ä",
      selectLayerDefaultOptionText: "Ĳ_Select Layer_ä",
      defaultBasemap: "Ĳ_Basemap Toggle_ä",
      secondaryBasemap: "Ĳ_Default Basemap_ä",
      detailsTabTitleText: "Ĳ_Form Details_ä",
      detailTitleLabelText: "Ĳ_Title_ä",
      detailLogoLabelText: "Ĳ_Logo Image_ä",
      descriptionLabelText: "Ĳ_Form Instructions & Details_ä",
      fieldDescriptionLabelText: "Ĳ_Help Text (optional)_ä",
      fieldTabFieldHeaderText: "Ĳ_Field_ä",
      fieldTabLabelHeaderText: "Ĳ_Label_ä",
      fieldTabDisplayTypeHeaderText: "Ĳ_Display As_ä",
      fieldTabOrderColumnText: "Ĳ_Order_ä",
      fieldTabVisibleColumnText: "Ĳ_Enabled_ä",
      selectMenuOption: "Ĳ_Select Menu_ä",
      selectRadioOption: "Ĳ_Radio Button_ä",
      selectTextOption: "Ĳ_Text_ä",
      selectDateOption: "Ĳ_Date Picker_ä",
      selectRangeOption: "Ĳ_Touch-Spinner_ä",
      selectCheckboxOption: "Ĳ_Checkbox_ä",
      selectMailOption: "Ĳ_Email_ä",
      selectUrlOption: "Ĳ_URL_ä",
      selectTextAreaOption: "Ĳ_Text Area_ä",
      previewApplicationText: "Ĳ_Preview Application_ä",
      saveApplicationText: "Ĳ_Save Application_ä",
      saveText: "Ĳ_Save_ä",
      toggleNavigationText: "Ĳ_Toggle navigation_ä",
      formPlaceholderText: "Ĳ_My Form_ä",
      shareBuilderInProgressTitleMessage: "Ĳ_Publishing GeoForm_ä",
      shareBuilderProgressBarMessage: "Ĳ_Please Wait&hellip;_ä",
      shareBuilderTitleMessage: "Ĳ_Success! Item saved_ä",
      shareBuilderTextMessage: "Ĳ_You can start collecting information by sharing with others_ä",
      shareModalFormText: "Ĳ_Form Link_ä",
      shareBuilderSuccess: "Ĳ_Your GeoForm has been updated & published_ä!",
      geoformTitleText: "Ĳ_Geo Form_ä",
      layerTabText: "Ĳ_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_ä.",
      detailsTabText: "Ĳ_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_ä.",
      fieldsTabText: "Ĳ_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_ä.",
      styleTabText: "Ĳ_Style your GeoForm using the themes below based on your preference_ä.",
      publishTabText: "Ĳ_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_ä.",
      headerSizeLabel: "Ĳ_Header Size_ä",
      smallHeader: "Ĳ_Use Small Header_ä",
      bigHeader: "Ĳ_Use Large Header_ä",
      pushpinText: "Ĳ_Push pin_ä",
      doneButtonText: "Ĳ_Save and Exit_ä",
      fieldTabPlaceHolderHeaderText: "Ĳ_Hint (optional)_ä",
      enableAttachmentLabelText: "Ĳ_${openStrong}Enable Attachments${closeStrong}_ä",
      enableAttachmentLabelHint: "Ĳ_You can enable/disable the attachments here_ä",
      attachmentIsRequiredLabelText: "Ĳ_${openStrong}Attachment Required${closeStrong}_ä",
      attachmentIsRequiredLabelHint: "Ĳ_If necessary, users can be required to enter an attachment_ä.",
      attachmentLabelText: "Ĳ_Attachment Button Label_ä",
      attachmentLabelHint: "Ĳ_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ä",
      attachmentDescription: "Ĳ_Attachment Description_ä",
      attachmentHint: "Ĳ_If necessary, you can provide additional attachment instructions here_ä.",
      jumbotronDescription: "Ĳ_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ä",
      shareGeoformText: "Ĳ_Share Geoform_ä",
      shareDescription: "Ĳ_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_ä.",
      defaultMapExtent: "Ĳ_Default Map Extent_ä",
      defaultMapExtentDescription: "Ĳ_The map will reset to the default extent in your web map after submission - this can be disabled at any time_ä.",
      pushpinOptionsDescription: "Ĳ_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ä",
      selectLocationText: "Ĳ_Select Location By_ä",
      myLocationText: "Ĳ_My Location_ä",
      searchText: "Ĳ_Search_ä",
      coordinatesText: "Ĳ_Latitude & Longitude Coordinates_ä",
      usng: "Ĳ_USNG Coordinates_ä",
      mgrs: "Ĳ_MGRS Coordinates_ä",
      utm: "Ĳ_UTM Coordinates_ä",
      selectLocationSDescription: "Ĳ_Allow users to select a location using these methods_ä.",
      dragTooltipText: "Ĳ_Drag the field where you want it to appear_ä",
      showHideLayerText: "Ĳ_Show Layer_ä",
      showHideLayerHelpText: "Ĳ_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_ä.",
      labelHelpMessage: "Ĳ_Label_ä",
      placeHolderHintMessage: "Ĳ_Hint Text_ä",
      placeHolderHelpMessage: "Ĳ_Help Text_ä",
      selectTextOptionValue: "Ĳ_Filter Select_ä",
      disableLogo: "Ĳ_Disable Logo_ä",
      disableLogoDescription: "Ĳ_You can configure the GeoForm to Show/Hide the Logo in the form header_ä",
      locateOnLoadText: "Ĳ_Locate On Load_ä",
      locateOnLoadDescription: "Ĳ_You can configure the GeoForm to use the current location on page load_ä",
      selectLayerFieldTabText: "Ĳ_Select Layer_ä",
      allLayerSelectOptionText:"Ĳ_All_ä"
    }
  })
);