define(
({
		viewer: {
			loading: {
				step1: "IELĀDĒ APLIKĀCIJU",
				step2: "IELĀDĒ DATUS",
				step3: "IZPILDA TŪRI",
				loadBuilder: "PĀRSLĒGT UZ BUILDER MODE",
				redirectSignIn: "ķ_REDIRECTING TO SIGN-IN PAGE_ū",
				redirectSignIn2: "ķ_(you will be redirected here after sign-in)_ū",
				fail: "Atvainojiet, Map Tour ielādēšanas neveiksme",
				failButton: "Atkārtot"
			},
			errors: {
				boxTitle: "Kļūda",
				portalSelf: "Fatāla kļūda: neizdevās iegūt portāla konfigurāciju",
				invalidConfig: "Fatāla kļūda: konfigurācijas neveiksme",
				invalidConfigOwner: "Fatāla kļūda: konfigurācijas neveiksme (nepieciešams autorizēts īpašnieks)",
				invalidConfigNoWebmap: "Fatāla kļūda: konfigurācijas neveiksme (nav norādīta web karte vai aplikācijas identifikators index.html failā)",
				createMap: "Nevar izveidot karti",
				invalidApp: "Fatāla kļūda: aplikāciju nevar ielādēt",
				noLayer: "Web karte nesatur derīgu datu slāni priekš Map Tour.",
				noLayerMobile: "Laipni lūdzam Map Tour web aplikācijā. Aplikācija nav konfigurēta. Map Tour veidotājs netiek atbalstīts uz mobilajām ierīcēm.",
				noLayerView: "Laipni lūdzam Map Tour web aplikācijā.<br />Aplikācija nav vēl konfigurēta.",
				appSave: "Kļūda, saglabājot web aplikāciju",
				mapSave: "Kļūda, saglabājot web karti",
				featureServiceLoad: "Kļūda ielādējot elementu servisu",
				notAuthorized: "Jums nav atļauts piekļūt šai aplikācijai",
				oldBrowserTitle: "Pārlūks netiek pilnībā atbalstīts",
				noBuilderIE8: "Map Tour veidotājs neatbalsta Internet Explorer pirms 9 versiju.",
				ie10Win7Explain: "Map Tour interaktīvais veidotājs nav atbalstīts ar Internet Explorer 10 uz Windows 7, kad datu avots ir Feature Service ar piesaistēm. Lai lietotu Feature Service ar piesaistēm, jums vajag <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuāli piespiest dokumenta režīmu uz Internet Explorer 9 standartu</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>pazemināt uz Internet Explore 9</a> vai uzlabot uz Windows 8.",
				oldBrowserExplain: "Šis pārlūks neatbalsta automātisku sīktēlu radīšanu no attēliem, ko jūs augšupielādējat jūsu map tour. Jūs varat izveidot map tour, izmantojot šo pārlūku, bet jums būs jāsniedz atsevišķs sīktēls par katru no augšupielādētiem attēliem .",
				oldBrowserExplain2: "Lai uzlabotu jūsu pieredzi, <a href='http://browsehappy.com/' target='_blank'>jaunina jūsu pārlūku</a> vai <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivizē Google Chrome Frame priekš Internet Explorer</a>.",
				oldBrowserExplain3: "The Map Tour veidotājs nedarbojas ar Internet Explorer 10 uz Windows XP.",
				oldBrowserClose: "Aizvērt"
			},
			mobileHTML: {
				showIntro: "RĀDĪT VIRSRAKSTU",
				hideIntro: "PASLĒPT VIRSRAKSTU",
				navList: "Saraksts",
				navMap: "Karte",
				navInfo: "Mediji",
				introStartBtn: "Starts"
			},
			desktopHTML: {
				storymapsText: "Stāstu karte",
				builderButton: "Pārslēgties uz veidotāja režīmu",
				bitlyTooltip: "Iegūt īssaiti uz aplikāciju",
				bitlyStartIndex: "ķ_Link to current place_ū"
			},
			builderHTML: {
				panelHeader: "APLIKĀCIJAS KONFIGURĀCIJA",
				buttonSave: "SAGLABĀT",
				buttonSettings: "Iestatījumi",
				buttonShare: "ķ_Share_ū",
				buttonView: "Skata režīms",
				buttonItem: "Atvērt web aplikācijas vienību",
				buttonHelp: "Palīdzība",
				buttonOrganize: "Organizē",
				buttonAdd: "Pievienot",
				buttonImport: "Importēt",
				buttonImportDisabled: "Imports nav iespējams, lietojot  Feature Service ar piesaistēm",
				dataEditionDisabled: "Datu rediģēšana ir atspējota CSV datu avotam",
				dataSourceWarning: "Map Tour datu slānis ir mainījies. Ja elementu ID nav tāds pat, jums jāatiestata kārtība un slēptie punkti caur <b>Organizēt</b>. Ja atšķiras lauku nosaukumi, jums jāatiestata lauku iestatījumi zem <b>datu cilnes Iestatījumos</b>.",
				organizeWarning: "Viens vai vairāki punkti pievienoti ārpus interaktīvā veidotāja ir paslēpti.",
				dataPicError0a: "Ši tūre ietver <b>%NB%</b> neatbisltošu bildes URL.",
				dataPicError0b: "Šī tūre var ietvert <b>%NB%</b> neatbilstošu bildes URL.",
				dataPicError1: "Map Tour tagad pieprasa, lai attēla URL beidzas ar vienu no sekojošiem paplašinājumiem: .jp(e)g, .png, .gif vai .bmp.",
				dataPicError2: "Šī prasība neietekmēs jau eksistējošās publicētās Map Tour. Lai gan, lai izmantotu inerkatīvo veidotāju, jums jāatrisina URL jautājums, veicot vienu no divām darbībām:",
				dataPicError3: "Rediģēt URL",
				dataPicError4: "Tas pievienos <i>#isImage</i> neatbalstītā URL galā. Lielākā daļa serveru atbalsta URL pielikumus. Lai gan, līdzko jūs esat veikuši šo darbību, jums jāpārliecinās, ka koriģētā attēla URL funkcionē, naviģējot caur punktiem. Ja katrs attēls ielādējas, jūs varat saglabāt Map Tour. Ja <b>ja attēli neielādējas, nesaglabājiet Map Tour</b>. Tā vietā pārlādējiet veidotāju un veiciet otru darbību.",
				dataPicError5: "Limitēt tūri uz attēliem",
				dataPicError6: "Ši izvēlne liks uzkatīt visus URL par attēliem, bet nebūs iespējams pievienot video izmantojot interaktīvo veidotāju. Ši darbība ir atgriezeniska, ja jūs izlemsiet pievienot video nākotnē.",
				dataPicError7: "Map Tour ir ierobežots lietot attēlus, video nevar tikt izmantots. Ja izvēlaties noņemt šo ierobežojumu, pārbaudiet vai attēli ielādējas korekti pirms saglabāt Map Tour. Jus varēsiet atjaunot šo ierobežojumu vēlāk, ja tas būs nepieciešams.",
				dataPicError8: "noņemt attēlu ierobežojumu",
				dataPicError9: "Ja šie URL norāda uz video, jūs varat ignorēt šo brīdinājumu, ja tie norāda uz attēliem, jums jāveic viena no sekojošām divām darbībām:",
				modalCancel: "Atcelt",
				modalApply: "Lietot",
				organizeHeader: "Organizē tūri",
				organizeGeneralCaption: "Izmantot vilkt un nomest, lai kārtotu maršruta punktus",
				organizeDelete: "Izdzēst",
				organizeHide: "Paslēpt",
				organizeReset: "Atiestatīt kārtību un slēptos punktus",
				addMaxPointReached: "Jūs esat sasniedzis maksimālo punktu skaitu, ko pilnvarojuši  ikonu iestatījumi un nevarat pievienot citu tūres punktu.<br/><br/>Ņemiet vērā, ja jūs izdzēstu esošos punktus, jums būtu nepieciešams pārlādēt aplikāciju.",
				addMaxPointReachedMobile: "Atvainojiet, jūs esat sasniedzis maksimālo autorizēto punktu skaitu un nevarat pievienot šo bildi.",
				addClose: "Aizvērt",
				addHeader: "Pievienot jaunu tūres punktu",
				addTabPicture: "Mediji",
				addTabInformation: "Informācija",
				addTabLocation: "Izvietojums",
				addSelectCaption: "Izvēlieties vai iemetiet bildi",
				addNoteVideo: "Apskatiet Palīdzību, lai uzzinātu instrukcijas kā izmantot video",		
				addSelectCaptionNoFileReader: "Izvēlieties bildi",	
				addChangePhoto: "Mainīt bildi un sīkattēlu",
				addPictureResolutionIntro: "Attēla rezolūcija ir lielāka nekā nepieciešams:",
				addPictureResolutionOldBrowser: "Attēla rezolūcija ir lielāka nekā nepieciešams. Optimizēt Map Tour pieredzi, norādot zemāku rezolūciju nekā %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Mainīt attēla rezolūciju uz %RESOLUTION%",
				addPictureResolutionKeep: "Paturēt oriģinālo rezolūciju %RESOLUTION%",
				addSelectThumbnail: "Izvēlēties sīktēlu",
				addNoThumbSelected: "Nav izvēlēts sīktēls",
				addThumbSelected: "Izvēlētais",
				addCameraSettingsHeader: "KAMERAS IESTATĪJUMI",
				addThumbnailHeader: "SĪKTĒLS",
				addLabelPicUrl: "Bilde",
				addLabelThumbUrl: "Sīktēls",
				addTextPlaceholderUrl: "Ievadiet attēla URL",
				addTextPlaceholderUrl2: "ķ_Enter a Youtube page URL_ū",
				addTextPlaceholderUrl3: "Ievadiet Vimeo lapas URL",
				addTextPlaceholderUrl4: "Ievadiet iedarinātā video URL",
				addLabelVideo: "Video",
				addMediaVideoOther: "Citi",
				addMediaVideoHelp: "Pārbaudiet URL un iegūstiet noklusējuma sīkattēlu",
				addMediaVideoHelpTooltip1: "Pārbaude izdevās",
				addMediaVideoHelpTooltip2: "Pārbaude neizdevās",
				addMediaVideoHelpTooltip4: "Atrodiet opciju lai iedarinātu video un kopējiet video URL kas ir redzams kodā",
				addLabelName: "Nosaukums",
				addLabelDescription: "Uzraksts",
				addTextPlaceholder: "Rakstīt kaut ko",
				addLocatePlaceholder: "Atrast adresi vai vietu",
				addPinColor: "Krāsa",
				addLatitude: "Platums",
				addLongitude: "Garums",
				addLatitudePlaceholder: "piem. 34.056",
				addLongitudePlaceholder: "piem. -117.195",
				addUploading: "Augšupielādējot tūres punktu",
				addSave: "Pievienot tūres punktu",
				addMobileUploading: "Augšupielādē bildi",
				addMobileName: "Ievadiet nosaukumu",
				addMobileNameMandatory: "Kļūda, lūdzu, ievadiet nosaukumu.",
				addMobileError: "Atvainojiet, kaut kas ir nogājis greizi",
				settingsHeader: "Aplikācijas iestatījumi",
				settingsTabLayout: "Izkārtojums",
				settingsTabColor: "Krāsas",
				settingsTabLogo: "Galvene",
				settingsTabFields: "Dati",
				settingsTabExtent: "Pārklājums",
				settingsTabZoom: "Mērogmaiņas līmenis",
				settingsLayoutExplain: "Izvēlieties vēlamo aplikācijas izkārtojumu.",
				settingsLayoutProfessional: "Trīs paneļu izkārtojums",
				settingsLayoutModern: "Integrētais izkārtojums",
				settingsLayoutSelected: "Izvēlētais izkārtojums",
				settingsLayoutSelect: "Izvēlieties šo izkārtojumu",
				settingsLayoutNote: "Ņemiet vērā, ka punktiem, kuriem izmantoti video, plakāti vienmēr būs novietoti zem video, pat ja šī izvēlne būs atiezīmēta.",
				settingsLayoutLocBtn: "ķ_Display a locate button on supported browser_ū",
				settingsLayoutLocBtnHelp: "Šī funkcionalitāte tiek atbalstīta uz biežāk lietotajām mobilājām ierīcēm un darbvirsmas pārlūkiem (Internet Explorer 9).",
				settingsColorExplain: "Mainīt izskatu, izvēloties iepriekš noteiktu tēmu, vai izveidojot savu.",
				settingsLabelColor: "Galvenes, satura un kājenes krāsas",
				settingsLogoExplain: "Pielāgot galvenes logotipu (maksimums  ir 250 x 50piks).",
				settingsLogoEsri: "Esri logotips",
				settingsLogoNone: "Nav logotipa",
				settingsLogoCustom: "Pielāgots logotips",
				settingsLogoCustomPlaceholder: "Attēla URL",
				settingsLogoCustomTargetPlaceholder: "Klikšķis caur saiti",
				settingsLogoSocialExplain: "Pielāgot galvenes labās augšējās saites.",
				settingsLogoSocialText: "Teksts",
				settingsLogoSocialLink: "Saite",
				settingsLogoSocialDisabled: "Administrators ir atspējojis šo iezīmi",
				settingsDataFieldsExplain: "Izvēlieties foto nosaukumu, uzrakstu un krāsu laukus.",
				settingsDataFieldsError: "Aplikācija nevar noteikt piemērotu nosaukumu, uzrakstu vai krāsu datus. Lūdzu, izvēlieties laukus ko šeit izmantot. Šos iestatījumus var mainīt vēlāk.",
				settingsFieldsLabelName: "Nosaukums",
				settingsFieldsLabelDescription: "Uzraksts",
				settingsFieldsLabelColor: "Krāsa",
				settingsFieldsReset: "Atiestātīt lauku atlasi",
				settingsExtentExplain: "Iestatīt Map Tour sākotnējo pārklājumu, izmantojot interaktīvo karti zemāk.",
				settingsExtentExplainBottom: "Pārklājums, kas tiek definēts, modificēs jūsu web kartes sākotnējo pārklājumu. Ņemiet vērā, ka šis pārklājums netiks izmantots, ja ras nesatur pirmo tūres punktu. Šajā gadījumā tūre atvērsies iecentrēta uz pirmo punktu.",
				settingsExtentDateLineError: "Pārklājums nevar būt pāri 180° meridiāna garumam.",
				settingsExtentDateLineError2: "Kļūda aprēķinot pārklājumu",
				settingsExtentDrawBtn: "Zīmēt jaunu pārklājumu",
				settingsExtentModifyBtn: "Rediģēt pārklājumu",
				settingsExtentApplyBtn: "Priekšskatīt Map Tour",
				settingsExtentUseMainMap: "Lietot Map Tour pārklājumu",
				settingsZoomExplain: "Iestatīt mērogmaiņu stāstu punktiem, kas seko pēc ievada (pēc izvēles).",
				settingsLabelZoom: "Mērogs/līmenis",
				settingsZoomFirstValue: "Neviens",
				settingsFieldError: "Lūdzu, izvēlieties lauku katrā sarakstā",
				dataTitle: "ķ_ArcGIS Online hosting_ū",
				dataExplain: "ķ_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._ū",
				dataNameLbl: "Servisa nosaukums",
				dataFolderListLbl: "Mape",
				dataFolderListFetching: "Mapju ienešana ...",
				dataRootFolder: "Sakne",
				dataNameError: "Ievadiet nosaukumu elementu servisam",
				dataFolderError: "Izvēlieties derīgu mapi",
				dataSrcContainsInvalidChar: "Elementu servisa nosaukums satur vienu vai vairākas nederīgas rakstzīmes (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "Serviss ar šādu nosaukumu jau pastāv organizācijā. Lūdzu, izvēlieties citu nosaukumu.",
				dataBtnSave: "Izveidot servisu",
				dataFooterProgress: "Izveide notiek",
				dataFooterSucceed: "Izveide izdevās. Ielādē",
				dataFooterError: "Izveide neizdevās. Lūdzu, mēģiniet vēlreiz",
				tabError: "Lūdzu pārbaudīt kļūdas visās cilnēs",
				introRecordBtn: "Ievads",
				introRecordActivate: "Izmantojiet pirmo punktu, kā ievadu (neparādās karuselī)"
			},
			addPopupJS: {
				uploadingPicture: "Augšupielādē attēlu",
				uploadSuccess: "Augšupielāde veiksmīga",
				uploadError: "Kļūda, augšupielādējot attēlu",
				uploadError2: "Kļūda pievienojot elementu (nederīgs html tags)",
				notJpg: "Lūdzu, izvēlieties jpeg foto, lai augšupielādētu",
				errorNoPhoto: "Izvēlieties attēlu, lai augšupielādētu",
				errorNoThumbnail: "Izvēlieties sīktēlu, lai augšupielādētu",
				errorInvalidPicUrl: "Ievadiet derīgu bildi (sākas ar http(s)://, beidzas ar jpg, png, gif vai bmp). URL var beigties ar '#isImage', lai ignorētu šo noteikumu.",
				errorInvalidThumbUrl: "Ievadiet derīgu sīktēlu (sākas ar http(s)://, beidzas ar jpg, png, gif vai bmp).",
				errorInvalidVideoUrl: "Ievadiet derīgu video URL (sākas ar http(s)://)",
				errorNoName: "Ievadiet nosaukumu šim tūres punktam",
				errorNoDescription: "Ievadiet uzrakstu šim tūres punktam",
				errorNoLocation: "Iestatiet izvietojumu šim tūres punktam"
			},
			builderJS: {
				noPendingChange: "ķ_No unsaved change_ū",
				unSavedChangeSingular: "1 nesaglabāta izmaiņa",
				unSavedChangePlural: "nesaglabātas izmaiņas",
				shareStatus1: "ķ_Tour is not saved_ū",
				shareStatus2: "ķ_Tour is shared publicly_ū",
				shareStatus3: "ķ_Tour is shared within the organization_ū",
				shareStatus4: "ķ_Tour is not shared_ū",
				popoverDiscard: "Vai esat pārliecināts, ka vēlaties izmest visas nesaglabātās izmaiņas?",
				yes: "Jā",
				no: "Nē",
				popoverLoseSave: "Atverot skatītāju, jūs zaudēsiet visas nesaglabātās izmaiņas",
				ok: "Labi",
				popoverSaveWhenDone: "Neaizmirstiet saglabāt, kad jūs pabeidzat",
				closeWithPendingChange: "Vai esat pārliecināts, ka vēlaties apstiprināt darbību? Jūsu izmaiņas tiks zaudētas.",
				gotIt: "Labi",
				savingApplication: "Saglabā aplikāciju",
				saveSuccess: "Aplikācija saglabāta veiksmīgi",
				saveError: "Saglabāt neizdevās, lūdzu, mēģiniet vēlreiz",
				saveError2: "Saglabāšana neizdevās nederīga html taga dēļ vārdā vai aprakstā",
				saveError3: "ķ_The title can't be empty_ū",
				dragColorPicker: "Pārvietot man apkārt<br />vai mainīt manu krāsu",
				dataWarningExtent: "Jums ir dati web kartes pārklājuma ārpusē. Šie dati netiks izmantoti kā tūres punkti, izmainiet kartes pārklājumu, ja jūs vēlaties tos izmantot.",
				dataWarningVisibi: "Jūsu Map Tour slānis nav redzams pašreizējā web kartes pārklājumā. Apstipriniet, ka jūsu Map Tour slānis ir redzams ar %MAPSIZE% lielā kartē.",
				dataWarningEdit: "Rediģēt web karti",
				dataWarningClose: "Aizvērt",
				signIn: "Lūdzu, pierakstieties kontā uz",
				signInTwo: "lai saglabātu aplikāciju.",
				switchBM: "ķ_Change Basemap_ū"
			},
			organizePopupJS: {
				messageStart: "Jūs esat izvēlējies izdzēst",
				messageSinglePoint: "vienu tūres punktu",
				messageMultiPoint: "tūres punkti",
				messagePermantRemove: "Tas neatgriezeniski izņems",
				messageRecord: "ieraksts",
				messageRecordPlural: "ieraksti",
				messageConfirm: "no jūsu datubāzes. Vai vēlaties turpināt?",
				labelButtonShow: "Parādīt",
				labelButtonHide: "Paslēpt"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Tas neatgriezeniski izdzēstu bildi un sīktēlu",
				popoverDeleteWarningThumb: "Tas neatgriezeniski izdzēstu sīktēlu",
				popoverUploadingPhoto: "Augšupielādē bildi un sīktēlu",
				popoverUploadingThumbnail: "Augšupielādē sīktēlu",
				popoverUploadSuccessful: "Augšupielāde veiksmīga",
				popoverUploadError: "Augšupielādes neveiksme, lūdzu, mēģiniet vēlreiz",
				changePicAndThumb: "Mainīt bildi",
				changeThumb: "Mainīt sīktēlu",
				selectPic: "Mainīt mediju",
				selectThumb: "Mainīt sīktēlu",
				uploadPicAndThumb: "Lietot"
			},
			headerJS:{
				editMe: "Rediģē mani !",
				templateTitle: "Iestatīt šablona virsrakstu",
				templateSubtitle: "Iestatīt šablona apakšvirsrakstu"
			},
			crossFaderJS:{
				setPicture: "Iestatīt bildes virsrakstu",
				setCaption: "Iestatīt bildes uzrakstu"
			},
			importPopup: {
				title: "Importēt",
				prevBtn: "Atpakaļ",
				nextBtn: "Nākošais"
			},
			importPopupHome: {
				header: "Kur ir jūsu bildes uzglabātas?"
			},
			onlinePhotoSharingCommon: {
				pictures: "attēli",
				videos: "video",
				disabled: "Administrators ir atspējojis šo iezīmi",
				disabledPortal: "Ši iezīme ir atiespējota Portal for ArcGIS",
				header1: "ķ_Your pictures must be shared publicly._ū",
				header2: "ķ_The import will be limited to the first %NB1% %MEDIA%._ū",
				emptyDataset: "Kļūda, nav atrastas bildes",
				footerImport: "Importēt",
				selectAlbum: "Izvēlieties publisku albumu",
				selectAlbum2: "Izvēlieties albumu",
				pleaseChoose: "Lūdzu, izvēlieties",
				userLookup: "Uzmeklēt",
				userLookingup: "Meklēšanai",
				csv: "Atsauce uz CSV",
				advanced: "Papildus opcijas",
				advancedScratchLbl: "ķ_Start a new Tour_ū",
				advancedScratchTip: "ķ_Create an empty Tour that you will be able populate manually using a wizard._ū",
				advancedCSVLbl: "ķ_Import Tour data from a CSV file_ū",
				advancedCSVTip: "ķ_Import your Tour content from a CSV file._ū",
				advancedCommonTip: "ķ_It requires that your images and videos are already online._ū",
				select: "Veikt izvēli",
				locUse: "ķ_Use pictures geolocation_ū",
				locExplain: "ķ_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._ū",
				locExplain2: "ķ_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._ū"
			},
			viewFlickr: {
				title: "ķ_Flickr import_ū",
				header: "ķ_Enter your Flickr user name and select a Photo Set or a Tag to be imported._ū",
				userInputLbl: "Ievadiet Lietotāja vārdu",
				signInMsg2: "Lietotājs nav atrasts",
				selectSet: "Izvēlieties Foto iestatījumu",
				selectTag: "vai izvēlieties Tagu",
				footerImportTag: "Importēt izvēlēto Tagu",
				footerImportSet: "Importēt izvēlēto iestatījumu"
			},
			viewFacebook: {
				title: "ķ_Facebook import_ū",
				header: "ķ_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._ū",
				leftHeader: "Facebook Lietotājs",
				rightHeader: "Facebook Lapa",
				pageExplain: "Facebook lapa ir publisks zīmols/produkts vai slavenība, piem., <b>esrigis</b>. Jūs varat saņemt lapas nosaukumu, pēc pirmās '/' lapas URL.",
				pageInputLbl: "Ievadiet lapas nosaukumu",
				lookupMsgError: "Lapa nav atrasta"
			},
			viewPicasa: {
				title: "ķ_Picasa/Google+ import_ū",
				header: "ķ_Enter your email address or the ID of your Picasa or Google+ account._ū",
				userInputLbl: "Ievadiet epastu vai ID",
				signInMsg2: "Konts nav atrasts",
				howToFind: "ķ_How to find a Picasa or Google+ account ID_ū",
				howToFind2: "Kopēt ciparus starp pirmo un otro '/' no jebkura Picasa vai G+ lapa"
			},
			viewCSV: {
				title: "ķ_CSV import_ū",
				uploadBtn: "Izvēlieties vai nometiet CSV failu",
				resultHeaderEmpty: "CSV ir tukšs",
				resultHeaderSuccess: "Sekmīgi ielādēja %NB_POINTS% punktus",
				resultHasBeenLimited: "Imports ir limitēts ar pirmo %VAL1% norāda uz %VAL2% ievērot limitu %VAL3% punktus par katru tūri",
				browserSupport: "Jūsu pārlūks neatbalsta, lai izmantotu CSV jums ir <a href='http://browsehappy.com/' target='_blank'>jāatjaunina jūsu pārlūks</a> vai lietojiet ArcGIS.com web kartes skatītāju (skat. Palīdzību).",
				errorLatLng: "Platuma un Garuma lauki nav atrasti. Iespējamās platuma vērtības ir: <i>%LAT%</i> un garuma: <i>%LONG%</i>.",
				errorFieldsExplain: "Ielādēšana neizdevās, jo šādi obligātie lauki nav atrasti",
				errorFieldsName: "<b>Nosaukums</b> iespējamās vērtības ir: %VAL%",
				errorFieldsDesc: "<b>Apraksts</b> iespējamās vērtības ir: %VAL%",
				errorFieldsUrl: "<b>Bildes URL</b> iespējamās vērtības ir: %VAL%",
				errorFieldsThumb: "<b>Sīktēla URL</b> iespējamās vērtības ir: %VAL%",
				errorFields2Explain: "Ielādēšana neizdevās, jo CSV neizmanto tos pašus atribūtus, nekā slānis priekš sekojošajiem atribūtiem",
				errorFields2Name: "<b>Nosaukums</b> lieto %VAL1% vietā %VAL2%",
				errorFields2Desc: "<b>Apraksts</b> lieto %VAL1%vietā %VAL2%",
				errorFields2Url: "<b>Bildes URL</b> lieto %VAL1% vietā %VAL2%",
				errorFields2Thumb: "<b>Sīktēla URL</b> lieto %VAL1% vietā %VAL2%",
				resultFieldsAll: "Visi atribūti ir importēti",
				resultFieldsNotAll: "Šādi atribūti nav importēti, jo tie nepastāv kartes slānī",
				resultFieldsNotAll2: "Sekojošie atribūti tiks importēti",
				footerNextBtnResult: "Imports uz web karti",
				footerProgress: "Imports progresā",
				footerSucceed: "Imports sekmīgs. Ielādē"
			},
			viewYoutube: {
				title: "ķ_Youtube import_ū",
				header: "ķ_Enter a YouTube user name to find publicly shared videos._ū",
				pageInputLbl: "ķ_Enter a Youtube user name_ū",
				lookupMsgError: "Lietotājs nav atrasts",
				howToFind: "ķ_How to find a Youtube user name_ū",
				howToFind2: "Lietotāja vārds ir attēlots zem video",
				found: "Atrasts",
				noData: "Nav atrasti publiski video"
			},
			viewGeoTag: {
				title: "ķ_Select and locate your images/videos_ū",
				header: "Lai atrastu, noklikšķiniet vai pieskarieties bildēm, kuras vēlaties importēt.",
				headerMore: "ķ_Why aren't my images/videos geolocated?_ū",
				headerExplain: "ķ_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._ū",
				leftPanelTab1: "Lai atrastu",
				leftPanelTab2: "Atrodas",
				clickOrTap: "Noklikšķiniet vai pieskarieties kartei, lai atrastu",
				clearLoc: "ķ_Clear locations_ū",
				clickDrop: "Neimportē",
				footerImport: "Importēt",
				footerProgress: "Imports progresā",
				footerSucceed: "Imports sekmīgs. Ielādē...",
				loading: "Ielādē",
				error: "ķ_Pictures geolocation import failed, geolocations have been ignored._ū"
			},
			initPopup: {
				title: "Laipni lūdzam Map Tour Veidotājā",
				prevBtn: "Atpakaļ",
				nextBtn: "Nākošais"
			},
			initPopupHome: {
				header1: "ķ_Where are your images or videos?_ū",
				header2: "ķ_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._ū",
				title1: "ķ_They are already online_ū",
				title2: "ķ_I need to upload my images_ū",
				hostedFSTooltip: "ķ_Use ArcGIS Online to host your images (doesn't support videos)._ū",
				hostedFsNA: "ķ_Only available for ArcGIS for Organizations Publisher and Administrator users_ū",
				footer1: "Kad tas ir izdarīts, neaizmirstiet dalīties ar jūsu Map Tour ar jūsu auditoriju, izmantojot aplikācijas vienības lapu.",
				footer3: "Lejupielādēt CSV šablonu",
				footer4: "\"Saglabājiet kā\" ja tas nelejupielādējas",
				footer4bis: "ķ_Use right click and \"Save as\" if download doesn't start_ū",
				footer5: "ķ_Learn more_ū",
				footerProgress: "Izveide notiek",
				footerSucceed: "Izveide sekmīga. Ielādē..."
			},
			helpPopup: {
				title: "Palīdzība",
				close: "Aizvērt",
				tab1: {
					title: "Ievads",
					div1: "ķ_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._ū",
					div2: "ķ_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_ū",
					div4: "ķ_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._ū",
					div42: "ķ_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._ū",
					div5: "ķ_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._ū"
				},
				tab2: {
					title: "Dati",
					div1: "Galvenais elements, kas ir jāievēro, būvējot Map Tour, ir izvēlēties, kur tiks glabātas bildes. Map Tour varat izmantot bildes, kas saglabātas uz galvenajiem foto koplietošanas servisiem, jebkurā web serverī vai kā piesaiste elementu servisam.",
					div1a: "Aplūkojiet pēdējo sadaļu šajā tabulatorā, lai uzzinātu par atbalstītajiem attēlu un video formātiem.",
					div2: "Interaktīvais veidotājs dod jums divas iespējas apstrādāt attēlus jūsu Map Tour:",
					div3: "<ul><li>Jūs varat lietot <b>foto, kas jau ir tiešsaistē</b>, piem., attēlus, kas glabājas foto koplietošanas vietnēs, piemēram, Flickr vai saglabātos attēlus savā mājas lapā. Šiem attēliem būs atsauce jūsu Map Tour caur to URL</li><li>Jūs varat arī <b>augšupielādēt fotoattēlus no jūsu datora</b> tieši jūsu Map Tour. Šī augšupielādes opcija paredz, ka jums ir ArcGIS for Organizations abonementa konts un jums ir Izdevēja vai Administratora privilēģijas, jo tas automātiski rada viesotu elementu servisu, kur jūsu fotogrāfijas tiek saglabātas kā piesaistes)</li></ul>",
					div4: "Galvenie lietošanas gadījumi ir:",
					div4b: "<b>Jūsu fotogrāfijas vēl netiek viesotas</b> un jums ir ArcGIS online abonements: izmantot  elementu servisu ir jūsu labākā izvēle. Līdzīgi publiskajiem foto koplietošanas servisiem, mēs optimizēsim jūsu bildes, lai radītu ātras ielādēšanas attēlus un jums būs piekļuve visām ArcGIS platformas administratīvajām un datu pārvaldības iespējām.",
					div5: "<b>Jūs neesat Organizācijas biedrs</b>: Jums vispirms jāaugšupielādē savas bildes foto koplietošanas mājas lapā, vai uz jūsu web serveri. Tad veidotājs palīdzēs izmantot šīs bildes, kas turpmāk tiks viesotas savā oriģinālajā izvietojumā.",
					div6: "<b>Jūs meklējat, lai atkārtoti lietotu esošo Feature Service</b> kas glabā jūsu bildes kā piesaistes, vai kas atsaucas uz ārējām bildēm: skatiet detalizētāku nodaļu apakšā.",
					div7: "<b>Jūs esat iepriekšējās versijas lietotājs</b> Map Tour šablonam un jau ir jūsu CSV, kas atsaucas jūsu bildēm un sīktēliem: jums būs iespēja importēt un uzlabot savus datus. Veidotājs atbalsta tikai CSV, kas lieto plat/gar laukus; uz adresēm balstīts CSV var tikt turpināts lietot caur jūsu web karti (skatīt nodaļu zemāk).",
					div8: "Importē no tiešsaistes foto koplietošanas servisu",
					div9: "Importa operācijas atsaucas uz attēliem, kas tiek viesoti, saglabājot to URL web kartes elementu kolekcijā. Attēli netiek saglabāti ArcGIS Online. Ja viesotiem attēliem nevar piekļūt, tie nebūs pieejami Map Tour un jūs redzēsiet \'Attēls nav pieejams\' attēlu. Atkarībā no attēlu servisu sniedzēja, Map Tour tiks vai netiks importēts nosaukums, apraksts un attēla izvietojums. Šie atribūti tiek glabāti web kartē un jebkādi labojumi uz tiešsaistes servisiem netiks atspoguļoti Map Tour.",
					div10: "Uzglabā bildes uz web servera",
					div11: "Ja vēlaties viesot bildes pats, jums būs manuāli jāizveido sīktēli jūsu attēliem. Izmantojot pilnas rezolūcijas bildes priekš sīktēliem radīs sliktu sniegumu. Šī iemesla dēļ mēs noteikti iesakām, ka jūs izmantojat tiešsaistes foto koplietošanas servisus vai elementu servisu, kas to veiks jūsu vietā.",
					div12: "Lieto eksistējošu Feature Service vai Shapefile",
					div13: "Jebkurš punktu elementu serviss vai shape fails var tikt lietots kā Map Tour datu avots. Jums vienkārši ir jāpievieno to kā slāni savā web kartē, izmantojot arcgis.com kartes pārlūku. Ja aplikācija atrod gaidītos atribūtus jūsu slānī, visa veidotāja funkcionalitāte būs pieejama.",
					div14: "ķ_The possible values for fields name are (case insensitive):_ū",
					div151: "Nosaukums",
					div152: "Apraksts",
					div153: "Bilde",
					div154: "Sīktēls",
					div155: "ķ_Color_ū ",
					div16: "ķ_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._ū",
					div162: "Izmantojot elementu servisu kas glabā attēlus kā piesaistes, <b>tiks izmantoti tikai tie elementi kuriem ir divas piesaistes</b>. Pirmā piesaiste definē galveno attēlu, otrā definē sīkattēlu.",
					div17: "Attēlu un sīktēlu lauki ir obligāti elementu servisam bez piesaistēm un pēc izvēles (bet ļoti ieteicami) elementu servisam ar piesaistēm. Ja jūsu servisam ir iespējotas piesaistes, veidotājs ļaus jums augšupielādēt bildes kā piesaistes. Ja nē, jums būs tikai iespēja rediģēt bilžu un sīktēlu URL.",
					div172: "Ja tādi būs, vienmēr tiks izmantoti attēlu un sīkattēlu lauki un elemetu servisa piesaistes netiks pieprasītas.",
					div173: "Piemēra CSV un shape faili var tikt lejupielādēti no",
					div18: "Rada viesotu elementu servisu no CSV vai shape faila",
					div19: "Kad jūs izveidojat elementu servisu no CSV vai shape faila, piesaistes nav iespējotas pēc noklusējuma. Lai tās iespējotu, atveriet elementu servisa detaļu lapu, noklikšķiniet uz nelielas bultiņas slāņa sadaļā, un jūs redzēsiet šo opciju. Pēc tam Map Tour turpinās izmantot attēlus un sīktēlus, uz ko jūs atsaucaties caur atribūtiem. Pēc izvēles, ja jūs vēlaties augšupielādēt savas bildes kā elementu servisa piesaistes, jums būs iespēja to darīt caur divām pogām uz bildes paneļa (\"Mainīt attēlu\" un \"Mainīt sīkattēlu\").",
					div20: "Atbalstītie bilžu un video formāti",
					div21: "Atbalstītie attēla formāti: <b>.jpg, .jpeg, .png, .gif un .bmp</b>. Ja jūsu medijs nebeidzas ar šādu paplašinājumu, Map Tour uzksatīs to par video, izņemot gadījumu, ja izmanto elementu servisu (skatīt zemāk).",
					div22: "Map Tour šablons nesatur videopleijeri, tādēļ jāizmanto ārējs videopleijers, ko nodrošina video viesošanas serviss (atrodiet opciju lai iedarinātu video un iekopētu doto URL dotajā kodā) Ja vēlaties viesot video pats, jūs varat izveidot HTML lapu, kas satur videopleijeri, piemēram, <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Ineraktīvais veidotājs nenodrošina dialogu, lai iekļautu video, gadījumos kad izmanto elementu servisu ar piesaistēm, bet ir iespējams to izdarīt rediģējot datus ārpus inerkatīvā veidotāja. Arcgis.com kartes pārlūkā, ja modificējat attēla laukus, lai norādītu ārēju video, un pievienojat speciālu parametru URL beigās (#isVideo), jūsu medijs tiks uzkatīs par video.",
					div24: "Atcerieties, ka jums nepieciešami divas derīgas attēla piesaistes vai punkts netiks izmantots. Nav iespējams izmantoto video, izmantojot elementu servisa piesaistes bez attēla un sīkattēla laukiem."
				},
				tab3: {
					title: "Pielāgošana",
					div1: "Veidotājs nodrošina vairākas pielāgošanas opcijas, kas ir pieejamas, izmantojot SETTINGS pogu, kas ir augšējā panelī. Ja jūs nevarat atrast sagaidīto opciju, mēs nodrošinām arī lejupielādējamu versija, ko varat izvietot uz jūsu web servera un uzlabot, lai atbilstu jūsu vajadzībām.",
					div2: "Mēs iesakām izmantot viesoto versiju, ja vien:",
					div3: "<li>Tas nepiedāvā UI pielāgošanu, kādu vēlaties, piemēram, izmantojot galvenes fona attēlu</li><li>Jūs esat programmētājs un jūs vēlaties uzlabot aplikāciju.</li>",
					div4: "Lejupielādējamā versija var tikt konfigurēta izmantojot web karti vai web kartēšanas aplikācijas identifikatoru. Galvenie lietošanas gadījumi ir:",
					div41: "Jūs veidojat kartes tūri izmantojot interaktīvo veidotāju viesotā vidē un konfigurējat šablonu ar web kartēšanas aplikācijas identifikatoru. Tiks piemēroti iestatījumi, kurus jūs definējat ar interaktīvo veidotāju.",
					div42: "ķ_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._ū",
					div43: "Atcerieties, ka interaktīvais veidotājs ir pieejams lejupielādēšanas versijā, bet ar dažiem tehniskiem ierobežojumiem pārlūkam Internet Explorer vecākām verijām par 10.",
					div5: "ķ_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._ū"
				},
				tab4: {
					title: "Padomi",
					div0: "Atbalstītie pārlūki",
					div0a: "Map Tour pārlūks tiek atbalstīts uz IE8 un augstāka versija. Interaktīvais veidotājs tiek atbalstīts uz IE9 un augstāka versija. Mēs veicam aktīvu testēšanu visos galvenajos pārlūkos, bet gadījumā ja sastopaties ar kādām grūtībām, iesakām izmantot Chrome pārlūku.",
					div0b: "Ja jūs saskaraties ar grūtībām, lūdzu ziņojiet. Tikmēr veidojot Map Tour izmantojot CSV šablonu jūs minimizēsiet jūsu mijiedarbību ar veidotāja interfeisu.",
					div1: "Bildes",
					div2: "ķ_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._ū",
					div2a: "ķ_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._ū",
					div3: "Formatē jūsu uzrakstu tekstu, izmantojot HTML tagus",
					div4: "Galvenes un attēla nosaukums/paraksts var ietvert HTML tagus, lai definētu formatējumu un saites. Piemēram, šis kods pievieno dzeltenu saiti:",
					div4a: "ķ_Write a good subtitle for your tour_ū",
					div4b: "ķ_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._ū",
					div5: "Atbalstot slāņus",
					div6: "Jūs varat pievienot papildu atbalsta slāņus, lai nodrošinātu kontekstu Map Tour. Šie slāņi var saturēt citus ģeogrāfiskos elementus, kurus jūs vēlaties attēlot kartē paplidus Map Tour punktiem, kā piemēram, studiju areālu, iešanas vai braukšanas maršrutu, kas savieno jūsu maršruta punktus, utt. Map Tour šablons parāda šos papildu atbalsta slāņus, izmantojot jūsu norādīto simboliku šajā web kartē, bet uznirstošie logi nav pieejami.",
					div7: "Turiet jūsu ceļojumu īsu un saldu",
					div8: "Tūres limits ir 99 punkti. Protams, vairums Map Tours, būs ievērojami īsāks nekā minētie 99 punkti. Nesagaidiet, ka jūsu auditorija vēlas apskatīt pārāk daudz tūres punktus. Jūs variet uzkatīt šo tēmu par saistošu, bet nepieņemiet, ka pārējais vairums arī!",
					div9: "Lai uzzinātu vairāk, skatiet <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>detalizēts gids</a>.",
					div10: "Iedarināts režims",
					div11: "Ja vēlaties iedarināt šablonu citā web vietnē imantojot iframe, pievienojot izvēles parametru \"&embed\" URL saites beigās tiks noņemta galvene. Šads režīms var tikt iestatīs lejupielādējamajai versijai caur konfigurācijas failu.",
					div12: "ķ_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._ū" 
				},
				tab5: {
					title: "Publicē",
					div1: "ķ_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._ū",
					div2a: "ķ_Sharing the Tour through the builder_ū",
					div2b: "ķ_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._ū",
					div2c: "ķ_Sharing the Tour through ArcGIS Online_ū",
					div2d: "ķ_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._ū",
					div3t: "ķ_Feature Service security_ū",
					div3a: "ķ_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._ū",
					div3t2: "ķ_Before sharing your Tour with your audience_ū",
					div3: "ķ_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._ū",
					div4: "ķ_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._ū",
					div5a: "ķ_Recommendation for search_ū",
					div5b: "ķ_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._ū"
				}
			},
			share: {
				firstSaveTitle: "ķ_Tour successfully saved_ū",
				firstSaveHeader: "ķ_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._ū",
				firstSaveA1: "ķ_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_ū",
				firstSaveA1bis: "ķ_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._ū",
				firstSaveQ2: "ķ_Is my Tour shared?_ū",
				firstSaveA2: "ķ_Currently your Tour is not shared. To share it, use the SHARE button._ū",
				shareTitle: "ķ_Share your Tour_ū",
				sharePrivateHeader: "ķ_Your Tour is not shared, would you like to share it?_ū",
				sharePrivateBtn1: "ķ_Share publicly_ū",
				sharePrivateBtn2: "ķ_Share with my Organization_ū",
				sharePrivateProgress: "ķ_Sharing in progress..._ū",
				sharePrivateErr: "ķ_Sharing failed, try again or_ū",
				sharePrivateOk: "ķ_Sharing updated successfully, loading..._ū",
				sharePreviewAsUser: "ķ_Preview_ū",
				shareHeader1: "ķ_Your Tour is <strong>publicly accessible</strong>._ū",
				shareHeader2: "ķ_Your Tour is accessible by your organization members (login is required)._ū",
				shareLinkHeader: "ķ_Share the Tour with your audience_ū",
				shareLinkOpen: "ķ_OPEN_ū",
				shareQ1Opt1: "ķ_How do I keep the Tour private?_ū",
				shareQ1Opt2: "ķ_How do I keep the Tour private or share it publicly?_ū",
				shareA1: "ķ_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._ū",
				shareA1bis: "ķ_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._ū",
				shareQ2: "ķ_How do I edit the Tour later?_ū",
				shareQ2bis: "ķ_How do I get back to the authoring interface?_ū",
				shareA2div1: "ķ_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._ū",
				shareA2div2: "ķ_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_ū",				
				shareQ3: "ķ_Where is the data stored?_ū",
				shareA3: "ķ_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._ū"
			}
        }
    })
);
