define(
	 ({
		header: {
			start: "start",
			searchStories: "Søk i historiene dine...",
			filter: "Filter",
			sort: "Sortere",
			sortColon: "Sorter:",
			numResults: "Resultater: {{NUM_RESULTS}}",
			sortBy: "Sorter etter",
			dateModified: "Oppdatert dato",
			title: "Tittel",
			type: "Type",
			views: "Visninger",
			errors: "Feil",
			filterBy: "Filtrer etter",
			filterItems: "Filtrer elementer",
			apps: "Apper/programmer",
			sharing: "Elementdeling",
			clearAll: "Fjern alle",
			clearSearch: "Fjerner søket",
			logOut: "Logg av",
			mainQuote: "Det å fortelle historier er den mest effektive måten å dele ideer med verden på i dag.",
			quoteSource: "Robert McKee",
			checkYourStories: "Kontroller historier",
			createStory: "Opprett historie",
			totalStories: "Totalt antall historier: {{NUM_STORIES}}",
			noIssues: "Alle er ok",
			userStories: "Historier av {{USER_NAME}}",
			headerDisabledTooltip: "Vent litt mens vi tryller frem innholdet...",
			notOnTouch: "Ikke tilgjengelig på berøringsenheter",
		},
		deleteModal: {
			title: "Bekreft sletting",
			warningText: "Er du sikker på at du vil slette denne historien? Du kommer ikke til å kunne gjenopprette den.",
			deleteText: "Slett",
			cancel: "Avbryt"
		},
		loading: {
			loadingText: "Laster inn historiene dine..."
		},
		cantFindStories: {
			whereAreStories: "Ser du ikke historien din?",
			notSeeExplanation: "I My Stories finner du bare en liste over fortellende kart som er hostet på ArcGIS Online og opprettet med programmene {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} eller {{SWIPE_SPYGLASS}}. Se {{FAQ}} hvis du vil ha mer informasjon.",
			faq: "Vanlige spørsmål",
			followingStoriesToUpdate: "De følgende historiene, opprettet med tidlige versjoner av programmene våre, må oppdateres for at de skal bli oppført i My Stories:",
			gettingStories: "Søker etter historier opprettet med tidlige versjoner av programmene våre som trenger å oppdateres...",
			title: "Tittel",
			typeOfStoryMap: "Type",
			lastModified: "Sist endret",
			allUpToDate: "Ingen historier opprettet med tidlige versjoner av programmene våre trenger å oppdateres.",
			updateAll: "Oppdater alle",
			errorScanningForStories: "Det oppstod en feil under søk i historiene dine.",
			close: "Lukk",
			updates: "Oppdateringer",
			updatingNumberOfNumber: "Oppdaterer {{CURRENT_NUMBER}} av {{TOTAL}}",
			updatingNumberOfNumberAlt: "Oppdaterer {{CURRENT_NUMBER}} / {{TOTAL}}",
			updateSucceeded: "Oppdateringen er fullført!",
			reloadingStories: "Laster inn historiene dine på nytt...",
			errorUpdatingStories: "Det oppstod en feil under oppdatering av historiene dine.",
			partialUpdateMessage: "Historier som ble oppdatert: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "Logg på Story Maps",
			signInTo: "Logg på med en eksisterende ArcGIS Online-konto for å",
			explanationOne: "Opprett fengslende fortellende kart for å formidle historiene dine.",
			explanationTwo: "Bruk kartene og dataene dine fra ArcGIS Online i de fortellende kartene.",
			explanationThree: "Administrer de fortellende kartene dine, og se statusen til innholdet i dem.",
			dontHaveAccount: "Har du ingen ArcGIS Online-konto? Registrer deg, og få:",
			publicAccount: "Gratis ikke-kommersiell offentlig konto",
			orgAccount: "Gratis prøveabonnement på ArcGIS",
			timeExpired: "Påloggingen din har utløpt. Logg på på nytt for å fortsette der du slapp.",
			apiDidntLoad: "Det er noe som ikke lastes inn på riktig måte. Prøv å oppdatere siden.",
			needAccount: "Trenger du konto?",
			letsGo: "Kjør!"
		},
		sharingLevel: {
			publicMessage: "Felles",
			privateMessage: "Privat",
			organization: "Organisasjon",
			changedSharing: "Endret delingsnivå.",
			unableToChange: "Kan ikke endre deling.",
			partOfMap: "Dette elementet befinner seg i et kart. Hvis du vil endre delingsnivået for det, må du endre delingsnivået for kartet.",
			storyPublicContentOrg: "Historien din er offentlig, så innholdet i den kan ikke bare deles med organisasjonen din",
			storyPublicContentPrivate: "Historien din er offentlig, så innholdet i den kan ikke være privat",
			mapOrg: "Hvis du deler kartet med organisasjonen din, kommer det til å ødelegge historien",
			layerOrg: "Hvis du deler laget med organisasjonen din, kommer det til å ødelegge historien",
			mapPrivate: "Hvis du gjør kartet privat, kommer det til å ødelegge historien",
			layerPrivate: "Hvis du gjør laget privat, kommer det til å ødelegge historien"
		},
		collectionList: {
			advocacy: "Interesse- og hjelpearbeid",
			architecture: "Arkitektur og design",
			conservation: "Naturforvaltning og bærekraftighet",
			culture: "Kultur",
			destinations: "Reisemål og turisme",
			disasters: "Katastrofer og katastrofehåndtering",
			economy: "Økonomi og utvikling",
			entertainment: "Underholdning",
			history: "Historikk",
			infrastructure: "Infrastruktur",
			marketing: "Markedsføring",
			nature: "Natur og miljø",
			news: "Nyheter og arrangementer",
			oceans: "Hav",
			parks: "Parker og rekreasjon",
			people: "Personer og samfunn",
			planning: "Planlegging og analyse",
			publicArt: "Offentlig kunst",
			science: "Vitenskap og teknologi",
			sport: "Sport",
			travelogues: "Reisebeskrivelser"
		},
		types: {
			custom: "Tilpasset",
			notSpecified: "Type ikke angitt"
		},
		storyMap: {
			shared: "Delt",
			saveFailed: "Feil ved lagring",
			numViews: "Visninger: {{NUM_VIEWS}}",
			editStory: "Rediger historie",
			viewLive: "Vis i sanntid",
			preview: "Forhåndsvisning",
			deleteButton: "Slett",
			modified: "Endret {{DATE}}",
			summary: "Sammendrag",
			loading: "Laster inn...",
			collapse: "slå sammen",
			close: "lukk",
			hide: "skjule",
			notAvailableWhenBroken: "Historien din har problemer nedenfor",
			cantBeDeleted: "Denne historien har slettebeskyttelse aktivert, se elementsiden på ArcGIS Online for å deaktivere det",
			shareDialog: {
				title: "Del historien din med verden!",
				notPublicWarning: "Historien er delt med organisasjonen din. Bare medlemmer av organisasjonen vil kunne vise den.",
				embedStory: "Bygg inn historien",
				shortLink: "Kort kobling",
				hideHeaderBar: "Skjul topptekstlinje",
				copied: "Kopiert",
				small: "liten",
				medium: "middels",
				large: "stor",
				custom: "egendefinert",
				widthAbbreviation: "v",
				heightAbbreviation: "h",
				emptyDimension: "Angi et mål.",
				seeExample: "Forhåndsvis det du har bygd inn",
				removeHeader: "Skjul programtopptekst"
			},
			maps: {
				unableRetrieveTitle: "Kan ikke hente kart",
				unableRetrieveDescription: "Vi kan ikke hente kart for dette fortellende kartet."
			},
			images: {
				unableRetrieveTitle: "Kan ikke hente bilder",
				unableRetrieveDescription: "Vi kan ikke hente bilder for dette fortellende kartet."
			},
			tags: {
				tags: "Knagger",
				collectionTags: "Emne",
				selectASubject: "Velg et emne",
				save: "Lagre",
				saved: "Lagret",
				errorSaving: "Feil ved lagring",
				tagTip: "Tips: Med merker blir det enklere for folk å finne historien din på ArcGIS Online. Jo mer relevante merkene er, jo større synlighet får arbeidet ditt."
			},
			submitToGallery: {
				gallerySubmission: "Galleri med fortellende kart",
				canSubmitIf: "Du kan nominere historien din for galleriet hvis den inneholder følgende:",
				hasOwnImage: "et egendefinert miniatyrbilde",
				chosenSubject: "et emne og noen merker",
				chosenSubjectAlt: "et {{SUBJECT}} og noen merker",
				storyMapTopicSubject: "et emne",
				sharedPublicly: "Delt offentlig",
				noBrokenContent: "å_No issues____ø",
				nominateToGallery: "Nominer for galleriet",
				comingSoon: "Kommer snart!",
				submitted: "Sendt",
				errorSubmitting: "Feil under innsending",
				ourGallery: "Galleriet med fortellende kart",
				galleryTip: "{{THE_GALLERY}} er et bearbeidet sett med fortellende kart som viser frem noen av de beste eksemplene. Hvis historien din blir valgt ut, blir den lagt til innen 10 dager etter at du sendte den inn. På grunn av antallet nominasjoner, kan vi ikke garantere at historien din blir lagt til."
			},
			placeholders: {
				noSummary: "Ikke noe sammendrag, klikk for å legge til et."
			},
			errors: {
				cantDeleteStory: "Kan ikke slette historien.",
				unableToFind: "Finner ikke innhold",
				unableToRetrieve: "Vi kan ikke hente innholdet for dette fortellende kartet."
			},
			socialSharing: {
				availableWhenPublic: "Dette alternativet blir tilgjengelig når historien gjøres offentlig"
			},
			dialog: {
				back: "Tilbake",
				close: "Lukk",
				cancel: "Avbryt"
			},
			imagePicker: {
				changeDefault: "Endre standardbildet",
				changeImage: "Endre miniatyrbilde",
				uploadImage: "Last opp miniatyrbilde",
				chooseImage: "Velg miniatyrbilde",
				chooseAnImage: "Velg et bilde",
				notInIEVersion: "Denne funksjonen er ikke tilgjengelig i Internet Explorer {{VERSION_NUMBER}}.",
				or: "Or",
				uploadAnImage: "Last opp et bilde",
				supportedFileTypes: "Støtter .png, .jpg og .gif",
				imageSizeMessage: "Bildet ditt må være minst 286 piksler bredt og 190 piksler høyt.",
				minimumDimensions: "Minimum: 286 x 190 piksler",
				imagesLoading: "Laster inn bilder…",
				noImages: "Denne historien har ingen bilder",
				errorLoading: "Kan ikke hente bildene i denne historien",
				clickBelowTip: "Klikk knappen nedenfor for å laste opp et bilde.",
				dragAndDrop: "Dra og slipp",
				cropImage: "Beskjær bilde",
				saveImage: "Lagre bilde",
				save: "Lagre",
				savingImage: "Lagrer bildet...",
				saved: "Lagret",
				errorSaving: "Kan ikke lagre bildet.",
				skipAndCrop: "Hopp over, og beskjær det for meg",
				wrongFormat: "Denne filtypen støttes ikke.",
				noCropWarning: "Dette bildet kan ikke beskjæres, men du kan fremdeles lagre det som miniatyrbilde for historien din med de opprinnelige målene ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}} piksler)."
			}
		},
		content: {
			media: {
				maps: "Kart",
				images: "Bilder",
				videos: "Videoer",
				webpages: "Websider",
				tags: "Knagger",
				gallery: "Galleri"
			},
			headers: {
				status: "Status",
				source: "Kilde",
				name: "Navn",
				shared: "Delt"
			},
			component: {
				mapTour: "Nummerert punkt",
				bullet: "Punkt",
				tab: "Kategori",
				accordion: "Seksjon",
				mapJournal: "Seksjon"
			},
			titleType: {
				mapTour: "Undertekst",
				mapJournal: "URL",
				mapSeries: "URL"
			},
			actions: {
				viewMap: "Vis kart",
				editMap: "Rediger kart",
				fix: "Fiks",
				viewLayer: "Vis lag"
			},
			contentType: {
				mainStage: "handling på hovedstadiet",
				sidePanel: "description"
			},
			notification: {
				refreshExplanation: "Kontroller historien på nytt",
				checking: "Kontrollerer ...",
				foundSomeIssues: "Vi fant noen problemer",
				noIssuesFound: "Ingen problemer funnet",
				storyPublic: "Historien er nå offentlig",
				storyOrg: "Historien er nå delt med organisasjonen din",
				storyPrivate: "Historien er nå privat",
				mapPublic: "Kartet er nå offentlig",
				mapOrg: "Kartet er nå delt med organisasjonen din",
				mapPrivate: "Kartet er nå privat",
				layerPublic: "Laget er nå offentlig",
				layerOrg: "Laget er nå delt med organisasjonen din",
				layerPrivate: "Laget er nå privat",
				contentPublic: "Innholdet er nå offentlig",
				contentOrg: "Innholdet er nå delt med organisasjonen din",
				contentPrivate: "Innholdet er nå privat",
				storyAndContentPublic: "Historien og innholdet i den er nå offentlig",
				storyAndContentOrg: "Historien og innholdet i den er nå delt med organisasjonen din",
				storyAndContentPrivate: "Historien og innholdet i den er nå privat",
				shareBulkPrompt: "Vil du dele innholdet i historien i henhold til dette?",
				layersPublic: "Noen lag er også delt offentlig",
				layersOrg: "Noen lag er også delt med organisasjonen din",
				layersPrivate: "Noen lag har også blitt gjort private",
				mapsPublic: "Noen kart er også delt offentlig",
				mapsOrg: "Noen kart er også delt med organisasjonen din",
				mapsPrivate: "Noen kart har også blitt gjort private",
				layersAndMapsPublic: "Noen kart og lag er også delt offentlig",
				layersAndMapsOrg: "Noen kart og lag er også delt med organisasjonen din",
				layersAndMapsPrivate: "Noen kart og lag har også blitt gjort private",
				yes: "Ja",
				no: "Nei",
				premiumPublicSuccess: "Premium-innholdet ditt er nå offentlig tilgjengelig",
				subscriptionPublicSuccess: "Abonnementsinnholdet ditt er nå offentlig tilgjengelig"
			},
			errors: {
				publicDisabled: "Offentlig deling er deaktivert av administratoren",
				noMapName: "Kan ikke hente kartnavn",
				notPublic: "IKKE OFFENTLIG",
				inaccessible: "IKKE TILGJENGELIG",
				deleted: "SLETTET",
				cantAccessVideo: "Får ikke tilgang til videoen",
				noStoriesFound: "Vi finner ingen fortellende kart i innholdet ditt.",
				cantShowStories: "Kan ikke vise de fortellende kartene dine. Prøv på nytt senere.",
				consolationSearch: "Vi finner ingen historier.",
				notCompatibleWithBrowser : "My Stories støttes ikke i versjoner av Internet Explorer som er eldre enn versjon {{VERSION_NUMBER}}.",
				pleaseUpdateBrowser: "Oppdater nettleseren din",
				searchTip: "Prøv å gjøre det litt enklere.",
				consolationNoStories: "Velkommen til My Stories!",
				noStoriesTip: "Ta en titt på appsiden for å lage ditt første fortellende kart.",
				letsGo: "Kjør!",
				cantChangeSharingLevel: "Kan ikke endre delingsnivå",
				cantChangeSharingLevels: "Kan ikke endre delingsnivåer",
				errorUpdatingTitle: "Feil ved oppdatering av tittelen",
				errorUpdatingSummary: "Feil ved oppdatering av sammendraget",
				noEmptyTitle: "Tittelen kan ikke være tom",
				cantUpdatePremiumContent: "Kan ikke oppdatere Premium-innhold",
				cantUpdateSubscriptionContent: "Kan ikke oppdatere abonnementsinnhold",
				createFirstStory: "Opprett min første historie"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Kartet er slettet",
				layerHasBeenDeleted: "Laget er slettet",
				mapIsInaccessible: "Kartet er ikke tilgjengelig",
				layerIsInaccessible: "Laget er ikke tilgjengelig",
				mapNotYoursNotAccessible: "Kartet eies av noen andre og er ikke tilgjengelig",
				layerServiceOkItemNot: "Laget ble lagt til som et element som er slettet eller ikke tilgjengelig",
				layerNotYoursNotAccessible: "Laget eies av noen andre og er ikke tilgjengelig",
				mapOthersSharedBelowLevel: "Kartet er ikke eid av deg og er ikke offentlig",
				layerOthersSharedBelowLevel: "Laget er ikke eid av deg og er ikke offentlig",
				noMapNoDetails: "Uten kartdetaljene kan vi ikke fortelle deg noe om lagene",
				mapIsPrivate: "Kartet er privat",
				mapIsOrg: "Kartet er bare delt i organisasjonen din",
				layerIsPrivate: "Laget er privat",
				layerIsOrg: "Laget er bare delt i organisasjonen din",
				imageInaccessible: "Dette bildet er ikke tilgjengelig",
				videoInaccessible: "Denne videoen er ikke tilgjengelig",
				webpageInaccessible: "Denne websiden er ikke tilgjengelig",
				layerSecureService: "Laget er en sikret tjeneste",
				mapSecureService: "Kartet er en sikret tjeneste",
				layerConsumesCredits: "Laget er Premium-innhold og forbruker credits",
				layerSubscriptionContent: "Laget er abonnementsinnhold",
				mapConsumesCredits: "Kartet er Premium-innhold og forbruker credits",
				mapSubscriptionContent: "Kartet er abonnementsinnhold"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Vi kan ikke kontrollere denne typen lag",
				cantScanThisType: "Laget er ikke av en type vi kan kontrollere",
				webpageNotScanned: "Websider kontrolleres ikke for problemer"
			},
			scanningErrors: {
				deletedMap: "Slettet innhold",
				inaccessibleMap: "Utilgjengelig kartinnhold",
				notYoursNotAccessible: "Innholdet er ikke eid av deg og er ikke offentlig",
				serviceOkItemNot: "Fungerende lag, men utilgjengelige elementer",
				someContentNotPublic: "Innholdet er ikke delt offentlig",
				someContentPrivate: "Privat innhold",
				othersSharedBelowLevel: "Innholdet er ikke eid av deg og er ikke offentlig",
				premiumContent: "Premium-innhold",
				subscriptionContent: "Abonnementsinnhold",
				secureService: "Sikrede tjenester",
				inaccessibleImage: "Utilgjengelige bilder",
				inaccessibleVideo: "Utilgjengelige videoer",
				inaccessibleWebpage: "Utilgjengelige websider"
			},
			scanningErrorTips: {
				deletedMapTip: "å_Tip: Edit your web map and remove the broken content, or remove the web map from your story_____________________________ø.",
				inaccessibleMapTip: "å_Tip: Edit your web map and remove the broken content, or remove the web map from your story_____________________________ø.",
				notYoursNotAccessibleTip: "å_Tip: Edit your web map and remove the layer, or remove the web map from your story__________________________ø.",
				serviceOkItemNotTip: "Lagene ble lagt til som elementer som er utilgjengelige eller slettet. Lagene fungerer, men dette kan påvirke kartet (popuper, symboler).",
				ignore: "Ignorer",
				fix: "Fiks",
				clickToShareOrg: "Klikk på knappen for å dele alt dette innholdet med organisasjonen, eller endre hvert element manuelt ved å klikke på delingsknappene.",
				clickToSharePublic: "Klikk på knappen for å dele alt dette innholdet offentlig, eller endre hvert element manuelt ved å klikke på delingsknappene.",
				shareOrg: "Del med organisasjonen",
				sharePublicly: "Del offentlig",
				othersSharedBelowLevelTip: "Tips: Noe av historiens innhold eies av {{USER_NAME}}, og det kan hende at andre som prøver å vise historien, ikke kan se den.",
				secureServiceTip: "Tips: Fjern den sikrede tjenesten fra historien, eller følg prosedyren som er beskrevet {{HERE}}.",
				blogArticle: "her",
				premiumContentTip: "Historien din inneholder Premium-innhold som kommer til å forbruke {{CREDITS}} når du gjør den offentlig. Gjør historien offentlig og fortsett, eller fjern lagene fra historien.",
				premiumContentPublicTip: "Historien din inneholder Premium-innhold som kommer til å forbruke {{CREDITS}} når den blir offentlig tilgjengelig. Bekreft at du vil gjøre disse lagene offentlige, eller fjern lagene fra historien.",
				subscriptionContentTip: "Historien din inneholder abonnementsinnhold som i utgangspunktet ikke er offentlig tilgjengelig. Bekreft at du vil gjøre disse lagene tilgjengelige (ingen credits blir forbrukt), eller fjern disse lagene fra historien.",
				agolCredits: "ArcGIS Online-credits",
				credits: "credits",
				makePublic: "Gjør offentlig",
				confirm: "Bekreft",
				inaccessibleImageTip: "Tips: Oppgi bildet som mangler, eller fjern referansen til det.",
				inaccessibleVideoTip: "Tips: Oppgi videoen som mangler, eller fjern referansen til den.",
				inaccessibleWebpageTip: "Tips: Oppgi websiden som mangler, eller fjern referansen til den."
			},
			removeLayer: {
				title: "Fiks problem med lag",
				layersWithIssue: "Lag med dette problemet: {{NUM_WITH_ISSUE}}",
				issueExplanation: "Laget {{LAYER_NAME}} ble lagt til som et element som er utilgjengelig eller slettet. Laget fungerer, men dette kan påvirke kartet (popuper, symboler). Vi vet ikke om elementet var viktig for historien.",
				issueSolution: "Du kan løse problemet ved å redigere kartet, fjerne laget, og legge til laget i kartet igjen ved hjelp av denne webadressen:",
				editMap: "Rediger kartet",
				clickBelowWhenDone: "Når du er ferdig med å redigere, klikker du på knappen nedenfor:",
				rescanAndClose: "Søk på nytt, og lukk"
			},
			info: {
				ownedBy: "Dette elementet er eid av {{USER_NAME}}",
				unknownUser: "noen andre",
				untitledSection: "(avsnitt uten navn)",
				introRecord: "Innledning"
			},
			layers: {
				layersHeader: "Lag",
				noLayers: "(Ingen lag)",
				basemapParens: "(bakgrunnskart)"
			},
			images: {
				thumbnails: "Miniatyrbilder",
				thumbnail: "Miniatyrbilde",
				thumbnailParens: "(miniatyrbilde)"
			},
			general: {
				noTitle: "(ingen tittel)",
				loading: "Laster inn..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "avsnitt",
				secondTitle: "stil",
				secondValueA: "sidepanel",
				secondValueB: "flytende panel",
				thirdTitle: "kart"
			},
			mapTour: {
				firstTitle: "omvisningspunkter",
				secondTitle: "stil",
				secondValueA: "integrert",
				secondValueB: "trepanel",
				thirdTitle: "bakgrunnskart",
				thirdValueLoading: "Laster inn...",
				thirdValueUnknown: "ukjent"
			},
			mapSeries: {
				firstTitleA: "punkter",
				firstTitleB: "avsnitt",
				firstTitleC: "kategorier",
				secondTitle: "stil",
				secondValueA: "punktbasert",
				secondValueB: "trekkspillkontroll",
				secondValueC: "kategoribasert",
				thirdTitle: "kart"
			},
			swipeSpyglass: {
				firstTitle: "interessepunkter",
				secondTitle: "stil",
				secondValueA: "sveiping",
				secondValueB: "forstørrelsesglass",
				thirdTitle: "kart"
			}
		},
		progress: {
			checkingStories: "Ser etter problemer med historiene...",
			stop: "Stopp",
			exit: "Avslutt",
			dismiss: "Lukk",
			done: "Fullført.",
			noStoriesWithIssuesLower: "Ingen problemer funnet!",
			storiesErrorFree: "Det ser ut som historiene dine er fri for problemer",
			scanAllError: "Kan ikke søke -- vi kan ikke hente én eller flere av historiene dine",
			scanProgress: "{{NUM_SCANNED}} av {{NUM_TOTAL}}",
			scanStopped: "Historier gjennomsøkt: {{NUM_SCANNED}}, historier med problemer: {{ISSUE_STORIES}}",
			storiesWithIssues: "Historier med problemer: {{NUM_STORIES}}"
		}
    })
);
