define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Vybraná webová mapa neobsahuje platnou vrstvu vhodnou k použití. Pokud chcete pokračovat, přidejte do webové mapy editovatelnou vrstvu prvků.",
            selectFieldsText:"Vyberte pole formuláře",
            selectThemeText: "Vybrat motiv formuláře",
            fieldLabelPlaceHolder: "Označit toto pole",
            fieldDescPlaceHolder: "Popsat toto pole",
            webmapText: "1. Webová mapa",
            layerText: "2. Vrstva",
            detailsText: "3. Podrobnosti",
            fieldsText: "4. Pole",
            styleText: "5. Styl",
            previewText: "6. Náhled",
            publishText: "7. Publikovat",
            titleText: "Nástroj pro tvorbu formulářů GeoForm",
            descriptionText: "GeoForm je konfigurovatelná šablona určená k úpravě dat <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>služeb Feature Service</a> formou formulářů. Tato aplikace uživatelům umožňuje zadávat data prostřednictvím formuláře namísto vyskakovacího okna v mapě a využívá předností <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>webové mapy</a> a editovatelných služeb Feature Service. Postup v levé části stránky vám pomůže upravit a vydat vlastní formulář GeoForm.",
            btnPreviousText: "Předchozí",
            btnNextText:"Další",
            webmapTabTitleText: "Zvolte webovou mapu",
            btnSelectWebmapText:"Vybrat webovou mapu",
            layerTabTitleText: "Vybrat editovatelnou vrstvu",
            selectLayerLabelText:"Vrstva",
            selectLayerDefaultOptionText:"Vybrat vrstvu",
            detailsTabTitleText:"Podrobnosti formuláře",
            detailTitleLabelText: "Název",
            detailLogoLabelText: "Obrázek loga",
            detailDescriptionLabelText: "Popis",
            fieldTabFieldHeaderText: "Pole",
            fieldTabLabelHeaderText: "Štítek",
            fieldTabTypeHeaderText: "Typ",
            fieldTabDescriptionHeaderText: "Popis",
            previewApplicationText: "Náhled aplikace",
            saveApplicationText: "Uložit aplikaci",
            saveText: "Uložit",
            toggleNavigationText: "Přepnout navigaci",
            formPlaceholderText: "Můj formulář",
            imageLogoPlaceholderText: "http://www.mujweb.com/mujobrazek.png",
            shareBuilderInProgressTitleMessage: "Publikování formuláře GeoForm",
            shareBuilderProgressBarMessage:"Čekejte prosím…",
            shareBuilderTitleMessage: "Váš formulář GeoForm byl aktualizován a publikován!",
            shareBuilderTextMessage: "Můžete začít sbírat informace sdílením s ostatními.",
            shareDialogFormText: "Odkaz na formulář",
            geoformTitleText: "Geo Form",
            layerTabText: "Z této vrstvy bude formulář GeoForm vytvořen. Vrstva musí být služba Feature Service s povolenými úpravami a oprávněními sdílení vhodnými pro vaše publikum.",
            detailsTabText:"Pomocí polí Podrobnosti formuláře můžete přizpůsobit nadpis, přidat vlastní logo a poskytnout krátký popis pro publikum svého formuláře GeoForm.",
            fieldsTabText:"Zde můžete vybrat, která pole se zobrazí publiku vašeho formuláře GeoForm, upravit popisky, které uvidí, a přidat krátký popis, který jim pomůže se zadáváním dat.",
            styleTabText: "Upravte styl svého formuláře GeoForm podle svých představ pomocí níže uvedených motivů.",
            publishTabText: "Pokud jste s přizpůsobením formuláře GeoForm hotovi, uložte aplikaci a začněte ji sdílet se svým publikem. Vždy se můžete vrátit do tohoto nástroje pro tvorbu a na základě zpětné odezvy pokračovat v přizpůsobování."
        }
    })
);