define(
     ({
        map: {
            error: "Nelze vytvořit mapu"
        },
        onlineStatus: {
            offline: "Právě pracujete v režimu offline. Odeslané formuláře budou uloženy na místní počítač, dokud nebude navázáno spojení se serverem.",
            reconnecting: "Obnovuje se připojení&hellip;",
            pending: "Po opětovném navázání síťového připojení bude odesláno ${total} neuložených úprav."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Moje organizace",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Můj obsah",
                    favoritesLabel: "Moje oblíbené"
                },
                title: "Vybrat webovou mapu",
                searchTitle: "Hledat",
                ok: "OK",
                cancel: "Storno",
                placeholder: "Zadat vyhledávací výraz"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Moje organizace",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Můj obsah",
                    favoritesLabel: "Moje oblíbené"
                },
                title: "Vybrat skupinu",
                searchTitle: "Hledat",
                ok: "OK",
                cancel: "Storno",
                placeholder: "Zadat vyhledávací výraz"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Ř_Here is a link to a GeoForm_ů"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Odsazení v severním směru",
            utm_easting: "Odsazení ve východním směru",
            utm_zone_number: "Číslo zóny",
            geoFormGeneralTabText: "1. Zadejte informace",
            locationInformationText: "2. Vyberte umístění",
            submitInformationText: "3. Vyplňte formulář",
            submitInstructions: "Přidejte tyto informace do mapy.",
            myLocationText: "Současná poloha",
            locationDescriptionForMoreThanOneOption: "Ř_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ů.",
            locationDescriptionForOneOption: "Ř_Specify the location for this entry by clicking/tapping the map or by using the following option_ů.",
            locationDescriptionForNoOption: "Ř_Specify the location for this entry by clicking/tapping the map_ů.",
            addressText: "Hledat",
            geographic: "Zem. šířka/délka",
            locationTabText: "Umístění",
            locationPopupTitle: "Poloha",
            submitButtonText: "Odeslat záznam",
            submitButtonTextLoading: "Odesílání&hellip;",
            formValidationMessageAlertText: "Následující pole jsou povinná:",
            selectLocation: "Ř_Please select a location for your submission_ů.",
            emptylatitudeAlertMessage: "Zadejte souřadnice ${openLink}zeměpisné šířky${closeLink}.",
            emptylongitudeAlertMessage: "Zadejte souřadnice ${openLink}zeměpisné délky${closeLink}.",
            shareUserTitleMessage: "Děkujeme za váš příspěvek!",
            entrySubmitted: "Váš záznam byl odeslán do mapy.",
            shareThisForm: "Sdílet tento formulář",
            shareUserTextMessage: "Požádejte ostatní o přispění pomocí následujících možností.",
            addAttachmentFailedMessage: "K vrstvě nelze připojit přílohu.",
            addFeatureFailedMessage: "K vrstvě nelze přidat prvek.",
            noLayerConfiguredMessage: "Ř_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ů.",
            placeholderLatitude: "Zeměpisná šířka (Y)",
            placeholderLongitude: "Zeměpisná délka (X)",
            latitude: "Zeměpisná šířka",
            longitude: "Zeměpisná délka",
            findMyLocation: "Najít mou polohu",
            finding: "Vyhledávání polohy&hellip;",
            backToTop: "Zpět na začátek",
            addressSearchText: "Váš příspěvek se objeví zde. Pro opravu polohy můžete posunout špendlík.",
            shareModalFormText: "Odkaz na formulář",
            close: "Zavřít",
            locationNotFound: "Umístění nebylo nalezeno.",
            setLocation: "Nastavit polohu",
            find: "Najít adresu nebo místo",
            attachment: "Příloha",
            toggleDropdown: "Přepnout rozbalovací seznam",
            invalidString: "Ř_Please enter valid value_ů.",
            invalidSmallNumber: "Ř_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ů.",
            invalidNumber: "Ř_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ů.",
            invalidFloat: "Ř_Please enter valid ${openStrong}floating point${closeStrong} value_ů.",
            invalidDouble: "Ř_Please enter valid ${openStrong}double${closeStrong} value_ů.",
            invalidLatLong: "Ř_Please enter valid latitude and longitude coordinates_ů.",
            invalidUTM: "Ř_Please enter valid UTM coordinates_ů.",
            invalidUSNG: "Ř_Please enter valid USNG coordinates_ů.",
            invalidMGRS: "Ř_Please enter valid MGRS coordinates_ů.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Výběr&hellip;",
            applyEditsFailedMessage: "Je nám líto, vaši položku není možné odeslat. Zkuste to znovu.",
            requiredFields: "Byly nalezeny chyby. Prosím, opravte je.",
            requiredField: "(vyžadováno)",
            error: "Chyba",
            textRangeHintMessage: "${openStrong}Tip:${closeStrong} Minimální hodnota ${minValue} a Maximální hodnota ${maxValue}",
            dateRangeHintMessage: "${openStrong}Tip:${closeStrong} Minimální datum ${minValue} a Maximální datum ${maxValue}",
            remainingCharactersHintMessage: "Ř_${value} characters remaining_ů"
        },
        builder: {
            invalidUser: "Je nám líto, ale nemáte oprávnění prohlížet tuto položku.",
            invalidWebmapSelectionAlert: "Vybraná webová mapa neobsahuje platnou vrstvu vhodnou k použití. Pokud chcete pokračovat, přidejte do webové mapy editovatelnou vrstvu s prvky.",
            invalidWebmapSelectionAlert2: "Další informace naleznete v části ${openLink}Co je služba Feature Service?${closeLink}",
            selectFieldsText: "Vyberte pole formuláře",
            selectThemeText: "Vybrat motiv formuláře",
            webmapText: "Webová mapa",
            layerText: "Vrstva",
            detailsText: "Podrobnosti",
            fieldsText: "Pole",
            styleText: "Styl",
            optionText: "Možnosti",
            previewText: "Náhled",
            publishText: "Publikovat",
            optionsApplicationText: "Možnosti",
            titleText: "Nástroj pro tvorbu",
            descriptionText: "Ř_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ů.",
            btnPreviousText: "Předchozí",
            btnNextText: "Další",
            webmapTabTitleText: "Vyberte webovou mapu",
            viewWebmap: "Zobrazit webovou mapu",
            webmapDetailsText: "Ř_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ů",
            btnSelectWebmapText: "Zvolit webovou mapu",
            btnSelectWebmapTextLoading: "Načítání&hellip;",
            layerTabTitleText: "Vybrat editovatelnou vrstvu",
            selectLayerLabelText: "Vrstva",
            selectLayerDefaultOptionText: "Vybrat vrstvu",
            detailsTabTitleText: "Podrobnosti formuláře",
            detailTitleLabelText: "Nadpis",
            detailLogoLabelText: "Obrázek loga",
            descriptionLabelText: "Ř_Form Instructions & Details_ů",
            fieldDescriptionLabelText: "Ř_Help Text (optional)_ů",
            fieldTabFieldHeaderText: "Pole",
            fieldTabLabelHeaderText: "Štítek",
            fieldTabDisplayTypeHeaderText: "Zobrazit jako",
            fieldTabOrderColumnText: "Ř_Order_ů",
            fieldTabVisibleColumnText: "Ř_Enabled_ů",
            selectMenuOption: "Vybrat nabídku",
            selectRadioOption: "Přepínač",
            selectTextOption: "Text",
            selectDateOption: "Ř_Date Picker_ů",
            selectRangeOption: "Ř_Touch-Spinner_ů",
            selectCheckboxOption: "Zaškrtávací políčko",
            selectMailOption: "E-mail",
            selectUrlOption: "adresa URL",
            selectTextAreaOption: "Ř_Text Area_ů",
            previewApplicationText: "Náhled aplikace",
            saveApplicationText: "Uložit aplikaci",
            saveText: "Uložit",
            toggleNavigationText: "Přepnout navigaci",
            formPlaceholderText: "Můj formulář",
            shareBuilderInProgressTitleMessage: "Publikování formuláře GeoForm",
            shareBuilderProgressBarMessage: "Čekejte prosím&hellip;",
            shareBuilderTitleMessage: "Úspěch! Položka byla uložena.",
            shareBuilderTextMessage: "Můžete začít sbírat informace sdílením s ostatními.",
            shareModalFormText: "Odkaz na formulář",
            shareBuilderSuccess: "Váš formulář GeoForm byl aktualizován a publikován!",
            geoformTitleText: "Geo Form",
            layerTabText: "Z této vrstvy bude vytvořen formulář GeoForm. Vrstva musí být typu Feature Service s povolenými možnostmi úprav a oprávněními pro sdílení vhodnými pro vaše uživatele.",
            detailsTabText: "Pomocí polí Podrobnosti formuláře můžete přizpůsobit nadpis, přidat vlastní logo a zadat krátký popis pro uživatele svého formuláře GeoForm. Do popisu můžete přidat odkazy na další zdroje, kontaktní informace, nebo odkázat uživatele na aplikaci webového mapování obsahující všechna data shromážděná prostřednictvím formuláře GeoForm.",
            fieldsTabText: "Zde můžete vybrat, která pole se zobrazí uživatelům vašeho formuláře GeoForm, upravit popisky, které uvidí, a přidat krátký popis, který jim pomůže se zadáváním dat.",
            styleTabText: "Upravte styl svého formuláře GeoForm podle svých představ pomocí níže uvedených motivů.",
            publishTabText: "Pokud jste dokončili úpravy formuláře GeoForm, uložte aplikaci a začněte ji sdílet se svými uživateli. Do tohoto nástroje pro tvorbu se můžete kdykoli vrátit a na základě zpětné vazby aplikaci dále upravit.",
            headerSizeLabel:"Ř_Header Size_ů",
            smallHeader: "Použít malé záhlaví",
            bigHeader: "Ř_Use Large Header_ů",
            pushpinText: "Připínáček",
            doneButtonText: "Ř_Save and Exit_ů",
            fieldTabPlaceHolderHeaderText: "Tip (volitelný)",
            enableAttachmentLabelText: "Ř_${openStrong}Enable Attachments${closeStrong}_ů",
            enableAttachmentLabelHint: "Ř_You can enable/disable the attachments here_ů",
            attachmentIsRequiredLabelText: "Ř_${openStrong}Attachment Required${closeStrong}_ů",
            attachmentIsRequiredLabelHint: "Ř_If necessary, users can be required to enter an attachment_ů.",
            attachmentLabelText: "Ř_Attachment Button Label_ů",
            attachmentLabelHint: "Ř_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ů",
            attachmentDescription: "Popis přílohy",
            attachmentHint: "V případě potřeby zde můžete uvést dodatečné pokyny týkající se příloh.",
            jumbotronDescription: "Ř_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ů",
            shareGeoformText: "Sdílet formulář GeoForm",
            shareDescription: "Panel sdílení umožňuje uživatelům jednoduše sdílet formuláře GeoForm s ostatními spolupracovníky poté, co odešlou příspěvek. Tuto možnost je možné kdykoliv vypnout.",
            defaultMapExtent: "Výchozí rozsah mapy",
            defaultMapExtentDescription: "Po odeslání se mapa obnoví na výchozí rozsah Vaší webové mapy. Tuto možnost je možné kdykoliv vypnout.",
            pushpinOptionsDescription: "Zvolte si z řady barev určených pro připínáček do mapy. Barva by měla být odlišná od symbolů mapy, aby uživatelé mohli snadno umísťovat příspěvky do mapy.",
            selectLocationText: "Vybrat polohu podle",
            myLocationText: "Moje poloha",
            searchText: "Hledat",
            coordinatesText: "Souřadnice zeměpisné šířky a délky",
            usng: "Souřadnice USNG",
            mgrs: "Souřadnice MGRS",
            utm: "Souřadnice UTM",
            selectLocationSDescription: "Umožňuje uživatelům vybírat polohu těmito způsoby.",
            dragTooltipText:"Ř_Drag the field where you want it to appear_ů",
            showHideLayerText:"Ř_Show/Hide Layer_ů",
            showHideLayerHelpText:"Ř_You can configure the GeoForm to Show/Hide Layer_ů"
        }
    })
);