define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "選択した Web マップに、使用する有効なレイヤが含まれていません。編集可能なフィーチャ レイヤを Web マップに追加して、続行してください。",
            selectFieldsText:"フォーム フィールドの選択",
            selectThemeText: "フォームの主題の選択",
            fieldLabelPlaceHolder: "このフィールドにラベルを付ける",
            fieldDescPlaceHolder: "このフィールドを説明する",
            webmapText: "1. Web マップ",
            layerText: "2. レイヤ",
            detailsText: "3. 詳細",
            fieldsText: "4. フィールド",
            styleText: "5. スタイル",
            previewText: "6. プレビュー",
            publishText: "7. 公開",
            titleText: "GeoForm ビルダ",
            descriptionText: "GeoForm は、<a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>フィーチャ サービス</a>のデータをフォームベースで編集するための構成可能なテンプレートです。このアプリケーションによって、ユーザは <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web マップ</a>と編集可能なフィーチャ サービスの機能を活用しながら、マップのポップアップの代わりにフォームを使用してデータを入力できます。このビルダを使用して、左側の手順に従い、GeoForm をカスタマイズおよび配置できます。",
            btnPreviousText: "前へ",
            btnNextText:"次へ",
            webmapTabTitleText: "Web マップの選択",
            btnSelectWebmapText:"Web マップの選択",
            layerTabTitleText: "編集可能レイヤの選択",
            selectLayerLabelText:"レイヤ",
            selectLayerDefaultOptionText:"レイヤの選択",
            detailsTabTitleText:"フォームの詳細",
            detailTitleLabelText: "タイトル",
            detailLogoLabelText: "ロゴ画像",
            detailDescriptionLabelText: "説明",
            fieldTabFieldHeaderText: "フィールド",
            fieldTabLabelHeaderText: "ラベル",
            fieldTabTypeHeaderText: "タイプ",
            fieldTabDescriptionHeaderText: "説明",
            previewApplicationText: "アプリケーションのプレビュー",
            saveApplicationText: "アプリケーションの保存",
            saveText: "保存",
            toggleNavigationText: "ナビゲーションの切り替え",
            formPlaceholderText: "マイ フォーム",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "GeoForm を公開しています",
            shareBuilderProgressBarMessage:"お待ちください...",
            shareBuilderTitleMessage: "GeoForm が更新および公開されました。",
            shareBuilderTextMessage: "他のユーザと共有することで情報の収集を開始できます",
            shareDialogFormText: "フォーム リンク",
            geoformTitleText: "GeoForm",
            layerTabText: "これは GeoForm の構築元になるレイヤです。このレイヤは、一般ユーザが適切な共有権限を持ち、編集機能が有効なフィーチャ サービスである必要があります。",
            detailsTabText:"以下の [フォームの詳細] ボックスを使用して、タイトルをカスタマイズしたり、カスタム ロゴを追加したり、GeoForm の一般ユーザ向けに短い説明を入力したりします。",
            fieldsTabText:"ここで、GeoForm の一般ユーザに表示するフィールドを選択したり、ラベルを編集したり、データ入力を補助する短い説明を追加したりできます。",
            styleTabText: "必要に応じて、以下のテーマを使用して GeoForm のスタイルを設定します。",
            publishTabText: "GeoForm のカスタマイズが完了したら、アプリケーションを保存して、一般ユーザとの共有を開始します。いつでもこのビルダに戻り、フィードバックに基づいてカスタマイズを続けることができます。"
        }
    })
);