define(
     ({
        map: {
            error: "マップを作成できません"
        },
        onlineStatus: {
            offline: "現在、オフラインで作業しています。フォームの送信は、サーバに接続できるようになるまでローカルに保存されます。",
            reconnecting: "再接続しています&hellip;",
            pending: "ネットワーク接続が再び確立されると、保留中の ${total} 個の編集内容が送信されます。"
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "組織",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "マイ コンテンツ",
                    favoritesLabel: "お気に入り"
                },
                title: "Web マップの選択",
                searchTitle: "検索",
                ok: "OK",
                cancel: "キャンセル",
                placeholder: "検索語句の入力"
            },
            groupdlg: {
                items: {
                    organizationLabel: "組織",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "マイ コンテンツ",
                    favoritesLabel: "お気に入り"
                },
                title: "グループの選択",
                searchTitle: "検索",
                ok: "OK",
                cancel: "キャンセル",
                placeholder: "検索語句の入力"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "須_Here is a link to a GeoForm_鷗"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "北距",
            utm_easting: "東距",
            utm_zone_number: "ゾーン ナンバー",
            geoFormGeneralTabText: "1. 情報の入力",
            locationInformationText: "2. 位置の選択",
            submitInformationText: "3. フォームの入力",
            submitInstructions: "この情報をマップに追加します。",
            myLocationText: "現在の位置",
            locationDescriptionForMoreThanOneOption: "須_Specify the location for this entry by clicking/tapping the map or by using one of the following options_鷗.",
            locationDescriptionForOneOption: "須_Specify the location for this entry by clicking/tapping the map or by using the following option_鷗.",
            locationDescriptionForNoOption: "須_Specify the location for this entry by clicking/tapping the map_鷗.",
            addressText: "検索",
            geographic: "緯度/経度",
            locationTabText: "位置",
            locationPopupTitle: "位置",
            submitButtonText: "エントリの送信",
            submitButtonTextLoading: "送信しています&hellip;",
            formValidationMessageAlertText: "次のフィールドが必要です:",
            selectLocation: "須_Please select a location for your submission_鷗.",
            emptylatitudeAlertMessage: "${openLink}緯度${closeLink}座標を入力してください。",
            emptylongitudeAlertMessage: "${openLink}経度${closeLink}座標を入力してください。",
            shareUserTitleMessage: "ご協力ありがとうございました。",
            entrySubmitted: "エントリがマップに送信されました。",
            shareThisForm: "このフォームを共有",
            shareUserTextMessage: "次のオプションを使用して、他のユーザに提供を求めます。",
            addAttachmentFailedMessage: "添付ファイルをレイヤに追加できません",
            addFeatureFailedMessage: "フィーチャをレイヤに追加できません",
            noLayerConfiguredMessage: "須_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_鷗.",
            placeholderLatitude: "緯度 (Y)",
            placeholderLongitude: "経度 (X)",
            latitude: "緯度",
            longitude: "経度",
            findMyLocation: "現在の場所を検索",
            finding: "位置を検索しています&hellip;",
            backToTop: "トップへ戻る",
            addressSearchText: "送信内容はここに表示されます。ピンをドラッグして、位置を修正できます。",
            shareModalFormText: "フォーム リンク",
            close: "閉じる",
            locationNotFound: "場所が見つかりませんでした。",
            setLocation: "場所の設定",
            find: "住所または場所の検索",
            attachment: "添付ファイル",
            toggleDropdown: "ドロップダウンの切り替え",
            invalidString: "須_Please enter valid value_鷗.",
            invalidSmallNumber: "須_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_鷗.",
            invalidNumber: "須_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_鷗.",
            invalidFloat: "須_Please enter valid ${openStrong}floating point${closeStrong} value_鷗.",
            invalidDouble: "須_Please enter valid ${openStrong}double${closeStrong} value_鷗.",
            invalidLatLong: "須_Please enter valid latitude and longitude coordinates_鷗.",
            invalidUTM: "須_Please enter valid UTM coordinates_鷗.",
            invalidUSNG: "須_Please enter valid USNG coordinates_鷗.",
            invalidMGRS: "須_Please enter valid MGRS coordinates_鷗.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "選択&hellip;",
            applyEditsFailedMessage: "エントリが送信できません。もう一度やり直してください。",
            requiredFields: "エラーが発生しました。以下で修正してください。",
            requiredField: "(必須)",
            error: "エラー",
            textRangeHintMessage: "${openStrong}ヒント:${closeStrong} 最小値 ${minValue} および最大値 ${maxValue}",
            dateRangeHintMessage: "${openStrong}ヒント:${closeStrong} 最小日付 ${minValue} および最大日付 ${maxValue}",
            remainingCharactersHintMessage: "須_${value} characters remaining_鷗"
        },
        builder: {
            invalidUser: "このアイテムを表示する権限がありません",
            invalidWebmapSelectionAlert: "選択した Web マップに、使用する有効なレイヤが含まれていません。編集可能なフィーチャ レイヤを Web マップに追加して、続行してください。",
            invalidWebmapSelectionAlert2: "詳細については、「${openLink}フィーチャ サービスとは${closeLink}」をご参照ください。",
            selectFieldsText: "フォーム フィールドの選択",
            selectThemeText: "フォームの主題の選択",
            webmapText: "Web マップ",
            layerText: "レイヤ",
            detailsText: "詳細",
            fieldsText: "フィールド",
            styleText: "スタイル",
            optionText: "オプション",
            previewText: "プレビュー",
            publishText: "公開",
            optionsApplicationText: "オプション",
            titleText: "ビルダ",
            descriptionText: "須_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_鷗.",
            btnPreviousText: "前へ",
            btnNextText: "次へ",
            webmapTabTitleText: "Web マップの選択",
            viewWebmap: "Web マップの表示",
            webmapDetailsText: "須_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_鷗",
            btnSelectWebmapText: "Web マップの選択",
            btnSelectWebmapTextLoading: "読み込んでいます...",
            layerTabTitleText: "編集可能レイヤの選択",
            selectLayerLabelText: "レイヤ",
            selectLayerDefaultOptionText: "レイヤの選択",
            detailsTabTitleText: "フォームの詳細",
            detailTitleLabelText: "タイトル",
            detailLogoLabelText: "ロゴ画像",
            descriptionLabelText: "須_Form Instructions & Details_鷗",
            fieldDescriptionLabelText: "須_Help Text (optional)_鷗",
            fieldTabFieldHeaderText: "フィールド",
            fieldTabLabelHeaderText: "ラベル",
            fieldTabDisplayTypeHeaderText: "表示方法",
            fieldTabOrderColumnText: "須_Order_鷗",
            fieldTabVisibleColumnText: "須_Enabled_鷗",
            selectMenuOption: "メニューの選択",
            selectRadioOption: "ラジオ ボタン",
            selectTextOption: "テキスト",
            selectDateOption: "須_Date Picker_鷗",
            selectRangeOption: "須_Touch-Spinner_鷗",
            selectCheckboxOption: "チェックボックス",
            selectMailOption: "電子メール",
            selectUrlOption: "URL",
            selectTextAreaOption: "須_Text Area_鷗",
            previewApplicationText: "アプリケーションのプレビュー",
            saveApplicationText: "アプリケーションの保存",
            saveText: "保存",
            toggleNavigationText: "ナビゲーションの切り替え",
            formPlaceholderText: "マイ フォーム",
            shareBuilderInProgressTitleMessage: "GeoForm を公開しています",
            shareBuilderProgressBarMessage: "お待ちください&hellip",
            shareBuilderTitleMessage: "アイテムを正常に保存しました",
            shareBuilderTextMessage: "他のユーザと共有することで情報の収集を開始できます",
            shareModalFormText: "フォーム リンク",
            shareBuilderSuccess: "GeoForm が更新および公開されました。",
            geoformTitleText: "GeoForm",
            layerTabText: "これは GeoForm の構築元になるレイヤです。このレイヤは、一般ユーザが適切な共有権限を持ち、編集機能が有効なフィーチャ サービスである必要があります。",
            detailsTabText: "以下の [フォームの詳細] ボックスを使用して、タイトルをカスタマイズしたり、カスタム ロゴを追加したり、GeoForm の一般ユーザ向けに短い説明を入力したりします。説明では、他のリソースや連絡先情報へのリンクを追加したり、GeoForm で収集したデータのすべてを備えた Web マップ アプリケーションを一般ユーザに示したりすることができます。",
            fieldsTabText: "ここで、GeoForm の一般ユーザに表示するフィールドを選択したり、ラベルを編集したり、データ入力を補助する短い説明を追加したりできます。",
            styleTabText: "必要に応じて、以下のテーマを使用して GeoForm のスタイルを設定します。",
            publishTabText: "GeoForm のカスタマイズが完了したら、アプリケーションを保存して、一般ユーザとの共有を開始します。いつでもこのビルダに戻り、フィードバックに基づいてカスタマイズを続けることができます。",
            headerSizeLabel:"須_Header Size_鷗",
            smallHeader: "小さいヘッダーを使用",
            bigHeader: "須_Use Large Header_鷗",
            pushpinText: "ピンをプッシュ",
            doneButtonText: "須_Save and Exit_鷗",
            fieldTabPlaceHolderHeaderText: "ヒント (オプション)",
            enableAttachmentLabelText: "須_${openStrong}Enable Attachments${closeStrong}_鷗",
            enableAttachmentLabelHint: "須_You can enable/disable the attachments here_鷗",
            attachmentIsRequiredLabelText: "須_${openStrong}Attachment Required${closeStrong}_鷗",
            attachmentIsRequiredLabelHint: "須_If necessary, users can be required to enter an attachment_鷗.",
            attachmentLabelText: "須_Attachment Button Label_鷗",
            attachmentLabelHint: "須_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_鷗",
            attachmentDescription: "添付ファイルの説明",
            attachmentHint: "必要に応じて、添付ファイルの追加の指示をここに入力できます。",
            jumbotronDescription: "須_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_鷗",
            shareGeoformText: "Geoform の共有",
            shareDescription: "いったん送信すると、共有パネルにより、一般ユーザが他の協力者と GeoForm を容易に共有できるようになります。これは、いつでも無効にできます。",
            defaultMapExtent: "デフォルトのマップ範囲",
            defaultMapExtentDescription: "送信後、マップは Web マップのデフォルトの範囲にリセットされます。これは、いつでも無効にできます。",
            pushpinOptionsDescription: "マップの押しピンの色を選択します。ユーザがマップで使用する際に便利なように、マップのシンボルとは違う色にします。",
            selectLocationText: "位置の選択で使用",
            myLocationText: "現在の場所",
            searchText: "検索",
            coordinatesText: "緯度および経度座標",
            usng: "USNG 座標",
            mgrs: "MGRS 座標",
            utm: "UTM 座標",
            selectLocationSDescription: "ユーザはこれらの方法を使用して位置を選択できます。",
            dragTooltipText:"須_Drag the field where you want it to appear_鷗",
            showHideLayerText:"須_Show/Hide Layer_鷗",
            showHideLayerHelpText:"須_You can configure the GeoForm to Show/Hide Layer_鷗"
        }
    })
);