define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ø_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._å",
            selectFieldsText:"ø_Select Form Fields_å",
            selectThemeText: "Vælg formulartema",
            fieldLabelPlaceHolder: "Forsyn dette felt med en label",
            fieldDescPlaceHolder: "Beskriv dette felt",
            webmapText: "ø_1. Webmap_å",
            layerText: "ø_2. Layer_å",
            detailsText: "ø_3. Details_å",
            fieldsText: "ø_4. Fields_å",
            styleText: "ø_5. Style_å",
            previewText: "ø_6. Preview_å",
            publishText: "ø_7. Publish_å",
            titleText: "GeoForm Builder",
            descriptionText: "ø_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._å",
            btnPreviousText: "Forrige",
            btnNextText:"Næste",
            webmapTabTitleText: "Vælg et webkort",
            btnSelectWebmapText:"Vælg webkort",
            layerTabTitleText: "Vælg redigérbart lag",
            selectLayerLabelText:"Lag",
            selectLayerDefaultOptionText:"Vælg lag",
            detailsTabTitleText:"Formularoplysninger",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logobillede",
            detailDescriptionLabelText: "Beskrivelse",
            fieldTabFieldHeaderText: "Felt",
            fieldTabLabelHeaderText: "Mærke",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Beskrivelse",
            previewApplicationText: "Få vist eksempel på applikation",
            saveApplicationText: "Gem applikation",
            saveText: "Gem",
            toggleNavigationText: "ø_Toggle navigation_å",
            formPlaceholderText: "ø_My Form_å",
            imageLogoPlaceholderText: "ø_http://www.mysite.com/myimage.png_å",
            shareBuilderInProgressTitleMessage: "ø_Publishing GeoForm_å",
            shareBuilderProgressBarMessage:"ø_Please Wait..._å",
            shareBuilderTitleMessage: "ø_Your GeoForm has been updated & published!_å",
            shareBuilderTextMessage: "ø_You can start collecting information by sharing with others_å",
            shareDialogFormText: "ø_Form Link_å",
            geoformTitleText: "ø_Geo Form_å",
            layerTabText: "ø_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._å",
            detailsTabText:"ø_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._å",
            fieldsTabText:"ø_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._å",
            styleTabText: "ø_Style your GeoForm using the themes below based on your preference._å",
            publishTabText: "ø_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._å"
        }
    })
);