define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Det valgte webkort indeholder ikke noget gyldigt lag, som kan anvendes. Føj et redig\érbart vektorlag til dit webkort for at fortsætte.",
            selectFieldsText:"Vælg formularfelter",
            selectThemeText: "Vælg formulartema",
            fieldLabelPlaceHolder: "Forsyn dette felt med en label",
            fieldDescPlaceHolder: "Beskriv dette felt",
            webmapText: "1. Webkort",
            layerText: "2. Lag",
            detailsText: "3. Detaljer",
            fieldsText: "4. Felter",
            styleText: "5. Typografi",
            previewText: "6. Forhåndsvisning",
            publishText: "7. Offentliggør",
            titleText: "GeoForm Builder",
            descriptionText: "GeoForm er en konfigur\érbar skabelon til formularbaseret redigering af en <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>featuretjeneste</a>. Denne applikation gør brugere i stand til at indtaste data via en formular i stedet for pop-up’en til et kort, samtidig med at styrken i <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>webkortet</a> og de redig\érbare featuretjenester udnyttes. Brug dette builder-program til at tilpasse og implementere din GeoForm ved hjælp af fremgangsmåden til venstre.",
            btnPreviousText: "Forrige",
            btnNextText:"Næste",
            webmapTabTitleText: "Vælg et webkort",
            btnSelectWebmapText:"Vælg webkort",
            layerTabTitleText: "Vælg redigérbart lag",
            selectLayerLabelText:"Lag",
            selectLayerDefaultOptionText:"Vælg lag",
            detailsTabTitleText:"Formularoplysninger",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logobillede",
            detailDescriptionLabelText: "Beskrivelse",
            fieldTabFieldHeaderText: "Felt",
            fieldTabLabelHeaderText: "Mærke",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Beskrivelse",
            previewApplicationText: "Få vist eksempel på applikation",
            saveApplicationText: "Gem applikation",
            saveText: "Gem",
            toggleNavigationText: "Skift navigation",
            formPlaceholderText: "Min formular",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "Publicerer GeoForm",
            shareBuilderProgressBarMessage:"Vent...",
            shareBuilderTitleMessage: "Din GeoForm er blevet opdateret og publiceret!",
            shareBuilderTextMessage: "Du kan starte indsamling af oplysninger ved at dele med andre",
            shareDialogFormText: "Formular-link",
            geoformTitleText: "GeoForm",
            layerTabText: "GeoForm vil blive oprettet ud fra dette lag. Laget skal være en featuretjeneste, der er aktiveret for redigering med de delingsrettigheder, der er relevante for dit publikum.",
            detailsTabText:"Brug felterne med formularoplysninger til at tilpasse titlen, tilføje et brugerdefineret logo og indtaste en kort beskrivelse til dit GeoForm-publikum.",
            fieldsTabText:"Her kan du vælge, hvilke felter der skal være synlige for dit GeoForm-publikum, redigere de labels, de får vist, og tilføje en kort beskrivelse til hjælp for dataindtastning.",
            styleTabText: "Forsyn din GeoForm med en typografi ved hjælp af temaerne nedenfor på grundlag af dine præferencer.",
            publishTabText: "Hvis du er færdig med at tilpasse din GeoForm, kan du gemme applikationen og begynde at dele med dit publikum. Du kan altid vende tilbage til dette builder-program og fortsætte tilpasningen på grundlag af feedback."
        }
    })
);