define(
({
		viewer: {
			loading: {
				step1: "ก้_LOADING APPLICATION_ษฺ",
				step2: "ก้_LOADING DATA_ษฺ",
				step3: "ก้_INITIALIZING THE TOUR_ษฺ",
				loadBuilder: "ก้_SWITCHING TO BUILDER MODE_ษฺ",
				redirectSignIn: "ก้_REDIRECTING TO SIGN-IN PAGE_ษฺ",
				redirectSignIn2: "ก้_(you will be redirected here after sign-in)_ษฺ",
				fail: "ก้_Sorry, Map Tour loading failed_ษฺ",
				failButton: "ก้_Retry_ษฺ"
			},
			errors: {
				boxTitle: "ก้_An error has occurred_ษฺ",
				portalSelf: "ก้_Fatal error: Failed to get portal configuration_ษฺ",
				invalidConfig: "ก้_Fatal error: Invalid configuration_ษฺ",
				invalidConfigOwner: "ก้_Fatal error: Invalid configuration (authorized owner required)_ษฺ",
				invalidConfigNoWebmap: "ก้_Fatal error: Invalid configuration (web map or application identifier not specified in index.html)_ษฺ",
				createMap: "ก้_Unable to create map_ษฺ",
				invalidApp: "ก้_Fatal error: The application cannot be loaded_ษฺ",
				noLayer: "ก้_The web map does not contain a valid data layer for Map Tour._ษฺ",
				noLayerMobile: "ก้_Welcome to the Map Tour web application. The application is not configured. The Map Tour builder is not supported on mobile devices._ษฺ",
				noLayerView: "ก้_Welcome to the Map Tour web application.<br />The application is not configured yet._ษฺ",
				appSave: "ก้_Error saving the web application_ษฺ",
				mapSave: "ก้_Error saving the web map_ษฺ",
				featureServiceLoad: "ก้_Error loading feature service_ษฺ",
				notAuthorized: "ก้_You are not authorized to access this application_ษฺ",
				oldBrowserTitle: "ก้_Browser not fully supported_ษฺ",
				noBuilderIE8: "ก้_The Map Tour builder is not supported on Internet Explorer before version 9._ษฺ",
				ie10Win7Explain: "ก้_The Map Tour interactive builder is not supported on Internet Explorer 10 on Windows 7 when the data source is a Feature Service with attachments. To use a Feature Service with attachments, you have to <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manually force document mode to Internet Explorer 9 standards</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgrade to Internet Explorer 9</a> or upgrade to Windows 8._ษฺ",
				oldBrowserExplain: "ก้_This browser doesn't support automatic thumbnail generation from the images you upload into your map tour. You can create a map tour using this browser, but you will have to provide a separate thumbnail image for each of the images you upload._ษฺ",
				oldBrowserExplain2: "ก้_To improve your experience, <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activate Google Chrome Frame for Internet Explorer</a>._ษฺ",
				oldBrowserExplain3: "ก้_The Map Tour builder doesn't work with Internet Explorer 10 on Windows XP._ษฺ",
				oldBrowserClose: "ก้_Close_ษฺ"
			},
			mobileHTML: {
				showIntro: "ก้_SHOW TITLE_ษฺ",
				hideIntro: "ก้_HIDE TITLE_ษฺ",
				navList: "ก้_List_ษฺ",
				navMap: "ก้_Map_ษฺ",
				navInfo: "ก้_Media_ษฺ",
				introStartBtn: "ก้_Start_ษฺ"
			},
			desktopHTML: {
				storymapsText: "ก้_A story map_ษฺ",
				builderButton: "ก้_Switch to builder mode_ษฺ",
				bitlyTooltip: "ก้_Get a short link to the application_ษฺ",
				bitlyStartIndex: "ก้_Link to current place_ษฺ"
			},
			builderHTML: {
				panelHeader: "ก้_APPLICATION CONFIGURATION_ษฺ",
				buttonSave: "ก้_SAVE_ษฺ",
				buttonSettings: "ก้_Settings_ษฺ",
				buttonShare: "ก้_Share_ษฺ",
				buttonView: "ก้_View mode_ษฺ",
				buttonItem: "ก้_Open the Web Application item_ษฺ",
				buttonHelp: "ก้_Help_ษฺ",
				buttonOrganize: "ก้_Organize_ษฺ",
				buttonAdd: "ก้_Add_ษฺ",
				buttonImport: "ก้_Import_ษฺ",
				buttonImportDisabled: "ก้_Import is not available when using a Feature Service with attachments_ษฺ",
				dataEditionDisabled: "ก้_Data edition is disabled on CSV data source_ษฺ",
				dataSourceWarning: "ก้_The Map Tour data layer has changed. If the features ID are not the same, you have to reset the order and hidden points through <b>Organize</b>. If the fields name differs, you have to reset the fields settings under the <b>data tab in Settings</b>._ษฺ",
				organizeWarning: "ก้_One or multiple points added outside of the interactive builder are hidden._ษฺ",
				dataPicError0a: "ก้_This tour includes <b>%NB%</b> non-compliant picture URLs._ษฺ",
				dataPicError0b: "ก้_This tour may includes <b>%NB%</b> non-compliant picture URLs._ษฺ",
				dataPicError1: "ก้_Map Tour now requires that a picture URL end with one of the following extension: .jp(e)g, .png, .gif or .bmp._ษฺ",
				dataPicError2: "ก้_This requirement will not affect your existing published Map Tour. However, in order to use the interactive builder, you must first resolve the URL issue by performing one of two actions:_ษฺ",
				dataPicError3: "ก้_Edit URLs_ษฺ",
				dataPicError4: "ก้_This will add <i>#isImage</i> to the end of unsupported picture URLs. Most server support URL appendages. However, once you have performed that action, you should verify that the updated picture URLs are functional by navigating through your points. If each pictures loads, you can now save the Map Tour. If <b>pictures are broken, don’t save the Map Tour</b>. Instead, reload the builder and perform the second action._ษฺ",
				dataPicError5: "ก้_Limit the tour to pictures_ษฺ",
				dataPicError6: "ก้_This option cause all URLs to be considered images, but you won't be able to add videos using the interactive builder. This action is reversible, should you decide to add video in the future._ษฺ",
				dataPicError7: "ก้_Your Map Tour has been restricted to pictures, videos can't be used. If you choose to remove that limitation, check that your pictures still loads correctly before saving the Map Tour. You will be able to restore that limitation later if needed._ษฺ",
				dataPicError8: "ก้_Remove picture limitation_ษฺ",
				dataPicError9: "ก้_If these URLs points to videos you can ignore this warning, if they point to image, you need to perform one of the following two actions:_ษฺ",
				modalCancel: "ก้_Cancel_ษฺ",
				modalApply: "ก้_Apply_ษฺ",
				organizeHeader: "ก้_Organize the tour_ษฺ",
				organizeGeneralCaption: "ก้_Use drag and drop to sort tour points_ษฺ",
				organizeDelete: "ก้_Delete_ษฺ",
				organizeHide: "ก้_Hide_ษฺ",
				organizeReset: "ก้_Reset order and hidden points_ษฺ",
				addMaxPointReached: "ก้_You have reached the maximum number of points authorized by the icons set and cannot add another tour point.<br /><br />Note that if you delete existing points, you will need to reload the application._ษฺ",
				addMaxPointReachedMobile: "ก้_Sorry, you have reached the maximum number of authorized points and cannot add that picture._ษฺ",
				addClose: "ก้_Close_ษฺ",
				addHeader: "ก้_Add a new tour point_ษฺ",
				addTabPicture: "ก้_Media_ษฺ",
				addTabInformation: "ก้_Information_ษฺ",
				addTabLocation: "ก้_Location_ษฺ",
				addSelectCaption: "ก้_Select or drop picture_ษฺ",
				addNoteVideo: "ก้_Consult Help for instructions on using videos_ษฺ",		
				addSelectCaptionNoFileReader: "ก้_Select picture_ษฺ",	
				addChangePhoto: "ก้_Change picture and thumbnail_ษฺ",
				addPictureResolutionIntro: "ก้_The picture resolution is higher than required:_ษฺ",
				addPictureResolutionOldBrowser: "ก้_The picture resolution is higher than required. Optimize the Map Tour experience by specifying a resolution lower than %RECOMMENDED_RES%._ษฺ",
				addPictureResolutionResize: "ก้_Change picture resolution to %RESOLUTION%_ษฺ",
				addPictureResolutionKeep: "ก้_Keep the original resolution of %RESOLUTION%_ษฺ",
				addSelectThumbnail: "ก้_Select thumbnail_ษฺ",
				addNoThumbSelected: "ก้_No thumbnail selected_ษฺ",
				addThumbSelected: "ก้_Selected_ษฺ",
				addCameraSettingsHeader: "ก้_CAMERA SETTINGS_ษฺ",
				addThumbnailHeader: "ก้_THUMBNAIL_ษฺ",
				addLabelPicUrl: "ก้_Picture_ษฺ",
				addLabelThumbUrl: "ก้_Thumbnail_ษฺ",
				addTextPlaceholderUrl: "ก้_Enter an image URL_ษฺ",
				addTextPlaceholderUrl2: "ก้_Enter a Youtube page URL_ษฺ",
				addTextPlaceholderUrl3: "ก้_Enter a Vimeo page URL_ษฺ",
				addTextPlaceholderUrl4: "ก้_Enter a video embed URL_ษฺ",
				addLabelVideo: "ก้_Video_ษฺ",
				addMediaVideoOther: "ก้_Other_ษฺ",
				addMediaVideoHelp: "ก้_Check the URL and get the default thumbnail_ษฺ",
				addMediaVideoHelpTooltip1: "ก้_Check succeeded_ษฺ",
				addMediaVideoHelpTooltip2: "ก้_Check failed_ษฺ",
				addMediaVideoHelpTooltip4: "ก้_Find the option to embed the video and copy the video URL that is present in the code_ษฺ",
				addLabelName: "ก้_Name_ษฺ",
				addLabelDescription: "ก้_Caption_ษฺ",
				addTextPlaceholder: "ก้_Type something_ษฺ",
				addLocatePlaceholder: "ก้_Locate an address or a place_ษฺ",
				addPinColor: "ก้_Color_ษฺ",
				addLatitude: "ก้_Latitude_ษฺ",
				addLongitude: "ก้_Longitude_ษฺ",
				addLatitudePlaceholder: "ก้_e.g. 34.056_ษฺ",
				addLongitudePlaceholder: "ก้_e.g. -117.195_ษฺ",
				addUploading: "ก้_Uploading tour point_ษฺ",
				addSave: "ก้_Add tour point_ษฺ",
				addMobileUploading: "ก้_Uploading picture_ษฺ",
				addMobileName: "ก้_Enter a name_ษฺ",
				addMobileNameMandatory: "ก้_Error, please enter a name._ษฺ",
				addMobileError: "ก้_Sorry, something has gone wrong_ษฺ",
				settingsHeader: "ก้_Application settings_ษฺ",
				settingsTabLayout: "ก้_Layout_ษฺ",
				settingsTabColor: "ก้_Colors_ษฺ",
				settingsTabLogo: "ก้_Header_ษฺ",
				settingsTabFields: "ก้_Data_ษฺ",
				settingsTabExtent: "ก้_Extent_ษฺ",
				settingsTabZoom: "ก้_Zoom Level_ษฺ",
				settingsLayoutExplain: "ก้_Select the application layout you want._ษฺ",
				settingsLayoutProfessional: "ก้_Three-panel Layout_ษฺ",
				settingsLayoutModern: "ก้_Integrated Layout_ษฺ",
				settingsLayoutSelected: "ก้_Selected layout_ษฺ",
				settingsLayoutSelect: "ก้_Select this layout_ษฺ",
				settingsLayoutNote: "ก้_Note that on points using videos, the placard will always be placed under the video even if that option is unchecked._ษฺ",
				settingsLayoutLocBtn: "ก้_Display a 'Locate' button_ษฺ",
				settingsLayoutLocBtnHelp: "ก้_That functionality is supported on most mobile device and desktop browsers (Internet Explorer 9)._ษฺ",
				settingsColorExplain: "ก้_Change appearance by choosing a pre-defined theme, or create your own._ษฺ",
				settingsLabelColor: "ก้_Header, content and footer colors_ษฺ",
				settingsLogoExplain: "ก้_Customize the header logo (maximum is 250 x 50px)._ษฺ",
				settingsLogoEsri: "ก้_Esri logo_ษฺ",
				settingsLogoNone: "ก้_No logo_ษฺ",
				settingsLogoCustom: "ก้_Custom logo_ษฺ",
				settingsLogoCustomPlaceholder: "ก้_Image URL_ษฺ",
				settingsLogoCustomTargetPlaceholder: "ก้_Click-through link_ษฺ",
				settingsLogoSocialExplain: "ก้_Customize the header top right link._ษฺ",
				settingsLogoSocialText: "ก้_Text_ษฺ",
				settingsLogoSocialLink: "ก้_Link_ษฺ",
				settingsLogoSocialDisabled: "ก้_This feature has been disabled by the Administrator_ษฺ",
				settingsDataFieldsExplain: "ก้_Select photo name, caption and color fields._ษฺ",
				settingsDataFieldsError: "ก้_The application cannot determine the appropriate name, caption or color data. Please select the fields to be used here. These settings can be changed at a later time._ษฺ",
				settingsFieldsLabelName: "ก้_Name_ษฺ",
				settingsFieldsLabelDescription: "ก้_Caption_ษฺ",
				settingsFieldsLabelColor: "ก้_Color_ษฺ",
				settingsFieldsReset: "ก้_Reset fields selection_ษฺ",
				settingsExtentExplain: "ก้_Set the Map Tour initial extent through the interactive map below._ษฺ",
				settingsExtentExplainBottom: "ก้_The extent you define will modify your web map initial extent. Note that this extent isn't used if it doesn't include the first tour point. In that case the tour will open centered on the first point._ษฺ",
				settingsExtentDateLineError: "ก้_The extent cannot be across the meridian of 180° longitude_ษฺ",
				settingsExtentDateLineError2: "ก้_Error computing the extent_ษฺ",
				settingsExtentDrawBtn: "ก้_Draw a new extent_ษฺ",
				settingsExtentModifyBtn: "ก้_Edit the extent_ษฺ",
				settingsExtentApplyBtn: "ก้_Preview on Map Tour_ษฺ",
				settingsExtentUseMainMap: "ก้_Use Map Tour extent_ษฺ",
				settingsZoomExplain: "ก้_Set zoom for story points following introduction (optional)._ษฺ",
				settingsLabelZoom: "ก้_Scale/level_ษฺ",
				settingsZoomFirstValue: "ก้_None_ษฺ",
				settingsFieldError: "ก้_Please select a field in each list_ษฺ",
				dataTitle: "ก้_ArcGIS Online hosting_ษฺ",
				dataExplain: "ก้_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._ษฺ",
				dataNameLbl: "ก้_Service name_ษฺ",
				dataFolderListLbl: "ก้_Folder_ษฺ",
				dataFolderListFetching: "ก้_Fetching folders ..._ษฺ",
				dataRootFolder: "ก้_Root_ษฺ",
				dataNameError: "ก้_Enter a name for the feature service_ษฺ",
				dataFolderError: "ก้_Select a valid folder_ษฺ",
				dataSrcContainsInvalidChar: "ก้_The feature service name contains one or more invalid characters (-, <, >, #, %, :, \", ?, &, +, /, or \)._ษฺ",
				dataSrvAlreadyExistsError: "ก้_A service with that name already exists within the organization. Please choose a different name._ษฺ",
				dataBtnSave: "ก้_Create the service_ษฺ",
				dataFooterProgress: "ก้_Creation in progress_ษฺ",
				dataFooterSucceed: "ก้_Creation succeeded. Loading_ษฺ",
				dataFooterError: "ก้_Creation failed. Please try again_ษฺ",
				tabError: "ก้_Please check for errors in all tabs_ษฺ",
				introRecordBtn: "ก้_Intro_ษฺ",
				introRecordActivate: "ก้_Use the first point as introduction (does not appear in carousel)_ษฺ"
			},
			addPopupJS: {
				uploadingPicture: "ก้_Uploading picture_ษฺ",
				uploadSuccess: "ก้_Upload successful_ษฺ",
				uploadError: "ก้_Error uploading the picture_ษฺ",
				uploadError2: "ก้_Error adding the feature (invalid html tag)_ษฺ",
				notJpg: "ก้_Please choose a jpeg photo to upload_ษฺ",
				errorNoPhoto: "ก้_Choose an image to upload_ษฺ",
				errorNoThumbnail: "ก้_Choose a thumbnail to upload_ษฺ",
				errorInvalidPicUrl: "ก้_Enter a valid picture (starts with http(s)://, ends with jpg, png, gif or bmp). You can end the URL with '#isImage' to override that rule._ษฺ",
				errorInvalidThumbUrl: "ก้_Enter a valid thumbnail (starts with http(s)://, ends with jpg, png, gif or bmp)._ษฺ",
				errorInvalidVideoUrl: "ก้_Enter a valid video URL (starts with http(s)://)_ษฺ",
				errorNoName: "ก้_Enter a name for this tour point_ษฺ",
				errorNoDescription: "ก้_Enter a caption for this tour point_ษฺ",
				errorNoLocation: "ก้_Set a location for this tour point_ษฺ"
			},
			builderJS: {
				noPendingChange: "ก้_No unsaved change_ษฺ",
				unSavedChangeSingular: "ก้_1 unsaved change_ษฺ",
				unSavedChangePlural: "ก้_unsaved changes_ษฺ",
				shareStatus1: "ก้_Tour is not saved_ษฺ",
				shareStatus2: "ก้_Tour is shared publicly_ษฺ",
				shareStatus3: "ก้_Tour is shared within the organization_ษฺ",
				shareStatus4: "ก้_Tour is not shared_ษฺ",
				popoverDiscard: "ก้_Are you sure to want to discard any unsaved changes?_ษฺ",
				yes: "ก้_Yes_ษฺ",
				no: "ก้_No_ษฺ",
				popoverLoseSave: "ก้_By opening the viewer, you will lose any unsaved changes_ษฺ",
				ok: "ก้_Ok_ษฺ",
				popoverSaveWhenDone: "ก้_Don't forget to save when you are done_ษฺ",
				closeWithPendingChange: "ก้_Are you sure to want to confirm the action ? Your changes will be lost._ษฺ",
				gotIt: "ก้_Ok_ษฺ",
				savingApplication: "ก้_Saving application_ษฺ",
				saveSuccess: "ก้_Application saved successfully_ษฺ",
				saveError: "ก้_Save failed, please try again_ษฺ",
				saveError2: "ก้_Save failed due to an invalid html tag in a name or description_ษฺ",
				saveError3: "ก้_The title can't be empty_ษฺ",
				dragColorPicker: "ก้_Move me around<br />or change my color_ษฺ",
				dataWarningExtent: "ก้_You have data outside of the web map extent. Those data won't be used as tour points, change map extent if you want to use them._ษฺ",
				dataWarningVisibi: "ก้_Your Map Tour layer is not visible at the current web map extent. Confirm your Map Tour layer is visible with a %MAPSIZE% large map._ษฺ",
				dataWarningEdit: "ก้_Edit web map_ษฺ",
				dataWarningClose: "ก้_Close_ษฺ",
				signIn: "ก้_Please sign in with an account on_ษฺ",
				signInTwo: "ก้_to save the application._ษฺ",
				switchBM: "ก้_Change Basemap_ษฺ"
			},
			organizePopupJS: {
				messageStart: "ก้_You have chosen to delete_ษฺ",
				messageSinglePoint: "ก้_one tour point_ษฺ",
				messageMultiPoint: "ก้_tour points_ษฺ",
				messagePermantRemove: "ก้_This will permanently remove the_ษฺ",
				messageRecord: "ก้_record_ษฺ",
				messageRecordPlural: "ก้_records_ษฺ",
				messageConfirm: "ก้_from your database. Do you want to continue?_ษฺ",
				labelButtonShow: "ก้_Show_ษฺ",
				labelButtonHide: "ก้_Hide_ษฺ"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "ก้_This will permanently delete the picture and thumbnail_ษฺ",
				popoverDeleteWarningThumb: "ก้_This will permanently delete the thumbnail_ษฺ",
				popoverUploadingPhoto: "ก้_Uploading picture and thumbnail_ษฺ",
				popoverUploadingThumbnail: "ก้_Uploading thumbnail_ษฺ",
				popoverUploadSuccessful: "ก้_Upload successful_ษฺ",
				popoverUploadError: "ก้_Upload failed, please try again_ษฺ",
				changePicAndThumb: "ก้_Change picture_ษฺ",
				changeThumb: "ก้_Change thumbnail_ษฺ",
				selectPic: "ก้_Change media_ษฺ",
				selectThumb: "ก้_Change thumbnail_ษฺ",
				uploadPicAndThumb: "ก้_Apply_ษฺ"
			},
			headerJS:{
				editMe: "ก้_Edit me !_ษฺ",
				templateTitle: "ก้_Set template title_ษฺ",
				templateSubtitle: "ก้_Set template subtitle_ษฺ"
			},
			crossFaderJS:{
				setPicture: "ก้_Set picture title_ษฺ",
				setCaption: "ก้_Set picture caption_ษฺ"
			},
			importPopup: {
				title: "ก้_Import_ษฺ",
				prevBtn: "ก้_Back_ษฺ",
				nextBtn: "ก้_Next_ษฺ"
			},
			importPopupHome: {
				header: "ก้_Where are your pictures stored ?_ษฺ"
			},
			onlinePhotoSharingCommon: {
				pictures: "ก้_pictures_ษฺ",
				videos: "ก้_videos_ษฺ",
				disabled: "ก้_This feature has been disabled by the Administrator_ษฺ",
				disabledPortal: "ก้_This feature is disabled on Portal for ArcGIS_ษฺ",
				header1: "ก้_Your pictures must be shared publicly._ษฺ",
				header2: "ก้_The import will be limited to the first %NB1% %MEDIA%._ษฺ",
				emptyDataset: "ก้_Error, no pictures found_ษฺ",
				footerImport: "ก้_Import_ษฺ",
				selectAlbum: "ก้_Select a public album_ษฺ",
				selectAlbum2: "ก้_Select an album_ษฺ",
				pleaseChoose: "ก้_Please Choose_ษฺ",
				userLookup: "ก้_Look up_ษฺ",
				userLookingup: "ก้_Looking up_ษฺ",
				csv: "ก้_Referenced in a CSV_ษฺ",
				advanced: "ก้_Advanced options_ษฺ",
				advancedScratchLbl: "ก้_Start a new Tour_ษฺ",
				advancedScratchTip: "ก้_Create an empty Tour that you will be able populate manually using a wizard._ษฺ",
				advancedCSVLbl: "ก้_Import Tour data from a CSV file_ษฺ",
				advancedCSVTip: "ก้_Import your Tour content from a CSV file._ษฺ",
				advancedCommonTip: "ก้_It requires that your images and videos are already online._ษฺ",
				select: "ก้_Make a selection_ษฺ",
				locUse: "ก้_Use pictures geolocation_ษฺ",
				locExplain: "ก้_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._ษฺ",
				locExplain2: "ก้_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._ษฺ"
			},
			viewFlickr: {
				title: "ก้_Flickr import_ษฺ",
				header: "ก้_Enter your Flickr user name and select a Photo Set or a Tag to be imported._ษฺ",
				userInputLbl: "ก้_Enter a User Name_ษฺ",
				signInMsg2: "ก้_User not found_ษฺ",
				selectSet: "ก้_Select a Photo Set_ษฺ",
				selectTag: "ก้_or Select a Tag_ษฺ",
				footerImportTag: "ก้_Import the selected Tag_ษฺ",
				footerImportSet: "ก้_Import the selected Set_ษฺ"
			},
			viewFacebook: {
				title: "ก้_Facebook import_ษฺ",
				header: "ก้_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._ษฺ",
				leftHeader: "ก้_Facebook User_ษฺ",
				rightHeader: "ก้_Facebook Page_ษฺ",
				pageExplain: "ก้_A Facebook page is a public brand/product or celebrity like <b>esrigis</b>. You can get the page name after the first '/' in the page URL._ษฺ",
				pageInputLbl: "ก้_Enter a page name_ษฺ",
				lookupMsgError: "ก้_Page not found_ษฺ"
			},
			viewPicasa: {
				title: "ก้_Picasa/Google+ import_ษฺ",
				header: "ก้_Enter your email address or the ID of your Picasa or Google+ account._ษฺ",
				userInputLbl: "ก้_Enter an email or ID_ษฺ",
				signInMsg2: "ก้_Account not found_ษฺ",
				howToFind: "ก้_How to find a Picasa or Google+ account ID_ษฺ",
				howToFind2: "ก้_Copy digits between the first and second '/' of any Picasa or G+ page_ษฺ"
			},
			viewCSV: {
				title: "ก้_CSV import_ษฺ",
				uploadBtn: "ก้_Select or drop a CSV file_ษฺ",
				resultHeaderEmpty: "ก้_The CSV is empty_ษฺ",
				resultHeaderSuccess: "ก้_Successfully loaded %NB_POINTS% points_ษฺ",
				resultHasBeenLimited: "ก้_The import has been limited to the first %VAL1% points out of %VAL2% to respect the limit of %VAL3% points per tour_ษฺ",
				browserSupport: "ก้_Your browser isn't supported, to use a CSV you have to <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or use ArcGIS.com web map viewer (see Help)._ษฺ",
				errorLatLng: "ก้_Latitude and Longitude fields haven't been found. Possible values for latitude are: <i>%LAT%</i> and for longitude: <i>%LONG%</i>._ษฺ",
				errorFieldsExplain: "ก้_The loading failed as the following required fields hasn't been found_ษฺ",
				errorFieldsName: "ก้_<b>Name</b> possible values are: %VAL%_ษฺ",
				errorFieldsDesc: "ก้_<b>Description</b> possible values are: %VAL%_ษฺ",
				errorFieldsUrl: "ก้_<b>Picture URL</b> possible values are: %VAL%_ษฺ",
				errorFieldsThumb: "ก้_<b>Thumbnail URL</b> possible values are: %VAL%_ษฺ",
				errorFields2Explain: "ก้_The loading failed as the CSV does not use the same attributes than the layer for the following attributes_ษฺ",
				errorFields2Name: "ก้_<b>Name</b> use %VAL1% instead of %VAL2%_ษฺ",
				errorFields2Desc: "ก้_<b>Description</b> use %VAL1% instead of %VAL2%_ษฺ",
				errorFields2Url: "ก้_<b>Picture URL</b> use %VAL1% instead of %VAL2%_ษฺ",
				errorFields2Thumb: "ก้_<b>Thumbnail URL</b> use %VAL1% instead of %VAL2%_ษฺ",
				resultFieldsAll: "ก้_All attributes have been imported_ษฺ",
				resultFieldsNotAll: "ก้_The following attributes haven't been imported because they don't exists in the map layer_ษฺ",
				resultFieldsNotAll2: "ก้_The following attributes have been imported_ษฺ",
				footerNextBtnResult: "ก้_Import into the web map_ษฺ",
				footerProgress: "ก้_Import in progress_ษฺ",
				footerSucceed: "ก้_Import succeeded. Loading_ษฺ"
			},
			viewYoutube: {
				title: "ก้_Youtube import_ษฺ",
				header: "ก้_Enter a YouTube user name to find publicly shared videos._ษฺ",
				pageInputLbl: "ก้_Enter a Youtube user name_ษฺ",
				lookupMsgError: "ก้_User not found_ษฺ",
				howToFind: "ก้_How to find a Youtube user name_ษฺ",
				howToFind2: "ก้_User name is displayed under videos_ษฺ",
				found: "ก้_Found_ษฺ",
				noData: "ก้_No public videos found_ษฺ"
			},
			viewGeoTag: {
				title: "ก้_Select and locate your images/videos_ษฺ",
				header: "ก้_Click or tap the pictures you want to import to locate them._ษฺ",
				headerMore: "ก้_Why aren't my images/videos geolocated?_ษฺ",
				headerExplain: "ก้_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._ษฺ",
				leftPanelTab1: "ก้_To locate_ษฺ",
				leftPanelTab2: "ก้_Located_ษฺ",
				clickOrTap: "ก้_Click or tap the Map to locate_ษฺ",
				clearLoc: "ก้_Clear locations_ษฺ",
				clickDrop: "ก้_Do not import_ษฺ",
				footerImport: "ก้_Import_ษฺ",
				footerProgress: "ก้_Import in progress_ษฺ",
				footerSucceed: "ก้_Import succeeded. Loading..._ษฺ",
				loading: "ก้_Loading_ษฺ",
				error: "ก้_Pictures geolocation import failed, geolocations have been ignored._ษฺ"
			},
			initPopup: {
				title: "ก้_Welcome to the Map Tour Builder_ษฺ",
				prevBtn: "ก้_Back_ษฺ",
				nextBtn: "ก้_Next_ษฺ"
			},
			initPopupHome: {
				header1: "ก้_Where are your images or videos?_ษฺ",
				header2: "ก้_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._ษฺ",
				title1: "ก้_They are already online_ษฺ",
				title2: "ก้_I need to upload my images_ษฺ",
				hostedFSTooltip: "ก้_Use ArcGIS Online to host your images (doesn't support videos)._ษฺ",
				hostedFsNA: "ก้_Only available for ArcGIS for Organizations Publisher and Administrator users_ษฺ",
				footer1: "ก้_When you are done, don't forget to share your Map Tour with your audience through the application item page._ษฺ",
				footer3: "ก้_Download the CSV template_ษฺ",
				footer4: "ก้_\"Save as\" if it doesn't download_ษฺ",
				footer4bis: "ก้_Use right click and \"Save as\" if download doesn't start_ษฺ",
				footer5: "ก้_Learn more_ษฺ",
				footerProgress: "ก้_Creation in progress_ษฺ",
				footerSucceed: "ก้_Creation succeeded. Loading..._ษฺ"
			},
			helpPopup: {
				title: "ก้_Help_ษฺ",
				close: "ก้_Close_ษฺ",
				tab1: {
					title: "ก้_Introduction_ษฺ",
					div1: "ก้_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._ษฺ",
					div2: "ก้_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_ษฺ",
					div4: "ก้_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._ษฺ",
					div42: "ก้_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._ษฺ",
					div5: "ก้_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._ษฺ"
				},
				tab2: {
					title: "ก้_Data_ษฺ",
					div1: "ก้_The main element to consider when building a Map Tour is to choose where your pictures will be stored. A Map Tour can use pictures stored on major photo sharing services, on any web server, or as attachments to a feature service._ษฺ",
					div1a: "ก้_See the last section of this tab for details about supported picture formats and videos._ษฺ",
					div2: "ก้_The interactive builder gives you two options for handling the images in your Map Tour:_ษฺ",
					div3: "ก้_<ul><li>You can use <b>photos that are already online</b>, such as images stored in a photo sharing site like Flickr, or images stored on your own website. These images will be referenced in your Map Tour via their URLs.</li><li>You can also <b>upload photos from your computer</b> directly into your Map Tour. This upload option requires that you have an ArcGIS Online subscription and that you have Publisher or Administrator privileges, because a hosted feature service is automatically created for you in which your photos are stored as attachments.</li></ul>_ษฺ",
					div4: "ก้_The main use cases are:_ษฺ",
					div4b: "ก้_<b>Your photos are not hosted</b> yet and you have an ArcGIS Online subscription: Using a hosted feature service is your best choice. Like public photo sharing services, we will optimize your pictures to create fast-loading images and you will have access to all administration and data management capabilities of the ArcGIS platform._ษฺ",
					div5: "ก้_<b>You aren't a member of an Organization</b>: You first have to upload your pictures to a photo sharing website or to your own web server. The builder will help you use these pictures that will continue to be hosted at their original location._ษฺ",
					div6: "ก้_<b>You are looking to reuse an existing Feature Service</b> that stores your pictures as attachments or that references external pictures: See the detailed section below._ษฺ",
					div7: "ก้_<b>You are a user of a previous version</b> of the Map Tour template and already have your CSV that references your pictures and thumbnails: You will be able to import it and refine your data. The builder only supports CSVs that use lat/long fields; address-based CSVs can continue to be used through your web map (see section below)._ษฺ",
					div8: "ก้_Importing from online photo sharing services_ษฺ",
					div9: "ก้_The import operation references pictures that are already hosted by storing their URLs in a web map feature collection. The pictures are not stored in ArcGIS Online. If the hosted pictures can't be accessed, they won't be available in the Map Tour and you'll see a 'Picture not available' image. Depending on your photo service provider, the Map Tour may not import the name, description, and location of the pictures. Those attributes are stored in the web map and any edits to the online services won't be reflected in the Map Tour._ษฺ",
					div10: "ก้_Storing the pictures on a web server_ษฺ",
					div11: "ก้_If you choose to host the pictures yourself, you will have to manually create thumbnails of your pictures. Using the full resolution pictures for the thumbnail will result in poor performance. For that reason, we strongly recommend that you use an online photo sharing services or a feature service that will do that for you._ษฺ",
					div12: "ก้_Using an existing Feature Service or Shapefile_ษฺ",
					div13: "ก้_Any point feature service or shapefile can be used as a Map Tour data source. You just have to add it as a layer into your web map through the arcgis.com Map Viewer. If the application finds the expected attributes in your layer, all builder functionalities will be available._ษฺ",
					div14: "ก้_The possible values for fields name are (case insensitive):_ษฺ",
					div151: "ก้_Name_ษฺ",
					div152: "ก้_Description_ษฺ",
					div153: "ก้_Picture_ษฺ",
					div154: "ก้_Thumbnail_ษฺ",
					div155: "ก้_Color_ษฺ ",
					div16: "ก้_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._ษฺ",
					div162: "ก้_When using a feature service that stores the pictures as attachments, <b>only the features with two attachments will be used</b>. The first attachment defines the main picture, and the second attachment defines the thumbnail._ษฺ",
					div17: "ก้_The picture and thumbnail fields are mandatory for feature services without attachments and optional (but strongly recommended) for feature services with attachments. If your service has attachments enabled, the builder will let you upload pictures as attachments. If not, you will only be able to edit the picture and thumbnail URLs._ษฺ",
					div172: "ก้_When present, the picture and thumbnail fields will always be used and the feature service attachments won't be queried._ษฺ",
					div173: "ก้_Example CSVs and shapefiles can be downloaded from_ษฺ",
					div18: "ก้_Creating a hosted Feature Services from a CSV or shapefile_ษฺ",
					div19: "ก้_When you create a hosted feature service from a CSV or shapefile, the attachments are not enabled by default. To enable them, open the feature service’s details page, click the small arrow on the layer section, and you will see that option. The Map Tour will continue to use the pictures and thumbnail you have referenced through attributes. Optionally, if you want to upload your pictures as feature service attachments, you will be able to do so through two buttons on the picture panel (\"Change Picture\" and \"Change Thumbnail\")._ษฺ",
					div20: "ก้_Supported pictures formats and videos_ษฺ",
					div21: "ก้_Supported picture format are: <b>.jpg, .jpeg, .png, .gif and .bmp</b>. If your media doesn’t end with that extension, the Map Tour will consider it to be a video, except when using a feature service (see below)._ษฺ",
					div22: "ก้_The Map Tour template doesn't include a video player, so you have to use the external video player provided by your favorite video hosting service (find the option to embed the video and copy the URL present in the given code). If you want to host the video yourself, you can create an HTML page that contains a video player like <a href='http://www.videojs.com/'>Video.js</a>._ษฺ",
					div23: "ก้_The interactive builder doesn't provide a dialog to include video when using feature services with attachments, but it is possible to do so by editing your data outside of the interactive builder. In the arcgis.com map viewer, if you modify the picture fields to point to an external video and add a special parameter at the end of your URL (#isVideo), your media will be considered to be a video._ษฺ",
					div24: "ก้_Note that you still need to have two valid pictures attachments or the point won’t be used. It isn't possible to use videos when using feature service attachments without the picture and thumbnail fields._ษฺ"
				},
				tab3: {
					title: "ก้_Customization_ษฺ",
					div1: "ก้_The builder provides several customization options that are accessible through the SETTINGS button in the top panel. If you don't find the option you expect, we also provide a downloadable version that you can deploy on your web server and enhance to fit your needs._ษฺ",
					div2: "ก้_We recommend that you use the hosted version unless:_ษฺ",
					div3: "ก้_<li>It doesn't offer a UI customization you want to have, like using a header background image.</li><li>You are a developer and you want to enhance the application.</li>_ษฺ",
					div4: "ก้_The downloadable version can be configured through a web map or a web mapping application identifier. The main use cases are:_ษฺ",
					div41: "ก้_You build your map tour using the interactive builder in the hosted environment and configure the template with the web mapping application identifier. The settings you have defined with the interactive builder will be applied._ษฺ",
					div42: "ก้_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._ษฺ",
					div43: "ก้_Note that the interactive builder is available in the downloadable version but with some technical restrictions on browsers like Internet Explorer older than version 10._ษฺ",
					div5: "ก้_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._ษฺ"
				},
				tab4: {
					title: "ก้_Tips_ษฺ",
					div0: "ก้_Supported browsers_ษฺ",
					div0a: "ก้_The Map Tour viewer is supported on IE8+. The interactive builder is supported on IE9+. We actively test it in all major browsers but if you experience some difficulties, we recommend that you use Chrome._ษฺ",
					div0b: "ก้_If you experience some difficulties, please let us know. In the meantime, by building your Map Tour using the CSV template you will minimize your interaction with the builder interface._ษฺ",
					div1: "ก้_Pictures_ษฺ",
					div2: "ก้_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._ษฺ",
					div2a: "ก้_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._ษฺ",
					div3: "ก้_Formatting your caption text using HTML tags_ษฺ",
					div4: "ก้_The header and picture title/caption can include HTML tags to define formatting and links. For example, this code adds a yellow link:_ษฺ",
					div4a: "ก้_Write a good subtitle for your tour_ษฺ",
					div4b: "ก้_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._ษฺ",
					div5: "ก้_Supporting Layers_ษฺ",
					div6: "ก้_You can add additional supporting layers to provide context to the Map Tour. These layers may contain other geographic features you want the map to show in addition to the Map Tour points, such as a study area, a walking or driving route linking your tour points, etc. The Map Tour template displays these additional supporting layers using the symbology you specify in the web map, but the popups aren't available._ษฺ",
					div7: "ก้_Keep your tour short and sweet_ษฺ",
					div8: "ก้_There's a limit of 99 points per tour. Most Map Tours will of course be significantly shorter than this. Don't expect your audience to want to step through too many tour points. You might find your subject fascinating, but don't assume they will, too!_ษฺ",
					div9: "ก้_To learn more, see <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>the detailed guide</a>._ษฺ",
					div10: "ก้_Embed mode_ษฺ",
					div11: "ก้_If you want to embed the template in another website through an iframe, adding the optional parameter \"&embed\" at the end of the URL will remove the header. That mode can also be set in the downloadable version through the configuration file._ษฺ",
					div12: "ก้_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._ษฺ" 
				},
				tab5: {
					title: "ก้_Publishing_ษฺ",
					div1: "ก้_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._ษฺ",
					div2a: "ก้_Sharing the Tour through the builder_ษฺ",
					div2b: "ก้_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._ษฺ",
					div2c: "ก้_Sharing the Tour through ArcGIS Online_ษฺ",
					div2d: "ก้_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._ษฺ",
					div3t: "ก้_Feature Service security_ษฺ",
					div3a: "ก้_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._ษฺ",
					div3t2: "ก้_Before sharing your Tour with your audience_ษฺ",
					div3: "ก้_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._ษฺ",
					div4: "ก้_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._ษฺ",
					div5a: "ก้_Recommendation for search_ษฺ",
					div5b: "ก้_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._ษฺ"
				}
			},
			share: {
				firstSaveTitle: "ก้_Tour successfully saved_ษฺ",
				firstSaveHeader: "ก้_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._ษฺ",
				firstSaveA1: "ก้_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_ษฺ",
				firstSaveA1bis: "ก้_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._ษฺ",
				firstSaveQ2: "ก้_Is my Tour shared?_ษฺ",
				firstSaveA2: "ก้_Currently your Tour is not shared. To share it, use the SHARE button._ษฺ",
				shareTitle: "ก้_Share your Tour_ษฺ",
				sharePrivateHeader: "ก้_Your Tour is not shared, would you like to share it?_ษฺ",
				sharePrivateBtn1: "ก้_Share publicly_ษฺ",
				sharePrivateBtn2: "ก้_Share with my Organization_ษฺ",
				sharePrivateProgress: "ก้_Sharing in progress..._ษฺ",
				sharePrivateErr: "ก้_Sharing failed, try again or_ษฺ",
				sharePrivateOk: "ก้_Sharing updated successfully, loading..._ษฺ",
				sharePreviewAsUser: "ก้_Preview_ษฺ",
				shareHeader1: "ก้_Your Tour is <strong>publicly accessible</strong>._ษฺ",
				shareHeader2: "ก้_Your Tour is accessible by your organization members (login is required)._ษฺ",
				shareLinkHeader: "ก้_Share the Tour with your audience_ษฺ",
				shareLinkOpen: "ก้_OPEN_ษฺ",
				shareQ1Opt1: "ก้_How do I keep the Tour private?_ษฺ",
				shareQ1Opt2: "ก้_How do I keep the Tour private or share it publicly?_ษฺ",
				shareA1: "ก้_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._ษฺ",
				shareA1bis: "ก้_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._ษฺ",
				shareQ2: "ก้_How do I edit the Tour later?_ษฺ",
				shareQ2bis: "ก้_How do I get back to the authoring interface?_ษฺ",
				shareA2div1: "ก้_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._ษฺ",
				shareA2div2: "ก้_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_ษฺ",				
				shareQ3: "ก้_Where is the data stored?_ษฺ",
				shareA3: "ก้_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._ษฺ"
			}
        }
    })
);
