define({
    root: ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "กรอกตัวสร้าง",
                "exitBuilderButtonText": "ออกจากตัวสร้าง",
                "enterBuilderModeHelpText": "กรอกแบบตัวสร้างเพื่อกำหนดในโปรแกรมประยุกต์",
                "builderModeHelpText": "โครงร่างแบบตัวสร้าง",
                "webmapCaption": "แผนที่",
                "selectMapMessage": "ปัจจุบัน ${displaying} <b>${webmapTitle}</b><br/>คลิก Select map เพื่อเลือกเว็บแม็พที่แตกต่าง",
                "loadMapMessage": "เลือก <b>${webmapTitle}</b><br/>คลิก Save เพื่อใช้เว็บแม็พนี้",
                "changeWebmap": "เลือกแผนที่",
                "saveButtonText": "บันทึก",
                "webmapNextButtonText": "ถัดไป ->",
                "previousButtonText":"ก่อนหน้า",
                "layerLabelText": "ชั้นข้อมูล",
                "noLayerFoundText": "ไม่พบชั้นข้อมูล",
                "selectLayer": "เลือกชั้นข้อมูล",
                "applicationSettingText": "ตั้งค่าโปรแกรมประยุกต์",
                "summaryAttrAscendingOrderTooltip": "เรียงจากน้อยไปมาก",
                "onStartLabel": "เริ่มต้น",
                "selectVariableText": "เลือกตัวแปร",
                "selectVariableDropdown": "เลือกตัวแปร",
                "label":"ตัวอักษร",
                "sourceLinkText":"เชื่อมโยงแหล่งที่มา",
                "selectSubVariableText":"เลือกตัวแปรย่อย",
                "subVariablePanelButtonText":"เสร็จ",
                "onButtonLabel":"เปิด",
                "offButtonLabel":"ปิด",
                "appSettingsSaveCloseButtonText": "บันทึกและปิด",
                "appSettingsTitleText":"ชื่อแอ็พ",
                "appSettingsDescriptionText": "คำบรรยายโปรแกรมประยุกต์",
                "appSetingsRendererAreaText":"พื้นที่แสดงผล",
                "shareText":"แชร์",
                "popupText": "ป๊อปอัพ",
                "basemapText":"แผนที่ฐาน",
                "cancel": "ยกเลิก",
                "theme": "หัวข้อ",
                "zoomLevel": "ระดับการขยาย",
                "existingValue": "ใช้ค่าที่มีอยู่แล้ว",
                "enrichLayer": "การปรับแต่งข้อมูลเพิ่มเติม",
                "imageLabel": "ทำงานได้อย่างไร ?",
                "clearData": "ล้างข้อมูล",
                "basemapSelectionText":"การเลือกแผนที่าน",
                "secondaryBasemapText":"แผนที่ฐานทุติยภูมิ",
                "defaultBasemapText": "แผนที่ฐานเริ่มต้น",
                "entireAreaButton": "พื้นที่ทั้งหมด",
                "entireAreaOnStartButton": "พื้นที่ทั้งหมดในการเริ่มต้น",
                "aboutPanel": "เกี่ยวกับแผงหน้าปัดข้อมูล",
                "legendPanel": "หน้าต่างสัญลักษณ์",
                "layersPanel": "หน้าต่างชั้นข้อมูล",
                "dataConfigurationButtonText": "การกำหนดข้อมูล",
                "savingChangesMessage": "กำลังจัดเก็บการเปลี่ยนแปลง...",
                "nextButtonText": "ถัดไป",
                "prevButtonText": "ก่อน",
                "enterLabelText": "กรอกตัวอักษร",
                "SelectedFeatureText": "ฟีเจอร์ที่เลือก",
                "layerHelpTextMessage": "โปรแกรมประยุกต์นี้",
                "alertMessage": {
                    "resetVariableMessage": "คุณแน่ใจว่าต้องการปรับตัวแปรใหม่ ?",
                    "emptyAppTitleMessage": "ชื่อโปรแกรมไม่สามารถเว้นว่าง",
                    "emptyDescriptionMessage": "คำบรรยายไม่สามารถเว้นว่าง",
                    "maxVariableSelection": "คุณไม่สามารถเลือกตัวแปรย่อยมากกว่า 25 ตัวแปร",
                    "signInFail" : "เข้าใช้ระบบล้มเหลว",
                    "itemUpdateMessage": "อัพเดทรายการ",
                    "unsavedChangesMessage": "ไม่ได้บันทึกการเปลี่ยนแปลง",
                    "failMessage": "ไม่สามารถอัพเดทรายการอย่างสมบูรณ์",
                    "saveChangesAlert": "คุณต้องการจัดเก็บการเปลี่ยนแปลงนี้หรือไม่ ?",
                    "variableLabelValidation": "ตัวแปรนี้ไม่สามารถว่างเปล่า",
                    "subVariableLabelValidation": "ตัวแปรย่อยไม่สามารถที่จะว่างเปล่า"
                    }
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});