define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ķ_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ū",
            selectFieldsText:"ķ_Select Form Fields_ū",
            selectThemeText: "Atlasīt formas dizainu",
            fieldLabelPlaceHolder: "Atzīmēt šo lauku",
            fieldDescPlaceHolder: "Aprakstīt šo lauku",
            webmapText: "ķ_1. Webmap_ū",
            layerText: "ķ_2. Layer_ū",
            detailsText: "ķ_3. Details_ū",
            fieldsText: "ķ_4. Fields_ū",
            styleText: "ķ_5. Style_ū",
            previewText: "ķ_6. Preview_ū",
            publishText: "ķ_7. Publish_ū",
            titleText: "GeoForm Builder",
            descriptionText: "ķ_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._ū",
            btnPreviousText: "Iepriekšējs",
            btnNextText:"Tālāk",
            webmapTabTitleText: "Tīmekļa kartes izvēle",
            btnSelectWebmapText:"Atlasiet tīmekļa karti",
            layerTabTitleText: "Atlasiet rediģējamu slāni",
            selectLayerLabelText:"Slānis",
            selectLayerDefaultOptionText:"Atlasīt slāni",
            detailsTabTitleText:"Formas detaļas",
            detailTitleLabelText: "Nosaukums",
            detailLogoLabelText: "Logotipa attēls",
            detailDescriptionLabelText: "Apraksts",
            fieldTabFieldHeaderText: "Lauks",
            fieldTabLabelHeaderText: "Kartes teksts",
            fieldTabTypeHeaderText: "Tips",
            fieldTabDescriptionHeaderText: "Apraksts",
            previewApplicationText: "Priekšskatīt aplikāciju",
            saveApplicationText: "Saglabāt aplikāciju",
            saveText: "Saglabāt",
            toggleNavigationText: "ķ_Toggle navigation_ū",
            formPlaceholderText: "ķ_My Form_ū",
            imageLogoPlaceholderText: "ķ_http://www.mysite.com/myimage.png_ū",
            shareBuilderInProgressTitleMessage: "ķ_Publishing GeoForm_ū",
            shareBuilderProgressBarMessage:"ķ_Please Wait..._ū",
            shareBuilderTitleMessage: "ķ_Your GeoForm has been updated & published!_ū",
            shareBuilderTextMessage: "ķ_You can start collecting information by sharing with others_ū",
            shareDialogFormText: "ķ_Form Link_ū",
            geoformTitleText: "ķ_Geo Form_ū",
            layerTabText: "ķ_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ū",
            detailsTabText:"ķ_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._ū",
            fieldsTabText:"ķ_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ū",
            styleTabText: "ķ_Style your GeoForm using the themes below based on your preference._ū",
            publishTabText: "ķ_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ū"
        }
    })
);