define({
  root: ({
    layer: "ķ_Layer___ū",
    sort: "ķ_Sort by___ū",
    order: "ķ_Order___ū",
    desc: "ķ_Desc__ū",
    asc: "ķ_Asc__ū",
    loading: "ķ_loading&hellip;______ū",
    search: "ķ_Search___ū",
    searchPlaceholder: "ķ_Find reports_____ū",
    noResults: "ķ_No results____ū",
    ascending: "ķ_Ascending____ū",
    descending: "ķ_Descending____ū"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});