define(
     ({
        map: {
            error: "Nevar izveidot karti"
        },
        onlineStatus: {
            offline: "Jūs pašreiz strādājat bezsaistē. Iesniegtās formas tiks saglabātas lokāli, līdz tiks izveidots savienojums ar serveri.",
            reconnecting: "Notiek atkārtota savienošana&hellip;",
            pending: "Kad tīkla savienojums tiks atjaunots, tiks iesniegti ${total} neapstrādāti labojumi."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organizācija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mans saturs",
                    favoritesLabel: "Mani favorīti"
                },
                title: "Izvēlēties web karti",
                searchTitle: "Meklēšana",
                ok: "Labi",
                cancel: "Atcelt",
                placeholder: "Ievadīt meklēšanas kritēriju"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organizācija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mans saturs",
                    favoritesLabel: "Mani favorīti"
                },
                title: "Atlasīt grupu",
                searchTitle: "Meklēšana",
                ok: "Labi",
                cancel: "Atcelt",
                placeholder: "Ievadīt meklēšanas kritēriju"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "ķ_Here is a link to a GeoForm_ū"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Virzība uz ziemeļiem",
            utm_easting: "Virzība uz austrumiem",
            utm_zone_number: "Zonas numurs",
            geoFormGeneralTabText: "1. Ievadiet informāciju",
            locationInformationText: "2. Atlasiet atrašanās vietu",
            submitInformationText: "3. Aizpildiet veidlapu",
            submitInstructions: "Pievienot šo informāciju kartei.",
            myLocationText: "Pašreizējais izvietojums",
            locationDescriptionForMoreThanOneOption: "ķ_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ū.",
            locationDescriptionForOneOption: "ķ_Specify the location for this entry by clicking/tapping the map or by using the following option_ū.",
            locationDescriptionForNoOption: "ķ_Specify the location for this entry by clicking/tapping the map_ū.",
            addressText: "Meklēt",
            geographic: "Ģeogrāfiskais platums/garums",
            locationTabText: "Izvietojums",
            locationPopupTitle: "Atrašanās vieta",
            submitButtonText: "Iesniegt jaunu ierakstu",
            submitButtonTextLoading: "Iesniegšana&hellip;",
            formValidationMessageAlertText: "Tālāk norādītie lauki ir obligāti.",
            selectLocation: "ķ_Please select a location for your submission_ū.",
            emptylatitudeAlertMessage: "Lūdzu, ievadiet ${openLink}platuma${closeLink} koordinātu.",
            emptylongitudeAlertMessage: "Lūdzu, ievadiet ${openLink}garuma${closeLink} koordinātu.",
            shareUserTitleMessage: "Pateicamies par ieguldījumu!",
            entrySubmitted: "Jūsu ieraksts ir iesniegts kartei.",
            shareThisForm: "Koplietot šo šablonu",
            shareUserTextMessage: "Jūsu ieraksts ir iesniegts. Kopīgojiet ar citiem, izmantojot tālāk minētās iespējas.",
            addAttachmentFailedMessage: "Slānim nevar pievienot pielikumu",
            addFeatureFailedMessage: "Slānim nevar pievienot elementu",
            noLayerConfiguredMessage: "ķ_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ū.",
            placeholderLatitude: "Platums (Y)",
            placeholderLongitude: "Garums (X)",
            latitude: "Platums",
            longitude: "Garums",
            findMyLocation: "Atrast manu izvietojumu",
            finding: "Izvietojuma noteikšana&hellip;",
            backToTop: "Augšup",
            addressSearchText: "Jūsu iesniegtā informācija būs redzama šeit. Varat vilkt spraudīti, lai koriģētu atrašanās vietu.",
            shareModalFormText: "Veidlapas saite",
            close: "Aizvērt",
            locationNotFound: "Izvietojumu nevar atrast.",
            setLocation: "Iestatīt izvietojumu",
            find: "Atrast adresi vai vietu",
            attachment: "Pielikums",
            toggleDropdown: "Pārslēgt nolaižamo izvēlni",
            invalidString: "ķ_Please enter valid value_ū.",
            invalidSmallNumber: "ķ_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ū.",
            invalidNumber: "ķ_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ū.",
            invalidFloat: "ķ_Please enter valid ${openStrong}floating point${closeStrong} value_ū.",
            invalidDouble: "ķ_Please enter valid ${openStrong}double${closeStrong} value_ū.",
            invalidLatLong: "ķ_Please enter valid latitude and longitude coordinates_ū.",
            invalidUTM: "ķ_Please enter valid UTM coordinates_ū.",
            invalidUSNG: "ķ_Please enter valid USNG coordinates_ū.",
            invalidMGRS: "ķ_Please enter valid MGRS coordinates_ū.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Atlasīt&hellip;",
            applyEditsFailedMessage: "Atvainojiet, jūsu informāciju nevar iesniegt. Lūdzu, mēģiniet vēlreiz.",
            requiredFields: "Radās kļūdas. Lūdzu, izlabojiet tās tālāk.",
            requiredField: "(obligāti)",
            error: "Kļūda",
            textRangeHintMessage: "${openStrong}Padoms:${closeStrong} minimālā vērtība ${minValue} un maksimālā vērtība ${maxValue}",
            dateRangeHintMessage: "${openStrong}Padoms:${closeStrong} minimālais datums ${minValue} un maksimālais datums ${maxValue}",
            remainingCharactersHintMessage: "ķ_${value} characters remaining_ū"
        },
        builder: {
            invalidUser: "Diemžēl jums nav atļaujas skatīt šo vienību",
            invalidWebmapSelectionAlert: "Atlasītajā web kartē nav iekļauts neviens derīgs slānis, kuru izmantot. Lai turpinātu, savai web kartei pievienojiet rediģējamu elementu slāni.",
            invalidWebmapSelectionAlert2: "Papildinformāciju skatiet sadaļā ${openLink}Kas ir elementu pakalpojums?${closeLink}",
            selectFieldsText: "Atlasīt veidlapas laukus",
            selectThemeText: "Atlasīt formas dizainu",
            webmapText: "Web karte",
            layerText: "Slānis",
            detailsText: "Detaļas",
            fieldsText: "Lauki",
            styleText: "Stils",
            optionText: "Opcijas",
            previewText: "Priekšskatījums",
            publishText: "Publicēt",
            optionsApplicationText: "Opcijas",
            titleText: "Veidotājs",
            descriptionText: "ķ_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ū.",
            btnPreviousText: "Iepriekšējais",
            btnNextText: "Tālāk",
            webmapTabTitleText: "Web kartes izvēle",
            viewWebmap: "Skatīt web karti",
            webmapDetailsText: "ķ_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ū",
            btnSelectWebmapText: "Izvēlieties web karti",
            btnSelectWebmapTextLoading: "Notiek ielāde&hellip;",
            layerTabTitleText: "Atlasiet rediģējamu slāni",
            selectLayerLabelText: "Slānis",
            selectLayerDefaultOptionText: "Atlasīt slāni",
            detailsTabTitleText: "Formas detaļas",
            detailTitleLabelText: "Nosaukums",
            detailLogoLabelText: "Logotipa attēls",
            descriptionLabelText: "ķ_Form Instructions & Details_ū",
            fieldDescriptionLabelText: "ķ_Help Text (optional)_ū",
            fieldTabFieldHeaderText: "Lauks",
            fieldTabLabelHeaderText: "Kartes teksts",
            fieldTabDisplayTypeHeaderText: "Parādīt kā",
            fieldTabOrderColumnText: "ķ_Order_ū",
            fieldTabVisibleColumnText: "ķ_Enabled_ū",
            selectMenuOption: "Izvēlēties izvēlni",
            selectRadioOption: "Radio poga",
            selectTextOption: "Teksts",
            selectDateOption: "ķ_Date Picker_ū",
            selectRangeOption: "ķ_Touch-Spinner_ū",
            selectCheckboxOption: "Izvēles rūtiņa",
            selectMailOption: "Epasts",
            selectUrlOption: "URL",
            selectTextAreaOption: "ķ_Text Area_ū",
            previewApplicationText: "Priekšskatīt aplikāciju",
            saveApplicationText: "Saglabāt aplikāciju",
            saveText: "Saglabāt",
            toggleNavigationText: "Pārslēgt navigāciju",
            formPlaceholderText: "Mana veidlapa",
            shareBuilderInProgressTitleMessage: "GeoForm publicēšana",
            shareBuilderProgressBarMessage: "Lūdzu, uzgaidiet&hellip;",
            shareBuilderTitleMessage: "Izdevās! Vienība ir saglabāta",
            shareBuilderTextMessage: "Varat sākt apkopot infomāciju, kopīgojot ar citiem.",
            shareModalFormText: "Veidlapas saite",
            shareBuilderSuccess: "Jūsu GeoForm ir atjaunināta un publicēta.",
            geoformTitleText: "Geo Form",
            layerTabText: "Šis ir slānis, no kura tiks veidota GeoForm. Slānim ir jābūt elementu servisam ar iespējotu rediģēšanu un kopīgošanas atļaujām, kas ir piemērotas jūsu auditorijai.",
            detailsTabText: "Izmantojiet tālāk esošos veidlapas informācijas lodziņus, lai pielāgotu virsrakstu un pievienotu pielāgotu logotipu, kā arī sniedziet īsu aprakstu, kas paredzēts GeoForm auditorijai. Aprakstā varat pievienot saites uz citiem resursiem, kontaktinformāciju un norādīt auditorijai uz web kartēšanas lietotni, kurā attēloti visi dati, kas apkopoti, izmantojot GeoForm.",
            fieldsTabText: "Šeit varat atlasīt, kuri lauki būs redzami jūsu GeoForm auditorijai, rediģēt apzīmējumus, kurus viņi redzēs, un pievienot īsu aprakstu, lai atvieglotu datu ievadi.",
            styleTabText: "Veidojiet savas GeoForm stilu, atbilstoši savām vēlmēm izmantojot tālāk esošos motīvus.",
            publishTabText: "Ja esat pabeidzis GeoForm pielāgošanu, saglabājiet aplikāciju un sāciet kopīgot ar savu auditoriju. Jebkurā laikā varat atgriezties šajā veidotājā un turpināt pielāgošanu atbilstoši atsauksmēm.",
            headerSizeLabel:"ķ_Header Size_ū",
            smallHeader: "Izmantojiet mazo galveni",
            bigHeader: "ķ_Use Large Header_ū",
            pushpinText: "Spraudīte",
            doneButtonText: "ķ_Save and Exit_ū",
            fieldTabPlaceHolderHeaderText: "Padoms (pēc izvēles)",
            enableAttachmentLabelText: "ķ_${openStrong}Enable Attachments${closeStrong}_ū",
            enableAttachmentLabelHint: "ķ_You can enable/disable the attachments here_ū",
            attachmentIsRequiredLabelText: "ķ_${openStrong}Attachment Required${closeStrong}_ū",
            attachmentIsRequiredLabelHint: "ķ_If necessary, users can be required to enter an attachment_ū.",
            attachmentLabelText: "ķ_Attachment Button Label_ū",
            attachmentLabelHint: "ķ_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ū",
            attachmentDescription: "Pielikuma apraksts",
            attachmentHint: "Ja nepieciešams, šeit varat norādīt papildu norādījumus par pielikumu.",
            jumbotronDescription: "ķ_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ū",
            shareGeoformText: "Kopīgot ģeoveidlapu",
            shareDescription: "Koplietošanas panelis atvieglo auditorijai iespēju koplietot GeoForm ar citiem sadarbības partneriem pēc iesniegšanas pabeigšanas — šo darbību jebkurā laikā var atspējot.",
            defaultMapExtent: "Noklusējuma kartes paplašinājums",
            defaultMapExtentDescription: "Pēc iesniegšanas karte tiks atiestatīta uz noklusējuma paplašinājumu jūsu web kartē — šo darbību jebkurā laikā var atspējot.",
            pushpinOptionsDescription: "Kartes spraudītei izvēlieties kādu no plašā krāsu klāsta; spraudītei vajadzētu atšķirties no kartes simboliem lietotajām krāsām, lai lietotājiem būtu vieglāk piedalīties kartes veidošanā.",
            selectLocationText: "Izvēlēties izvietojumu pēc",
            myLocationText: "Mans izvietojums",
            searchText: "Meklēt",
            coordinatesText: "Ģeogrāfiskā platuma un garuma koordinātas",
            usng: "USNG koordinātas",
            mgrs: "MGRS koordinātas",
            utm: "UTM koordinātas",
            selectLocationSDescription: "Atļaujiet lietotājiem izvēlēties izvietojumu, izmantojot šīs metodes.",
            dragTooltipText:"ķ_Drag the field where you want it to appear_ū",
            showHideLayerText:"ķ_Show/Hide Layer_ū",
            showHideLayerHelpText:"ķ_You can configure the GeoForm to Show/Hide Layer_ū"
        }
    })
);