define({
    root: ({
        map: {
            error: "Kreiranje mape nije moguće",
            views: "prikazi."
        },
        report: {
            flag: "Označi zastavicom kao neprikladno",
            error: "Greška",
            success: "Označeno zastavicom",
            loading: "Učitavanja&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Opis nije dostupan",
            bookmarks: "Obeleživači",
            zoomTo: "Zumirajte na ovu lokaciju da pronađete više informacija.",
            untitledNote: "Bez naslova"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Slojevi medija",
            mediaLayersDescription: "Prikažite doprinose javnosti na mapi.",
            flickrSettings: "Flickr postavke",
            twitter: "Twitter",
            twitterSettings: "Twitter postavke",
            twitterUser: "Twitter nalog",
            twitterSignIn: "Prijavi se na Twitter",
            webcams: "Webcams.travel",
            instagram: "Instagram",
            instagramSettings: "Instagram postavke",
            igTime: "Otpremljeno u toku proteklih nekoliko dana",
            youtube: "YouTube",
            youtubeSettings: "YouTube postavke",
            ytSettingsInfo: "Prikažite video zapise generisane od strane korisnika uključujući mrežni i profesionalni sadržaj.",
            ytTime: "Otpremljeno tokom proteklih",
            today: "Dan",
            this_week: "Sedmica",
            this_month: "Mesec",
            all_time: "Sva vremena",
            moreInfo: "Više informacija",
            searchTerms: "Pretraži uslove",
            search: "Pretraži",
            flSettingsInfo: "Povratni rezultati se podudaraju sa naslovom, opisom ili oznakama fotografije.",
            twSettingsInfo: "Pogledajte šta se sada događa.",
            igSettingsInfo: "Instagram je brz, lep i zabavan način da podelite život sa prijateljima i porodicom.",
            advancedOperators: "Savet: koristite <a target=“_blank“ href=“https://support.twitter.com/articles/71577-using-advanced-search“>operatore</a> za kreiranje naprednih pretraga.",
            tweetsFilteredBy: "filtriraj tvitove po:",
            photosFilteredBy: "filtriraj fotografije po:",
            videosFilteredBy: "filtriraj video zapise po:",
            twitterAccountStatus: "Omogućite da Twitter sloj može da vidi vaš status."
        },
        general: {
            map: "Mapa",
            mapInfo: "Informacije o mapi",
            legend: "Legenda",
            featured: "Istaknute lokacije",
            layers: "Slojevi",
            share: "Podeli",
            about: "Više informacija",
            find: "Poštanski broj, grad, itd.",
            moreInfo: "Više informacija",
            dateModified: "Poslednja izmena",
            noSearchResult: "Nema pronađenog rezultata",
            switchAccount: "Promeni nalog",
            signIn: "Prijavite se",
            settings: "Postavke"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});