define({
    root: ({
        map: {
            error: "Kaarti ei saa luua",
            views: "vaatamisi."
        },
        report: {
            flag: "Märgi mittesobilikuks",
            error: "Viga",
            success: "Märgitud",
            loading: "Laadimine&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Kirjeldus pole saadaval",
            bookmarks: "Järjehoidjad",
            zoomTo: "Suumi sellele kohale ning leia rohkem infot.",
            untitledNote: "Pealkirjata"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Meediakihid",
            mediaLayersDescription: "Kuva kaardil avalikkuse kaudu saadud panust.",
            flickrSettings: "Flickri seaded",
            twitter: "Twitter",
            twitterSettings: "Twitteri seaded",
            twitterUser: "Twitteri konto",
            twitterSignIn: "Logi sisse Twitterisse",
            webcams: "Webcams.travel",
            instagram: "Instagram",
            instagramSettings: "Instagrami sätted",
            igTime: "Üles laaditud viimaste päevade jooksul",
            youtube: "YouTube",
            youtubeSettings: "YouTube seaded",
            ytSettingsInfo: "Kuva kasutaja loodud videod, sh professionaalne ja võrgusisu.",
            ytTime: "Üles laaditud viimase",
            today: "Päev",
            this_week: "Nädal",
            this_month: "Kuu",
            all_time: "Kogu aeg",
            moreInfo: "Detailsem info",
            searchTerms: "Otsinguterminid",
            search: "Otsi",
            flSettingsInfo: "Tagastatakse foto pealkirjale, kirjeldustele või siltidele vastavad tulemused.",
            twSettingsInfo: "Näete, mis parasjagu toimub.",
            igSettingsInfo: "Instagram kiire, kaunis ja lõbus viis jagada oma elusündmusi pere ja sõpradega.",
            advancedOperators: "Näpunäide: kasutage täpsemate otsingute loomiseks <a target=\"_blank\" href=\"https://support.twitter.com/articles/71577-using-advanced-search\">tehtemärke</a>.",
            tweetsFilteredBy: "säutsud on filtreeritud:",
            photosFilteredBy: "fotod on filtreeritud:",
            videosFilteredBy: "videomaterjali filtreerimine:",
            twitterAccountStatus: "Luba Twitteri kihti, et näha enda staatust."
        },
        general: {
            map: "Kaart",
            mapInfo: "Kaardi info",
            legend: "Legend",
            featured: "Esiletõstetud asukohad",
            layers: "Kihid",
            share: "Jaga",
            about: "Info",
            find: "Postikood, linn jne.",
            moreInfo: "Detailsem info",
            dateModified: "Viimati muudetud",
            noSearchResult: "Tulemust ei leitud",
            switchAccount: "Vaheta kontot",
            signIn: "Logi sisse",
            settings: "Seaded"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});