define({
  root: ({
    layer: "כן_Layer___ש",
    sort: "כן_Sort by___ש",
    order: "כן_Order___ש",
    desc: "כן_Desc__ש",
    asc: "כן_Asc__ש",
    loading: "כן_loading&hellip;______ש",
    search: "כן_Search___ש",
    searchPlaceholder: "כן_Find reports_____ש",
    noResults: "כן_No results____ש",
    ascending: "כן_Ascending____ש",
    descending: "כן_Descending____ש"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});