define(
   ({
    map: {
      error: "כן_Unable to create map_ש"
    },
    onlineStatus: {
      offline: "כן_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_ש.",
      reconnecting: "כן_Reconnecting&hellip;_ש",
      pending: "כן_${total} pending edit(s) will be submitted when a network connection is re-established_ש."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "כן_My Organization_ש",
          onlineLabel: "כן_ArcGIS Online_ש",
          contentLabel: "כן_My Content_ש",
          favoritesLabel: "כן_My Favorites_ש"
        },
        title: "כן_Select Web Map_ש",
        searchTitle: "כן_Search_ש",
        ok: "כן_Ok_ש",
        cancel: "כן_Cancel_ש",
        placeholder: "כן_Enter search term_ש"
      },
      groupdlg: {
        items: {
          organizationLabel: "כן_My Organization_ש",
          onlineLabel: "כן_ArcGIS Online_ש",
          contentLabel: "כן_My Content_ש",
          favoritesLabel: "כן_My Favorites_ש"
        },
        title: "כן_Select Group_ש",
        searchTitle: "כן_Search_ש",
        ok: "כן_Ok_ש",
        cancel: "כן_Cancel_ש",
        placeholder: "כן_Enter search term_ש"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "כן_Here is a link to a GeoForm_ש"
      }
    },
    user: {
      mgrs: "כן_MGRS_ש",
      usng: "כן_USNG_ש",
      utm: "כן_UTM_ש",
      utm_northing: "כן_Northing_ש",
      utm_easting: "כן_Easting_ש",
      utm_zone_number: "כן_Zone Number_ש",
      selectLayerTabText: "כן_${formSection} Select Form_ש",
      geoFormGeneralTabText: "כן_${formSection} Enter Information_ש",
      locationInformationText: "כן_${formSection} Select Location_ש",
      submitInformationText: "כן_${formSection} Complete Form_ש",
      submitInstructions: "כן_Add this information to the map_ש.",
      myLocationText: "כן_Current Location_ש",
      locationDescriptionForMoreThanOneOption: "כן_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ש.",
      locationDescriptionForOneOption: "כן_Specify the location for this entry by clicking/tapping the map or by using the following option_ש.",
      locationDescriptionForNoOption: "כן_Specify the location for this entry by clicking/tapping the map_ש.",
      addressText: "כן_Search_ש",
      geographic: "כן_Lat/Lon_ש",
      locationTabText: "כן_Location_ש",
      locationPopupTitle: "כן_Location_ש",
      submitButtonText: "כן_Submit Entry_ש",
      submitButtonTextLoading: "כן_Submitting&hellip;_ש",
      formValidationMessageAlertText: "כן_The following fields are required_ש:",
      selectLocation: "כן_Please select a location for your submission_ש.",
      emptylatitudeAlertMessage: "כן_Please enter a ${openLink}latitude${closeLink} coordinate_ש.",
      emptylongitudeAlertMessage: "כן_Please enter a ${openLink}longitude${closeLink} coordinate_ש.",
      shareUserTitleMessage: "כן_Thank you for your contribution_ש!",
      entrySubmitted: "כן_Your entry has been submitted to the map_ש.",
      shareThisForm: "כן_Share This Form_ש",
      shareUserTextMessage: "כן_Tell others to contribute using the following options_ש.",
      addAttachmentFailedMessage: "כן_Unable to add attachment to layer_ש",
      addFeatureFailedMessage: "כן_Unable to add feature to layer_ש",
      noLayerConfiguredMessage: "כן_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ש.",
      placeholderLatitude: "כן_Latitude (Y)_ש",
      placeholderLongitude: "כן_Longitude (X)_ש",
      latitude: "כן_Latitude_ש",
      longitude: "כן_Longitude_ש",
      findMyLocation: "כן_Locate Me_ש",
      finding: "כן_Locating&hellip;_ש",
      backToTop: "כן_Back to top_ש",
      addressSearchText: "כן_Your submission will appear here. You can drag the pin to correct the location_ש.",
      shareModalFormText: "כן_Form Link_ש",
      close: "כן_Close_ש",
      locationNotFound: "כן_Location could not be found_ש.",
      setLocation: "כן_Set Location_ש",
      find: "כן_Find address or place_ש",
      attachment: "כן_Attachment_ש",
      toggleDropdown: "כן_Toggle Dropdown_ש",
      invalidString: "כן_Please enter valid value_ש.",
      invalidSmallNumber: "כן_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ש.",
      invalidNumber: "כן_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ש.",
      invalidFloat: "כן_Please enter valid ${openStrong}floating point${closeStrong} value_ש.",
      invalidDouble: "כן_Please enter valid ${openStrong}double${closeStrong} value_ש.",
      invalidLatLong: "כן_Please enter valid latitude and longitude coordinates_ש.",
      invalidUTM: "כן_Please enter valid UTM coordinates_ש.",
      invalidUSNG: "כן_Please enter valid USNG coordinates_ש.",
      invalidMGRS: "כן_Please enter valid MGRS coordinates_ש.",
      geoformTitleText: "כן_GeoForm_ש",
      domainDefaultText: "כן_Select&hellip;_ש",
      applyEditsFailedMessage: "כן_Sorry your entry cannot be submitted. Please try again_ש.",
      requiredFields: "כן_There are some errors. Please correct them below_ש.",
      requiredField: "כן_(required)_ש",
      error: "כן_Error_ש",
      textRangeHintMessage: "כן_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ש",
      dateRangeHintMessage: "כן_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ש",
      remainingCharactersHintMessage: "כן_${value} characters remaining_ש",
      mapFullScreen: "כן_Full Screen_ש",
      mapRestore: "כן_Restore_ש",
      filterSelectEmptyText: "כן_Select_ש",
      invalidLayerMessage: "כן_Form layer does not exist. Please configure the application and set the layer_ש.",
      selectedLayerText: "כן_All_ש"
    },
    builder: {
      invalidUser: "כן_Sorry, you dont have permission to view this item_ש",
      invalidWebmapSelectionAlert: "כן_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_ש.",
      invalidWebmapSelectionAlert2: "כן_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ש",
      selectFieldsText: "כן_Select Form Fields_ש",
      selectThemeText: "כן_Select Form Theme_ש",
      webmapText: "כן_Webmap_ש",
      layerText: "כן_Layer_ש",
      detailsText: "כן_Details_ש",
      fieldsText: "כן_Fields_ש",
      styleText: "כן_Style_ש",
      optionText: "כן_Options_ש",
      previewText: "כן_Preview_ש",
      publishText: "כן_Publish_ש",
      optionsApplicationText: "כן_Options_ש",
      titleText: "כן_Builder_ש",
      descriptionText: "כן_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ש.",
      btnPreviousText: "כן_Previous_ש",
      btnNextText: "כן_Next_ש",
      webmapTabTitleText: "כן_Select a Webmap_ש",
      viewWebmap: "כן_View webmap_ש",
      webmapDetailsText: "כן_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ש",
      btnSelectWebmapText: "כן_Choose Webmap_ש",
      btnSelectWebmapTextLoading: "כן_Loading&hellip;_ש",
      layerTabTitleText: "כן_Select Editable Layer_ש",
      selectLayerLabelText: "כן_Layer_ש",
      selectLayerDefaultOptionText: "כן_Select Layer_ש",
      defaultBasemap: "כן_Basemap Toggle_ש",
      secondaryBasemap: "כן_Default Basemap_ש",
      detailsTabTitleText: "כן_Form Details_ש",
      detailTitleLabelText: "כן_Title_ש",
      detailLogoLabelText: "כן_Logo Image_ש",
      descriptionLabelText: "כן_Form Instructions & Details_ש",
      fieldDescriptionLabelText: "כן_Help Text (optional)_ש",
      fieldTabFieldHeaderText: "כן_Field_ש",
      fieldTabLabelHeaderText: "כן_Label_ש",
      fieldTabDisplayTypeHeaderText: "כן_Display As_ש",
      fieldTabOrderColumnText: "כן_Order_ש",
      fieldTabVisibleColumnText: "כן_Enabled_ש",
      selectMenuOption: "כן_Select Menu_ש",
      selectRadioOption: "כן_Radio Button_ש",
      selectTextOption: "כן_Text_ש",
      selectDateOption: "כן_Date Picker_ש",
      selectRangeOption: "כן_Touch-Spinner_ש",
      selectCheckboxOption: "כן_Checkbox_ש",
      selectMailOption: "כן_Email_ש",
      selectUrlOption: "כן_URL_ש",
      selectTextAreaOption: "כן_Text Area_ש",
      previewApplicationText: "כן_Preview Application_ש",
      saveApplicationText: "כן_Save Application_ש",
      saveText: "כן_Save_ש",
      toggleNavigationText: "כן_Toggle navigation_ש",
      formPlaceholderText: "כן_My Form_ש",
      shareBuilderInProgressTitleMessage: "כן_Publishing GeoForm_ש",
      shareBuilderProgressBarMessage: "כן_Please Wait&hellip;_ש",
      shareBuilderTitleMessage: "כן_Success! Item saved_ש",
      shareBuilderTextMessage: "כן_You can start collecting information by sharing with others_ש",
      shareModalFormText: "כן_Form Link_ש",
      shareBuilderSuccess: "כן_Your GeoForm has been updated & published_ש!",
      geoformTitleText: "כן_Geo Form_ש",
      layerTabText: "כן_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_ש.",
      detailsTabText: "כן_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_ש.",
      fieldsTabText: "כן_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_ש.",
      styleTabText: "כן_Style your GeoForm using the themes below based on your preference_ש.",
      publishTabText: "כן_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_ש.",
      headerSizeLabel: "כן_Header Size_ש",
      smallHeader: "כן_Use Small Header_ש",
      bigHeader: "כן_Use Large Header_ש",
      pushpinText: "כן_Push pin_ש",
      doneButtonText: "כן_Save and Exit_ש",
      fieldTabPlaceHolderHeaderText: "כן_Hint (optional)_ש",
      enableAttachmentLabelText: "כן_${openStrong}Enable Attachments${closeStrong}_ש",
      enableAttachmentLabelHint: "כן_You can enable/disable the attachments here_ש",
      attachmentIsRequiredLabelText: "כן_${openStrong}Attachment Required${closeStrong}_ש",
      attachmentIsRequiredLabelHint: "כן_If necessary, users can be required to enter an attachment_ש.",
      attachmentLabelText: "כן_Attachment Button Label_ש",
      attachmentLabelHint: "כן_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ש",
      attachmentDescription: "כן_Attachment Description_ש",
      attachmentHint: "כן_If necessary, you can provide additional attachment instructions here_ש.",
      jumbotronDescription: "כן_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ש",
      shareGeoformText: "כן_Share Geoform_ש",
      shareDescription: "כן_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_ש.",
      defaultMapExtent: "כן_Default Map Extent_ש",
      defaultMapExtentDescription: "כן_The map will reset to the default extent in your web map after submission - this can be disabled at any time_ש.",
      pushpinOptionsDescription: "כן_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ש",
      selectLocationText: "כן_Select Location By_ש",
      myLocationText: "כן_My Location_ש",
      searchText: "כן_Search_ש",
      coordinatesText: "כן_Latitude & Longitude Coordinates_ש",
      usng: "כן_USNG Coordinates_ש",
      mgrs: "כן_MGRS Coordinates_ש",
      utm: "כן_UTM Coordinates_ש",
      selectLocationSDescription: "כן_Allow users to select a location using these methods_ש.",
      dragTooltipText: "כן_Drag the field where you want it to appear_ש",
      showHideLayerText: "כן_Show Layer_ש",
      showHideLayerHelpText: "כן_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_ש.",
      labelHelpMessage: "כן_Label_ש",
      placeHolderHintMessage: "כן_Hint Text_ש",
      placeHolderHelpMessage: "כן_Help Text_ש",
      selectTextOptionValue: "כן_Filter Select_ש",
      disableLogo: "כן_Disable Logo_ש",
      disableLogoDescription: "כן_You can configure the GeoForm to Show/Hide the Logo in the form header_ש",
      locateOnLoadText: "כן_Locate On Load_ש",
      locateOnLoadDescription: "כן_You can configure the GeoForm to use the current location on page load_ש",
      selectLayerFieldTabText: "כן_Select Layer_ש",
      allLayerSelectOptionText:"כן_All_ש"
    }
  })
);