define(
     ({
        map: {
            error: "לא ניתן ליצור מפה"
        },
        onlineStatus: {
            offline: "אתה עובד כרגע במצב לא מקוון. הטופס ישמר באופן מקומי עד שחיבור לשרת יכול להתבצע.",
            reconnecting: "מתקשר מחש&hellip;",
            pending: "${total} עריכות ממתינות ישלחו כאשר חיבור לרשת ייווצר מחדש."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "הארגון שלי",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "התוכן שלי",
                    favoritesLabel: "המועדפים שלי"
                },
                title: "בחר Web Map",
                searchTitle: "חפש",
                ok: "אישור",
                cancel: "ביטול",
                placeholder: "הכנס מונח לחיפוש"
            },
            groupdlg: {
                items: {
                    organizationLabel: "הארגון שלי",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "התוכן שלי",
                    favoritesLabel: "המועדפים שלי"
                },
                title: "בחר קבוצה",
                searchTitle: "חפש",
                ok: "אישור",
                cancel: "ביטול",
                placeholder: "הכנס מונח לחיפוש"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "כן_Here is a link to a GeoForm_ש"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "כלפי צפון",
            utm_easting: "כלפי מזרח",
            utm_zone_number: "מספר אזור",
            geoFormGeneralTabText: "1. הכנס מידע",
            locationInformationText: "2. בחר מיקום",
            submitInformationText: "3. השלם טופס",
            submitInstructions: "הוסף מידע זה למפה.",
            myLocationText: "מיקום נוכחי",
            locationDescriptionForMoreThanOneOption: "כן_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ש.",
            locationDescriptionForOneOption: "כן_Specify the location for this entry by clicking/tapping the map or by using the following option_ש.",
            locationDescriptionForNoOption: "כן_Specify the location for this entry by clicking/tapping the map_ש.",
            addressText: "חיפוש",
            geographic: "רוחב/אורך",
            locationTabText: "מיקום",
            locationPopupTitle: "מיקום",
            submitButtonText: "שלח ערך",
            submitButtonTextLoading: "מגיש",
            formValidationMessageAlertText: "השדות הבאים דרושים:",
            selectLocation: "כן_Please select a location for your submission_ש.",
            emptylatitudeAlertMessage: "הזן קואורדינטת ${openLink}קו רוחב${closeLink}.",
            emptylongitudeAlertMessage: "הזן קואורדינטת ${openLink}קו אורך${closeLink}.",
            shareUserTitleMessage: "תודה רבה עבור התרומה שלך!",
            entrySubmitted: "הערך שלך נשלח למפה.",
            shareThisForm: "שתף טופס זה",
            shareUserTextMessage: "בקש מאחרים להשתתף באמצעות האפשרויות הבאות.",
            addAttachmentFailedMessage: "לא ניתן להוסיף קישור לשכבה",
            addFeatureFailedMessage: "לא ניתן להוסיף ישות לשכבה",
            noLayerConfiguredMessage: "כן_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ש.",
            placeholderLatitude: "קו רוחב (Y)",
            placeholderLongitude: "קו אורך (X)",
            latitude: "קו רוחב",
            longitude: "קו אורך",
            findMyLocation: "מצא את המיקום שלי",
            finding: "מאתר",
            backToTop: "חזור לראש הדף",
            addressSearchText: "המידע שלך יווצג פה. אתה יכול לגרור את סמן הסיכה כדי לתקן את המיקום.",
            shareModalFormText: "קישור טופס",
            close: "סגור",
            locationNotFound: "לא ניתן למצוא מיקום.",
            setLocation: "הגדר מיקום",
            find: "מצא כתובת או מקום",
            attachment: "קישור",
            toggleDropdown: "שנה מצב רשימה נפתחת",
            invalidString: "כן_Please enter valid value_ש.",
            invalidSmallNumber: "כן_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ש.",
            invalidNumber: "כן_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ש.",
            invalidFloat: "כן_Please enter valid ${openStrong}floating point${closeStrong} value_ש.",
            invalidDouble: "כן_Please enter valid ${openStrong}double${closeStrong} value_ש.",
            invalidLatLong: "כן_Please enter valid latitude and longitude coordinates_ש.",
            invalidUTM: "כן_Please enter valid UTM coordinates_ש.",
            invalidUSNG: "כן_Please enter valid USNG coordinates_ש.",
            invalidMGRS: "כן_Please enter valid MGRS coordinates_ש.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "בחר",
            applyEditsFailedMessage: "מצטערים, לא ניתן להגיש את הערך שלך. נסה שוב.",
            requiredFields: "קיימות שגיאות. תקן אותן להלן.",
            requiredField: "(חובה)",
            error: "שגיאה",
            textRangeHintMessage: "${openStrong}רמז:${closeStrong} ערך מינימום ${minValue} וערך מקסימום ${maxValue}",
            dateRangeHintMessage: "${openStrong}רמז:${closeStrong} תאריך מינימום ${minValue} ותאריך מקסימום ${maxValue}",
            remainingCharactersHintMessage: "כן_${value} characters remaining_ש"
        },
        builder: {
            invalidUser: "מצטערים, אין לך הרשאה להצגת פריט זה",
            invalidWebmapSelectionAlert: "ה-webmap שנבחרה לא מכילה שכבה חוקית שניתן להשתמש בה. הוסף ל-webmap שכבת ישויות שניתן לערוך כדי שתוכל להמשיך.",
            invalidWebmapSelectionAlert2: "לקבלת מידע נוסף, ראה ${openLink}מהו שירות ישויות?${closeLink}",
            selectFieldsText: "בחר מהשדות",
            selectThemeText: "בחר ערכת נושא של טופס",
            webmapText: "Webmap",
            layerText: "שכבה",
            detailsText: "פרטים",
            fieldsText: "שדות",
            styleText: "סגנון",
            optionText: "אפשרויות",
            previewText: "תצוגה מקדימה",
            publishText: "פרסם",
            optionsApplicationText: "אפשרויות",
            titleText: "אשף בנייה",
            descriptionText: "כן_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ש.",
            btnPreviousText: "הקודם",
            btnNextText: "הבא",
            webmapTabTitleText: "בחר Webmap",
            viewWebmap: "הצג webmap",
            webmapDetailsText: "כן_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ש",
            btnSelectWebmapText: "בחר Webmap",
            btnSelectWebmapTextLoading: "טוען&hellip;",
            layerTabTitleText: "בחר שכבה לעריכה",
            selectLayerLabelText: "שכבה",
            selectLayerDefaultOptionText: "בחר שכבה",
            detailsTabTitleText: "פרטי הטופס",
            detailTitleLabelText: "כותרת",
            detailLogoLabelText: "תמונת לוגו",
            descriptionLabelText: "כן_Form Instructions & Details_ש",
            fieldDescriptionLabelText: "כן_Help Text (optional)_ש",
            fieldTabFieldHeaderText: "שדה",
            fieldTabLabelHeaderText: "תווית",
            fieldTabDisplayTypeHeaderText: "הצג כ:",
            fieldTabOrderColumnText: "כן_Order_ש",
            fieldTabVisibleColumnText: "כן_Enabled_ש",
            selectMenuOption: "בחר תפריט",
            selectRadioOption: "לחצן בחירה",
            selectTextOption: "טקסט",
            selectDateOption: "כן_Date Picker_ש",
            selectRangeOption: "כן_Touch-Spinner_ש",
            selectCheckboxOption: "תיבת סימון",
            selectMailOption: "דואר אלקטרוני",
            selectUrlOption: "כתובת URL",
            selectTextAreaOption: "כן_Text Area_ש",
            previewApplicationText: "תצוגה מקדימה של אפליקציה",
            saveApplicationText: "שמור אפליקציה",
            saveText: "שמור",
            toggleNavigationText: "החלף ניווט",
            formPlaceholderText: "הטופס שלי",
            shareBuilderInProgressTitleMessage: "פרסום GeoForm",
            shareBuilderProgressBarMessage: "המתן בבקשה&hellip;",
            shareBuilderTitleMessage: "הצלחה! הפריט נשמר",
            shareBuilderTextMessage: "אתה יכול להתחיל לאסוף מידע על-ידי שיתוף עם אחרים",
            shareModalFormText: "קישור לטופס",
            shareBuilderSuccess: "ה-GeoForm שלך עודכן ופורסם!",
            geoformTitleText: "Geo Form",
            layerTabText: "ה-GeoForm ייבנה מתוך שכבה זו. השכבה חייבת להיות שירות ישויות ניתן לעריכה עם הרשאות שיתוף המתאימות לקהל היעד.",
            detailsTabText: "השתמש בתיבות פרטי טופס למטה כדי להתאים את הכותרת, להוסיף לוגו מותאם ולספק תיאור קצר לקהל של ה-GeoForm שלך. בתיאור ניתן להוסיף קישורים למשאבים אחרים, פרטי קשר ואפילו להפנות את הקהל שלך אל אפליקציית web mapping הכוללת את כל הנתונים שנאספו עם ה-GeoForm.",
            fieldsTabText: "כאן אתה יכול לבחור אילו שדות יוצגו לקהל ה-GeoForm שלך, לערוך את התוויות שהם יראו ולהוסיף תיאור קצר שיעזור בהזנת נתונים.",
            styleTabText: "סגנן את ה-GeoForm שלך בעזרת ערכות הנושא למטה בהתאם להעדפות שלך.",
            publishTabText: "אם סיימת להתאים את ה-GeoForm, שמור את האפליקציה והתחל שיתוף עם הקהל שלך. תוכל תמיד לחזור לאשף בנייה זה ולהמשיך להתאים אותו לפי המשוב שתקבל.",
            headerSizeLabel:"כן_Header Size_ש",
            smallHeader: "השתמש בכותרת עליונה קטנה",
            bigHeader: "כן_Use Large Header_ש",
            pushpinText: "נעץ",
            doneButtonText: "כן_Save and Exit_ש",
            fieldTabPlaceHolderHeaderText: "רמז (אופציונלי)",
            enableAttachmentLabelText: "כן_${openStrong}Enable Attachments${closeStrong}_ש",
            enableAttachmentLabelHint: "כן_You can enable/disable the attachments here_ש",
            attachmentIsRequiredLabelText: "כן_${openStrong}Attachment Required${closeStrong}_ש",
            attachmentIsRequiredLabelHint: "כן_If necessary, users can be required to enter an attachment_ש.",
            attachmentLabelText: "כן_Attachment Button Label_ש",
            attachmentLabelHint: "כן_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ש",
            attachmentDescription: "תיאור קובץ מצורף",
            attachmentHint: "במקרה הצורך, תוכל לספק כאן הוראות נוספות לגבי קבצים מצורפים.",
            jumbotronDescription: "כן_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ש",
            shareGeoformText: "שתף את Geoform",
            shareDescription: "לוח השיתוף מאפשר לקהל שלך לשתף בקלות את GeoForm עם משתפי פעולה אחרים לאחר שהם הגישו אותו - ניתן להשבית אפשרות זו בכל עת.",
            defaultMapExtent: "תיחום מפה המהווה ברירת מחדל",
            defaultMapExtentDescription: "המפה תתאפס לתיחום ברירת המחדל ב-web map שלך לאחר השליחה - ניתן לבטל אפשרות זו בכל עת.",
            pushpinOptionsDescription: "בחר לנעץ במפה צבע ממגוון צבעים, עליו להיות שונה מהסימבולוגיה של המפה כדי לסייע למשתמש להראות את המידע שלו על-גבי המפה",
            selectLocationText: "בחר מיקום לפי",
            myLocationText: "המיקום שלי",
            searchText: "חיפוש",
            coordinatesText: "קואורדינטות קו רוחב וקו אורך",
            usng: "קואורדינטות USNG",
            mgrs: "קואורדינטות MGRS",
            utm: "קואורדינטות UTM",
            selectLocationSDescription: "אפשר למשתמשים לבחור מיקום באמצעות שיטות אלה.",
            dragTooltipText:"כן_Drag the field where you want it to appear_ש",
            showHideLayerText:"כן_Show/Hide Layer_ש",
            showHideLayerHelpText:"כן_You can configure the GeoForm to Show/Hide Layer_ש"
        }
    })
);