define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Valitud veebikaardil pole ühtegi kasutamiseks sobivat kihti. Jätkamiseks lisage veebikaardile muudetav objektikiht.",
            selectFieldsText:"Vali vormi väljad",
            selectThemeText: "Vali teemade hulgast",
            fieldLabelPlaceHolder: "Lisa sellele väljale silt",
            fieldDescPlaceHolder: "Kirjelda seda välja",
            webmapText: "1. Veebikaart",
            layerText: "2. Kiht",
            detailsText: "3. Detailid",
            fieldsText: "4. Väljad",
            styleText: "5. Laad",
            previewText: "6. Eelvaade",
            publishText: "7. Publitseeri",
            titleText: "GeoFormi koostur",
            descriptionText: "GeoForm on konfigureeritav mall, mille abil saab vormipõhiselt muuta <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>objektiteenuse</a> andmeid. Selle rakenduse abil saab andmeid sisestada mitte kaardi hüpikakna, vaid vormi kaudu ning kasutada <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>veebikaardi</a> ja muudetavate objektiteenuste võimalusi. Kasutage seda koostajat oma GeoFormi kohandamiseks ja rakendamiseks, järgides vasakul olevaid juhiseid.",
            btnPreviousText: "Eelmine",
            btnNextText:"Järgmine",
            webmapTabTitleText: "Veebikaardi valimine",
            btnSelectWebmapText:"Vali veebikaart",
            layerTabTitleText: "Vali muudetav kiht",
            selectLayerLabelText:"Kiht",
            selectLayerDefaultOptionText:"Vali kiht",
            detailsTabTitleText:"Vormi üksikasjad",
            detailTitleLabelText: "Pealkiri",
            detailLogoLabelText: "Logo pilt",
            detailDescriptionLabelText: "Kirjeldus",
            fieldTabFieldHeaderText: "Väli",
            fieldTabLabelHeaderText: "Silt",
            fieldTabTypeHeaderText: "Tüüp",
            fieldTabDescriptionHeaderText: "Kirjeldus",
            previewApplicationText: "Kuva rakenduse eelvaade",
            saveApplicationText: "Salvesta rakendus",
            saveText: "Salvesta",
            toggleNavigationText: "Muuda navigeerimist",
            formPlaceholderText: "Minu vorm",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "GeoFormi publitseerimine",
            shareBuilderProgressBarMessage:"Palun oodake...",
            shareBuilderTitleMessage: "Teie GeoForm on uuendatud ja publitseeritud!",
            shareBuilderTextMessage: "Saate teistega jagamise kaudu hakata teavet koguma",
            shareDialogFormText: "Vormi link",
            geoformTitleText: "Geo Form",
            layerTabText: "GeoForm koostatakse selle kihi põhjal. Kihiks peab olema objektiteenus, mida on lubatud muuta ning mis sisaldab sihtrühmale vastavaid jagamisõigusi.",
            detailsTabText:"Pealkirja kohandamiseks ning oma logo ja GeoFormi sihtrühma jaoks mõeldud lühikese kirjelduse lisamiseks kasutage allolevaid vormi üksikasjade välju.",
            fieldsTabText:"Siin saate valida, millised väljad on teie GeoFormi sihtrühma jaoks nähtavad, muuta sihtrühma jaoks kuvatavaid silte ning lisada lühikese kirjelduse andmete sisestamise hõlbustamiseks.",
            styleTabText: "Saate allolevate teemade abil vastavalt oma eelistusele GeoFormi laadi muuta.",
            publishTabText: "Kui olete GeoFormi kohandamise lõpetanud, salvestage rakendus ja hakake seda oma sihtrühmaga jagama. Saate sellesse koosturisse igal ajal naasta ja tagasiside põhjal rakendust veelgi kohandada."
        }
    })
);