define({
  root: ({
    "pagination": {
      "page": "Š_Page__ä",
      "previousTitle": "Š_Previous___ä",
      "nextTitle": "Š_Next__ä",
      "firstTitle": "Š_First___ä",
      "lastTitle": "Š_Last__ä",
      "helip": "Š_&hellip;___ä"
    }
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});