define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "á_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Ó",
            selectFieldsText:"á_Select Form Fields_Ó",
            selectThemeText: "Seleccionar tema del formulario",
            fieldLabelPlaceHolder: "Etiquetar este campo",
            fieldDescPlaceHolder: "Describir este campo",
            webmapText: "á_1. Webmap_Ó",
            layerText: "á_2. Layer_Ó",
            detailsText: "á_3. Details_Ó",
            fieldsText: "á_4. Fields_Ó",
            styleText: "á_5. Style_Ó",
            previewText: "á_6. Preview_Ó",
            publishText: "á_7. Publish_Ó",
            titleText: "GeoForm Builder",
            descriptionText: "á_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._Ó",
            btnPreviousText: "Anterior",
            btnNextText:"Siguiente",
            webmapTabTitleText: "Elegir un mapa web",
            btnSelectWebmapText:"Seleccionar mapa web",
            layerTabTitleText: "Seleccionar capa editable",
            selectLayerLabelText:"Capa",
            selectLayerDefaultOptionText:"Seleccionar capa",
            detailsTabTitleText:"Detalles del formulario",
            detailTitleLabelText: "Título",
            detailLogoLabelText: "Imagen del logotipo",
            detailDescriptionLabelText: "Descripción",
            fieldTabFieldHeaderText: "Campo",
            fieldTabLabelHeaderText: "Etiqueta",
            fieldTabTypeHeaderText: "Tipo",
            fieldTabDescriptionHeaderText: "Descripción",
            previewApplicationText: "Vista previa de la aplicación",
            saveApplicationText: "Guardar aplicación",
            saveText: "Guardar",
            toggleNavigationText: "á_Toggle navigation_Ó",
            formPlaceholderText: "á_My Form_Ó",
            imageLogoPlaceholderText: "á_http://www.mysite.com/myimage.png_Ó",
            shareBuilderInProgressTitleMessage: "á_Publishing GeoForm_Ó",
            shareBuilderProgressBarMessage:"á_Please Wait..._Ó",
            shareBuilderTitleMessage: "á_Your GeoForm has been updated & published!_Ó",
            shareBuilderTextMessage: "á_You can start collecting information by sharing with others_Ó",
            shareDialogFormText: "á_Form Link_Ó",
            geoformTitleText: "á_Geo Form_Ó",
            layerTabText: "á_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Ó",
            detailsTabText:"á_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._Ó",
            fieldsTabText:"á_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Ó",
            styleTabText: "á_Style your GeoForm using the themes below based on your preference._Ó",
            publishTabText: "á_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Ó"
        }
    })
);