define(
   ({
    map: {
      error: "á_Unable to create map_Ó"
    },
    onlineStatus: {
      offline: "á_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_Ó.",
      reconnecting: "á_Reconnecting&hellip;_Ó",
      pending: "á_${total} pending edit(s) will be submitted when a network connection is re-established_Ó."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "á_My Organization_Ó",
          onlineLabel: "á_ArcGIS Online_Ó",
          contentLabel: "á_My Content_Ó",
          favoritesLabel: "á_My Favorites_Ó"
        },
        title: "á_Select Web Map_Ó",
        searchTitle: "á_Search_Ó",
        ok: "á_Ok_Ó",
        cancel: "á_Cancel_Ó",
        placeholder: "á_Enter search term_Ó"
      },
      groupdlg: {
        items: {
          organizationLabel: "á_My Organization_Ó",
          onlineLabel: "á_ArcGIS Online_Ó",
          contentLabel: "á_My Content_Ó",
          favoritesLabel: "á_My Favorites_Ó"
        },
        title: "á_Select Group_Ó",
        searchTitle: "á_Search_Ó",
        ok: "á_Ok_Ó",
        cancel: "á_Cancel_Ó",
        placeholder: "á_Enter search term_Ó"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "á_Here is a link to a GeoForm_Ó"
      }
    },
    user: {
      mgrs: "á_MGRS_Ó",
      usng: "á_USNG_Ó",
      utm: "á_UTM_Ó",
      utm_northing: "á_Northing_Ó",
      utm_easting: "á_Easting_Ó",
      utm_zone_number: "á_Zone Number_Ó",
      selectLayerTabText: "á_${formSection} Select Form_Ó",
      geoFormGeneralTabText: "á_${formSection} Enter Information_Ó",
      locationInformationText: "á_${formSection} Select Location_Ó",
      submitInformationText: "á_${formSection} Complete Form_Ó",
      submitInstructions: "á_Add this information to the map_Ó.",
      myLocationText: "á_Current Location_Ó",
      locationDescriptionForMoreThanOneOption: "á_Specify the location for this entry by clicking/tapping the map or by using one of the following options_Ó.",
      locationDescriptionForOneOption: "á_Specify the location for this entry by clicking/tapping the map or by using the following option_Ó.",
      locationDescriptionForNoOption: "á_Specify the location for this entry by clicking/tapping the map_Ó.",
      addressText: "á_Search_Ó",
      geographic: "á_Lat/Lon_Ó",
      locationTabText: "á_Location_Ó",
      locationPopupTitle: "á_Location_Ó",
      submitButtonText: "á_Submit Entry_Ó",
      submitButtonTextLoading: "á_Submitting&hellip;_Ó",
      formValidationMessageAlertText: "á_The following fields are required_Ó:",
      selectLocation: "á_Please select a location for your submission_Ó.",
      emptylatitudeAlertMessage: "á_Please enter a ${openLink}latitude${closeLink} coordinate_Ó.",
      emptylongitudeAlertMessage: "á_Please enter a ${openLink}longitude${closeLink} coordinate_Ó.",
      shareUserTitleMessage: "á_Thank you for your contribution_Ó!",
      entrySubmitted: "á_Your entry has been submitted to the map_Ó.",
      shareThisForm: "á_Share This Form_Ó",
      shareUserTextMessage: "á_Tell others to contribute using the following options_Ó.",
      addAttachmentFailedMessage: "á_Unable to add attachment to layer_Ó",
      addFeatureFailedMessage: "á_Unable to add feature to layer_Ó",
      noLayerConfiguredMessage: "á_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_Ó.",
      placeholderLatitude: "á_Latitude (Y)_Ó",
      placeholderLongitude: "á_Longitude (X)_Ó",
      latitude: "á_Latitude_Ó",
      longitude: "á_Longitude_Ó",
      findMyLocation: "á_Locate Me_Ó",
      finding: "á_Locating&hellip;_Ó",
      backToTop: "á_Back to top_Ó",
      addressSearchText: "á_Your submission will appear here. You can drag the pin to correct the location_Ó.",
      shareModalFormText: "á_Form Link_Ó",
      close: "á_Close_Ó",
      locationNotFound: "á_Location could not be found_Ó.",
      setLocation: "á_Set Location_Ó",
      find: "á_Find address or place_Ó",
      attachment: "á_Attachment_Ó",
      toggleDropdown: "á_Toggle Dropdown_Ó",
      invalidString: "á_Please enter valid value_Ó.",
      invalidSmallNumber: "á_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_Ó.",
      invalidNumber: "á_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_Ó.",
      invalidFloat: "á_Please enter valid ${openStrong}floating point${closeStrong} value_Ó.",
      invalidDouble: "á_Please enter valid ${openStrong}double${closeStrong} value_Ó.",
      invalidLatLong: "á_Please enter valid latitude and longitude coordinates_Ó.",
      invalidUTM: "á_Please enter valid UTM coordinates_Ó.",
      invalidUSNG: "á_Please enter valid USNG coordinates_Ó.",
      invalidMGRS: "á_Please enter valid MGRS coordinates_Ó.",
      geoformTitleText: "á_GeoForm_Ó",
      domainDefaultText: "á_Select&hellip;_Ó",
      applyEditsFailedMessage: "á_Sorry your entry cannot be submitted. Please try again_Ó.",
      requiredFields: "á_There are some errors. Please correct them below_Ó.",
      requiredField: "á_(required)_Ó",
      error: "á_Error_Ó",
      textRangeHintMessage: "á_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_Ó",
      dateRangeHintMessage: "á_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_Ó",
      remainingCharactersHintMessage: "á_${value} characters remaining_Ó",
      mapFullScreen: "á_Full Screen_Ó",
      mapRestore: "á_Restore_Ó",
      filterSelectEmptyText: "á_Select_Ó",
      invalidLayerMessage: "á_Form layer does not exist. Please configure the application and set the layer_Ó.",
      selectedLayerText: "á_All_Ó",
      fileUploadStatus: "á_File Upload Status_Ó",
      uploadingBadge: "á_&nbsp;Uploading&hellip;_Ó",
      successBadge: "á_&nbsp;Uploaded_Ó",
      retryBadge: "á_Retry_Ó",
      errorBadge: "á_Error uploading&nbsp;&nbsp;&nbsp;_Ó",
      fileTooLargeError: "á_File too large to attach_Ó",
      exceededFileCountError: "á_Exceeded maximum no. of attachments allowed_Ó",
      selectFileTitle: "á_Select a file_Ó",
      btnViewSubmissions: "á_View Submissions_Ó",
      dateFormat: "á_MM/DD/YYYY h:mm a_Ó"
    },
    builder: {
      invalidUser: "á_Sorry, you don't have permission to view this item_Ó",
      invalidWebmapSelectionAlert: "á_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_Ó.",
      invalidWebmapSelectionAlert2: "á_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_Ó",
      selectFieldsText: "á_Select Form Fields_Ó",
      selectThemeText: "á_Select Form Theme_Ó",
      webmapText: "á_Webmap_Ó",
      layerText: "á_Layer_Ó",
      detailsText: "á_Details_Ó",
      fieldsText: "á_Fields_Ó",
      styleText: "á_Style_Ó",
      optionText: "á_Options_Ó",
      previewText: "á_Preview_Ó",
      publishText: "á_Publish_Ó",
      optionsApplicationText: "á_Options_Ó",
      titleText: "á_Builder_Ó",
      descriptionText: "á_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_Ó.",
      btnPreviousText: "á_Previous_Ó",
      btnNextText: "á_Next_Ó",
      webmapTabTitleText: "á_Select a Webmap_Ó",
      viewWebmap: "á_View webmap_Ó",
      webmapDetailsText: "á_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_Ó",
      btnSelectWebmapText: "á_Choose Webmap_Ó",
      btnSelectWebmapTextLoading: "á_Loading&hellip;_Ó",
      layerTabTitleText: "á_Select Editable Layer_Ó",
      selectLayerLabelText: "á_Layer_Ó",
      selectLayerDefaultOptionText: "á_Select Layer_Ó",
      defaultBasemap: "á_Basemap Toggle_Ó",
      secondaryBasemap: "á_Default Basemap_Ó",
      detailsTabTitleText: "á_Form Details_Ó",
      detailTitleLabelText: "á_Title_Ó",
      detailLogoLabelText: "á_Logo Image_Ó",
      descriptionLabelText: "á_Form Instructions & Details_Ó",
      fieldDescriptionLabelText: "á_Help Text (optional)_Ó",
      fieldTabFieldHeaderText: "á_Field_Ó",
      fieldTabLabelHeaderText: "á_Label_Ó",
      fieldTabDisplayTypeHeaderText: "á_Display As_Ó",
      fieldTabOrderColumnText: "á_Order_Ó",
      fieldTabVisibleColumnText: "á_Enabled_Ó",
      displayFieldText: "á_Display Field_Ó",
      selectMenuOption: "á_Select Menu_Ó",
      selectRadioOption: "á_Radio Button_Ó",
      selectTextOption: "á_Text_Ó",
      selectDateOption: "á_Date Picker_Ó",
      selectRangeOption: "á_Touch-Spinner_Ó",
      selectCheckboxOption: "á_Checkbox_Ó",
      selectMailOption: "á_Email_Ó",
      selectUrlOption: "á_URL_Ó",
      selectTextAreaOption: "á_Text Area_Ó",
      previewApplicationText: "á_Preview Application_Ó",
      saveApplicationText: "á_Save Application_Ó",
      saveText: "á_Save_Ó",
      toggleNavigationText: "á_Toggle navigation_Ó",
      formPlaceholderText: "á_My Form_Ó",
      shareBuilderInProgressTitleMessage: "á_Publishing GeoForm_Ó",
      shareBuilderProgressBarMessage: "á_Please Wait&hellip;_Ó",
      shareBuilderTitleMessage: "á_Success! Item saved_Ó",
      shareBuilderTextMessage: "á_You can start collecting information by sharing with others_Ó",
      shareModalFormText: "á_Form Link_Ó",
      shareBuilderSuccess: "á_Your GeoForm has been updated & published_Ó!",
      geoformTitleText: "á_Geo Form_Ó",
      layerTabText: "á_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_Ó.",
      detailsTabText: "á_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_Ó.",
      fieldsTabText: "á_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_Ó.",
      styleTabText: "á_Style your GeoForm using the themes below based on your preference_Ó.",
      publishTabText: "á_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_Ó.",
      headerSizeLabel: "á_Header Size_Ó",
      smallHeader: "á_Use Small Header_Ó",
      bigHeader: "á_Use Large Header_Ó",
      pushpinText: "á_Push pin_Ó",
      doneButtonText: "á_Save and Exit_Ó",
      fieldTabPlaceHolderHeaderText: "á_Hint (optional)_Ó",
      enableAttachmentLabelText: "á_${openStrong}Enable Attachments${closeStrong}_Ó",
      enableAttachmentLabelHint: "á_You can enable/disable the attachments here_Ó",
      attachmentIsRequiredLabelText: "á_${openStrong}Attachment Required${closeStrong}_Ó",
      attachmentIsRequiredLabelHint: "á_If necessary, users can be required to enter an attachment_Ó.",
      attachmentLabelText: "á_Attachment Button Label_Ó",
      attachmentLabelHint: "á_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_Ó",
      attachmentDescription: "á_Attachment Description_Ó",
      attachmentHint: "á_If necessary, you can provide additional attachment instructions here_Ó.",
      jumbotronDescription: "á_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_Ó",
      shareGeoformText: "á_Share Geoform_Ó",
      shareDescription: "á_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_Ó.",
      defaultMapExtent: "á_Default Map Extent_Ó",
      defaultMapExtentDescription: "á_The map will reset to the default extent in your web map after submission - this can be disabled at any time_Ó.",
      pushpinOptionsDescription: "á_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_Ó",
      selectLocationText: "á_Select Location By_Ó",
      myLocationText: "á_My Location_Ó",
      searchText: "á_Search_Ó",
      coordinatesText: "á_Latitude & Longitude Coordinates_Ó",
      usng: "á_USNG Coordinates_Ó",
      mgrs: "á_MGRS Coordinates_Ó",
      utm: "á_UTM Coordinates_Ó",
      selectLocationSDescription: "á_Allow users to select a location using these methods_Ó.",
      dragTooltipText: "á_Drag the field where you want it to appear_Ó",
      showHideLayerText: "á_Show Layer_Ó",
      showHideLayerHelpText: "á_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_Ó.",
      labelHelpMessage: "á_Label_Ó",
      placeHolderHintMessage: "á_Hint Text_Ó",
      placeHolderHelpMessage: "á_Help Text_Ó",
      selectTextOptionValue: "á_Filter Select_Ó",
      disableLogo: "á_Disable Logo_Ó",
      disableLogoDescription: "á_You can configure the GeoForm to Show/Hide the Logo in the form header_Ó",
      locateOnLoadText: "á_Locate On Load_Ó",
      locateOnLoadDescription: "á_You can configure the GeoForm to use the current location on page load_Ó",
      selectLayerFieldTabText: "á_Select Layer_Ó",
      allLayerSelectOptionText: "á_All_Ó",
      disableViewer: "á_Disable Viewer_Ó",
      disableViewerDescription: "á_You can configure the GeoForm to disable/enable Viewer_Ó",
      displayFieldHintText: "á_Selected display field will be shown in viewerMode as title field_Ó"
    },
    viewer: {
      geocoderCancelText: "á_Cancel_Ó",
      viewReportsTabText: "á_Submissions_Ó",
      viewLegendTabText: "á_Legend_Ó",
      viewAboutusTabText: "á_About_Ó",
      viewMapTabText: "á_Map_Ó",
      sortHeaderText: "á_Sort By_Ó:",
      btnSubmitReportText: "á_Submit a Report_Ó",
      geocoderPlaceholderText: "á_Zip Code, city, etc_Ó.",
      noSearchResult: "á_No result found_Ó",
      recordsTabTooltip: "á_View Submissions_Ó",
      legendTabTooltip: "á_Legend_Ó",
      aboutUsTabTooltip: "á_AboutUs_Ó",
      mapTabTooltip: "á_Map_Ó",
      appLoadingFailedMessage: "á_ViewerMode is Unavailable_Ó",
      btnDescendingText: "á_Desc_Ó",
      btnAscendingText: "á_Asc_Ó",
      geometryUnavailableErrorMessage: "á_Unable to find the geometry of the feature_Ó",
      infoPopupOffErrorMessage: "á_InfoPopup is off_Ó",
      btnLoadMoreText: "á_Load More_Ó",
      unavailableTitleText: "á_Untitled_Ó",
      unavailableConfigMessage: "á_Unable to load config_Ó"
    }
  })
);