define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Die ausgewählte Webkarte enthält keinen gültigen Layer. Fügen Sie einen editierbaren Feature-Layer in Ihre Webkarte ein, um den Vorgang fortzusetzen.",
            selectFieldsText:"Formularfelder auswählen",
            selectThemeText: "Formular-Design auswählen",
            fieldLabelPlaceHolder: "Dieses Feld beschriften",
            fieldDescPlaceHolder: "Dieses Feld beschreiben",
            webmapText: "1. Webkarte",
            layerText: "2. Layer",
            detailsText: "3. Details",
            fieldsText: "4. Felder",
            styleText: "5. Style",
            previewText: "6. Vorschau",
            publishText: "7. Veröffentlichen",
            titleText: "GeoForm-Generator",
            descriptionText: "GeoForm ist eine konfigurierbare Vorlage zur formularbasierten Datenbearbeitung eines <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature-Service</a>. Diese Anwendung ermöglicht die Eingabe von Daten über ein Formular statt über das Pop-up einer Karte und nutzt gleichzeitig das Potenzial der <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Webkarte</a> und editierbarer Feature-Services. Verwenden Sie diesen Builder, um Ihre GeoForm-Vorlage anzupassen und bereitzustellen, indem Sie die links aufgeführten Schritte ausführen.",
            btnPreviousText: "Zurück",
            btnNextText:"Weiter",
            webmapTabTitleText: "Eine Webkarte auswählen",
            btnSelectWebmapText:"Webkarte auswählen",
            layerTabTitleText: "Editierbaren Layer auswählen",
            selectLayerLabelText:"Layer",
            selectLayerDefaultOptionText:"Layer auswählen",
            detailsTabTitleText:"Formulardetails",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logo-Bild",
            detailDescriptionLabelText: "Beschreibung",
            fieldTabFieldHeaderText: "Feld",
            fieldTabLabelHeaderText: "Beschriftung",
            fieldTabTypeHeaderText: "Typ",
            fieldTabDescriptionHeaderText: "Beschreibung",
            previewApplicationText: "Vorschau der Anwendung anzeigen",
            saveApplicationText: "Anwendung speichern",
            saveText: "Speichern",
            toggleNavigationText: "Navigation ein-/ausschalten",
            formPlaceholderText: "Eigenes Formular",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "GeoForm wird veröffentlicht",
            shareBuilderProgressBarMessage:"Bitte warten...",
            shareBuilderTitleMessage: "GeoForm wurde aktualisiert und veröffentlicht!",
            shareBuilderTextMessage: "Sie können mit der Erfassung von Informationen beginnen, indem Sie es für andere Benutzer freigeben",
            shareDialogFormText: "Formular-Link",
            geoformTitleText: "GeoForm",
            layerTabText: "Dies ist der Layer, aus dem die GeoForm erstellt wird. Der Layer muss ein Feature-Service sein, für den die Bearbeitung aktiviert ist, und dessen Freigabeberechtigungen für Ihre Zielgruppe geeignet sind.",
            detailsTabText:"Verwenden Sie die Formulardetailfelder, um den Titel anzupassen, ein benutzerdefiniertes Logo hinzuzufügen und eine kurze Beschreibung Ihrer GeoForm-Zielgruppe bereitzustellen.",
            fieldsTabText:"Hier können Sie festlegen welche Felder für Ihre GeoForm-Zielgruppe sichtbar sind, die Beschriftungen bearbeiten, die sie sehen können, und eine kurze Beschreibung hinzufügen, um die Dateneingabe zu vereinfachen.",
            styleTabText: "Legen Sie das GeoForm-Design anhand der folgenden Themen nach Ihren Vorlieben fest.",
            publishTabText: "Wenn Sie Ihre GeoForm-Vorlage angepasst haben, speichern Sie die Anwendung, und teilen Sie diese mit Ihrer Zielgruppe. Sie können jederzeit zu diesem Assistenten zurückkehren und die Anpassung je nach Feedback fortsetzen."
        }
    })
);