define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ä_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Ü",
            selectFieldsText:"ä_Select Form Fields_Ü",
            selectThemeText: "Formular-Design auswählen",
            fieldLabelPlaceHolder: "Dieses Feld beschriften",
            fieldDescPlaceHolder: "Dieses Feld beschreiben",
            webmapText: "ä_1. Webmap_Ü",
            layerText: "ä_2. Layer_Ü",
            detailsText: "ä_3. Details_Ü",
            fieldsText: "ä_4. Fields_Ü",
            styleText: "ä_5. Style_Ü",
            previewText: "ä_6. Preview_Ü",
            publishText: "ä_7. Publish_Ü",
            titleText: "GeoForm-Generator",
            descriptionText: "ä_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._Ü",
            btnPreviousText: "Zurück",
            btnNextText:"Weiter",
            webmapTabTitleText: "Eine Webkarte auswählen",
            btnSelectWebmapText:"Webkarte auswählen",
            layerTabTitleText: "Editierbaren Layer auswählen",
            selectLayerLabelText:"Layer",
            selectLayerDefaultOptionText:"Layer auswählen",
            detailsTabTitleText:"Formulardetails",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logo-Bild",
            detailDescriptionLabelText: "Beschreibung",
            fieldTabFieldHeaderText: "Feld",
            fieldTabLabelHeaderText: "Beschriftung",
            fieldTabTypeHeaderText: "Typ",
            fieldTabDescriptionHeaderText: "Beschreibung",
            previewApplicationText: "Vorschau der Anwendung anzeigen",
            saveApplicationText: "Anwendung speichern",
            saveText: "Speichern",
            toggleNavigationText: "ä_Toggle navigation_Ü",
            formPlaceholderText: "ä_My Form_Ü",
            imageLogoPlaceholderText: "ä_http://www.mysite.com/myimage.png_Ü",
            shareBuilderInProgressTitleMessage: "ä_Publishing GeoForm_Ü",
            shareBuilderProgressBarMessage:"ä_Please Wait..._Ü",
            shareBuilderTitleMessage: "ä_Your GeoForm has been updated & published!_Ü",
            shareBuilderTextMessage: "ä_You can start collecting information by sharing with others_Ü",
            shareDialogFormText: "ä_Form Link_Ü",
            geoformTitleText: "ä_Geo Form_Ü",
            layerTabText: "ä_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Ü",
            detailsTabText:"ä_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._Ü",
            fieldsTabText:"ä_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Ü",
            styleTabText: "ä_Style your GeoForm using the themes below based on your preference._Ü",
            publishTabText: "ä_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Ü"
        }
    })
);