define(
   ({
    map: {
      error: "ä_Unable to create map_Ü"
    },
    onlineStatus: {
      offline: "ä_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_Ü.",
      reconnecting: "ä_Reconnecting&hellip;_Ü",
      pending: "ä_${total} pending edit(s) will be submitted when a network connection is re-established_Ü."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "ä_My Organization_Ü",
          onlineLabel: "ä_ArcGIS Online_Ü",
          contentLabel: "ä_My Content_Ü",
          favoritesLabel: "ä_My Favorites_Ü"
        },
        title: "ä_Select Web Map_Ü",
        searchTitle: "ä_Search_Ü",
        ok: "ä_Ok_Ü",
        cancel: "ä_Cancel_Ü",
        placeholder: "ä_Enter search term_Ü"
      },
      groupdlg: {
        items: {
          organizationLabel: "ä_My Organization_Ü",
          onlineLabel: "ä_ArcGIS Online_Ü",
          contentLabel: "ä_My Content_Ü",
          favoritesLabel: "ä_My Favorites_Ü"
        },
        title: "ä_Select Group_Ü",
        searchTitle: "ä_Search_Ü",
        ok: "ä_Ok_Ü",
        cancel: "ä_Cancel_Ü",
        placeholder: "ä_Enter search term_Ü"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "ä_Here is a link to a GeoForm_Ü"
      }
    },
    user: {
      mgrs: "ä_MGRS_Ü",
      usng: "ä_USNG_Ü",
      utm: "ä_UTM_Ü",
      utm_northing: "ä_Northing_Ü",
      utm_easting: "ä_Easting_Ü",
      utm_zone_number: "ä_Zone Number_Ü",
      selectLayerTabText: "ä_${formSection} Select Form_Ü",
      geoFormGeneralTabText: "ä_${formSection} Enter Information_Ü",
      locationInformationText: "ä_${formSection} Select Location_Ü",
      submitInformationText: "ä_${formSection} Complete Form_Ü",
      submitInstructions: "ä_Add this information to the map_Ü.",
      myLocationText: "ä_Current Location_Ü",
      locationDescriptionForMoreThanOneOption: "ä_Specify the location for this entry by clicking/tapping the map or by using one of the following options_Ü.",
      locationDescriptionForOneOption: "ä_Specify the location for this entry by clicking/tapping the map or by using the following option_Ü.",
      locationDescriptionForNoOption: "ä_Specify the location for this entry by clicking/tapping the map_Ü.",
      addressText: "ä_Search_Ü",
      geographic: "ä_Lat/Lon_Ü",
      locationTabText: "ä_Location_Ü",
      locationPopupTitle: "ä_Location_Ü",
      submitButtonText: "ä_Submit Entry_Ü",
      submitButtonTextLoading: "ä_Submitting&hellip;_Ü",
      formValidationMessageAlertText: "ä_The following fields are required_Ü:",
      selectLocation: "ä_Please select a location for your submission_Ü.",
      emptylatitudeAlertMessage: "ä_Please enter a ${openLink}latitude${closeLink} coordinate_Ü.",
      emptylongitudeAlertMessage: "ä_Please enter a ${openLink}longitude${closeLink} coordinate_Ü.",
      shareUserTitleMessage: "ä_Thank you for your contribution_Ü!",
      entrySubmitted: "ä_Your entry has been submitted to the map_Ü.",
      shareThisForm: "ä_Share This Form_Ü",
      shareUserTextMessage: "ä_Tell others to contribute using the following options_Ü.",
      addAttachmentFailedMessage: "ä_Unable to add attachment to layer_Ü",
      addFeatureFailedMessage: "ä_Unable to add feature to layer_Ü",
      noLayerConfiguredMessage: "ä_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_Ü.",
      placeholderLatitude: "ä_Latitude (Y)_Ü",
      placeholderLongitude: "ä_Longitude (X)_Ü",
      latitude: "ä_Latitude_Ü",
      longitude: "ä_Longitude_Ü",
      findMyLocation: "ä_Locate Me_Ü",
      finding: "ä_Locating&hellip;_Ü",
      backToTop: "ä_Back to top_Ü",
      addressSearchText: "ä_Your submission will appear here. You can drag the pin to correct the location_Ü.",
      shareModalFormText: "ä_Form Link_Ü",
      close: "ä_Close_Ü",
      locationNotFound: "ä_Location could not be found_Ü.",
      setLocation: "ä_Set Location_Ü",
      find: "ä_Find address or place_Ü",
      attachment: "ä_Attachment_Ü",
      toggleDropdown: "ä_Toggle Dropdown_Ü",
      invalidString: "ä_Please enter valid value_Ü.",
      invalidSmallNumber: "ä_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_Ü.",
      invalidNumber: "ä_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_Ü.",
      invalidFloat: "ä_Please enter valid ${openStrong}floating point${closeStrong} value_Ü.",
      invalidDouble: "ä_Please enter valid ${openStrong}double${closeStrong} value_Ü.",
      invalidLatLong: "ä_Please enter valid latitude and longitude coordinates_Ü.",
      invalidUTM: "ä_Please enter valid UTM coordinates_Ü.",
      invalidUSNG: "ä_Please enter valid USNG coordinates_Ü.",
      invalidMGRS: "ä_Please enter valid MGRS coordinates_Ü.",
      geoformTitleText: "ä_GeoForm_Ü",
      domainDefaultText: "ä_Select&hellip;_Ü",
      applyEditsFailedMessage: "ä_Sorry your entry cannot be submitted. Please try again_Ü.",
      requiredFields: "ä_There are some errors. Please correct them below_Ü.",
      requiredField: "ä_(required)_Ü",
      error: "ä_Error_Ü",
      textRangeHintMessage: "ä_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_Ü",
      dateRangeHintMessage: "ä_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_Ü",
      remainingCharactersHintMessage: "ä_${value} characters remaining_Ü",
      mapFullScreen: "ä_Full Screen_Ü",
      mapRestore: "ä_Restore_Ü",
      filterSelectEmptyText: "ä_Select_Ü",
      invalidLayerMessage: "ä_Form layer does not exist. Please configure the application and set the layer_Ü.",
      selectedLayerText: "ä_All_Ü"
    },
    builder: {
      invalidUser: "ä_Sorry, you dont have permission to view this item_Ü",
      invalidWebmapSelectionAlert: "ä_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_Ü.",
      invalidWebmapSelectionAlert2: "ä_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_Ü",
      selectFieldsText: "ä_Select Form Fields_Ü",
      selectThemeText: "ä_Select Form Theme_Ü",
      webmapText: "ä_Webmap_Ü",
      layerText: "ä_Layer_Ü",
      detailsText: "ä_Details_Ü",
      fieldsText: "ä_Fields_Ü",
      styleText: "ä_Style_Ü",
      optionText: "ä_Options_Ü",
      previewText: "ä_Preview_Ü",
      publishText: "ä_Publish_Ü",
      optionsApplicationText: "ä_Options_Ü",
      titleText: "ä_Builder_Ü",
      descriptionText: "ä_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_Ü.",
      btnPreviousText: "ä_Previous_Ü",
      btnNextText: "ä_Next_Ü",
      webmapTabTitleText: "ä_Select a Webmap_Ü",
      viewWebmap: "ä_View webmap_Ü",
      webmapDetailsText: "ä_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_Ü",
      btnSelectWebmapText: "ä_Choose Webmap_Ü",
      btnSelectWebmapTextLoading: "ä_Loading&hellip;_Ü",
      layerTabTitleText: "ä_Select Editable Layer_Ü",
      selectLayerLabelText: "ä_Layer_Ü",
      selectLayerDefaultOptionText: "ä_Select Layer_Ü",
      defaultBasemap: "ä_Basemap Toggle_Ü",
      secondaryBasemap: "ä_Default Basemap_Ü",
      detailsTabTitleText: "ä_Form Details_Ü",
      detailTitleLabelText: "ä_Title_Ü",
      detailLogoLabelText: "ä_Logo Image_Ü",
      descriptionLabelText: "ä_Form Instructions & Details_Ü",
      fieldDescriptionLabelText: "ä_Help Text (optional)_Ü",
      fieldTabFieldHeaderText: "ä_Field_Ü",
      fieldTabLabelHeaderText: "ä_Label_Ü",
      fieldTabDisplayTypeHeaderText: "ä_Display As_Ü",
      fieldTabOrderColumnText: "ä_Order_Ü",
      fieldTabVisibleColumnText: "ä_Enabled_Ü",
      selectMenuOption: "ä_Select Menu_Ü",
      selectRadioOption: "ä_Radio Button_Ü",
      selectTextOption: "ä_Text_Ü",
      selectDateOption: "ä_Date Picker_Ü",
      selectRangeOption: "ä_Touch-Spinner_Ü",
      selectCheckboxOption: "ä_Checkbox_Ü",
      selectMailOption: "ä_Email_Ü",
      selectUrlOption: "ä_URL_Ü",
      selectTextAreaOption: "ä_Text Area_Ü",
      previewApplicationText: "ä_Preview Application_Ü",
      saveApplicationText: "ä_Save Application_Ü",
      saveText: "ä_Save_Ü",
      toggleNavigationText: "ä_Toggle navigation_Ü",
      formPlaceholderText: "ä_My Form_Ü",
      shareBuilderInProgressTitleMessage: "ä_Publishing GeoForm_Ü",
      shareBuilderProgressBarMessage: "ä_Please Wait&hellip;_Ü",
      shareBuilderTitleMessage: "ä_Success! Item saved_Ü",
      shareBuilderTextMessage: "ä_You can start collecting information by sharing with others_Ü",
      shareModalFormText: "ä_Form Link_Ü",
      shareBuilderSuccess: "ä_Your GeoForm has been updated & published_Ü!",
      geoformTitleText: "ä_Geo Form_Ü",
      layerTabText: "ä_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_Ü.",
      detailsTabText: "ä_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_Ü.",
      fieldsTabText: "ä_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_Ü.",
      styleTabText: "ä_Style your GeoForm using the themes below based on your preference_Ü.",
      publishTabText: "ä_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_Ü.",
      headerSizeLabel: "ä_Header Size_Ü",
      smallHeader: "ä_Use Small Header_Ü",
      bigHeader: "ä_Use Large Header_Ü",
      pushpinText: "ä_Push pin_Ü",
      doneButtonText: "ä_Save and Exit_Ü",
      fieldTabPlaceHolderHeaderText: "ä_Hint (optional)_Ü",
      enableAttachmentLabelText: "ä_${openStrong}Enable Attachments${closeStrong}_Ü",
      enableAttachmentLabelHint: "ä_You can enable/disable the attachments here_Ü",
      attachmentIsRequiredLabelText: "ä_${openStrong}Attachment Required${closeStrong}_Ü",
      attachmentIsRequiredLabelHint: "ä_If necessary, users can be required to enter an attachment_Ü.",
      attachmentLabelText: "ä_Attachment Button Label_Ü",
      attachmentLabelHint: "ä_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_Ü",
      attachmentDescription: "ä_Attachment Description_Ü",
      attachmentHint: "ä_If necessary, you can provide additional attachment instructions here_Ü.",
      jumbotronDescription: "ä_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_Ü",
      shareGeoformText: "ä_Share Geoform_Ü",
      shareDescription: "ä_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_Ü.",
      defaultMapExtent: "ä_Default Map Extent_Ü",
      defaultMapExtentDescription: "ä_The map will reset to the default extent in your web map after submission - this can be disabled at any time_Ü.",
      pushpinOptionsDescription: "ä_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_Ü",
      selectLocationText: "ä_Select Location By_Ü",
      myLocationText: "ä_My Location_Ü",
      searchText: "ä_Search_Ü",
      coordinatesText: "ä_Latitude & Longitude Coordinates_Ü",
      usng: "ä_USNG Coordinates_Ü",
      mgrs: "ä_MGRS Coordinates_Ü",
      utm: "ä_UTM Coordinates_Ü",
      selectLocationSDescription: "ä_Allow users to select a location using these methods_Ü.",
      dragTooltipText: "ä_Drag the field where you want it to appear_Ü",
      showHideLayerText: "ä_Show Layer_Ü",
      showHideLayerHelpText: "ä_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_Ü.",
      labelHelpMessage: "ä_Label_Ü",
      placeHolderHintMessage: "ä_Hint Text_Ü",
      placeHolderHelpMessage: "ä_Help Text_Ü",
      selectTextOptionValue: "ä_Filter Select_Ü",
      disableLogo: "ä_Disable Logo_Ü",
      disableLogoDescription: "ä_You can configure the GeoForm to Show/Hide the Logo in the form header_Ü",
      locateOnLoadText: "ä_Locate On Load_Ü",
      locateOnLoadDescription: "ä_You can configure the GeoForm to use the current location on page load_Ü",
      selectLayerFieldTabText: "ä_Select Layer_Ü",
      allLayerSelectOptionText:"ä_All_Ü"
    }
  })
);