define(
     ({
        map: {
            error: "Karte kann nicht erstellt werden"
        },
        onlineStatus: {
            offline: "Sie arbeiten derzeit offline. Gesendete Formulare werden lokal gespeichert, bis eine Verbindung mit dem Server hergestellt werden kann.",
            reconnecting: "Verbindung erneut herstellen&hellip;",
            pending: "${total} ausstehende Änderung(en) wird/werden übermittelt, sobald die Netzwerkverbindung wiederhergestellt ist."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Eigene Organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Eigene Inhalte",
                    favoritesLabel: "Eigene Favoriten"
                },
                title: "Webkarte auswählen",
                searchTitle: "Suchen",
                ok: "OK",
                cancel: "Abbrechen",
                placeholder: "Suchbegriff eingeben"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Eigene Organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Eigene Inhalte",
                    favoritesLabel: "Eigene Favoriten"
                },
                title: "Gruppe auswählen",
                searchTitle: "Suchen",
                ok: "OK",
                cancel: "Abbrechen",
                placeholder: "Suchbegriff eingeben"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Hochwert",
            utm_easting: "Rechtswert",
            utm_zone_number: "Zonennummer",
            geoFormGeneralTabText: "1. Informationen eingeben",
            locationInformationText: "2. Position auswählen",
            submitInformationText: "3. Formular ausfüllen",
            submitInstructions: "Fügen Sie der Karte diese Informationen hinzu.",
            myLocationText: "ä_Current Location_Ü",
            locationDescription: "ä_Specify the location for this entry by clicking/tapping the map or by using one of the following options._Ü",
            addressText: "Suchen",
            geographic: "ä_Lat/Lon_Ü",
            locationTabText: "Position",
            locationPopupTitle: "ä_Location_Ü",
            submitButtonText: "ä_Submit Entry_Ü",
            submitButtonTextLoading: "Wird übermittelt&hellip;",
            formValidationMessageAlertText: "Die folgenden Felder sind erforderlich:",
            selectLocation: "Wählen Sie eine ${openLink}Position${closeLink} für die Übermittlung aus.",
            emptylatitudeAlertMessage: "Geben Sie eine ${openLink}Breitengrad${closeLink}koordinate ein.",
            emptylongitudeAlertMessage: "Geben Sie eine ${openLink}Längengrad${closeLink}koordinate ein.",
            shareUserTitleMessage: "Vielen Dank für Ihren Beitrag!",
            entrySubmitted: "ä_Your entry has been submitted to the map._Ü",
            shareThisForm: "ä_Share This Form_Ü",
            shareUserTextMessage: "ä_Tell others to contribute using the following options._Ü",
            addAttachmentFailedMessage: "Anlage kann dem Layer nicht hinzugefügt werden",
            addFeatureFailedMessage: "Feature kann dem Layer nicht hinzugefügt werden",
            noLayerConfiguredMessage: "Hoppla! Hier wird nichts angezeigt. Um die Erfassung gesendeter Formulare zu starten, konfigurieren Sie diese GeoForm-Vorlage, und wählen Sie einen editierbaren Feature-Service-Layer aus.",
            placeholderLatitude: "Breitengrad (Y)",
            placeholderLongitude: "Längengrad (X)",
            latitude: "Breitengrad",
            longitude: "Längengrad",
            findMyLocation: "ä_Locate Me_Ü",
            finding: "Standortsuche&hellip;",
            backToTop: "Nach oben",
            addressSearchText: "Ihr gesendetes Formular wird hier angezeigt. Sie können den Pin ziehen, um die Position zu korrigieren.",
            shareModalFormText: "Formular-Link",
            close: "Schließen",
            locationNotFound: "Position konnte nicht gefunden werden.",
            setLocation: "ä_Set Location_Ü",
            find: "ä_Find address or place_Ü",
            attachment: "Anlage",
            toggleDropdown: "Dropdown ein-/ausschalten",
            invalidLatLong: "Geben Sie gültige ${latLink}Breitengrad${closeLink}- und ${lngLink}Längengrad${closeLink}koordinaten ein.",
            invalidUTM: "Geben Sie gültige ${openLink}UTM${closeLink}-Koordinaten ein.",
            invalidUSNG: "Geben Sie gültige ${openLink}USNG${closeLink}-Koordinaten ein.",
            invalidMGRS: "Geben Sie gültige ${openLink}MGRS${closeLink}-Koordinaten ein.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Auswählen&hellip;",
            applyEditsFailedMessage: "Ihr Eintrag konnte nicht übermittelt werden. Versuchen Sie es erneut.",
            requiredFields: "Es sind einige Fehler aufgetreten. Beheben Sie sie unten.",
            requiredField: "ä_(required)_Ü",
            error: "Fehler",
            textRangeHintMessage: "ä_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_Ü",
            dateRangeHintMessage: "ä_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_Ü"
        },
        builder: {
            invalidUser: "ä_Sorry, you dont have permission to view this item_Ü",
            invalidWebmapSelectionAlert: "ä_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Ü",
            invalidWebmapSelectionAlert2: "ä_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_Ü",
            selectFieldsText: "ä_Select Form Fields_Ü",
            selectThemeText: "ä_Select Form Theme_Ü",
            webmapText: "ä_Webmap_Ü",
            layerText: "ä_Layer_Ü",
            detailsText: "ä_Details_Ü",
            fieldsText: "ä_Fields_Ü",
            styleText: "ä_Style_Ü",
            optionText: "ä_Options_Ü",
            previewText: "ä_Preview_Ü",
            publishText: "ä_Publish_Ü",
            optionsApplicationText: "ä_Options_Ü",
            titleText: "ä_Builder_Ü",
            descriptionText: "ä_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._Ü",
            btnPreviousText: "ä_Previous_Ü",
            btnNextText: "ä_Next_Ü",
            webmapTabTitleText: "ä_Select a Webmap_Ü",
            viewWebmap: "ä_View webmap_Ü",
            btnSelectWebmapText: "ä_Choose Webmap_Ü",
            btnSelectWebmapTextLoading: "ä_Loading&hellip;_Ü",
            layerTabTitleText: "ä_Select Editable Layer_Ü",
            selectLayerLabelText: "ä_Layer_Ü",
            selectLayerDefaultOptionText: "ä_Select Layer_Ü",
            detailsTabTitleText: "ä_Form Details_Ü",
            detailTitleLabelText: "ä_Title_Ü",
            detailLogoLabelText: "ä_Logo Image_Ü",
            descriptionLabelText: "ä_Help Text (optional)_Ü",
            fieldTabFieldHeaderText: "ä_Field_Ü",
            fieldTabLabelHeaderText: "ä_Label_Ü",
            fieldTabDisplayTypeHeaderText: "ä_Display As_Ü",
            selectMenuOption: "ä_Select Menu_Ü",
            selectRadioOption: "ä_Radio Button_Ü",
            selectTextOption: "ä_Text_Ü",
            selectCheckboxOption: "ä_Checkbox_Ü",
            selectMailOption: "ä_Email_Ü",
            selectUrlOption: "ä_URL_Ü",
            selectTextAreaOption: "ä_Textarea_Ü",
            previewApplicationText: "ä_Preview Application_Ü",
            saveApplicationText: "ä_Save Application_Ü",
            saveText: "ä_Save_Ü",
            toggleNavigationText: "ä_Toggle navigation_Ü",
            formPlaceholderText: "ä_My Form_Ü",
            shareBuilderInProgressTitleMessage: "ä_Publishing GeoForm_Ü",
            shareBuilderProgressBarMessage: "ä_Please Wait&hellip;_Ü",
            shareBuilderTitleMessage: "ä_Success! Item saved_Ü",
            shareBuilderTextMessage: "ä_You can start collecting information by sharing with others_Ü",
            shareModalFormText: "ä_Form Link_Ü",
            shareBuilderSuccess: "ä_Your GeoForm has been updated & published!_Ü",
            geoformTitleText: "ä_Geo Form_Ü",
            layerTabText: "ä_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Ü",
            detailsTabText: "ä_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._Ü",
            fieldsTabText: "ä_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Ü",
            styleTabText: "ä_Style your GeoForm using the themes below based on your preference._Ü",
            publishTabText: "ä_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Ü",
            smallHeader: "ä_Use Small Header_Ü",
            pushpinText: "ä_Push pin_Ü",
            doneButtonText: "ä_View Application Item_Ü",
            fieldTabPlaceHolderHeaderText: "ä_Hint (optional)_Ü",
            attachmentLabelText: "ä_Attchment Label_Ü",
            attachmentLabelHint: "ä_Tell users what type of file to attach._Ü",
            attachmentDescription: "ä_Attachment Description_Ü",
            attachmentHint: "ä_If necessary, you can provide additional attachment instructions here._Ü",
            jumbotronDescription: "ä_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._Ü",
            shareGeoformText: "ä_Share Geoform_Ü",
            shareDescription: "ä_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._Ü",
            defaultMapExtent: "ä_Default Map Extent_Ü",
            defaultMapExtentDescription: "ä_The map will reset to the default extent in your web map after submission - this can be disabled at any time._Ü",
            pushpinOptionsDescription: "ä_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_Ü",
            selectLocationText: "ä_Select Location By_Ü",
            myLocationText: "ä_My Location_Ü",
            searchText: "ä_Search_Ü",
            coordinatesText: "ä_Latitude & Longitude Coordinates_Ü",
            usng: "ä_USNG Coordinates_Ü",
            mgrs: "ä_MGRS Coordinates_Ü",
            utm: "ä_UTM Coordinates_Ü",
            selectLocationSDescription: "ä_Allow users to select a location using these methods._Ü"
        }
    })
);