define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Enter Builder",
                "exitBuilderButtonText": "Exit Builder",
                "enterBuilderModeHelpText": "Enter Builder Mode to configure application",
                "builderModeHelpText": "Template Builder Mode",
                "webmapCaption": "Map",
                "selectMapMessage": "Currently ${displaying} <b>${webmapTitle}</b><br/>Click Select map to choose a different webmap",
                "loadMapMessage": "Currently selected <b>${webmapTitle}</b><br/>Click Save to use this webmap",
                "changeWebmap": "Select map",
                "saveButtonText": "Save",
                "webmapNextButtonText": "Next ->",
                "previousButtonText":"Previous",
                "layerLabelText": "Layer",
                "noLayerFoundText": "No Layer Found",
                "selectLayer": "Select Layer",
                "applicationSettingText": "Application Settings",
                "summaryAttrAscendingOrderTooltip": "Ascending",
                "onStartLabel": "On Start",
                "selectVariableText": "Select A Variable",
                "selectVariableDropdown": "Select A Variable",
                "label":"Label",
                "sourceLinkText":"Source Link",
                "selectSubVariableText":"Select Sub Variables",
                "subVariablePanelButtonText":"DONE",
                "onButtonLabel":"On",
                "offButtonLabel":"Off",
                "appSettingsSaveCloseButtonText": "SAVE & CLOSE",
                "appSettingsTitleText":"App Title",
                "appSettingsDescriptionText": "Application Description",
                "appSetingsRendererAreaText":"Rendered Area",
                "shareText":"Share",
                "popupText": "Popup",
                "basemapText":"Basemap",
                "cancel": "Cancel",
                "theme": "Theme",
                "zoomLevel": "Zoom Level",
                "existingValue": "Use existing values",
                "enrichLayer": "Enrich Layer",
                "imageLabel": "How does this work ?",
                "clearData": "Clear Data",
                "basemapSelectionText":"Basemap Selection",
                "secondaryBasemapText":"Secondary Basemap",
                "defaultBasemapText": "Default Basemap",
                "entireAreaButton": "Entire Area",
                "entireAreaOnStartButton": "Entire Area on start",
                "aboutPanel": "About Panel",
                "legendPanel": "Legend Panel",
                "layersPanel": "Layers Panel",
                "dataConfigurationButtonText": "Data Configuration",
                "savingChangesMessage": "Saving Changes...",
                "nextButtonText": "Next",
                "prevButtonText": "Previous",
                "enterLabelText": "Enter Label",
                "SelectedFeatureText": "Selected Feature",
                "layerHelpTextMessage": "This application requires a layer with numeric fields",
                "alertMessage": {
                    "resetVariableMessage": "Are you sure you want to reset variable?",
                    "emptyAppTitleMessage": "Application title cannot be empty",
                    "emptyDescriptionMessage": "Description cannot be empty",
                    "maxVariableSelection": "You cannot select more than 25 sub variables",
                    "signInFail" : "Sign-in Failed",
                    "itemUpdateMessage": "Item Updated",
                    "unsavedChangesMessage": "Unsaved Changes",
                    "failMessage": "Could not update the item sucessfully",
                    "saveChangesAlert": "Do you want to save the changes ?",
                    "variableLabelValidation": "Variable label cannot be empty",
                    "subVariableLabelValidation": "Sub variable label cannot be empty"
                    }
            }
        }
    })
);