define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Enter Builder",
                "exitBuilderButtonText": "Exit Builder",
                "enterBuilderModeHelpText": "Enter Builder Mode to configure application",
                "builderModeHelpText": "Template Builder Mode",
                "webmapCaption": "Map",
                "selectMapMessage": "Currently ${displaying} <b>${webmapTitle}</b><br/>Click Select map to choose a different webmap",
                "loadMapMessage": "Currently selected <b>${webmapTitle}</b><br/>Click Save to use this webmap",
                "changeWebmap": "Select map",
                "saveButtonText": "Save",
                "webmapNextButtonText": "Next ->",
                "previousButtonText":"Previous",
                "layerLabelText": "Layer",
                "noLayerFoundText": "No Layer Found",
                "selectLayer": "Select Layer",
                "applicationSettingText": "Application Settings",
                "summaryAttrAscendingOrderTooltip": "Ascending",
                "onStartLabel": "On Start",
                "selectVariableText": "Select A Variable",
                "selectVariableDropdown": "Select A Variable",
                "label":"Label",
                "sourceLinkText":"Source Link",
                "selectSubVariableText":"Select Sub Variables",
                "subVariablePanelButtonText":"DONE",
                "onButtonLabel":"On",
                "offButtonLabel":"Off",
                "appSettingsSaveCloseButtonText": "SAVE & CLOSE",
                "appSettingsTitleText":"App Title",
                "appSettingsDescriptionText": "Application Description",
                "appSetingsRendererAreaText":"Rendered Area",
                "shareText":"Share",
                "basemapText":"Basemap",
                "basemapSelectionText":"Basemap Selection",
                "secondaryBasemapText":"Secondary Basemap",
                "defaultBasemapText": "Default Basemap",
                "entireAreaButton": "Entire Area",
                "entireAreaOnStartButton": "Entire Area on start",
                "aboutPanel": "About Panel",
                "legendPanel": "Legend Panel",
                "layersPanel": "Layers Panel",
                "dataConfigurationButtonText": "Data Configuration",
                "savingChangesMessage": "Saving Changes...",
                "nextButtonText": "Next",
                "prevButtonText": "Previous",
                "enterLabelText": "Enter Label",
                "SelectedFeatureText": "Selected Feature",
                "layerHelpTextMessage": "This application requires a layer with numeric fields",
                "alertMessage": {
                    "resetVariableMessage": "Are You sure you want to reset variable ?",
                    "emptyAppTitleMessage": "Application title cannot be empty",
                    "emptyDescriptionMessage": "Description cannot be empty",
                    "maxVariableSelection": "You cannot select more than 25 sub variables",
                    "signInFail" : "Sign-in Failed",
                    "itemUpdateMessage": "Item Updated",
                    "unsavedChangesMessage": "Unsaved Changes",
                    "failMessage": "Could not update the item sucessfully",
                    "saveChangesAlert": "Do you want to save the changes ?",
                    "variableLabelValidation": "Variable label cannot be EMPTY",
                    "subVariableLabelValidation": "Sub variable label cannot be EMPTY"
                    }
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "zh-cn": 1
});