define(
({
		viewer: {
			loading: {
				step1: "ANWENDUNG WIRD GELADEN",
				step2: "DATEN WERDEN GELADEN",
				step3: "TOUR WIRD INITIALISIERT",
				loadBuilder: "ES WIRD ZUM BUILDER-MODUS GEWECHSELT",
				redirectSignIn: "ä_REDIRECTING TO SIGN-IN PAGE_Ü",
				redirectSignIn2: "ä_(you will be redirected here after sign-in)_Ü",
				fail: "Map Tour konnte leider nicht geladen werden",
				failButton: "Wiederholen"
			},
			errors: {
				boxTitle: "Ein Fehler ist aufgetreten",
				portalSelf: "Schwerwiegender Fehler: Die Portalkonfiguration konnte nicht abgerufen werden",
				invalidConfig: "Schwerwiegender Fehler: Ungültige Konfiguration",
				invalidConfigOwner: "Schwerwiegender Fehler: Ungültige Konfiguration (autorisierter Benutzer erforderlich)",
				invalidConfigNoWebmap: "Schwerwiegender Fehler: Ungültige Konfiguration (Webkarte oder Anwendungskennung nicht in \"index.html\" angegeben)",
				createMap: "Karte kann nicht erstellt werden",
				invalidApp: "Schwerwiegender Fahler: Die Anwendung kann nicht geladen werden",
				noLayer: "Die Webkarte enthält keinen gültigen Daten-Layer für Map Tour.",
				noLayerMobile: "Willkommen bei der Webanwendung \"Map Tour\". Die Anwendung ist nicht konfiguriert. Der Map Tour-Generator wird auf mobilen Geräten nicht unterstützt.",
				noLayerView: "Willkommen bei der Webanwendung \"Map Tour\".<br />Die Anwendung ist noch nicht konfiguriert.",
				appSave: "Fehler beim Speichern der Webanwendung",
				mapSave: "Fehler beim Speichern der Webkarte",
				featureServiceLoad: "Fehler beim Laden des Feature-Service",
				notAuthorized: "Sie sind nicht autorisiert, auf diese Anwendung zuzugreifen",
				oldBrowserTitle: "Browser wird nicht vollständig unterstützt",
				noBuilderIE8: "Der Map Tour-Builder wird von Internet Explorer vor Version 9 nicht unterstützt.",
				ie10Win7Explain: "Der interaktive Map Tour-Builder wird von Internet Explorer 10 unter Windows 7 nicht unterstützt, wenn es sich bei der Datenquelle um einen Feature-Service mit Anlagen handelt. Um einen Feature-Service mit Anlagen zu verwenden, müssen Sie <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>den Dokumentmodus manuell auf Internet Explorer 9-Standards setzen</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>auf Internet Explorer 9 herunterstufen</a> oder ein Upgrade auf Windows 8 durchführen.",
				oldBrowserExplain: "Dieser Browser unterstützt keine automatische Erstellung von Miniaturansichten der Bilder, die Sie in Ihre Karten-Tour hochladen. Sie können zwar mit diesem Browser eine Map-Tour erstellen, aber Sie müssen für jedes hochgeladene Bild eine eigene Miniaturansicht bereitstellen.",
				oldBrowserExplain2: "Um die Performance zu verbessern, <a href='http://browsehappy.com/' target='_blank'>aktualisieren Sie Ihren Browser</a>, oder <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivieren Sie Google Chrome Frame für Internet Explorer</a>.",
				oldBrowserExplain3: "Der Map Tour-Builder kann nicht mit Internet Explorer 10 unter Windows XP verwendet werden.",
				oldBrowserClose: "Schließen"
			},
			mobileHTML: {
				showIntro: "TITEL EINBLENDEN",
				hideIntro: "TITEL AUSBLENDEN",
				navList: "Liste",
				navMap: "Karte",
				navInfo: "Medien",
				introStartBtn: "Start"
			},
			desktopHTML: {
				storymapsText: "Eine Story Map",
				builderButton: "Zum Generator-Modus wechseln",
				bitlyTooltip: "Kurzlink zur Anwendung abrufen",
				bitlyStartIndex: "ä_Link to current place_Ü"
			},
			builderHTML: {
				panelHeader: "ANWENDUNGSKONFIGURATION",
				buttonSave: "SPEICHERN",
				buttonSettings: "Einstellungen",
				buttonShare: "ä_Share_Ü",
				buttonView: "Anzeigemodus",
				buttonItem: "Webanwendungselement öffnen",
				buttonHelp: "Hilfe",
				buttonOrganize: "Organisieren",
				buttonAdd: "Hinzufügen",
				buttonImport: "Importieren",
				buttonImportDisabled: "Bei Verwendung eines Feature-Service mit Anlagen ist die Option \"Importieren\" nicht verfügbar",
				dataEditionDisabled: "Datenbearbeitung ist für CSV-Datenquelle deaktiviert",
				dataSourceWarning: "Der Map Tour-Daten-Layer hat sich geändert. Wenn die Feature-IDs nicht übereinstimmen, müssen Sie die Reihenfolge und verborgenen Punkte durch <b>Organisieren</b> zurücksetzen. Wenn die Feldnamen abweichen, müssen Sie die Feldeinstellungen auf der <b>Datenregisterkarte in den Einstellungen</b> zurücksetzen.",
				organizeWarning: "Ein oder mehrere außerhalb des interaktiven Builders erstellte Punkte sind ausgeblendet.",
				dataPicError0a: "Diese Tour enthält <b>%NB%</b> nicht-konforme Bild-URLs.",
				dataPicError0b: "Diese Tour könnte <b>%NB%</b> nicht-konforme Bild-URLs enthalten.",
				dataPicError1: "Für Map Tour ist jetzt eine Bild-URL erforderlich, die auf eine der folgenden Erweiterungen endet: .jp(e)g, .png, .gif oder .bmp.",
				dataPicError2: "Diese Anforderung hat keine Auswirkungen auf Ihre bereits veröffentlichte Map Tour. Um jedoch den interaktiven Builder nutzen zu können, müssen Sie zunächst eine von zwei Modifikationen an der URL vornehmen:",
				dataPicError3: "URLs bearbeiten",
				dataPicError4: "Hiermit wird <i>#isImage</i> an das Ende von nicht unterstützten Bild-URLs gehängt. URL-Anhänge werden von den meisten Servern unterstützt. Sobald Sie diese Aktion durchgeführt haben, sollten Sie allerdings mittels Navigation durch Ihre Punkte prüfen, ob die aktualisierten Bild-URLs funktionieren. Wird jedes Bild geladen, können Sie die Map Tour jetzt speichern. Sollten die <b>Bilder nicht angezeigt werden, speichern Sie Map Tour bitte nicht</b>. Rufen Sie stattdessen den Builder erneut auf und führen Sie die zweite Aktion durch.",
				dataPicError5: "Die Tour auf Bilder beschränken",
				dataPicError6: "Durch diese Option werden alle URLS als Bilder behandelt, es lassen sich jedoch keine Videos mithilfe des interaktiven Builders hinzufügen. Diese Aktion kann rückgängig gemacht werden, falls Sie künftig Videos hinzufügen möchten.",
				dataPicError7: "Ihre Map Tour ist auf Bilder beschränkt, es können keine Videos verwendet werden. Wenn Sie diese Beschränkung aufheben wollen, vergewissern Sie sich bitte vor dem Speichern der Map Tour, ob Ihre Bilder immer noch richtig geladen werden. Sie können diese Beschränkung später bei Bedarf wiederherstellen.",
				dataPicError8: "Beschränkung auf Bilder aufheben",
				dataPicError9: "Verweisen diese URLs auf Videos, so können Sie diese Warnung ignorieren, sollten sie auf Bilder verweisen, müssen Sie eine der folgenden beiden Aktionen ausführen:",
				modalCancel: "Abbrechen",
				modalApply: "Übernehmen",
				organizeHeader: "Tour organisieren",
				organizeGeneralCaption: "Tour-Punkte per Drag & Drop sortieren",
				organizeDelete: "Löschen",
				organizeHide: "Ausblenden",
				organizeReset: "Reihenfolge und verborgene Punkte zurücksetzen",
				addMaxPointReached: "Sie haben die maximale Punktzahl erreicht, die für die festgelegten Symbole zulässig ist, und können keine weiteren Tour-Punkte hinzufügen.<br /><br />Beachten Sie, dass die Anwendung erneut geladen werden muss, wenn Sie vorhandene Punkte löschen.",
				addMaxPointReachedMobile: "Sie können dieses Bild leider nicht hinzufügen, da Sie die maximal zulässige Anzahl von autorisierten Punkten erreicht haben.",
				addClose: "Schließen",
				addHeader: "Neuen Tour-Punkt hinzufügen",
				addTabPicture: "Medien",
				addTabInformation: "Informationen",
				addTabLocation: "Position",
				addSelectCaption: "Bild auswählen oder löschen",
				addNoteVideo: "Konsultieren Sie die Hilfe in Bezug auf Anweisungen zur Verwendung von Videos",		
				addSelectCaptionNoFileReader: "Bild auswählen",	
				addChangePhoto: "Bild und Miniaturansicht ändern",
				addPictureResolutionIntro: "Die Bildauflösung ist höher als erforderlich:",
				addPictureResolutionOldBrowser: "Die Bildauflösung ist höher als erforderlich. Optimieren Sie die Performance von Map Tour, indem Sie eine Auflösung von weniger als %RECOMMENDED_RES% angeben.",
				addPictureResolutionResize: "Bildauflösung in %RESOLUTION% ändern",
				addPictureResolutionKeep: "Ursprüngliche Auflösung von %RESOLUTION% beibehalten",
				addSelectThumbnail: "Miniaturansicht auswählen",
				addNoThumbSelected: "Keine Miniaturansicht ausgewählt",
				addThumbSelected: "Ausgewählt",
				addCameraSettingsHeader: "KAMERAEINSTELLUNGEN",
				addThumbnailHeader: "MINIATURANSICHT",
				addLabelPicUrl: "Bild",
				addLabelThumbUrl: "Miniaturansicht",
				addTextPlaceholderUrl: "Bild-URL eingeben",
				addTextPlaceholderUrl2: "ä_Enter a Youtube page URL_Ü",
				addTextPlaceholderUrl3: "Videoseiten-URL eingeben",
				addTextPlaceholderUrl4: "Videoeinbettungs-URL eingeben",
				addLabelVideo: "Video",
				addMediaVideoOther: "Andere",
				addMediaVideoHelp: "URL überprüfen und Standardminiaturansicht aufrufen",
				addMediaVideoHelpTooltip1: "Überprüfung erfolgreich",
				addMediaVideoHelpTooltip2: "Überprüfung fehlgeschlagen",
				addMediaVideoHelpTooltip4: "Option zum Einbetten des Videos und Kopieren der Video-URL im Code suchen",
				addLabelName: "Name",
				addLabelDescription: "Beschriftung",
				addTextPlaceholder: "Geben Sie etwas ein",
				addLocatePlaceholder: "Suchen Sie eine Adresse oder einen Ort",
				addPinColor: "Farbe",
				addLatitude: "Breitengrad",
				addLongitude: "Längengrad",
				addLatitudePlaceholder: "z. B. 34.056",
				addLongitudePlaceholder: "z. B. -117.195",
				addUploading: "Tour-Punkt wird hochgeladen",
				addSave: "Tour-Punkt hinzufügen",
				addMobileUploading: "Bild wird hochgeladen",
				addMobileName: "Namen eingeben",
				addMobileNameMandatory: "Fehler, geben Sie einen Namen ein.",
				addMobileError: "Leider ist hier etwas schiefgegangen",
				settingsHeader: "Anwendungseinstellungen",
				settingsTabLayout: "Layout",
				settingsTabColor: "Farben",
				settingsTabLogo: "Kopfzeile",
				settingsTabFields: "Daten",
				settingsTabExtent: "Ausdehnung",
				settingsTabZoom: "Zoomfaktor",
				settingsLayoutExplain: "Wählen Sie das gewünschte Anwendungs-Layout aus.",
				settingsLayoutProfessional: "Layout mit drei Fenstern",
				settingsLayoutModern: "Integriertes Layout",
				settingsLayoutSelected: "Ausgewähltes Layout",
				settingsLayoutSelect: "Dieses Layout auswählen",
				settingsLayoutNote: "Beachten Sie, dass für Punkte, die Videos verwenden, das Werbeplakat immer unter dem Video angezeigt wird, selbst wenn die Option deaktiviert ist.",
				settingsLayoutLocBtn: "ä_Display a locate button on supported browser_Ü",
				settingsLayoutLocBtnHelp: "Diese Funktion wird von den meisten Browsern für mobile Geräte und Desktops (Internet Explorer 9) unterstützt.",
				settingsColorExplain: "Ändern Sie das Aussehen durch Auswahl eines vordefinierten Themas, oder erstellen Sie ein eigenes.",
				settingsLabelColor: "Farben für Kopfzeilen, Inhalt und Fußzeilen",
				settingsLogoExplain: "Kopfzeilen-Logo anpassen (max. 250 x 50 Pixel).",
				settingsLogoEsri: "Esri Logo",
				settingsLogoNone: "Kein Logo",
				settingsLogoCustom: "Benutzerdefiniertes Logo",
				settingsLogoCustomPlaceholder: "Bild-URL",
				settingsLogoCustomTargetPlaceholder: "Link zum Durchklicken",
				settingsLogoSocialExplain: "Den Link rechts oben für die Kopfzeile anpassen.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Link",
				settingsLogoSocialDisabled: "Diese Funktion wurde vom Administrator deaktiviert",
				settingsDataFieldsExplain: "Namen, die Beschriftung und die Farbfelder für das Foto auswählen.",
				settingsDataFieldsError: "Die Anwendung kann die entsprechenden Namens-, Beschriftungs- oder Farbdaten nicht ermitteln. Wählen Sie die Felder aus, die hier verwendet werden sollen. Diese Einstellungen können zu einem späteren Zeitpunkt geändert werden.",
				settingsFieldsLabelName: "Name",
				settingsFieldsLabelDescription: "Beschriftung",
				settingsFieldsLabelColor: "Farbe",
				settingsFieldsReset: "Feldauswahl zurücksetzen",
				settingsExtentExplain: "Die Anfangsausdehnung von Map Tour über die nachstehende interaktive Karte festlegen.",
				settingsExtentExplainBottom: "Die definierte Ausdehnung ändert die Anfangsausdehnung Ihrer Webkarte. Beachten Sie, dass diese Ausdehnung nicht verwendet wird, wenn sie nicht den ersten Tour-Punkt umfasst. In diesem Fall wird die Tour mit Zentrierung auf den ersten Punkt geöffnet.",
				settingsExtentDateLineError: "Die Ausdehnung darf nicht über den Meridian von 180° Längengrad hinausreichen",
				settingsExtentDateLineError2: "Fehler beim Berechnen der Ausdehnung",
				settingsExtentDrawBtn: "Eine neue Ausdehnung darstellen",
				settingsExtentModifyBtn: "Ausdehnung bearbeiten",
				settingsExtentApplyBtn: "Vorschau auf Map Tour",
				settingsExtentUseMainMap: "Ausdehnung von Map Tour verwenden",
				settingsZoomExplain: "Legt den Zoom für Story-Punkte fest, die auf die Einführung folgen (optional).",
				settingsLabelZoom: "Maßstab/Ebene",
				settingsZoomFirstValue: "Keine",
				settingsFieldError: "Wählen Sie in jeder Liste ein Feld aus",
				dataTitle: "ä_ArcGIS Online hosting_Ü",
				dataExplain: "ä_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._Ü",
				dataNameLbl: "Service-Name",
				dataFolderListLbl: "Ordner",
				dataFolderListFetching: "Ordner werden abgerufen ...",
				dataRootFolder: "Stammverzeichnis",
				dataNameError: "Geben Sie einen Namen für den Feature-Service ein",
				dataFolderError: "Wählen Sie einen gültigen Ordner aus",
				dataSrcContainsInvalidChar: "Der Feature-Service-Name enthält ein oder mehrere ungültige Zeichen (-, <, >, #, %, :, \", ?, &, +, / oder \).",
				dataSrvAlreadyExistsError: "Ein Service mit diesem Namen ist bereits in der Organisation vorhanden. Wählen Sie einen anderen Namen.",
				dataBtnSave: "Service erstellen",
				dataFooterProgress: "Wird erstellt",
				dataFooterSucceed: "Erstellung erfolgreich. Wird geladen",
				dataFooterError: "Erstellung fehlgeschlagen. Versuchen Sie es erneut",
				tabError: "Überprüfen Sie alle Registerkarten auf Fehler",
				introRecordBtn: "Intro",
				introRecordActivate: "Ersten Punkt als Einführung verwenden (wird nicht im Karussell angezeigt)"
			},
			addPopupJS: {
				uploadingPicture: "Bild wird hochgeladen",
				uploadSuccess: "Upload erfolgreich",
				uploadError: "Fehler beim Hochladen des Bildes",
				uploadError2: "Fehler beim Hinzufügen des Features (ungültiges HTML-Tag)",
				notJpg: "Wählen Sie ein JPEG-Foto zum Hochladen",
				errorNoPhoto: "Wählen Sie ein Bild zum Hochladen",
				errorNoThumbnail: "Wählen Sie eine Miniaturansicht zum Hochladen",
				errorInvalidPicUrl: "Geben Sie eine gültige Bild-URL ein (beginnt mit http(s)://, endet mit jpg, png, gif oder bmp). Sie können die URL auf \'#isImage\' enden lassen, um die Regel zu umgehen.",
				errorInvalidThumbUrl: "Geben Sie eine gültige Miniaturansicht-URL für diesen Tour-Punkt ein.",
				errorInvalidVideoUrl: "Geben Sie eine gültige Video-URL ein (beginnt mit http(s)://)",
				errorNoName: "Geben Sie einen Namen für den Tour-Punkt ein",
				errorNoDescription: "Geben Sie eine Beschriftung für diesen Tour-Punkt ein",
				errorNoLocation: "Legen Sie eine Position für diesen Tour-Punkt fest"
			},
			builderJS: {
				noPendingChange: "ä_No unsaved change_Ü",
				unSavedChangeSingular: "1 nicht gespeicherte Änderung",
				unSavedChangePlural: "nicht gespeicherte Änderungen",
				shareStatus1: "ä_Tour is not saved_Ü",
				shareStatus2: "ä_Tour is shared publicly_Ü",
				shareStatus3: "ä_Tour is shared within the organization_Ü",
				shareStatus4: "ä_Tour is not shared_Ü",
				popoverDiscard: "Möchten Sie wirklich alle nicht gespeicherten Änderungen verwerfen?",
				yes: "Ja",
				no: "Nein",
				popoverLoseSave: "Durch Öffnen des Viewers gehen alle nicht gespeicherten Änderungen verloren",
				ok: "OK",
				popoverSaveWhenDone: "Denken Sie daran, nach Abschluss des Vorgangs eine Speicherung durchzuführen",
				closeWithPendingChange: "Möchten Sie die Aktion wirklich bestätigen? Ihre Änderungen gehen dabei verloren.",
				gotIt: "OK",
				savingApplication: "Anwendung wird gespeichert",
				saveSuccess: "Anwendung wurde erfolgreich gespeichert",
				saveError: "Speichern fehlgeschlagen, versuchen Sie es erneut",
				saveError2: "Fehler beim Speichern aufgrund eines ungültigen HTML-Tags in einem Namen oder einer Beschreibung",
				saveError3: "ä_The title can't be empty_Ü",
				dragColorPicker: "Verschieben<br />oder Farbe ändern",
				dataWarningExtent: "Es befinden sich Daten außerhalb der Webkartenausdehnung. Diese Daten werden nicht als Tour-Punkte verwendet. Ändern Sie die Kartenausdehnung, wenn Sie sie verwenden möchten.",
				dataWarningVisibi: "Der Map Tour-Layer ist in der aktuellen Webkartenausdehnung nicht sichtbar. Überprüfen Sie, ob der Map Tour-Layer bei einer Kartengröße von %MAPSIZE% sichtbar ist.",
				dataWarningEdit: "Webkarte bearbeiten",
				dataWarningClose: "Schließen",
				signIn: "Melden Sie sich mit einem Konto an,",
				signInTwo: "um die Anwendung zu speichern.",
				switchBM: "ä_Change Basemap_Ü"
			},
			organizePopupJS: {
				messageStart: "Sie haben ausgewählt, dass",
				messageSinglePoint: "ein Tour-Punkt",
				messageMultiPoint: "Tour-Punkte gelöscht werden soll(en)",
				messagePermantRemove: "Dabei wird/werden der/die",
				messageRecord: "Datensatz",
				messageRecordPlural: "Datensätze",
				messageConfirm: "dauerhaft aus der Datenbank gelöscht. Möchten Sie fortfahren?",
				labelButtonShow: "Anzeigen",
				labelButtonHide: "Ausblenden"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Dabei werden das Bild und die Miniaturansicht dauerhaft gelöscht",
				popoverDeleteWarningThumb: "Dabei wird die Miniaturansicht dauerhaft gelöscht",
				popoverUploadingPhoto: "Bild und Miniaturansicht werden hochgeladen",
				popoverUploadingThumbnail: "Miniaturansicht wird hochgeladen",
				popoverUploadSuccessful: "Upload erfolgreich",
				popoverUploadError: "Upload fehlgeschlagen, versuchen Sie es erneut",
				changePicAndThumb: "Bild ändern",
				changeThumb: "Miniaturansicht ändern",
				selectPic: "Medien ändern",
				selectThumb: "Miniaturansicht ändern",
				uploadPicAndThumb: "Übernehmen"
			},
			headerJS:{
				editMe: "Bearbeiten!",
				templateTitle: "Vorlagentitel festlegen",
				templateSubtitle: "Untertitel der Vorlage festlegen"
			},
			crossFaderJS:{
				setPicture: "Bildtitel festlegen",
				setCaption: "Bildbeschreibung festlegen"
			},
			importPopup: {
				title: "Importieren",
				prevBtn: "Zurück",
				nextBtn: "Weiter"
			},
			importPopupHome: {
				header: "Wo werden Ihre Bilder gespeichert?"
			},
			onlinePhotoSharingCommon: {
				pictures: "Bilder",
				videos: "Videos",
				disabled: "Diese Funktion wurde vom Administrator deaktiviert",
				disabledPortal: "Dieses Feature ist in Portal for ArcGIS deaktiviert",
				header1: "ä_Your pictures must be shared publicly._Ü",
				header2: "ä_The import will be limited to the first %NB1% %MEDIA%._Ü",
				emptyDataset: "Fehler, keine Bilder gefunden",
				footerImport: "Importieren",
				selectAlbum: "Öffentliches Album auswählen",
				selectAlbum2: "Album auswählen",
				pleaseChoose: "Treffen Sie eine Auswahl",
				userLookup: "Suchen",
				userLookingup: "Wird gesucht",
				csv: "In CSV referenziert",
				advanced: "Erweiterte Optionen",
				advancedScratchLbl: "ä_Start a new Tour_Ü",
				advancedScratchTip: "ä_Create an empty Tour that you will be able populate manually using a wizard._Ü",
				advancedCSVLbl: "ä_Import Tour data from a CSV file_Ü",
				advancedCSVTip: "ä_Import your Tour content from a CSV file._Ü",
				advancedCommonTip: "ä_It requires that your images and videos are already online._Ü",
				select: "Auswahl treffen",
				locUse: "ä_Use pictures geolocation_Ü",
				locExplain: "ä_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._Ü",
				locExplain2: "ä_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._Ü"
			},
			viewFlickr: {
				title: "ä_Flickr import_Ü",
				header: "ä_Enter your Flickr user name and select a Photo Set or a Tag to be imported._Ü",
				userInputLbl: "Benutzername eingeben",
				signInMsg2: "Benutzer nicht gefunden",
				selectSet: "Fotosatz auswählen",
				selectTag: "oder Tag auswählen",
				footerImportTag: "Ausgewählten Tag importieren",
				footerImportSet: "Ausgewählten Satz importieren"
			},
			viewFacebook: {
				title: "ä_Facebook import_Ü",
				header: "ä_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._Ü",
				leftHeader: "Facebook-Benutzer",
				rightHeader: "Facebook-Seite",
				pageExplain: "Eine Facebook-Seite entspricht einer öffentlichen Marke/einem Produkt oder einer prominenten Person wie <b>esrigis</b>. Den Seitennamen können sie dem Text nach dem ersten Schrägstrich (\'/\') in der Seiten-URL entnehmen.",
				pageInputLbl: "Seitenname eingeben",
				lookupMsgError: "Seite nicht gefunden"
			},
			viewPicasa: {
				title: "ä_Picasa/Google+ import_Ü",
				header: "ä_Enter your email address or the ID of your Picasa or Google+ account._Ü",
				userInputLbl: "E-Mail-Adresse oder ID eingeben",
				signInMsg2: "Konto nicht gefunden",
				howToFind: "ä_How to find a Picasa or Google+ account ID_Ü",
				howToFind2: "Kopieren Sie die Ziffern zwischen dem ersten und zweiten Schrägstrich (\'/\') einer Picasa- oder G+-Seite"
			},
			viewCSV: {
				title: "ä_CSV import_Ü",
				uploadBtn: "CSV-Datei auswählen oder ablegen",
				resultHeaderEmpty: "Die CSV ist leer",
				resultHeaderSuccess: "%NB_POINTS% Punkte erfolgreich geladen",
				resultHasBeenLimited: "Es wurden nur die ersten %VAL1% Punkte von %VAL2% importiert, um den Höchstwert von %VAL3% Punkten pro Tour nicht zu überschreiten",
				browserSupport: "Ihr Browser wird nicht unterstützt. Um eine CSV zu verwenden, müssen Sie <a href='http://browsehappy.com/' target='_blank'>Ihren Browser aktualisieren</a> oder den Webkarten-Viewer von ArcGIS.com verwenden (siehe Hilfe).",
				errorLatLng: "Die Längen- und Breitengradfelder wurden nicht gefunden. Mögliche Werte sind <i>%LAT%</i> für den Breitengrad und <i>%LONG%</i> für den Längengrad.",
				errorFieldsExplain: "Der Ladevorgang ist fehlgeschlagen, da die folgenden erforderlichen Felder nicht gefunden wurden",
				errorFieldsName: "Mögliche Werte für <b>Name</b> sind: %VAL%",
				errorFieldsDesc: "Mögliche Werte für <b>Beschreibung</b> sind: %VAL%",
				errorFieldsUrl: "Mögliche Werte für <b>Bild-URL</b> sind: %VAL%",
				errorFieldsThumb: "Mögliche Werte für <b>Miniaturansicht-URL</b> sind: %VAL%",
				errorFields2Explain: "Der Ladevorgang ist fehlgeschlagen, da die CSV nicht dieselben Attribute verwendet wie der Layer für die folgenden Attribute",
				errorFields2Name: "<b>Name:</b> Verwenden Sie %VAL1% anstelle von %VAL2%",
				errorFields2Desc: "<b>Beschreibung:</b> Verwenden Sie %VAL1% anstelle von %VAL2%",
				errorFields2Url: "<b>Bild-URL:</b> Verwenden Sie %VAL1% anstelle von %VAL2%",
				errorFields2Thumb: "<b>Miniaturansicht-URL:</b> Verwenden Sie %VAL1% anstelle von %VAL2%",
				resultFieldsAll: "Alle Attribute wurden importiert",
				resultFieldsNotAll: "Die folgenden Attribute wurden nicht importiert, da sie nicht im Karten-Layer vorhanden sind",
				resultFieldsNotAll2: "Die folgenden Attribute wurden importiert",
				footerNextBtnResult: "In Webkarte importieren",
				footerProgress: "Import wird ausgeführt",
				footerSucceed: "Import erfolgreich. Wird geladen"
			},
			viewYoutube: {
				title: "ä_Youtube import_Ü",
				header: "ä_Enter a YouTube user name to find publicly shared videos._Ü",
				pageInputLbl: "ä_Enter a Youtube user name_Ü",
				lookupMsgError: "Benutzer nicht gefunden",
				howToFind: "ä_How to find a Youtube user name_Ü",
				howToFind2: "Benutzername wird unter Videos angezeigt",
				found: "Gefunden",
				noData: "Keine öffentlichen Videos gefunden"
			},
			viewGeoTag: {
				title: "ä_Select and locate your images/videos_Ü",
				header: "Klicken oder tippen Sie auf die Bilder, die importiert werden sollen, um sie zu verorten.",
				headerMore: "ä_Why aren't my images/videos geolocated?_Ü",
				headerExplain: "ä_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._Ü",
				leftPanelTab1: "Zur Verortung",
				leftPanelTab2: "Verortet",
				clickOrTap: "Klicken oder tippen Sie zur Verortung auf die Karte",
				clearLoc: "ä_Clear locations_Ü",
				clickDrop: "Nicht importieren",
				footerImport: "Importieren",
				footerProgress: "Import wird ausgeführt",
				footerSucceed: "Import erfolgreich. Wird geladen...",
				loading: "Wird geladen",
				error: "ä_Pictures geolocation import failed, geolocations have been ignored._Ü"
			},
			initPopup: {
				title: "ä_Welcome to the Map Tour Builder_Ü",
				prevBtn: "Zurück",
				nextBtn: "Weiter"
			},
			initPopupHome: {
				header1: "ä_Where are your images or videos?_Ü",
				header2: "ä_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._Ü",
				title1: "ä_They are already online_Ü",
				title2: "ä_I need to upload my images_Ü",
				hostedFSTooltip: "ä_Use ArcGIS Online to host your images (doesn't support videos)._Ü",
				hostedFsNA: "ä_Only available for ArcGIS for Organizations Publisher and Administrator users_Ü",
				footer1: "Vergessen Sie nach der Fertigstellung nicht, Ihre Map Tour über die Seite der Anwendungselemente für Ihre Zielgruppe freizugeben.",
				footer3: "CSV-Vorlage herunterladen",
				footer4: "\"Speichern unter\", falls kein Download möglich",
				footer4bis: "ä_Use right click and \"Save as\" if download doesn't start_Ü",
				footer5: "ä_Learn more_Ü",
				footerProgress: "Wird erstellt",
				footerSucceed: "Erstellung erfolgreich. Wird geladen..."
			},
			helpPopup: {
				title: "ä_Help_Ü",
				close: "Schließen",
				tab1: {
					title: "Einführung",
					div1: "ä_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._Ü",
					div2: "ä_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_Ü",
					div4: "ä_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._Ü",
					div42: "ä_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._Ü",
					div5: "ä_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._Ü"
				},
				tab2: {
					title: "Daten",
					div1: "Die wichtigste Entscheidung bei der Erstellung einer Map Tour betrifft die Frage, wo die Bilder gespeichert werden. Eine Map Tour kann in den großen Fotofreigabe-Services, auf einem Webserver oder als Anlage eines Feature-Service gespeicherte Bilder verwenden.",
					div1a: "Dem letzten Abschnitt dieses Registers können Sie Näheres zu unterstützten Bildformaten und Videos entnehmen.",
					div2: "Mit dem interaktiven Builder stehen Ihnen zwei Optionen für die Verwendung der Bilder in der Map Tour zur Verfügung:",
					div3: "<ul><li>Sie können <b>Fotos verwenden, die bereits online sind</b>, etwa auf einer Fotofreigabe-Website wie Flickr oder auf Ihrer eigenen Website gespeicherte Fotos. Diese Bilder werden in der Map Tour über die URLs referenziert.</li><li>Sie können auch <b>Fotos von Ihrem Computer</b> direkt in die Map Tour hochladen. Diese Upload-Funktion setzt voraus, dass Sie eine ArcGIS Online-Subskription haben sowie über Publisher- oder Administratorberechtigungen verfügen, da bei dieser Option automatisch ein gehosteter Feature-Service für Sie erstellt wird, in dem die Fotos als Anlagen gespeichert werden.</li></ul>",
					div4: "Es gibt hauptsächlich folgende Anwendungsfälle:",
					div4b: "<b>Ihre Fotos werden noch nicht gehostet</b> und Sie verfügen über eine ArcGIS Online-Subskription: Die beste Option in diesem Fall ist die Verwendung eines gehosteten Feature-Service. Wie bei öffentlichen Fotofreigabe-Services werden Ihre Bilder optimiert, damit sie schnell geladen werden können, und Sie haben Zugriff auf alle Administrations- und Datenmanagementfunktionen der ArcGIS-Plattform.",
					div5: "<b>Sie sind kein Mitglied einer Organisation</b>: Sie müssen Ihre Bilder zuerst auf eine Fotofreigabe-Website oder einen eigenen Webserver hochladen. Danach unterstützt Sie der Builder bei der Verwendung der Bilder, die weiter am ursprünglichen Speicherort gehostet werden.",
					div6: "<b>Sie möchten einen vorhandenen Feature-Service verwenden</b>, in dem Ihre Bilder als Anlagen gespeichert werden oder auf externe Bilder verwiesen wird: Lesen Sie die ausführlichen Informationen im Abschnitt unten.",
					div7: "<b>Sie verwenden eine frühere Version</b> der Map Tour-Vorlage und verfügen bereits über eine CSV-Datei mit Verweis auf Ihre Bilder und Miniaturansichten: Sie können diese Vorlage importieren und die Daten optimieren. Der Builder unterstützt nur CSV-Dateien mit Verwendung von Längen-/Breitengradfeldern; eine adressbasierte CSV-Datei kann weiter durch Ihre Webkarte verwendet werden (siehe Abschnitt unten).",
					div8: "Importieren aus Online-Fotofreigabe-Services",
					div9: "Beim Importvorgang wird auf bereits gehostete Bilder verwiesen, indem die URLs in einer Webkarten-Feature-Sammlung gespeichert werden. Die Bilder werden nicht in ArcGIS Online gespeichert. Wenn auf die gehosteten Bilder nicht zugegriffen werden kann, sind sie nicht in der Map Tour verfügbar, stattdessen wird \"Bild nicht verfügbar\" angezeigt. Abhängig vom Service-Provider werden Name, Beschreibung und Position der Bilder nicht in die Map Tour importiert. Diese Attribute werden in der Webkarte gespeichert, Änderungen in den Online-Services werden nicht in die Map Tour übernommen.",
					div10: "Speichern der Bilder auf einem Webserver",
					div11: "Wenn Sie die Bilder selbst hosten, müssen Sie manuell Miniaturansichten der Bilder erstellen. Wenn für die Miniaturansichten die Bilder in voller Auflösung verwendet werden, wirkt sich dies negativ auf die Performance aus. Aus diesem Grund empfiehlt es sich, einen Online-Fotofreigabe-Service oder einen Feature-Service zu verwenden, der dies für Sie übernimmt.",
					div12: "Verwenden eines vorhandenen Feature-Service oder Shapefile",
					div13: "Als Map Tour-Datenquelle kann jeder Punkt-Feature-Service oder jedes Shapefile verwendet werden. Sie müssen den Feature-Service oder das Shapefile nur durch den arcGIS.com Map Viewer als Layer zu Ihrer Webkarte hinzufügen. Wenn die erwarteten Attribute von der Anwendung im Layer gefunden werden, sind alle Builder-Funktionalitäten verfügbar.",
					div14: "ä_The possible values for fields name are (case insensitive):_Ü",
					div151: "Name",
					div152: "Beschreibung",
					div153: "Bild",
					div154: "Miniaturansicht",
					div155: "ä_Color_Ü ",
					div16: "ä_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._Ü",
					div162: "Bei Nutzung eines Feature-Service, der die Bilder in Form von Anlagen speichert,<b>werden lediglich die Features mit zwei Anlagen verwendet</b>. Die erste Anlage definiert das Hauptbild, der zweite die Miniaturansicht.",
					div17: "Die Bild- und Miniaturansichtsfelder sind für Feature-Services ohne Anlagen Pflichtfelder und für Feature-Services mit Anlagen optional (jedoch sehr empfehlenswert). Wenn Anlagen für den Service aktiviert sind, können Sie Bilder mit dem Map Tour Builder als Anlagen hochladen. Andernfalls können Sie nur die Bild- und Miniaturansicht-URL bearbeiten.",
					div172: "Sofern vorhanden, werden die Felder Bild und Miniaturansicht stets verwendet, und die Anlagen des Feature-Service werden nicht abgefragt.",
					div173: "Beispiele für CSV-Dateien und Shapefiles können heruntergeladen werden unter",
					div18: "Erstellen eines gehosteten Feature-Service aus einer CSV-Datei oder einem Shapefile",
					div19: "Bei der Erstellung eines gehosteten Feature-Service aus einer CSV-Datei oder einem Shapefile sind Anlagen nicht standardmäßig aktiviert. Um sie zu aktivieren, öffnen Sie die Feature-Service-Seite und klicken Sie auf den kleinen Pfeil im Layer-Abschnitt, damit die Option angezeigt wird. Die Bilder und Miniaturansichten, auf die Sie durch Attribute verwiesen haben, werden in Map Tour weiter verwendet. Wenn Sie Ihre Bilder optional als Feature-Service-Anlagen hochladen möchten, ist dies über zwei Schaltflächen im Bildbereich möglich (\"Bild ändern\" und \"Miniaturansicht ändern\").",
					div20: "Unterstützte Bildformate und Videos",
					div21: "Folgende Bildformate werden unterstützt: <b>.jpg, .jpeg, .png, .gif und .bmp</b>. Sollten Ihre Medien keine dieser Dateierweiterungen aufweisen, werden sie von Map Tour als Video behandelt, es sei denn, Sie verwenden einen Feature-Service (siehe unten).",
					div22: "Da die Map Tour-Vorlage über keine Videoabspielfunktion verfügt, müssen Sie auf den externen Videoplayer Ihres bevorzugten Video-Hosting-Service zurückgreifen (betten Sie das Video mit der entsprechenden Option ein und kopieren Sie die vorhandene URL in den angegebenen Code). Wenn Sie das Video selbst hosten möchten, können Sie eine HTML-Seite erstellen, die einen Videoplayer wie <a href='http://www.videojs.com/'>Video.js</a> enthält.",
					div23: "Der interaktive Builder bietet keine Dialogfunktion zum Einbetten eines Videos bei Verwendung von Feature-Services mit Anlagen an, aber Sie können die Daten einfach außerhalb des interaktiven Builders bearbeiten. Bearbeiten Sie im arcgis.com Map Viewer die Bildfelder so, dass diese auf ein externes Video verweisen, fügen Sie einen speziellen Parameter (#isVideo) an das Ende Ihrer URL an und schon werden Ihre Medien als Video behandelt.",
					div24: "Beachten Sie, dass Sie weiterhin zwei gültige Anlagen mit Bildern benötigen; andernfalls wird der Punkt nicht verwendet. Wenn Anlagen von Feature-Services ohne die Felder für Bild und Miniaturansicht verwendet werden, können keine Videos integriert werden."
				},
				tab3: {
					title: "Anpassung",
					div1: "Der Builder enthält mehrere Anpassungsoptionen, auf die durch die Schaltfläche EINSTELLUNGEN im oberen Bereich zugegriffen werden kann. Wenn Sie nicht die erwartete Option finden, steht auch eine herunterladbare Version zur Verfügung, die Sie auf Ihrem Webserver bereitstellen und an Ihre Anforderungen anpassen können.",
					div2: "Wir empfehlen, mit Ausnahme der im Folgenden genannten Situationen die gehostete Version zu verwenden:",
					div3: "<li>Eine gewünschte Anpassung für die Benutzeroberfläche ist nicht verfügbar, etwa die Verwendung eines Kopfzeilen-Hintergrundbildes.</li><li>Sie sind Entwickler und möchten die Anwendung erweitern.</li>",
					div4: "Die herunterladbare Version kann durch eine Webkartenkennung oder eine Web Mapping-Anwendungskennung konfiguriert werden. Es gibt hauptsächlich folgende Anwendungsfälle:",
					div41: "Sie erstellen unter Verwendung des interaktiven Builders Ihre Map Tour in der gehosteten Umgebung und konfigurieren die Vorlage mit der Kennung der Webkartenanwendung. Ihre mit dem interaktiven Builder definierten Einstellungen werden angewendet.",
					div42: "ä_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._Ü",
					div43: "Beachten Sie, dass der interaktive Builder in der herunterladbaren Version verfügbar ist, allerdings ist in manchen Browsern wie dem Internet Explorer vor Version 10 mit technischen Einschränkungen zu rechnen.",
					div5: "ä_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._Ü"
				},
				tab4: {
					title: "Tipps",
					div0: "Unterstützte Browser",
					div0a: "Der Map Tour Viewer wird ab IE8+ unterstützt. Der interaktive Builder wird ab IE9+ unterstützt. Wir testen ihn in den wichtigsten Browsern, aber sollten Sie auf Schwierigkeiten stoßen, empfehlen wir Ihnen die Verwendung von Chrome.",
					div0b: "Bitte informieren Sie uns, wenn Probleme auftauchen sollten. Zwischenzeitlich können Sie die Interaktionen mit der Builder-Oberfläche reduzieren, indem Sie Ihre Map Tour mithilfe der CSV-Vorlage erstellen.",
					div1: "Bilder",
					div2: "ä_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._Ü",
					div2a: "ä_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._Ü",
					div3: "Formatieren des Beschriftungstexts mit HTML-Tags",
					div4: "Der Beschriftungstext kann HTML-Tags zur Definition von Formatierung und Links enthalten. Mit dem folgenden Code wird z.B. ein gelber Link hinzugefügt:",
					div4a: "ä_Write a good subtitle for your tour_Ü",
					div4b: "ä_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._Ü",
					div5: "Unterstützende Layer",
					div6: "Sie können der Map Tour zusätzliche unterstützende Layer hinzufügen. Diese Layer können andere geographische Features enthalten, die Sie neben den Punkten der Map Tour auf der Karte anzeigen möchten, z. B. ein Untersuchungsgebiet, eine Fußgänger- oder Fahrroute zwischen den Tourpunkten usw. Die Map Tour-Vorlage zeigt diese zusätzlichen unterstützenden Layer mit der in der Webkarte angegebenen Symbologie an, allerdings ohne Pop-up-Fenster.",
					div7: "Halten Sie die Tour kurz und interessant",
					div8: "Eine Tour kann höchstens 99 Punkte enthalten. Die meisten Map Tours sind natürlich weit kürzer. Erwarten Sie nicht, dass Ihre Zielgruppe sich für zu viele Tourpunkte interessiert. Dass Sie selbst Ihr Thema faszinierend finden, bedeutet nicht, dass andere dies ähnlich empfinden müssen!",
					div9: "Weitere Informationen finden Sie in der <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>ausführlichen Anleitung</a>.",
					div10: "Einbettungsmodus",
					div11: "Wenn Sie die Vorlage auf einer anderen Website über ein iframe einbetten wollen, dann können Sie die Kopfzeile entfernen, indem Sie der URL am Ende \"&embed\" anfügen. Dieser Modus lässt sich auch in der herunterladbaren Version über die Konfigurationsdatei einstellen.",
					div12: "ä_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._Ü" 
				},
				tab5: {
					title: "Veröffentlichung",
					div1: "ä_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._Ü",
					div2a: "ä_Sharing the Tour through the builder_Ü",
					div2b: "ä_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._Ü",
					div2c: "ä_Sharing the Tour through ArcGIS Online_Ü",
					div2d: "ä_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._Ü",
					div3t: "ä_Feature Service security_Ü",
					div3a: "ä_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._Ü",
					div3t2: "ä_Before sharing your Tour with your audience_Ü",
					div3: "ä_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._Ü",
					div4: "ä_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._Ü",
					div5a: "ä_Recommendation for search_Ü",
					div5b: "ä_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._Ü"
				}
			},
			share: {
				firstSaveTitle: "ä_Tour successfully saved_Ü",
				firstSaveHeader: "ä_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._Ü",
				firstSaveA1: "ä_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_Ü",
				firstSaveA1bis: "ä_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._Ü",
				firstSaveQ2: "ä_Is my Tour shared?_Ü",
				firstSaveA2: "ä_Currently your Tour is not shared. To share it, use the SHARE button._Ü",
				shareTitle: "ä_Share your Tour_Ü",
				sharePrivateHeader: "ä_Your Tour is not shared, would you like to share it?_Ü",
				sharePrivateBtn1: "ä_Share publicly_Ü",
				sharePrivateBtn2: "ä_Share with my Organization_Ü",
				sharePrivateProgress: "ä_Sharing in progress..._Ü",
				sharePrivateErr: "ä_Sharing failed, try again or_Ü",
				sharePrivateOk: "ä_Sharing updated successfully, loading..._Ü",
				sharePreviewAsUser: "ä_Preview_Ü",
				shareHeader1: "ä_Your Tour is <strong>publicly accessible</strong>._Ü",
				shareHeader2: "ä_Your Tour is accessible by your organization members (login is required)._Ü",
				shareLinkHeader: "ä_Share the Tour with your audience_Ü",
				shareLinkOpen: "ä_OPEN_Ü",
				shareQ1Opt1: "ä_How do I keep the Tour private?_Ü",
				shareQ1Opt2: "ä_How do I keep the Tour private or share it publicly?_Ü",
				shareA1: "ä_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._Ü",
				shareA1bis: "ä_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._Ü",
				shareQ2: "ä_How do I edit the Tour later?_Ü",
				shareQ2bis: "ä_How do I get back to the authoring interface?_Ü",
				shareA2div1: "ä_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._Ü",
				shareA2div2: "ä_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_Ü",				
				shareQ3: "ä_Where is the data stored?_Ü",
				shareA3: "ä_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._Ü"
			}
        }
    })
);
