define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Mappa Web",
				lblLocation: "Posizione",
				lblContent: "Contenuti",
				lblPopup: "Popup",
				lblControls: "Extra",
				lblOverview: "Mappa d\'insieme",
				lblLegend: "Legenda",
				loadingTitle: "Caricamento titolo in corso",
				entry: "Voce",
				entries: "Voci",
				section: "Sezione",
				sections: "Sezioni",
				and: "e",
				action: "Azione nella sezione",
				actions: "Azione nelle sezioni",
				originalWebmap: "Mappa Web utilizzata per pubblicare %TPL_NAME%",
				browseMaps: "Cerca mappe",
				current: "Mappa Web corrente",
				select: "Seleziona mappa Web",
				newMap: "Nuova mappa Web selezionata",
				webmapDefault: "Predefinite mappa Web",
				customCfg: "Configurazione personalizzata",
				tooltipLocation: "Definisce la posizione visualizzata da questa mappa.",
				tooltipContent: "Definisce i layer visibili.",
				tooltipPopup: "Consente di scegliere un popup da aprire quando viene visualizzata questa mappa.",
				tooltipOverview: "Consente di visualizzare una piccola mappa d\'insieme assieme alla mappa principale.",
				tooltipLegend: "Consente di visualizzare la legenda della mappa, utile quando la mappa contiene numerosi layer e simboli.",
				mapCfgInvite: "Utilizzare questi controlli per configurare la mappa",
				lblLocationAlt: "Ereditata dalla prima mappa",
				tooltipLocationAlt: "La posizione di questa mappa viene sincronizzata in base alla prima mappa della serie. Per modificare questo funzionamento per la serie, scegliere Impostazioni > Opzioni mappa."
			},
			configure: {
				btnReset: "Reimposta",
				btnCancel: "Annulla",
				tocTitle: "Contenuti mappa",
				tocExplain: "Consente di selezionare i layer che verranno visualizzati.",
				tocNoData: "Non è possibile configurare nessun layer.",
				tocSave: "Salva contenuti mappa",
				extentTitle: "Posizione mappa",
				extentExplain: "Consente di applicare pan e zoom alla mappa per definirne l\'aspetto per i lettori.",
				extentSave: "Salva posizione mappa",
				popupTitle: "Popup mappa",
				popupExplain: "Fare clic su una feature per aprire il popup da visualizzare.",
				popupSave: "Salva la configurazione del popup",
				hintNavigation: "Navigazione mappa disabilitata."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "La mia organizzazione",
					onlineLabel: "ArcGIS Online",
					contentLabel: "I miei contenuti",
					favoritesLabel: "I miei preferiti"
				},
				title: "Seleziona mappa Web",
				searchTitle: "Cerca",
				ok: "OK",
				cancel: "Annulla",
				placeholder: "Immettere termine di ricerca o ID mappa Web..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
