define(
   ({
    map: {
      error: "試_Unable to create map_驗"
    },
    onlineStatus: {
      offline: "試_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_驗.",
      reconnecting: "試_Reconnecting&hellip;_驗",
      pending: "試_${total} pending edit(s) will be submitted when a network connection is re-established_驗."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "試_My Organization_驗",
          onlineLabel: "試_ArcGIS Online_驗",
          contentLabel: "試_My Content_驗",
          favoritesLabel: "試_My Favorites_驗"
        },
        title: "試_Select Web Map_驗",
        searchTitle: "試_Search_驗",
        ok: "試_Ok_驗",
        cancel: "試_Cancel_驗",
        placeholder: "試_Enter search term_驗"
      },
      groupdlg: {
        items: {
          organizationLabel: "試_My Organization_驗",
          onlineLabel: "試_ArcGIS Online_驗",
          contentLabel: "試_My Content_驗",
          favoritesLabel: "試_My Favorites_驗"
        },
        title: "試_Select Group_驗",
        searchTitle: "試_Search_驗",
        ok: "試_Ok_驗",
        cancel: "試_Cancel_驗",
        placeholder: "試_Enter search term_驗"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "試_Here is a link to a GeoForm_驗"
      }
    },
    user: {
      mgrs: "試_MGRS_驗",
      usng: "試_USNG_驗",
      utm: "試_UTM_驗",
      utm_northing: "試_Northing_驗",
      utm_easting: "試_Easting_驗",
      utm_zone_number: "試_Zone Number_驗",
      selectLayerTabText: "試_${formSection} Select Form_驗",
      geoFormGeneralTabText: "試_${formSection} Enter Information_驗",
      locationInformationText: "試_${formSection} Select Location_驗",
      submitInformationText: "試_${formSection} Complete Form_驗",
      submitInstructions: "試_Add this information to the map_驗.",
      myLocationText: "試_Current Location_驗",
      locationDescriptionForMoreThanOneOption: "試_Specify the location for this entry by clicking/tapping the map or by using one of the following options_驗.",
      locationDescriptionForOneOption: "試_Specify the location for this entry by clicking/tapping the map or by using the following option_驗.",
      locationDescriptionForNoOption: "試_Specify the location for this entry by clicking/tapping the map_驗.",
      addressText: "試_Search_驗",
      geographic: "試_Lat/Lon_驗",
      locationTabText: "試_Location_驗",
      locationPopupTitle: "試_Location_驗",
      submitButtonText: "試_Submit Entry_驗",
      submitButtonTextLoading: "試_Submitting&hellip;_驗",
      formValidationMessageAlertText: "試_The following fields are required_驗:",
      selectLocation: "試_Please select a location for your submission_驗.",
      emptylatitudeAlertMessage: "試_Please enter a ${openLink}latitude${closeLink} coordinate_驗.",
      emptylongitudeAlertMessage: "試_Please enter a ${openLink}longitude${closeLink} coordinate_驗.",
      shareUserTitleMessage: "試_Thank you for your contribution_驗!",
      entrySubmitted: "試_Your entry has been submitted to the map_驗.",
      shareThisForm: "試_Share This Form_驗",
      shareUserTextMessage: "試_Tell others to contribute using the following options_驗.",
      addAttachmentFailedMessage: "試_Unable to add attachment to layer_驗",
      addFeatureFailedMessage: "試_Unable to add feature to layer_驗",
      noLayerConfiguredMessage: "試_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_驗.",
      placeholderLatitude: "試_Latitude (Y)_驗",
      placeholderLongitude: "試_Longitude (X)_驗",
      latitude: "試_Latitude_驗",
      longitude: "試_Longitude_驗",
      findMyLocation: "試_Locate Me_驗",
      finding: "試_Locating&hellip;_驗",
      backToTop: "試_Back to top_驗",
      addressSearchText: "試_Your submission will appear here. You can drag the pin to correct the location_驗.",
      shareModalFormText: "試_Form Link_驗",
      close: "試_Close_驗",
      locationNotFound: "試_Location could not be found_驗.",
      setLocation: "試_Set Location_驗",
      find: "試_Find address or place_驗",
      attachment: "試_Attachment_驗",
      toggleDropdown: "試_Toggle Dropdown_驗",
      invalidString: "試_Please enter valid value_驗.",
      invalidSmallNumber: "試_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_驗.",
      invalidNumber: "試_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_驗.",
      invalidFloat: "試_Please enter valid ${openStrong}floating point${closeStrong} value_驗.",
      invalidDouble: "試_Please enter valid ${openStrong}double${closeStrong} value_驗.",
      invalidLatLong: "試_Please enter valid latitude and longitude coordinates_驗.",
      invalidUTM: "試_Please enter valid UTM coordinates_驗.",
      invalidUSNG: "試_Please enter valid USNG coordinates_驗.",
      invalidMGRS: "試_Please enter valid MGRS coordinates_驗.",
      geoformTitleText: "試_GeoForm_驗",
      domainDefaultText: "試_Select&hellip;_驗",
      applyEditsFailedMessage: "試_Sorry your entry cannot be submitted. Please try again_驗.",
      requiredFields: "試_There are some errors. Please correct them below_驗.",
      requiredField: "試_(required)_驗",
      error: "試_Error_驗",
      textRangeHintMessage: "試_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_驗",
      dateRangeHintMessage: "試_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_驗",
      remainingCharactersHintMessage: "試_${value} characters remaining_驗",
      mapFullScreen: "試_Full Screen_驗",
      mapRestore: "試_Restore_驗",
      filterSelectEmptyText: "試_Select_驗",
      invalidLayerMessage: "試_Form layer does not exist. Please configure the application and set the layer_驗.",
      selectedLayerText: "試_All_驗",
      fileUploadStatus: "試_File Upload Status_驗",
      uploadingBadge: "試_&nbsp;Uploading&hellip;_驗",
      successBadge: "試_&nbsp;Uploaded_驗",
      retryBadge: "試_Retry_驗",
      errorBadge: "試_Error uploading&nbsp;&nbsp;&nbsp;_驗",
      fileTooLargeError: "試_File too large to attach_驗",
      exceededFileCountError: "試_Exceeded maximum no. of attachments allowed_驗",
      selectFileTitle: "試_Select a file_驗",
      btnViewSubmissions: "試_View Submissions_驗",
      dateFormat: "試_MM/DD/YYYY h:mm a_驗"
    },
    builder: {
      invalidUser: "試_Sorry, you don't have permission to view this item_驗",
      invalidWebmapSelectionAlert: "試_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_驗.",
      invalidWebmapSelectionAlert2: "試_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_驗",
      selectFieldsText: "試_Select Form Fields_驗",
      selectThemeText: "試_Select Form Theme_驗",
      webmapText: "試_Webmap_驗",
      layerText: "試_Layer_驗",
      detailsText: "試_Details_驗",
      fieldsText: "試_Fields_驗",
      styleText: "試_Style_驗",
      optionText: "試_Options_驗",
      previewText: "試_Preview_驗",
      publishText: "試_Publish_驗",
      optionsApplicationText: "試_Options_驗",
      titleText: "試_Builder_驗",
      descriptionText: "試_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_驗.",
      btnPreviousText: "試_Previous_驗",
      btnNextText: "試_Next_驗",
      webmapTabTitleText: "試_Select a Webmap_驗",
      viewWebmap: "試_View webmap_驗",
      webmapDetailsText: "試_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_驗",
      btnSelectWebmapText: "試_Choose Webmap_驗",
      btnSelectWebmapTextLoading: "試_Loading&hellip;_驗",
      layerTabTitleText: "試_Select Editable Layer_驗",
      selectLayerLabelText: "試_Layer_驗",
      selectLayerDefaultOptionText: "試_Select Layer_驗",
      defaultBasemap: "試_Basemap Toggle_驗",
      secondaryBasemap: "試_Default Basemap_驗",
      detailsTabTitleText: "試_Form Details_驗",
      detailTitleLabelText: "試_Title_驗",
      detailLogoLabelText: "試_Logo Image_驗",
      descriptionLabelText: "試_Form Instructions & Details_驗",
      fieldDescriptionLabelText: "試_Help Text (optional)_驗",
      fieldTabFieldHeaderText: "試_Field_驗",
      fieldTabLabelHeaderText: "試_Label_驗",
      fieldTabDisplayTypeHeaderText: "試_Display As_驗",
      fieldTabOrderColumnText: "試_Order_驗",
      fieldTabVisibleColumnText: "試_Enabled_驗",
      displayFieldText: "試_Display Field_驗",
      selectMenuOption: "試_Select Menu_驗",
      selectRadioOption: "試_Radio Button_驗",
      selectTextOption: "試_Text_驗",
      selectDateOption: "試_Date Picker_驗",
      selectRangeOption: "試_Touch-Spinner_驗",
      selectCheckboxOption: "試_Checkbox_驗",
      selectMailOption: "試_Email_驗",
      selectUrlOption: "試_URL_驗",
      selectTextAreaOption: "試_Text Area_驗",
      previewApplicationText: "試_Preview Application_驗",
      saveApplicationText: "試_Save Application_驗",
      saveText: "試_Save_驗",
      toggleNavigationText: "試_Toggle navigation_驗",
      formPlaceholderText: "試_My Form_驗",
      shareBuilderInProgressTitleMessage: "試_Publishing GeoForm_驗",
      shareBuilderProgressBarMessage: "試_Please Wait&hellip;_驗",
      shareBuilderTitleMessage: "試_Success! Item saved_驗",
      shareBuilderTextMessage: "試_You can start collecting information by sharing with others_驗",
      shareModalFormText: "試_Form Link_驗",
      shareBuilderSuccess: "試_Your GeoForm has been updated & published_驗!",
      geoformTitleText: "試_Geo Form_驗",
      layerTabText: "試_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_驗.",
      detailsTabText: "試_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_驗.",
      fieldsTabText: "試_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_驗.",
      styleTabText: "試_Style your GeoForm using the themes below based on your preference_驗.",
      publishTabText: "試_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_驗.",
      headerSizeLabel: "試_Header Size_驗",
      smallHeader: "試_Use Small Header_驗",
      bigHeader: "試_Use Large Header_驗",
      pushpinText: "試_Push pin_驗",
      doneButtonText: "試_Save and Exit_驗",
      fieldTabPlaceHolderHeaderText: "試_Hint (optional)_驗",
      enableAttachmentLabelText: "試_${openStrong}Enable Attachments${closeStrong}_驗",
      enableAttachmentLabelHint: "試_You can enable/disable the attachments here_驗",
      attachmentIsRequiredLabelText: "試_${openStrong}Attachment Required${closeStrong}_驗",
      attachmentIsRequiredLabelHint: "試_If necessary, users can be required to enter an attachment_驗.",
      attachmentLabelText: "試_Attachment Button Label_驗",
      attachmentLabelHint: "試_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_驗",
      attachmentDescription: "試_Attachment Description_驗",
      attachmentHint: "試_If necessary, you can provide additional attachment instructions here_驗.",
      jumbotronDescription: "試_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_驗",
      shareGeoformText: "試_Share Geoform_驗",
      shareDescription: "試_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_驗.",
      defaultMapExtent: "試_Default Map Extent_驗",
      defaultMapExtentDescription: "試_The map will reset to the default extent in your web map after submission - this can be disabled at any time_驗.",
      pushpinOptionsDescription: "試_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_驗",
      selectLocationText: "試_Select Location By_驗",
      myLocationText: "試_My Location_驗",
      searchText: "試_Search_驗",
      coordinatesText: "試_Latitude & Longitude Coordinates_驗",
      usng: "試_USNG Coordinates_驗",
      mgrs: "試_MGRS Coordinates_驗",
      utm: "試_UTM Coordinates_驗",
      selectLocationSDescription: "試_Allow users to select a location using these methods_驗.",
      dragTooltipText: "試_Drag the field where you want it to appear_驗",
      showHideLayerText: "試_Show Layer_驗",
      showHideLayerHelpText: "試_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_驗.",
      labelHelpMessage: "試_Label_驗",
      placeHolderHintMessage: "試_Hint Text_驗",
      placeHolderHelpMessage: "試_Help Text_驗",
      selectTextOptionValue: "試_Filter Select_驗",
      disableLogo: "試_Disable Logo_驗",
      disableLogoDescription: "試_You can configure the GeoForm to Show/Hide the Logo in the form header_驗",
      locateOnLoadText: "試_Locate On Load_驗",
      locateOnLoadDescription: "試_You can configure the GeoForm to use the current location on page load_驗",
      selectLayerFieldTabText: "試_Select Layer_驗",
      allLayerSelectOptionText: "試_All_驗",
      disableViewer: "試_Disable Viewer_驗",
      disableViewerDescription: "試_You can configure the GeoForm to disable/enable Viewer_驗",
      displayFieldHintText: "試_Selected display field will be shown in viewerMode as title field_驗"
    },
    viewer: {
      geocoderCancelText: "試_Cancel_驗",
      viewReportsTabText: "試_Submissions_驗",
      viewLegendTabText: "試_Legend_驗",
      viewAboutusTabText: "試_About_驗",
      viewMapTabText: "試_Map_驗",
      sortHeaderText: "試_Sort By_驗:",
      btnSubmitReportText: "試_Submit a Report_驗",
      geocoderPlaceholderText: "試_Zip Code, city, etc_驗.",
      noSearchResult: "試_No result found_驗",
      recordsTabTooltip: "試_View Submissions_驗",
      legendTabTooltip: "試_Legend_驗",
      aboutUsTabTooltip: "試_AboutUs_驗",
      mapTabTooltip: "試_Map_驗",
      appLoadingFailedMessage: "試_ViewerMode is Unavailable_驗",
      btnDescendingText: "試_Desc_驗",
      btnAscendingText: "試_Asc_驗",
      geometryUnavailableErrorMessage: "試_Unable to find the geometry of the feature_驗",
      infoPopupOffErrorMessage: "試_InfoPopup is off_驗",
      btnLoadMoreText: "試_Load More_驗",
      unavailableTitleText: "試_Untitled_驗",
      unavailableConfigMessage: "試_Unable to load config_驗"
    }
  })
);