define(
     ({
        map: {
            error: "يتعذر إنشاء الخريطة"
        },
        onlineStatus: {
            offline: "أنت الآن غير مُتصل بالإنترنت. سيتم حفظ عمليات الإرسال محليًا حتى يتم إنشاء الاتصال بالخادم.",
            reconnecting: "إعادة الاتصال&hellip;",
            pending: "سيتم إرسال التحريرات المعلقة ${total} عند إعادة تأسيس اتصال الشبكة."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "المؤسسة",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "المحتوى",
                    favoritesLabel: "المفضلات"
                },
                title: "تحديد خريطة الويب",
                searchTitle: "البحث",
                ok: "موافق",
                cancel: "إلغاء",
                placeholder: "أدخل مصطلح البحث"
            },
            groupdlg: {
                items: {
                    organizationLabel: "المؤسسة",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "المحتوى",
                    favoritesLabel: "المفضلات"
                },
                title: "تحديد المجموعة",
                searchTitle: "البحث",
                ok: "موافق",
                cancel: "إلغاء",
                placeholder: "أدخل مصطلح البحث"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "بيت_Here is a link to a GeoForm_لاحقة"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "لا شيء",
            utm_easting: "اتجاه نحو الشرق",
            utm_zone_number: "رقم المنطقة",
            geoFormGeneralTabText: "1. أدخل المعلومات",
            locationInformationText: "2. حدد الموقع",
            submitInformationText: "3. أكمل النموذج",
            submitInstructions: "أضف هذه المعلومات إلى الخريطة.",
            myLocationText: "الموقع الحالي",
            locationDescriptionForMoreThanOneOption: "بيت_Specify the location for this entry by clicking/tapping the map or by using one of the following options_لاحقة.",
            locationDescriptionForOneOption: "بيت_Specify the location for this entry by clicking/tapping the map or by using the following option_لاحقة.",
            locationDescriptionForNoOption: "بيت_Specify the location for this entry by clicking/tapping the map_لاحقة.",
            addressText: "بحث",
            geographic: "خطوط الطول/خطوط العرض",
            locationTabText: "موقع",
            locationPopupTitle: "الموقع",
            submitButtonText: "تقديم إدخال",
            submitButtonTextLoading: "إرسال&hellip;",
            formValidationMessageAlertText: "يتطلب الحقول التالية:",
            selectLocation: "بيت_Please select a location for your submission_لاحقة.",
            emptylatitudeAlertMessage: "الرجاء إدخال إحداثيات ${openLink}خطوط العرض${closeLink}.",
            emptylongitudeAlertMessage: "الرجاء إدخال إحداثيات ${openLink}خطوط الطول${closeLink}.",
            shareUserTitleMessage: "أشكرك على مساهمتك!",
            entrySubmitted: "لقد تم تقديم الإدخال الخاص بك على الخريطة.",
            shareThisForm: "مشاركة هذا النموذج",
            shareUserTextMessage: "أخبر الأخرين بالمشاركة باستخدام الخيارات التالية.",
            addAttachmentFailedMessage: "تعذر إضافة مرفقات إلى الطبقة",
            addFeatureFailedMessage: "تعذر إضافة معلم إلى الطبقة",
            noLayerConfiguredMessage: "بيت_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_لاحقة.",
            placeholderLatitude: "خط العرض (Y)",
            placeholderLongitude: "خط الطول (X)",
            latitude: "خط العرض",
            longitude: "خط الطول",
            findMyLocation: "تحديد موقعي",
            finding: "تحديد موقع&hellip;",
            backToTop: "عودة لأعلى",
            addressSearchText: "سيظهر الإرسال هنا. يمكنك سحب الدبوس لتصحيح الموقع.",
            shareModalFormText: "رابط النموذج",
            close: "غلق",
            locationNotFound: "يتعذر العثور على الموقع.",
            setLocation: "تعيين الموقع",
            find: "العثور على عنوان أو مكان ما",
            attachment: "مرفق",
            toggleDropdown: "تبديل القائمة المنسدلة",
            invalidString: "بيت_Please enter valid value_لاحقة.",
            invalidSmallNumber: "بيت_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_لاحقة.",
            invalidNumber: "بيت_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_لاحقة.",
            invalidFloat: "بيت_Please enter valid ${openStrong}floating point${closeStrong} value_لاحقة.",
            invalidDouble: "بيت_Please enter valid ${openStrong}double${closeStrong} value_لاحقة.",
            invalidLatLong: "بيت_Please enter valid latitude and longitude coordinates_لاحقة.",
            invalidUTM: "بيت_Please enter valid UTM coordinates_لاحقة.",
            invalidUSNG: "بيت_Please enter valid USNG coordinates_لاحقة.",
            invalidMGRS: "بيت_Please enter valid MGRS coordinates_لاحقة.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "حدد&hellip;",
            applyEditsFailedMessage: "عذرًا، يتعذر إرسال الإدخال الخاص بك. الرجاء المحاولة مرة أخرى.",
            requiredFields: "يوجد بعض الأخطاء، الرجاء تصحيحهم أدناه.",
            requiredField: "(مطلوب)",
            error: "خطأ",
            textRangeHintMessage: "${openStrong}لمحة:${closeStrong} قيمة الحد الأدنى ${minValue} وقيمة الحد الأقصى ${maxValue}",
            dateRangeHintMessage: "${openStrong}لمحة:${closeStrong} الحد الأدنى للتاريخ ${minValue} والحد الأقصى للتاريخ ${maxValue}",
            remainingCharactersHintMessage: "بيت_${value} characters remaining_لاحقة"
        },
        builder: {
            invalidUser: "عذرًا، ليس لديك الإذن لعرض هذا العنصر",
            invalidWebmapSelectionAlert: "لا تحتوي خريطة الويب المحددة على طبقة صحيحة للاستخدام. الرجاء إضافة FeatureLayer قابلة للتحرير في خريطة الويب للاستمرار.",
            invalidWebmapSelectionAlert2: "لمزيد من المعلومات، الرجاء الرجوع إلى ${openLink}ما هي خدمة المعلم؟${closeLink}",
            selectFieldsText: "حدد من الحقول",
            selectThemeText: "تحديد سمة النموذج",
            webmapText: "خريطة الويب",
            layerText: "طبقة",
            detailsText: "تفاصيل",
            fieldsText: "حقول",
            styleText: "النمط",
            optionText: "خيارات",
            previewText: "معاينة",
            publishText: "نشر",
            optionsApplicationText: "خيارات",
            titleText: "منشيء",
            descriptionText: "بيت_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_لاحقة.",
            btnPreviousText: "السابق",
            btnNextText: "التالي",
            webmapTabTitleText: "حدد خريطة ويب",
            viewWebmap: "عرض خريطة الويب",
            webmapDetailsText: "بيت_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_لاحقة",
            btnSelectWebmapText: "اختر خريطة ويب",
            btnSelectWebmapTextLoading: "تحميل&hellip",
            layerTabTitleText: "تحديد الطبقة التي يمكن تحريرها",
            selectLayerLabelText: "طبقة",
            selectLayerDefaultOptionText: "تحديد الطبقة",
            detailsTabTitleText: "تفاصيل النموذج",
            detailTitleLabelText: "العنوان",
            detailLogoLabelText: "صورة الشعار",
            descriptionLabelText: "بيت_Form Instructions & Details_لاحقة",
            fieldDescriptionLabelText: "بيت_Help Text (optional)_لاحقة",
            fieldTabFieldHeaderText: "حقل",
            fieldTabLabelHeaderText: "لافتة التسمية",
            fieldTabDisplayTypeHeaderText: "عرض في شكل",
            fieldTabOrderColumnText: "بيت_Order_لاحقة",
            fieldTabVisibleColumnText: "بيت_Enabled_لاحقة",
            selectMenuOption: "حدد قائمة",
            selectRadioOption: "زر الراديو",
            selectTextOption: "النص",
            selectDateOption: "بيت_Date Picker_لاحقة",
            selectRangeOption: "بيت_Touch-Spinner_لاحقة",
            selectCheckboxOption: "خانة الاختيار",
            selectMailOption: "البريد الإلكتروني",
            selectUrlOption: "محدد موقع معلومات (URL)",
            selectTextAreaOption: "بيت_Text Area_لاحقة",
            previewApplicationText: "معاينة التطبيق",
            saveApplicationText: "حفظ التطبيق",
            saveText: "حفظ",
            toggleNavigationText: "تبديل التنقل",
            formPlaceholderText: "النموذج الخاص بي",
            shareBuilderInProgressTitleMessage: "نشر GeoForm",
            shareBuilderProgressBarMessage: "الرجاء الانتظار&hellip;",
            shareBuilderTitleMessage: "عملية ناجحة! تم حفظ العنصر",
            shareBuilderTextMessage: "يمكن بدء تجميع المعلومات عن طريق المشاركة مع الأخرين",
            shareModalFormText: "رابط النموذج",
            shareBuilderSuccess: "تم تحديث ونشر GeoForm!",
            geoformTitleText: "Geo Form",
            layerTabText: "هذه هي الطبقة التي سيُبنَى GeoForm منها، ويجب أن تكون الطبقة خدمة معالم مُمكنة للتحرير ولديها أذونات المشاركة المناسبة للجمهور.",
            detailsTabText: "استخدام مربعات تفاصيل النموذج أدناه لتخصيص العنوان وإضافة شعار مُخصّص وتقديم وصف مختصر لجمهور GeoForm. في الوصف، يمكنك إضافة روابط إلى الموارد الأخرى ومعلومات جهة الاتصال وحتى إشارة جمهورك إلى تطبيق رسم الخرائط على الويب الذي يشتمل على جميع البيانات المجمعة مع GeoForm.",
            fieldsTabText: "هنا يمكنك تحديد الحقول التي ستكون مرئية لجمهور GeoForm وتحرير التسميات التي سيراها الجمهور، وكذلك إضافة وصف مختصر للمساعدة عبر إدخال البيانات.",
            styleTabText: "إنشاء نمط لـ GeoForm باستخدام المواضيع أدناه بناءً على الإسناد.",
            publishTabText: "إذا قمت بإنهاء تخصيص GeoForm، احفظ التطبيق وابدأ المشاركة مع الجمهور. يمكنك دائمًا الرجوع إلى هذا المنشئ واستمرار التخصيص استنادً إلى الملاحظات.",
            headerSizeLabel:"بيت_Header Size_لاحقة",
            smallHeader: "استخدم رأس صفحة صغير",
            bigHeader: "بيت_Use Large Header_لاحقة",
            pushpinText: "دبوس الضبط",
            doneButtonText: "بيت_Save and Exit_لاحقة",
            fieldTabPlaceHolderHeaderText: "تلميح (اختياري)",
            enableAttachmentLabelText: "بيت_${openStrong}Enable Attachments${closeStrong}_لاحقة",
            enableAttachmentLabelHint: "بيت_You can enable/disable the attachments here_لاحقة",
            attachmentIsRequiredLabelText: "بيت_${openStrong}Attachment Required${closeStrong}_لاحقة",
            attachmentIsRequiredLabelHint: "بيت_If necessary, users can be required to enter an attachment_لاحقة.",
            attachmentLabelText: "بيت_Attachment Button Label_لاحقة",
            attachmentLabelHint: "بيت_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_لاحقة",
            attachmentDescription: "وصف المرفقات",
            attachmentHint: "إذا لزم الأمر، يمكنك توفير تعليمات المرفقات الإضافية هنا.",
            jumbotronDescription: "بيت_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_لاحقة",
            shareGeoformText: "مشاركة Geoform",
            shareDescription: "لوحة المشاركة تجعل الجمهور من السهل مشاركة GeoForm مع المساهمين الأخرين عند قيامهم بالإرسال - يمكن تعطيل هذا في أي وقت.",
            defaultMapExtent: "نطاق الخريطة الافتراضي",
            defaultMapExtentDescription: "ستقوم الخريطة بإعادة تعيين النطاق الافتراضي في خريطة الويب بعد الإرسال - يمكن تعطيل هذا في أي وقت.",
            pushpinOptionsDescription: "اختر من مجموعة الألوان المتعددة الخاصة بدبوس تثبيت الخريطة، وينبغي أن تختلف عن ترميز الخريطة لمساعدة المستخدم في وضع إرسالهم على الخريطة.",
            selectLocationText: "حدد الموقع حسب",
            myLocationText: "الموقع الخاص بي",
            searchText: "بحث",
            coordinatesText: "إحداثيات خطوط الطول وخطوط العرض",
            usng: "إحداثيات USNG",
            mgrs: "إحداثيات MGRS",
            utm: "إحداثيات UTM",
            selectLocationSDescription: "السماح للمستخدمين بتحديد موقع باستخدام تلك الطرق.",
            dragTooltipText:"بيت_Drag the field where you want it to appear_لاحقة",
            showHideLayerText:"بيت_Show/Hide Layer_لاحقة",
            showHideLayerHelpText:"بيت_You can configure the GeoForm to Show/Hide Layer_لاحقة"
        }
    })
);