define(
   ({
    map: {
      error: "بيت_Unable to create map_لاحقة"
    },
    onlineStatus: {
      offline: "بيت_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_لاحقة.",
      reconnecting: "بيت_Reconnecting&hellip;_لاحقة",
      pending: "بيت_${total} pending edit(s) will be submitted when a network connection is re-established_لاحقة."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "بيت_My Organization_لاحقة",
          onlineLabel: "بيت_ArcGIS Online_لاحقة",
          contentLabel: "بيت_My Content_لاحقة",
          favoritesLabel: "بيت_My Favorites_لاحقة"
        },
        title: "بيت_Select Web Map_لاحقة",
        searchTitle: "بيت_Search_لاحقة",
        ok: "بيت_Ok_لاحقة",
        cancel: "بيت_Cancel_لاحقة",
        placeholder: "بيت_Enter search term_لاحقة"
      },
      groupdlg: {
        items: {
          organizationLabel: "بيت_My Organization_لاحقة",
          onlineLabel: "بيت_ArcGIS Online_لاحقة",
          contentLabel: "بيت_My Content_لاحقة",
          favoritesLabel: "بيت_My Favorites_لاحقة"
        },
        title: "بيت_Select Group_لاحقة",
        searchTitle: "بيت_Search_لاحقة",
        ok: "بيت_Ok_لاحقة",
        cancel: "بيت_Cancel_لاحقة",
        placeholder: "بيت_Enter search term_لاحقة"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "بيت_Here is a link to a GeoForm_لاحقة"
      }
    },
    user: {
      mgrs: "بيت_MGRS_لاحقة",
      usng: "بيت_USNG_لاحقة",
      utm: "بيت_UTM_لاحقة",
      utm_northing: "بيت_Northing_لاحقة",
      utm_easting: "بيت_Easting_لاحقة",
      utm_zone_number: "بيت_Zone Number_لاحقة",
      selectLayerTabText: "بيت_${formSection} Select Form_لاحقة",
      geoFormGeneralTabText: "بيت_${formSection} Enter Information_لاحقة",
      locationInformationText: "بيت_${formSection} Select Location_لاحقة",
      submitInformationText: "بيت_${formSection} Complete Form_لاحقة",
      submitInstructions: "بيت_Add this information to the map_لاحقة.",
      myLocationText: "بيت_Current Location_لاحقة",
      locationDescriptionForMoreThanOneOption: "بيت_Specify the location for this entry by clicking/tapping the map or by using one of the following options_لاحقة.",
      locationDescriptionForOneOption: "بيت_Specify the location for this entry by clicking/tapping the map or by using the following option_لاحقة.",
      locationDescriptionForNoOption: "بيت_Specify the location for this entry by clicking/tapping the map_لاحقة.",
      addressText: "بيت_Search_لاحقة",
      geographic: "بيت_Lat/Lon_لاحقة",
      locationTabText: "بيت_Location_لاحقة",
      locationPopupTitle: "بيت_Location_لاحقة",
      submitButtonText: "بيت_Submit Entry_لاحقة",
      submitButtonTextLoading: "بيت_Submitting&hellip;_لاحقة",
      formValidationMessageAlertText: "بيت_The following fields are required_لاحقة:",
      selectLocation: "بيت_Please select a location for your submission_لاحقة.",
      emptylatitudeAlertMessage: "بيت_Please enter a ${openLink}latitude${closeLink} coordinate_لاحقة.",
      emptylongitudeAlertMessage: "بيت_Please enter a ${openLink}longitude${closeLink} coordinate_لاحقة.",
      shareUserTitleMessage: "بيت_Thank you for your contribution_لاحقة!",
      entrySubmitted: "بيت_Your entry has been submitted to the map_لاحقة.",
      shareThisForm: "بيت_Share This Form_لاحقة",
      shareUserTextMessage: "بيت_Tell others to contribute using the following options_لاحقة.",
      addAttachmentFailedMessage: "بيت_Unable to add attachment to layer_لاحقة",
      addFeatureFailedMessage: "بيت_Unable to add feature to layer_لاحقة",
      noLayerConfiguredMessage: "بيت_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_لاحقة.",
      placeholderLatitude: "بيت_Latitude (Y)_لاحقة",
      placeholderLongitude: "بيت_Longitude (X)_لاحقة",
      latitude: "بيت_Latitude_لاحقة",
      longitude: "بيت_Longitude_لاحقة",
      findMyLocation: "بيت_Locate Me_لاحقة",
      finding: "بيت_Locating&hellip;_لاحقة",
      backToTop: "بيت_Back to top_لاحقة",
      addressSearchText: "بيت_Your submission will appear here. You can drag the pin to correct the location_لاحقة.",
      shareModalFormText: "بيت_Form Link_لاحقة",
      close: "بيت_Close_لاحقة",
      locationNotFound: "بيت_Location could not be found_لاحقة.",
      setLocation: "بيت_Set Location_لاحقة",
      find: "بيت_Find address or place_لاحقة",
      attachment: "بيت_Attachment_لاحقة",
      toggleDropdown: "بيت_Toggle Dropdown_لاحقة",
      invalidString: "بيت_Please enter valid value_لاحقة.",
      invalidSmallNumber: "بيت_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_لاحقة.",
      invalidNumber: "بيت_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_لاحقة.",
      invalidFloat: "بيت_Please enter valid ${openStrong}floating point${closeStrong} value_لاحقة.",
      invalidDouble: "بيت_Please enter valid ${openStrong}double${closeStrong} value_لاحقة.",
      invalidLatLong: "بيت_Please enter valid latitude and longitude coordinates_لاحقة.",
      invalidUTM: "بيت_Please enter valid UTM coordinates_لاحقة.",
      invalidUSNG: "بيت_Please enter valid USNG coordinates_لاحقة.",
      invalidMGRS: "بيت_Please enter valid MGRS coordinates_لاحقة.",
      geoformTitleText: "بيت_GeoForm_لاحقة",
      domainDefaultText: "بيت_Select&hellip;_لاحقة",
      applyEditsFailedMessage: "بيت_Sorry your entry cannot be submitted. Please try again_لاحقة.",
      requiredFields: "بيت_There are some errors. Please correct them below_لاحقة.",
      requiredField: "بيت_(required)_لاحقة",
      error: "بيت_Error_لاحقة",
      textRangeHintMessage: "بيت_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_لاحقة",
      dateRangeHintMessage: "بيت_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_لاحقة",
      remainingCharactersHintMessage: "بيت_${value} characters remaining_لاحقة",
      mapFullScreen: "بيت_Full Screen_لاحقة",
      mapRestore: "بيت_Restore_لاحقة",
      filterSelectEmptyText: "بيت_Select_لاحقة",
      invalidLayerMessage: "بيت_Form layer does not exist. Please configure the application and set the layer_لاحقة.",
      selectedLayerText: "بيت_All_لاحقة"
    },
    builder: {
      invalidUser: "بيت_Sorry, you dont have permission to view this item_لاحقة",
      invalidWebmapSelectionAlert: "بيت_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_لاحقة.",
      invalidWebmapSelectionAlert2: "بيت_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_لاحقة",
      selectFieldsText: "بيت_Select Form Fields_لاحقة",
      selectThemeText: "بيت_Select Form Theme_لاحقة",
      webmapText: "بيت_Webmap_لاحقة",
      layerText: "بيت_Layer_لاحقة",
      detailsText: "بيت_Details_لاحقة",
      fieldsText: "بيت_Fields_لاحقة",
      styleText: "بيت_Style_لاحقة",
      optionText: "بيت_Options_لاحقة",
      previewText: "بيت_Preview_لاحقة",
      publishText: "بيت_Publish_لاحقة",
      optionsApplicationText: "بيت_Options_لاحقة",
      titleText: "بيت_Builder_لاحقة",
      descriptionText: "بيت_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_لاحقة.",
      btnPreviousText: "بيت_Previous_لاحقة",
      btnNextText: "بيت_Next_لاحقة",
      webmapTabTitleText: "بيت_Select a Webmap_لاحقة",
      viewWebmap: "بيت_View webmap_لاحقة",
      webmapDetailsText: "بيت_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_لاحقة",
      btnSelectWebmapText: "بيت_Choose Webmap_لاحقة",
      btnSelectWebmapTextLoading: "بيت_Loading&hellip;_لاحقة",
      layerTabTitleText: "بيت_Select Editable Layer_لاحقة",
      selectLayerLabelText: "بيت_Layer_لاحقة",
      selectLayerDefaultOptionText: "بيت_Select Layer_لاحقة",
      defaultBasemap: "بيت_Basemap Toggle_لاحقة",
      secondaryBasemap: "بيت_Default Basemap_لاحقة",
      detailsTabTitleText: "بيت_Form Details_لاحقة",
      detailTitleLabelText: "بيت_Title_لاحقة",
      detailLogoLabelText: "بيت_Logo Image_لاحقة",
      descriptionLabelText: "بيت_Form Instructions & Details_لاحقة",
      fieldDescriptionLabelText: "بيت_Help Text (optional)_لاحقة",
      fieldTabFieldHeaderText: "بيت_Field_لاحقة",
      fieldTabLabelHeaderText: "بيت_Label_لاحقة",
      fieldTabDisplayTypeHeaderText: "بيت_Display As_لاحقة",
      fieldTabOrderColumnText: "بيت_Order_لاحقة",
      fieldTabVisibleColumnText: "بيت_Enabled_لاحقة",
      selectMenuOption: "بيت_Select Menu_لاحقة",
      selectRadioOption: "بيت_Radio Button_لاحقة",
      selectTextOption: "بيت_Text_لاحقة",
      selectDateOption: "بيت_Date Picker_لاحقة",
      selectRangeOption: "بيت_Touch-Spinner_لاحقة",
      selectCheckboxOption: "بيت_Checkbox_لاحقة",
      selectMailOption: "بيت_Email_لاحقة",
      selectUrlOption: "بيت_URL_لاحقة",
      selectTextAreaOption: "بيت_Text Area_لاحقة",
      previewApplicationText: "بيت_Preview Application_لاحقة",
      saveApplicationText: "بيت_Save Application_لاحقة",
      saveText: "بيت_Save_لاحقة",
      toggleNavigationText: "بيت_Toggle navigation_لاحقة",
      formPlaceholderText: "بيت_My Form_لاحقة",
      shareBuilderInProgressTitleMessage: "بيت_Publishing GeoForm_لاحقة",
      shareBuilderProgressBarMessage: "بيت_Please Wait&hellip;_لاحقة",
      shareBuilderTitleMessage: "بيت_Success! Item saved_لاحقة",
      shareBuilderTextMessage: "بيت_You can start collecting information by sharing with others_لاحقة",
      shareModalFormText: "بيت_Form Link_لاحقة",
      shareBuilderSuccess: "بيت_Your GeoForm has been updated & published_لاحقة!",
      geoformTitleText: "بيت_Geo Form_لاحقة",
      layerTabText: "بيت_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_لاحقة.",
      detailsTabText: "بيت_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_لاحقة.",
      fieldsTabText: "بيت_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_لاحقة.",
      styleTabText: "بيت_Style your GeoForm using the themes below based on your preference_لاحقة.",
      publishTabText: "بيت_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_لاحقة.",
      headerSizeLabel: "بيت_Header Size_لاحقة",
      smallHeader: "بيت_Use Small Header_لاحقة",
      bigHeader: "بيت_Use Large Header_لاحقة",
      pushpinText: "بيت_Push pin_لاحقة",
      doneButtonText: "بيت_Save and Exit_لاحقة",
      fieldTabPlaceHolderHeaderText: "بيت_Hint (optional)_لاحقة",
      enableAttachmentLabelText: "بيت_${openStrong}Enable Attachments${closeStrong}_لاحقة",
      enableAttachmentLabelHint: "بيت_You can enable/disable the attachments here_لاحقة",
      attachmentIsRequiredLabelText: "بيت_${openStrong}Attachment Required${closeStrong}_لاحقة",
      attachmentIsRequiredLabelHint: "بيت_If necessary, users can be required to enter an attachment_لاحقة.",
      attachmentLabelText: "بيت_Attachment Button Label_لاحقة",
      attachmentLabelHint: "بيت_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_لاحقة",
      attachmentDescription: "بيت_Attachment Description_لاحقة",
      attachmentHint: "بيت_If necessary, you can provide additional attachment instructions here_لاحقة.",
      jumbotronDescription: "بيت_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_لاحقة",
      shareGeoformText: "بيت_Share Geoform_لاحقة",
      shareDescription: "بيت_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_لاحقة.",
      defaultMapExtent: "بيت_Default Map Extent_لاحقة",
      defaultMapExtentDescription: "بيت_The map will reset to the default extent in your web map after submission - this can be disabled at any time_لاحقة.",
      pushpinOptionsDescription: "بيت_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_لاحقة",
      selectLocationText: "بيت_Select Location By_لاحقة",
      myLocationText: "بيت_My Location_لاحقة",
      searchText: "بيت_Search_لاحقة",
      coordinatesText: "بيت_Latitude & Longitude Coordinates_لاحقة",
      usng: "بيت_USNG Coordinates_لاحقة",
      mgrs: "بيت_MGRS Coordinates_لاحقة",
      utm: "بيت_UTM Coordinates_لاحقة",
      selectLocationSDescription: "بيت_Allow users to select a location using these methods_لاحقة.",
      dragTooltipText: "بيت_Drag the field where you want it to appear_لاحقة",
      showHideLayerText: "بيت_Show Layer_لاحقة",
      showHideLayerHelpText: "بيت_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_لاحقة.",
      labelHelpMessage: "بيت_Label_لاحقة",
      placeHolderHintMessage: "بيت_Hint Text_لاحقة",
      placeHolderHelpMessage: "بيت_Help Text_لاحقة",
      selectTextOptionValue: "بيت_Filter Select_لاحقة",
      disableLogo: "بيت_Disable Logo_لاحقة",
      disableLogoDescription: "بيت_You can configure the GeoForm to Show/Hide the Logo in the form header_لاحقة",
      locateOnLoadText: "بيت_Locate On Load_لاحقة",
      locateOnLoadDescription: "بيت_You can configure the GeoForm to use the current location on page load_لاحقة",
      selectLayerFieldTabText: "بيت_Select Layer_لاحقة",
      allLayerSelectOptionText:"بيت_All_لاحقة"
    }
  })
);