define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ı_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._İ",
            selectFieldsText:"ı_Select Form Fields_İ",
            selectThemeText: "Form Teması Seç",
            fieldLabelPlaceHolder: "Bu alanı etiketle",
            fieldDescPlaceHolder: "Bu alanı açıkla",
            webmapText: "ı_1. Webmap_İ",
            layerText: "ı_2. Layer_İ",
            detailsText: "ı_3. Details_İ",
            fieldsText: "ı_4. Fields_İ",
            styleText: "ı_5. Style_İ",
            previewText: "ı_6. Preview_İ",
            publishText: "ı_7. Publish_İ",
            titleText: "GeoForm Oluşturucu",
            descriptionText: "ı_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._İ",
            btnPreviousText: "Önceki",
            btnNextText:"Sonraki",
            webmapTabTitleText: "Bir Web Haritası seç",
            btnSelectWebmapText:"Web haritası seç",
            layerTabTitleText: "Düzenlenebilir Katman Seç",
            selectLayerLabelText:"Katman",
            selectLayerDefaultOptionText:"Katman seç",
            detailsTabTitleText:"Form Ayrıntıları",
            detailTitleLabelText: "Başlık",
            detailLogoLabelText: "Logo Görseli",
            detailDescriptionLabelText: "Açıklama",
            fieldTabFieldHeaderText: "Alan",
            fieldTabLabelHeaderText: "Etiket",
            fieldTabTypeHeaderText: "Tür",
            fieldTabDescriptionHeaderText: "Açıklama",
            previewApplicationText: "Uygulamayı Önizle",
            saveApplicationText: "Uygulamayı Kaydet",
            saveText: "Kaydet",
            toggleNavigationText: "ı_Toggle navigation_İ",
            formPlaceholderText: "ı_My Form_İ",
            imageLogoPlaceholderText: "ı_http://www.mysite.com/myimage.png_İ",
            shareBuilderInProgressTitleMessage: "ı_Publishing GeoForm_İ",
            shareBuilderProgressBarMessage:"ı_Please Wait..._İ",
            shareBuilderTitleMessage: "ı_Your GeoForm has been updated & published!_İ",
            shareBuilderTextMessage: "ı_You can start collecting information by sharing with others_İ",
            shareDialogFormText: "ı_Form Link_İ",
            geoformTitleText: "ı_Geo Form_İ",
            layerTabText: "ı_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._İ",
            detailsTabText:"ı_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._İ",
            fieldsTabText:"ı_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._İ",
            styleTabText: "ı_Style your GeoForm using the themes below based on your preference._İ",
            publishTabText: "ı_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._İ"
        }
    })
);