define(
   ({
    map: {
      error: "ı_Unable to create map_İ"
    },
    onlineStatus: {
      offline: "ı_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_İ.",
      reconnecting: "ı_Reconnecting&hellip;_İ",
      pending: "ı_${total} pending edit(s) will be submitted when a network connection is re-established_İ."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "ı_My Organization_İ",
          onlineLabel: "ı_ArcGIS Online_İ",
          contentLabel: "ı_My Content_İ",
          favoritesLabel: "ı_My Favorites_İ"
        },
        title: "ı_Select Web Map_İ",
        searchTitle: "ı_Search_İ",
        ok: "ı_Ok_İ",
        cancel: "ı_Cancel_İ",
        placeholder: "ı_Enter search term_İ"
      },
      groupdlg: {
        items: {
          organizationLabel: "ı_My Organization_İ",
          onlineLabel: "ı_ArcGIS Online_İ",
          contentLabel: "ı_My Content_İ",
          favoritesLabel: "ı_My Favorites_İ"
        },
        title: "ı_Select Group_İ",
        searchTitle: "ı_Search_İ",
        ok: "ı_Ok_İ",
        cancel: "ı_Cancel_İ",
        placeholder: "ı_Enter search term_İ"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "ı_Here is a link to a GeoForm_İ"
      }
    },
    user: {
      mgrs: "ı_MGRS_İ",
      usng: "ı_USNG_İ",
      utm: "ı_UTM_İ",
      utm_northing: "ı_Northing_İ",
      utm_easting: "ı_Easting_İ",
      utm_zone_number: "ı_Zone Number_İ",
      selectLayerTabText: "ı_${formSection} Select Form_İ",
      geoFormGeneralTabText: "ı_${formSection} Enter Information_İ",
      locationInformationText: "ı_${formSection} Select Location_İ",
      submitInformationText: "ı_${formSection} Complete Form_İ",
      submitInstructions: "ı_Add this information to the map_İ.",
      myLocationText: "ı_Current Location_İ",
      locationDescriptionForMoreThanOneOption: "ı_Specify the location for this entry by clicking/tapping the map or by using one of the following options_İ.",
      locationDescriptionForOneOption: "ı_Specify the location for this entry by clicking/tapping the map or by using the following option_İ.",
      locationDescriptionForNoOption: "ı_Specify the location for this entry by clicking/tapping the map_İ.",
      addressText: "ı_Search_İ",
      geographic: "ı_Lat/Lon_İ",
      locationTabText: "ı_Location_İ",
      locationPopupTitle: "ı_Location_İ",
      submitButtonText: "ı_Submit Entry_İ",
      submitButtonTextLoading: "ı_Submitting&hellip;_İ",
      formValidationMessageAlertText: "ı_The following fields are required_İ:",
      selectLocation: "ı_Please select a location for your submission_İ.",
      emptylatitudeAlertMessage: "ı_Please enter a ${openLink}latitude${closeLink} coordinate_İ.",
      emptylongitudeAlertMessage: "ı_Please enter a ${openLink}longitude${closeLink} coordinate_İ.",
      shareUserTitleMessage: "ı_Thank you for your contribution_İ!",
      entrySubmitted: "ı_Your entry has been submitted to the map_İ.",
      shareThisForm: "ı_Share This Form_İ",
      shareUserTextMessage: "ı_Tell others to contribute using the following options_İ.",
      addAttachmentFailedMessage: "ı_Unable to add attachment to layer_İ",
      addFeatureFailedMessage: "ı_Unable to add feature to layer_İ",
      noLayerConfiguredMessage: "ı_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_İ.",
      placeholderLatitude: "ı_Latitude (Y)_İ",
      placeholderLongitude: "ı_Longitude (X)_İ",
      latitude: "ı_Latitude_İ",
      longitude: "ı_Longitude_İ",
      findMyLocation: "ı_Locate Me_İ",
      finding: "ı_Locating&hellip;_İ",
      backToTop: "ı_Back to top_İ",
      addressSearchText: "ı_Your submission will appear here. You can drag the pin to correct the location_İ.",
      shareModalFormText: "ı_Form Link_İ",
      close: "ı_Close_İ",
      locationNotFound: "ı_Location could not be found_İ.",
      setLocation: "ı_Set Location_İ",
      find: "ı_Find address or place_İ",
      attachment: "ı_Attachment_İ",
      toggleDropdown: "ı_Toggle Dropdown_İ",
      invalidString: "ı_Please enter valid value_İ.",
      invalidSmallNumber: "ı_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_İ.",
      invalidNumber: "ı_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_İ.",
      invalidFloat: "ı_Please enter valid ${openStrong}floating point${closeStrong} value_İ.",
      invalidDouble: "ı_Please enter valid ${openStrong}double${closeStrong} value_İ.",
      invalidLatLong: "ı_Please enter valid latitude and longitude coordinates_İ.",
      invalidUTM: "ı_Please enter valid UTM coordinates_İ.",
      invalidUSNG: "ı_Please enter valid USNG coordinates_İ.",
      invalidMGRS: "ı_Please enter valid MGRS coordinates_İ.",
      geoformTitleText: "ı_GeoForm_İ",
      domainDefaultText: "ı_Select&hellip;_İ",
      applyEditsFailedMessage: "ı_Sorry your entry cannot be submitted. Please try again_İ.",
      requiredFields: "ı_There are some errors. Please correct them below_İ.",
      requiredField: "ı_(required)_İ",
      error: "ı_Error_İ",
      textRangeHintMessage: "ı_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_İ",
      dateRangeHintMessage: "ı_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_İ",
      remainingCharactersHintMessage: "ı_${value} characters remaining_İ",
      mapFullScreen: "ı_Full Screen_İ",
      mapRestore: "ı_Restore_İ",
      filterSelectEmptyText: "ı_Select_İ",
      invalidLayerMessage: "ı_Form layer does not exist. Please configure the application and set the layer_İ.",
      selectedLayerText: "ı_All_İ"
    },
    builder: {
      invalidUser: "ı_Sorry, you dont have permission to view this item_İ",
      invalidWebmapSelectionAlert: "ı_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_İ.",
      invalidWebmapSelectionAlert2: "ı_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_İ",
      selectFieldsText: "ı_Select Form Fields_İ",
      selectThemeText: "ı_Select Form Theme_İ",
      webmapText: "ı_Webmap_İ",
      layerText: "ı_Layer_İ",
      detailsText: "ı_Details_İ",
      fieldsText: "ı_Fields_İ",
      styleText: "ı_Style_İ",
      optionText: "ı_Options_İ",
      previewText: "ı_Preview_İ",
      publishText: "ı_Publish_İ",
      optionsApplicationText: "ı_Options_İ",
      titleText: "ı_Builder_İ",
      descriptionText: "ı_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_İ.",
      btnPreviousText: "ı_Previous_İ",
      btnNextText: "ı_Next_İ",
      webmapTabTitleText: "ı_Select a Webmap_İ",
      viewWebmap: "ı_View webmap_İ",
      webmapDetailsText: "ı_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_İ",
      btnSelectWebmapText: "ı_Choose Webmap_İ",
      btnSelectWebmapTextLoading: "ı_Loading&hellip;_İ",
      layerTabTitleText: "ı_Select Editable Layer_İ",
      selectLayerLabelText: "ı_Layer_İ",
      selectLayerDefaultOptionText: "ı_Select Layer_İ",
      defaultBasemap: "ı_Basemap Toggle_İ",
      secondaryBasemap: "ı_Default Basemap_İ",
      detailsTabTitleText: "ı_Form Details_İ",
      detailTitleLabelText: "ı_Title_İ",
      detailLogoLabelText: "ı_Logo Image_İ",
      descriptionLabelText: "ı_Form Instructions & Details_İ",
      fieldDescriptionLabelText: "ı_Help Text (optional)_İ",
      fieldTabFieldHeaderText: "ı_Field_İ",
      fieldTabLabelHeaderText: "ı_Label_İ",
      fieldTabDisplayTypeHeaderText: "ı_Display As_İ",
      fieldTabOrderColumnText: "ı_Order_İ",
      fieldTabVisibleColumnText: "ı_Enabled_İ",
      selectMenuOption: "ı_Select Menu_İ",
      selectRadioOption: "ı_Radio Button_İ",
      selectTextOption: "ı_Text_İ",
      selectDateOption: "ı_Date Picker_İ",
      selectRangeOption: "ı_Touch-Spinner_İ",
      selectCheckboxOption: "ı_Checkbox_İ",
      selectMailOption: "ı_Email_İ",
      selectUrlOption: "ı_URL_İ",
      selectTextAreaOption: "ı_Text Area_İ",
      previewApplicationText: "ı_Preview Application_İ",
      saveApplicationText: "ı_Save Application_İ",
      saveText: "ı_Save_İ",
      toggleNavigationText: "ı_Toggle navigation_İ",
      formPlaceholderText: "ı_My Form_İ",
      shareBuilderInProgressTitleMessage: "ı_Publishing GeoForm_İ",
      shareBuilderProgressBarMessage: "ı_Please Wait&hellip;_İ",
      shareBuilderTitleMessage: "ı_Success! Item saved_İ",
      shareBuilderTextMessage: "ı_You can start collecting information by sharing with others_İ",
      shareModalFormText: "ı_Form Link_İ",
      shareBuilderSuccess: "ı_Your GeoForm has been updated & published_İ!",
      geoformTitleText: "ı_Geo Form_İ",
      layerTabText: "ı_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_İ.",
      detailsTabText: "ı_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_İ.",
      fieldsTabText: "ı_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_İ.",
      styleTabText: "ı_Style your GeoForm using the themes below based on your preference_İ.",
      publishTabText: "ı_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_İ.",
      headerSizeLabel: "ı_Header Size_İ",
      smallHeader: "ı_Use Small Header_İ",
      bigHeader: "ı_Use Large Header_İ",
      pushpinText: "ı_Push pin_İ",
      doneButtonText: "ı_Save and Exit_İ",
      fieldTabPlaceHolderHeaderText: "ı_Hint (optional)_İ",
      enableAttachmentLabelText: "ı_${openStrong}Enable Attachments${closeStrong}_İ",
      enableAttachmentLabelHint: "ı_You can enable/disable the attachments here_İ",
      attachmentIsRequiredLabelText: "ı_${openStrong}Attachment Required${closeStrong}_İ",
      attachmentIsRequiredLabelHint: "ı_If necessary, users can be required to enter an attachment_İ.",
      attachmentLabelText: "ı_Attachment Button Label_İ",
      attachmentLabelHint: "ı_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_İ",
      attachmentDescription: "ı_Attachment Description_İ",
      attachmentHint: "ı_If necessary, you can provide additional attachment instructions here_İ.",
      jumbotronDescription: "ı_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_İ",
      shareGeoformText: "ı_Share Geoform_İ",
      shareDescription: "ı_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_İ.",
      defaultMapExtent: "ı_Default Map Extent_İ",
      defaultMapExtentDescription: "ı_The map will reset to the default extent in your web map after submission - this can be disabled at any time_İ.",
      pushpinOptionsDescription: "ı_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_İ",
      selectLocationText: "ı_Select Location By_İ",
      myLocationText: "ı_My Location_İ",
      searchText: "ı_Search_İ",
      coordinatesText: "ı_Latitude & Longitude Coordinates_İ",
      usng: "ı_USNG Coordinates_İ",
      mgrs: "ı_MGRS Coordinates_İ",
      utm: "ı_UTM Coordinates_İ",
      selectLocationSDescription: "ı_Allow users to select a location using these methods_İ.",
      dragTooltipText: "ı_Drag the field where you want it to appear_İ",
      showHideLayerText: "ı_Show Layer_İ",
      showHideLayerHelpText: "ı_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_İ.",
      labelHelpMessage: "ı_Label_İ",
      placeHolderHintMessage: "ı_Hint Text_İ",
      placeHolderHelpMessage: "ı_Help Text_İ",
      selectTextOptionValue: "ı_Filter Select_İ",
      disableLogo: "ı_Disable Logo_İ",
      disableLogoDescription: "ı_You can configure the GeoForm to Show/Hide the Logo in the form header_İ",
      locateOnLoadText: "ı_Locate On Load_İ",
      locateOnLoadDescription: "ı_You can configure the GeoForm to use the current location on page load_İ",
      selectLayerFieldTabText: "ı_Select Layer_İ",
      allLayerSelectOptionText:"ı_All_İ"
    }
  })
);