define({
    root: ({
        map: {
            error: "Não foi possível criar o mapa",
            views: "visualizações."
        },
        report: {
            flag: "Marcar como inapropriado",
            error: "Erro",
            success: "Marcado",
            loading: "Loading&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Descrição indisponível",
            bookmarks: "Marcadores",
            zoomTo: "Efetuar zoom para esta localização e obter mais informações.",
            untitledNote: "Sem título"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Camadas de Media",
            mediaLayersDescription: "Exibir as contribuições do público no mapa.",
            flickrSettings: "Configurações do Flickr",
            twitter: "Twitter",
            twitterSettings: "Configurações do Twitter",
            twitterUser: "Conta do Twitter",
            twitterSignIn: "Iniciar sessão no Twitter",
            webcams: "Câmaras web",
            instagram: "Instagram",
            instagramSettings: "Definições do Instagram",
            igTime: "Carregado no passado número de dias",
            youtube: "YouTube",
            youtubeSettings: "Configurações do YouTube",
            ytSettingsInfo: "Visualizar vídeos gerados pelos utilizadores, incluindo conteúdo de rede e profissional.",
            ytTime: "Carregado no passado",
            today: "Dia",
            this_week: "Semana",
            this_month: "Mês",
            all_time: "Sempre",
            moreInfo: "Mais informações",
            searchTerms: "Termos de Pesquisa",
            search: "Pesquisar",
            flSettingsInfo: "Devolve resultados que correspondem ao título, descrição ou palavras-chave de uma fotografia. .",
            twSettingsInfo: "Veja o que está a acontecer agora mesmo.",
            igSettingsInfo: "O Instagram é uma forma fácil, atrativa e divertida de partilhar a sua vida com amigos e família.",
            advancedOperators: "Sugestão: utilize um <a target=\"_blank\" href=\"https://support.twitter.com/articles/71577-using-advanced-search\">operators</a> para criar pesquisas avançadas.",
            tweetsFilteredBy: "tweets filtrados por:",
            photosFilteredBy: "fotos filtradas por:",
            videosFilteredBy: "vídeos filtrados por:",
            twitterAccountStatus: "Ative a camada do Twitter para visualizar o seu estado."
        },
        general: {
            map: "Mapa",
            mapInfo: "Informação do Mapa",
            legend: "Legenda",
            featured: "Locais em Destaque",
            layers: "Camadas",
            share: "Partilhar",
            about: "Sobre",
            find: "Código postal, cidade, etc.",
            moreInfo: "Mais informações",
            dateModified: "Última atualização",
            noSearchResult: "Não foram encontrados resultados",
            switchAccount: "Mudar de conta",
            signIn: "Iniciar Sessão",
            settings: "Configurações"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});