define(
	 ({
		header: {
			start: "é_start___È",
			searchStories: "é_Search your stories________È...",
			filter: "é_Filter___È",
			sort: "é_Sort__È",
			sortColon: "é_Sort___È:",
			numResults: "é_Results: {{NUM_RESULTS}}________È",
			sortBy: "é_Sort by___È",
			dateModified: "é_Date modified_____È",
			title: "é_Title___È",
			type: "é_Type__È",
			views: "é_Views___È",
			errors: "é_Errors___È",
			filterBy: "é_Filter by____È",
			filterItems: "é_Filter Items_____È",
			apps: "é_Apps__È",
			sharing: "é_Sharing___È",
			clearAll: "é_Clear all____È",
			clearSearch: "é_Clears the search______È",
			logOut: "é_Log Out___È",
			mainQuote: "é_Storytelling is the most powerful way to put ideas into the world today_______________________È.",
			quoteSource: "é_Robert McKee_____È",
			checkYourStories: "é_Check Stories_____È",
			createStory: "é_Create Story_____È",
			totalStories: "é_Total stories: {{NUM_STORIES}}__________È",
			noIssues: "é_All good___È",
			userStories: "é_Stories of {{USER_NAME}}________È",
			headerDisabledTooltip: "é_Please wait while we work some magic_____________È...",
			notOnTouch: "é_Not available on touch devices__________È",
		},
		deleteModal: {
			title: "é_Confirm Delete_____È",
			warningText: "é_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________È.",
			deleteText: "é_Delete___È",
			cancel: "é_Cancel___È"
		},
		loading: {
			loadingText: "é_Loading your stories________È..."
		},
		cantFindStories: {
			whereAreStories: "é_Not seeing your story________È?",
			notSeeExplanation: "é_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________È.",
			faq: "é_FAQ__È",
			followingStoriesToUpdate: "é_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________È:",
			gettingStories: "é_Searching for stories created with early versions of our applications that need to be updated______________________________È...",
			title: "é_Title___È",
			typeOfStoryMap: "é_Type__È",
			lastModified: "é_Last modified_____È",
			allUpToDate: "é_No stories created with early versions of our applications need to be updated________________________È.",
			updateAll: "é_Update All____È",
			errorScanningForStories: "é_There was an error searching your stories______________È.",
			close: "é_Close___È",
			updates: "é_Updates___È",
			updatingNumberOfNumber: "é_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________È",
			updatingNumberOfNumberAlt: "é_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________È",
			updateSucceeded: "é_Update succeeded______È!",
			reloadingStories: "é_Reloading your stories_________È...",
			errorUpdatingStories: "é_There was an error updating your stories_____________È.",
			partialUpdateMessage: "é_Stories updated successfully: {{NUM_UPDATED}}_______________È"
		},
		signIn: {
			signInTitle: "é_Sign in to Story Maps_______È",
			signInTo: "é_Sign in with your existing ArcGIS Online account to_________________È:",
			explanationOne: "é_Create compelling story maps to tell your stories________________È.",
			explanationTwo: "é_Use your maps and data from ArcGIS Online in your story maps___________________È.",
			explanationThree: "é_Manage your story maps and check the status of their content___________________È.",
			dontHaveAccount: "é_Don't have an ArcGIS Online account? Sign up for a________________È:",
			publicAccount: "é_Free non-commercial public account___________È",
			orgAccount: "é_Free trial ArcGIS subscription__________È",
			timeExpired: "é_Your sign-in expired. Sign in again to pick up where you left off_____________________È.",
			apiDidntLoad: "é_Something isn't loading correctly. Try refreshing the page___________________È.",
			needAccount: "é_Need an account______È?",
			letsGo: "é_Let's go____È!"
		},
		sharingLevel: {
			publicMessage: "é_Public___È",
			privateMessage: "é_Private___È",
			organization: "é_Organization_____È",
			changedSharing: "é_Changed sharing level________È.",
			unableToChange: "é_Unable to change sharing_________È.",
			partOfMap: "é_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________È.",
			storyPublicContentOrg: "é_Your story is public, so its content can't be shared only with your organization_________________________È",
			storyPublicContentPrivate: "é_Your story is public, so its content can't be private_________________È",
			mapOrg: "é_Sharing your map to your organization would break your story___________________È",
			layerOrg: "é_Sharing your layer to your organization would break your story____________________È",
			mapPrivate: "é_Making your map private would break your story_______________È",
			layerPrivate: "é_Making your layer private would break your story_______________È"
		},
		collectionList: {
			advocacy: "é_Advocacy and Outreach_______È",
			architecture: "é_Architecture and Design________È",
			conservation: "é_Conservation and Sustainability__________È",
			culture: "é_Culture___È",
			destinations: "é_Destinations and Tourism________È",
			disasters: "é_Disasters and Recovery________È",
			economy: "é_Economy and Development________È",
			entertainment: "é_Entertainment_____È",
			history: "é_History___È",
			infrastructure: "é_Infrastructure_____È",
			marketing: "é_Marketing____È",
			nature: "é_Nature and Environment________È",
			news: "é_News and Events______È",
			oceans: "é_Oceans___È",
			parks: "é_Parks and Recreation_______È",
			people: "é_People and Society______È",
			planning: "é_Planning and Analysis_______È",
			publicArt: "é_Public Art____È",
			science: "é_Science and Technology________È",
			sport: "é_Sport___È",
			travelogues: "é_Travelogues____È"
		},
		types: {
			custom: "é_Custom___È",
			notSpecified: "é_Type not specified______È"
		},
		storyMap: {
			shared: "é_Shared___È",
			saveFailed: "é_Error saving_____È",
			numViews: "é_Views: {{NUM_VIEWS}}_______È",
			editStory: "é_Edit Story____È",
			viewLive: "é_View Live____È",
			preview: "é_Preview___È",
			deleteButton: "é_Delete___È",
			modified: "é_Modified {{DATE}}______È",
			summary: "é_Summary___È",
			loading: "é_Loading____È...",
			collapse: "é_collapse___È",
			close: "é_close___È",
			hide: "é_hide__È",
			notAvailableWhenBroken: "é_Your story has issues below_________È",
			cantBeDeleted: "é_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________È",
			shareDialog: {
				title: "é_Share your story with the world___________È!",
				notPublicWarning: "é_Your story is shared with your organization. Only members of your organization will be able to view it________________________________È.",
				embedStory: "é_Embed your story______È",
				shortLink: "é_Shortlink____È",
				hideHeaderBar: "é_Hide header bar______È",
				copied: "é_Copied___È",
				small: "é_small___È",
				medium: "é_medium___È",
				large: "é_large___È",
				custom: "é_custom___È",
				widthAbbreviation: "é_w_È",
				heightAbbreviation: "é_h_È",
				emptyDimension: "é_Enter a dimension______È.",
				seeExample: "é_Preview your embed______È",
				removeHeader: "é_Hide application header________È"
			},
			maps: {
				unableRetrieveTitle: "é_Unable to retrieve maps________È",
				unableRetrieveDescription: "é_We weren't able to retrieve maps for this story map_________________È."
			},
			images: {
				unableRetrieveTitle: "é_Unable to retrieve images_________È",
				unableRetrieveDescription: "é_We weren't able to retrieve images for this story map_________________È."
			},
			tags: {
				tags: "é_Tags__È",
				collectionTags: "é_Subject___È",
				selectASubject: "é_Select a subject______È",
				save: "é_Save__È",
				saved: "é_Saved___È",
				errorSaving: "é_Error saving_____È",
				tagTip: "é_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________È."
			},
			submitToGallery: {
				gallerySubmission: "é_Story Maps Gallery______È",
				canSubmitIf: "é_You can nominate your story to the gallery if it contains the following_______________________È:",
				hasOwnImage: "é_Custom thumbnail______È",
				chosenSubject: "é_A subject and some tags________È",
				chosenSubjectAlt: "é_A {{SUBJECT}} and some tags_________È",
				storyMapTopicSubject: "é_subject___È",
				sharedPublicly: "é_Shared publicly______È",
				noBrokenContent: "é_No broken content______È",
				nominateToGallery: "é_Nominate to Gallery_______È",
				comingSoon: "é_Coming soon_____È!",
				submitted: "é_Submitted____È",
				errorSubmitting: "é_Error submitting______È",
				ourGallery: "é_The Story Maps gallery________È",
				galleryTip: "é_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________È."
			},
			placeholders: {
				noSummary: "é_No summary, click to add one__________È."
			},
			errors: {
				cantDeleteStory: "é_Unable to delete story________È.",
				unableToFind: "é_Unable to find content________È",
				unableToRetrieve: "é_We weren't able to retrieve the content for this story map___________________È."
			},
			socialSharing: {
				availableWhenPublic: "é_This option will be available when your story is public__________________È"
			},
			dialog: {
				back: "é_Back__È",
				close: "é_Close___È",
				cancel: "é_Cancel___È"
			},
			imagePicker: {
				changeDefault: "é_Change the default image________È",
				changeImage: "é_Change thumbnail______È",
				uploadImage: "é_Upload thumbnail______È",
				chooseImage: "é_Choose thumbnail______È",
				chooseAnImage: "é_Choose an Image______È",
				notInIEVersion: "é_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________È.",
				or: "é_Or__È",
				uploadAnImage: "é_Upload an Image______È",
				supportedFileTypes: "é_Supports .png, .jpg, .gif_________È",
				imageSizeMessage: "é_Your image needs to be at least 286 px wide by 190 px tall___________________È.",
				minimumDimensions: "é_Minimum: 286 x 190px_______È",
				imagesLoading: "é_Loading images______È...",
				noImages: "é_This story has no images________È",
				errorLoading: "é_Unable to retrieve the images in this story______________È",
				clickBelowTip: "é_Click the button below to upload an image______________È.",
				dragAndDrop: "é_Drag and Drop_____È",
				cropImage: "é_Crop Image____È",
				saveImage: "é_Save Image____È",
				save: "é_Save__È",
				savingImage: "é_Saving your image_______È...",
				saved: "é_Saved___È!",
				errorSaving: "é_Unable to save your image_________È.",
				skipAndCrop: "é_Skip and Crop for me_______È",
				wrongFormat: "é_This file type is not supported___________È.",
				noCropWarning: "é_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________È."
			}
		},
		content: {
			media: {
				maps: "é_Maps__È",
				images: "é_Images___È",
				videos: "é_Videos___È",
				webpages: "é_Webpages___È",
				tags: "é_Tags__È",
				gallery: "é_Gallery___È"
			},
			headers: {
				status: "é_Status___È",
				source: "é_Source___È",
				name: "é_Name__È",
				shared: "é_Shared___È"
			},
			component: {
				mapTour: "é_Point Number_____È",
				bullet: "é_Bullet___È",
				tab: "é_Tab__È",
				accordion: "é_Section___È",
				mapJournal: "é_Section___È"
			},
			titleType: {
				mapTour: "é_Caption___È",
				mapJournal: "é_URL__È",
				mapSeries: "é_URL__È"
			},
			actions: {
				viewMap: "é_View Map___È",
				editMap: "é_Edit Map___È",
				fix: "é_Fix__È",
				viewLayer: "é_View Layer____È"
			},
			contentType: {
				mainStage: "é_main stage action______È",
				sidePanel: "é_description____È"
			},
			notification: {
				refreshExplanation: "é_Check your story again________È",
				checking: "é_Checking____È...",
				foundSomeIssues: "é_We found some issues_______È",
				noIssuesFound: "é_No issues found______È",
				storyPublic: "é_Your story is now public________È",
				storyOrg: "é_Your story is now shared to your organization_______________È",
				storyPrivate: "é_Your story is now private_________È",
				mapPublic: "é_Your map is now public________È",
				mapOrg: "é_Your map is now shared to your organization______________È",
				mapPrivate: "é_Your map is now private________È",
				layerPublic: "é_Your layer is now public________È",
				layerOrg: "é_Your layer is now shared to your organization_______________È",
				layerPrivate: "é_Your layer is now private_________È",
				contentPublic: "é_Your content is now public_________È",
				contentOrg: "é_Your content is now shared to your organization_______________È",
				contentPrivate: "é_Your content is now private_________È",
				storyAndContentPublic: "é_Your story and its content are now public_____________È",
				storyAndContentOrg: "é_Your story and its content are now shared to your organization____________________È",
				storyAndContentPrivate: "é_Your story and its content are now private______________È",
				shareBulkPrompt: "é_Do you want to share your storyâ€™s content accordingly__________________È?",
				layersPublic: "é_Some layers have also been shared publicly______________È",
				layersOrg: "é_Some layers have also been shared with your organization__________________È",
				layersPrivate: "é_Some layers have also been made private_____________È",
				mapsPublic: "é_Some maps have also been shared publicly_____________È",
				mapsOrg: "é_Some maps have also been shared with your organization_________________È",
				mapsPrivate: "é_Some maps have also been made private____________È",
				layersAndMapsPublic: "é_Some maps and layers have also been shared publicly________________È",
				layersAndMapsOrg: "é_Some maps and layers have also been shared with your organization_____________________È",
				layersAndMapsPrivate: "é_Some maps and layers have also been made private_______________È",
				yes: "é_Yes__È",
				no: "é_No__È",
				premiumPublicSuccess: "é_Your premium content is now publicly accessible_______________È",
				subscriptionPublicSuccess: "é_Your subscription content is now publicly accessible_________________È"
			},
			errors: {
				publicDisabled: "é_Sharing publicly has been disabled by the Administrator__________________È",
				noMapName: "é_Could Not Retrieve Map Name_________È",
				notPublic: "é_NOT PUBLIC____È",
				inaccessible: "é_INACCESSIBLE_____È",
				deleted: "é_DELETED___È",
				cantAccessVideo: "é_Could Not Access Video________È",
				noStoriesFound: "é_We could not find any Story Maps in your content________________È.",
				cantShowStories: "é_Unable to show your story maps. Please try again later__________________È.",
				consolationSearch: "é_We couldn't find any stories__________È.",
				notCompatibleWithBrowser : "é_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________È.",
				pleaseUpdateBrowser: "é_Please update your browser_________È.",
				searchTip: "é_Try and simplify it a bit_________È.",
				consolationNoStories: "é_Welcome to My Stories________È!",
				noStoriesTip: "é_To make your first story map, check out the Apps page_________________È.",
				letsGo: "é_Let's Go___È",
				cantChangeSharingLevel: "é_Unable to change sharing level__________È",
				cantChangeSharingLevels: "é_Unable to change sharing levels__________È",
				errorUpdatingTitle: "é_Error updating title_______È",
				errorUpdatingSummary: "é_Error updating summary________È",
				noEmptyTitle: "é_Title cannot be empty_______È",
				cantUpdatePremiumContent: "é_Unable to update premium content___________È",
				cantUpdateSubscriptionContent: "é_Unable to update subscription content____________È",
				createFirstStory: "é_Create My First Story_______È"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "é_Map has been deleted_______È",
				layerHasBeenDeleted: "é_Layer has been deleted________È",
				mapIsInaccessible: "é_Map is inaccessible_______È",
				layerIsInaccessible: "é_Layer is inaccessible_______È",
				mapNotYoursNotAccessible: "é_Map is owned by someone else and isn't accessible________________È",
				layerServiceOkItemNot: "é_Layer was added as an item that is deleted or inaccessible__________________È",
				layerNotYoursNotAccessible: "é_Layer is owned by someone else and isn't accessible________________È",
				mapOthersSharedBelowLevel: "é_Map is not owned by you and is not public_____________È",
				layerOthersSharedBelowLevel: "é_Layer is not owned by you and is not public______________È",
				noMapNoDetails: "é_Without the map details, we can't tell you anything about the layers_____________________È",
				mapIsPrivate: "é_Map is private_____È",
				mapIsOrg: "é_Map is only shared in your organization_____________È",
				layerIsPrivate: "é_Layer is private______È",
				layerIsOrg: "é_Layer is only shared in your organization_____________È",
				imageInaccessible: "é_This image is inaccessible_________È",
				videoInaccessible: "é_This video is inaccessible_________È",
				webpageInaccessible: "é_This web page is inaccessible__________È",
				layerSecureService: "é_Layer is a secure service_________È",
				mapSecureService: "é_Map is a secure service________È",
				layerConsumesCredits: "é_Layer is premium content and consumes credits_______________È",
				layerSubscriptionContent: "é_Layer is subscription content__________È",
				mapConsumesCredits: "é_Map is premium content and consumes credits______________È",
				mapSubscriptionContent: "é_Map is subscription content_________È"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "é_We're not able to check this type of layer______________È",
				cantScanThisType: "é_Layer is not a type of layer we can check_____________È",
				webpageNotScanned: "é_Webpages are not checked for issues____________È"
			},
			scanningErrors: {
				deletedMap: "é_Deleted content______È",
				inaccessibleMap: "é_Inaccessible map content________È",
				notYoursNotAccessible: "é_Content not owned by you and not public_____________È",
				serviceOkItemNot: "é_Working layers but inaccessible items____________È",
				someContentNotPublic: "é_Content not shared publicly_________È",
				someContentPrivate: "é_Private content______È",
				othersSharedBelowLevel: "é_Content not owned by you and not public_____________È",
				premiumContent: "é_Premium content______È",
				subscriptionContent: "é_Subscription content_______È",
				secureService: "é_Secure services______È",
				inaccessibleImage: "é_Inaccessible images_______È",
				inaccessibleVideo: "é_Inaccessible videos_______È",
				inaccessibleWebpage: "é_Inaccessible webpages_______È"
			},
			scanningErrorTips: {
				deletedMapTip: "é_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________È.",
				inaccessibleMapTip: "é_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________È.",
				notYoursNotAccessibleTip: "é_Tip: Open the web map and remove the layer or map from the story_____________________È.",
				serviceOkItemNotTip: "é_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________È.",
				ignore: "é_Ignore___È",
				fix: "é_Fix__È",
				clickToShareOrg: "é_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________È.",
				clickToSharePublic: "é_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________È.",
				shareOrg: "é_Share to your org______È",
				sharePublicly: "é_Share publicly_____È",
				othersSharedBelowLevelTip: "é_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________È.",
				secureServiceTip: "é_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________È.",
				blogArticle: "é_here__È",
				premiumContentTip: "é_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________È.",
				premiumContentPublicTip: "é_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________È.",
				subscriptionContentTip: "é_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________È.",
				agolCredits: "é_ArcGIS Online credits_______È",
				credits: "é_credits___È",
				makePublic: "é_Make public____È",
				confirm: "é_Confirm___È",
				inaccessibleImageTip: "é_Tip: Provide the missing image or remove the reference to it___________________È.",
				inaccessibleVideoTip: "é_Tip: Provide the missing video or remove the reference to it___________________È.",
				inaccessibleWebpageTip: "é_Tip: Provide the missing web page or remove the reference to it____________________È."
			},
			removeLayer: {
				title: "é_Fix Layer Issue______È",
				layersWithIssue: "é_Layers with this issue: {{NUM_WITH_ISSUE}}______________È",
				issueExplanation: "é_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________È.",
				issueSolution: "é_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________È:",
				editMap: "é_Edit Your Map_____È",
				clickBelowWhenDone: "é_When you have finished editing, click the button below__________________È:",
				rescanAndClose: "é_Rescan And Close______È"
			},
			info: {
				ownedBy: "é_This item is owned by {{USER_NAME}}____________È",
				unknownUser: "é_someone else_____È",
				untitledSection: "é_(Untitled section)______È",
				introRecord: "é_Introduction_____È"
			},
			layers: {
				layersHeader: "é_Layers___È",
				noLayers: "é_(No Layers)____È",
				basemapParens: "é_(basemap)____È"
			},
			images: {
				thumbnails: "é_Thumbnails____È",
				thumbnail: "é_Thumbnail____È",
				thumbnailParens: "é_(thumbnail)____È"
			},
			general: {
				noTitle: "é_(no title)____È",
				loading: "é_Loading____È..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "é_sections___È",
				secondTitle: "é_style___È",
				secondValueA: "é_side panel____È",
				secondValueB: "é_floating panel_____È",
				thirdTitle: "é_maps__È"
			},
			mapTour: {
				firstTitle: "é_tour points____È",
				secondTitle: "é_style___È",
				secondValueA: "é_integrated____È",
				secondValueB: "é_three-panel____È",
				thirdTitle: "é_basemap___È",
				thirdValueLoading: "é_Loading____È...",
				thirdValueUnknown: "é_unknown___È"
			},
			mapSeries: {
				firstTitleA: "é_bullets___È",
				firstTitleB: "é_sections___È",
				firstTitleC: "é_tabs__È",
				secondTitle: "é_style___È",
				secondValueA: "é_bulleted___È",
				secondValueB: "é_side accordion_____È",
				secondValueC: "é_tabbed___È",
				thirdTitle: "é_maps__È"
			},
			swipeSpyglass: {
				firstTitle: "é_points of interest______È",
				secondTitle: "é_style___È",
				secondValueA: "é_swipe___È",
				secondValueB: "é_spyglass___È",
				thirdTitle: "é_maps__È"
			}
		},
		progress: {
			checkingStories: "é_Checking your stories for issues____________È...",
			stop: "é_Stop__È",
			exit: "é_Exit__È",
			dismiss: "é_Dismiss___È",
			done: "é_Done___È.",
			noStoriesWithIssuesLower: "é_No issues found______È!",
			storiesErrorFree: "é_Looks like your stories are error-free____________È",
			scanAllError: "é_Unable to scan -- we couldn't retrieve one or more of your stories_____________________È",
			scanProgress: "é_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________È",
			scanStopped: "é_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________È",
			storiesWithIssues: "é_Stories with issues: {{NUM_STORIES}}____________È"
		}
    })
);