define({
    root: ({
        map: {
            error: "Nije moguće stvoriti kartu",
            views: "prikazi."
        },
        report: {
            flag: "Označi kao neprikladno",
            error: "Pogreška",
            success: "Obilježeno zastavicom",
            loading: "Učitavanje&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Opis nije dostupan",
            bookmarks: "Knjižne oznake",
            zoomTo: "Uvećajte ovu lokaciju i saznajte više.",
            untitledNote: "Neimenovano"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Medijski slojevi",
            mediaLayersDescription: "Prikaži doprinose javnosti na karti.",
            flickrSettings: "Postavke Flickra",
            twitter: "Twitter",
            twitterSettings: "Postavke Twittera",
            twitterUser: "Račun za Twitter",
            twitterSignIn: "Prijava na Twitter",
            webcams: "Webcams.travel",
            instagram: "Instagram",
            instagramSettings: "Postavke Instagrama",
            igTime: "Poslano u prethodnih nekoliko dana",
            youtube: "YouTube",
            youtubeSettings: "Postavke YouTubea",
            ytSettingsInfo: "Prikaz videozapisa korisnika uključujući mrežni i profesionalni sadržaj.",
            ytTime: "Poslano u prošlosti",
            today: "Dan",
            this_week: "Tjedan",
            this_month: "Mjesec",
            all_time: "Bilo kada",
            moreInfo: "Više informacija",
            searchTerms: "Termini za pretraživanje",
            search: "Pretraži",
            flSettingsInfo: "Vrati rezultate koji se podudaraju s nazivom fotografije, opisom ili oznakama.",
            twSettingsInfo: "Pogledajte što se sada događa.",
            igSettingsInfo: "Instagram je brzi, divni i zabavni način da podijelite životne trenutke s prijateljima i obitelji.",
            advancedOperators: "Savjet: upotrijebite <a target=\"_blank\" href=\"https://support.twitter.com/articles/71577-using-advanced-search\">operators</a> za napredno pretraživanje.",
            tweetsFilteredBy: "tweetovi filtrirani prema:",
            photosFilteredBy: "fotografije filtrirane prema:",
            videosFilteredBy: "videozapisi filtrirani prema:",
            twitterAccountStatus: "Omogućite Twitter sloj da vidite svoj status."
        },
        general: {
            map: "Karta",
            mapInfo: "Informacije o karti",
            legend: "Legenda",
            featured: "Izdvojene lokacije",
            layers: "Slojevi",
            share: "Podijeli",
            about: "Informacije",
            find: "Poštanski broj, grad itd.",
            moreInfo: "Više informacija",
            dateModified: "Posljednja izmjena",
            noSearchResult: "Nema rezultata",
            switchAccount: "Promijeni račun",
            signIn: "Prijava",
            settings: "Postavke"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});