define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Harta web selectată nu conţine niciun strat tematic valid pentru utilizare. Pentru a continua, adăugaţi un strat tematic de obiecte spaţiale editabil în harta web.",
            selectFieldsText:"Selectare câmpuri din formular",
            selectThemeText: "Selectare temă formular",
            fieldLabelPlaceHolder: "Etichetaţi acest câmp",
            fieldDescPlaceHolder: "Descrieţi acest câmp",
            webmapText: "1. Hartă web",
            layerText: "2. Strat tematic",
            detailsText: "3. Detalii",
            fieldsText: "4. Câmpuri",
            styleText: "5. Stil",
            previewText: "6. Previzualizare",
            publishText: "7Publicare.",
            titleText: "Builder GeoForm",
            descriptionText: "GeoForm este un şablon configurabil pentru editarea datelor bazate pe formulare ale unui <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Serviciu de obiecte spaţiale</a>. Această aplicaţie le permite utilizatorilor să introducă date printr-un formular în locul unei ferestre pop-up de hartă , beneficiind astfel de capacităţile <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>hărţilor web</a> şi ale serviciilor de obiecte spaţiale editabile. Utilizaţi acest instrument de creare pentru a vă particulariza şi instala serviciul GeoForm urmând paşii din partea stângă.",
            btnPreviousText: "Înapoi",
            btnNextText:"Înainte",
            webmapTabTitleText: "Selectaţi o hartă web",
            btnSelectWebmapText:"Selectare hartă Web",
            layerTabTitleText: "Selectare strat tematic editabil",
            selectLayerLabelText:"Strat tematic",
            selectLayerDefaultOptionText:"Selectare strat tematic",
            detailsTabTitleText:"Detalii formular",
            detailTitleLabelText: "Titlu",
            detailLogoLabelText: "Imagine siglă",
            detailDescriptionLabelText: "Descriere",
            fieldTabFieldHeaderText: "Câmp",
            fieldTabLabelHeaderText: "Etichetă",
            fieldTabTypeHeaderText: "Tip",
            fieldTabDescriptionHeaderText: "Descriere",
            previewApplicationText: "Previzualizare aplicaţie",
            saveApplicationText: "Salvare aplicaţie",
            saveText: "Salvare",
            toggleNavigationText: "Comutare navigaţie",
            formPlaceholderText: "Formularul meu",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "Publicare GeoForm în curs",
            shareBuilderProgressBarMessage:"Aşteptaţi...",
            shareBuilderTitleMessage: "Serviciul dvs. GeoForm a fost actualizat şi publicat!",
            shareBuilderTextMessage: "Puteţi începe să conectaţi informaţii partajându-le cu alţii",
            shareDialogFormText: "Link formular",
            geoformTitleText: "GeoForm",
            layerTabText: "Acesta este stratul tematic din care va fi creat serviciul GeoForm. Stratul tematic trebuie să fie un serviciu de obiecte spaţiale editabil cu permisiuni de partajare adaptate audienţei dvs.",
            detailsTabText:"Utilizaţi casetele Detalii formular de mai jos pentru a particulariza titlul, adăuga o siglă particularizată şi furniza o scurtă descriere pentru audienţa serviciului GeoForm.",
            fieldsTabText:"Aici puteţi selecta ce câmpuri vor fi vizibile pentru audienţa GeoForm, edita etichetele pe care aceştia le vor vedea şi adăuga o scurtă descriere pentru a ajuta la introducerea datelor.",
            styleTabText: "Modelaţi-vă serviciul GeoForm utilizând temele de mai jos, în funcţie de propriile preferinţe.",
            publishTabText: "După ce terminaţi de particularizat serviciul GeoForm, salvaţi aplicaţia şi începeţi să o partajaţi cu audienţa. Puteţi reveni oricând la acest instrument de creare şi continua particularizarea în funcţie de feedbackul primit."
        }
    })
);