define(
    ({
        builder: {
            invalidWebmapSelectionAlert: "Ă_Selected webmap does not contain any feature server_ș",
            selectThemeText: "Ă_Select Form Theme_ș",
            fieldLabelPlaceHolder: "Ă_Label this field_ș",
            fieldDescPlaceHolder: "Ă_Describe this field_ș",
            webmapText: "Ă_Webmap_ș",
            layerText: "Strat tematic",
            detailsText: "Detalii",
            fieldsText: "Câmpuri",
            styleText: "Ă_Style_ș",
            previewText: "Previzualizare",
            publishText: "Publicare",
            titleText: "Ă_GeoForm Builder_ș",
            descriptionText: "Ă_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._ș",
            btnPreviousText: "Ă_Previous_ș",
            btnNextText:"Ă_Next_ș",
            webmapTabTitleText: "Ă_Choose a Webmap_ș",
            btnSelectWebmapText:"Ă_Select Webmap_ș",
            layerTabTitleText: "Ă_Select Editable Layer_ș",
            selectLayerLabelText:"Strat tematic",
            selectLayerDefaultOptionText:"Selectare strat tematic",
            detailsTabTitleText:"Ă_Form Details_ș",
            detailTitleLabelText: "Titlu",
            detailLogoLabelText: "Ă_Logo Image_ș",
            detailDescriptionLabelText: "Descriere",
            fieldTabDisplayHeaderText: "Afişare",
            fieldTabFieldHeaderText: "Câmp",
            fieldTabLabelHeaderText: "Etichetă",
            fieldTabTypeHeaderText: "Tip",
            fieldTabDescriptionHeaderText: "Descriere",
            previewApplicationText: "Ă_Preview Application_ș",
            saveApplicationText: "Ă_Save Application_ș",
            saveText: "Salvare",

            //Local string for user mode
            defaultTitleText: "Ă_Default Title_ș",
            defaultDescriptionText: "Ă_Default Description_ș",
            geoFormGeneralTabText: "Noţiuni generale",
            locationInformationText: "Ă_Location Info_ș",
            myLocationText: "Locaţia mea",
            addressText: "Adresă",
            cooridnatesText: "Ă_Coordinates_ș",
            locationTabText: "Locaţie",
            enterCoordinatesPlaceholder: "Ă_Enter Coordinates_ș",
            submitButtonText: "Trimitere",
            clearButtonText: "Golire",
            fieldvalidationMessageAlertText: "Ă_Please enter a valid number_ș",
            formValidationMessageAlertText: "Ă_Please verify the form for errors and resubmit the form_ș",
            latlongValidationMessageAlert: "Ă_Please select x and y coordinates_ș",
            emptylatitudeAlertMessage:"Ă_Please enter Latitude_ș",
            emptylongitudeAlertMessage:"Ă_Please enter Longitude_ș"
        }
    })
    
);