define({
  root: ({
    layer: "Ă_Layer___ș",
    sort: "Ă_Sort by___ș",
    order: "Ă_Order___ș",
    desc: "Ă_Desc__ș",
    asc: "Ă_Asc__ș",
    loading: "Ă_loading&hellip;______ș",
    search: "Ă_Search___ș",
    searchPlaceholder: "Ă_Find reports_____ș",
    noResults: "Ă_No results____ș",
    ascending: "Ă_Ascending____ș",
    descending: "Ă_Descending____ș"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});