define({
  root: ({
    "pagination": {
      "page": "Ă_Page__ș",
      "previousTitle": "Ă_Previous___ș",
      "nextTitle": "Ă_Next__ș",
      "firstTitle": "Ă_First___ș",
      "lastTitle": "Ă_Last__ș",
      "helip": "Ă_&hellip;___ș"
    }
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});