define(
     ({
        map: {
            error: "Imposibil de creat harta"
        },
        onlineStatus: {
            offline: "În prezent, lucraţi offline. Trimiterea formularelor va fi salvată local până când se va putea stabili o conexiune la server.",
            reconnecting: "Se reconectează&hellip;",
            pending: "${total} editări în aşteptare vor fi trimise la restabilirea unei conexiuni de reţea."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organizaţia mea",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Resursele mele",
                    favoritesLabel: "Preferinţele mele"
                },
                title: "Selectare hartă Web",
                searchTitle: "Căutare",
                ok: "OK",
                cancel: "Anulare",
                placeholder: "Introducere termen de căutare"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organizaţia mea",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Resursele mele",
                    favoritesLabel: "Preferinţele mele"
                },
                title: "Selectare grup",
                searchTitle: "Căutare",
                ok: "OK",
                cancel: "Anulare",
                placeholder: "Introducere termen de căutare"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Spre nord",
            utm_easting: "Spre est",
            utm_zone_number: "Număr zonă",
            geoFormGeneralTabText: "1. Introduceţi informaţii",
            locationInformationText: "2. Selectaţi o locaţie",
            submitInformationText: "3. Completaţi un formular",
            submitInstructions: "Adăugaţi aceste informaţii în hartă.",
            myLocationText: "Ă_Current Location_ș",
            locationDescription: "Ă_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ș",
            addressText: "Căutare",
            geographic: "Ă_Lat/Lon_ș",
            locationTabText: "Locaţie",
            locationPopupTitle: "Ă_Location_ș",
            submitButtonText: "Ă_Submit Entry_ș",
            submitButtonTextLoading: "Se trimite&hellip;",
            formValidationMessageAlertText: "Următoarele câmpuri sunt obligatorii:",
            selectLocation: "Selectaţi o ${openLink}locaţie${closeLink} pentru trimitere.",
            emptylatitudeAlertMessage: "Introduceţi o coordonată de ${openLink}latitudine${closeLink}.",
            emptylongitudeAlertMessage: "Introduceţi o coordonată de ${openLink}longitudine${closeLink}.",
            shareUserTitleMessage: "Vă mulţumim pentru contribuţie!",
            entrySubmitted: "Ă_Your entry has been submitted to the map._ș",
            shareThisForm: "Ă_Share This Form_ș",
            shareUserTextMessage: "Ă_Tell others to contribute using the following options._ș",
            addAttachmentFailedMessage: "Nu se poate adăuga o ataşare la stratul tematic",
            addFeatureFailedMessage: "Nu se poate adăuga un obiect spaţial la stratul tematic",
            noLayerConfiguredMessage: "Hopa! Aici nu există nimic. Pentru a începe să colectaţi date pentru formular, configuraţi acest serviciu GeoForm şi selectaţi un strat tematic de serviciu de obiecte spaţiale editabil, pe care să îl utilizaţi.",
            placeholderLatitude: "Latitudine (Y)",
            placeholderLongitude: "Longitudine (X)",
            latitude: "Latitudine",
            longitude: "Longitudine",
            findMyLocation: "Ă_Locate Me_ș",
            finding: "Se localizează&hellip;",
            backToTop: "Înapoi sus",
            addressSearchText: "Datele introduse vor apărea aici. Puteţi trage marcajul pentru a corecta locaţia.",
            shareModalFormText: "Link formular",
            close: "Închidere",
            locationNotFound: "Locaţia nu a putut fi găsită.",
            setLocation: "Ă_Set Location_ș",
            find: "Ă_Find address or place_ș",
            attachment: "Ataşare",
            toggleDropdown: "Comutare listă derulantă",
            invalidLatLong: "Introduceţi coordonate valide pentru ${latLink}latitudine${closeLink} şi ${lngLink}longitudine${closeLink}.",
            invalidUTM: "Introduceţi coordonate ${openLink}UTM${closeLink} valide.",
            invalidUSNG: "Introduceţi coordonate ${openLink}USNG${closeLink} valide.",
            invalidMGRS: "Introduceţi coordonate ${openLink}MGRS${closeLink} valide.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Selectare&hellip;",
            applyEditsFailedMessage: "Ne pare rău, intrarea dvs. nu poate fi trimisă. Încercaţi din nou.",
            requiredFields: "Există erori. Corectaţi-le mai jos.",
            requiredField: "Ă_(required)_ș",
            error: "Eroare",
            textRangeHintMessage: "Ă_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ș",
            dateRangeHintMessage: "Ă_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ș"
        },
        builder: {
            invalidUser: "Ă_Sorry, you dont have permission to view this item_ș",
            invalidWebmapSelectionAlert: "Ă_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ș",
            invalidWebmapSelectionAlert2: "Ă_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ș",
            selectFieldsText: "Ă_Select Form Fields_ș",
            selectThemeText: "Ă_Select Form Theme_ș",
            webmapText: "Ă_Webmap_ș",
            layerText: "Ă_Layer_ș",
            detailsText: "Ă_Details_ș",
            fieldsText: "Ă_Fields_ș",
            styleText: "Ă_Style_ș",
            optionText: "Ă_Options_ș",
            previewText: "Ă_Preview_ș",
            publishText: "Ă_Publish_ș",
            optionsApplicationText: "Ă_Options_ș",
            titleText: "Ă_Builder_ș",
            descriptionText: "Ă_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ș",
            btnPreviousText: "Ă_Previous_ș",
            btnNextText: "Ă_Next_ș",
            webmapTabTitleText: "Ă_Select a Webmap_ș",
            viewWebmap: "Ă_View webmap_ș",
            btnSelectWebmapText: "Ă_Choose Webmap_ș",
            btnSelectWebmapTextLoading: "Ă_Loading&hellip;_ș",
            layerTabTitleText: "Ă_Select Editable Layer_ș",
            selectLayerLabelText: "Ă_Layer_ș",
            selectLayerDefaultOptionText: "Ă_Select Layer_ș",
            detailsTabTitleText: "Ă_Form Details_ș",
            detailTitleLabelText: "Ă_Title_ș",
            detailLogoLabelText: "Ă_Logo Image_ș",
            descriptionLabelText: "Ă_Help Text (optional)_ș",
            fieldTabFieldHeaderText: "Ă_Field_ș",
            fieldTabLabelHeaderText: "Ă_Label_ș",
            fieldTabDisplayTypeHeaderText: "Ă_Display As_ș",
            selectMenuOption: "Ă_Select Menu_ș",
            selectRadioOption: "Ă_Radio Button_ș",
            selectTextOption: "Ă_Text_ș",
            selectCheckboxOption: "Ă_Checkbox_ș",
            selectMailOption: "Ă_Email_ș",
            selectUrlOption: "Ă_URL_ș",
            selectTextAreaOption: "Ă_Textarea_ș",
            previewApplicationText: "Ă_Preview Application_ș",
            saveApplicationText: "Ă_Save Application_ș",
            saveText: "Ă_Save_ș",
            toggleNavigationText: "Ă_Toggle navigation_ș",
            formPlaceholderText: "Ă_My Form_ș",
            shareBuilderInProgressTitleMessage: "Ă_Publishing GeoForm_ș",
            shareBuilderProgressBarMessage: "Ă_Please Wait&hellip;_ș",
            shareBuilderTitleMessage: "Ă_Success! Item saved_ș",
            shareBuilderTextMessage: "Ă_You can start collecting information by sharing with others_ș",
            shareModalFormText: "Ă_Form Link_ș",
            shareBuilderSuccess: "Ă_Your GeoForm has been updated & published!_ș",
            geoformTitleText: "Ă_Geo Form_ș",
            layerTabText: "Ă_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ș",
            detailsTabText: "Ă_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._ș",
            fieldsTabText: "Ă_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ș",
            styleTabText: "Ă_Style your GeoForm using the themes below based on your preference._ș",
            publishTabText: "Ă_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ș",
            smallHeader: "Ă_Use Small Header_ș",
            pushpinText: "Ă_Push pin_ș",
            doneButtonText: "Ă_View Application Item_ș",
            fieldTabPlaceHolderHeaderText: "Ă_Hint (optional)_ș",
            attachmentLabelText: "Ă_Attchment Label_ș",
            attachmentLabelHint: "Ă_Tell users what type of file to attach._ș",
            attachmentDescription: "Ă_Attachment Description_ș",
            attachmentHint: "Ă_If necessary, you can provide additional attachment instructions here._ș",
            jumbotronDescription: "Ă_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ș",
            shareGeoformText: "Ă_Share Geoform_ș",
            shareDescription: "Ă_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._ș",
            defaultMapExtent: "Ă_Default Map Extent_ș",
            defaultMapExtentDescription: "Ă_The map will reset to the default extent in your web map after submission - this can be disabled at any time._ș",
            pushpinOptionsDescription: "Ă_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ș",
            selectLocationText: "Ă_Select Location By_ș",
            myLocationText: "Ă_My Location_ș",
            searchText: "Ă_Search_ș",
            coordinatesText: "Ă_Latitude & Longitude Coordinates_ș",
            usng: "Ă_USNG Coordinates_ș",
            mgrs: "Ă_MGRS Coordinates_ș",
            utm: "Ă_UTM Coordinates_ș",
            selectLocationSDescription: "Ă_Allow users to select a location using these methods._ș"
        }
    })
);