define({
  "header": {
    "start": "Start",
    "searchStories": "Eigene Storys durchsuchen...",
    "filter": "Filter",
    "sort": "Sortieren",
    "sortColon": "Sortieren:",
    "numResults": "Ergebnisse: {{NUM_RESULTS}}",
    "sortBy": "Sortieren nach",
    "dateModified": "Änderungsdatum",
    "title": "Titel",
    "type": "Typ",
    "views": "Aufrufe",
    "errors": "Fehler",
    "filterBy": "Filtern nach",
    "filterItems": "Elemente filtern",
    "apps": "Apps",
    "sharing": "Freigabe",
    "clearAll": "Alle löschen",
    "clearSearch": "Suche wird gelöscht",
    "logOut": "Abmelden",
    "mainQuote": "Geschichten sind die beste Methode, neue Ideen in die Welt zu setzen.",
    "quoteSource": "Robert McKee",
    "checkYourStories": "Storys prüfen",
    "createStory": "Story erstellen",
    "totalStories": "Anzahl an Storys insgesamt: {{NUM_STORIES}}",
    "noIssues": "In Ordnung",
    "userStories": "Storys von {{USER_NAME}}",
    "headerDisabledTooltip": "Bitte warten – das Wunder ist gleich vollbracht...",
    "notOnTouch": "Auf Touchscreen-Geräten nicht verfügbar"
  },
  "deleteModal": {
    "title": "Löschen bestätigen",
    "warningText": "Möchten Sie diese Story wirklich löschen? Es ist dann nicht möglich, sie wiederherzustellen.",
    "deleteText": "Löschen",
    "cancel": "Abbrechen"
  },
  "loading": {
    "loadingText": "Ihre Storys werden geladen..."
  },
  "cantFindStories": {
    "whereAreStories": "Ihre Story wird nicht angezeigt?",
    "notSeeExplanation": "Unter \"My Stories\" werden nur in ArcGIS gehostete Story Maps aufgeführt, die mit den Anwendungen {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} oder {{SWIPE_SPYGLASS}} erstellt wurden. Weitere Informationen finden Sie in unseren {{FAQ}}.",
    "faq": "FAQ",
    "followingStoriesToUpdate": "Die folgenden Storys, die mit früheren Versionen unserer Anwendungen erstellt wurden, müssen aktualisiert werden, damit sie in \"My Stories\" aufgeführt werden:",
    "gettingStories": "Es wird nach Storys gesucht, die mit früheren Versionen unserer Anwendungen erstellt wurden und aktualisiert werden müssen...",
    "title": "Titel",
    "typeOfStoryMap": "Typ",
    "lastModified": "Zuletzt geändert",
    "allUpToDate": "Es ist keine Aktualisierung von Storys erforderlich, die mit früheren Versionen unserer Anwendungen erstellt wurden.",
    "updateAll": "Alle aktualisieren",
    "errorScanningForStories": "Beim Durchsuchen Ihrer Storys ist ein Fehler aufgetreten.",
    "close": "Schließen",
    "updates": "Updates",
    "updatingNumberOfNumber": "{{CURRENT_NUMBER}} von {{TOTAL}} werden aktualisiert",
    "updatingNumberOfNumberAlt": "{{CURRENT_NUMBER}} / {{TOTAL}} aktualisiert",
    "updateSucceeded": "Aktualisierung erfolgreich!",
    "reloadingStories": "Ihre Storys werden erneut geladen...",
    "errorUpdatingStories": "Beim Aktualisieren Ihrer Storys ist ein Fehler aufgetreten.",
    "partialUpdateMessage": "Erfolgreich aktualisierte Storys: {{NUM_UPDATED}}"
  },
  "signIn": {
    "signInTitle": "Melden Sie sich bei Story Maps an",
    "signInTo": "Melden Sie sich mit Ihrem vorhandenen ArcGIS Online-Konto an, um folgende Schritte auszuführen:",
    "explanationOne": "Interessante Story Maps erstellen, um Ihre Informationen erzählerisch zu vermitteln",
    "explanationTwo": "Ihre Karten und Daten aus ArcGIS Online in Story Maps einbinden",
    "explanationThree": "Ihre Story Maps verwalten und den Status der Inhalte prüfen",
    "dontHaveAccount": "Sie haben noch kein ArcGIS Online-Konto? Registrieren Sie sich für ein(e):",
    "publicAccount": "kostenloses, nicht-kommerzielles öffentliches Konto",
    "orgAccount": "kostenlose ArcGIS-Testversion",
    "timeExpired": "Ihre Anmeldung ist abgelaufen. Melden Sie sich erneut an, um an derselben Stelle fortzufahren.",
    "apiDidntLoad": "Einige Inhalte wurden nicht richtig geladen. Laden Sie die Seite erneut.",
    "needAccount": "Sie benötigen ein Konto?",
    "letsGo": "Los geht's!"
  },
  "sharingLevel": {
    "publicMessage": "Öffentlich",
    "privateMessage": "Privat",
    "organization": "Organisation",
    "changedSharing": "Geändertes Freigabe-Level.",
    "unableToChange": "Freigabe konnte nicht geändert werden.",
    "partOfMap": "Dieses Element befindet sich in einer Karte. Um dessen Freigabe-Level ändern zu können, müssen Sie erst das Freigabe-Level der Karte ändern.",
    "storyPublicContentOrg": "Da Ihre Story öffentlich ist, kann ihr Inhalt nicht nur für Ihre Organisation freigegeben werden",
    "storyPublicContentPrivate": "Da Ihre Story öffentlich ist, kann deren Inhalt nicht privat sein",
    "mapOrg": "Wenn Sie Ihre Karte für Ihre Organisation freigeben, wird das Ihre Story beeinträchtigen.",
    "layerOrg": "Wenn Sie Ihren Layer für Ihre Organisation freigeben, wird das Ihre Story beeinträchtigen.",
    "mapPrivate": "Wenn Sie Ihre Karte als privat einstufen, wird das Ihre Story beeinträchtigen.",
    "layerPrivate": "Wenn Sie Ihren Layer als privat einstufen, wird das Ihre Story beeinträchtigen."
  },
  "collectionList": {
    "advocacy": "Interessenvertretung und Öffentlichkeitsarbeit",
    "architecture": "Architektur und Design",
    "conservation": "Naturschutz und Nachhaltigkeit",
    "culture": "Kultur",
    "destinations": "Reiseziele und Tourismus",
    "disasters": "Katastrophen und Wiederaufbau",
    "economy": "Wirtschaft und Entwicklung",
    "entertainment": "Unterhaltung",
    "history": "Geschichte",
    "infrastructure": "Infrastruktur",
    "marketing": "Marketing",
    "nature": "Natur und Umwelt",
    "news": "Nachrichten und Ereignisse",
    "oceans": "Ozeane",
    "parks": "Parks und Freizeiteinrichtungen",
    "people": "Menschen und Gesellschaft",
    "planning": "Planung und Analyse",
    "publicArt": "Öffentliche Kunst",
    "science": "Wissenschaft und Technologie",
    "sport": "Sport",
    "travelogues": "Reiseberichte"
  },
  "types": {
    "custom": "Benutzerdefiniert",
    "notSpecified": "Typ ist nicht angegeben"
  },
  "storyMap": {
    "shared": "Freigegeben",
    "saveFailed": "Fehler beim Speichern",
    "numViews": "Aufrufe: {{NUM_VIEWS}}",
    "editStory": "Story bearbeiten",
    "viewLive": "Story anzeigen",
    "preview": "Vorschau",
    "deleteButton": "Löschen",
    "modified": "Geändert am {{DATE}}",
    "summary": "Zusammenfassung",
    "loading": "Wird geladen...",
    "collapse": "Ausblenden",
    "close": "Schließen",
    "hide": "Ausblenden",
    "notAvailableWhenBroken": "Ihre Story weist folgende Probleme auf",
    "cantBeDeleted": "Für diese Story ist der Löschschutz aktiviert. Rufen Sie die zugehörige Elementseite in ArcGIS auf, um ihn zu deaktivieren.",
    "shareDialog": {
      "title": "Geben Sie Ihre Story für ein weltweites Publikum frei!",
      "notPublicWarning": "Sie haben Ihre Story für Ihre Organisation freigegeben. Nur Mitglieder Ihrer Organisation können sie anzeigen.",
      "embedStory": "Story einbetten",
      "shortLink": "Kurzer Link",
      "hideHeaderBar": "Titelzeile ausblenden",
      "copied": "Kopiert",
      "small": "klein",
      "medium": "mittel",
      "large": "groß",
      "custom": "benutzerdefiniert",
      "widthAbbreviation": "w",
      "heightAbbreviation": "h",
      "emptyDimension": "Geben Sie eine Dimension ein.",
      "seeExample": "Vorschau der Einbettung anzeigen",
      "removeHeader": "Anwendungskopfzeile ausblenden"
    },
    "maps": {
      "unableRetrieveTitle": "Karten können nicht abgerufen werden",
      "unableRetrieveDescription": "Für diese Story Map konnten keine Karten abgerufen werden."
    },
    "images": {
      "unableRetrieveTitle": "Bilder können nicht abgerufen werden",
      "unableRetrieveDescription": "Für diese Story Map konnten keine Bilder abgerufen werden."
    },
    "tags": {
      "tags": "Tags",
      "collectionTags": "Betreff",
      "selectASubject": "Ein Thema auswählen",
      "save": "Speichern",
      "saved": "Gespeichert",
      "errorSaving": "Fehler beim Speichern",
      "tagTip": "Tipp: Tags ermöglichen die Suche nach Ihrer Story. Je aussagekräftiger die Tags sind, desto mehr Aufmerksamkeit ist Ihrer Arbeit gewiss."
    },
    "submitToGallery": {
      "gallerySubmission": "Story Maps-Galerie",
      "canSubmitIf": "Sie können Ihre Story für die Galerie nominieren, wenn sie die folgenden Bedingungen erfüllt:",
      "hasOwnImage": "benutzerdefinierte Miniaturansicht",
      "chosenSubject": "ein Thema und mind. 1 Tag",
      "chosenSubjectAlt": "ein {{SUBJECT}} und mind. 1 Tag",
      "storyMapTopicSubject": "Thema",
      "sharedPublicly": "öffentlich freigegeben",
      "noBrokenContent": "Keine Probleme",
      "nominateToGallery": "Für die Galerie nominieren",
      "comingSoon": "In Kürze verfügbar!",
      "submitted": "Übergeben",
      "errorSubmitting": "Fehler beim Senden",
      "ourGallery": "Die Story Maps-Galerie",
      "galleryTip": "{{THE_GALLERY}} ist eine kuratierte Auswahl von Story Maps, in der besonders gelungene Beispiele vorgestellt werden. Wenn Ihre Story ausgewählt wurde, wird sie innerhalb von zehn Tagen nach Einreichung hinzugefügt. Aufgrund der Zahl der Nominierungen können wir nicht versprechen, dass Ihre Story aufgenommen wird."
    },
    "placeholders": {
      "noSummary": "Keine Zusammenfassung. Klicken Sie, um eine hinzuzufügen."
    },
    "errors": {
      "cantDeleteStory": "Die Story kann nicht gelöscht werden.",
      "unableToFind": "Inhalt nicht gefunden",
      "unableToRetrieve": "Der Inhalt dieser Story Map konnte nicht abgerufen werden."
    },
    "socialSharing": {
      "availableWhenPublic": "Diese Option ist nach Veröffentlichung Ihrer Story verfügbar."
    },
    "dialog": {
      "back": "Zurück",
      "close": "Schließen",
      "cancel": "Abbrechen"
    },
    "imagePicker": {
      "changeDefault": "Standardbild ändern",
      "changeImage": "Miniaturansicht ändern",
      "uploadImage": "Miniaturansicht hochladen",
      "chooseImage": "Miniaturansicht auswählen",
      "chooseAnImage": "Ein Bild auswählen",
      "notInIEVersion": "Dieses Feature ist in Internet Explorer {{VERSION_NUMBER}} nicht verfügbar.",
      "or": "Oder",
      "uploadAnImage": "Ein Bild hochladen",
      "supportedFileTypes": "Unterstützt .png, .jpg, .gif",
      "imageSizeMessage": "Ihr Bild muss mindestens 286 Px breit und 190 Px hoch sein.",
      "minimumDimensions": "Mindestmaße: 286x190 Pixel",
      "imagesLoading": "Bilder werden geladen...",
      "noImages": "Diese Story weist keine Bilder auf",
      "errorLoading": "Die Bilder in dieser Story können nicht abgerufen werden",
      "clickBelowTip": "Klicken Sie auf die Schaltfläche unten, um ein Bild hochzuladen.",
      "dragAndDrop": "Drag & Drop",
      "cropImage": "Bild zuschneiden",
      "saveImage": "Bild speichern",
      "save": "Speichern",
      "savingImage": "Bild wird gespeichert...",
      "saved": "Gespeichert!",
      "errorSaving": "Ihr Bild kann nicht gespeichert werden.",
      "skipAndCrop": "Überspringen und für mich zuschneiden",
      "wrongFormat": "Dieser Dateityp wird nicht unterstützt.",
      "noCropWarning": "Dieses Bild kann nicht zugeschnitten werden. Es kann trotzdem mit den ursprünglichen Maßen ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}} Pixel) als Miniaturansicht für Ihre Story gespeichert werden."
    }
  },
  "content": {
    "media": {
      "maps": "Karten",
      "images": "Bilder",
      "videos": "Videos",
      "webpages": "Webseiten",
      "tags": "Tags",
      "gallery": "Galerie"
    },
    "headers": {
      "status": "Status",
      "source": "Quelle",
      "name": "Name",
      "shared": "Freigegeben"
    },
    "component": {
      "mapTour": "Punktnummer",
      "bullet": "Aufzählungszeichen",
      "tab": "Registerkarte",
      "accordion": "Abschnitt",
      "mapJournal": "Abschnitt"
    },
    "titleType": {
      "mapTour": "Beschriftung",
      "mapJournal": "URL",
      "mapSeries": "URL"
    },
    "actions": {
      "viewMap": "Karte anzeigen",
      "editMap": "Karte bearbeiten",
      "fix": "Fix",
      "viewLayer": "Layer anzeigen"
    },
    "contentType": {
      "mainStage": "Aktion der Hauptanzeige",
      "sidePanel": "description"
    },
    "notification": {
      "refreshExplanation": "Die Story erneut prüfen",
      "checking": "Wird überprüft...",
      "foundSomeIssues": "Wir haben einige Probleme ermittelt.",
      "noIssuesFound": "Keine Probleme gefunden",
      "storyPublic": "Ihre Story ist jetzt veröffentlicht.",
      "storyOrg": "Ihre Story wurde jetzt für Ihre Organisation freigegeben.",
      "storyPrivate": "Ihre Story ist jetzt als privat eingestuft.",
      "mapPublic": "Ihre Karte ist jetzt veröffentlicht.",
      "mapOrg": "Ihre Karte wurde jetzt für Ihre Organisation freigegeben.",
      "mapPrivate": "Ihre Karte ist jetzt als privat eingestuft.",
      "layerPublic": "Ihr Layer ist jetzt veröffentlicht.",
      "layerOrg": "Ihr Layer wurde jetzt für Ihre Organisation freigegeben.",
      "layerPrivate": "Ihr Layer ist jetzt als privat eingestuft.",
      "contentPublic": "Ihr Inhalt ist jetzt veröffentlicht.",
      "contentOrg": "Ihr Inhalt wurde jetzt für Ihre Organisation freigegeben.",
      "contentPrivate": "Ihr Inhalt ist jetzt als privat eingestuft.",
      "storyAndContentPublic": "Ihre Story und deren Inhalt sind jetzt öffentlich.",
      "storyAndContentOrg": "Ihre Story und deren Inhalt wurden jetzt für Ihre Organisation freigegeben.",
      "storyAndContentPrivate": "Ihre Story und deren Inhalt sind jetzt als privat eingestuft.",
      "shareBulkPrompt": "Möchten Sie den Inhalt Ihrer Story entsprechend freigeben?",
      "layersPublic": "Einige Layer wurden auch öffentlich freigegeben",
      "layersOrg": "Einige Layer wurden auch für Ihre Organisation freigegeben",
      "layersPrivate": "Einige Layer wurden auch als privat gekennzeichnet",
      "mapsPublic": "Einige Karten wurden auch öffentlich freigegeben",
      "mapsOrg": "Einige Karten wurden auch für Ihre Organisation freigegeben",
      "mapsPrivate": "Einige Karten wurden auch als privat gekennzeichnet",
      "layersAndMapsPublic": "Einige Karten und Layer wurden auch öffentlich freigegeben",
      "layersAndMapsOrg": "Einige Karten und Layer wurden auch für Ihre Organisation freigegeben",
      "layersAndMapsPrivate": "Einige Karten und Layer wurden auch als privat gekennzeichnet",
      "yes": "Ja",
      "no": "Nein",
      "premiumPublicSuccess": "Ihre Premium-Inhalte sind nun öffentlich zugänglich",
      "subscriptionPublicSuccess": "Ihr Subskriptionsinhalt ist nun öffentlich zugänglich"
    },
    "errors": {
      "publicDisabled": "Die öffentliche Freigabe wurde von einem Administrator deaktiviert",
      "orgDisabled": "Die Freigabe für Ihre Organisation wurde von einem Administrator deaktiviert",
      "noMapName": "Kartenname konnte nicht abgerufen werden",
      "notPublic": "NICHT ÖFFENTLICH",
      "inaccessible": "ZUGRIFF NICHT MÖGLICH",
      "deleted": "GELÖSCHT",
      "cantAccessVideo": "Auf das Video konnte nicht zugegriffen werden.",
      "noStoriesFound": "Wir konnten keine Story Maps in Ihren Inhalten finden.",
      "cantShowStories": "Ihre Story Maps können nicht angezeigt werden. Versuchen Sie es später erneut.",
      "consolationSearch": "Es konnten keine Storys gefunden werden.",
      "notCompatibleWithBrowser": "\"My Stories\" wird von Internet Explorer-Versionen unter {{VERSION_NUMBER}} nicht unterstützt.",
      "pleaseUpdateBrowser": "Aktualisieren Sie Ihren Browser.",
      "searchTip": "Bitte versuchen Sie, es ein wenig zu vereinfachen.",
      "consolationNoStories": "Willkommen bei My Stories!",
      "noStoriesTip": "Schauen Sie auf die Apps-Seite, um Ihre erste Story Map zu erstellen.",
      "letsGo": "Los geht's",
      "cantChangeSharingLevel": "Freigabe-Level konnte nicht geändert werden",
      "cantChangeSharingLevels": "Freigabe-Level konnten nicht geändert werden",
      "errorUpdatingTitle": "Fehler beim Aktualisieren des Titels",
      "errorUpdatingSummary": "Fehler beim Aktualisieren der Zusammenfassung",
      "noEmptyTitle": "Titel darf nicht leer sein",
      "cantUpdatePremiumContent": "Premium-Inhalt kann nicht aktualisiert werden",
      "cantUpdateSubscriptionContent": "Subskriptionsinhalt kann nicht aktualisiert werden",
      "createFirstStory": "Meine erste Story erstellen"
    },
    "tooltipErrors": {
      "mapHasBeenDeleted": "Karte wurde gelöscht",
      "layerHasBeenDeleted": "Layer wurde gelöscht",
      "mapIsInaccessible": "Zugriff auf Karte nicht möglich",
      "layerIsInaccessible": "Zugriff auf Layer nicht möglich",
      "mapNotYoursNotAccessible": "Die Karte ist im Besitz eines anderen Benutzers; daher ist der Zugriff nicht möglich.",
      "layerServiceOkItemNot": "Der Layer wurde als Element hinzugefügt, das entweder gelöscht wurde oder auf das nicht zugegriffen werden kann.",
      "layerNotYoursNotAccessible": "Der Layer ist im Besitz eines anderen Benutzers; daher ist der Zugriff nicht möglich.",
      "mapOthersSharedBelowLevel": "Die Karte ist nicht in Ihrem Besitz und auch nicht öffentlich.",
      "layerOthersSharedBelowLevel": "Der Layer ist nicht in Ihrem Besitz und auch nicht öffentlich.",
      "noMapNoDetails": "Ohne Details zur Karte ist keine Aussage zu den Layers möglich.",
      "mapIsPrivate": "Die Karte ist als privat eingestuft.",
      "mapIsOrg": "Die Karte ist ausschließlich für Ihre Organisation freigegeben.",
      "layerIsPrivate": "Der Layer ist als privat eingestuft.",
      "layerIsOrg": "Der Layer ist ausschließlich für Ihre Organisation freigegeben.",
      "imageInaccessible": "Zugriff auf dieses Bild nicht möglich",
      "videoInaccessible": "Zugriff auf dieses Video nicht möglich",
      "webpageInaccessible": "Zugriff auf diese Webseite nicht möglich",
      "layerSecureService": "Der Layer ist ein sicherer Service.",
      "mapSecureService": "Die Karte ist ein sicherer Service.",
      "layerConsumesCredits": "Der Layer ist Premium-Inhalt und verbraucht Credits.",
      "layerSubscriptionContent": "Der Layer ist Subskriptionsinhalt.",
      "mapConsumesCredits": "Die Karte ist Premium-Inhalt und verbraucht Credits.",
      "mapSubscriptionContent": "Die Karte ist Subskriptionsinhalt."
    },
    "tooltipWarnings": {
      "cantScanThisTypeAlt": "Dieser Layer-Typ kann nicht überprüft werden.",
      "cantScanThisType": "Der Layer ist ein Layer-Typ, der nicht überprüft werden kann.",
      "webpageNotScanned": "Webseiten werden nicht auf Probleme überprüft.",
      "ignoredIssue": "Sie haben einen Fehler in diesem Layer ignoriert. Laden Sie die Seite erneut, und überprüfen Sie diese Story noch einmal, um den Fehler wieder anzuzeigen.",
      "ignoredIssueBuilder": "Sie haben einen Fehler in diesem Layer ignoriert. Laden Sie den Builder erneut, um den Fehler erneut zu überprüfen."
    },
    "scanningErrors": {
      "deletedMap": "Gelöschter Inhalt",
      "inaccessibleMap": "Nicht zugänglicher Karteninhalt",
      "notYoursNotAccessible": "Der Inhalt ist nicht in Ihrem Besit\tz und auch nicht öffentlich.",
      "serviceOkItemNot": "Funktionierende Layer, aber nicht zugängliche Elemente",
      "someContentNotPublic": "Der Inhalt ist nicht öffentlich freigeben.",
      "someContentPrivate": "Privater Inhalt",
      "othersSharedBelowLevel": "Der Inhalt ist nicht in Ihrem Besitz und auch nicht öffentlich.",
      "premiumContent": "Premium-Inhalte",
      "subscriptionContent": "Subskriptionsinhalt",
      "secureService": "Sichere Dienste",
      "inaccessibleImage": "Nicht zugängliche Bilder",
      "inaccessibleVideo": "Nicht zugängliche Videos",
      "inaccessibleWebpage": "Nicht zugängliche Webseiten"
    },
    "scanningErrorTips": {
      "deletedMapTip": "Tipp: Bearbeiten Sie Ihre Webkarte und entfernen Sie den fehlerhaften Inhalt, oder entfernen Sie die Webkarte aus Ihrer Story.",
      "inaccessibleMapTip": "Tipp: Bearbeiten Sie Ihre Webkarte und entfernen Sie den fehlerhaften Inhalt, oder entfernen Sie die Webkarte aus Ihrer Story.",
      "notYoursNotAccessibleTip": "Tipp: Bearbeiten Sie Ihre Webkarte und entfernen Sie den Layer, oder entfernen Sie die Webkarte aus Ihrer Story.",
      "serviceOkItemNotTip": "Es wurden Layer als Elemente hinzugefügt, die entweder gelöscht wurden oder auf die nicht zugegriffen werden kann. Zwar funktionieren die Layer, doch kann sich dies auf Ihre Karte auswirken (Pop-ups, Symbolisierung).",
      "ignore": "Ignorieren",
      "fix": "Fix",
      "clickToShareOrg": "Klicken Sie auf die Schaltfläche, um die vorliegenden Inhalte für Ihre Organisation freizugeben, oder ändern Sie jedes Element manuell, indem Sie auf die jeweilige Freigabeschaltfläche klicken.",
      "clickToSharePublic": "Klicken Sie auf die Schaltfläche, um die vorliegenden Inhalte öffentlich freizugeben, oder ändern Sie jedes Element manuell, indem Sie auf die jeweilige Freigabeschaltfläche klicken.",
      "shareOrg": "Für Ihre Organisation freigeben",
      "sharePublicly": "Öffentlich freigeben",
      "othersSharedBelowLevelTip": "Tipp: Manche Inhalte Ihrer Story befinden sich im Besitz von {{USER_NAME}}, weshalb diese möglicherweise Dritten nicht angezeigt werden.",
      "secureServiceTip": "Tipp: Entfernen Sie den sicheren Service aus Ihrer Story, oder gehen Sie wie {{HERE}} beschrieben vor.",
      "blogArticle": "hier",
      "premiumContentTip": "Ihre Story enthält Premium-Inhalte, die nach der Veröffentlichung {{CREDITS}} verbrauchen. Veröffentlichen Sie Ihre Story, und setzen Sie den Vorgang fort, oder entfernen Sie die Layer aus Ihrer Story.",
      "premiumContentPublicTip": "Ihre Story enthält Premium-Inhalte, die {{CREDITS}} verbrauchen, wenn sie öffentlich verfügbar sind. Bestätigen Sie, dass diese Layer veröffentlicht werden sollen, oder entfernen Sie die Layer aus Ihrer Story.",
      "subscriptionContentTip": "Ihre Story enthält Subskriptionsinhalt, der standardmäßig nicht öffentlich verfügbar ist. Bestätigen Sie, dass Sie diese Layer zur Verfügung stellen möchten (es werden keine Credits verbraucht), oder entfernen Sie die Layer aus Ihrer Story.",
      "credits": "Credits",
      "makePublic": "Veröffentlichen",
      "confirm": "Bestätigen",
      "inaccessibleImageTip": "Tipp: Stellen Sie das fehlende Bild bereit oder entfernen Sie den Verweis darauf.",
      "inaccessibleVideoTip": "Tipp: Stellen Sie das fehlende Video bereit oder entfernen Sie den Verweis darauf.",
      "inaccessibleWebpageTip": "Tipp: Stellen Sie die fehlende Webseite bereit oder entfernen Sie den Verweis darauf."
    },
    "removeLayer": {
      "title": "Layer-Problem beheben",
      "layersWithIssue": "Layer mit diesem Problem: {{NUM_WITH_ISSUE}}",
      "issueExplanation": "Der Layer {{LAYER_NAME}} wurde als Element hinzugefügt, auf das nicht zugegriffen werden kann oder das gelöscht wurde. Zwar funktioniert der Layer, doch kann sich dies auf Ihre Karte auswirken (Pop-ups, Symbolisierung). Es ist uns nicht möglich festzustellen, ob das Element für Ihre Story relevant war.",
      "issueSolution": "Um dieses Problem zu beheben, können Sie Ihre Karte bearbeiten, den Layer entfernen und ihn anschließend erneut mithilfe der folgenden URL in die Karte einfügen:",
      "editMap": "Die Karte bearbeiten",
      "clickBelowWhenDone": "Wenn Sie die Bearbeitung beendet haben, klicken Sie auf die folgende Schaltfläche:",
      "rescanAndClose": "Erneut prüfen und schließen"
    },
    "info": {
      "ownedBy": "Dieses Element ist im Besitz von {{USER_NAME}}.",
      "unknownUser": "jemand anderem",
      "untitledSection": "(Unbenannter Abschnitt)",
      "introRecord": "Einführung"
    },
    "layers": {
      "layersHeader": "Layer",
      "noLayers": "(Keine Layer)",
      "basemapParens": "(Grundkarte)"
    },
    "images": {
      "thumbnails": "Miniaturansicht",
      "thumbnail": "Miniaturansicht",
      "thumbnailParens": "(Miniaturbild)"
    },
    "general": {
      "noTitle": "(ohne Titel)",
      "loading": "Wird geladen..."
    }
  },
  "infographics": {
    "mapJournal": {
      "firstTitle": "Abschnitte",
      "secondTitle": "Style",
      "secondValueA": "Seitenfenster",
      "secondValueB": "unverankertes Fenster",
      "thirdTitle": "Karten"
    },
    "mapTour": {
      "firstTitle": "Tour-Punkte",
      "secondTitle": "Style",
      "secondValueA": "integriert",
      "secondValueB": "mit drei Fenstern",
      "thirdTitle": "Grundkarte",
      "thirdValueLoading": "Wird geladen...",
      "thirdValueUnknown": "Unbekannt"
    },
    "mapSeries": {
      "firstTitleA": "Aufzählungszeichen",
      "firstTitleB": "Abschnitte",
      "firstTitleC": "Registerkarten",
      "secondTitle": "Style",
      "secondValueA": "mit Aufzählungszeichen",
      "secondValueB": "Side Accordion",
      "secondValueC": "mit Registerkarten",
      "thirdTitle": "Karten"
    },
    "swipeSpyglass": {
      "firstTitle": "Points of Interest",
      "secondTitle": "Style",
      "secondValueA": "vergleichen",
      "secondValueB": "Fernglas",
      "thirdTitle": "Karten"
    },
    "crowdsource": {
      "firstTitle": "Beiträge",
      "secondTitle": "Style",
      "secondValueA": "Seitenfenster",
      "secondValueB": "Gestapelt",
      "thirdTitle": "Grundkarte",
      "thirdValueLoading": "Wird geladen...",
      "thirdValueUnknown": "Unbekannt"
    }
  },
  "progress": {
    "checkingStories": "Ihre Storys werden auf Probleme überprüft...",
    "stop": "Stoppen",
    "exit": "Beenden",
    "dismiss": "Verwerfen",
    "done": "Fertig.",
    "noStoriesWithIssuesLower": "Keine Probleme gefunden!",
    "storiesErrorFree": "Offenbar sind Ihre Storys fehlerfrei.",
    "scanAllError": "Durchsuchen nicht möglich -- eine oder mehrere Ihrer Storys konnten nicht gefunden werden.",
    "scanProgress": "{{NUM_SCANNED}} von {{NUM_TOTAL}}",
    "scanStopped": "Durchsuchte Storys: {{NUM_SCANNED}}, Storys mit Problemen: {{ISSUE_STORIES}}",
    "storiesWithIssues": "Storys mit Problemen: {{NUM_STORIES}}"
  },
  "newStories": {
    "newStoriesFound": "Sie haben offenbar eine neue Story erstellt.",
    "includeStories": "Storys aktualisieren",
    "notWhileScanning": "Dies ist nach Abschluss der Überprüfung verfügbar"
  }
});