define(
	 ({
		header: {
			start: "ä_start___Ü",
			searchStories: "ä_Search your stories________Ü...",
			filter: "ä_Filter___Ü",
			sort: "ä_Sort__Ü",
			sortColon: "ä_Sort___Ü:",
			numResults: "ä_Results: {{NUM_RESULTS}}________Ü",
			sortBy: "ä_Sort by___Ü",
			dateModified: "ä_Date modified_____Ü",
			title: "ä_Title___Ü",
			type: "ä_Type__Ü",
			views: "ä_Views___Ü",
			errors: "ä_Errors___Ü",
			filterBy: "ä_Filter by____Ü",
			filterItems: "ä_Filter Items_____Ü",
			apps: "ä_Apps__Ü",
			sharing: "ä_Sharing___Ü",
			clearAll: "ä_Clear all____Ü",
			clearSearch: "ä_Clears the search______Ü",
			logOut: "ä_Log Out___Ü",
			mainQuote: "ä_Storytelling is the most powerful way to put ideas into the world today_______________________Ü.",
			quoteSource: "ä_Robert McKee_____Ü",
			checkYourStories: "ä_Check Stories_____Ü",
			createStory: "ä_Create Story_____Ü",
			totalStories: "ä_Total stories: {{NUM_STORIES}}__________Ü",
			noIssues: "ä_All good___Ü",
			userStories: "ä_Stories of {{USER_NAME}}________Ü",
			headerDisabledTooltip: "ä_Please wait while we work some magic_____________Ü...",
			notOnTouch: "ä_Not available on touch devices__________Ü",
		},
		deleteModal: {
			title: "ä_Confirm Delete_____Ü",
			warningText: "ä_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________Ü.",
			deleteText: "ä_Delete___Ü",
			cancel: "ä_Cancel___Ü"
		},
		loading: {
			loadingText: "ä_Loading your stories________Ü..."
		},
		cantFindStories: {
			whereAreStories: "ä_Not seeing your story________Ü?",
			notSeeExplanation: "ä_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________Ü.",
			faq: "ä_FAQ__Ü",
			followingStoriesToUpdate: "ä_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________Ü:",
			gettingStories: "ä_Searching for stories created with early versions of our applications that need to be updated______________________________Ü...",
			title: "ä_Title___Ü",
			typeOfStoryMap: "ä_Type__Ü",
			lastModified: "ä_Last modified_____Ü",
			allUpToDate: "ä_No stories created with early versions of our applications need to be updated________________________Ü.",
			updateAll: "ä_Update All____Ü",
			errorScanningForStories: "ä_There was an error searching your stories______________Ü.",
			close: "ä_Close___Ü",
			updates: "ä_Updates___Ü",
			updatingNumberOfNumber: "ä_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________Ü",
			updatingNumberOfNumberAlt: "ä_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________Ü",
			updateSucceeded: "ä_Update succeeded______Ü!",
			reloadingStories: "ä_Reloading your stories_________Ü...",
			errorUpdatingStories: "ä_There was an error updating your stories_____________Ü.",
			partialUpdateMessage: "ä_Stories updated successfully: {{NUM_UPDATED}}_______________Ü"
		},
		signIn: {
			signInTitle: "ä_Sign in to Story Maps_______Ü",
			signInTo: "ä_Sign in with your existing ArcGIS Online account to_________________Ü:",
			explanationOne: "ä_Create compelling story maps to tell your stories________________Ü.",
			explanationTwo: "ä_Use your maps and data from ArcGIS Online in your story maps___________________Ü.",
			explanationThree: "ä_Manage your story maps and check the status of their content___________________Ü.",
			dontHaveAccount: "ä_Don't have an ArcGIS Online account? Sign up for a________________Ü:",
			publicAccount: "ä_Free non-commercial public account___________Ü",
			orgAccount: "ä_Free trial ArcGIS subscription__________Ü",
			timeExpired: "ä_Your sign-in expired. Sign in again to pick up where you left off_____________________Ü.",
			apiDidntLoad: "ä_Something isn't loading correctly. Try refreshing the page___________________Ü.",
			needAccount: "ä_Need an account______Ü?",
			letsGo: "ä_Let's go____Ü!"
		},
		sharingLevel: {
			publicMessage: "ä_Public___Ü",
			privateMessage: "ä_Private___Ü",
			organization: "ä_Organization_____Ü",
			changedSharing: "ä_Changed sharing level________Ü.",
			unableToChange: "ä_Unable to change sharing_________Ü.",
			partOfMap: "ä_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________Ü.",
			storyPublicContentOrg: "ä_Your story is public, so its content can't be shared only with your organization_________________________Ü",
			storyPublicContentPrivate: "ä_Your story is public, so its content can't be private_________________Ü",
			mapOrg: "ä_Sharing your map to your organization would break your story___________________Ü",
			layerOrg: "ä_Sharing your layer to your organization would break your story____________________Ü",
			mapPrivate: "ä_Making your map private would break your story_______________Ü",
			layerPrivate: "ä_Making your layer private would break your story_______________Ü"
		},
		collectionList: {
			advocacy: "ä_Advocacy and Outreach_______Ü",
			architecture: "ä_Architecture and Design________Ü",
			conservation: "ä_Conservation and Sustainability__________Ü",
			culture: "ä_Culture___Ü",
			destinations: "ä_Destinations and Tourism________Ü",
			disasters: "ä_Disasters and Recovery________Ü",
			economy: "ä_Economy and Development________Ü",
			entertainment: "ä_Entertainment_____Ü",
			history: "ä_History___Ü",
			infrastructure: "ä_Infrastructure_____Ü",
			marketing: "ä_Marketing____Ü",
			nature: "ä_Nature and Environment________Ü",
			news: "ä_News and Events______Ü",
			oceans: "ä_Oceans___Ü",
			parks: "ä_Parks and Recreation_______Ü",
			people: "ä_People and Society______Ü",
			planning: "ä_Planning and Analysis_______Ü",
			publicArt: "ä_Public Art____Ü",
			science: "ä_Science and Technology________Ü",
			sport: "ä_Sport___Ü",
			travelogues: "ä_Travelogues____Ü"
		},
		types: {
			custom: "ä_Custom___Ü",
			notSpecified: "ä_Type not specified______Ü"
		},
		storyMap: {
			shared: "ä_Shared___Ü",
			saveFailed: "ä_Error saving_____Ü",
			numViews: "ä_Views: {{NUM_VIEWS}}_______Ü",
			editStory: "ä_Edit Story____Ü",
			viewLive: "ä_View Live____Ü",
			preview: "ä_Preview___Ü",
			deleteButton: "ä_Delete___Ü",
			modified: "ä_Modified {{DATE}}______Ü",
			summary: "ä_Summary___Ü",
			loading: "ä_Loading____Ü...",
			collapse: "ä_collapse___Ü",
			close: "ä_close___Ü",
			hide: "ä_hide__Ü",
			notAvailableWhenBroken: "ä_Your story has issues below_________Ü",
			cantBeDeleted: "ä_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________Ü",
			shareDialog: {
				title: "ä_Share your story with the world___________Ü!",
				notPublicWarning: "ä_Your story is shared with your organization. Only members of your organization will be able to view it________________________________Ü.",
				embedStory: "ä_Embed your story______Ü",
				shortLink: "ä_Shortlink____Ü",
				hideHeaderBar: "ä_Hide header bar______Ü",
				copied: "ä_Copied___Ü",
				small: "ä_small___Ü",
				medium: "ä_medium___Ü",
				large: "ä_large___Ü",
				custom: "ä_custom___Ü",
				widthAbbreviation: "ä_w_Ü",
				heightAbbreviation: "ä_h_Ü",
				emptyDimension: "ä_Enter a dimension______Ü.",
				seeExample: "ä_Preview your embed______Ü",
				removeHeader: "ä_Hide application header________Ü"
			},
			maps: {
				unableRetrieveTitle: "ä_Unable to retrieve maps________Ü",
				unableRetrieveDescription: "ä_We weren't able to retrieve maps for this story map_________________Ü."
			},
			images: {
				unableRetrieveTitle: "ä_Unable to retrieve images_________Ü",
				unableRetrieveDescription: "ä_We weren't able to retrieve images for this story map_________________Ü."
			},
			tags: {
				tags: "ä_Tags__Ü",
				collectionTags: "ä_Subject___Ü",
				selectASubject: "ä_Select a subject______Ü",
				save: "ä_Save__Ü",
				saved: "ä_Saved___Ü",
				errorSaving: "ä_Error saving_____Ü",
				tagTip: "ä_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________Ü."
			},
			submitToGallery: {
				gallerySubmission: "ä_Story Maps Gallery______Ü",
				canSubmitIf: "ä_You can nominate your story to the gallery if it contains the following_______________________Ü:",
				hasOwnImage: "ä_Custom thumbnail______Ü",
				chosenSubject: "ä_A subject and some tags________Ü",
				chosenSubjectAlt: "ä_A {{SUBJECT}} and some tags_________Ü",
				storyMapTopicSubject: "ä_subject___Ü",
				sharedPublicly: "ä_Shared publicly______Ü",
				noBrokenContent: "ä_No broken content______Ü",
				nominateToGallery: "ä_Nominate to Gallery_______Ü",
				comingSoon: "ä_Coming soon_____Ü!",
				submitted: "ä_Submitted____Ü",
				errorSubmitting: "ä_Error submitting______Ü",
				ourGallery: "ä_The Story Maps gallery________Ü",
				galleryTip: "ä_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________Ü."
			},
			placeholders: {
				noSummary: "ä_No summary, click to add one__________Ü."
			},
			errors: {
				cantDeleteStory: "ä_Unable to delete story________Ü.",
				unableToFind: "ä_Unable to find content________Ü",
				unableToRetrieve: "ä_We weren't able to retrieve the content for this story map___________________Ü."
			},
			socialSharing: {
				availableWhenPublic: "ä_This option will be available when your story is public__________________Ü"
			},
			dialog: {
				back: "ä_Back__Ü",
				close: "ä_Close___Ü",
				cancel: "ä_Cancel___Ü"
			},
			imagePicker: {
				changeDefault: "ä_Change the default image________Ü",
				changeImage: "ä_Change thumbnail______Ü",
				uploadImage: "ä_Upload thumbnail______Ü",
				chooseImage: "ä_Choose thumbnail______Ü",
				chooseAnImage: "ä_Choose an Image______Ü",
				notInIEVersion: "ä_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________Ü.",
				or: "ä_Or__Ü",
				uploadAnImage: "ä_Upload an Image______Ü",
				supportedFileTypes: "ä_Supports .png, .jpg, .gif_________Ü",
				imageSizeMessage: "ä_Your image needs to be at least 286 px wide by 190 px tall___________________Ü.",
				minimumDimensions: "ä_Minimum: 286 x 190px_______Ü",
				imagesLoading: "ä_Loading images______Ü...",
				noImages: "ä_This story has no images________Ü",
				errorLoading: "ä_Unable to retrieve the images in this story______________Ü",
				clickBelowTip: "ä_Click the button below to upload an image______________Ü.",
				dragAndDrop: "ä_Drag and Drop_____Ü",
				cropImage: "ä_Crop Image____Ü",
				saveImage: "ä_Save Image____Ü",
				save: "ä_Save__Ü",
				savingImage: "ä_Saving your image_______Ü...",
				saved: "ä_Saved___Ü!",
				errorSaving: "ä_Unable to save your image_________Ü.",
				skipAndCrop: "ä_Skip and Crop for me_______Ü",
				wrongFormat: "ä_This file type is not supported___________Ü.",
				noCropWarning: "ä_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________Ü."
			}
		},
		content: {
			media: {
				maps: "ä_Maps__Ü",
				images: "ä_Images___Ü",
				videos: "ä_Videos___Ü",
				webpages: "ä_Webpages___Ü",
				tags: "ä_Tags__Ü",
				gallery: "ä_Gallery___Ü"
			},
			headers: {
				status: "ä_Status___Ü",
				source: "ä_Source___Ü",
				name: "ä_Name__Ü",
				shared: "ä_Shared___Ü"
			},
			component: {
				mapTour: "ä_Point Number_____Ü",
				bullet: "ä_Bullet___Ü",
				tab: "ä_Tab__Ü",
				accordion: "ä_Section___Ü",
				mapJournal: "ä_Section___Ü"
			},
			titleType: {
				mapTour: "ä_Caption___Ü",
				mapJournal: "ä_URL__Ü",
				mapSeries: "ä_URL__Ü"
			},
			actions: {
				viewMap: "ä_View Map___Ü",
				editMap: "ä_Edit Map___Ü",
				fix: "ä_Fix__Ü",
				viewLayer: "ä_View Layer____Ü"
			},
			contentType: {
				mainStage: "ä_main stage action______Ü",
				sidePanel: "ä_description____Ü"
			},
			notification: {
				refreshExplanation: "ä_Check your story again________Ü",
				checking: "ä_Checking____Ü...",
				foundSomeIssues: "ä_We found some issues_______Ü",
				noIssuesFound: "ä_No issues found______Ü",
				storyPublic: "ä_Your story is now public________Ü",
				storyOrg: "ä_Your story is now shared to your organization_______________Ü",
				storyPrivate: "ä_Your story is now private_________Ü",
				mapPublic: "ä_Your map is now public________Ü",
				mapOrg: "ä_Your map is now shared to your organization______________Ü",
				mapPrivate: "ä_Your map is now private________Ü",
				layerPublic: "ä_Your layer is now public________Ü",
				layerOrg: "ä_Your layer is now shared to your organization_______________Ü",
				layerPrivate: "ä_Your layer is now private_________Ü",
				contentPublic: "ä_Your content is now public_________Ü",
				contentOrg: "ä_Your content is now shared to your organization_______________Ü",
				contentPrivate: "ä_Your content is now private_________Ü",
				storyAndContentPublic: "ä_Your story and its content are now public_____________Ü",
				storyAndContentOrg: "ä_Your story and its content are now shared to your organization____________________Ü",
				storyAndContentPrivate: "ä_Your story and its content are now private______________Ü",
				shareBulkPrompt: "ä_Do you want to share your storyâ€™s content accordingly__________________Ü?",
				layersPublic: "ä_Some layers have also been shared publicly______________Ü",
				layersOrg: "ä_Some layers have also been shared with your organization__________________Ü",
				layersPrivate: "ä_Some layers have also been made private_____________Ü",
				mapsPublic: "ä_Some maps have also been shared publicly_____________Ü",
				mapsOrg: "ä_Some maps have also been shared with your organization_________________Ü",
				mapsPrivate: "ä_Some maps have also been made private____________Ü",
				layersAndMapsPublic: "ä_Some maps and layers have also been shared publicly________________Ü",
				layersAndMapsOrg: "ä_Some maps and layers have also been shared with your organization_____________________Ü",
				layersAndMapsPrivate: "ä_Some maps and layers have also been made private_______________Ü",
				yes: "ä_Yes__Ü",
				no: "ä_No__Ü",
				premiumPublicSuccess: "ä_Your premium content is now publicly accessible_______________Ü",
				subscriptionPublicSuccess: "ä_Your subscription content is now publicly accessible_________________Ü"
			},
			errors: {
				publicDisabled: "ä_Sharing publicly has been disabled by the Administrator__________________Ü",
				noMapName: "ä_Could Not Retrieve Map Name_________Ü",
				notPublic: "ä_NOT PUBLIC____Ü",
				inaccessible: "ä_INACCESSIBLE_____Ü",
				deleted: "ä_DELETED___Ü",
				cantAccessVideo: "ä_Could Not Access Video________Ü",
				noStoriesFound: "ä_We could not find any Story Maps in your content________________Ü.",
				cantShowStories: "ä_Unable to show your story maps. Please try again later__________________Ü.",
				consolationSearch: "ä_We couldn't find any stories__________Ü.",
				notCompatibleWithBrowser : "ä_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________Ü.",
				pleaseUpdateBrowser: "ä_Please update your browser_________Ü.",
				searchTip: "ä_Try and simplify it a bit_________Ü.",
				consolationNoStories: "ä_Welcome to My Stories________Ü!",
				noStoriesTip: "ä_To make your first story map, check out the Apps page_________________Ü.",
				letsGo: "ä_Let's Go___Ü",
				cantChangeSharingLevel: "ä_Unable to change sharing level__________Ü",
				cantChangeSharingLevels: "ä_Unable to change sharing levels__________Ü",
				errorUpdatingTitle: "ä_Error updating title_______Ü",
				errorUpdatingSummary: "ä_Error updating summary________Ü",
				noEmptyTitle: "ä_Title cannot be empty_______Ü",
				cantUpdatePremiumContent: "ä_Unable to update premium content___________Ü",
				cantUpdateSubscriptionContent: "ä_Unable to update subscription content____________Ü",
				createFirstStory: "ä_Create My First Story_______Ü"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "ä_Map has been deleted_______Ü",
				layerHasBeenDeleted: "ä_Layer has been deleted________Ü",
				mapIsInaccessible: "ä_Map is inaccessible_______Ü",
				layerIsInaccessible: "ä_Layer is inaccessible_______Ü",
				mapNotYoursNotAccessible: "ä_Map is owned by someone else and isn't accessible________________Ü",
				layerServiceOkItemNot: "ä_Layer was added as an item that is deleted or inaccessible__________________Ü",
				layerNotYoursNotAccessible: "ä_Layer is owned by someone else and isn't accessible________________Ü",
				mapOthersSharedBelowLevel: "ä_Map is not owned by you and is not public_____________Ü",
				layerOthersSharedBelowLevel: "ä_Layer is not owned by you and is not public______________Ü",
				noMapNoDetails: "ä_Without the map details, we can't tell you anything about the layers_____________________Ü",
				mapIsPrivate: "ä_Map is private_____Ü",
				mapIsOrg: "ä_Map is only shared in your organization_____________Ü",
				layerIsPrivate: "ä_Layer is private______Ü",
				layerIsOrg: "ä_Layer is only shared in your organization_____________Ü",
				imageInaccessible: "ä_This image is inaccessible_________Ü",
				videoInaccessible: "ä_This video is inaccessible_________Ü",
				webpageInaccessible: "ä_This web page is inaccessible__________Ü",
				layerSecureService: "ä_Layer is a secure service_________Ü",
				mapSecureService: "ä_Map is a secure service________Ü",
				layerConsumesCredits: "ä_Layer is premium content and consumes credits_______________Ü",
				layerSubscriptionContent: "ä_Layer is subscription content__________Ü",
				mapConsumesCredits: "ä_Map is premium content and consumes credits______________Ü",
				mapSubscriptionContent: "ä_Map is subscription content_________Ü"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "ä_We're not able to check this type of layer______________Ü",
				cantScanThisType: "ä_Layer is not a type of layer we can check_____________Ü",
				webpageNotScanned: "ä_Webpages are not checked for issues____________Ü"
			},
			scanningErrors: {
				deletedMap: "ä_Deleted content______Ü",
				inaccessibleMap: "ä_Inaccessible map content________Ü",
				notYoursNotAccessible: "ä_Content not owned by you and not public_____________Ü",
				serviceOkItemNot: "ä_Working layers but inaccessible items____________Ü",
				someContentNotPublic: "ä_Content not shared publicly_________Ü",
				someContentPrivate: "ä_Private content______Ü",
				othersSharedBelowLevel: "ä_Content not owned by you and not public_____________Ü",
				premiumContent: "ä_Premium content______Ü",
				subscriptionContent: "ä_Subscription content_______Ü",
				secureService: "ä_Secure services______Ü",
				inaccessibleImage: "ä_Inaccessible images_______Ü",
				inaccessibleVideo: "ä_Inaccessible videos_______Ü",
				inaccessibleWebpage: "ä_Inaccessible webpages_______Ü"
			},
			scanningErrorTips: {
				deletedMapTip: "ä_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________Ü.",
				inaccessibleMapTip: "ä_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________Ü.",
				notYoursNotAccessibleTip: "ä_Tip: Open the web map and remove the layer or map from the story_____________________Ü.",
				serviceOkItemNotTip: "ä_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________Ü.",
				ignore: "ä_Ignore___Ü",
				fix: "ä_Fix__Ü",
				clickToShareOrg: "ä_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________Ü.",
				clickToSharePublic: "ä_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________Ü.",
				shareOrg: "ä_Share to your org______Ü",
				sharePublicly: "ä_Share publicly_____Ü",
				othersSharedBelowLevelTip: "ä_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________Ü.",
				secureServiceTip: "ä_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________Ü.",
				blogArticle: "ä_here__Ü",
				premiumContentTip: "ä_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________Ü.",
				premiumContentPublicTip: "ä_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________Ü.",
				subscriptionContentTip: "ä_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________Ü.",
				agolCredits: "ä_ArcGIS Online credits_______Ü",
				credits: "ä_credits___Ü",
				makePublic: "ä_Make public____Ü",
				confirm: "ä_Confirm___Ü",
				inaccessibleImageTip: "ä_Tip: Provide the missing image or remove the reference to it___________________Ü.",
				inaccessibleVideoTip: "ä_Tip: Provide the missing video or remove the reference to it___________________Ü.",
				inaccessibleWebpageTip: "ä_Tip: Provide the missing web page or remove the reference to it____________________Ü."
			},
			removeLayer: {
				title: "ä_Fix Layer Issue______Ü",
				layersWithIssue: "ä_Layers with this issue: {{NUM_WITH_ISSUE}}______________Ü",
				issueExplanation: "ä_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________Ü.",
				issueSolution: "ä_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________Ü:",
				editMap: "ä_Edit Your Map_____Ü",
				clickBelowWhenDone: "ä_When you have finished editing, click the button below__________________Ü:",
				rescanAndClose: "ä_Rescan And Close______Ü"
			},
			info: {
				ownedBy: "ä_This item is owned by {{USER_NAME}}____________Ü",
				unknownUser: "ä_someone else_____Ü",
				untitledSection: "ä_(Untitled section)______Ü",
				introRecord: "ä_Introduction_____Ü"
			},
			layers: {
				layersHeader: "ä_Layers___Ü",
				noLayers: "ä_(No Layers)____Ü",
				basemapParens: "ä_(basemap)____Ü"
			},
			images: {
				thumbnails: "ä_Thumbnails____Ü",
				thumbnail: "ä_Thumbnail____Ü",
				thumbnailParens: "ä_(thumbnail)____Ü"
			},
			general: {
				noTitle: "ä_(no title)____Ü",
				loading: "ä_Loading____Ü..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "ä_sections___Ü",
				secondTitle: "ä_style___Ü",
				secondValueA: "ä_side panel____Ü",
				secondValueB: "ä_floating panel_____Ü",
				thirdTitle: "ä_maps__Ü"
			},
			mapTour: {
				firstTitle: "ä_tour points____Ü",
				secondTitle: "ä_style___Ü",
				secondValueA: "ä_integrated____Ü",
				secondValueB: "ä_three-panel____Ü",
				thirdTitle: "ä_basemap___Ü",
				thirdValueLoading: "ä_Loading____Ü...",
				thirdValueUnknown: "ä_unknown___Ü"
			},
			mapSeries: {
				firstTitleA: "ä_bullets___Ü",
				firstTitleB: "ä_sections___Ü",
				firstTitleC: "ä_tabs__Ü",
				secondTitle: "ä_style___Ü",
				secondValueA: "ä_bulleted___Ü",
				secondValueB: "ä_side accordion_____Ü",
				secondValueC: "ä_tabbed___Ü",
				thirdTitle: "ä_maps__Ü"
			},
			swipeSpyglass: {
				firstTitle: "ä_points of interest______Ü",
				secondTitle: "ä_style___Ü",
				secondValueA: "ä_swipe___Ü",
				secondValueB: "ä_spyglass___Ü",
				thirdTitle: "ä_maps__Ü"
			}
		},
		progress: {
			checkingStories: "ä_Checking your stories for issues____________Ü...",
			stop: "ä_Stop__Ü",
			exit: "ä_Exit__Ü",
			dismiss: "ä_Dismiss___Ü",
			done: "ä_Done___Ü.",
			noStoriesWithIssuesLower: "ä_No issues found______Ü!",
			storiesErrorFree: "ä_Looks like your stories are error-free____________Ü",
			scanAllError: "ä_Unable to scan -- we couldn't retrieve one or more of your stories_____________________Ü",
			scanProgress: "ä_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________Ü",
			scanStopped: "ä_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________Ü",
			storiesWithIssues: "ä_Stories with issues: {{NUM_STORIES}}____________Ü"
		}
    })
);