define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "خريطة الويب",
				lblLocation: "الموقع",
				lblContent: "المحتوى",
				lblPopup: "القائمة المنبثقة",
				lblControls: "التطبيقات الإضافية",
				lblOverview: "خريطة النظرة العامة",
				lblLegend: "وسيلة الإيضاح",
				loadingTitle: "تحميل العنوان",
				entry: "إدخال",
				entries: "إدخالات",
				section: "الجزء",
				sections: "الأجزاء",
				and: "و",
				action: "إجراءات المقطع",
				actions: "إجراءات المقاطع",
				originalWebmap: "خريطة الويب المستخدمة في نشر %TPL_NAME%",
				browseMaps: "استعراض الخرائط",
				current: "خريطة الويب الحالية",
				select: "تحديد خريطة الويب",
				newMap: "خريطة الويب المحددة حديثًا",
				webmapDefault: "خريطة الويب الافتراضية",
				customCfg: "التكوين المخصص",
				tooltipLocation: "تعريف الموقع الذي ستعرضه هذه الخريطة.",
				tooltipContent: "تعريف الطبقات المرئية.",
				tooltipPopup: "اختيار عناصر منبثق سيتم فتحه عند عرض هذه الخريطة.",
				tooltipOverview: "عرض خريطة نظرة عامة صغيرة مع الخريطة الأساسية",
				tooltipLegend: "عرض وسيلة إيضاح الخريطة على الخريطة وتكون مفيدة عند حصول الخريطة على العديد من الطبقات والرموز.",
				mapCfgInvite: "استخدم عناصر التحكم الحالية لتكوين الخريطة",
				lblLocationAlt: "موروث من الخريطة الأولى",
				tooltipLocationAlt: "يتم تزامن موقع الخريطة للخريطة الأولى في السلسلة، ولتغيير هذا السلوك في السلسلة، انتقل إلى إعدادات > خيارات الخريطة."
			},
			configure: {
				btnReset: "إعادة تعيين",
				btnCancel: "إلغاء الأمر",
				tocTitle: "محتويات الخريطة",
				tocExplain: "تحديد اي الطبقات سيتم إظهارها.",
				tocNoData: "يتعذر تكوين طبقة.",
				tocSave: "احفظ محتويات الخريطة",
				extentTitle: "موقع الخريطة",
				extentExplain: "تحريك الخريطة وتكبيرها لتحديد كيفية ظهورها للقراء.",
				extentSave: "حفظ موقع الخريطة",
				popupTitle: "العناصر المنبثقة للخريطة",
				popupExplain: "انقر على معلم لفتح النافذة المنبثقة التي ترغب في عرضها.",
				popupSave: "حفظ تكوين العناصر المنبثقة",
				hintNavigation: "انتقال الخريطة مُعطل."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "المؤسسة",
					onlineLabel: "ArcGIS Online",
					contentLabel: "المحتوى",
					favoritesLabel: "المفضلات"
				},
				title: "تحديد خريطة الويب",
				searchTitle: "بحث",
				ok: "موافق",
				cancel: "إلغاء الأمر",
				placeholder: "أدخل مصطلحات البحث أو مُعرف خريطة الويب..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
