define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "é_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._È",
            selectFieldsText:"é_Select Form Fields_È",
            selectThemeText: "Seleziona tema modulo",
            fieldLabelPlaceHolder: "Etichetta per campo",
            fieldDescPlaceHolder: "Descrizione per campo",
            webmapText: "é_1. Webmap_È",
            layerText: "é_2. Layer_È",
            detailsText: "é_3. Details_È",
            fieldsText: "é_4. Fields_È",
            styleText: "é_5. Style_È",
            previewText: "é_6. Preview_È",
            publishText: "é_7. Publish_È",
            titleText: "Generatore GeoForm",
            descriptionText: "é_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._È",
            btnPreviousText: "Indietro",
            btnNextText:"Avanti",
            webmapTabTitleText: "Scegli mappa Web",
            btnSelectWebmapText:"Seleziona mappa Web",
            layerTabTitleText: "Seleziona layer modificabile",
            selectLayerLabelText:"Layer",
            selectLayerDefaultOptionText:"Seleziona layer",
            detailsTabTitleText:"Dettagli modulo",
            detailTitleLabelText: "Titolo",
            detailLogoLabelText: "Immagine logo",
            detailDescriptionLabelText: "Descrizione",
            fieldTabFieldHeaderText: "Campo",
            fieldTabLabelHeaderText: "Etichetta",
            fieldTabTypeHeaderText: "Tipo",
            fieldTabDescriptionHeaderText: "Descrizione",
            previewApplicationText: "Anteprima applicazione",
            saveApplicationText: "Salva applicazione",
            saveText: "Salva",
            toggleNavigationText: "é_Toggle navigation_È",
            formPlaceholderText: "é_My Form_È",
            imageLogoPlaceholderText: "é_http://www.mysite.com/myimage.png_È",
            shareBuilderInProgressTitleMessage: "é_Publishing GeoForm_È",
            shareBuilderProgressBarMessage:"é_Please Wait..._È",
            shareBuilderTitleMessage: "é_Your GeoForm has been updated & published!_È",
            shareBuilderTextMessage: "é_You can start collecting information by sharing with others_È",
            shareDialogFormText: "é_Form Link_È",
            geoformTitleText: "é_Geo Form_È",
            layerTabText: "é_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._È",
            detailsTabText:"é_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._È",
            fieldsTabText:"é_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._È",
            styleTabText: "é_Style your GeoForm using the themes below based on your preference._È",
            publishTabText: "é_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._È"
        }
    })
);