define({
    root: ({
        map: {
            error: "Harita oluşturulamıyor",
            views: "görünümler."
        },
        report: {
            flag: "Uygunsuz olarak işaretle",
            error: "Hata",
            success: "İşaretlendi",
            loading: "Yükleniyor&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Açıklama bulunmuyor",
            bookmarks: "Yer İşaretleri",
            zoomTo: "Bu konumu yakınlaştırın ve daha fazla bilgi edinin.",
            untitledNote: "Başlıksız"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Ortam Katmanları",
            mediaLayersDescription: "Harita üzerinde dışarıdan gelen katkıları göster.",
            flickrSettings: "Flickr Ayarları",
            twitter: "Twitter",
            twitterSettings: "Twitter Ayarları",
            twitterUser: "Twitter Hesabı",
            twitterSignIn: "Twitter\'a giriş yap",
            webcams: "Webcams.travel",
            instagram: "Instagram",
            instagramSettings: "Instagram Ayarları",
            igTime: "Geçmiş gün sayısı dahilinde yüklenen",
            youtube: "YouTube",
            youtubeSettings: "YouTube Ayarları",
            ytSettingsInfo: "Kullanıcı tarafından üretilen videoları ağ ve profesyonel içerik de dahil görüntüleyin.",
            ytTime: "Geçmişte yüklenen",
            today: "Gün",
            this_week: "Hafta",
            this_month: "Ay",
            all_time: "Tüm Zamanlar",
            moreInfo: "Daha Fazla Bilgi",
            searchTerms: "Arama Terimleri",
            search: "Ara",
            flSettingsInfo: "Bir fotoğrafın başlığı, açıklaması veya etiketleriyle eşleşen sonuçlar döndürün.",
            twSettingsInfo: "Şu anda ne olduğunu görün.",
            igSettingsInfo: "Instagram, hayatınızı arkadaşlarınız ve ailenizle paylaşmak için hızlı, güzel ve eğlenceli bir yoldur.",
            advancedOperators: "İpucu: gelişmiş aramalar oluşturmak için <a target=\"_blank\" href=\"https://support.twitter.com/articles/71577-using-advanced-search\">işleçler</a> kullanın.",
            tweetsFilteredBy: "tweet filtreleme ölçütü:",
            photosFilteredBy: "fotoğraf filtreleme ölçütü:",
            videosFilteredBy: "Video filtreleme kriteri:",
            twitterAccountStatus: "Durumunuzu görmek için Twitter katmanını etkinleştirin."
        },
        general: {
            map: "Harita",
            mapInfo: "Harita Bilgileri",
            legend: "Gösterim",
            featured: "Tanıtılan Konumlar",
            layers: "Katmanlar",
            share: "Paylaş",
            about: "Hakkında",
            find: "Posta Kodu, şehir vb.",
            moreInfo: "Ek bilgiler",
            dateModified: "Son değiştirilme tarihi",
            noSearchResult: "Hiçbir sonuç bulunamadı",
            switchAccount: "Hesap değiştir",
            signIn: "Hesabınıza",
            settings: "Ayarlar"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});