define({
	root: ({
		signInDialog: {
			title: "تسجيل الدخول إلى خرائط القصة",
			subtitle: "تسجيل الدخول باستخدام حساب ArcGIS Online الحالي على:",
			reasonOne: "إنشاء خرائط قصص مُقنعة للتعبير عن القصص التي تريد التعبير عنها.",
			reasonTwo: "استخدم الخرائط والبيانات من ArcGIS Online في خرائط القصة.",
			reasonThree: "إدارة خرائط القصص وفحص حالة المحتوى الخاص بها.",
			noAccountYet: "هل لا يوجد لديك حساب على ArcGIS Online؟ اشترك:",
			publicAccount: "حساب عام مجاني للاستخدام غير التجاري",
			subscriptionAccount: "اشتراك ArcGIS التجريبي المجاني",
			signInExpired: "انتهت صلاحية تسجيل دخولك. سجل الدخول مجددًا للاستمرار حيث انتهيت.",
			somethingNotLoading: "لم يتم تحميل بعض العناصر بشكل صحيح. حاول تحديث الصفحة مرة أخرى."
		},
		unavailableDialog: {
			title: "تسجيل الدخول غير متاح",
			explanation: "عذرًا، هذا غير مدعوم في العرض الصغير. يرجى الفتح في عرض أكبر أو جهاز أكبر.",
			close: "إغلاق",
			returnButton: "عائد" 
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 	
});