define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "試_Enter Builder_驗",
                "exitBuilderButtonText": "試_Exit Builder_驗",
                "enterBuilderModeHelpText": "試_Enter Builder Mode to configure application_驗",
                "builderModeHelpText": "試_Template Builder Mode_驗",
                "webmapCaption": "試_Map_驗",
                "selectMapMessage": "試_Currently ${displaying} <b>${webmapTitle}</b><br/>Click Select map to choose a different webmap_驗",
                "loadMapMessage": "試_Currently selected <b>${webmapTitle}</b><br/>Click Save to use this webmap_驗",
                "changeWebmap": "試_Select map_驗",
                "saveButtonText": "試_Save_驗",
                "webmapNextButtonText": "試_Next ->_驗",
                "previousButtonText":"試_Previous_驗",
                "layerLabelText": "試_Layer_驗",
                "noLayerFoundText": "試_No Layer Found_驗",
                "selectLayer": "試_Select Layer_驗",
                "applicationSettingText": "試_Application Settings_驗",
                "summaryAttrAscendingOrderTooltip": "試_Ascending_驗",
                "onStartLabel": "試_On Start_驗",
                "selectVariableText": "試_Select A Variable_驗",
                "selectVariableDropdown": "試_Select A Variable_驗",
                "label":"試_Label_驗",
                "sourceLinkText":"試_Source Link_驗",
                "selectSubVariableText":"試_Select Sub Variables_驗",
                "subVariablePanelButtonText":"試_DONE_驗",
                "onButtonLabel":"試_On_驗",
                "offButtonLabel":"試_Off_驗",
                "appSettingsSaveCloseButtonText": "試_SAVE & CLOSE_驗",
                "appSettingsTitleText":"試_App Title_驗",
                "appSettingsDescriptionText": "試_Application Description_驗",
                "appSetingsRendererAreaText":"試_Rendered Area_驗",
                "shareText":"試_Share_驗",
                "popupText": "試_Popup_驗",
                "basemapText":"試_Basemap_驗",
                "cancel": "試_Cancel_驗",
                "theme": "試_Theme_驗",
                "zoomLevel": "試_Zoom Level_驗",
                "existingValue": "試_Use existing values_驗",
                "enrichLayer": "試_Enrich Layer_驗",
                "imageLabel": "試_How does this work_驗 ?",
                "clearData": "試_Clear Data_驗",
                "basemapSelectionText":"試_Basemap Selection_驗",
                "secondaryBasemapText":"試_Secondary Basemap_驗",
                "defaultBasemapText": "試_Default Basemap_驗",
                "entireAreaButton": "試_Entire Area_驗",
                "entireAreaOnStartButton": "試_Entire Area on start_驗",
                "aboutPanel": "試_About Panel_驗",
                "legendPanel": "試_Legend Panel_驗",
                "layersPanel": "試_Layers Panel_驗",
                "dataConfigurationButtonText": "試_Data Configuration_驗",
                "savingChangesMessage": "試_Saving Changes_驗...",
                "nextButtonText": "試_Next_驗",
                "prevButtonText": "試_Previous_驗",
                "enterLabelText": "試_Enter Label_驗",
                "SelectedFeatureText": "試_Selected Feature_驗",
                "layerHelpTextMessage": "試_This application requires a layer with numeric fields_驗",
                "alertMessage": {
                    "resetVariableMessage": "試_Are you sure you want to reset variable_驗?",
                    "emptyAppTitleMessage": "試_Application title cannot be empty_驗",
                    "emptyDescriptionMessage": "試_Description cannot be empty_驗",
                    "maxVariableSelection": "試_You cannot select more than 25 sub variables_驗",
                    "signInFail" : "試_Sign-in Failed_驗",
                    "itemUpdateMessage": "試_Item Updated_驗",
                    "unsavedChangesMessage": "試_Unsaved Changes_驗",
                    "failMessage": "試_Could not update the item sucessfully_驗",
                    "saveChangesAlert": "試_Do you want to save the changes_驗 ?",
                    "variableLabelValidation": "試_Variable label cannot be empty_驗",
                    "subVariableLabelValidation": "試_Sub variable label cannot be empty_驗"
                    }
            }
        }
    })
);