define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Öppna Builder",
                "exitBuilderButtonText": "Avsluta Builder",
                "enterBuilderModeHelpText": "Öppna byggläget för att konfigurera program",
                "builderModeHelpText": "Mallbyggläge",
                "webmapCaption": "Karta",
                "selectMapMessage": "Nu ${displaying} <b>${webmapTitle}</b><br/>Klicka på Välj karta för att välja en annan webbkarta",
                "loadMapMessage": "Vald <b>${webmapTitle}</b><br/>Klicka på Spara för att använda den här webbkartan",
                "changeWebmap": "Välj karta",
                "saveButtonText": "Spara",
                "webmapNextButtonText": "Nästa ->",
                "previousButtonText":"Föregående",
                "layerLabelText": "Lager",
                "noLayerFoundText": "Inget lager hittades",
                "selectLayer": "Välj lager",
                "applicationSettingText": "Programinställningar",
                "summaryAttrAscendingOrderTooltip": "Stigande",
                "onStartLabel": "Å_On Start_ö",
                "selectVariableText": "Välj en variabel",
                "selectVariableDropdown": "Välj en variabel",
                "label":"Etikett",
                "sourceLinkText":"Länk till källa",
                "selectSubVariableText":"Välj undervariabler",
                "subVariablePanelButtonText":"KLAR",
                "onButtonLabel":"På",
                "offButtonLabel":"Av",
                "appSettingsSaveCloseButtonText": "SPARA OCH STÄNG",
                "appSettingsTitleText":"Apptitel",
                "appSettingsDescriptionText": "Programbeskrivning",
                "appSetingsRendererAreaText":"Renderad yta",
                "shareText":"Dela",
                "basemapText":"Baskarta",
                "basemapSelectionText":"Baskarteval",
                "secondaryBasemapText":"Sekundär baskarta",
                "defaultBasemapText": "Standardbaskarta",
                "entireAreaButton": "Å_Entire Area_ö",
                "entireAreaOnStartButton": "Å_Entire Area on start_ö",
                "aboutPanel": "Å_About Panel_ö",
                "legendPanel": "Å_Legend Panel_ö",
                "layersPanel": "Å_Layers Panel_ö",
                "dataConfigurationButtonText": "Datakonfiguration",
                "savingChangesMessage": "Sparar ändringar...",
                "nextButtonText": "Nästa",
                "prevButtonText": "Föregående",
                "enterLabelText": "Ange etikett",
                "layerHelpTextMessage": "Programmet kräver ett lager med numeriska fält",
                "alertMessage": {
                    "resetVariableMessage": "Vill du återställa variabeln?",
                    "emptyAppTitleMessage": "Programtiteln får inte vara tom",
                    "emptyDescriptionMessage": "Beskrivningen får inte vara tom",
                    "maxVariableSelection": "Det går inte att välja fler än 25 undervariabler",
                    "signInFail" : "Inloggningen misslyckades",
                    "itemUpdateMessage": "Objektet uppdaterades",
                    "unsavedChangesMessage": "Osparade ändringar",
                    "failMessage": "Det gick inte att uppdatera objektet",
                    "saveChangesAlert": "Vill du spara ändringarna?",
                    "variableLabelValidation": "Variabeletiketten får inte vara TOM",
                    "subVariableLabelValidation": "Undervariabeletiketten får inte vara TOM"
                    }
            }
        }
    })
});