define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Č_Enter Builder_____ž",
                "exitBuilderButtonText": "Č_Exit Builder_____ž",
                "enterBuilderModeHelpText": "Č_Enter Builder Mode to configure application______________ž",
                "builderModeHelpText": "Č_Template Builder Mode_______ž",
                "webmapCaption": "Č_Map__ž",
                "selectMapMessage": "Č_Currently ${displaying} <b>${webmapTitle}</b><br/>Click Select map to choose a different webmap______________________________ž",
                "loadMapMessage": "Č_Currently selected <b>${webmapTitle}</b><br/>Click Save to use this webmap_______________________ž",
                "changeWebmap": "Č_Select map____ž",
                "saveButtonText": "Č_Save__ž",
                "webmapNextButtonText": "Č_Next ->___ž",
                "previousButtonText":"Č_Previous___ž",
                "layerLabelText": "Č_Layer___ž",
                "noLayerFoundText": "Č_No Layer Found_____ž",
                "selectLayer": "Č_Select Layer_____ž",
                "applicationSettingText": "Č_Application Settings_______ž",
                "summaryAttrAscendingOrderTooltip": "Č_Ascending____ž",
                "onStartLabel": "Č_On Start___ž",
                "selectVariableText": "Č_Select A Variable______ž",
                "selectVariableDropdown": "Č_Select A Variable______ž",
                "label":"Č_Label___ž",
                "sourceLinkText":"Č_Source Link____ž",
                "selectSubVariableText":"Č_Select Sub Variables_______ž",
                "subVariablePanelButtonText":"Č_DONE__ž",
                "onButtonLabel":"Č_On__ž",
                "offButtonLabel":"Č_Off__ž",
                "appSettingsSaveCloseButtonText": "Č_SAVE & CLOSE_____ž",
                "appSettingsTitleText":"Č_App Title____ž",
                "appSettingsDescriptionText": "Č_Application Description________ž",
                "appSetingsRendererAreaText":"Č_Rendered Area_____ž",
                "shareText":"Č_Share___ž",
                "popupText": "Č_Popup___ž",
                "basemapText":"Č_Basemap___ž",
                "cancel": "Č_Cancel___ž",
                "theme": "Č_Theme___ž",
                "zoomLevel": "Č_Zoom Level____ž",
                "existingValue": "Č_Use existing values_______ž",
                "enrichLayer": "Č_Enrich Layer_____ž",
                "imageLabel": "Č_How does this work_______ž ?",
                "clearData": "Č_Clear Data____ž",
                "basemapSelectionText":"Č_Basemap Selection______ž",
                "secondaryBasemapText":"Č_Secondary Basemap______ž",
                "defaultBasemapText": "Č_Default Basemap______ž",
                "entireAreaButton": "Č_Entire Area____ž",
                "entireAreaOnStartButton": "Č_Entire Area on start_______ž",
                "aboutPanel": "Č_About Panel____ž",
                "legendPanel": "Č_Legend Panel_____ž",
                "layersPanel": "Č_Layers Panel_____ž",
                "dataConfigurationButtonText": "Č_Data Configuration______ž",
                "savingChangesMessage": "Č_Saving Changes______ž...",
                "nextButtonText": "Č_Next__ž",
                "prevButtonText": "Č_Previous___ž",
                "enterLabelText": "Č_Enter Label____ž",
                "SelectedFeatureText": "Č_Selected Feature______ž",
                "layerHelpTextMessage": "Č_This application requires a layer with numeric fields_________________ž",
                "alertMessage": {
                    "resetVariableMessage": "Č_Are you sure you want to reset variable_____________ž?",
                    "emptyAppTitleMessage": "Č_Application title cannot be empty___________ž",
                    "emptyDescriptionMessage": "Č_Description cannot be empty_________ž",
                    "maxVariableSelection": "Č_You cannot select more than 25 sub variables______________ž",
                    "signInFail" : "Č_Sign-in Failed_____ž",
                    "itemUpdateMessage": "Č_Item Updated_____ž",
                    "unsavedChangesMessage": "Č_Unsaved Changes______ž",
                    "failMessage": "Č_Could not update the item sucessfully____________ž",
                    "saveChangesAlert": "Č_Do you want to save the changes___________ž ?",
                    "variableLabelValidation": "Č_Variable label cannot be empty__________ž",
                    "subVariableLabelValidation": "Č_Sub variable label cannot be empty___________ž"
                    }
            }
        }
    })
);