define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Uđite u alatku za izradu",
                "exitBuilderButtonText": "Izađite iz alatke za izradu",
                "enterBuilderModeHelpText": "Uđite u režim alatke za izradu da konfigurišete aplikaciju",
                "builderModeHelpText": "Režim šablona alatke za izradu",
                "webmapCaption": "Mapa",
                "selectMapMessage": "Trenutno ${displaying} <b>${webmapTitle}</b><br/>Kliknite na „Izaberi mapu“ da odaberete drugu veb mapu",
                "loadMapMessage": "Trenutno izabrano <b>${webmapTitle}</b><br/>Kliknite na „Sačuvaj“ da koristite ovu veb mapu",
                "changeWebmap": "Izaberite mapu",
                "saveButtonText": "Sačuvaj",
                "webmapNextButtonText": "Sledeće->",
                "previousButtonText":"Prethodno",
                "layerLabelText": "Sloj",
                "noLayerFoundText": "Nijedan sloj nije pronađen",
                "selectLayer": "Izaberite sloj",
                "applicationSettingText": "Postavke aplikacije",
                "summaryAttrAscendingOrderTooltip": "Rastuće",
                "onStartLabel": "Na početak",
                "selectVariableText": "Izaberite promenljivu vrednost A",
                "selectVariableDropdown": "Izaberite promenljivu vrednost A",
                "label":"Oznaka",
                "sourceLinkText":"Link ka izvoru",
                "selectSubVariableText":"Izaberite sub varijablu",
                "subVariablePanelButtonText":"ZAVRŠENO",
                "onButtonLabel":"Uključeno",
                "offButtonLabel":"Isključeno",
                "appSettingsSaveCloseButtonText": "SAČUVAJ I ZATVORI",
                "appSettingsTitleText":"Naslov aplikacije",
                "appSettingsDescriptionText": "Opis aplikacije",
                "appSetingsRendererAreaText":"Oblast procesirana za vizuelizaciju",
                "shareText":"Podeli",
                "popupText": "Iskačući prozor",
                "basemapText":"Pozadinska mapa",
                "cancel": "Otkaži",
                "theme": "Tema",
                "zoomLevel": "Nivo zumiranja",
                "existingValue": "Koristi postojeće vrednosti",
                "enrichLayer": "Obogati sloj",
                "imageLabel": "Kako ovo funkcioniše?",
                "clearData": "Izbriši podatke",
                "basemapSelectionText":"Izbor pozadinske mape",
                "secondaryBasemapText":"Pomoćna pozadinska mapa",
                "defaultBasemapText": "Podrazumevana pozadinska mapa",
                "entireAreaButton": "Čitava površina",
                "entireAreaOnStartButton": "Čitava površina na početku",
                "aboutPanel": "Tabla sa više informacija",
                "legendPanel": "Tabla legende",
                "layersPanel": "Tabla slojeva",
                "dataConfigurationButtonText": "Konfiguracija podataka",
                "savingChangesMessage": "Čuvanje promena...",
                "nextButtonText": "Sledeće",
                "prevButtonText": "Prethodno",
                "enterLabelText": "Unesi oznaku",
                "SelectedFeatureText": "Izabrani geoobjekat",
                "layerHelpTextMessage": "Ova aplikacija zahteva sloj sa numeričkim poljima",
                "alertMessage": {
                    "resetVariableMessage": "Želite li zaista da poništite promenljivu vrednost?",
                    "emptyAppTitleMessage": "Naslov aplikacije ne može da bude prazan",
                    "emptyDescriptionMessage": "Opis ne može da bude prazan",
                    "maxVariableSelection": "Ne možete da izaberete više od 25 sub varijabli",
                    "signInFail" : "Prijavljivanje nije uspelo",
                    "itemUpdateMessage": "Stavka je ažurirana",
                    "unsavedChangesMessage": "Nesačuvane izmene",
                    "failMessage": "Ažuriranje stavke nije uspelo",
                    "saveChangesAlert": "Želite li da sačuvate promene?",
                    "variableLabelValidation": "Oznaka promenljive vrednosti ne može da bude prazna",
                    "subVariableLabelValidation": "Oznaka sub varijable ne može da bude prazna"
                    }
            }
        }
    })
);