define(
({
		viewer: {
			loading: {
				step1: "CHARGEMENT DE L\’APPLICATION",
				step2: "CHARGEMENT DES DONNEES",
				step3: "INITIALISATION DE LA VISITE",
				loadBuilder: "PASSAGE EN MODE DE GENERATEUR",
				redirectSignIn: "REDIRECTION VERS LA PAGE DE CONNEXION",
				redirectSignIn2: "(vous serez redirigé vers cette page une fois connecté)",
				fail: "Le chargement de Map Tour a échoué",
				failButton: "Réessayez"
			},
			errors: {
				boxTitle: "Une erreur s\’est produite",
				portalSelf: "Erreur fatale : échec de l\'obtention de la configuration du portail",
				invalidConfig: "Erreur fatale : configuration non valide",
				invalidConfigOwner: "Erreur fatale : configuration non valide (propriétaire autorisé requis)",
				invalidConfigNoWebmap: "Erreur fatale : configuration non valide (identifiant de carte Web ou d\'application non spécifié dans index.htm)",
				createMap: "Impossible de créer la carte",
				invalidApp: "Erreur fatale : impossible de charger l\’application",
				noLayer: "La carte Web ne contient pas de couche de données valide pour Map Tour.",
				noLayerMobile: "Bienvenue dans l\’application Web Map Tour. L\’application n\’est pas configurée. Le générateur Map Tour n\’est pas pris en charge sur les appareils mobiles.",
				noLayerView: "Bienvenue dans l\’application Web Map Tour.<br />L\’application n\’est pas encore configurée.",
				appSave: "Erreur d\’enregistrement de l\’application Web",
				mapSave: "Erreur d\’enregistrement de la carte Web",
				featureServiceLoad: "Erreur de chargement du service d\'entités",
				notAuthorized: "Vous n\’êtes pas autorisé à accéder à cette application",
				oldBrowserTitle: "Le navigateur n\’est pas entièrement pris en charge",
				noBuilderIE8: "Le générateur Map Tour n\'est pas pris en charge avant la version 9 d\'Internet Explorer.",
				ie10Win7Explain: "Le générateur interactif Map Tour n\’est pas pris en charge dans Internet Explorer 10 sous Windows 7 lorsque la source de données est un service d\’entités comportant des pièces jointes. Pour pouvoir utiliser un service d\’entités comportant des pièces jointes, vous devez <a target='_blank\' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>définir manuellement le mode de document sur les normes d\’Internet Explorer 9</a>, <a target='_blank\' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>utiliser Internet Explore 9</a> ou mettre à niveau vers Windows 8.",
				oldBrowserExplain: "Ce navigateur ne prend pas en charge la génération automatique des miniatures à partir d\’images que vous ajoutez dans votre visite cartographique. Vous pouvez créer une visite cartographique avec ce navigateur, mais vous devez fournir une image miniature distincte pour chacune des images que vous ajoutez.",
				oldBrowserExplain2: "Pour profiter pleinement de l\’application, <a href='http://browsehappy.com/\' target='_blank'>mettez votre navigateur à niveau</a> ou <a href='http://www.google.com/chromeframe/?redirect=true\' target='_blank'>activez Google Chrome Frame pour Internet Explorer</a>.",
				oldBrowserExplain3: "Le générateur Map Tour ne fonctionne pas avec Internet Explorer 10 sous Windows XP.",
				oldBrowserClose: "Fermer"
			},
			mobileHTML: {
				showIntro: "AFFICHER LE TITRE",
				hideIntro: "MASQUER LE TITRE",
				navList: "Liste",
				navMap: "Carte",
				navInfo: "Elément multimédia",
				introStartBtn: "Démarrer"
			},
			desktopHTML: {
				storymapsText: "Carte de narration",
				builderButton: "Mode de générateur",
				bitlyTooltip: "Obtenir un lien court vers l\'application",
				bitlyStartIndex: "Relier au site actuel"
			},
			builderHTML: {
				panelHeader: "CONFIGURATION DE L\’APPLICATION",
				buttonSave: "ENREGISTRER",
				buttonSettings: "Paramètres",
				buttonShare: "æ_Share_Â",
				buttonView: "Mode d\’affichage",
				buttonItem: "Ouvrir l\'élément d\'application Web",
				buttonHelp: "Aide",
				buttonOrganize: "Organiser",
				buttonAdd: "Ajouter",
				buttonImport: "Importation",
				buttonImportDisabled: "L\'importation n\'est pas disponible lors de l\'utilisation d\'un service d\'entités comportant des pièces jointes.",
				dataEditionDisabled: "La mise à jour de données est désactivée sur la source de données CSV",
				dataSourceWarning: "La couche de données Map Tour a changé. Si les ID des entités sont différents, vous devez réinitialiser l\'ordre et les points masqués via <b>Organiser</b>. Si les noms des champs sont différents, vous devez réinitialiser les paramètres des champs sous l\'<b>onglet Données dans Paramètres</b>.",
				organizeWarning: "Un ou plusieurs points ajoutés en dehors du générateur interactif sont masqués.",
				dataPicError0a: "Cette visite comprend des URL d\'images non compatibles avec <b>%NB%</b>.",
				dataPicError0b: "Cette visite peut comprendre des URL d\'images non compatibles avec <b>%NB%</b>. <b>%NB%</b>.",
				dataPicError1: "Map Tour requiert désormais que l\'URL d\'une image possède une des extensions suivantes : .jp(e)g, .png, .gif ou .bmp.",
				dataPicError2: "Cela ne concerne pas vos visites cartographiques existantes publiées. Cependant, pour pouvoir utiliser le générateur interactif, vous devez d\'abord résoudre le problème de l\'URL en effectuant l\'une des deux actions suivantes :",
				dataPicError3: "Modifier les URL",
				dataPicError4: "Cela ajoutera <i>#isImage</i> à la fin des URL des images non prises en charge. La plupart des serveurs prennent en charge l\'ajout d\'URL. Cependant, une fois que vous avez effectué cette action, vous devez vérifier que les URL des images mises à jour sont fonctionnelles en parcourant vos points. Si chaque image se charge, vous pouvez enregistrer la visite cartographique. Si les <b>images sont endommagées, n\'enregistrez pas la visite cartographique</b>. 
Rechargez le générateur et effectuez la seconde action.",
				dataPicError5: "Limiter la visite aux images",
				dataPicError6: "Cette option fait en sorte que toutes les URL soient considérées comme des images, mais vous ne pourrez pas ajouter de vidéos au moyen du générateur interactif. Cette action est réversible, au cas où vous décideriez d\'ajouter des vidéos à l\'avenir.",
				dataPicError7: "Votre Map Tour est limité aux images, vous ne pouvez pas utiliser de vidéos. Si vous décidez de supprimer cette limitation, vérifiez que vos images se chargent correctement avant d\'enregistrer la visite cartographique. Vous pourrez restaurer cette limitation plus tard le cas échéant.",
				dataPicError8: "Supprimer la limitation des images",
				dataPicError9: "Si ces URL pointent sur des vidéos vous pouvez ignorer cet avertissement, si elles pointent sur une image, vous devez effectuer l\'une des deux actions suivantes :",
				modalCancel: "Annuler",
				modalApply: "Appliquer",
				organizeHeader: "Organiser la visite",
				organizeGeneralCaption: "Déplacez les points de la visite pour les trier",
				organizeDelete: "Effacer",
				organizeHide: "Masquer",
				organizeReset: "Réinitialiser l\'ordre et les points masqués",
				addMaxPointReached: "Vous avez atteint le nombre maximal de points autorisés par les icônes définies et il est impossible d\’en ajouter un autre.<br /><br />Notez que si vous supprimez des points existants, vous devrez recharger l\’application.",
				addMaxPointReachedMobile: "Vous avez atteint le nombre maximal de points autorisés et cette image ne peut pas être ajoutée.",
				addClose: "Fermer",
				addHeader: "Ajouter un nouveau point à la visite",
				addTabPicture: "Elément multimédia",
				addTabInformation: "Informations",
				addTabLocation: "Emplacement",
				addSelectCaption: "Sélectionner ou supprimer une image",
				addNoteVideo: "Consultez l\'aide pour savoir comment utiliser des vidéos",		
				addSelectCaptionNoFileReader: "Sélectionner une image",	
				addChangePhoto: "Modifier l\'image et la miniature",
				addPictureResolutionIntro: "La résolution de l\’image est trop élevée :",
				addPictureResolutionOldBrowser: "La résolution de l\’image est trop élevée. Optimisez l\’utilisation de Map Tour en spécifiant une résolution inférieure à %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Définir la résolution de l\’image sur %RESOLUTION%",
				addPictureResolutionKeep: "Conserver la résolution d\’origine %RESOLUTION%",
				addSelectThumbnail: "Sélectionner la miniature",
				addNoThumbSelected: "Aucune miniature sélectionnée",
				addThumbSelected: "Sélectionné(e)",
				addCameraSettingsHeader: "PARAMETRES DE CAMERA",
				addThumbnailHeader: "MINIATURE",
				addLabelPicUrl: "Image",
				addLabelThumbUrl: "Miniature",
				addTextPlaceholderUrl: "Saisissez l\'URL d\'une image",
				addTextPlaceholderUrl2: "æ_Enter a Youtube page URL_Â",
				addTextPlaceholderUrl3: "Saisissez l\'URL d\'une page Vimeo",
				addTextPlaceholderUrl4: "Saisissez l\'URL d\'incorporation d\'une vidéo",
				addLabelVideo: "Vidéo",
				addMediaVideoOther: "Autre",
				addMediaVideoHelp: "Vérifiez l\'URL et obtenez la miniature par défaut",
				addMediaVideoHelpTooltip1: "La vérification a réussi",
				addMediaVideoHelpTooltip2: "La vérification a échoué",
				addMediaVideoHelpTooltip4: "Recherchez l\'option d\'incorporation de la vidéo et copiez l\'URL de la vidéo qui se trouve dans le code",
				addLabelName: "Nom",
				addLabelDescription: "Légende",
				addTextPlaceholder: "Entrez des données",
				addLocatePlaceholder: "Rechercher une adresse ou un lieu",
				addPinColor: "Couleur",
				addLatitude: "Latitude",
				addLongitude: "Longitude",
				addLatitudePlaceholder: "par ex. 34.056",
				addLongitudePlaceholder: "par ex. -117.195",
				addUploading: "Chargement d\’un point dans la visite",
				addSave: "Ajouter un point à la visite",
				addMobileUploading: "Chargement de l\’image",
				addMobileName: "Entrer un nom",
				addMobileNameMandatory: "Erreur : entrez un nom.",
				addMobileError: "Une erreur s\’est produite.",
				settingsHeader: "Paramètres de l\’application",
				settingsTabLayout: "Mise en page",
				settingsTabColor: "Couleurs",
				settingsTabLogo: "En-tête",
				settingsTabFields: "Données",
				settingsTabExtent: "Etendue",
				settingsTabZoom: "Niveau de zoom",
				settingsLayoutExplain: "Sélectionnez la mise en page d\’application de votre choix.",
				settingsLayoutProfessional: "Mise en page à trois volets",
				settingsLayoutModern: "Mise en page intégrée",
				settingsLayoutSelected: "Mise en page sélectionnée",
				settingsLayoutSelect: "Sélectionner cette mise en page",
				settingsLayoutNote: "Notez que sur les points qui utilisent des vidéos, le message est toujours placé sous la vidéo même si cette option est désélectionnée.",
				settingsLayoutLocBtn: "æ_Display a 'Locate' button_Â",
				settingsLayoutLocBtnHelp: "Cette fonctionnalité est prise en charge sur la plupart des navigateurs pour appareils mobiles et ordinateurs de bureau (Internet Explorer 9).",
				settingsColorExplain: "Modifiez l\’apparence en choisissant un thème prédéfini ou créez le vôtre.",
				settingsLabelColor: "Couleurs d\’en-tête, de contenu et de pied de page",
				settingsLogoExplain: "Personnalisez le logo d\’en-tête (250 x 50 px au maximum).",
				settingsLogoEsri: "Logo Esri",
				settingsLogoNone: "Aucun logo",
				settingsLogoCustom: "Logo personnalisé",
				settingsLogoCustomPlaceholder: "URL de l\’image",
				settingsLogoCustomTargetPlaceholder: "Lien",
				settingsLogoSocialExplain: "Personnalisez le lien d\’en-tête en haut à droite.",
				settingsLogoSocialText: "Texte",
				settingsLogoSocialLink: "Lien",
				settingsLogoSocialDisabled: "Cette entité a été désactivée par l\'administrateur",
				settingsDataFieldsExplain: "Sélectionnez les champs du nom de la photo, de la légende et des couleurs.",
				settingsDataFieldsError: "L\’application ne peut pas déterminer le nom, la légende ou les couleurs appropriés. Sélectionnez les champs à utiliser ici. Ces paramètres peuvent être modifiés ultérieurement.",
				settingsFieldsLabelName: "Nom",
				settingsFieldsLabelDescription: "Légende",
				settingsFieldsLabelColor: "Couleur",
				settingsFieldsReset: "Réinitialiser la sélection des champs",
				settingsExtentExplain: "Définissez l\’étendue initiale de Map Tour au moyen de la carte interactive ci-dessous.",
				settingsExtentExplainBottom: "L\'étendue que vous définissez modifie l\'étendue initiale de votre carte Web. Notez que cette étendue n\'est pas utilisée si elle ne comprend pas le premier point de la visite. Dans ce cas, la visite est centrée sur le premier point lors de son ouverture.",
				settingsExtentDateLineError: "L\'étendue ne peut pas traverser le méridien de 180° de longitude",
				settingsExtentDateLineError2: "Erreur de calcul de l\'étendue",
				settingsExtentDrawBtn: "Tracer une nouvelle étendue",
				settingsExtentModifyBtn: "Modifier l\’étendue",
				settingsExtentApplyBtn: "Aperçu dans Map Tour",
				settingsExtentUseMainMap: "Utiliser l\'étendue de Map Tour",
				settingsZoomExplain: "Définissez le zoom des points de narration qui suivent l\’introduction (facultatif).",
				settingsLabelZoom: "Echelle/niveau",
				settingsZoomFirstValue: "Aucun",
				settingsFieldError: "Sélectionnez un champ dans chaque liste",
				dataTitle: "Hébergement sur ArcGIS Online",
				dataExplain: "æ_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._Â",
				dataNameLbl: "Nom du service",
				dataFolderListLbl: "Dossier",
				dataFolderListFetching: "Extraction des dossiers...",
				dataRootFolder: "Racine",
				dataNameError: "Attribuez un nom au service d\’entités",
				dataFolderError: "Sélectionnez un dossier valide",
				dataSrcContainsInvalidChar: "Le nom du service d\’entités contient un ou plusieurs caractères non valides (-, <, >, #, %, :, \", ?, &, +, / ou \).",
				dataSrvAlreadyExistsError: "Un service de ce nom existe déjà au sein de l\’organisation. Choisissez un autre nom.",
				dataBtnSave: "Créer le service",
				dataFooterProgress: "Création en cours",
				dataFooterSucceed: "Création réussie. Chargement en cours",
				dataFooterError: "La création du service a échoué. Réessayez",
				tabError: "Recherchez des erreurs dans tous les onglets",
				introRecordBtn: "Introduction",
				introRecordActivate: "Utilisez le premier point en introduction (n\'apparaît pas dans le vidéorama)"
			},
			addPopupJS: {
				uploadingPicture: "Chargement de l\’image",
				uploadSuccess: "Chargement réussi",
				uploadError: "Erreur de chargement de l\’image",
				uploadError2: "Erreur d\'ajout de l\entité (balise HTML non valide)",
				notJpg: "Choisissez une photo jpeg à charger",
				errorNoPhoto: "Choisissez une image à charger",
				errorNoThumbnail: "Choisissez une miniature à charger",
				errorInvalidPicUrl: "Saisissez une image valide (commence par http(s)://, finit par jpg, png, gif ou bmp). Vous pouvez terminer l\'URL par \'#isImage\' pour ignorer cette règle.",
				errorInvalidThumbUrl: "Saisissez une miniature valide (commence par http(s)://, finit par jpg, png, gif ou bmp).",
				errorInvalidVideoUrl: "Saisissez une URL de vidéo valide (commence par http(s)://)",
				errorNoName: "Attribuez un nom à ce point de la visite",
				errorNoDescription: "Attribuez une légende à ce point de la visite",
				errorNoLocation: "Définissez un emplacement pour ce point de la visite"
			},
			builderJS: {
				noPendingChange: "Aucune modification non enregistrée",
				unSavedChangeSingular: "1 modification non enregistrée",
				unSavedChangePlural: "modifications non enregistrées",
				shareStatus1: "æ_Tour is not saved_Â",
				shareStatus2: "æ_Tour is shared publicly_Â",
				shareStatus3: "æ_Tour is shared within the organization_Â",
				shareStatus4: "æ_Tour is not shared_Â",
				popoverDiscard: "Voulez-vous vraiment ignorer les modifications non enregistrées ?",
				yes: "Oui",
				no: "Non",
				popoverLoseSave: "En ouvrant la visionneuse, vous perdez les modifications non enregistrées",
				ok: "OK",
				popoverSaveWhenDone: "N\’oubliez pas d\’enregistrer lorsque vous avez terminé",
				closeWithPendingChange: "Voulez-vous vraiment confirmer l\’opération ? Vos modifications seront perdues.",
				gotIt: "OK",
				savingApplication: "Enregistrement de l\’application",
				saveSuccess: "L\’application a été enregistrée",
				saveError: "L\’enregistrement a échoué, réessayez",
				saveError2: "L\'enregistrement a échoué en raison d\'une balise HTML non valide dans un nom ou une description",
				saveError3: "Le titre ne peut pas être vide",
				dragColorPicker: "Me déplacer<br />ou modifier ma couleur",
				dataWarningExtent: "Des données se trouvent à l\’extérieur de l\’étendue de la carte Web. Ces données ne seront pas utilisées comme points de la visite. Modifiez l\’étendue de la carte si vous souhaitez les utiliser.",
				dataWarningVisibi: "Votre couche Map Tour n\’est pas visible dans l\’étendue actuelle de la carte Web. Rendez votre couche Map Tour visible avec une carte de taille %MAPSIZE%.",
				dataWarningEdit: "Modifier la carte Web",
				dataWarningClose: "Fermer",
				signIn: "Connectez-vous avec un compte sur",
				signInTwo: "pour enregistrer l\’application.",
				switchBM: "Modifier le fond de carte"
			},
			organizePopupJS: {
				messageStart: "Vous avez choisi de supprimer",
				messageSinglePoint: "un point de la visite",
				messageMultiPoint: "des points de la visite",
				messagePermantRemove: "Cette opération supprime définitivement",
				messageRecord: "l\’enregistrement",
				messageRecordPlural: "les enregistrements",
				messageConfirm: "de votre base de données. Voulez-vous continuer ?",
				labelButtonShow: "Afficher",
				labelButtonHide: "Masquer"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "L\’image et la miniature seront supprimées définitivement",
				popoverDeleteWarningThumb: "La miniature sera supprimée définitivement",
				popoverUploadingPhoto: "Chargement de l\’image et de la miniature",
				popoverUploadingThumbnail: "Chargement de la miniature",
				popoverUploadSuccessful: "Chargement réussi",
				popoverUploadError: "Le chargement a échoué, réessayez",
				changePicAndThumb: "Modifier l\’image",
				changeThumb: "Modifier la miniature",
				selectPic: "Modifier l\'élément multimédia",
				selectThumb: "Modifier la miniature",
				uploadPicAndThumb: "Appliquer"
			},
			headerJS:{
				editMe: "Modifier",
				templateTitle: "Définir le titre du modèle",
				templateSubtitle: "Définir le sous-titre du modèle"
			},
			crossFaderJS:{
				setPicture: "Définir le titre de l\’image",
				setCaption: "Définir la légende de l\’image"
			},
			importPopup: {
				title: "Importation",
				prevBtn: "Retour",
				nextBtn: "Suivant"
			},
			importPopupHome: {
				header: "Où vos images sont-elles stockées ?"
			},
			onlinePhotoSharingCommon: {
				pictures: "images",
				videos: "vidéos",
				disabled: "Cette entité a été désactivée par l\'administrateur",
				disabledPortal: "Cette fonctionnalité est désactivée pour Portal for ArcGIS",
				header1: "Vos images doivent être partagées publiquement.",
				header2: "L'importation sera limitée aux %NB1% premiers %MEDIA%.",
				emptyDataset: "Erreur, aucune image trouvée",
				footerImport: "Importation",
				selectAlbum: "Sélectionner un album public",
				selectAlbum2: "Sélectionner un album",
				pleaseChoose: "Sélectionnez",
				userLookup: "Rechercher",
				userLookingup: "Recherche",
				csv: "Référencées dans un fichier CSV",
				advanced: "Options avancées",
				advancedScratchLbl: "æ_Start a new Tour_Â",
				advancedScratchTip: "æ_Create an empty Tour that you will be able populate manually using a wizard._Â",
				advancedCSVLbl: "æ_Import Tour data from a CSV file_Â",
				advancedCSVTip: "æ_Import your Tour content from a CSV file._Â",
				advancedCommonTip: "æ_It requires that your images and videos are already online._Â",
				select: "Effectuer une sélection",
				locUse: "Utiliser la géolocalisation des images",
				locExplain: "æ_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._Â",
				locExplain2: "æ_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._Â"
			},
			viewFlickr: {
				title: "Importation de Flickr",
				header: "æ_Enter your Flickr user name and select a Photo Set or a Tag to be imported._Â",
				userInputLbl: "Saisir un nom d\'utilisateur",
				signInMsg2: "Utilisateur introuvable",
				selectSet: "Sélectionner un ensemble de photos",
				selectTag: "ou Sélectionner un tag",
				footerImportTag: "Importer le tag sélectionné",
				footerImportSet: "Importer l\'ensemble sélectionné"
			},
			viewFacebook: {
				title: "Importation de Facebook",
				header: "æ_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._Â",
				leftHeader: "Utilisateur de Facebook",
				rightHeader: "Page Facebook",
				pageExplain: "Une page Facebook est une marque, une célébrité ou un produit public, comme <b>esrigis</b>. Vous pouvez obtenir le nom de la page après la première barre oblique inverse \'/\' de l\'URL de la page.",
				pageInputLbl: "Saisissez un nom de page",
				lookupMsgError: "Page introuvable"
			},
			viewPicasa: {
				title: "Importation de Picasa/Google+",
				header: "æ_Enter your email address or the ID of your Picasa or Google+ account._Â",
				userInputLbl: "Saisissez un e-mail ou un ID",
				signInMsg2: "Compte introuvable",
				howToFind: "Comment trouver un ID de compte Picasa ou Google+",
				howToFind2: "Copiez les chiffres compris entre la première et la deuxième barre oblique inverse \'/\' d\'une page Picasa ou G+"
			},
			viewCSV: {
				title: "Importation de CSV",
				uploadBtn: "Sélectionnez ou supprimer un fichier CSV",
				resultHeaderEmpty: "Le fichier CSV est vide",
				resultHeaderSuccess: "Chargement réussi de %NB_POINTS% points",
				resultHasBeenLimited: "L\'importation a été limitée aux %VAL1% premiers points sur %VAL2%, afin de respecter la limite de %VAL3% points par visite.",
				browserSupport: "Votre navigateur n\'est pas pris en charge. Pour pouvoir utiliser un fichier CSV vous devez <a href='http://browsehappy.com/\' target='_blank'>mettre à niveau votre navigateur</a> ou faire appel à la visionneuse de cartes Web d\'ArcGIS.com (consultez l\'Aide).",
				errorLatLng: "Les champs Latitude et Longitude sont introuvables. Les valeurs possibles pour la latitude sont : <i>%LAT%</i> et pour la longitude : <i>%LONG%</i>.",
				errorFieldsExplain: "Le chargement a échoué car les champs requis suivants sont introuvables",
				errorFieldsName: "Les valeurs possibles du champ <b>Nom</b> sont : %VAL%",
				errorFieldsDesc: "Les valeurs possibles du champ <b>Description</b> sont : %VAL%",
				errorFieldsUrl: "Les valeurs possibles du champ <b>URL de l\'image</b> sont : %VAL%",
				errorFieldsThumb: "Les valeurs possibles du champ <b>URL de la miniature</b> sont : %VAL%",
				errorFields2Explain: "Le chargement a échoué car le fichier CSV n\'utilise pas les mêmes attributs que la couche pour les attributs suivants",
				errorFields2Name: "<b>Nom</b> utiliser %VAL1% au lieu de %VAL2%",
				errorFields2Desc: "<b>Description</b> utiliser %VAL1% au lieu de %VAL2%",
				errorFields2Url: "<b>URL de l\'image</b> utiliser %VAL1% au lieu de %VAL2%",
				errorFields2Thumb: "<b>URL de la miniature</b> utiliser %VAL1% au lieu de %VAL2%",
				resultFieldsAll: "Tous les attributs ont été importés",
				resultFieldsNotAll: "Les attributs suivants n\'ont pas été importés car ils n\'existent pas dans la couche de carte",
				resultFieldsNotAll2: "Les attributs suivants ont été importés",
				footerNextBtnResult: "Importer dans la carte Web",
				footerProgress: "Importation en cours",
				footerSucceed: "Importation réussie. Chargement en cours"
			},
			viewYoutube: {
				title: "Importation de Youtube",
				header: "Saisissez un nom d'utilisateur YouTube pour chercher des vidéos partagées publiquement.",
				pageInputLbl: "æ_Enter a Youtube user name_Â",
				lookupMsgError: "Utilisateur introuvable",
				howToFind: "æ_How to find a Youtube user name_Â",
				howToFind2: "Le nom d\'utilisateur est affiché sous les vidéos",
				found: "Trouvés",
				noData: "Aucune vidéo publique trouvée"
			},
			viewGeoTag: {
				title: "æ_Select and locate your images/videos_Â",
				header: "Cliquez ou touchez les images que vous voulez importer pour les localiser.",
				headerMore: "Pourquoi mes images/vidéos ne sont-elles pas géolocalisées ?",
				headerExplain: "æ_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._Â",
				leftPanelTab1: "Pour localiser",
				leftPanelTab2: "Localisé",
				clickOrTap: "Cliquez sur la carte ou touchez-la pour localiser",
				clearLoc: "æ_Clear locations_Â",
				clickDrop: "Ne pas importer",
				footerImport: "Importation",
				footerProgress: "Importation en cours",
				footerSucceed: "Importation réussie. Chargement en cours...",
				loading: "Chargement en cours",
				error: "Echec d'importation de la géolocalisation d'images, les géolocalisations ont été ignorées."
			},
			initPopup: {
				title: "Bienvenue dans le générateur Map Tour",
				prevBtn: "Retour",
				nextBtn: "Suivant"
			},
			initPopupHome: {
				header1: "Où sont stockées vos images ou vidéos ?",
				header2: "Cet assistant va vous aider à créer un Map Tour à partir des images déjà stockées en ligne ou il les importera dans votre compte ArcGIS Online for Organizations.",
				title1: "Elles sont déjà en ligne",
				title2: "J'ai besoin de télécharger mes images",
				hostedFSTooltip: "Utilisez ArcGIS Online pour héberger vos images (vidéos non prises en charge).",
				hostedFsNA: "Disponible uniquement pour les utilisateurs éditeurs ou administrateurs d'ArcGIS for Organizations",
				footer1: "Lorsque vous aurez terminé, n\'oubliez pas de partager votre Map Tour avec votre public par le biais de la page d\'élément de l\'application.",
				footer3: "Télécharger le modèle CSV",
				footer4: "\"Enregistrer sous\" si le téléchargement ne fonctionne pas",
				footer4bis: "Cliquez avec le bouton droit et sélectionnez \"Enregistrer sous\" si le téléchargement ne commence pas",
				footer5: "En savoir plus",
				footerProgress: "Création en cours",
				footerSucceed: "Création réussie. Chargement en cours..."
			},
			helpPopup: {
				title: "Aide",
				close: "Fermer",
				tab1: {
					title: "Introduction",
					div1: "æ_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._Â",
					div2: "æ_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_Â",
					div4: "æ_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._Â",
					div42: "æ_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._Â",
					div5: "æ_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._Â"
				},
				tab2: {
					title: "Données",
					div1: "Le principal élément à envisager lorsque vous créez un Map Tour est l\'endroit de stockage de vos images. Un Map Tour peut utiliser des images stockées sur les principaux services de partage de photos, sur un serveur Web ou comme pièce jointe dans un service d\'entités.",
					div1a: "Consultez la dernière section de cet onglet pour connaître les formats d\'image et les vidéos pris en charge.",
					div2: "Le générateur interactif vous propose deux options de gestion des images dans votre Map Tour :",
					div3: "<ul><li>Vous pouvez utiliser des <b>photos qui sont déjà en ligne</b>, par exemple des images stockées sur un site de partage de photos tel que Flickr ou des images contenues sur votre propre site Web. Ces images seront référencées dans votre Map Tour via leurs URL</li><li>Vous pouvez également <b>charger des photos depuis votre ordinateur</b> directement dans votre Map Tour. Cette option nécessite que vous déteniez un abonnement à ArcGIS Online avec des privilèges d\'éditeur ou d\'administrateur, car un service d\'entités hébergées est créé automatiquement, dans lequel vos photos sont stockées sous la forme de pièces jointes.</li></ul>",
					div4: "Les principaux cas d\'usage sont les suivants :",
					div4b: "<b>Vos photos ne sont pas hébergées</b> pour l\'instant et vous détenez un abonnement à ArcGIS Online. Votre meilleure option consiste à utiliser un service d\'entités hébergé. Tout comme les services de partage de photos publics, nous optimiserons vos photos pour créer des images à chargement rapide et vous aurez accès à toutes les fonctionnalités d\'administration et de gestion de données de la plate-forme ArcGIS.",
					div5: "<b>Vous n\'êtes pas membre d\'une organisation</b> : vous devez d\'abord charger vos images sur un site Web de partage de photos ou sur votre propre serveur Web. Le générateur vous aidera ensuite à utiliser ces images qui resteront hébergées à l\'emplacement d\'origine.",
					div6: "<b>Vous envisagez de réutiliser un service d\'entités existant</b>qui stocke vos images sous la forme de pièces jointes ou qui référence des images externes : reportez-vous à la section détaillée ci-après.",
					div7: "<b>Vous êtes un utilisateur d\'une version précédente</b> du modèle de Map Tour et vous possédez déjà votre fichier CSV qui référence vos images et miniatures : vous pourrez l\'importer et peaufiner vos données. Le générateur prend en charge uniquement des CSV utilisant des champs de latitude/longitude, mais vous pouvez continuer à utiliser des CSV basés sur des adresses via votre carte Web (voir la section ci-après).",
					div8: "Importation à partir de services de partage de photos en ligne",
					div9: "L\'opération d\'importation référence les images déjà hébergées en stockant leurs URL dans une collection d\'entités de cartes Web. Les images ne sont pas stockées sur ArcGIS Online. Si les images hébergées sont inaccessibles, elles ne sont pas disponibles dans le Map Tour et une image « Photo non disponible » est utilisée. Selon le fournisseur de services de photos, le Map Tour peut ne pas importer le nom, la description et l\'emplacement des images. Ces attributs sont stockés dans la carte Web et les modifications apportées aux services en ligne ne seront pas répercutées dans le Map Tour.",
					div10: "Stockage des images sur un serveur Web",
					div11: "Si vous décidez d\'héberger les images vous-même, vous devez créer manuellement les miniatures de vos photos. L\'utilisation d\'images à résolution maximale en tant que miniatures donnera des performances médiocres. Nous vous conseillons par conséquent d\'utiliser des services de partage de photos en ligne ou un service d\'entités, qui créent les miniatures.",
					div12: "Utilisation d\'un service d\'entités ou d\'un fichier de formes existant",
					div13: "Tout service d\'entités ponctuelles ou fichier de formes peut être utilisé comme source de données Map Tour. Il vous suffit de l\'ajouter en tant que couche dans votre carte Web via la visionneuse de cartes arcgis.com.Si l\'application trouve les attributs attendus dans votre couche, toutes les fonctionnalités du générateur seront disponibles.",
					div14: "æ_The possible values for fields name are (case insensitive):_Â",
					div151: "Nom",
					div152: "Description",
					div153: "Image",
					div154: "Miniature",
					div155: "æ_Color_Â ",
					div16: "æ_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._Â",
					div162: "Si vous utilisez un service d\'entités qui stocke les images sous la forme de pièces jointes, <b>seules les entités possédant deux pièces jointes seront utilisées</b>. La première pièce jointe définit la première image et la seconde définit la miniature.",
					div17: "Les champs d\'image et de miniature sont obligatoires pour le service d\'entités comportant des pièces jointes. Si votre service a les pièces jointes activées, le générateur vous permet de charger les images en tant que pièces jointes. Dans le cas contraire, vous pourrez seulement modifier l\'URL de l\'image et de la miniature.",
					div172: "Lorsqu\'ils existent, les champs d\'image et de miniature sont toujours utilisés et les pièces jointes au service d\'entités ne sont pas interrogées.",
					div173: "Vous pouvez télécharger des exemples de fichiers CSV et de fichiers de forme sur le site",
					div18: "Création de services d\'entités hébergés à partir d\'un CSV ou d\'un fichier de forme",
					div19: "Lorsque vous créez un service d\'entités hébergé à partir d\'un fichier CSV ou d\'un fichier de forme, les pièces jointes ne sont pas activées par défaut. Pour les activer, ouvrez la page de détails du service d\'entités, cliquez sur la petite flèche dans la section de la couche et vous verrez cette option. Après cela, le Map Tour continuera d\'utiliser les images et les miniatures que vous avez référencées via les attributs. Facultativement, si vous souhaitez charger vos images en tant que pièces jointes du service d\'entités, vous pouvez le faire grâce à deux boutons situés dans le volet d\'image (\"Modifier l\'image\" et \"Modifier la miniature\").",
					div20: "Vidéos et formats d\'images pris en charge",
					div21: "Les formats d\'images pris en charge sont les suivants : <b>.jpg, .jpeg, .png, .gif et .bmp</b>. Si votre support ne possède pas cette extension, le Map Tour le considère comme une vidéo, sauf lorsqu\'il utilise un service d\'entités (voir ci-après).",
					div22: "Le modèle Map Tour ne comprenant pas de lecteur vidéo, vous devez utiliser le lecteur vidéo externe fourni par votre service d\'hébergement de vidéo favori (trouvez l\'option d\'incorporation de la vidéo et copiez l\'URL présente dans le code donné).Si vous souhaitez héberger la vidéo vous-même, vous pouvez créer une page HTML contenant un lecteur vidéo tel que <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Le générateur interactif ne possède pas de boîte de dialogue permettant d\'inclure de la vidéo lors de l\'utilisation de services d\'entités avec des pièces jointes, mais il est possible de le faire en modifiant vos données en dehors du générateur interactif. Dans la visionneuse de carte arcgis.com, si vous modifiez les champs de l\'image de manière à pointer sur une vidéo externe et que vous ajoutez un paramètre spécial à la fin de votre URL (#isVideo), votre support sera considéré comme une vidéo.",
					div24: "Notez que vous devez tout de même avoir deux pièces jointes d\'images valides pour que le point soit utilisé. Il est impossible d\'utiliser des vidéos lors de l\'utilisation de pièces jointes de service d\'entités sans les champs d\'image et de miniature."
				},
				tab3: {
					title: "Personnalisation",
					div1: "Le générateur offre plusieurs options de personnalisation, accessibles en cliquant sur le bouton PARAMÈTRES dans le volet supérieur. Si vous ne trouvez pas l\'option que vous cherchez, nous proposons également une version à télécharger que vous pouvez déployer sur votre serveur Web et améliorer de manière à correspondre à vos besoins.",
					div2: "Nous recommandons l\'utilisation de la version hébergée, sauf si :",
					div3: "<li>Elle ne permet pas la personnalisation de l\'interface utilisateur que vous recherchez, par exemple utiliser une image d\'arrière-plan de l\'en-tête</li><li>Vous êtes un développeur et vous souhaitez améliorer l\'application</li>",
					div4: "La version téléchargeable peut être configurée via l\'identifiant d\'une carte Web ou d\'une application cartographique Web. Les principaux cas d\'utilisation sont :",
					div41: "Vous créez votre Map Tour grâce au générateur interactif contenu dans l\'environnement hébergé et vous configurez le modèle avec l\'identifiant de l\'application de cartographie Web.Les paramètres que vous avez définis avec le générateur interactif seront appliqués.",
					div42: "Vous créez votre carte Web en dehors du générateur interactif et vous configurez le modèle avec l\'identifiant de la carte Web. Vous devrez lire la documentation pour savoir comment configurer le modèle.",
					div43: "Notez que le générateur interactif est disponible dans sa version à télécharger mais avec certaines restrictions techniques sur des navigateurs tels qu\'Internet Explorer dans une version ultérieure à la version 10.",
					div5: "æ_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._Â"
				},
				tab4: {
					title: "Astuces",
					div0: "Navigateurs pris en charge",
					div0a: "La visionneuse de Map Tour est prise en charge sous Internet Explorer 8+. Le générateur interactif est pris en charge sous Internet Explorer 9+. Nous testons activement dans tous les principaux navigateurs, mais si vous rencontrez des difficultés quelconques, nous vous recommandons d|\'utiliser Chrome.",
					div0b: "Si vous rencontrez des difficultés, faites-le nous savoir. Dans l\'intervalle, en créant votre Map Tour grâce au modèle CSV vous réduisez votre interaction avec l\'interface du générateur.",
					div1: "Images",
					div2: "æ_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._Â",
					div2a: "æ_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._Â",
					div3: "Formatage du texte de votre légende grâce à des balises HTML",
					div4: "Le titre/la légende de l\'en-tête et de l\'image peut comporter des balises HTML permettant de définir le formatage et les liens. Par exemple, le code suivant ajoute un lien jaune :",
					div4a: "æ_Write a good subtitle for your tour_Â",
					div4b: "æ_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._Â",
					div5: "Couches complémentaires",
					div6: "Vous pouvez ajouter des couches supplémentaires pour fournir du contexte au Map Tour. Ces couches peuvent contenir d\'autres entités géographiques que vous voulez que la carte présente en plus des points du Map Tour, par exemple la zone d\'étude, un itinéraire à pied ou en voiture reliant les points de la visite, etc. Le modèle de Map Tour affiche ces couches complémentaires grâce à la symbologie que vous spécifiez dans la carte Web, mais les fenêtres contextuelles ne sont pas disponibles.",
					div7: "Faites en sorte que votre visite soit brève et factuelle",
					div8: "Le nombre de points par visite est limité à 99. La plupart des Map Tours sont bien entendu beaucoup plus courts. Ne vous attendez pas à ce que votre public ait la patience de parcourir un trop grand nombre de points. Vous trouvez probablement votre sujet fascinant, mais ce ne sera peut-être pas le cas de tout le monde !",
					div9: "Pour en savoir plus, reportez-vous au <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf\' target='_blank'>guide détaillé</a>.",
					div10: "Mode d\'incorporation",
					div11: "Si vous souhaitez intégrer le modèle dans un autre site Web via un iframe, le fait d\'ajouter le paramètre facultatif \"&embed\" à la fin de l\'URL supprimera l\'en-tête. Vous pouvez aussi définir ce mode dans la version à télécharger via le fichier de configuration.",
					div12: "æ_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._Â" 
				},
				tab5: {
					title: "Publication",
					div1: "æ_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._Â",
					div2a: "æ_Sharing the Tour through the builder_Â",
					div2b: "æ_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._Â",
					div2c: "æ_Sharing the Tour through ArcGIS Online_Â",
					div2d: "æ_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._Â",
					div3t: "æ_Feature Service security_Â",
					div3a: "Si vous utilisez un service d\'entités hébergé créé via le générateur de Map Tour, l\'application gère la sécurité du service et vous restez la seule personne dotée de privilèges de modification, même si vous partagez le service publiquement.",
					div3t2: "æ_Before sharing your Tour with your audience_Â",
					div3: "æ_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._Â",
					div4: "æ_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._Â",
					div5a: "æ_Recommendation for search_Â",
					div5b: "æ_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._Â"
				}
			},
			share: {
				firstSaveTitle: "Visite enregistrée",
				firstSaveHeader: "æ_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._Â",
				firstSaveA1: "Si vous n'êtes pas familiarisé avec ArcGIS Online ou si vous voulez un raccourci pour accéder à l'interface de création, vous pouvez enregistrer le lien suivant : %LINK1%",
				firstSaveA1bis: "æ_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._Â",
				firstSaveQ2: "Ma visite est-elle partagée ?",
				firstSaveA2: "æ_Currently your Tour is not shared. To share it, use the SHARE button._Â",
				shareTitle: "Partager votre visite",
				sharePrivateHeader: "Votre visite n'est pas partagée, souhaitez-vous la partager ?",
				sharePrivateBtn1: "Partager publiquement",
				sharePrivateBtn2: "Partager avec mon organisation",
				sharePrivateProgress: "Partage en cours...",
				sharePrivateErr: "Echec du partage, essayez à nouveau ou",
				sharePrivateOk: "Partage mis à jour, en cours de chargement...",
				sharePreviewAsUser: "Aperçu",
				shareHeader1: "Votre visite est <strong>accessible publiquement</strong>.",
				shareHeader2: "Votre visite est accessible par les membres de votre organisation (une ouverture de session est requise).",
				shareLinkHeader: "Partagez la visite avec votre public",
				shareLinkOpen: "OUVRIR",
				shareQ1Opt1: "Comment maintenir la visite privée ?",
				shareQ1Opt2: "æ_How do I keep the Tour private or share it publicly?_Â",
				shareA1: "æ_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._Â",
				shareA1bis: "æ_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._Â",
				shareQ2: "æ_How do I edit the Tour later?_Â",
				shareQ2bis: "æ_How do I get back to the authoring interface?_Â",
				shareA2div1: "æ_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._Â",
				shareA2div2: "En tant que propriétaire de l'application, lorsque vous êtes connecté à ArcGIS.com, l'application affiche un bouton permettant d'ouvrir le générateur interactif :",				
				shareQ3: "Où les données sont-elles stockées ?",
				shareA3: "La configuration de la visite est enregistrée dans <a href='%LINK1%' target='_blank'>cet élément de carte Web</a> et <a href='%LINK2%' target='_blank'>cet élément d'application Web</a>. Si vous avez utilisé une importation Flickr, Picasa, Facebook ou YouTube, vos images et vidéos y restent stockées et ne sont pas dupliquées dans ArcGIS Online."
			}
        }
    })
);
