define(
({
		viewer: {
			loading: {
				step1: "ı_LOADING APPLICATION_İ",
				step2: "ı_LOADING DATA_İ",
				step3: "ı_INITIALIZING THE TOUR_İ",
				loadBuilder: "ı_SWITCHING TO BUILDER MODE_İ",
				redirectSignIn: "ı_REDIRECTING TO SIGN-IN PAGE_İ",
				redirectSignIn2: "ı_(you will be redirected here after sign-in)_İ",
				fail: "ı_Sorry, Map Tour loading failed_İ",
				failButton: "ı_Retry_İ"
			},
			errors: {
				boxTitle: "ı_An error has occurred_İ",
				portalSelf: "ı_Fatal error: Failed to get portal configuration_İ",
				invalidConfig: "ı_Fatal error: Invalid configuration_İ",
				invalidConfigOwner: "ı_Fatal error: Invalid configuration (authorized owner required)_İ",
				invalidConfigNoWebmap: "ı_Fatal error: Invalid configuration (web map or application identifier not specified in index.html)_İ",
				createMap: "ı_Unable to create map_İ",
				invalidApp: "ı_Fatal error: The application cannot be loaded_İ",
				noLayer: "ı_The web map does not contain a valid data layer for Map Tour._İ",
				noLayerMobile: "ı_Welcome to the Map Tour web application. The application is not configured. The Map Tour builder is not supported on mobile devices._İ",
				noLayerView: "ı_Welcome to the Map Tour web application.<br />The application is not configured yet._İ",
				appSave: "ı_Error saving the web application_İ",
				mapSave: "ı_Error saving the web map_İ",
				featureServiceLoad: "ı_Error loading feature service_İ",
				notAuthorized: "ı_You are not authorized to access this application_İ",
				oldBrowserTitle: "ı_Browser not fully supported_İ",
				noBuilderIE8: "ı_The Map Tour builder is not supported on Internet Explorer before version 9._İ",
				ie10Win7Explain: "ı_The Map Tour interactive builder is not supported on Internet Explorer 10 on Windows 7 when the data source is a Feature Service with attachments. To use a Feature Service with attachments, you have to <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manually force document mode to Internet Explorer 9 standards</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgrade to Internet Explorer 9</a> or upgrade to Windows 8._İ",
				oldBrowserExplain: "ı_This browser doesn't support automatic thumbnail generation from the images you upload into your map tour. You can create a map tour using this browser, but you will have to provide a separate thumbnail image for each of the images you upload._İ",
				oldBrowserExplain2: "ı_To improve your experience, <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activate Google Chrome Frame for Internet Explorer</a>._İ",
				oldBrowserExplain3: "ı_The Map Tour builder doesn't work with Internet Explorer 10 on Windows XP._İ",
				oldBrowserClose: "ı_Close_İ"
			},
			mobileHTML: {
				showIntro: "ı_SHOW TITLE_İ",
				hideIntro: "ı_HIDE TITLE_İ",
				navList: "ı_List_İ",
				navMap: "ı_Map_İ",
				navInfo: "ı_Media_İ",
				introStartBtn: "ı_Start_İ"
			},
			desktopHTML: {
				storymapsText: "ı_A story map_İ",
				builderButton: "ı_Switch to builder mode_İ",
				bitlyTooltip: "ı_Get a short link to the application_İ",
				bitlyStartIndex: "ı_Link to current place_İ"
			},
			builderHTML: {
				panelHeader: "ı_APPLICATION CONFIGURATION_İ",
				buttonSave: "ı_SAVE_İ",
				buttonSettings: "ı_Settings_İ",
				buttonShare: "ı_Share_İ",
				buttonView: "ı_View mode_İ",
				buttonItem: "ı_Open the Web Application item_İ",
				buttonHelp: "ı_Help_İ",
				buttonOrganize: "ı_Organize_İ",
				buttonAdd: "ı_Add_İ",
				buttonImport: "ı_Import_İ",
				buttonImportDisabled: "ı_Import is not available when using a Feature Service with attachments_İ",
				dataEditionDisabled: "ı_Data edition is disabled on CSV data source_İ",
				dataSourceWarning: "ı_The Map Tour data layer has changed. If the features ID are not the same, you have to reset the order and hidden points through <b>Organize</b>. If the fields name differs, you have to reset the fields settings under the <b>data tab in Settings</b>._İ",
				organizeWarning: "ı_One or multiple points added outside of the interactive builder are hidden._İ",
				dataPicError0a: "ı_This tour includes <b>%NB%</b> non-compliant picture URLs._İ",
				dataPicError0b: "ı_This tour may includes <b>%NB%</b> non-compliant picture URLs._İ",
				dataPicError1: "ı_Map Tour now requires that a picture URL end with one of the following extension: .jp(e)g, .png, .gif or .bmp._İ",
				dataPicError2: "ı_This requirement will not affect your existing published Map Tour. However, in order to use the interactive builder, you must first resolve the URL issue by performing one of two actions:_İ",
				dataPicError3: "ı_Edit URLs_İ",
				dataPicError4: "ı_This will add <i>#isImage</i> to the end of unsupported picture URLs. Most server support URL appendages. However, once you have performed that action, you should verify that the updated picture URLs are functional by navigating through your points. If each pictures loads, you can now save the Map Tour. If <b>pictures are broken, don’t save the Map Tour</b>. Instead, reload the builder and perform the second action._İ",
				dataPicError5: "ı_Limit the tour to pictures_İ",
				dataPicError6: "ı_This option cause all URLs to be considered images, but you won't be able to add videos using the interactive builder. This action is reversible, should you decide to add video in the future._İ",
				dataPicError7: "ı_Your Map Tour has been restricted to pictures, videos can't be used. If you choose to remove that limitation, check that your pictures still loads correctly before saving the Map Tour. You will be able to restore that limitation later if needed._İ",
				dataPicError8: "ı_Remove picture limitation_İ",
				dataPicError9: "ı_If these URLs points to videos you can ignore this warning, if they point to image, you need to perform one of the following two actions:_İ",
				modalCancel: "ı_Cancel_İ",
				modalApply: "ı_Apply_İ",
				organizeHeader: "ı_Organize the tour_İ",
				organizeGeneralCaption: "ı_Use drag and drop to sort tour points_İ",
				organizeDelete: "ı_Delete_İ",
				organizeHide: "ı_Hide_İ",
				organizeReset: "ı_Reset order and hidden points_İ",
				addMaxPointReached: "ı_You have reached the maximum number of points authorized by the icons set and cannot add another tour point.<br /><br />Note that if you delete existing points, you will need to reload the application._İ",
				addMaxPointReachedMobile: "ı_Sorry, you have reached the maximum number of authorized points and cannot add that picture._İ",
				addClose: "ı_Close_İ",
				addHeader: "ı_Add a new tour point_İ",
				addTabPicture: "ı_Media_İ",
				addTabInformation: "ı_Information_İ",
				addTabLocation: "ı_Location_İ",
				addSelectCaption: "ı_Select or drop picture_İ",
				addNoteVideo: "ı_Consult Help for instructions on using videos_İ",		
				addSelectCaptionNoFileReader: "ı_Select picture_İ",	
				addChangePhoto: "ı_Change picture and thumbnail_İ",
				addPictureResolutionIntro: "ı_The picture resolution is higher than required:_İ",
				addPictureResolutionOldBrowser: "ı_The picture resolution is higher than required. Optimize the Map Tour experience by specifying a resolution lower than %RECOMMENDED_RES%._İ",
				addPictureResolutionResize: "ı_Change picture resolution to %RESOLUTION%_İ",
				addPictureResolutionKeep: "ı_Keep the original resolution of %RESOLUTION%_İ",
				addSelectThumbnail: "ı_Select thumbnail_İ",
				addNoThumbSelected: "ı_No thumbnail selected_İ",
				addThumbSelected: "ı_Selected_İ",
				addCameraSettingsHeader: "ı_CAMERA SETTINGS_İ",
				addThumbnailHeader: "ı_THUMBNAIL_İ",
				addLabelPicUrl: "ı_Picture_İ",
				addLabelThumbUrl: "ı_Thumbnail_İ",
				addTextPlaceholderUrl: "ı_Enter an image URL_İ",
				addTextPlaceholderUrl2: "ı_Enter a Youtube page URL_İ",
				addTextPlaceholderUrl3: "ı_Enter a Vimeo page URL_İ",
				addTextPlaceholderUrl4: "ı_Enter a video embed URL_İ",
				addLabelVideo: "ı_Video_İ",
				addMediaVideoOther: "ı_Other_İ",
				addMediaVideoHelp: "ı_Check the URL and get the default thumbnail_İ",
				addMediaVideoHelpTooltip1: "ı_Check succeeded_İ",
				addMediaVideoHelpTooltip2: "ı_Check failed_İ",
				addMediaVideoHelpTooltip4: "ı_Find the option to embed the video and copy the video URL that is present in the code_İ",
				addLabelName: "ı_Name_İ",
				addLabelDescription: "ı_Caption_İ",
				addTextPlaceholder: "ı_Type something_İ",
				addLocatePlaceholder: "ı_Locate an address or a place_İ",
				addPinColor: "ı_Color_İ",
				addLatitude: "ı_Latitude_İ",
				addLongitude: "ı_Longitude_İ",
				addLatitudePlaceholder: "ı_e.g. 34.056_İ",
				addLongitudePlaceholder: "ı_e.g. -117.195_İ",
				addUploading: "ı_Uploading tour point_İ",
				addSave: "ı_Add tour point_İ",
				addMobileUploading: "ı_Uploading picture_İ",
				addMobileName: "ı_Enter a name_İ",
				addMobileNameMandatory: "ı_Error, please enter a name._İ",
				addMobileError: "ı_Sorry, something has gone wrong_İ",
				settingsHeader: "ı_Application settings_İ",
				settingsTabLayout: "ı_Layout_İ",
				settingsTabColor: "ı_Colors_İ",
				settingsTabLogo: "ı_Header_İ",
				settingsTabFields: "ı_Data_İ",
				settingsTabExtent: "ı_Extent_İ",
				settingsTabZoom: "ı_Zoom Level_İ",
				settingsLayoutExplain: "ı_Select the application layout you want._İ",
				settingsLayoutProfessional: "ı_Three-panel Layout_İ",
				settingsLayoutModern: "ı_Integrated Layout_İ",
				settingsLayoutSelected: "ı_Selected layout_İ",
				settingsLayoutSelect: "ı_Select this layout_İ",
				settingsLayoutNote: "ı_Note that on points using videos, the placard will always be placed under the video even if that option is unchecked._İ",
				settingsLayoutLocBtn: "ı_Display a 'Locate' button_İ",
				settingsLayoutLocBtnHelp: "ı_That functionality is supported on most mobile device and desktop browsers (Internet Explorer 9)._İ",
				settingsColorExplain: "ı_Change appearance by choosing a pre-defined theme, or create your own._İ",
				settingsLabelColor: "ı_Header, content and footer colors_İ",
				settingsLogoExplain: "ı_Customize the header logo (maximum is 250 x 50px)._İ",
				settingsLogoEsri: "ı_Esri logo_İ",
				settingsLogoNone: "ı_No logo_İ",
				settingsLogoCustom: "ı_Custom logo_İ",
				settingsLogoCustomPlaceholder: "ı_Image URL_İ",
				settingsLogoCustomTargetPlaceholder: "ı_Click-through link_İ",
				settingsLogoSocialExplain: "ı_Customize the header top right link._İ",
				settingsLogoSocialText: "ı_Text_İ",
				settingsLogoSocialLink: "ı_Link_İ",
				settingsLogoSocialDisabled: "ı_This feature has been disabled by the Administrator_İ",
				settingsDataFieldsExplain: "ı_Select photo name, caption and color fields._İ",
				settingsDataFieldsError: "ı_The application cannot determine the appropriate name, caption or color data. Please select the fields to be used here. These settings can be changed at a later time._İ",
				settingsFieldsLabelName: "ı_Name_İ",
				settingsFieldsLabelDescription: "ı_Caption_İ",
				settingsFieldsLabelColor: "ı_Color_İ",
				settingsFieldsReset: "ı_Reset fields selection_İ",
				settingsExtentExplain: "ı_Set the Map Tour initial extent through the interactive map below._İ",
				settingsExtentExplainBottom: "ı_The extent you define will modify your web map initial extent. Note that this extent isn't used if it doesn't include the first tour point. In that case the tour will open centered on the first point._İ",
				settingsExtentDateLineError: "ı_The extent cannot be across the meridian of 180° longitude_İ",
				settingsExtentDateLineError2: "ı_Error computing the extent_İ",
				settingsExtentDrawBtn: "ı_Draw a new extent_İ",
				settingsExtentModifyBtn: "ı_Edit the extent_İ",
				settingsExtentApplyBtn: "ı_Preview on Map Tour_İ",
				settingsExtentUseMainMap: "ı_Use Map Tour extent_İ",
				settingsZoomExplain: "ı_Set zoom for story points following introduction (optional)._İ",
				settingsLabelZoom: "ı_Scale/level_İ",
				settingsZoomFirstValue: "ı_None_İ",
				settingsFieldError: "ı_Please select a field in each list_İ",
				dataTitle: "ı_ArcGIS Online hosting_İ",
				dataExplain: "ı_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._İ",
				dataNameLbl: "ı_Service name_İ",
				dataFolderListLbl: "ı_Folder_İ",
				dataFolderListFetching: "ı_Fetching folders ..._İ",
				dataRootFolder: "ı_Root_İ",
				dataNameError: "ı_Enter a name for the feature service_İ",
				dataFolderError: "ı_Select a valid folder_İ",
				dataSrcContainsInvalidChar: "ı_The feature service name contains one or more invalid characters (-, <, >, #, %, :, \", ?, &, +, /, or \)._İ",
				dataSrvAlreadyExistsError: "ı_A service with that name already exists within the organization. Please choose a different name._İ",
				dataBtnSave: "ı_Create the service_İ",
				dataFooterProgress: "ı_Creation in progress_İ",
				dataFooterSucceed: "ı_Creation succeeded. Loading_İ",
				dataFooterError: "ı_Creation failed. Please try again_İ",
				tabError: "ı_Please check for errors in all tabs_İ",
				introRecordBtn: "ı_Intro_İ",
				introRecordActivate: "ı_Use the first point as introduction (does not appear in carousel)_İ"
			},
			addPopupJS: {
				uploadingPicture: "ı_Uploading picture_İ",
				uploadSuccess: "ı_Upload successful_İ",
				uploadError: "ı_Error uploading the picture_İ",
				uploadError2: "ı_Error adding the feature (invalid html tag)_İ",
				notJpg: "ı_Please choose a jpeg photo to upload_İ",
				errorNoPhoto: "ı_Choose an image to upload_İ",
				errorNoThumbnail: "ı_Choose a thumbnail to upload_İ",
				errorInvalidPicUrl: "ı_Enter a valid picture (starts with http(s)://, ends with jpg, png, gif or bmp). You can end the URL with '#isImage' to override that rule._İ",
				errorInvalidThumbUrl: "ı_Enter a valid thumbnail (starts with http(s)://, ends with jpg, png, gif or bmp)._İ",
				errorInvalidVideoUrl: "ı_Enter a valid video URL (starts with http(s)://)_İ",
				errorNoName: "ı_Enter a name for this tour point_İ",
				errorNoDescription: "ı_Enter a caption for this tour point_İ",
				errorNoLocation: "ı_Set a location for this tour point_İ"
			},
			builderJS: {
				noPendingChange: "ı_No unsaved change_İ",
				unSavedChangeSingular: "ı_1 unsaved change_İ",
				unSavedChangePlural: "ı_unsaved changes_İ",
				shareStatus1: "ı_Tour is not saved_İ",
				shareStatus2: "ı_Tour is shared publicly_İ",
				shareStatus3: "ı_Tour is shared within the organization_İ",
				shareStatus4: "ı_Tour is not shared_İ",
				popoverDiscard: "ı_Are you sure to want to discard any unsaved changes?_İ",
				yes: "ı_Yes_İ",
				no: "ı_No_İ",
				popoverLoseSave: "ı_By opening the viewer, you will lose any unsaved changes_İ",
				ok: "ı_Ok_İ",
				popoverSaveWhenDone: "ı_Don't forget to save when you are done_İ",
				closeWithPendingChange: "ı_Are you sure to want to confirm the action ? Your changes will be lost._İ",
				gotIt: "ı_Ok_İ",
				savingApplication: "ı_Saving application_İ",
				saveSuccess: "ı_Application saved successfully_İ",
				saveError: "ı_Save failed, please try again_İ",
				saveError2: "ı_Save failed due to an invalid html tag in a name or description_İ",
				saveError3: "ı_The title can't be empty_İ",
				dragColorPicker: "ı_Move me around<br />or change my color_İ",
				dataWarningExtent: "ı_You have data outside of the web map extent. Those data won't be used as tour points, change map extent if you want to use them._İ",
				dataWarningVisibi: "ı_Your Map Tour layer is not visible at the current web map extent. Confirm your Map Tour layer is visible with a %MAPSIZE% large map._İ",
				dataWarningEdit: "ı_Edit web map_İ",
				dataWarningClose: "ı_Close_İ",
				signIn: "ı_Please sign in with an account on_İ",
				signInTwo: "ı_to save the application._İ",
				switchBM: "ı_Change Basemap_İ"
			},
			organizePopupJS: {
				messageStart: "ı_You have chosen to delete_İ",
				messageSinglePoint: "ı_one tour point_İ",
				messageMultiPoint: "ı_tour points_İ",
				messagePermantRemove: "ı_This will permanently remove the_İ",
				messageRecord: "ı_record_İ",
				messageRecordPlural: "ı_records_İ",
				messageConfirm: "ı_from your database. Do you want to continue?_İ",
				labelButtonShow: "ı_Show_İ",
				labelButtonHide: "ı_Hide_İ"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "ı_This will permanently delete the picture and thumbnail_İ",
				popoverDeleteWarningThumb: "ı_This will permanently delete the thumbnail_İ",
				popoverUploadingPhoto: "ı_Uploading picture and thumbnail_İ",
				popoverUploadingThumbnail: "ı_Uploading thumbnail_İ",
				popoverUploadSuccessful: "ı_Upload successful_İ",
				popoverUploadError: "ı_Upload failed, please try again_İ",
				changePicAndThumb: "ı_Change picture_İ",
				changeThumb: "ı_Change thumbnail_İ",
				selectPic: "ı_Change media_İ",
				selectThumb: "ı_Change thumbnail_İ",
				uploadPicAndThumb: "ı_Apply_İ"
			},
			headerJS:{
				editMe: "ı_Edit me !_İ",
				templateTitle: "ı_Set template title_İ",
				templateSubtitle: "ı_Set template subtitle_İ"
			},
			crossFaderJS:{
				setPicture: "ı_Set picture title_İ",
				setCaption: "ı_Set picture caption_İ"
			},
			importPopup: {
				title: "ı_Import_İ",
				prevBtn: "ı_Back_İ",
				nextBtn: "ı_Next_İ"
			},
			importPopupHome: {
				header: "ı_Where are your pictures stored ?_İ"
			},
			onlinePhotoSharingCommon: {
				pictures: "ı_pictures_İ",
				videos: "ı_videos_İ",
				disabled: "ı_This feature has been disabled by the Administrator_İ",
				disabledPortal: "ı_This feature is disabled on Portal for ArcGIS_İ",
				header1: "ı_Your pictures must be shared publicly._İ",
				header2: "ı_The import will be limited to the first %NB1% %MEDIA%._İ",
				emptyDataset: "ı_Error, no pictures found_İ",
				footerImport: "ı_Import_İ",
				selectAlbum: "ı_Select a public album_İ",
				selectAlbum2: "ı_Select an album_İ",
				pleaseChoose: "ı_Please Choose_İ",
				userLookup: "ı_Look up_İ",
				userLookingup: "ı_Looking up_İ",
				csv: "ı_Referenced in a CSV_İ",
				advanced: "ı_Advanced options_İ",
				advancedScratchLbl: "ı_Start a new Tour_İ",
				advancedScratchTip: "ı_Create an empty Tour that you will be able populate manually using a wizard._İ",
				advancedCSVLbl: "ı_Import Tour data from a CSV file_İ",
				advancedCSVTip: "ı_Import your Tour content from a CSV file._İ",
				advancedCommonTip: "ı_It requires that your images and videos are already online._İ",
				select: "ı_Make a selection_İ",
				locUse: "ı_Use pictures geolocation_İ",
				locExplain: "ı_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._İ",
				locExplain2: "ı_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._İ"
			},
			viewFlickr: {
				title: "ı_Flickr import_İ",
				header: "ı_Enter your Flickr user name and select a Photo Set or a Tag to be imported._İ",
				userInputLbl: "ı_Enter a User Name_İ",
				signInMsg2: "ı_User not found_İ",
				selectSet: "ı_Select a Photo Set_İ",
				selectTag: "ı_or Select a Tag_İ",
				footerImportTag: "ı_Import the selected Tag_İ",
				footerImportSet: "ı_Import the selected Set_İ"
			},
			viewFacebook: {
				title: "ı_Facebook import_İ",
				header: "ı_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._İ",
				leftHeader: "ı_Facebook User_İ",
				rightHeader: "ı_Facebook Page_İ",
				pageExplain: "ı_A Facebook page is a public brand/product or celebrity like <b>esrigis</b>. You can get the page name after the first '/' in the page URL._İ",
				pageInputLbl: "ı_Enter a page name_İ",
				lookupMsgError: "ı_Page not found_İ"
			},
			viewPicasa: {
				title: "ı_Picasa/Google+ import_İ",
				header: "ı_Enter your email address or the ID of your Picasa or Google+ account._İ",
				userInputLbl: "ı_Enter an email or ID_İ",
				signInMsg2: "ı_Account not found_İ",
				howToFind: "ı_How to find a Picasa or Google+ account ID_İ",
				howToFind2: "ı_Copy digits between the first and second '/' of any Picasa or G+ page_İ"
			},
			viewCSV: {
				title: "ı_CSV import_İ",
				uploadBtn: "ı_Select or drop a CSV file_İ",
				resultHeaderEmpty: "ı_The CSV is empty_İ",
				resultHeaderSuccess: "ı_Successfully loaded %NB_POINTS% points_İ",
				resultHasBeenLimited: "ı_The import has been limited to the first %VAL1% points out of %VAL2% to respect the limit of %VAL3% points per tour_İ",
				browserSupport: "ı_Your browser isn't supported, to use a CSV you have to <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or use ArcGIS.com web map viewer (see Help)._İ",
				errorLatLng: "ı_Latitude and Longitude fields haven't been found. Possible values for latitude are: <i>%LAT%</i> and for longitude: <i>%LONG%</i>._İ",
				errorFieldsExplain: "ı_The loading failed as the following required fields hasn't been found_İ",
				errorFieldsName: "ı_<b>Name</b> possible values are: %VAL%_İ",
				errorFieldsDesc: "ı_<b>Description</b> possible values are: %VAL%_İ",
				errorFieldsUrl: "ı_<b>Picture URL</b> possible values are: %VAL%_İ",
				errorFieldsThumb: "ı_<b>Thumbnail URL</b> possible values are: %VAL%_İ",
				errorFields2Explain: "ı_The loading failed as the CSV does not use the same attributes than the layer for the following attributes_İ",
				errorFields2Name: "ı_<b>Name</b> use %VAL1% instead of %VAL2%_İ",
				errorFields2Desc: "ı_<b>Description</b> use %VAL1% instead of %VAL2%_İ",
				errorFields2Url: "ı_<b>Picture URL</b> use %VAL1% instead of %VAL2%_İ",
				errorFields2Thumb: "ı_<b>Thumbnail URL</b> use %VAL1% instead of %VAL2%_İ",
				resultFieldsAll: "ı_All attributes have been imported_İ",
				resultFieldsNotAll: "ı_The following attributes haven't been imported because they don't exists in the map layer_İ",
				resultFieldsNotAll2: "ı_The following attributes have been imported_İ",
				footerNextBtnResult: "ı_Import into the web map_İ",
				footerProgress: "ı_Import in progress_İ",
				footerSucceed: "ı_Import succeeded. Loading_İ"
			},
			viewYoutube: {
				title: "ı_Youtube import_İ",
				header: "ı_Enter a YouTube user name to find publicly shared videos._İ",
				pageInputLbl: "ı_Enter a Youtube user name_İ",
				lookupMsgError: "ı_User not found_İ",
				howToFind: "ı_How to find a Youtube user name_İ",
				howToFind2: "ı_User name is displayed under videos_İ",
				found: "ı_Found_İ",
				noData: "ı_No public videos found_İ"
			},
			viewGeoTag: {
				title: "ı_Select and locate your images/videos_İ",
				header: "ı_Click or tap the pictures you want to import to locate them._İ",
				headerMore: "ı_Why aren't my images/videos geolocated?_İ",
				headerExplain: "ı_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._İ",
				leftPanelTab1: "ı_To locate_İ",
				leftPanelTab2: "ı_Located_İ",
				clickOrTap: "ı_Click or tap the Map to locate_İ",
				clearLoc: "ı_Clear locations_İ",
				clickDrop: "ı_Do not import_İ",
				footerImport: "ı_Import_İ",
				footerProgress: "ı_Import in progress_İ",
				footerSucceed: "ı_Import succeeded. Loading..._İ",
				loading: "ı_Loading_İ",
				error: "ı_Pictures geolocation import failed, geolocations have been ignored._İ"
			},
			initPopup: {
				title: "ı_Welcome to the Map Tour Builder_İ",
				prevBtn: "ı_Back_İ",
				nextBtn: "ı_Next_İ"
			},
			initPopupHome: {
				header1: "ı_Where are your images or videos?_İ",
				header2: "ı_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._İ",
				title1: "ı_They are already online_İ",
				title2: "ı_I need to upload my images_İ",
				hostedFSTooltip: "ı_Use ArcGIS Online to host your images (doesn't support videos)._İ",
				hostedFsNA: "ı_Only available for ArcGIS for Organizations Publisher and Administrator users_İ",
				footer1: "ı_When you are done, don't forget to share your Map Tour with your audience through the application item page._İ",
				footer3: "ı_Download the CSV template_İ",
				footer4: "ı_\"Save as\" if it doesn't download_İ",
				footer4bis: "ı_Use right click and \"Save as\" if download doesn't start_İ",
				footer5: "ı_Learn more_İ",
				footerProgress: "ı_Creation in progress_İ",
				footerSucceed: "ı_Creation succeeded. Loading..._İ"
			},
			helpPopup: {
				title: "ı_Help_İ",
				close: "ı_Close_İ",
				tab1: {
					title: "ı_Introduction_İ",
					div1: "ı_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._İ",
					div2: "ı_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_İ",
					div4: "ı_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._İ",
					div42: "ı_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._İ",
					div5: "ı_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._İ"
				},
				tab2: {
					title: "ı_Data_İ",
					div1: "ı_The main element to consider when building a Map Tour is to choose where your pictures will be stored. A Map Tour can use pictures stored on major photo sharing services, on any web server, or as attachments to a feature service._İ",
					div1a: "ı_See the last section of this tab for details about supported picture formats and videos._İ",
					div2: "ı_The interactive builder gives you two options for handling the images in your Map Tour:_İ",
					div3: "ı_<ul><li>You can use <b>photos that are already online</b>, such as images stored in a photo sharing site like Flickr, or images stored on your own website. These images will be referenced in your Map Tour via their URLs.</li><li>You can also <b>upload photos from your computer</b> directly into your Map Tour. This upload option requires that you have an ArcGIS Online subscription and that you have Publisher or Administrator privileges, because a hosted feature service is automatically created for you in which your photos are stored as attachments.</li></ul>_İ",
					div4: "ı_The main use cases are:_İ",
					div4b: "ı_<b>Your photos are not hosted</b> yet and you have an ArcGIS Online subscription: Using a hosted feature service is your best choice. Like public photo sharing services, we will optimize your pictures to create fast-loading images and you will have access to all administration and data management capabilities of the ArcGIS platform._İ",
					div5: "ı_<b>You aren't a member of an Organization</b>: You first have to upload your pictures to a photo sharing website or to your own web server. The builder will help you use these pictures that will continue to be hosted at their original location._İ",
					div6: "ı_<b>You are looking to reuse an existing Feature Service</b> that stores your pictures as attachments or that references external pictures: See the detailed section below._İ",
					div7: "ı_<b>You are a user of a previous version</b> of the Map Tour template and already have your CSV that references your pictures and thumbnails: You will be able to import it and refine your data. The builder only supports CSVs that use lat/long fields; address-based CSVs can continue to be used through your web map (see section below)._İ",
					div8: "ı_Importing from online photo sharing services_İ",
					div9: "ı_The import operation references pictures that are already hosted by storing their URLs in a web map feature collection. The pictures are not stored in ArcGIS Online. If the hosted pictures can't be accessed, they won't be available in the Map Tour and you'll see a 'Picture not available' image. Depending on your photo service provider, the Map Tour may not import the name, description, and location of the pictures. Those attributes are stored in the web map and any edits to the online services won't be reflected in the Map Tour._İ",
					div10: "ı_Storing the pictures on a web server_İ",
					div11: "ı_If you choose to host the pictures yourself, you will have to manually create thumbnails of your pictures. Using the full resolution pictures for the thumbnail will result in poor performance. For that reason, we strongly recommend that you use an online photo sharing services or a feature service that will do that for you._İ",
					div12: "ı_Using an existing Feature Service or Shapefile_İ",
					div13: "ı_Any point feature service or shapefile can be used as a Map Tour data source. You just have to add it as a layer into your web map through the arcgis.com Map Viewer. If the application finds the expected attributes in your layer, all builder functionalities will be available._İ",
					div14: "ı_The possible values for fields name are (case insensitive):_İ",
					div151: "ı_Name_İ",
					div152: "ı_Description_İ",
					div153: "ı_Picture_İ",
					div154: "ı_Thumbnail_İ",
					div155: "ı_Color_İ ",
					div16: "ı_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._İ",
					div162: "ı_When using a feature service that stores the pictures as attachments, <b>only the features with two attachments will be used</b>. The first attachment defines the main picture, and the second attachment defines the thumbnail._İ",
					div17: "ı_The picture and thumbnail fields are mandatory for feature services without attachments and optional (but strongly recommended) for feature services with attachments. If your service has attachments enabled, the builder will let you upload pictures as attachments. If not, you will only be able to edit the picture and thumbnail URLs._İ",
					div172: "ı_When present, the picture and thumbnail fields will always be used and the feature service attachments won't be queried._İ",
					div173: "ı_Example CSVs and shapefiles can be downloaded from_İ",
					div18: "ı_Creating a hosted Feature Services from a CSV or shapefile_İ",
					div19: "ı_When you create a hosted feature service from a CSV or shapefile, the attachments are not enabled by default. To enable them, open the feature service’s details page, click the small arrow on the layer section, and you will see that option. The Map Tour will continue to use the pictures and thumbnail you have referenced through attributes. Optionally, if you want to upload your pictures as feature service attachments, you will be able to do so through two buttons on the picture panel (\"Change Picture\" and \"Change Thumbnail\")._İ",
					div20: "ı_Supported pictures formats and videos_İ",
					div21: "ı_Supported picture format are: <b>.jpg, .jpeg, .png, .gif and .bmp</b>. If your media doesn’t end with that extension, the Map Tour will consider it to be a video, except when using a feature service (see below)._İ",
					div22: "ı_The Map Tour template doesn't include a video player, so you have to use the external video player provided by your favorite video hosting service (find the option to embed the video and copy the URL present in the given code). If you want to host the video yourself, you can create an HTML page that contains a video player like <a href='http://www.videojs.com/'>Video.js</a>._İ",
					div23: "ı_The interactive builder doesn't provide a dialog to include video when using feature services with attachments, but it is possible to do so by editing your data outside of the interactive builder. In the arcgis.com map viewer, if you modify the picture fields to point to an external video and add a special parameter at the end of your URL (#isVideo), your media will be considered to be a video._İ",
					div24: "ı_Note that you still need to have two valid pictures attachments or the point won’t be used. It isn't possible to use videos when using feature service attachments without the picture and thumbnail fields._İ"
				},
				tab3: {
					title: "ı_Customization_İ",
					div1: "ı_The builder provides several customization options that are accessible through the SETTINGS button in the top panel. If you don't find the option you expect, we also provide a downloadable version that you can deploy on your web server and enhance to fit your needs._İ",
					div2: "ı_We recommend that you use the hosted version unless:_İ",
					div3: "ı_<li>It doesn't offer a UI customization you want to have, like using a header background image.</li><li>You are a developer and you want to enhance the application.</li>_İ",
					div4: "ı_The downloadable version can be configured through a web map or a web mapping application identifier. The main use cases are:_İ",
					div41: "ı_You build your map tour using the interactive builder in the hosted environment and configure the template with the web mapping application identifier. The settings you have defined with the interactive builder will be applied._İ",
					div42: "ı_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._İ",
					div43: "ı_Note that the interactive builder is available in the downloadable version but with some technical restrictions on browsers like Internet Explorer older than version 10._İ",
					div5: "ı_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._İ"
				},
				tab4: {
					title: "ı_Tips_İ",
					div0: "ı_Supported browsers_İ",
					div0a: "ı_The Map Tour viewer is supported on IE8+. The interactive builder is supported on IE9+. We actively test it in all major browsers but if you experience some difficulties, we recommend that you use Chrome._İ",
					div0b: "ı_If you experience some difficulties, please let us know. In the meantime, by building your Map Tour using the CSV template you will minimize your interaction with the builder interface._İ",
					div1: "ı_Pictures_İ",
					div2: "ı_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._İ",
					div2a: "ı_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._İ",
					div3: "ı_Formatting your caption text using HTML tags_İ",
					div4: "ı_The header and picture title/caption can include HTML tags to define formatting and links. For example, this code adds a yellow link:_İ",
					div4a: "ı_Write a good subtitle for your tour_İ",
					div4b: "ı_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._İ",
					div5: "ı_Supporting Layers_İ",
					div6: "ı_You can add additional supporting layers to provide context to the Map Tour. These layers may contain other geographic features you want the map to show in addition to the Map Tour points, such as a study area, a walking or driving route linking your tour points, etc. The Map Tour template displays these additional supporting layers using the symbology you specify in the web map, but the popups aren't available._İ",
					div7: "ı_Keep your tour short and sweet_İ",
					div8: "ı_There's a limit of 99 points per tour. Most Map Tours will of course be significantly shorter than this. Don't expect your audience to want to step through too many tour points. You might find your subject fascinating, but don't assume they will, too!_İ",
					div9: "ı_To learn more, see <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>the detailed guide</a>._İ",
					div10: "ı_Embed mode_İ",
					div11: "ı_If you want to embed the template in another website through an iframe, adding the optional parameter \"&embed\" at the end of the URL will remove the header. That mode can also be set in the downloadable version through the configuration file._İ",
					div12: "ı_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._İ" 
				},
				tab5: {
					title: "ı_Publishing_İ",
					div1: "ı_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._İ",
					div2a: "ı_Sharing the Tour through the builder_İ",
					div2b: "ı_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._İ",
					div2c: "ı_Sharing the Tour through ArcGIS Online_İ",
					div2d: "ı_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._İ",
					div3t: "ı_Feature Service security_İ",
					div3a: "ı_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._İ",
					div3t2: "ı_Before sharing your Tour with your audience_İ",
					div3: "ı_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._İ",
					div4: "ı_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._İ",
					div5a: "ı_Recommendation for search_İ",
					div5b: "ı_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._İ"
				}
			},
			share: {
				firstSaveTitle: "ı_Tour successfully saved_İ",
				firstSaveHeader: "ı_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._İ",
				firstSaveA1: "ı_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_İ",
				firstSaveA1bis: "ı_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._İ",
				firstSaveQ2: "ı_Is my Tour shared?_İ",
				firstSaveA2: "ı_Currently your Tour is not shared. To share it, use the SHARE button._İ",
				shareTitle: "ı_Share your Tour_İ",
				sharePrivateHeader: "ı_Your Tour is not shared, would you like to share it?_İ",
				sharePrivateBtn1: "ı_Share publicly_İ",
				sharePrivateBtn2: "ı_Share with my Organization_İ",
				sharePrivateProgress: "ı_Sharing in progress..._İ",
				sharePrivateErr: "ı_Sharing failed, try again or_İ",
				sharePrivateOk: "ı_Sharing updated successfully, loading..._İ",
				sharePreviewAsUser: "ı_Preview_İ",
				shareHeader1: "ı_Your Tour is <strong>publicly accessible</strong>._İ",
				shareHeader2: "ı_Your Tour is accessible by your organization members (login is required)._İ",
				shareLinkHeader: "ı_Share the Tour with your audience_İ",
				shareLinkOpen: "ı_OPEN_İ",
				shareQ1Opt1: "ı_How do I keep the Tour private?_İ",
				shareQ1Opt2: "ı_How do I keep the Tour private or share it publicly?_İ",
				shareA1: "ı_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._İ",
				shareA1bis: "ı_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._İ",
				shareQ2: "ı_How do I edit the Tour later?_İ",
				shareQ2bis: "ı_How do I get back to the authoring interface?_İ",
				shareA2div1: "ı_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._İ",
				shareA2div2: "ı_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_İ",				
				shareQ3: "ı_Where is the data stored?_İ",
				shareA3: "ı_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._İ"
			}
        }
    })
);
