define(
	 ({
		header: {
			start: "Ĳ_start___ä",
			searchStories: "Ĳ_Search your stories________ä...",
			filter: "Ĳ_Filter___ä",
			sort: "Ĳ_Sort__ä",
			sortColon: "Ĳ_Sort___ä:",
			numResults: "Ĳ_Results: {{NUM_RESULTS}}________ä",
			sortBy: "Ĳ_Sort by___ä",
			dateModified: "Ĳ_Date modified_____ä",
			title: "Ĳ_Title___ä",
			type: "Ĳ_Type__ä",
			views: "Ĳ_Views___ä",
			errors: "Ĳ_Errors___ä",
			filterBy: "Ĳ_Filter by____ä",
			filterItems: "Ĳ_Filter Items_____ä",
			apps: "Ĳ_Apps__ä",
			sharing: "Ĳ_Sharing___ä",
			clearAll: "Ĳ_Clear all____ä",
			clearSearch: "Ĳ_Clears the search______ä",
			logOut: "Ĳ_Log Out___ä",
			mainQuote: "Ĳ_Storytelling is the most powerful way to put ideas into the world today_______________________ä.",
			quoteSource: "Ĳ_Robert McKee_____ä",
			checkYourStories: "Ĳ_Check Stories_____ä",
			createStory: "Ĳ_Create Story_____ä",
			totalStories: "Ĳ_Total stories: {{NUM_STORIES}}__________ä",
			noIssues: "Ĳ_All good___ä",
			userStories: "Ĳ_Stories of {{USER_NAME}}________ä",
			headerDisabledTooltip: "Ĳ_Please wait while we work some magic_____________ä...",
			notOnTouch: "Ĳ_Not available on touch devices__________ä",
		},
		deleteModal: {
			title: "Ĳ_Confirm Delete_____ä",
			warningText: "Ĳ_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________ä.",
			deleteText: "Ĳ_Delete___ä",
			cancel: "Ĳ_Cancel___ä"
		},
		loading: {
			loadingText: "Ĳ_Loading your stories________ä..."
		},
		cantFindStories: {
			whereAreStories: "Ĳ_Not seeing your story________ä?",
			notSeeExplanation: "Ĳ_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________ä.",
			faq: "Ĳ_FAQ__ä",
			followingStoriesToUpdate: "Ĳ_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________ä:",
			gettingStories: "Ĳ_Searching for stories created with early versions of our applications that need to be updated______________________________ä...",
			title: "Ĳ_Title___ä",
			typeOfStoryMap: "Ĳ_Type__ä",
			lastModified: "Ĳ_Last modified_____ä",
			allUpToDate: "Ĳ_No stories created with early versions of our applications need to be updated________________________ä.",
			updateAll: "Ĳ_Update All____ä",
			errorScanningForStories: "Ĳ_There was an error searching your stories______________ä.",
			close: "Ĳ_Close___ä",
			updates: "Ĳ_Updates___ä",
			updatingNumberOfNumber: "Ĳ_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________ä",
			updatingNumberOfNumberAlt: "Ĳ_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________ä",
			updateSucceeded: "Ĳ_Update succeeded______ä!",
			reloadingStories: "Ĳ_Reloading your stories_________ä...",
			errorUpdatingStories: "Ĳ_There was an error updating your stories_____________ä.",
			partialUpdateMessage: "Ĳ_Stories updated successfully: {{NUM_UPDATED}}_______________ä"
		},
		signIn: {
			signInTitle: "Ĳ_Sign in to Story Maps_______ä",
			signInTo: "Ĳ_Sign in with your existing ArcGIS Online account to_________________ä:",
			explanationOne: "Ĳ_Create compelling story maps to tell your stories________________ä.",
			explanationTwo: "Ĳ_Use your maps and data from ArcGIS Online in your story maps___________________ä.",
			explanationThree: "Ĳ_Manage your story maps and check the status of their content___________________ä.",
			dontHaveAccount: "Ĳ_Don't have an ArcGIS Online account? Sign up for a________________ä:",
			publicAccount: "Ĳ_Free non-commercial public account___________ä",
			orgAccount: "Ĳ_Free trial ArcGIS subscription__________ä",
			timeExpired: "Ĳ_Your sign-in expired. Sign in again to pick up where you left off_____________________ä.",
			apiDidntLoad: "Ĳ_Something isn't loading correctly. Try refreshing the page___________________ä.",
			needAccount: "Ĳ_Need an account______ä?",
			letsGo: "Ĳ_Let's go____ä!"
		},
		sharingLevel: {
			publicMessage: "Ĳ_Public___ä",
			privateMessage: "Ĳ_Private___ä",
			organization: "Ĳ_Organization_____ä",
			changedSharing: "Ĳ_Changed sharing level________ä.",
			unableToChange: "Ĳ_Unable to change sharing_________ä.",
			partOfMap: "Ĳ_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________ä.",
			storyPublicContentOrg: "Ĳ_Your story is public, so its content can't be shared only with your organization_________________________ä",
			storyPublicContentPrivate: "Ĳ_Your story is public, so its content can't be private_________________ä",
			mapOrg: "Ĳ_Sharing your map to your organization would break your story___________________ä",
			layerOrg: "Ĳ_Sharing your layer to your organization would break your story____________________ä",
			mapPrivate: "Ĳ_Making your map private would break your story_______________ä",
			layerPrivate: "Ĳ_Making your layer private would break your story_______________ä"
		},
		collectionList: {
			advocacy: "Ĳ_Advocacy and Outreach_______ä",
			architecture: "Ĳ_Architecture and Design________ä",
			conservation: "Ĳ_Conservation and Sustainability__________ä",
			culture: "Ĳ_Culture___ä",
			destinations: "Ĳ_Destinations and Tourism________ä",
			disasters: "Ĳ_Disasters and Recovery________ä",
			economy: "Ĳ_Economy and Development________ä",
			entertainment: "Ĳ_Entertainment_____ä",
			history: "Ĳ_History___ä",
			infrastructure: "Ĳ_Infrastructure_____ä",
			marketing: "Ĳ_Marketing____ä",
			nature: "Ĳ_Nature and Environment________ä",
			news: "Ĳ_News and Events______ä",
			oceans: "Ĳ_Oceans___ä",
			parks: "Ĳ_Parks and Recreation_______ä",
			people: "Ĳ_People and Society______ä",
			planning: "Ĳ_Planning and Analysis_______ä",
			publicArt: "Ĳ_Public Art____ä",
			science: "Ĳ_Science and Technology________ä",
			sport: "Ĳ_Sport___ä",
			travelogues: "Ĳ_Travelogues____ä"
		},
		types: {
			custom: "Ĳ_Custom___ä",
			notSpecified: "Ĳ_Type not specified______ä"
		},
		storyMap: {
			shared: "Ĳ_Shared___ä",
			saveFailed: "Ĳ_Error saving_____ä",
			numViews: "Ĳ_Views: {{NUM_VIEWS}}_______ä",
			editStory: "Ĳ_Edit Story____ä",
			viewLive: "Ĳ_View Live____ä",
			preview: "Ĳ_Preview___ä",
			deleteButton: "Ĳ_Delete___ä",
			modified: "Ĳ_Modified {{DATE}}______ä",
			summary: "Ĳ_Summary___ä",
			loading: "Ĳ_Loading____ä...",
			collapse: "Ĳ_collapse___ä",
			close: "Ĳ_close___ä",
			hide: "Ĳ_hide__ä",
			notAvailableWhenBroken: "Ĳ_Your story has issues below_________ä",
			cantBeDeleted: "Ĳ_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________ä",
			shareDialog: {
				title: "Ĳ_Share your story with the world___________ä!",
				notPublicWarning: "Ĳ_Your story is shared with your organization. Only members of your organization will be able to view it________________________________ä.",
				embedStory: "Ĳ_Embed your story______ä",
				shortLink: "Ĳ_Shortlink____ä",
				hideHeaderBar: "Ĳ_Hide header bar______ä",
				copied: "Ĳ_Copied___ä",
				small: "Ĳ_small___ä",
				medium: "Ĳ_medium___ä",
				large: "Ĳ_large___ä",
				custom: "Ĳ_custom___ä",
				widthAbbreviation: "Ĳ_w_ä",
				heightAbbreviation: "Ĳ_h_ä",
				emptyDimension: "Ĳ_Enter a dimension______ä.",
				seeExample: "Ĳ_Preview your embed______ä",
				removeHeader: "Ĳ_Hide application header________ä"
			},
			maps: {
				unableRetrieveTitle: "Ĳ_Unable to retrieve maps________ä",
				unableRetrieveDescription: "Ĳ_We weren't able to retrieve maps for this story map_________________ä."
			},
			images: {
				unableRetrieveTitle: "Ĳ_Unable to retrieve images_________ä",
				unableRetrieveDescription: "Ĳ_We weren't able to retrieve images for this story map_________________ä."
			},
			tags: {
				tags: "Ĳ_Tags__ä",
				collectionTags: "Ĳ_Subject___ä",
				selectASubject: "Ĳ_Select a subject______ä",
				save: "Ĳ_Save__ä",
				saved: "Ĳ_Saved___ä",
				errorSaving: "Ĳ_Error saving_____ä",
				tagTip: "Ĳ_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________ä."
			},
			submitToGallery: {
				gallerySubmission: "Ĳ_Story Maps Gallery______ä",
				canSubmitIf: "Ĳ_You can nominate your story to the gallery if it contains the following_______________________ä:",
				hasOwnImage: "Ĳ_Custom thumbnail______ä",
				chosenSubject: "Ĳ_A subject and some tags________ä",
				chosenSubjectAlt: "Ĳ_A {{SUBJECT}} and some tags_________ä",
				storyMapTopicSubject: "Ĳ_subject___ä",
				sharedPublicly: "Ĳ_Shared publicly______ä",
				noBrokenContent: "Ĳ_No broken content______ä",
				nominateToGallery: "Ĳ_Nominate to Gallery_______ä",
				comingSoon: "Ĳ_Coming soon_____ä!",
				submitted: "Ĳ_Submitted____ä",
				errorSubmitting: "Ĳ_Error submitting______ä",
				ourGallery: "Ĳ_The Story Maps gallery________ä",
				galleryTip: "Ĳ_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________ä."
			},
			placeholders: {
				noSummary: "Ĳ_No summary, click to add one__________ä."
			},
			errors: {
				cantDeleteStory: "Ĳ_Unable to delete story________ä.",
				unableToFind: "Ĳ_Unable to find content________ä",
				unableToRetrieve: "Ĳ_We weren't able to retrieve the content for this story map___________________ä."
			},
			socialSharing: {
				availableWhenPublic: "Ĳ_This option will be available when your story is public__________________ä"
			},
			dialog: {
				back: "Ĳ_Back__ä",
				close: "Ĳ_Close___ä",
				cancel: "Ĳ_Cancel___ä"
			},
			imagePicker: {
				changeDefault: "Ĳ_Change the default image________ä",
				changeImage: "Ĳ_Change thumbnail______ä",
				uploadImage: "Ĳ_Upload thumbnail______ä",
				chooseImage: "Ĳ_Choose thumbnail______ä",
				chooseAnImage: "Ĳ_Choose an Image______ä",
				notInIEVersion: "Ĳ_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________ä.",
				or: "Ĳ_Or__ä",
				uploadAnImage: "Ĳ_Upload an Image______ä",
				supportedFileTypes: "Ĳ_Supports .png, .jpg, .gif_________ä",
				imageSizeMessage: "Ĳ_Your image needs to be at least 286 px wide by 190 px tall___________________ä.",
				minimumDimensions: "Ĳ_Minimum: 286 x 190px_______ä",
				imagesLoading: "Ĳ_Loading images______ä...",
				noImages: "Ĳ_This story has no images________ä",
				errorLoading: "Ĳ_Unable to retrieve the images in this story______________ä",
				clickBelowTip: "Ĳ_Click the button below to upload an image______________ä.",
				dragAndDrop: "Ĳ_Drag and Drop_____ä",
				cropImage: "Ĳ_Crop Image____ä",
				saveImage: "Ĳ_Save Image____ä",
				save: "Ĳ_Save__ä",
				savingImage: "Ĳ_Saving your image_______ä...",
				saved: "Ĳ_Saved___ä!",
				errorSaving: "Ĳ_Unable to save your image_________ä.",
				skipAndCrop: "Ĳ_Skip and Crop for me_______ä",
				wrongFormat: "Ĳ_This file type is not supported___________ä.",
				noCropWarning: "Ĳ_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________ä."
			}
		},
		content: {
			media: {
				maps: "Ĳ_Maps__ä",
				images: "Ĳ_Images___ä",
				videos: "Ĳ_Videos___ä",
				webpages: "Ĳ_Webpages___ä",
				tags: "Ĳ_Tags__ä",
				gallery: "Ĳ_Gallery___ä"
			},
			headers: {
				status: "Ĳ_Status___ä",
				source: "Ĳ_Source___ä",
				name: "Ĳ_Name__ä",
				shared: "Ĳ_Shared___ä"
			},
			component: {
				mapTour: "Ĳ_Point Number_____ä",
				bullet: "Ĳ_Bullet___ä",
				tab: "Ĳ_Tab__ä",
				accordion: "Ĳ_Section___ä",
				mapJournal: "Ĳ_Section___ä"
			},
			titleType: {
				mapTour: "Ĳ_Caption___ä",
				mapJournal: "Ĳ_URL__ä",
				mapSeries: "Ĳ_URL__ä"
			},
			actions: {
				viewMap: "Ĳ_View Map___ä",
				editMap: "Ĳ_Edit Map___ä",
				fix: "Ĳ_Fix__ä",
				viewLayer: "Ĳ_View Layer____ä"
			},
			contentType: {
				mainStage: "Ĳ_main stage action______ä",
				sidePanel: "Ĳ_description____ä"
			},
			notification: {
				refreshExplanation: "Ĳ_Check your story again________ä",
				checking: "Ĳ_Checking____ä...",
				foundSomeIssues: "Ĳ_We found some issues_______ä",
				noIssuesFound: "Ĳ_No issues found______ä",
				storyPublic: "Ĳ_Your story is now public________ä",
				storyOrg: "Ĳ_Your story is now shared to your organization_______________ä",
				storyPrivate: "Ĳ_Your story is now private_________ä",
				mapPublic: "Ĳ_Your map is now public________ä",
				mapOrg: "Ĳ_Your map is now shared to your organization______________ä",
				mapPrivate: "Ĳ_Your map is now private________ä",
				layerPublic: "Ĳ_Your layer is now public________ä",
				layerOrg: "Ĳ_Your layer is now shared to your organization_______________ä",
				layerPrivate: "Ĳ_Your layer is now private_________ä",
				contentPublic: "Ĳ_Your content is now public_________ä",
				contentOrg: "Ĳ_Your content is now shared to your organization_______________ä",
				contentPrivate: "Ĳ_Your content is now private_________ä",
				storyAndContentPublic: "Ĳ_Your story and its content are now public_____________ä",
				storyAndContentOrg: "Ĳ_Your story and its content are now shared to your organization____________________ä",
				storyAndContentPrivate: "Ĳ_Your story and its content are now private______________ä",
				shareBulkPrompt: "Ĳ_Do you want to share your storyâ€™s content accordingly__________________ä?",
				layersPublic: "Ĳ_Some layers have also been shared publicly______________ä",
				layersOrg: "Ĳ_Some layers have also been shared with your organization__________________ä",
				layersPrivate: "Ĳ_Some layers have also been made private_____________ä",
				mapsPublic: "Ĳ_Some maps have also been shared publicly_____________ä",
				mapsOrg: "Ĳ_Some maps have also been shared with your organization_________________ä",
				mapsPrivate: "Ĳ_Some maps have also been made private____________ä",
				layersAndMapsPublic: "Ĳ_Some maps and layers have also been shared publicly________________ä",
				layersAndMapsOrg: "Ĳ_Some maps and layers have also been shared with your organization_____________________ä",
				layersAndMapsPrivate: "Ĳ_Some maps and layers have also been made private_______________ä",
				yes: "Ĳ_Yes__ä",
				no: "Ĳ_No__ä",
				premiumPublicSuccess: "Ĳ_Your premium content is now publicly accessible_______________ä",
				subscriptionPublicSuccess: "Ĳ_Your subscription content is now publicly accessible_________________ä"
			},
			errors: {
				publicDisabled: "Ĳ_Sharing publicly has been disabled by the Administrator__________________ä",
				noMapName: "Ĳ_Could Not Retrieve Map Name_________ä",
				notPublic: "Ĳ_NOT PUBLIC____ä",
				inaccessible: "Ĳ_INACCESSIBLE_____ä",
				deleted: "Ĳ_DELETED___ä",
				cantAccessVideo: "Ĳ_Could Not Access Video________ä",
				noStoriesFound: "Ĳ_We could not find any Story Maps in your content________________ä.",
				cantShowStories: "Ĳ_Unable to show your story maps. Please try again later__________________ä.",
				consolationSearch: "Ĳ_We couldn't find any stories__________ä.",
				notCompatibleWithBrowser : "Ĳ_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________ä.",
				pleaseUpdateBrowser: "Ĳ_Please update your browser_________ä.",
				searchTip: "Ĳ_Try and simplify it a bit_________ä.",
				consolationNoStories: "Ĳ_Welcome to My Stories________ä!",
				noStoriesTip: "Ĳ_To make your first story map, check out the Apps page_________________ä.",
				letsGo: "Ĳ_Let's Go___ä",
				cantChangeSharingLevel: "Ĳ_Unable to change sharing level__________ä",
				cantChangeSharingLevels: "Ĳ_Unable to change sharing levels__________ä",
				errorUpdatingTitle: "Ĳ_Error updating title_______ä",
				errorUpdatingSummary: "Ĳ_Error updating summary________ä",
				noEmptyTitle: "Ĳ_Title cannot be empty_______ä",
				cantUpdatePremiumContent: "Ĳ_Unable to update premium content___________ä",
				cantUpdateSubscriptionContent: "Ĳ_Unable to update subscription content____________ä",
				createFirstStory: "Ĳ_Create My First Story_______ä"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Ĳ_Map has been deleted_______ä",
				layerHasBeenDeleted: "Ĳ_Layer has been deleted________ä",
				mapIsInaccessible: "Ĳ_Map is inaccessible_______ä",
				layerIsInaccessible: "Ĳ_Layer is inaccessible_______ä",
				mapNotYoursNotAccessible: "Ĳ_Map is owned by someone else and isn't accessible________________ä",
				layerServiceOkItemNot: "Ĳ_Layer was added as an item that is deleted or inaccessible__________________ä",
				layerNotYoursNotAccessible: "Ĳ_Layer is owned by someone else and isn't accessible________________ä",
				mapOthersSharedBelowLevel: "Ĳ_Map is not owned by you and is not public_____________ä",
				layerOthersSharedBelowLevel: "Ĳ_Layer is not owned by you and is not public______________ä",
				noMapNoDetails: "Ĳ_Without the map details, we can't tell you anything about the layers_____________________ä",
				mapIsPrivate: "Ĳ_Map is private_____ä",
				mapIsOrg: "Ĳ_Map is only shared in your organization_____________ä",
				layerIsPrivate: "Ĳ_Layer is private______ä",
				layerIsOrg: "Ĳ_Layer is only shared in your organization_____________ä",
				imageInaccessible: "Ĳ_This image is inaccessible_________ä",
				videoInaccessible: "Ĳ_This video is inaccessible_________ä",
				webpageInaccessible: "Ĳ_This web page is inaccessible__________ä",
				layerSecureService: "Ĳ_Layer is a secure service_________ä",
				mapSecureService: "Ĳ_Map is a secure service________ä",
				layerConsumesCredits: "Ĳ_Layer is premium content and consumes credits_______________ä",
				layerSubscriptionContent: "Ĳ_Layer is subscription content__________ä",
				mapConsumesCredits: "Ĳ_Map is premium content and consumes credits______________ä",
				mapSubscriptionContent: "Ĳ_Map is subscription content_________ä"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Ĳ_We're not able to check this type of layer______________ä",
				cantScanThisType: "Ĳ_Layer is not a type of layer we can check_____________ä",
				webpageNotScanned: "Ĳ_Webpages are not checked for issues____________ä"
			},
			scanningErrors: {
				deletedMap: "Ĳ_Deleted content______ä",
				inaccessibleMap: "Ĳ_Inaccessible map content________ä",
				notYoursNotAccessible: "Ĳ_Content not owned by you and not public_____________ä",
				serviceOkItemNot: "Ĳ_Working layers but inaccessible items____________ä",
				someContentNotPublic: "Ĳ_Content not shared publicly_________ä",
				someContentPrivate: "Ĳ_Private content______ä",
				othersSharedBelowLevel: "Ĳ_Content not owned by you and not public_____________ä",
				premiumContent: "Ĳ_Premium content______ä",
				subscriptionContent: "Ĳ_Subscription content_______ä",
				secureService: "Ĳ_Secure services______ä",
				inaccessibleImage: "Ĳ_Inaccessible images_______ä",
				inaccessibleVideo: "Ĳ_Inaccessible videos_______ä",
				inaccessibleWebpage: "Ĳ_Inaccessible webpages_______ä"
			},
			scanningErrorTips: {
				deletedMapTip: "Ĳ_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ä.",
				inaccessibleMapTip: "Ĳ_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ä.",
				notYoursNotAccessibleTip: "Ĳ_Tip: Open the web map and remove the layer or map from the story_____________________ä.",
				serviceOkItemNotTip: "Ĳ_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________ä.",
				ignore: "Ĳ_Ignore___ä",
				fix: "Ĳ_Fix__ä",
				clickToShareOrg: "Ĳ_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________ä.",
				clickToSharePublic: "Ĳ_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________ä.",
				shareOrg: "Ĳ_Share to your org______ä",
				sharePublicly: "Ĳ_Share publicly_____ä",
				othersSharedBelowLevelTip: "Ĳ_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________ä.",
				secureServiceTip: "Ĳ_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________ä.",
				blogArticle: "Ĳ_here__ä",
				premiumContentTip: "Ĳ_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________ä.",
				premiumContentPublicTip: "Ĳ_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________ä.",
				subscriptionContentTip: "Ĳ_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________ä.",
				agolCredits: "Ĳ_ArcGIS Online credits_______ä",
				credits: "Ĳ_credits___ä",
				makePublic: "Ĳ_Make public____ä",
				confirm: "Ĳ_Confirm___ä",
				inaccessibleImageTip: "Ĳ_Tip: Provide the missing image or remove the reference to it___________________ä.",
				inaccessibleVideoTip: "Ĳ_Tip: Provide the missing video or remove the reference to it___________________ä.",
				inaccessibleWebpageTip: "Ĳ_Tip: Provide the missing web page or remove the reference to it____________________ä."
			},
			removeLayer: {
				title: "Ĳ_Fix Layer Issue______ä",
				layersWithIssue: "Ĳ_Layers with this issue: {{NUM_WITH_ISSUE}}______________ä",
				issueExplanation: "Ĳ_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________ä.",
				issueSolution: "Ĳ_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________ä:",
				editMap: "Ĳ_Edit Your Map_____ä",
				clickBelowWhenDone: "Ĳ_When you have finished editing, click the button below__________________ä:",
				rescanAndClose: "Ĳ_Rescan And Close______ä"
			},
			info: {
				ownedBy: "Ĳ_This item is owned by {{USER_NAME}}____________ä",
				unknownUser: "Ĳ_someone else_____ä",
				untitledSection: "Ĳ_(Untitled section)______ä",
				introRecord: "Ĳ_Introduction_____ä"
			},
			layers: {
				layersHeader: "Ĳ_Layers___ä",
				noLayers: "Ĳ_(No Layers)____ä",
				basemapParens: "Ĳ_(basemap)____ä"
			},
			images: {
				thumbnails: "Ĳ_Thumbnails____ä",
				thumbnail: "Ĳ_Thumbnail____ä",
				thumbnailParens: "Ĳ_(thumbnail)____ä"
			},
			general: {
				noTitle: "Ĳ_(no title)____ä",
				loading: "Ĳ_Loading____ä..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "Ĳ_sections___ä",
				secondTitle: "Ĳ_style___ä",
				secondValueA: "Ĳ_side panel____ä",
				secondValueB: "Ĳ_floating panel_____ä",
				thirdTitle: "Ĳ_maps__ä"
			},
			mapTour: {
				firstTitle: "Ĳ_tour points____ä",
				secondTitle: "Ĳ_style___ä",
				secondValueA: "Ĳ_integrated____ä",
				secondValueB: "Ĳ_three-panel____ä",
				thirdTitle: "Ĳ_basemap___ä",
				thirdValueLoading: "Ĳ_Loading____ä...",
				thirdValueUnknown: "Ĳ_unknown___ä"
			},
			mapSeries: {
				firstTitleA: "Ĳ_bullets___ä",
				firstTitleB: "Ĳ_sections___ä",
				firstTitleC: "Ĳ_tabs__ä",
				secondTitle: "Ĳ_style___ä",
				secondValueA: "Ĳ_bulleted___ä",
				secondValueB: "Ĳ_side accordion_____ä",
				secondValueC: "Ĳ_tabbed___ä",
				thirdTitle: "Ĳ_maps__ä"
			},
			swipeSpyglass: {
				firstTitle: "Ĳ_points of interest______ä",
				secondTitle: "Ĳ_style___ä",
				secondValueA: "Ĳ_swipe___ä",
				secondValueB: "Ĳ_spyglass___ä",
				thirdTitle: "Ĳ_maps__ä"
			}
		},
		progress: {
			checkingStories: "Ĳ_Checking your stories for issues____________ä...",
			stop: "Ĳ_Stop__ä",
			exit: "Ĳ_Exit__ä",
			dismiss: "Ĳ_Dismiss___ä",
			done: "Ĳ_Done___ä.",
			noStoriesWithIssuesLower: "Ĳ_No issues found______ä!",
			storiesErrorFree: "Ĳ_Looks like your stories are error-free____________ä",
			scanAllError: "Ĳ_Unable to scan -- we couldn't retrieve one or more of your stories_____________________ä",
			scanProgress: "Ĳ_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________ä",
			scanStopped: "Ĳ_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________ä",
			storiesWithIssues: "Ĳ_Stories with issues: {{NUM_STORIES}}____________ä"
		}
    })
);