define({
	root: ({
		header: {
			start: "start",
			searchStories: "Uw verhalen zoeken...",
			filter: "Filter",
			sort: "Sorteren",
			sortColon: "Sorteren:",
			numResults: "Resultaten: {{NUM_RESULTS}}",
			sortBy: "Sorteren op",
			dateModified: "Datum wijziging",
			title: "Titel",
			type: "Type",
			views: "Weergaven",
			errors: "Fouten",
			filterBy: "Filteren op",
			filterItems: "Items filteren",
			apps: "Apps",
			sharing: "Delen",
			clearAll: "Alles wissen",
			clearSearch: "Wist de zoekopdracht",
			logOut: "Afmelden",
			mainQuote: "Verhalen vertellen is de meest krachtige manier om vandaag de dag ideeën in de wereld te zetten.",
			quoteSource: "Robert McKee",
			checkYourStories: "Verhalen bekijken",
			createStory: "Verhaal maken",
			totalStories: "Totaal aantal verhalen: {{NUM_STORIES}}",
			noIssues: "Allemaal goed",
			userStories: "Verhalen van {{USER_NAME}}",
			headerDisabledTooltip: "Even geduld zodat wij onze magie kunnen laten werken...",
			notOnTouch: "Niet beschikbaar voor apparaten met touchscreen",
		},
		deleteModal: {
			title: "Bevestig verwijderen",
			warningText: "Bent u zeker dat u dit verhaal wenst te verwijderen? U zult het niet kunnen herstellen.",
			deleteText: "Verwijderen",
			cancel: "Annuleren"
		},
		loading: {
			loadingText: "Uw verhalen laden..."
		},
		cantFindStories: {
			whereAreStories: "Ziet u uw verhaal niet?",
			notSeeExplanation: "My Stories geeft alleen een lijst met storymaps die in ArcGIS gehost zijn en gemaakt zijn met de applicaties {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} of {{SWIPE_SPYGLASS}}. Bekijk onze {{FAQ}} voor meer informatie.",
			faq: "Veelgestelde vragen",
			followingStoriesToUpdate: "De volgende verhalen, gemaakt met eerdere versies van onze applicaties, moeten geactualiseerd worden zodat ze in My Stories opgelijst worden:",
			gettingStories: "Verhalen zoeken die met eerdere versies van onze applicaties gemaakt zijn en geactualiseerd moeten worden...",
			title: "Titel",
			typeOfStoryMap: "Type",
			lastModified: "Laatst gewijzigd",
			allUpToDate: "Er zijn geen verhalen die met eerdere versies van onze applicaties gemaakt zijn en geactualiseerd moeten worden.",
			updateAll: "Alles actualiseren",
			errorScanningForStories: "Er is een fout opgetreden bij het zoeken van uw verhalen.",
			close: "Sluiten",
			updates: "Updates",
			updatingNumberOfNumber: "actualiseren {{CURRENT_NUMBER}} van {{TOTAL}}",
			updatingNumberOfNumberAlt: "actualiseren {{CURRENT_NUMBER}} / {{TOTAL}}",
			updateSucceeded: "actualiseren gelukt!",
			reloadingStories: "Uw verhalen opnieuw laden...",
			errorUpdatingStories: "Er is een fout opgetreden bij het actualiseren van uw verhalen.",
			partialUpdateMessage: "Verhalen succesvol geactualiseerd: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "Meld u aan bij Story Maps",
			signInTo: "Inschrijven met u bestaande ArcGIS Online-account op:",
			explanationOne: "Maak meeslepende storymaps om uw verhalen te vertellen.",
			explanationTwo: "Gebruik uw kaarten en gegevens van ArcGIS Online in uw storymaps.",
			explanationThree: "Beheer uw storymaps en controleer de status van hun content.",
			dontHaveAccount: "Hebt u geen ArcGIS Online account? Meld u dan aan voor een:",
			publicAccount: "Gratis niet-commercieel openbaar account",
			orgAccount: "Gratis proefabonnement ArcGIS",
			timeExpired: "Uw sessie is verlopen. Meld u opnieuw aan om uw werk voort te zetten.",
			apiDidntLoad: "Er laadt iets niet juist. Probeer de pagina te hernieuwen.",
			needAccount: "Account nodig?",
			letsGo: "Aan de slag!"
		},
		sharingLevel: {
			publicMessage: "Openbaar",
			privateMessage: "Privé",
			organization: "Organisatie",
			changedSharing: "Gewijzigd deelstatus.",
			unableToChange: "Kan deelstatus niet wijzigen.",
			partOfMap: "Dit item bevindt zich in een kaart. Om het deelstatus ervan te wijzigen, moet u het deelstatus van de kaart wijzigen.",
			storyPublicContentOrg: "Uw verhaal is openbaar, dus de inhoud ervan kan niet uitsluitend met uw organisatie gedeeld worden",
			storyPublicContentPrivate: "Uw verhaal is openbaar, dus de inhoud ervan kan niet privé zijn",
			mapOrg: "Uw kaart delen met uw organisatie zal uw verhaal defect maken",
			layerOrg: "Uw kaartlaag delen met uw organisatie zal uw verhaal defect maken",
			mapPrivate: "Uw kaart privé maken zal uw verhaal defect maken",
			layerPrivate: "Uw kaartlaag privé maken zal uw verhaal defect maken"
		},
		collectionList: {
			advocacy: "Belangenbehartiging en meningen",
			architecture: "Architectuur en design",
			conservation: "Bescherming en duurzaamheid",
			culture: "Cultuur",
			destinations: "Bestemmingen en toerisme",
			disasters: "Rampen en herstel",
			economy: "Economie en ontwikkeling",
			entertainment: "Entertainment",
			history: "Historie",
			infrastructure: "Infrastructuur",
			marketing: "Marketing",
			nature: "Natuur en milieu",
			news: "Nieuws en evenementen",
			oceans: "Oceanen",
			parks: "Parken en recreatie",
			people: "Mensen en de gemeenschap",
			planning: "Planning en analyse",
			publicArt: "Openbare kunst",
			science: "Wetenschap en technologie",
			sport: "Sport",
			travelogues: "Reisverhalen"
		},
		types: {
			custom: "Aangepast",
			notSpecified: "Type niet gespecificeerd"
		},
		storyMap: {
			shared: "Gedeeld",
			saveFailed: "Fout bij opslaan",
			numViews: "Aantal weergaven: {{NUM_VIEWS}}",
			editStory: "Verhaal bewerken",
			viewLive: "Verhaal bekijken",
			preview: "Voorbeeld",
			deleteButton: "Verwijderen",
			modified: "Aangepast {{DATE}}",
			summary: "Samenvatting",
			loading: "Bezig met laden...",
			collapse: "samenvouwen",
			close: "sluiten",
			hide: "verbergen",
			notAvailableWhenBroken: "Uw verhaal heeft onderstaande problemen",
			cantBeDeleted: "Bij dit verhaal is de verwijderbeveiliging geactiveerd. Zie de itempagina op ArcGIS om te deactiveren",
			shareDialog: {
				title: "Deel uw verhaal met de wereld!",
				notPublicWarning: "Uw verhaal is gedeeld met uw organisatie. Alleen leden van uw organisatie kunnen het bekijken.",
				embedStory: "Uw verhaal embedden",
				shortLink: "Snelkoppeling",
				hideHeaderBar: "Titelbalk verbergen",
				copied: "Gekopieerd",
				small: "klein",
				medium: "medium",
				large: "groot",
				custom: "aangepast",
				widthAbbreviation: "w",
				heightAbbreviation: "h",
				emptyDimension: "Voer een afmeting in.",
				seeExample: "Een voorbeeld van het embedden bekijken",
				removeHeader: "Applicatietitel verbergen"
			},
			maps: {
				unableRetrieveTitle: "Kan kaarten niet laden",
				unableRetrieveDescription: "We konden geen kaarten laden voor deze story map."
			},
			images: {
				unableRetrieveTitle: "Kan beelden niet laden",
				unableRetrieveDescription: "We konden geen beelden laden voor deze story map."
			},
			tags: {
				tags: "Labels",
				collectionTags: "Onderwerp",
				selectASubject: "Een onderwerp selecteren",
				save: "Opslaan",
				saved: "Opgeslagen",
				errorSaving: "Fout bij opslaan",
				tagTip: "Tip: Tags helpen mensen uw verhaal te vinden. Hoe relevanter de tags zijn, des te hoger de zichtbaarheid van uw werk."
			},
			submitToGallery: {
				gallerySubmission: "Story Maps-galerij",
				canSubmitIf: "U kunt uw verhaal toevoegen aan de galerij als het de volgende zaken bevat:",
				hasOwnImage: "Aangepaste thumbnail",
				chosenSubject: "Een onderwerp en enkele tags",
				chosenSubjectAlt: "Een {{SUBJECT}} en enkele tags",
				storyMapTopicSubject: "onderwerp",
				sharedPublicly: "Openbaar gedeeld",
				noBrokenContent: "Geen problemen",
				nominateToGallery: "Toevoegen aan Galerij",
				comingSoon: "Binnenkort beschikbaar!",
				submitted: "Verzonden",
				errorSubmitting: "Fout bij het verzenden",
				ourGallery: "De Story Maps-galerij",
				galleryTip: "{{THE_GALLERY}} is een geselecteerde reeks Story Maps die enkele van de beste voorbeelden weergeeft. Als uw verhaal geselecteerd wordt, wordt het binnen 10 dagen na verzending toegevoegd. Omwille van de hoeveelheid nominaties kunnen we niet beloven dat uw verhaal toegevoegd zal worden."
			},
			placeholders: {
				noSummary: "Geen samenvatting, klik om toe te voegen."
			},
			errors: {
				cantDeleteStory: "Kan verhaal niet verwijderen.",
				unableToFind: "Kan content niet vinden",
				unableToRetrieve: "We konden de content voor deze story map niet laden."
			},
			socialSharing: {
				availableWhenPublic: "Deze optie zal beschikbaar zijn als uw verhaal openbaar is"
			},
			dialog: {
				back: "Vorige",
				close: "Sluiten",
				cancel: "Annuleren"
			},
			imagePicker: {
				changeDefault: "De standaardafbeelding wijzigen",
				changeImage: "Miniatuur wijzigen",
				uploadImage: "Thumbnail uploaden",
				chooseImage: "Thumbnail kiezen",
				chooseAnImage: "Een afbeelding kiezen",
				notInIEVersion: "Deze functie is niet beschikbaar in Internet Explorer {{VERSION_NUMBER}}.",
				or: "Of",
				uploadAnImage: "Een afbeelding uploaden",
				supportedFileTypes: "Ondersteunt .png, .jpg, .gif",
				imageSizeMessage: "Uw afbeelding moet minimaal 286 px breed en 190 px hoog zijn.",
				minimumDimensions: "Minimum: 286 x 190px",
				imagesLoading: "Afbeeldingen laden...",
				noImages: "Dit verhaal bevat geen afbeeldingen",
				errorLoading: "Kan de afbeeldingen in dit verhaal niet laden",
				clickBelowTip: "Klik op onderstaande knop om een afbeelding te uploaden.",
				dragAndDrop: "Drag & drop",
				cropImage: "Afbeelding bijsnijden",
				saveImage: "Afbeelding opslaan",
				save: "Opslaan",
				savingImage: "Uw afbeelding opslaan...",
				saved: "Opgeslagen!",
				errorSaving: "Kon uw afbeelding niet opslaan.",
				skipAndCrop: "Overslaan en bijsnijden",
				wrongFormat: "Dit bestandstype worden niet ondersteund.",
				noCropWarning: "Deze afbeelding kan niet bijgesneden worden, maar u kunt ze wel opslaan als uw verhaalthumbnail met de oorspronkelijke afmetingen ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)."
			}
		},
		content: {
			media: {
				maps: "Maps",
				images: "Afbeeldingen",
				videos: "Video\'s",
				webpages: "Webpagina\'s",
				tags: "Labels",
				gallery: "Gallery"
			},
			headers: {
				status: "Status",
				source: "Bron",
				name: "Naam",
				shared: "Gedeeld"
			},
			component: {
				mapTour: "Puntnummer",
				bullet: "Opsommingstekens",
				tab: "Tab:",
				accordion: "Sectie",
				mapJournal: "Sectie"
			},
			titleType: {
				mapTour: "Bijschrift",
				mapJournal: "URL",
				mapSeries: "URL"
			},
			actions: {
				viewMap: "Kaart weergeven",
				editMap: "Kaart bewerken",
				fix: "Herstel",
				viewLayer: "Kaartlagen weergeven"
			},
			contentType: {
				mainStage: "actie van hoofdvenster",
				sidePanel: "description"
			},
			notification: {
				refreshExplanation: "Controleer uw verhaal nogmaals",
				checking: "Controleren...",
				foundSomeIssues: "We hebben enkele problemen gevonden",
				noIssuesFound: "Geen problemen gevonden",
				storyPublic: "Uw verhaal is nu openbaar",
				storyOrg: "Uw verhaal is nu gedeeld met uw organisatie",
				storyPrivate: "Uw verhaal is nu privé",
				mapPublic: "Uw kaart is nu openbaar",
				mapOrg: "Uw kaart is nu gedeeld met uw organisatie",
				mapPrivate: "Uw kaart is nu privé",
				layerPublic: "Uw kaartlaag is nu openbaar",
				layerOrg: "Uw kaartlaag is nu gedeeld met uw organisatie",
				layerPrivate: "Uw kaartlaag is nu privé",
				contentPublic: "Uw content is nu openbaar",
				contentOrg: "Uw content is nu gedeeld met uw organisatie",
				contentPrivate: "Uw content is nu privé",
				storyAndContentPublic: "Uw verhaal en de content ervan zijn nu openbaar",
				storyAndContentOrg: "Uw verhaal en de content ervan zijn nu gedeeld met uw organisatie",
				storyAndContentPrivate: "Uw verhaal en de content ervan zijn nu privé",
				shareBulkPrompt: "Wilt u de content van uw verhaal overeenkomstig delen?",
				layersPublic: "Bepaalde kaartlagen zijn ook openbaar gedeeld",
				layersOrg: "Bepaalde kaartlagen zijn ook gedeeld met uw organisatie",
				layersPrivate: "Bepaalde kaartlagen zijn ook privé gemaakt",
				mapsPublic: "Bepaalde kaarten zijn ook openbaar gedeeld",
				mapsOrg: "Bepaalde kaarten zijn ook gedeeld met uw organisatie",
				mapsPrivate: "Bepaalde kaarten zijn ook privé gemaakt",
				layersAndMapsPublic: "Bepaalde kaarten en kaartlagen zijn ook openbaar gedeeld",
				layersAndMapsOrg: "Bepaalde kaarten en kaartlagen zijn ook gedeeld met uw organisatie",
				layersAndMapsPrivate: "Bepaalde kaarten en kaartlagen zijn ook privé gemaakt",
				yes: "Ja",
				no: "Nee",
				premiumPublicSuccess: "Uw premium content is nu openbaar toegankelijk",
				subscriptionPublicSuccess: "Uw abonnementcontent is nu openbaar toegankelijk"
			},
			errors: {
				publicDisabled: "Openbaar delen is uitgeschakeld door een beheerder",
				orgDisabled: "Delen met uw organisatie is uitgeschakeld door een beheerder",
				noMapName: "Kon de kaartnaam niet laden",
				notPublic: "NIET OPENBAAR",
				inaccessible: "NIET TOEGANKELIJK",
				deleted: "VERWIJDERD",
				cantAccessVideo: "Kon de video niet openen",
				noStoriesFound: "We konden geen Story Maps vinden in uw content.",
				cantShowStories: "Kan uw storymaps niet tonen. Probeer het later nogmaals.",
				consolationSearch: "We konden geen verhalen vinden.",
				notCompatibleWithBrowser : "My Stories wordt niet ondersteund op eerdere versies van Internet Explorer dan versie {{VERSION_NUMBER}}.",
				pleaseUpdateBrowser: "Werk uw browser bij.",
				searchTip: "Probeer het wat te vereenvoudigen.",
				consolationNoStories: "Welkom bij My Stories!",
				noStoriesTip: "Om uw eerste story map te maken, raadpleeg de Apps-pagina.",
				letsGo: "Aan de slag",
				cantChangeSharingLevel: "Kan deelstatus niet wijzigen",
				cantChangeSharingLevels: "Kan deelstatuss niet wijzigen",
				errorUpdatingTitle: "Fout bij het bijwerken van de titel",
				errorUpdatingSummary: "Fout bij het bijwerken van de samenvatting",
				noEmptyTitle: "Titel mag niet leeg zijn",
				cantUpdatePremiumContent: "Kan de premium content niet actualiseren",
				cantUpdateSubscriptionContent: "Kan de abonnementcontent niet actualiseren",
				createFirstStory: "Mijn eerste verhaal maken"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Kaart werd verwijderd",
				layerHasBeenDeleted: "Kaartlaag werd verwijderd",
				mapIsInaccessible: "Kaart is niet toegankelijk",
				layerIsInaccessible: "Kaartlaag is niet toegankelijk",
				mapNotYoursNotAccessible: "Kaart is eigendom van iemand anders en is niet toegankelijk",
				layerServiceOkItemNot: "Kaartlaag werd toegevoegd als een item dat verwijderd of niet toegankelijk is",
				layerNotYoursNotAccessible: "Kaartlaag is eigendom van iemand anders en is niet toegankelijk",
				mapOthersSharedBelowLevel: "Kaart is niet uw eigendom en is niet openbaar",
				layerOthersSharedBelowLevel: "Kaartlaag is niet uw eigendom en is niet openbaar",
				noMapNoDetails: "Zonder de kaartgegevens kunnen we u niets vertellen over de kaartlagen",
				mapIsPrivate: "Kaart is privé",
				mapIsOrg: "Kaart is alleen gedeeld met uw organisatie",
				layerIsPrivate: "Kaartlaag is privé",
				layerIsOrg: "Kaartlaag is alleen gedeeld met uw organisatie",
				imageInaccessible: "Deze afbeelding is niet toegankelijk",
				videoInaccessible: "Deze video is niet toegankelijk",
				webpageInaccessible: "Deze webpagina is niet toegankelijk",
				layerSecureService: "Kaartlaag is een beveiligde service",
				mapSecureService: "Kaart is een beveiligde service",
				layerConsumesCredits: "Kaartlaag is premium content en kost credits",
				layerSubscriptionContent: "Kaartlaag is abonnementcontent",
				mapConsumesCredits: "Kaart is premium content en kost credits",
				mapSubscriptionContent: "Kaart is abonnementcontent"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "We kunnen dit type kaartlaag niet controleren",
				cantScanThisType: "Kaartlaag is geen kaartlaagtype dat we kunnen controleren",
				webpageNotScanned: "Webpagina\'s worden niet gecontroleerd op problemen",
				ignoredIssue: "U negeert een fout op deze laag. Laad de pagina opnieuw en controleer dit verhaal nogmaals om de fout te beoordelen",
				ignoredIssueBuilder: "U negeert een fout op deze laag. Laad de builder opnieuw om deze fout weer te controleren"
			},
			scanningErrors: {
				deletedMap: "Verwijderde content",
				inaccessibleMap: "Niet-toegankelijke kaartcontent",
				notYoursNotAccessible: "Content is niet uw eigendom en is niet openbaar",
				serviceOkItemNot: "Functionerende kaartlagen maar niet-toegankelijke items",
				someContentNotPublic: "Content niet openbaar gedeeld",
				someContentPrivate: "Persoonlijke content",
				othersSharedBelowLevel: "Content is niet uw eigendom en is niet openbaar",
				premiumContent: "Premium content",
				subscriptionContent: "Abonnementcontent",
				secureService: "Beveiligde services",
				inaccessibleImage: "Niet-toegankelijke afbeeldingen",
				inaccessibleVideo: "Niet-toegankelijke video\'s",
				inaccessibleWebpage: "Niet-toegankelijke webpagina\'s"
			},
			scanningErrorTips: {
				deletedMapTip: "Tip: Bewerk uw webmap en verwijder de defecte content, of verwijder uw webmap uit uw verhaal.",
				inaccessibleMapTip: "Tip: Bewerk uw webmap en verwijder de defecte content, of verwijder uw webmap uit uw verhaal.",
				notYoursNotAccessibleTip: "Tip: Bewerk uw webmap en verwijder de laag, of verwijder uw webmap uit uw verhaal.",
				serviceOkItemNotTip: "Kaartlagen werden toegevoegd als items die niet-toegankelijk of verwijderd zijn. De kaartlagen functioneren niet, maar dit kan uw kaart aantasten (pop-ups, symbolen).",
				ignore: "Ignore",
				fix: "Herstel",
				clickToShareOrg: "Klik op de knop om al deze content met uw organisatie te delen, of wijzig elk item handmatig d.m.v. de deelknoppen.",
				clickToSharePublic: "Klik op de knop om al deze content openbaar te delen, of wijzig elk item handmatig d.m.v. de deelknoppen.",
				shareOrg: "Uw organisatie delen",
				sharePublicly: "Openbaar delen",
				othersSharedBelowLevelTip: "Tip: Bepaalde content van uw verhaal is eigendom van {{USER_NAME}}, en anderen die uw verhaal bekijken kunnen deze mogelijk niet zien.",
				secureServiceTip: "Tip: Verwijder de beveiligde service uit uw verhaal of volg de procedure die {{HERE}} beschreven is.",
				blogArticle: "hier",
				premiumContentTip: "Uw verhaal bevat premium content die {{CREDITS}} zal verbruiken als deze openbaar gemaakt wordt. Maak uw verhaal openbaar en ga verder of verwijder de kaartlagen uit uw verhaal.",
				premiumContentPublicTip: "Uw verhaal bevat premium content die {{CREDITS}} zal verbruiken als deze openbaar beschikbaar is. Bevestig om deze kaartlagen openbaar te maken of verwijder de kaartlagen uit uw verhaal.",
				subscriptionContentTip: "Uw verhaal bevat abonnementcontent die niet standaard openbaar beschikbaar is. Bevestig dat u deze kaartlagen beschikbaar wenst te majen (er worden geen credits verbruikt), of verwijder de kaartlagen uit uw verhaal.",
				credits: "credits",
				makePublic: "Openbaar maken",
				confirm: "Bevestigen",
				inaccessibleImageTip: "Tip: Voeg de ontbrekende afbeelding toe of verwijder de verwijzing ernaar.",
				inaccessibleVideoTip: "Tip: Voeg de ontbrekende video toe of verwijder de verwijzing ernaar.",
				inaccessibleWebpageTip: "Tip: Voeg de ontbrekende webpagina toe of verwijder de verwijzing ernaar."
			},
			removeLayer: {
				title: "Kaartlaagprobleem corrigeren",
				layersWithIssue: "Kaartlagen met dit probleem: {{NUM_WITH_ISSUE}}",
				issueExplanation: "De kaartlaag {{LAYER_NAME}} werd toegevoegd als een item dat niet-toegankelijk of verwijderd is. De laag functioneert, maar dit kan uw kaart aantasten (pop-ups, symbolen). We kunnen niet zeggen of het item belangrijk is voor uw verhaal.",
				issueSolution: "Om het probleem te corrigeren, kunt u uw kaart bewerken, de kaartlaag verwijderen en de kaartlaag terug toevoegen d.m.v. volgende URL:",
				editMap: "Uw kaart bewerken",
				clickBelowWhenDone: "Als u uw kaart bewerkt heeft, klik op onderstaande knop:",
				rescanAndClose: "Herscannen en sluiten"
			},
			info: {
				ownedBy: "Dit item is eigendom van {{USER_NAME}}",
				unknownUser: "iemand anders",
				untitledSection: "(sectie zonder titel)",
				introRecord: "Inleiding"
			},
			layers: {
				layersHeader: "Kaartlagen",
				noLayers: "(Geen lagen)",
				basemapParens: "(basiskaart)"
			},
			images: {
				thumbnails: "Thumbnails",
				thumbnail: "Thumbnail",
				thumbnailParens: "(thumbnail)"
			},
			general: {
				noTitle: "(geen titel)",
				loading: "Bezig met laden..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "secties",
				secondTitle: "style",
				secondValueA: "zijvenster",
				secondValueB: "zwevend venster",
				thirdTitle: "kaarten"
			},
			mapTour: {
				firstTitle: "punten van de tour",
				secondTitle: "style",
				secondValueA: "geïntegreerd",
				secondValueB: "driedelig",
				thirdTitle: "basiskaart",
				thirdValueLoading: "Bezig met laden...",
				thirdValueUnknown: "onbekend"
			},
			mapSeries: {
				firstTitleA: "opsommingstekens",
				firstTitleB: "secties",
				firstTitleC: "tabbladen",
				secondTitle: "style",
				secondValueA: "met opsommingstekens",
				secondValueB: "zij-accordeon",
				secondValueC: "met tabbladen",
				thirdTitle: "kaarten"
			},
			swipeSpyglass: {
				firstTitle: "nuttige plaatsen",
				secondTitle: "style",
				secondValueA: "swipe",
				secondValueB: "verrekijker",
				thirdTitle: "kaarten"
			},
			crowdsource: {
				firstTitle: "bijdragen",
				secondTitle: "style",
				secondValueA: "zijvenster",
				secondValueB: "gestapeld",
				thirdTitle: "basiskaart",
				thirdValueLoading: "Bezig met laden...",
				thirdValueUnknown: "onbekend"
			}
		},
		progress: {
			checkingStories: "Uw verhalen controleren op problemen...",
			stop: "Stoppen",
			exit: "Afsluiten",
			dismiss: "Negeren",
			done: "Gereed.",
			noStoriesWithIssuesLower: "Geen problemen gevonden!",
			storiesErrorFree: "Blijkbaar bevatten uw verhalen geen fouten",
			scanAllError: "Kan niet scannen -- we konden één of meerdere van uw verhalen niet laden",
			scanProgress: "{{NUM_SCANNED}} van {{NUM_TOTAL}}",
			scanStopped: "Verhalen gescand: {{NUM_SCANNED}}, Verhalen met problemen: {{ISSUE_STORIES}}",
			storiesWithIssues: "Verhalen met problemen: {{NUM_STORIES}}"
		},
		newStories: {
			newStoriesFound: "Het lijkt erop dat u een nieuw verhaal hebt gemaakt.",
			includeStories: "Verhalen vernieuwen",
			notWhileScanning: "Dit is beschikbaar als de controle is voltooid"
		}
    }),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1,
	"zh-tw": 1
});
