define(
	 ({
		header: {
			start: "Č_start___ž",
			searchStories: "Č_Search your stories________ž...",
			filter: "Č_Filter___ž",
			sort: "Č_Sort__ž",
			sortColon: "Č_Sort___ž:",
			numResults: "Č_Results: {{NUM_RESULTS}}________ž",
			sortBy: "Č_Sort by___ž",
			dateModified: "Č_Date modified_____ž",
			title: "Č_Title___ž",
			type: "Č_Type__ž",
			views: "Č_Views___ž",
			errors: "Č_Errors___ž",
			filterBy: "Č_Filter by____ž",
			filterItems: "Č_Filter Items_____ž",
			apps: "Č_Apps__ž",
			sharing: "Č_Sharing___ž",
			clearAll: "Č_Clear all____ž",
			clearSearch: "Č_Clears the search______ž",
			logOut: "Č_Log Out___ž",
			mainQuote: "Č_Storytelling is the most powerful way to put ideas into the world today_______________________ž.",
			quoteSource: "Č_Robert McKee_____ž",
			checkYourStories: "Č_Check Stories_____ž",
			createStory: "Č_Create Story_____ž",
			totalStories: "Č_Total stories: {{NUM_STORIES}}__________ž",
			noIssues: "Č_All good___ž",
			userStories: "Č_Stories of {{USER_NAME}}________ž",
			headerDisabledTooltip: "Č_Please wait while we work some magic_____________ž...",
			notOnTouch: "Č_Not available on touch devices__________ž",
		},
		deleteModal: {
			title: "Č_Confirm Delete_____ž",
			warningText: "Č_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________ž.",
			deleteText: "Č_Delete___ž",
			cancel: "Č_Cancel___ž"
		},
		loading: {
			loadingText: "Č_Loading your stories________ž..."
		},
		cantFindStories: {
			whereAreStories: "Č_Not seeing your story________ž?",
			notSeeExplanation: "Č_My Stories will only list story maps hosted in ArcGIS and created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} or {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information____________________________________________________________ž.",
			faq: "Č_FAQ__ž",
			followingStoriesToUpdate: "Č_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________ž:",
			gettingStories: "Č_Searching for stories created with early versions of our applications that need to be updated______________________________ž...",
			title: "Č_Title___ž",
			typeOfStoryMap: "Č_Type__ž",
			lastModified: "Č_Last modified_____ž",
			allUpToDate: "Č_No stories created with early versions of our applications need to be updated________________________ž.",
			updateAll: "Č_Update All____ž",
			errorScanningForStories: "Č_There was an error searching your stories______________ž.",
			close: "Č_Close___ž",
			updates: "Č_Updates___ž",
			updatingNumberOfNumber: "Č_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________ž",
			updatingNumberOfNumberAlt: "Č_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________ž",
			updateSucceeded: "Č_Update succeeded______ž!",
			reloadingStories: "Č_Reloading your stories_________ž...",
			errorUpdatingStories: "Č_There was an error updating your stories_____________ž.",
			partialUpdateMessage: "Č_Stories updated successfully: {{NUM_UPDATED}}_______________ž"
		},
		signIn: {
			signInTitle: "Č_Sign in to Story Maps_______ž",
			signInTo: "Č_Sign in with your existing ArcGIS Online account to_________________ž:",
			explanationOne: "Č_Create compelling story maps to tell your stories________________ž.",
			explanationTwo: "Č_Use your maps and data from ArcGIS Online in your story maps___________________ž.",
			explanationThree: "Č_Manage your story maps and check the status of their content___________________ž.",
			dontHaveAccount: "Č_Don't have an ArcGIS Online account? Sign up for a________________ž:",
			publicAccount: "Č_Free non-commercial public account___________ž",
			orgAccount: "Č_Free trial ArcGIS subscription__________ž",
			timeExpired: "Č_Your sign-in expired. Sign in again to pick up where you left off_____________________ž.",
			apiDidntLoad: "Č_Something isn't loading correctly. Try refreshing the page___________________ž.",
			needAccount: "Č_Need an account______ž?",
			letsGo: "Č_Let's go____ž!"
		},
		sharingLevel: {
			publicMessage: "Č_Public___ž",
			privateMessage: "Č_Private___ž",
			organization: "Č_Organization_____ž",
			changedSharing: "Č_Changed sharing level________ž.",
			unableToChange: "Č_Unable to change sharing_________ž.",
			partOfMap: "Č_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________ž.",
			storyPublicContentOrg: "Č_Your story is public, so its content can't be shared only with your organization_________________________ž",
			storyPublicContentPrivate: "Č_Your story is public, so its content can't be private_________________ž",
			mapOrg: "Č_Sharing your map to your organization would break your story___________________ž",
			layerOrg: "Č_Sharing your layer to your organization would break your story____________________ž",
			mapPrivate: "Č_Making your map private would break your story_______________ž",
			layerPrivate: "Č_Making your layer private would break your story_______________ž"
		},
		collectionList: {
			advocacy: "Č_Advocacy and Outreach_______ž",
			architecture: "Č_Architecture and Design________ž",
			conservation: "Č_Conservation and Sustainability__________ž",
			culture: "Č_Culture___ž",
			destinations: "Č_Destinations and Tourism________ž",
			disasters: "Č_Disasters and Recovery________ž",
			economy: "Č_Economy and Development________ž",
			entertainment: "Č_Entertainment_____ž",
			history: "Č_History___ž",
			infrastructure: "Č_Infrastructure_____ž",
			marketing: "Č_Marketing____ž",
			nature: "Č_Nature and Environment________ž",
			news: "Č_News and Events______ž",
			oceans: "Č_Oceans___ž",
			parks: "Č_Parks and Recreation_______ž",
			people: "Č_People and Society______ž",
			planning: "Č_Planning and Analysis_______ž",
			publicArt: "Č_Public Art____ž",
			science: "Č_Science and Technology________ž",
			sport: "Č_Sport___ž",
			travelogues: "Č_Travelogues____ž"
		},
		types: {
			custom: "Č_Custom___ž",
			notSpecified: "Č_Type not specified______ž"
		},
		storyMap: {
			shared: "Č_Shared___ž",
			saveFailed: "Č_Error saving_____ž",
			numViews: "Č_Views: {{NUM_VIEWS}}_______ž",
			editStory: "Č_Edit Story____ž",
			viewLive: "Č_View Story____ž",
			preview: "Č_Preview___ž",
			deleteButton: "Č_Delete___ž",
			modified: "Č_Modified {{DATE}}______ž",
			summary: "Č_Summary___ž",
			loading: "Č_Loading____ž...",
			collapse: "Č_collapse___ž",
			close: "Č_close___ž",
			hide: "Č_hide__ž",
			notAvailableWhenBroken: "Č_Your story has issues below_________ž",
			cantBeDeleted: "Č_This story has delete protection enabled. See its item page on ArcGIS to disable_________________________ž.",
			shareDialog: {
				title: "Č_Share your story with the world___________ž!",
				notPublicWarning: "Č_Your story is shared with your organization. Only members of your organization will be able to view it________________________________ž.",
				embedStory: "Č_Embed your story______ž",
				shortLink: "Č_Shortlink____ž",
				hideHeaderBar: "Č_Hide header bar______ž",
				copied: "Č_Copied___ž",
				small: "Č_small___ž",
				medium: "Č_medium___ž",
				large: "Č_large___ž",
				custom: "Č_custom___ž",
				widthAbbreviation: "Č_w_ž",
				heightAbbreviation: "Č_h_ž",
				emptyDimension: "Č_Enter a dimension______ž.",
				seeExample: "Č_Preview your embed______ž",
				removeHeader: "Č_Hide application header________ž"
			},
			maps: {
				unableRetrieveTitle: "Č_Unable to retrieve maps________ž",
				unableRetrieveDescription: "Č_We weren't able to retrieve maps for this story map_________________ž."
			},
			images: {
				unableRetrieveTitle: "Č_Unable to retrieve images_________ž",
				unableRetrieveDescription: "Č_We weren't able to retrieve images for this story map_________________ž."
			},
			tags: {
				tags: "Č_Tags__ž",
				collectionTags: "Č_Subject___ž",
				selectASubject: "Č_Select a subject______ž",
				save: "Č_Save__ž",
				saved: "Č_Saved___ž",
				errorSaving: "Č_Error saving_____ž",
				tagTip: "Č_Tip: Tags help people find your story. The more relevant the tags are, the higher the visibility your work will receive_____________________________________ž."
			},
			submitToGallery: {
				gallerySubmission: "Č_Story Maps Gallery______ž",
				canSubmitIf: "Č_You can nominate your story to the gallery if it contains the following_______________________ž:",
				hasOwnImage: "Č_Custom thumbnail______ž",
				chosenSubject: "Č_A subject and some tags________ž",
				chosenSubjectAlt: "Č_A {{SUBJECT}} and some tags_________ž",
				storyMapTopicSubject: "Č_subject___ž",
				sharedPublicly: "Č_Shared publicly______ž",
				noBrokenContent: "Č_No issues____ž",
				nominateToGallery: "Č_Nominate to Gallery_______ž",
				comingSoon: "Č_Coming soon_____ž!",
				submitted: "Č_Submitted____ž",
				errorSubmitting: "Č_Error submitting______ž",
				ourGallery: "Č_The Story Maps gallery________ž",
				galleryTip: "Č_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________ž."
			},
			placeholders: {
				noSummary: "Č_No summary, click to add one__________ž."
			},
			errors: {
				cantDeleteStory: "Č_Unable to delete story________ž.",
				unableToFind: "Č_Unable to find content________ž",
				unableToRetrieve: "Č_We weren't able to retrieve the content for this story map___________________ž."
			},
			socialSharing: {
				availableWhenPublic: "Č_This option will be available when your story is public__________________ž"
			},
			dialog: {
				back: "Č_Back__ž",
				close: "Č_Close___ž",
				cancel: "Č_Cancel___ž"
			},
			imagePicker: {
				changeDefault: "Č_Change the default image________ž",
				changeImage: "Č_Change thumbnail______ž",
				uploadImage: "Č_Upload thumbnail______ž",
				chooseImage: "Č_Choose thumbnail______ž",
				chooseAnImage: "Č_Choose an Image______ž",
				notInIEVersion: "Č_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________ž.",
				or: "Č_Or__ž",
				uploadAnImage: "Č_Upload an Image______ž",
				supportedFileTypes: "Č_Supports .png, .jpg, .gif_________ž",
				imageSizeMessage: "Č_Your image needs to be at least 286 px wide by 190 px tall___________________ž.",
				minimumDimensions: "Č_Minimum: 286 x 190px_______ž",
				imagesLoading: "Č_Loading images______ž...",
				noImages: "Č_This story has no images________ž",
				errorLoading: "Č_Unable to retrieve the images in this story______________ž",
				clickBelowTip: "Č_Click the button below to upload an image______________ž.",
				dragAndDrop: "Č_Drag and Drop_____ž",
				cropImage: "Č_Crop Image____ž",
				saveImage: "Č_Save Image____ž",
				save: "Č_Save__ž",
				savingImage: "Č_Saving your image_______ž...",
				saved: "Č_Saved___ž!",
				errorSaving: "Č_Unable to save your image_________ž.",
				skipAndCrop: "Č_Skip and Crop for me_______ž",
				wrongFormat: "Č_This file type is not supported___________ž.",
				noCropWarning: "Č_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________ž."
			}
		},
		content: {
			media: {
				maps: "Č_Maps__ž",
				images: "Č_Images___ž",
				videos: "Č_Videos___ž",
				webpages: "Č_Webpages___ž",
				tags: "Č_Tags__ž",
				gallery: "Č_Gallery___ž"
			},
			headers: {
				status: "Č_Status___ž",
				source: "Č_Source___ž",
				name: "Č_Name__ž",
				shared: "Č_Shared___ž"
			},
			component: {
				mapTour: "Č_Point Number_____ž",
				bullet: "Č_Bullet___ž",
				tab: "Č_Tab__ž",
				accordion: "Č_Section___ž",
				mapJournal: "Č_Section___ž"
			},
			titleType: {
				mapTour: "Č_Caption___ž",
				mapJournal: "Č_URL__ž",
				mapSeries: "Č_URL__ž"
			},
			actions: {
				viewMap: "Č_View Map___ž",
				editMap: "Č_Edit Map___ž",
				fix: "Č_Fix__ž",
				viewLayer: "Č_View Layer____ž"
			},
			contentType: {
				mainStage: "Č_main stage action______ž",
				sidePanel: "Č_description____ž"
			},
			notification: {
				refreshExplanation: "Č_Check your story again________ž",
				checking: "Č_Checking____ž...",
				foundSomeIssues: "Č_We found some issues_______ž",
				noIssuesFound: "Č_No issues found______ž",
				storyPublic: "Č_Your story is now public________ž",
				storyOrg: "Č_Your story is now shared to your organization_______________ž",
				storyPrivate: "Č_Your story is now private_________ž",
				mapPublic: "Č_Your map is now public________ž",
				mapOrg: "Č_Your map is now shared to your organization______________ž",
				mapPrivate: "Č_Your map is now private________ž",
				layerPublic: "Č_Your layer is now public________ž",
				layerOrg: "Č_Your layer is now shared to your organization_______________ž",
				layerPrivate: "Č_Your layer is now private_________ž",
				contentPublic: "Č_Your content is now public_________ž",
				contentOrg: "Č_Your content is now shared to your organization_______________ž",
				contentPrivate: "Č_Your content is now private_________ž",
				storyAndContentPublic: "Č_Your story and its content are now public_____________ž",
				storyAndContentOrg: "Č_Your story and its content are now shared to your organization____________________ž",
				storyAndContentPrivate: "Č_Your story and its content are now private______________ž",
				shareBulkPrompt: "Č_Do you want to share your storyâ€™s content accordingly__________________ž?",
				layersPublic: "Č_Some layers have also been shared publicly______________ž",
				layersOrg: "Č_Some layers have also been shared with your organization__________________ž",
				layersPrivate: "Č_Some layers have also been made private_____________ž",
				mapsPublic: "Č_Some maps have also been shared publicly_____________ž",
				mapsOrg: "Č_Some maps have also been shared with your organization_________________ž",
				mapsPrivate: "Č_Some maps have also been made private____________ž",
				layersAndMapsPublic: "Č_Some maps and layers have also been shared publicly________________ž",
				layersAndMapsOrg: "Č_Some maps and layers have also been shared with your organization_____________________ž",
				layersAndMapsPrivate: "Č_Some maps and layers have also been made private_______________ž",
				yes: "Č_Yes__ž",
				no: "Č_No__ž",
				premiumPublicSuccess: "Č_Your premium content is now publicly accessible_______________ž",
				subscriptionPublicSuccess: "Č_Your subscription content is now publicly accessible_________________ž"
			},
			errors: {
				publicDisabled: "Č_Sharing publicly has been disabled by an Administrator_________________ž",
				orgDisabled: "Č_Sharing to your organization has been disabled by an Administrator_____________________ž",
				noMapName: "Č_Could Not Retrieve Map Name_________ž",
				notPublic: "Č_NOT PUBLIC____ž",
				inaccessible: "Č_INACCESSIBLE_____ž",
				deleted: "Č_DELETED___ž",
				cantAccessVideo: "Č_Could Not Access Video________ž",
				noStoriesFound: "Č_We could not find any Story Maps in your content________________ž.",
				cantShowStories: "Č_Unable to show your story maps. Please try again later__________________ž.",
				consolationSearch: "Č_We couldn't find any stories__________ž.",
				notCompatibleWithBrowser : "Č_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________ž.",
				pleaseUpdateBrowser: "Č_Please update your browser_________ž.",
				searchTip: "Č_Try and simplify it a bit_________ž.",
				consolationNoStories: "Č_Welcome to My Stories________ž!",
				noStoriesTip: "Č_To make your first story map, check out the Apps page_________________ž.",
				letsGo: "Č_Let's Go___ž",
				cantChangeSharingLevel: "Č_Unable to change sharing level__________ž",
				cantChangeSharingLevels: "Č_Unable to change sharing levels__________ž",
				errorUpdatingTitle: "Č_Error updating title_______ž",
				errorUpdatingSummary: "Č_Error updating summary________ž",
				noEmptyTitle: "Č_Title cannot be empty_______ž",
				cantUpdatePremiumContent: "Č_Unable to update premium content___________ž",
				cantUpdateSubscriptionContent: "Č_Unable to update subscription content____________ž",
				createFirstStory: "Č_Create My First Story_______ž"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Č_Map has been deleted_______ž",
				layerHasBeenDeleted: "Č_Layer has been deleted________ž",
				mapIsInaccessible: "Č_Map is inaccessible_______ž",
				layerIsInaccessible: "Č_Layer is inaccessible_______ž",
				mapNotYoursNotAccessible: "Č_Map is owned by someone else and isn't accessible________________ž",
				layerServiceOkItemNot: "Č_Layer was added as an item that is deleted or inaccessible__________________ž",
				layerNotYoursNotAccessible: "Č_Layer is owned by someone else and isn't accessible________________ž",
				mapOthersSharedBelowLevel: "Č_Map is not owned by you and is not public_____________ž",
				layerOthersSharedBelowLevel: "Č_Layer is not owned by you and is not public______________ž",
				noMapNoDetails: "Č_Without the map details, we can't tell you anything about the layers_____________________ž",
				mapIsPrivate: "Č_Map is private_____ž",
				mapIsOrg: "Č_Map is only shared in your organization_____________ž",
				layerIsPrivate: "Č_Layer is private______ž",
				layerIsOrg: "Č_Layer is only shared in your organization_____________ž",
				imageInaccessible: "Č_This image is inaccessible_________ž",
				videoInaccessible: "Č_This video is inaccessible_________ž",
				webpageInaccessible: "Č_This web page is inaccessible__________ž",
				layerSecureService: "Č_Layer is a secure service_________ž",
				mapSecureService: "Č_Map is a secure service________ž",
				layerConsumesCredits: "Č_Layer is premium content and consumes credits_______________ž",
				layerSubscriptionContent: "Č_Layer is subscription content__________ž",
				mapConsumesCredits: "Č_Map is premium content and consumes credits______________ž",
				mapSubscriptionContent: "Č_Map is subscription content_________ž"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Č_We're not able to check this type of layer______________ž",
				cantScanThisType: "Č_Layer is not a type of layer we can check_____________ž",
				webpageNotScanned: "Č_Webpages are not checked for issues____________ž",
				ignoredIssue: "Č_You have ignored an error on this layer. Reload the page and check this story again to review the error________________________________ž",
				ignoredIssueBuilder: "Č_You have ignored an error on this layer. Reload the builder to check this error again___________________________ž"
			},
			scanningErrors: {
				deletedMap: "Č_Deleted content______ž",
				inaccessibleMap: "Č_Inaccessible map content________ž",
				notYoursNotAccessible: "Č_Content not owned by you and not public_____________ž",
				serviceOkItemNot: "Č_Working layers but inaccessible items____________ž",
				someContentNotPublic: "Č_Content not shared publicly_________ž",
				someContentPrivate: "Č_Private content______ž",
				othersSharedBelowLevel: "Č_Content not owned by you and not public_____________ž",
				premiumContent: "Č_Premium content______ž",
				subscriptionContent: "Č_Subscription content_______ž",
				secureService: "Č_Secure services______ž",
				inaccessibleImage: "Č_Inaccessible images_______ž",
				inaccessibleVideo: "Č_Inaccessible videos_______ž",
				inaccessibleWebpage: "Č_Inaccessible webpages_______ž"
			},
			scanningErrorTips: {
				deletedMapTip: "Č_Tip: Edit your web map and remove the broken content, or remove the web map from your story_____________________________ž.",
				inaccessibleMapTip: "Č_Tip: Edit your web map and remove the broken content, or remove the web map from your story_____________________________ž.",
				notYoursNotAccessibleTip: "Č_Tip: Edit your web map and remove the layer, or remove the web map from your story__________________________ž.",
				serviceOkItemNotTip: "Č_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________ž.",
				ignore: "Č_Ignore___ž",
				fix: "Č_Fix__ž",
				clickToShareOrg: "Č_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________ž.",
				clickToSharePublic: "Č_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________ž.",
				shareOrg: "Č_Share to your org______ž",
				sharePublicly: "Č_Share publicly_____ž",
				othersSharedBelowLevelTip: "Č_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________ž.",
				secureServiceTip: "Č_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________ž.",
				blogArticle: "Č_here__ž",
				premiumContentTip: "Č_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________ž.",
				premiumContentPublicTip: "Č_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________ž.",
				subscriptionContentTip: "Č_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________ž.",
				credits: "Č_credits___ž",
				makePublic: "Č_Make public____ž",
				confirm: "Č_Confirm___ž",
				inaccessibleImageTip: "Č_Tip: Provide the missing image or remove the reference to it___________________ž.",
				inaccessibleVideoTip: "Č_Tip: Provide the missing video or remove the reference to it___________________ž.",
				inaccessibleWebpageTip: "Č_Tip: Provide the missing web page or remove the reference to it____________________ž."
			},
			removeLayer: {
				title: "Č_Fix Layer Issue______ž",
				layersWithIssue: "Č_Layers with this issue: {{NUM_WITH_ISSUE}}______________ž",
				issueExplanation: "Č_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________ž.",
				issueSolution: "Č_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________ž:",
				editMap: "Č_Edit Your Map_____ž",
				clickBelowWhenDone: "Č_When you have finished editing, click the button below__________________ž:",
				rescanAndClose: "Č_Rescan And Close______ž"
			},
			info: {
				ownedBy: "Č_This item is owned by {{USER_NAME}}____________ž",
				unknownUser: "Č_someone else_____ž",
				untitledSection: "Č_(Untitled section)______ž",
				introRecord: "Č_Introduction_____ž"
			},
			layers: {
				layersHeader: "Č_Layers___ž",
				noLayers: "Č_(No Layers)____ž",
				basemapParens: "Č_(basemap)____ž"
			},
			images: {
				thumbnails: "Č_Thumbnails____ž",
				thumbnail: "Č_Thumbnail____ž",
				thumbnailParens: "Č_(thumbnail)____ž"
			},
			general: {
				noTitle: "Č_(no title)____ž",
				loading: "Č_Loading____ž..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "Č_sections___ž",
				secondTitle: "Č_style___ž",
				secondValueA: "Č_side panel____ž",
				secondValueB: "Č_floating panel_____ž",
				thirdTitle: "Č_maps__ž"
			},
			mapTour: {
				firstTitle: "Č_tour points____ž",
				secondTitle: "Č_style___ž",
				secondValueA: "Č_integrated____ž",
				secondValueB: "Č_three-panel____ž",
				thirdTitle: "Č_basemap___ž",
				thirdValueLoading: "Č_Loading____ž...",
				thirdValueUnknown: "Č_unknown___ž"
			},
			mapSeries: {
				firstTitleA: "Č_bullets___ž",
				firstTitleB: "Č_sections___ž",
				firstTitleC: "Č_tabs__ž",
				secondTitle: "Č_style___ž",
				secondValueA: "Č_bulleted___ž",
				secondValueB: "Č_side accordion_____ž",
				secondValueC: "Č_tabbed___ž",
				thirdTitle: "Č_maps__ž"
			},
			swipeSpyglass: {
				firstTitle: "Č_points of interest______ž",
				secondTitle: "Č_style___ž",
				secondValueA: "Č_swipe___ž",
				secondValueB: "Č_spyglass___ž",
				thirdTitle: "Č_maps__ž"
			},
			crowdsource: {
				firstTitle: "Č_contributions_____ž",
				secondTitle: "Č_style___ž",
				secondValueA: "Č_side panel____ž",
				secondValueB: "Č_stacked___ž",
				thirdTitle: "Č_basemap___ž",
				thirdValueLoading: "Č_Loading____ž...",
				thirdValueUnknown: "Č_unknown___ž"
			}
		},
		progress: {
			checkingStories: "Č_Checking your stories for issues____________ž...",
			stop: "Č_Stop__ž",
			exit: "Č_Exit__ž",
			dismiss: "Č_Dismiss___ž",
			done: "Č_Done___ž.",
			noStoriesWithIssuesLower: "Č_No issues found______ž!",
			storiesErrorFree: "Č_Looks like your stories are error-free____________ž",
			scanAllError: "Č_Unable to scan -- we couldn't retrieve one or more of your stories_____________________ž",
			scanProgress: "Č_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________ž",
			scanStopped: "Č_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________ž",
			storiesWithIssues: "Č_Stories with issues: {{NUM_STORIES}}____________ž"
		},
		newStories: {
			newStoriesFound: "Č_Looks like you have created a new story_____________ž.",
			includeStories: "Č_Refresh Stories______ž",
			notWhileScanning: "Č_This will be available when the check is complete________________ž"
		}
    })
);
