define(
({
		viewer: {
			loading: {
				step1: "ЗАГРУЗКА ПРИЛОЖЕНИЯ",
				step2: "ЗАГРУЗКА ДАННЫХ",
				step3: "ИНИЦИАЛИЗАЦИЯ",
				loadBuilder: "ПЕРЕКЛЮЧИТЬСЯ В РЕЖИМ КОНСТРУКТОРА",
				redirectSignIn: "Ж_REDIRECTING TO SIGN-IN PAGE_Я",
				redirectSignIn2: "Ж_(you will be redirected here after sign-in)_Я",
				fail: "Загрузка Тура по карте не удалась",
				failButton: "Повторить"
			},
			errors: {
				boxTitle: "Произошла ошибка",
				portalSelf: "Критическая ошибка: не удалось получить конфигурацию портала",
				invalidConfig: "Критическая ошибка: недопустимая конфигурация",
				invalidConfigOwner: "Критическая ошибка: недопустимая конфигурация (требуется авторизованный владелец)",
				invalidConfigNoWebmap: "Критическая ошибка: недопустимая конфигурация (идентификатор веб-карты или приложения не указаны в index.html)",
				createMap: "Не удалось создать карту",
				invalidApp: "Критическая ошибка: не удается загрузить приложение",
				noLayer: "Веб-карта не содержит слой данных для обзора карты.",
				noLayerMobile: "Добро пожаловать в веб-приложение Тур по карте. Приложение не настроено. Конструктор Тура по карте не поддерживается на мобильных устройствах.",
				noLayerView: "Добро пожаловать в веб-приложение Тур по карте.<br />Приложение еще не настроено.",
				appSave: "Ошибка при сохранении веб-приложения",
				mapSave: "Ошибка при сохранении веб-карты",
				featureServiceLoad: "Ошибка загрузки сервиса объектов",
				notAuthorized: "Вы не авторизованы для доступа к данному приложению",
				oldBrowserTitle: "Браузер поддерживается не полностью",
				noBuilderIE8: "Конструктор Тура по поддерживается в браузере Internet Explorer, начиная с версии 9 .",
				ie10Win7Explain: "Интерактивный конструктор Тура по карте не поддерживается в Internet Explorer 10 на Windows 7, когда источником данных является Сервис объектов с вложениями. Для использования Сервиса объектов с вложениями необходимо <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>вручную привести режим документа к стандартам Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>вернуться к Internet Explorer 9</a> или обновить ОС до Windows 8.",
				oldBrowserExplain: "Этот браузер не поддерживает автоматическое создание эскизов из изображений, которые вы загрузили в Тур по карте. Можно создать Тур по карте с помощью этого браузера, но вам придется задать отдельный эскиз для каждого из загруженных изображений.",
				oldBrowserExplain2: "Для достижения наилучшего результата <a href='http://browsehappy.com/' target='_blank'>обновите браузер</a> или <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>активируйте Google Chrome Frame для Internet Explorer</a>.",
				oldBrowserExplain3: "Конструктор Тура по карте не работает в Internet Explorer 10 на Windows XP.",
				oldBrowserClose: "Закрыть"
			},
			mobileHTML: {
				showIntro: "ПОКАЗАТЬ НАЗВАНИЕ",
				hideIntro: "СКРЫТЬ НАЗВАНИЕ",
				navList: "Список",
				navMap: "Карта",
				navInfo: "Медиа",
				introStartBtn: "Начало"
			},
			desktopHTML: {
				storymapsText: "Карта истории",
				builderButton: "Переключиться в режим компоновки",
				bitlyTooltip: "Получить короткую ссылку на приложение",
				bitlyStartIndex: "Ж_Link to current place_Я"
			},
			builderHTML: {
				panelHeader: "КОНФИГУРАЦИЯ ПРИЛОЖЕНИЯ",
				buttonSave: "СОХРАНИТЬ",
				buttonSettings: "Настройки",
				buttonShare: "Ж_Share_Я",
				buttonView: "Режим просмотра",
				buttonItem: "Открыть элемент Веб-приложение",
				buttonHelp: "Справка",
				buttonOrganize: "Организовать",
				buttonAdd: "Добавить",
				buttonImport: "Импорт",
				buttonImportDisabled: "Импорт не доступен при использовании сервиса объектов с вложениями",
				dataEditionDisabled: "У источника данных CSV отключено редактирование данных",
				dataSourceWarning: "Слой данных Тура по карте был изменен. Если ID объектов отличаются, необходимо сбросить упорядоченные и скрытые точки с помощью команды <b>Организовать</b>. Если имена полей отличаются, следует сбросить настройки полей на <b>закладке данных в разделе Настройки</b>.",
				organizeWarning: "Одна или несколько точек, добавленные вне интерактивного построителя, скрыты.",
				dataPicError0a: "Этот тур содержит <b>%NB%</b> несоответствующих URL-адресов изображений.",
				dataPicError0b: "Этот тур может содержать <b>%NB%</b> несоответствующих URL-адресов изображений.",
				dataPicError1: "Теперь для тура по карте требуется, чтобы URL-адрес изображения заканчивался одним из следующих расширений: .jp(e)g, .png, .gif или .bmp.",
				dataPicError2: "Это требование не касается существующих, уже опубликованных туров по карте. Однако чтобы использовать интерактивный конструктор, следует сначала решить проблему URL-адреса одним из двух способов:",
				dataPicError3: "Отредактировать URL-адреса",
				dataPicError4: "При этом в конце неподдерживаемого URL-адреса будет добавлено окончание <i>#isImage</i>. Большинство серверов поддерживает окончания URL-адресов. Однако после этого следует проверить, что обновленные URL-адреса изображений работоспособны, пройдя по точкам. Если каждое изображение загружается, можно сохранить тур по карте. Если <b>изображения не появляются, не сохраняйте тур по карте</b>. Вместо этого, перезапустите конструктор и выполните второе действие.",
				dataPicError5: "Ограничьте тур только изображениями",
				dataPicError6: "При включении этой опции все URL-адреса рассматриваются как изображения, но вы не сможете добавлять с помощью интерактивного конструктора видео-файлы. Эту опцию можно отключить, если вы захотите в будущем добавить видео.",
				dataPicError7: "Тур по карте был ограничен для работы только с изображениями, видео использоваться не может. Если вы хотите убрать это ограничение, проверьте, что изображения загружаются правильно перед сохранением тура по карте. При необходимости данное ограничение можно снова включить.",
				dataPicError8: "Убрать ограничение на использование только изображений",
				dataPicError9: "Если эти URL-адреса ссылаются на видео, вы можете игнорировать предупреждение, но если по ним загружаются изображения, необходимо выполнить одно из следующих действий:",
				modalCancel: "Отмена",
				modalApply: "Применить",
				organizeHeader: "Организовать тур",
				organizeGeneralCaption: "Используйте перетаскивание для сортировки точек тура",
				organizeDelete: "Удалить",
				organizeHide: "Скрыть",
				organizeReset: "Сбросить упорядоченные и скрытые точки",
				addMaxPointReached: "Вы достигли максимального числа точек, разрешенного набором значков, и не можете добавить еще одну точку тура.<br /><br />Обратите внимание, что если удалить существующие точки, приложение придется перезагрузить.",
				addMaxPointReachedMobile: "Вы достигли максимального количества авторизованных точек и не можете добавить это изображение.",
				addClose: "Закрыть",
				addHeader: "Добавить новую точку тура",
				addTabPicture: "Медиа",
				addTabInformation: "Информация",
				addTabLocation: "Местоположение",
				addSelectCaption: "Выберите или перетащите изображение",
				addNoteVideo: "Обратитесь к Справке, чтобы получить инструкции по использованию видео",		
				addSelectCaptionNoFileReader: "Выбрать изображение",	
				addChangePhoto: "Изменить изображение и эскиз",
				addPictureResolutionIntro: "Разрешение изображения выше необходимого:",
				addPictureResolutionOldBrowser: "Разрешение изображения выше необходимого. Оптимизируйте Тур по карте, задав разрешение ниже, чем %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Изменить разрешение изображения на %RESOLUTION%",
				addPictureResolutionKeep: "Сохранить исходное разрешение %RESOLUTION%",
				addSelectThumbnail: "Выберите значок",
				addNoThumbSelected: "Значок не выбран",
				addThumbSelected: "Выбрано",
				addCameraSettingsHeader: "НАСТРОЙКИ КАМЕРЫ",
				addThumbnailHeader: "ЗНАЧОК",
				addLabelPicUrl: "Изображение",
				addLabelThumbUrl: "Образец",
				addTextPlaceholderUrl: "Введите URL-адрес изображения",
				addTextPlaceholderUrl2: "Ж_Enter a Youtube page URL_Я",
				addTextPlaceholderUrl3: "Введите URL-адрес страницы Vimeo",
				addTextPlaceholderUrl4: "Введите URL-адрес видео",
				addLabelVideo: "Видео",
				addMediaVideoOther: "Другие",
				addMediaVideoHelp: "Отметьте URL-адрес и получите эскиз, использующийся по умолчанию",
				addMediaVideoHelpTooltip1: "Проверка выполнена успешно",
				addMediaVideoHelpTooltip2: "Проверка не удалась",
				addMediaVideoHelpTooltip4: "Найдите опцию для вставки видео и скопируйте URL-адрес видео-файла из этого кода",
				addLabelName: "Имя",
				addLabelDescription: "Заголовок",
				addTextPlaceholder: "Введите что-нибудь",
				addLocatePlaceholder: "Найдите адрес или место",
				addPinColor: "Цвет",
				addLatitude: "Широта",
				addLongitude: "Долгота",
				addLatitudePlaceholder: "например, 34.056",
				addLongitudePlaceholder: "например, -117.195",
				addUploading: "Загрузка точки маршрута",
				addSave: "Добавить точку маршрута",
				addMobileUploading: "Загрузка изображения",
				addMobileName: "Введите имя",
				addMobileNameMandatory: "Ошибка, введите имя.",
				addMobileError: "Извините, что-то пошло не так",
				settingsHeader: "Настройки приложения",
				settingsTabLayout: "Компоновка",
				settingsTabColor: "Цвета",
				settingsTabLogo: "Заголовок",
				settingsTabFields: "Данные",
				settingsTabExtent: "Экстент",
				settingsTabZoom: "Уровень масштабирования",
				settingsLayoutExplain: "Выберите желаемую компоновку приложения.",
				settingsLayoutProfessional: "Трехпанельная компоновка",
				settingsLayoutModern: "Интегрированная компоновка",
				settingsLayoutSelected: "Выбранная компоновка",
				settingsLayoutSelect: "Выбрать эту компоновку",
				settingsLayoutNote: "У точек, использующих видео, всегда имеется соответствующий значок, даже если эта опция отключена.",
				settingsLayoutLocBtn: "Ж_Display a locate button on supported browser_Я",
				settingsLayoutLocBtnHelp: "Эта функция поддерживается на большинстве браузеров мобильных устройств и настольных ПК (Internet Explorer 9).",
				settingsColorExplain: "Измените внешний вид, выбрав готовую тему или создав свою собственную.",
				settingsLabelColor: "Цвета колонтитулов и содержания",
				settingsLogoExplain: "Настройка логотипа заголовка (максимум 250 x 50px).",
				settingsLogoEsri: "Логотип Esri",
				settingsLogoNone: "Без логотипа",
				settingsLogoCustom: "Собственный логотип",
				settingsLogoCustomPlaceholder: "URL-адрес изображения",
				settingsLogoCustomTargetPlaceholder: "Переход по ссылке",
				settingsLogoSocialExplain: "Настроить верхнюю правую ссылку заголовка.",
				settingsLogoSocialText: "Текст",
				settingsLogoSocialLink: "Ссылка",
				settingsLogoSocialDisabled: "Объект был отключен администратором",
				settingsDataFieldsExplain: "Выберите поля имени, заголовка и цвета фотографии.",
				settingsDataFieldsError: "Приложение не может определить соответствующие данные имени, заголовка или цвета. Выберите поля, которые будут здесь использоваться. Позже эти параметры можно будет изменить.",
				settingsFieldsLabelName: "Имя",
				settingsFieldsLabelDescription: "Заголовок",
				settingsFieldsLabelColor: "Цвет",
				settingsFieldsReset: "Очистить выборку полей",
				settingsExtentExplain: "Выберите начальный экстент Тура по карте через интерактивную карту, показанную ниже.",
				settingsExtentExplainBottom: "Указанный экстент приведет к изменению исходного экстента веб-карты. Помните, этот экстент не используется, если он не содержит первую точку маршрута. В этом случае первая точка маршрута будет отображаться в центре.",
				settingsExtentDateLineError: "Экстент не может продолжаться за меридиан 180°",
				settingsExtentDateLineError2: "Ошибка вычисления экстента",
				settingsExtentDrawBtn: "Нарисовать новый экстент",
				settingsExtentModifyBtn: "Изменить экстент",
				settingsExtentApplyBtn: "Просмотр на Туре по карте",
				settingsExtentUseMainMap: "Использовать экстент Тура по карте",
				settingsZoomExplain: "Установить масштаб для точек истории после введения (необязательно).",
				settingsLabelZoom: "Масштаб/уровень",
				settingsZoomFirstValue: "Нет",
				settingsFieldError: "Выберите поле в каждом списке",
				dataTitle: "Ж_ArcGIS Online hosting_Я",
				dataExplain: "Ж_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._Я",
				dataNameLbl: "Имя сервиса",
				dataFolderListLbl: "Папка",
				dataFolderListFetching: "Извлечение папок ...",
				dataRootFolder: "Корень",
				dataNameError: "Введите имя сервиса объектов",
				dataFolderError: "Выберите допустимую папку",
				dataSrcContainsInvalidChar: "Имя сервиса объектов содержит один или несколько недопустимых символов (-, <, >, #, %, :, \", ?, &, +, / или \).",
				dataSrvAlreadyExistsError: "Сервис с таким именем уже существует в организации. Выберите другое имя.",
				dataBtnSave: "Создать сервис",
				dataFooterProgress: "Создание в процессе",
				dataFooterSucceed: "Создание выполнено успешно. Загрузка",
				dataFooterError: "Создание не удалось. Попробуйте еще раз",
				tabError: "Проверьте все закладки на наличие ошибок",
				introRecordBtn: "Введение",
				introRecordActivate: "Использовать первую точку как введение (не показывается в карусели)"
			},
			addPopupJS: {
				uploadingPicture: "Загрузка изображения",
				uploadSuccess: "Загрузка выполнена успешно",
				uploadError: "Ошибка загрузки изображения",
				uploadError2: "Ошибка добавления объекта (недопустимый html-тег)",
				notJpg: "Выберите фотографию в формате jpeg для загрузки",
				errorNoPhoto: "Выберите изображение для загрузки",
				errorNoThumbnail: "Выберите значок для загрузки",
				errorInvalidPicUrl: "Введите корректный URL-адрес изображения (начинается с http(s)://, заканчивается расширением jpg, png, gif или bmp). Для обхода этого правила можно закончить URL-адрес окончанием '#isImage'.",
				errorInvalidThumbUrl: "Введите корректный URL-адрес эскиза (начинается с http(s)://, заканчивается расширением jpg, png, gif или bmp).",
				errorInvalidVideoUrl: "Введите корректный URL-адрес видео (начинающийся с http(s)://)",
				errorNoName: "Введите имя для этой точки маршрута",
				errorNoDescription: "Введите заголовок для этой точки маршрута",
				errorNoLocation: "Введите местоположение для этой точки маршрута"
			},
			builderJS: {
				noPendingChange: "Ж_No unsaved change_Я",
				unSavedChangeSingular: "1 несохраненное изменение",
				unSavedChangePlural: "несохраненных изменений",
				shareStatus1: "Ж_Tour is not saved_Я",
				shareStatus2: "Ж_Tour is shared publicly_Я",
				shareStatus3: "Ж_Tour is shared within the organization_Я",
				shareStatus4: "Ж_Tour is not shared_Я",
				popoverDiscard: "Вы действительно хотите отказаться от несохраненных изменений?",
				yes: "Да",
				no: "Нет",
				popoverLoseSave: "При открытии вьюера вы потеряете все несохраненные изменения",
				ok: "Ok",
				popoverSaveWhenDone: "Не забудьте сохранить изменения, когда закончите",
				closeWithPendingChange: "Вы действительно хотите подтвердить это действие? Все изменения будут потеряны.",
				gotIt: "Ok",
				savingApplication: "Сохранение приложения",
				saveSuccess: "Приложение успешно сохранено",
				saveError: "Сохранение не удалось, попробуйте еще раз",
				saveError2: "Ошибка при сохранении из-за недопустимого html-тега в имени или описании",
				saveError3: "Ж_The title can't be empty_Я",
				dragColorPicker: "Переместить меня<br />или изменить цвет",
				dataWarningExtent: "Имеются данные за пределами экстента веб-карты. Эти данные не будет использоваться как точки маршрута, измените экстент карты, чтобы использовать их.",
				dataWarningVisibi: "Слой Тура по карте не отображается при текущем экстенте веб-карты. Подтвердите, что слой Тура по карте отображается на карте размера %MAPSIZE%.",
				dataWarningEdit: "Редактировать веб-карту",
				dataWarningClose: "Закрыть",
				signIn: "Войдите с помощью учетной записи в",
				signInTwo: "чтобы сохранить приложение.",
				switchBM: "Ж_Change Basemap_Я"
			},
			organizePopupJS: {
				messageStart: "Вы выбрали удаление",
				messageSinglePoint: "одной точки тура",
				messageMultiPoint: "точек тура",
				messagePermantRemove: "Произойдет окончательное удаление",
				messageRecord: "записи",
				messageRecordPlural: "записей",
				messageConfirm: "из вашей базы данных. Вы хотите продолжить?",
				labelButtonShow: "Показать",
				labelButtonHide: "Скрыть"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Рисунок и образец будет полностью удален",
				popoverDeleteWarningThumb: "Образец будет полностью удален",
				popoverUploadingPhoto: "Загрузка изображения и значка",
				popoverUploadingThumbnail: "Загрузка значка",
				popoverUploadSuccessful: "Загрузка выполнена успешно",
				popoverUploadError: "Загрузка не удалась, попробуйте еще раз",
				changePicAndThumb: "Выберите изображение",
				changeThumb: "Изменить значок",
				selectPic: "Изменить медиа",
				selectThumb: "Изменить значок",
				uploadPicAndThumb: "Применить"
			},
			headerJS:{
				editMe: "Отредактируйте меня !",
				templateTitle: "Ввести заголовок шаблона",
				templateSubtitle: "Ввести подзаголовок шаблона"
			},
			crossFaderJS:{
				setPicture: "Ввести название изображения",
				setCaption: "Ввести заголовок изображения"
			},
			importPopup: {
				title: "Импорт",
				prevBtn: "Назад",
				nextBtn: "Далее"
			},
			importPopupHome: {
				header: "Где хранятся ваши изображения?"
			},
			onlinePhotoSharingCommon: {
				pictures: "рисунки",
				videos: "видео",
				disabled: "Объект был отключен администратором",
				disabledPortal: "В Portal for ArcGIS эта функция отключена",
				header1: "Ж_Your pictures must be shared publicly._Я",
				header2: "Ж_The import will be limited to the first %NB1% %MEDIA%._Я",
				emptyDataset: "Ошибка, изображения не найдены",
				footerImport: "Импорт",
				selectAlbum: "Выберите публичный альбом",
				selectAlbum2: "Выберите альбом",
				pleaseChoose: "Выберите",
				userLookup: "Найти",
				userLookingup: "Поиск",
				csv: "Указан в CSV",
				advanced: "Дополнительные опции",
				advancedScratchLbl: "Ж_Start a new Tour_Я",
				advancedScratchTip: "Ж_Create an empty Tour that you will be able populate manually using a wizard._Я",
				advancedCSVLbl: "Ж_Import Tour data from a CSV file_Я",
				advancedCSVTip: "Ж_Import your Tour content from a CSV file._Я",
				advancedCommonTip: "Ж_It requires that your images and videos are already online._Я",
				select: "Сделать выборку",
				locUse: "Ж_Use pictures geolocation_Я",
				locExplain: "Ж_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._Я",
				locExplain2: "Ж_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._Я"
			},
			viewFlickr: {
				title: "Ж_Flickr import_Я",
				header: "Ж_Enter your Flickr user name and select a Photo Set or a Tag to be imported._Я",
				userInputLbl: "Введите имя пользователя",
				signInMsg2: "Пользователь не найден",
				selectSet: "Выберите набор фотографий",
				selectTag: "или выберите тег",
				footerImportTag: "Импорт выбранного тега",
				footerImportSet: "Импорт выбранного набора"
			},
			viewFacebook: {
				title: "Ж_Facebook import_Я",
				header: "Ж_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._Я",
				leftHeader: "Пользователь Facebook",
				rightHeader: "Страница Facebook",
				pageExplain: "Страница Facebook - это публичный продукт, как <b>esrigis</b>. Вы можете взять имя страницы, расположенное после первой косой черты \'/\' в URL страницы.",
				pageInputLbl: "Введите название страницы",
				lookupMsgError: "Страница не найдена"
			},
			viewPicasa: {
				title: "Ж_Picasa/Google+ import_Я",
				header: "Ж_Enter your email address or the ID of your Picasa or Google+ account._Я",
				userInputLbl: "Введите эл.почту или ID",
				signInMsg2: "Учетная запись не найдена",
				howToFind: "Ж_How to find a Picasa or Google+ account ID_Я",
				howToFind2: "Скопируйте цифры, расположенные между первой и второй косой чертой \'/\' любой страницы Picasa или G+"
			},
			viewCSV: {
				title: "Ж_CSV import_Я",
				uploadBtn: "Выберите или перетащите CSV-файл",
				resultHeaderEmpty: "CSV-файл пустой",
				resultHeaderSuccess: "Успешно загружено %NB_POINTS% точек",
				resultHasBeenLimited: "Импорт ограничен первыми %VAL1% из %VAL2% точек для соответствия ограничению в %VAL3% точек на тур",
				browserSupport: "Ваш браузер не поддерживается. Для использования CSV вам нужно <a href='http://browsehappy.com/' target='_blank'>обновить браузер</a> либо использовать вьюер веб-карт ArcGIS.com (см. Справку).",
				errorLatLng: "Не найдены поля широты и долготы. Возможные значения для широты: <i>%LAT%</i>, а для долготы: <i>%LONG%</i>.",
				errorFieldsExplain: "Загрузка не удалась, т.к. не найдены следующие обязательные поля",
				errorFieldsName: "<b>Имя</b>. Допустимые значения: %VAL%",
				errorFieldsDesc: "<b>Описание</b>. Допустимые значения: %VAL%",
				errorFieldsUrl: "<b>URL изображения</b>. Допустимые значения: %VAL%",
				errorFieldsThumb: "<b>URL образца</b>. Допустимые значения: %VAL%",
				errorFields2Explain: "Загрузка не удалась, т.к. CSV не использует такие же атрибуты, как следующие атрибуты слоя",
				errorFields2Name: "<b>Имя</b>. Используется %VAL1% вместо %VAL2%",
				errorFields2Desc: "<b>Описание</b>. Используется %VAL1% вместо %VAL2%",
				errorFields2Url: "<b>URL изображения</b>. Используется %VAL1% вместо %VAL2%",
				errorFields2Thumb: "<b>URL образца</b>. Используется %VAL1% вместо %VAL2%",
				resultFieldsAll: "Все атрибуты импортированы",
				resultFieldsNotAll: "Следующие атрибуты не были импортированы, т.к. они отсутствуют в слое карты",
				resultFieldsNotAll2: "Следующие атрибуты были импортированы",
				footerNextBtnResult: "Импорт в веб-карту",
				footerProgress: "Производится импорт",
				footerSucceed: "Импорт успешно завершен. Загрузка"
			},
			viewYoutube: {
				title: "Ж_Youtube import_Я",
				header: "Ж_Enter a YouTube user name to find publicly shared videos._Я",
				pageInputLbl: "Ж_Enter a Youtube user name_Я",
				lookupMsgError: "Пользователь не найден",
				howToFind: "Ж_How to find a Youtube user name_Я",
				howToFind2: "Имя пользователя отображается под видео",
				found: "Найдено",
				noData: "Публичных видео не найдено"
			},
			viewGeoTag: {
				title: "Ж_Select and locate your images/videos_Я",
				header: "Щелкните или коснитесь изображений, которые вы хотите импортировать, чтобы разместить их.",
				headerMore: "Ж_Why aren't my images/videos geolocated?_Я",
				headerExplain: "Ж_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._Я",
				leftPanelTab1: "Для размещения",
				leftPanelTab2: "С местоположениями",
				clickOrTap: "Щелкните или коснитесь карты для установки местоположения",
				clearLoc: "Ж_Clear locations_Я",
				clickDrop: "Не импортировать",
				footerImport: "Импорт",
				footerProgress: "Производится импорт",
				footerSucceed: "Импорт успешно завершен. Загрузка...",
				loading: "Загрузка",
				error: "Ж_Pictures geolocation import failed, geolocations have been ignored._Я"
			},
			initPopup: {
				title: "Ж_Welcome to the Map Tour Builder_Я",
				prevBtn: "Назад",
				nextBtn: "Далее"
			},
			initPopupHome: {
				header1: "Ж_Where are your images or videos?_Я",
				header2: "Ж_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._Я",
				title1: "Ж_They are already online_Я",
				title2: "Ж_I need to upload my images_Я",
				hostedFSTooltip: "Ж_Use ArcGIS Online to host your images (doesn't support videos)._Я",
				hostedFsNA: "Ж_Only available for ArcGIS for Organizations Publisher and Administrator users_Я",
				footer1: "По окончании не забудьте опубликовать ваш обзорный тур Тур по карте на странице элемента приложения.",
				footer3: "Скачать шаблон CSV",
				footer4: "Если возникли проблемы с загрузкой, используйте опцию \"Сохранить как\"",
				footer4bis: "Ж_Use right click and \"Save as\" if download doesn't start_Я",
				footer5: "Ж_Learn more_Я",
				footerProgress: "Создание в процессе",
				footerSucceed: "Создание выполнено успешно. Загрузка..."
			},
			helpPopup: {
				title: "Ж_Help_Я",
				close: "Закрыть",
				tab1: {
					title: "Введение",
					div1: "Ж_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._Я",
					div2: "Ж_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_Я",
					div4: "Ж_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._Я",
					div42: "Ж_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._Я",
					div5: "Ж_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._Я"
				},
				tab2: {
					title: "Данные",
					div1: "Главным моментом, который следует учитывать при построении тура, является выбор места хранения ваших изображений. В обзорной карте могут использоваться изображения, которые хранятся на популярных сервисах обмена изображениями, равно как и на любом веб-сервере, а также в виде вложений сервисов объектов.",
					div1a: "В последнем разделе этой закладки находятся сведения о поддерживаемых форматах изображений и видео.",
					div2: "Интерактивный мастер предложит вам два варианта обработки изображений вашего Тура по карте:",
					div3: "<ul><li>Вы можете использовать <b>фотографии, хранящиеся онлайн</b>, например, изображения, содержащиеся на сервисах обмена изображениями, таких как Flickr либо изображения, сохраненные на вашем веб-сайте. Эти изображения будут добавлены в Тур по карте по их URL-адресам.</li><li>Также вы можете <b>загрузить фотографии с вашего компьютера</b> непосредственно в тур. Для этого вам понадобится учетная запись ArcGIS Online и права доступа издателя или администратора, поскольку при этом автоматически создается сервис объектов, в котором фотографии хранятся в виде вложений.</li></ul>",
					div4: "Основные направления применения:",
					div4b: "<b>Ваши фотографии еще не опубликованы</b>, но у вас есть учетная запись ArcGIS Online: наилучший выбор - использование размещенного сервиса объектов. Как и популярные сервисы обмена изображениями, мы оптимизируем ваши изображения для быстрой загрузки, а у вас будет доступ ко всем возможностям администрирования и управления данными платформы ArcGIS.",
					div5: "<b>Вы не являетесь участником организации</b>: сначала вам нужно загрузить изображения на веб-сайт сервиса обмена изображениями либо на собственный веб-сервер. Затем построитель поможет вам использовать эти изображения, которые при этом будут по-прежнему храниться в исходном местоположении.",
					div6: "<b>Вы хотите заново использовать имеющийся сервис объектов</b>, содержащий ваши изображения в виде вложений, либо ссылающийся на внешние изображения: за инструкциями обратитесь к расположенному ниже разделу.",
					div7: "<b>Вы являетесь пользователем предыдущей версии</b> шаблона Тура по карте и у вас есть CSV-файл со ссылками на изображения и эскизы: вы сможете импортировать и настраивать свои данные. Построитель поддерживает только CSV-файлы с полями широты/долготы; CSV-файлы с адресами по-прежнему могут использоваться в веб-карте (см. расположенный ниже раздел).",
					div8: "Импорт из сервисов обмена изображениями",
					div9: "Операция импорта берет ссылки на уже размещенные изображения и сохраняет URL этих изображений в наборе объектов веб-карты. Изображения не сохраняются в ArcGIS Online. Если хостинг изображений не работает, они не будут доступны в Тур по карте, а вместо них будет отображена фраза \"Изображение не доступно\". В зависимости от провайдера сервиса, обзорная карта может не импортировать имя, описание и местоположение изображений. Эти атрибуты хранятся в веб-карте, а любые изменения, внесенные на сервисе хранения изображений, не будут отражены в обзорной карте.",
					div10: "Хранение изображений на веб-сервере",
					div11: "Если вы решите самостоятельно разместить изображения, необходимо вручную создать их образцы. Использование для образцов полноразмерных изображений приведет к потере производительности. В связи с этим мы настоятельно рекомендуем вам использовать сервисы хранения изображений, либо сервисы объектов, которые проделают эту работу за вас.",
					div12: "Использование существующего сервиса объектов или шейп-файла",
					div13: "В качестве источника данных для обзорной карты может использоваться любой точечный сервис объектов или шейп-файл. Вам нужно лишь добавить его в качестве слоя на карту во вьюере карт arcgis.com. Если приложение найдет все необходимые атрибуты в слое, вам будут доступны все возможности мастера.",
					div14: "Ж_The possible values for fields name are (case insensitive):_Я",
					div151: "Имя",
					div152: "Описание",
					div153: "Изображение",
					div154: "Образец",
					div155: "Ж_Color_Я ",
					div16: "Ж_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._Я",
					div162: "При использовании сервиса объектов, в котором изображения хранятся в виде вложений, <b>будут использоваться объекты только с двумя вложениями</b>. Первое вложение задает основное изображение, второе - эскиз.",
					div17: "Поля изображения и эскиза обязательны для сервиса объектов без вложений и не являются обязательными (но настоятельно рекомендуются к использованию) для сервиса объектов с вложениями. Если в вашем сервисе включены вложения, конструктор позволит загружать изображения в качестве вложений. Если нет - вы сможете лишь изменить URL-адрес изображения и эскиза.",
					div172: "При наличии, поля изображения и эскиза будут использоваться всегда, вложения сервиса объектов запрашиваться не будут.",
					div173: "Примеры файлов CSV и шейп-файлов можно загрузить с",
					div18: "Создание размещенных сервисов объектов из файлов CSV или шейп-файлов",
					div19: "При создании размещенного сервиса объектов из файла CSV или шейп-файла по умолчанию вложения не активированы. Для их включения откройте страницу описания сервиса объектов, щелкните стрелку в разделе слоя и вы увидите эту опцию. Тур по карте продолжит использование изображений и эскизов, содержащихся в атрибутах. Кроме того, если вы хотите загрузить изображения в качестве вложений сервиса объектов, вы можете сделать это, используя две кнопки, расположенные на панели управления изображениями (\"Изменить изображение\" и \"Изменить образец\").",
					div20: "Поддерживаемые форматы изображений и видео",
					div21: "Поддерживаемые форматы изображений это: <b>.jpg, .jpeg, .png, .gif и .bmp</b>. Если изображение имеет другое расширение, тур по карте рассматривает его как видео, кроме случаев использования сервиса объектов (подробнее см. ниже).",
					div22: "Шаблон Тура по карте не содержит видео-плейера, поэтому следует использовать внешний видео-плейер, предлагаемый вашим сервисом видео-хостинга (найдите опцию для встраивания видео и скопируйте представленный в нем URL). Если вы хотите сами опубликовать видео, можно создать HTML-страницу с видео-плейером наподобие <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Интерактивный конструктор не имеет элементов интерфейса для вставки видео при использовании сервиса объектов с вложениями, но это можно сделать, отредактировав данные во внешнем редакторе. Например, с помощью вьюера карт arcgis.com, если вы измените поля изображения, укажите внешний видео-файл и добавите в конце строки URL-адреса специальный параметр (#isVideo), указанный файл будет рассматриваться как видео-файл.",
					div24: "Помните, что вам необходимы два вложенных изображения, иначе объект использоваться не будет. Невозможно использовать видео при работе с вложениями сервиса объектов без полей изображения и эскиза."
				},
				tab3: {
					title: "Настройка",
					div1: "Мастер предоставляет вам несколько опций настройки, доступных с использованием кнопки Настройки (SETTINGS) на верхней панели. Если вы не нашли нужную опцию, мы также предоставляем вам загружаемую версию, которую вы сможете развернуть на своем веб-сервере и настроить в соответствии со своими требованиями.",
					div2: "Мы рекомендуем использовать размещенную версию, кроме следующих случаев:",
					div3: "<li>Не предоставляется нужная вам настройка UI, например, использование фонового изображения для заголовка.</li><li>Вы являетесь разработчиком и хотите доработать приложение.</li>",
					div4: "Загружаемую версию можно настроить с помощью веб-карты или идентификатора приложения веб-картографии. В основном используются следующие способы:",
					div41: "Вы создаете обзорную карту с помощью интерактивного построителя в размещенной среде и настраиваете шаблон с применением идентификатора приложения веб-картографии. Будут применены все настройки, заданные в конструкторе.",
					div42: "Ж_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._Я",
					div43: "Обратите внимание, что интерактивный конструктор доступен в загружаемой версии, но с некоторыми техническими ограничениями по используемым браузерам, например не работает в Internet Explorer до версии 10.",
					div5: "Ж_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._Я"
				},
				tab4: {
					title: "Подсказки",
					div0: "Поддерживаемые браузеры",
					div0a: "Вьюер Тура по карте поддерживается в IE8+. Интерактивный конструктор поддерживается в IE9+. Мы постоянно тестируем его во всех основных браузерах, но если есть проблемы, рекомендуется перейти на Chrome.",
					div0b: "Если вы испытываете трудности, пожалуйста, дайте нам знать. Между тем, при построении Тура по карте с помощью CSV-шаблона используется минимальное количество функций конструктора.",
					div1: "Рисунки",
					div2: "Ж_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._Я",
					div2a: "Ж_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._Я",
					div3: "Форматирование текста заголовка с помощью тегов HTML",
					div4: "Заголовок и название/подпись изображения могут содержать HTML-теги для форматирования и добавления ссылок. Например, этот код позволяет добавить ссылку желтого цвета:",
					div4a: "Ж_Write a good subtitle for your tour_Я",
					div4b: "Ж_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._Я",
					div5: "Поддержка слоев",
					div6: "Вы также можете добавлять дополнительные слои, обеспечивающие контекст для Тура по карте. Эти слои могут содержать другие географические объекты, которые вы хотите показать в дополнение к точкам Тура по карте, например, границы изучаемой территории, пешеходный или автомобильный маршрут, соединяющий ваши точки и т.д. Шаблон Тура по карте отображает такие дополнительные слои с помощью символов, заданных в веб-карте, но всплывающие окна не поддерживаются.",
					div7: "Сделайте ваш тур коротким и интересным",
					div8: "Число точек Тура по карте ограничено 99-ю. Большинство таких Туров, конечно же, значительно короче. Не рассчитывайте, что пользователи захотят изучать слишком большое количество точек. Вы можете считать свой Тур очень интересным, но не следует рассчитывать, что все пользователи думают так же!",
					div9: "Подробнее см. <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>детальное руководство</a>.",
					div10: "Встроенный режим",
					div11: "Если вы хотите встроить шаблон в другой сайт через iframe, добавление дополнительного параметра \"&embed\" в конце URL-адреса приведет к удалению заголовка. Этот режим также можно включить в загружаемой версии через файл конфигурации.",
					div12: "Ж_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._Я" 
				},
				tab5: {
					title: "Публикация",
					div1: "Ж_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._Я",
					div2a: "Ж_Sharing the Tour through the builder_Я",
					div2b: "Ж_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._Я",
					div2c: "Ж_Sharing the Tour through ArcGIS Online_Я",
					div2d: "Ж_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._Я",
					div3t: "Ж_Feature Service security_Я",
					div3a: "Ж_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._Я",
					div3t2: "Ж_Before sharing your Tour with your audience_Я",
					div3: "Ж_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._Я",
					div4: "Ж_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._Я",
					div5a: "Ж_Recommendation for search_Я",
					div5b: "Ж_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._Я"
				}
			},
			share: {
				firstSaveTitle: "Ж_Tour successfully saved_Я",
				firstSaveHeader: "Ж_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._Я",
				firstSaveA1: "Ж_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_Я",
				firstSaveA1bis: "Ж_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._Я",
				firstSaveQ2: "Ж_Is my Tour shared?_Я",
				firstSaveA2: "Ж_Currently your Tour is not shared. To share it, use the SHARE button._Я",
				shareTitle: "Ж_Share your Tour_Я",
				sharePrivateHeader: "Ж_Your Tour is not shared, would you like to share it?_Я",
				sharePrivateBtn1: "Ж_Share publicly_Я",
				sharePrivateBtn2: "Ж_Share with my Organization_Я",
				sharePrivateProgress: "Ж_Sharing in progress..._Я",
				sharePrivateErr: "Ж_Sharing failed, try again or_Я",
				sharePrivateOk: "Ж_Sharing updated successfully, loading..._Я",
				sharePreviewAsUser: "Ж_Preview_Я",
				shareHeader1: "Ж_Your Tour is <strong>publicly accessible</strong>._Я",
				shareHeader2: "Ж_Your Tour is accessible by your organization members (login is required)._Я",
				shareLinkHeader: "Ж_Share the Tour with your audience_Я",
				shareLinkOpen: "Ж_OPEN_Я",
				shareQ1Opt1: "Ж_How do I keep the Tour private?_Я",
				shareQ1Opt2: "Ж_How do I keep the Tour private or share it publicly?_Я",
				shareA1: "Ж_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._Я",
				shareA1bis: "Ж_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._Я",
				shareQ2: "Ж_How do I edit the Tour later?_Я",
				shareQ2bis: "Ж_How do I get back to the authoring interface?_Я",
				shareA2div1: "Ж_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._Я",
				shareA2div2: "Ж_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_Я",				
				shareQ3: "Ж_Where is the data stored?_Я",
				shareA3: "Ж_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._Я"
			}
        }
    })
);
