define({
    root: ({
        map: {
            error: "Không thể tạo bản đồ",
            views: "lượt xem."
        },
        report: {
            flag: "Gắn cờ là không phù hợp",
            error: "Lỗi",
            success: "Gắn cờ",
            loading: "Đang tải&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Mô tả không khả dụng",
            bookmarks: "Đánh dấu",
            zoomTo: "Phóng to đến vị trí này và tìm hiểu thêm thông tin.",
            untitledNote: "Chưa có tiêu đề"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Lớp phương tiện",
            mediaLayersDescription: "Hiển thị đóng góp của cộng đồng trên bản đồ.",
            flickrSettings: "Thiết lập Flickr",
            twitter: "Twitter",
            twitterSettings: "Thiết lập Twitter",
            twitterUser: "Tài khoản Twitter",
            twitterSignIn: "Đăng nhập vào Twitter",
            webcams: "Webcams.travel",
            instagram: "Instagram",
            instagramSettings: "Thiết lập Instagram",
            igTime: "Tải lên trong số ngày qua",
            youtube: "YouTube",
            youtubeSettings: "Thiết lập YouTube",
            ytSettingsInfo: "Xem video do người dùng tạo bao gồm nội dung trên mạng và nội dung chuyên nghiệp.",
            ytTime: "Tải lên trong quá khứ",
            today: "Ngày",
            this_week: "Tuần",
            this_month: "Tháng",
            all_time: "Tất cả thời gian",
            moreInfo: "Thông tin khác",
            searchTerms: "Thuật ngữ tìm kiếm",
            search: "Tìm kiếm",
            flSettingsInfo: "Trả về kết quả phù hợp với tiêu đề hình ảnh, mô tả hoặc thẻ.",
            twSettingsInfo: "Xem điều gìâ€™đang xảy ra.",
            igSettingsInfo: "Instagram là một cách nhanh chóng, thú vị và hay để chia sẻ cuộc sống của bạn với bạn bè và gia đình.",
            advancedOperators: "Mẹo: sử dụng <a target=\"_blank\" href=\"https://support.twitter.com/articles/71577-using-advanced-search\">các toán tử</a> để tạo tìm kiếm nâng cao.",
            tweetsFilteredBy: "lọc bài đăng theo:",
            photosFilteredBy: "lọc ảnh theo:",
            videosFilteredBy: "lọc video theo:",
            twitterAccountStatus: "Bật lớp Twitter để xem trạng thái của bạn."
        },
        general: {
            map: "Bản đồ",
            mapInfo: "Thông tin Bản đồ",
            legend: "Chú giải",
            featured: "Địa điểm nổi bật",
            layers: "Lớp",
            share: "Chia sẻ",
            about: "Về",
            find: "Mã Zip, thành phố, v.v.",
            moreInfo: "Thông tin khác",
            dateModified: "Chỉnh sửa lần cuối",
            noSearchResult: "Không tìm thấy kết quả",
            switchAccount: "Chuyển đổi tài khoản",
            signIn: "Đăng nhập",
            settings: "Thiết lập"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});