/* 
This source is a compressed form of part of the git commit 
b6ac0c9905c57950 2014-08-15 15:54:01 -0700
Uncompressed source is available from https://github.com/Esri/local-government-online-apps 
*/ 
/*

 | Copyright 2012 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
*/
define("js/lgonlineBase js/lgonlineCommand js/lgonlineDijit js/lgonlineDrawing js/lgonlineEditing js/lgonlineFrame js/lgonlineMap js/lgonlineOutput".split(" "),function(){return{}});
require({cache:{"js/lgonlineBase":function(){define("dojo/_base/declare dojo/dom-construct dojo/dom dojo/on dojo/dom-geometry dojo/dom-style dojo/dom-class dojo/_base/array dojo/topic dojo/_base/lang".split(" "),function(d,l,r,m,t,n,q,b,p,h){d("js.LGObject",null,{constructor:function(c){var f,b,g=this;void 0!==c&&d.safeMixin(this,c);this.checkPrerequisites&&this.checkPrerequisites();c={};this.rootId&&(c.id=this.rootId);this.rootClass?c.className=this.rootClass:c.style="display:none";void 0!==this.parentDiv?
(f=this.parentDiv,(b=r.byId(f))||(f=null)):f=null;b&&b.getLGObject&&b.getLGObject().addItem?(this.rootDiv=l.create("div",c),b.getLGObject().addItem(this.rootDiv)):this.rootDiv=l.create("div",c,f);this.rootDiv.getLGObject=function(){return g}},getRootDiv:function(){return this.rootDiv},lgById:function(c){var f=null;(c=r.byId(c))&&c.getLGObject&&(f=c.getLGObject());return f},deleteDivFromDom:function(){this.rootDiv&&this.rootDiv.parentNode.removeChild(this.rootDiv)},injectCSS:function(c){var f;f=document.createElement("style");
f.setAttribute("type","text/css");f.styleSheet?f.styleSheet.cssText=c:(c=document.createTextNode(c),f.appendChild(c));document.body.appendChild(f);return f},checkForSubstitution:function(c){var f,b=c;c&&1<c.length&&(f=c.substring(0,1),"@"===f?this.appConfig.i18n&&(b=this.followAttributePath(this.appConfig.i18n,c.substring(1))):"!"===f?window.jsapi_i18n&&(b=this.followAttributePath(window.jsapi_i18n,c.substring(1))):"."===f&&(b=this.followAttributePath(null,c.substring(1))));return b},followAttributePath:function(c,
f){var b,g=c,s;try{for(s=f.split("."),b=0;b<s.length;b+=1)g=null===g?this.lgById(s[b]):g[s[b]]}catch(h){g=null}return g},toBoolean:function(c,f){var b;if(!0===c)return!0;if(!1===c)return!1;if("string"===typeof c){b=c.toLowerCase();if("true"===b)return!0;if("false"===b)return!1}return void 0===f?!0:f},toNumber:function(c,f){if("number"===typeof c)return c;c=parseFloat(c);return isNaN(c)?void 0===f?0:f:c},log:function(c,f){console&&console.log(c);f&&this.publishMessage(this.appConfig.errorPublishingFlag,
c);window.gLogMessageBox&&window.gLogMessageBox.append(c)},publishMessage:function(c,f){p.publish("publish",{id:this.rootId,tag:c,data:f});p.publish(c,f)},subscribeToMessage:function(c,f){var b=this;p.subscribe(c,function(f){p.publish("receive",{id:b.rootId,tag:c,data:f})});p.subscribe(c,f)}});d("js.LGGraphic",js.LGObject,{constructor:function(){m(window,"resize",h.hitch(this,this.handleWindowResize));this.handleWindowResize()},setIsVisible:function(c,f){f?(n.set(this.getRootDiv(),"display","block"),
n.set(this.getRootDiv(),"visibility",c?"visible":"hidden")):(c?this.show():this.hide(),n.set(this.getRootDiv(),"visibility","visible"))},getIsVisible:function(){return"none"!==n.get(this.getRootDiv(),"display")},toggleVisibility:function(){this.getIsVisible()?this.hide():this.show()},show:function(){n.set(this.getRootDiv(),"display","block")},hide:function(){n.set(this.getRootDiv(),"display","none")},handleWindowResize:function(){void 0!==this.fill&&!0===this.fill?this.fillParentDiv():void 0!==this.horizOffset&&
void 0!==this.vertOffset&&this.alignOver(this.rootDiv,this.rootDiv.parentNode,this.horizOffset,this.vertOffset)},fillParentDiv:function(){var c;this.rootDiv.parentNode&&(c={left:"0px",top:"0px",width:this.rootDiv.parentNode.clientWidth+"px",height:this.rootDiv.parentNode.clientHeight+"px"},n.set(this.rootDiv,c))},alignOver:function(c,f,h,g){var s,u,d,p=this;c&&f&&(s=t.getMarginBox(c),u=t.getMarginBox(f),d={},"number"===typeof h?d=this.insertHorizPositioningStyle(d,h,s,u):"object"===typeof h&&b.forEach(h,
function(c){d=p.insertHorizPositioningStyle(d,c,s,u)}),"number"===typeof g?d=this.insertVertPositioningStyle(d,g,s,u):"object"===typeof g&&b.forEach(g,function(c){d=p.insertVertPositioningStyle(d,c,s,u)}),n.set(c,d))},insertHorizPositioningStyle:function(c,f,b,g){0<f?c.left=f+"px":0===f?c.left=Math.round((g.w-b.w)/2)+"px":c.right=-f+"px";return c},insertVertPositioningStyle:function(c,b,h,g){0<b?c.top=b+"px":0===b?c.top=Math.round((g.h-h.h)/2)+"px":c.bottom=-b+"px";return c},applyTheme:function(c,
b){q.remove(b||this.rootDiv,"appTheme2");q.add(b||this.rootDiv,"appTheme");c&&q.add(b||this.rootDiv,"appThemeHover")},applyThemeAltBkgd:function(c,b){q.remove(b||this.rootDiv,"appTheme");q.add(b||this.rootDiv,"appTheme2");c&&q.add(b||this.rootDiv,"appThemeHover")}});d("js.LGDependency",null,{setUpWaitForDependency:function(c){var b=this;this.dependencyId&&this.declaredClass===c&&(c=this.lgById(this.dependencyId),this.onDependencyPrep(c),c.ready.then(function(){b.onDependencyReady()}))},onDependencyPrep:function(){return null},
onDependencyReady:function(){return null}});d("js.LGDefaults",null,{constructor:function(){this.defaultValues={};this.listenForDefaultsTrigger&&this.listenForDefaultsUpdate()},listenForDefaultsUpdate:function(){var c=this;this.subscribeToMessage(this.listenForDefaultsTrigger,function(b){c.defaultValues=b;c.onDefaultsUpdate()})},onDefaultsUpdate:function(){return null},changeDefaults:function(){this.broadcastDefaultsUpdate()},broadcastDefaultsUpdate:function(){this.broadcastDefaultsPublish&&this.publishMessage(this.broadcastDefaultsPublish,
this.defaultValues)}})})},"js/lgonlineCommand":function(){define("dojo/_base/declare dojo/dom-construct dojo/dom dojo/on dojo/dom-geometry dojo/Deferred dojo/DeferredList dojo/dom-style dojo/dom-class dojo/_base/array dojo/_base/lang dojo/request/xhr dojo/string dijit/form/TextBox dijit/layout/ContentPane dojox/gfx dojox/gfx/utils dgrid/Grid dgrid/Selection esri/dijit/Legend esri/dijit/BasemapGallery esri/dijit/Basemap esri/tasks/locator esri/tasks/PrintTask esri/tasks/PrintParameters esri/tasks/PrintTemplate esri/tasks/LegendLayer esri/tasks/query esri/tasks/QueryTask esri/dijit/PopupTemplate js/lgonlineBase js/lgonlineMap".split(" "),
function(d,l,r,m,t,n,q,b,p,h,c,f,v,g,s,u,y,z,w,A,B,C,D,E,F,G,H,x,I,J){d("js.LGDropdownBox",js.LGGraphic,{constructor:function(){var a=this;this.applyTheme(!1);this.isShowable=!0;this.trigger&&(this.setUpListeningForCommands(),this.subscribeToMessage(this.trigger,function(e){a.handleTrigger(e)}))},setUpListeningForCommands:function(){var a=this;this.subscribeToMessage("command",function(e){e!==a.trigger&&a.setIsVisible(!1)})},setShowable:function(a){this.isShowable=a;!this.isShowable&&this.getIsVisible()&&
this.toggleVisibility()},handleTrigger:function(){this.isShowable&&this.toggleVisibility()}});d("js.LGMapBasedMenuBox",[js.LGDropdownBox,js.LGMapDependency],{constructor:function(){this.ready=new n;this.setUpWaitForDependency("js.LGMapBasedMenuBox")},onDependencyReady:function(){this.ready.resolve(this);this.inherited(arguments)}});d("js.LGBasemapBox",js.LGMapBasedMenuBox,{constructor:function(){this.setUpWaitForDependency("js.LGBasemapBox")},onDependencyReady:function(){var a,e,k,b=this.getBasemapGroup(),
g,h,d;a=this.rootId+"_gallery";e=(new s({id:a,className:this.galleryClass})).placeAt(this.rootDiv);touchScroll(a);g=this.webmapThumbnail||"images/webmap.png";d=new n;try{this.appConfig.proxyurl&&this.appConfig.itemInfo.item.thumbnail?(h=this.appConfig.sharinghost+"/sharing/rest/content/items/"+this.appConfig.itemInfo.item.id+"/info/"+this.appConfig.itemInfo.item.thumbnail,f(this.appConfig.proxyurl+"?"+h).then(function(){g=h;d.resolve()},function(a){d.resolve()})):d.resolve()}catch(u){d.resolve()}d.then(c.hitch(this,
function(){k=(new B({basemaps:[new C({layers:this.appConfig.itemInfo.itemData.baseMap.baseMapLayers,title:this.appConfig.itemInfo.itemData.baseMap.title,thumbnailUrl:g})],showArcGISBasemaps:!0,portalUrl:this.appConfig.sharinghost,basemapsGroup:b,bingMapsKey:this.appConfig.bingKey,map:this.appConfig.map},l.create("div"))).placeAt(this.rootDiv);e.set("content",k.domNode);k.startup()}));this.inherited(arguments)},getBasemapGroup:function(){var a=null;this.basemapgroupTitle&&this.basemapgroupOwner&&0<
this.basemapgroupTitle.length&&0<this.basemapgroupOwner.length?a={title:this.basemapgroupTitle,owner:this.basemapgroupOwner}:this.appConfig.basemapgroup&&(a=this.appConfig.basemapgroup);return a}});d("js.LGDijitLegendBox",js.LGMapBasedMenuBox,{constructor:function(){this.setUpWaitForDependency("js.LGDijitLegendBox")},onDependencyReady:function(){try{var a,e,k,b=this.rootId+"_legend";a=(new s({id:b,className:this.dijitLegendClass})).placeAt(this.rootDiv);touchScroll(b);e=esri.arcgis.utils.getLegendLayers({map:this.appConfig.map,
itemInfo:this.appConfig.itemInfo});k=(new A({map:this.appConfig.map,layerInfos:e},l.create("legendDiv"))).placeAt(this.rootDiv);a.set("content",k.domNode);k.startup();this.inherited(arguments)}catch(c){this.log("LGDijitLegendBox_1: "+c.toString())}}});d("js.LGCallMethods",js.LGObject,{constructor:function(){var a,e=this;this.todo&&h.forEach(this.todo,function(k){try{if(a=r.byId(k.rootId))if(a=a.getLGObject())a[k.method](k.arg)}catch(b){e.log("LGCallMethods_1: "+b.toString())}})}});d("js.LGButton",
js.LGGraphic,{constructor:function(){var a;this.iconJson?(this.foregroundColor="#000",this.hoverColor="#00f",this.iconColorizerId&&(a=r.byId(this.iconColorizerId))&&(a=a.getLGObject(),this.foregroundColor=a.foregroundColor(),this.hoverColor=a.hoverColor()),this.applyTheme(!1),this.rootDiv.surface=this.createSVGIcon(this.iconJson),m(this.rootDiv,"mouseover",c.hitch(this,function(a){this.onMouseOver(a)})),m(this.rootDiv,"mouseout",c.hitch(this,function(a){if(this.mouseOut(a))this.onMouseOut(a)}))):
(this.applyTheme(!0),this.iconUrl&&(a={src:this.iconUrl},this.iconClass&&(a.className=this.iconClass),this.iconImg=l.create("img",a,this.rootDiv)));this.displayText&&(a={innerHTML:this.checkForSubstitution(this.displayText)},this.displayTextClass&&(a.className=this.displayTextClass),l.create("div",a,this.rootDiv));this.tooltip&&(this.rootDiv.title=this.checkForSubstitution(this.tooltip))},createSVGIcon:function(a,e){var k;k=u.createSurface(this.rootDiv,32,32);y.fromJson(k,a);e||(e=this.foregroundColor);
this.changeColor(k,e);this.iconClass&&k.rawNode.setAttribute("class",this.iconClass);return k},onMouseOver:function(a){this.changeColor(a.currentTarget.surface,this.hoverColor)},onMouseOut:function(a){this.changeColor(a.currentTarget.surface,this.foregroundColor)},mouseOut:function(a){var e;e=a.currentTarget||a.srcElement;a=a.relatedTarget||a.toElement;if(!a)return!0;for(;a.parentElement;){if(e===a)return!1;a=a.parentElement}return!0},changeColor:function(a,e){h.forEach(a.children,function(a){if("text"===
a.shape.type)a.setFill(e);else{var b=a.getStroke();b.color=e;a.setStroke(b)}})}});d("js.LGRadioButton",js.LGButton,{constructor:function(){this.isOn=this.toBoolean(this.isOn,!1);this.setIsOn(this.isOn);this.controller=null;m(this.rootDiv,"click",this.handleClick)},setController:function(a){this.controller=a},setIsOn:function(a){this.isOn=a;this.rootDiv.surface?this.isOn?this.changeColor(this.rootDiv.surface,this.hoverColor):this.changeColor(this.rootDiv.surface,this.foregroundColor):this.isOn?this.applyThemeAltBkgd(!0):
this.applyTheme(!0)},onMouseOver:function(a){this.rootDiv.surface?this.isOn||this.changeColor(this.rootDiv.surface,this.hoverColor):this.inherited(arguments)},onMouseOut:function(a){this.rootDiv.surface?this.isOn||this.changeColor(this.rootDiv.surface,this.foregroundColor):this.inherited(arguments)},handleClick:function(a){a=a.currentTarget.getLGObject();a.controller&&a.controller.selectMember(a)}});d("js.LGRadioButtonController",js.LGObject,{constructor:function(){this.members=[];this.currentMember=
null},addMember:function(a){this.members.push(a);a.setController(this)},selectMember:function(a){var e,k=this;this.currentMember&&(this.currentMember.setIsOn(!1),this.currentMember=null);"number"===typeof a?0<this.members.length&&(a=Math.max(0,Math.min(a,k.members.length-1)),k.currentMember=k.members[a],k.currentMember.setIsOn(!0)):"string"===typeof a?h.some(this.members,function(e){return e.value===a?(k.currentMember=e,k.currentMember.setIsOn(!0),!0):!1}):a&&(e=a.rootId,h.some(this.members,function(a){return a.rootId===
e?(k.currentMember=a,k.currentMember.setIsOn(!0),!0):!1}))},getCurrentMember:function(){return this.currentMember}});d("js.LGCommand",[js.LGButton,js.LGDependency],{constructor:function(){this.publish&&(this.clickHandler=m(this.rootDiv,"click",this.handleClick));this.setUpWaitForDependency("js.LGCommand")},onDependencyPrep:function(){this.setIsVisible(!1);this.inherited(arguments)},onDependencyReady:function(){this.setIsVisible(!0);this.inherited(arguments)},handleClick:function(a){a=a.currentTarget.getLGObject();
a.publishMessage("command",a.publish);a.publishMessage(a.publish,a.publishArg)}});d("js.LGCommandToggle",js.LGCommand,{constructor:function(){var a=this;this.rootDiv.surface?p.contains(document.body,"okIE")&&(this.iconDisabledJson=this.iconDisabledJson||this.iconJson,this.rootDiv.surface2=this.createSVGIcon(this.iconDisabledJson)):this.iconDisabledUrl=this.iconDisabledUrl||this.iconUrl;this.isEnabled=this.toBoolean(this.isEnabled,!0);a.setIsEnabled(this.isEnabled);this.isVisible=this.toBoolean(this.isVisible,
!0);a.setIsVisible(this.isVisible);this.triggerEnable&&this.subscribeToMessage(this.triggerEnable,function(){a.isEnabled=!0;a.setIsEnabled(a.isEnabled)});this.triggerDisable&&this.subscribeToMessage(this.triggerDisable,function(){a.isEnabled=!1;a.setIsEnabled(a.isEnabled)});this.triggerVisible&&this.subscribeToMessage(this.triggerVisible,function(){a.isVisible=!0;a.setIsVisible(a.isVisible)});this.triggerInvisible&&this.subscribeToMessage(this.triggerInvisible,function(){a.isVisible=!1;a.setIsVisible(a.isVisible)});
this.setUpWaitForDependency("js.LGCommandToggle")},setIsEnabled:function(a){this.isEnabled=a;this.rootDiv.surface?p.contains(document.body,"okIE")&&(this.isEnabled?(b.set(this.rootDiv.surface.rawNode,"display","inline-block"),b.set(this.rootDiv.surface2.rawNode,"display","none")):(b.set(this.rootDiv.surface.rawNode,"display","none"),b.set(this.rootDiv.surface2.rawNode,"display","inline-block"))):this.isEnabled?(this.iconImg.src=this.iconUrl,p.add(this.rootDiv,"appThemeHover")):(this.iconImg.src=this.iconDisabledUrl,
p.remove(this.rootDiv,"appThemeHover"))},handleClick:function(a){var e=a.currentTarget.getLGObject();e.isEnabled&&e.inherited("handleClick",arguments)}});d("js.LGLaunchUrl",js.LGObject,{constructor:function(){this.subscribeToMessage(this.sameWinTrigger,function(a){a&&window.open(a,"_parent")});this.subscribeToMessage(this.newWinTrigger,function(a){a&&window.open(a,"_blank")})}});d("js.LGPrintMap",js.LGMapBasedMenuBox,{constructor:function(){var a,e=this;this.radioButtonController=new js.LGRadioButtonController;
a=new js.LGRadioButton({rootId:this.rootId+"_landscape",parentDiv:this.rootId,iconUrl:this.landscapeButtonIconUrl,iconJson:this.landscapeButtonIconJson,iconColorizerId:this.iconColorizerId,rootClass:this.orientationButtonClass,iconClass:this.orientationButtonIconClass,tooltip:this.checkForSubstitution(this.landscapeButtonTooltip),value:this.landscapeServerSpec});a.setIsVisible(!0);this.radioButtonController.addMember(a);b.set(a.rootDiv,"display","inline-block");a=new js.LGRadioButton({rootId:this.rootId+
"_portrait",parentDiv:this.rootId,iconUrl:this.portraitButtonIconUrl,iconJson:this.portraitButtonIconJson,iconColorizerId:this.iconColorizerId,rootClass:this.orientationButtonClass,iconClass:this.orientationButtonIconClass,tooltip:this.checkForSubstitution(this.portraitButtonTooltip),value:this.portraitServerSpec});a.setIsVisible(!0);this.radioButtonController.addMember(a);b.set(a.rootDiv,"display","inline-block");this.titleEntryTextBox=(new g({id:this.rootId+"_titleEntry",value:this.title,trim:!0,
placeHolder:this.titleHint||this.checkForSubstitution(this.titleHintDefault)||""})).placeAt(this.rootId);b.set(this.titleEntryTextBox.domNode,"width","97%");p.add(this.titleEntryTextBox.domNode,this.titleClass);this.authorEntryTextBox=(new g({id:this.rootId+"_authorEntry",value:this.author,trim:!0,placeHolder:this.authorHint||this.checkForSubstitution(this.authorHintDefault)||""})).placeAt(this.rootId);b.set(this.authorEntryTextBox.domNode,"width","97%");p.add(this.authorEntryTextBox.domNode,this.authorClass);
a=new js.LGButton({rootId:this.rootId+"_doPrint",parentDiv:this.rootId,iconUrl:this.printButtonIconUrl,iconJson:this.printButtonIconJson,iconColorizerId:this.iconColorizerId,rootClass:this.printButtonClass,iconClass:this.printButtonIconClass,tooltip:this.checkForSubstitution(this.printButtonTooltip)});a.setIsVisible(!0);b.set(a.rootDiv,"display","inline-block");this.radioButtonController.selectMember(0);m(a.rootDiv,"click",function(){var a,b,c=[],g;e.publishMessage(e.publishWorking);e.setIsVisible(!1);
a=e.mapObj.getOperationalLayers();h.forEach(a,function(a){b=new H;b.layerId=a.id;c.push(b)});a=(a=e.radioButtonController.getCurrentMember())?a.value:null;g=new F;g.map=e.appConfig.map;g.outSpatialReference=e.appConfig.map.spatialReference;g.template=new G;g.template.format=e.format||"PDF";g.template.layout=a||e.layout||"Letter ANSI A Landscape";g.template.layoutOptions={titleText:e.titleEntryTextBox.value,authorText:e.authorEntryTextBox.value,copyrightText:e.copyrightText,legendLayers:c};g.template.preserveScale=
e.toBoolean(e.preserveScale,!1);g.template.showAttribution=!0;e.printTask.execute(g,function(a){e.publishMessage(e.publishPrintUrl,a.url);e.publishMessage(e.publishReady)},function(a){e.publishMessage(e.publishReady);e.log("Print failed: "+a.message,!0)})});this.setUpWaitForDependency("js.LGPrintMap")},checkPrerequisites:function(){if(this.appConfig.helperServices&&this.appConfig.helperServices.printTask&&this.appConfig.helperServices.printTask.url)this.printTask=new E(this.appConfig.helperServices.printTask.url,
{async:!1});else throw this.log("no print task configured"),"no print task configured";}});d("js.LGFetchPrintedMap",[js.LGObject,js.LGMapDependency],{constructor:function(){this.fetchPrintUrl=null;this.printAvailabilityTimeoutMinutes=this.toNumber(this.printAvailabilityTimeoutMinutes,10);this.printTimeouter=null;this.setUpWaitForDependency("js.LGFetchPrintedMap")},onDependencyReady:function(){var a=this;this.subscribeToMessage(this.triggerPrintUrl,function(e){clearTimeout(a.printTimeouter);a.fetchPrintUrl=
e;a.publishMessage(a.publishPrintAvailable);0<a.printAvailabilityTimeoutMinutes&&(a.printTimeouter=setTimeout(function(){a.publishMessage(a.publishPrintNotAvailable)},6E4*a.printAvailabilityTimeoutMinutes))});this.subscribeToMessage(this.trigger,function(){null!==a.fetchPrintUrl&&a.publishMessage(a.publish,a.fetchPrintUrl)})}});d("js.LGLocate",js.LGObject,{constructor:function(){var a=this,e;this.ready=new n;Modernizr.geolocation?(this.subscribeToMessage(this.trigger,function(){e=setTimeout(function(){alert(a.checkForSubstitution("@messages.geolocationTimeout"))},
16E3);navigator.geolocation.getCurrentPosition(function(k){clearTimeout(e);a.log("go to "+k.coords.latitude+" "+k.coords.longitude);a.publishMessage(a.publish,new esri.geometry.Point(k.coords.longitude,k.coords.latitude,new esri.SpatialReference({wkid:4326})))},function(k){clearTimeout(e);switch(k.code){case k.PERMISSION_DENIED:k=a.checkForSubstitution("@messages.geolocationDenied");break;case k.TIMEOUT:k=a.checkForSubstitution("@messages.geolocationTimeout");break;default:k=a.checkForSubstitution("@messages.geolocationUnavailable")}alert(k)},
{timeout:8E3})}),this.ready.resolve(a)):this.ready.reject(a)}});d("js.LGSearch",js.LGObject,{constructor:function(){this.busyIndicator&&(this.busyIndicator=this.lgById(this.busyIndicator))},search:function(){return null},toList:function(){return[]},publish:function(a,e){this.publishMessage(a,e)},sortByLabel:function(a,e){var k=0;a&&e&&a.label&&e.label&&(k=a.label.localeCompare(e.label));return k},getRepresentativePoint:function(a){var e;"point"===a.type?e=a:"polygon"===a.type?(e=a.getExtent().getCenter(),
a.contains(e)||(e=a.getPoint(0,0))):"polyline"===a.type&&(e=a.getPoint(0,0));return e}});d("js.LGSearchAddress",[js.LGSearch,js.LGMapDependency],{constructor:function(){this.searcher=new D(this.searchUrl);this.searcher.outSpatialReference=new esri.SpatialReference({wkid:this.outWkid});this.params={};this.params.outFields=this.outFields;this.ready=new n;this.setUpWaitForDependency("js.LGSearchAddress")},onDependencyReady:function(){this.params.searchExtent=this.appConfig.map.extent;this.ready.resolve(this);
this.inherited(arguments)},search:function(a,e,k){this.params.address={};this.params.address[this.addressParamName]=a;this.searcher.addressToLocations(this.params,e,k)},toList:function(a){var e,k=this,b=[];a&&h.forEach(a,function(a){e=!1;a.score>=k.minimumScore&&(k.validLocators?h.some(k.validLocators,function(k){if(a.attributes.Loc_name===k)return e=!0}):e=!0);e&&b.push({label:a.address,data:new esri.geometry.Point(a.location.x,a.location.y,new esri.SpatialReference({wkid:102100}))})});return b},
publish:function(a,e){this.publishMessage(a,e)}});d("js.LGSearchFeatureLayer",[js.LGSearch,js.LGMapDependency],{constructor:function(){if(!this.searchPattern||0>this.searchPattern.indexOf("${1}"))this.searchPattern="%${1}%";this.caseInsensitiveSearch=this.toBoolean(this.caseInsensitiveSearch,!0);this.ready=new n;this.displayField=this.displayField?this.displayField.split(",")[0].trim():"";this.setUpWaitForDependency("js.LGSearchFeatureLayer")},onDependencyReady:function(){var a,e,k,b=",",c,g=this,
f=[],d;if(this.searchLayerName)try{if((a=this.mapObj.getLayer(this.searchLayerName))&&a.url&&a.resourceInfo&&a.resourceInfo.fields){this.searchURL=a.url;h.forEach(a.resourceInfo.fields,function(a){b+=a.name+","});this.searchFields&&0<this.searchFields.length?(k=this.searchFields.split(","),this.searchFields=[],h.forEach(k,function(a){g.searchFields.push(a.trim())}),h.forEach(this.searchFields,function(a){0<=b.indexOf(","+a+",")&&f.push(a)})):this.searchFields=[];if(0===f.length){this.showSearchLayerFieldError(this.searchFields,
this.searchLayerName,a);this.ready.reject(this);this.inherited(arguments);return}""!==this.displayField&&0>b.indexOf(","+this.displayField+",")&&(this.showSearchLayerFieldError([this.displayField],this.searchLayerName,a),this.displayField="");this.searchFields=f;this.objectIdField="ObjectID";a.resourceInfo&&a.resourceInfo.objectIdField?this.objectIdField=a.resourceInfo.objectIdField:a.layerObject&&a.layerObject.objectIdField&&(this.objectIdField=a.layerObject.objectIdField);this.publishPointsOnly=
"boolean"===typeof this.publishPointsOnly?this.publishPointsOnly:!0;this.searcher=new I(this.searchURL);this.generalSearchParams=new x;this.generalSearchParams.returnGeometry=!1;this.generalSearchParams.outSpatialReference=this.appConfig.map.spatialReference;d=[this.objectIdField];""!==this.displayField&&(d=d.concat(this.displayField));this.generalSearchParams.outFields=d.concat(this.searchFields);this.objectSearchParams=new x;this.objectSearchParams.returnGeometry=!0;this.objectSearchParams.outSpatialReference=
this.appConfig.map.spatialReference;this.objectSearchParams.outFields=["*"];c=this.appConfig.itemInfo.itemData.operationalLayers;h.some(c,function(a){return a.title===g.searchLayerName?(g.layer=a,g.popupTemplate=new J(a.popupInfo),!0):!1});this.log("Search layer "+this.searchLayerName+" set up for queries");this.ready.resolve(this);this.inherited(arguments);return}}catch(s){e=s.toString()}this.showSearchLayerError(this.searchLayerName,e);this.ready.reject(this);this.inherited(arguments)},isSearchableLayer:function(a){var e=
!1;(a=this.mapObj.getLayer(a))&&a.url&&a.resourceInfo&&a.resourceInfo.fields&&(e=!0);return e},showSearchLayerError:function(a,e){var k,b=this;k='"'+(a||"")+'"<br>';this.mapObj.getLayer(a)&&!this.isSearchableLayer(a)?k+=this.checkForSubstitution("@messages.searchLayerNotSearchable"):(e||(e=this.checkForSubstitution("@messages.searchLayerMissing")),k+=e);k+="<br><hr>"+this.checkForSubstitution("@prompts.mapLayers")+"<br><ul>";h.forEach(this.mapObj.getLayerNameList(),function(a){b.isSearchableLayer(a)&&
(k+='<li>"'+a+'"</li>')});k+="</ul>";this.log(k,!0)},showSearchLayerFieldError:function(a,e,k){var b="",c;k.resourceInfo&&k.resourceInfo.fields?(h.forEach(a,function(a){0<b.length&&(b+=",");b+=a}),c='"'+b+'"<br>',c=1<a.length?c+this.checkForSubstitution("@messages.allSearchFieldsMissing"):c+this.checkForSubstitution("@messages.searchFieldMissing"),c+='<br><hr>"'+e+'"<br>',c+=this.checkForSubstitution("@prompts.layerFields")+"<br><ul>",h.forEach(k.resourceInfo.fields,function(a){c+='<li>"'+a.name+
'"</li>'}),c+="</ul>",this.log(c,!0)):this.showSearchLayerError(e)},search:function(a,e,b){var c,g="",f,d="";!0===this.caseInsensitiveSearch?(c=a.toUpperCase(),f="UPPER(${0}) LIKE N'"+this.searchPattern+"'"):(c=a,f="${0} LIKE N'"+this.searchPattern+"'");c=c.replace(/'/g,"''");h.forEach(this.searchFields,function(a){g=g+d+v.substitute(f,[a,c]);d="  OR  "});0<g.length&&(this.generalSearchParams.where=g,this.searcher.execute(this.generalSearchParams,e,b))},toList:function(a,e){var b=this,c=[],g,f,d=
e.toUpperCase();a&&a.features&&0<a.features.length&&(h.forEach(a.features,function(a){f="";a.attributes[b.displayField]?f=a.attributes[b.displayField].toString():h.some(b.searchFields,function(e){return a.attributes[e]&&(g=a.attributes[e].toString(),0<=g.toUpperCase().indexOf(d))?(f=g,!0):!1});""===f&&(f="result");c.push({label:f,data:a.attributes[b.objectIdField]})}),c.sort(b.sortByLabel));return c},publish:function(a,e){var b,c,g=this;this.busyIndicator&&this.busyIndicator.setIsVisible(!0);this.objectSearchParams.where=
this.objectIdField+"="+e;this.layer.layerObject.queryFeatures(this.objectSearchParams,function(e){e&&e.features&&0<e.features.length?(b=e.features[0],b.infoTemplate=g.popupTemplate,b._graphicsLayer=g.layer.layerObject,c=g.publishPointsOnly?g.getRepresentativePoint(b.geometry):b,g.publishMessage(a,c)):g.log("LGSearchFeatureLayer_1: no results");g.busyIndicator&&g.busyIndicator.setIsVisible(!1)},function(a){g.log("LGSearchFeatureLayer_2: "+a.message);g.busyIndicator&&g.busyIndicator.setIsVisible(!1)})}});
d("js.LGSearchMultiplexer",js.LGSearch,{constructor:function(){var a=this,e;this.ready=new n;e=this.createSearchersList();(new q(e)).then(function(e){h.every(e,function(a){return a[0]})?a.ready.resolve(a):a.ready.reject(a)})},createSearchersList:function(){var a=this,e=[];this.searchers=[];this.searchers=[];this.searcherNames&&h.forEach(this.searcherNames,function(b){if(b=a.lgById(b))a.searchers.push(b),e.push(b.ready)});return e},search:function(a,e,b){var c=[],g=[];h.forEach(this.searchers,function(e,
b){var k=new n;g.push(k);e.search(a,function(g){g=e.toList(g,a);g=h.map(g,function(a){return{data:{iSearcher:b,itemData:a.data},label:a.label}});c=c.concat(g);k.resolve()},function(a){k.reject(a)})});(new q(g)).then(function(a){var g=!0;b&&(g=!h.some(a,function(a){return a[0]?!1:(b(a[1]),!0)}));g&&e&&e(c)})},toList:function(a){return a},publish:function(a,e){this.searchers[e.iSearcher].publish(a,e.itemData)}});d("js.LGSearchFeatureLayerMultiplexer",[js.LGSearchMultiplexer,js.LGMapDependency],{constructor:function(){this.setUpWaitForDependency("js.LGSearchFeatureLayerMultiplexer")},
createSearchersList:function(){var a=[],e=[],b=[],c,g;this.searchers=[];this.searchLayerName&&(e=this.searchLayerName.split(","));this.displayFields&&(b=this.displayFields.split(","));for(c=0;c<e.length;c+=1)g=this.rootId+"_"+this.searchers.length,g=new js.LGSearchFeatureLayer({appConfig:this.appConfig,rootId:g,parentDiv:this.parentDiv,dependencyId:this.dependencyId,busyIndicator:this.busyIndicator,publishPointsOnly:this.publishPointsOnly,searchPattern:this.searchPattern,caseInsensitiveSearch:this.caseInsensitiveSearch,
searchLayerName:e[c].trim(),searchFields:this.searchFields,displayField:b[c]}),this.searchers.push(g),a.push(g.ready);return a},onDependencyReady:function(){0===this.searchers.length&&this.showSearchLayerError("")},isSearchableLayer:function(a){var e=!1;(a=this.mapObj.getLayer(a))&&a.url&&a.resourceInfo&&a.resourceInfo.fields&&(e=!0);return e},showSearchLayerError:function(a,e){var b,c=this;b='"'+(a||"")+'"<br>';this.mapObj.getLayer(a)&&!this.isSearchableLayer(a)?b+=this.checkForSubstitution("@messages.searchLayerNotSearchable"):
(e||(e=this.checkForSubstitution("@messages.searchLayerMissing")),b+=e);b+="<br><hr>"+this.checkForSubstitution("@prompts.mapLayers")+"<br><ul>";h.forEach(this.mapObj.getLayerNameList(),function(a){c.isSearchableLayer(a)&&(b+='<li>"'+a+'"</li>')});b+="</ul>";this.log(b,!0)}});d("js.LGSearchBoxByText",js.LGDropdownBox,{constructor:function(){var a=this,e,c,f,d,h;e=this.rootId+"_entry";l.create("label",{"for":e,innerHTML:this.checkForSubstitution(this.showPrompt)},this.rootId);this.searchEntryTextBox=
(new g({id:e,value:"",trim:!0,placeHolder:this.hint,intermediateChanges:!0})).placeAt(this.rootId);b.set(this.searchEntryTextBox.domNode,"width","99%");this.prepareResultsBox();c=this.lgById(this.searcher);f="";d=0;h=null;m(this.searchEntryTextBox,"change",function(){var b=a.searchEntryTextBox.get("value");f!==b&&(f=b,a.clearResultsBox(),clearTimeout(h),0<b.length&&(h=setTimeout(function(){var e,g;a.showSearchingBusy();e=d=(new Date).getTime();c.search(b,function(f){e<d||(a.hideSearchingBusy(),f=
c.toList(f,b),g=(new Date).getTime(),a.log("retd "+f.length+" items in "+(g-e)/1E3+" secs"),0<f.length&&a.showResults(c,f))},function(b){a.log("LGSearchBoxByText_1: "+b.message);f="";a.hideSearchingBusy()})},1E3)))})},prepareResultsBox:function(){var a,b;a=l.create("div",{className:this.resultsListBoxClass},this.rootId);b=l.create("table",{className:this.resultsListTableClass},a);this.tableBody=l.create("tbody",{className:this.resultsListBodyClass},b);touchScroll(a)},clearResultsBox:function(){l.empty(this.tableBody)},
showSearchingBusy:function(){var a=l.create("tr",null,this.tableBody);l.create("td",{className:this.resultsListSearchingClass},a)},hideSearchingBusy:function(){l.empty(this.tableBody)},showResults:function(a,b){var c=this;h.forEach(b,function(b){var e;e=l.create("tr",null,c.tableBody);e=l.create("td",{className:c.resultsListEntryClass,innerHTML:b.label},e);c.applyTheme(!0,e);m(e,"click",function(){a.publish(c.publish,b.data)})})},toggleVisibility:function(){this.inherited(arguments);this.getIsVisible()&&
this.searchEntryTextBox.focus()}});d("js.LGSearchBoxByTextGrid",js.LGSearchBoxByText,{constructor:function(){},prepareResultsBox:function(){var a,b;a=d([z,w]);b=l.create("div",{className:this.resultsListBoxClass,style:{overflow:"none"}},this.rootId);t.getMarginBox(b);b=l.create("div",{style:{width:"198px",height:"172px"}},b);this.grid=new a({columns:{col1:"",col2:""},selectionMode:"single"},b)},clearResultsBox:function(){this.rowClick&&(this.rowClick.remove(),this.rowClick=null);this.grid.refresh();
this.grid.renderArray([])},showSearchingBusy:function(){console.log("searching...")},hideSearchingBusy:function(){console.log("search done")},showResults:function(a,b){var c=this,g=[],f;this.rowClick=this.grid.on(".dgrid-row:click",function(b){b=c.grid.row(b);a.publish(c.publish,b.data.data)});f=1;h.forEach(b,function(a){var b={};b.col1=f.toString();++f;b.col2=a.label;b.data=a.data;g.push(b)});this.grid.refresh();this.grid.renderArray(g);this.grid.set("sort","col1",!1)}});d("js.LGShare",js.LGObject,
{constructor:function(){var a=this;this.busyIndicator&&(this.busyIndicator=this.lgById(this.busyIndicator));this.subscribeToMessage(this.trigger,function(){a.share()})},share:function(){var a=this,b,c;b=encodeURIComponent(this.getSubject())||"%20";c=encodeURIComponent(this.getUrlToShare());this.tinyURLServiceURL&&0<this.tinyURLServiceURL.length?(this.busyIndicator&&this.busyIndicator.setIsVisible(!0),c=esri.substitute({url:c},this.tinyURLServiceURL),esri.request({url:c,handleAs:"json"},{useProxy:!1}).then(function(c){var g,
f;try{if(g=a.followAttributePath(c,a.tinyURLResponseAttribute))f=esri.substitute({subject:b,url:g},a.shareUrl),a.publishMessage(a.publish,f)}catch(k){a.log("LGShare_1: "+k.toString())}a.busyIndicator&&a.busyIndicator.setIsVisible(!1)},function(b){a.log("LGShare_2: "+b.toString());a.busyIndicator&&a.busyIndicator.setIsVisible(!1)})):(c=esri.substitute({subject:b,url:c},this.shareUrl),this.publishMessage(this.publish,c))},getSubject:function(){return""},getUrlToShare:function(){return this.getAppUrl()},
getAppUrl:function(){return window.location.toString()}});d("js.LGShareAppExtents",[js.LGShare,js.LGMapDependency],{constructor:function(){this.setUpWaitForDependency("js.LGShareAppExtents")},getSubject:function(){var a="";this.subject&&(a=this.checkForSubstitution(this.subject));return a},getUrlToShare:function(){var a=this.removeMapExtentsArg(this.getAppUrl());return a+(0>a.indexOf("?")?"?":"&")+this.getMapExtentsArg()},removeMapExtentsArg:function(a){var b,c,g;b=a.split("?",2);if(1===b.length)return a;
for(c="&"+b[1]+"&";;){a=c.indexOf("&ex=");if(0>a)break;g=c.indexOf("&",a+1);c=c.substring(0,a)+c.substring(g)}a=b[0];2<c.length&&(a+="?"+c.substring(1,c.length-1));return a},getMapExtentsArg:function(){return"ex="+this.mapObj.getMapExtentsAsString()}});d("js.LGFilterLayers1",js.LGMapBasedMenuBox,{constructor:function(){this.layers=[];this.switchDelayTimer=null;this.busyIndicator&&(this.busyIndicator=this.lgById(this.busyIndicator));this.switchDelayTimer=null;this.switchDelaySecs=1E3*this.toNumber(this.nonieSwitchDelaySecs,
1.5);this.switchDelayMultiplier=1;this.setUpWaitForDependency("js.LGFilterLayers1")},onDependencyReady:function(){var a;this.fieldname1&&(h.forEach(this.appConfig.itemInfo.itemData.operationalLayers,c.hitch(this,function(a){var b;if(a.layerObject&&"Feature Layer"===a.layerObject.type)for(b=0;b<a.layerObject.fields.length;b+=1)if(a.layerObject.fields[b].name===this.fieldname1){a={layerObject:a.layerObject,fieldType:a.layerObject.fields[b].type};this.layers.push(a);break}})),l.create("label",{innerHTML:this.hint1},
l.create("div",{},this.rootId)),a=(new g({id:this.rootId+"_field1",value:this.value1,trim:!0,placeHolder:this.hint1,intermediateChanges:!0})).placeAt(this.rootId),b.set(a.domNode,"width","99%"),this.tooltip&&a.set("title",this.checkForSubstitution(this.tooltip)),m(a,"change",c.hitch(this,function(){this.value1=a.value;this.onValueChanged()})));0===this.layers.length?(this.setShowable(!1),this.showFieldError(this.fieldname1)):this.applyFilter()},showFieldError:function(a){var b;b='"'+a+'"<br>';b+=
this.checkForSubstitution("@messages.fieldNotFound")+"<br><hr>";b+=this.checkForSubstitution("@prompts.mapLayers")+"<br><ul>";h.forEach(this.appConfig.itemInfo.itemData.operationalLayers,c.hitch(this,function(a){var c;if(a.layerObject&&"Feature Layer"===a.layerObject.type){b+='<li>"'+a.title+'"<ul>';for(c=0;c<a.layerObject.fields.length;c+=1)b+='<li>"'+a.layerObject.fields[c].name+'"</li>';b+="</ul></li>"}}));b+="</ul>";this.log(b,!0)},onValueChanged:function(){this.applyFilter()},applyFilter:function(){var a=
this;this.busyIndicator&&this.busyIndicator.setIsVisible(!0);null!==this.switchDelayTimer&&clearTimeout(this.switchDelayTimer);this.switchDelayTimer=setTimeout(function(){a.switchDelayTimer=null;a.applyFilterCore();a.busyIndicator&&a.busyIndicator.setIsVisible(!1)},this.switchDelaySecs*this.switchDelayMultiplier);this.switchDelayMultiplier=1},applyFilterCore:function(){h.forEach(this.layers,c.hitch(this,function(a){this.setLayerDefinitionExpression(a.layerObject,a.fieldType);a.layerObject.clearSelection()}))},
setLayerDefinitionExpression:function(a,b){var c=a.defaultDefinitionExpression;try{this.value1&&""!==this.value1&&("esriFieldTypeString"===b?c=v.substitute(this.defnExpression,{fieldname1:this.fieldname1,value1:"'"+this.value1+"'"}):"esriFieldTypeInteger"===b&&(c=v.substitute(this.defnExpression,{fieldname1:this.fieldname1,value1:this.value1}))),a.setDefinitionExpression(c)}catch(g){}}});d("js.LGFilterLayers1WithDefaults",[js.LGFilterLayers1,js.LGDefaults],{constructor:function(){this.changeDefaults();
this.setUpWaitForDependency("js.LGFilterLayers1WithDefaults")},onValueChanged:function(){this.inherited(arguments);this.changeDefaults()},changeDefaults:function(){this.defaultValues.value1=this.value1;this.defaultValues.fieldname1=this.fieldname1;this.inherited(arguments)}})})},"js/lgonlineDijit":function(){define(["dojo/_base/declare","dojo/Deferred","dojo/dom-construct","js/lgonlineMap"],function(d,l,r){d("js.LGMapDijitContainer",[js.LGGraphic,js.LGMapDependency],{constructor:function(){this.ready=
new l;this.setUpWaitForDependency("js.LGMapDijitContainer")},onDependencyReady:function(){this.createDijit()},createDijit:function(){var d=this;require([this.dijitAmd],function(l){d.dijit=(new l({map:d.appConfig.map},r.create("div",null,d.rootDiv))).startup();d.ready.resolve(d)})}})})},"js/lgonlineDrawing":function(){define("dojo/_base/declare dojo/Deferred dojo/_base/Color dojo/on esri/lang esri/graphic esri/symbols/SimpleLineSymbol esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleFillSymbol js/lgonlineMap".split(" "),
function(d,l,r,m,t,n,q,b,p){d("js.LGHighlighter",[js.LGObject,js.LGMapDependency],{constructor:function(){this.showFeaturePopup=this.toBoolean(this.showFeaturePopup,!0);this.setUpWaitForDependency("js.LGHighlighter")},onDependencyReady:function(){var b=this;this.highlighterLayer=b.mapObj.createGraphicsLayer("highlighterLayer");this.lineHiliteColor=new r(this.lineHiliteColor||"#0000ff");this.fillHiliteColor=new r(this.fillHiliteColor||[0,0,255,.1]);this.concentricCircleFillColor=new r([0,0,0,0]);this.intervalID=
this.intervalTerminator=null;this.subscribeToMessage("highlightItem",function(c){var f,d;c&&(d=c.geometry||c,f=(f=d.getExtent())?f.getCenter():d,d=b.createHighlightGraphics(d,c.attributes,c.infoTemplate),0<d.length&&b.showHighlight(d,f,b.highlightZoomLevel,t.isDefined(c.attributes)&&t.isDefined(c.infoTemplate)&&b.showFeaturePopup,c))});this.appConfig.map.infoWindow&&m(this.appConfig.map.infoWindow,"hide",function(){b.highlighterLayer.clear()});this.showFeaturePopup||this.appConfig.map.infoWindow&&
m(this.appConfig.map.infoWindow,"show",function(){b.highlighterLayer.clear()})},createHighlightGraphics:function(d,c,f){var l,g=[];if("polyline"===d.type)g.push(new n(d,new q(esri.symbol.SimpleLineSymbol.STYLE_SOLID,this.lineHiliteColor,3),c,f));else if("point"===d.type){if(!d.x||!d.y||isNaN(d.x)||isNaN(d.y))return g;for(l=0;4>=l;++l)g.push(new n(d,new b(b.STYLE_CIRCLE,2.5*(l+16),new q(q.STYLE_SOLID,this.lineHiliteColor,3),this.concentricCircleFillColor),c,f))}else d.type&&g.push(new esri.Graphic(d,
new p(p.STYLE_SOLID,new q(q.STYLE_SOLID,this.lineHiliteColor,3),this.fillHiliteColor),c,f));return g},showHighlight:function(b,c,f,d,g){var s,u,p,q,m=this;c?s=this.mapObj.centerAt(c):(s=new l,s.resolve());s.then(function(){f?u=m.mapObj.setZoom(f):(u=new l,u.resolve());u.then(function(){m.intervalTerminator&&(clearTimeout(m.intervalTerminator),clearInterval(m.intervalID));m.mapObj.hidePopup();1<b.length?(p=0,q=!0,m.intervalID=setInterval(function(){m.highlighterLayer.clear();m.highlighterLayer.add(b[p]);
q?++p:--p;p===b.length?(q=!1,--p):0>p&&(q=!0,p=0)},120),m.intervalTerminator=setTimeout(function(){clearInterval(m.intervalID);m.intervalTerminator=null;m.intervalID=null;m.highlighterLayer.clear()},5E3)):m.highlighterLayer.add(b[0]);d&&m.mapObj.showPopupWithFeature(c,g)})})}})})},"js/lgonlineEditing":function(){define("dojo/_base/declare dojo/dom dojo/dom-construct dojo/_base/array dojo/_base/lang dojo/_base/Color dojo/aspect esri/dijit/editing/TemplatePicker esri/dijit/editing/Editor esri/toolbars/draw esri/graphic js/lgonlineBase js/lgonlineMap js/lgonlineCommand".split(" "),
function(d,l,r,m,t,n,q,b,p,h,c){d("js.LGEditTemplatePicker",js.LGMapBasedMenuBox,{constructor:function(){var b;b=l.byId(this.colorizerId).getLGObject();b=".templatePicker{border:1px solid transparent!important;}.templatePicker .dojoxGrid{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridScrollbox{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridRow{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridCell{border:1px solid transparent}.templatePicker .dojoxGrid .dojoxGridRow{border:1px solid transparent}.templatePicker .grid .dojoxGridRowOver{background-color:transparent;color:inherit;}.templatePicker .grid .dojoxGridRowOver .dojoxGridCell{background-color:transparent;color:inherit;}.templatePicker .dojoxGrid .dojoxGridCellFocus{border:1px solid transparent!important;}.templatePicker .dojoxGrid .dojoxGridRowOdd{background-color:transparent;}.templatePicker .dojoxGrid .selectedItem{border:1px solid transparent!important;color:"+
b.foregroundColor()+"!important;background-color:"+b.alternateBackgroundColor()+"!important}";this.injectCSS(b);this.setUpWaitForDependency("js.LGEditTemplatePicker")},onDependencyReady:function(){var b,c,g,d=!0;this.appConfig.userPrivileges&&(d=!1,m.some(this.appConfig.userPrivileges,function(b){return"features:user:edit"===b?d=!0:!1}));d?(b=this.appConfig.itemInfo.itemData.operationalLayers,this.layerInfos=[],this.layers=[],m.forEach(b,t.hitch(this,function(b){var d,f=b.layerObject;f instanceof
esri.layers.FeatureLayer&&f.isEditable()&&!(null!==b.capabilities&&"Query"===b.capabilities||null!==f.capabilities&&"Query"===f.capabilities)&&(g={featureLayer:f},c=null,b.popupInfo&&b.popupInfo.fieldInfos?c=b.popupInfo.fieldInfos:f.infoTemplate&&f.infoTemplate.info&&f.infoTemplate.info.fieldInfos&&(c=f.infoTemplate.info.fieldInfos),c&&(d=[],m.forEach(c,function(b){b.visible&&d.push(b)}),g.fieldInfos=d),this.layerInfos.push(g),this.layers.push(f))})),0===this.layers.length?this.setShowable(!1):(this.templatePickerHolder=
r.create("div",{className:this.templatePickerHolderClass}),r.place(this.templatePickerHolder,this.rootId),touchScroll(this.templatePickerHolder))):this.setShowable(!1);this.inherited(arguments)},createEditor:function(){var c=this,d,g;this.templatePickerHolder&&(this.setIsVisible(!0,!0),d=r.create("div"),r.place(d,this.templatePickerHolder),g=new b({featureLayers:this.layers,rows:"auto",columns:2,grouping:!0},d),g.startup(),this.setIsVisible(!1,!1),d=r.create("div"),r.place(d,this.templatePickerHolder),
g={map:this.appConfig.map,templatePicker:g,toolbarVisible:!1,layerInfos:this.layerInfos},this.editor=new p({settings:g},d),this.editor.startup(),q.before(this.editor,"_applyEdits",function(b){m.forEach(b,function(b){b.adds&&c.preprocessEditAdds(b);b.updates&&c.preprocessEditUpdates(b);b.deletes&&c.preprocessEditDeletes(b)})}),this.mapObj.disablePopups())},destroyEditor:function(){this.editor&&(this.editor.destroy(),this.editor=null,this.mapObj.enablePopups())},show:function(){this.createEditor();
this.inherited(arguments)},hide:function(){this.destroyEditor();this.inherited(arguments)},preprocessEditAdds:function(b){return b},preprocessEditUpdates:function(b){return b},preprocessEditDeletes:function(b){return b}});d("js.LGEditTemplatePickerWithDefaults",[js.LGEditTemplatePicker,js.LGDefaults],{constructor:function(){this.changeDefaults();this.setUpWaitForDependency("js.LGEditTemplatePickerWithDefaults")},preprocessEditAdds:function(b){b.adds[0].attributes[this.defaultValues.fieldname1]=this.defaultValues.value1;
return b}});d("js.LGFeatureByClick",[js.LGObject,js.LGMapDependency],{constructor:function(){this.setUpWaitForDependency("js.LGFeatureByClick")},onDependencyReady:function(){var b=this;this.inherited(arguments);this.clickHandle=this.subscribeToMessage("mapClick",function(c){b.handleClick(c)})},handleClick:function(){return null}});d("js.LGAddFeatureByClick",js.LGFeatureByClick,{constructor:function(){this.setUpWaitForDependency("js.LGAddFeatureByClick")},onDependencyReady:function(){this.inherited(arguments);
esri.bundle.toolbars.draw.addPoint=this.checkForSubstitution("@tooltips.collect");this.drawingToolbar=new h(this.appConfig.map,{});this.drawingToolbarActive=!1;this.drawingToolbar.on("draw-end",t.hitch(this,this.handleDrawEnd))},handleClick:function(b){this.drawingToolbarActive||(this.drawingToolbarActive=!0,this.drawingToolbar.activate(h.POINT),this.drawingToolbar._updateTooltip(b))},handleDrawEnd:function(b){var d=this,g;this.drawingToolbarActive=!1;this.drawingToolbar.deactivate();g=new c(b.geometry,
new esri.symbol.SimpleMarkerSymbol(esri.symbol.SimpleMarkerSymbol.STYLE_SQUARE,10,new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,new n([255,0,0]),1),new n([0,255,0,.25])));this.appConfig.map.graphics.add(g);setTimeout(function(){alert(d.checkForSubstitution("@messages.yourContentSubmitted"));d.appConfig.map.graphics.remove(g)},2E3)}})})},"js/lgonlineFrame":function(){define("dojo/_base/declare dojo/dom-construct dojo/on dojo/dom-geometry dojo/dom-style dojo/_base/array dojo/_base/lang js/lgonlineBase".split(" "),
function(d,l,r,m,t,n,q){d("js.LGColorizer",js.LGObject,{constructor:function(){var b,d="",h=this,c=["#fff","#333333","#5d5d5d","#5d5d5d"];this.colors=[];n.some(this.colorTable,function(b){return h.theme===b.theme?(h.colors=b.colors,!0):!1});if(this.colors.length<c.length)for(b=this.colors.length;b<c.length;b+=1)this.colors.push(c[b]);d+=".appTheme{color:"+this.colors[0]+";background-color:"+this.colors[1]+"}";d+=".appTheme2{color:"+this.colors[0]+";background-color:"+this.colors[3]+"}";d+=".appThemeHover:hover{background-color:"+
this.colors[2]+"}";this.injectCSS(d)},foregroundColor:function(){return this.colors[0]},backgroundColor:function(){return this.colors[1]},hoverColor:function(){return this.colors[2]},alternateBackgroundColor:function(){return this.colors[3]}});d("js.LGFrame",js.LGGraphic,{constructor:function(){var b;b={};this.headerDivId&&(b.id=this.headerDivId);this.headerDivClass&&(b.className=this.headerDivClass);this.headerDiv=l.create("div",b,this.rootDiv);this.applyTheme(!1,this.headerDiv);b={};this.contentDivId&&
(b.id=this.contentDivId);this.contentDivClass&&(b.className=this.contentDivClass);this.contentDiv=l.create("div",b,this.rootDiv);this.handleWindowResize()},handleWindowResize:function(){this.inherited(arguments);this.resizeContentDiv()},resizeContentDiv:function(){var b,d,h;this.headerDiv&&this.contentDiv&&(b=m.getMarginBox(this.rootDiv),d=m.getMarginBox(this.headerDiv),h=b.h-d.h,0<h&&(h={},h.top=d.h+"px",h.height=b.h-d.h+"px",t.set(this.contentDiv,h)))}});d("js.LGGallery",js.LGGraphic,{constructor:function(){var b,
d=this;b=l.create("table",null,this.rootDiv);this.applyTheme(!1,b);r(window,"resize",q.hitch(this,this.handleParentResize));this.rootDiv.getContentDiv=function(){return d.addItem()};b=l.create("tbody",null,b);this.galleryRow=l.create("tr",null,b);b={innerHTML:"&lt;",style:{visibility:"hidden"}};this.arrowClass&&(b.className=this.arrowClass);this.leftArrow=l.create("td",b,this.galleryRow);this.applyTheme(!0,this.leftArrow);r(this.leftArrow,"click",q.hitch(this,this.shiftLeft));b.innerHTML="&gt;";this.rightArrow=
l.create("td",b,this.galleryRow);this.applyTheme(!0,this.rightArrow);r(this.rightArrow,"click",q.hitch(this,this.shiftRight));this.zeroItemWidth=m.getMarginBox(this.rootDiv).w;this.numItemsToDisplay=this.iFirstItem=this.numItems=this.itemWidth=0;this.firstItem=null;this.handleParentResize()},addItem:function(b){var d;d={};"string"===typeof b&&(d.innerHTML=b);this.itemClass&&(d.className=this.itemClass);d=l.create("td",d);"string"!==typeof b&&d.appendChild(b);this.galleryRow.insertBefore(d,this.rightArrow);
this.numItems+=1;this.firstItem||(this.firstItem=d,this.itemWidth=m.getMarginBox(d).w);this.handleParentResize();return d},clearItems:function(){for(;2<this.galleryRow.childNodes.length;)this.galleryRow.removeChild(this.galleryRow.childNodes[1]);this.numItemsToDisplay=this.iFirstItem=this.numItems=0;this.firstItem=null;this.handleParentResize()},handleParentResize:function(){var b,d;0===this.zeroItemWidth&&(this.zeroItemWidth=m.getMarginBox(this.rootDiv).w);b=m.getMarginBox(this.rootDiv.parentNode).w;
d=this.zeroItemWidth+this.numItems*this.itemWidth;0!==this.numItems&&(d>b?(this.leftArrow.style.visibility="visible",this.rightArrow.style.visibility="visible",this.numItemsToDisplay=Math.max(Math.floor((b-this.zeroItemWidth)/this.itemWidth),1)):(this.leftArrow.style.visibility="hidden",this.rightArrow.style.visibility="hidden",this.numItemsToDisplay=this.numItems),this.iFirstItem=Math.min(this.iFirstItem,this.numItems-this.numItemsToDisplay),this.drawGallery())},shiftLeft:function(){this.iFirstItem=
Math.min(this.iFirstItem+1,this.numItems-this.numItemsToDisplay);this.drawGallery()},shiftRight:function(){this.iFirstItem=Math.max(this.iFirstItem-1,0);this.drawGallery()},drawGallery:function(){var b,d=this.iFirstItem,h=this.iFirstItem+this.numItemsToDisplay,c=this.firstItem;this.leftArrow.style.visibility="hidden";this.rightArrow.style.visibility="hidden";for(b=0;b<d;)this.rightArrow.style.visibility="visible",c.style.display="none",c=c.nextSibling,b+=1;for(;b<h;)c.style.display="",c=c.nextSibling,
b+=1;for(;b<this.numItems;)this.leftArrow.style.visibility="visible",c.style.display="none",c=c.nextSibling,b+=1;this.handleWindowResize()}});d("js.LGTitleBar",js.LGGraphic,{constructor:function(){var b;this.iconUrl&&0<this.iconUrl.length&&(b={src:this.iconUrl},this.iconClass&&(b.className=this.iconClass),l.create("img",b,this.rootDiv));this.title&&0<this.title.length&&(b={innerHTML:this.title},this.titleClass&&(b.className=this.titleClass),l.create("span",b,this.rootDiv),document.title=this.title);
this.handleWindowResize()}})})},"js/lgonlineMap":function(){define("dojo/_base/declare dojo/dom-construct dojo/dom dojo/on dojo/_base/lang dojo/_base/array dojo/Deferred dojo/dom-class dojo/dom-attr esri/arcgis/utils esri/dijit/Popup esri/layers/GraphicsLayer esri/tasks/ProjectParameters js/lgonlineBase".split(" "),function(d,l,r,m,t,n,q,b,p,h,c,f,v){d("js.LGMapDependency",js.LGDependency,{onDependencyPrep:function(b){this.mapObj=b;this.inherited(arguments)}});d("js.LGMap",js.LGGraphic,{constructor:function(c){var d=
null;c=null;var f=this,h,n;this.ready=new q;h=this.appConfig.map;n=h.extent;l.destroy(this.rootDiv);this.rootDiv=r.byId("mapDiv");l.place(this.rootDiv,this.parentDiv);b.add(this.rootDiv,this.rootClass);p.set(this.rootDiv,"id",this.rootId);this.rootDiv.getLGObject=function(){return f};this.handleWindowResize();h.resize(!0);h.reposition();if(this.xmin&&this.ymin&&this.xmax&&this.ymax)try{d={xmin:this.xmin,ymin:this.ymin,xmax:this.xmax,ymax:this.ymax,spatialReference:{}},d.spatialReference.wkid=this.wkid?
Number(this.wkid):102100,d=new esri.geometry.Extent(d)}catch(w){d=null}this.appConfig.ex&&(c=this.getExtentsFromString(this.appConfig.ex))&&(d=c);d?d.spatialReference.wkid!==h.spatialReference.wkid?esri.config.defaults.geometryService?(c=new v,c.geometries=[d],c.outSR=h.spatialReference,esri.config.defaults.geometryService.project(c).then(function(b){d=b[0];h.setExtent(d)})):this.log("LGMap_1: Need geometry service to convert extent from wkid "+d.spatialReference.wkid+" to map's "+h.spatialReference.wkid):
h.setExtent(d):h.setExtent(n);h.spatialReference||(h.spatialReference=new esri.SpatialReference(102100));m(window,"resize",t.hitch(this,function(){h.resize();h.reposition()}));this.tempGraphicsLayer=this.createGraphicsLayer("tempGraphicsLayer");this.positionHandle=this.subscribeToMessage("position",function(b){var c;b.spatialReference.wkid===f.appConfig.map.spatialReference.wkid?f.publishMessage("highlightItem",b):4326===b.spatialReference.wkid&&102100===f.appConfig.map.spatialReference.wkid?(b=esri.geometry.geographicToWebMercator(b),
f.publishMessage("highlightItem",b)):esri.config.defaults.geometryService?(c=new esri.tasks.ProjectParameters,c.geometries=[b],c.outSR=f.appConfig.map.spatialReference,esri.config.defaults.geometryService.project(c).then(function(c){b=c[0];f.publishMessage("highlightItem",b)})):f.log("LGMap_1: Need geometry service to convert position from wkid "+b.spatialReference.wkid+" to map's "+f.appConfig.map.spatialReference.wkid)});this.showFeatureHandle=this.subscribeToMessage("showFeature",function(b){f.publishMessage("highlightItem",
b)});this.clickHandle=m(h,"click",function(b){f.publishMessage("mapClick",b)});this.ready.resolve(this)},showPopupWithFeature:function(b,c){var d=this.appConfig.map.infoWindow;d.clearFeatures();d.setContent(c.getContent());d.show(b)},hidePopup:function(){this.appConfig.map.infoWindow.hide()},setExtent:function(b){return this.appConfig.map.setExtent(b)},centerAt:function(b){return this.appConfig.map.centerAt(b)},setZoom:function(b){var c=this.appConfig.map.getMinZoom(),d=this.appConfig.map.getMaxZoom();
0<=c&&0<=d&&(b=Math.max(c,Math.min(d,b)));return this.appConfig.map.setZoom(b)},getMapExtentsAsString:function(){var b="";this.appConfig.map&&(b=this.getStringFromExtents(this.appConfig.map.extent));return b},getStringFromExtents:function(b){var c=b.xmin.toFixed().toString()+","+b.ymin.toFixed().toString()+","+b.xmax.toFixed().toString()+","+b.ymax.toFixed().toString();(b=b.spatialReference)&&(b.wkid?c=c+","+b.wkid.toString():b.wkt&&(c=c+","+encodeURIComponent(b.wkt)));return c},getExtentsFromString:function(b){var c,
d=null,f,h;b instanceof Array&&(b=b[b.length-1]);c=b.split(",");1===c.length&&(h=b.indexOf("PROJCS"),0<h?(c=b.substr(0,h).split("%2C"),c[4]=b.substr(h)):c=b.split("%2C"));try{d={xmin:Number(c[0]),ymin:Number(c[1]),xmax:Number(c[2]),ymax:Number(c[3]),spatialReference:{}},5===c.length?(f=Number(c[4]),isNaN(f)?d.spatialReference.wkid=102100:d.spatialReference.wkid=f):5<c.length?d.spatialReference.wkt=c.slice(4).join(","):d.spatialReference.wkid=102100,d=new esri.geometry.Extent(d)}catch(l){d=null}return d},
getLayer:function(b){var c;n.some(this.appConfig.itemInfo.itemData.operationalLayers,function(d){return d.title===b?(c=d,!0):!1});return c},getLayerNameList:function(){var b=[];n.forEach(this.appConfig.itemInfo.itemData.operationalLayers,function(c){b.push(c.title)});return b},getOperationalLayers:function(){return this.appConfig.itemInfo.itemData.operationalLayers},createGraphicsLayer:function(b){var c=new f;c.id=b;m(c,"graphic-add",function(){c.disableMouseEvents()});return this.appConfig.map.addLayer(c)},
enablePopups:function(){this.appConfig.mapInfo.clickEventListener&&(this.appConfig.mapInfo.clickEventHandle=m(this.appConfig.map,"click",this.appConfig.mapInfo.clickEventListener))},disablePopups:function(){this.appConfig.mapInfo.clickEventHandle&&this.appConfig.mapInfo.clickEventHandle.remove()}})})},"js/lgonlineOutput":function(){define("dojo/_base/declare dojo/dom-construct dojo/dom-class dojo/_base/array dojo/_base/lang dojo/topic js/lgonlineBase".split(" "),function(d,l,r,m,t,n){d("js.LGNotes",
js.LGObject,{constructor:function(){console&&this.notes&&m.forEach(this.notes,function(d){console.log(d)})}});d("js.LGBusy",js.LGGraphic,{constructor:function(){this.busyImageClass&&r.add(this.rootDiv,this.busyImageClass)}});d("js.LGLogBox",js.LGDropdownBox,{constructor:function(){window.gLogMessageBox=this;touchScroll(this.rootDiv)},append:function(d){"string"===typeof d?l.create("div",{innerHTML:d,style:"margin:2px"},this.rootDiv):"object"===typeof d&&null!==d&&this.rootDiv.appendChild(d)}});d("js.LGMessageBox",
js.LGDropdownBox,{constructor:function(){this.content=this.content?this.checkForSubstitution(this.content):"";this.rootDiv.innerHTML=this.content;touchScroll(this.rootDiv)},setMessage:function(d){this.show();this.content=d;this.rootDiv.innerHTML=this.content}});d("js.LGSelfHidingMessageBox",js.LGMessageBox,{constructor:function(){this.timeoutSeconds=this.toNumber(this.timeoutSeconds,5)},setUpListeningForCommands:function(){},handleTrigger:function(){this.getIsVisible()||(this.pendingClosure&&(clearTimeout(this.pendingClosure),
this.pendingClosure=null),this.show(),this.pendingClosure=setTimeout(t.hitch(this,function(){this.hide();this.pendingClosure=null}),1E3*this.timeoutSeconds))}});d("js.LGPublishEcho",js.LGDropdownBox,{handleTrigger:function(d){this.rootDiv.innerHTML=d.toString();this.setIsVisible(!0)}});d("js.LGMessageWatch",js.LGObject,{constructor:function(){var d=this;n.subscribe("publish",function(b){d.showMessage("message from",b)});n.subscribe("receive",function(b){d.showMessage("received by",b)})},showMessage:function(d,
b){var l="";if(b.data)try{l=JSON.stringify(b.data)}catch(h){l="<data>"}this.log(d+" "+b.id+': "'+b.tag+'" '+(l||""))}})})}}});
