/* 
This source is a compressed form of part of the git commit 
50d28aa205a5aa4f 2013-11-22 14:29:36 -0800
Uncompressed source is available from https://github.com/Esri/local-government-online-apps 
*/ 
/*

 | ArcGIS Solutions
 | Version 10.2
 | Copyright 2012 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
*/
define("js/lgonlineApp","js/lgonlineBase js/lgonlineCommand js/lgonlineDrawing js/lgonlineEditing js/lgonlineFrame js/lgonlineMap js/lgonlineOutput".split(" "),function(){return{}});
require({cache:{"js/lgonlineBase":function(){define("js/lgonlineBase","dojo/dom-construct dojo/dom dojo/on dojo/dom-style dojo/dom-class dojo/_base/array dojo/topic dojo/_base/lang".split(" "),function(h,n,l,k,g,d,f,a){dojo.declare("js.LGObject",null,{constructor:function(b){var e,a,d=this;void 0!==b&&dojo.safeMixin(this,b);this.checkPrerequisites&&this.checkPrerequisites();b={};this.rootId&&(b.id=this.rootId);this.rootClass?b.className=this.rootClass:b.style="display:none";void 0!==this.parentDiv?
(e=this.parentDiv,(a=n.byId(e))||(e=null)):e=null;a&&a.getLGObject&&a.getLGObject().addItem?(this.rootDiv=h.create("div",b),a.getLGObject().addItem(this.rootDiv)):this.rootDiv=h.create("div",b,e);this.rootDiv.getLGObject=function(){return d}},getRootDiv:function(){return this.rootDiv},lgById:function(b){var e=null;(b=n.byId(b))&&b.getLGObject&&(e=b.getLGObject());return e},deleteDivFromDom:function(){this.rootDiv&&this.rootDiv.parentNode.removeChild(this.rootDiv)},injectCSS:function(b){var e;e=document.createElement("style");
e.setAttribute("type","text/css");e.styleSheet?e.styleSheet.cssText=b:(b=document.createTextNode(b),e.appendChild(b));document.body.appendChild(e);return e},checkForSubstitution:function(b){var e,a=b;b&&1<b.length&&(e=b.substring(0,1),"@"===e?this.i18n&&(a=this.followAttributePath(this.i18n,b.substring(1))):"."===e&&(a=this.followAttributePath(null,b.substring(1))));return a},followAttributePath:function(b,e){var a,d=b,f;try{f=e.split(".");for(a=0;a<f.length;a+=1)d=null===d?this.lgById(f[a]):d[f[a]]}catch(g){d=
null}return d},toBoolean:function(b,a){var d;if(!0===b)return!0;if(!1===b)return!1;if("string"===typeof b){d=b.toLowerCase();if("true"===d)return!0;if("false"===d)return!1}return void 0===a?!0:a},toNumber:function(b,a){if("number"===typeof b)return b;b=parseFloat(b);return!isNaN(b)?b:void 0===a?0:a},log:function(b,a){console&&console.log(b);a&&this.publishMessage("error",b);window.gLogMessageBox&&window.gLogMessageBox.append(b)},publishMessage:function(b,a){f.publish("publish",{id:this.rootId,tag:b,
data:a});f.publish(b,a)},subscribeToMessage:function(b,a){var d=this;f.subscribe(b,function(a){f.publish("receive",{id:d.rootId,tag:b,data:a})});f.subscribe(b,a)}});dojo.declare("js.LGGraphic",js.LGObject,{constructor:function(){l(window,"resize",a.hitch(this,this.handleWindowResize));this.handleWindowResize()},setIsVisible:function(b,a){a?(k.set(this.getRootDiv(),"display","block"),k.set(this.getRootDiv(),"visibility",b?"visible":"hidden")):(k.set(this.getRootDiv(),"display",b?"block":"none"),k.set(this.getRootDiv(),
"visibility","visible"))},getIsVisible:function(){return"none"!==k.get(this.getRootDiv(),"display")},toggleVisibility:function(){k.set(this.getRootDiv(),"display",this.getIsVisible()?"none":"block")},handleWindowResize:function(){void 0!==this.fill&&!0===this.fill?this.fillParentDiv():void 0!==this.horizOffset&&void 0!==this.vertOffset&&this.alignOver(this.rootDiv,this.rootDiv.parentNode,this.horizOffset,this.vertOffset)},fillParentDiv:function(){var b;this.rootDiv.parentNode&&(b={left:"0px",top:"0px",
width:this.rootDiv.parentNode.clientWidth+"px",height:this.rootDiv.parentNode.clientHeight+"px"},dojo.style(this.rootDiv,b))},alignOver:function(b,a,f,g){var h,k,l,n=this;b&&a&&(h=dojo.marginBox(b),k=dojo.marginBox(a),l={},"number"===typeof f?l=this.insertHorizPositioningStyle(l,f,h,k):"object"===typeof f&&d.forEach(f,function(b){l=n.insertHorizPositioningStyle(l,b,h,k)}),"number"===typeof g?l=this.insertVertPositioningStyle(l,g,h,k):"object"===typeof g&&d.forEach(g,function(b){l=n.insertVertPositioningStyle(l,
b,h,k)}),dojo.style(b,l))},insertHorizPositioningStyle:function(b,a,d,f){0<a?b.left=a+"px":0===a?b.left=Math.round((f.w-d.w)/2)+"px":b.right=-a+"px";return b},insertVertPositioningStyle:function(b,a,d,f){0<a?b.top=a+"px":0===a?b.top=Math.round((f.h-d.h)/2)+"px":b.bottom=-a+"px";return b},applyTheme:function(b,a){g.remove(a||this.rootDiv,"appTheme2");g.add(a||this.rootDiv,"appTheme");b&&g.add(a||this.rootDiv,"appThemeHover")},applyThemeAltBkgd:function(b,a){g.remove(a||this.rootDiv,"appTheme");g.add(a||
this.rootDiv,"appTheme2");b&&g.add(a||this.rootDiv,"appThemeHover")}});dojo.declare("js.LGDependency",null,{constructor:function(){var b,a=this;this.dependencyId&&(b=this.lgById(this.dependencyId),this.onDependencyPrep(b),b.ready.then(function(){a.onDependencyReady()}))},onDependencyPrep:function(){return null},onDependencyReady:function(){return null}});dojo.declare("js.LGDefaults",null,{constructor:function(){this.defaultValues={};this.listenForDefaultsTrigger&&this.listenForDefaultsUpdate()},listenForDefaultsUpdate:function(){var b=
this;this.subscribeToMessage(this.listenForDefaultsTrigger,function(a){b.defaultValues=a;b.onDefaultsUpdate()})},onDefaultsUpdate:function(){return null},changeDefaults:function(){this.broadcastDefaultsUpdate()},broadcastDefaultsUpdate:function(){this.broadcastDefaultsPublish&&this.publishMessage(this.broadcastDefaultsPublish,this.defaultValues)}})})},"js/lgonlineCommand":function(){define("js/lgonlineCommand","dojo/dom-construct dojo/dom dojo/on dojo/Deferred dojo/DeferredList dojo/dom-style dojo/dom-class dojo/_base/array dojo/_base/lang dojo/string dijit/form/TextBox dijit/layout/ContentPane esri/dijit/BasemapGallery esri/tasks/PrintTask esri/tasks/PrintParameters esri/tasks/PrintTemplate esri/dijit/PopupTemplate js/lgonlineBase js/lgonlineMap".split(" "),
function(h,n,l,k,g,d,f,a,b,e,m,q,p,r,s,t,u){dojo.declare("js.LGDropdownBox",js.LGGraphic,{constructor:function(){var c=this;this.applyTheme(!1);this.isShowable=!0;this.trigger&&(this.subscribeToMessage("command",function(a){a!==c.trigger&&c.setIsVisible(!1)}),this.subscribeToMessage(this.trigger,function(a){c.handleTrigger(a)}))},setShowable:function(c){this.isShowable=c;!this.isShowable&&this.getIsVisible()&&this.toggleVisibility()},handleTrigger:function(){this.isShowable&&this.toggleVisibility()}});
dojo.declare("js.LGMapBasedMenuBox",[js.LGDropdownBox,js.LGMapDependency],{constructor:function(){this.ready=new k},onDependencyReady:function(){this.ready.resolve(this);this.inherited(arguments)}});dojo.declare("js.LGBasemapBox",js.LGMapBasedMenuBox,{onDependencyReady:function(){var c,a,b=this.getBasemapGroup();c=this.rootId+"_gallery";a=(new q({id:c,className:this.galleryClass})).placeAt(this.rootDiv);touchScroll(c);c=(new p({showArcGISBasemaps:!0,basemapsGroup:b,bingMapsKey:this.mapObj.commonConfig.bingMapsKey,
map:this.mapObj.mapInfo.map},h.create("div"))).placeAt(this.rootDiv);a.set("content",c.domNode);c.startup();this.inherited(arguments)},getBasemapGroup:function(){var c=null;this.basemapgroupTitle&&(this.basemapgroupOwner&&0<this.basemapgroupTitle.length&&0<this.basemapgroupOwner.length)&&(c={title:this.basemapgroupTitle,owner:this.basemapgroupOwner});return c}});dojo.declare("js.LGCallMethods",js.LGObject,{constructor:function(){var c,b=this;this.todo&&a.forEach(this.todo,function(a){try{if(c=n.byId(a.rootId))if(c=
c.getLGObject())c[a.method](a.arg)}catch(d){b.log("LGCallMethods_1: "+d.toString())}})}});dojo.declare("js.LGButton",js.LGGraphic,{constructor:function(){var c;this.applyTheme(!0);this.iconUrl&&(c={src:this.iconUrl},this.iconClass&&(c.className=this.iconClass),this.iconImg=h.create("img",c,this.rootDiv));this.displayText&&(c={innerHTML:this.checkForSubstitution(this.displayText)},this.displayTextClass&&(c.className=this.displayTextClass),h.create("div",c,this.rootDiv));this.tooltip&&(this.rootDiv.title=
this.checkForSubstitution(this.tooltip))}});dojo.declare("js.LGRadioButton",js.LGButton,{constructor:function(){this.isOn=this.toBoolean(this.isOn,!1);this.setIsOn(this.isOn);this.controller=null;l(this.rootDiv,"click",this.handleClick)},setController:function(c){this.controller=c},setIsOn:function(c){(this.isOn=c)?this.applyThemeAltBkgd(!0):this.applyTheme(!0)},handleClick:function(c){c=c.currentTarget.getLGObject();c.controller&&c.controller.selectMember(c)}});dojo.declare("js.LGRadioButtonController",
js.LGObject,{constructor:function(){this.members=[];this.currentMember=null},addMember:function(c){this.members.push(c);c.setController(this)},selectMember:function(c){var b,d=this;this.currentMember&&(this.currentMember.setIsOn(!1),this.currentMember=null);"number"===typeof c?0<this.members.length&&(c=Math.max(0,Math.min(c,d.members.length-1)),d.currentMember=d.members[c],d.currentMember.setIsOn(!0)):"string"===typeof c?a.some(this.members,function(a){return a.value===c?(d.currentMember=a,d.currentMember.setIsOn(!0),
!0):!1}):c&&(b=c.rootId,a.some(this.members,function(c){return c.rootId===b?(d.currentMember=c,d.currentMember.setIsOn(!0),!0):!1}))},getCurrentMember:function(){return this.currentMember}});dojo.declare("js.LGCommand",[js.LGButton,js.LGDependency],{constructor:function(){this.publish&&(this.clickHandler=l(this.rootDiv,"click",this.handleClick))},onDependencyPrep:function(){this.setIsVisible(!1);this.inherited(arguments)},onDependencyReady:function(){this.setIsVisible(!0);this.inherited(arguments)},
handleClick:function(c){c=c.currentTarget.getLGObject();c.publishMessage("command",c.publish);c.publishMessage(c.publish,c.publishArg)}});dojo.declare("js.LGCommandToggle",js.LGCommand,{constructor:function(){var c=this;this.iconDisabledUrl=this.iconDisabledUrl||this.iconUrl;this.isEnabled=this.toBoolean(this.isEnabled,!0);c.setIsEnabled(this.isEnabled);this.isVisible=this.toBoolean(this.isVisible,!0);c.setIsVisible(this.isVisible);this.triggerEnable&&this.subscribeToMessage(this.triggerEnable,function(){c.isEnabled=
!0;c.setIsEnabled(c.isEnabled)});this.triggerDisable&&this.subscribeToMessage(this.triggerDisable,function(){c.isEnabled=!1;c.setIsEnabled(c.isEnabled)});this.triggerVisible&&this.subscribeToMessage(this.triggerVisible,function(){c.isVisible=!0;c.setIsVisible(c.isVisible)});this.triggerInvisible&&this.subscribeToMessage(this.triggerInvisible,function(){c.isVisible=!1;c.setIsVisible(c.isVisible)})},setIsEnabled:function(c){(this.isEnabled=c)?(this.iconImg.src=this.iconUrl,f.add(this.rootDiv,"appThemeHover")):
(this.iconImg.src=this.iconDisabledUrl,f.remove(this.rootDiv,"appThemeHover"))},handleClick:function(c){var a=c.currentTarget.getLGObject();a.isEnabled&&a.inherited("handleClick",arguments)}});dojo.declare("js.LGLaunchUrl",js.LGObject,{constructor:function(){this.subscribeToMessage(this.sameWinTrigger,function(c){c&&window.open(c,"_parent")});this.subscribeToMessage(this.newWinTrigger,function(c){c&&window.open(c,"_blank")})}});dojo.declare("js.LGPrintMap",js.LGMapBasedMenuBox,{constructor:function(){var c,
a=this;this.radioButtonController=new js.LGRadioButtonController;c=new js.LGRadioButton({rootId:this.rootId+"_landscape",parentDiv:this.rootId,iconUrl:this.landscapeButtonIconUrl,rootClass:this.orientationButtonClass,iconClass:this.orientationButtonIconClass,tooltip:this.checkForSubstitution(this.landscapeButtonTooltip),value:this.landscapeServerSpec});c.setIsVisible(!0);this.radioButtonController.addMember(c);d.set(c.rootDiv,"display","inline-block");c=new js.LGRadioButton({rootId:this.rootId+"_portrait",
parentDiv:this.rootId,iconUrl:this.portraitButtonIconUrl,rootClass:this.orientationButtonClass,iconClass:this.orientationButtonIconClass,tooltip:this.checkForSubstitution(this.portraitButtonTooltip),value:this.portraitServerSpec});c.setIsVisible(!0);this.radioButtonController.addMember(c);d.set(c.rootDiv,"display","inline-block");this.titleEntryTextBox=(new m({id:this.rootId+"_titleEntry",value:this.title,trim:!0,placeHolder:this.titleHint})).placeAt(this.rootId);d.set(this.titleEntryTextBox.domNode,
"width","97%");f.add(this.titleEntryTextBox.domNode,this.titleClass);this.authorEntryTextBox=(new m({id:this.rootId+"_authorEntry",value:this.author,trim:!0,placeHolder:this.authorHint})).placeAt(this.rootId);d.set(this.authorEntryTextBox.domNode,"width","97%");f.add(this.authorEntryTextBox.domNode,this.authorClass);c=new js.LGButton({rootId:this.rootId+"_doPrint",parentDiv:this.rootId,iconUrl:this.printButtonIconUrl,rootClass:this.printButtonClass,iconClass:this.printButtonIconClass,tooltip:this.checkForSubstitution(this.printButtonTooltip)});
c.setIsVisible(!0);d.set(c.rootDiv,"display","inline-block");this.radioButtonController.selectMember(0);l(c.rootDiv,"click",function(){var c,b;a.publishMessage(a.publishWorking);a.setIsVisible(!1);c=(c=a.radioButtonController.getCurrentMember())?c.value:null;b=new s;b.map=a.mapObj.mapInfo.map;b.outSpatialReference=a.mapObj.mapInfo.map.spatialReference;b.template=new t;b.template.format=a.format||"PDF";b.template.layout=c||a.layout||"Letter ANSI A Landscape";b.template.layoutOptions={titleText:a.titleEntryTextBox.value,
authorText:a.authorEntryTextBox.value,copyrightText:a.copyrightText};b.template.preserveScale=a.toBoolean(a.preserveScale,!1);b.template.showAttribution=!0;a.printTask.execute(b,function(c){a.publishMessage(a.publishReady);a.publishMessage(a.publishPrintUrl,c.url)},function(c){a.publishMessage(a.publishReady);a.log("Print failed: "+c.message,!0)})})},checkPrerequisites:function(){if(this.commonConfig.helperServices&&this.commonConfig.helperServices.printTask&&this.commonConfig.helperServices.printTask.url)this.printTask=
new r(this.commonConfig.helperServices.printTask.url,{async:!1});else throw this.log("no print task configured"),"no print task configured";}});dojo.declare("js.LGFetchPrintedMap",[js.LGObject,js.LGMapDependency],{constructor:function(){this.fetchPrintUrl=null;this.printAvailabilityTimeoutMinutes=this.toNumber(this.printAvailabilityTimeoutMinutes,10);this.printTimeouter=null},onDependencyReady:function(){var c=this;this.subscribeToMessage(this.triggerPrintUrl,function(a){clearTimeout(c.printTimeouter);
c.fetchPrintUrl=a;c.publishMessage(c.publishPrintAvailable);0<c.printAvailabilityTimeoutMinutes&&(c.printTimeouter=setTimeout(function(){c.publishMessage(c.publishPrintNotAvailable)},6E4*c.printAvailabilityTimeoutMinutes))});this.subscribeToMessage(this.trigger,function(){null!==c.fetchPrintUrl&&c.publishMessage(c.publish,c.fetchPrintUrl)})}});dojo.declare("js.LGLocate",js.LGObject,{constructor:function(){var c=this,a;this.ready=new k;Modernizr.geolocation?(this.subscribeToMessage(this.trigger,function(){a=
setTimeout(function(){alert(c.checkForSubstitution("@messages.geolocationTimeout"))},16E3);navigator.geolocation.getCurrentPosition(function(b){clearTimeout(a);c.log("go to "+b.coords.latitude+" "+b.coords.longitude);c.publishMessage(c.publish,new esri.geometry.Point(b.coords.longitude,b.coords.latitude,new esri.SpatialReference({wkid:4326})))},function(b){clearTimeout(a);switch(b.code){case b.PERMISSION_DENIED:b=c.checkForSubstitution("@messages.geolocationDenied");break;case b.TIMEOUT:b=c.checkForSubstitution("@messages.geolocationTimeout");
break;default:b=c.checkForSubstitution("@messages.geolocationUnavailable")}alert(b)},{timeout:8E3})}),this.ready.resolve(c)):this.ready.reject(c)}});dojo.declare("js.LGSearch",js.LGObject,{constructor:function(){this.busyIndicator&&(this.busyIndicator=this.lgById(this.busyIndicator))},search:function(){return null},toList:function(){return[]},publish:function(c,a){this.publishMessage(c,a)},sortByLabel:function(c,a){var b=0;c&&(a&&c.label&&a.label)&&(b=c.label.localeCompare(a.label));return b},getRepresentativePoint:function(c){var a;
"point"===c.type?a=c:"polygon"===c.type?(a=c.getExtent().getCenter(),c.contains(a)||(a=c.getPoint(0,0))):"polyline"===c.type&&(a=c.getPoint(0,0));return a}});dojo.declare("js.LGSearchAddress",[js.LGSearch,js.LGMapDependency],{constructor:function(){this.searcher=new esri.tasks.Locator(this.searchUrl);this.searcher.outSpatialReference=new esri.SpatialReference({wkid:this.outWkid});this.params={};this.params.outFields=this.outFields;this.ready=new k},onDependencyReady:function(){this.params.searchExtent=
this.mapObj.mapInfo.map.extent;this.ready.resolve(this);this.inherited(arguments)},search:function(c,a,b){this.params.address={};this.params.address[this.addressParamName]=c;this.searcher.addressToLocations(this.params,a,b)},toList:function(c){var b,d=this,e=[];c&&a.forEach(c,function(c){b=!1;c.score>=d.minimumScore&&(d.validLocators?a.some(d.validLocators,function(a){if(c.attributes.Loc_name===a)return b=!0}):b=!0);b&&e.push({label:c.address,data:new esri.geometry.Point(c.location.x,c.location.y,
new esri.SpatialReference({wkid:102100}))})});return e},publish:function(c,a){this.publishMessage(c,a)}});dojo.declare("js.LGSearchFeatureLayer",[js.LGSearch,js.LGMapDependency],{constructor:function(){if(!this.searchPattern||0>this.searchPattern.indexOf("${1}"))this.searchPattern="%${1}%";this.caseInsensitiveSearch=this.toBoolean(this.caseInsensitiveSearch,!0);this.ready=new k},onDependencyReady:function(){var c,b,d,e=",",f,g=null,h=this;try{if(c=this.mapObj.getLayer(this.searchLayerName),!c||!c.url)b=
this.checkForSubstitution("@messages.searchLayerMissing");else{this.searchURL=c.url;a.forEach(c.fields,function(c){e+=c.name+","});a.every(this.searchFields,function(c){b=c;return 0<=e.indexOf(","+c+",")})||(d='"'+b+'"<br>',d+=this.checkForSubstitution("@messages.searchFieldMissing")+"<br><hr><br>",d+=this.checkForSubstitution("@prompts.layerFields")+"<br>",1<e.length&&(d+=e.substring(1,e.length-1)),this.log(d,!0));this.objectIdField=c.objectIdField;this.publishPointsOnly="boolean"===typeof this.publishPointsOnly?
this.publishPointsOnly:!0;this.searcher=new esri.tasks.QueryTask(this.searchURL);this.generalSearchParams=new esri.tasks.Query;this.generalSearchParams.returnGeometry=!1;this.generalSearchParams.outSpatialReference=this.mapObj.mapInfo.map.spatialReference;this.generalSearchParams.outFields=[c.objectIdField].concat(this.searchFields);this.objectSearchParams=new esri.tasks.Query;this.objectSearchParams.returnGeometry=!0;this.objectSearchParams.outSpatialReference=this.mapObj.mapInfo.map.spatialReference;
this.objectSearchParams.outFields=["*"];f=this.mapObj.mapInfo.itemInfo.itemData.operationalLayers;a.some(f,function(c){return c.title===h.searchLayerName?(g=new u(c.popupInfo),!0):!1});this.mapObj.setPopup(g);this.log("Search layer "+this.searchLayerName+" set up for queries");this.ready.resolve(this);this.inherited(arguments);return}}catch(l){b=l.toString()}d='"'+(this.searchLayerName||"")+'"<br>';d+=b+"<br><hr><br>";d+=this.checkForSubstitution("@prompts.mapLayers")+"<br><ul>";a.forEach(this.mapObj.getLayerNameList(),
function(c){d+='<li>"'+c+'"</li>'});d+="</ul>";this.log(d,!0);this.ready.reject(this);this.inherited(arguments)},checkPrerequisites:function(){var c,b=this;if(this.searchFields&&0<this.searchFields.length)c=this.searchFields.split(","),this.searchFields=[],a.forEach(c,function(c){b.searchFields.push(c.trim())});else throw this.log("missing search fields"),"missing search fields";},search:function(c,b,d){var e,f="",g,h="";!0===this.caseInsensitiveSearch?(e=c.toUpperCase(),g="UPPER(${0}) LIKE '"+this.searchPattern+
"'"):(e=c,g="${0} LIKE '"+this.searchPattern+"'");e=e.replace(/'/g,"''");a.forEach(this.searchFields,function(c){f=f+h+dojo.string.substitute(g,[c,e]);h="  OR  "});0<f.length&&(this.generalSearchParams.where=f,this.searcher.execute(this.generalSearchParams,b,d))},toList:function(c,b){var d=this,e=[],f,g,h=b.toUpperCase();c&&(c.features&&0<c.features.length)&&(a.forEach(c.features,function(c){g="";a.some(d.searchFields,function(a){return c.attributes[a]&&(f=c.attributes[a].toString(),0<=f.toUpperCase().indexOf(h))?
(g=f,!0):!1});""===g&&(g="result");e.push({label:g,data:c.attributes[d.objectIdField]})}),e.sort(d.sortByLabel));return e},publish:function(c,a){var b,d,e=this;this.busyIndicator&&this.busyIndicator.setIsVisible(!0);this.objectSearchParams.where=this.objectIdField+"="+a;this.searcher.execute(this.objectSearchParams,function(a){a&&a.features&&0<a.features.length?(b=a.features[0],d=e.publishPointsOnly?e.getRepresentativePoint(b.geometry):b,e.publishMessage(c,d)):e.log("LGSearchFeatureLayer_1: no results");
e.busyIndicator&&e.busyIndicator.setIsVisible(!1)},function(c){e.log("LGSearchFeatureLayer_2: "+c.message);e.busyIndicator&&e.busyIndicator.setIsVisible(!1)})}});dojo.declare("js.LGSearchMultiplexer",js.LGSearch,{constructor:function(){var c=this,b;this.ready=new k;b=this.createSearchersList();(new g(b)).then(function(b){a.every(b,function(c){return c[0]})?c.ready.resolve(c):c.ready.reject(c)})},createSearchersList:function(){var c=this,b=[];this.searchers=[];this.searchers=[];this.searcherNames&&
a.forEach(this.searcherNames,function(a){if(a=c.lgById(a))c.searchers.push(a),b.push(a.ready)});return b},search:function(c,b,d){var e=[],f=[];a.forEach(this.searchers,function(b,d){var g=new k;f.push(g);b.search(c,function(f){f=b.toList(f,c);f=a.map(f,function(c){return{data:{iSearcher:d,itemData:c.data},label:c.label}});e=e.concat(f);g.resolve()},function(c){g.reject(c)})});(new g(f)).then(function(c){var f=!0;d&&(f=!a.some(c,function(c){return!c[0]?(d(c[1]),!0):!1}));f&&b&&b(e)})},toList:function(c){return c},
publish:function(c,a){this.searchers[a.iSearcher].publish(c,a.itemData)}});dojo.declare("js.LGSearchFeatureLayerMultiplexer",js.LGSearchMultiplexer,{createSearchersList:function(){var c=this,b=[],d=[];this.searchers=[];this.searchLayerName&&(d=this.searchLayerName.split(","));a.forEach(d,function(a){a=new js.LGSearchFeatureLayer({app:c.app,commonConfig:c.commonConfig,i18n:c.i18n,webmap:c.webmap,rootId:c.rootId+"_"+c.searchers.length,parentDiv:c.parentDiv,dependencyId:c.dependencyId,busyIndicator:c.busyIndicator,
publishPointsOnly:c.publishPointsOnly,searchPattern:c.searchPattern,caseInsensitiveSearch:c.caseInsensitiveSearch,searchLayerName:a.trim(),searchFields:c.searchFields});c.searchers.push(a);b.push(a.ready)});return b}});dojo.declare("js.LGSearchBoxByText",js.LGDropdownBox,{constructor:function(){var c=this,b,e,f,g,k,p,n;b=this.rootId+"_entry";h.create("label",{"for":b,innerHTML:this.checkForSubstitution(this.showPrompt)},this.rootId);this.searchEntryTextBox=(new m({id:b,value:"",trim:!0,placeHolder:this.hint,
intermediateChanges:!0})).placeAt(this.rootId);d.set(this.searchEntryTextBox.domNode,"width","99%");b=h.create("div",{className:this.resultsListBoxClass},this.rootId);e=h.create("table",{className:this.resultsListTableClass},b);f=h.create("tbody",{className:this.resultsListBodyClass},e);touchScroll(b);g=this.lgById(this.searcher);k="";p=0;n=null;l(this.searchEntryTextBox,"change",function(){var b=c.searchEntryTextBox.get("value");k!==b&&(k=b,h.empty(f),clearTimeout(n),0<b.length&&(n=setTimeout(function(){var d,
e,m;d=h.create("tr",null,f);h.create("td",{className:c.resultsListSearchingClass},d);e=p=(new Date).getTime();g.search(b,function(d){e<p||(h.empty(f),d=g.toList(d,b),m=(new Date).getTime(),c.log("retd "+d.length+" items in "+(m-e)/1E3+" secs"),0<d.length&&a.forEach(d,function(a){var b;b=h.create("tr",null,f);b=h.create("td",{className:c.resultsListEntryClass,innerHTML:a.label},b);c.applyTheme(!0,b);l(b,"click",function(){g.publish(c.publish,a.data)})}))},function(b){c.log("LGSearchBoxByText_1: "+
b.message);k="";h.empty(f)})},1E3)))})},toggleVisibility:function(){this.inherited(arguments);this.getIsVisible()&&this.searchEntryTextBox.focus()}});dojo.declare("js.LGShare",js.LGObject,{constructor:function(){var c=this;this.busyIndicator&&(this.busyIndicator=this.lgById(this.busyIndicator));this.subscribeToMessage(this.trigger,function(){c.share()})},share:function(){var c=this,b,a;b=encodeURIComponent(this.getSubject());a=encodeURIComponent(this.getUrlToShare());this.tinyURLServiceURL&&0<this.tinyURLServiceURL.length?
(this.busyIndicator&&this.busyIndicator.setIsVisible(!0),a=esri.substitute({url:a},this.tinyURLServiceURL),esri.request({url:a,handleAs:"json"},{useProxy:!1}).then(function(a){var d,e;try{if(d=c.followAttributePath(a,c.tinyURLResponseAttribute))e=esri.substitute({subject:b,url:d},c.shareUrl),c.publishMessage(c.publish,e)}catch(f){c.log("LGShare_1: "+f.toString())}c.busyIndicator&&c.busyIndicator.setIsVisible(!1)},function(a){c.log("LGShare_2: "+a.toString());c.busyIndicator&&c.busyIndicator.setIsVisible(!1)})):
(a=esri.substitute({subject:b,url:a},this.shareUrl),this.publishMessage(this.publish,a))},getSubject:function(){return""},getUrlToShare:function(){return this.getAppUrl()},getAppUrl:function(){return window.location.toString()}});dojo.declare("js.LGShareAppExtents",[js.LGShare,js.LGMapDependency],{getSubject:function(){var c="";this.subject&&(c=this.checkForSubstitution(this.subject));return c},getUrlToShare:function(){var c=this.getAppUrl();return c+(0>c.indexOf("?")?"?":"&")+this.getMapExtentsArg()},
getMapExtentsArg:function(){return"ex="+this.mapObj.getMapExtentsAsString()}});dojo.declare("js.LGFilterLayers1",js.LGMapBasedMenuBox,{constructor:function(){this.layers=[]},onDependencyReady:function(){var c;this.fieldname1&&(a.forEach(this.mapObj.mapInfo.itemInfo.itemData.operationalLayers,b.hitch(this,function(c){var a;if(c.layerObject&&"Feature Layer"===c.layerObject.type)for(a=0;a<c.layerObject.fields.length;a+=1)if(c.layerObject.fields[a].name===this.fieldname1){c={layerObject:c.layerObject,
fieldType:c.layerObject.fields[a].type};this.layers.push(c);break}})),this.applyFilter(),h.create("label",{innerHTML:this.hint1},h.create("div",{},this.rootId)),c=(new m({id:this.rootId+"_field1",value:this.value1,trim:!0,placeHolder:this.hint1,intermediateChanges:!0})).placeAt(this.rootId),d.set(c.domNode,"width","99%"),this.tooltip&&c.set("title",this.checkForSubstitution(this.tooltip)),l(c,"change",b.hitch(this,function(){this.value1=c.value.trim();this.onValueChanged()})))},onValueChanged:function(){this.applyFilter()},
applyFilter:function(){a.forEach(this.layers,b.hitch(this,function(c){this.setLayerDefinitionExpression(c.layerObject,c.fieldType);c.layerObject.clearSelection()}))},setLayerDefinitionExpression:function(c,a){var b=c.defaultDefinitionExpression;try{this.value1&&""!==this.value1&&("esriFieldTypeString"===a?b=e.substitute(this.defnExpression,{fieldname1:this.fieldname1,value1:"'"+this.value1+"'"}):"esriFieldTypeInteger"===a&&(b=e.substitute(this.defnExpression,{fieldname1:this.fieldname1,value1:this.value1}))),
c.setDefinitionExpression(b)}catch(d){}}});dojo.declare("js.LGFilterLayers1WithDefaults",[js.LGFilterLayers1,js.LGDefaults],{constructor:function(){this.changeDefaults()},onValueChanged:function(){this.inherited(arguments);this.changeDefaults()},changeDefaults:function(){this.defaultValues.value1=this.value1;this.defaultValues.fieldname1=this.fieldname1;this.inherited(arguments)}})})},"js/lgonlineDrawing":function(){define("js/lgonlineDrawing",["dojo/Deferred","dojo/_base/Color","js/lgonlineMap"],
function(h,n){dojo.declare("js.LGHighlighter",[js.LGObject,js.LGMapDependency],{onDependencyReady:function(){var h,k,g=this;this.highlighterLayer=g.mapObj.createGraphicsLayer("highlighterLayer");this.lineHiliteColor=new n(this.lineHiliteColor?this.lineHiliteColor:"#0000ff");this.fillHiliteColor=new n(this.fillHiliteColor?this.fillHiliteColor:[0,0,255,0.1]);this.intervalID=this.intervalTerminator=null;this.subscribeToMessage("highlightItem",function(d){var f,a,b;d&&(f=d.geometry?d.geometry:d,d.attributes&&
(a=d.attributes),d.infoTemplate&&(b=d.infoTemplate),d=g.createHighlightGraphics(f,a,b),k=(h=f.getExtent())?h.getCenter():f,g.showHighlight(d,k,g.highlightZoomLevel,a&&g.showFeaturePopup))})},createHighlightGraphics:function(h,k,g){var d,f=[];if("polyline"===h.type)f.push(new esri.Graphic(h,new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,this.lineHiliteColor,3),k,g));else if("point"===h.type)for(d=0;4>=d;++d)f.push(new esri.Graphic(h,new esri.symbol.SimpleMarkerSymbol(esri.symbol.SimpleMarkerSymbol.STYLE_CIRCLE,
2.5*(d+16),new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,new dojo.Color(this.lineHiliteColor),3),new dojo.Color([0,0,0,0])),k,g));else f.push(new esri.Graphic(h,new esri.symbol.SimpleFillSymbol(esri.symbol.SimpleFillSymbol.STYLE_SOLID,new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,this.lineHiliteColor,3),this.fillHiliteColor),k,g));return f},showHighlight:function(l,k,g,d){var f,a,b,e,m=this;k?f=this.mapObj.centerAt(k):(f=new h,f.resolve());f.then(function(){g?
a=m.mapObj.setZoom(g):(a=new h,a.resolve());a.then(function(){1<l.length?(m.intervalTerminator&&(clearTimeout(m.intervalTerminator),clearInterval(m.intervalID)),b=0,e=!0,m.intervalID=setInterval(function(){m.highlighterLayer.clear();m.highlighterLayer.add(l[b]);e?++b:--b;b===l.length?(e=!1,--b):0>b&&(e=!0,b=0)},120),m.intervalTerminator=setTimeout(function(){clearInterval(m.intervalID);m.intervalTerminator=null;m.intervalID=null;m.highlighterLayer.clear()},5E3)):(m.highlighterLayer.clear(),m.highlighterLayer.add(l[0]));
d&&m.mapObj.showPopupWithFeature(k,l[0])})})}})})},"js/lgonlineEditing":function(){define("js/lgonlineEditing","dojo/dom-construct dojo/on dojo/_base/array dojo/_base/lang dojo/aspect esri/dijit/editing/TemplatePicker esri/dijit/editing/Editor js/lgonlineBase js/lgonlineMap js/lgonlineCommand".split(" "),function(h,n,l,k,g,d,f){dojo.declare("js.LGEditTemplatePicker",js.LGMapBasedMenuBox,{constructor:function(){var a;a=dojo.byId(this.colorizerId).getLGObject();a=".templatePicker{border:1px solid transparent!important;}.templatePicker .dojoxGrid{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridScrollbox{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridRow{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridCell{border:1px solid transparent}.templatePicker .dojoxGrid .dojoxGridRow{border:1px solid transparent}.templatePicker .grid .dojoxGridRowOver{background-color:transparent;color:inherit;}.templatePicker .grid .dojoxGridRowOver .dojoxGridCell{background-color:transparent;color:inherit;}.templatePicker .dojoxGrid .dojoxGridCellFocus{border:1px solid transparent!important;}.templatePicker .dojoxGrid .dojoxGridRowOdd{background-color:transparent;}.templatePicker .dojoxGrid .selectedItem{border:1px solid transparent!important;color:"+
a.foregroundColor()+"!important;background-color:"+a.alternateBackgroundColor()+"!important}";this.injectCSS(a)},onDependencyReady:function(){var a=this,b,e,m;b=this.mapObj.mapInfo;this.layerInfos=[];this.layers=[];l.forEach(b.itemInfo.itemData.operationalLayers,k.hitch(this,function(a){var b=a.layerObject;b instanceof esri.layers.FeatureLayer&&b.isEditable()&&!(a.capabilities&&"Query"===a.capabilities)&&(this.layerInfos.push({featureLayer:b}),this.layers.push(b))}));0===this.layers.length?this.setShowable(!1):
(e=b.map,this.setIsVisible(!1,!0),b=h.create("div",{className:this.templatePickerHolderClass}),h.place(b,this.rootId),m=h.create("div"),h.place(m,b),m=new d({featureLayers:this.layers,rows:"auto",columns:2,grouping:!0},m),m.startup(),touchScroll(b),this.setIsVisible(!1,!1),e={map:e,templatePicker:m,toolbarVisible:!1,layerInfos:this.layerInfos},m=h.create("div"),h.place(m,b),b=new f({settings:e},m),b.startup(),g.before(b,"_applyEdits",function(b){l.forEach(b,function(b){b.adds&&a.preprocessEditAdds(b);
b.updates&&a.preprocessEditUpdates(b);b.deletes&&a.preprocessEditDeletes(b)})}));this.inherited(arguments)},preprocessEditAdds:function(a){return a},preprocessEditUpdates:function(a){return a},preprocessEditDeletes:function(a){return a}});dojo.declare("js.LGEditTemplatePickerWithDefaults",[js.LGEditTemplatePicker,js.LGDefaults],{preprocessEditAdds:function(a){a.adds[0].attributes[this.defaultValues.fieldname1]=this.defaultValues.value1;return a}});dojo.declare("js.LGEditAttributes",[js.LGObject,js.LGMapDependency],
{onDependencyReady:function(){this.inherited(arguments);this.clickHandle=this.subscribeToMessage("mapClick",function(a){console.log(a.type)})}})})},"js/lgonlineFrame":function(){define("js/lgonlineFrame","dojo/dom-construct dojo/on dojo/dom-style dojo/_base/array dojo/_base/lang js/lgonlineBase".split(" "),function(h,n,l,k,g){dojo.declare("js.LGColorizer",js.LGObject,{constructor:function(){var d,f="",a=this,b=["#fff","#333333","#5d5d5d","#5d5d5d"];this.colors=[];k.some(this.colorTable,function(b){return a.theme===
b.theme?(a.colors=b.colors,!0):!1});if(this.colors.length<b.length)for(d=this.colors.length;d<b.length;d+=1)this.colors.push(b[d]);f+=".appTheme{color:"+this.colors[0]+";background-color:"+this.colors[1]+"}";f+=".appTheme2{color:"+this.colors[0]+";background-color:"+this.colors[3]+"}";f+=".appThemeHover:hover{background-color:"+this.colors[2]+"}";this.injectCSS(f)},foregroundColor:function(){return this.colors[0]},backgroundColor:function(){return this.colors[1]},hoverColor:function(){return this.colors[2]},
alternateBackgroundColor:function(){return this.colors[3]}});dojo.declare("js.LGFrame",js.LGGraphic,{constructor:function(){var d;d={};this.headerDivId&&(d.id=this.headerDivId);this.headerDivClass&&(d.className=this.headerDivClass);this.headerDiv=h.create("div",d,this.rootDiv);this.applyTheme(!1,this.headerDiv);d={};this.contentDivId&&(d.id=this.contentDivId);this.contentDivClass&&(d.className=this.contentDivClass);this.contentDiv=h.create("div",d,this.rootDiv);this.handleWindowResize()},handleWindowResize:function(){this.inherited(arguments);
this.resizeContentDiv()},resizeContentDiv:function(){var d,f,a;this.headerDiv&&this.contentDiv&&(d=dojo.marginBox(this.rootDiv),f=dojo.marginBox(this.headerDiv),a=d.h-f.h,0<a&&(a={},a.top=f.h+"px",a.height=d.h-f.h+"px",l.set(this.contentDiv,a)))}});dojo.declare("js.LGGallery",js.LGGraphic,{constructor:function(){var d,f=this;d=h.create("table",null,this.rootDiv);this.applyTheme(!1,d);n(window,"resize",g.hitch(this,this.handleParentResize));this.rootDiv.getContentDiv=function(){return f.addItem()};
d=h.create("tbody",null,d);this.galleryRow=h.create("tr",null,d);d={innerHTML:"&lt;",style:{visibility:"hidden"}};this.arrowClass&&(d.className=this.arrowClass);this.leftArrow=h.create("td",d,this.galleryRow);this.applyTheme(!0,this.leftArrow);n(this.leftArrow,"click",g.hitch(this,this.shiftLeft));d.innerHTML="&gt;";this.rightArrow=h.create("td",d,this.galleryRow);this.applyTheme(!0,this.rightArrow);n(this.rightArrow,"click",g.hitch(this,this.shiftRight));this.zeroItemWidth=dojo.marginBox(this.rootDiv).w;
this.numItemsToDisplay=this.iFirstItem=this.numItems=this.itemWidth=0;this.firstItem=null;this.handleParentResize()},addItem:function(d){var f;f={};"string"===typeof d&&(f.innerHTML=d);this.itemClass&&(f.className=this.itemClass);f=h.create("td",f);"string"!==typeof d&&f.appendChild(d);this.galleryRow.insertBefore(f,this.rightArrow);this.numItems+=1;this.firstItem||(this.firstItem=f,this.itemWidth=dojo.marginBox(f).w);this.handleParentResize();return f},clearItems:function(){for(;2<this.galleryRow.childNodes.length;)this.galleryRow.removeChild(this.galleryRow.childNodes[1]);
this.numItemsToDisplay=this.iFirstItem=this.numItems=0;this.firstItem=null;this.handleParentResize()},handleParentResize:function(){var d,f;0===this.zeroItemWidth&&(this.zeroItemWidth=dojo.marginBox(this.rootDiv).w);d=dojo.marginBox(this.rootDiv.parentNode).w;f=this.zeroItemWidth+this.numItems*this.itemWidth;0!==this.numItems&&(f>d?(this.leftArrow.style.visibility="visible",this.rightArrow.style.visibility="visible",this.numItemsToDisplay=Math.max(Math.floor((d-this.zeroItemWidth)/this.itemWidth),
1)):(this.leftArrow.style.visibility="hidden",this.rightArrow.style.visibility="hidden",this.numItemsToDisplay=this.numItems),this.iFirstItem=Math.min(this.iFirstItem,this.numItems-this.numItemsToDisplay),this.drawGallery())},shiftLeft:function(){this.iFirstItem=Math.min(this.iFirstItem+1,this.numItems-this.numItemsToDisplay);this.drawGallery()},shiftRight:function(){this.iFirstItem=Math.max(this.iFirstItem-1,0);this.drawGallery()},drawGallery:function(){var d,f=this.iFirstItem,a=this.iFirstItem+
this.numItemsToDisplay,b=this.firstItem;this.leftArrow.style.visibility="hidden";this.rightArrow.style.visibility="hidden";for(d=0;d<f;)this.rightArrow.style.visibility="visible",b.style.display="none",b=b.nextSibling,d+=1;for(;d<a;)b.style.display="",b=b.nextSibling,d+=1;for(;d<this.numItems;)this.leftArrow.style.visibility="visible",b.style.display="none",b=b.nextSibling,d+=1;this.handleWindowResize()}});dojo.declare("js.LGTitleBar",js.LGGraphic,{constructor:function(){var d;this.iconUrl&&0<this.iconUrl.length&&
(d={src:this.iconUrl},this.iconClass&&(d.className=this.iconClass),h.create("img",d,this.rootDiv));this.title&&0<this.title.length&&(d={innerHTML:this.title},this.titleClass&&(d.className=this.titleClass),h.create("span",d,this.rootDiv),document.title=this.title);this.handleWindowResize()}})})},"js/lgonlineMap":function(){define("js/lgonlineMap","dojo/dom-construct dojo/on dojo/_base/lang dojo/_base/array dojo/Deferred esri/arcgis/utils esri/dijit/Popup js/lgonlineBase".split(" "),function(h,n,l,
k,g,d,f){dojo.declare("js.LGMapDependency",js.LGDependency,{onDependencyPrep:function(a){this.mapObj=a;this.inherited(arguments)}});dojo.declare("js.LGMap",js.LGGraphic,{constructor:function(){var a,b=null,e=this;this.ready=new g;a={ignorePopups:this.toBoolean(this.ignorePopups,!1)};a.mapOptions=this.mapOptions||{};a.mapOptions.showAttribution=!0;this.popup=new f(null,h.create("div"));a.mapOptions.infoWindow=this.popup;if(this.xmin&&this.ymin&&this.xmax&&this.ymax)try{b={xmin:this.xmin,ymin:this.ymin,
xmax:this.xmax,ymax:this.ymax,spatialReference:{}},b.spatialReference.wkid=this.wkid?Number(this.wkid):102100,b=new esri.geometry.Extent(b)}catch(k){b=null}this.ex&&(b=this.getExtentsFromString(this.ex));this.commonConfig&&this.commonConfig.bingMapsKey&&(a.bingMapsKey=this.commonConfig.bingMapsKey);this.webmap&&(this.mapId=this.webmap);d.createMap(this.mapId,this.rootDiv,a).then(function(a){e.mapInfo=a;a.map.spatialReference||(e.mapInfo.map.spatialReference=new esri.SpatialReference(102100));n(window,
"resize",l.hitch(e.mapInfo.map,function(){e.mapInfo.map.resize();e.mapInfo.map.reposition()}));b&&(b.spatialReference.wkid!==e.mapInfo.map.spatialReference.wkid?esri.config.defaults.geometryService?(a=new esri.tasks.ProjectParameters,a.geometries=[b],a.outSR=e.mapInfo.map.spatialReference,esri.config.defaults.geometryService.project(a).then(function(a){b=a[0];e.mapInfo.map.setExtent(b)})):e.log("LGMap_1: Need geometry service to convert extents from wkid "+b.spatialReference.wkid+" to map's "+e.mapInfo.map.spatialReference.wkid):
e.mapInfo.map.setExtent(b));e.tempGraphicsLayer=e.createGraphicsLayer("tempGraphicsLayer");e.positionHandle=e.subscribeToMessage("position",function(a){var b;a.spatialReference.wkid===e.mapInfo.map.spatialReference.wkid?e.publishMessage("highlightItem",a):4326===a.spatialReference.wkid&&102100===e.mapInfo.map.spatialReference.wkid?(a=esri.geometry.geographicToWebMercator(a),e.publishMessage("highlightItem",a)):esri.config.defaults.geometryService?(b=new esri.tasks.ProjectParameters,b.geometries=[a],
b.outSR=e.mapInfo.map.spatialReference,esri.config.defaults.geometryService.project(b).then(function(b){a=b[0];e.publishMessage("highlightItem",a)})):e.log("LGMap_1: Need geometry service to convert position from wkid "+a.spatialReference.wkid+" to map's "+e.mapInfo.map.spatialReference.wkid)});e.showFeatureHandle=e.subscribeToMessage("showFeature",function(a){e.popupTemplate&&(a.infoTemplate=e.popupTemplate);e.publishMessage("highlightItem",a)});e.clickHandle=n(e.mapInfo.map,"click",function(a){e.publishMessage("mapClick",
a.mapPoint)});e.ready.resolve(e)},function(){e.ready.reject(e)})},mapInfo:function(){return this.mapInfo},setPopup:function(a){this.popupTemplate=a},showPopupWithFeature:function(a,b){this.popup.clearFeatures();this.popup.setContent(b.getContent());this.mapInfo.map.infoWindow.show(this.mapInfo.map.toScreen(a))},setExtent:function(a){return this.mapInfo.map.setExtent(a)},centerAt:function(a){return this.mapInfo.map.centerAt(a)},setZoom:function(a){var b=this.mapInfo.map.getMinZoom(),d=this.mapInfo.map.getMaxZoom();
0<=b&&0<=d&&(a=Math.max(b,Math.min(d,a)));return this.mapInfo.map.setZoom(a)},getMapExtentsAsString:function(){var a="";this.mapInfo&&this.mapInfo.map&&(a=this.getStringFromExtents(this.mapInfo.map.extent));return a},getStringFromExtents:function(a){var b=a.xmin.toFixed().toString()+","+a.ymin.toFixed().toString()+","+a.xmax.toFixed().toString()+","+a.ymax.toFixed().toString();(a=a.spatialReference)&&(a.wkid?b=b+","+a.wkid.toString():a.wkt&&(b=b+","+encodeURIComponent(a.wkt)));return b},getExtentsFromString:function(a){var b,
d=null,f;b=a.split(",");if(1===b.length){var g=a.indexOf("PROJCS");0<g?(b=a.substr(0,g).split("%2C"),b[4]=a.substr(g)):b=a.split("%2C")}try{d={xmin:Number(b[0]),ymin:Number(b[1]),xmax:Number(b[2]),ymax:Number(b[3]),spatialReference:{}},4<b.length?(f=Number(b[4]),isNaN(f)?d.spatialReference.wkt=decodeURIComponent(b[4]):d.spatialReference.wkid=f):d.spatialReference.wkid=102100,d=new esri.geometry.Extent(d)}catch(h){d=null}return d},getLayer:function(a){var b;k.some(this.mapInfo.itemInfo.itemData.operationalLayers,
function(d){return d.title===a?(b=d.layerObject,!0):!1});return b},getLayerNameList:function(){var a=[];k.forEach(this.mapInfo.itemInfo.itemData.operationalLayers,function(b){a.push(b.title)});return a},getOperationalLayers:function(){return this.mapInfo.itemInfo.itemData.operationalLayers},createGraphicsLayer:function(a){var b=new esri.layers.GraphicsLayer;b.id=a;return this.mapInfo.map.addLayer(b)},enablePopups:function(){this.mapInfo&&this.mapInfo.clickEventListener&&(this.mapInfo.clickEventHandle=
n(this.mapInfo.map,"click",this.mapInfo.clickEventListener))},disablePopups:function(){this.mapInfo&&this.mapInfo.clickEventHandle&&this.mapInfo.clickEventHandle.remove()}})})},"js/lgonlineOutput":function(){define("js/lgonlineOutput",["dojo/dom-construct","dojo/dom-class","dojo/_base/array","dojo/topic","js/lgonlineBase"],function(h,n,l,k){dojo.declare("js.LGNotes",js.LGObject,{constructor:function(){console&&this.notes&&l.forEach(this.notes,function(g){console.log(g)})}});dojo.declare("js.LGBusy",
js.LGGraphic,{constructor:function(){this.busyImageClass&&n.add(this.rootDiv,this.busyImageClass)}});dojo.declare("js.LGLogBox",js.LGDropdownBox,{constructor:function(){window.gLogMessageBox=this;touchScroll(this.rootDiv)},append:function(g){"string"===typeof g?h.create("div",{innerHTML:g,style:"margin:2px"},this.rootDiv):"object"===typeof g&&null!==g&&this.rootDiv.appendChild(g)}});dojo.declare("js.LGMessageBox",js.LGDropdownBox,{constructor:function(){this.content&&0<this.content.length&&(this.rootDiv.innerHTML=
this.content);touchScroll(this.rootDiv)}});dojo.declare("js.LGPublishEcho",js.LGDropdownBox,{handleTrigger:function(g){this.rootDiv.innerHTML=g.toString();this.setIsVisible(!0)}});dojo.declare("js.LGMessageWatch",js.LGObject,{constructor:function(){var g=this;k.subscribe("publish",function(d){g.showMessage("message from",d)});k.subscribe("receive",function(d){g.showMessage("received by",d)})},showMessage:function(g,d){var f=JSON.stringify(d.data);this.log(g+" "+d.id+': "'+d.tag+'" '+(f||""))}})})}}});
