/* 
This source is a compressed form of part of the git commit 
b2a0569f0e520c09 2013-11-06 11:35:59 -0800
Uncompressed source is available from https://github.com/Esri/local-government-online-apps 
*/ 
/*

 | ArcGIS Solutions
 | Version 10.2
 | Copyright 2012 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
*/
define("js/lgonlineApp","js/lgonlineBase js/lgonlineCommand js/lgonlineDrawing js/lgonlineEditing js/lgonlineFrame js/lgonlineMap js/lgonlineOutput".split(" "),function(){return{}});
require({cache:{"js/lgonlineBase":function(){define("js/lgonlineBase","dojo/dom-construct dojo/dom dojo/on dojo/dom-style dojo/dom-class dojo/_base/array dojo/topic dojo/_base/lang".split(" "),function(l,h,n,k,g,b,e,f){dojo.declare("js.LGObject",null,{constructor:function(a){var c,b,f=this;void 0!==a&&dojo.safeMixin(this,a);this.checkPrerequisites&&this.checkPrerequisites();a={};this.rootId&&(a.id=this.rootId);this.rootClass?a.className=this.rootClass:a.style="display:none";void 0!==this.parentDiv?
(c=this.parentDiv,(b=h.byId(c))||(c=null)):c=null;b&&b.getLGObject&&b.getLGObject().addItem?(this.rootDiv=l.create("div",a),b.getLGObject().addItem(this.rootDiv)):this.rootDiv=l.create("div",a,c);this.rootDiv.getLGObject=function(){return f}},getRootDiv:function(){return this.rootDiv},lgById:function(a){var c=null;(a=h.byId(a))&&a.getLGObject&&(c=a.getLGObject());return c},deleteDivFromDom:function(){this.rootDiv&&this.rootDiv.parentNode.removeChild(this.rootDiv)},injectCSS:function(a){var c;c=document.createElement("style");
c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:(a=document.createTextNode(a),c.appendChild(a));document.body.appendChild(c);return c},checkForSubstitution:function(a){var c,b=a;a&&1<a.length&&(c=a.substring(0,1),"@"===c?this.i18n&&(b=this.followAttributePath(this.i18n,a.substring(1))):"."===c&&(b=this.followAttributePath(null,a.substring(1))));return b},followAttributePath:function(a,c){var b,f=a,e;try{e=c.split(".");for(b=0;b<e.length;b+=1)f=null===f?this.lgById(e[b]):f[e[b]]}catch(g){f=
null}return f},toBoolean:function(a,c){var b;if(!0===a)return!0;if(!1===a)return!1;if("string"===typeof a){b=a.toLowerCase();if("true"===b)return!0;if("false"===b)return!1}return void 0===c?!0:c},toNumber:function(a,c){if("number"===typeof a)return a;a=parseFloat(a);return!isNaN(a)?a:void 0===c?0:c},log:function(a,c){console&&console.log(a);c&&this.publishMessage("error",a);window.gLogMessageBox&&window.gLogMessageBox.append(a)},publishMessage:function(a,c){e.publish("publish",{id:this.rootId,tag:a,
data:c});e.publish(a,c)},subscribeToMessage:function(a,c){var b=this;e.subscribe(a,function(c){e.publish("receive",{id:b.rootId,tag:a,data:c})});e.subscribe(a,c)}});dojo.declare("js.LGGraphic",js.LGObject,{constructor:function(){n(window,"resize",f.hitch(this,this.handleWindowResize));this.handleWindowResize()},setIsVisible:function(a,c){c?(k.set(this.getRootDiv(),"display","block"),k.set(this.getRootDiv(),"visibility",a?"visible":"hidden")):(k.set(this.getRootDiv(),"display",a?"block":"none"),k.set(this.getRootDiv(),
"visibility","visible"))},getIsVisible:function(){return"none"!==k.get(this.getRootDiv(),"display")},toggleVisibility:function(){k.set(this.getRootDiv(),"display",this.getIsVisible()?"none":"block")},handleWindowResize:function(){void 0!==this.fill&&!0===this.fill?this.fillParentDiv():void 0!==this.horizOffset&&void 0!==this.vertOffset&&this.alignOver(this.rootDiv,this.rootDiv.parentNode,this.horizOffset,this.vertOffset)},fillParentDiv:function(){var a;this.rootDiv.parentNode&&(a={left:"0px",top:"0px",
width:this.rootDiv.parentNode.clientWidth+"px",height:this.rootDiv.parentNode.clientHeight+"px"},dojo.style(this.rootDiv,a))},alignOver:function(a,c,f,e){var g,k,h,l=this;a&&c&&(g=dojo.marginBox(a),k=dojo.marginBox(c),h={},"number"===typeof f?h=this.insertHorizPositioningStyle(h,f,g,k):"object"===typeof f&&b.forEach(f,function(a){h=l.insertHorizPositioningStyle(h,a,g,k)}),"number"===typeof e?h=this.insertVertPositioningStyle(h,e,g,k):"object"===typeof e&&b.forEach(e,function(a){h=l.insertVertPositioningStyle(h,
a,g,k)}),dojo.style(a,h))},insertHorizPositioningStyle:function(a,c,b,f){0<c?a.left=c+"px":0===c?a.left=Math.round((f.w-b.w)/2)+"px":a.right=-c+"px";return a},insertVertPositioningStyle:function(a,c,b,f){0<c?a.top=c+"px":0===c?a.top=Math.round((f.h-b.h)/2)+"px":a.bottom=-c+"px";return a},applyTheme:function(a,c){g.remove(c||this.rootDiv,"appTheme2");g.add(c||this.rootDiv,"appTheme");a&&g.add(c||this.rootDiv,"appThemeHover")},applyThemeAltBkgd:function(a,c){g.remove(c||this.rootDiv,"appTheme");g.add(c||
this.rootDiv,"appTheme2");a&&g.add(c||this.rootDiv,"appThemeHover")}});dojo.declare("js.LGDependency",null,{constructor:function(){var a,c=this;this.dependencyId&&(a=this.lgById(this.dependencyId),this.onDependencyPrep(a),a.ready.then(function(){c.onDependencyReady()}))},onDependencyPrep:function(){return null},onDependencyReady:function(){return null}});dojo.declare("js.LGDefaults",null,{constructor:function(){this.defaultValues={};this.listenForDefaultsTrigger&&this.listenForDefaultsUpdate()},listenForDefaultsUpdate:function(){var a=
this;this.subscribeToMessage(this.listenForDefaultsTrigger,function(c){a.defaultValues=c;a.onDefaultsUpdate()})},onDefaultsUpdate:function(){return null},changeDefaults:function(){this.broadcastDefaultsUpdate()},broadcastDefaultsUpdate:function(){this.broadcastDefaultsPublish&&this.publishMessage(this.broadcastDefaultsPublish,this.defaultValues)}})})},"js/lgonlineCommand":function(){define("js/lgonlineCommand","dijit dojo/dom-construct dojo/dom dojo/on dojo/Deferred dojo/DeferredList dojo/dom-style dojo/dom-class dojo/_base/array dojo/_base/lang dojo/string dijit/form/TextBox dijit/layout/ContentPane esri/dijit/BasemapGallery esri/tasks/PrintTask esri/tasks/PrintParameters esri/tasks/PrintTemplate esri/dijit/PopupTemplate js/lgonlineBase js/lgonlineMap".split(" "),
function(l,h,n,k,g,b,e,f,a,c,m,q,p,r,s,t,u,v){dojo.declare("js.LGDropdownBox",js.LGGraphic,{constructor:function(){var d=this;this.applyTheme(!1);this.isShowable=!0;this.trigger&&(this.subscribeToMessage("command",function(a){a!==d.trigger&&d.setIsVisible(!1)}),this.subscribeToMessage(this.trigger,function(a){d.handleTrigger(a)}))},setShowable:function(d){this.isShowable=d;!this.isShowable&&this.getIsVisible()&&this.toggleVisibility()},handleTrigger:function(){this.isShowable&&this.toggleVisibility()}});
dojo.declare("js.LGMapBasedMenuBox",[js.LGDropdownBox,js.LGMapDependency],{constructor:function(){this.ready=new g},onDependencyReady:function(){this.ready.resolve(this);this.inherited(arguments)}});dojo.declare("js.LGBasemapBox",js.LGMapBasedMenuBox,{onDependencyReady:function(){var d,a,c=this.getBasemapGroup();d=this.rootId+"_gallery";a=(new p({id:d,className:this.galleryClass})).placeAt(this.rootDiv);touchScroll(d);d=(new r({showArcGISBasemaps:!0,basemapsGroup:c,bingMapsKey:this.mapObj.commonConfig.bingMapsKey,
map:this.mapObj.mapInfo.map},h.create("div"))).placeAt(this.rootDiv);a.set("content",d.domNode);d.startup();this.inherited(arguments)},getBasemapGroup:function(){var d=null;this.basemapgroupTitle&&(this.basemapgroupOwner&&0<this.basemapgroupTitle.length&&0<this.basemapgroupOwner.length)&&(d={title:this.basemapgroupTitle,owner:this.basemapgroupOwner});return d}});dojo.declare("js.LGCallMethods",js.LGObject,{constructor:function(){var d,c=this;this.todo&&a.forEach(this.todo,function(a){try{if(d=n.byId(a.rootId))if(d=
d.getLGObject())d[a.method](a.arg)}catch(b){c.log("LGCallMethods_1: "+b.toString())}})}});dojo.declare("js.LGButton",js.LGGraphic,{constructor:function(){var d;this.applyTheme(!0);this.iconUrl&&(d={src:this.iconUrl},this.iconClass&&(d.className=this.iconClass),this.iconImg=h.create("img",d,this.rootDiv));this.displayText&&(d={innerHTML:this.checkForSubstitution(this.displayText)},this.displayTextClass&&(d.className=this.displayTextClass),h.create("div",d,this.rootDiv));this.tooltip&&(this.rootDiv.title=
this.checkForSubstitution(this.tooltip))}});dojo.declare("js.LGRadioButton",js.LGButton,{constructor:function(){this.isOn=this.toBoolean(this.isOn,!1);this.setIsOn(this.isOn);this.controller=null;k(this.rootDiv,"click",this.handleClick)},setController:function(d){this.controller=d},setIsOn:function(d){(this.isOn=d)?this.applyThemeAltBkgd(!0):this.applyTheme(!0)},handleClick:function(d){d=d.currentTarget.getLGObject();d.controller&&d.controller.selectMember(d)}});dojo.declare("js.LGRadioButtonController",
js.LGObject,{constructor:function(){this.members=[];this.currentMember=null},addMember:function(d){this.members.push(d);d.setController(this)},selectMember:function(d){var c,b=this;this.currentMember&&(this.currentMember.setIsOn(!1),this.currentMember=null);"number"===typeof d?0<this.members.length&&(d=Math.max(0,Math.min(d,b.members.length-1)),b.currentMember=b.members[d],b.currentMember.setIsOn(!0)):"string"===typeof d?a.some(this.members,function(a){return a.value===d?(b.currentMember=a,b.currentMember.setIsOn(!0),
!0):!1}):d&&(c=d.rootId,a.some(this.members,function(d){return d.rootId===c?(b.currentMember=d,b.currentMember.setIsOn(!0),!0):!1}))},getCurrentMember:function(){return this.currentMember}});dojo.declare("js.LGCommand",[js.LGButton,js.LGDependency],{constructor:function(){this.publish&&(this.clickHandler=k(this.rootDiv,"click",this.handleClick))},onDependencyPrep:function(){this.setIsVisible(!1);this.inherited(arguments)},onDependencyReady:function(){this.setIsVisible(!0);this.inherited(arguments)},
handleClick:function(d){d=d.currentTarget.getLGObject();d.publishMessage("command",d.publish);d.publishMessage(d.publish,d.publishArg)}});dojo.declare("js.LGCommandToggle",js.LGCommand,{constructor:function(){var d=this;this.iconDisabledUrl=this.iconDisabledUrl||this.iconUrl;this.isEnabled=this.toBoolean(this.isEnabled,!0);d.setIsEnabled(this.isEnabled);this.isVisible=this.toBoolean(this.isVisible,!0);d.setIsVisible(this.isVisible);this.triggerEnable&&this.subscribeToMessage(this.triggerEnable,function(){d.isEnabled=
!0;d.setIsEnabled(d.isEnabled)});this.triggerDisable&&this.subscribeToMessage(this.triggerDisable,function(){d.isEnabled=!1;d.setIsEnabled(d.isEnabled)});this.triggerVisible&&this.subscribeToMessage(this.triggerVisible,function(){d.isVisible=!0;d.setIsVisible(d.isVisible)});this.triggerInvisible&&this.subscribeToMessage(this.triggerInvisible,function(){d.isVisible=!1;d.setIsVisible(d.isVisible)})},setIsEnabled:function(d){(this.isEnabled=d)?(this.iconImg.src=this.iconUrl,f.add(this.rootDiv,"appThemeHover")):
(this.iconImg.src=this.iconDisabledUrl,f.remove(this.rootDiv,"appThemeHover"))},handleClick:function(d){var a=d.currentTarget.getLGObject();a.isEnabled&&a.inherited("handleClick",arguments)}});dojo.declare("js.LGLaunchUrl",js.LGObject,{constructor:function(){this.subscribeToMessage(this.sameWinTrigger,function(d){d&&window.open(d,"_parent")});this.subscribeToMessage(this.newWinTrigger,function(d){d&&window.open(d,"_blank")})}});dojo.declare("js.LGPrintMap",js.LGMapBasedMenuBox,{constructor:function(){var d,
a=this;this.radioButtonController=new js.LGRadioButtonController;d=new js.LGRadioButton({rootId:this.rootId+"_landscape",parentDiv:this.rootId,iconUrl:this.landscapeButtonIconUrl,rootClass:this.orientationButtonClass,iconClass:this.orientationButtonIconClass,tooltip:this.checkForSubstitution(this.landscapeButtonTooltip),value:this.landscapeServerSpec});d.setIsVisible(!0);this.radioButtonController.addMember(d);e.set(d.rootDiv,"display","inline-block");d=new js.LGRadioButton({rootId:this.rootId+"_portrait",
parentDiv:this.rootId,iconUrl:this.portraitButtonIconUrl,rootClass:this.orientationButtonClass,iconClass:this.orientationButtonIconClass,tooltip:this.checkForSubstitution(this.portraitButtonTooltip),value:this.portraitServerSpec});d.setIsVisible(!0);this.radioButtonController.addMember(d);e.set(d.rootDiv,"display","inline-block");this.titleEntryTextBox=(new q({id:this.rootId+"_titleEntry",value:this.title,trim:!0,placeHolder:this.titleHint})).placeAt(this.rootId);e.set(this.titleEntryTextBox.domNode,
"width","97%");f.add(this.titleEntryTextBox.domNode,this.titleClass);this.authorEntryTextBox=(new q({id:this.rootId+"_authorEntry",value:this.author,trim:!0,placeHolder:this.authorHint})).placeAt(this.rootId);e.set(this.authorEntryTextBox.domNode,"width","97%");f.add(this.authorEntryTextBox.domNode,this.authorClass);d=new js.LGButton({rootId:this.rootId+"_doPrint",parentDiv:this.rootId,iconUrl:this.printButtonIconUrl,rootClass:this.printButtonClass,iconClass:this.printButtonIconClass,tooltip:this.checkForSubstitution(this.printButtonTooltip)});
d.setIsVisible(!0);e.set(d.rootDiv,"display","inline-block");this.radioButtonController.selectMember(0);k(d.rootDiv,"click",function(){var d,c;a.publishMessage(a.publishWorking);a.setIsVisible(!1);d=(d=a.radioButtonController.getCurrentMember())?d.value:null;c=new t;c.map=a.mapObj.mapInfo.map;c.outSpatialReference=a.mapObj.mapInfo.map.spatialReference;c.template=new u;c.template.format=a.format||"PDF";c.template.layout=d||a.layout||"Letter ANSI A Landscape";c.template.layoutOptions={titleText:a.titleEntryTextBox.value,
authorText:a.authorEntryTextBox.value,copyrightText:a.copyrightText};c.template.preserveScale=a.toBoolean(a.preserveScale,!1);c.template.showAttribution=!0;a.printTask.execute(c,function(d){a.publishMessage(a.publishReady);a.publishMessage(a.publishPrintUrl,d.url)},function(d){a.publishMessage(a.publishReady);a.log("Print failed: "+d.message,!0)})})},checkPrerequisites:function(){if(this.commonConfig.helperServices&&this.commonConfig.helperServices.printTask&&this.commonConfig.helperServices.printTask.url)this.printTask=
new s(this.commonConfig.helperServices.printTask.url,{async:!1});else throw this.log("no print task configured"),"no print task configured";}});dojo.declare("js.LGFetchPrintedMap",[js.LGObject,js.LGMapDependency],{constructor:function(){this.fetchPrintUrl=null;this.printAvailabilityTimeoutMinutes=this.toNumber(this.printAvailabilityTimeoutMinutes,10);this.printTimeouter=null},onDependencyReady:function(){var d=this;this.subscribeToMessage(this.triggerPrintUrl,function(a){clearTimeout(d.printTimeouter);
d.fetchPrintUrl=a;d.publishMessage(d.publishPrintAvailable);0<d.printAvailabilityTimeoutMinutes&&(d.printTimeouter=setTimeout(function(){d.publishMessage(d.publishPrintNotAvailable)},6E4*d.printAvailabilityTimeoutMinutes))});this.subscribeToMessage(this.trigger,function(){null!==d.fetchPrintUrl&&d.publishMessage(d.publish,d.fetchPrintUrl)})}});dojo.declare("js.LGLocate",js.LGObject,{constructor:function(){var d=this,a;this.ready=new g;Modernizr.geolocation?(this.subscribeToMessage(this.trigger,function(){a=
setTimeout(function(){alert(d.checkForSubstitution("@messages.geolocationTimeout"))},16E3);navigator.geolocation.getCurrentPosition(function(c){clearTimeout(a);d.log("go to "+c.coords.latitude+" "+c.coords.longitude);d.publishMessage(d.publish,new esri.geometry.Point(c.coords.longitude,c.coords.latitude,new esri.SpatialReference({wkid:4326})))},function(c){clearTimeout(a);switch(c.code){case c.PERMISSION_DENIED:c=d.checkForSubstitution("@messages.geolocationDenied");break;case c.TIMEOUT:c=d.checkForSubstitution("@messages.geolocationTimeout");
break;default:c=d.checkForSubstitution("@messages.geolocationUnavailable")}alert(c)},{timeout:8E3})}),this.ready.resolve(d)):this.ready.reject(d)}});dojo.declare("js.LGSearch",js.LGObject,{constructor:function(){this.busyIndicator&&(this.busyIndicator=this.lgById(this.busyIndicator))},search:function(){return null},toList:function(){return[]},publish:function(d,a){this.publishMessage(d,a)},sortByLabel:function(d,a){var c=0;d&&(a&&d.label&&a.label)&&(c=d.label.localeCompare(a.label));return c},getRepresentativePoint:function(a){var c;
"point"===a.type?c=a:"polygon"===a.type?(c=a.getExtent().getCenter(),a.contains(c)||(c=a.getPoint(0,0))):"polyline"===a.type&&(c=a.getPoint(0,0));return c}});dojo.declare("js.LGSearchAddress",[js.LGSearch,js.LGMapDependency],{constructor:function(){this.searcher=new esri.tasks.Locator(this.searchUrl);this.searcher.outSpatialReference=new esri.SpatialReference({wkid:this.outWkid});this.params={};this.params.outFields=this.outFields;this.ready=new g},onDependencyReady:function(){this.params.searchExtent=
this.mapObj.mapInfo.map.extent;this.ready.resolve(this);this.inherited(arguments)},search:function(a,c,b){this.params.address={};this.params.address[this.addressParamName]=a;this.searcher.addressToLocations(this.params,c,b)},toList:function(d){var c,b=this,f=[];d&&a.forEach(d,function(d){c=!1;d.score>=b.minimumScore&&(b.validLocators?a.some(b.validLocators,function(a){if(d.attributes.Loc_name===a)return c=!0}):c=!0);c&&f.push({label:d.address,data:new esri.geometry.Point(d.location.x,d.location.y,
new esri.SpatialReference({wkid:102100}))})});return f},publish:function(a,c){this.publishMessage(a,c)}});dojo.declare("js.LGSearchFeatureLayer",[js.LGSearch,js.LGMapDependency],{constructor:function(){if(!this.searchPattern||0>this.searchPattern.indexOf("${1}"))this.searchPattern="%${1}%";this.caseInsensitiveSearch=this.toBoolean(this.caseInsensitiveSearch,!0);this.ready=new g},onDependencyReady:function(){var d,c,b,f=",",e,g=null,h=this;try{if(d=this.mapObj.getLayer(this.searchLayerName),!d||!d.url)c=
this.checkForSubstitution("@messages.searchLayerMissing");else{this.searchURL=d.url;a.forEach(d.fields,function(a){f+=a.name+","});a.every(this.searchFields,function(a){c=a;return 0<=f.indexOf(","+a+",")})||(b='"'+c+'"<br>',b+=this.checkForSubstitution("@messages.searchFieldMissing")+"<br><hr><br>",b+=this.checkForSubstitution("@prompts.layerFields")+"<br>",1<f.length&&(b+=f.substring(1,f.length-1)),this.log(b,!0));this.objectIdField=d.objectIdField;this.publishPointsOnly="boolean"===typeof this.publishPointsOnly?
this.publishPointsOnly:!0;this.searcher=new esri.tasks.QueryTask(this.searchURL);this.generalSearchParams=new esri.tasks.Query;this.generalSearchParams.returnGeometry=!1;this.generalSearchParams.outSpatialReference=this.mapObj.mapInfo.map.spatialReference;this.generalSearchParams.outFields=[d.objectIdField].concat(this.searchFields);this.objectSearchParams=new esri.tasks.Query;this.objectSearchParams.returnGeometry=!0;this.objectSearchParams.outSpatialReference=this.mapObj.mapInfo.map.spatialReference;
this.objectSearchParams.outFields=["*"];e=this.mapObj.mapInfo.itemInfo.itemData.operationalLayers;a.some(e,function(a){return a.title===h.searchLayerName?(g=new v(a.popupInfo),!0):!1});this.mapObj.setPopup(g);this.log("Search layer "+this.searchLayerName+" set up for queries");this.ready.resolve(this);this.inherited(arguments);return}}catch(k){c=k.toString()}b='"'+this.searchLayerName+'"<br>';b+=c+"<br><hr><br>";b+=this.checkForSubstitution("@prompts.mapLayers")+"<br><ul>";a.forEach(this.mapObj.getLayerNameList(),
function(a){b+='<li>"'+a+'"</li>'});b+="</ul>";this.log(b,!0);this.ready.reject(this);this.inherited(arguments)},checkPrerequisites:function(){var d,c=this;if(this.searchFields&&0<this.searchFields.length)d=this.searchFields.split(","),this.searchFields=[],a.forEach(d,function(a){c.searchFields.push(a.trim())});else throw this.log("missing search fields"),"missing search fields";},search:function(d,c,b){var f,e="",g,h="";!0===this.caseInsensitiveSearch?(f=d.toUpperCase(),g="UPPER(${0}) LIKE '"+this.searchPattern+
"'"):(f=d,g="${0} LIKE '"+this.searchPattern+"'");f=f.replace(/'/g,"''");a.forEach(this.searchFields,function(a){e=e+h+dojo.string.substitute(g,[a,f]);h="  OR  "});0<e.length&&(this.generalSearchParams.where=e,this.searcher.execute(this.generalSearchParams,c,b))},toList:function(d,c){var b=this,f=[],e,g,h=c.toUpperCase();d&&(d.features&&0<d.features.length)&&(a.forEach(d.features,function(d){g="";a.some(b.searchFields,function(a){return d.attributes[a]&&(e=d.attributes[a].toString(),0<=e.toUpperCase().indexOf(h))?
(g=e,!0):!1});""===g&&(g="result");f.push({label:g,data:d.attributes[b.objectIdField]})}),f.sort(b.sortByLabel));return f},publish:function(a,c){var b,f,e=this;this.busyIndicator&&this.busyIndicator.setIsVisible(!0);this.objectSearchParams.where=this.objectIdField+"="+c;this.searcher.execute(this.objectSearchParams,function(c){c&&c.features&&0<c.features.length?(b=c.features[0],f=e.publishPointsOnly?e.getRepresentativePoint(b.geometry):b,e.publishMessage(a,f)):e.log("LGSearchFeatureLayer_1: no results");
e.busyIndicator&&e.busyIndicator.setIsVisible(!1)},function(a){e.log("LGSearchFeatureLayer_2: "+a.message);e.busyIndicator&&e.busyIndicator.setIsVisible(!1)})}});dojo.declare("js.LGSearchMultiplexer",js.LGSearch,{constructor:function(){var d=this,c=[];this.ready=new g;this.searchers=[];this.searcherNames&&a.forEach(this.searcherNames,function(a){if(a=d.lgById(a))d.searchers.push(a),c.push(a.ready)});(new b(c)).then(function(a){!a[0]||!a[1]?d.ready.reject(d):d.ready.resolve(d)})},search:function(d,
c,f){var e=[],h=[];a.forEach(this.searchers,function(c,b){var f=new g;h.push(f);c.search(d,function(g){g=c.toList(g,d);g=a.map(g,function(a){return{data:{iSearcher:b,itemData:a.data},label:a.label}});e=e.concat(g);f.resolve()},function(a){f.reject(a)})});(new b(h)).then(function(d){var b=!0;f&&(b=!a.some(d,function(a){return!a[0]?(f(a[1]),!0):!1}));b&&c&&c(e)})},toList:function(a){return a},publish:function(a,c){this.searchers[c.iSearcher].publish(a,c.itemData)}});dojo.declare("js.LGSearchBoxByText",
js.LGDropdownBox,{constructor:function(){var d=this,c,b,f,g,l,p,m;c=this.rootId+"_entry";h.create("label",{"for":c,innerHTML:this.checkForSubstitution(this.showPrompt)},this.rootId);this.searchEntryTextBox=(new q({id:c,value:"",trim:!0,placeHolder:this.hint,intermediateChanges:!0})).placeAt(this.rootId);e.set(this.searchEntryTextBox.domNode,"width","99%");c=h.create("div",{className:this.resultsListBoxClass},this.rootId);b=h.create("table",{className:this.resultsListTableClass},c);f=h.create("tbody",
{className:this.resultsListBodyClass},b);touchScroll(c);g=this.lgById(this.searcher);l="";p=0;m=null;k(this.searchEntryTextBox,"change",function(){var c=d.searchEntryTextBox.get("value");l!==c&&(l=c,h.empty(f),clearTimeout(m),0<c.length&&(m=setTimeout(function(){var b,e,m;b=h.create("tr",null,f);h.create("td",{className:d.resultsListSearchingClass},b);e=p=(new Date).getTime();g.search(c,function(b){e<p||(h.empty(f),b=g.toList(b,c),m=(new Date).getTime(),d.log("retd "+b.length+" items in "+(m-e)/1E3+
" secs"),0<b.length&&a.forEach(b,function(a){var c;c=h.create("tr",null,f);c=h.create("td",{className:d.resultsListEntryClass,innerHTML:a.label},c);d.applyTheme(!0,c);k(c,"click",function(){g.publish(d.publish,a.data)})}))},function(a){d.log("LGSearchBoxByText_1: "+a.message);l="";h.empty(f)})},1E3)))})},toggleVisibility:function(){this.inherited(arguments);this.getIsVisible()&&this.searchEntryTextBox.focus()}});dojo.declare("js.LGShare",js.LGObject,{constructor:function(){var a=this;this.busyIndicator&&
(this.busyIndicator=this.lgById(this.busyIndicator));this.subscribeToMessage(this.trigger,function(){a.share()})},share:function(){var a=this,c,b;c=encodeURIComponent(this.getSubject());b=encodeURIComponent(this.getUrlToShare());this.tinyURLServiceURL&&0<this.tinyURLServiceURL.length?(this.busyIndicator&&this.busyIndicator.setIsVisible(!0),b=esri.substitute({url:b},this.tinyURLServiceURL),esri.request({url:b,handleAs:"json"},{useProxy:!1}).then(function(b){var f,e;try{if(f=a.followAttributePath(b,
a.tinyURLResponseAttribute))e=esri.substitute({subject:c,url:f},a.shareUrl),a.publishMessage(a.publish,e)}catch(g){a.log("LGShare_1: "+g.toString())}a.busyIndicator&&a.busyIndicator.setIsVisible(!1)},function(c){a.log("LGShare_2: "+c.toString());a.busyIndicator&&a.busyIndicator.setIsVisible(!1)})):(b=esri.substitute({subject:c,url:b},this.shareUrl),this.publishMessage(this.publish,b))},getSubject:function(){return""},getUrlToShare:function(){return this.getAppUrl()},getAppUrl:function(){return window.location.toString()}});
dojo.declare("js.LGShareAppExtents",[js.LGShare,js.LGMapDependency],{getSubject:function(){var a="";this.subject&&(a=this.checkForSubstitution(this.subject));return a},getUrlToShare:function(){var a=this.getAppUrl();return a+(0>a.indexOf("?")?"?":"&")+this.getMapExtentsArg()},getMapExtentsArg:function(){return"ex="+this.mapObj.getMapExtentsAsString()}});dojo.declare("js.LGFilterLayers1",js.LGMapBasedMenuBox,{constructor:function(){this.layers=[]},onDependencyReady:function(){var d;this.fieldname1&&
(a.forEach(this.mapObj.mapInfo.itemInfo.itemData.operationalLayers,c.hitch(this,function(a){var c;if(a.layerObject&&"Feature Layer"===a.layerObject.type)for(c=0;c<a.layerObject.fields.length;c+=1)if(a.layerObject.fields[c].name===this.fieldname1){a={layerObject:a.layerObject,fieldType:a.layerObject.fields[c].type};this.layers.push(a);break}})),this.applyFilter(),h.create("label",{innerHTML:this.hint1},h.create("div",{},this.rootId)),d=(new q({id:this.rootId+"_field1",value:this.value1,trim:!0,placeHolder:this.hint1,
intermediateChanges:!0})).placeAt(this.rootId),e.set(d.domNode,"width","99%"),this.tooltip&&d.set("title",this.checkForSubstitution(this.tooltip)),k(d,"change",c.hitch(this,function(){this.value1=d.value.trim();this.onValueChanged()})))},onValueChanged:function(){this.applyFilter()},applyFilter:function(){a.forEach(this.layers,c.hitch(this,function(a){this.setLayerDefinitionExpression(a.layerObject,a.fieldType);a.layerObject.clearSelection()}))},setLayerDefinitionExpression:function(a,c){var b=a.defaultDefinitionExpression;
try{this.value1&&""!==this.value1&&("esriFieldTypeString"===c?b=m.substitute(this.defnExpression,{fieldname1:this.fieldname1,value1:"'"+this.value1+"'"}):"esriFieldTypeInteger"===c&&(b=m.substitute(this.defnExpression,{fieldname1:this.fieldname1,value1:this.value1}))),a.setDefinitionExpression(b)}catch(f){}}});dojo.declare("js.LGFilterLayers1WithDefaults",[js.LGFilterLayers1,js.LGDefaults],{constructor:function(){this.changeDefaults()},onValueChanged:function(){this.inherited(arguments);this.changeDefaults()},
changeDefaults:function(){this.defaultValues.value1=this.value1;this.defaultValues.fieldname1=this.fieldname1;this.inherited(arguments)}})})},"js/lgonlineDrawing":function(){define("js/lgonlineDrawing",["dojo/Deferred","dojo/_base/Color","js/lgonlineMap"],function(l,h){dojo.declare("js.LGHighlighter",[js.LGObject,js.LGMapDependency],{onDependencyReady:function(){var l,k,g=this;this.highlighterLayer=g.mapObj.createGraphicsLayer("highlighterLayer");this.lineHiliteColor=new h(this.lineHiliteColor?this.lineHiliteColor:
"#0000ff");this.fillHiliteColor=new h(this.fillHiliteColor?this.fillHiliteColor:[0,0,255,0.1]);this.intervalID=this.intervalTerminator=null;this.subscribeToMessage("highlightItem",function(b){var e,f,a;b&&(e=b.geometry?b.geometry:b,b.attributes&&(f=b.attributes),b.infoTemplate&&(a=b.infoTemplate),b=g.createHighlightGraphics(e,f,a),k=(l=e.getExtent())?l.getCenter():e,g.showHighlight(b,k,g.highlightZoomLevel,f&&g.showFeaturePopup))})},createHighlightGraphics:function(h,k,g){var b,e=[];if("polyline"===
h.type)e.push(new esri.Graphic(h,new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,this.lineHiliteColor,3),k,g));else if("point"===h.type)for(b=0;4>=b;++b)e.push(new esri.Graphic(h,new esri.symbol.SimpleMarkerSymbol(esri.symbol.SimpleMarkerSymbol.STYLE_CIRCLE,2.5*(b+16),new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,new dojo.Color(this.lineHiliteColor),3),new dojo.Color([0,0,0,0])),k,g));else e.push(new esri.Graphic(h,new esri.symbol.SimpleFillSymbol(esri.symbol.SimpleFillSymbol.STYLE_SOLID,
new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,this.lineHiliteColor,3),this.fillHiliteColor),k,g));return e},showHighlight:function(h,k,g,b){var e,f,a,c,m=this;k?e=this.mapObj.centerAt(k):(e=new l,e.resolve());e.then(function(){g?f=m.mapObj.setZoom(g):(f=new l,f.resolve());f.then(function(){1<h.length?(m.intervalTerminator&&(clearTimeout(m.intervalTerminator),clearInterval(m.intervalID)),a=0,c=!0,m.intervalID=setInterval(function(){m.highlighterLayer.clear();m.highlighterLayer.add(h[a]);
c?++a:--a;a===h.length?(c=!1,--a):0>a&&(c=!0,a=0)},120),m.intervalTerminator=setTimeout(function(){clearInterval(m.intervalID);m.intervalTerminator=null;m.intervalID=null;m.highlighterLayer.clear()},5E3)):(m.highlighterLayer.clear(),m.highlighterLayer.add(h[0]));b&&m.mapObj.showPopupWithFeature(k,h[0])})})}})})},"js/lgonlineEditing":function(){define("js/lgonlineEditing","dojo/dom-construct dojo/on dojo/_base/array dojo/_base/lang dojo/aspect esri/dijit/editing/TemplatePicker esri/dijit/editing/Editor js/lgonlineBase js/lgonlineMap js/lgonlineCommand".split(" "),
function(l,h,n,k,g,b,e){dojo.declare("js.LGEditTemplatePicker",js.LGMapBasedMenuBox,{constructor:function(){var b;b=dojo.byId(this.colorizerId).getLGObject();b=".templatePicker{border:1px solid transparent!important;}.templatePicker .dojoxGrid{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridScrollbox{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridRow{background-color:transparent;}.templatePicker .dojoxGrid .dojoxGridCell{border:1px solid transparent}.templatePicker .dojoxGrid .dojoxGridRow{border:1px solid transparent}.templatePicker .grid .dojoxGridRowOver{background-color:transparent;color:inherit;}.templatePicker .grid .dojoxGridRowOver .dojoxGridCell{background-color:transparent;color:inherit;}.templatePicker .dojoxGrid .dojoxGridCellFocus{border:1px solid transparent!important;}.templatePicker .dojoxGrid .dojoxGridRowOdd{background-color:transparent;}.templatePicker .dojoxGrid .selectedItem{border:1px solid transparent!important;color:"+
b.foregroundColor()+"!important;background-color:"+b.alternateBackgroundColor()+"!important}";this.injectCSS(b)},onDependencyReady:function(){var f=this,a,c,h;a=this.mapObj.mapInfo;this.layerInfos=[];this.layers=[];n.forEach(a.itemInfo.itemData.operationalLayers,k.hitch(this,function(a){var c=a.layerObject;c instanceof esri.layers.FeatureLayer&&c.isEditable()&&!(a.capabilities&&"Query"===a.capabilities)&&(this.layerInfos.push({featureLayer:c}),this.layers.push(c))}));0===this.layers.length?this.setShowable(!1):
(c=a.map,this.setIsVisible(!1,!0),a=l.create("div",{className:this.templatePickerHolderClass}),l.place(a,this.rootId),h=l.create("div"),l.place(h,a),h=new b({featureLayers:this.layers,rows:"auto",columns:2,grouping:!0},h),h.startup(),touchScroll(a),this.setIsVisible(!1,!1),c={map:c,templatePicker:h,toolbarVisible:!1,layerInfos:this.layerInfos},h=l.create("div"),l.place(h,a),a=new e({settings:c},h),a.startup(),g.before(a,"_applyEdits",function(a){n.forEach(a,function(a){a.adds&&f.preprocessEditAdds(a);
a.updates&&f.preprocessEditUpdates(a);a.deletes&&f.preprocessEditDeletes(a)})}));this.inherited(arguments)},preprocessEditAdds:function(b){return b},preprocessEditUpdates:function(b){return b},preprocessEditDeletes:function(b){return b}});dojo.declare("js.LGEditTemplatePickerWithDefaults",[js.LGEditTemplatePicker,js.LGDefaults],{preprocessEditAdds:function(b){b.adds[0].attributes[this.defaultValues.fieldname1]=this.defaultValues.value1;return b}});dojo.declare("js.LGEditAttributes",[js.LGObject,js.LGMapDependency],
{onDependencyReady:function(){this.inherited(arguments);this.clickHandle=this.subscribeToMessage("mapClick",function(b){console.log(b.type)})}})})},"js/lgonlineFrame":function(){define("js/lgonlineFrame","dojo/dom-construct dojo/on dojo/dom-style dojo/_base/array dojo/_base/lang js/lgonlineBase".split(" "),function(l,h,n,k,g){dojo.declare("js.LGColorizer",js.LGObject,{constructor:function(){var b,e="",f=this,a=["#fff","#333333","#5d5d5d","#5d5d5d"];this.colors=[];k.some(this.colorTable,function(a){return f.theme===
a.theme?(f.colors=a.colors,!0):!1});if(this.colors.length<a.length)for(b=this.colors.length;b<a.length;b+=1)this.colors.push(a[b]);e+=".appTheme{color:"+this.colors[0]+";background-color:"+this.colors[1]+"}";e+=".appTheme2{color:"+this.colors[0]+";background-color:"+this.colors[3]+"}";e+=".appThemeHover:hover{background-color:"+this.colors[2]+"}";this.injectCSS(e)},foregroundColor:function(){return this.colors[0]},backgroundColor:function(){return this.colors[1]},hoverColor:function(){return this.colors[2]},
alternateBackgroundColor:function(){return this.colors[3]}});dojo.declare("js.LGFrame",js.LGGraphic,{constructor:function(){var b;b={};this.headerDivId&&(b.id=this.headerDivId);this.headerDivClass&&(b.className=this.headerDivClass);this.headerDiv=l.create("div",b,this.rootDiv);this.applyTheme(!1,this.headerDiv);b={};this.contentDivId&&(b.id=this.contentDivId);this.contentDivClass&&(b.className=this.contentDivClass);this.contentDiv=l.create("div",b,this.rootDiv);this.handleWindowResize()},handleWindowResize:function(){this.inherited(arguments);
this.resizeContentDiv()},resizeContentDiv:function(){var b,e,f;this.headerDiv&&this.contentDiv&&(b=dojo.marginBox(this.rootDiv),e=dojo.marginBox(this.headerDiv),f=b.h-e.h,0<f&&(f={},f.top=e.h+"px",f.height=b.h-e.h+"px",n.set(this.contentDiv,f)))}});dojo.declare("js.LGGallery",js.LGGraphic,{constructor:function(){var b,e=this;b=l.create("table",null,this.rootDiv);this.applyTheme(!1,b);h(window,"resize",g.hitch(this,this.handleParentResize));this.rootDiv.getContentDiv=function(){return e.addItem()};
b=l.create("tbody",null,b);this.galleryRow=l.create("tr",null,b);b={innerHTML:"&lt;",style:{visibility:"hidden"}};this.arrowClass&&(b.className=this.arrowClass);this.leftArrow=l.create("td",b,this.galleryRow);this.applyTheme(!0,this.leftArrow);h(this.leftArrow,"click",g.hitch(this,this.shiftLeft));b.innerHTML="&gt;";this.rightArrow=l.create("td",b,this.galleryRow);this.applyTheme(!0,this.rightArrow);h(this.rightArrow,"click",g.hitch(this,this.shiftRight));this.zeroItemWidth=dojo.marginBox(this.rootDiv).w;
this.numItemsToDisplay=this.iFirstItem=this.numItems=this.itemWidth=0;this.firstItem=null;this.handleParentResize()},addItem:function(b){var e;e={};"string"===typeof b&&(e.innerHTML=b);this.itemClass&&(e.className=this.itemClass);e=l.create("td",e);"string"!==typeof b&&e.appendChild(b);this.galleryRow.insertBefore(e,this.rightArrow);this.numItems+=1;this.firstItem||(this.firstItem=e,this.itemWidth=dojo.marginBox(e).w);this.handleParentResize();return e},clearItems:function(){for(;2<this.galleryRow.childNodes.length;)this.galleryRow.removeChild(this.galleryRow.childNodes[1]);
this.numItemsToDisplay=this.iFirstItem=this.numItems=0;this.firstItem=null;this.handleParentResize()},handleParentResize:function(){var b,e;0===this.zeroItemWidth&&(this.zeroItemWidth=dojo.marginBox(this.rootDiv).w);b=dojo.marginBox(this.rootDiv.parentNode).w;e=this.zeroItemWidth+this.numItems*this.itemWidth;0!==this.numItems&&(e>b?(this.leftArrow.style.visibility="visible",this.rightArrow.style.visibility="visible",this.numItemsToDisplay=Math.max(Math.floor((b-this.zeroItemWidth)/this.itemWidth),
1)):(this.leftArrow.style.visibility="hidden",this.rightArrow.style.visibility="hidden",this.numItemsToDisplay=this.numItems),this.iFirstItem=Math.min(this.iFirstItem,this.numItems-this.numItemsToDisplay),this.drawGallery())},shiftLeft:function(){this.iFirstItem=Math.min(this.iFirstItem+1,this.numItems-this.numItemsToDisplay);this.drawGallery()},shiftRight:function(){this.iFirstItem=Math.max(this.iFirstItem-1,0);this.drawGallery()},drawGallery:function(){var b,e=this.iFirstItem,f=this.iFirstItem+
this.numItemsToDisplay,a=this.firstItem;this.leftArrow.style.visibility="hidden";this.rightArrow.style.visibility="hidden";for(b=0;b<e;)this.rightArrow.style.visibility="visible",a.style.display="none",a=a.nextSibling,b+=1;for(;b<f;)a.style.display="",a=a.nextSibling,b+=1;for(;b<this.numItems;)this.leftArrow.style.visibility="visible",a.style.display="none",a=a.nextSibling,b+=1;this.handleWindowResize()}});dojo.declare("js.LGTitleBar",js.LGGraphic,{constructor:function(){var b;this.iconUrl&&0<this.iconUrl.length&&
(b={src:this.iconUrl},this.iconClass&&(b.className=this.iconClass),l.create("img",b,this.rootDiv));this.title&&0<this.title.length&&(b={innerHTML:this.title},this.titleClass&&(b.className=this.titleClass),l.create("span",b,this.rootDiv),document.title=this.title);this.handleWindowResize()}})})},"js/lgonlineMap":function(){define("js/lgonlineMap","dojo/dom-construct dojo/on dojo/_base/lang dojo/_base/array dojo/Deferred esri/arcgis/utils esri/dijit/Popup js/lgonlineBase".split(" "),function(l,h,n,
k,g,b,e){dojo.declare("js.LGMapDependency",js.LGDependency,{onDependencyPrep:function(b){this.mapObj=b;this.inherited(arguments)}});dojo.declare("js.LGMap",js.LGGraphic,{constructor:function(){var f,a=null,c=this;this.ready=new g;f={ignorePopups:this.toBoolean(this.ignorePopups,!1)};f.mapOptions=this.mapOptions||{};f.mapOptions.showAttribution=!0;this.popup=new e(null,l.create("div"));f.mapOptions.infoWindow=this.popup;if(this.xmin&&this.ymin&&this.xmax&&this.ymax)try{a={xmin:this.xmin,ymin:this.ymin,
xmax:this.xmax,ymax:this.ymax,spatialReference:{}},a.spatialReference.wkid=this.wkid?Number(this.wkid):102100,a=new esri.geometry.Extent(a)}catch(k){a=null}this.ex&&(a=this.getExtentsFromString(this.ex));this.commonConfig&&this.commonConfig.bingMapsKey&&(f.bingMapsKey=this.commonConfig.bingMapsKey);this.webmap&&(this.mapId=this.webmap);b.createMap(this.mapId,this.rootDiv,f).then(function(b){c.mapInfo=b;b.map.spatialReference||(c.mapInfo.map.spatialReference=new esri.SpatialReference({wkid:102100}));
h(window,"resize",n.hitch(c.mapInfo.map,function(){c.mapInfo.map.resize();c.mapInfo.map.reposition()}));a&&(a.spatialReference.wkid!==c.mapInfo.map.spatialReference.wkid?esri.config.defaults.geometryService?(b=new esri.tasks.ProjectParameters,b.geometries=[a],b.outSR=c.mapInfo.map.spatialReference,esri.config.defaults.geometryService.project(b).then(function(b){a=b[0];c.mapInfo.map.setExtent(a)})):c.log("LGMap_1: Need geometry service to convert extents from wkid "+a.spatialReference.wkid+" to map's "+
c.mapInfo.map.spatialReference.wkid):c.mapInfo.map.setExtent(a));c.tempGraphicsLayer=c.createGraphicsLayer("tempGraphicsLayer");c.positionHandle=c.subscribeToMessage("position",function(a){var b;a.spatialReference.wkid===c.mapInfo.map.spatialReference.wkid?c.publishMessage("highlightItem",a):4326===a.spatialReference.wkid&&102100===c.mapInfo.map.spatialReference.wkid?(a=esri.geometry.geographicToWebMercator(a),c.publishMessage("highlightItem",a)):esri.config.defaults.geometryService?(b=new esri.tasks.ProjectParameters,
b.geometries=[a],b.outSR=c.mapInfo.map.spatialReference,esri.config.defaults.geometryService.project(b).then(function(b){a=b[0];c.publishMessage("highlightItem",a)})):c.log("LGMap_1: Need geometry service to convert position from wkid "+a.spatialReference.wkid+" to map's "+c.mapInfo.map.spatialReference.wkid)});c.showFeatureHandle=c.subscribeToMessage("showFeature",function(a){c.popupTemplate&&(a.infoTemplate=c.popupTemplate);c.publishMessage("highlightItem",a)});c.clickHandle=h(c.mapInfo.map,"click",
function(a){c.publishMessage("mapClick",a.mapPoint)});c.ready.resolve(c)},function(){c.ready.reject(c)})},mapInfo:function(){return this.mapInfo},setPopup:function(b){this.popupTemplate=b},showPopupWithFeature:function(b,a){this.popup.clearFeatures();this.popup.setContent(a.getContent());this.mapInfo.map.infoWindow.show(this.mapInfo.map.toScreen(b))},setExtent:function(b){return this.mapInfo.map.setExtent(b)},centerAt:function(b){return this.mapInfo.map.centerAt(b)},setZoom:function(b){var a=this.mapInfo.map.getMinZoom(),
c=this.mapInfo.map.getMaxZoom();0<=a&&0<=c&&(b=Math.max(a,Math.min(c,b)));return this.mapInfo.map.setZoom(b)},getMapExtentsAsString:function(){var b="";this.mapInfo&&this.mapInfo.map&&(b=this.getStringFromExtents(this.mapInfo.map.extent));return b},getStringFromExtents:function(b){return b.xmin.toFixed().toString()+","+b.ymin.toFixed().toString()+","+b.xmax.toFixed().toString()+","+b.ymax.toFixed().toString()+","+b.spatialReference.wkid.toString()},getExtentsFromString:function(b){var a,c=null;a=
b.split(",");1===a.length&&(a=b.split("%2C"));try{c={xmin:Number(a[0]),ymin:Number(a[1]),xmax:Number(a[2]),ymax:Number(a[3]),spatialReference:{}},c.spatialReference.wkid=4<a.length?Number(a[4]):102100,c=new esri.geometry.Extent(c)}catch(e){c=null}return c},getLayer:function(b){var a;k.some(this.mapInfo.itemInfo.itemData.operationalLayers,function(c){return c.title===b?(a=c.layerObject,!0):!1});return a},getLayerNameList:function(){var b=[];k.forEach(this.mapInfo.itemInfo.itemData.operationalLayers,
function(a){b.push(a.title)});return b},getOperationalLayers:function(){return this.mapInfo.itemInfo.itemData.operationalLayers},createGraphicsLayer:function(b){var a=new esri.layers.GraphicsLayer;a.id=b;return this.mapInfo.map.addLayer(a)},enablePopups:function(){this.mapInfo&&this.mapInfo.clickEventListener&&(this.mapInfo.clickEventHandle=h(this.mapInfo.map,"click",this.mapInfo.clickEventListener))},disablePopups:function(){this.mapInfo&&this.mapInfo.clickEventHandle&&this.mapInfo.clickEventHandle.remove()}})})},
"js/lgonlineOutput":function(){define("js/lgonlineOutput",["dojo/dom-construct","dojo/dom-class","dojo/_base/array","dojo/topic","js/lgonlineBase"],function(l,h,n,k){dojo.declare("js.LGNotes",js.LGObject,{constructor:function(){console&&this.notes&&n.forEach(this.notes,function(g){console.log(g)})}});dojo.declare("js.LGBusy",js.LGGraphic,{constructor:function(){this.busyImageClass&&h.add(this.rootDiv,this.busyImageClass)}});dojo.declare("js.LGLogBox",js.LGDropdownBox,{constructor:function(){window.gLogMessageBox=
this;touchScroll(this.rootDiv)},append:function(g){"string"===typeof g?l.create("div",{innerHTML:g,style:"margin:2px"},this.rootDiv):"object"===typeof g&&null!==g&&this.rootDiv.appendChild(g)}});dojo.declare("js.LGMessageBox",js.LGDropdownBox,{constructor:function(){this.content&&0<this.content.length&&(this.rootDiv.innerHTML=this.content);touchScroll(this.rootDiv)}});dojo.declare("js.LGPublishEcho",js.LGDropdownBox,{handleTrigger:function(g){this.rootDiv.innerHTML=g.toString();this.setIsVisible(!0)}});
dojo.declare("js.LGMessageWatch",js.LGObject,{constructor:function(){var g=this;k.subscribe("publish",function(b){g.showMessage("message from",b)});k.subscribe("receive",function(b){g.showMessage("received by",b)})},showMessage:function(g,b){var e=JSON.stringify(b.data);this.log(g+" "+b.id+': "'+b.tag+'" '+(e||""))}})})}}});
