define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Utiliser le générateur",
                "exitBuilderButtonText": "Quitter le générateur",
                "enterBuilderModeHelpText": "Utiliser le mode de générateur pour configurer l\'application",
                "builderModeHelpText": "Modèle de mode de générateur",
                "webmapCaption": "Carte",
                "selectMapMessage": "Actuellement ${displaying} <b>${webmapTitle}</b><br/>Cliquez sur Sélectionner une carte pour choisir un fond de carte différent",
                "loadMapMessage": "<b>${webmapTitle}</b> actuellement sélectionné<br/>Cliquez sur Enregistrer pour utiliser cette carte Web",
                "changeWebmap": "Sélectionner une carte",
                "saveButtonText": "Enregistrer",
                "webmapNextButtonText": "Suivant ->",
                "previousButtonText":"Précédent",
                "layerLabelText": "Couche",
                "noLayerFoundText": "Aucune couche trouvée",
                "selectLayer": "Sélectionner une couche",
                "applicationSettingText": "Paramètres de l\'application",
                "summaryAttrAscendingOrderTooltip": "Croissant",
                "onStartLabel": "æ_On Start_Â",
                "selectVariableText": "Sélectionner une variable",
                "selectVariableDropdown": "Sélectionner une variable",
                "label":"Etiquette",
                "sourceLinkText":"Lien source",
                "selectSubVariableText":"Sélectionner des sous-variables",
                "subVariablePanelButtonText":"TERMINE",
                "onButtonLabel":"Activé",
                "offButtonLabel":"Désactivé",
                "appSettingsSaveCloseButtonText": "ENREGISTRER ET FERMER",
                "appSettingsTitleText":"Titre de l\'application",
                "appSettingsDescriptionText": "Description de l\'application",
                "appSetingsRendererAreaText":"Zone affichée",
                "shareText":"Partager",
                "basemapText":"Fond de carte",
                "basemapSelectionText":"Sélection du fond de carte",
                "secondaryBasemapText":"Fond de carte secondaire",
                "defaultBasemapText": "Fond de carte par défaut",
                "entireAreaButton": "æ_Entire Area_Â",
                "entireAreaOnStartButton": "æ_Entire Area on start_Â",
                "aboutPanel": "æ_About Panel_Â",
                "legendPanel": "æ_Legend Panel_Â",
                "layersPanel": "æ_Layers Panel_Â",
                "dataConfigurationButtonText": "Configuration des données",
                "savingChangesMessage": "Enregistrement des modifications...",
                "nextButtonText": "Suivant",
                "prevButtonText": "Précédent",
                "enterLabelText": "Entrer l\'étiquette",
                "layerHelpTextMessage": "Cette application nécessite une couche avec des champs numériques",
                "alertMessage": {
                    "resetVariableMessage": "Voulez-vous vraiment réinitialiser la variable ?",
                    "emptyAppTitleMessage": "Le titre de l\'application doit être indiqué",
                    "emptyDescriptionMessage": "La description doit être indiquée",
                    "maxVariableSelection": "Vous ne pouvez pas sélectionner plus de 25 sous-variables",
                    "signInFail" : "La connexion a échoué",
                    "itemUpdateMessage": "L\'élément a été mis à jour",
                    "unsavedChangesMessage": "Modifications non enregistrées",
                    "failMessage": "Impossible de mettre à jour l\'élément",
                    "saveChangesAlert": "Voulez-vous enregistrer les modifications ?",
                    "variableLabelValidation": "L\'étiquette de la variable ne peut pas être VIDE",
                    "subVariableLabelValidation": "L\'étiquette de la sous-variable ne peut pas être VIDE"
                    }
            }
        }
    })
});