define(
	 ({
		header: {
			start: "试_start___验",
			searchStories: "试_Search your stories________验...",
			filter: "试_Filter___验",
			sort: "试_Sort__验",
			sortColon: "试_Sort___验:",
			numResults: "试_Results: {{NUM_RESULTS}}________验",
			sortBy: "试_Sort by___验",
			dateModified: "试_Date modified_____验",
			title: "试_Title___验",
			type: "试_Type__验",
			views: "试_Views___验",
			errors: "试_Errors___验",
			filterBy: "试_Filter by____验",
			filterItems: "试_Filter Items_____验",
			apps: "试_Apps__验",
			sharing: "试_Sharing___验",
			clearAll: "试_Clear all____验",
			clearSearch: "试_Clears the search______验",
			logOut: "试_Log Out___验",
			mainQuote: "试_Storytelling is the most powerful way to put ideas into the world today_______________________验.",
			quoteSource: "试_Robert McKee_____验",
			checkYourStories: "试_Check Stories_____验",
			createStory: "试_Create Story_____验",
			totalStories: "试_Total stories: {{NUM_STORIES}}__________验",
			noIssues: "试_All good___验",
			userStories: "试_Stories of {{USER_NAME}}________验",
			headerDisabledTooltip: "试_Please wait while we work some magic_____________验...",
			notOnTouch: "试_Not available on touch devices__________验",
		},
		deleteModal: {
			title: "试_Confirm Delete_____验",
			warningText: "试_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________验.",
			deleteText: "试_Delete___验",
			cancel: "试_Cancel___验"
		},
		loading: {
			loadingText: "试_Loading your stories________验..."
		},
		cantFindStories: {
			whereAreStories: "试_Not seeing your story________验?",
			notSeeExplanation: "试_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________验.",
			faq: "试_FAQ__验",
			followingStoriesToUpdate: "试_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________验:",
			gettingStories: "试_Searching for stories created with early versions of our applications that need to be updated______________________________验...",
			title: "试_Title___验",
			typeOfStoryMap: "试_Type__验",
			lastModified: "试_Last modified_____验",
			allUpToDate: "试_No stories created with early versions of our applications need to be updated________________________验.",
			updateAll: "试_Update All____验",
			errorScanningForStories: "试_There was an error searching your stories______________验.",
			close: "试_Close___验",
			updates: "试_Updates___验",
			updatingNumberOfNumber: "试_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________验",
			updatingNumberOfNumberAlt: "试_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________验",
			updateSucceeded: "试_Update succeeded______验!",
			reloadingStories: "试_Reloading your stories_________验...",
			errorUpdatingStories: "试_There was an error updating your stories_____________验.",
			partialUpdateMessage: "试_Stories updated successfully: {{NUM_UPDATED}}_______________验"
		},
		signIn: {
			signInTitle: "试_Sign in to Story Maps_______验",
			signInTo: "试_Sign in with your existing ArcGIS Online account to_________________验:",
			explanationOne: "试_Create compelling story maps to tell your stories________________验.",
			explanationTwo: "试_Use your maps and data from ArcGIS Online in your story maps___________________验.",
			explanationThree: "试_Manage your story maps and check the status of their content___________________验.",
			dontHaveAccount: "试_Don't have an ArcGIS Online account? Sign up for a________________验:",
			publicAccount: "试_Free non-commercial public account___________验",
			orgAccount: "试_Free trial ArcGIS subscription__________验",
			timeExpired: "试_Your sign-in expired. Sign in again to pick up where you left off_____________________验.",
			apiDidntLoad: "试_Something isn't loading correctly. Try refreshing the page___________________验.",
			needAccount: "试_Need an account______验?",
			letsGo: "试_Let's go____验!"
		},
		sharingLevel: {
			publicMessage: "试_Public___验",
			privateMessage: "试_Private___验",
			organization: "试_Organization_____验",
			changedSharing: "试_Changed sharing level________验.",
			unableToChange: "试_Unable to change sharing_________验.",
			partOfMap: "试_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________验.",
			storyPublicContentOrg: "试_Your story is public, so its content can't be shared only with your organization_________________________验",
			storyPublicContentPrivate: "试_Your story is public, so its content can't be private_________________验",
			mapOrg: "试_Sharing your map to your organization would break your story___________________验",
			layerOrg: "试_Sharing your layer to your organization would break your story____________________验",
			mapPrivate: "试_Making your map private would break your story_______________验",
			layerPrivate: "试_Making your layer private would break your story_______________验"
		},
		collectionList: {
			advocacy: "试_Advocacy and Outreach_______验",
			architecture: "试_Architecture and Design________验",
			conservation: "试_Conservation and Sustainability__________验",
			culture: "试_Culture___验",
			destinations: "试_Destinations and Tourism________验",
			disasters: "试_Disasters and Recovery________验",
			economy: "试_Economy and Development________验",
			entertainment: "试_Entertainment_____验",
			history: "试_History___验",
			infrastructure: "试_Infrastructure_____验",
			marketing: "试_Marketing____验",
			nature: "试_Nature and Environment________验",
			news: "试_News and Events______验",
			oceans: "试_Oceans___验",
			parks: "试_Parks and Recreation_______验",
			people: "试_People and Society______验",
			planning: "试_Planning and Analysis_______验",
			publicArt: "试_Public Art____验",
			science: "试_Science and Technology________验",
			sport: "试_Sport___验",
			travelogues: "试_Travelogues____验"
		},
		types: {
			custom: "试_Custom___验",
			notSpecified: "试_Type not specified______验"
		},
		storyMap: {
			shared: "试_Shared___验",
			saveFailed: "试_Error saving_____验",
			numViews: "试_Views: {{NUM_VIEWS}}_______验",
			editStory: "试_Edit Story____验",
			viewLive: "试_View Live____验",
			preview: "试_Preview___验",
			deleteButton: "试_Delete___验",
			modified: "试_Modified {{DATE}}______验",
			summary: "试_Summary___验",
			loading: "试_Loading____验...",
			collapse: "试_collapse___验",
			close: "试_close___验",
			hide: "试_hide__验",
			notAvailableWhenBroken: "试_Your story has issues below_________验",
			cantBeDeleted: "试_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________验",
			shareDialog: {
				title: "试_Share your story with the world___________验!",
				notPublicWarning: "试_Your story is shared with your organization. Only members of your organization will be able to view it________________________________验.",
				embedStory: "试_Embed your story______验",
				shortLink: "试_Shortlink____验",
				hideHeaderBar: "试_Hide header bar______验",
				copied: "试_Copied___验",
				small: "试_small___验",
				medium: "试_medium___验",
				large: "试_large___验",
				custom: "试_custom___验",
				widthAbbreviation: "试_w_验",
				heightAbbreviation: "试_h_验",
				emptyDimension: "试_Enter a dimension______验.",
				seeExample: "试_Preview your embed______验",
				removeHeader: "试_Hide application header________验"
			},
			maps: {
				unableRetrieveTitle: "试_Unable to retrieve maps________验",
				unableRetrieveDescription: "试_We weren't able to retrieve maps for this story map_________________验."
			},
			images: {
				unableRetrieveTitle: "试_Unable to retrieve images_________验",
				unableRetrieveDescription: "试_We weren't able to retrieve images for this story map_________________验."
			},
			tags: {
				tags: "试_Tags__验",
				collectionTags: "试_Subject___验",
				selectASubject: "试_Select a subject______验",
				save: "试_Save__验",
				saved: "试_Saved___验",
				errorSaving: "试_Error saving_____验",
				tagTip: "试_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________验."
			},
			submitToGallery: {
				gallerySubmission: "试_Story Maps Gallery______验",
				canSubmitIf: "试_You can nominate your story to the gallery if it contains the following_______________________验:",
				hasOwnImage: "试_Custom thumbnail______验",
				chosenSubject: "试_A subject and some tags________验",
				chosenSubjectAlt: "试_A {{SUBJECT}} and some tags_________验",
				storyMapTopicSubject: "试_subject___验",
				sharedPublicly: "试_Shared publicly______验",
				noBrokenContent: "试_No broken content______验",
				nominateToGallery: "试_Nominate to Gallery_______验",
				comingSoon: "试_Coming soon_____验!",
				submitted: "试_Submitted____验",
				errorSubmitting: "试_Error submitting______验",
				ourGallery: "试_The Story Maps gallery________验",
				galleryTip: "试_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________验."
			},
			placeholders: {
				noSummary: "试_No summary, click to add one__________验."
			},
			errors: {
				cantDeleteStory: "试_Unable to delete story________验.",
				unableToFind: "试_Unable to find content________验",
				unableToRetrieve: "试_We weren't able to retrieve the content for this story map___________________验."
			},
			socialSharing: {
				availableWhenPublic: "试_This option will be available when your story is public__________________验"
			},
			dialog: {
				back: "试_Back__验",
				close: "试_Close___验",
				cancel: "试_Cancel___验"
			},
			imagePicker: {
				changeDefault: "试_Change the default image________验",
				changeImage: "试_Change thumbnail______验",
				uploadImage: "试_Upload thumbnail______验",
				chooseImage: "试_Choose thumbnail______验",
				chooseAnImage: "试_Choose an Image______验",
				notInIEVersion: "试_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________验.",
				or: "试_Or__验",
				uploadAnImage: "试_Upload an Image______验",
				supportedFileTypes: "试_Supports .png, .jpg, .gif_________验",
				imageSizeMessage: "试_Your image needs to be at least 286 px wide by 190 px tall___________________验.",
				minimumDimensions: "试_Minimum: 286 x 190px_______验",
				imagesLoading: "试_Loading images______验...",
				noImages: "试_This story has no images________验",
				errorLoading: "试_Unable to retrieve the images in this story______________验",
				clickBelowTip: "试_Click the button below to upload an image______________验.",
				dragAndDrop: "试_Drag and Drop_____验",
				cropImage: "试_Crop Image____验",
				saveImage: "试_Save Image____验",
				save: "试_Save__验",
				savingImage: "试_Saving your image_______验...",
				saved: "试_Saved___验!",
				errorSaving: "试_Unable to save your image_________验.",
				skipAndCrop: "试_Skip and Crop for me_______验",
				wrongFormat: "试_This file type is not supported___________验.",
				noCropWarning: "试_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________验."
			}
		},
		content: {
			media: {
				maps: "试_Maps__验",
				images: "试_Images___验",
				videos: "试_Videos___验",
				webpages: "试_Webpages___验",
				tags: "试_Tags__验",
				gallery: "试_Gallery___验"
			},
			headers: {
				status: "试_Status___验",
				source: "试_Source___验",
				name: "试_Name__验",
				shared: "试_Shared___验"
			},
			component: {
				mapTour: "试_Point Number_____验",
				bullet: "试_Bullet___验",
				tab: "试_Tab__验",
				accordion: "试_Section___验",
				mapJournal: "试_Section___验"
			},
			titleType: {
				mapTour: "试_Caption___验",
				mapJournal: "试_URL__验",
				mapSeries: "试_URL__验"
			},
			actions: {
				viewMap: "试_View Map___验",
				editMap: "试_Edit Map___验",
				fix: "试_Fix__验",
				viewLayer: "试_View Layer____验"
			},
			contentType: {
				mainStage: "试_main stage action______验",
				sidePanel: "试_description____验"
			},
			notification: {
				refreshExplanation: "试_Check your story again________验",
				checking: "试_Checking____验...",
				foundSomeIssues: "试_We found some issues_______验",
				noIssuesFound: "试_No issues found______验",
				storyPublic: "试_Your story is now public________验",
				storyOrg: "试_Your story is now shared to your organization_______________验",
				storyPrivate: "试_Your story is now private_________验",
				mapPublic: "试_Your map is now public________验",
				mapOrg: "试_Your map is now shared to your organization______________验",
				mapPrivate: "试_Your map is now private________验",
				layerPublic: "试_Your layer is now public________验",
				layerOrg: "试_Your layer is now shared to your organization_______________验",
				layerPrivate: "试_Your layer is now private_________验",
				contentPublic: "试_Your content is now public_________验",
				contentOrg: "试_Your content is now shared to your organization_______________验",
				contentPrivate: "试_Your content is now private_________验",
				storyAndContentPublic: "试_Your story and its content are now public_____________验",
				storyAndContentOrg: "试_Your story and its content are now shared to your organization____________________验",
				storyAndContentPrivate: "试_Your story and its content are now private______________验",
				shareBulkPrompt: "试_Do you want to share your storyâ€™s content accordingly__________________验?",
				layersPublic: "试_Some layers have also been shared publicly______________验",
				layersOrg: "试_Some layers have also been shared with your organization__________________验",
				layersPrivate: "试_Some layers have also been made private_____________验",
				mapsPublic: "试_Some maps have also been shared publicly_____________验",
				mapsOrg: "试_Some maps have also been shared with your organization_________________验",
				mapsPrivate: "试_Some maps have also been made private____________验",
				layersAndMapsPublic: "试_Some maps and layers have also been shared publicly________________验",
				layersAndMapsOrg: "试_Some maps and layers have also been shared with your organization_____________________验",
				layersAndMapsPrivate: "试_Some maps and layers have also been made private_______________验",
				yes: "试_Yes__验",
				no: "试_No__验",
				premiumPublicSuccess: "试_Your premium content is now publicly accessible_______________验",
				subscriptionPublicSuccess: "试_Your subscription content is now publicly accessible_________________验"
			},
			errors: {
				publicDisabled: "试_Sharing publicly has been disabled by the Administrator__________________验",
				noMapName: "试_Could Not Retrieve Map Name_________验",
				notPublic: "试_NOT PUBLIC____验",
				inaccessible: "试_INACCESSIBLE_____验",
				deleted: "试_DELETED___验",
				cantAccessVideo: "试_Could Not Access Video________验",
				noStoriesFound: "试_We could not find any Story Maps in your content________________验.",
				cantShowStories: "试_Unable to show your story maps. Please try again later__________________验.",
				consolationSearch: "试_We couldn't find any stories__________验.",
				notCompatibleWithBrowser : "试_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________验.",
				pleaseUpdateBrowser: "试_Please update your browser_________验.",
				searchTip: "试_Try and simplify it a bit_________验.",
				consolationNoStories: "试_Welcome to My Stories________验!",
				noStoriesTip: "试_To make your first story map, check out the Apps page_________________验.",
				letsGo: "试_Let's Go___验",
				cantChangeSharingLevel: "试_Unable to change sharing level__________验",
				cantChangeSharingLevels: "试_Unable to change sharing levels__________验",
				errorUpdatingTitle: "试_Error updating title_______验",
				errorUpdatingSummary: "试_Error updating summary________验",
				noEmptyTitle: "试_Title cannot be empty_______验",
				cantUpdatePremiumContent: "试_Unable to update premium content___________验",
				cantUpdateSubscriptionContent: "试_Unable to update subscription content____________验",
				createFirstStory: "试_Create My First Story_______验"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "试_Map has been deleted_______验",
				layerHasBeenDeleted: "试_Layer has been deleted________验",
				mapIsInaccessible: "试_Map is inaccessible_______验",
				layerIsInaccessible: "试_Layer is inaccessible_______验",
				mapNotYoursNotAccessible: "试_Map is owned by someone else and isn't accessible________________验",
				layerServiceOkItemNot: "试_Layer was added as an item that is deleted or inaccessible__________________验",
				layerNotYoursNotAccessible: "试_Layer is owned by someone else and isn't accessible________________验",
				mapOthersSharedBelowLevel: "试_Map is not owned by you and is not public_____________验",
				layerOthersSharedBelowLevel: "试_Layer is not owned by you and is not public______________验",
				noMapNoDetails: "试_Without the map details, we can't tell you anything about the layers_____________________验",
				mapIsPrivate: "试_Map is private_____验",
				mapIsOrg: "试_Map is only shared in your organization_____________验",
				layerIsPrivate: "试_Layer is private______验",
				layerIsOrg: "试_Layer is only shared in your organization_____________验",
				imageInaccessible: "试_This image is inaccessible_________验",
				videoInaccessible: "试_This video is inaccessible_________验",
				webpageInaccessible: "试_This web page is inaccessible__________验",
				layerSecureService: "试_Layer is a secure service_________验",
				mapSecureService: "试_Map is a secure service________验",
				layerConsumesCredits: "试_Layer is premium content and consumes credits_______________验",
				layerSubscriptionContent: "试_Layer is subscription content__________验",
				mapConsumesCredits: "试_Map is premium content and consumes credits______________验",
				mapSubscriptionContent: "试_Map is subscription content_________验"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "试_We're not able to check this type of layer______________验",
				cantScanThisType: "试_Layer is not a type of layer we can check_____________验",
				webpageNotScanned: "试_Webpages are not checked for issues____________验"
			},
			scanningErrors: {
				deletedMap: "试_Deleted content______验",
				inaccessibleMap: "试_Inaccessible map content________验",
				notYoursNotAccessible: "试_Content not owned by you and not public_____________验",
				serviceOkItemNot: "试_Working layers but inaccessible items____________验",
				someContentNotPublic: "试_Content not shared publicly_________验",
				someContentPrivate: "试_Private content______验",
				othersSharedBelowLevel: "试_Content not owned by you and not public_____________验",
				premiumContent: "试_Premium content______验",
				subscriptionContent: "试_Subscription content_______验",
				secureService: "试_Secure services______验",
				inaccessibleImage: "试_Inaccessible images_______验",
				inaccessibleVideo: "试_Inaccessible videos_______验",
				inaccessibleWebpage: "试_Inaccessible webpages_______验"
			},
			scanningErrorTips: {
				deletedMapTip: "试_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________验.",
				inaccessibleMapTip: "试_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________验.",
				notYoursNotAccessibleTip: "试_Tip: Open the web map and remove the layer or map from the story_____________________验.",
				serviceOkItemNotTip: "试_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________验.",
				ignore: "试_Ignore___验",
				fix: "试_Fix__验",
				clickToShareOrg: "试_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________验.",
				clickToSharePublic: "试_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________验.",
				shareOrg: "试_Share to your org______验",
				sharePublicly: "试_Share publicly_____验",
				othersSharedBelowLevelTip: "试_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________验.",
				secureServiceTip: "试_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________验.",
				blogArticle: "试_here__验",
				premiumContentTip: "试_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________验.",
				premiumContentPublicTip: "试_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________验.",
				subscriptionContentTip: "试_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________验.",
				agolCredits: "试_ArcGIS Online credits_______验",
				credits: "试_credits___验",
				makePublic: "试_Make public____验",
				confirm: "试_Confirm___验",
				inaccessibleImageTip: "试_Tip: Provide the missing image or remove the reference to it___________________验.",
				inaccessibleVideoTip: "试_Tip: Provide the missing video or remove the reference to it___________________验.",
				inaccessibleWebpageTip: "试_Tip: Provide the missing web page or remove the reference to it____________________验."
			},
			removeLayer: {
				title: "试_Fix Layer Issue______验",
				layersWithIssue: "试_Layers with this issue: {{NUM_WITH_ISSUE}}______________验",
				issueExplanation: "试_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________验.",
				issueSolution: "试_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________验:",
				editMap: "试_Edit Your Map_____验",
				clickBelowWhenDone: "试_When you have finished editing, click the button below__________________验:",
				rescanAndClose: "试_Rescan And Close______验"
			},
			info: {
				ownedBy: "试_This item is owned by {{USER_NAME}}____________验",
				unknownUser: "试_someone else_____验",
				untitledSection: "试_(Untitled section)______验",
				introRecord: "试_Introduction_____验"
			},
			layers: {
				layersHeader: "试_Layers___验",
				noLayers: "试_(No Layers)____验",
				basemapParens: "试_(basemap)____验"
			},
			images: {
				thumbnails: "试_Thumbnails____验",
				thumbnail: "试_Thumbnail____验",
				thumbnailParens: "试_(thumbnail)____验"
			},
			general: {
				noTitle: "试_(no title)____验",
				loading: "试_Loading____验..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "试_sections___验",
				secondTitle: "试_style___验",
				secondValueA: "试_side panel____验",
				secondValueB: "试_floating panel_____验",
				thirdTitle: "试_maps__验"
			},
			mapTour: {
				firstTitle: "试_tour points____验",
				secondTitle: "试_style___验",
				secondValueA: "试_integrated____验",
				secondValueB: "试_three-panel____验",
				thirdTitle: "试_basemap___验",
				thirdValueLoading: "试_Loading____验...",
				thirdValueUnknown: "试_unknown___验"
			},
			mapSeries: {
				firstTitleA: "试_bullets___验",
				firstTitleB: "试_sections___验",
				firstTitleC: "试_tabs__验",
				secondTitle: "试_style___验",
				secondValueA: "试_bulleted___验",
				secondValueB: "试_side accordion_____验",
				secondValueC: "试_tabbed___验",
				thirdTitle: "试_maps__验"
			},
			swipeSpyglass: {
				firstTitle: "试_points of interest______验",
				secondTitle: "试_style___验",
				secondValueA: "试_swipe___验",
				secondValueB: "试_spyglass___验",
				thirdTitle: "试_maps__验"
			}
		},
		progress: {
			checkingStories: "试_Checking your stories for issues____________验...",
			stop: "试_Stop__验",
			exit: "试_Exit__验",
			dismiss: "试_Dismiss___验",
			done: "试_Done___验.",
			noStoriesWithIssuesLower: "试_No issues found______验!",
			storiesErrorFree: "试_Looks like your stories are error-free____________验",
			scanAllError: "试_Unable to scan -- we couldn't retrieve one or more of your stories_____________________验",
			scanProgress: "试_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________验",
			scanStopped: "试_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________验",
			storiesWithIssues: "试_Stories with issues: {{NUM_STORIES}}____________验"
		}
    })
);