define({
  "header": {
    "start": "启动",
    "searchStories": "搜索故事...",
    "filter": "过滤器",
    "sort": "排序",
    "sortColon": "排列:",
    "numResults": "结果: {{NUM_RESULTS}}",
    "sortBy": "排序方式",
    "dateModified": "修改日期",
    "title": "标题",
    "type": "类型",
    "views": "查看",
    "errors": "错误",
    "filterBy": "过滤依据",
    "filterItems": "过滤项目",
    "apps": "应用程序",
    "sharing": "共享",
    "clearAll": "全部清除",
    "clearSearch": "清除搜索",
    "logOut": "注销",
    "mainQuote": "讲故事是目前向世界传递想法的最有效方式。",
    "quoteSource": "Robert McKee",
    "checkYourStories": "检查故事",
    "createStory": "创建故事",
    "totalStories": "总故事数: {{NUM_STORIES}}",
    "noIssues": "一切妥当",
    "userStories": "{{USER_NAME}}的故事",
    "headerDisabledTooltip": "请稍后，正在进行处理...",
    "notOnTouch": "不适用于触摸屏设备"
  },
  "deleteModal": {
    "title": "确认删除",
    "warningText": "是否确认要删除此故事? 执行删除后将无法恢复。",
    "deleteText": "删除",
    "cancel": "取消"
  },
  "loading": {
    "loadingText": "正在加载故事..."
  },
  "cantFindStories": {
    "whereAreStories": "无法查看您的故事？",
    "notSeeExplanation": "“我的故事”中仅会列出在 ArcGIS 中托管的故事地图(当前不支持 {{STORY_MAP_BASIC}})。有关详细信息请参阅 {{常见问题}}。",
    "faq": "FAQ",
    "followingStoriesToUpdate": "以下使用早期版本应用程序创建的故事需要在更新后才能在“我的故事”中列出:",
    "gettingStories": "搜索使用需要进行更新的早期版本应用程序创建的故事...",
    "title": "标题",
    "typeOfStoryMap": "类型",
    "lastModified": "上次修改时间",
    "allUpToDate": "没有使用需要进行更新的早期版本应用程序创建的故事...",
    "updateAll": "更新全部",
    "errorScanningForStories": "搜索故事时出错。",
    "close": "关闭",
    "updates": "更新",
    "updatingNumberOfNumber": "正在更新，目前 {{CURRENT_NUMBER}}，共 {{TOTAL}}",
    "updatingNumberOfNumberAlt": "正在更新 {{CURRENT_NUMBER}} / {{TOTAL}}",
    "updateSucceeded": "更新成功！",
    "reloadingStories": "正在重新加载故事...",
    "errorUpdatingStories": "更新故事时出错。",
    "partialUpdateMessage": "故事更新成功: {{NUM_UPDATED}}"
  },
  "signIn": {
    "signInTitle": "登录到 Story Maps",
    "signInTo": "使用您现有的 ArcGIS Online 帐户登录执行以下操作:",
    "explanationOne": "创建引人注目的故事地图，讲述您自己的故事。",
    "explanationTwo": "将 ArcGIS Online 中的地图和数据用于您的故事地图。",
    "explanationThree": "管理您的故事地图，并检查其内容的状态。",
    "dontHaveAccount": "没有 ArcGIS Online 账户? 注册获取:",
    "publicAccount": "免费的非商业公共帐户",
    "orgAccount": "免费试用 ArcGIS 订阅",
    "timeExpired": "您的登录已过期。请再次登录以返回您之前的操作。",
    "apiDidntLoad": "发生加载错误。请尝试刷新页面。",
    "needAccount": "是否需要帐户?",
    "letsGo": "快去注册吧！"
  },
  "sharingLevel": {
    "publicMessage": "公共",
    "privateMessage": "私有",
    "organization": "组织",
    "changedSharing": "共享级别已更改。",
    "unableToChange": "无法更改共享。",
    "partOfMap": "此项存在于地图中。要更改其共享级别，必须更改地图的共享级别。",
    "storyPublicContentOrg": "您的故事是公开的，因此不能仅与组织共享其内容",
    "storyPublicContentPrivate": "您的故事是公开的，因此其内容不能为私有",
    "mapOrg": "将地图共享到组织会使故事中断",
    "layerOrg": "将图层共享到组织会使故事中断",
    "mapPrivate": "将地图设为私有会使故事中断",
    "layerPrivate": "将图层设为私有会使故事中断"
  },
  "collectionList": {
    "business": "商业和经济",
    "history": "历史和文化",
    "inNews": "时事新闻",
    "infrastructure": "基础设施和建设",
    "nature": "自然与资源保护",
    "people": "人与社会",
    "planning": "规划和设计",
    "science": "科学和技术",
    "sports": "运动和娱乐",
    "travel": "旅行和休闲"
  },
  "types": {
    "custom": "自定义",
    "notSpecified": "未指定类型"
  },
  "storyMap": {
    "shared": "共享",
    "saveFailed": "保存时出错",
    "numViews": "查看: {{NUM_VIEWS}}",
    "editStory": "编辑故事",
    "viewLive": "查看故事",
    "preview": "预览",
    "deleteButton": "删除",
    "modified": "修改 {{DATE}}",
    "summary": "摘要",
    "loading": "正在加载...",
    "collapse": "折叠",
    "close": "关闭",
    "hide": "隐藏",
    "notAvailableWhenBroken": "您的故事存在下列问题",
    "cantBeDeleted": "此故事已启用删除保护。请在 ArcGIS 中查看其项目页面以禁用保护。",
    "shareDialog": {
      "title": "与世界共享故事！",
      "notPublicWarning": "您的故事会在您的组织内共享。只有您的组织成员能够查看您的故事。",
      "embedStory": "嵌入您的故事",
      "shortLink": "短链接",
      "hideHeaderBar": "隐藏标题栏",
      "copied": "已复制",
      "small": "小",
      "medium": "中",
      "large": "大",
      "custom": "自定义",
      "widthAbbreviation": "宽度",
      "heightAbbreviation": "高度",
      "emptyDimension": "输入尺寸。",
      "seeExample": "预览嵌入效果",
      "removeHeader": "隐藏应用程序标题"
    },
    "maps": {
      "unableRetrieveTitle": "无法检索地图",
      "unableRetrieveDescription": "我们未能检索到此 Story Map 的地图。"
    },
    "images": {
      "unableRetrieveTitle": "无法检索图像",
      "unableRetrieveDescription": "我们未能检索到此 Story Map 的图像。"
    },
    "tags": {
      "tags": "标签",
      "collectionTags": "主题",
      "selectASubject": "选择主题",
      "save": "保存",
      "saved": "已保存",
      "errorSaving": "保存时出错",
      "tagTip": "提示: 标签可帮助人们找到您的故事。标签的相关性越强，您的工作得到的可见度越高。"
    },
    "submitToGallery": {
      "gallerySubmission": "Story Maps 图库",
      "canSubmitIf": "如果故事包含以下内容，可将其推荐到库中：",
      "hasOwnImage": "自定义缩略图",
      "chosenSubject": "主题和一些标签",
      "chosenSubjectAlt": "{{SUBJECT}} 以及部分标签",
      "storyMapTopicSubject": "主题",
      "sharedPublicly": "公开共享",
      "noBrokenContent": "没有问题",
      "nominateToGallery": "推荐至库",
      "comingSoon": "即将推出!",
      "submitted": "已提交",
      "errorSubmitting": "提交时出错",
      "ourGallery": "Story Maps 图库",
      "galleryTip": "{{THE_GALLERY}} 是陈列部分最佳示例的“故事地图”的展览集。如果您的故事被选中，则将在您提交后的 10 天内被添加到其中。鉴于提名的数量，我们不能保证您的故事一定会被添加。"
    },
    "placeholders": {
      "noSummary": "无摘要，单击进行添加。"
    },
    "errors": {
      "cantDeleteStory": "无法删除故事。",
      "unableToFind": "无法找到内容",
      "unableToRetrieve": "我们未能检索到此 Story Map 的内容。"
    },
    "socialSharing": {
      "availableWhenPublic": "此选项在故事为公开状态时可用"
    },
    "dialog": {
      "back": "后退",
      "close": "关闭",
      "cancel": "取消"
    },
    "imagePicker": {
      "changeDefault": "更改默认图像",
      "changeImage": "更改缩略图",
      "uploadImage": "上传缩略图",
      "chooseImage": "选择缩略图",
      "chooseAnImage": "选择图像",
      "notInIEVersion": "此功能在 Internet Explorer {{VERSION_NUMBER}} 中不可用。",
      "or": "或",
      "uploadAnImage": "上传图像",
      "supportedFileTypes": "支持 .png、.jpg、.gif",
      "imageSizeMessage": "图像需要至少为 286 像素(宽) x 190 像素(高)。",
      "minimumDimensions": "最小：286 x 190 像素",
      "imagesLoading": "正在加载图像...",
      "noImages": "此故事没有图像",
      "errorLoading": "无法检索此故事中的图像",
      "clickBelowTip": "单击下方按钮上传图像。",
      "dragAndDrop": "拖放",
      "cropImage": "裁剪图像",
      "saveImage": "保存图像",
      "save": "保存",
      "savingImage": "正在保存图像...",
      "saved": "已保存！",
      "errorSaving": "无法保存图像。",
      "skipAndCrop": "跳过并裁剪",
      "wrongFormat": "此文件类型不受支持。",
      "noCropWarning": "此图像不可剪裁，但您仍然可使用原尺寸将其保存为您故事的缩略图({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)。"
    }
  },
  "content": {
    "media": {
      "maps": "地图",
      "scenes": "场景",
      "images": "影像",
      "videos": "视频",
      "webpages": "网页",
      "tags": "标签",
      "gallery": "图库"
    },
    "headers": {
      "status": "状态",
      "source": "源",
      "name": "名称",
      "shared": "共享"
    },
    "component": {
      "mapTour": "标记序号",
      "bullet": "项目符号",
      "tab": "选项卡",
      "accordion": "节",
      "mapJournal": "节",
      "cascade": "章节",
      "crowdsource": "贡献",
      "shortlist": "选项卡"
    },
    "titleType": {
      "mapTour": "标题",
      "mapJournal": "URL",
      "mapSeries": "URL",
      "cascade": "URL",
      "crowdsource": "URL",
      "shortlist": "URL"
    },
    "actions": {
      "viewMap": "查看地图",
      "editMap": "编辑地图",
      "editScene": "编辑场景",
      "fix": "固定",
      "viewLayer": "查看图层"
    },
    "contentType": {
      "mainStage": "主舞台操作",
      "sidePanel": "描述",
      "introImage": "(封面页照片)"
    },
    "notification": {
      "refreshExplanation": "重新检查您的故事",
      "checking": "正在检查...",
      "foundSomeIssues": "我们发现一些问题",
      "noIssuesFound": "未发现问题",
      "storyPublic": "您的故事现已公开",
      "storyOrg": "您的故事现已共享至您所在的组织",
      "storyPrivate": "您的故事现已变为私有",
      "mapPublic": "您的地图现已公开",
      "mapOrg": "您的地图现已共享至您所在的组织",
      "mapPrivate": "您的地图现已变为私有",
      "layerPublic": "您的图层现已公开",
      "layerOrg": "您的图层现已共享至您所在的组织",
      "layerPrivate": "您的图层现已变为私有",
      "contentPublic": "您的内容现已公开",
      "contentOrg": "您的内容现已共享至您所在的组织",
      "contentPrivate": "您的内容现已变为私有",
      "storyAndContentPublic": "您的故事及其内容现已公开",
      "storyAndContentOrg": "您的故事及其内容现已共享至您所在的组织",
      "storyAndContentPrivate": "您的故事及其内容现已变为私有",
      "shareBulkPrompt": "你是否希望相应地共享您的故事内容？",
      "layersPublic": "一些图层已然被公开共享",
      "layersOrg": "一些图层已然被您的组织共享",
      "layersPrivate": "一些图层已然被设为私有",
      "mapsPublic": "一些地图已然被公开共享",
      "mapsOrg": "一些地图已然被您的组织共享",
      "mapsPrivate": "一些地图已然被设为私有",
      "layersAndMapsPublic": "一些地图和图层已然被公开共享",
      "layersAndMapsOrg": "一些地图和图层已然被您的组织共享",
      "layersAndMapsPrivate": "一些地图和图层已然被设为私有",
      "yes": "是",
      "no": "否",
      "premiumPublicSuccess": "您的高级内容现在可公开访问",
      "subscriptionPublicSuccess": "您的订阅内容现在可公开访问"
    },
    "errors": {
      "publicDisabled": "管理员已禁用公开共享",
      "orgDisabled": "管理员已禁用共享到您的组织",
      "noMapName": "无法检索地图名称",
      "noSceneName": "无法检索场景",
      "notPublic": "未公开",
      "inaccessible": "无法访问",
      "deleted": "已删除",
      "cantAccessVideo": "无法访问视频",
      "noStoriesFound": "我们未能在内容中找到任何 Story Maps。",
      "cantShowStories": "无法显示您的故事地图。请稍候再次尝试。",
      "consolationSearch": "未能找到任何故事。",
      "notCompatibleWithBrowser": "Internet Explorer {{VERSION_NUMBER}} 之前的版本不支持“我的故事”。",
      "pleaseUpdateBrowser": "请更新浏览器。",
      "searchTip": "尝试进行一些简化。",
      "consolationNoStories": "欢迎使用“我的故事”！",
      "noStoriesTip": "要制作您的第一个故事地图，请查看应用程序页面。",
      "letsGo": "快开始吧",
      "cantChangeSharingLevel": "无法更改共享级别",
      "cantChangeSharingLevels": "无法更改共享级别",
      "errorUpdatingTitle": "更新标题时出错",
      "errorUpdatingSummary": "更新摘要时出错",
      "noEmptyTitle": "标题不能为空",
      "cantUpdatePremiumContent": "无法更新高级内容",
      "cantUpdateSubscriptionContent": "无法更新订阅内容",
      "createFirstStory": "创建首个故事"
    },
    "tooltipErrors": {
      "mapHasBeenDeleted": "地图已删除",
      "layerHasBeenDeleted": "图层已删除",
      "mapIsInaccessible": "地图无法访问",
      "layerIsInaccessible": "图层无法访问",
      "mapNotYoursNotAccessible": "地图为他人所拥有，无法访问",
      "layerServiceOkItemNot": "图层被添加到已被删除或无法访问的项",
      "layerNotYoursNotAccessible": "图层属于其他人且无法访问",
      "mapOthersSharedBelowLevel": "地图不属于您且未公开",
      "layerOthersSharedBelowLevel": "图层不属于您且未公开",
      "noMapNoDetails": "没有地图详细信息，我们无法提供任何有关图层的信息。",
      "mapIsPrivate": "地图为私有",
      "mapIsOrg": "地图仅在组织内部共享",
      "layerIsPrivate": "图层为私有",
      "layerIsOrg": "图层仅在组织内共享",
      "imageInaccessible": "此图像无法访问",
      "videoInaccessible": "此视频无法访问",
      "webpageInaccessible": "此网页无法访问",
      "layerSecureService": "图层是一种安全服务",
      "mapSecureService": "地图是一种安全服务",
      "layerConsumesCredits": "图层是高级内容，会消耗配额",
      "layerSubscriptionContent": "图层是订阅内容",
      "mapConsumesCredits": "地图是高级内容，会消耗配额",
      "mapSubscriptionContent": "地图是订阅内容"
    },
    "tooltipWarnings": {
      "cantScanThisTypeAlt": "无法检查此类图层",
      "cantScanThisType": "图层是我们无法查看的图层类型",
      "webpageNotScanned": "未检查网页是否存在问题",
      "sceneNotScanned": "目前尚未检查场景是否存在问题，请确保场景及其所有图层均已正确共享",
      "scenesNotScannedGlobally": "本故事中含有场景，且目前尚未检查场景是否存在问题。请确保场景及其所有图层均已正确共享",
      "ignoredIssue": "您忽略了此图层上的一个错误。请重新加载此页面并重新检查此故事以检查错误",
      "ignoredIssueBuilder": "您忽略了此图层上的一个错误。请重新加载构建器以再次检查此错误"
    },
    "scanningErrors": {
      "deletedMap": "已删除的内容",
      "inaccessibleMap": "无法访问的地图内容",
      "notYoursNotAccessible": "不属于您且未公开的内容",
      "serviceOkItemNot": "图层有效但无法访问的项目",
      "someContentNotPublic": "未公开共享的内容",
      "someContentPrivate": "私有内容",
      "othersSharedBelowLevel": "不属于您且未公开的内容",
      "premiumContent": "高级内容",
      "subscriptionContent": "订阅内容",
      "secureService": "安全服务",
      "inaccessibleImage": "无法访问的图像",
      "inaccessibleVideo": "无法访问的视频",
      "inaccessibleWebpage": "无法访问的网页"
    },
    "scanningErrorTips": {
      "deletedMapTip": "提示: 编辑 web 地图并移除损坏内容，或者从故事中移除 web 地图。",
      "inaccessibleMapTip": "提示: 编辑 web 地图并移除损坏内容，或者从故事中移除 web 地图。",
      "notYoursNotAccessibleTip": "提示: 编辑 web 地图并移除图层，或者从故事中移除 web 地图。",
      "serviceOkItemNotTip": "图层被添加为无法访问或已删除的项。图层可以使用，但可能会影响您的地图(弹出窗口、符号)。",
      "ignore": "忽略",
      "fix": "定位",
      "clickToShareOrg": "单击按钮将所有这些内容共享至组织，或者通过单击共享按钮手动更改每个项目。",
      "clickToSharePublic": "单击按钮将所有这些内容公开共享，或者通过单击共享按钮手动更改每个项目。",
      "shareOrg": "共享至组织",
      "sharePublicly": "公开共享",
      "othersSharedBelowLevelTip": "提示: 您的某些故事内容属于 {{USER_NAME}}，并且其他人在查看您的故事时，可能无法看到这些故事内容。",
      "secureServiceTip": "提示: 从您的故事中移除安全服务，或按照 {{HERE}} 说明的步骤进行操作。",
      "blogArticle": "此处",
      "premiumContentTip": "您的故事包含高级内容，将其公开时将消耗 {{CREDITS}}。将您的故事公开并继续，或从您的故事中移除图层。",
      "premiumContentPublicTip": "您的故事包含高级内容，将其公开时将消耗 {{CREDITS}}。确认将这些图层公开，或从您的故事中移除图层。",
      "subscriptionContentTip": "您的故事包含默认情况下不可公开的订阅内容。确认您希望公开这些图层(不会消耗配额)，或从您的故事中移除图层。",
      "credits": "配额",
      "makePublic": "公开",
      "confirm": "确认",
      "inaccessibleImageTip": "提示：提供缺失图像或移除对该图像的引用。",
      "inaccessibleVideoTip": "提示：提供缺失视频或移除对该视频的引用。",
      "inaccessibleWebpageTip": "提示：提供缺失网页或移除对该网页的引用。"
    },
    "removeLayer": {
      "title": "修复图层问题",
      "layersWithIssue": "带有此问题的图层: {{NUM_WITH_ISSUE}}",
      "issueExplanation": "图层 {{LAYER_NAME}} 已被添加为不可访问或已删除的项。图层正在工作，但这将影响您的地图(弹出窗口、符号)。我们无法告知该项对您的故事而言是否重要。",
      "issueSolution": "要修复此问题，您可以编辑地图，移除图层，然后使用以下 URL 将该图层重新添加到地图中：",
      "editMap": "编辑地图",
      "clickBelowWhenDone": "完成编辑后，请单击以下按钮：",
      "rescanAndClose": "重新扫描并关闭"
    },
    "info": {
      "ownedBy": "此项属于 {{USER_NAME}}",
      "unknownUser": "他人",
      "untitledSection": "(无标题部分)",
      "introRecord": "简介"
    },
    "layers": {
      "layersHeader": "图层",
      "noLayers": "(无图层)",
      "basemapParens": "(底图)"
    },
    "images": {
      "thumbnails": "缩略图",
      "thumbnail": "缩略图",
      "thumbnailParens": "(缩略图)"
    },
    "general": {
      "noTitle": "(无标题)",
      "loading": "正在加载..."
    }
  },
  "infographics": {
    "mapJournal": {
      "firstTitle": "部分",
      "secondTitle": "样式",
      "secondValueA": "侧面板",
      "secondValueB": "浮动面板",
      "thirdTitle": "地图"
    },
    "mapTour": {
      "firstTitle": "多个浏览点",
      "secondTitle": "样式",
      "secondValueA": "集成",
      "secondValueB": "三面板",
      "thirdTitle": "底图",
      "thirdValueLoading": "正在加载...",
      "thirdValueUnknown": "未知"
    },
    "mapSeries": {
      "firstTitleA": "项目符号",
      "firstTitleB": "部分",
      "firstTitleC": "选项卡",
      "secondTitle": "样式",
      "secondValueA": "项目符号",
      "secondValueB": "手风琴式",
      "secondValueC": "选项卡式",
      "thirdTitle": "地图"
    },
    "cascade": {
      "firstTitle": "章节",
      "secondTitle": "地图"
    },
    "swipeSpyglass": {
      "firstTitle": "感兴趣点",
      "secondTitle": "样式",
      "secondValueA": "卷帘",
      "secondValueB": "望远镜",
      "thirdTitle": "地图"
    },
    "crowdsource": {
      "firstTitle": "贡献",
      "secondTitle": "底图",
      "secondValueLoading": "正在加载...",
      "secondValueUnknown": "未知"
    },
    "shortlist": {
      "firstTitle": "地点",
      "secondTitle": "选项卡",
      "thirdTitle": "底图",
      "thirdValueLoading": "正在加载...",
      "thirdValueUnknown": "未知"
    }
  },
  "progress": {
    "checkingStories": "正在检查故事是否存在问题...",
    "stop": "停止",
    "exit": "退出",
    "dismiss": "清除",
    "done": "完成。",
    "noStoriesWithIssuesLower": "未发现问题！",
    "storiesErrorFree": "您的故事似乎没有问题",
    "scanAllError": "无法扫描 -- 我们未能检索一个或多个故事",
    "scanProgress": "{{NUM_SCANNED}} 已完成，共 {{NUM_TOTAL}}",
    "scanStopped": "已扫描故事: {{NUM_SCANNED}}，有问题的故事: {{ISSUE_STORIES}}",
    "storiesWithIssues": "有问题的故事: {{NUM_STORIES}}"
  },
  "newStories": {
    "newStoriesFound": "您似乎已创建新故事。",
    "includeStories": "刷新故事",
    "notWhileScanning": "此功能将在检查完成后可用"
  }
});