define(
    ({
        builder: {
            invalidWebmapSelectionAlert: "试_Selected webmap does not contain any feature server_验",
            selectThemeText: "试_Select Form Theme_验",
            fieldLabelPlaceHolder: "试_Label this field_验",
            fieldDescPlaceHolder: "试_Describe this field_验",
            webmapText: "试_Webmap_验",
            layerText: "图层",
            detailsText: "详细信息",
            fieldsText: "字段",
            styleText: "试_Style_验",
            previewText: "预览",
            publishText: "发布",
            titleText: "试_GeoForm Builder_验",
            descriptionText: "试_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._验",
            btnPreviousText: "试_Previous_验",
            btnNextText:"试_Next_验",
            webmapTabTitleText: "试_Choose a Webmap_验",
            btnSelectWebmapText:"试_Select Webmap_验",
            layerTabTitleText: "试_Select Editable Layer_验",
            selectLayerLabelText:"图层",
            selectLayerDefaultOptionText:"选择图层",
            detailsTabTitleText:"试_Form Details_验",
            detailTitleLabelText: "标题",
            detailLogoLabelText: "试_Logo Image_验",
            detailDescriptionLabelText: "描述",
            fieldTabDisplayHeaderText: "显示",
            fieldTabFieldHeaderText: "字段",
            fieldTabLabelHeaderText: "标注",
            fieldTabTypeHeaderText: "类型",
            fieldTabDescriptionHeaderText: "描述",
            previewApplicationText: "试_Preview Application_验",
            saveApplicationText: "试_Save Application_验",
            saveText: "保存",

            //Local string for user mode
            defaultTitleText: "试_Default Title_验",
            defaultDescriptionText: "试_Default Description_验",
            geoFormGeneralTabText: "常规",
            locationInformationText: "试_Location Info_验",
            myLocationText: "我的位置",
            addressText: "地址",
            cooridnatesText: "试_Coordinates_验",
            locationTabText: "位置",
            enterCoordinatesPlaceholder: "试_Enter Coordinates_验",
            submitButtonText: "提交",
            clearButtonText: "清除",
            fieldvalidationMessageAlertText: "试_Please enter a valid number_验",
            formValidationMessageAlertText: "试_Please verify the form for errors and resubmit the form_验",
            latlongValidationMessageAlert: "试_Please select x and y coordinates_验",
            emptylatitudeAlertMessage:"试_Please enter Latitude_验",
            emptylongitudeAlertMessage:"试_Please enter Longitude_验"
        }
    })
    
);