define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "试_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._验",
            selectFieldsText:"试_Select Form Fields_验",
            selectThemeText: "选择表单主题",
            fieldLabelPlaceHolder: "标注此字段",
            fieldDescPlaceHolder: "描述此字段",
            webmapText: "试_1. Webmap_验",
            layerText: "试_2. Layer_验",
            detailsText: "试_3. Details_验",
            fieldsText: "试_4. Fields_验",
            styleText: "试_5. Style_验",
            previewText: "试_6. Preview_验",
            publishText: "试_7. Publish_验",
            titleText: "GeoForm 构建器",
            descriptionText: "试_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._验",
            btnPreviousText: "上一步",
            btnNextText:"下一步",
            webmapTabTitleText: "选择 Web 地图",
            btnSelectWebmapText:"选择 Web 地图",
            layerTabTitleText: "选择可编辑图层",
            selectLayerLabelText:"图层",
            selectLayerDefaultOptionText:"选择图层",
            detailsTabTitleText:"表单详细信息",
            detailTitleLabelText: "标题",
            detailLogoLabelText: "徽标图像",
            detailDescriptionLabelText: "描述",
            fieldTabFieldHeaderText: "字段",
            fieldTabLabelHeaderText: "标注",
            fieldTabTypeHeaderText: "类型",
            fieldTabDescriptionHeaderText: "描述",
            previewApplicationText: "预览应用程序",
            saveApplicationText: "保存应用程序",
            saveText: "保存",
            toggleNavigationText: "试_Toggle navigation_验",
            formPlaceholderText: "试_My Form_验",
            imageLogoPlaceholderText: "试_http://www.mysite.com/myimage.png_验",
            shareBuilderInProgressTitleMessage: "试_Publishing GeoForm_验",
            shareBuilderProgressBarMessage:"试_Please Wait..._验",
            shareBuilderTitleMessage: "试_Your GeoForm has been updated & published!_验",
            shareBuilderTextMessage: "试_You can start collecting information by sharing with others_验",
            shareDialogFormText: "试_Form Link_验",
            geoformTitleText: "试_Geo Form_验",
            layerTabText: "试_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._验",
            detailsTabText:"试_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._验",
            fieldsTabText:"试_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._验",
            styleTabText: "试_Style your GeoForm using the themes below based on your preference._验",
            publishTabText: "试_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._验"
        }
    })
);