define(
     ({
        map: {
            error: "无法创建地图"
        },
        onlineStatus: {
            offline: "您目前正在离线工作。连接到服务器之前，提交的表单将保存在本地。",
            reconnecting: "重新连接&hellip;",
            pending: "重新建立网络连接时将提交 ${total} 个挂起的编辑内容。"
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "我的组织",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "我的内容",
                    favoritesLabel: "我的收藏夹"
                },
                title: "选择 Web 地图",
                searchTitle: "搜索",
                ok: "确定",
                cancel: "取消",
                placeholder: "输入搜索词"
            },
            groupdlg: {
                items: {
                    organizationLabel: "我的组织",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "我的内容",
                    favoritesLabel: "我的收藏夹"
                },
                title: "选择组",
                searchTitle: "搜索",
                ok: "确定",
                cancel: "取消",
                placeholder: "输入搜索词"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "试_Here is a link to a GeoForm_验"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "北移",
            utm_easting: "东移",
            utm_zone_number: "区域编号",
            geoFormGeneralTabText: "1. 输入信息",
            locationInformationText: "2. 选择位置",
            submitInformationText: "3. 完成表单",
            submitInstructions: "将此信息添加到地图。",
            myLocationText: "当前位置",
            locationDescriptionForMoreThanOneOption: "试_Specify the location for this entry by clicking/tapping the map or by using one of the following options_验.",
            locationDescriptionForOneOption: "试_Specify the location for this entry by clicking/tapping the map or by using the following option_验.",
            locationDescriptionForNoOption: "试_Specify the location for this entry by clicking/tapping the map_验.",
            addressText: "搜索",
            geographic: "经纬度",
            locationTabText: "位置",
            locationPopupTitle: "位置",
            submitButtonText: "提交输入内容",
            submitButtonTextLoading: "正在提交&hellip;",
            formValidationMessageAlertText: "以下为必填字段:",
            selectLocation: "试_Please select a location for your submission_验.",
            emptylatitudeAlertMessage: "请输入${openLink}纬度${closeLink}坐标。",
            emptylongitudeAlertMessage: "请输入${openLink}经度${closeLink}坐标。",
            shareUserTitleMessage: "感谢您所做的贡献!",
            entrySubmitted: "您的输入已提交至地图。",
            shareThisForm: "共享此表",
            shareUserTextMessage: "通知其他用户继续使用以下选项。",
            addAttachmentFailedMessage: "无法向图层添加附件",
            addFeatureFailedMessage: "无法向图层添加要素",
            noLayerConfiguredMessage: "试_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_验.",
            placeholderLatitude: "纬度 (Y)",
            placeholderLongitude: "经度 (X)",
            latitude: "纬度",
            longitude: "经度",
            findMyLocation: "查找我的位置",
            finding: "正在定位&hellip;",
            backToTop: "返回顶部",
            addressSearchText: "将在此处显示您的提交。您可以拖动图钉以更正位置。",
            shareModalFormText: "表单链接",
            close: "关闭",
            locationNotFound: "无法找到位置。",
            setLocation: "设置位置",
            find: "查找地址或地点",
            attachment: "附件",
            toggleDropdown: "切换下拉菜单",
            invalidString: "试_Please enter valid value_验.",
            invalidSmallNumber: "试_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_验.",
            invalidNumber: "试_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_验.",
            invalidFloat: "试_Please enter valid ${openStrong}floating point${closeStrong} value_验.",
            invalidDouble: "试_Please enter valid ${openStrong}double${closeStrong} value_验.",
            invalidLatLong: "试_Please enter valid latitude and longitude coordinates_验.",
            invalidUTM: "试_Please enter valid UTM coordinates_验.",
            invalidUSNG: "试_Please enter valid USNG coordinates_验.",
            invalidMGRS: "试_Please enter valid MGRS coordinates_验.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "选择&hellip;",
            applyEditsFailedMessage: "抱歉，无法提交您的输入。请重试。",
            requiredFields: "存在一些错误。请在下方进行更正。",
            requiredField: "(必填项)",
            error: "错误",
            textRangeHintMessage: "${openStrong}提示:${closeStrong} 最小值 ${minValue} 和最大值 ${maxValue}",
            dateRangeHintMessage: "${openStrong}提示:${closeStrong} 最小日期 ${minValue} 和最大日期 ${maxValue}",
            remainingCharactersHintMessage: "试_${value} characters remaining_验"
        },
        builder: {
            invalidUser: "抱歉，您无权查看此项目",
            invalidWebmapSelectionAlert: "所选 web 地图未包含可以使用的有效图层。请向您的 web 地图中添加可编辑的要素图层以继续。",
            invalidWebmapSelectionAlert2: "有关详细信息，请参阅 ${openLink}什么是要素服务?${closeLink}",
            selectFieldsText: "选择表单字段",
            selectThemeText: "选择表单主题",
            webmapText: "Web 地图",
            layerText: "图层",
            detailsText: "详细信息",
            fieldsText: "字段",
            styleText: "样式",
            optionText: "选项",
            previewText: "预览",
            publishText: "发布",
            optionsApplicationText: "选项",
            titleText: "构建器",
            descriptionText: "试_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_验.",
            btnPreviousText: "上一步",
            btnNextText: "下一步",
            webmapTabTitleText: "选择 web 地图",
            viewWebmap: "查看 web 地图",
            webmapDetailsText: "试_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_验",
            btnSelectWebmapText: "选择 web 地图",
            btnSelectWebmapTextLoading: "正在加载&hellip;",
            layerTabTitleText: "选择可编辑图层",
            selectLayerLabelText: "图层",
            selectLayerDefaultOptionText: "选择图层",
            detailsTabTitleText: "表单详细信息",
            detailTitleLabelText: "标题",
            detailLogoLabelText: "徽标图像",
            descriptionLabelText: "试_Form Instructions & Details_验",
            fieldDescriptionLabelText: "试_Help Text (optional)_验",
            fieldTabFieldHeaderText: "字段",
            fieldTabLabelHeaderText: "标注",
            fieldTabDisplayTypeHeaderText: "显示为",
            fieldTabOrderColumnText: "试_Order_验",
            fieldTabVisibleColumnText: "试_Enabled_验",
            selectMenuOption: "选择菜单",
            selectRadioOption: "单选按钮",
            selectTextOption: "文本",
            selectDateOption: "试_Date Picker_验",
            selectRangeOption: "试_Touch-Spinner_验",
            selectCheckboxOption: "复选框",
            selectMailOption: "电子邮件",
            selectUrlOption: "URL",
            selectTextAreaOption: "试_Text Area_验",
            previewApplicationText: "预览应用程序",
            saveApplicationText: "保存应用程序",
            saveText: "保存",
            toggleNavigationText: "切换导航",
            formPlaceholderText: "我的表单",
            shareBuilderInProgressTitleMessage: "发布 GeoForm",
            shareBuilderProgressBarMessage: "请稍候&hellip;",
            shareBuilderTitleMessage: "成功! 项目已保存",
            shareBuilderTextMessage: "可通过与其他成员共享来启动收集信息",
            shareModalFormText: "表单链接",
            shareBuilderSuccess: "已更新并发布 GeoForm!",
            geoformTitleText: "地理表单",
            layerTabText: "这是创建 GeoForm 所基于的图层。该图层必须是为编辑并共享适于受众的权限而启用的要素服务。",
            detailsTabText: "使用下方的\“表单详细信息\”框自定义标题、添加自定义徽标并为 GeoForm 受众提供简短描述。您可以在描述中添加其他资源的链接和联系信息，甚至可以将您的受众指向包含所有通过 GeoForm 所收集数据的 Web 制图应用程序。",
            fieldsTabText: "您可以在此处选择对 GeoForm 受众可见的字段，编辑受众可见的标签并添加简短描述以帮助输入数据。",
            styleTabText: "根据首选项使用下方的专题设置 GeoForm 样式。",
            publishTabText: "如果完成了自定义 GeoForm，请保存应用程序并与受众共享。您可随时返回至此构建器并根据反馈继续进行自定义。",
            headerSizeLabel:"试_Header Size_验",
            smallHeader: "使用小标题",
            bigHeader: "试_Use Large Header_验",
            pushpinText: "图钉",
            doneButtonText: "试_Save and Exit_验",
            fieldTabPlaceHolderHeaderText: "提示 (可选)",
            enableAttachmentLabelText: "试_${openStrong}Enable Attachments${closeStrong}_验",
            enableAttachmentLabelHint: "试_You can enable/disable the attachments here_验",
            attachmentIsRequiredLabelText: "试_${openStrong}Attachment Required${closeStrong}_验",
            attachmentIsRequiredLabelHint: "试_If necessary, users can be required to enter an attachment_验.",
            attachmentLabelText: "试_Attachment Button Label_验",
            attachmentLabelHint: "试_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_验",
            attachmentDescription: "附件描述",
            attachmentHint: "如有必要，可在此处提供其他附件说明。",
            jumbotronDescription: "试_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_验",
            shareGeoformText: "共享 Geoform",
            shareDescription: "通过共享面板，受众可以在提交后与其他协作者轻松共享 GeoForm - 可随时禁用此功能。",
            defaultMapExtent: "默认地图范围",
            defaultMapExtentDescription: "地图在提交后将重置为 web 地图中的默认范围 - 可随时禁用此功能。",
            pushpinOptionsDescription: "可从多种地图图钉颜色中选择，该颜色应不同于地图符号系统颜色以帮助用户将其提交内容放在地图上",
            selectLocationText: "位置选择依据",
            myLocationText: "我的位置",
            searchText: "搜索",
            coordinatesText: "经纬度坐标",
            usng: "USNG 坐标",
            mgrs: "MGRS 坐标",
            utm: "UTM 坐标",
            selectLocationSDescription: "允许用户使用这些方法选择位置",
            dragTooltipText:"试_Drag the field where you want it to appear_验",
            showHideLayerText:"试_Show/Hide Layer_验",
            showHideLayerHelpText:"试_You can configure the GeoForm to Show/Hide Layer_验"
        }
    })
);