define(
   ({
    map: {
      error: "试_Unable to create map_验"
    },
    onlineStatus: {
      offline: "试_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_验.",
      reconnecting: "试_Reconnecting&hellip;_验",
      pending: "试_${total} pending edit(s) will be submitted when a network connection is re-established_验."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "试_My Organization_验",
          onlineLabel: "试_ArcGIS Online_验",
          contentLabel: "试_My Content_验",
          favoritesLabel: "试_My Favorites_验"
        },
        title: "试_Select Web Map_验",
        searchTitle: "试_Search_验",
        ok: "试_Ok_验",
        cancel: "试_Cancel_验",
        placeholder: "试_Enter search term_验"
      },
      groupdlg: {
        items: {
          organizationLabel: "试_My Organization_验",
          onlineLabel: "试_ArcGIS Online_验",
          contentLabel: "试_My Content_验",
          favoritesLabel: "试_My Favorites_验"
        },
        title: "试_Select Group_验",
        searchTitle: "试_Search_验",
        ok: "试_Ok_验",
        cancel: "试_Cancel_验",
        placeholder: "试_Enter search term_验"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "试_Here is a link to a GeoForm_验"
      }
    },
    user: {
      mgrs: "试_MGRS_验",
      usng: "试_USNG_验",
      utm: "试_UTM_验",
      utm_northing: "试_Northing_验",
      utm_easting: "试_Easting_验",
      utm_zone_number: "试_Zone Number_验",
      selectLayerTabText: "试_${formSection} Select Form_验",
      geoFormGeneralTabText: "试_${formSection} Enter Information_验",
      locationInformationText: "试_${formSection} Select Location_验",
      submitInformationText: "试_${formSection} Complete Form_验",
      submitInstructions: "试_Add this information to the map_验.",
      myLocationText: "试_Current Location_验",
      locationDescriptionForMoreThanOneOption: "试_Specify the location for this entry by clicking/tapping the map or by using one of the following options_验.",
      locationDescriptionForOneOption: "试_Specify the location for this entry by clicking/tapping the map or by using the following option_验.",
      locationDescriptionForNoOption: "试_Specify the location for this entry by clicking/tapping the map_验.",
      addressText: "试_Search_验",
      geographic: "试_Lat/Lon_验",
      locationTabText: "试_Location_验",
      locationPopupTitle: "试_Location_验",
      submitButtonText: "试_Submit Entry_验",
      submitButtonTextLoading: "试_Submitting&hellip;_验",
      formValidationMessageAlertText: "试_The following fields are required_验:",
      selectLocation: "试_Please select a location for your submission_验.",
      emptylatitudeAlertMessage: "试_Please enter a ${openLink}latitude${closeLink} coordinate_验.",
      emptylongitudeAlertMessage: "试_Please enter a ${openLink}longitude${closeLink} coordinate_验.",
      shareUserTitleMessage: "试_Thank you for your contribution_验!",
      entrySubmitted: "试_Your entry has been submitted to the map_验.",
      shareThisForm: "试_Share This Form_验",
      shareUserTextMessage: "试_Tell others to contribute using the following options_验.",
      addAttachmentFailedMessage: "试_Unable to add attachment to layer_验",
      addFeatureFailedMessage: "试_Unable to add feature to layer_验",
      noLayerConfiguredMessage: "试_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_验.",
      placeholderLatitude: "试_Latitude (Y)_验",
      placeholderLongitude: "试_Longitude (X)_验",
      latitude: "试_Latitude_验",
      longitude: "试_Longitude_验",
      findMyLocation: "试_Locate Me_验",
      finding: "试_Locating&hellip;_验",
      backToTop: "试_Back to top_验",
      addressSearchText: "试_Your submission will appear here. You can drag the pin to correct the location_验.",
      shareModalFormText: "试_Form Link_验",
      close: "试_Close_验",
      locationNotFound: "试_Location could not be found_验.",
      setLocation: "试_Set Location_验",
      find: "试_Find address or place_验",
      attachment: "试_Attachment_验",
      toggleDropdown: "试_Toggle Dropdown_验",
      invalidString: "试_Please enter valid value_验.",
      invalidSmallNumber: "试_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_验.",
      invalidNumber: "试_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_验.",
      invalidFloat: "试_Please enter valid ${openStrong}floating point${closeStrong} value_验.",
      invalidDouble: "试_Please enter valid ${openStrong}double${closeStrong} value_验.",
      invalidLatLong: "试_Please enter valid latitude and longitude coordinates_验.",
      invalidUTM: "试_Please enter valid UTM coordinates_验.",
      invalidUSNG: "试_Please enter valid USNG coordinates_验.",
      invalidMGRS: "试_Please enter valid MGRS coordinates_验.",
      geoformTitleText: "试_GeoForm_验",
      domainDefaultText: "试_Select&hellip;_验",
      applyEditsFailedMessage: "试_Sorry your entry cannot be submitted. Please try again_验.",
      requiredFields: "试_There are some errors. Please correct them below_验.",
      requiredField: "试_(required)_验",
      error: "试_Error_验",
      textRangeHintMessage: "试_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_验",
      dateRangeHintMessage: "试_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_验",
      remainingCharactersHintMessage: "试_${value} characters remaining_验",
      mapFullScreen: "试_Full Screen_验",
      mapRestore: "试_Restore_验",
      filterSelectEmptyText: "试_Select_验",
      invalidLayerMessage: "试_Form layer does not exist. Please configure the application and set the layer_验.",
      selectedLayerText: "试_All_验"
    },
    builder: {
      invalidUser: "试_Sorry, you dont have permission to view this item_验",
      invalidWebmapSelectionAlert: "试_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_验.",
      invalidWebmapSelectionAlert2: "试_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_验",
      selectFieldsText: "试_Select Form Fields_验",
      selectThemeText: "试_Select Form Theme_验",
      webmapText: "试_Webmap_验",
      layerText: "试_Layer_验",
      detailsText: "试_Details_验",
      fieldsText: "试_Fields_验",
      styleText: "试_Style_验",
      optionText: "试_Options_验",
      previewText: "试_Preview_验",
      publishText: "试_Publish_验",
      optionsApplicationText: "试_Options_验",
      titleText: "试_Builder_验",
      descriptionText: "试_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_验.",
      btnPreviousText: "试_Previous_验",
      btnNextText: "试_Next_验",
      webmapTabTitleText: "试_Select a Webmap_验",
      viewWebmap: "试_View webmap_验",
      webmapDetailsText: "试_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_验",
      btnSelectWebmapText: "试_Choose Webmap_验",
      btnSelectWebmapTextLoading: "试_Loading&hellip;_验",
      layerTabTitleText: "试_Select Editable Layer_验",
      selectLayerLabelText: "试_Layer_验",
      selectLayerDefaultOptionText: "试_Select Layer_验",
      defaultBasemap: "试_Basemap Toggle_验",
      secondaryBasemap: "试_Default Basemap_验",
      detailsTabTitleText: "试_Form Details_验",
      detailTitleLabelText: "试_Title_验",
      detailLogoLabelText: "试_Logo Image_验",
      descriptionLabelText: "试_Form Instructions & Details_验",
      fieldDescriptionLabelText: "试_Help Text (optional)_验",
      fieldTabFieldHeaderText: "试_Field_验",
      fieldTabLabelHeaderText: "试_Label_验",
      fieldTabDisplayTypeHeaderText: "试_Display As_验",
      fieldTabOrderColumnText: "试_Order_验",
      fieldTabVisibleColumnText: "试_Enabled_验",
      selectMenuOption: "试_Select Menu_验",
      selectRadioOption: "试_Radio Button_验",
      selectTextOption: "试_Text_验",
      selectDateOption: "试_Date Picker_验",
      selectRangeOption: "试_Touch-Spinner_验",
      selectCheckboxOption: "试_Checkbox_验",
      selectMailOption: "试_Email_验",
      selectUrlOption: "试_URL_验",
      selectTextAreaOption: "试_Text Area_验",
      previewApplicationText: "试_Preview Application_验",
      saveApplicationText: "试_Save Application_验",
      saveText: "试_Save_验",
      toggleNavigationText: "试_Toggle navigation_验",
      formPlaceholderText: "试_My Form_验",
      shareBuilderInProgressTitleMessage: "试_Publishing GeoForm_验",
      shareBuilderProgressBarMessage: "试_Please Wait&hellip;_验",
      shareBuilderTitleMessage: "试_Success! Item saved_验",
      shareBuilderTextMessage: "试_You can start collecting information by sharing with others_验",
      shareModalFormText: "试_Form Link_验",
      shareBuilderSuccess: "试_Your GeoForm has been updated & published_验!",
      geoformTitleText: "试_Geo Form_验",
      layerTabText: "试_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_验.",
      detailsTabText: "试_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_验.",
      fieldsTabText: "试_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_验.",
      styleTabText: "试_Style your GeoForm using the themes below based on your preference_验.",
      publishTabText: "试_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_验.",
      headerSizeLabel: "试_Header Size_验",
      smallHeader: "试_Use Small Header_验",
      bigHeader: "试_Use Large Header_验",
      pushpinText: "试_Push pin_验",
      doneButtonText: "试_Save and Exit_验",
      fieldTabPlaceHolderHeaderText: "试_Hint (optional)_验",
      enableAttachmentLabelText: "试_${openStrong}Enable Attachments${closeStrong}_验",
      enableAttachmentLabelHint: "试_You can enable/disable the attachments here_验",
      attachmentIsRequiredLabelText: "试_${openStrong}Attachment Required${closeStrong}_验",
      attachmentIsRequiredLabelHint: "试_If necessary, users can be required to enter an attachment_验.",
      attachmentLabelText: "试_Attachment Button Label_验",
      attachmentLabelHint: "试_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_验",
      attachmentDescription: "试_Attachment Description_验",
      attachmentHint: "试_If necessary, you can provide additional attachment instructions here_验.",
      jumbotronDescription: "试_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_验",
      shareGeoformText: "试_Share Geoform_验",
      shareDescription: "试_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_验.",
      defaultMapExtent: "试_Default Map Extent_验",
      defaultMapExtentDescription: "试_The map will reset to the default extent in your web map after submission - this can be disabled at any time_验.",
      pushpinOptionsDescription: "试_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_验",
      selectLocationText: "试_Select Location By_验",
      myLocationText: "试_My Location_验",
      searchText: "试_Search_验",
      coordinatesText: "试_Latitude & Longitude Coordinates_验",
      usng: "试_USNG Coordinates_验",
      mgrs: "试_MGRS Coordinates_验",
      utm: "试_UTM Coordinates_验",
      selectLocationSDescription: "试_Allow users to select a location using these methods_验.",
      dragTooltipText: "试_Drag the field where you want it to appear_验",
      showHideLayerText: "试_Show Layer_验",
      showHideLayerHelpText: "试_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_验.",
      labelHelpMessage: "试_Label_验",
      placeHolderHintMessage: "试_Hint Text_验",
      placeHolderHelpMessage: "试_Help Text_验",
      selectTextOptionValue: "试_Filter Select_验",
      disableLogo: "试_Disable Logo_验",
      disableLogoDescription: "试_You can configure the GeoForm to Show/Hide the Logo in the form header_验",
      locateOnLoadText: "试_Locate On Load_验",
      locateOnLoadDescription: "试_You can configure the GeoForm to use the current location on page load_验",
      selectLayerFieldTabText: "试_Select Layer_验",
      allLayerSelectOptionText:"试_All_验"
    }
  })
);