define(
	 ({
		header: {
			start: "Đ_start___ớ",
			searchStories: "Đ_Search your stories________ớ...",
			filter: "Đ_Filter___ớ",
			sort: "Đ_Sort__ớ",
			sortColon: "Đ_Sort___ớ:",
			numResults: "Đ_Results: {{NUM_RESULTS}}________ớ",
			sortBy: "Đ_Sort by___ớ",
			dateModified: "Đ_Date modified_____ớ",
			title: "Đ_Title___ớ",
			type: "Đ_Type__ớ",
			views: "Đ_Views___ớ",
			errors: "Đ_Errors___ớ",
			filterBy: "Đ_Filter by____ớ",
			filterItems: "Đ_Filter Items_____ớ",
			apps: "Đ_Apps__ớ",
			sharing: "Đ_Sharing___ớ",
			clearAll: "Đ_Clear all____ớ",
			clearSearch: "Đ_Clears the search______ớ",
			logOut: "Đ_Log Out___ớ",
			mainQuote: "Đ_Storytelling is the most powerful way to put ideas into the world today_______________________ớ.",
			quoteSource: "Đ_Robert McKee_____ớ",
			checkYourStories: "Đ_Check Stories_____ớ",
			createStory: "Đ_Create Story_____ớ",
			totalStories: "Đ_Total stories: {{NUM_STORIES}}__________ớ",
			noIssues: "Đ_All good___ớ",
			userStories: "Đ_Stories of {{USER_NAME}}________ớ",
			headerDisabledTooltip: "Đ_Please wait while we work some magic_____________ớ...",
			notOnTouch: "Đ_Not available on touch devices__________ớ",
		},
		deleteModal: {
			title: "Đ_Confirm Delete_____ớ",
			warningText: "Đ_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________ớ.",
			deleteText: "Đ_Delete___ớ",
			cancel: "Đ_Cancel___ớ"
		},
		loading: {
			loadingText: "Đ_Loading your stories________ớ..."
		},
		cantFindStories: {
			whereAreStories: "Đ_Not seeing your story________ớ?",
			notSeeExplanation: "Đ_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________ớ.",
			faq: "Đ_FAQ__ớ",
			followingStoriesToUpdate: "Đ_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________ớ:",
			gettingStories: "Đ_Searching for stories created with early versions of our applications that need to be updated______________________________ớ...",
			title: "Đ_Title___ớ",
			typeOfStoryMap: "Đ_Type__ớ",
			lastModified: "Đ_Last modified_____ớ",
			allUpToDate: "Đ_No stories created with early versions of our applications need to be updated________________________ớ.",
			updateAll: "Đ_Update All____ớ",
			errorScanningForStories: "Đ_There was an error searching your stories______________ớ.",
			close: "Đ_Close___ớ",
			updates: "Đ_Updates___ớ",
			updatingNumberOfNumber: "Đ_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________ớ",
			updatingNumberOfNumberAlt: "Đ_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________ớ",
			updateSucceeded: "Đ_Update succeeded______ớ!",
			reloadingStories: "Đ_Reloading your stories_________ớ...",
			errorUpdatingStories: "Đ_There was an error updating your stories_____________ớ.",
			partialUpdateMessage: "Đ_Stories updated successfully: {{NUM_UPDATED}}_______________ớ"
		},
		signIn: {
			signInTitle: "Đ_Sign in to Story Maps_______ớ",
			signInTo: "Đ_Sign in with your existing ArcGIS Online account to_________________ớ:",
			explanationOne: "Đ_Create compelling story maps to tell your stories________________ớ.",
			explanationTwo: "Đ_Use your maps and data from ArcGIS Online in your story maps___________________ớ.",
			explanationThree: "Đ_Manage your story maps and check the status of their content___________________ớ.",
			dontHaveAccount: "Đ_Don't have an ArcGIS Online account? Sign up for a________________ớ:",
			publicAccount: "Đ_Free non-commercial public account___________ớ",
			orgAccount: "Đ_Free trial ArcGIS subscription__________ớ",
			timeExpired: "Đ_Your sign-in expired. Sign in again to pick up where you left off_____________________ớ.",
			apiDidntLoad: "Đ_Something isn't loading correctly. Try refreshing the page___________________ớ.",
			needAccount: "Đ_Need an account______ớ?",
			letsGo: "Đ_Let's go____ớ!"
		},
		sharingLevel: {
			publicMessage: "Đ_Public___ớ",
			privateMessage: "Đ_Private___ớ",
			organization: "Đ_Organization_____ớ",
			changedSharing: "Đ_Changed sharing level________ớ.",
			unableToChange: "Đ_Unable to change sharing_________ớ.",
			partOfMap: "Đ_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________ớ.",
			storyPublicContentOrg: "Đ_Your story is public, so its content can't be shared only with your organization_________________________ớ",
			storyPublicContentPrivate: "Đ_Your story is public, so its content can't be private_________________ớ",
			mapOrg: "Đ_Sharing your map to your organization would break your story___________________ớ",
			layerOrg: "Đ_Sharing your layer to your organization would break your story____________________ớ",
			mapPrivate: "Đ_Making your map private would break your story_______________ớ",
			layerPrivate: "Đ_Making your layer private would break your story_______________ớ"
		},
		collectionList: {
			advocacy: "Đ_Advocacy and Outreach_______ớ",
			architecture: "Đ_Architecture and Design________ớ",
			conservation: "Đ_Conservation and Sustainability__________ớ",
			culture: "Đ_Culture___ớ",
			destinations: "Đ_Destinations and Tourism________ớ",
			disasters: "Đ_Disasters and Recovery________ớ",
			economy: "Đ_Economy and Development________ớ",
			entertainment: "Đ_Entertainment_____ớ",
			history: "Đ_History___ớ",
			infrastructure: "Đ_Infrastructure_____ớ",
			marketing: "Đ_Marketing____ớ",
			nature: "Đ_Nature and Environment________ớ",
			news: "Đ_News and Events______ớ",
			oceans: "Đ_Oceans___ớ",
			parks: "Đ_Parks and Recreation_______ớ",
			people: "Đ_People and Society______ớ",
			planning: "Đ_Planning and Analysis_______ớ",
			publicArt: "Đ_Public Art____ớ",
			science: "Đ_Science and Technology________ớ",
			sport: "Đ_Sport___ớ",
			travelogues: "Đ_Travelogues____ớ"
		},
		types: {
			custom: "Đ_Custom___ớ",
			notSpecified: "Đ_Type not specified______ớ"
		},
		storyMap: {
			shared: "Đ_Shared___ớ",
			saveFailed: "Đ_Error saving_____ớ",
			numViews: "Đ_Views: {{NUM_VIEWS}}_______ớ",
			editStory: "Đ_Edit Story____ớ",
			viewLive: "Đ_View Live____ớ",
			preview: "Đ_Preview___ớ",
			deleteButton: "Đ_Delete___ớ",
			modified: "Đ_Modified {{DATE}}______ớ",
			summary: "Đ_Summary___ớ",
			loading: "Đ_Loading____ớ...",
			collapse: "Đ_collapse___ớ",
			close: "Đ_close___ớ",
			hide: "Đ_hide__ớ",
			notAvailableWhenBroken: "Đ_Your story has issues below_________ớ",
			cantBeDeleted: "Đ_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________ớ",
			shareDialog: {
				title: "Đ_Share your story with the world___________ớ!",
				notPublicWarning: "Đ_Your story is shared with your organization. Only members of your organization will be able to view it________________________________ớ.",
				embedStory: "Đ_Embed your story______ớ",
				shortLink: "Đ_Shortlink____ớ",
				hideHeaderBar: "Đ_Hide header bar______ớ",
				copied: "Đ_Copied___ớ",
				small: "Đ_small___ớ",
				medium: "Đ_medium___ớ",
				large: "Đ_large___ớ",
				custom: "Đ_custom___ớ",
				widthAbbreviation: "Đ_w_ớ",
				heightAbbreviation: "Đ_h_ớ",
				emptyDimension: "Đ_Enter a dimension______ớ.",
				seeExample: "Đ_Preview your embed______ớ",
				removeHeader: "Đ_Hide application header________ớ"
			},
			maps: {
				unableRetrieveTitle: "Đ_Unable to retrieve maps________ớ",
				unableRetrieveDescription: "Đ_We weren't able to retrieve maps for this story map_________________ớ."
			},
			images: {
				unableRetrieveTitle: "Đ_Unable to retrieve images_________ớ",
				unableRetrieveDescription: "Đ_We weren't able to retrieve images for this story map_________________ớ."
			},
			tags: {
				tags: "Đ_Tags__ớ",
				collectionTags: "Đ_Subject___ớ",
				selectASubject: "Đ_Select a subject______ớ",
				save: "Đ_Save__ớ",
				saved: "Đ_Saved___ớ",
				errorSaving: "Đ_Error saving_____ớ",
				tagTip: "Đ_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________ớ."
			},
			submitToGallery: {
				gallerySubmission: "Đ_Story Maps Gallery______ớ",
				canSubmitIf: "Đ_You can nominate your story to the gallery if it contains the following_______________________ớ:",
				hasOwnImage: "Đ_Custom thumbnail______ớ",
				chosenSubject: "Đ_A subject and some tags________ớ",
				chosenSubjectAlt: "Đ_A {{SUBJECT}} and some tags_________ớ",
				storyMapTopicSubject: "Đ_subject___ớ",
				sharedPublicly: "Đ_Shared publicly______ớ",
				noBrokenContent: "Đ_No broken content______ớ",
				nominateToGallery: "Đ_Nominate to Gallery_______ớ",
				comingSoon: "Đ_Coming soon_____ớ!",
				submitted: "Đ_Submitted____ớ",
				errorSubmitting: "Đ_Error submitting______ớ",
				ourGallery: "Đ_The Story Maps gallery________ớ",
				galleryTip: "Đ_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________ớ."
			},
			placeholders: {
				noSummary: "Đ_No summary, click to add one__________ớ."
			},
			errors: {
				cantDeleteStory: "Đ_Unable to delete story________ớ.",
				unableToFind: "Đ_Unable to find content________ớ",
				unableToRetrieve: "Đ_We weren't able to retrieve the content for this story map___________________ớ."
			},
			socialSharing: {
				availableWhenPublic: "Đ_This option will be available when your story is public__________________ớ"
			},
			dialog: {
				back: "Đ_Back__ớ",
				close: "Đ_Close___ớ",
				cancel: "Đ_Cancel___ớ"
			},
			imagePicker: {
				changeDefault: "Đ_Change the default image________ớ",
				changeImage: "Đ_Change thumbnail______ớ",
				uploadImage: "Đ_Upload thumbnail______ớ",
				chooseImage: "Đ_Choose thumbnail______ớ",
				chooseAnImage: "Đ_Choose an Image______ớ",
				notInIEVersion: "Đ_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________ớ.",
				or: "Đ_Or__ớ",
				uploadAnImage: "Đ_Upload an Image______ớ",
				supportedFileTypes: "Đ_Supports .png, .jpg, .gif_________ớ",
				imageSizeMessage: "Đ_Your image needs to be at least 286 px wide by 190 px tall___________________ớ.",
				minimumDimensions: "Đ_Minimum: 286 x 190px_______ớ",
				imagesLoading: "Đ_Loading images______ớ...",
				noImages: "Đ_This story has no images________ớ",
				errorLoading: "Đ_Unable to retrieve the images in this story______________ớ",
				clickBelowTip: "Đ_Click the button below to upload an image______________ớ.",
				dragAndDrop: "Đ_Drag and Drop_____ớ",
				cropImage: "Đ_Crop Image____ớ",
				saveImage: "Đ_Save Image____ớ",
				save: "Đ_Save__ớ",
				savingImage: "Đ_Saving your image_______ớ...",
				saved: "Đ_Saved___ớ!",
				errorSaving: "Đ_Unable to save your image_________ớ.",
				skipAndCrop: "Đ_Skip and Crop for me_______ớ",
				wrongFormat: "Đ_This file type is not supported___________ớ.",
				noCropWarning: "Đ_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________ớ."
			}
		},
		content: {
			media: {
				maps: "Đ_Maps__ớ",
				images: "Đ_Images___ớ",
				videos: "Đ_Videos___ớ",
				webpages: "Đ_Webpages___ớ",
				tags: "Đ_Tags__ớ",
				gallery: "Đ_Gallery___ớ"
			},
			headers: {
				status: "Đ_Status___ớ",
				source: "Đ_Source___ớ",
				name: "Đ_Name__ớ",
				shared: "Đ_Shared___ớ"
			},
			component: {
				mapTour: "Đ_Point Number_____ớ",
				bullet: "Đ_Bullet___ớ",
				tab: "Đ_Tab__ớ",
				accordion: "Đ_Section___ớ",
				mapJournal: "Đ_Section___ớ"
			},
			titleType: {
				mapTour: "Đ_Caption___ớ",
				mapJournal: "Đ_URL__ớ",
				mapSeries: "Đ_URL__ớ"
			},
			actions: {
				viewMap: "Đ_View Map___ớ",
				editMap: "Đ_Edit Map___ớ",
				fix: "Đ_Fix__ớ",
				viewLayer: "Đ_View Layer____ớ"
			},
			contentType: {
				mainStage: "Đ_main stage action______ớ",
				sidePanel: "Đ_description____ớ"
			},
			notification: {
				refreshExplanation: "Đ_Check your story again________ớ",
				checking: "Đ_Checking____ớ...",
				foundSomeIssues: "Đ_We found some issues_______ớ",
				noIssuesFound: "Đ_No issues found______ớ",
				storyPublic: "Đ_Your story is now public________ớ",
				storyOrg: "Đ_Your story is now shared to your organization_______________ớ",
				storyPrivate: "Đ_Your story is now private_________ớ",
				mapPublic: "Đ_Your map is now public________ớ",
				mapOrg: "Đ_Your map is now shared to your organization______________ớ",
				mapPrivate: "Đ_Your map is now private________ớ",
				layerPublic: "Đ_Your layer is now public________ớ",
				layerOrg: "Đ_Your layer is now shared to your organization_______________ớ",
				layerPrivate: "Đ_Your layer is now private_________ớ",
				contentPublic: "Đ_Your content is now public_________ớ",
				contentOrg: "Đ_Your content is now shared to your organization_______________ớ",
				contentPrivate: "Đ_Your content is now private_________ớ",
				storyAndContentPublic: "Đ_Your story and its content are now public_____________ớ",
				storyAndContentOrg: "Đ_Your story and its content are now shared to your organization____________________ớ",
				storyAndContentPrivate: "Đ_Your story and its content are now private______________ớ",
				shareBulkPrompt: "Đ_Do you want to share your storyâ€™s content accordingly__________________ớ?",
				layersPublic: "Đ_Some layers have also been shared publicly______________ớ",
				layersOrg: "Đ_Some layers have also been shared with your organization__________________ớ",
				layersPrivate: "Đ_Some layers have also been made private_____________ớ",
				mapsPublic: "Đ_Some maps have also been shared publicly_____________ớ",
				mapsOrg: "Đ_Some maps have also been shared with your organization_________________ớ",
				mapsPrivate: "Đ_Some maps have also been made private____________ớ",
				layersAndMapsPublic: "Đ_Some maps and layers have also been shared publicly________________ớ",
				layersAndMapsOrg: "Đ_Some maps and layers have also been shared with your organization_____________________ớ",
				layersAndMapsPrivate: "Đ_Some maps and layers have also been made private_______________ớ",
				yes: "Đ_Yes__ớ",
				no: "Đ_No__ớ",
				premiumPublicSuccess: "Đ_Your premium content is now publicly accessible_______________ớ",
				subscriptionPublicSuccess: "Đ_Your subscription content is now publicly accessible_________________ớ"
			},
			errors: {
				publicDisabled: "Đ_Sharing publicly has been disabled by the Administrator__________________ớ",
				noMapName: "Đ_Could Not Retrieve Map Name_________ớ",
				notPublic: "Đ_NOT PUBLIC____ớ",
				inaccessible: "Đ_INACCESSIBLE_____ớ",
				deleted: "Đ_DELETED___ớ",
				cantAccessVideo: "Đ_Could Not Access Video________ớ",
				noStoriesFound: "Đ_We could not find any Story Maps in your content________________ớ.",
				cantShowStories: "Đ_Unable to show your story maps. Please try again later__________________ớ.",
				consolationSearch: "Đ_We couldn't find any stories__________ớ.",
				notCompatibleWithBrowser : "Đ_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________ớ.",
				pleaseUpdateBrowser: "Đ_Please update your browser_________ớ.",
				searchTip: "Đ_Try and simplify it a bit_________ớ.",
				consolationNoStories: "Đ_Welcome to My Stories________ớ!",
				noStoriesTip: "Đ_To make your first story map, check out the Apps page_________________ớ.",
				letsGo: "Đ_Let's Go___ớ",
				cantChangeSharingLevel: "Đ_Unable to change sharing level__________ớ",
				cantChangeSharingLevels: "Đ_Unable to change sharing levels__________ớ",
				errorUpdatingTitle: "Đ_Error updating title_______ớ",
				errorUpdatingSummary: "Đ_Error updating summary________ớ",
				noEmptyTitle: "Đ_Title cannot be empty_______ớ",
				cantUpdatePremiumContent: "Đ_Unable to update premium content___________ớ",
				cantUpdateSubscriptionContent: "Đ_Unable to update subscription content____________ớ",
				createFirstStory: "Đ_Create My First Story_______ớ"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Đ_Map has been deleted_______ớ",
				layerHasBeenDeleted: "Đ_Layer has been deleted________ớ",
				mapIsInaccessible: "Đ_Map is inaccessible_______ớ",
				layerIsInaccessible: "Đ_Layer is inaccessible_______ớ",
				mapNotYoursNotAccessible: "Đ_Map is owned by someone else and isn't accessible________________ớ",
				layerServiceOkItemNot: "Đ_Layer was added as an item that is deleted or inaccessible__________________ớ",
				layerNotYoursNotAccessible: "Đ_Layer is owned by someone else and isn't accessible________________ớ",
				mapOthersSharedBelowLevel: "Đ_Map is not owned by you and is not public_____________ớ",
				layerOthersSharedBelowLevel: "Đ_Layer is not owned by you and is not public______________ớ",
				noMapNoDetails: "Đ_Without the map details, we can't tell you anything about the layers_____________________ớ",
				mapIsPrivate: "Đ_Map is private_____ớ",
				mapIsOrg: "Đ_Map is only shared in your organization_____________ớ",
				layerIsPrivate: "Đ_Layer is private______ớ",
				layerIsOrg: "Đ_Layer is only shared in your organization_____________ớ",
				imageInaccessible: "Đ_This image is inaccessible_________ớ",
				videoInaccessible: "Đ_This video is inaccessible_________ớ",
				webpageInaccessible: "Đ_This web page is inaccessible__________ớ",
				layerSecureService: "Đ_Layer is a secure service_________ớ",
				mapSecureService: "Đ_Map is a secure service________ớ",
				layerConsumesCredits: "Đ_Layer is premium content and consumes credits_______________ớ",
				layerSubscriptionContent: "Đ_Layer is subscription content__________ớ",
				mapConsumesCredits: "Đ_Map is premium content and consumes credits______________ớ",
				mapSubscriptionContent: "Đ_Map is subscription content_________ớ"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Đ_We're not able to check this type of layer______________ớ",
				cantScanThisType: "Đ_Layer is not a type of layer we can check_____________ớ",
				webpageNotScanned: "Đ_Webpages are not checked for issues____________ớ"
			},
			scanningErrors: {
				deletedMap: "Đ_Deleted content______ớ",
				inaccessibleMap: "Đ_Inaccessible map content________ớ",
				notYoursNotAccessible: "Đ_Content not owned by you and not public_____________ớ",
				serviceOkItemNot: "Đ_Working layers but inaccessible items____________ớ",
				someContentNotPublic: "Đ_Content not shared publicly_________ớ",
				someContentPrivate: "Đ_Private content______ớ",
				othersSharedBelowLevel: "Đ_Content not owned by you and not public_____________ớ",
				premiumContent: "Đ_Premium content______ớ",
				subscriptionContent: "Đ_Subscription content_______ớ",
				secureService: "Đ_Secure services______ớ",
				inaccessibleImage: "Đ_Inaccessible images_______ớ",
				inaccessibleVideo: "Đ_Inaccessible videos_______ớ",
				inaccessibleWebpage: "Đ_Inaccessible webpages_______ớ"
			},
			scanningErrorTips: {
				deletedMapTip: "Đ_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ớ.",
				inaccessibleMapTip: "Đ_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ớ.",
				notYoursNotAccessibleTip: "Đ_Tip: Open the web map and remove the layer or map from the story_____________________ớ.",
				serviceOkItemNotTip: "Đ_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________ớ.",
				ignore: "Đ_Ignore___ớ",
				fix: "Đ_Fix__ớ",
				clickToShareOrg: "Đ_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________ớ.",
				clickToSharePublic: "Đ_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________ớ.",
				shareOrg: "Đ_Share to your org______ớ",
				sharePublicly: "Đ_Share publicly_____ớ",
				othersSharedBelowLevelTip: "Đ_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________ớ.",
				secureServiceTip: "Đ_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________ớ.",
				blogArticle: "Đ_here__ớ",
				premiumContentTip: "Đ_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________ớ.",
				premiumContentPublicTip: "Đ_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________ớ.",
				subscriptionContentTip: "Đ_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________ớ.",
				agolCredits: "Đ_ArcGIS Online credits_______ớ",
				credits: "Đ_credits___ớ",
				makePublic: "Đ_Make public____ớ",
				confirm: "Đ_Confirm___ớ",
				inaccessibleImageTip: "Đ_Tip: Provide the missing image or remove the reference to it___________________ớ.",
				inaccessibleVideoTip: "Đ_Tip: Provide the missing video or remove the reference to it___________________ớ.",
				inaccessibleWebpageTip: "Đ_Tip: Provide the missing web page or remove the reference to it____________________ớ."
			},
			removeLayer: {
				title: "Đ_Fix Layer Issue______ớ",
				layersWithIssue: "Đ_Layers with this issue: {{NUM_WITH_ISSUE}}______________ớ",
				issueExplanation: "Đ_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________ớ.",
				issueSolution: "Đ_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________ớ:",
				editMap: "Đ_Edit Your Map_____ớ",
				clickBelowWhenDone: "Đ_When you have finished editing, click the button below__________________ớ:",
				rescanAndClose: "Đ_Rescan And Close______ớ"
			},
			info: {
				ownedBy: "Đ_This item is owned by {{USER_NAME}}____________ớ",
				unknownUser: "Đ_someone else_____ớ",
				untitledSection: "Đ_(Untitled section)______ớ",
				introRecord: "Đ_Introduction_____ớ"
			},
			layers: {
				layersHeader: "Đ_Layers___ớ",
				noLayers: "Đ_(No Layers)____ớ",
				basemapParens: "Đ_(basemap)____ớ"
			},
			images: {
				thumbnails: "Đ_Thumbnails____ớ",
				thumbnail: "Đ_Thumbnail____ớ",
				thumbnailParens: "Đ_(thumbnail)____ớ"
			},
			general: {
				noTitle: "Đ_(no title)____ớ",
				loading: "Đ_Loading____ớ..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "Đ_sections___ớ",
				secondTitle: "Đ_style___ớ",
				secondValueA: "Đ_side panel____ớ",
				secondValueB: "Đ_floating panel_____ớ",
				thirdTitle: "Đ_maps__ớ"
			},
			mapTour: {
				firstTitle: "Đ_tour points____ớ",
				secondTitle: "Đ_style___ớ",
				secondValueA: "Đ_integrated____ớ",
				secondValueB: "Đ_three-panel____ớ",
				thirdTitle: "Đ_basemap___ớ",
				thirdValueLoading: "Đ_Loading____ớ...",
				thirdValueUnknown: "Đ_unknown___ớ"
			},
			mapSeries: {
				firstTitleA: "Đ_bullets___ớ",
				firstTitleB: "Đ_sections___ớ",
				firstTitleC: "Đ_tabs__ớ",
				secondTitle: "Đ_style___ớ",
				secondValueA: "Đ_bulleted___ớ",
				secondValueB: "Đ_side accordion_____ớ",
				secondValueC: "Đ_tabbed___ớ",
				thirdTitle: "Đ_maps__ớ"
			},
			swipeSpyglass: {
				firstTitle: "Đ_points of interest______ớ",
				secondTitle: "Đ_style___ớ",
				secondValueA: "Đ_swipe___ớ",
				secondValueB: "Đ_spyglass___ớ",
				thirdTitle: "Đ_maps__ớ"
			}
		},
		progress: {
			checkingStories: "Đ_Checking your stories for issues____________ớ...",
			stop: "Đ_Stop__ớ",
			exit: "Đ_Exit__ớ",
			dismiss: "Đ_Dismiss___ớ",
			done: "Đ_Done___ớ.",
			noStoriesWithIssuesLower: "Đ_No issues found______ớ!",
			storiesErrorFree: "Đ_Looks like your stories are error-free____________ớ",
			scanAllError: "Đ_Unable to scan -- we couldn't retrieve one or more of your stories_____________________ớ",
			scanProgress: "Đ_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________ớ",
			scanStopped: "Đ_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________ớ",
			storiesWithIssues: "Đ_Stories with issues: {{NUM_STORIES}}____________ớ"
		}
    })
);