define(
	 ({
		header: {
			start: "bắt đầu",
			searchStories: "Tìm kiếm câu chuyện của bạn...",
			filter: "Lọc",
			sort: "Sắp xếp",
			sortColon: "Sắp xếp:",
			numResults: "Kết quả: {{NUM_RESULTS}}",
			sortBy: "Sắp xếp theo",
			dateModified: "Ngày sửa đổi",
			title: "Tiêu đề",
			type: "Loại",
			views: "Xem",
			errors: "Lỗi",
			filterBy: "Lọc theo",
			filterItems: "Lọc Mục",
			apps: "Ứng dụng",
			sharing: "Chia sẻ",
			clearAll: "Xóa tất cả",
			clearSearch: "Xóa tìm kiếm",
			logOut: "Đăng xuất",
			mainQuote: "Ngày nay, kể chuyện là cách hiệu quả nhất để đưa ý tưởng ra thế giới.",
			quoteSource: "Robert McKee",
			checkYourStories: "Kiểm tra Câu chuyện",
			createStory: "Tạo Câu chuyện",
			totalStories: "Tổng số câu chuyện: {{NUM_STORIES}}",
			noIssues: "Tất cả đều tốt",
			userStories: "Câu chuyện của {{USER_NAME}}",
			headerDisabledTooltip: "Vui lòng chờ trong lúc chúng tôi làm vài điều kỳ diệu...",
			notOnTouch: "Không khả dụng trên thiết bị cảm ứng",
		},
		deleteModal: {
			title: "Xác nhận Xóa",
			warningText: "Bạn có chắc chắn muốn gỡ bỏ câu chuyệnÂ này không? Bạn sẽ không thể khôi phục câu chuyện này.",
			deleteText: "Xóa",
			cancel: "Hủy"
		},
		loading: {
			loadingText: "Đang tải câu chuyện của bạn..."
		},
		cantFindStories: {
			whereAreStories: "Không thấy câu chuyện của bạn?",
			notSeeExplanation: "Câu chuyện Của tôi sẽ chỉ liệt kê các story map được lưu trữ trong ArcGIS và được tạo bằng ứng dụng {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} hoặc {{SWIPE_SPYGLASS}}. Hãy xem {{FAQ}} của chúng tôi để biết thêm thông tin.",
			faq: "Câu hỏi thường gặp",
			followingStoriesToUpdate: "Các câu chuyện sau được tạo bằng các ứng dung phiên bản cũ của chúng tôi, vì vậy cần được cập nhật để các câu chuyện được liệt kê trong Câu chuyện Của tôi:",
			gettingStories: "Tìm kiếm câu chuyện được tạo bằng phiên bản cũ hơn của các ứng dụng của chúng tôi cần được cập nhật...",
			title: "Tiêu đề",
			typeOfStoryMap: "Loại",
			lastModified: "Chỉnh sửa lần cuối",
			allUpToDate: "Không có câu chuyện nào được tạo bằng ứng dụng ở phiên bản cũ của chúng tôi cần được cập nhật.",
			updateAll: "Cập nhật Tất cả",
			errorScanningForStories: "Đã có lỗi khi tìm kiếm câu chuyện của bạn.",
			close: "Đóng",
			updates: "Cập nhật",
			updatingNumberOfNumber: "Đang cập nhật {{CURRENT_NUMBER}} trên {{TOTAL}}",
			updatingNumberOfNumberAlt: "Đang cập nhật {{CURRENT_NUMBER}} / {{TOTAL}}",
			updateSucceeded: "Cập nhật thành công!",
			reloadingStories: "Tải lại câu chuyện của bạn...",
			errorUpdatingStories: "Đã có lỗi khi cập nhật câu chuyện của bạn.",
			partialUpdateMessage: "Câu chuyện được cập nhật thành công: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "Đăng nhập vào Story Maps",
			signInTo: "Đăng nhập bằng Tài khoản ArcGIS Online hiện có của bạn vào:",
			explanationOne: "Tạo các story map hấp dẫn để kể câu chuyện của bạn.",
			explanationTwo: "Sử dụng bản đồ và dữ liệu từ ArcGIS Online trong story map của bạn.",
			explanationThree: "Quản lý story map và kiểm tra trạng thái nội dung của các story map này.",
			dontHaveAccount: "Không có tài khoản ArcGIS Online? Hãy đăng ký để nhận:",
			publicAccount: "Tài khoản công cộng phi thương mại miễn phí",
			orgAccount: "Gói đăng ký ArcGIS dùng thử miễn phí",
			timeExpired: "Phiên đăng nhập của bạn đã hết hạn. Hãy đăng nhập lại để tiếp tục ở nơi bạn đã dừng lại.",
			apiDidntLoad: "Đã xảy ra lỗi tải không đúng. Hãy thử làm mới trang.",
			needAccount: "Cần tài khoản?",
			letsGo: "Hãy bắt đầu!"
		},
		sharingLevel: {
			publicMessage: "Công khai",
			privateMessage: "Riêng tư",
			organization: "Tổ chức",
			changedSharing: "Thay đổi cấp độ chia sẻ.",
			unableToChange: "Không thể thay đổi chia sẻ.",
			partOfMap: "Mục này nằm trong bản đồ. Để thay đổi cấp độ chia sẻ, bạn phải thay đổi cấp độ chia sẻ của bản đồ.",
			storyPublicContentOrg: "Câu chuyện của bạn ở chế độ công khai, nên nội dung của câu chuyện không thể được chia sẻ chỉ trong tổ chức của bạn",
			storyPublicContentPrivate: "Câu chuyện của bạn ở chế độ công khai, nên nội dung của câu chuyện không thể ở chế độ riêng tư",
			mapOrg: "Chia sẻ bản đồ của bạn với tổ chức của bạn sẽ phá vỡ câu chuyện của bạn",
			layerOrg: "Chia sẻ lớp của bạn với tổ chức của bạn sẽ phá vỡ câu chuyện của bạn",
			mapPrivate: "Để bản đồ của bạn ở chế độ riêng tư sẽ phá vỡ câu chuyện của bạn",
			layerPrivate: "Để lớp của bạn ở chế độ riêng tư sẽ phá vỡ câu chuyện của bạn"
		},
		collectionList: {
			advocacy: "Bênh vực và Cứu trợ",
			architecture: "Kiến trúc và Thiết kế",
			conservation: "Bảo tồn và Bền vững",
			culture: "Văn hóa",
			destinations: "Điểm đến và Du lịch",
			disasters: "Thảm họa và Phục hồi",
			economy: "Kinh tế và Phát triển",
			entertainment: "Giải trí",
			history: "Lịch sử",
			infrastructure: "Hạ tầng",
			marketing: "Tiếp thị",
			nature: "Thiên nhiên và Môi trường",
			news: "Tin tức và Sự kiện",
			oceans: "Đại dương",
			parks: "Công viên và Giải trí",
			people: "Con người và Xã hội",
			planning: "Kế hoạch và Phân tích",
			publicArt: "Nghệ thuật Công chúng",
			science: "Khoa học và Công nghệ",
			sport: "Thể thao",
			travelogues: "Chiếu phim thám hiểm"
		},
		types: {
			custom: "Tùy chỉnh",
			notSpecified: "Loại không xác định"
		},
		storyMap: {
			shared: "Đã chia sẻ",
			saveFailed: "Lỗi trong khi lưu",
			numViews: "Xem: {{NUM_VIEWS}}",
			editStory: "Sửa Câu chuyện",
			viewLive: "Xem Câu chuyện",
			preview: "Xem trước",
			deleteButton: "Xóa",
			modified: "Sửa đổi {{DATE}}",
			summary: "Tóm tắt",
			loading: "Đang tải...",
			collapse: "thu gọn",
			close: "đóng",
			hide: "ẩn",
			notAvailableWhenBroken: "Câu chuyện của bạn có các sự cố bên dưới",
			cantBeDeleted: "Câu chuyện này đã được kích hoạt bảo vệ chống xóa. Hãy xem trang mục của câu chuyện trên ArcGIS Online để tắt.",
			shareDialog: {
				title: "Chia sẻ câu chuyện của bạn với thế giới!",
				notPublicWarning: "Câu chuyện của bạn được chia sẻ với tổ chức của bạn. Chỉ các thành viên tổ chức của bạn mới có thể xem.",
				embedStory: "Nhúng câu chuyện của bạn",
				shortLink: "Shortlink",
				hideHeaderBar: "Ẩn thanh tiêu đề",
				copied: "Đã sao chép",
				small: "nhỏ",
				medium: "trung bình",
				large: "lớn",
				custom: "tùy chỉnh",
				widthAbbreviation: "độ rộng",
				heightAbbreviation: "độ cao",
				emptyDimension: "Nhập kích thước.",
				seeExample: "Xem trước phần nhúng của bạn",
				removeHeader: "Ẩn tiêu đề ứng dụng"
			},
			maps: {
				unableRetrieveTitle: "Không thể truy xuất bản đồ",
				unableRetrieveDescription: "Chúng tôi không thể truy xuất bản đồ cho story map này."
			},
			images: {
				unableRetrieveTitle: "Không thể truy xuất hình ảnh",
				unableRetrieveDescription: "Chúng tôi không thể truy xuất hình ảnh cho story map này."
			},
			tags: {
				tags: "Từ khóa",
				collectionTags: "Chủ đề",
				selectASubject: "Chọn chủ đề",
				save: "Lưu",
				saved: "Đã lưu",
				errorSaving: "Lỗi trong khi lưu",
				tagTip: "Mẹo: Từ khóa giúp mọi người tìm câu chuyện của bạn. Các từ khóa càng liên quan thì tác phẩm của bạn càng được biết đến."
			},
			submitToGallery: {
				gallerySubmission: "Story Maps Gallery",
				canSubmitIf: "Bạn có thể đề cử câu chuyện của bạn vào thư viện nếu câu chuyện có chứa các điều sau:",
				hasOwnImage: "Hình thu nhỏ tùy chỉnh",
				chosenSubject: "Chủ đề và một số từ khóa",
				chosenSubjectAlt: "{{SUBJECT}} và một số từ khóa",
				storyMapTopicSubject: "chủ đề",
				sharedPublicly: "Được chia sẻ công khai",
				noBrokenContent: "Không có sự cố",
				nominateToGallery: "Đề cử vào Thư viện",
				comingSoon: "Sắp ra mắt!",
				submitted: "Đã gửi",
				errorSubmitting: "Lỗi trong khi gửi",
				ourGallery: "Thư viện Story Maps",
				galleryTip: "{{THE_GALLERY}} là tập hợp Story Maps đã được thu thập để thể hiện một số ví dụ tốt nhất của bạn. Nếu câu chuyện của bạn được chọn, câu chuyện đó sẽ được thêm trong vòng 10 ngày từ khi gửi. Do số lượng đề cử, chúng tôi không thể hứa rằng câu chuyện của bạn sẽ được thêm."
			},
			placeholders: {
				noSummary: "Không có tổng kết, hãy nhấp để thêm."
			},
			errors: {
				cantDeleteStory: "Không thể xóa câu chuyện.",
				unableToFind: "Không thể tìm thấy nội dung",
				unableToRetrieve: "Chúng tôi không thể truy xuất nội dung cho story map này."
			},
			socialSharing: {
				availableWhenPublic: "Tùy chọn này sẽ khả dụng khi câu chuyện của bạn ở chế độ công khai"
			},
			dialog: {
				back: "Quay lại",
				close: "Đóng",
				cancel: "Hủy"
			},
			imagePicker: {
				changeDefault: "Thay đổi hình ảnh mặc định",
				changeImage: "Thay đổi hình thu nhỏ",
				uploadImage: "Tải lên hình thu nhỏ",
				chooseImage: "Chọn hình thu nhỏ",
				chooseAnImage: "Chọn Hình ảnh",
				notInIEVersion: "Tính năng này không khả dụng trong Internet Explorer {{VERSION_NUMBER}}.",
				or: "Hoặc",
				uploadAnImage: "Tải Ảnh lên",
				supportedFileTypes: "Hỗ trợ .png, .jpg, .gif",
				imageSizeMessage: "Hình ảnh của bạn phải rộng ít nhất 286 px và cao ít nhất 190 px.",
				minimumDimensions: "Tối thiểu: 286 x 190px",
				imagesLoading: "Đang tải hình ảnh…",
				noImages: "Câu chuyện này không có ảnh",
				errorLoading: "Không thể truy xuất ảnh trong câu chuyện này",
				clickBelowTip: "Nhấp vào nút bên dưới để tải ảnh lên.",
				dragAndDrop: "Kéo và Thả",
				cropImage: "Xén Ảnh",
				saveImage: "Lưu Ảnh",
				save: "Lưu",
				savingImage: "Đang lưu hình ảnh của bạn...",
				saved: "Đã lưu!",
				errorSaving: "Không thể lưu hình ảnh của bạn.",
				skipAndCrop: "Bỏ qua và Xén cho tôi",
				wrongFormat: "Loại tệp này không được hỗ trợ.",
				noCropWarning: "Không thể xén hình ảnh này nhưng bạn vẫn có thể lưu làm hình thu nhỏ câu chuyện của bạn với kích thước nguyên gốc ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)."
			}
		},
		content: {
			media: {
				maps: "Bản đồ",
				images: "Hình ảnh",
				videos: "Video",
				webpages: "Trang web",
				tags: "Từ khóa",
				gallery: "Bộ sưu tập"
			},
			headers: {
				status: "Trạng thái",
				source: "Nguồn",
				name: "Tên",
				shared: "Đã chia sẻ"
			},
			component: {
				mapTour: "Số Điểm",
				bullet: "Dấu đầu dòng",
				tab: "Tab",
				accordion: "Phần",
				mapJournal: "Phần"
			},
			titleType: {
				mapTour: "Chú thích",
				mapJournal: "URL",
				mapSeries: "URL"
			},
			actions: {
				viewMap: "Xem Bản đồ",
				editMap: "Chỉnh sửa Bản đồ",
				fix: "Sửa",
				viewLayer: "Xem Lớp"
			},
			contentType: {
				mainStage: "hành động trong sân khấu chính",
				sidePanel: "mô tả"
			},
			notification: {
				refreshExplanation: "Kiểm tra lại câu chuyện của bạn",
				checking: "Đang kiểm tra...",
				foundSomeIssues: "Chúng tôi tìm thấy một số sự cố",
				noIssuesFound: "Không tìm thấy sự cố nào",
				storyPublic: "Câu chuyện của bạn hiện đã ở chế độ công khai",
				storyOrg: "Câu chuyện của bạn hiện đã được chia sẻ cho tổ chức của bạn",
				storyPrivate: "Câu chuyện của bạn hiện đã ở chế độ riêng tư",
				mapPublic: "Bản đồ của bạn hiện đã ở chế độ công khai",
				mapOrg: "Bản đồ của bạn hiện đã được chia sẻ cho tổ chức của bạn",
				mapPrivate: "Bản đồ của bạn hiện đã ở chế độ riêng tư",
				layerPublic: "Lớp của bạn hiện đã ở chế độ công khai",
				layerOrg: "Lớp của bạn hiện đã được chia sẻ cho tổ chức của bạn",
				layerPrivate: "Lớp của bạn hiện ở chế độ riêng tư",
				contentPublic: "Nội dung của bạn hiện đã ở chế độ công khai",
				contentOrg: "Nội dung của bạn hiện đã được chia sẻ cho tổ chức của bạn",
				contentPrivate: "Nội dung của bạn hiện đã ở chế độ riêng tư",
				storyAndContentPublic: "Câu chuyện của bạn và nội dung câu chuyện hiện đã ở chế độ công khai",
				storyAndContentOrg: "Câu chuyện của bạn và nội dung câu chuyện hiện đã được chia sẻ cho tổ chức của bạn",
				storyAndContentPrivate: "Câu chuyện của bạn và nội dung câu chuyện hiện đã ở chế độ riêng tư",
				shareBulkPrompt: "Bạn có muốn chia sẽ nội dung câu chuyện của bạn theo đó không?",
				layersPublic: "Một số lớp cũng đã được chia sẻ công khai",
				layersOrg: "Một số lớp cũng đã được chia sẻ với tổ chức của bạn",
				layersPrivate: "Một số lớp cũng đã được đặt ở chế độ riêng tư",
				mapsPublic: "Một số bản đồ cũng đã được chia sẻ công khai",
				mapsOrg: "Một số bản đồ cũng đã được chia sẻ với tổ chức của bạn",
				mapsPrivate: "Một số bản đồ cũng đã được đặt ở chế độ riêng tư",
				layersAndMapsPublic: "Một số bản đồ và lớp cũng đã được chia sẻ công khai",
				layersAndMapsOrg: "Một số bản đồ và lớp cũng đã được chia sẻ với tổ chức của bạn",
				layersAndMapsPrivate: "Một số bản đồ và lớp cũng đã được đặt ở chế độ riêng tư",
				yes: "Có",
				no: "Không",
				premiumPublicSuccess: "Nội dung cao cấp của bạn hiện đã có thể truy cập công khai",
				subscriptionPublicSuccess: "Nội dung gói đăng ký của bạn hiện đã có thể truy cập công khai"
			},
			errors: {
				publicDisabled: "Người quản trị đã vô hiệu hóa tính năng chia sẻ công khai",
				orgDisabled: "Người quản trị đã vô hiệu hóa tính năng chia sẻ đến tổ chức của bạn",
				noMapName: "Không thể Truy xuất Tên Bản đồ",
				notPublic: "KHÔNG CÔNG KHAI",
				inaccessible: "KHÔNG THỂ TRUY CẬP ĐƯỢC",
				deleted: "ĐÃ XÓA",
				cantAccessVideo: "Không thể Truy cập Video",
				noStoriesFound: "Chúng tôi không tìm thấy bất kỳ Story Map vào trong nội dung của bạn.",
				cantShowStories: "Không thể tìm thấy story map của bạn. Vui lòng thử lại sau.",
				consolationSearch: "Chúng tôi không thể tìm thấy bất kỳ câu chuyện nào.",
				notCompatibleWithBrowser : "Câu chuyện Của tôi không được hỗ trợ trong Internet Explorer trước phiên bản {{VERSION_NUMBER}}.",
				pleaseUpdateBrowser: "Vui lòng cập nhật trình duyệt của bạn.",
				searchTip: "Hãy thử và đơn giản hóa một chút.",
				consolationNoStories: "Chào mừng bạn đến với Câu chuyện Của tôi!",
				noStoriesTip: "Để tạo story map đầu tiên của bạn, hãy xem trang Ứng dụng.",
				letsGo: "Hãy bắt đầu",
				cantChangeSharingLevel: "Không thể thay đổi cấp độ chia sẻ",
				cantChangeSharingLevels: "Không thể thay đổi cấp độ chia sẻ",
				errorUpdatingTitle: "Lỗi trong khi cập nhật tiêu đề",
				errorUpdatingSummary: "Lỗi trong khi cập nhật tổng kết",
				noEmptyTitle: "Tiêu đề không được để trống",
				cantUpdatePremiumContent: "Không thể cập nhật nội dung cao cấp",
				cantUpdateSubscriptionContent: "Không thể cập nhật nội dung gói đăng ký",
				createFirstStory: "Tạo Câu chuyện Đầu tiên Của tôi"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Bản đồ đã bị xóa",
				layerHasBeenDeleted: "Lớp đã bị xóa",
				mapIsInaccessible: "Không thể truy cập bản đồ",
				layerIsInaccessible: "Không thể truy cập lớp",
				mapNotYoursNotAccessible: "Bản đồ thuộc sở hữu của người khác và không thể truy cập",
				layerServiceOkItemNot: "Lớp được thêm làm mục bị xóa hoặc không thể truy cập",
				layerNotYoursNotAccessible: "Lớp thuộc sở hữu của người khác và không thể truy cập",
				mapOthersSharedBelowLevel: "Bản đồ không thuộc sở hữu của bạn và không công khai",
				layerOthersSharedBelowLevel: "Lớp không thuộc sở hữu của bạn và không công khai",
				noMapNoDetails: "Không có thông tin chi tiết bản đồ, chúng tôi không thể cho bạn biết bất kỳ điều gì về lớp",
				mapIsPrivate: "Bản đồ ở chế độ riêng tư",
				mapIsOrg: "Bản đồ chỉ được chia sẻ trong tổ chức của bạn",
				layerIsPrivate: "Lớp ở chế độ riêng tư",
				layerIsOrg: "Lớp chỉ được chia sẻ trong tổ chức của bạn",
				imageInaccessible: "Không thể truy cập ảnh này",
				videoInaccessible: "Không thể truy cập video này",
				webpageInaccessible: "Không thể truy cập trang web này",
				layerSecureService: "Lớp là dịch vụ bảo mật",
				mapSecureService: "Bản đồ là dịch vụ bảo mật",
				layerConsumesCredits: "Lớp là nội dung cao cấp và tốn credit",
				layerSubscriptionContent: "Lớp là nội dung gói đăng ký",
				mapConsumesCredits: "Bản đồ là nội dung cao cấp và tốn credit",
				mapSubscriptionContent: "Bản đồ là nội dung gói đăng ký"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Chúng tôi không thể kiểm tra loại lớp này",
				cantScanThisType: "Lớp không thuộc loại lớp mà chúng tôi có thể kiểm tra",
				webpageNotScanned: "Trang web không được kiểm tra để phát hiện sự cố",
				ignoredIssue: "Bạn đã bỏ qua một lỗi trong lớp này. Hãy tải lại trang và kiểm tra lại câu chuyện này để xem xét lỗi đó",
				ignoredIssueBuilder: "Bạn đã bỏ qua một lỗi trong lớp này. Hãy tải lại bộ thiết lập để kiểm tra lại lỗi đó"
			},
			scanningErrors: {
				deletedMap: "Nội dung đã bị xóa",
				inaccessibleMap: "Nội dung bản đồ không thể truy cập",
				notYoursNotAccessible: "Nội dung không thuộc sở hữu của bạn và không công khai",
				serviceOkItemNot: "Lớp làm việc là mục không thể truy cập",
				someContentNotPublic: "Nội dung không được chia sẻ công khai",
				someContentPrivate: "Nội dung riêng tư",
				othersSharedBelowLevel: "Nội dung không thuộc sở hữu của bạn và không công khai",
				premiumContent: "Nội dung cao cấp",
				subscriptionContent: "Nội dung gói đăng ký",
				secureService: "Dịch vụ bảo mật",
				inaccessibleImage: "Ảnh không thể truy cập",
				inaccessibleVideo: "Video không thể truy cập",
				inaccessibleWebpage: "Trang web không thể truy cập"
			},
			scanningErrorTips: {
				deletedMapTip: "Mẹo: Hãy chỉnh sửa bản đồ web của bạn và gỡ bỏ nội dung bị hư, hoặc gỡ bỏ bản đồ web khỏi câu chuyện của bạn.",
				inaccessibleMapTip: "Mẹo: Hãy chỉnh sửa bản đồ web của bạn và gỡ bỏ nội dung bị hư, hoặc gỡ bỏ bản đồ web khỏi câu chuyện của bạn.",
				notYoursNotAccessibleTip: "Mẹo: Hãy chỉnh sửa bản đồ web của bạn và gỡ bỏ lớp, hoặc gỡ bỏ bản đồ web khỏi câu chuyện của bạn.",
				serviceOkItemNotTip: "Lớp được thêm làm mục không thể truy cập hoặc bị xóa. Các lớp vẫn hoạt động nhưng điều này có thể ảnh hưởng bản đồ của bạn (popup, ký hiệu hóa).",
				ignore: "Bỏ qua",
				fix: "Sửa",
				clickToShareOrg: "Nhấp vào nút để chia sẻ tất cả nội dung với tổ chức của bạn, hoặc thay đổi thủ công từng mục bằng cách nhấp vào các nút chia sẻ.",
				clickToSharePublic: "Nhấp vào nút để chia sẻ công khai tất cả nội dung này, hoặc thay đổi thủ công từng mục bằng cách nhấp vào các nút chia sẻ.",
				shareOrg: "Chia sẻ với tổ chức của bạn",
				sharePublicly: "Chia sẻ công khai",
				othersSharedBelowLevelTip: "Mẹo: Một số nội dung trong câu chuyện của bạn thuộc sỏ hữu của {{USER_NAME}}, và những người khác xem câu chuyện của bạn có thể không xem được.",
				secureServiceTip: "Mẹo: Hãy gỡ bỏ dịch vụ bảo mật khỏi câu chuyện của bạnÂ hoặc làm theo quy trình được mô tả {{HERE}}.",
				blogArticle: "ở đây",
				premiumContentTip: "Câu chuyện của bạn có chứa nội dung cao cấp và sẽ tốn {{CREDITS}} khi ở chế độ công khai. Hãy để câu chuyện của bạn ở chế độ công khai và tiếp tục, hoặc gỡ bỏ lớp khỏi câu chuyện của bạn.",
				premiumContentPublicTip: "Câu chuyện của bạn có chứa nội dung cao cấp và sẽ tốn {{CREDITS}} khi cung cấp ở chế độ công khai. Hãy xác nhận để đặt lớp ở chế độ công khai hoặc gỡ bỏ lớp khỏi câu chuyện của bạn.",
				subscriptionContentTip: "Câu chuyện của bạn có chứa nội dung gói đăng ký không khả dụng công khai theo mặc định. Hãy xác nhận rằng bạn muốn đặt các lớp này khả dụng (không tốn credit), hoặc gỡ bỏ lớp khỏi câu chuyện của bạn.",
				credits: "service credit",
				makePublic: "Công khai",
				confirm: "Xác nhận",
				inaccessibleImageTip: "Mẹo: Hãy cung cấp ảnh bị thiếu hoặc gỡ bỏ tham chiếu đến ảnh đó.",
				inaccessibleVideoTip: "Mẹo: Hãy cung cấp video bị thiếu hoặc gỡ bỏ tham chiếu đến video đó.",
				inaccessibleWebpageTip: "Mẹo: Hãy cung cấp trang web bị thiếu hoặc gỡ bỏ tham chiếu đến trang web đó."
			},
			removeLayer: {
				title: "Khắc phục Sự cố Lớp",
				layersWithIssue: "Lớp bị sự cố này: {{NUM_WITH_ISSUE}}",
				issueExplanation: "Lớp {{LAYER_NAME}} được thêm làm mục không thể truy cập hoặc bị xóa. Các lớp vẫn hoạt động nhưng điều này có thể ảnh hưởng bản đồ của bạn (popup, ký hiệu hóa). Chúng tôi không thể xác nhận mục này có quan trọng đối với câu chuyện của bạn hay không.",
				issueSolution: "Để khắc phục sự cố, bạn có thể chỉnh sửa bản đồ của bạn, gỡ bỏ lớp và thêm lại lớp vào bản đồ bằng cách sử dụng URL sau:",
				editMap: "Sửa Bản đồ Của bạn",
				clickBelowWhenDone: "Khi bạn đã chỉnh sửa xong, hãy nhấp vào nút bên dưới:",
				rescanAndClose: "Quét lại và Đóng"
			},
			info: {
				ownedBy: "Mục này thuộc sở hữu của {{USER_NAME}}",
				unknownUser: "người khác",
				untitledSection: "(Mục không có tiêu đề)",
				introRecord: "Giới thiệu"
			},
			layers: {
				layersHeader: "Lớp",
				noLayers: "(Không có Lớp)",
				basemapParens: "(bản đồ nền)"
			},
			images: {
				thumbnails: "Hình thu nhỏ",
				thumbnail: "Hình thu nhỏ",
				thumbnailParens: "(hình thu nhỏ)"
			},
			general: {
				noTitle: "(không có tiêu đề)",
				loading: "Đang tải..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "phần",
				secondTitle: "kiểu",
				secondValueA: "bảng điều khiển bên",
				secondValueB: "bảng điều khiển nổi",
				thirdTitle: "bản đồ"
			},
			mapTour: {
				firstTitle: "các điểm tham quan",
				secondTitle: "kiểu",
				secondValueA: "được tích hợp",
				secondValueB: "ba bảng điều khiển",
				thirdTitle: "bản đồ nền",
				thirdValueLoading: "Đang tải...",
				thirdValueUnknown: "không xác định"
			},
			mapSeries: {
				firstTitleA: "dấu đầu dòng",
				firstTitleB: "phần",
				firstTitleC: "tab",
				secondTitle: "kiểu",
				secondValueA: "được đánh dấu đầu dòng",
				secondValueB: "xếp bên",
				secondValueC: "đã thêm tab",
				thirdTitle: "bản đồ"
			},
			swipeSpyglass: {
				firstTitle: "điểm quan tâm",
				secondTitle: "kiểu",
				secondValueA: "trượt nhanh",
				secondValueB: "kính phóng đại",
				thirdTitle: "bản đồ"
			},
			crowdsource: {
				firstTitle: "đóng góp",
				secondTitle: "kiểu",
				secondValueA: "bảng điều khiển bên",
				secondValueB: "đã xếp chồng",
				thirdTitle: "bản đồ nền",
				thirdValueLoading: "Đang tải...",
				thirdValueUnknown: "không xác định"
			}
		},
		progress: {
			checkingStories: "Đang kiểm tra câu chuyện của bạn để phát hiện sự cố...",
			stop: "Dừng",
			exit: "Thoát",
			dismiss: "Bỏ qua",
			done: "Hoàn tất.",
			noStoriesWithIssuesLower: "Không tìm thấy sự cố nào!",
			storiesErrorFree: "Có vẻ câu chuyện của bạn không có lỗi",
			scanAllError: "Không thể quét -- chúng tôi không thể truy xuất một hoặc nhiều câu chuyện của bạn",
			scanProgress: "{{NUM_SCANNED}} trên {{NUM_TOTAL}}",
			scanStopped: "Câu chuyện đã được quét: {{NUM_SCANNED}}, Câu chuyện có sự cố: {{ISSUE_STORIES}}",
			storiesWithIssues: "Câu chuyện có sự cố: {{NUM_STORIES}}"
		},
		newStories: {
			newStoriesFound: "Có vẻ như bạn đã tạo một câu chuyện mới.",
			includeStories: "Làm mới Câu chuyện",
			notWhileScanning: "Tính năng này sẽ khả dụng khi kiểm tra hoàn thành"
		}
    })
);
