define({
  "tagHeaderText": "Tags",
  "expandGroupDescText": "Weitere Informationen",
  "shrinkGroupDescText": "Weniger",
  "layoutText": "Layout",
  "signInText": "Anmelden",
  "signOutText": "Abmelden",
  "showNullValue": "N/A",
  "detailsDisplayText": "Details",
  "sortByText": "Sortieren nach",
  "sortByViewText": "Aufrufe",
  "sortByDateText": "Datum",
  "sortByNameText": "Name",
  "gridViewTitle": "Tabellenansicht",
  "listViewTitle": "Listenansicht",
  "appHeaderTitle": "Startseite",
  "allText": "ALLE",
  "orgText": "ORG",
  "grpText": "GRP",
  "groupLogoText": "Gruppenlogo",
  "appTypeText": "Typ",
  "appOwnerText": "Besitzer",
  "tryItButtonText": "Ansicht",
  "downloadButtonText": "Herunterladen",
  "appDesText": "Beschreibung",
  "reviewText": "Kommentare",
  "itemDetailsLegendTab": "LEGENDE",
  "itemDetailsInfoTab": "INFO",
  "tagsText": "Tags",
  "sizeText": "Größe",
  "accessConstraintsText": "Zugriffs- und Nutzungsbeschränkungen",
  "numberOfCommentsText": "Kommentare",
  "numberOfRatingsText": "Bewertungen",
  "numberOfViewsText": "Aufrufe",
  "noResultsText": "Keine Ergebnisse gefunden.",
  "backToMapButtonText": "Karte",
  "showMoreResultsGalleryText": "Mehr Ergebnisse anzeigen",
  "clearBtnTitle": "Löschen",
  "addressSearchBtnTitle": "Adressensuche",
  "fullScreenBtnTitle": "Vollbild",
  "noLegendText": "Keine Legende",
  "sizeUnitKB": "KB",
  "sizeUnitMB": "MB",
  "itemUnavailableText": "Element ist auf diesem Gerät nicht verfügbar.",
  "title": {
    "settingsBtnTitle": "Einstellungen",
    "itemSearchBtnTitle": "Elementsuche",
    "infoBtnTitle": "Info",
    "sortByBtnTitle": "Sortieren nach",
    "layoutBtnTitle": "Layout",
    "signInBtnTitle": "Anmelden",
    "signOutBtnTitle": "Abmelden",
    "geolocationBtnTitle": "Geolocation",
    "ascendingSort": "Aufsteigend",
    "descendingSort": "Absteigend",
    "viewBtnTitle": "ä_View__Ü",
    "backButtonTitle": "ä_Back__Ü"
  },
  "errorMessages": {
    "emptyGroup": "Die konfigurierte Gruppe verfügt über keine Daten, um die Abfrage auszuführen.",
    "invalidSearch": "Keine Ergebnisse gefunden.",
    "invalidBasemapQuery": "Grundkartengruppe kann nicht abgerufen werden.",
    "falseConfigParams": "Erforderliche Konfigurationsschlüsselwerte sind NULL oder stimmen nicht genau mit Layer-Attributen überein. Diese Meldung kann mehrmals angezeigt werden.",
    "invalidLocation": "Aktuelle Position nicht gefunden.",
    "invalidProjection": "Aktuelle Position kann nicht auf Karte projiziert werden.",
    "widgetNotLoaded": "Widgets konnten nicht geladen werden.",
    "minfontSizeGreater": "Minimaler Schriftgradwert in Konfigurationseinstellungen ist größer als maximaler Wert.",
    "layerNotFound": "Daten können nicht aus Layer abgerufen werden.",
    "unableToOpenItem": "Element kann nicht geöffnet werden.",
    "wmsSpatialReferenceError": "Raumbezug des WMS-Layers stimmt nicht mit dem Raumbezug der Karte überein.",
    "noPublicItems": "Die konfigurierte Gruppe enthält keine öffentlichen Elemente, oder es wurden noch keine Elemente für diese Gruppe freigegeben.",
    "emptyUsernamePassword": "Geben Sie den Benutzernamen und das Kennwort ein.",
    "noFullScreenSupport": "Vollbildmodus wird von aktuellem Browser nicht unterstützt.",
    "notMemberOfOrg": "Sie sind kein Mitglied der Organisation"
  }
});