define(
({
		viewer: {
			loading: {
				step1: "CARGANDO APLICACIÓN",
				step2: "CARGANDO DATOS",
				step3: "INICIALIZANDO EL RECORRIDO",
				loadBuilder: "CAMBIANDO A MODO DE BUILDER",
				redirectSignIn: "á_REDIRECTING TO SIGN-IN PAGE_Ó",
				redirectSignIn2: "á_(you will be redirected here after sign-in)_Ó",
				fail: "Lo sentimos. Error al cargar Ruta de mapa",
				failButton: "Reintentar"
			},
			errors: {
				boxTitle: "Se ha producido un error",
				portalSelf: "Error muy grave: no se ha podido obtener la configuración del portal",
				invalidConfig: "Error muy grave: configuración no válida",
				invalidConfigOwner: "Error muy grave: configuración no válida (se requiere el propietario autorizado)",
				invalidConfigNoWebmap: "Error muy grave: configuración no válida (el mapa web o el identificador de la aplicación no están especificados en index.html)",
				createMap: "No se puede crear el mapa",
				invalidApp: "Error muy grave: la aplicación no se puede cargar",
				noLayer: "El mapa web no contiene una capa de datos válida para la ruta de mapa.",
				noLayerMobile: "Bienvenido a la aplicación web Ruta de mapa. La aplicación no está configurada. El builder de Ruta de mapa no es compatible con dispositivos móviles.",
				noLayerView: "Bienvenido a la aplicación web Ruta de mapa.<br />La aplicación aún no está configurada.",
				appSave: "Error al guardar la aplicación web",
				mapSave: "Error al guardar el mapa web",
				featureServiceLoad: "Error al cargar el servicio de entidades",
				notAuthorized: "No tienes autorización para acceder a esta aplicación",
				oldBrowserTitle: "Explorador no compatible totalmente",
				noBuilderIE8: "El builder de Ruta de mapa no es compatible con Internet Explorer anterior a la versión 9.",
				ie10Win7Explain: "El builder interactivo de ruta de mapa no es compatible con Internet Explorer 10 en Windows 7 cuando el origen de los datos es un servicio de entidades con adjuntos. Para utilizar el servicio de entidades con adjuntos, tienes que <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forzar manualmente el modo del documento hasta conseguir los estándares de Internet Explorer 9 </a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>cambiar la versión a Internet Explorer 9</a> o actualizar a Windows 8.",
				oldBrowserExplain: "Este navegador no es compatible con la generación de vistas en miniatura automática a partir de las imágenes que subas a tu ruta de mapa. Puedes crear una ruta de mapa con este navegador, pero tendrás que proporcionar una imagen en miniatura diferente para cada una de las imágenes que subas.",
				oldBrowserExplain2: "Para mejorar tu experiencia, <a href='http://browsehappy.com/' target='_blank'>actualiza tu explorador</a> o <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activa Google Chrome Frame para Internet Explorer</a>.",
				oldBrowserExplain3: "El builder de ruta de mapa no funciona con Internet Explorer 10 ni Windows XP.",
				oldBrowserClose: "Cerrar"
			},
			mobileHTML: {
				showIntro: "MOSTRAR TÍTULO",
				hideIntro: "OCULTAR TÍTULO",
				navList: "Lista",
				navMap: "Mapa",
				navInfo: "Multimedia",
				introStartBtn: "Inicio"
			},
			desktopHTML: {
				storymapsText: "Un mapa de historias",
				builderButton: "Cambiar a modo de builder",
				bitlyTooltip: "Consigue un enlace corto a la aplicación",
				bitlyStartIndex: "á_Link to current place_Ó"
			},
			builderHTML: {
				panelHeader: "CONFIGURACIÓN DE LA APLICACIÓN",
				buttonSave: "GUARDAR",
				buttonSettings: "Configuración",
				buttonShare: "á_Share_Ó",
				buttonView: "Modo Vista",
				buttonItem: "Abre el elemento de la aplicación web",
				buttonHelp: "Ayuda",
				buttonOrganize: "Organizar",
				buttonAdd: "Agregar",
				buttonImport: "Importar",
				buttonImportDisabled: "La importación no está disponible al usar un servicio de entidades con adjuntos",
				dataEditionDisabled: "La edición de datos está desactivada en la fuente de datos CSV",
				dataSourceWarning: "La capa de datos de la ruta de mapa ha cambiado. Si el ID de las entidades no es el mismo, debes restablecer el orden y los puntos ocultos mediante <b>Organizar</b>. Si el nombre de los campos cambia, debes restablecer la configuración de los campos en la<b>pestaña de datos de Configuración</b>",
				organizeWarning: "Uno o varios puntos agregados fuera del builder interactivo están ocultos.",
				dataPicError0a: "El recorrido incluye <b>%NB%</b> direcciones URL de imágenes no conformes.",
				dataPicError0b: "Este recorrido puede incluir <b>%NB%</b> direcciones URL de imágenes no conformes.",
				dataPicError1: "La ruta de mapa ahora requiere que las direcciones URL de las imágenes acaben con una de las siguientes extensiones: .jp(e)g, .png, .gif o .bmp.",
				dataPicError2: "Este requisito no afectará a las rutas de mapa existentes que ya estén publicadas. Sin embargo, para utilizar el builder interactivo, debes solucionar en primer lugar el problema con la dirección URL realizando una de las dos siguientes acciones:",
				dataPicError3: "Editar las direcciones URL",
				dataPicError4: "De esta forma, se agregará <i>#isImage</i> al final de las direcciones URL de imágenes que no sean compatibles. La mayoría de los servidores son compatibles con los extremos URL. Sin embargo, una vez que se haya realizado la acción, es necesario desplazarse por los puntos para comprobar que las direcciones URL de las imágenes actualizadas funcionan. Si se cargan todas las imágenes, puedes guardar la ruta de mapa. Si <b>las imágenes están dañadas, no guardes la ruta de mapa</b>. En lugar de eso, vuelve a cargar el builder y realiza la segunda acción.",
				dataPicError5: "Limitar el recorrido a las imágenes",
				dataPicError6: "Con esta opción, se considera que todas las direcciones URL son imágenes, pero no se puede agregar vídeos mediante el builder interactivo. Esta acción es reversible si deseas agregar vídeos en el futuro.",
				dataPicError7: "La ruta de mapa está limitada a imágenes, por lo que no puedes utilizar vídeos. Si deseas eliminar dicha limitación, comprueba si las imágenes siguen cargándose correctamente antes de guardar la ruta de mapa. Podrás restaurar dicha limitación posteriormente, en caso necesario.",
				dataPicError8: "Eliminar la limitación de imágenes",
				dataPicError9: "Si estas direcciones URL llevan a vídeos, puedes ignorar esta advertencia. Si llevan a imágenes, deberás realizar una de las siguientes dos acciones:",
				modalCancel: "Cancelar",
				modalApply: "Aplicar",
				organizeHeader: "Organizar el recorrido",
				organizeGeneralCaption: "Utilizar arrastrar y colocar para ordenar los puntos del recorrido",
				organizeDelete: "Eliminar",
				organizeHide: "Ocultar",
				organizeReset: "Restablecer el orden y los puntos ocultos",
				addMaxPointReached: "Has alcanzado el número máximo de puntos autorizado por los iconos establecidos y no puedes añadir otro punto de recorrido.<br /><br />Recuerda que si eliminas puntos existentes, tendrás que volver a cargar la aplicación.",
				addMaxPointReachedMobile: "Lo sentimos, pero has alcanzado el número máximo de puntos autorizados y no puedes agregar esa imagen.",
				addClose: "Cerrar",
				addHeader: "Añadir un punto de recorrido nuevo",
				addTabPicture: "Multimedia",
				addTabInformation: "Información",
				addTabLocation: "Ubicación",
				addSelectCaption: "Seleccionar o soltar la imagen",
				addNoteVideo: "Consulta la Ayuda para obtener instrucciones sobre el uso de vídeos",		
				addSelectCaptionNoFileReader: "Seleccionar imagen",	
				addChangePhoto: "Cambiar la imagen y la vista en miniatura",
				addPictureResolutionIntro: "La resolución de imagen es superior a la necesaria:",
				addPictureResolutionOldBrowser: "La resolución de la imagen es superior a la necesaria. Para optimizar la experiencia con Ruta de mapa, especifica una resolución inferior a %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Cambiar la resolución de la imagen a %RESOLUTION%",
				addPictureResolutionKeep: "Mantener la solución original de %RESOLUTION%",
				addSelectThumbnail: "Seleccionar miniatura",
				addNoThumbSelected: "No hay una miniatura seleccionada",
				addThumbSelected: "Seleccionado",
				addCameraSettingsHeader: "AJUSTES DE LA CÁMARA",
				addThumbnailHeader: "MINIATURA",
				addLabelPicUrl: "Imagen",
				addLabelThumbUrl: "Miniatura",
				addTextPlaceholderUrl: "Introduce la URL de una imagen",
				addTextPlaceholderUrl2: "á_Enter a Youtube page URL_Ó",
				addTextPlaceholderUrl3: "Introduce la URL de una página de Vimeo",
				addTextPlaceholderUrl4: "Introduce la URL de un vídeo integrado",
				addLabelVideo: "Vídeo",
				addMediaVideoOther: "Otro",
				addMediaVideoHelp: "Comprueba la URL y consigue la vista previa predeterminada",
				addMediaVideoHelpTooltip1: "Comprobación correcta",
				addMediaVideoHelpTooltip2: "Error en la comprobación",
				addMediaVideoHelpTooltip4: "Encuentra la opción que permite integrar el vídeo y copia la URL del vídeo que se muestra en el código",
				addLabelName: "Nombre",
				addLabelDescription: "Leyenda",
				addTextPlaceholder: "Escribir algo",
				addLocatePlaceholder: "Localizar una dirección o un lugar",
				addPinColor: "Color",
				addLatitude: "Latitud",
				addLongitude: "Longitud",
				addLatitudePlaceholder: "por ejemplo, 34.056",
				addLongitudePlaceholder: "por ejemplo, -117.195",
				addUploading: "Cargando punto de recorrido",
				addSave: "Añadir punto de recorrido",
				addMobileUploading: "Cargando imagen",
				addMobileName: "Introduce un nombre",
				addMobileNameMandatory: "Error, introduce un nombre.",
				addMobileError: "Lo sentimos pero se ha producido un error",
				settingsHeader: "Ajustes de la aplicación",
				settingsTabLayout: "Diseño",
				settingsTabColor: "Colores",
				settingsTabLogo: "Encabezado",
				settingsTabFields: "Datos",
				settingsTabExtent: "Extensión",
				settingsTabZoom: "Nivel de zoom",
				settingsLayoutExplain: "Selecciona el diseño de aplicación que desees.",
				settingsLayoutProfessional: "Diseño de tres paneles",
				settingsLayoutModern: "Diseño integrado",
				settingsLayoutSelected: "Diseño seleccionado",
				settingsLayoutSelect: "Selecciona este diseño",
				settingsLayoutNote: "Ten en cuenta que en los puntos que usan vídeos, el letrero siempre se situará debajo del vídeo, incluso si esta opción está desactivada.",
				settingsLayoutLocBtn: "á_Display a locate button on supported browser_Ó",
				settingsLayoutLocBtnHelp: "Esa funcionalidad se admite en la mayoría de los dispositivos móviles y navegadores de escritorio (Internet Explorer 9).",
				settingsColorExplain: "Cambia el aspecto eligiendo un tema predefinido, o crea uno propio.",
				settingsLabelColor: "Colores del encabezado, contenido y pie",
				settingsLogoExplain: "Personaliza el logotipo del encabezado (el valor máximo es 250 x 50px).",
				settingsLogoEsri: "Logotipo de Esri",
				settingsLogoNone: "Sin logotipo",
				settingsLogoCustom: "Logotipo personalizado",
				settingsLogoCustomPlaceholder: "URL de imagen",
				settingsLogoCustomTargetPlaceholder: "Enlace click-through",
				settingsLogoSocialExplain: "Personaliza el enlace superior derecho del encabezado.",
				settingsLogoSocialText: "Texto",
				settingsLogoSocialLink: "Vínculo",
				settingsLogoSocialDisabled: "El administrador ha deshabilitado esta característica",
				settingsDataFieldsExplain: "Selecciona los campos de nombre de foto, leyenda y color.",
				settingsDataFieldsError: "La aplicación no puede determinar los datos de nombre, leyenda o color adecuados. Selecciona los campos que se usarán aquí. Estos ajustes se pueden cambiar más adelante.",
				settingsFieldsLabelName: "Nombre",
				settingsFieldsLabelDescription: "Leyenda",
				settingsFieldsLabelColor: "Color",
				settingsFieldsReset: "Restablece la selección de campos",
				settingsExtentExplain: "Define la extensión inicial de la ruta de mapa mediante el mapa interactivo siguiente.",
				settingsExtentExplainBottom: "La extensión que definas modificará la extensión inicial de tu mapa web. Ten en cuenta que esta extensión no se utiliza si no incluye el primer punto del recorrido. En ese caso, el recorrido se abrirá centrándose en el primer punto.",
				settingsExtentDateLineError: "La extensión no puede atravesar el meridiano de longitud 180º",
				settingsExtentDateLineError2: "Error al calcular la extensión",
				settingsExtentDrawBtn: "Dibuja una nueva extensión",
				settingsExtentModifyBtn: "Edita la extensión",
				settingsExtentApplyBtn: "Vista previa de la ruta de mapa",
				settingsExtentUseMainMap: "Uso de la extensión de la ruta de mapa",
				settingsZoomExplain: "Ajusta el zoom para los puntos de la historia después de la introducción (opcional).",
				settingsLabelZoom: "Escala/Nivel",
				settingsZoomFirstValue: "Ninguno",
				settingsFieldError: "Selecciona un campo de cada lista",
				dataTitle: "á_ArcGIS Online hosting_Ó",
				dataExplain: "á_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._Ó",
				dataNameLbl: "Nombre del servicio",
				dataFolderListLbl: "Carpeta",
				dataFolderListFetching: "Recuperando carpetas ...",
				dataRootFolder: "Raíz",
				dataNameError: "Introduce un nombre para el servicio de entidades",
				dataFolderError: "Selecciona una carpeta válida",
				dataSrcContainsInvalidChar: "El nombre del servicio de entidades contiene uno o varios caracteres no válidos (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "En la organización ya existe un servicio con este nombre. Elige un nombre diferente.",
				dataBtnSave: "Crear el servicio",
				dataFooterProgress: "Creación en curso",
				dataFooterSucceed: "Creación satisfactoria. Cargando",
				dataFooterError: "Error de creación. Inténtalo de nuevo",
				tabError: "Comprueba todas las fichas por si existen errores",
				introRecordBtn: "Introducción",
				introRecordActivate: "Utiliza el punto de partida como introducción (no aparece en la muestra)"
			},
			addPopupJS: {
				uploadingPicture: "Cargando imagen",
				uploadSuccess: "Carga satisfactoria",
				uploadError: "Error al cargar la imagen",
				uploadError2: "Error al agregar la entidad (etiqueta HTML no válida)",
				notJpg: "Elige una foto jpeg para cargarla",
				errorNoPhoto: "Elige una imagen para cargarla",
				errorNoThumbnail: "Elige una miniatura para cargarla",
				errorInvalidPicUrl: "Introduce una imagen válida (empieza por http(s):// y acaba en jpg, png, gif o bmp). Puedes terminar la dirección URL con \'#isImage\' para anular la regla.",
				errorInvalidThumbUrl: "Introduce una vista en miniatura válida (empieza por http(s):// y acaba en jpg, png, gif o bmp).",
				errorInvalidVideoUrl: "Introduce una URL de vídeo válida (que empiece por http(s)://)",
				errorNoName: "Escribe un nombre para este punto de recorrido",
				errorNoDescription: "Escribe una leyenda para este punto de recorrido",
				errorNoLocation: "Establece una ubicación para este punto de recorrido"
			},
			builderJS: {
				noPendingChange: "á_No unsaved change_Ó",
				unSavedChangeSingular: "1 cambio sin guardar",
				unSavedChangePlural: "cambios no guardados",
				shareStatus1: "á_Tour is not saved_Ó",
				shareStatus2: "á_Tour is shared publicly_Ó",
				shareStatus3: "á_Tour is shared within the organization_Ó",
				shareStatus4: "á_Tour is not shared_Ó",
				popoverDiscard: "¿Estás seguro de que deseas descartar los cambios no guardados?",
				yes: "Sí",
				no: "No",
				popoverLoseSave: "Al abrir el visor, perderás los cambios no guardados",
				ok: "Aceptar",
				popoverSaveWhenDone: "No olvides guardar los cambios cuando hayas terminado",
				closeWithPendingChange: "¿Estás seguro de que deseas confirmar la acción? Tus cambios se perderán.",
				gotIt: "Aceptar",
				savingApplication: "Guardando la aplicación",
				saveSuccess: "La aplicación se ha guardado con éxito",
				saveError: "Error al guardar. Inténtalo de nuevo",
				saveError2: "Error al guardar a causa de una etiqueta HTML no válida en un nombre o una descripción",
				saveError3: "á_The title can't be empty_Ó",
				dragColorPicker: "Desplázame<br />o cambia mi color",
				dataWarningExtent: "Tienes datos fuera de la extensión del mapa web. Estos datos no se usarán como puntos de recorrido. Si quieres usarlos, cambia la extensión del mapa.",
				dataWarningVisibi: "Tu capa de Ruta de mapa no está visible en la extensión de mapa web actual. Confirma que tu capa de Ruta de mapa esté visible con un mapa grande %MAPSIZE%.",
				dataWarningEdit: "Editar mapa web",
				dataWarningClose: "Cerrar",
				signIn: "Inicia sesión con una cuenta en",
				signInTwo: "para guardar la aplicación.",
				switchBM: "á_Change Basemap_Ó"
			},
			organizePopupJS: {
				messageStart: "Has elegido eliminar",
				messageSinglePoint: "un punto de recorrido",
				messageMultiPoint: "dos puntos",
				messagePermantRemove: "Esto eliminará permanentemente",
				messageRecord: "el registro",
				messageRecordPlural: "los registros",
				messageConfirm: "de la base de datos. ¿Deseas continuar?",
				labelButtonShow: "Mostrar",
				labelButtonHide: "Ocultar"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Esto eliminará la imagen y la miniatura de forma permanente",
				popoverDeleteWarningThumb: "Esto eliminará la miniatura de forma permanente",
				popoverUploadingPhoto: "Actualizando imagen y miniatura",
				popoverUploadingThumbnail: "Actualizando miniatura",
				popoverUploadSuccessful: "Carga satisfactoria",
				popoverUploadError: "Error de carga. Inténtalo de nuevo",
				changePicAndThumb: "Cambiar imagen",
				changeThumb: "Cambiar miniatura",
				selectPic: "Cambiar medio",
				selectThumb: "Cambiar miniatura",
				uploadPicAndThumb: "Aplicar"
			},
			headerJS:{
				editMe: "¡Modifícame!",
				templateTitle: "Establecer título de plantilla",
				templateSubtitle: "Establecer subtítulo de plantilla"
			},
			crossFaderJS:{
				setPicture: "Establecer título de imagen",
				setCaption: "Establecer leyenda de imagen"
			},
			importPopup: {
				title: "Importar",
				prevBtn: "Atrás",
				nextBtn: "Siguiente"
			},
			importPopupHome: {
				header: "¿Dónde se almacenan las imágenes?"
			},
			onlinePhotoSharingCommon: {
				pictures: "imágenes",
				videos: "vídeos",
				disabled: "El administrador ha deshabilitado esta entidad",
				disabledPortal: "Esta función se encuentra deshabilitada en Portal for ArcGIS.",
				header1: "á_Your pictures must be shared publicly._Ó",
				header2: "á_The import will be limited to the first %NB1% %MEDIA%._Ó",
				emptyDataset: "Error, no se han encontrado imágenes",
				footerImport: "Importar",
				selectAlbum: "Selecciona un álbum público",
				selectAlbum2: "Selecciona un álbum",
				pleaseChoose: "Elige",
				userLookup: "Buscar",
				userLookingup: "Buscando",
				csv: "Referenciado en un CSV",
				advanced: "Opciones avanzadas",
				advancedScratchLbl: "á_Start a new Tour_Ó",
				advancedScratchTip: "á_Create an empty Tour that you will be able populate manually using a wizard._Ó",
				advancedCSVLbl: "á_Import Tour data from a CSV file_Ó",
				advancedCSVTip: "á_Import your Tour content from a CSV file._Ó",
				advancedCommonTip: "á_It requires that your images and videos are already online._Ó",
				select: "Crear una selección",
				locUse: "á_Use pictures geolocation_Ó",
				locExplain: "á_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._Ó",
				locExplain2: "á_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._Ó"
			},
			viewFlickr: {
				title: "á_Flickr import_Ó",
				header: "á_Enter your Flickr user name and select a Photo Set or a Tag to be imported._Ó",
				userInputLbl: "Introduce un nombre de usuario",
				signInMsg2: "Usuario no encontrado",
				selectSet: "Selecciona un conjunto de imágenes",
				selectTag: "o selecciona una etiqueta",
				footerImportTag: "Importar la etiqueta seleccionada",
				footerImportSet: "Importar el conjunto seleccionado"
			},
			viewFacebook: {
				title: "á_Facebook import_Ó",
				header: "á_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._Ó",
				leftHeader: "Usuario de Facebook",
				rightHeader: "Página de Facebook",
				pageExplain: "Una página de Facebook es una marca/producto público o un famoso como <b>esrigis</b>. Puedes obtener el nombre de la página después de la  primera '/' de la URL de la página.",
				pageInputLbl: "Introduce un nombre de página",
				lookupMsgError: "No se encontró la página"
			},
			viewPicasa: {
				title: "á_Picasa/Google+ import_Ó",
				header: "á_Enter your email address or the ID of your Picasa or Google+ account._Ó",
				userInputLbl: "Introduce un correo electrónico o ID",
				signInMsg2: "Cuenta no encontrada",
				howToFind: "á_How to find a Picasa or Google+ account ID_Ó",
				howToFind2: "Copia los dígitos que hay entre la primera y la segunda '/' de cualquier página de Picasa o G+"
			},
			viewCSV: {
				title: "á_CSV import_Ó",
				uploadBtn: "Selecciona o coloca un archivo CSV",
				resultHeaderEmpty: "El archivo CSV está vacío",
				resultHeaderSuccess: "%NB_POINTS% puntos cargados correctamente",
				resultHasBeenLimited: "La importación se ha limitado a los primeros %VAL1% puntos de %VAL2% para respetar el límite de %VAL3% puntos por recorrido",
				browserSupport: "El navegador no es compatible. Si quieres utilizar un archivo CSV tienes que <a href='http://browsehappy.com/' target='_blank'>actualizar el navegador</a> o utilizar el visor de mapas Web de ArcGIS.com (consulta la ayuda).",
				errorLatLng: "No se han encontrado los campos de latitud y longitud. Los valores posibles de latitud son: <i>%LAT%</i>y los de longitud son: <i>%LONG%</i>.",
				errorFieldsExplain: "Se ha producido un error en la carga porque no se han encontrado los siguientes campos obligatorios",
				errorFieldsName: "Los posibles valores de <b>Nombre</b> son: %VAL%",
				errorFieldsDesc: "Los posibles valores de <b>Descripción</b> son: %VAL%",
				errorFieldsUrl: "Los posibles valores de <b>URL de imagen</b> son: %VAL%",
				errorFieldsThumb: "Los posibles valores de <b>URL de vista en miniatura</b> son: %VAL%",
				errorFields2Explain: "Se ha producido un error en la carga porque el archivo CSV no utiliza los mismos atributos que la capa en los siguientes atributos",
				errorFields2Name: "<b>Nombre</b> usa %VAL1% en lugar de %VAL2%",
				errorFields2Desc: "<b>Descripción</b> usa %VAL1% en lugar de %VAL2%",
				errorFields2Url: "<b>URL de imagen</b> usa %VAL1% en lugar de %VAL2%",
				errorFields2Thumb: "<b>URL de vista en miniatura</b> usa %VAL1% en lugar de %VAL2%",
				resultFieldsAll: "Se han importado todos los atributos",
				resultFieldsNotAll: "No se han importado los siguientes atributos porque no existen en la capa del mapa",
				resultFieldsNotAll2: "Se han importado los siguientes atributos",
				footerNextBtnResult: "Importar al mapa Web",
				footerProgress: "Importación en curso",
				footerSucceed: "Importación correcta. Cargando"
			},
			viewYoutube: {
				title: "á_Youtube import_Ó",
				header: "á_Enter a YouTube user name to find publicly shared videos._Ó",
				pageInputLbl: "á_Enter a Youtube user name_Ó",
				lookupMsgError: "Usuario no encontrado",
				howToFind: "á_How to find a Youtube user name_Ó",
				howToFind2: "El nombre de usuario se muestra bajo los vídeos",
				found: "Encontrados",
				noData: "No se han encontrado vídeos públicos"
			},
			viewGeoTag: {
				title: "á_Select and locate your images/videos_Ó",
				header: "Haz clic o puntea en las imágenes que desees importar para buscarlas.",
				headerMore: "á_Why aren't my images/videos geolocated?_Ó",
				headerExplain: "á_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._Ó",
				leftPanelTab1: "Para localizar",
				leftPanelTab2: "Localizado",
				clickOrTap: "Haz clic o puntea el mapa para localizar",
				clearLoc: "á_Clear locations_Ó",
				clickDrop: "No importar",
				footerImport: "Importar",
				footerProgress: "Importación en curso",
				footerSucceed: "Importación correcta. Cargando...",
				loading: "Cargando",
				error: "á_Pictures geolocation import failed, geolocations have been ignored._Ó"
			},
			initPopup: {
				title: "Bienvenido al builder de recorridos de mapa",
				prevBtn: "Atrás",
				nextBtn: "Siguiente"
			},
			initPopupHome: {
				header1: "á_Where are your images or videos?_Ó",
				header2: "á_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._Ó",
				title1: "á_They are already online_Ó",
				title2: "á_I need to upload my images_Ó",
				hostedFSTooltip: "á_Use ArcGIS Online to host your images (doesn't support videos)._Ó",
				hostedFsNA: "á_Only available for ArcGIS for Organizations Publisher and Administrator users_Ó",
				footer1: "Cuando termines, no olvides compartir la ruta de mapa con tu audiencia a través de la página de elementos de la aplicación.",
				footer3: "Descargar la plantilla CSV",
				footer4: "Utilizar\"Guardar como\" si no se descarga",
				footer4bis: "á_Use right click and \"Save as\" if download doesn't start_Ó",
				footer5: "á_Learn more_Ó",
				footerProgress: "Creación en curso",
				footerSucceed: "Se ha creado correctamente. Cargando..."
			},
			helpPopup: {
				title: "Ayuda",
				close: "Cerrar",
				tab1: {
					title: "Introducción",
					div1: "á_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._Ó",
					div2: "á_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_Ó",
					div4: "á_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._Ó",
					div42: "á_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._Ó",
					div5: "á_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._Ó"
				},
				tab2: {
					title: "Datos",
					div1: "El principal aspecto que hay que tener en cuenta al generar una ruta de mapa es decidir dónde se almacenarán las imágenes. Las rutas de mapa pueden utilizar las imágenes almacenadas en los principales servicios de uso compartido de fotos, en cualquier servidor web o como adjuntos para un servicio de entidades.",
					div1a: "Consulta la última sección de esta pestaña para obtener información detallada acerca de los formatos de imágenes y vídeos compatibles.",
					div2: "El builder interactivo te da dos opciones para gestionar las imágenes de la ruta de mapa:",
					div3: "<ul><li>Puedes utilizar <b>fotos que ya estén en línea</b>, como imágenes almacenadas en sitios de uso compartido de fotos, como Flickr, o imágenes almacenadas en tu propio sitio web. Se consultarán estas imágenes en la ruta de mapa mediante las direcciones URL.</li><li>También puedes <b>cargar fotos de su ordenador</b> directamente en la ruta de mapa. Para esta opción de carga, es necesario disponer de una suscripción de ArcGIS Online y de privilegios de publicador o administrador, ya que se crea automáticamente un servicio de entidades alojado para ti donde las fotos se almacenan como adjuntos.</li></ul>",
					div4: "Los principales casos de uso son:",
					div4b: "<b>Las fotos todavía no están alojadas</b> y dispones de una suscripción de ArcGIS Online: el uso de un servicio de entidades alojado es la mejor opción. Al igual que ocurre con los servicios públicos de uso compartido de fotos, las imágenes se optimizarán para que se carguen rápidamente y puedas disponer de acceso a todas las funciones de administración y gestión de datos de la plataforma ArcGIS.",
					div5: "<b>No eres miembro de ninguna organización</b>: en primer lugar, debes cargar las imágenes en un sitio web de uso compartido de fotos o en tu propio sitio web. El builder te ayudará a utilizar estas imágenes, que seguirán alojadas en su ubicación original.",
					div6: "<b>Deseas volver a utilizar un servicio de entidades existente</b> que almacena las imágenes como adjuntos o que hace referencia a imágenes externas: consulta la siguiente sección detallada.",
					div7: "<b>Eres usuario de una versión anterior</b> de la plantilla de ruta de mapa y ya posees un archivo CSV que hace referencia a las imágenes y miniaturas: puedes importarlo y refinar los datos. El builder solo es compatible con los archivos CSV que utilicen campos lat./long.; puedes seguir utilizando los archivos CSV basados en direcciones mediante el mapa web (consulta la siguiente sección).",
					div8: "Importando de los servicios de intercambio de fotos en línea",
					div9: "La operación de importación hace referencia a imágenes que ya se encuentran alojadas mediante el almacenamiento de las direcciones URL en una recopilación de entidades de mapas web. Las imágenes no se almacenan en ArcGIS Online. Si no se puede acceder a las imágenes alojadas, no estarán disponibles en la ruta de mapa y aparecerá la imagen \'Imagen no disponible\'. En función del proveedor de servicios fotográficos, la ruta de mapa podría no importar el nombre, la descripción ni la ubicación de las imágenes. Estos atributos se almacenan en el mapa web y las modificaciones de los servicios en línea no aparecerán reflejadas en la ruta de mapa.",
					div10: "Almacenando las imágenes en un servidor Web",
					div11: "Si decides alojar las imágenes tú mismo, deberás crear manualmente las miniaturas de las imágenes. Al utilizar las imágenes con resolución completa para la miniatura, el rendimiento se vería afectado de forma negativa. Por ese motivo, te recomendamos encarecidamente que utilices servicios de uso compartido de fotos en línea o servicios de entidades que lo hagan por ti.",
					div12: "Uso de un Shapefile o un servicio de entidades existente",
					div13: "Se puede utilizar cualquier Shapefile o servicio de entidades de puntos como fuente de datos de la ruta de mapa. Solo tienes que agregarlo como capa en el mapa web mediante el visor de mapas de arcgis.com. Si la aplicación encuentra los atributos esperados en la capa, todas las funciones del builder estarán disponibles.",
					div14: "á_The possible values for fields name are (case insensitive):_Ó",
					div151: "Nombre",
					div152: "Descripción",
					div153: "Imagen",
					div154: "Miniatura",
					div155: "á_Color_Ó ",
					div16: "á_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._Ó",
					div162: "Al utilizar un servicio de entidades que almacene las imágenes como adjuntos, <b>solamente se utilizarán las entidades con dos adjuntos</b>. El primer adjunto define la imagen principal y el segundo, la vista en miniatura.",
					div17: "Los campos de imágenes y miniaturas son obligatorios para los servicios de entidades sin adjuntos y opcionales (pero muy recomendables) para los servicios de entidades con adjuntos. Si el servicio tiene los adjuntos habilitados, el builder te permitirá cargar imágenes como adjuntos. En caso contrario, solamente podrás editar las direcciones URL de la imagen y la vista en miniatura.",
					div172: "Si están presentes, siempre se utilizarán los campos de imagen y miniatura, y no se consultarán los adjuntos del servicio de entidades.",
					div173: "Puedes descargar archivos Shapefile y CSV de ejemplo en:",
					div18: "Creación de servicios de entidades alojados desde archivos CSV o Shapefile",
					div19: "Al crear un servicio de entidades alojado a partir de un archivo CSV o Shapefile, los adjuntos no se habilitan de forma predeterminada. Para habilitarlos, abre la página de detalles del servicio de entidades, haz clic en la flecha pequeña de la sección de capas y podrás ver dicha opción. La ruta de mapa seguirá utilizando las imágenes y las miniaturas a las que se hace referencia mediante atributos. De forma opcional, si deseas cargar las imágenes como adjuntos de servicios de entidades, podrás hacerlo mediante dos botones en el panel de imágenes (\"Cambiar imagen\" y \"Cambiar vista en miniatura\").",
					div20: "Vídeos y formatos de imagen compatibles",
					div21: "Los formatos de imágenes compatibles son los siguientes: <b>.jpg, .jpeg, .png, .gif y .bmp</b>. Si los medios no acaban con dichas extensiones, la ruta de mapa considerará que es un vídeo, excepto al utilizar un servicio de entidades (consulta a continuación).",
					div22: "La plantilla de ruta de mapa no incluye un reproductor de vídeos, por lo que deberás utilizar el reproductor de vídeos externo ofrecido por tu servicio de alojamiento de vídeos favorito (busca la opción para integrar el vídeo y copia de la dirección URL presente en un código determinado). Si deseas alojar un vídeo tú mismo, puedes crear una página HTML que contenga un reproductor de vídeos como <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "El builder interactivo no ofrece ningún cuadro de diálogo para incluir vídeos al utilizar servicios de entidades con adjuntos, pero es posible hacerlo mediante la edición de datos fuera del builder interactivo. En el visor de mapas de arcgis.com, si modificas los campos de imágenes para que señalen a un vídeo externo y agregas un parámetro especial al final de la dirección URL (#isVideo), se considerará que el medio es un vídeo.",
					div24: "Ten en cuenta que seguirás necesitando dos adjuntos de imágenes válidos o no se utilizará el punto. No se puede utilizar vídeos al emplear adjuntos de servicios de entidades sin los campos de imágenes y vistas en miniatura."
				},
				tab3: {
					title: "Personalización",
					div1: "El builder proporciona varias opciones de personalización a las que se puede acceder a través del botón CONFIGURACIÓN del panel superior. Si no encuentras la opción esperada, también proporcionamos una versión para descarga que puedes desplegar en el servidor Web y mejorarla para adaptarla a tus necesidades.",
					div2: "Se recomienda utilizar la versión alojada, salvo en los siguientes casos:",
					div3: "<li>No ofrece la personalización de la IU deseada, como el uso de una imagen de fondo de encabezado.</li><li>Eres desarrollador y deseas mejorar la aplicación.</li>",
					div4: "Se puede configurar la versión para descarga a través de un mapa web o un identificador de aplicaciones de representación cartográfica. Los principales casos de uso son:",
					div41: "Genera tu ruta de mapa con el builder interactivo en el entorno alojado y configura la plantilla con el identificador de la aplicación de mapas web. Se aplicará la configuración que hayas definido con el builder interactivo.",
					div42: "á_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._Ó",
					div43: "Ten en cuenta que hay una versión descargable disponible del builder interactivo, pero con algunas restricciones técnicas en exploradores como las versiones anteriores a Internet Explorer 10.",
					div5: "á_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._Ó"
				},
				tab4: {
					title: "Consejos",
					div0: "Exploradores compatibles",
					div0a: "El visor de rutas de mapa es compatible con IE8 (y posteriores). El builder interactivo es compatible con IE9 (y posteriores). Lo hemos probado de forma activa en todos los exploradores principales, pero, si experimentas dificultades, te recomendamos que utilices Chrome.",
					div0b: "Si experimentas dificultades, ponte en contacto con nosotros. Mientras tanto, si generas la ruta de mapa con la plantilla CSV, se minimizará la interacción con la interfaz del builder.",
					div1: "Imágenes",
					div2: "á_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._Ó",
					div2a: "á_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._Ó",
					div3: "Establece el formato de texto de tu leyenda usando etiquetas HTML",
					div4: "El encabezado y el título/leyenda de la imagen pueden incluir etiquetas HTML para definir formatos y enlaces. Por ejemplo, este código agrega un enlace amarillo:",
					div4a: "á_Write a good subtitle for your tour_Ó",
					div4b: "á_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._Ó",
					div5: "Capas de apoyo",
					div6: "Puedes agregar capas adicionales para proporcionar un contexto a la ruta de mapa. Estas capas pueden contener otras entidades geográficas que deseas que aparezcan en el mapa además de los puntos de la ruta de mapa, como áreas de estudio, rutas peatonales o de conducción enlazadas con los puntos del recorrido, etc. La plantilla de ruta de mapa muestra estas capas adicionales con la simbología especificada en el mapa web, pero las ventanas emergentes no se encuentran disponibles.",
					div7: "Mantén tu recorrido corto y agradable",
					div8: "Hay un límite de 99 puntos por recorrido. Por supuesto, la mayoría de las rutas de mapa tendrán menos. No esperes a que los demás usuarios deseen pasar por demasiados puntos de recorrido. Aunque el tema te resulte fascinante, puede que a otros usuarios no se lo parezca.",
					div9: "Para obtener más información, consulta <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>la guía detallada</a>.",
					div10: "Modo integrado",
					div11: "Si deseas integrar la plantilla en otro sitio web mediante un iframe, al agregar el parámetro opcional \"&embed\" al final de la dirección URL, se eliminará el encabezado. Dicho modo también se puede establecer en la versión descargable mediante el archivo de configuración.",
					div12: "á_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._Ó" 
				},
				tab5: {
					title: "Publicación",
					div1: "á_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._Ó",
					div2a: "á_Sharing the Tour through the builder_Ó",
					div2b: "á_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._Ó",
					div2c: "á_Sharing the Tour through ArcGIS Online_Ó",
					div2d: "á_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._Ó",
					div3t: "á_Feature Service security_Ó",
					div3a: "á_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._Ó",
					div3t2: "á_Before sharing your Tour with your audience_Ó",
					div3: "á_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._Ó",
					div4: "á_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._Ó",
					div5a: "á_Recommendation for search_Ó",
					div5b: "á_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._Ó"
				}
			},
			share: {
				firstSaveTitle: "á_Tour successfully saved_Ó",
				firstSaveHeader: "á_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._Ó",
				firstSaveA1: "á_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_Ó",
				firstSaveA1bis: "á_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._Ó",
				firstSaveQ2: "á_Is my Tour shared?_Ó",
				firstSaveA2: "á_Currently your Tour is not shared. To share it, use the SHARE button._Ó",
				shareTitle: "á_Share your Tour_Ó",
				sharePrivateHeader: "á_Your Tour is not shared, would you like to share it?_Ó",
				sharePrivateBtn1: "á_Share publicly_Ó",
				sharePrivateBtn2: "á_Share with my Organization_Ó",
				sharePrivateProgress: "á_Sharing in progress..._Ó",
				sharePrivateErr: "á_Sharing failed, try again or_Ó",
				sharePrivateOk: "á_Sharing updated successfully, loading..._Ó",
				sharePreviewAsUser: "á_Preview_Ó",
				shareHeader1: "á_Your Tour is <strong>publicly accessible</strong>._Ó",
				shareHeader2: "á_Your Tour is accessible by your organization members (login is required)._Ó",
				shareLinkHeader: "á_Share the Tour with your audience_Ó",
				shareLinkOpen: "á_OPEN_Ó",
				shareQ1Opt1: "á_How do I keep the Tour private?_Ó",
				shareQ1Opt2: "á_How do I keep the Tour private or share it publicly?_Ó",
				shareA1: "á_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._Ó",
				shareA1bis: "á_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._Ó",
				shareQ2: "á_How do I edit the Tour later?_Ó",
				shareQ2bis: "á_How do I get back to the authoring interface?_Ó",
				shareA2div1: "á_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._Ó",
				shareA2div2: "á_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_Ó",				
				shareQ3: "á_Where is the data stored?_Ó",
				shareA3: "á_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._Ó"
			}
        }
    })
);
