define({
  "header": {
    "start": "başlangıç",
    "searchStories": "Hikayelerinizi arayın...",
    "filter": "Filtrele",
    "sort": "Sırala",
    "sortColon": "Sırala:",
    "numResults": "Sonuç sayısı: {{NUM_RESULTS}}",
    "sortBy": "Şuna göre sırala:",
    "dateModified": "Değiştirme tarihi:",
    "title": "Başlık",
    "type": "Tür",
    "views": "Görünümler",
    "errors": "Hatalar",
    "filterBy": "Filtreleme ölçütü",
    "filterItems": "Öğeleri Filtrele",
    "apps": "Uygulamalar",
    "sharing": "Paylaş",
    "clearAll": "Tümünü sil",
    "clearSearch": "Aramayı temizler",
    "logOut": "Oturumu Kapat",
    "mainQuote": "Hikaye anlatımı, günümüzde fikirleri dünyaya sunmanın en güçlü yoludur.",
    "quoteSource": "Robert McKee",
    "checkYourStories": "Hikayeleri İşaretle",
    "createStory": "Hikaye Oluştur",
    "totalStories": "Toplam hikaye oluştur: {{NUM_STORIES}}",
    "noIssues": "Tümü iyi",
    "userStories": "{{USER_NAME}} kullanıcısının hikayeleri",
    "headerDisabledTooltip": "Uygun işlemler yapılırken bekleyin...",
    "notOnTouch": "Dokunmatik cihazlarda kullanılamaz"
  },
  "deleteModal": {
    "title": "Silmeyi Onayla",
    "warningText": "Bu Â hikayesini silmek istediğinizden emin misiniz? İşlemi geri alamazsınız.",
    "deleteText": "Sil",
    "cancel": "İptal"
  },
  "loading": {
    "loadingText": "Hikayeleriniz yükleniyor..."
  },
  "cantFindStories": {
    "whereAreStories": "Hikayenizi göremiyor musunuz?",
    "notSeeExplanation": "Hikayelerim yalnızca ArcGIS içinde barındırılan hikaye haritalarında listelenir ({{STORY_MAP_BASIC}} şu anda desteklenmemektedir). Daha fazla bilgi için {{FAQ}} bölümümüzü inceleyin.",
    "faq": "SSS",
    "followingStoriesToUpdate": "Uygulamalarımızın önceki sürümleri ile oluşturulan aşağıdaki hikayelerin, Hikayelerim içinde listelenebilmesi için güncelleştirilmesi gerekir:",
    "gettingStories": "Uygulamalarımızın önceki sürümleri ile oluşturulan ve güncellenmesi gereken hikayeler aranıyor...",
    "title": "Başlık",
    "typeOfStoryMap": "Tür",
    "lastModified": "Son değiştirilme tarihi",
    "allUpToDate": "Uygulamalarımızın önceki sürümleri ile oluşturulan hikayelerin hiçbirinin güncellenmesi gerekli değil.",
    "updateAll": "Tümünü Güncelle",
    "errorScanningForStories": "Hikayeleriniz aranırken bir hata oluştu.",
    "close": "Kapat",
    "updates": "Güncellemeler",
    "updatingNumberOfNumber": "Güncelleniyor: {{CURRENT_NUMBER}} / {{TOTAL}}",
    "updatingNumberOfNumberAlt": "Güncelleniyor: {{CURRENT_NUMBER}} / {{TOTAL}}",
    "updateSucceeded": "Güncelleme başarılı!",
    "reloadingStories": "Hikayeleriniz yeniden yükleniyor...",
    "errorUpdatingStories": "Hikayeleriniz güncellenirken bir hata oluştu.",
    "partialUpdateMessage": "Başarıyla güncellenen hikaye sayısı: {{NUM_UPDATED}}"
  },
  "signIn": {
    "signInTitle": "Story Maps oturumu açın",
    "signInTo": "Mevcut ArcGIS Online hesabınızla şurada oturum açın:",
    "explanationOne": "Hikayelerinizi anlatmak için çekici hikaye haritaları oluşturun.",
    "explanationTwo": "Hikaye haritalarınızda ArcGIS Online haritalarınızı ve verilerinizi kullanın.",
    "explanationThree": "Hikaye haritalarınızı yönetin ve içeriğinizin durumunu denetleyin.",
    "dontHaveAccount": "ArcGIS Online hesabınız yok mu? Aşağıdakiler için kayıt yaptırın:",
    "publicAccount": "Ticari olmayan ücretsiz genel hesap",
    "orgAccount": "Ücretsiz ArcGIS deneme sürümü",
    "timeExpired": "Oturumunuzun süresi doldu. Kaldığınız yerden devam etmek için yeniden oturum açın.",
    "apiDidntLoad": "Düzgün yüklenmeyen şeyler var. Sayfayı yenilemeyi deneyin.",
    "needAccount": "Hesap mı gerekiyor?",
    "letsGo": "İşte gerekenler!"
  },
  "sharingLevel": {
    "publicMessage": "Genel",
    "privateMessage": "Gizli",
    "organization": "Kuruluş",
    "changedSharing": "Paylaşım düzeyi değiştirildi",
    "unableToChange": "Paylaşım değiştirilemiyor.",
    "partOfMap": "Bu öğe bir haritada bulunuyor. Öğenin paylaşım düzeyini değiştirmek için haritanın paylaşım düzeyini değiştirmelisiniz.",
    "storyPublicContentOrg": "Hikayeniz genel özelliktedir, bu nedenle içeriği kuruluşunuza özel olamaz",
    "storyPublicContentPrivate": "Hikayeniz genel özelliktedir, bu nedenle içeriği özel olamaz",
    "mapOrg": "Haritanızın kuruluşunuzla paylaşılması hikayenizi kesintiye uğratabilir",
    "layerOrg": "Katmanınızın kuruluşunuzla paylaşılması hikayenizi kesintiye uğratabilir",
    "mapPrivate": "Haritanızın özel yapılması hikayenizi kesintiye uğratabilir",
    "layerPrivate": "Katmanınızın özel yapılması hikayenizi kesintiye uğratabilir"
  },
  "collectionList": {
    "business": "İş ve Ekonomi",
    "history": "Tarih ve Kültür",
    "inNews": "Haberlerde Öne Çıkanlar",
    "infrastructure": "Altyapı ve İnşaat",
    "nature": "Doğa ve Koruma",
    "people": "İnsanlar ve Toplum",
    "planning": "Planlama ve Tasarım",
    "science": "Bilim ve Teknoloji",
    "sports": "Spor ve Eğlence",
    "travel": "Seyahat ve Tatil"
  },
  "types": {
    "custom": "Özel",
    "notSpecified": "Tür belirtilmedi"
  },
  "storyMap": {
    "shared": "Paylaşılan",
    "saveFailed": "Kaydetme hatası",
    "numViews": "Görüntüleme sayısı: {{NUM_VIEWS}}",
    "editStory": "Hikayeyi Düzenle",
    "viewLive": "Hikayeyi Görüntüle",
    "preview": "Önizleme",
    "deleteButton": "Sil",
    "modified": "Değiştirilme tarihi: {{DATE}}",
    "summary": "Özet",
    "loading": "Yükleniyor...",
    "collapse": "daralt",
    "close": "kapat",
    "hide": "gizle",
    "notAvailableWhenBroken": "Hikayenizde aşağıdaki sorunlar belirlendi:",
    "cantBeDeleted": "Bu hikayede silme koruması etkinleştirilmiş. Devre dışı bırakmak için ArcGIS Online'daki ilgili öğe sayfasını inceleyin.",
    "shareDialog": {
      "title": "Hikayenizi dünyayla paylaşın!",
      "notPublicWarning": "Hikayeniz kuruluşunuzla paylaşılmıştır. Yalnızca kuruluşunuzun üyeleri bunu görüntüleyebilir.",
      "embedStory": "Hikayenizi yerleştirin",
      "shortLink": "Kısa Bağlantı",
      "hideHeaderBar": "Başlık çubuğunu gizle",
      "copied": "Kopyalandı",
      "small": "küçük",
      "medium": "orta",
      "large": "büyük",
      "custom": "özel",
      "widthAbbreviation": "g",
      "heightAbbreviation": "y",
      "emptyDimension": "Boyut girin.",
      "seeExample": "Gömülü öğenizi önizleyin",
      "removeHeader": "Uygulama başlığını gizle"
    },
    "maps": {
      "unableRetrieveTitle": "Haritalar alınamıyor",
      "unableRetrieveDescription": "Bu hikaye haritası için harita alınamadı."
    },
    "images": {
      "unableRetrieveTitle": "Görüntü alınamadı",
      "unableRetrieveDescription": "Bu hikaye haritası için görüntü alınamadı."
    },
    "tags": {
      "tags": "Etiketler",
      "collectionTags": "Konu",
      "selectASubject": "Konu seç",
      "save": "Kaydet",
      "saved": "Kaydedildi",
      "errorSaving": "Kaydetme hatası",
      "tagTip": "İpucu: Etiketler, başkalarının hikayenizi bulmasına yardım eder. Etiketler ne kadar ilgili olursa, çalışmanız o kadar fazla görüntülenir."
    },
    "submitToGallery": {
      "gallerySubmission": "Story Maps Galerisi",
      "canSubmitIf": "Aşağıdakileri içerdiği takdirde hikayenizi galeriye aday gösterebilirsiniz:",
      "hasOwnImage": "Özel küçük resim",
      "chosenSubject": "Konu ve bazı etiketler",
      "chosenSubjectAlt": "{{SUBJECT}} ve bazı etiketler",
      "storyMapTopicSubject": "konu",
      "sharedPublicly": "Genel olarak paylaşıldı",
      "noBrokenContent": "Sorun bulunmadı",
      "nominateToGallery": "Galeriye Aday Göster",
      "comingSoon": "Yakında karşınızda!",
      "submitted": "Gönderildi",
      "errorSubmitting": "Gönderme hatası",
      "ourGallery": "Story Maps galerisi",
      "galleryTip": "{{THE_GALLERY}}, en iyi örneklerden bazılarını sergileyen özel oluşturulmuş bir Story Maps grubudur. Hikayeniz seçilirse, gönderildikten sonraki 10 gün içinde galeriye eklenir. Aday sayısının çok fazla olması nedeniyle hikayenizin ekleneceği garantisini veremiyoruz."
    },
    "placeholders": {
      "noSummary": "Özet yok, eklemek için tıklayın."
    },
    "errors": {
      "cantDeleteStory": "Hikaye silinemiyor.",
      "unableToFind": "İçerik bulunamıyor.",
      "unableToRetrieve": "Bu hikaye haritası için içerik alınamadı."
    },
    "socialSharing": {
      "availableWhenPublic": "Hikayeniz genel yapıldığında bu seçenek kullanılabilir duruma gelir."
    },
    "dialog": {
      "back": "Geri",
      "close": "Kapat",
      "cancel": "İptal"
    },
    "imagePicker": {
      "changeDefault": "Varsayılan görüntüyü değiştir",
      "changeImage": "Küçük resmi değiştir",
      "uploadImage": "Küçük resmi yükle",
      "chooseImage": "Küçük resim seç",
      "chooseAnImage": "Görüntü Seç",
      "notInIEVersion": "Bu detay Internet Explorer {{VERSION_NUMBER}} sürümünde yok.",
      "or": "Veya",
      "uploadAnImage": "Görüntü Yükle",
      "supportedFileTypes": ".png, .jpg, .gif dosyalarını destekler",
      "imageSizeMessage": "Görüntünüzün en az 286 px genişliğinde ve 190 px yüksekliğinde olması gerekir.",
      "minimumDimensions": "Minimum: 286 x 190px",
      "imagesLoading": "Görüntüler yükleniyor…",
      "noImages": "Bu hikayede görüntü yok",
      "errorLoading": "Bu hikayedeki görüntüler alınamıyor",
      "clickBelowTip": "Görüntü yüklemek için aşağıdaki düğmeye tıklayın.",
      "dragAndDrop": "Sürükle ve Bırak",
      "cropImage": "Görüntüyü Kırp",
      "saveImage": "Görüntüyü Kaydet",
      "save": "Kaydet",
      "savingImage": "Görüntünüz kaydediliyor...",
      "saved": "Kaydedildi!",
      "errorSaving": "Görüntünüz kaydedilemiyor.",
      "skipAndCrop": "Atla ve benim için Kırp",
      "wrongFormat": "Bu dosya türü desteklenmiyor.",
      "noCropWarning": "Bu görüntü kırpılamıyor, ancak yine de orijinal boyutlarıyla ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px) hikaye küçük resminiz olarak kaydedebilirsiniz."
    }
  },
  "content": {
    "media": {
      "maps": "Haritalar",
      "scenes": "Sahneler",
      "images": "Görüntüler",
      "videos": "Videolar",
      "webpages": "Web sayfaları",
      "tags": "Etiketler",
      "gallery": "Galeri"
    },
    "headers": {
      "status": "Durum",
      "source": "Kaynak",
      "name": "Adı",
      "shared": "Paylaşılan"
    },
    "component": {
      "mapTour": "Nokta Sayısı",
      "bullet": "Madde İşareti",
      "tab": "Sekme",
      "accordion": "Bölüm",
      "mapJournal": "Bölüm",
      "cascade": "Bölüm",
      "crowdsource": "Katkı",
      "shortlist": "Sekme"
    },
    "titleType": {
      "mapTour": "Yakalama:",
      "mapJournal": "URL",
      "mapSeries": "URL",
      "cascade": "URL",
      "crowdsource": "URL",
      "shortlist": "URL"
    },
    "actions": {
      "viewMap": "Haritayı Görüntüle",
      "editMap": "Harita Düzenle",
      "editScene": "Görünümü Düzenle",
      "fix": "Düzelt",
      "viewLayer": "Katmanı Görüntüle"
    },
    "contentType": {
      "mainStage": "ana aşama eylemi",
      "sidePanel": "açıklama",
      "introImage": "(kapak sayfası fotoğrafı)"
    },
    "notification": {
      "refreshExplanation": "Hikayenizi yeniden denetleyin",
      "checking": "Denetleniyor...",
      "foundSomeIssues": "Bazı sorunlar bulundu",
      "noIssuesFound": "Sorun bulunmadı",
      "storyPublic": "Hikayeniz artık genel",
      "storyOrg": "Hikayeniz artık kendi kuruluşunuzla paylaşılıyor",
      "storyPrivate": "Hikayeniz artık özel",
      "mapPublic": "Haritanız artık genel",
      "mapOrg": "Haritanız artık kendi kuruluşunuzla paylaşılıyor",
      "mapPrivate": "Haritanız artık özel",
      "layerPublic": "Katmanınız artık genel",
      "layerOrg": "Katmanınız artık kendi kuruluşunuzla paylaşılıyor",
      "layerPrivate": "Katmanınız artık özel",
      "contentPublic": "İçeriğiniz artık genel",
      "contentOrg": "İçeriğiniz artık kendi kuruluşunuzla paylaşılıyor",
      "contentPrivate": "İçeriğiniz artık özel",
      "storyAndContentPublic": "Hikayeniz ve içeriği artık genel",
      "storyAndContentOrg": "Hikayeniz ve içeriği artık kuruluşunuzla paylaşılıyor",
      "storyAndContentPrivate": "Hikayeniz ve içeriği artık özel",
      "shareBulkPrompt": "Hikayenizin içeriğini buna uygun olarak paylaşmak istiyor musunuz?",
      "layersPublic": "Bazı katmanlar da genel olarak paylaşıldı",
      "layersOrg": "Bazı katmanlar da kuruluşunuzla paylaşıldı",
      "layersPrivate": "Bazı katmanlar da özel yapıldı",
      "mapsPublic": "Bazı haritalar da genel olarak paylaşıldı",
      "mapsOrg": "Bazı haritalar da kuruluşunuzla paylaşıldı",
      "mapsPrivate": "Bazı haritalar da özel yapıldı",
      "layersAndMapsPublic": "Bazı haritalar ve katmanlar da genel olarak paylaşıldı",
      "layersAndMapsOrg": "Bazı haritalar ve katmanlar da kuruluşunuzla paylaşıldı",
      "layersAndMapsPrivate": "Bazı haritalar ve katmanlar da özel yapıldı",
      "yes": "Evet",
      "no": "Hayır",
      "premiumPublicSuccess": "Ayrıcalıklı içeriğiniz artık genel olarak erişilebilir",
      "subscriptionPublicSuccess": "Abonelik içeriğiniz artık genel olarak erişilebilir"
    },
    "errors": {
      "publicDisabled": "Genel paylaşım bir Yönetici tarafından devre dışı bırakıldı",
      "orgDisabled": "Kuruluşunuzla paylaşma bir Yönetici tarafından devre dışı bırakıldı",
      "noMapName": "Harita Adı Alınamadı",
      "noSceneName": "Görünüm Alınamadı",
      "notPublic": "GENEL DEĞİL",
      "inaccessible": "ERİŞİLEMEZ",
      "deleted": "SİLİNDİ",
      "cantAccessVideo": "Videoya Erişilemedi",
      "noStoriesFound": "İçeriğinizde Story Maps bulunamadı.",
      "cantShowStories": "Hikaye haritalarınız gösterilemiyor. Daha sonra yeniden deneyin.",
      "consolationSearch": "Hikaye bulunamadı.",
      "notCompatibleWithBrowser": "Hikayelerim {{VERSION_NUMBER}} öncesindeki Internet Explorer sürümlerinde desteklenmiyor.",
      "pleaseUpdateBrowser": "Tarayıcınızı güncelleyin.",
      "searchTip": "Deneyin ve biraz basitleştirin.",
      "consolationNoStories": "Hikayelerim'e Hoş Geldiniz!",
      "noStoriesTip": "İlk hikaye haritanızı oluşturmak için Uygulamalar sayfasını inceleyin.",
      "letsGo": "İşe Koyulun",
      "cantChangeSharingLevel": "Paylaşım düzeyi değiştirilemiyor",
      "cantChangeSharingLevels": "Paylaşım düzeyleri değiştirilemiyor",
      "errorUpdatingTitle": "Başlık güncelleme hatası",
      "errorUpdatingSummary": "Özet güncelleme hatası",
      "noEmptyTitle": "Başlık boş olamaz",
      "cantUpdatePremiumContent": "Ayrıcalıklı içerik güncellenemiyor",
      "cantUpdateSubscriptionContent": "Abonelik içeriği güncellenemiyor",
      "createFirstStory": "İlk Hikayemi Oluştur"
    },
    "tooltipErrors": {
      "mapHasBeenDeleted": "Harita silindi",
      "layerHasBeenDeleted": "Katman silindi",
      "mapIsInaccessible": "Haritaya erişilemiyor",
      "layerIsInaccessible": "Katmana erişilemiyor",
      "mapNotYoursNotAccessible": "Haritanın sahibi başka bir kişi ve haritaya erişilemiyor",
      "layerServiceOkItemNot": "Katman, silinen veya erişilemeyen bir öğe olarak eklendi",
      "layerNotYoursNotAccessible": "Katmanın sahibi başka bir kişi ve katmana erişilemiyor",
      "mapOthersSharedBelowLevel": "Haritanın sahibi siz değilsiniz ve harita genel değil",
      "layerOthersSharedBelowLevel": "Katmanın sahibi siz değilsiniz ve katman genel değil",
      "noMapNoDetails": "Harita detayları olmadan katmanlar hakkında bir şey söylenemez",
      "mapIsPrivate": "Harita özel",
      "mapIsOrg": "Harita yalnızca kendi kuruluşunuzda paylaşılıyor",
      "layerIsPrivate": "Katman özel",
      "layerIsOrg": "Katman yalnızca kendi kuruluşunuzda paylaşılıyor",
      "imageInaccessible": "Bu görüntüye erişilemiyor",
      "videoInaccessible": "Bu videoya erişilemiyor",
      "webpageInaccessible": "Bu web sayfasına erişilemiyor",
      "layerSecureService": "Katman güvenli hizmettir",
      "mapSecureService": "Harita güvenli hizmettir",
      "layerConsumesCredits": "Katman ayrıcalıklı içeriğe sahiptir ve kredi gerektirir",
      "layerSubscriptionContent": "Katman abonelik içeriğinden oluşur",
      "mapConsumesCredits": "Harita ayrıcalıklı içeriğe sahiptir ve kredi gerektirir",
      "mapSubscriptionContent": "Harita abonelik içeriğinden oluşur"
    },
    "tooltipWarnings": {
      "cantScanThisTypeAlt": "Bu katman türü denetlenemiyor",
      "cantScanThisType": "Katman denetleyebildiğimiz bir katman türü değil",
      "webpageNotScanned": "Web sayfaları sorunlar açısından denetlenmez",
      "sceneNotScanned": "Görünümlerde şu an için sorun denetimi yapılamıyor, görünümün ve tüm katmanlarının düzgün biçimde paylaşıldığından emin olun",
      "scenesNotScannedGlobally": "Bunlar hikayede bulunan ve henüz sorunlar açısından denetlenmemiş olan görünümlerdir. Görünümlerin ve tüm katmanlarının düzgün biçimde paylaşıldığından emin olun",
      "ignoredIssue": "Bu katmandaki bir hatayı yok saydınız. Sayfayı yeniden yükleyin ve hatayı incelemek için bu hikayeyi yeniden denetleyin",
      "ignoredIssueBuilder": "Bu katmandaki bir hatayı yok saydınız. Oluşturucuyu yeniden yükleyin ve bu hatayı yeniden inceleyin"
    },
    "scanningErrors": {
      "deletedMap": "Silinmiş içerik",
      "inaccessibleMap": "Erişilemeyen harita içeriği",
      "notYoursNotAccessible": "İçeriğin sahibi siz değilsiniz ve içerik genel değil",
      "serviceOkItemNot": "Çalışan katmanlar ancak erişilemeyen öğeler",
      "someContentNotPublic": "İçerik genel olarak paylaşılmamış",
      "someContentPrivate": "Özel içerik",
      "othersSharedBelowLevel": "İçeriğin sahibi siz değilsiniz ve içerik genel değil",
      "premiumContent": "Ayrıcalıklı içerik",
      "subscriptionContent": "Abonelik içeriği",
      "secureService": "Güvenli hizmetler",
      "inaccessibleImage": "Erişilemeyen görüntüler",
      "inaccessibleVideo": "Erişilemeyen videolar",
      "inaccessibleWebpage": "Erişilemeyen web sayfaları"
    },
    "scanningErrorTips": {
      "deletedMapTip": "İpucu: Web haritanızı düzenleyin ve bozuk içeriği kaldırın veya web haritasını hikayenizden kaldırın.",
      "inaccessibleMapTip": "İpucu: Web haritanızı düzenleyin ve bozuk içeriği kaldırın veya web haritasını hikayenizden kaldırın.",
      "notYoursNotAccessibleTip": "İpucu: Web haritanızı düzenleyin ve katmanı çıkarın veya web haritasını hikayenizden kaldırın.",
      "serviceOkItemNotTip": "Katmanlar erişilemeyen veya silinmiş öğeler olarak eklendi. Katmanlar çalışıyor, ancak bu haritanızı (açılan pencereler, semboller) etkileyebilir.",
      "ignore": "Yoksay",
      "fix": "Düzelt",
      "clickToShareOrg": "Tüm içeriği kuruluşunuzla paylaşmak için düğmeye tıklayın veya her öğeyi paylaşma düğmelerine tıklayarak manuel olarak değiştirin.",
      "clickToSharePublic": "Tüm içeriği genel olarak paylaşmak için düğmeye tıklayın veya her öğeyi paylaşma düğmelerine tıklayarak manuel olarak değiştirin.",
      "shareOrg": "Kuruluşunuzla paylaşın",
      "sharePublicly": "Herkesle paylaş",
      "othersSharedBelowLevelTip": "İpucu: Hikayenizdeki bazı içeriklerin sahibi {{USER_NAME}}; hikayenizi görüntüleyen başkaları bunu göremeyebilir.",
      "secureServiceTip": "İpucu: Hikayenizden güvenli hizmeti kaldırın veya {{HERE}} açıklanan işlemi uygulayın.",
      "blogArticle": "buraya",
      "premiumContentTip": "Genel yaptıktan sonra hikayenizde {{CREDITS}} kullanılmasını gerektiren ayrıcalıklı içerik var. Hikayenizi genel yapın ve devam edin ya da hikayenizden katmanları kaldırın.",
      "premiumContentPublicTip": "Genel olarak erişilebilir olduğunda hikayenizde {{CREDITS}} kullanılmasını gerektiren ayrıcalıklı içerik var. Bu katmanların genel yapılmasını onaylayın veya hikayenizden katmanları kaldırın.",
      "subscriptionContentTip": "Hikayenizde varsayılan olarak genel olmayan abonelik içeriği var. Bu katmanları kullanılabilir yapmak istediğinizi onaylayın (kredi kullanılmaz) veya hikayenizden katmanları kaldırın.",
      "credits": "krediler",
      "makePublic": "Genel yap",
      "confirm": "Onayla",
      "inaccessibleImageTip": "İpucu: Eksik görüntüyü sağlayın veya ona başvuran öğeyi kaldırın.",
      "inaccessibleVideoTip": "İpucu: Eksik videoyu sağlayın veya ona başvuran öğeyi kaldırın.",
      "inaccessibleWebpageTip": "İpucu: Eksik web sayfasını sağlayın veya ona başvuran öğeyi kaldırın."
    },
    "removeLayer": {
      "title": "Katman Sorununu Düzelt",
      "layersWithIssue": "Bu soruna sahip katmanlar: {{NUM_WITH_ISSUE}}",
      "issueExplanation": "{{LAYER_NAME}} katmanı erişilemeyen bir öğe olarak eklenmiş veya silinmiş. Katman çalışıyor, ancak bu haritanızı (açılır pencereler, semboller) etkileyebilir. Öğenin hikayeniz açısından önemli olup olmadığı belirlenemiyor.",
      "issueSolution": "Sorunu düzeltmek için haritanızı düzenleyebilir, katmanı kaldırabilir ve aşağıdaki URL'yi kullanarak katmanı yeniden haritaya ekleyebilirsiniz:",
      "editMap": "Haritayı Düzenle",
      "clickBelowWhenDone": "Düzenlemeyi tamamladığınızda aşağıdaki düğmeye tıklayın:",
      "rescanAndClose": "Yeniden Tara ve Kapat"
    },
    "info": {
      "ownedBy": "Bu öğenin sahibi: {{USER_NAME}}",
      "unknownUser": "başka bir kişi",
      "untitledSection": "(Başlıksız bölüm)",
      "introRecord": "Giriş"
    },
    "layers": {
      "layersHeader": "Katmanlar",
      "noLayers": "(Katman Yok)",
      "basemapParens": "(altlık harita)"
    },
    "images": {
      "thumbnails": "Küçük Görünüm",
      "thumbnail": "Küçük Resim",
      "thumbnailParens": "(küçük resim)"
    },
    "general": {
      "noTitle": "(başlık yok)",
      "loading": "Yükleniyor..."
    }
  },
  "infographics": {
    "mapJournal": {
      "firstTitle": "bölümler",
      "secondTitle": "stil",
      "secondValueA": "yan pano",
      "secondValueB": "kayar pano",
      "thirdTitle": "haritalar"
    },
    "mapTour": {
      "firstTitle": "tur noktaları",
      "secondTitle": "stil",
      "secondValueA": "bütünleşik",
      "secondValueB": "üç panelli",
      "thirdTitle": "altlık harita",
      "thirdValueLoading": "Yükleniyor...",
      "thirdValueUnknown": "bilinmeyen"
    },
    "mapSeries": {
      "firstTitleA": "madde işaretleri",
      "firstTitleB": "bölümler",
      "firstTitleC": "sekmeler",
      "secondTitle": "stil",
      "secondValueA": "madde işaretli",
      "secondValueB": "yana doğru genişleyen",
      "secondValueC": "sekmeli",
      "thirdTitle": "haritalar"
    },
    "cascade": {
      "firstTitle": "bölümler",
      "secondTitle": "haritalar"
    },
    "swipeSpyglass": {
      "firstTitle": "gezilecek yerler",
      "secondTitle": "stil",
      "secondValueA": "kaydır",
      "secondValueB": "dürbün",
      "thirdTitle": "haritalar"
    },
    "crowdsource": {
      "firstTitle": "katkıda bulunanlar",
      "secondTitle": "altlık harita",
      "secondValueLoading": "Yükleniyor...",
      "secondValueUnknown": "bilinmeyen"
    },
    "shortlist": {
      "firstTitle": "yerler",
      "secondTitle": "sekmeler",
      "thirdTitle": "altlık harita",
      "thirdValueLoading": "Yükleniyor...",
      "thirdValueUnknown": "bilinmeyen"
    }
  },
  "progress": {
    "checkingStories": "Hikayelerinizdeki sorunlar denetleniyor...",
    "stop": "Durdur",
    "exit": "Çıkış",
    "dismiss": "Vazgeç",
    "done": "Tamamlandı.",
    "noStoriesWithIssuesLower": "Sorun bulunmadı!",
    "storiesErrorFree": "Hikayelerinizde hata yok gibi görünüyor",
    "scanAllError": "Taranamıyor -- bir ya da birkaç hikayeniz alınamadı",
    "scanProgress": "{{NUM_SCANNED}} / {{NUM_TOTAL}}",
    "scanStopped": "Taranan hikaye sayısı: {{NUM_SCANNED}}, Sorun olan hikaye sayısı: {{ISSUE_STORIES}}",
    "storiesWithIssues": "Sorun olan hikaye sayısı: {{NUM_STORIES}}"
  },
  "newStories": {
    "newStoriesFound": "Yeni bir hikaye oluşturduğunuz görülüyor.",
    "includeStories": "Hikayeleri Yenile",
    "notWhileScanning": "Kontrol tamamlandıktan sonra bu özellik kullanılabilecek."
  }
});