define({
    root: ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Zum Builder wechseln",
                "exitBuilderButtonText": "Builder beenden",
                "enterBuilderModeHelpText": "Zum Konfigurieren der Anwendung zum Builder-Modus wechseln",
                "builderModeHelpText": "Builder-Modus für Vorlagen",
                "webmapCaption": "Karte",
                "selectMapMessage": "Aktuell wird <b>${webmapTitle}</b> ${displaying} <br/>Klicken Sie auf \"Karte auswählen\", um eine andere Webkarte auszuwählen",
                "loadMapMessage": "Aktuell ist <b>${webmapTitle}</b> ausgewählt<br/>Klicken Sie auf \"Speichern unter\", um diese Webkarte zu speichern",
                "changeWebmap": "Karte auswählen",
                "saveButtonText": "Speichern",
                "webmapNextButtonText": "Weiter ->",
                "previousButtonText":"Zurück",
                "layerLabelText": "Layer",
                "noLayerFoundText": "Kein Layer gefunden",
                "selectLayer": "Layer auswählen",
                "applicationSettingText": "Anwendungseinstellungen",
                "summaryAttrAscendingOrderTooltip": "Aufsteigend",
                "onStartLabel": "Beim Start",
                "selectVariableText": "Variable auswählen",
                "selectVariableDropdown": "Variable auswählen",
                "label":"Beschriftung",
                "sourceLinkText":"Quellen-Link",
                "selectSubVariableText":"Subvariablen auswählen",
                "subVariablePanelButtonText":"FERTIG",
                "onButtonLabel":"Ein",
                "offButtonLabel":"Aus",
                "appSettingsSaveCloseButtonText": "SPEICHERN UND SCHLIESSEN",
                "appSettingsTitleText":"App-Titel",
                "appSettingsDescriptionText": "Anwendungsbeschreibung",
                "appSetingsRendererAreaText":"Gerenderter Bereich",
                "shareText":"Freigeben",
                "popupText": "Pop-up",
                "basemapText":"Grundkarte",
                "cancel": "Abbrechen",
                "theme": "Design",
                "zoomLevel": "Zoomfaktor",
                "existingValue": "Vorhandene Werte verwenden",
                "enrichLayer": "Layer anreichern",
                "imageLabel": "Wie funktioniert es?",
                "clearData": "Daten löschen",
                "basemapSelectionText":"Grundkartenauswahl",
                "secondaryBasemapText":"Sekundäre Grundkarte",
                "defaultBasemapText": "Standardgrundkarte",
                "entireAreaButton": "Gesamtfläche",
                "entireAreaOnStartButton": "Gesamtes Gebiet beim Start",
                "aboutPanel": "Bereich \"Info\"",
                "legendPanel": "Bereich \"Legende\"",
                "layersPanel": "Bereich \"Layer\"",
                "dataConfigurationButtonText": "Datenkonfiguration",
                "savingChangesMessage": "Änderungen werden gespeichert...",
                "nextButtonText": "Weiter",
                "prevButtonText": "Zurück",
                "enterLabelText": "Beschriftung eingeben",
                "SelectedFeatureText": "Ausgewähltes Feature",
                "layerHelpTextMessage": "Für diese Anwendung ist ein Layer mit numerischen Feldern erforderlich",
                "alertMessage": {
                    "resetVariableMessage": "Möchten Sie diese Variable wirklich zurücksetzen?",
                    "emptyAppTitleMessage": "Anwendungstitel darf nicht leer sein",
                    "emptyDescriptionMessage": "Beschreibung darf nicht leer sein",
                    "maxVariableSelection": "Sie können nicht mehr als 25 Subvariablen auswählen",
                    "signInFail" : "Anmeldung fehlgeschlagen",
                    "itemUpdateMessage": "Element wurde aktualisiert",
                    "unsavedChangesMessage": "Nicht gespeicherte Änderungen",
                    "failMessage": "Element konnte nicht erfolgreich gespeichert werden",
                    "saveChangesAlert": "Möchten Sie die Änderungen speichern?",
                    "variableLabelValidation": "Variablenbeschriftung darf nicht leer sein",
                    "subVariableLabelValidation": "Subvariablenbeschriftung darf nicht leer sein"
                    }
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});