define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "æ_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Â",
            selectFieldsText:"æ_Select Form Fields_Â",
            selectThemeText: "Sélectionner le thème du formulaire",
            fieldLabelPlaceHolder: "Etiqueter ce champ",
            fieldDescPlaceHolder: "Décrire ce champ",
            webmapText: "æ_1. Webmap_Â",
            layerText: "æ_2. Layer_Â",
            detailsText: "æ_3. Details_Â",
            fieldsText: "æ_4. Fields_Â",
            styleText: "æ_5. Style_Â",
            previewText: "æ_6. Preview_Â",
            publishText: "æ_7. Publish_Â",
            titleText: "Générateur de formulaires géographiques",
            descriptionText: "æ_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._Â",
            btnPreviousText: "Précédent",
            btnNextText:"Suivant",
            webmapTabTitleText: "Choisir une carte Web",
            btnSelectWebmapText:"Sélectionner une carte Web",
            layerTabTitleText: "Sélectionner une couche modifiable",
            selectLayerLabelText:"Couche",
            selectLayerDefaultOptionText:"Sélectionner une couche",
            detailsTabTitleText:"Détails du formulaire",
            detailTitleLabelText: "Titre",
            detailLogoLabelText: "Image du logo",
            detailDescriptionLabelText: "Description",
            fieldTabFieldHeaderText: "Champ",
            fieldTabLabelHeaderText: "Etiquette",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Description",
            previewApplicationText: "Aperçu de l\'application",
            saveApplicationText: "Enregistrer l\'application",
            saveText: "Enregistrer",
            toggleNavigationText: "æ_Toggle navigation_Â",
            formPlaceholderText: "æ_My Form_Â",
            imageLogoPlaceholderText: "æ_http://www.mysite.com/myimage.png_Â",
            shareBuilderInProgressTitleMessage: "æ_Publishing GeoForm_Â",
            shareBuilderProgressBarMessage:"æ_Please Wait..._Â",
            shareBuilderTitleMessage: "æ_Your GeoForm has been updated & published!_Â",
            shareBuilderTextMessage: "æ_You can start collecting information by sharing with others_Â",
            shareDialogFormText: "æ_Form Link_Â",
            geoformTitleText: "æ_Geo Form_Â",
            layerTabText: "æ_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Â",
            detailsTabText:"æ_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._Â",
            fieldsTabText:"æ_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Â",
            styleTabText: "æ_Style your GeoForm using the themes below based on your preference._Â",
            publishTabText: "æ_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Â"
        }
    })
);