define(
     ({
        map: {
            error: "Impossible de créer la carte"
        },
        onlineStatus: {
            offline: "Vous travaillez actuellement en mode hors connexion. Les envois de formulaires seront enregistrés localement jusqu\'à l\'établissement d\'une connexion au serveur.",
            reconnecting: "Reconnexion&hellip;",
            pending: "${total} modifications en attente seront envoyées lorsqu\'une connexion réseau sera rétablie."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Mon organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mon contenu",
                    favoritesLabel: "Mes favoris"
                },
                title: "Sélectionner une carte Web",
                searchTitle: "Rechercher",
                ok: "OK",
                cancel: "Annuler",
                placeholder: "Saisir un terme de recherche"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Mon organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mon contenu",
                    favoritesLabel: "Mes favoris"
                },
                title: "Sélectionner un groupe",
                searchTitle: "Rechercher",
                ok: "OK",
                cancel: "Annuler",
                placeholder: "Saisir un terme de recherche"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Ordonnée",
            utm_easting: "Abscisse",
            utm_zone_number: "Numéro de fuseau",
            geoFormGeneralTabText: "1. Entrez des informations",
            locationInformationText: "2. Sélectionnez un emplacement",
            submitInformationText: "3. Remplissez le formulaire",
            submitInstructions: "Ajoutez ces informations à la carte.",
            myLocationText: "æ_Current Location_Â",
            locationDescription: "æ_Specify the location for this entry by clicking/tapping the map or by using one of the following options._Â",
            addressText: "Rechercher",
            geographic: "æ_Lat/Lon_Â",
            locationTabText: "Emplacement",
            locationPopupTitle: "æ_Location_Â",
            submitButtonText: "æ_Submit Entry_Â",
            submitButtonTextLoading: "Envoi&hellip;",
            formValidationMessageAlertText: "Les champs suivants sont requis :",
            selectLocation: "Sélectionnez un ${openLink}emplacement${closeLink} pour votre envoi.",
            emptylatitudeAlertMessage: "Entrez une coordonnée de ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Entrez une coordonnée de ${openLink}longitude${closeLink}.",
            shareUserTitleMessage: "Merci de votre contribution !",
            entrySubmitted: "æ_Your entry has been submitted to the map._Â",
            shareThisForm: "æ_Share This Form_Â",
            shareUserTextMessage: "æ_Tell others to contribute using the following options._Â",
            addAttachmentFailedMessage: "Impossible d\'ajouter une pièce jointe à la couche",
            addFeatureFailedMessage: "Impossible d\'ajouter une entité à la couche",
            noLayerConfiguredMessage: "Aucun élément à visualiser. Afin de commencer à collecter les envois de formulaires, configurez ce formulaire géographique et sélectionnez une couche de service d\'entités modifiable à utiliser.",
            placeholderLatitude: "Latitude (Y)",
            placeholderLongitude: "Longitude (X)",
            latitude: "Latitude",
            longitude: "Longitude",
            findMyLocation: "æ_Locate Me_Â",
            finding: "Localisation&hellip;",
            backToTop: "Retour en haut",
            addressSearchText: "Votre envoi apparaîtra ici. Vous pouvez faire glisser l\'épingle pour corriger l\'emplacement.",
            shareModalFormText: "Lien du formulaire",
            close: "Fermer",
            locationNotFound: "L\'emplacement est introuvable.",
            setLocation: "æ_Set Location_Â",
            find: "æ_Find address or place_Â",
            attachment: "Pièce jointe",
            toggleDropdown: "Activer/Désactiver le menu déroulant",
            invalidLatLong: "Entrez des coordonnées de ${latLink}latitude${closeLink} et de ${lngLink}longitude${closeLink} valides.",
            invalidUTM: "Entrez des coordonnées ${openLink}UTM${closeLink} valides.",
            invalidUSNG: "Entrez des coordonnées ${openLink}USNG${closeLink} valides.",
            invalidMGRS: "Entrez des coordonnées ${openLink}MGRS${closeLink} valides.",
            geoformTitleText: "Formulaire géographique",
            domainDefaultText: "Sélectionner&hellip;",
            applyEditsFailedMessage: "Votre entrée ne peut pas être envoyée. Réessayez.",
            requiredFields: "Des erreurs se sont produites. Corrigez-les ci-dessous.",
            requiredField: "æ_(required)_Â",
            error: "Erreur",
            textRangeHintMessage: "æ_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_Â",
            dateRangeHintMessage: "æ_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_Â"
        },
        builder: {
            invalidUser: "æ_Sorry, you dont have permission to view this item_Â",
            invalidWebmapSelectionAlert: "æ_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Â",
            invalidWebmapSelectionAlert2: "æ_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_Â",
            selectFieldsText: "æ_Select Form Fields_Â",
            selectThemeText: "æ_Select Form Theme_Â",
            webmapText: "æ_Webmap_Â",
            layerText: "æ_Layer_Â",
            detailsText: "æ_Details_Â",
            fieldsText: "æ_Fields_Â",
            styleText: "æ_Style_Â",
            optionText: "æ_Options_Â",
            previewText: "æ_Preview_Â",
            publishText: "æ_Publish_Â",
            optionsApplicationText: "æ_Options_Â",
            titleText: "æ_Builder_Â",
            descriptionText: "æ_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._Â",
            btnPreviousText: "æ_Previous_Â",
            btnNextText: "æ_Next_Â",
            webmapTabTitleText: "æ_Select a Webmap_Â",
            viewWebmap: "æ_View webmap_Â",
            btnSelectWebmapText: "æ_Choose Webmap_Â",
            btnSelectWebmapTextLoading: "æ_Loading&hellip;_Â",
            layerTabTitleText: "æ_Select Editable Layer_Â",
            selectLayerLabelText: "æ_Layer_Â",
            selectLayerDefaultOptionText: "æ_Select Layer_Â",
            detailsTabTitleText: "æ_Form Details_Â",
            detailTitleLabelText: "æ_Title_Â",
            detailLogoLabelText: "æ_Logo Image_Â",
            descriptionLabelText: "æ_Help Text (optional)_Â",
            fieldTabFieldHeaderText: "æ_Field_Â",
            fieldTabLabelHeaderText: "æ_Label_Â",
            fieldTabDisplayTypeHeaderText: "æ_Display As_Â",
            selectMenuOption: "æ_Select Menu_Â",
            selectRadioOption: "æ_Radio Button_Â",
            selectTextOption: "æ_Text_Â",
            selectCheckboxOption: "æ_Checkbox_Â",
            selectMailOption: "æ_Email_Â",
            selectUrlOption: "æ_URL_Â",
            selectTextAreaOption: "æ_Textarea_Â",
            previewApplicationText: "æ_Preview Application_Â",
            saveApplicationText: "æ_Save Application_Â",
            saveText: "æ_Save_Â",
            toggleNavigationText: "æ_Toggle navigation_Â",
            formPlaceholderText: "æ_My Form_Â",
            shareBuilderInProgressTitleMessage: "æ_Publishing GeoForm_Â",
            shareBuilderProgressBarMessage: "æ_Please Wait&hellip;_Â",
            shareBuilderTitleMessage: "æ_Success! Item saved_Â",
            shareBuilderTextMessage: "æ_You can start collecting information by sharing with others_Â",
            shareModalFormText: "æ_Form Link_Â",
            shareBuilderSuccess: "æ_Your GeoForm has been updated & published!_Â",
            geoformTitleText: "æ_Geo Form_Â",
            layerTabText: "æ_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Â",
            detailsTabText: "æ_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._Â",
            fieldsTabText: "æ_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Â",
            styleTabText: "æ_Style your GeoForm using the themes below based on your preference._Â",
            publishTabText: "æ_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Â",
            smallHeader: "æ_Use Small Header_Â",
            pushpinText: "æ_Push pin_Â",
            doneButtonText: "æ_View Application Item_Â",
            fieldTabPlaceHolderHeaderText: "æ_Hint (optional)_Â",
            attachmentLabelText: "æ_Attchment Label_Â",
            attachmentLabelHint: "æ_Tell users what type of file to attach._Â",
            attachmentDescription: "æ_Attachment Description_Â",
            attachmentHint: "æ_If necessary, you can provide additional attachment instructions here._Â",
            jumbotronDescription: "æ_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._Â",
            shareGeoformText: "æ_Share Geoform_Â",
            shareDescription: "æ_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._Â",
            defaultMapExtent: "æ_Default Map Extent_Â",
            defaultMapExtentDescription: "æ_The map will reset to the default extent in your web map after submission - this can be disabled at any time._Â",
            pushpinOptionsDescription: "æ_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_Â",
            selectLocationText: "æ_Select Location By_Â",
            myLocationText: "æ_My Location_Â",
            searchText: "æ_Search_Â",
            coordinatesText: "æ_Latitude & Longitude Coordinates_Â",
            usng: "æ_USNG Coordinates_Â",
            mgrs: "æ_MGRS Coordinates_Â",
            utm: "æ_UTM Coordinates_Â",
            selectLocationSDescription: "æ_Allow users to select a location using these methods._Â"
        }
    })
);