define({
  "tagHeaderText": "Tag",
  "expandGroupDescText": "Altro",
  "shrinkGroupDescText": "Meno",
  "layoutText": "Layout",
  "signInText": "Accedi",
  "signOutText": "Disconnetti",
  "showNullValue": "N/D",
  "detailsDisplayText": "Dettagli",
  "sortByText": "Ordina per",
  "sortByViewText": "Viste",
  "sortByDateText": "Data",
  "sortByNameText": "Nome",
  "gridViewTitle": "Vista griglia",
  "listViewTitle": "Vista elenco",
  "appHeaderTitle": "Home",
  "allText": "TUTTO",
  "orgText": "ORG",
  "grpText": "GRUPPO",
  "groupLogoText": "Logo gruppo",
  "appTypeText": "Tipo",
  "appOwnerText": "Proprietario",
  "tryItButtonText": "Visualizza",
  "downloadButtonText": "Download",
  "appDesText": "Descrizione",
  "reviewText": "Commenti",
  "itemDetailsLegendTab": "LEGENDA",
  "itemDetailsInfoTab": "INFO",
  "tagsText": "Tag",
  "sizeText": "Dimensione",
  "accessConstraintsText": "Vincoli di accesso e uso",
  "numberOfCommentsText": "Commenti",
  "numberOfRatingsText": "Valutazioni",
  "numberOfViewsText": "Viste",
  "noResultsText": "Nessun risultato trovato.",
  "backToMapButtonText": "Mappa",
  "showMoreResultsGalleryText": "Mostra altri risultati",
  "clearBtnTitle": "Cancella",
  "addressSearchBtnTitle": "Ricerca indirizzi",
  "fullScreenBtnTitle": "Schermo intero",
  "noLegendText": "Nessuna legenda",
  "sizeUnitKB": "KB",
  "sizeUnitMB": "MB",
  "itemUnavailableText": "Elemento non disponibile nel dispositivo.",
  "title": {
    "settingsBtnTitle": "Impostazioni",
    "itemSearchBtnTitle": "Ricerca elementi",
    "infoBtnTitle": "Informazioni",
    "sortByBtnTitle": "Ordina per",
    "layoutBtnTitle": "Layout",
    "signInBtnTitle": "Accedi",
    "signOutBtnTitle": "Disconnetti",
    "geolocationBtnTitle": "Geoposizione",
    "ascendingSort": "Ascendente",
    "descendingSort": "Decrescente",
    "viewBtnTitle": "é_View__È",
    "backButtonTitle": "é_Back__È"
  },
  "errorMessages": {
    "emptyGroup": "Per il gruppo configurato non sono disponibili dati per eseguire interrogazioni.",
    "invalidSearch": "Nessun risultato trovato.",
    "invalidBasemapQuery": "Impossibile ottenere il gruppo delle mappe di base.",
    "falseConfigParams": "I valori obbligatori della chiave di configurazione sono Null o non perfettamente corrispondenti agli attributi del layer. È possibile che questo messaggio venga visualizzato più volte.",
    "invalidLocation": "Posizione corrente non trovata.",
    "invalidProjection": "Impossibile proiettare la posizione corrente nella mappa.",
    "widgetNotLoaded": "Impossibile caricare i widget.",
    "minfontSizeGreater": "Il valore minimo del tipo di carattere nelle impostazioni di configurazione è maggiore di quello massimo.",
    "layerNotFound": "Impossibile ottenere dati dai layer.",
    "unableToOpenItem": "Impossibile aprire l'elemento.",
    "wmsSpatialReferenceError": "Il riferimento spaziale del layer WMS non corrisponde a quello della mappa.",
    "noPublicItems": "Non sono disponibili elementi pubblici nel gruppo configurato oppure non sono stati ancora condivisi elementi con il gruppo.",
    "emptyUsernamePassword": "Immettere nome utente e password.",
    "noFullScreenSupport": "Il browser in uso non supporta la modalità a schermo intero.",
    "notMemberOfOrg": "L'utente non appartiene a questa organizzazione"
  }
});