define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "ビルダの開始",
                "exitBuilderButtonText": "ビルダの終了",
                "enterBuilderModeHelpText": "ビルダ モードに入りアプリケーションを構成",
                "builderModeHelpText": "テンプレート ビルダ モード",
                "webmapCaption": "マップ",
                "selectMapMessage": "現在 <b>${webmapTitle}</b> を ${displaying} しています。<br/>[マップの選択] をクリックして、別の Web マップを選択します。",
                "loadMapMessage": "現在 <b>${webmapTitle}</b> を選択しています。<br/>この Web マップを使用するには、[保存] をクリックします。",
                "changeWebmap": "マップの選択",
                "saveButtonText": "保存",
                "webmapNextButtonText": "次へ ->",
                "previousButtonText":"前へ",
                "layerLabelText": "レイヤ",
                "noLayerFoundText": "レイヤが見つかりません",
                "selectLayer": "レイヤの選択",
                "applicationSettingText": "アプリケーション設定",
                "summaryAttrAscendingOrderTooltip": "昇順",
                "onStartLabel": "須_On Start_鷗",
                "selectVariableText": "変数の選択",
                "selectVariableDropdown": "変数の選択",
                "label":"ラベル",
                "sourceLinkText":"ソース リンク",
                "selectSubVariableText":"サブ変数の選択",
                "subVariablePanelButtonText":"完了",
                "onButtonLabel":"オン",
                "offButtonLabel":"オフ",
                "appSettingsSaveCloseButtonText": "保存して閉じる",
                "appSettingsTitleText":"アプリケーション タイトル",
                "appSettingsDescriptionText": "アプリケーションの説明",
                "appSetingsRendererAreaText":"レンダリングされるエリア",
                "shareText":"共有",
                "basemapText":"ベースマップ",
                "basemapSelectionText":"ベースマップ選択",
                "secondaryBasemapText":"第 2 ベースマップ",
                "defaultBasemapText": "デフォルト ベースマップ",
                "entireAreaButton": "須_Entire Area_鷗",
                "entireAreaOnStartButton": "須_Entire Area on start_鷗",
                "aboutPanel": "須_About Panel_鷗",
                "legendPanel": "須_Legend Panel_鷗",
                "layersPanel": "須_Layers Panel_鷗",
                "dataConfigurationButtonText": "データ構成",
                "savingChangesMessage": "変更を保存しています...",
                "nextButtonText": "次へ",
                "prevButtonText": "前へ",
                "enterLabelText": "ラベルの入力",
                "layerHelpTextMessage": "このアプリケーションには数値フィールドを持つレイヤが必要です",
                "alertMessage": {
                    "resetVariableMessage": "変数をリセットしますか？",
                    "emptyAppTitleMessage": "アプリケーション タイトルは空にできません",
                    "emptyDescriptionMessage": "説明は空にできません",
                    "maxVariableSelection": "25 を超えるサブ変数は選択できません",
                    "signInFail" : "サインインできませんでした",
                    "itemUpdateMessage": "更新されたアイテム",
                    "unsavedChangesMessage": "保存されていない変更",
                    "failMessage": "アイテムを正常に更新できませんでした",
                    "saveChangesAlert": "変更内容を保存しますか？",
                    "variableLabelValidation": "変数のラベルは空にできません",
                    "subVariableLabelValidation": "サブ変数のラベルは空にできません"
                    }
            }
        }
    })
});