define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ก้_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ษฺ",
            selectFieldsText:"ก้_Select Form Fields_ษฺ",
            selectThemeText: "ก้_Select Form Theme_ษฺ",
            fieldLabelPlaceHolder: "ก้_Label this field_ษฺ",
            fieldDescPlaceHolder: "ก้_Describe this field_ษฺ",
            webmapText: "ก้_1. Webmap_ษฺ",
            layerText: "ก้_2. Layer_ษฺ",
            detailsText: "ก้_3. Details_ษฺ",
            fieldsText: "ก้_4. Fields_ษฺ",
            styleText: "ก้_5. Style_ษฺ",
            previewText: "ก้_6. Preview_ษฺ",
            publishText: "ก้_7. Publish_ษฺ",
            titleText: "ก้_GeoForm Builder_ษฺ",
            descriptionText: "ก้_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._ษฺ",
            btnPreviousText: "ก้_Previous_ษฺ",
            btnNextText:"ก้_Next_ษฺ",
            webmapTabTitleText: "ก้_Choose a Webmap_ษฺ",
            btnSelectWebmapText:"ก้_Select Webmap_ษฺ",
            layerTabTitleText: "ก้_Select Editable Layer_ษฺ",
            selectLayerLabelText:"ชั้นข้อมูล",
            selectLayerDefaultOptionText:"เลือกชั้นข้อมูล",
            detailsTabTitleText:"ก้_Form Details_ษฺ",
            detailTitleLabelText: "ก้_Title_ษฺ",
            detailLogoLabelText: "ก้_Logo Image_ษฺ",
            detailDescriptionLabelText: "ก้_Description_ษฺ",
            fieldTabFieldHeaderText: "ก้_Field_ษฺ",
            fieldTabLabelHeaderText: "ตัวอักษร",
            fieldTabTypeHeaderText: "ก้_Type_ษฺ",
            fieldTabDescriptionHeaderText: "ก้_Description_ษฺ",
            previewApplicationText: "ก้_Preview Application_ษฺ",
            saveApplicationText: "ก้_Save Application_ษฺ",
            saveText: "ก้_Save_ษฺ",
            toggleNavigationText: "ก้_Toggle navigation_ษฺ",
            formPlaceholderText: "ก้_My Form_ษฺ",
            imageLogoPlaceholderText: "ก้_http://www.mysite.com/myimage.png_ษฺ",
            shareBuilderInProgressTitleMessage: "ก้_Publishing GeoForm_ษฺ",
            shareBuilderProgressBarMessage:"ก้_Please Wait..._ษฺ",
            shareBuilderTitleMessage: "ก้_Your GeoForm has been updated & published!_ษฺ",
            shareBuilderTextMessage: "ก้_You can start collecting information by sharing with others_ษฺ",
            shareDialogFormText: "ก้_Form Link_ษฺ",
            geoformTitleText: "ก้_Geo Form_ษฺ",
            layerTabText: "ก้_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ษฺ",
            detailsTabText:"ก้_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._ษฺ",
            fieldsTabText:"ก้_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ษฺ",
            styleTabText: "ก้_Style your GeoForm using the themes below based on your preference._ษฺ",
            publishTabText: "ก้_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ษฺ"
        }
    })
);