define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "เว็บแมพที่เลือกไว้ไม่มีชั้นข้อมูลที่สามารถนำไปใช้งานได้ โปรดเพิ่มชั้นข้อมูลฟีเจอร์ที่สามารถแก้ไขได้ไปยังเว็บแมพของคุณ เพื่อดำเนินการต่อ",
            selectFieldsText:"เลือกแบบฟอร์มของฟิลด์",
            selectThemeText: "เลือกรูปแบบฟอร์ม",
            fieldLabelPlaceHolder: "ทำป้ายที่ฟิลด์นี้",
            fieldDescPlaceHolder: "อธิบายฟิลด์นี้",
            webmapText: "1. เว็บแมพ",
            layerText: "2. ชั้นข้อมูล",
            detailsText: "3. รายละเอียด",
            fieldsText: "4. ฟิลด์",
            styleText: "5. สไตล์",
            previewText: "6. ดูตัวอย่าง",
            publishText: "7. เผยแพร่",
            titleText: "ตัวสร้าง GeoForm",
            descriptionText: "GeoForm เป็นเทมเพลตที่สามารถปรับแต่งได้สำหรับการแก้ไขแบบฟอร์มข้อมูลฐานของ <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>ฟีเจอร์เซอร์วิส</a> โดยแอพพลิเคชั่นนี้จะอนุญาตให้ผู้ใช้งานสามารถใส่ข้อมูลผ่านทางแบบฟอร์มแทนการใส่ลงบนแผนที่ได้â€™s และแสดง pop-up เพื่อช่วยเพิ่มประสิทธิภาพการใช้งานของ <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> และฟีเจอร์เซอร์วิสที่แก้ไขได้ คุณสามารถใช้เครื่องมือนี้ในการปรับแต่งและควบคุมการทำงานของ GeoForm ตามขั้นตอนทางซ้ายนี้",
            btnPreviousText: "ก่อนหน้า",
            btnNextText:"ต่อไป",
            webmapTabTitleText: "เลือกเว็บแมพ",
            btnSelectWebmapText:"เลือกเว็บแมพ",
            layerTabTitleText: "เลือกชั้นข้อมูลที่แก้ไขได้",
            selectLayerLabelText:"ชั้นข้อมูล",
            selectLayerDefaultOptionText:"เลือกชั้นข้อมูล",
            detailsTabTitleText:"แบบฟอร์มรายละเอียด",
            detailTitleLabelText: "ชื่อเรื่อง",
            detailLogoLabelText: "รูปโลโก้",
            detailDescriptionLabelText: "คำอธิบาย",
            fieldTabFieldHeaderText: "ฟิลด์",
            fieldTabLabelHeaderText: "ตัวอักษร",
            fieldTabTypeHeaderText: "ประเภท",
            fieldTabDescriptionHeaderText: "คำอธิบาย",
            previewApplicationText: "ดูตัวอย่างแอพพลิเคชั่น",
            saveApplicationText: "บันทึกแอพพลิเคชั่น",
            saveText: "บันทึก",
            toggleNavigationText: "เปลี่ยนการนำทาง",
            formPlaceholderText: "แบบฟอร์มของฉัน",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "กำลังเผยแพร่ GeoForm",
            shareBuilderProgressBarMessage:"โปรดรอสักครู่...",
            shareBuilderTitleMessage: "GeoForm ของคุณได้อัพเดทและเผยแพร่แล้ว!",
            shareBuilderTextMessage: "คุณสามารถเริ่มเก็บรวบรวมข้อมูลโดยการแชร์ร่วมกับผู้อื่น",
            shareDialogFormText: "แบบฟอร์มลิงก์",
            geoformTitleText: "Geo Form",
            layerTabText: "นี่คือชั้นข้อมูลที่จะนำไปสร้างเป็น GeoForm ชั้นข้อมูลจะต้องเป็นฟีเจอร์เซอร์วิสที่สามารถแก้ไขได้ พร้อมกับเปิดสิทธิ์การแชร์ให้กับทุกคนเรียบร้อยแล้ว",
            detailsTabText:"ใช้แบบฟอร์มรายละเอียดตามกล่องด้านล่างในการปรับแต่งชื่อเรื่อง เพิ่มโลโก้ และใส่คำบรรยายสั้นๆ สำหรับผู้ใช้งาน GeoForm ของคุณ",
            fieldsTabText:"คุณสามารถเลือกได้ว่าฟิลด์ที่จะปรากฏให้ผู้ชม ข้อมูล GeoForm ของคุณแก้ไขตัวอักษรที่พวกเขาจะเห็นและเพิ่มคำอธิบายสั้น ๆ เพื่อช่วยในการป้อนข้อมูล",
            styleTabText: "ปรับแต่งรูปแบบ GeoForm ของคุณ โดยใช้ธีมเหล่านี้ตามความชอบของคุณ",
            publishTabText: "หากคุณปรับแต่ง GeoForm ของคุณเสร็จ บันทึกการสมัครและเริ่มต้นการใช้งานร่วมกันกับผู้ชมของคุณ คุณสามารถกลับไปสร้างและดำเนินการในการปรับแต่งตามความคิดเห็นที่ได้รับ"
        }
    })
);