define({
  root: ({
    layer: "ก้_Layer___ษฺ",
    sort: "ก้_Sort by___ษฺ",
    order: "ก้_Order___ษฺ",
    desc: "ก้_Desc__ษฺ",
    asc: "ก้_Asc__ษฺ",
    loading: "ก้_loading&hellip;______ษฺ",
    search: "ก้_Search___ษฺ",
    searchPlaceholder: "ก้_Find reports_____ษฺ",
    noResults: "ก้_No results____ษฺ",
    ascending: "ก้_Ascending____ษฺ",
    descending: "ก้_Descending____ษฺ"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});