define(
     ({
        map: {
            error: "ไม่สามารถสร้างแผนที่ได้"
        },
        onlineStatus: {
            offline: "คุณกำลังทำงานแบบออฟไลน์ การส่งแบบฟอร์มจะถูกบันทึกไว้ที่เครื่องจนกว่าการเชื่อมต่อกับเซิร์ฟเวอร์จะสามารถทำได้",
            reconnecting: "กำลังเชื่อมต่อใหม่&hellip;",
            pending: "ก้_${total} pending edit(s) will be submitted when a network connection is re-established._ษฺ"
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "องค์กรของฉัน",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "เนื้อหาของฉัน",
                    favoritesLabel: "รายการโปรดของฉัน"
                },
                title: "เลือกเว็บแมพ",
                searchTitle: "ค้นหา",
                ok: "ตกลง",
                cancel: "ยกเลิก",
                placeholder: "ใส่เงื่อนไขการค้นหา"
            },
            groupdlg: {
                items: {
                    organizationLabel: "องค์กรของฉัน",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "เนื้อหาของฉัน",
                    favoritesLabel: "รายการโปรดของฉัน"
                },
                title: "เลือกกลุ่ม",
                searchTitle: "ค้นหา",
                ok: "ตกลง",
                cancel: "ยกเลิก",
                placeholder: "ใส่เงื่อนไขการค้นหา"
            }
        },
        user: {
            mgrs: "ก้_MGRS_ษฺ",
            usng: "ก้_USNG_ษฺ",
            utm: "ก้_UTM_ษฺ",
            utm_northing: "ก้_Northing_ษฺ",
            utm_easting: "ก้_Easting_ษฺ",
            utm_zone_number: "ก้_Zone Number_ษฺ",
            geoFormGeneralTabText: "ก้_1. Enter Information_ษฺ",
            locationInformationText: "ก้_2. Select Location_ษฺ",
            submitInformationText: "ก้_3. Complete Form_ษฺ",
            submitInstructions: "ก้_Add this information to the map._ษฺ",
            myLocationText: "ก้_Current Location_ษฺ",
            locationDescription: "ก้_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ษฺ",
            addressText: "ก้_Search_ษฺ",
            geographic: "ก้_Lat/Lon_ษฺ",
            locationTabText: "ก้_Location_ษฺ",
            locationPopupTitle: "ก้_Location_ษฺ",
            submitButtonText: "ก้_Submit Entry_ษฺ",
            submitButtonTextLoading: "ก้_Submitting&hellip;_ษฺ",
            formValidationMessageAlertText: "ก้_The following fields are required:_ษฺ",
            selectLocation: "ก้_Please select a ${openLink}location${closeLink} for your submission._ษฺ",
            emptylatitudeAlertMessage: "ก้_Please enter a ${openLink}latitude${closeLink} coordinate._ษฺ",
            emptylongitudeAlertMessage: "ก้_Please enter a ${openLink}longitude${closeLink} coordinate._ษฺ",
            shareUserTitleMessage: "ก้_Thank you for your contribution!_ษฺ",
            entrySubmitted: "ก้_Your entry has been submitted to the map._ษฺ",
            shareThisForm: "ก้_Share This Form_ษฺ",
            shareUserTextMessage: "ก้_Tell others to contribute using the following options._ษฺ",
            addAttachmentFailedMessage: "ก้_Unable to add attachment to layer_ษฺ",
            addFeatureFailedMessage: "ก้_Unable to add feature to layer_ษฺ",
            noLayerConfiguredMessage: "ก้_Whoops! Nothing to see here. In order to start collecting form submissions, configure this GeoForm and select an editable Feature Service layer to use._ษฺ",
            placeholderLatitude: "ก้_Latitude (Y)_ษฺ",
            placeholderLongitude: "ก้_Longitude (X)_ษฺ",
            latitude: "ก้_Latitude_ษฺ",
            longitude: "ก้_Longitude_ษฺ",
            findMyLocation: "ก้_Locate Me_ษฺ",
            finding: "ก้_Locating&hellip;_ษฺ",
            backToTop: "ก้_Back to top_ษฺ",
            addressSearchText: "ก้_Your submission will appear here. You can drag the pin to correct the location._ษฺ",
            shareModalFormText: "ก้_Form Link_ษฺ",
            close: "ก้_Close_ษฺ",
            locationNotFound: "ก้_Location could not be found._ษฺ",
            setLocation: "ก้_Set Location_ษฺ",
            find: "ก้_Find address or place_ษฺ",
            attachment: "ก้_Attachment_ษฺ",
            toggleDropdown: "ก้_Toggle Dropdown_ษฺ",
            invalidLatLong: "ก้_Please enter valid ${latLink}latitude${closeLink} and ${lngLink}longitude${closeLink} coordinates._ษฺ",
            invalidUTM: "ก้_Please enter valid ${openLink}UTM${closeLink} coordinates._ษฺ",
            invalidUSNG: "ก้_Please enter valid ${openLink}USNG${closeLink} coordinates._ษฺ",
            invalidMGRS: "ก้_Please enter valid ${openLink}MGRS${closeLink} coordinates._ษฺ",
            geoformTitleText: "ก้_GeoForm_ษฺ",
            domainDefaultText: "ก้_Select&hellip;_ษฺ",
            applyEditsFailedMessage: "ก้_Sorry your entry cannot be submitted. Please try again._ษฺ",
            requiredFields: "ก้_There are some errors. Please correct them below._ษฺ",
            requiredField: "ก้_(required)_ษฺ",
            error: "ก้_Error_ษฺ",
            textRangeHintMessage: "ก้_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ษฺ",
            dateRangeHintMessage: "ก้_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ษฺ"
        },
        builder: {
            invalidUser: "ก้_Sorry, you dont have permission to view this item_ษฺ",
            invalidWebmapSelectionAlert: "ก้_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ษฺ",
            invalidWebmapSelectionAlert2: "ก้_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ษฺ",
            selectFieldsText: "ก้_Select Form Fields_ษฺ",
            selectThemeText: "ก้_Select Form Theme_ษฺ",
            webmapText: "ก้_Webmap_ษฺ",
            layerText: "ก้_Layer_ษฺ",
            detailsText: "ก้_Details_ษฺ",
            fieldsText: "ก้_Fields_ษฺ",
            styleText: "ก้_Style_ษฺ",
            optionText: "ก้_Options_ษฺ",
            previewText: "ก้_Preview_ษฺ",
            publishText: "ก้_Publish_ษฺ",
            optionsApplicationText: "ก้_Options_ษฺ",
            titleText: "ก้_Builder_ษฺ",
            descriptionText: "ก้_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ษฺ",
            btnPreviousText: "ก้_Previous_ษฺ",
            btnNextText: "ก้_Next_ษฺ",
            webmapTabTitleText: "ก้_Select a Webmap_ษฺ",
            viewWebmap: "ก้_View webmap_ษฺ",
            btnSelectWebmapText: "ก้_Choose Webmap_ษฺ",
            btnSelectWebmapTextLoading: "ก้_Loading&hellip;_ษฺ",
            layerTabTitleText: "ก้_Select Editable Layer_ษฺ",
            selectLayerLabelText: "ก้_Layer_ษฺ",
            selectLayerDefaultOptionText: "ก้_Select Layer_ษฺ",
            detailsTabTitleText: "ก้_Form Details_ษฺ",
            detailTitleLabelText: "ก้_Title_ษฺ",
            detailLogoLabelText: "ก้_Logo Image_ษฺ",
            descriptionLabelText: "ก้_Help Text (optional)_ษฺ",
            fieldTabFieldHeaderText: "ก้_Field_ษฺ",
            fieldTabLabelHeaderText: "ก้_Label_ษฺ",
            fieldTabDisplayTypeHeaderText: "ก้_Display As_ษฺ",
            selectMenuOption: "ก้_Select Menu_ษฺ",
            selectRadioOption: "ก้_Radio Button_ษฺ",
            selectTextOption: "ก้_Text_ษฺ",
            selectCheckboxOption: "ก้_Checkbox_ษฺ",
            selectMailOption: "ก้_Email_ษฺ",
            selectUrlOption: "ก้_URL_ษฺ",
            selectTextAreaOption: "ก้_Textarea_ษฺ",
            previewApplicationText: "ก้_Preview Application_ษฺ",
            saveApplicationText: "ก้_Save Application_ษฺ",
            saveText: "ก้_Save_ษฺ",
            toggleNavigationText: "ก้_Toggle navigation_ษฺ",
            formPlaceholderText: "ก้_My Form_ษฺ",
            shareBuilderInProgressTitleMessage: "ก้_Publishing GeoForm_ษฺ",
            shareBuilderProgressBarMessage: "ก้_Please Wait&hellip;_ษฺ",
            shareBuilderTitleMessage: "ก้_Success! Item saved_ษฺ",
            shareBuilderTextMessage: "ก้_You can start collecting information by sharing with others_ษฺ",
            shareModalFormText: "ก้_Form Link_ษฺ",
            shareBuilderSuccess: "ก้_Your GeoForm has been updated & published!_ษฺ",
            geoformTitleText: "ก้_Geo Form_ษฺ",
            layerTabText: "ก้_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ษฺ",
            detailsTabText: "ก้_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._ษฺ",
            fieldsTabText: "ก้_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ษฺ",
            styleTabText: "ก้_Style your GeoForm using the themes below based on your preference._ษฺ",
            publishTabText: "ก้_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ษฺ",
            smallHeader: "ก้_Use Small Header_ษฺ",
            pushpinText: "ก้_Push pin_ษฺ",
            doneButtonText: "ก้_View Application Item_ษฺ",
            fieldTabPlaceHolderHeaderText: "ก้_Hint (optional)_ษฺ",
            attachmentLabelText: "ก้_Attchment Label_ษฺ",
            attachmentLabelHint: "ก้_Tell users what type of file to attach._ษฺ",
            attachmentDescription: "ก้_Attachment Description_ษฺ",
            attachmentHint: "ก้_If necessary, you can provide additional attachment instructions here._ษฺ",
            jumbotronDescription: "ก้_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ษฺ",
            shareGeoformText: "ก้_Share Geoform_ษฺ",
            shareDescription: "ก้_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._ษฺ",
            defaultMapExtent: "ก้_Default Map Extent_ษฺ",
            defaultMapExtentDescription: "ก้_The map will reset to the default extent in your web map after submission - this can be disabled at any time._ษฺ",
            pushpinOptionsDescription: "ก้_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ษฺ",
            selectLocationText: "ก้_Select Location By_ษฺ",
            myLocationText: "ก้_My Location_ษฺ",
            searchText: "ก้_Search_ษฺ",
            coordinatesText: "ก้_Latitude & Longitude Coordinates_ษฺ",
            usng: "ก้_USNG Coordinates_ษฺ",
            mgrs: "ก้_MGRS Coordinates_ษฺ",
            utm: "ก้_UTM Coordinates_ษฺ",
            selectLocationSDescription: "ก้_Allow users to select a location using these methods._ษฺ"
        }
    })
);