define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Vào Bộ thiết lập",
                "exitBuilderButtonText": "Thoát Bộ thiết lập",
                "enterBuilderModeHelpText": "Chuyển sang Chế độ Bộ thiết lập để cấu hình ứng dụng",
                "builderModeHelpText": "Chế độ Bộ thiết lập Mẫu",
                "webmapCaption": "Bản đồ",
                "selectMapMessage": "Hiện ${displaying} <b>${webmapTitle}</b><br/>Nhấp vào Chọn bản đồ để chọn một webmap khác",
                "loadMapMessage": "Hiện đã chọn <b>${webmapTitle}</b><br/>Nhấp vào Lưu để sử dụng webmap này",
                "changeWebmap": "Chọn bản đồ",
                "saveButtonText": "Lưu",
                "webmapNextButtonText": "Tiếp theo ->",
                "previousButtonText":"Trước",
                "layerLabelText": "Lớp",
                "noLayerFoundText": "Không tìm thấy Lớp nào",
                "selectLayer": "Chọn Lớp",
                "applicationSettingText": "Cài đặt ứng dụng",
                "summaryAttrAscendingOrderTooltip": "Tăng dần",
                "onStartLabel": "Bắt đầu",
                "selectVariableText": "Chọn Biến A",
                "selectVariableDropdown": "Chọn Biến A",
                "label":"Nhãn",
                "sourceLinkText":"Liên kết nguồn",
                "selectSubVariableText":"Chọn các biến phụ",
                "subVariablePanelButtonText":"ĐÃ HOÀN TẤT",
                "onButtonLabel":"Bật",
                "offButtonLabel":"Tắt",
                "appSettingsSaveCloseButtonText": "LƯU & ĐÓNG",
                "appSettingsTitleText":"Tiêu đề ứng dụng",
                "appSettingsDescriptionText": "Mô tả ứng dụng",
                "appSetingsRendererAreaText":"Khu vực hiển thị",
                "shareText":"Chia sẻ",
                "basemapText":"Bản đồ nền",
                "basemapSelectionText":"Chọn bản đồ nền",
                "secondaryBasemapText":"Bản đồ nền phụ",
                "defaultBasemapText": "Bản đồ nền mặc định",
                "entireAreaButton": "Toàn bộ Khu vực",
                "entireAreaOnStartButton": "Toàn bộ khu vực khi bắt đầu",
                "aboutPanel": "Về Bảng điều khiển",
                "legendPanel": "Bảng điều khiển chú giải",
                "layersPanel": "Bảng điều khiển lớp",
                "dataConfigurationButtonText": "Cấu hình dữ liệu",
                "savingChangesMessage": "Đang lưu thay đổi...",
                "nextButtonText": "Tiếp",
                "prevButtonText": "Trước",
                "enterLabelText": "Nhập Nhãn",
                "SelectedFeatureText": "Yếu tố được chọn",
                "layerHelpTextMessage": "Ứng dụng này yêu cầu một lớp có các trường số",
                "alertMessage": {
                    "resetVariableMessage": "Đ_Are you sure you want to reset variable_ớ?",
                    "emptyAppTitleMessage": "Tên ứng dụng không được trống",
                    "emptyDescriptionMessage": "Mô tả không được trống",
                    "maxVariableSelection": "Bạn không thể chọn nhiều hơn 25 biến phụ",
                    "signInFail" : "Đăng nhập Thất bại",
                    "itemUpdateMessage": "Mục được cập nhật",
                    "unsavedChangesMessage": "Thay đổi chưa được lưu",
                    "failMessage": "Không thể cập nhật mục thành công",
                    "saveChangesAlert": "Bạn có muốn lưu thay đổi không?",
                    "variableLabelValidation": "Đ_Variable label cannot be empty_ớ",
                    "subVariableLabelValidation": "Đ_Sub variable label cannot be empty_ớ"
                    }
            }
        }
    })
);