define(
({
		viewer: {
			loading: {
				step1: "NAHRÁVÁNÍ APLIKACE",
				step2: "NAHRÁVÁNÍ DAT",
				step3: "SPOUŠTĚNÍ PROHLÍDKY",
				loadBuilder: "PŘEPÍNÁNÍ DO REŽIMU TVORBY",
				redirectSignIn: "PROBÍHÁ PŘESMĚROVÁNÍ NA PŘIHLAŠOVACÍ STRÁNKU",
				redirectSignIn2: "(budete sem přesměrováni po přihlášení)",
				fail: "Je nám líto, ale nepodařilo se načíst prohlídku mapy.",
				failButton: "Zkusit znovu"
			},
			errors: {
				boxTitle: "Nastala chyba.",
				portalSelf: "Závažná chyba: Nepodařilo se získat konfiguraci portálu.",
				invalidConfig: "Závažná chyba: Neplatná konfigurace",
				invalidConfigOwner: "Závažná chyba: Neplatná konfigurace (vyžadován autorizovaný vlastník)",
				invalidConfigNoWebmap: "Závažná chyba: Neplatná konfigurace (v index.html není specifikována webová mapa nebo identifikátor aplikace)",
				createMap: "Nelze vytvořit mapu",
				invalidApp: "Závažná chyba: Aplikaci nelze načíst",
				noLayer: "Webová mapa neobsahuje platnou datovou vrstvu k prohlídce mapy.",
				noLayerMobile: "Vítejte ve webové aplikaci prohlídky mapy. Aplikace není nakonfigurována. Nástroj pro tvorbu prohlídek map není podporován na mobilních zařízeních.",
				noLayerView: "Vítejte ve webové aplikaci prohlídky mapy.<br />Aplikace zatím není nakonfigurována.",
				appSave: "Chyba při ukládání webové aplikace",
				mapSave: "Chyba při ukládání webové mapy",
				featureServiceLoad: "Chyba při načítání služby Feature Service",
				notAuthorized: "Nemáte oprávnění k přístupu do této aplikace.",
				oldBrowserTitle: "Prohlížeč není plně podporován.",
				noBuilderIE8: "Nástroj pro tvorbu prohlídek map není podporován programem Internet Explorer verze nižší než 9.",
				ie10Win7Explain: "Interaktivní nástroj pro tvorbu prohlídek map není podporován prohlížečem Internet Explorer 10 ve Windows 7, pokud je zdrojem dat služba Feature Service s přílohami. Chcete-li použít službu Feature Service s přílohami, bude nutné <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuálně přepnout režim dokumentu na standardy Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgradovat na Internet Explorer 9</a> nebo upgradovat na Windows 8.",
				oldBrowserExplain: "Váš prohlížeč nepodporuje automatickou tvorbu miniatur z obrázků nahraných do prohlídky mapy. Prohlídku mapy lze v prohlížeči vytvořit, bude však nutné ke každému nahranému obrázku dodat samostatnou miniaturu.",
				oldBrowserExplain2: "Pro plynulejší chod <a href='http://browsehappy.com/' target='_blank'>stáhněte jiný prohlížeč</a> nebo <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>nainstalujte Google Chrome Frame pro Internet Explorer</a>.",
				oldBrowserExplain3: "Nástroj pro tvorbu prohlídek map nefunguje v prohlížeči Internet Explorer 10 ve Windows XP.",
				oldBrowserClose: "Zavřít"
			},
			mobileHTML: {
				showIntro: "ZOBRAZIT NADPIS",
				hideIntro: "SKRÝT NADPIS",
				navList: "Seznam",
				navMap: "Mapa",
				navInfo: "Média",
				introStartBtn: "Spustit"
			},
			desktopHTML: {
				storymapsText: "Mapa s příběhem",
				builderButton: "Přepnout do režimu tvorby",
				bitlyTooltip: "Získejte krátký odkaz k aplikaci",
				bitlyStartIndex: "Odkaz na současné místo"
			},
			builderHTML: {
				panelHeader: "KONFIGURACE APLIKACE",
				buttonSave: "ULOŽIT",
				buttonSettings: "Nastavení",
				buttonShare: "Ř_Share_ů",
				buttonView: "Režim prohlížení",
				buttonItem: "Otevřít položku webové aplikace",
				buttonHelp: "Nápověda",
				buttonOrganize: "Organizovat",
				buttonAdd: "Přidat",
				buttonImport: "Import",
				buttonImportDisabled: "Import není dostupný, pokud je využívána služba Feature Service s přílohami.",
				dataEditionDisabled: "Úprava dat je u zdroje dat ve formátu CSV zakázána.",
				dataSourceWarning: "Vrstva prohlídky mapy se změnila. Nejsou-li ID prvků stejná, musíte resetovat pořadí a skryté body pomocí volby <b>Organizovat</b>. Pokud se liší názvy polí, musíte resetovat nastavení polí v <b>záložce dat v Nastavení</b>.",
				organizeWarning: "Jeden nebo více bodů přidaných mimo interaktivní nástroj pro tvorbu jsou skryty.",
				dataPicError0a: "Tato prohlídka obsahuje <b>%NB%</b> nevyhovujících URL obrázků.",
				dataPicError0b: "Tato prohlídka může obsahovat <b>%NB%</b> nevyhovujících URL obrázků.",
				dataPicError1: "Prohlídky map nyní vyžadují, aby URL obrázků měly jednu z těchto přípon: jp(e)g, png, gif nebo bmp.",
				dataPicError2: "Tento požadavek nebude mít vliv na existující publikované prohlídky mapy. Aby však bylo možné používat interaktivní nástroj pro tvorbu, je nutné nejprve vyřešit problém s URL provedením jedné z následujících akcí:",
				dataPicError3: "Upravit URL",
				dataPicError4: "Tato možnost přidá na konec nepodporovaných URL obrázků parametr <i>#isImage</i>. Většina serverů dodatky k URL adresám podporuje. Po provedení této akce je vhodné si navigací mezi body ověřit, zda jsou aktualizované URL obrázků funkční. Pokud se všechny obrázky načtou, můžete prohlídku mapy uložit. Pokud jsou <b>některé obrázky nefunkční, neukládejte prohlídku mapy</b>. Namísto toho znovu načtěte nástroj pro tvorbu a proveďte druhou nabídnutou akci.",
				dataPicError5: "Omezit prohlídku na obrázky",
				dataPicError6: "Tato možnost způsobí, že budou všechny URL adresy považovány za obrázky. Pomocí interaktivního nástroje pro tvorbu však nebude možné přidávat videa. Pokud se v budoucnosti rozhodnete přidávat videa, lze tuto akci vrátit zpět.",
				dataPicError7: "Vaše prohlídka mapy byla omezena na obrázky, není možné používat videa. Pokud se rozhodnete toto omezení odebrat, před uložením prohlídky se ujistěte, že se všechny obrázky stále správně načítají. V případě potřeby budete moci toto omezení později znovu obnovit.",
				dataPicError8: "Odebrat omezení na obrázky",
				dataPicError9: "Pokud tyto URL adresy odkazují na videa, můžete toto upozornění ignorovat. Pokud odkazují na obrázky, je nutné provést jednu z následujících akcí:",
				modalCancel: "Storno",
				modalApply: "Použít",
				organizeHeader: "Organizovat prohlídku",
				organizeGeneralCaption: "Uspořádejte body prohlídky jejich přetáhnutím.",
				organizeDelete: "Smazat",
				organizeHide: "Skrýt",
				organizeReset: "Resetovat pořadí a skryté body.",
				addMaxPointReached: "Dosáhli jste maximálního počtu bodů autorizovaných sadou ikon a nemůžete již přidat další bod prohlídky.<br /><br />Vymažete-li již existující body, budete muset aplikaci otevřít znovu.",
				addMaxPointReachedMobile: "Omlouváme se, dosáhli jste maximálního počtu autorizovaných bodů a tento obrázek proto nemůžete přidat.",
				addClose: "Zavřít",
				addHeader: "Přidat nový bod prohlídky",
				addTabPicture: "Média",
				addTabInformation: "Informace",
				addTabLocation: "Umístění",
				addSelectCaption: "Vyberte nebo přetáhněte obrázek.",
				addNoteVideo: "Více informací o používání videí naleznete v nápovědě",		
				addSelectCaptionNoFileReader: "Vybrat obrázek",	
				addChangePhoto: "Změnit obrázek a miniaturu",
				addPictureResolutionIntro: "Rozlišení obrázku je příliš vysoké.",
				addPictureResolutionOldBrowser: "Rozlišení obrázku je příliš vysoké. Optimalizujte chod prohlídky mapy použitím rozlišení, které je nižší než %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Změnit rozlišení obrázku na %RESOLUTION%",
				addPictureResolutionKeep: "Ponechat původní rozlišení %RESOLUTION%",
				addSelectThumbnail: "Vybrat miniaturu",
				addNoThumbSelected: "Není vybrána žádná miniatura",
				addThumbSelected: "Vybrána",
				addCameraSettingsHeader: "NASTAVENÍ FOTOAPARÁTU",
				addThumbnailHeader: "MINIATURA",
				addLabelPicUrl: "Obrázek",
				addLabelThumbUrl: "Miniatura",
				addTextPlaceholderUrl: "Zadejte URL obrázku.",
				addTextPlaceholderUrl2: "Ř_Enter a Youtube page URL_ů",
				addTextPlaceholderUrl3: "Zadejte URL stránky Vimeo.",
				addTextPlaceholderUrl4: "Zadejte URL pro vložení videa.",
				addLabelVideo: "Video",
				addMediaVideoOther: "Jiné",
				addMediaVideoHelp: "Zkontrolovat URL a získat výchozí miniaturu",
				addMediaVideoHelpTooltip1: "Kontrola byla úspěšná.",
				addMediaVideoHelpTooltip2: "Kontrola se nezdařila.",
				addMediaVideoHelpTooltip4: "Najděte možnost vložení videa a zkopírujte URL videa, které se nachází v kódu",
				addLabelName: "Název",
				addLabelDescription: "Popisek",
				addTextPlaceholder: "Napište zde něco",
				addLocatePlaceholder: "Najít adresu nebo místo",
				addPinColor: "Barva",
				addLatitude: "Zeměpisná šířka",
				addLongitude: "Zeměpisná délka",
				addLatitudePlaceholder: "např. 34,056",
				addLongitudePlaceholder: "např. -117,195",
				addUploading: "Nahrávání bodu prohlídky",
				addSave: "Přidat bod prohlídky",
				addMobileUploading: "Nahrávání obrázku",
				addMobileName: "Zadejte jméno",
				addMobileNameMandatory: "Chyba, zadejte prosím název.",
				addMobileError: "Omlouváme se, někde se stala chyba.",
				settingsHeader: "Nastavení aplikace",
				settingsTabLayout: "Rozvržení",
				settingsTabColor: "Barvy",
				settingsTabLogo: "Záhlaví",
				settingsTabFields: "Data",
				settingsTabExtent: "Rozsah",
				settingsTabZoom: "Úroveň přiblížení",
				settingsLayoutExplain: "Vyberte požadované rozvržení aplikace.",
				settingsLayoutProfessional: "Rozvržení tří panelů",
				settingsLayoutModern: "Ucelené rozvržení",
				settingsLayoutSelected: "Vybrané rozvržení",
				settingsLayoutSelect: "Zvolit toto rozvržení",
				settingsLayoutNote: "Při používání videí na bodech bude pod videem vždy poutač, i když tato možnost není zaškrtnuta.",
				settingsLayoutLocBtn: "Ř_Display a locate button on supported browser_ů",
				settingsLayoutLocBtnHelp: "Tato funkcionalita je podporována na většině mobilních zařízení a stolních prohlížečů (Internet Explorer 9).",
				settingsColorExplain: "Změňte vzhled volbou přednastaveného motivu, nebo si vytvořte svůj vlastní.",
				settingsLabelColor: "Barvy záhlaví, obsahu a zápatí",
				settingsLogoExplain: "Přizpůsobte logo v záhlaví (maximum je 250 × 50 px).",
				settingsLogoEsri: "Logo Esri",
				settingsLogoNone: "Bez loga",
				settingsLogoCustom: "Vlastní logo",
				settingsLogoCustomPlaceholder: "URL obrázku",
				settingsLogoCustomTargetPlaceholder: "Odkaz při kliknutí na obrázek",
				settingsLogoSocialExplain: "Upravit odkaz v pravé horní části záhlaví.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Odkaz",
				settingsLogoSocialDisabled: "Tato funkce byla zakázána administrátorem.",
				settingsDataFieldsExplain: "Vyberte pole názvu, popisku a barvy.",
				settingsDataFieldsError: "Aplikace nedokáže určit vhodná data názvu, popisku nebo barvy. Zvolte prosím pole, která mají být použita. Toto nastavení lze kdykoliv změnit.",
				settingsFieldsLabelName: "Název",
				settingsFieldsLabelDescription: "Popisek",
				settingsFieldsLabelColor: "Barva",
				settingsFieldsReset: "Resetovat výběr polí.",
				settingsExtentExplain: "Prostřednictvím následující interaktivní mapy nastavte výchozí rozsah prohlídky mapy.",
				settingsExtentExplainBottom: "Vámi definovaný rozsah upraví počáteční rozsah vaší webové mapy. Pokud rozsah neobsahuje první bod prohlídky, nepoužije se. Prohlídka se v takovém případě otevře vycentrovaná na první bod.",
				settingsExtentDateLineError: "Rozsah nesmí přesahovat 180° zeměpisné délky.",
				settingsExtentDateLineError2: "Při výpočtu rozsahu došlo k chybě.",
				settingsExtentDrawBtn: "Určit nový rozsah",
				settingsExtentModifyBtn: "Upravit rozsah",
				settingsExtentApplyBtn: "Zobrazit náhled na prohlídce mapy",
				settingsExtentUseMainMap: "Použít rozsah prohlídky mapy",
				settingsZoomExplain: "Nastavit přiblížení bodů příběhu po úvodu (nepovinné).",
				settingsLabelZoom: "Měřítko/úroveň",
				settingsZoomFirstValue: "Žádné",
				settingsFieldError: "Vyberte pole v každém seznamu.",
				dataTitle: "Hosting ArcGIS Online",
				dataExplain: "Ř_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._ů",
				dataNameLbl: "Název služby",
				dataFolderListLbl: "Složka",
				dataFolderListFetching: "Načítání složek…",
				dataRootFolder: "Kořenový adresář",
				dataNameError: "Zadejte název služby Feature Service",
				dataFolderError: "Vyberte platnou složku",
				dataSrcContainsInvalidChar: "Jméno služby obsahuje jeden nebo několik neplatných znaků (-, <, >, #, %, :, \", ?, &, +, /, nebo \).",
				dataSrvAlreadyExistsError: "Služba s tímto jménem už v mapách organizace existuje. Zvolte prosím jiné jméno.",
				dataBtnSave: "Vytvořit službu",
				dataFooterProgress: "Služba se vytváří",
				dataFooterSucceed: "Vytvoření se podařilo. Načítání",
				dataFooterError: "Vytvoření se nezdařilo. Zkuste to prosím znovu.",
				tabError: "Zkontrolujte prosím, nejsou-li v záložkách chyby.",
				introRecordBtn: "Úvod",
				introRecordActivate: "Použít první bod jako úvod (nezobrazuje se v karuselu)"
			},
			addPopupJS: {
				uploadingPicture: "Nahrávání obrázku",
				uploadSuccess: "Nahrání proběhlo úspěšně.",
				uploadError: "Při nahrávání obrázku nastala chyba.",
				uploadError2: "Chyba při přidávání prvku (neplatná značka HTML)",
				notJpg: "Vyberte prosím soubor jpeg, který chcete nahrát.",
				errorNoPhoto: "Vyberte obrázek, který chcete nahrát.",
				errorNoThumbnail: "Vyberte miniaturu, kterou chcete nahrát.",
				errorInvalidPicUrl: "Zadejte platný obrázek (začíná http(s):// a končí příponou jpg, png, gif nebo bmp). Chcete-li tento požadavek potlačit, vložte na konec URL parametr #isImage.",
				errorInvalidThumbUrl: "Zadejte platnou miniaturu (začíná http(s):// a končí příponou jpg, png, gif nebo bmp).",
				errorInvalidVideoUrl: "Zadejte platnou adresu URL videa (začíná http(s)://).",
				errorNoName: "Zadejte jméno tohoto bodu prohlídky.",
				errorNoDescription: "Zadejte popisek tohoto bodu prohlídky.",
				errorNoLocation: "Nastavte umístění tohoto bodu prohlídky."
			},
			builderJS: {
				noPendingChange: "Žádná neuložená změna",
				unSavedChangeSingular: "1 neuložená změna",
				unSavedChangePlural: "neuložených změn",
				shareStatus1: "Ř_Tour is not saved_ů",
				shareStatus2: "Ř_Tour is shared publicly_ů",
				shareStatus3: "Ř_Tour is shared within the organization_ů",
				shareStatus4: "Ř_Tour is not shared_ů",
				popoverDiscard: "Určitě chcete přijít o všechny neuložené změny?",
				yes: "Ano",
				no: "Ne",
				popoverLoseSave: "Otevřením tohoto prohlížeče přijdete o všechny neuložené změny.",
				ok: "OK",
				popoverSaveWhenDone: "Až budete hotovi, nezapomeňte provedené změny uložit.",
				closeWithPendingChange: "Určitě chcete potvrdit tuto akci? Vaše změny nebudou uloženy.",
				gotIt: "OK",
				savingApplication: "Ukládání aplikace",
				saveSuccess: "Aplikace byla úspěšně uložena.",
				saveError: "Uložení se nezdařilo, zkuste to prosím znovu.",
				saveError2: "Ukládání selhalo kvůli neplatné značce HTML v názvu nebo popisu.",
				saveError3: "Název nesmí být prázdný",
				dragColorPicker: "Přesuň<br />nebo změň  barvu.",
				dataWarningExtent: "Některá data se nachází mimo rozsah webové mapy. Tato data nebudou použita jako body prohlídky. Chcete-li je použít, změňte rozsah mapy.",
				dataWarningVisibi: "Vrstva prohlídky mapy není při současném rozsahu webové mapy viditelná. Ujistěte se, že je vrstva prohlídky mapy viditelná v mapě o velikosti %MAPSIZE%.",
				dataWarningEdit: "Upravit webovou mapu",
				dataWarningClose: "Zavřít",
				signIn: "Přihlaste se pomocí účtu na",
				signInTwo: "pro uložení aplikace.",
				switchBM: "Změnit podkladovou mapu"
			},
			organizePopupJS: {
				messageStart: "Přejete si odstranit",
				messageSinglePoint: "bod prohlídky",
				messageMultiPoint: "body prohlídky",
				messagePermantRemove: "Tato činnost nevratně odstraní",
				messageRecord: "záznam",
				messageRecordPlural: "záznamy",
				messageConfirm: "z vaší databáze. Přejete si pokračovat?",
				labelButtonShow: "Zobrazit",
				labelButtonHide: "Skrýt"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Tato činnost nevratně odstraní obrázek a miniaturu.",
				popoverDeleteWarningThumb: "Tato činnost nevratně odstraní miniaturu.",
				popoverUploadingPhoto: "Nahrávání obrázku a miniatury",
				popoverUploadingThumbnail: "Nahrávání miniatury",
				popoverUploadSuccessful: "Nahrání proběhlo úspěšně.",
				popoverUploadError: "Nahrání se nezdařilo, zkuste to prosím znovu.",
				changePicAndThumb: "Změnit obrázek",
				changeThumb: "Změnit miniaturu",
				selectPic: "Změnit média",
				selectThumb: "Změnit miniaturu",
				uploadPicAndThumb: "Použít"
			},
			headerJS:{
				editMe: "Uprav mě!",
				templateTitle: "Nastavit název šablony",
				templateSubtitle: "Nastavit podnadpis šablony"
			},
			crossFaderJS:{
				setPicture: "Nastavit název obrázku",
				setCaption: "Nastavit popisek obrázku"
			},
			importPopup: {
				title: "Import",
				prevBtn: "Zpět",
				nextBtn: "Další"
			},
			importPopupHome: {
				header: "Kde máte obrázky uloženy?"
			},
			onlinePhotoSharingCommon: {
				pictures: "obrázky",
				videos: "videa",
				disabled: "Tato funkce byla zakázána administrátorem.",
				disabledPortal: "Tato funkce byla ve službě Portal for ArcGIS zakázána.",
				header1: "Vaše obrázky musí být sdíleny veřejně.",
				header2: "Import bude omezen na prvních %NB1% %MEDIA%.",
				emptyDataset: "Chyba: nebyly nalezeny žádné obrázky",
				footerImport: "Import",
				selectAlbum: "Vybrat veřejné album",
				selectAlbum2: "Vybrat album",
				pleaseChoose: "Prosím vyberte.",
				userLookup: "Vyhledat",
				userLookingup: "Vyhledávání",
				csv: "Odkazováno ze souboru CSV",
				advanced: "Pokročilé možnosti",
				advancedScratchLbl: "Ř_Start a new Tour_ů",
				advancedScratchTip: "Ř_Create an empty Tour that you will be able populate manually using a wizard._ů",
				advancedCSVLbl: "Ř_Import Tour data from a CSV file_ů",
				advancedCSVTip: "Ř_Import your Tour content from a CSV file._ů",
				advancedCommonTip: "Ř_It requires that your images and videos are already online._ů",
				select: "Provést výběr",
				locUse: "Používat geo-umístění obrázků",
				locExplain: "Ř_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._ů",
				locExplain2: "Ř_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._ů"
			},
			viewFlickr: {
				title: "Import z Flickru",
				header: "Ř_Enter your Flickr user name and select a Photo Set or a Tag to be imported._ů",
				userInputLbl: "Zadat uživatelské jméno",
				signInMsg2: "Uživatel nenalezen",
				selectSet: "Vybrat sadu fotografií",
				selectTag: "nebo Vybrat značku",
				footerImportTag: "Importovat vybranou značku",
				footerImportSet: "Importovat vybranou sadu"
			},
			viewFacebook: {
				title: "Import z Facebooku",
				header: "Ř_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._ů",
				leftHeader: "Uživatel služby Facebook",
				rightHeader: "Stránka služby Facebook",
				pageExplain: "Stránka služby Facebook představuje veřejnou značku či službu nebo známou osobnost, jako je například <b>esrigis</b>. Název stránky začíná za prvním lomítkem (/) v URL adrese stránky.",
				pageInputLbl: "Zadat název stránky",
				lookupMsgError: "Stránka nenalezena"
			},
			viewPicasa: {
				title: "Import z Picasa/Google+",
				header: "Ř_Enter your email address or the ID of your Picasa or Google+ account._ů",
				userInputLbl: "Zadat e-mail nebo identifikátor",
				signInMsg2: "Účet nenalezen",
				howToFind: "Jak najít identifikátor účtu Picasa nebo Google+",
				howToFind2: "Zkopírujte číslice mezi prvním a druhým lomítkem (/) libovolné stránky služeb Picasa nebo Google+."
			},
			viewCSV: {
				title: "Import CSV",
				uploadBtn: "Vybrat nebo přetáhnout soubor CSV",
				resultHeaderEmpty: "Soubor CSV je prázdný",
				resultHeaderSuccess: "Počet úspěšně načtených bodů: %NB_POINTS%",
				resultHasBeenLimited: "Import byl omezen na prvních %VAL1% bodů z %VAL2%, aby byl dodržen limit %VAL3% bodů na prohlídku.",
				browserSupport: "Váš prohlížeč není podporován. Chcete-li používat formát CSV, bude nutné <a href='http://browsehappy.com/' target='_blank'>upgradovat prohlížeč</a> nebo použít webový prohlížeč map ArcGIS.com (viz nápověda).",
				errorLatLng: "Pole pro zeměpisnou šířku a délku nebyly nalezeny. Možné hodnoty pro zeměpisnou šířku jsou <i>%LAT%</i> a pro délku <i>%LONG%</i>.",
				errorFieldsExplain: "Načtení se nezdařilo, protože nebyla nalezena následující pole:",
				errorFieldsName: "<b>Název</b>, možné hodnoty: %VAL%",
				errorFieldsDesc: "<b>Popis</b>, možné hodnoty: %VAL%",
				errorFieldsUrl: "<b>URL obrázku</b>, možné hodnoty: %VAL%",
				errorFieldsThumb: "<b>URL miniatury</b>, možné hodnoty: %VAL%",
				errorFields2Explain: "Načtení se nezdařilo, protože soubor CSV nepoužívá stejné atributy, jako vrstva pro následující atributy.",
				errorFields2Name: "<b>Název</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
				errorFields2Desc: "<b>Popis</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
				errorFields2Url: "<b>URL obrázku</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
				errorFields2Thumb: "<b>URL miniatury</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
				resultFieldsAll: "Všechny atributy byly importovány.",
				resultFieldsNotAll: "Následující atributy nebyly importovány, protože v mapové vrstvě neexistují.",
				resultFieldsNotAll2: "Byly importovány následující atributy:",
				footerNextBtnResult: "Import do webové mapy",
				footerProgress: "Probíhá import",
				footerSucceed: "Import byl úspěšný. Načítání"
			},
			viewYoutube: {
				title: "Import z YouTube",
				header: "Zadejte uživatelské jméno YouTube, abyste našli veřejně sdílená videa.",
				pageInputLbl: "Ř_Enter a Youtube user name_ů",
				lookupMsgError: "Uživatel nenalezen",
				howToFind: "Ř_How to find a Youtube user name_ů",
				howToFind2: "Uživatelské jméno se zobrazuje pod videi",
				found: "Nalezeno",
				noData: "Nenalezena žádná veřejná videa"
			},
			viewGeoTag: {
				title: "Ř_Select and locate your images/videos_ů",
				header: "Klikněte nebo klepněte na obrázky, které chcete importovat, abyste je našli.",
				headerMore: "Proč nejsou mé obrázky/videa geolokalizovány?",
				headerExplain: "Ř_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._ů",
				leftPanelTab1: "Umístit",
				leftPanelTab2: "Umístěno",
				clickOrTap: "Kliknutím nebo klepnutím na mapu provedete umístění.",
				clearLoc: "Ř_Clear locations_ů",
				clickDrop: "Neimportovat",
				footerImport: "Import",
				footerProgress: "Probíhá import",
				footerSucceed: "Import byl úspěšný. Načítání…",
				loading: "Načítání",
				error: "Nezdařil se import geo-umístění obrázků, geo-umístění byla ignorována."
			},
			initPopup: {
				title: "Vítejte v Nástroji pro tvorbu prohlídek map",
				prevBtn: "Zpět",
				nextBtn: "Další"
			},
			initPopupHome: {
				header1: "Kde jsou vaše obrázky nebo videa?",
				header2: "Tento asistent vám pomůže vytvořit prohlídku mapy z médií, která jsou již uložena online, případně je importuje do vašeho účtu ArcGIS Online pro organizace.",
				title1: "Jsou již online",
				title2: "Potřebuji nahrát své obrázky",
				hostedFSTooltip: "Použít ArcGIS Online pro hosting vašich obrázků (nepodporuje videa)",
				hostedFsNA: "Dostupné pouze pro uživatele služby ArcGIS pro organizace v roli vydavatele nebo administrátora.",
				footer1: "Až budete hotovi, nezapomeňte prohlídku mapy sdílet se svým publikem na stránce položek aplikace.",
				footer3: "Stáhnout šablony CSV",
				footer4: "Pokud se nestáhne, zvolte možnost \"Uložit jako\".",
				footer4bis: "Pokud se stahování nespustí, použijte kliknutí pravým tlačítkem a  \"Uložit jako\"",
				footer5: "Více informací",
				footerProgress: "Probíhá vytváření",
				footerSucceed: "Úspěšně vytvořeno. Načítání..."
			},
			helpPopup: {
				title: "Nápověda",
				close: "Zavřít",
				tab1: {
					title: "Úvod",
					div1: "Ř_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._ů",
					div2: "Ř_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_ů",
					div4: "Ř_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._ů",
					div42: "Ř_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._ů",
					div5: "Ř_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._ů"
				},
				tab2: {
					title: "Data",
					div1: "Hlavním aspektem, který je třeba při vytváření prohlídky mapy zvážit, je výběr úložiště obrázků. Prohlídky map mohou využívat obrázky uložené prostřednictvím hlavních služeb pro sdílení fotografií, na libovolném webovém serveru nebo jako přílohy služeb feature service.",
					div1a: "Podrobné informace o podporovaných formátech obrázků a videa naleznete v poslední části této karty.",
					div2: "Interaktivní nástroj pro tvorbu vám dává dvě možnosti, jak v prohlídce mapy zpracovávat obrázky:",
					div3: "<ul><li>Můžete použít <b>fotografie, které již jsou online</b>, například obrázky uložené ve službě pro sdílení fotografií jako Flickr nebo obrázky uložené na vašem vlastním webu. Na URL těchto obrázků budou mířit odkazy z prohlídky mapy.</li><li>Můžete také <b>nahrávat fotografie z počítače</b> přímo do prohlídky mapy. Tato možnost pro nahrávání vyžaduje předplatné ArcGIS Online a oprávnění vydavatele nebo administrátora, protože automaticky vytvoří hostovanou službu feature service, ve které se fotografie uloží jako přílohy.</li></ul>",
					div4: "Využití se najde hlavně v těchto případech:",
					div4b: "<b>Fotografie ještě nemáte hostované</b> a máte předplatné ArcGIS Online: Využití hostované služby feature service je pro vás nejlepší možnost. Stejně jako veřejné služby pro sdílení fotografií vaše obrázky optimalizujeme, aby se rychle načítaly. Budete mít přístup ke všem možnostem administrace a správy dat platformy ArcGIS.",
					div5: "<b>Nejste členem organizace</b>: Nejprve bude nutné nahrát obrázky na web pro sdílení fotografií nebo na vlastní webový server. Nástroj pro tvorbu vám pak pomůže použít tyto obrázky, které budou dál uloženy v původním umístění.",
					div6: "<b>Chcete znovu využít stávající službu Feature Service</b>, ve které jsou obrázky uloženy jako přílohy nebo která odkazuje na externě uložené obrázky. Podrobný návod najdete v příslušné části níže.",
					div7: "<b>Využíváte předchozí verzi</b> šablony prohlídky mapy a již máte soubor CSV, který odkazuje na příslušné obrázky a miniatury. Budete moci importovat a doplnit data. Nástroj pro tvorbu podporuje pouze soubory CSV, které využívají pole zeměpisné šířky a délky. Soubory CSV využívající adresy mohou je nadále možno používat prostřednictvím webové mapy (viz příslušná část níže).",
					div8: "Import ze služeb pro online sdílení fotografií",
					div9: "Operace importu odkazuje na hostované obrázky uložením jejich adresy URL ve sbírce prvků webové mapy. Obrázky nejsou uloženy ve službě ArcGIS Online. Pokud hostované obrázky nejsou přístupné, nebudou se v prohlídce mapy zobrazovat. Místo nich se zobrazí zpráva „Obrázek není k dispozici“. V závislosti na poskytovateli služeb obrázků nemusí prohlídka mapy importovat název, popis a umístění obrázků. Tyto atributy jsou uloženy ve webové mapě a případné úpravy online služeb se v prohlídce mapy nijak neprojeví.",
					div10: "Obrázky uložené na webovém serveru",
					div11: "Rozhodnete-li se hostovat si obrázky sami, bude nutné manuálně vytvořit jejich miniatury. Použijete-li jako miniatury obrázky v plném rozlišení, výrazně tím snížíte výkon. Z tohoto důvodu důrazně doporučujeme využívat služby pro online sdílení fotografií nebo službu feature service, které to provedou za vás.",
					div12: "Využití stávající služby Feature Service nebo souboru Shapefile",
					div13: "Jako zdroj dat pro prohlídku mapy lze využít libovolnou službu feature service nebo soubor Shapefile využívající body. Bude jen třeba je přidat do webové mapy jako vrstvu prostřednictvím prohlížeče map na stránkách arcgis.com. Pokud aplikace ve vrstvě najde očekávané atributy, budou k dispozici všechny funkce nástroje pro vytváření.",
					div14: "Ř_The possible values for fields name are (case insensitive):_ů",
					div151: "Název",
					div152: "Popis",
					div153: "Obrázek",
					div154: "Miniatura",
					div155: "Ř_Color_ů ",
					div16: "Ř_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._ů",
					div162: "Při používání služby feature service, která obrázky ukládá jako přílohy, <b>budou použity pouze prvky se dvěma přílohami</b>. První příloha určuje hlavní obrázek, druhá příloha určuje miniaturu.",
					div17: "Pole obrázku a miniatury jsou povinná pro službu feature service bez příloh. Pro službu feature service s přílohami jsou volitelné (ale důrazně je doporučujeme). Pokud máte ve službě povolené přílohy, nástroj pro tvorbu vám umožní nahrávat obrázky jako přílohy. V opačném případě budete moci pouze editovat adresu URL obrázku a miniatury.",
					div172: "Pokud jsou pole obrázku a miniatury přítomna, budou vždy použita a přílohy služby feature service nebudou dotazovány.",
					div173: "Vzorové soubory CSV a shapefile můžete stáhnout z",
					div18: "Vytváření hostovaných služeb Feature Service ze souboru CSV nebo shapefile",
					div19: "Při vytváření hostovaných služeb feature service ze souboru CSV nebo shapefile nejsou přílohy ve výchozím nastavení povoleny. Chcete-li je povolit, otevřete stránku podrobností služby feature service, klikněte na malou šipku v sekci vrstev. Daná možnost se zobrazí. Prohlídka map bude nadále používat obrázky a miniatury, na které odkazujete prostřednictvím atributů. Pokud chcete obrázky nahrát jako přílohy služby feature service, budete to moci volitelně provést dvěma tlačítky na panelu obrázku (Změnit obrázek a Změnit miniaturu).",
					div20: "Podporované formáty obrázků a videí",
					div21: "Podporované formáty obrázků: <b>jpg, jpeg, png, gif a bmp</b>. Pokud multimediální soubor nekončí touto příponou, bude jej prohlídka mapy považovat za video (mimo případy, kdy je používána služba feature service, viz níže).",
					div22: "Šablona prohlídky mapy neobsahuje přehrávač videí, je nutné použít externí přehrávač videí poskytovaný některou službou pro hosting videí (najděte možnost vložení videa a zkopírujte adresu URL obsaženou v daném kódu). Chcete-li videa hostovat sami, můžete vytvořit html stránku, která obsahuje přehrávač videí jako např. <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Interaktivní nástroj pro tvorbu neobsahuje dialogové rozhraní pro přidání videa při používání služeb feature service s přílohami, ale je možné tak učinit úpravou vašich dat mimo nástroj pro tvorbu. Pokud ve webovém prohlížeči na stránkách arcgis.com upravíte pole obrázků tak, aby odkazovala na externí video, a přidáte na konec adresy URL speciální parametr (#isVideo), budou vaše média považována za video.",
					div24: "Mějte na paměti, že je stále nutné mít dvě platné přílohy s obrázky, jinak bod nebude použit. U příloh služby feature service bez polí pro obrázek a miniaturu nelze používat videa."
				},
				tab3: {
					title: "Přizpůsobení",
					div1: "Nástroj pro tvorbu nabízí několik možností přizpůsobení, které jsou dostupné po kliknutí na tlačítko NASTAVENÍ v horním panelu. Pokud nenajdete možnost, kterou očekáváte, nabízíme také verzi ke stažení, kterou můžete implementovat na svůj webový server a upravit podle svých potřeb.",
					div2: "Hostovanou verzi doporučujeme s výjimkou následujících případů:",
					div3: "<li>Nenabízí požadované přizpůsobení uživatelského rozhraní, jako je například obrázek pozadí záhlaví.</li><li>Jste vývojář a chcete si aplikaci upravit.</li>",
					div4: "Verzi ke stažení lze nakonfigurovat prostřednictvím webové mapy nebo identifikátoru aplikace webového mapování. Hlavní způsoby použití jsou:",
					div41: "Svou prohlídku mapy tvoříte pomocí interaktivního nástroje pro tvorbu v hostovaném prostředí a šablonu konfigurujete pomocí identifikátoru aplikace webového mapování. Budou použita nastavení určena interaktivním nástrojem pro tvorbu.",
					div42: "Svou prohlídku mapy tvoříte mimo interaktivní nástroj pro tvorbu a šablonu konfigurujete pomocí identifikátoru webových map. V dokumentaci se dozvíte, jak šablonu konfigurovat.",
					div43: "Mějte na paměti, že interaktivní nástroj pro tvorbu je dostupný ve stažitelné verzi. Obsahuje však některá technická omezení ohledně prohlížečů, jako je například Internet Explorer ve verzi starší než 10.",
					div5: "Ř_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._ů"
				},
				tab4: {
					title: "Tipy",
					div0: "Podporované prohlížeče",
					div0a: "Zobrazování prohlídek map je podporováno v IE8+. Interaktivní nástroj pro tvorbu je podporován v IE9+. Produkty aktivně testujeme ve všech hlavních prohlížečích, nicméně v případě potíží doporučujeme používat Chrome.",
					div0b: "Narazíte-li na jakékoli potíže, dejte nám vědět. Prozatím bude při vytváření prohlídky mapy pomocí CSV šablony minimalizována vaše interakce s rozhraním nástroje pro tvorbu.",
					div1: "Obrázky",
					div2: "Ř_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._ů",
					div2a: "Ř_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._ů",
					div3: "Formátování textu popisku značkami HTML",
					div4: "Text popisku může obsahovat značky HTML, kterými lze určit formátování a odkazy. Tento kód například přidá žlutý odkaz:",
					div4a: "Ř_Write a good subtitle for your tour_ů",
					div4b: "Ř_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._ů",
					div5: "Podpůrné vrstvy",
					div6: "Do mapy můžete přidávat dodatečné podpůrné vrstvy, které slouží k přidání kontextu pro prohlídku mapy. Tyto vrstvy mohou obsahovat další geografické prvky, které chcete zobrazovat v mapě navíc k bodům prohlídky mapy, jako jsou naučné oblasti, pěší či automobilovou trasu po bodech prohlídky atd. Šablona zobrazuje tyto dodatečné podpůrné vrstvy s využitím symbolů, které určíte ve webové mapě. Vyskakovací okna však nejsou dostupná.",
					div7: "Prohlídka by měla být krátká a poutavá",
					div8: "Prohlídka může obsahovat nejvýše 99 bodů. Většina prohlídek bude ale samozřejmě výrazně kratší. Předpokládejte, že publikum nemá zájem procházet příliš mnoho bodů. Vám možná téma připadá fascinující, ale to nemusí automaticky platit pro všechny.",
					div9: "Další informace najdete v <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>podrobném průvodci</a>.",
					div10: "Režim vkládání",
					div11: "Chcete-li vložit šablonu do jiné webové stránky pomocí iframe, přidáním volitelného parametru \"&embed\" na konec adresy URL odstraníte záhlaví. Ve verzi ke stažení lze tento režim nastavit také konfiguračním souborem.",
					div12: "Ř_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._ů" 
				},
				tab5: {
					title: "Publikování",
					div1: "Ř_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._ů",
					div2a: "Ř_Sharing the Tour through the builder_ů",
					div2b: "Ř_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._ů",
					div2c: "Ř_Sharing the Tour through ArcGIS Online_ů",
					div2d: "Ř_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._ů",
					div3t: "Ř_Feature Service security_ů",
					div3a: "Pokud používáte hostovanou službu feature service vytvořenou nástrojem pro tvorbu prohlídek map, bude za vás aplikace spravovat zabezpečení služby. Zůstanete jediným uživatelem s oprávněním k editaci, i kdy budete službu sdílet veřejně.",
					div3t2: "Ř_Before sharing your Tour with your audience_ů",
					div3: "Ř_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._ů",
					div4: "Ř_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._ů",
					div5a: "Ř_Recommendation for search_ů",
					div5b: "Ř_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._ů"
				}
			},
			share: {
				firstSaveTitle: "Prohlídka byla úspěšně uložena",
				firstSaveHeader: "Ř_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._ů",
				firstSaveA1: "Pokud nejste obeznámeni s ArcGIS Online nebo chcete zkratku pro přístup do autorského rozhraní, můžete si uložit následující odkaz: %LINK1%",
				firstSaveA1bis: "Ř_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._ů",
				firstSaveQ2: "Je má prohlídka sdílená?",
				firstSaveA2: "Ř_Currently your Tour is not shared. To share it, use the SHARE button._ů",
				shareTitle: "Sdílet vaši prohlídku",
				sharePrivateHeader: "Vaše prohlídka není sdílená, chcete ji sdílet?",
				sharePrivateBtn1: "Sdílet veřejně",
				sharePrivateBtn2: "Sdílet s mou organizací",
				sharePrivateProgress: "Probíhá sdílení…",
				sharePrivateErr: "Sdílení selhalo, zkuste to znovu nebo",
				sharePrivateOk: "Sdílení bylo úspěšně aktualizováno, probíhá nahrávání…",
				sharePreviewAsUser: "Náhled",
				shareHeader1: "Vaše prohlídka je <strong>veřejně přístupná</strong>.",
				shareHeader2: "Vaše prohlídka je přístupná členům vaší organizace (je vyžadováno přihlášení).",
				shareLinkHeader: "Sdílejte prohlídku se svým publikem",
				shareLinkOpen: "OTEVŘENO",
				shareQ1Opt1: "Jak ponechám prohlídku soukromou?",
				shareQ1Opt2: "Ř_How do I keep the Tour private or share it publicly?_ů",
				shareA1: "Ř_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._ů",
				shareA1bis: "Ř_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._ů",
				shareQ2: "Ř_How do I edit the Tour later?_ů",
				shareQ2bis: "Ř_How do I get back to the authoring interface?_ů",
				shareA2div1: "Ř_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._ů",
				shareA2div2: "Když jste přihlášeni na webu ArcGIS.com jako majitel aplikace, tak aplikace obsahuje tlačítko pro otevření interaktivního nástroje pro tvorbu:",				
				shareQ3: "Kde jsou uložena data?",
				shareA3: "Nastavení prohlídky je uloženo v <a href='%LINK1%' target='_blank'>této položce webové mapy</a> a <a href='%LINK2%' target='_blank'>této položce webové aplikace</a>. Pokud jste použili import z Flickru, Picasa, Facebooku nebo YouTube, zůstávají vaše obrázky a videa uloženy tam a nejsou duplikovány v ArcGIS Online."
			}
        }
    })
);
