define(
({
		viewer: {
			loading: {
				step1: "á»‡_LOADING APPLICATION_á»",
				step2: "á»‡_LOADING DATA_á»",
				step3: "á»‡_INITIALIZING THE TOUR_á»",
				loadBuilder: "á»‡_SWITCHING TO BUILDER MODE_á»",
				redirectSignIn: "á»‡_REDIRECTING TO SIGN-IN PAGE_á»",
				redirectSignIn2: "á»‡_(you will be redirected here after sign-in)_á»",
				fail: "á»‡_Sorry, Map Tour loading failed_á»",
				failButton: "á»‡_Retry_á»"
			},
			errors: {
				boxTitle: "á»‡_An error has occurred_á»",
				portalSelf: "á»‡_Fatal error: Failed to get portal configuration_á»",
				invalidConfig: "á»‡_Fatal error: Invalid configuration_á»",
				invalidConfigOwner: "á»‡_Fatal error: Invalid configuration (authorized owner required)_á»",
				invalidConfigNoWebmap: "á»‡_Fatal error: Invalid configuration (web map or application identifier not specified in index.html)_á»",
				createMap: "á»‡_Unable to create map_á»",
				invalidApp: "á»‡_Fatal error: The application cannot be loaded_á»",
				noLayer: "á»‡_The web map does not contain a valid data layer for Map Tour_á».",
				noLayerMobile: "á»‡_Welcome to the Map Tour web application. The application is not configured. The Map Tour builder is not supported on mobile devices_á».",
				noLayerView: "á»‡_Welcome to the Map Tour web application.<br />The application is not configured yet_á».",
				appSave: "á»‡_Error saving the web application_á»",
				mapSave: "á»‡_Error saving the web map_á»",
				featureServiceLoad: "á»‡_Error loading feature service_á»",
				notAuthorized: "á»‡_You are not authorized to access this application_á»",
				oldBrowserTitle: "á»‡_Browser not fully supported_á»",
				noBuilderIE8: "á»‡_The Map Tour builder is not supported on Internet Explorer before version 9_á».",
				ie10Win7Explain: "á»‡_The Map Tour interactive builder is not supported on Internet Explorer 10 on Windows 7 when the data source is a Feature Service with attachments. To use a Feature Service with attachments, you have to <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manually force document mode to Internet Explorer 9 standards</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgrade to Internet Explorer 9</a> or upgrade to Windows 8_á».",
				oldBrowserExplain: "á»‡_This browser doesn't support automatic thumbnail generation from the images you upload into your map tour. You can create a map tour using this browser, but you will have to provide a separate thumbnail image for each of the images you upload_á».",
				oldBrowserExplain2: "á»‡_To improve your experience, <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activate Google Chrome Frame for Internet Explorer</a>_á».",
				oldBrowserExplain3: "á»‡_The Map Tour builder doesn't work with Internet Explorer 10 on Windows XP_á».",
				oldBrowserClose: "á»‡_Close_á»"
			},
			mobileHTML: {
				showIntro: "á»‡_SHOW TITLE_á»",
				hideIntro: "á»‡_HIDE TITLE_á»",
				navList: "á»‡_List_á»",
				navMap: "á»‡_Map_á»",
				navInfo: "á»‡_Media_á»",
				introStartBtn: "á»‡_Start_á»"
			},
			desktopHTML: {
				storymapsText: "á»‡_A story map_á»",
				builderButton: "á»‡_Switch to builder mode_á»",
				bitlyTooltip: "á»‡_Get a short link to the application_á»",
				bitlyStartIndex: "á»‡_Link to current place_á»"
			},
			builderHTML: {
				panelHeader: "á»‡_APPLICATION CONFIGURATION_á»",
				buttonSave: "á»‡_SAVE_á»",
				buttonSettings: "á»‡_Settings_á»",
				buttonShare: "á»‡_Share_á»",
				buttonView: "á»‡_View mode_á»",
				buttonItem: "á»‡_Open the Web Application item_á»",
				buttonHelp: "á»‡_Help_á»",
				buttonOrganize: "á»‡_Organize_á»",
				buttonAdd: "á»‡_Add_á»",
				buttonImport: "á»‡_Import_á»",
				buttonImportDisabled: "á»‡_Import is not available when using a Feature Service with attachments_á»",
				dataEditionDisabled: "á»‡_Data edition is disabled on CSV data source_á»",
				dataSourceWarning: "á»‡_The Map Tour data layer has changed. If the features ID are not the same, you have to reset the order and hidden points through <b>Organize</b>. If the fields name differs, you have to reset the fields settings under the <b>data tab in Settings</b>_á».",
				organizeWarning: "á»‡_One or multiple points added outside of the interactive builder are hidden_á».",
				dataPicError0a: "á»‡_This tour includes <b>%NB%</b> non-compliant picture URLs_á».",
				dataPicError0b: "á»‡_This tour may includes <b>%NB%</b> non-compliant picture URLs_á».",
				dataPicError1: "á»‡_Map Tour now requires that a picture URL end with one of the following extension: .jp(e)g, .png, .gif or .bmp_á».",
				dataPicError2: "á»‡_This requirement will not affect your existing published Map Tour. However, in order to use the interactive builder, you must first resolve the URL issue by performing one of two actions_á»:",
				dataPicError3: "á»‡_Edit URLs_á»",
				dataPicError4: "á»‡_This will add <i>#isImage</i> to the end of unsupported picture URLs. Most server support URL appendages. However, once you have performed that action, you should verify that the updated picture URLs are functional by navigating through your points. If each pictures loads, you can now save the Map Tour. If <b>pictures are broken, don’t save the Map Tour</b>. Instead, reload the builder and perform the second action_á».",
				dataPicError5: "á»‡_Limit the tour to pictures_á»",
				dataPicError6: "á»‡_This option cause all URLs to be considered images, but you won't be able to add videos using the interactive builder. This action is reversible, should you decide to add video in the future_á».",
				dataPicError7: "á»‡_Your Map Tour has been restricted to pictures, videos can't be used. If you choose to remove that limitation, check that your pictures still loads correctly before saving the Map Tour. You will be able to restore that limitation later if needed_á».",
				dataPicError8: "á»‡_Remove picture limitation_á»",
				dataPicError9: "á»‡_If these URLs points to videos you can ignore this warning, if they point to image, you need to perform one of the following two actions_á»:",
				modalCancel: "á»‡_Cancel_á»",
				modalApply: "á»‡_Apply_á»",
				organizeHeader: "á»‡_Organize the tour_á»",
				organizeGeneralCaption: "á»‡_Use drag and drop to sort tour points_á»",
				organizeDelete: "á»‡_Delete_á»",
				organizeHide: "á»‡_Hide_á»",
				organizeReset: "á»‡_Reset order and hidden points_á»",
				addMaxPointReached: "á»‡_You have reached the maximum number of points authorized by the icons set and cannot add another tour point.<br /><br />Note that if you delete existing points, you will need to reload the application_á».",
				addMaxPointReachedMobile: "á»‡_Sorry, you have reached the maximum number of authorized points and cannot add that picture_á».",
				addClose: "á»‡_Close_á»",
				addHeader: "á»‡_Add a new tour point_á»",
				addTabPicture: "á»‡_Media_á»",
				addTabInformation: "á»‡_Information_á»",
				addTabLocation: "á»‡_Location_á»",
				addSelectCaption: "á»‡_Select or drop picture_á»",
				addNoteVideo: "á»‡_Consult Help for instructions on using videos_á»",		
				addSelectCaptionNoFileReader: "á»‡_Select picture_á»",	
				addChangePhoto: "á»‡_Change picture and thumbnail_á»",
				addPictureResolutionIntro: "á»‡_The picture resolution is higher than required_á»:",
				addPictureResolutionOldBrowser: "á»‡_The picture resolution is higher than required. Optimize the Map Tour experience by specifying a resolution lower than %RECOMMENDED_RES%_á».",
				addPictureResolutionResize: "á»‡_Change picture resolution to %RESOLUTION%_á»",
				addPictureResolutionKeep: "á»‡_Keep the original resolution of %RESOLUTION%_á»",
				addSelectThumbnail: "á»‡_Select thumbnail_á»",
				addNoThumbSelected: "á»‡_No thumbnail selected_á»",
				addThumbSelected: "á»‡_Selected_á»",
				addCameraSettingsHeader: "á»‡_CAMERA SETTINGS_á»",
				addThumbnailHeader: "á»‡_THUMBNAIL_á»",
				addLabelPicUrl: "á»‡_Picture_á»",
				addLabelThumbUrl: "á»‡_Thumbnail_á»",
				addTextPlaceholderUrl: "á»‡_Enter an image URL_á»",
				addTextPlaceholderUrl2: "á»‡_Enter a Youtube page URL_á»",
				addTextPlaceholderUrl3: "á»‡_Enter a Vimeo page URL_á»",
				addTextPlaceholderUrl4: "á»‡_Enter a video embed URL_á»",
				addLabelVideo: "á»‡_Video_á»",
				addMediaVideoOther: "á»‡_Other_á»",
				addMediaVideoHelp: "á»‡_Check the URL and get the default thumbnail_á»",
				addMediaVideoHelpTooltip1: "á»‡_Check succeeded_á»",
				addMediaVideoHelpTooltip2: "á»‡_Check failed_á»",
				addMediaVideoHelpTooltip4: "á»‡_Find the option to embed the video and copy the video URL that is present in the code_á»",
				addLabelName: "á»‡_Name_á»",
				addLabelDescription: "á»‡_Caption_á»",
				addTextPlaceholder: "á»‡_Type something_á»",
				addLocatePlaceholder: "á»‡_Locate an address or a place_á»",
				addPinColor: "á»‡_Color_á»",
				addLatitude: "á»‡_Latitude_á»",
				addLongitude: "á»‡_Longitude_á»",
				addLatitudePlaceholder: "á»‡_e.g. 34.056_á»",
				addLongitudePlaceholder: "á»‡_e.g. -117.195_á»",
				addUploading: "á»‡_Uploading tour point_á»",
				addSave: "á»‡_Add tour point_á»",
				addMobileUploading: "á»‡_Uploading picture_á»",
				addMobileName: "á»‡_Enter a name_á»",
				addMobileNameMandatory: "á»‡_Error, please enter a name_á».",
				addMobileError: "á»‡_Sorry, something has gone wrong_á»",
				settingsHeader: "á»‡_Application settings_á»",
				settingsTabLayout: "á»‡_Layout_á»",
				settingsTabColor: "á»‡_Colors_á»",
				settingsTabLogo: "á»‡_Header_á»",
				settingsTabFields: "á»‡_Data_á»",
				settingsTabExtent: "á»‡_Extent_á»",
				settingsTabZoom: "á»‡_Zoom Level_á»",
				settingsLayoutExplain: "á»‡_Select the application layout you want_á».",
				settingsLayoutProfessional: "á»‡_Three-panel Layout_á»",
				settingsLayoutModern: "á»‡_Integrated Layout_á»",
				settingsLayoutSelected: "á»‡_Selected layout_á»",
				settingsLayoutSelect: "á»‡_Select this layout_á»",
				settingsLayoutNote: "á»‡_Note that on points using videos, the placard will always be placed under the video even if that option is unchecked_á».",
				settingsLayoutLocBtn: "á»‡_Display a 'Locate' button_á»",
				settingsLayoutLocBtnHelp: "á»‡_That functionality is supported on most mobile device and desktop browsers (Internet Explorer 9)_á».",
				settingsColorExplain: "á»‡_Change appearance by choosing a pre-defined theme, or create your own_á».",
				settingsLabelColor: "á»‡_Header, content and footer colors_á»",
				settingsLogoExplain: "á»‡_Customize the header logo (maximum is 250 x 50px)_á».",
				settingsLogoEsri: "á»‡_Esri logo_á»",
				settingsLogoNone: "á»‡_No logo_á»",
				settingsLogoCustom: "á»‡_Custom logo_á»",
				settingsLogoCustomPlaceholder: "á»‡_Image URL_á»",
				settingsLogoCustomTargetPlaceholder: "á»‡_Click-through link_á»",
				settingsLogoSocialExplain: "á»‡_Customize the header top right link_á».",
				settingsLogoSocialText: "á»‡_Text_á»",
				settingsLogoSocialLink: "á»‡_Link_á»",
				settingsLogoSocialDisabled: "á»‡_This feature has been disabled by the Administrator_á»",
				settingsDataFieldsExplain: "á»‡_Select photo name, caption and color fields_á».",
				settingsDataFieldsError: "á»‡_The application cannot determine the appropriate name, caption or color data. Please select the fields to be used here. These settings can be changed at a later time_á».",
				settingsFieldsLabelName: "á»‡_Name_á»",
				settingsFieldsLabelDescription: "á»‡_Caption_á»",
				settingsFieldsLabelColor: "á»‡_Color_á»",
				settingsFieldsReset: "á»‡_Reset fields selection_á»",
				settingsExtentExplain: "á»‡_Set the Map Tour initial extent through the interactive map below_á».",
				settingsExtentExplainBottom: "á»‡_The extent you define will modify your web map initial extent. Note that this extent isn't used if it doesn't include the first tour point. In that case the tour will open centered on the first point_á».",
				settingsExtentDateLineError: "á»‡_The extent cannot be across the meridian of 180° longitude_á»",
				settingsExtentDateLineError2: "á»‡_Error computing the extent_á»",
				settingsExtentDrawBtn: "á»‡_Draw a new extent_á»",
				settingsExtentModifyBtn: "á»‡_Edit the extent_á»",
				settingsExtentApplyBtn: "á»‡_Preview on Map Tour_á»",
				settingsExtentUseMainMap: "á»‡_Use Map Tour extent_á»",
				settingsZoomExplain: "á»‡_Set zoom for story points following introduction (optional)_á».",
				settingsLabelZoom: "á»‡_Scale/level_á»",
				settingsZoomFirstValue: "á»‡_None_á»",
				settingsFieldError: "á»‡_Please select a field in each list_á»",
				dataTitle: "á»‡_ArcGIS Online hosting_á»",
				dataExplain: "á»‡_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges_á».",
				dataNameLbl: "á»‡_Service name_á»",
				dataFolderListLbl: "á»‡_Folder_á»",
				dataFolderListFetching: "á»‡_Fetching folders_á» ...",
				dataRootFolder: "á»‡_Root_á»",
				dataNameError: "á»‡_Enter a name for the feature service_á»",
				dataFolderError: "á»‡_Select a valid folder_á»",
				dataSrcContainsInvalidChar: "á»‡_The feature service name contains one or more invalid characters (-, <, >, #, %, :, \", ?, &, +, /, or \)_á».",
				dataSrvAlreadyExistsError: "á»‡_A service with that name already exists within the organization. Please choose a different name_á».",
				dataBtnSave: "á»‡_Create the service_á»",
				dataFooterProgress: "á»‡_Creation in progress_á»",
				dataFooterSucceed: "á»‡_Creation succeeded. Loading_á»",
				dataFooterError: "á»‡_Creation failed. Please try again_á»",
				tabError: "á»‡_Please check for errors in all tabs_á»",
				introRecordBtn: "á»‡_Intro_á»",
				introRecordActivate: "á»‡_Use the first point as introduction (does not appear in carousel)_á»"
			},
			addPopupJS: {
				uploadingPicture: "á»‡_Uploading picture_á»",
				uploadSuccess: "á»‡_Upload successful_á»",
				uploadError: "á»‡_Error uploading the picture_á»",
				uploadError2: "á»‡_Error adding the feature (invalid html tag)_á»",
				notJpg: "á»‡_Please choose a jpeg photo to upload_á»",
				errorNoPhoto: "á»‡_Choose an image to upload_á»",
				errorNoThumbnail: "á»‡_Choose a thumbnail to upload_á»",
				errorInvalidPicUrl: "á»‡_Enter a valid picture (starts with http(s)://, ends with jpg, png, gif or bmp). You can end the URL with '#isImage' to override that rule_á».",
				errorInvalidThumbUrl: "á»‡_Enter a valid thumbnail (starts with http(s)://, ends with jpg, png, gif or bmp)_á».",
				errorInvalidVideoUrl: "á»‡_Enter a valid video URL (starts with http(s)://)_á»",
				errorNoName: "á»‡_Enter a name for this tour point_á»",
				errorNoDescription: "á»‡_Enter a caption for this tour point_á»",
				errorNoLocation: "á»‡_Set a location for this tour point_á»"
			},
			builderJS: {
				noPendingChange: "á»‡_No unsaved change_á»",
				unSavedChangeSingular: "á»‡_1 unsaved change_á»",
				unSavedChangePlural: "á»‡_unsaved changes_á»",
				shareStatus1: "á»‡_Tour is not saved_á»",
				shareStatus2: "á»‡_Tour is shared publicly_á»",
				shareStatus3: "á»‡_Tour is shared within the organization_á»",
				shareStatus4: "á»‡_Tour is not shared_á»",
				popoverDiscard: "á»‡_Are you sure to want to discard any unsaved changes_á»?",
				yes: "á»‡_Yes_á»",
				no: "á»‡_No_á»",
				popoverLoseSave: "á»‡_By opening the viewer, you will lose any unsaved changes_á»",
				ok: "á»‡_Ok_á»",
				popoverSaveWhenDone: "á»‡_Don't forget to save when you are done_á»",
				closeWithPendingChange: "á»‡_Are you sure to want to confirm the action ? Your changes will be lost_á».",
				gotIt: "á»‡_Ok_á»",
				savingApplication: "á»‡_Saving application_á»",
				saveSuccess: "á»‡_Application saved successfully_á»",
				saveError: "á»‡_Save failed, please try again_á»",
				saveError2: "á»‡_Save failed due to an invalid html tag in a name or description_á»",
				saveError3: "á»‡_The title can't be empty_á»",
				dragColorPicker: "á»‡_Move me around<br />or change my color_á»",
				dataWarningExtent: "á»‡_You have data outside of the web map extent. Those data won't be used as tour points, change map extent if you want to use them_á».",
				dataWarningVisibi: "á»‡_Your Map Tour layer is not visible at the current web map extent. Confirm your Map Tour layer is visible with a %MAPSIZE% large map_á».",
				dataWarningEdit: "á»‡_Edit web map_á»",
				dataWarningClose: "á»‡_Close_á»",
				signIn: "á»‡_Please sign in with an account on_á»",
				signInTwo: "á»‡_to save the application_á».",
				switchBM: "á»‡_Change Basemap_á»"
			},
			organizePopupJS: {
				messageStart: "á»‡_You have chosen to delete_á»",
				messageSinglePoint: "á»‡_one tour point_á»",
				messageMultiPoint: "á»‡_tour points_á»",
				messagePermantRemove: "á»‡_This will permanently remove the_á»",
				messageRecord: "á»‡_record_á»",
				messageRecordPlural: "á»‡_records_á»",
				messageConfirm: "á»‡_from your database. Do you want to continue_á»?",
				labelButtonShow: "á»‡_Show_á»",
				labelButtonHide: "á»‡_Hide_á»"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "á»‡_This will permanently delete the picture and thumbnail_á»",
				popoverDeleteWarningThumb: "á»‡_This will permanently delete the thumbnail_á»",
				popoverUploadingPhoto: "á»‡_Uploading picture and thumbnail_á»",
				popoverUploadingThumbnail: "á»‡_Uploading thumbnail_á»",
				popoverUploadSuccessful: "á»‡_Upload successful_á»",
				popoverUploadError: "á»‡_Upload failed, please try again_á»",
				changePicAndThumb: "á»‡_Change picture_á»",
				changeThumb: "á»‡_Change thumbnail_á»",
				selectPic: "á»‡_Change media_á»",
				selectThumb: "á»‡_Change thumbnail_á»",
				uploadPicAndThumb: "á»‡_Apply_á»"
			},
			headerJS:{
				editMe: "á»‡_Edit me_á» !",
				templateTitle: "á»‡_Set template title_á»",
				templateSubtitle: "á»‡_Set template subtitle_á»"
			},
			crossFaderJS:{
				setPicture: "á»‡_Set picture title_á»",
				setCaption: "á»‡_Set picture caption_á»"
			},
			importPopup: {
				title: "á»‡_Import_á»",
				prevBtn: "á»‡_Back_á»",
				nextBtn: "á»‡_Next_á»"
			},
			importPopupHome: {
				header: "á»‡_Where are your pictures stored_á» ?"
			},
			onlinePhotoSharingCommon: {
				pictures: "á»‡_pictures_á»",
				videos: "á»‡_videos_á»",
				disabled: "á»‡_This feature has been disabled by the Administrator_á»",
				disabledPortal: "á»‡_This feature is disabled on Portal for ArcGIS_á»",
				header1: "á»‡_Your pictures must be shared publicly_á».",
				header2: "á»‡_The import will be limited to the first %NB1% %MEDIA%_á».",
				emptyDataset: "á»‡_Error, no pictures found_á»",
				footerImport: "á»‡_Import_á»",
				selectAlbum: "á»‡_Select a public album_á»",
				selectAlbum2: "á»‡_Select an album_á»",
				pleaseChoose: "á»‡_Please Choose_á»",
				userLookup: "á»‡_Look up_á»",
				userLookingup: "á»‡_Looking up_á»",
				csv: "á»‡_Referenced in a CSV_á»",
				advanced: "á»‡_Advanced options_á»",
				advancedScratchLbl: "á»‡_Start a new Tour_á»",
				advancedScratchTip: "á»‡_Create an empty Tour that you will be able populate manually using a wizard_á».",
				advancedCSVLbl: "á»‡_Import Tour data from a CSV file_á»",
				advancedCSVTip: "á»‡_Import your Tour content from a CSV file_á».",
				advancedCommonTip: "á»‡_It requires that your images and videos are already online_á».",
				select: "á»‡_Make a selection_á»",
				locUse: "á»‡_Use pictures geolocation_á»",
				locExplain: "á»‡_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location_á».",
				locExplain2: "á»‡_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location_á»."
			},
			viewFlickr: {
				title: "á»‡_Flickr import_á»",
				header: "á»‡_Enter your Flickr user name and select a Photo Set or a Tag to be imported_á».",
				userInputLbl: "á»‡_Enter a User Name_á»",
				signInMsg2: "á»‡_User not found_á»",
				selectSet: "á»‡_Select a Photo Set_á»",
				selectTag: "á»‡_or Select a Tag_á»",
				footerImportTag: "á»‡_Import the selected Tag_á»",
				footerImportSet: "á»‡_Import the selected Set_á»"
			},
			viewFacebook: {
				title: "á»‡_Facebook import_á»",
				header: "á»‡_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private_á».",
				leftHeader: "á»‡_Facebook User_á»",
				rightHeader: "á»‡_Facebook Page_á»",
				pageExplain: "á»‡_A Facebook page is a public brand/product or celebrity like <b>esrigis</b>. You can get the page name after the first '/' in the page URL_á».",
				pageInputLbl: "á»‡_Enter a page name_á»",
				lookupMsgError: "á»‡_Page not found_á»"
			},
			viewPicasa: {
				title: "á»‡_Picasa/Google+ import_á»",
				header: "á»‡_Enter your email address or the ID of your Picasa or Google+ account_á».",
				userInputLbl: "á»‡_Enter an email or ID_á»",
				signInMsg2: "á»‡_Account not found_á»",
				signInMsg3: "á»‡_No public album_á»",
				howToFind: "á»‡_How to find a Picasa or Google+ account ID_á»",
				howToFind2: "á»‡_Copy digits between the first and second '/' of any Picasa or G+ page_á»"
			},
			viewCSV: {
				title: "á»‡_CSV import_á»",
				uploadBtn: "á»‡_Select or drop a CSV file_á»",
				resultHeaderEmpty: "á»‡_The CSV is empty_á»",
				resultHeaderSuccess: "á»‡_Successfully loaded %NB_POINTS% points_á»",
				resultHasBeenLimited: "á»‡_The import has been limited to the first %VAL1% points out of %VAL2% to respect the limit of %VAL3% points per tour_á»",
				browserSupport: "á»‡_Your browser isn't supported, to use a CSV you have to <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or use ArcGIS.com web map viewer (see Help)_á».",
				errorLatLng: "á»‡_Latitude and Longitude fields haven't been found. Possible values for latitude are: <i>%LAT%</i> and for longitude: <i>%LONG%</i>_á».",
				errorFieldsExplain: "á»‡_The loading failed as the following required fields hasn't been found_á»",
				errorFieldsName: "á»‡_<b>Name</b> possible values are: %VAL%_á»",
				errorFieldsDesc: "á»‡_<b>Description</b> possible values are: %VAL%_á»",
				errorFieldsUrl: "á»‡_<b>Picture URL</b> possible values are: %VAL%_á»",
				errorFieldsThumb: "á»‡_<b>Thumbnail URL</b> possible values are: %VAL%_á»",
				errorFields2Explain: "á»‡_The loading failed as the CSV does not use the same attributes than the layer for the following attributes_á»",
				errorFields2Name: "á»‡_<b>Name</b> use %VAL1% instead of %VAL2%_á»",
				errorFields2Desc: "á»‡_<b>Description</b> use %VAL1% instead of %VAL2%_á»",
				errorFields2Url: "á»‡_<b>Picture URL</b> use %VAL1% instead of %VAL2%_á»",
				errorFields2Thumb: "á»‡_<b>Thumbnail URL</b> use %VAL1% instead of %VAL2%_á»",
				resultFieldsAll: "á»‡_All attributes have been imported_á»",
				resultFieldsNotAll: "á»‡_The following attributes haven't been imported because they don't exists in the map layer_á»",
				resultFieldsNotAll2: "á»‡_The following attributes have been imported_á»",
				footerNextBtnResult: "á»‡_Import into the web map_á»",
				footerProgress: "á»‡_Import in progress_á»",
				footerSucceed: "á»‡_Import succeeded. Loading_á»"
			},
			viewYoutube: {
				title: "á»‡_Youtube import_á»",
				header: "á»‡_Enter a YouTube user name to find publicly shared videos_á».",
				pageInputLbl: "á»‡_Enter a Youtube user name_á»",
				lookupMsgError: "á»‡_User not found_á»",
				howToFind: "á»‡_How to find a Youtube user name_á»",
				howToFind2: "á»‡_User name is displayed under videos_á»",
				found: "á»‡_Found_á»",
				noData: "á»‡_No public videos found_á»"
			},
			viewGeoTag: {
				title: "á»‡_Select and locate your images/videos_á»",
				header: "á»‡_Click or tap the pictures you want to import to locate them_á».",
				headerMore: "á»‡_Why aren't my images/videos geolocated_á»?",
				headerExplain: "á»‡_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location_á».",
				leftPanelTab1: "á»‡_To locate_á»",
				leftPanelTab2: "á»‡_Located_á»",
				clickOrTap: "á»‡_Click or tap the Map to locate_á»",
				clearLoc: "á»‡_Clear locations_á»",
				clickDrop: "á»‡_Do not import_á»",
				footerImport: "á»‡_Import_á»",
				footerProgress: "á»‡_Import in progress_á»",
				footerSucceed: "á»‡_Import succeeded. Loading_á»...",
				loading: "á»‡_Loading_á»",
				error: "á»‡_Pictures geolocation import failed, geolocations have been ignored_á»."
			},
			initPopup: {
				title: "á»‡_Welcome to the Map Tour Builder_á»",
				prevBtn: "á»‡_Back_á»",
				nextBtn: "á»‡_Next_á»"
			},
			initPopupHome: {
				header1: "á»‡_Where are your images or videos_á»?",
				header2: "á»‡_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account_á».",
				title1: "á»‡_They are already online_á»",
				title2: "á»‡_I need to upload my images_á»",
				hostedFSTooltip: "á»‡_Use ArcGIS Online to host your images (doesn't support videos)_á».",
				hostedFsNA: "á»‡_Only available for ArcGIS for Organizations Publisher and Administrator users_á»",
				footer1: "á»‡_When you are done, don't forget to share your Map Tour with your audience through the application item page_á».",
				footer3: "á»‡_Download the CSV template_á»",
				footer4: "á»‡_\"Save as\" if it doesn't download_á»",
				footer4bis: "á»‡_Use right click and \"Save as\" if download doesn't start_á»",
				footer5: "á»‡_Learn more_á»",
				footerProgress: "á»‡_Creation in progress_á»",
				footerSucceed: "á»‡_Creation succeeded. Loading_á»..."
			},
			helpPopup: {
				title: "á»‡_Help_á»",
				close: "á»‡_Close_á»",
				tab1: {
					title: "á»‡_Introduction_á»",
					div1: "á»‡_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell_á».",
					div2: "á»‡_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create_á»:",
					div4: "á»‡_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>_á».",
					div42: "á»‡_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.arcgis.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>_á».",
					div5: "á»‡_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>_á»."
				},
				tab2: {
					title: "á»‡_Data_á»",
					div1: "á»‡_The main element to consider when building a Map Tour is to choose where your pictures will be stored. A Map Tour can use pictures stored on major photo sharing services, on any web server, or as attachments to a feature service_á».",
					div1a: "á»‡_See the last section of this tab for details about supported picture formats and videos_á».",
					div2: "á»‡_The interactive builder gives you two options for handling the images in your Map Tour_á»:",
					div3: "á»‡_<ul><li>You can use <b>photos that are already online</b>, such as images stored in a photo sharing site like Flickr, or images stored on your own website. These images will be referenced in your Map Tour via their URLs.</li><li>You can also <b>upload photos from your computer</b> directly into your Map Tour. This upload option requires that you have an ArcGIS for Organizations account and that you have Publisher or Administrator privileges, because a hosted feature service is automatically created for you in which your photos are stored as attachments.</li></ul>_á»",
					div4: "á»‡_The main use cases are_á»:",
					div4b: "á»‡_<b>Your photos are not hosted</b> yet and you have an ArcGIS for Organizations account: Using a hosted feature service is your best choice. Like public photo sharing services, we will optimize your pictures to create fast-loading images and you will have access to all administration and data management capabilities of the ArcGIS platform_á».",
					div5: "á»‡_<b>You aren't a member of an Organization</b>: You first have to upload your pictures to a photo sharing website or to your own web server. The builder will help you use these pictures that will continue to be hosted at their original location_á».",
					div6: "á»‡_<b>You are looking to reuse an existing Feature Service</b> that stores your pictures as attachments or that references external pictures: See the detailed section below_á».",
					div7: "á»‡_<b>You are a user of a previous version</b> of the Map Tour template and already have your CSV that references your pictures and thumbnails: You will be able to import it and refine your data. The builder only supports CSVs that use lat/long fields; address-based CSVs can continue to be used through your web map (see section below)_á».",
					div8: "á»‡_Importing from online photo sharing services_á»",
					div9: "á»‡_The import operation references pictures that are already hosted by storing their URLs in a web map feature collection. The pictures are not stored in ArcGIS Online. If the hosted pictures can't be accessed, they won't be available in the Map Tour and you'll see a 'Picture not available' image. Depending on your photo service provider, the Map Tour may not import the name, description, and location of the pictures. Those attributes are stored in the web map and any edits to the online services won't be reflected in the Map Tour_á».",
					div10: "á»‡_Storing the pictures on a web server_á»",
					div11: "á»‡_If you choose to host the pictures yourself, you will have to manually create thumbnails of your pictures. Using the full resolution pictures for the thumbnail will result in poor performance. For that reason, we strongly recommend that you use an online photo sharing services or a feature service that will do that for you_á».",
					div12: "á»‡_Using an existing Feature Service or Shapefile_á»",
					div13: "á»‡_Any point feature service or shapefile can be used as a Map Tour data source. You just have to add it as a layer into your web map through the arcgis.com Map Viewer. If the application finds the expected attributes in your layer, all builder functionalities will be available_á».",
					div14: "á»‡_The possible values for fields name are (case insensitive)_á»:",
					div151: "á»‡_Name_á»",
					div152: "á»‡_Description_á»",
					div153: "á»‡_Picture_á»",
					div154: "á»‡_Thumbnail_á»",
					div155: "á»‡_Color_á» ",
					div16: "á»‡_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work_á».",
					div162: "á»‡_When using a feature service that stores the pictures as attachments, <b>only the features with two attachments will be used</b>. The first attachment defines the main picture, and the second attachment defines the thumbnail_á».",
					div17: "á»‡_The picture and thumbnail fields are mandatory for feature services without attachments and optional (but strongly recommended) for feature services with attachments. If your service has attachments enabled, the builder will let you upload pictures as attachments. If not, you will only be able to edit the picture and thumbnail URLs_á».",
					div172: "á»‡_When present, the picture and thumbnail fields will always be used and the feature service attachments won't be queried_á».",
					div173: "á»‡_Example CSVs and shapefiles can be downloaded from_á»",
					div18: "á»‡_Creating a hosted Feature Services from a CSV or shapefile_á»",
					div19: "á»‡_When you create a hosted feature service from a CSV or shapefile, the attachments are not enabled by default. To enable them, open the feature service’s details page, click the small arrow on the layer section, and you will see that option. The Map Tour will continue to use the pictures and thumbnail you have referenced through attributes. Optionally, if you want to upload your pictures as feature service attachments, you will be able to do so through two buttons on the picture panel (\"Change Picture\" and \"Change Thumbnail\")_á».",
					div20: "á»‡_Supported pictures formats and videos_á»",
					div21: "á»‡_Supported picture format are: <b>.jpg, .jpeg, .png, .gif and .bmp</b>. If your media doesn’t end with that extension, the Map Tour will consider it to be a video, except when using a feature service (see below)_á».",
					div22: "á»‡_The Map Tour template doesn't include a video player, so you have to use the external video player provided by your favorite video hosting service (find the option to embed the video and copy the URL present in the given code). If you want to host the video yourself, you can create an HTML page that contains a video player like <a href='http://www.videojs.com/'>Video.js</a>_á».",
					div23: "á»‡_The interactive builder doesn't provide a dialog to include video when using feature services with attachments, but it is possible to do so by editing your data outside of the interactive builder. In the arcgis.com map viewer, if you modify the picture fields to point to an external video and add a special parameter at the end of your URL (#isVideo), your media will be considered to be a video_á».",
					div24: "á»‡_Note that you still need to have two valid pictures attachments or the point won’t be used. It isn't possible to use videos when using feature service attachments without the picture and thumbnail fields_á»."
				},
				tab3: {
					title: "á»‡_Customization_á»",
					div1: "á»‡_The builder provides several customization options that are accessible through the SETTINGS button in the top panel. If you don't find the option you expect, we also provide a downloadable version that you can deploy on your web server and enhance to fit your needs_á».",
					div2: "á»‡_We recommend that you use the hosted version unless_á»:",
					div3: "á»‡_<li>It doesn't offer a UI customization you want to have, like using a header background image.</li><li>You are a developer and you want to enhance the application.</li>_á»",
					div4: "á»‡_The downloadable version can be configured through a web map or a web mapping application identifier. The main use cases are_á»:",
					div41: "á»‡_You build your map tour using the interactive builder in the hosted environment and configure the template with the web mapping application identifier. The settings you have defined with the interactive builder will be applied_á».",
					div42: "á»‡_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template_á».",
					div43: "á»‡_Note that the interactive builder is available in the downloadable version but with some technical restrictions on browsers like Internet Explorer older than version 10_á».",
					div5: "á»‡_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>_á»."
				},
				tab4: {
					title: "á»‡_Tips_á»",
					div0: "á»‡_Supported browsers_á»",
					div0a: "á»‡_The Map Tour viewer is supported on IE8+. The interactive builder is supported on IE9+. We actively test it in all major browsers but if you experience some difficulties, we recommend that you use Chrome_á».",
					div0b: "á»‡_If you experience some difficulties, please let us know. In the meantime, by building your Map Tour using the CSV template you will minimize your interaction with the builder interface_á».",
					div1: "á»‡_Pictures_á»",
					div2: "á»‡_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour_á».",
					div2a: "á»‡_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails_á».",
					div3: "á»‡_Formatting your caption text using HTML tags_á»",
					div4: "á»‡_The header and picture title/caption can include HTML tags to define formatting and links. For example, this code adds a yellow link_á»:",
					div4a: "á»‡_Write a good subtitle for your tour_á»",
					div4b: "á»‡_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank_á».",
					div5: "á»‡_Supporting Layers_á»",
					div6: "á»‡_You can add additional supporting layers to provide context to the Map Tour. These layers may contain other geographic features you want the map to show in addition to the Map Tour points, such as a study area, a walking or driving route linking your tour points, etc. The Map Tour template displays these additional supporting layers using the symbology you specify in the web map, but the popups aren't available_á».",
					div7: "á»‡_Keep your tour short and sweet_á»",
					div8: "á»‡_There's a limit of 99 points per tour. Most Map Tours will of course be significantly shorter than this. Don't expect your audience to want to step through too many tour points. You might find your subject fascinating, but don't assume they will, too_á»!",
					div9: "á»‡_To learn more, see <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>the detailed guide</a>_á».",
					div10: "á»‡_Embed mode_á»",
					div11: "á»‡_If you want to embed the template in another website through an iframe, adding the optional parameter \"&embed\" at the end of the URL will remove the header. That mode can also be set in the downloadable version through the configuration file_á».",
					div12: "á»‡_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen_á»." 
				},
				tab5: {
					title: "á»‡_Publishing_á»",
					div1: "á»‡_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online_á».",
					div2a: "á»‡_Sharing the Tour through the builder_á»",
					div2b: "á»‡_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated_á».",
					div2c: "á»‡_Sharing the Tour through ArcGIS Online_á»",
					div2d: "á»‡_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page_á».",
					div3t: "á»‡_Feature Service security_á»",
					div3a: "á»‡_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly_á».",
					div3t2: "á»‡_Before sharing your Tour with your audience_á»",
					div3: "á»‡_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode_á».",
					div4: "á»‡_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped_á».",
					div5a: "á»‡_Recommendation for search_á»",
					div5b: "á»‡_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery_á»."
				}
			},
			share: {
				firstSaveTitle: "á»‡_Tour successfully saved_á»",
				firstSaveHeader: "á»‡_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions_á».",
				firstSaveA1: "á»‡_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_á»",
				firstSaveA1bis: "á»‡_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>_á».",
				firstSaveQ2: "á»‡_Is my Tour shared_á»?",
				firstSaveA2: "á»‡_Currently your Tour is not shared. To share it, use the SHARE button_á».",
				shareTitle: "á»‡_Share your Tour_á»",
				sharePrivateHeader: "á»‡_Your Tour is not shared, would you like to share it_á»?",
				sharePrivateBtn1: "á»‡_Share publicly_á»",
				sharePrivateBtn2: "á»‡_Share with my Organization_á»",
				sharePrivateProgress: "á»‡_Sharing in progress_á»...",
				sharePrivateErr: "á»‡_Sharing failed, try again or_á»",
				sharePrivateOk: "á»‡_Sharing updated successfully, loading_á»...",
				sharePreviewAsUser: "á»‡_Preview_á»",
				shareHeader1: "á»‡_Your Tour is <strong>publicly accessible</strong>_á».",
				shareHeader2: "á»‡_Your Tour is accessible by your organization members (login is required)_á».",
				shareLinkHeader: "á»‡_Share the Tour with your audience_á»",
				shareLinkOpen: "á»‡_OPEN_á»",
				shareQ1Opt1: "á»‡_How do I keep the Tour private_á»?",
				shareQ1Opt2: "á»‡_How do I keep the Tour private or share it publicly_á»?",
				shareA1: "á»‡_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>_á».",
				shareA1bis: "á»‡_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>_á».",
				shareQ2: "á»‡_How do I edit the Tour later_á»?",
				shareQ2bis: "á»‡_How do I get back to the authoring interface_á»?",
				shareA2div1: "á»‡_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>_á».",
				shareA2div2: "á»‡_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder_á»:",				
				shareQ3: "á»‡_Where is the data stored_á»?",
				shareA3: "á»‡_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. Flickr, Picasa, and Facebook images and YouTube videos remain referenced at their respective sites and aren't duplicated in ArcGIS Online_á».",
				shareWarning: "á»‡_Sharing %WITH% has been disabled because you are not the owner of the <a href='%LINK%' target='_blank'>webmap</a>_á».",
				shareWarningWith1: "á»‡_publicly_á»",
				shareWarningWith2: "á»‡_publicly and with the Organization_á»"
			}
        }
    })
);
