define({
	root: ({
		header: {
			start: "啟動",
			searchStories: "搜尋您的故事...",
			filter: "篩選器",
			sort: "排序",
			sortColon: "排序:",
			numResults: "結果: {{NUM_RESULTS}}",
			sortBy: "排序方式",
			dateModified: "修改日期",
			title: "標題",
			type: "類別",
			views: "檢視",
			errors: "錯誤",
			filterBy: "篩選依據",
			filterItems: "篩選項目",
			apps: "應用程式",
			sharing: "分享",
			clearAll: "全部清除",
			clearSearch: "清除搜尋",
			logOut: "登出",
			mainQuote: "若要將構想融入現今的社會，講故事是最有用的方式。",
			quoteSource: "Robert McKee",
			checkYourStories: "檢查故事",
			createStory: "建立故事",
			totalStories: "故事總計: {{NUM_STORIES}}",
			noIssues: "全部良好",
			userStories: "{{USER_NAME}} 的故事",
			headerDisabledTooltip: "請稍候，我們正在執行一些工作...",
			notOnTouch: "不適用於觸控裝置",
		},
		deleteModal: {
			title: "確認刪除",
			warningText: "是否確定要刪除這篇故事? 您無法復原它。",
			deleteText: "刪除",
			cancel: "取消"
		},
		loading: {
			loadingText: "正在載入您的故事..."
		},
		cantFindStories: {
			whereAreStories: "看不到您的故事?",
			notSeeExplanation: "我的故事只會列出以 {{STORY_MAP_TOUR}}、{{JOURNAL}}、{{MAP_SERIES}} 或 {{SWIPE_SPYGLASS}} 應用程式建立的 ArcGIS 中所託管的故事地圖。如需詳細資訊，請參閱我們的 {{FAQ}}。",
			faq: "常見問題集",
			followingStoriesToUpdate: "下列故事是使用我們早期的應用程式版本建立，需要為它們進行「我的故事」所列出的更新:",
			gettingStories: "正在搜尋使用我們的早期應用程式版本建立且需要更新的故事...",
			title: "標題",
			typeOfStoryMap: "類別",
			lastModified: "上次修改時間",
			allUpToDate: "沒有使用我們的早期應用程式版本建立且需要更新的故事。",
			updateAll: "全部更新",
			errorScanningForStories: "搜尋您的故事時出錯。",
			close: "關閉",
			updates: "更新",
			updatingNumberOfNumber: "正在更新 {{CURRENT_NUMBER}} 個，總共 {{TOTAL}} 個",
			updatingNumberOfNumberAlt: "正在更新 {{CURRENT_NUMBER}}/{{TOTAL}}",
			updateSucceeded: "更新成功!",
			reloadingStories: "正在重新載入您的故事...",
			errorUpdatingStories: "更新您的故事時出錯。",
			partialUpdateMessage: "成功更新故事: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "登入 Story Maps",
			signInTo: "使用您現有的 ArcGIS Online 帳戶登入執行以下操作:",
			explanationOne: "建立吸引人的故事地圖來敘說您的故事。",
			explanationTwo: "在您的故事地圖中使用 ArcGIS Online 的地圖和資料。",
			explanationThree: "管理您的故事地圖並檢查其內容的狀態。",
			dontHaveAccount: "沒有 ArcGIS Online 帳戶? 註冊取得:",
			publicAccount: "免費的非商業用公共帳戶",
			orgAccount: "免費試用 ArcGIS 訂閱",
			timeExpired: "您的登入已到期。請重新登入以返回您離開的位置。",
			apiDidntLoad: "未正確載入某些資料。請試著重新整理頁面。",
			needAccount: "是否需要帳戶?",
			letsGo: "讓我們著手進行!"
		},
		sharingLevel: {
			publicMessage: "公共",
			privateMessage: "私有",
			organization: "組織",
			changedSharing: "已變更分享級別。",
			unableToChange: "無法變更分享。",
			partOfMap: "此項目位於地圖中。若要變更其分享級別，必須變更地圖的分享層別。",
			storyPublicContentOrg: "您的故事是公開，因此無您無法只與您的組織分享其內容",
			storyPublicContentPrivate: "您的故事是公開，因此其內容不可為私有",
			mapOrg: "將您的地圖分享給您的組織將中斷您的故事",
			layerOrg: "將您的圖層分享給您的組織將中斷您的故事",
			mapPrivate: "將您的地圖設為私有會中斷您的故事",
			layerPrivate: "將您的圖層設為私有會中斷您的故事"
		},
		collectionList: {
			advocacy: "宣傳和推廣",
			architecture: "架構和設計",
			conservation: "保護和可持續發展",
			culture: "文化",
			destinations: "目的地和旅遊",
			disasters: "災難和復原",
			economy: "經濟和發展",
			entertainment: "娛樂",
			history: "歷程記錄",
			infrastructure: "基礎設施",
			marketing: "行銷",
			nature: "自然和環境",
			news: "新增和事件",
			oceans: "海洋圖",
			parks: "公園和娛樂",
			people: "人們和社會",
			planning: "規劃和分析",
			publicArt: "公開藝術",
			science: "科學和技術",
			sport: "運動",
			travelogues: "遊記"
		},
		types: {
			custom: "自訂",
			notSpecified: "未指定類型"
		},
		storyMap: {
			shared: "共用",
			saveFailed: "儲存時出錯",
			numViews: "視圖: {{NUM_VIEWS}}",
			editStory: "編輯故事",
			viewLive: "檢視故事",
			preview: "預覽",
			deleteButton: "刪除",
			modified: "修改的 {{DATE}}",
			summary: "摘要",
			loading: "正在載入...",
			collapse: "折疊",
			close: "關閉",
			hide: "隱藏",
			notAvailableWhenBroken: "您的故事發生下列問題",
			cantBeDeleted: "這篇故事已啟用刪除防護。請在 ArcGIS 上查看其項目頁面以停用。",
			shareDialog: {
				title: "與世界分享您的故事!",
				notPublicWarning: "您的故事已與您的組織分享。只有您的組織成員能檢視它。",
				embedStory: "已嵌入您的故事",
				shortLink: "簡短連結",
				hideHeaderBar: "隱藏標頭列",
				copied: "已複製",
				small: "小",
				medium: "中",
				large: "大",
				custom: "自訂",
				widthAbbreviation: "w",
				heightAbbreviation: "h",
				emptyDimension: "輸入尺寸。",
				seeExample: "預覽您的內嵌",
				removeHeader: "隱藏應用程式標頭"
			},
			maps: {
				unableRetrieveTitle: "無法擷取地圖",
				unableRetrieveDescription: "我們無法擷取此故事地圖的地圖。"
			},
			images: {
				unableRetrieveTitle: "無法擷取圖像",
				unableRetrieveDescription: "我們無法擷取此故事地圖的圖像。"
			},
			tags: {
				tags: "標籤",
				collectionTags: "主旨",
				selectASubject: "選擇主旨",
				save: "儲存",
				saved: "已儲存",
				errorSaving: "儲存錯誤",
				tagTip: "提示: 標記可協助人們找到您的故事。標記愈相關，您工作獲得的可見度就越高。"
			},
			submitToGallery: {
				gallerySubmission: "Story Maps 圖庫",
				canSubmitIf: "如果故事包含下列內容，您可以將其指定給圖庫:",
				hasOwnImage: "自訂縮圖",
				chosenSubject: "主旨和部分標記",
				chosenSubjectAlt: "{{SUBJECT}} 和部分標記",
				storyMapTopicSubject: "主旨",
				sharedPublicly: "分享給大眾",
				noBrokenContent: "沒問題",
				nominateToGallery: "指定給圖庫",
				comingSoon: "即將推出！",
				submitted: "已提交",
				errorSubmitting: "正在提交錯誤",
				ourGallery: "Story Maps 圖庫",
				galleryTip: "{{THE_GALLERY}} 是展現某些最佳範例的 Story Maps 管理集。如果選擇您的故事，則會在您提交起 10 天內新增它。基於指定的數量，我們無法承諾會新增您的故事。"
			},
			placeholders: {
				noSummary: "無摘要，按一下以新增一個。"
			},
			errors: {
				cantDeleteStory: "無法刪除故事。",
				unableToFind: "找不到內容",
				unableToRetrieve: "我們無法擷取此故事地圖的內容。"
			},
			socialSharing: {
				availableWhenPublic: "當您的故事為公開時可使用此選項"
			},
			dialog: {
				back: "返回",
				close: "關閉",
				cancel: "取消"
			},
			imagePicker: {
				changeDefault: "變更預設圖像",
				changeImage: "變更縮圖",
				uploadImage: "上傳縮圖",
				chooseImage: "選擇縮圖",
				chooseAnImage: "選擇圖像",
				notInIEVersion: "無法在 Internet Explorer {{VERSION_NUMBER}} 中使用此圖徵。",
				or: "Or(R)",
				uploadAnImage: "上傳圖像",
				supportedFileTypes: "支援 .png、.jpg、.gif",
				imageSizeMessage: "您的圖像至少必須為 286 像素寬 x 190 像素高。",
				minimumDimensions: "最大值: 286 x 190 像素",
				imagesLoading: "正在載入圖像...",
				noImages: "此故事沒有圖像",
				errorLoading: "無法在此故事中擷取圖像",
				clickBelowTip: "按以下按鈕來上傳圖像。",
				dragAndDrop: "拖放",
				cropImage: "裁切圖像",
				saveImage: "儲存圖像",
				save: "儲存",
				savingImage: "正在儲存您的圖像...",
				saved: "已儲存!",
				errorSaving: "無法儲存您的圖像。",
				skipAndCrop: "略過並為我裁切",
				wrongFormat: "此檔案類型不被支援。",
				noCropWarning: "此圖像無法裁切，但您仍可以其原始尺寸 ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}} 像素) 將它儲存為故事縮圖。"
			}
		},
		content: {
			media: {
				maps: "地圖",
				images: "影像",
				videos: "影片",
				webpages: "網頁",
				tags: "標籤",
				gallery: "圖庫"
			},
			headers: {
				status: "狀態",
				source: "來源",
				name: "名稱",
				shared: "共用"
			},
			component: {
				mapTour: "點號碼",
				bullet: "項目符號",
				tab: "索引標籤",
				accordion: "節",
				mapJournal: "節"
			},
			titleType: {
				mapTour: "說明文字",
				mapJournal: "URL",
				mapSeries: "URL"
			},
			actions: {
				viewMap: "檢視地圖",
				editMap: "編輯地圖",
				fix: "修復",
				viewLayer: "檢視圖層"
			},
			contentType: {
				mainStage: "主舞台動作",
				sidePanel: "description"
			},
			notification: {
				refreshExplanation: "重新檢查您的故事",
				checking: "正在檢查...",
				foundSomeIssues: "我們發現部分問題",
				noIssuesFound: "找不到問題",
				storyPublic: "您的故事現在為公開",
				storyOrg: "您的故事現在已分享到您的組織",
				storyPrivate: "您的故事現在為私有",
				mapPublic: "您的地圖現在為公開",
				mapOrg: "您的地圖現在已分享到您的組織",
				mapPrivate: "您的地圖現在為私有",
				layerPublic: "您的圖層現在為公開",
				layerOrg: "您的圖層現在已分享到您的組織",
				layerPrivate: "您的圖層現在為私有",
				contentPublic: "您的內容現在為公開",
				contentOrg: "您的內容現在已分享到您的組織",
				contentPrivate: "您的內容現在為私有",
				storyAndContentPublic: "您的故事及其內容現在為公開",
				storyAndContentOrg: "您的故事及其內容現在已分享到您的組織",
				storyAndContentPrivate: "您的故事及其內容現在為私有",
				shareBulkPrompt: "是否要據以分享您的故事內容?",
				layersPublic: "部分圖層也已經公開分享",
				layersOrg: "部分圖層也已與您的組織分享",
				layersPrivate: "部分圖層也已經設定為私有",
				mapsPublic: "部分地圖也已經公開分享",
				mapsOrg: "部分地圖也已與您的組織分享",
				mapsPrivate: "部分地圖也已經設定為私有",
				layersAndMapsPublic: "部分地圖和圖層也已經公開分享",
				layersAndMapsOrg: "部分地圖和圖層也已與您的組織分享",
				layersAndMapsPrivate: "部分地圖和圖層也已經設定為私有",
				yes: "是",
				no: "否",
				premiumPublicSuccess: "您的高級內容現在可公開存取",
				subscriptionPublicSuccess: "您的訂閱內容現在可公開存取"
			},
			errors: {
				publicDisabled: "管理員已停用公開分享",
				orgDisabled: "管理員已停用分享到您的組織",
				noMapName: "無法擷取地圖名稱",
				notPublic: "未公開",
				inaccessible: "無法存取",
				deleted: "已刪除",
				cantAccessVideo: "無法存取影片",
				noStoriesFound: "我們在您的內容中找不到任何 Story Maps。",
				cantShowStories: "無法顯示您的故事地圖。請稍後再試。",
				consolationSearch: "我們找不到任何故事。",
				notCompatibleWithBrowser : "低於版本 {{VERSION_NUMBER}} 的 Internet Explorer 不支援「我的故事」。",
				pleaseUpdateBrowser: "請更新您的瀏覽器。",
				searchTip: "請試著稍微簡化它。",
				consolationNoStories: "歡迎使用「我的故事」!",
				noStoriesTip: "若要製作您的第一張故事地圖，請檢視「應用程式」頁面。",
				letsGo: "讓我們著手進行",
				cantChangeSharingLevel: "無法變更分享級別",
				cantChangeSharingLevels: "無法變更分享級別",
				errorUpdatingTitle: "更新標題時出錯",
				errorUpdatingSummary: "更新摘要時出錯",
				noEmptyTitle: "標題不能為空",
				cantUpdatePremiumContent: "無法更新高級內容",
				cantUpdateSubscriptionContent: "無法更新訂閱內容",
				createFirstStory: "建立我的第一個故事"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "已刪除地圖",
				layerHasBeenDeleted: "已刪除圖層",
				mapIsInaccessible: "地圖無法存取",
				layerIsInaccessible: "圖層無法存取",
				mapNotYoursNotAccessible: "地圖由某人擁有且無法存取",
				layerServiceOkItemNot: "已將圖層新增為已刪除或無法存取的項目",
				layerNotYoursNotAccessible: "圖層由某人擁有且無法存取",
				mapOthersSharedBelowLevel: "地圖非您所擁有且未公開",
				layerOthersSharedBelowLevel: "圖層非您所擁有且未公開",
				noMapNoDetails: "若無地圖詳細資訊，我們將無法向您說明圖層的任何相關資訊",
				mapIsPrivate: "地圖為私有",
				mapIsOrg: "地圖只在您的組織中分享",
				layerIsPrivate: "圖層為私有",
				layerIsOrg: "圖層只在您的組織中分享",
				imageInaccessible: "此圖像無法存取",
				videoInaccessible: "此影片無法存取",
				webpageInaccessible: "此網頁無法存取",
				layerSecureService: "圖層為安全服務",
				mapSecureService: "地圖為安全服務",
				layerConsumesCredits: "圖層為高級內容並使用點數",
				layerSubscriptionContent: "圖層為訂閱內容",
				mapConsumesCredits: "地圖為高級內容並使用點數",
				mapSubscriptionContent: "地圖為訂閱內容"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "我們無法檢查此類型的圖層",
				cantScanThisType: "圖層不屬於我們可檢查的圖層類型",
				webpageNotScanned: "未檢查網頁的問題",
				ignoredIssue: "您已忽略此圖層上的錯誤。請重新載入頁面，並重新檢查此故事來檢閱錯誤",
				ignoredIssueBuilder: "您已忽略此圖層上的錯誤。請重新載入建立器來檢查此錯誤"
			},
			scanningErrors: {
				deletedMap: "已刪除內容",
				inaccessibleMap: "無法存取的地圖內容",
				notYoursNotAccessible: "內容非您所擁有且未公開",
				serviceOkItemNot: "正在運作圖層，卻是無法存取的項目",
				someContentNotPublic: "內容未公開分享",
				someContentPrivate: "私有內容",
				othersSharedBelowLevel: "內容非您所擁有且未公開",
				premiumContent: "高級內容",
				subscriptionContent: "訂閱內容",
				secureService: "安全服務",
				inaccessibleImage: "無法存取的圖像",
				inaccessibleVideo: "無法存取的影片",
				inaccessibleWebpage: "無法存取的網頁"
			},
			scanningErrorTips: {
				deletedMapTip: "提示: 編輯您的 Web 地圖並移除殘缺的內容，或移除您故事中的 Web 地圖。",
				inaccessibleMapTip: "提示: 編輯您的 Web 地圖並移除殘缺的內容，或移除您故事中的 Web 地圖。",
				notYoursNotAccessibleTip: "提示: 編輯您的 Web 地圖並移除圖層，或移除您故事中的 Web 地圖。",
				serviceOkItemNotTip: "已將圖層新增為無法存取或已刪除的項目。圖層正在運作，但這可能會影響您的地圖 (快顯視窗、符號)。",
				ignore: "忽略",
				fix: "修復",
				clickToShareOrg: "按一下按鈕，與您的組織完全分享此內容，或按一下每個項目的分享按鈕來手動變更該項目。",
				clickToSharePublic: "按一下按鈕以公開且完全分享此內容，或按一下每個項目的分享按鈕來手動變更該項目。",
				shareOrg: "分享到您的組織",
				sharePublicly: "公開分享",
				othersSharedBelowLevelTip: "提示: 您的部分故事內容由 {{USER_NAME}} 擁有，且檢視您故事的其他人可能看不到該內容。",
				secureServiceTip: "提示: 從您的故事移除安全服務，或執行 {{HERE}} 說明的程序。",
				blogArticle: "此處",
				premiumContentTip: "您的故事包含在設為公開時將使用 {{CREDITS}} 的高級內容。請將您的故事設為公開並繼續，或從您的故事移除圖層。",
				premiumContentPublicTip: "您的故事包含開放大眾使用時將使用 {{CREDITS}} 的高級內容。請確認將這些圖層設為公開，或從您的故事移除圖層。",
				subscriptionContentTip: "您的故事包含預設未公開使用的訂閱內容。請確認要開放使用這些圖層 (不會使用點數)，或從您的故事移除圖層。",
				credits: "點數",
				makePublic: "設為公開",
				confirm: "確認",
				inaccessibleImageTip: "提示: 提供缺少的圖像或移除對圖像的參照。",
				inaccessibleVideoTip: "提示: 提供缺少的影片或移除對影片的參照。",
				inaccessibleWebpageTip: "提示: 提供缺少的網頁或移除對網頁的參照。"
			},
			removeLayer: {
				title: "修復圖層問題",
				layersWithIssue: "發生此問題的圖層: {{NUM_WITH_ISSUE}}",
				issueExplanation: "已將圖層 {{LAYER_NAME}} 新增為無法存取或已刪除的項目。圖層正在運作，但這可能會影響您的地圖 (快顯視窗、符號)。我們無法判斷此項目對您的故事是否重要。",
				issueSolution: "若要修復問題，您可以編輯您的地圖，移除圖層，再使用下列 URL 將圖層新增回地圖中:",
				editMap: "編輯您的地圖",
				clickBelowWhenDone: "完成編輯時，按以下按鈕:",
				rescanAndClose: "重新掃描並關閉"
			},
			info: {
				ownedBy: "此項目由 {{USER_NAME}} 擁有",
				unknownUser: "某人",
				untitledSection: "(無標題的部分)",
				introRecord: "簡介"
			},
			layers: {
				layersHeader: "圖層",
				noLayers: "(無圖層)",
				basemapParens: "(底圖)"
			},
			images: {
				thumbnails: "縮圖",
				thumbnail: "縮略圖",
				thumbnailParens: "(縮圖)"
			},
			general: {
				noTitle: "(無標題)",
				loading: "正在載入..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "部分",
				secondTitle: "樣式",
				secondValueA: "側面板",
				secondValueB: "浮動面板",
				thirdTitle: "地圖"
			},
			mapTour: {
				firstTitle: "多個導覽點",
				secondTitle: "樣式",
				secondValueA: "整合式",
				secondValueB: "三面板",
				thirdTitle: "底圖",
				thirdValueLoading: "正在載入...",
				thirdValueUnknown: "未知"
			},
			mapSeries: {
				firstTitleA: "項目符號",
				firstTitleB: "部分",
				firstTitleC: "索引標籤",
				secondTitle: "樣式",
				secondValueA: "項目符號式",
				secondValueB: "側折疊",
				secondValueC: "索引標籤式",
				thirdTitle: "地圖"
			},
			swipeSpyglass: {
				firstTitle: "景點",
				secondTitle: "樣式",
				secondValueA: "刷屏",
				secondValueB: "望遠鏡",
				thirdTitle: "地圖"
			},
			crowdsource: {
				firstTitle: "貢獻",
				secondTitle: "樣式",
				secondValueA: "側面板",
				secondValueB: "已堆疊",
				thirdTitle: "底圖",
				thirdValueLoading: "正在載入...",
				thirdValueUnknown: "未知"
			}
		},
		progress: {
			checkingStories: "正在檢查您的故事中的問題...",
			stop: "停止",
			exit: "退出",
			dismiss: "清除",
			done: "完成。",
			noStoriesWithIssuesLower: "找不到問題!",
			storiesErrorFree: "您的故事似無錯誤",
			scanAllError: "無法掃描 -- 我們無法擷取您的一或多個故事",
			scanProgress: "{{NUM_SCANNED}}，總計 {{NUM_TOTAL}}",
			scanStopped: "掃描的故事數: {{NUM_SCANNED}}，發生問題的故事數: {{ISSUE_STORIES}}",
			storiesWithIssues: "發生問題的故事數: {{NUM_STORIES}}"
		},
		newStories: {
			newStoriesFound: "您似已建立新故事。",
			includeStories: "重新整理故事",
			notWhileScanning: "完成檢查時可使用此動作"
		}
    }),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1,
	"zh-tw": 1
});
