define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Web マップ",
				lblLocation: "位置",
				lblContent: "コンテンツ",
				lblPopup: "ポップアップ",
				lblControls: "その他",
				lblOverview: "概観図",
				lblLegend: "凡例",
				loadingTitle: "タイトルを読み込んでいます",
				entry: "エントリ",
				entries: "エントリ",
				section: "セクション",
				sections: "セクション",
				and: "および",
				action: "セクション内のアクション",
				actions: "セクション内のアクション",
				originalWebmap: "%TPL_NAME% の公開に使用される Web マップ",
				browseMaps: "マップの参照",
				current: "現在の Web マップ",
				select: "Web マップの選択",
				newMap: "新しく選択した Web マップ",
				webmapDefault: "Web マップのデフォルト",
				customCfg: "カスタム構成",
				tooltipLocation: "このマップが表示される場所を定義します。",
				tooltipContent: "表示レイヤを定義します。",
				tooltipPopup: "このマップを表示するときに開くポップアップを選択します。",
				tooltipOverview: "メインのマップと一緒に小さいオーバービュー マップを表示します。",
				tooltipLegend: "マップの凡例をマップ上に表示します。マップに多くのレイヤとシンボルが存在する場合に役立ちます。",
				mapCfgInvite: "これらのコントロールを使用してマップを構成",
				lblLocationAlt: "最初のマップから継承",
				tooltipLocationAlt: "このマップの場所は一連のマップ内の最初のマップと同期します。この動作を変更するには、[設定] → [マップ オプション] の順に移動します。"
			},
			configure: {
				btnReset: "リセット",
				btnCancel: "キャンセル",
				tocTitle: "マップ コンテンツ",
				tocExplain: "表示するレイヤを選択します。",
				tocNoData: "レイヤを構成できません。",
				tocSave: "マップ コンテンツの保存",
				extentTitle: "マップ位置",
				extentExplain: "マップを移動および拡大/縮小して、ユーザに対する外観を定義します。",
				extentSave: "マップ位置の保存",
				popupTitle: "マップ ポップアップ",
				popupExplain: "フィーチャをクリックして、表示するポップアップを開きます。",
				popupSave: "ポップアップ構成の保存",
				hintNavigation: "マップ ナビゲーションは無効化されています。"
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "組織",
					onlineLabel: "ArcGIS Online",
					contentLabel: "マイ コンテンツ",
					favoritesLabel: "お気に入り"
				},
				title: "Web マップの選択",
				searchTitle: "検索",
				ok: "OK",
				cancel: "キャンセル",
				placeholder: "検索語句または Web マップ ID を入力..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
