define({
	root: ({
		builder: {
			layouts: {
				tabTitle: "Č_Tabbed___ž",
				tabDescr: "Č_Present maps and other content using tabs with an optional panel for descriptive text___________________________ž.",
				tabItem: "Č_Tab__ž",
				tabItems: "Č_Tabs__ž",
				sideTitle: "Č_Side Accordion_____ž",
				sideDescr: "Č_Present maps and other content using an expandable control that includes descriptive text____________________________ž.",
				sideItem: "Č_Entry___ž",
				sideItems: "Č_Entries___ž",
				bulletTitle: "Č_Bulleted___ž",
				bulletDescr: "Č_Present maps and other content using bullets with an optional panel for descriptive text____________________________ž.",
				bulletItem: "Č_Bullet___ž",
				bulletItems: "Č_Bullets___ž"
			},
			common: {
				lblStatus1: "Č_Published____ž",
				lblStatus3: "Č_Hidden___ž"
			},
			settingsLayoutOptions: {
				title: "Č_Layout options_____ž",
				lblDescription: "Č_Description____ž",
				lblLegend: "Č_Legend placement______ž",
				tooltipLegend: "Č_Choose where you want the map legend to be displayed. You can turn the legend on for any map when you add or configure it______________________________________ž.",
				lblDropdown: "Č_Dropdown___ž",
				lblBelowDesc: "Č_Below the description_______ž",
				lblOnPanel: "Č_As a panel____ž",
				lblPanelDescAndLegend: "Č_Description and legend panel_________ž",
				lblPanelDescAndOrLegend: "Č_Description and/or legend panel__________ž",
				lblPanelDesc: "Č_Description panel______ž",
				lblPanelLegend: "Č_Legend panel_____ž",
				lblPanelAccordion: "Č_Accordion panel______ž",
				cfgLeft: "Č_Left__ž",
				cfgRight: "Č_Right___ž",
				cfgSmall: "Č_Small___ž",
				cfgMedium: "Č_Medium___ž",
				cfgLarge: "Č_Large___ž",
				lblNumbering: "Č_Display numbers______ž",
				lblReverse: "Č_Reverse numbering______ž",
				canOverlapMap: "Č_can overlap map location________ž"
			},
			settingsMapOptions: {
				title: "Č_Map options____ž",
				lblOverview: "Č_Overview Map_____ž",
				tooltipOverview: "Č_Display a small overview map along with the main map_________________ž.",
				lblLocate: "Č_Locate button_____ž",
				tooltipLocate: "Č_This functionality is supported on most mobile device and desktop browsers (Internet Explorer 9)______________________________ž.",
				lblGeocoder: "Č_Address or Place Finder________ž",
				tooltipGeocoder: "Č_Allow your users to find addresses and places on your maps___________________ž.",
				lblSync: "Č_Synchronize map locations_________ž",
				tooltipSync: "Č_When enabled, the initial location of the first map in your series will be applied to all the maps, and navigation by users in any map will be reflected in all maps. Disable for each map's location to remain independent___________________________________________________________________ž."
			},
			initPopup: {
				title: "Č_Welcome to____ž"
			},
			addEditPopup: {
				lblAdd: "Č_Add__ž",
				lblEdit: "Č_Edit__ž",
				disabled: "Č_Add is disabled because the maximum number of allowed %LBL_LAYOUT% has been reached__________________________ž.",
				titleAdd: "Č_Add__ž",
				titleEdit: "Č_Edit__ž",
				stepMainStageNextTooltip: "Č_Enter the %LBL_LAYOUT% title and content_____________ž",
				titlePlaceholder: "Č_%LBL_LAYOUT% title_______ž..."
			},
			textEditor: {
				placeholder1: "Č_Add text, links, and small graphics here_____________ž.",
				placeholder2: "Č_If left blank the panel will be hidden_____________ž."
			},
			organizePopup: {
				title: "Č_Organize___ž",
				lblHeader: "Č_Drag and drop %LBL_LAYOUT% to organize your story________________ž.",
				lblColTitle: "Č_Title___ž",
				lblColStatus: "Č_Status___ž",
				btnApplyWarning: "Č_Confirm deletion of %NB% %LBL_LAYOUT%____________ž",
				deleteTooltip: "Č_Delete___ž",
				firstSectionExplain: "Č_(The home section cannot be moved)___________ž"
			},
			help: {
				lblHelp: "Č_Help__ž",
				lblAdd: "Č_Add__ž",
				lblSettings: "Č_Settings___ž",
				lblOrga: "Č_Organize___ž",
				lblEdit: "Č_Edits___ž",
				lblPublish: "Č_Share___ž",
				lblTips: "Č_Tips__ž",
				lblMore: "Č_Want more____ž?",
				lblLink: "Č_Visit the Esri Story Maps website___________ž.",
				content1Div1: "Č_To create your %TPL_NAME%, use the Add button to add each map or other content into the layout. The other content can include images, videos or embedded web pages or code. For example you might want your readers to see an introductory image or video when they first launch your  %TPL_NAME%, before they move on to explore your maps_____________________________________________________________________________________________________ž.",
				content1Div2: "Č_When you click the Add button a dialog will appear that lets you choose and configure the map or other content you want to add. For example you can specify the location you want the map to show, enable its legend, etc__________________________________________________________________ž.",
				content2Div1: "Č_The Settings dialog is where you can change the appearance of your %TPL_NAME%. You change the layout, choose a different color scheme, choose where the map legend will appear, etc_______________________________________________________ž.",
				content2Div2: "Č_You can also replace the Esri logo in the header of your %TPL_NAME% with your own logo to reflect your brand. You can also specify the website that will be launched if readers click your logo, so they can get more information_____________________________________________________________________ž.",
				content3Div1: "Č_The Organize dialog lets you manage your %TPL_NAME%. In this dialog you can change the order of the series by dragging and dropping_________________________________________ž.",
				content3Div2: "Č_You can also delete content or hide it. Hiding is useful if you are preparing new content that isn't ready to be included in your story map yet____________________________________________ž.",
				content4Div1: "Č_Found a mistake or want to change your material? No worries. Look for the edit icon throughout the app to make changes to your content. Youâ€™ll use the edit functions many times as you develop your %TPL_NAME%________________________________________________________________ž!",
				content5Div1: "Č_When you save your %TPL_NAME% it is private initially. Use the Share button to share it with others. You can share your %TPL_NAME% publicly so anyone can access it__________________________________________________ž.",
				content5Div2: "Č_Depending on your account, you may also have the option to share your %TPL_NAME% just to people within your organization, so others can't access it_____________________________________________ž.",
				content6Div1: "Č_By default the maps in a series are synchronized to show the same location. This means that the location shown in the first map will be automatically applied to all the other maps, and that if a reader zooms or pans to a different location in the map they are currently looking at, this will also be applied to the other maps___________________________________________________________________________________________________ž.",
				content6Div2: "Č_For example if your series shows different thematic data for a city, a reader can zoom to their neighborhood and then simply switch between the tabs to see the maps for that area_______________________________________________________ž.",
				content6Div3: "Č_To disable location synchronization, go to the Settings dialog and uncheck that setting in the Map Options tab__________________________________ž.",
				content6AltDiv1: "Č_By default the maps location are synchronized. Disabling synchronization allows each map to display a different location_____________________________________ž.",
				content6AltDiv2: "Č_Synchronization ON______ž",
				content6AltDiv3: "Č_Synchronization OFF_______ž",
				content6AltDiv4: "Č_To disable synchronization, go to Settings > Map Options and uncheck \"Synchronize map locations\"_______________________________ž."
			},
			landing: {
				lblAdd: "Č_What do you want to call your %LAYOUT_TITLE% Map Series__________________ž?",
				phAdd: "Č_Enter your title_______ž...",
				lblOR: "Č_Or__ž",
				lblHelp: "Č_Take a Tour____ž"
			}
        }
    }),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"hr": 1, 
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sr": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
