define(
	 ({
		header: {
			start: "Š_start___ä",
			searchStories: "Š_Search your stories________ä...",
			filter: "Š_Filter___ä",
			sort: "Š_Sort__ä",
			sortColon: "Š_Sort___ä:",
			numResults: "Š_Results: {{NUM_RESULTS}}________ä",
			sortBy: "Š_Sort by___ä",
			dateModified: "Š_Date modified_____ä",
			title: "Š_Title___ä",
			type: "Š_Type__ä",
			views: "Š_Views___ä",
			errors: "Š_Errors___ä",
			filterBy: "Š_Filter by____ä",
			filterItems: "Š_Filter Items_____ä",
			apps: "Š_Apps__ä",
			sharing: "Š_Sharing___ä",
			clearAll: "Š_Clear all____ä",
			clearSearch: "Š_Clears the search______ä",
			logOut: "Š_Log Out___ä",
			mainQuote: "Š_Storytelling is the most powerful way to put ideas into the world today_______________________ä.",
			quoteSource: "Š_Robert McKee_____ä",
			checkYourStories: "Š_Check Stories_____ä",
			createStory: "Š_Create Story_____ä",
			totalStories: "Š_Total stories: {{NUM_STORIES}}__________ä",
			noIssues: "Š_All good___ä",
			userStories: "Š_Stories of {{USER_NAME}}________ä",
			headerDisabledTooltip: "Š_Please wait while we work some magic_____________ä...",
			notOnTouch: "Š_Not available on touch devices__________ä",
		},
		deleteModal: {
			title: "Š_Confirm Delete_____ä",
			warningText: "Š_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________ä.",
			deleteText: "Š_Delete___ä",
			cancel: "Š_Cancel___ä"
		},
		loading: {
			loadingText: "Š_Loading your stories________ä..."
		},
		cantFindStories: {
			whereAreStories: "Š_Not seeing your story________ä?",
			notSeeExplanation: "Š_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________ä.",
			faq: "Š_FAQ__ä",
			followingStoriesToUpdate: "Š_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________ä:",
			gettingStories: "Š_Searching for stories created with early versions of our applications that need to be updated______________________________ä...",
			title: "Š_Title___ä",
			typeOfStoryMap: "Š_Type__ä",
			lastModified: "Š_Last modified_____ä",
			allUpToDate: "Š_No stories created with early versions of our applications need to be updated________________________ä.",
			updateAll: "Š_Update All____ä",
			errorScanningForStories: "Š_There was an error searching your stories______________ä.",
			close: "Š_Close___ä",
			updates: "Š_Updates___ä",
			updatingNumberOfNumber: "Š_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________ä",
			updatingNumberOfNumberAlt: "Š_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________ä",
			updateSucceeded: "Š_Update succeeded______ä!",
			reloadingStories: "Š_Reloading your stories_________ä...",
			errorUpdatingStories: "Š_There was an error updating your stories_____________ä.",
			partialUpdateMessage: "Š_Stories updated successfully: {{NUM_UPDATED}}_______________ä"
		},
		signIn: {
			signInTitle: "Š_Sign in to Story Maps_______ä",
			signInTo: "Š_Sign in with your existing ArcGIS Online account to_________________ä:",
			explanationOne: "Š_Create compelling story maps to tell your stories________________ä.",
			explanationTwo: "Š_Use your maps and data from ArcGIS Online in your story maps___________________ä.",
			explanationThree: "Š_Manage your story maps and check the status of their content___________________ä.",
			dontHaveAccount: "Š_Don't have an ArcGIS Online account? Sign up for a________________ä:",
			publicAccount: "Š_Free non-commercial public account___________ä",
			orgAccount: "Š_Free trial ArcGIS subscription__________ä",
			timeExpired: "Š_Your sign-in expired. Sign in again to pick up where you left off_____________________ä.",
			apiDidntLoad: "Š_Something isn't loading correctly. Try refreshing the page___________________ä.",
			needAccount: "Š_Need an account______ä?",
			letsGo: "Š_Let's go____ä!"
		},
		sharingLevel: {
			publicMessage: "Š_Public___ä",
			privateMessage: "Š_Private___ä",
			organization: "Š_Organization_____ä",
			changedSharing: "Š_Changed sharing level________ä.",
			unableToChange: "Š_Unable to change sharing_________ä.",
			partOfMap: "Š_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________ä.",
			storyPublicContentOrg: "Š_Your story is public, so its content can't be shared only with your organization_________________________ä",
			storyPublicContentPrivate: "Š_Your story is public, so its content can't be private_________________ä",
			mapOrg: "Š_Sharing your map to your organization would break your story___________________ä",
			layerOrg: "Š_Sharing your layer to your organization would break your story____________________ä",
			mapPrivate: "Š_Making your map private would break your story_______________ä",
			layerPrivate: "Š_Making your layer private would break your story_______________ä"
		},
		collectionList: {
			advocacy: "Š_Advocacy and Outreach_______ä",
			architecture: "Š_Architecture and Design________ä",
			conservation: "Š_Conservation and Sustainability__________ä",
			culture: "Š_Culture___ä",
			destinations: "Š_Destinations and Tourism________ä",
			disasters: "Š_Disasters and Recovery________ä",
			economy: "Š_Economy and Development________ä",
			entertainment: "Š_Entertainment_____ä",
			history: "Š_History___ä",
			infrastructure: "Š_Infrastructure_____ä",
			marketing: "Š_Marketing____ä",
			nature: "Š_Nature and Environment________ä",
			news: "Š_News and Events______ä",
			oceans: "Š_Oceans___ä",
			parks: "Š_Parks and Recreation_______ä",
			people: "Š_People and Society______ä",
			planning: "Š_Planning and Analysis_______ä",
			publicArt: "Š_Public Art____ä",
			science: "Š_Science and Technology________ä",
			sport: "Š_Sport___ä",
			travelogues: "Š_Travelogues____ä"
		},
		types: {
			custom: "Š_Custom___ä",
			notSpecified: "Š_Type not specified______ä"
		},
		storyMap: {
			shared: "Š_Shared___ä",
			saveFailed: "Š_Error saving_____ä",
			numViews: "Š_Views: {{NUM_VIEWS}}_______ä",
			editStory: "Š_Edit Story____ä",
			viewLive: "Š_View Live____ä",
			preview: "Š_Preview___ä",
			deleteButton: "Š_Delete___ä",
			modified: "Š_Modified {{DATE}}______ä",
			summary: "Š_Summary___ä",
			loading: "Š_Loading____ä...",
			collapse: "Š_collapse___ä",
			close: "Š_close___ä",
			hide: "Š_hide__ä",
			notAvailableWhenBroken: "Š_Your story has issues below_________ä",
			cantBeDeleted: "Š_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________ä",
			shareDialog: {
				title: "Š_Share your story with the world___________ä!",
				notPublicWarning: "Š_Your story is shared with your organization. Only members of your organization will be able to view it________________________________ä.",
				embedStory: "Š_Embed your story______ä",
				shortLink: "Š_Shortlink____ä",
				hideHeaderBar: "Š_Hide header bar______ä",
				copied: "Š_Copied___ä",
				small: "Š_small___ä",
				medium: "Š_medium___ä",
				large: "Š_large___ä",
				custom: "Š_custom___ä",
				widthAbbreviation: "Š_w_ä",
				heightAbbreviation: "Š_h_ä",
				emptyDimension: "Š_Enter a dimension______ä.",
				seeExample: "Š_Preview your embed______ä",
				removeHeader: "Š_Hide application header________ä"
			},
			maps: {
				unableRetrieveTitle: "Š_Unable to retrieve maps________ä",
				unableRetrieveDescription: "Š_We weren't able to retrieve maps for this story map_________________ä."
			},
			images: {
				unableRetrieveTitle: "Š_Unable to retrieve images_________ä",
				unableRetrieveDescription: "Š_We weren't able to retrieve images for this story map_________________ä."
			},
			tags: {
				tags: "Š_Tags__ä",
				collectionTags: "Š_Subject___ä",
				selectASubject: "Š_Select a subject______ä",
				save: "Š_Save__ä",
				saved: "Š_Saved___ä",
				errorSaving: "Š_Error saving_____ä",
				tagTip: "Š_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________ä."
			},
			submitToGallery: {
				gallerySubmission: "Š_Story Maps Gallery______ä",
				canSubmitIf: "Š_You can nominate your story to the gallery if it contains the following_______________________ä:",
				hasOwnImage: "Š_Custom thumbnail______ä",
				chosenSubject: "Š_A subject and some tags________ä",
				chosenSubjectAlt: "Š_A {{SUBJECT}} and some tags_________ä",
				storyMapTopicSubject: "Š_subject___ä",
				sharedPublicly: "Š_Shared publicly______ä",
				noBrokenContent: "Š_No broken content______ä",
				nominateToGallery: "Š_Nominate to Gallery_______ä",
				comingSoon: "Š_Coming soon_____ä!",
				submitted: "Š_Submitted____ä",
				errorSubmitting: "Š_Error submitting______ä",
				ourGallery: "Š_The Story Maps gallery________ä",
				galleryTip: "Š_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________ä."
			},
			placeholders: {
				noSummary: "Š_No summary, click to add one__________ä."
			},
			errors: {
				cantDeleteStory: "Š_Unable to delete story________ä.",
				unableToFind: "Š_Unable to find content________ä",
				unableToRetrieve: "Š_We weren't able to retrieve the content for this story map___________________ä."
			},
			socialSharing: {
				availableWhenPublic: "Š_This option will be available when your story is public__________________ä"
			},
			dialog: {
				back: "Š_Back__ä",
				close: "Š_Close___ä",
				cancel: "Š_Cancel___ä"
			},
			imagePicker: {
				changeDefault: "Š_Change the default image________ä",
				changeImage: "Š_Change thumbnail______ä",
				uploadImage: "Š_Upload thumbnail______ä",
				chooseImage: "Š_Choose thumbnail______ä",
				chooseAnImage: "Š_Choose an Image______ä",
				notInIEVersion: "Š_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________ä.",
				or: "Š_Or__ä",
				uploadAnImage: "Š_Upload an Image______ä",
				supportedFileTypes: "Š_Supports .png, .jpg, .gif_________ä",
				imageSizeMessage: "Š_Your image needs to be at least 286 px wide by 190 px tall___________________ä.",
				minimumDimensions: "Š_Minimum: 286 x 190px_______ä",
				imagesLoading: "Š_Loading images______ä...",
				noImages: "Š_This story has no images________ä",
				errorLoading: "Š_Unable to retrieve the images in this story______________ä",
				clickBelowTip: "Š_Click the button below to upload an image______________ä.",
				dragAndDrop: "Š_Drag and Drop_____ä",
				cropImage: "Š_Crop Image____ä",
				saveImage: "Š_Save Image____ä",
				save: "Š_Save__ä",
				savingImage: "Š_Saving your image_______ä...",
				saved: "Š_Saved___ä!",
				errorSaving: "Š_Unable to save your image_________ä.",
				skipAndCrop: "Š_Skip and Crop for me_______ä",
				wrongFormat: "Š_This file type is not supported___________ä.",
				noCropWarning: "Š_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________ä."
			}
		},
		content: {
			media: {
				maps: "Š_Maps__ä",
				images: "Š_Images___ä",
				videos: "Š_Videos___ä",
				webpages: "Š_Webpages___ä",
				tags: "Š_Tags__ä",
				gallery: "Š_Gallery___ä"
			},
			headers: {
				status: "Š_Status___ä",
				source: "Š_Source___ä",
				name: "Š_Name__ä",
				shared: "Š_Shared___ä"
			},
			component: {
				mapTour: "Š_Point Number_____ä",
				bullet: "Š_Bullet___ä",
				tab: "Š_Tab__ä",
				accordion: "Š_Section___ä",
				mapJournal: "Š_Section___ä"
			},
			titleType: {
				mapTour: "Š_Caption___ä",
				mapJournal: "Š_URL__ä",
				mapSeries: "Š_URL__ä"
			},
			actions: {
				viewMap: "Š_View Map___ä",
				editMap: "Š_Edit Map___ä",
				fix: "Š_Fix__ä",
				viewLayer: "Š_View Layer____ä"
			},
			contentType: {
				mainStage: "Š_main stage action______ä",
				sidePanel: "Š_description____ä"
			},
			notification: {
				refreshExplanation: "Š_Check your story again________ä",
				checking: "Š_Checking____ä...",
				foundSomeIssues: "Š_We found some issues_______ä",
				noIssuesFound: "Š_No issues found______ä",
				storyPublic: "Š_Your story is now public________ä",
				storyOrg: "Š_Your story is now shared to your organization_______________ä",
				storyPrivate: "Š_Your story is now private_________ä",
				mapPublic: "Š_Your map is now public________ä",
				mapOrg: "Š_Your map is now shared to your organization______________ä",
				mapPrivate: "Š_Your map is now private________ä",
				layerPublic: "Š_Your layer is now public________ä",
				layerOrg: "Š_Your layer is now shared to your organization_______________ä",
				layerPrivate: "Š_Your layer is now private_________ä",
				contentPublic: "Š_Your content is now public_________ä",
				contentOrg: "Š_Your content is now shared to your organization_______________ä",
				contentPrivate: "Š_Your content is now private_________ä",
				storyAndContentPublic: "Š_Your story and its content are now public_____________ä",
				storyAndContentOrg: "Š_Your story and its content are now shared to your organization____________________ä",
				storyAndContentPrivate: "Š_Your story and its content are now private______________ä",
				shareBulkPrompt: "Š_Do you want to share your storyâ€™s content accordingly__________________ä?",
				layersPublic: "Š_Some layers have also been shared publicly______________ä",
				layersOrg: "Š_Some layers have also been shared with your organization__________________ä",
				layersPrivate: "Š_Some layers have also been made private_____________ä",
				mapsPublic: "Š_Some maps have also been shared publicly_____________ä",
				mapsOrg: "Š_Some maps have also been shared with your organization_________________ä",
				mapsPrivate: "Š_Some maps have also been made private____________ä",
				layersAndMapsPublic: "Š_Some maps and layers have also been shared publicly________________ä",
				layersAndMapsOrg: "Š_Some maps and layers have also been shared with your organization_____________________ä",
				layersAndMapsPrivate: "Š_Some maps and layers have also been made private_______________ä",
				yes: "Š_Yes__ä",
				no: "Š_No__ä",
				premiumPublicSuccess: "Š_Your premium content is now publicly accessible_______________ä",
				subscriptionPublicSuccess: "Š_Your subscription content is now publicly accessible_________________ä"
			},
			errors: {
				publicDisabled: "Š_Sharing publicly has been disabled by the Administrator__________________ä",
				noMapName: "Š_Could Not Retrieve Map Name_________ä",
				notPublic: "Š_NOT PUBLIC____ä",
				inaccessible: "Š_INACCESSIBLE_____ä",
				deleted: "Š_DELETED___ä",
				cantAccessVideo: "Š_Could Not Access Video________ä",
				noStoriesFound: "Š_We could not find any Story Maps in your content________________ä.",
				cantShowStories: "Š_Unable to show your story maps. Please try again later__________________ä.",
				consolationSearch: "Š_We couldn't find any stories__________ä.",
				notCompatibleWithBrowser : "Š_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________ä.",
				pleaseUpdateBrowser: "Š_Please update your browser_________ä.",
				searchTip: "Š_Try and simplify it a bit_________ä.",
				consolationNoStories: "Š_Welcome to My Stories________ä!",
				noStoriesTip: "Š_To make your first story map, check out the Apps page_________________ä.",
				letsGo: "Š_Let's Go___ä",
				cantChangeSharingLevel: "Š_Unable to change sharing level__________ä",
				cantChangeSharingLevels: "Š_Unable to change sharing levels__________ä",
				errorUpdatingTitle: "Š_Error updating title_______ä",
				errorUpdatingSummary: "Š_Error updating summary________ä",
				noEmptyTitle: "Š_Title cannot be empty_______ä",
				cantUpdatePremiumContent: "Š_Unable to update premium content___________ä",
				cantUpdateSubscriptionContent: "Š_Unable to update subscription content____________ä",
				createFirstStory: "Š_Create My First Story_______ä"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Š_Map has been deleted_______ä",
				layerHasBeenDeleted: "Š_Layer has been deleted________ä",
				mapIsInaccessible: "Š_Map is inaccessible_______ä",
				layerIsInaccessible: "Š_Layer is inaccessible_______ä",
				mapNotYoursNotAccessible: "Š_Map is owned by someone else and isn't accessible________________ä",
				layerServiceOkItemNot: "Š_Layer was added as an item that is deleted or inaccessible__________________ä",
				layerNotYoursNotAccessible: "Š_Layer is owned by someone else and isn't accessible________________ä",
				mapOthersSharedBelowLevel: "Š_Map is not owned by you and is not public_____________ä",
				layerOthersSharedBelowLevel: "Š_Layer is not owned by you and is not public______________ä",
				noMapNoDetails: "Š_Without the map details, we can't tell you anything about the layers_____________________ä",
				mapIsPrivate: "Š_Map is private_____ä",
				mapIsOrg: "Š_Map is only shared in your organization_____________ä",
				layerIsPrivate: "Š_Layer is private______ä",
				layerIsOrg: "Š_Layer is only shared in your organization_____________ä",
				imageInaccessible: "Š_This image is inaccessible_________ä",
				videoInaccessible: "Š_This video is inaccessible_________ä",
				webpageInaccessible: "Š_This web page is inaccessible__________ä",
				layerSecureService: "Š_Layer is a secure service_________ä",
				mapSecureService: "Š_Map is a secure service________ä",
				layerConsumesCredits: "Š_Layer is premium content and consumes credits_______________ä",
				layerSubscriptionContent: "Š_Layer is subscription content__________ä",
				mapConsumesCredits: "Š_Map is premium content and consumes credits______________ä",
				mapSubscriptionContent: "Š_Map is subscription content_________ä"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "Š_We're not able to check this type of layer______________ä",
				cantScanThisType: "Š_Layer is not a type of layer we can check_____________ä",
				webpageNotScanned: "Š_Webpages are not checked for issues____________ä"
			},
			scanningErrors: {
				deletedMap: "Š_Deleted content______ä",
				inaccessibleMap: "Š_Inaccessible map content________ä",
				notYoursNotAccessible: "Š_Content not owned by you and not public_____________ä",
				serviceOkItemNot: "Š_Working layers but inaccessible items____________ä",
				someContentNotPublic: "Š_Content not shared publicly_________ä",
				someContentPrivate: "Š_Private content______ä",
				othersSharedBelowLevel: "Š_Content not owned by you and not public_____________ä",
				premiumContent: "Š_Premium content______ä",
				subscriptionContent: "Š_Subscription content_______ä",
				secureService: "Š_Secure services______ä",
				inaccessibleImage: "Š_Inaccessible images_______ä",
				inaccessibleVideo: "Š_Inaccessible videos_______ä",
				inaccessibleWebpage: "Š_Inaccessible webpages_______ä"
			},
			scanningErrorTips: {
				deletedMapTip: "Š_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ä.",
				inaccessibleMapTip: "Š_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ä.",
				notYoursNotAccessibleTip: "Š_Tip: Open the web map and remove the layer or map from the story_____________________ä.",
				serviceOkItemNotTip: "Š_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________ä.",
				ignore: "Š_Ignore___ä",
				fix: "Š_Fix__ä",
				clickToShareOrg: "Š_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________ä.",
				clickToSharePublic: "Š_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________ä.",
				shareOrg: "Š_Share to your org______ä",
				sharePublicly: "Š_Share publicly_____ä",
				othersSharedBelowLevelTip: "Š_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________ä.",
				secureServiceTip: "Š_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________ä.",
				blogArticle: "Š_here__ä",
				premiumContentTip: "Š_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________ä.",
				premiumContentPublicTip: "Š_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________ä.",
				subscriptionContentTip: "Š_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________ä.",
				agolCredits: "Š_ArcGIS Online credits_______ä",
				credits: "Š_credits___ä",
				makePublic: "Š_Make public____ä",
				confirm: "Š_Confirm___ä",
				inaccessibleImageTip: "Š_Tip: Provide the missing image or remove the reference to it___________________ä.",
				inaccessibleVideoTip: "Š_Tip: Provide the missing video or remove the reference to it___________________ä.",
				inaccessibleWebpageTip: "Š_Tip: Provide the missing web page or remove the reference to it____________________ä."
			},
			removeLayer: {
				title: "Š_Fix Layer Issue______ä",
				layersWithIssue: "Š_Layers with this issue: {{NUM_WITH_ISSUE}}______________ä",
				issueExplanation: "Š_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________ä.",
				issueSolution: "Š_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________ä:",
				editMap: "Š_Edit Your Map_____ä",
				clickBelowWhenDone: "Š_When you have finished editing, click the button below__________________ä:",
				rescanAndClose: "Š_Rescan And Close______ä"
			},
			info: {
				ownedBy: "Š_This item is owned by {{USER_NAME}}____________ä",
				unknownUser: "Š_someone else_____ä",
				untitledSection: "Š_(Untitled section)______ä",
				introRecord: "Š_Introduction_____ä"
			},
			layers: {
				layersHeader: "Š_Layers___ä",
				noLayers: "Š_(No Layers)____ä",
				basemapParens: "Š_(basemap)____ä"
			},
			images: {
				thumbnails: "Š_Thumbnails____ä",
				thumbnail: "Š_Thumbnail____ä",
				thumbnailParens: "Š_(thumbnail)____ä"
			},
			general: {
				noTitle: "Š_(no title)____ä",
				loading: "Š_Loading____ä..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "Š_sections___ä",
				secondTitle: "Š_style___ä",
				secondValueA: "Š_side panel____ä",
				secondValueB: "Š_floating panel_____ä",
				thirdTitle: "Š_maps__ä"
			},
			mapTour: {
				firstTitle: "Š_tour points____ä",
				secondTitle: "Š_style___ä",
				secondValueA: "Š_integrated____ä",
				secondValueB: "Š_three-panel____ä",
				thirdTitle: "Š_basemap___ä",
				thirdValueLoading: "Š_Loading____ä...",
				thirdValueUnknown: "Š_unknown___ä"
			},
			mapSeries: {
				firstTitleA: "Š_bullets___ä",
				firstTitleB: "Š_sections___ä",
				firstTitleC: "Š_tabs__ä",
				secondTitle: "Š_style___ä",
				secondValueA: "Š_bulleted___ä",
				secondValueB: "Š_side accordion_____ä",
				secondValueC: "Š_tabbed___ä",
				thirdTitle: "Š_maps__ä"
			},
			swipeSpyglass: {
				firstTitle: "Š_points of interest______ä",
				secondTitle: "Š_style___ä",
				secondValueA: "Š_swipe___ä",
				secondValueB: "Š_spyglass___ä",
				thirdTitle: "Š_maps__ä"
			}
		},
		progress: {
			checkingStories: "Š_Checking your stories for issues____________ä...",
			stop: "Š_Stop__ä",
			exit: "Š_Exit__ä",
			dismiss: "Š_Dismiss___ä",
			done: "Š_Done___ä.",
			noStoriesWithIssuesLower: "Š_No issues found______ä!",
			storiesErrorFree: "Š_Looks like your stories are error-free____________ä",
			scanAllError: "Š_Unable to scan -- we couldn't retrieve one or more of your stories_____________________ä",
			scanProgress: "Š_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________ä",
			scanStopped: "Š_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________ä",
			storiesWithIssues: "Š_Stories with issues: {{NUM_STORIES}}____________ä"
		}
    })
);