define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Webkort",
				lblLocation: "Placering",
				lblContent: "Indhold",
				lblPopup: "Pop-up",
				lblControls: "Ekstra",
				lblOverview: "Oversigtskort",
				lblLegend: "Signaturforklaring",
				loadingTitle: "Indlæser titel",
				entry: "Post",
				entries: "Poster",
				section: "Sektion",
				sections: "Sektioner",
				and: "og",
				action: "Handling i sektion",
				actions: "Handling i sektioner",
				originalWebmap: "Webkort, der blev brugt til at publicere %TPL_NAME%",
				browseMaps: "Gennemse for at finde kort",
				current: "Aktuelt webkort",
				select: "Vælg et webkort",
				newMap: "Webkort, der er valgt for nylig",
				webmapDefault: "Standard-webkort",
				customCfg: "Tilpasset konfiguration",
				tooltipLocation: "Definér den position, som kortet skal vise.",
				tooltipContent: "Definér synlige lag.",
				tooltipPopup: "Vælg en pop-up, der skal åbnes, når kortet bliver vist.",
				tooltipOverview: "Vis et lille oversigtskort langs med hovedkortet.",
				tooltipLegend: "Få vist signaturforklaringen på kortet. Dette er nyttigt, når kortet har mange lag og symboler.",
				mapCfgInvite: "Brug disse knapper til at konfigurere kortet",
				lblLocationAlt: "Arvet fra det første kort",
				tooltipLocationAlt: "Kortets placering synkroniseres med det første kort i serien. Hvis du vil ændre din series funktionsmåde, skal du gå til Indstillinger > Kortindstillinger."
			},
			configure: {
				btnReset: "Nulstil",
				btnCancel: "Annullér",
				tocTitle: "Kortindhold",
				tocExplain: "Vælg, hvilke lag de skal vises.",
				tocNoData: "Ingen lag kan konfigureres.",
				tocSave: "Gem kortindhold",
				extentTitle: "Kortposition",
				extentExplain: "Panorér og zoom kortet for at definere, hvordan det skal vises for læserne.",
				extentSave: "Gem kortposition",
				popupTitle: "Kort-pop-up",
				popupExplain: "Klik på et objekt for at åbne den pop-up, du vil have vist",
				popupSave: "Gem pop-up-konfiguration",
				hintNavigation: "Kortnavigation er deaktiveret."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "Min organisation",
					onlineLabel: "ArcGIS Online",
					contentLabel: "Mit indhold",
					favoritesLabel: "Mine favoritter"
				},
				title: "Vælg webkort",
				searchTitle: "Søg",
				ok: "OK",
				cancel: "Annullér",
				placeholder: "Indtast en søgeterm eller et webkort-ID..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
