define({
  root: ({
    layer: "Ж_Layer___Я",
    sort: "Ж_Sort by___Я",
    order: "Ж_Order___Я",
    desc: "Ж_Desc__Я",
    asc: "Ж_Asc__Я",
    loading: "Ж_loading&hellip;______Я",
    search: "Ж_Search___Я",
    searchPlaceholder: "Ж_Find reports_____Я",
    noResults: "Ж_No results____Я",
    ascending: "Ж_Ascending____Я",
    descending: "Ж_Descending____Я"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});