define(
     ({
        map: {
            error: "Не удалось создать карту"
        },
        onlineStatus: {
            offline: "В настоящее время вы работаете в автономном режиме. Форма представления будет сохранена локально до тех пор, пока не будет выполнено подключение к серверу.",
            reconnecting: "Повторное подключение&hellip;",
            pending: "${total} ожидающих исправлений будет выполнено после восстановления подключения к сети."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Моя организация",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Мои ресурсы",
                    favoritesLabel: "Мое избранное"
                },
                title: "Выберите веб-карту",
                searchTitle: "Поиск",
                ok: "Ok",
                cancel: "Отмена",
                placeholder: "Введите текст поиска"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Моя организация",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Мои ресурсы",
                    favoritesLabel: "Мое избранное"
                },
                title: "Выберите группу",
                searchTitle: "Поиск",
                ok: "Ok",
                cancel: "Отмена",
                placeholder: "Введите текст поиска"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Ж_Here is a link to a GeoForm_Я"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "По широте",
            utm_easting: "По долготе",
            utm_zone_number: "Номер зоны",
            geoFormGeneralTabText: "1. Введите информацию",
            locationInformationText: "2. Выберите местоположение",
            submitInformationText: "3. Заполните форму",
            submitInstructions: "Добавьте эту информацию в карту.",
            myLocationText: "Текущее местоположение",
            locationDescriptionForMoreThanOneOption: "Ж_Specify the location for this entry by clicking/tapping the map or by using one of the following options_Я.",
            locationDescriptionForOneOption: "Ж_Specify the location for this entry by clicking/tapping the map or by using the following option_Я.",
            locationDescriptionForNoOption: "Ж_Specify the location for this entry by clicking/tapping the map_Я.",
            addressText: "Поиск",
            geographic: "Широта/Долгота",
            locationTabText: "Местоположение",
            locationPopupTitle: "Местоположение",
            submitButtonText: "Отправить запись",
            submitButtonTextLoading: "Подтверждение&hellip;",
            formValidationMessageAlertText: "Следующие поля являются обязательными:",
            selectLocation: "Ж_Please select a location for your submission_Я.",
            emptylatitudeAlertMessage: "Введите координаты ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Введите координату ${openLink}долготы${closeLink}.",
            shareUserTitleMessage: "Спасибо за ваше участие!",
            entrySubmitted: "Ваша запись отправлена на карту.",
            shareThisForm: "Опубликовать эту форму",
            shareUserTextMessage: "Рассказать другим  при помощи следующих опций.",
            addAttachmentFailedMessage: "Невозможно добавить вложения к слою",
            addFeatureFailedMessage: "Невозможно добавить объект в слой",
            noLayerConfiguredMessage: "Ж_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_Я.",
            placeholderLatitude: "Широта (Y)",
            placeholderLongitude: "Долгота (X)",
            latitude: "Широта",
            longitude: "Долгота",
            findMyLocation: "Найти мое местоположение",
            finding: "Поиск местоположения&hellip;",
            backToTop: "Наверх",
            addressSearchText: "Ваша запись появится здесь. Вы можете перетащить булавку в желаемое местоположение.",
            shareModalFormText: "Ссылка на форму",
            close: "Закрыть",
            locationNotFound: "Невозможно найти местоположение.",
            setLocation: "Задать местоположение",
            find: "Найти адрес или место",
            attachment: "Вложение",
            toggleDropdown: "Сброс",
            invalidString: "Ж_Please enter valid value_Я.",
            invalidSmallNumber: "Ж_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_Я.",
            invalidNumber: "Ж_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_Я.",
            invalidFloat: "Ж_Please enter valid ${openStrong}floating point${closeStrong} value_Я.",
            invalidDouble: "Ж_Please enter valid ${openStrong}double${closeStrong} value_Я.",
            invalidLatLong: "Ж_Please enter valid latitude and longitude coordinates_Я.",
            invalidUTM: "Ж_Please enter valid UTM coordinates_Я.",
            invalidUSNG: "Ж_Please enter valid USNG coordinates_Я.",
            invalidMGRS: "Ж_Please enter valid MGRS coordinates_Я.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Выбор&hellip;",
            applyEditsFailedMessage: "Не удалось отправить введенные данные. Повторите попытку.",
            requiredFields: "Имеется несколько ошибок. Пожалуйста, исправьте их.",
            requiredField: "(обязательно)",
            error: "Ошибка",
            textRangeHintMessage: "${openStrong}Подсказка:${closeStrong} Минимальное значение ${minValue} и Максимальное значение ${maxValue}",
            dateRangeHintMessage: "${openStrong}Подсказка:${closeStrong} Минимальная дата ${minValue} и Максимальная дата ${maxValue}",
            remainingCharactersHintMessage: "Ж_${value} characters remaining_Я"
        },
        builder: {
            invalidUser: "У вас нет прав на просмотр этого элемента",
            invalidWebmapSelectionAlert: "На выбранной карте нет допустимого для использования слоя. Добавьте редактируемый FeatureLayer на вашу веб-карту для продолжения.",
            invalidWebmapSelectionAlert2: "За подробной информацией обратитесь к ${openLink}Что такое сервис пространственных объектов?${closeLink}",
            selectFieldsText: "Выберите поля формы",
            selectThemeText: "Выберите тему формы",
            webmapText: "Веб-карта",
            layerText: "Слой",
            detailsText: "Детали",
            fieldsText: "Поля",
            styleText: "Стиль",
            optionText: "Опции",
            previewText: "Просмотр",
            publishText: "Опубликовать",
            optionsApplicationText: "Опции",
            titleText: "Конструктор",
            descriptionText: "Ж_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_Я.",
            btnPreviousText: "Предыдущий",
            btnNextText: "Следующий",
            webmapTabTitleText: "Выбрать веб-карту",
            viewWebmap: "Просмотреть веб-карту",
            webmapDetailsText: "Ж_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_Я",
            btnSelectWebmapText: "Выбрать веб-карту",
            btnSelectWebmapTextLoading: "Загрузка&hellip (Loading&hellip);",
            layerTabTitleText: "Выбрать редактируемый слой",
            selectLayerLabelText: "Слой",
            selectLayerDefaultOptionText: "Выбрать слой",
            detailsTabTitleText: "Детали формы",
            detailTitleLabelText: "Заголовок",
            detailLogoLabelText: "Изображение логотипа",
            descriptionLabelText: "Ж_Form Instructions & Details_Я",
            fieldDescriptionLabelText: "Ж_Help Text (optional)_Я",
            fieldTabFieldHeaderText: "Поле",
            fieldTabLabelHeaderText: "Надпись",
            fieldTabDisplayTypeHeaderText: "Отобразить как",
            fieldTabOrderColumnText: "Ж_Order_Я",
            fieldTabVisibleColumnText: "Ж_Enabled_Я",
            selectMenuOption: "Выбрать меню",
            selectRadioOption: "Переключатель",
            selectTextOption: "Текст",
            selectDateOption: "Ж_Date Picker_Я",
            selectRangeOption: "Ж_Touch-Spinner_Я",
            selectCheckboxOption: "Окошко метки",
            selectMailOption: "Email",
            selectUrlOption: "URL-адрес",
            selectTextAreaOption: "Ж_Text Area_Я",
            previewApplicationText: "Просмотр приложения",
            saveApplicationText: "Сохранить приложение",
            saveText: "Сохранить",
            toggleNavigationText: "Переключение навигации",
            formPlaceholderText: "Моя форма",
            shareBuilderInProgressTitleMessage: "Публикация GeoForm",
            shareBuilderProgressBarMessage: "Пожалуйста, подождите...",
            shareBuilderTitleMessage: "Успешно! Элемент сохранен",
            shareBuilderTextMessage: "Открытие общего доступа - первый шаг для старта сбора информации",
            shareModalFormText: "Ссылка на форму",
            shareBuilderSuccess: "Ваш GeoForm был изменен и опубликован!",
            geoformTitleText: "Geo Form",
            layerTabText: "Из этого слоя будет построен GeoForm. Слой должен быть сервисом объектов, который допускает редактирование и предоставление общего доступа для вашей аудитории.",
            detailsTabText: "С помощью текстовых окон страницы Детали формы, настройте заголовок, добавьте собственный логотип и краткое описание для аудитории GeoForm. В описании вы можете добавить ссылки на другие ресурсы, контактную информацию и даже доступ к картографическому веб-приложению, где используются все данные, собранные с помощью  GeoForm.",
            fieldsTabText: "Здесь вы можете выбрать, какие поля будут видны для вашей аудитории GeoForm, измените отображаемые надписи, и добавьте краткое описание в справку, которая сопровождает данные.",
            styleTabText: "Оформите ваш GeoForm, выбрав тему из представленных ниже.",
            publishTabText: "Если вы завершили настройку вашего GeoForm, сохраните приложение и откройте общий доступ к нему для вашей аудитории. Вы можете всегда вернуться к конструктору и продолжить настройку, на основе отзывов.",
            headerSizeLabel:"Ж_Header Size_Я",
            smallHeader: "Используйте небольшой колонтитул",
            bigHeader: "Ж_Use Large Header_Я",
            pushpinText: "Кнопка",
            doneButtonText: "Ж_Save and Exit_Я",
            fieldTabPlaceHolderHeaderText: "Подсказка (дополнительно)",
            enableAttachmentLabelText: "Ж_${openStrong}Enable Attachments${closeStrong}_Я",
            enableAttachmentLabelHint: "Ж_You can enable/disable the attachments here_Я",
            attachmentIsRequiredLabelText: "Ж_${openStrong}Attachment Required${closeStrong}_Я",
            attachmentIsRequiredLabelHint: "Ж_If necessary, users can be required to enter an attachment_Я.",
            attachmentLabelText: "Ж_Attachment Button Label_Я",
            attachmentLabelHint: "Ж_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_Я",
            attachmentDescription: "Описание вложения",
            attachmentHint: "При необходимости вы можете предоставить дополнительные инструкции к вложению здесь.",
            jumbotronDescription: "Ж_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_Я",
            shareGeoformText: "Опубликовать Geoform",
            shareDescription: "Панель общего доступа позволяет вашей аудитории быстро предоставлять доступ к GeoForm своим сотрудникам, выполнившим вход - эту опцию в любой момент можно отключить.",
            defaultMapExtent: "Экстент карты по умолчанию",
            defaultMapExtentDescription: "После входа карта будет переключена к экстенту веб-карты по умолчанию - эту опцию в любой момент можно отключить.",
            pushpinOptionsDescription: "Для кнопки на карте можно выбрать любой их множества цветов, он должен отличаться от символов на карте, что облегчает пользователю нанесение на карту собственных знаков",
            selectLocationText: "Выбрать местоположение по",
            myLocationText: "Мое местоположение",
            searchText: "Поиск",
            coordinatesText: "Координаты широты-долготы",
            usng: "Координаты USNG",
            mgrs: "Координаты MGRS",
            utm: "Координаты UTM",
            selectLocationSDescription: "Позволяет выбирать местоположения одним из этих методов.",
            dragTooltipText:"Ж_Drag the field where you want it to appear_Я",
            showHideLayerText:"Ж_Show/Hide Layer_Я",
            showHideLayerHelpText:"Ж_You can configure the GeoForm to Show/Hide Layer_Я"
        }
    })
);