define(
   ({
    map: {
      error: "Ж_Unable to create map_Я"
    },
    onlineStatus: {
      offline: "Ж_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_Я.",
      reconnecting: "Ж_Reconnecting&hellip;_Я",
      pending: "Ж_${total} pending edit(s) will be submitted when a network connection is re-established_Я."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Ж_My Organization_Я",
          onlineLabel: "Ж_ArcGIS Online_Я",
          contentLabel: "Ж_My Content_Я",
          favoritesLabel: "Ж_My Favorites_Я"
        },
        title: "Ж_Select Web Map_Я",
        searchTitle: "Ж_Search_Я",
        ok: "Ж_Ok_Я",
        cancel: "Ж_Cancel_Я",
        placeholder: "Ж_Enter search term_Я"
      },
      groupdlg: {
        items: {
          organizationLabel: "Ж_My Organization_Я",
          onlineLabel: "Ж_ArcGIS Online_Я",
          contentLabel: "Ж_My Content_Я",
          favoritesLabel: "Ж_My Favorites_Я"
        },
        title: "Ж_Select Group_Я",
        searchTitle: "Ж_Search_Я",
        ok: "Ж_Ok_Я",
        cancel: "Ж_Cancel_Я",
        placeholder: "Ж_Enter search term_Я"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Ж_Here is a link to a GeoForm_Я"
      }
    },
    user: {
      mgrs: "Ж_MGRS_Я",
      usng: "Ж_USNG_Я",
      utm: "Ж_UTM_Я",
      utm_northing: "Ж_Northing_Я",
      utm_easting: "Ж_Easting_Я",
      utm_zone_number: "Ж_Zone Number_Я",
      selectLayerTabText: "Ж_${formSection} Select Form_Я",
      geoFormGeneralTabText: "Ж_${formSection} Enter Information_Я",
      locationInformationText: "Ж_${formSection} Select Location_Я",
      submitInformationText: "Ж_${formSection} Complete Form_Я",
      submitInstructions: "Ж_Add this information to the map_Я.",
      myLocationText: "Ж_Current Location_Я",
      locationDescriptionForMoreThanOneOption: "Ж_Specify the location for this entry by clicking/tapping the map or by using one of the following options_Я.",
      locationDescriptionForOneOption: "Ж_Specify the location for this entry by clicking/tapping the map or by using the following option_Я.",
      locationDescriptionForNoOption: "Ж_Specify the location for this entry by clicking/tapping the map_Я.",
      addressText: "Ж_Search_Я",
      geographic: "Ж_Lat/Lon_Я",
      locationTabText: "Ж_Location_Я",
      locationPopupTitle: "Ж_Location_Я",
      submitButtonText: "Ж_Submit Entry_Я",
      submitButtonTextLoading: "Ж_Submitting&hellip;_Я",
      formValidationMessageAlertText: "Ж_The following fields are required_Я:",
      selectLocation: "Ж_Please select a location for your submission_Я.",
      emptylatitudeAlertMessage: "Ж_Please enter a ${openLink}latitude${closeLink} coordinate_Я.",
      emptylongitudeAlertMessage: "Ж_Please enter a ${openLink}longitude${closeLink} coordinate_Я.",
      shareUserTitleMessage: "Ж_Thank you for your contribution_Я!",
      entrySubmitted: "Ж_Your entry has been submitted to the map_Я.",
      shareThisForm: "Ж_Share This Form_Я",
      shareUserTextMessage: "Ж_Tell others to contribute using the following options_Я.",
      addAttachmentFailedMessage: "Ж_Unable to add attachment to layer_Я",
      addFeatureFailedMessage: "Ж_Unable to add feature to layer_Я",
      noLayerConfiguredMessage: "Ж_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_Я.",
      placeholderLatitude: "Ж_Latitude (Y)_Я",
      placeholderLongitude: "Ж_Longitude (X)_Я",
      latitude: "Ж_Latitude_Я",
      longitude: "Ж_Longitude_Я",
      findMyLocation: "Ж_Locate Me_Я",
      finding: "Ж_Locating&hellip;_Я",
      backToTop: "Ж_Back to top_Я",
      addressSearchText: "Ж_Your submission will appear here. You can drag the pin to correct the location_Я.",
      shareModalFormText: "Ж_Form Link_Я",
      close: "Ж_Close_Я",
      locationNotFound: "Ж_Location could not be found_Я.",
      setLocation: "Ж_Set Location_Я",
      find: "Ж_Find address or place_Я",
      attachment: "Ж_Attachment_Я",
      toggleDropdown: "Ж_Toggle Dropdown_Я",
      invalidString: "Ж_Please enter valid value_Я.",
      invalidSmallNumber: "Ж_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_Я.",
      invalidNumber: "Ж_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_Я.",
      invalidFloat: "Ж_Please enter valid ${openStrong}floating point${closeStrong} value_Я.",
      invalidDouble: "Ж_Please enter valid ${openStrong}double${closeStrong} value_Я.",
      invalidLatLong: "Ж_Please enter valid latitude and longitude coordinates_Я.",
      invalidUTM: "Ж_Please enter valid UTM coordinates_Я.",
      invalidUSNG: "Ж_Please enter valid USNG coordinates_Я.",
      invalidMGRS: "Ж_Please enter valid MGRS coordinates_Я.",
      geoformTitleText: "Ж_GeoForm_Я",
      domainDefaultText: "Ж_Select&hellip;_Я",
      applyEditsFailedMessage: "Ж_Sorry your entry cannot be submitted. Please try again_Я.",
      requiredFields: "Ж_There are some errors. Please correct them below_Я.",
      requiredField: "Ж_(required)_Я",
      error: "Ж_Error_Я",
      textRangeHintMessage: "Ж_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_Я",
      dateRangeHintMessage: "Ж_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_Я",
      remainingCharactersHintMessage: "Ж_${value} characters remaining_Я",
      mapFullScreen: "Ж_Full Screen_Я",
      mapRestore: "Ж_Restore_Я",
      filterSelectEmptyText: "Ж_Select_Я",
      invalidLayerMessage: "Ж_Form layer does not exist. Please configure the application and set the layer_Я.",
      selectedLayerText: "Ж_All_Я",
      fileUploadStatus: "Ж_File Upload Status_Я",
      uploadingBadge: "Ж_&nbsp;Uploading&hellip;_Я",
      successBadge: "Ж_&nbsp;Uploaded_Я",
      retryBadge: "Ж_Retry_Я",
      errorBadge: "Ж_Error uploading&nbsp;&nbsp;&nbsp;_Я",
      fileTooLargeError: "Ж_File too large to attach_Я",
      exceededFileCountError: "Ж_Exceeded maximum no. of attachments allowed_Я",
      selectFileTitle: "Ж_Select a file_Я",
      btnViewSubmissions: "Ж_View Submissions_Я"
    },
    builder: {
      invalidUser: "Ж_Sorry, you don't have permission to view this item_Я",
      invalidWebmapSelectionAlert: "Ж_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_Я.",
      invalidWebmapSelectionAlert2: "Ж_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_Я",
      selectFieldsText: "Ж_Select Form Fields_Я",
      selectThemeText: "Ж_Select Form Theme_Я",
      webmapText: "Ж_Webmap_Я",
      layerText: "Ж_Layer_Я",
      detailsText: "Ж_Details_Я",
      fieldsText: "Ж_Fields_Я",
      styleText: "Ж_Style_Я",
      optionText: "Ж_Options_Я",
      previewText: "Ж_Preview_Я",
      publishText: "Ж_Publish_Я",
      optionsApplicationText: "Ж_Options_Я",
      titleText: "Ж_Builder_Я",
      descriptionText: "Ж_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_Я.",
      btnPreviousText: "Ж_Previous_Я",
      btnNextText: "Ж_Next_Я",
      webmapTabTitleText: "Ж_Select a Webmap_Я",
      viewWebmap: "Ж_View webmap_Я",
      webmapDetailsText: "Ж_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_Я",
      btnSelectWebmapText: "Ж_Choose Webmap_Я",
      btnSelectWebmapTextLoading: "Ж_Loading&hellip;_Я",
      layerTabTitleText: "Ж_Select Editable Layer_Я",
      selectLayerLabelText: "Ж_Layer_Я",
      selectLayerDefaultOptionText: "Ж_Select Layer_Я",
      defaultBasemap: "Ж_Basemap Toggle_Я",
      secondaryBasemap: "Ж_Default Basemap_Я",
      detailsTabTitleText: "Ж_Form Details_Я",
      detailTitleLabelText: "Ж_Title_Я",
      detailLogoLabelText: "Ж_Logo Image_Я",
      descriptionLabelText: "Ж_Form Instructions & Details_Я",
      fieldDescriptionLabelText: "Ж_Help Text (optional)_Я",
      fieldTabFieldHeaderText: "Ж_Field_Я",
      fieldTabLabelHeaderText: "Ж_Label_Я",
      fieldTabDisplayTypeHeaderText: "Ж_Display As_Я",
      fieldTabOrderColumnText: "Ж_Order_Я",
      fieldTabVisibleColumnText: "Ж_Enabled_Я",
      displayFieldText: "Ж_Display Field_Я",
      selectMenuOption: "Ж_Select Menu_Я",
      selectRadioOption: "Ж_Radio Button_Я",
      selectTextOption: "Ж_Text_Я",
      selectDateOption: "Ж_Date Picker_Я",
      selectRangeOption: "Ж_Touch-Spinner_Я",
      selectCheckboxOption: "Ж_Checkbox_Я",
      selectMailOption: "Ж_Email_Я",
      selectUrlOption: "Ж_URL_Я",
      selectTextAreaOption: "Ж_Text Area_Я",
      previewApplicationText: "Ж_Preview Application_Я",
      saveApplicationText: "Ж_Save Application_Я",
      saveText: "Ж_Save_Я",
      toggleNavigationText: "Ж_Toggle navigation_Я",
      formPlaceholderText: "Ж_My Form_Я",
      shareBuilderInProgressTitleMessage: "Ж_Publishing GeoForm_Я",
      shareBuilderProgressBarMessage: "Ж_Please Wait&hellip;_Я",
      shareBuilderTitleMessage: "Ж_Success! Item saved_Я",
      shareBuilderTextMessage: "Ж_You can start collecting information by sharing with others_Я",
      shareModalFormText: "Ж_Form Link_Я",
      shareBuilderSuccess: "Ж_Your GeoForm has been updated & published_Я!",
      geoformTitleText: "Ж_Geo Form_Я",
      layerTabText: "Ж_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_Я.",
      detailsTabText: "Ж_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_Я.",
      fieldsTabText: "Ж_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_Я.",
      styleTabText: "Ж_Style your GeoForm using the themes below based on your preference_Я.",
      publishTabText: "Ж_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_Я.",
      headerSizeLabel: "Ж_Header Size_Я",
      smallHeader: "Ж_Use Small Header_Я",
      bigHeader: "Ж_Use Large Header_Я",
      pushpinText: "Ж_Push pin_Я",
      doneButtonText: "Ж_Save and Exit_Я",
      fieldTabPlaceHolderHeaderText: "Ж_Hint (optional)_Я",
      enableAttachmentLabelText: "Ж_${openStrong}Enable Attachments${closeStrong}_Я",
      enableAttachmentLabelHint: "Ж_You can enable/disable the attachments here_Я",
      attachmentIsRequiredLabelText: "Ж_${openStrong}Attachment Required${closeStrong}_Я",
      attachmentIsRequiredLabelHint: "Ж_If necessary, users can be required to enter an attachment_Я.",
      attachmentLabelText: "Ж_Attachment Button Label_Я",
      attachmentLabelHint: "Ж_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_Я",
      attachmentDescription: "Ж_Attachment Description_Я",
      attachmentHint: "Ж_If necessary, you can provide additional attachment instructions here_Я.",
      jumbotronDescription: "Ж_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_Я",
      shareGeoformText: "Ж_Share Geoform_Я",
      shareDescription: "Ж_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_Я.",
      defaultMapExtent: "Ж_Default Map Extent_Я",
      defaultMapExtentDescription: "Ж_The map will reset to the default extent in your web map after submission - this can be disabled at any time_Я.",
      pushpinOptionsDescription: "Ж_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_Я",
      selectLocationText: "Ж_Select Location By_Я",
      myLocationText: "Ж_My Location_Я",
      searchText: "Ж_Search_Я",
      coordinatesText: "Ж_Latitude & Longitude Coordinates_Я",
      usng: "Ж_USNG Coordinates_Я",
      mgrs: "Ж_MGRS Coordinates_Я",
      utm: "Ж_UTM Coordinates_Я",
      selectLocationSDescription: "Ж_Allow users to select a location using these methods_Я.",
      dragTooltipText: "Ж_Drag the field where you want it to appear_Я",
      showHideLayerText: "Ж_Show Layer_Я",
      showHideLayerHelpText: "Ж_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_Я.",
      labelHelpMessage: "Ж_Label_Я",
      placeHolderHintMessage: "Ж_Hint Text_Я",
      placeHolderHelpMessage: "Ж_Help Text_Я",
      selectTextOptionValue: "Ж_Filter Select_Я",
      disableLogo: "Ж_Disable Logo_Я",
      disableLogoDescription: "Ж_You can configure the GeoForm to Show/Hide the Logo in the form header_Я",
      locateOnLoadText: "Ж_Locate On Load_Я",
      locateOnLoadDescription: "Ж_You can configure the GeoForm to use the current location on page load_Я",
      selectLayerFieldTabText: "Ж_Select Layer_Я",
      allLayerSelectOptionText: "Ж_All_Я",
      disableViewer: "Ж_Disable Viewer_Я",
      disableViewerDescription: "Ж_You can configure the GeoForm to disable/enable Viewer_Я",
      displayFieldHintText: "Ж_Selected display field will be shown in viewerMode as title field_Я"
    },
    viewer: {
      geocoderCancelText: "Ж_Cancel_Я",
      viewReportsTabText: "Ж_Submissions_Я",
      viewLegendTabText: "Ж_Legend_Я",
      viewAboutusTabText: "Ж_About_Я",
      viewMapTabText: "Ж_Map_Я",
      sortHeaderText: "Ж_Sort By_Я:",
      btnSubmitReportText: "Ж_Submit a Report_Я",
      geocoderPlaceholderText: "Ж_Zip Code, city, etc_Я.",
      noSearchResult: "Ж_No result found_Я",
      recordsTabTooltip: "Ж_View Submissions_Я",
      legendTabTooltip: "Ж_Legend_Я",
      aboutUsTabTooltip: "Ж_AboutUs_Я",
      mapTabTooltip: "Ж_Map_Я",
      appLoadingFailedMessage: "Ж_ViewerMode is Unavailable_Я",
      btnDescendingText: "Ж_Desc_Я",
      btnAscendingText: "Ж_Asc_Я",
      geometryUnavailableErrorMessage: "Ж_Unable to find the geometry of the feature_Я",
      infoPopupOffErrorMessage: "Ж_InfoPopup is off_Я",
      btnLoadMoreText: "Ж_Load More_Я",
      unavailableTitleText: "Ж_Untitled_Я",
      unavailableConfigMessage: "Ж_Unable to load config_Я"
    }
  })
);