define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Veebikaart",
				lblLocation: "Asukoht",
				lblContent: "Sisu",
				lblPopup: "Hüpikaken",
				lblControls: "Lisandid",
				lblOverview: "Ülevaatekaart",
				lblLegend: "Legend",
				loadingTitle: "Pealkirja laadimine",
				entry: "Sissekanne",
				entries: "Sissekanded",
				section: "Jaotis",
				sections: "Jaotised",
				and: "ja",
				action: "Toiming jaotises",
				actions: "Toiming jaotistes",
				originalWebmap: "Veebikaart, mille abil %TPL_NAME% avaldati",
				browseMaps: "Sirvi kaarte",
				current: "Praegune veebikaart",
				select: "Valige veebikaart",
				newMap: "Vastvalitud veebikaart",
				webmapDefault: "Veebikaardi vaikeseade",
				customCfg: "Kohandatud konfiguratsioon",
				tooltipLocation: "Määratlege sellel kaardil kuvatav asukoht.",
				tooltipContent: "Määratlege nähtavad kihid.",
				tooltipPopup: "Valige hüpikaken, mis avaneb selle kaardi kuvamisel.",
				tooltipOverview: "Kuvage koos peamise kaardiga väike ülevaatekaart.",
				tooltipLegend: "Kuva kaardil legend, millest on abi siis, kui kaardil on palju kihte ja sümboleid.",
				mapCfgInvite: "Nende juhtelementide abil saate kaardi konfigureerida",
				lblLocationAlt: "Pärineb esimeselt kaardilt",
				tooltipLocationAlt: "Selle kaardi asukoht sünkroniseeritakse sarja esimese kaardiga. Selle toimingu muutmiseks seeria puhul valige Seaded > Kaardi valikud."
			},
			configure: {
				btnReset: "Lähtesta",
				btnCancel: "Tühista",
				tocTitle: "Kaardi sisu",
				tocExplain: "Valige kuvatavad kihid.",
				tocNoData: "Kihti ei saa konfigureerida.",
				tocSave: "Salvesta kaardi sisu",
				extentTitle: "Kaardi asukoht",
				extentExplain: "Saate kaarti liigutada ja suumida, et määrata selle kuvamine lugejatele.",
				extentSave: "Salvesta kaardi asukoht",
				popupTitle: "Kaardi hüpikaken",
				popupExplain: "Klikkige objekti, et avada hüpikaken, mida soovite kuvada.",
				popupSave: "Salvesta hüpikakna konfiguratsioon",
				hintNavigation: "Kaardil navigeerimine on välja lülitatud."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "Minu organisatsioon",
					onlineLabel: "ArcGIS Online",
					contentLabel: "Minu sisu",
					favoritesLabel: "Minu lemmikud"
				},
				title: "Vali veebikaart",
				searchTitle: "Otsi",
				ok: "Ok",
				cancel: "Tühista",
				placeholder: "Sisestage otsingutermin või veebikaardi ID..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
