define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Webkart",
				lblLocation: "Lokasjon",
				lblContent: "Innhold",
				lblPopup: "Sprettoppvindu",
				lblControls: "Tillegg",
				lblOverview: "Oversiktskart",
				lblLegend: "Tegnforklaring",
				loadingTitle: "Laster inn tittel",
				entry: "Oppføring",
				entries: "Oppføringer",
				section: "Seksjon",
				sections: "Seksjoner",
				and: "og",
				action: "Handling i seksjon",
				actions: "Handling i seksjoner",
				originalWebmap: "Webkart brukt til å publisere %TPL_NAME%",
				browseMaps: "Bla igjennom kart",
				current: "Gjeldende webkart",
				select: "Velg et webkart",
				newMap: "Nylig valgt webkart",
				webmapDefault: "Webkartstandard",
				customCfg: "Tilpasset konfigurasjon",
				tooltipLocation: "Definer lokasjonen som skal vises på dette kartet.",
				tooltipContent: "Definer de synlige lagene.",
				tooltipPopup: "Velg en popup som skal åpnes når dette kartet vises.",
				tooltipOverview: "Vis et lite oversiktskart sammen med hovedkartet.",
				tooltipLegend: "Vis kartets tegnforklaring, som er nyttig når kartet har mange lag og symboler.",
				mapCfgInvite: "Bruk disse kontrollene til å konfigurere kartet",
				lblLocationAlt: "Hentet fra det første kartet",
				tooltipLocationAlt: "Lokasjonen på dette kartet synkroniseres med det første kartet i serien. Hvis du vil endre denne innstillingen for serien, går du til Innstillinger > Kartalternativer."
			},
			configure: {
				btnReset: "Tilbakestill",
				btnCancel: "Avbryt",
				tocTitle: "Kartinnhold",
				tocExplain: "Velg hvilke lag som skal vises.",
				tocNoData: "Ingen lag kan konfigureres.",
				tocSave: "Lagre kartinnhold",
				extentTitle: "Kartlokasjon",
				extentExplain: "Panorer og zoom på kartet for å definere hvordan det skal se ut for leserne.",
				extentSave: "Lagre kartlokasjon",
				popupTitle: "Sprettoppvindu for kart",
				popupExplain: "Klikk på et geoobjekt for å åpne sprettoppvinduet du vil vise",
				popupSave: "Lagre konfigurasjonen av sprettoppvinduet",
				hintNavigation: "Kartnavigasjon er deaktivert."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "Min organisasjon",
					onlineLabel: "ArcGIS Online",
					contentLabel: "Mitt innhold",
					favoritesLabel: "Mine favoritter"
				},
				title: "Velg webkart",
				searchTitle: "Søk",
				ok: "Ok",
				cancel: "Avbryt",
				placeholder: "Skriv inn søkeord eller webkart-ID..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1,
	"zh-hk": 1, 
	"zh-tw": 1 
});
