define({
  "widgets": {
    "geoEnrichment": {
      "placeholder": {
        "enterValue": "Introducir distancia",
        "layerName": "Introducir nombre de capa aquí"
      },
      "message": {
        "analysisFailed": "Falló el análisis.",
        "errorOccurred": "Se ha producido algún error.",
        "layerAdded": "Capa agregada correctamente. ",
        "enrichLayerNameError": "El \"Nombre de la capa de resultados\" no debe contener caracteres no válidos(<,>,#,%,:,\",?,&,+,/,\\).",
        "creatingService": "Creando servicio... ",
        "starting": "Iniciando",
        "performingAnalysis": "Realizando análisis...",
        "checkLayerName": "Comprobando el nombre de capa... ",
        "addingLayer": "Adición de capa a mapa web ",
        "layerNameExist": "El nombre de capa ya existe.",
        "clickOnSave": " Haz clic en el botón \"Guardar\" para volver a cargar la aplicación.",
        "clickOnOk": " Haz clic en el botón \"Aceptar\" para volver a intentarlo.",
        "enterNumbersOnly": "Los valores introducidos no son válidos",
        "nofeatures": "No hay entidades en la extensión actual",
        "selectData": "Selecciona datos para enriquecer la capa.",
        "resetVariableMessage": "¿Estás seguro de que deseas restablecer la variable?",
        "emptyTextFieldLayerName": "Introducir nombre de la capa resultante",
        "createService": "Capa no creada.",
        "sharingLayer": "Compartiendo capa...",
        "updateItemFailed": "Error al actualizar. Vuelve a intentarlo.",
        "geoEnrichFailed": "Error al enriquecer la capa. Vuelve a intentarlo.",
        "shareFailed": "Error al compartir la capa enriquecida. Vuelve a intentarlo.",
        "refreshServiceFailed": "Error a actualizar la capa. Vuelve a intentarlo.",
        "layerJsonFailed": "Error al crear JSON para la capa. Vuelve a intentarlo.",
        "addToWebmapFailed": "Error al agregar la capa al mapa web. Vuelve a intentarlo.",
        "bufferAreaHelpText": "Introduce el valor menor que ",
        "invalidBufferInput": "El valor introducido no es válido.",
        "emptyBufferInput": "Introduce un valor válido."
      },
      "populationText": "Población",
      "housingText": "Hogares",
      "businessText": "Empresas",
      "variableListText": " las variables se incluyen aquí:",
      "countrySelectTitle": "1. Seleccionar ubicación de los datos",
      "unitedStates": "Estados Unidos",
      "global": "Global",
      "geoenrichDialogText": "Variables de geoenriquecimiento",
      "viewVariablestext": "Ver variables",
      "backButtonText": "Atrás",
      "customizeVariables": "Personalizar variables",
      "resetVariables": "Restablecer",
      "defineAreaTitle": "3. Definir el área que se va a enriquecer",
      "currentMapExtent": "Usar la extensión del mapa actual",
      "enrichLayerName": "4. Nombre de la capa de resultados",
      "lineDistanceText": "Distancia en línea recta",
      "drivingTime": "Tiempo de conducción",
      "enrichButtonText": "Enriquecer capa",
      "selectDataText": "2. Seleccionar datos",
      "showCreditsText": "Mostrar créditos",
      "variableCount": "Recuento total de variables ",
      "totalRecords": "Registros totales:",
      "cost": "Coste:",
      "showCreditsDialogText": "Mostrar créditos",
      "nextButtonText": "Siguiente",
      "prevButtonText": "Anterior",
      "saveButtonText": "Guardar",
      "ok": "Aceptar"
    }
  }
});