define(
     ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Entrar en Builder",
                "exitBuilderButtonText": "Salir de Builder",
                "enterBuilderModeHelpText": "Entra en el modo Builder para configurar la aplicación",
                "builderModeHelpText": "Modo Builder de plantilla",
                "webmapCaption": "Mapa",
                "selectMapMessage": "Actualmente ${displaying} <b>${webmapTitle}</b><br/>Haz clic en seleccionar mapa para elegir un mapa web diferente",
                "loadMapMessage": "Actualmente seleccionado <b>${webmapTitle}</b><br/>Haz clic en Guardar para usar este mapa web",
                "changeWebmap": "Seleccionar mapa",
                "saveButtonText": "Guardar",
                "webmapNextButtonText": "Siguiente ->",
                "previousButtonText":"Anterior",
                "layerLabelText": "Capa",
                "noLayerFoundText": "No se ha encontrado ninguna capa",
                "selectLayer": "Seleccionar capa",
                "applicationSettingText": "Configuración de la aplicación",
                "summaryAttrAscendingOrderTooltip": "Ascendente",
                "onStartLabel": "En el inicio",
                "selectVariableText": "Seleccionar la variable A",
                "selectVariableDropdown": "Seleccionar la variable A",
                "label":"Etiqueta",
                "sourceLinkText":"Enlace de origen",
                "selectSubVariableText":"Seleccionar subvariables",
                "subVariablePanelButtonText":"HECHO",
                "onButtonLabel":"Activar",
                "offButtonLabel":"Desactivar",
                "appSettingsSaveCloseButtonText": "GUARDAR Y CERRAR",
                "appSettingsTitleText":"Título de aplicación",
                "appSettingsDescriptionText": "Descripción de la aplicación",
                "appSetingsRendererAreaText":"Área presentada",
                "shareText":"Compartir",
                "basemapText":"Mapa base",
                "basemapSelectionText":"Selección de mapa base",
                "secondaryBasemapText":"Mapa base secundario",
                "defaultBasemapText": "Mapa base predeterminado",
                "entireAreaButton": "Área completa",
                "entireAreaOnStartButton": "Área completa en el inicio",
                "aboutPanel": "Acerca del panel",
                "legendPanel": "Panel de leyenda",
                "layersPanel": "Panel de capas",
                "dataConfigurationButtonText": "Configuración de datos",
                "savingChangesMessage": "Guardando cambios...",
                "nextButtonText": "Siguiente",
                "prevButtonText": "Anterior",
                "enterLabelText": "Introducir etiqueta",
                "SelectedFeatureText": "Entidad seleccionada",
                "layerHelpTextMessage": "Esta aplicación necesita una capa con campos numéricos",
                "alertMessage": {
                    "resetVariableMessage": "á_Are you sure you want to reset variable_Ó?",
                    "emptyAppTitleMessage": "El título de la aplicación no puede estar vacío",
                    "emptyDescriptionMessage": "La descripción no puede estar vacía",
                    "maxVariableSelection": "No puedes seleccionar más de 25 subvariables",
                    "signInFail" : "Error de inicio de sesión",
                    "itemUpdateMessage": "Elemento actualizado",
                    "unsavedChangesMessage": "Cambios no guardados",
                    "failMessage": "El elemento no se ha podido actualizar correctamente",
                    "saveChangesAlert": "¿Deseas guardar los cambios?",
                    "variableLabelValidation": "á_Variable label cannot be empty_Ó",
                    "subVariableLabelValidation": "á_Sub variable label cannot be empty_Ó"
                    }
            }
        }
    })
);