define({
    root: ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Entrar en Builder",
                "exitBuilderButtonText": "Salir de Builder",
                "enterBuilderModeHelpText": "Entra en el modo Builder para configurar la aplicación",
                "builderModeHelpText": "Modo Builder de plantilla",
                "webmapCaption": "Mapa",
                "selectMapMessage": "Actualmente ${displaying} <b>${webmapTitle}</b><br/>Haz clic en seleccionar mapa para elegir un mapa web diferente",
                "loadMapMessage": "Actualmente seleccionado <b>${webmapTitle}</b><br/>Haz clic en Guardar para usar este mapa web",
                "changeWebmap": "Seleccionar mapa",
                "saveButtonText": "Guardar",
                "webmapNextButtonText": "Siguiente ->",
                "previousButtonText":"Anterior",
                "layerLabelText": "Capa",
                "noLayerFoundText": "No se ha encontrado ninguna capa",
                "selectLayer": "Seleccionar capa",
                "applicationSettingText": "Configuración de la aplicación",
                "summaryAttrAscendingOrderTooltip": "Ascendente",
                "onStartLabel": "En el inicio",
                "selectVariableText": "Seleccionar la variable A",
                "selectVariableDropdown": "Seleccionar la variable A",
                "label":"Etiqueta",
                "sourceLinkText":"Enlace de origen",
                "selectSubVariableText":"Seleccionar subvariables",
                "subVariablePanelButtonText":"HECHO",
                "onButtonLabel":"Activar",
                "offButtonLabel":"Desactivar",
                "appSettingsSaveCloseButtonText": "GUARDAR Y CERRAR",
                "appSettingsTitleText":"Título de aplicación",
                "appSettingsDescriptionText": "Descripción de la aplicación",
                "appSetingsRendererAreaText":"Área presentada",
                "shareText":"Compartir",
                "popupText": "Elemento emergente",
                "basemapText":"Mapa base",
                "cancel": "Cancelar",
                "theme": "Tema",
                "zoomLevel": "Nivel de zoom",
                "existingValue": "Utilizar valores existentes",
                "enrichLayer": "Enriquecer capa",
                "imageLabel": "¿Cómo funciona esto?",
                "clearData": "Borrar datos",
                "basemapSelectionText":"Selección de mapa base",
                "secondaryBasemapText":"Mapa base secundario",
                "defaultBasemapText": "Mapa base predeterminado",
                "entireAreaButton": "Área completa",
                "entireAreaOnStartButton": "Área completa en el inicio",
                "aboutPanel": "Acerca del panel",
                "legendPanel": "Panel de leyenda",
                "layersPanel": "Panel de capas",
                "dataConfigurationButtonText": "Configuración de datos",
                "savingChangesMessage": "Guardando cambios...",
                "nextButtonText": "Siguiente",
                "prevButtonText": "Anterior",
                "enterLabelText": "Introducir etiqueta",
                "SelectedFeatureText": "Entidad seleccionada",
                "layerHelpTextMessage": "Esta aplicación necesita una capa con campos numéricos",
                "alertMessage": {
                    "resetVariableMessage": "¿Estás seguro de que deseas restablecer la variable?",
                    "emptyAppTitleMessage": "El título de la aplicación no puede estar vacío",
                    "emptyDescriptionMessage": "La descripción no puede estar vacía",
                    "maxVariableSelection": "No puedes seleccionar más de 25 subvariables",
                    "signInFail" : "Error de inicio de sesión",
                    "itemUpdateMessage": "Elemento actualizado",
                    "unsavedChangesMessage": "Cambios no guardados",
                    "failMessage": "El elemento no se ha podido actualizar correctamente",
                    "saveChangesAlert": "¿Deseas guardar los cambios?",
                    "variableLabelValidation": "La etiqueta de variable no puede estar vacía",
                    "subVariableLabelValidation": "La etiqueta de subvariable no puede estar vacía"
                    }
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});