define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "선택한 웹 맵에 사용할 유효 레이어가 없습니다. 계속하려면 편집 가능한 피처 레이어를 웹 맵에 추가하세요.",
            selectFieldsText:"양식 필드 선택",
            selectThemeText: "양식 테마 선택",
            fieldLabelPlaceHolder: "이 필드의 레이블 지정",
            fieldDescPlaceHolder: "이 필드에 대해 설명",
            webmapText: "1. 웹 맵",
            layerText: "2. 레이어",
            detailsText: "3. 세부정보",
            fieldsText: "4. 필드",
            styleText: "5. 스타일",
            previewText: "6. 미리보기",
            publishText: "7. 발행",
            titleText: "GeoForm 빌더",
            descriptionText: "GeoForm은 <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>피처 서비스</a>의 양식 기반 데이터 편집을 위해 구성 가능한 템플릿입니다. 이 응용프로그램으로 사용자는 mapâ€™의 팝업 대신 양식을 통해 데이터를 입력할 수 있으며 <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>웹 맵</a> 및 편집 가능 피처 서비스의 기능을 활용할 수 있습니다. 이 빌더를 사용하여 왼쪽 단계를 따라 GeoForm을 사용자 지정하고 배포합니다.",
            btnPreviousText: "이전",
            btnNextText:"다음",
            webmapTabTitleText: "웹 맵 선택",
            btnSelectWebmapText:"웹 맵 선택",
            layerTabTitleText: "편집 가능한 레이어 선택",
            selectLayerLabelText:"레이어",
            selectLayerDefaultOptionText:"레이어 선택",
            detailsTabTitleText:"양식 세부정보",
            detailTitleLabelText: "제목",
            detailLogoLabelText: "로고 이미지",
            detailDescriptionLabelText: "설명",
            fieldTabFieldHeaderText: "필드",
            fieldTabLabelHeaderText: "레이블",
            fieldTabTypeHeaderText: "유형",
            fieldTabDescriptionHeaderText: "설명",
            previewApplicationText: "응용프로그램 미리보기",
            saveApplicationText: "응용프로그램 저장",
            saveText: "저장",
            toggleNavigationText: "탐색 전환",
            formPlaceholderText: "내 양식",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "GeoForm 발행",
            shareBuilderProgressBarMessage:"기다려 주세요...",
            shareBuilderTitleMessage: "GeoForm이 업데이트 및 발행되었습니다!",
            shareBuilderTextMessage: "다른 사용자와 공유하여 정보 수집을 시작할 수 있습니다.",
            shareDialogFormText: "양식 링크",
            geoformTitleText: "GeoForm",
            layerTabText: "GeoForm이 구축되는 레이어입니다. 이 레이어는 대상 그룹에 적합한 공유 권한으로 편집할 수 있도록 설정된 피처 서비스여야 합니다.",
            detailsTabText:"아래의 양식 세부정보 상자를 사용하여 타일을 사용자 지정하고, 사용자 지정 로고를 추가하고, GeoForm 대상 그룹을 위한 간단한 설명을 제공합니다.",
            fieldsTabText:"여기서 GeoForm 대상 그룹에게 표시될 필드를 선택하고, 대상 그룹에게 표시될 레이블을 편집하고, 데이터 입력에 도움이 되는 간단한 설명을 추가할 수 있습니다.",
            styleTabText: "기본 설정을 기반으로 아래의 테마를 사용하여 GeoForm의 스타일을 지정합니다.",
            publishTabText: "GeoForm 사용자 지정이 완료되면 응용프로그램을 저장하고 대상 그룹과 공유를 시작합니다. 언제든지 이 빌더로 돌아와 피드백을 기반으로 계속 사용자 지정할 수 있습니다."
        }
    })
);