define(
     ({
        map: {
            error: "맵을 생성할 수 없음"
        },
        onlineStatus: {
            offline: "현재 오프라인 상태에서 작업 중입니다. 서버에 대한 연결이 생성될 때까지는 양식 제출이 로컬에 저장됩니다.",
            reconnecting: "다시 연결 중&hellip;",
            pending: "네트워크 연결이 재연결되면 보류 중인 편집 ${total}개가 제출됩니다."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "내 기관",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "내 컨텐츠",
                    favoritesLabel: "내 즐겨찾기"
                },
                title: "웹 맵 선택",
                searchTitle: "검색",
                ok: "확인",
                cancel: "취소",
                placeholder: "검색어 입력"
            },
            groupdlg: {
                items: {
                    organizationLabel: "내 기관",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "내 컨텐츠",
                    favoritesLabel: "내 즐겨찾기"
                },
                title: "그룹 선택",
                searchTitle: "검색",
                ok: "확인",
                cancel: "취소",
                placeholder: "검색어 입력"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "노씽(Northing)",
            utm_easting: "이스팅(Easting)",
            utm_zone_number: "영역(Zone) 번호",
            geoFormGeneralTabText: "1. 정보 입력",
            locationInformationText: "2. 위치 선택",
            submitInformationText: "3. 양식 완료",
            submitInstructions: "이 정보를 맵에 추가합니다.",
            myLocationText: "한_Current Location_빠",
            locationDescription: "한_Specify the location for this entry by clicking/tapping the map or by using one of the following options._빠",
            addressText: "검색",
            geographic: "한_Lat/Lon_빠",
            locationTabText: "위치",
            locationPopupTitle: "한_Location_빠",
            submitButtonText: "한_Submit Entry_빠",
            submitButtonTextLoading: "제출 중&hellip;",
            formValidationMessageAlertText: "다음 필드가 필요합니다.",
            selectLocation: "제출할 ${openLink}위치${closeLink}를 선택하세요.",
            emptylatitudeAlertMessage: "${openLink}위도${closeLink} 좌표를 입력하세요.",
            emptylongitudeAlertMessage: "${openLink}경도${closeLink} 좌표를 입력하세요.",
            shareUserTitleMessage: "참여해주셔서 감사합니다!",
            entrySubmitted: "한_Your entry has been submitted to the map._빠",
            shareThisForm: "한_Share This Form_빠",
            shareUserTextMessage: "한_Tell others to contribute using the following options._빠",
            addAttachmentFailedMessage: "첨부 파일을 레이어에 추가할 수 없음",
            addFeatureFailedMessage: "피처를 레이어에 추가할 수 없음",
            noLayerConfiguredMessage: "죄송합니다! 여기에 표시할 항목이 없습니다. 양식 제출 수집을 시작하려면 이 GeoForm을 구성하고 사용할 편집 가능 피처 서비스 레이어를 선택합니다.",
            placeholderLatitude: "위도(Y)",
            placeholderLongitude: "경도(X)",
            latitude: "위도",
            longitude: "경도",
            findMyLocation: "한_Locate Me_빠",
            finding: "위치 지정 중&hellip;",
            backToTop: "맨 위로 가기",
            addressSearchText: "제출이 여기에 표시됩니다. 핀을 끌어서 위치를 수정할 수 있습니다.",
            shareModalFormText: "양식 링크",
            close: "닫기",
            locationNotFound: "위치를 찾을 수 없습니다.",
            setLocation: "한_Set Location_빠",
            find: "한_Find address or place_빠",
            attachment: "첨부",
            toggleDropdown: "드롭다운 전환",
            invalidLatLong: "올바른 ${latLink}위도${closeLink} 및 ${lngLink}경도${closeLink} 좌표를 입력하세요.",
            invalidUTM: "올바른 ${openLink}UTM${closeLink} 좌표를 입력하세요.",
            invalidUSNG: "올바른 ${openLink}USNG${closeLink} 좌표를 입력하세요.",
            invalidMGRS: "올바른 ${openLink}MGRS${closeLink} 좌표를 입력하세요.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "선택&hellip;",
            applyEditsFailedMessage: "죄송합니다. 항목을 제출할 수 없습니다. 다시 시도하세요.",
            requiredFields: "일부 오류가 있습니다. 아래와 같이 오류를 수정하세요.",
            requiredField: "한_(required)_빠",
            error: "오류",
            textRangeHintMessage: "한_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_빠",
            dateRangeHintMessage: "한_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_빠"
        },
        builder: {
            invalidUser: "한_Sorry, you dont have permission to view this item_빠",
            invalidWebmapSelectionAlert: "한_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._빠",
            invalidWebmapSelectionAlert2: "한_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_빠",
            selectFieldsText: "한_Select Form Fields_빠",
            selectThemeText: "한_Select Form Theme_빠",
            webmapText: "한_Webmap_빠",
            layerText: "한_Layer_빠",
            detailsText: "한_Details_빠",
            fieldsText: "한_Fields_빠",
            styleText: "한_Style_빠",
            optionText: "한_Options_빠",
            previewText: "한_Preview_빠",
            publishText: "한_Publish_빠",
            optionsApplicationText: "한_Options_빠",
            titleText: "한_Builder_빠",
            descriptionText: "한_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._빠",
            btnPreviousText: "한_Previous_빠",
            btnNextText: "한_Next_빠",
            webmapTabTitleText: "한_Select a Webmap_빠",
            viewWebmap: "한_View webmap_빠",
            btnSelectWebmapText: "한_Choose Webmap_빠",
            btnSelectWebmapTextLoading: "한_Loading&hellip;_빠",
            layerTabTitleText: "한_Select Editable Layer_빠",
            selectLayerLabelText: "한_Layer_빠",
            selectLayerDefaultOptionText: "한_Select Layer_빠",
            detailsTabTitleText: "한_Form Details_빠",
            detailTitleLabelText: "한_Title_빠",
            detailLogoLabelText: "한_Logo Image_빠",
            descriptionLabelText: "한_Help Text (optional)_빠",
            fieldTabFieldHeaderText: "한_Field_빠",
            fieldTabLabelHeaderText: "한_Label_빠",
            fieldTabDisplayTypeHeaderText: "한_Display As_빠",
            selectMenuOption: "한_Select Menu_빠",
            selectRadioOption: "한_Radio Button_빠",
            selectTextOption: "한_Text_빠",
            selectCheckboxOption: "한_Checkbox_빠",
            selectMailOption: "한_Email_빠",
            selectUrlOption: "한_URL_빠",
            selectTextAreaOption: "한_Textarea_빠",
            previewApplicationText: "한_Preview Application_빠",
            saveApplicationText: "한_Save Application_빠",
            saveText: "한_Save_빠",
            toggleNavigationText: "한_Toggle navigation_빠",
            formPlaceholderText: "한_My Form_빠",
            shareBuilderInProgressTitleMessage: "한_Publishing GeoForm_빠",
            shareBuilderProgressBarMessage: "한_Please Wait&hellip;_빠",
            shareBuilderTitleMessage: "한_Success! Item saved_빠",
            shareBuilderTextMessage: "한_You can start collecting information by sharing with others_빠",
            shareModalFormText: "한_Form Link_빠",
            shareBuilderSuccess: "한_Your GeoForm has been updated & published!_빠",
            geoformTitleText: "한_Geo Form_빠",
            layerTabText: "한_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._빠",
            detailsTabText: "한_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._빠",
            fieldsTabText: "한_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._빠",
            styleTabText: "한_Style your GeoForm using the themes below based on your preference._빠",
            publishTabText: "한_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._빠",
            smallHeader: "한_Use Small Header_빠",
            pushpinText: "한_Push pin_빠",
            doneButtonText: "한_View Application Item_빠",
            fieldTabPlaceHolderHeaderText: "한_Hint (optional)_빠",
            attachmentLabelText: "한_Attchment Label_빠",
            attachmentLabelHint: "한_Tell users what type of file to attach._빠",
            attachmentDescription: "한_Attachment Description_빠",
            attachmentHint: "한_If necessary, you can provide additional attachment instructions here._빠",
            jumbotronDescription: "한_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._빠",
            shareGeoformText: "한_Share Geoform_빠",
            shareDescription: "한_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._빠",
            defaultMapExtent: "한_Default Map Extent_빠",
            defaultMapExtentDescription: "한_The map will reset to the default extent in your web map after submission - this can be disabled at any time._빠",
            pushpinOptionsDescription: "한_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_빠",
            selectLocationText: "한_Select Location By_빠",
            myLocationText: "한_My Location_빠",
            searchText: "한_Search_빠",
            coordinatesText: "한_Latitude & Longitude Coordinates_빠",
            usng: "한_USNG Coordinates_빠",
            mgrs: "한_MGRS Coordinates_빠",
            utm: "한_UTM Coordinates_빠",
            selectLocationSDescription: "한_Allow users to select a location using these methods._빠"
        }
    })
);