define(
({
		viewer: {
			loading: {
				step1: "LASTER INN PROGRAM",
				step2: "LASTER INN DATA",
				step3: "INITIALISERER OMVISNINGEN",
				loadBuilder: "BYTTER TIL MODUS FOR BYGGEVERKTØY",
				redirectSignIn: "å_REDIRECTING TO SIGN-IN PAGE_ø",
				redirectSignIn2: "å_(you will be redirected here after sign-in)_ø",
				fail: "Beklager, innlastingen av kartomvisningen mislyktes",
				failButton: "Prøv på nytt"
			},
			errors: {
				boxTitle: "Det har oppstått en feil",
				portalSelf: "Alvorlig feil: Kan ikke hente portalkonfigurasjon",
				invalidConfig: "Alvorlig feil: Ugyldig konfigurasjon",
				invalidConfigOwner: "Alvorlig feil: Ugyldig konfigurasjon (autorisert eier kreves)",
				invalidConfigNoWebmap: "Alvorlig feil: Ugyldig konfigurasjon (webkart- eller applikasjons-ID ikke angitt i index.html)",
				createMap: "Kan ikke opprette kart",
				invalidApp: "Alvorlig feil: Kan ikke laste inn applikasjonen",
				noLayer: "Webkartet inneholder ikke noe gyldig datalag for Map Tour.",
				noLayerMobile: "Velkommen til webapplikasjonen Map Tour. Applikasjonen er ikke konfigurert. Map Tour-byggeren støttes ikke på mobile enheter.",
				noLayerView: "Velkommen til webapplikasjonen Map Tour.<br />Applikasjonen er ikke konfigurert ennå.",
				appSave: "Feil under lagring av webapplikasjonen",
				mapSave: "Feil under lagring av webkartet",
				featureServiceLoad: "Feil ved innlasting av geoobjektstjeneste",
				notAuthorized: "Du har ikke tillatelse til å bruke denne applikasjonen",
				oldBrowserTitle: "Webleseren støttes ikke fullt ut",
				noBuilderIE8: "Map Tour-byggeren støttes ikke på Internet Explorer før versjon 9.",
				ie10Win7Explain: "Det interaktive byggeverktøyet for Map Tour støttes ikke i Internet Explorer 10 på Windows 7 når datakilden er en geoobjektstjeneste med vedlegg. For å bruke en geoobjektstjeneste med vedlegg må du <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuelt tvinge dokumentmodusen til å bruke Internet Explorer 9-standarder</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradere til Internet Explorer 9</a> eller oppgradere til Windows 8.",
				oldBrowserExplain: "Denne nettleseren støtter ikke automatisk generering av miniatyrbilder fra bildene du laster inn i map tour. Du kan opprette map tour med denne nettleseren, men du må oppgi et eget miniatyrbilde for hvert av bildene du laster opp.",
				oldBrowserExplain2: "Hvis du vil få en bedre opplevelse, kan du <a href='http://browsehappy.com/' target='_blank'>oppgradere webleseren</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivere Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserExplain3: "Byggeverktøyet for Map Tour fungerer ikke med Internet Explorer 10 på Windows XP.",
				oldBrowserClose: "Lukk"
			},
			mobileHTML: {
				showIntro: "VIS TITTEL",
				hideIntro: "SKJUL TITTEL",
				navList: "Liste",
				navMap: "Kart",
				navInfo: "Medier",
				introStartBtn: "Start"
			},
			desktopHTML: {
				storymapsText: "Et fortellingskart",
				builderButton: "Gå over til byggermodus",
				bitlyTooltip: "Få en kort kobling til applikasjonen",
				bitlyStartIndex: "å_Link to current place_ø"
			},
			builderHTML: {
				panelHeader: "KONFIGURASJON AV APPLIKASJON",
				buttonSave: "LAGRE",
				buttonSettings: "Innstillinger",
				buttonShare: "å_Share_ø",
				buttonView: "Visningsmodus",
				buttonItem: "Åpne webapplikasjonselementet",
				buttonHelp: "Hjelp",
				buttonOrganize: "Organiser",
				buttonAdd: "Legg til",
				buttonImport: "Importer",
				buttonImportDisabled: "Importfunksjonen er ikke tilgjengelig når du bruker en geoobjektstjeneste med vedlegg",
				dataEditionDisabled: "Dataredigering er deaktivert i CSV-datakilden",
				dataSourceWarning: "Map Tour-datalaget er endret. Hvis ID-ene for geoobjektene er endret, må du tilbakestille rekkefølgen og skjulte punkt ved hjelp av <b>Organiser</b>. Hvis feltnavnene er endret, må du tilbakestille feltinnstillingene i <b>kategorien Data i Innstillinger</b>.",
				organizeWarning: "Ett eller flere punktet som er lagt til utenfor det interaktive byggeverktøyet, er skjult.",
				dataPicError0a: "Denne omvisningen har <b>%NB%</b> bilde-URLer som ikke samsvarer.",
				dataPicError0b: "Denne omvisningen kan ha <b>%NB%</b> bilde-URLer som ikke samsvarer.",
				dataPicError1: "Map Tour krever nå at en bilde-URL slutter med en av de følgende etternavnene: .jp(e)g, .png, .gif eller .bmp.",
				dataPicError2: "Dette kravet påvirker ikke Map Tours som allerede er publisert. For å bruke den interaktive byggeren må du imidlertid først løse URL-problemet ved å gjøre ett av følgende:",
				dataPicError3: "Rediger URLer",
				dataPicError4: "Dette legger til <i>#isImage</i> helt til slutt i bilde-URL-er som ikke støttes. De fleste servere støtter tillegg til URL-er, men så fort du har utført denne handlingen, bør du kontrollere at de oppdaterte bilde-URL-ene fungerer ved å navigere gjennom punktene. Hvis hvert bilde lastes inn, kan du nå lagre Map Tour.Hvis <b>bildene er ødelagt, lagrer du ikke Map Tour</b>. Da laster du inn byggeren på nytt og utfører den andre handlingen.",
				dataPicError5: "Begrens omvisningen til bilder",
				dataPicError6: "Dette alternativet gjør at alle URLene regnes som bilder, men du kan ikke legge til videoen med den interaktive byggeren. Denne handlingen kan angres hvis du bestemmer deg for å legge til video i fremtiden.",
				dataPicError7: "Din Map Tour er begrenset til bilder, videoer kan ikke brukes. Hvis du bestemmer deg for å fjerne den begrensningen, kontrollerer du at bildene fortsatt lastes inn korrekt før du lagrer Map Tour. Du kan gjenopprette begrensningen senere hvis du har behov for det.",
				dataPicError8: "Fjern bildebegrensning",
				dataPicError9: "Hvis disse URLene peker mot videoer, kan du ignorere denne advarselen. Hvis de peker mot et bilde, må du utføre en av disse to handlingene:",
				modalCancel: "Avbryt",
				modalApply: "Bruk",
				organizeHeader: "Organiser omvisningen",
				organizeGeneralCaption: "Bruk dra og slipp for å sortere omvisningspunkter",
				organizeDelete: "Slett",
				organizeHide: "Skjul",
				organizeReset: "Tilbakestill rekkefølge og skjulte punkt",
				addMaxPointReached: "Du har nådd maksimalt antall punkter som er tillatt av ikonene som er valgt, og kan ikke legge til flere omvisningspunkter.<br /><br />Vær oppmerksom på at du må laste inn applikasjonen på nytt hvis du sletter eksisterende punkter.",
				addMaxPointReachedMobile: "Beklager, du har nådd det maksimale antallet autoriserte punkter og kan ikke legge til dette bildet.",
				addClose: "Lukk",
				addHeader: "Legg til et nytt omvisningspunkt",
				addTabPicture: "Medier",
				addTabInformation: "Informasjon",
				addTabLocation: "Plassering",
				addSelectCaption: "Velg eller slipp bilde",
				addNoteVideo: "Se i Hjelp for instruksjoner om å bruke videoer",		
				addSelectCaptionNoFileReader: "Velg bilde",	
				addChangePhoto: "Endre bilde og miniatyrbilde",
				addPictureResolutionIntro: "Bildeoppløsningen er høyere enn nødvendig:",
				addPictureResolutionOldBrowser: "Bildeoppløsningen er høyere enn nødvendig. Få mest mulig ut av Map Tour ved å angi en oppløsning som er lavere enn %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Endre bildeoppløsningen til %RESOLUTION%",
				addPictureResolutionKeep: "Behold den opprinnelige bildeoppløsningen på %RESOLUTION%",
				addSelectThumbnail: "Velg miniatyrbilde",
				addNoThumbSelected: "Du har ikke valgt noe miniatyrbilde",
				addThumbSelected: "Valgt",
				addCameraSettingsHeader: "KAMERAINNSTILLINGER",
				addThumbnailHeader: "MINIATYRBILDE",
				addLabelPicUrl: "Bilde",
				addLabelThumbUrl: "Miniatyrbilde",
				addTextPlaceholderUrl: "Angi en bilde-URL",
				addTextPlaceholderUrl2: "å_Enter a Youtube page URL_ø",
				addTextPlaceholderUrl3: "Angi URL for Vimeo-side",
				addTextPlaceholderUrl4: "Angi URL for innebygging av video",
				addLabelVideo: "Video",
				addMediaVideoOther: "Annet",
				addMediaVideoHelp: "Kontroller URL-en, og hent standard miniatyrbilde",
				addMediaVideoHelpTooltip1: "Kontrollen var vellykket",
				addMediaVideoHelpTooltip2: "Kontrollen mislyktes",
				addMediaVideoHelpTooltip4: "Finn alternativet for å bygge inn videoen, og kopier video-URL-en som finnes i koden",
				addLabelName: "Navn",
				addLabelDescription: "Undertekst",
				addTextPlaceholder: "Skriv noe",
				addLocatePlaceholder: "Finn en adresse eller et sted",
				addPinColor: "Farge",
				addLatitude: "Breddegrad",
				addLongitude: "Lengdegrad",
				addLatitudePlaceholder: "f.eks. 34.056",
				addLongitudePlaceholder: "f.eks. -117.195",
				addUploading: "Laster opp omvisningspunkt",
				addSave: "Legg til omvisningspunkt",
				addMobileUploading: "Laster opp bilde",
				addMobileName: "Angi et navn",
				addMobileNameMandatory: "Feil, angi et navn.",
				addMobileError: "Beklager, noe gikk galt.",
				settingsHeader: "Applikasjonsinnstillinger",
				settingsTabLayout: "Utforming",
				settingsTabColor: "Farger",
				settingsTabLogo: "Overskrift",
				settingsTabFields: "Data",
				settingsTabExtent: "Utstrekning",
				settingsTabZoom: "Zoomnivå",
				settingsLayoutExplain: "Velg det programoppsettet du ønsker.",
				settingsLayoutProfessional: "Utforming med tre paneler",
				settingsLayoutModern: "Integrert utforming",
				settingsLayoutSelected: "Valgt utforming",
				settingsLayoutSelect: "Velg denne utformingen",
				settingsLayoutNote: "Legg merke til at for punkter som bruker video, plasseres oppslaget alltid under videoen, selv om det ikke er merket av for dette alternativet.",
				settingsLayoutLocBtn: "å_Display a locate button on supported browser_ø",
				settingsLayoutLocBtnHelp: "Denne funksjonaliteten støttes på de fleste nettlesere for mobile enheter og stasjonære datamaskiner (Internet Explorer 9).",
				settingsColorExplain: "Endre utseende ved å velge et forhåndsdefinert tema eller opprette ditt eget.",
				settingsLabelColor: "Farge på topptekst, innhold og bunntekst",
				settingsLogoExplain: "Tilpass logoen øverst (maks. 250 x 50 piksler).",
				settingsLogoEsri: "Esri-logo",
				settingsLogoNone: "Ingen logo",
				settingsLogoCustom: "Tilpasset logo",
				settingsLogoCustomPlaceholder: "Bilde-URL",
				settingsLogoCustomTargetPlaceholder: "Gjennomklikkingskobling",
				settingsLogoSocialExplain: "Tilpass overskriftkoblingen øverst til høyre.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Kobling",
				settingsLogoSocialDisabled: "Administratoren har deaktivert denne funksjonen",
				settingsDataFieldsExplain: "Velg bildenavn, tekst og fargefelter.",
				settingsDataFieldsError: "Kan ikke finne riktig navn, tekst eller fargedata. Velg feltene som skal brukes her. Disse innstillingene kan endres senere.",
				settingsFieldsLabelName: "Navn",
				settingsFieldsLabelDescription: "Undertekst",
				settingsFieldsLabelColor: "Farge",
				settingsFieldsReset: "Tilbakestill feltvalg",
				settingsExtentExplain: "Velg den opprinnelige utstrekningen av Map Tour gjennom det interaktive kartet nedenfor.",
				settingsExtentExplainBottom: "Utstrekningen du definerer, endrer webkartets opprinnelige utstrekning. Legg merke til at denne utstrekningen ikke brukes hvis den ikke omfatter det første punktet i omvisningen. I slike tilfeller åpnes kartomvisningen sentrert på det første punktet.",
				settingsExtentDateLineError: "Utstrekningen kan ikke være over den 180. lengdegraden",
				settingsExtentDateLineError2: "Feil ved beregning av utstrekningen",
				settingsExtentDrawBtn: "Tegn en ny utstrekning",
				settingsExtentModifyBtn: "Rediger utstrekningen",
				settingsExtentApplyBtn: "Forhåndsvis på Map Tour",
				settingsExtentUseMainMap: "Bruk Map Tour-utstrekning",
				settingsZoomExplain: "Angi zoomnivå for fortellingspunkter etter innledningen (valgfritt).",
				settingsLabelZoom: "Målestokk/nivå",
				settingsZoomFirstValue: "Ingen",
				settingsFieldError: "Velg et felt i hver liste",
				dataTitle: "å_ArcGIS Online hosting_ø",
				dataExplain: "å_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._ø",
				dataNameLbl: "Tjenestenavn",
				dataFolderListLbl: "Mappe",
				dataFolderListFetching: "Henter mapper...",
				dataRootFolder: "Rot",
				dataNameError: "Angi et navn for geoobjektstjenesten",
				dataFolderError: "Velg en gyldig mappe",
				dataSrcContainsInvalidChar: "Navnet på geoobjektstjenesten inneholder ett eller flere ugyldige tegn (-, <, >, #, %, :, \", ?, &, +, / eller \).",
				dataSrvAlreadyExistsError: "Det finnes allerede en tjeneste med det navnet i organisasjonen. Velg et annet navn.",
				dataBtnSave: "Opprett tjenesten",
				dataFooterProgress: "Opprettelse pågår",
				dataFooterSucceed: "Opprettelsen er fullført. Laster inn.",
				dataFooterError: "Opprettelsen mislyktes. Prøv på nytt.",
				tabError: "Se etter feil i alle faner",
				introRecordBtn: "Intro",
				introRecordActivate: "Bruk første punkt som innledning (vises ikke i karusell)"
			},
			addPopupJS: {
				uploadingPicture: "Laster opp bilde",
				uploadSuccess: "Opplastingen er fullført",
				uploadError: "Feil under opplasting av bildet",
				uploadError2: "Feil da geobjektet ble lagt til (ugyldig HTML-kode)",
				notJpg: "Velg et JPEG-bilde du vil laste opp",
				errorNoPhoto: "Velg et bilde du vil laste opp",
				errorNoThumbnail: "Velg et miniatyrbilde du vil laste opp",
				errorInvalidPicUrl: "Angi et gyldig bilde (begynner med http(s)://, slutter med jpg, png, gif eller bmp). Du kan avslutte URL-en med \"#isImage\" for å overstyre regelen.",
				errorInvalidThumbUrl: "Angi et gyldig miniatyrbilde (begynner med http(s)://, slutter med jpg, png, gif eller bmp).",
				errorInvalidVideoUrl: "Angi en gyldig video-URL (starter med http(s)://)",
				errorNoName: "Angi et navn for dette omvisningspunktet",
				errorNoDescription: "Angi en tekst for dette omvisningspunktet",
				errorNoLocation: "Angi et sted for dette omvisningspunktet"
			},
			builderJS: {
				noPendingChange: "å_No unsaved change_ø",
				unSavedChangeSingular: "1 ulagret endring",
				unSavedChangePlural: "ulagrede endringer",
				shareStatus1: "å_Tour is not saved_ø",
				shareStatus2: "å_Tour is shared publicly_ø",
				shareStatus3: "å_Tour is shared within the organization_ø",
				shareStatus4: "å_Tour is not shared_ø",
				popoverDiscard: "Er du sikker på at du vil forkaste endringer som ikke er lagret?",
				yes: "Ja",
				no: "Nei",
				popoverLoseSave: "Dersom du åpner viseren, mister du endringer som ikke er lagret",
				ok: "Ok",
				popoverSaveWhenDone: "Ikke glem å lagre når du er ferdig",
				closeWithPendingChange: "Er du sikker på at du vil bekrefte handlingen? Du mister da endringene du har gjort.",
				gotIt: "Ok",
				savingApplication: "Lagrer applikasjonen",
				saveSuccess: "Applikasjonen er lagret",
				saveError: "Lagringen mislyktes. Prøv på nytt.",
				saveError2: "Lagring mislyktes på grunn av ugyldig HTML-kode i et navn eller en beskrivelse",
				saveError3: "å_The title can't be empty_ø",
				dragColorPicker: "Flytt på meg<br />eller endre fargen min",
				dataWarningExtent: "Du har data utenfor webkartets utstrekning. Disse dataene blir ikke brukt som omvisningspunkter. Endre kartets utstrekning hvis du vil bruke dem.",
				dataWarningVisibi: "Map Tour-laget er ikke synlig med den gjeldende utstrekningen for webkartet. Bekreft at Map Tour-laget er synlig med et %MAPSIZE% stort kart.",
				dataWarningEdit: "Rediger webkart",
				dataWarningClose: "Lukk",
				signIn: "Logg på med en konto på",
				signInTwo: "for å lagre applikasjonen.",
				switchBM: "å_Change Basemap_ø"
			},
			organizePopupJS: {
				messageStart: "Du har valgt å slette",
				messageSinglePoint: "ett omvisningspunkt",
				messageMultiPoint: "omvisningspunkter",
				messagePermantRemove: "Dette fører til permanent fjerning av",
				messageRecord: "posten",
				messageRecordPlural: "poster",
				messageConfirm: "fra databasen. Vil du fortsette?",
				labelButtonShow: "Vis",
				labelButtonHide: "Skjul"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Dette vil slette bildet og miniatyrbildet permanent",
				popoverDeleteWarningThumb: "Dette vil slette miniatyrbildet permanent",
				popoverUploadingPhoto: "Laster opp bilde og miniatyrbilde",
				popoverUploadingThumbnail: "Laster opp miniatyrbilde",
				popoverUploadSuccessful: "Opplastingen er fullført",
				popoverUploadError: "Opplastingen mislyktes, prøv på nytt",
				changePicAndThumb: "Endre bilde",
				changeThumb: "Endre miniatyrbilde",
				selectPic: "Endre medier",
				selectThumb: "Endre miniatyrbilde",
				uploadPicAndThumb: "Bruk"
			},
			headerJS:{
				editMe: "Rediger meg!",
				templateTitle: "Angi tittel på malen",
				templateSubtitle: "Angi undertittel for malen"
			},
			crossFaderJS:{
				setPicture: "Angi bildetittel",
				setCaption: "Angi bildetekst"
			},
			importPopup: {
				title: "Importer",
				prevBtn: "Bak",
				nextBtn: "Neste"
			},
			importPopupHome: {
				header: "Hvor har du lagret bildene dine?"
			},
			onlinePhotoSharingCommon: {
				pictures: "bilder",
				videos: "videoer",
				disabled: "Administratoren har deaktivert denne funksjonen",
				disabledPortal: "Denne funksjonen er deaktivert på Portal for ArcGIS",
				header1: "å_Your pictures must be shared publicly._ø",
				header2: "å_The import will be limited to the first %NB1% %MEDIA%._ø",
				emptyDataset: "Feil; ingen bilder funnet",
				footerImport: "Importer",
				selectAlbum: "Velg et offentlig album",
				selectAlbum2: "Velg et album",
				pleaseChoose: "Velg",
				userLookup: "Slå opp",
				userLookingup: "Slår opp",
				csv: "Vist til i en CSV",
				advanced: "Avanserte alternativer",
				advancedScratchLbl: "å_Start a new Tour_ø",
				advancedScratchTip: "å_Create an empty Tour that you will be able populate manually using a wizard._ø",
				advancedCSVLbl: "å_Import Tour data from a CSV file_ø",
				advancedCSVTip: "å_Import your Tour content from a CSV file._ø",
				advancedCommonTip: "å_It requires that your images and videos are already online._ø",
				select: "Foreta et valg",
				locUse: "å_Use pictures geolocation_ø",
				locExplain: "å_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._ø",
				locExplain2: "å_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._ø"
			},
			viewFlickr: {
				title: "å_Flickr import_ø",
				header: "å_Enter your Flickr user name and select a Photo Set or a Tag to be imported._ø",
				userInputLbl: "Angi et brukernavn",
				signInMsg2: "Finner ikke bruker",
				selectSet: "Velg et bildesett",
				selectTag: "eller velg en tagg",
				footerImportTag: "Importer den valgte taggen",
				footerImportSet: "Importer det valgte settet"
			},
			viewFacebook: {
				title: "å_Facebook import_ø",
				header: "å_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._ø",
				leftHeader: "Facebook-bruker",
				rightHeader: "Facebook-side",
				pageExplain: "En Facebook-side er for et offisielt merke, et produkt eller en kjendis, for eksempel <b>esrigis</b>. Du finner navnet på siden etter første / i sidens URL-adresse.",
				pageInputLbl: "Angi et sidenavn",
				lookupMsgError: "Finner ikke siden"
			},
			viewPicasa: {
				title: "å_Picasa/Google+ import_ø",
				header: "å_Enter your email address or the ID of your Picasa or Google+ account._ø",
				userInputLbl: "Angi en e-postadresse eller ID",
				signInMsg2: "Finner ikke kontoen",
				howToFind: "å_How to find a Picasa or Google+ account ID_ø",
				howToFind2: "Kopier tallene mellom første og andre/ på en tilfeldig side på Picasa eller G+"
			},
			viewCSV: {
				title: "å_CSV import_ø",
				uploadBtn: "Velg eller dropp en CSV-fil",
				resultHeaderEmpty: "CSV-filen er tom",
				resultHeaderSuccess: "Innlastingen av %NB_POINTS% punkter var vellykket",
				resultHasBeenLimited: "Importen er blitt begrenset til de første %VAL1% punktene av %VAL2% for å overholde grensen på %VAL3% punkter per omvisning",
				browserSupport: "Du bruker en nettleser som ikke støttes. For å bruke en CSV må du <a href='http://browsehappy.com/' target='_blank'>oppgradere nettleseren</a> eller bruke visningsprogrammet for webkart på ArcGIS.com (se Hjelp).",
				errorLatLng: "Finner ikke bredde- og lengdegradfeltene. Mulige verdier for breddegrad er: <i>%LAT%</i> og for lengdegrad: <i>%LONG%</i>.",
				errorFieldsExplain: "Innlastingen mislyktes ettersom følgende obligatoriske felter ikke ble funnet",
				errorFieldsName: "<b>Navn</b> mulige verdier er: %VAL%",
				errorFieldsDesc: "<b>Beskrivelse</b> mulige verdier er: %VAL%",
				errorFieldsUrl: "<b>Bilde-URL</b> mulige verdier er: %VAL%",
				errorFieldsThumb: "<b>URL-adresse til miniatyrbilde</b> mulige verdier er: %VAL%",
				errorFields2Explain: "Innlastingen mislyktes ettersom CSV-filen ikke bruker samme attributter som laget, for følgende attributter",
				errorFields2Name: "<b>Navn</b> bruk %VAL1% i stedet for %VAL2%",
				errorFields2Desc: "<b>Beskrivelse</b> bruk %VAL1% i stedet for %VAL2%",
				errorFields2Url: "<b>Bilde-URL</b> bruk %VAL1% i stedet for %VAL2%",
				errorFields2Thumb: "<b>URL-adresse til miniatyrbilde</b> bruk %VAL1% i stedet for %VAL2%",
				resultFieldsAll: "Alle attributter er blitt importert",
				resultFieldsNotAll: "Følgende attributter er ikke blitt importert fordi de ikke finnes i kartlaget",
				resultFieldsNotAll2: "Følgende attributter er blitt importert",
				footerNextBtnResult: "Importer til webkart",
				footerProgress: "Import pågår",
				footerSucceed: "Import fullført. Laster inn"
			},
			viewYoutube: {
				title: "å_Youtube import_ø",
				header: "å_Enter a YouTube user name to find publicly shared videos._ø",
				pageInputLbl: "å_Enter a Youtube user name_ø",
				lookupMsgError: "Finner ikke bruker",
				howToFind: "å_How to find a Youtube user name_ø",
				howToFind2: "Brukernavnet vises under videoer",
				found: "Funnet",
				noData: "Finner ingen offentlige videoer"
			},
			viewGeoTag: {
				title: "å_Select and locate your images/videos_ø",
				header: "Klikk eller trykk på bildene du vil importere, for å finne dem.",
				headerMore: "å_Why aren't my images/videos geolocated?_ø",
				headerExplain: "å_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._ø",
				leftPanelTab1: "For å finne",
				leftPanelTab2: "Funnet",
				clickOrTap: "Klikk eller trykk på kartet for å finne",
				clearLoc: "å_Clear locations_ø",
				clickDrop: "Ikke importer",
				footerImport: "Importer",
				footerProgress: "Import pågår",
				footerSucceed: "Import fullført. Laster inn ...",
				loading: "Laster inn",
				error: "å_Pictures geolocation import failed, geolocations have been ignored._ø"
			},
			initPopup: {
				title: "å_Welcome to the Map Tour Builder_ø",
				prevBtn: "Bak",
				nextBtn: "Neste"
			},
			initPopupHome: {
				header1: "å_Where are your images or videos?_ø",
				header2: "å_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._ø",
				title1: "å_They are already online_ø",
				title2: "å_I need to upload my images_ø",
				hostedFSTooltip: "å_Use ArcGIS Online to host your images (doesn't support videos)._ø",
				hostedFsNA: "å_Only available for ArcGIS for Organizations Publisher and Administrator users_ø",
				footer1: "Når du er ferdig, må du ikke glemme å dele Map Tour med publikum via  siden for programelementer.",
				footer3: "Last ned CSV-malen",
				footer4: "\"Lagre som\" hvis det ikke lastes ned",
				footer4bis: "å_Use right click and \"Save as\" if download doesn't start_ø",
				footer5: "å_Learn more_ø",
				footerProgress: "Opprettelse pågår",
				footerSucceed: "Opprettelsen er fullført. Laster inn ..."
			},
			helpPopup: {
				title: "å_Help_ø",
				close: "Lukk",
				tab1: {
					title: "Innledning",
					div1: "å_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._ø",
					div2: "å_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_ø",
					div4: "å_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._ø",
					div42: "å_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._ø",
					div5: "å_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._ø"
				},
				tab2: {
					title: "Data",
					div1: "Det viktigste å tenke på når du skal bygge en Map Tour, er hvor du skal lagre bildene dine. Map Tour kan bruke bilder som er lagret på større bildedelingstjenester, på alle webservere eller som vedlegg til en geoobjektstjeneste.",
					div1a: "Se den siste delen av denne fanen for detaljer om støttede bilde- og videoformater.",
					div2: "Det interaktive verktøyet gir deg to alternativer for bildebehandling i Map Tour:",
					div3: "<ul><li>Du kan bruke <b>bilder som allerede er lagret online</b>, for eksempel bilder som er lagret på et bildedelingsområde som Flickr, eller bilder som du har lagret på ditt eget webområde. Disse bildene blir referert til med URL-adresser i Map Tour</li><li>Du kan også <b>laste opp bilder fra datamaskinen</b> direkte til Map Tour. Dette opplastingsalternativet krever at du har en ArcGIS Online-konto, og at du har en utgiver- eller administratorkonto fordi det automatisk opprettes en vertsbasert geoobjektstjeneste for deg, der bildene blir lagret som vedlegg</li></ul>",
					div4: "De viktigste brukertilfellene er:",
					div4b: "<b>Bildene dine er ikke driftet</b> ennå, og du har et ArcGIS Online-abonnement: Det beste er å bruke en vertsbasert geoobjektstjeneste. I likhet med offentlige bildedelingstjenester optimaliserer vi bildene slik at de lastes raskt, og du får tilgang til alle funksjonene for administrasjon og databehandling på ArcGIS-plattformen.",
					div5: "<b>Du er ikke medlem av en organisasjon</b>: Du må først laste opp bildene dine på et bildedelingsområde eller på din egen webserver. Veiviseren gir deg deretter hjelp til å bruke disse bildene, som fortsatt blir liggende på den opprinnelige plasseringen.",
					div6: "<b>Du prøver å gjenbruke en eksisterende geoobjektstjeneste</b> der bildene dine er lagret som vedlegg, eller som refererer
 til eksterne bilder: Les det mer utfyllende avsnittet nedenfor.",
					div7: "<b>Du bruker en tidligere versjon av</b> Map Tour-malen og har allerede en CSV som refererer til bildene og miniatyrbildene dine: Du kan importere den og forbedre dataene. Byggeren støtter bare CSV som bruker attributter for bredde- og lengdegrader; adressebasert CSV kan fortsatt brukes gjennom webkartet (se avsnitt nedenfor).",
					div8: "Importere fra bildedelingstjenester online",
					div9: "Importoperasjonen refererer til bilder som allerede er vertsbaserte, ved å lagre URL-adressene i en samling av webkartfunksjoner. Bildene lagres ikke i ArcGIS Online. Hvis driftingen av bildene avbrytes, blir de ikke lenger tilgjengelige i kartomvisningen og et "Bilde ikke tilgjengelig"-bilde blir brukt. Det avhenger av tjenesteleverandøren om kartomvisningen importerer bildenes navn, beskrivelse og plassering, eller ikke. De attributttene er lagret i webkartet, og eventuelle redigeringer av online-tjenestene gjenspeiles ikke i kartomvisningen.",
					div10: "Lagre bildene på en webserver",
					div11: "Hvis du velger å drifte bildene selv, må du opprette miniatyrer av bildene manuelt. Hvis du bruker bilder med maksimal oppløsning til miniatyrene, reduseres ytelsen. Derfor anbefaler vi på det sterkeste å bruke en online bildedelingstjeneste eller en geoobjektstjeneste til dette.",
					div12: "Bruke en eksisterende geoobjektstjeneste eller shapefil",
					div13: "Enhver geoobjektstjeneste eller shapefil kan brukes som datakilde for Map Tour. Du må bare legge den til som et lag i webkartet ved hjelp av kartvisningsprogrammet på arcgis.com. Hvis programmet finner de forventede attributtene i laget, vil alle byggeverktøyets funksjoner være tilgjengelige.",
					div14: "å_The possible values for fields name are (case insensitive):_ø",
					div151: "Navn",
					div152: "Beskrivelse",
					div153: "Bilde",
					div154: "Miniatyrbilde",
					div155: "å_Color_ø ",
					div16: "å_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._ø",
					div162: "Når du bruker en geoobjektstjeneste som lagrer bildene som vedlegg, <b>brukes bare geoobjektene med to vedlegg</b>. Det første vedlegge definerer hovedbilde, mens det andre vedlegget definerer miniatyrbildet.",
					div17: "Feltene Bilde og Miniatyrbilde er obligatoriske for geoobjektstjenester uten vedlegg, og valgfrie (men anbefales sterkt) for geoobjektstjenester med vedlegg. Hvis vedlegg er aktivert for tjenesten din, lar byggeverktøyet deg laste opp bilder som vedlegg. Hvis ikke kan du bare redigere bildet og miniatyrbildet via URL-adressen.",
					div172: "Når de er til stede, brukes bilde- og minatyrbildefeltene alltid, og geoobjekttjenestetilleggene blir ikke søkt opp.",
					div173: "Eksempel-CSV- og shapefiler kan lastes ned fra",
					div18: "Opprette en vertsbasert geoobjektstjeneste fra CSV eller shapefil",
					div19: "Når du oppretter en vertsbasert geoobjektstjeneste fra en CSV- eller shapefil, er vedlegg som standard ikke aktivert. Du kan aktivere dem ved å åpne siden for geoobjektstjenesteelementer og klikke på den lille pilen i lagdelen for å vise alternativet. Map Tour vil deretter fortsette å bruke de bildene og miniatyrbildene som du har referert til ved attributter. Hvis du heller vil laste opp bildene som vedlegg til en geoobjektstjeneste, kan du gjøre det ved hjelp av to knapper på bildepanelet (\"Bytt bilde\" og \"Bytt miniatyrbilde\").",
					div20: "Støttede bildeformater og videoer",
					div21: "Støttede bildeformater er: <b>.jpg, .jpeg, .png, .gif og .bmp</b>. Hvis mediene dine ikke slutter med dette etternavnet, regner Map Tpur med at det er en video, bortsett fra når du bruker en geoobjektstjeneste (se nedenfor).",
					div22: "Map Tour-malen inkluderer ingen videospiller, så du må bruke den eksterne videospilleren fra favorittvideovertstjenesten din (finn alternativet for å bygge inn videoen, og kopier URLen som gis i den koden som oppgis). Hvis du vil drifte videoen selv, kan du opprette en HTML-side som inneholder en videospiller som <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Den interaktive byggeren har ingen dialog for å ta med video ved bruk av geoobjektstjenester med vedlegg, men det er mulig å gjøre det ved å redigere dataene utenfor den interaktive byggeren. I arcgis.com-kartvisningen kan du endre bildefeltene slik at de peker mot en ekstern video og legge til en egen parameter til slutt i URLen (#isVideo), slik at mediene dine regnes som en video.",
					div24: "Merk at du fortsatt må ha to gyldige bildevedlegg, eller blir ikke punktet brukt. Det er ikke mulig å bruke videoer med geoobjektstjenestevedlegg uten bilde- og miniatyrbildefeltene."
				},
				tab3: {
					title: "Tilpasning",
					div1: "Byggeverktøyet inneholder flere alternativer for tilpasning, som er tilgjengelige via knappen INNSTILLINGER i toppanelet. Hvis du ikke finner alternativet du forventer, leverer vi også en nedlastbar versjon som du kan distribuere på din egen webserver og forbedre slik du ønsker.",
					div2: "Vi anbefaler å bruke den vertsbaserte versjonen, med mindre:",
					div3: "<li>Den ikke tilbyr en grensesnittilpasning som du gjerne vil ha, for eksempel å kunne bruke et bakgrunnsbilde i overskriften.</li><li>Du er en utvikler og ønsker å forbedre programmet.</li>",
					div4: "Du kan konfigurere den nedlastbare versjonen gjennom en webkart- eller webkartapplikasjons-ID. De viktigste bruksområdene er:",
					div41: "Du bygger Map Tour ved å bruke den interaktive byggeren i det vertsbaserte miljøet, og konfigurerer malen med webkartapplikasjonsidentifikatoren. Innstillingene du har definert med den interaktive byggeren, blir brukt.",
					div42: "å_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._ø",
					div43: "Merk at den interaktive byggeren er tilgjengelig i den nedlastbare versjonen, men med noen tekniske begrensninger i nettlesere som Internet Explorer som er eldre enn versjon 10.",
					div5: "å_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._ø"
				},
				tab4: {
					title: "Tips",
					div0: "Støttede nettlesere",
					div0a: "Map Tour-viseren støttes på IE8+. Den interaktive byggeren støttes på IE9+. Vi tester aktivt i alle større nettlesere, men hvis du opplever problemer, anbefaler vi at du bruker Chrome.",
					div0b: "Hvis du opplever problemer, må du varsle oss. I mellomtiden kan du begrense samhandlingen med byggergrensesnittet ved å bygge Map Tour med CSV-malen.",
					div1: "Bilder",
					div2: "å_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._ø",
					div2a: "å_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._ø",
					div3: "Formatere underteksten med HTML-koder",
					div4: "Underteksten kan inneholde HTML-koder som definerer formatering og koblinger. Denne koden legger f.eks. til en gul kobling:",
					div4a: "å_Write a good subtitle for your tour_ø",
					div4b: "å_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._ø",
					div5: "Støttelag",
					div6: "Du kan legge til ekstra støttelag i kartet for å gi kontekst i Map Tour. Disse lagene kan inneholde andre geoobjekter du vil at kartet skal vise i tillegg til Map Tour-punktene, f.eks. et studieområde, en gå- eller kjørerute som kobler omvisningspunktene sammen osv. Map Tour-malen viser disse ekstra støttelagene ved å bruke symbolene du angir i webkartet, men oppsprettvinduene er ikke tilgjengelige.",
					div7: "Gjør omvisningen kort og hyggelig",
					div8: "Det er en grense på 99 punkter per omvisning. De fleste omvisninger vil selvsagt være atskillig kortere en det. Ikke forvent at publikum har lyst til å gå gjennom altfor mange omvisningspunkter. Du synes kanskje emnet er uendelig fascinerende, men det er ikke sikkert at alle andre synes det samme!",
					div9: "Du kan finne ut mer ved å se <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>den detaljerte veiledningen</a>.",
					div10: "Innbyggingsmetode",
					div11: "Hvis du vil bygge inn malen i en annen nettside med en iframe, legger du til den ekstra parameteren \"&embed\" til slutt i URLen for å fjerne headeren. Denne modusen kan også stilles inn i den nedlastbare versjonen gjennom en konfigurasjonsfil.",
					div12: "å_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._ø" 
				},
				tab5: {
					title: "Publisere",
					div1: "å_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._ø",
					div2a: "å_Sharing the Tour through the builder_ø",
					div2b: "å_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._ø",
					div2c: "å_Sharing the Tour through ArcGIS Online_ø",
					div2d: "å_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._ø",
					div3t: "å_Feature Service security_ø",
					div3a: "å_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._ø",
					div3t2: "å_Before sharing your Tour with your audience_ø",
					div3: "å_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._ø",
					div4: "å_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._ø",
					div5a: "å_Recommendation for search_ø",
					div5b: "å_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._ø"
				}
			},
			share: {
				firstSaveTitle: "å_Tour successfully saved_ø",
				firstSaveHeader: "å_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._ø",
				firstSaveA1: "å_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_ø",
				firstSaveA1bis: "å_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._ø",
				firstSaveQ2: "å_Is my Tour shared?_ø",
				firstSaveA2: "å_Currently your Tour is not shared. To share it, use the SHARE button._ø",
				shareTitle: "å_Share your Tour_ø",
				sharePrivateHeader: "å_Your Tour is not shared, would you like to share it?_ø",
				sharePrivateBtn1: "å_Share publicly_ø",
				sharePrivateBtn2: "å_Share with my Organization_ø",
				sharePrivateProgress: "å_Sharing in progress..._ø",
				sharePrivateErr: "å_Sharing failed, try again or_ø",
				sharePrivateOk: "å_Sharing updated successfully, loading..._ø",
				sharePreviewAsUser: "å_Preview_ø",
				shareHeader1: "å_Your Tour is <strong>publicly accessible</strong>._ø",
				shareHeader2: "å_Your Tour is accessible by your organization members (login is required)._ø",
				shareLinkHeader: "å_Share the Tour with your audience_ø",
				shareLinkOpen: "å_OPEN_ø",
				shareQ1Opt1: "å_How do I keep the Tour private?_ø",
				shareQ1Opt2: "å_How do I keep the Tour private or share it publicly?_ø",
				shareA1: "å_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._ø",
				shareA1bis: "å_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._ø",
				shareQ2: "å_How do I edit the Tour later?_ø",
				shareQ2bis: "å_How do I get back to the authoring interface?_ø",
				shareA2div1: "å_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._ø",
				shareA2div2: "å_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_ø",				
				shareQ3: "å_Where is the data stored?_ø",
				shareA3: "å_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._ø"
			}
        }
    })
);
