define(
({
		viewer: {
			loading: {
				step1: "INDLÆSER APPLIKATION",
				step2: "INDLÆSER DATA",
				step3: "STARTER TUREN",
				loadBuilder: "SKIFTER TIL BUILDER-TILSTAND",
				redirectSignIn: "ø_REDIRECTING TO SIGN-IN PAGE_å",
				redirectSignIn2: "ø_(you will be redirected here after sign-in)_å",
				fail: "Beklager, indlæsning af Map Tour mislykkedes",
				failButton: "Prøv igen"
			},
			errors: {
				boxTitle: "Der opstod en fejl",
				portalSelf: "Uoprettelig fejl: Kunne ikke hente portalkonfiguration",
				invalidConfig: "Uoprettelig fejl: Ugyldig konfiguration",
				invalidConfigOwner: "Uoprettelig fejl: Ugyldig konfiguration (autoriseret ejer kræves)",
				invalidConfigNoWebmap: "Uoprettelig fejl: Ugyldig konfiguration (webkort- eller applikationsidentifikator er ikke angivet i index.html)",
				createMap: "Kan ikke oprette kort",
				invalidApp: "Uoprettelig fejl: Applikationen kan ikke indlæses",
				noLayer: "Webkort indeholder ikke et gyldigt datalag for kortturen.",
				noLayerMobile: "Velkommen til Map Tour-webapplikationen. Applikationen er ikke konfigureret. Map Tour builder-programmet understøttes ikke på mobile enheder.",
				noLayerView: "Velkommen til Map Tour-webapplikationen.<br />Applikationen er endnu ikke konfigureret.",
				appSave: "Fejl ved lagring af webapplikationen",
				mapSave: "Fejl ved lagring af webkortet",
				featureServiceLoad: "Fejl under indlæsning af featuretjeneste",
				notAuthorized: "Du er ikke autoriseret til at få adgang til denne applikation",
				oldBrowserTitle: "Browser understøttes ikke fuldt ud",
				noBuilderIE8: "Map Tour-builderprogrammet understøttes ikke for Internet Explorer før version 9.",
				ie10Win7Explain: "Map Tour-builderprogammet understøttes ikke i Internet Explorer 10 på Windows 7, når datakilden er en featuretjeneste med vedhæftninger. Hvs du vil bruge en featuretjenste med vedhæftninger, skal du <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuelt tvinge dokumenenttilstanden til at følge Internet Explorer 9-standarden</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradere til Internet Explorer 9</a> eller opgradere til Windows 8.",
				oldBrowserExplain: "Denne browser understøtter ikke automatisk miniaturegenerering af de billeder, du overfører til din korttur. Du kan oprette en korttur med denne browser, men du skal oprette et separat miniaturebillede for hvert af de billeder, du overfører.",
				oldBrowserExplain2: "For at forbedre din oplevelse skal du <a href='http://browsehappy.com/' target='_blank'>opgradere din browser</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivere Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserExplain3: "Map Tour-builder fungerer ikke med Internet Explorer 10 på Windows XP.",
				oldBrowserClose: "Luk"
			},
			mobileHTML: {
				showIntro: "VIS TITEL",
				hideIntro: "SKJUL TITEL",
				navList: "Liste",
				navMap: "Kort",
				navInfo: "Medier",
				introStartBtn: "Start"
			},
			desktopHTML: {
				storymapsText: "Et historiekort",
				builderButton: "Skift til builder-tilstand",
				bitlyTooltip: "Hent et kortere link til applikationen",
				bitlyStartIndex: "ø_Link to current place_å"
			},
			builderHTML: {
				panelHeader: "APPLIKATIONSKONFIGURATION",
				buttonSave: "GEM",
				buttonSettings: "Indstillinger",
				buttonShare: "ø_Share_å",
				buttonView: "Visningstilstand",
				buttonItem: "Åbn webapplikationselement",
				buttonHelp: "Hjælp",
				buttonOrganize: "Organis\ér",
				buttonAdd: "Tilføj",
				buttonImport: "Import\ér",
				buttonImportDisabled: "Import er ikke tilgængelig, når du bruger en featuretjeneste med vedhæftninger.",
				dataEditionDisabled: "Dataredigering er deaktiveret på CSV-datakilden",
				dataSourceWarning: "Datalaget til kortturen er ændret. Hvis objekt-ID\'et ikke er det samme, skal du nulstille rækkefølgen og de skjulte punkter med <b>Organis\ér</b>. Hvis feltnavnene er forskellige, skal du nulstille feltindstillingerne under<b>datafanen i Indstillinger</b>.",
				organizeWarning: "Et eller flere punkter, der er tilføjet uden for det interaktive builder-program, er skjulte.",
				dataPicError0a: "Denne tour omfatter <b>%NB%</b> ikke-kompatible billed-URL\'er.",
				dataPicError0b: "Denne tour omfatter <b>%NB%</b> ikke-kompatible billed-URL\'er.",
				dataPicError1: "Map Tour kræver nu, at billed-URL\'er slutter med \ét af følgende filtypenavne: .jp(e)g, .png, .gif eller .bmp.",
				dataPicError2: "Dette krav vil ikke få nogen indflydelse på din eksisterende publicerede Map Tour. Men for at kunne bruge det interaktive builder-program skal du først løse URL-problemet ved at udføre \én af følgende to handlinger:",
				dataPicError3: "Redig\ér URL\'er",
				dataPicError4: "Dette vil føje <i>#isPicture</i> til slutningen af ikke-understøttede billed-URL\'er. De fleste servere understøtter URL-tilknytninger. Men når du har udført denne handling, skal du kontrollere, at de opdaterede billed-URL\'er fungerer ved at navigere gennem dine punkter. Hvis alle billeder indlæses, kan du gemme din Map Tour. Hvis <b>billederne er ødelagte, skal du ikke gemme din Map Tour</b>. Genindlæs i stedet builder-programmet, og udfør den anden handling.",
				dataPicError5: "Begræns turen til billeder",
				dataPicError6: "Denne indstiling medfører, at alle URL\ér bliver betragtet som billeder, men du vil ikke kunne tilføje videoer med det interaktive builder-program. Denne handling kan fortrydes, hvis du på et tidspunkt i fremtiden beslutter at tilføje videoer.",
				dataPicError7: "Din Map Tour er begrænset til billeder, videoer kan ikke benyttes. Hvis du vælger at fjerne denne begrænsning, skal du kontrollere, at dine billeder fortsat indlæses korrekt, før du gemmer din Map Tour. Du kan gendanne denne begrænsning på et senere tidspunkt, hvis det bliver nødvendigt.",
				dataPicError8: "Fjern billedbegrænsningen",
				dataPicError9: "Hvis disse URL\ér peger på videoer, kan du se bort fra denne advarsel. Hvis de peger på billeder, skal du udføre \én af følgende to handlinger:",
				modalCancel: "Annull\ér",
				modalApply: "Anvend",
				organizeHeader: "Organisér turen",
				organizeGeneralCaption: "Brug træk og slip til at sortere turpunkter",
				organizeDelete: "Slet",
				organizeHide: "Skjul",
				organizeReset: "Nulstil rækkefølge og skjulte punkter",
				addMaxPointReached: "Du har nået det maksimale antal punkter, der er autoriseret af de indstillede ikoner, og du kan ikke tilføje endnu et turpunkt.<br /><br />Bemærk, at hvis du sletter eksisterende punkter, skal du genindlæse applikationen.",
				addMaxPointReachedMobile: "Beklager, du har nået det maksimale antal autoriserede points og kan ikke tilføje dette billede.",
				addClose: "Luk",
				addHeader: "Tilføj et nyt turpunkt",
				addTabPicture: "Medier",
				addTabInformation: "Oplysninger",
				addTabLocation: "Sted",
				addSelectCaption: "Vælg eller slet billede",
				addNoteVideo: "Se Hjælp for at få vejledning i brugen af videoer",		
				addSelectCaptionNoFileReader: "Vælg billede",	
				addChangePhoto: "Redigér billede og miniature",
				addPictureResolutionIntro: "Billedopløsningen er højere end krævet:",
				addPictureResolutionOldBrowser: "Billedopløsningen er højere end krævet. Optimér Map Tour-oplevelsen ved at indstille en opløsning, der er lavere end %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Skift billedopløsning til %RESOLUTION%",
				addPictureResolutionKeep: "Behold den oprindelige opløsning på %RESOLUTION%",
				addSelectThumbnail: "Vælg miniaturebillede",
				addNoThumbSelected: "Intet miniaturebillede valgt",
				addThumbSelected: "Valgt",
				addCameraSettingsHeader: "KAMERAINDSTILLLINGER",
				addThumbnailHeader: "MINIATUREBILLEDE",
				addLabelPicUrl: "Billede",
				addLabelThumbUrl: "Miniature",
				addTextPlaceholderUrl: "Indtast en billed-URL",
				addTextPlaceholderUrl2: "ø_Enter a Youtube page URL_å",
				addTextPlaceholderUrl3: "Indtast en Vimeo-side-URL",
				addTextPlaceholderUrl4: "Indtast en URL, der er indlejret i en video",
				addLabelVideo: "Video",
				addMediaVideoOther: "Andet",
				addMediaVideoHelp: "Kontroll\ér URL\'en, og hent standardminiaturen",
				addMediaVideoHelpTooltip1: "Kontrol lykkedes",
				addMediaVideoHelpTooltip2: "Kontrol mislykkedes",
				addMediaVideoHelpTooltip4: "Find indstillingen til indlejring af videoen, og kopi\ér video-URL\'en, der findes i koden",
				addLabelName: "Navn",
				addLabelDescription: "Billedtekst",
				addTextPlaceholder: "Skriv noget",
				addLocatePlaceholder: "Find en adresse eller et sted",
				addPinColor: "Farve",
				addLatitude: "Breddegrad",
				addLongitude: "Længdegrad",
				addLatitudePlaceholder: "f.eks. 34,056",
				addLongitudePlaceholder: "f.eks. -117,195",
				addUploading: "Overfører turpunkt",
				addSave: "Tilføj turpunkt",
				addMobileUploading: "Overfører billede",
				addMobileName: "Angiv et navn",
				addMobileNameMandatory: "Fejl, angiv et navn.",
				addMobileError: "Beklager, noget er gået galt",
				settingsHeader: "Applikationsindstillinger",
				settingsTabLayout: "Layout",
				settingsTabColor: "Farver",
				settingsTabLogo: "Logo",
				settingsTabFields: "Data",
				settingsTabExtent: "Område",
				settingsTabZoom: "Zoomniveau",
				settingsLayoutExplain: "Vælg det ønskede applikationslayout.",
				settingsLayoutProfessional: "Layout med tre paneler",
				settingsLayoutModern: "Integreret layout",
				settingsLayoutSelected: "Vælg layout",
				settingsLayoutSelect: "Vælg dette layout",
				settingsLayoutNote: "Bemærk, at ved punkter, der benytter videoer, vil opslaget altid være placeret under videoen, selvom denne indstilling ikke er markeret.",
				settingsLayoutLocBtn: "ø_Display a locate button on supported browser_å",
				settingsLayoutLocBtnHelp: "Denne funktionalitet understøttes på de fleste browsere på mobile enheder samt pc-browsere (Internet Explorer 9).",
				settingsColorExplain: "Skift udseende ved at vælge et foruddefineret tema eller ved at oprette dit eget.",
				settingsLabelColor: "Farver på toptekster, indhold og bundtekster",
				settingsLogoExplain: "Tilpas toptekstlogoet  (maks. 250 x 50 pixel).",
				settingsLogoEsri: "Esri-logo",
				settingsLogoNone: "Intet logo",
				settingsLogoCustom: "Brugerdefineret logo",
				settingsLogoCustomPlaceholder: "Billede-URL",
				settingsLogoCustomTargetPlaceholder: "Klik gennem-link",
				settingsLogoSocialExplain: "Tilpas header-linket øverst til højre.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Link",
				settingsLogoSocialDisabled: "Dette objekt er blevet deaktiveret af administratoren",
				settingsDataFieldsExplain: "Vælg fotonavn, billedtekst og farvefelter.",
				settingsDataFieldsError: "Applikationen kan ikke fastsætte et passende navn, billedtekst eller farvedata. Vælg de felter, der skal bruges her. Disse indstillinger kan ændres på et senere tidspunkt.",
				settingsFieldsLabelName: "Navn",
				settingsFieldsLabelDescription: "Billedtekst",
				settingsFieldsLabelColor: "Farve",
				settingsFieldsReset: "Nulstil feltvalget",
				settingsExtentExplain: "Indstil startudstrækningen for kortturen via det interaktive kort nedenfor.",
				settingsExtentExplainBottom: "Den udstrækning, du definerer, vil ændre din første webkortudstrækning. Bemærk, at denne udstrækning ikke bruges, hvis den ikke indeholder det første turpunkt. Hvis det er tilfældet, åbnes turen som centreret på det første punkt.",
				settingsExtentDateLineError: "Udstrækningen må ikke krydse meridianen på længdegraden 180°",
				settingsExtentDateLineError2: "Fejl ved behandlingen af udstrækningen",
				settingsExtentDrawBtn: "Tegn ny udstrækning",
				settingsExtentModifyBtn: "Redigér udstrækningen",
				settingsExtentApplyBtn: "Vis på Map Tour",
				settingsExtentUseMainMap: "Brug Map Tour-udstrækning",
				settingsZoomExplain: "Indstil zoom for historiepunkter efter introduktionen (valgfrit).",
				settingsLabelZoom: "Skala/niveau",
				settingsZoomFirstValue: "Ingen",
				settingsFieldError: "Marker et felt i hver liste",
				dataTitle: "ø_ArcGIS Online hosting_å",
				dataExplain: "ø_The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />Note that if you share the application through the item page, the system will ask if you also want to share the Feature Service. This is a required step. You will remain the only one with editing privileges._å",
				dataNameLbl: "Tjenestenavn",
				dataFolderListLbl: "Mappe",
				dataFolderListFetching: "Henter mapper...",
				dataRootFolder: "Rod",
				dataNameError: "Indtast et navn for featuretjenesten",
				dataFolderError: "Vælg en gyldig mappe",
				dataSrcContainsInvalidChar: "Navnet på featuretjenesten indeholder et eller flere ugyldige tegn (-, <, >, #, %, :, \", ?, &, +, / eller \).",
				dataSrvAlreadyExistsError: "Der findes allerede en tjeneste med dette navn i organisationen. Vælg et andet navn.",
				dataBtnSave: "Opret tjenesten",
				dataFooterProgress: "Oprettelse i gang",
				dataFooterSucceed: "Oprettelse lykkedes. Indlæser",
				dataFooterError: "Oprettelse mislykkedes. Prøv igen",
				tabError: "Kontrollér for fejl på alle faner",
				introRecordBtn: "Introduktion",
				introRecordActivate: "Brug det første punkt som introduktion (vises ikke i karrusellen)"
			},
			addPopupJS: {
				uploadingPicture: "Overfører billede",
				uploadSuccess: "Overførsel lykkedes",
				uploadError: "Fejl ved overførsel af billede",
				uploadError2: "Fejl ved tilføjelse af objektet (ugyldig html-kode)",
				notJpg: "Vælg et jpeg-foto at overføre",
				errorNoPhoto: "Vælg et billede at overføre",
				errorNoThumbnail: "Vælg et miniaturebillede at overføre",
				errorInvalidPicUrl: "Indtast en gyldig billed-URL (begynder med http(s)://, slutter med jpg, png, gif eller bmp). Du kan slutte URL\'en med \'#isImage\' for at tilsidesætte denne regel.",
				errorInvalidThumbUrl: "Indtast en gyldig miniature-URL (begynder med http(s)://, slutter med jpg, png, gif eller bmp).",
				errorInvalidVideoUrl: "Indtast en gyldig video-URL (starter med http(s)://)",
				errorNoName: "Angiv et navn for dette turpunkt",
				errorNoDescription: "Angiv en billedtekst for dette turpunkt",
				errorNoLocation: "Indstil en position for dette turpunkt"
			},
			builderJS: {
				noPendingChange: "ø_No unsaved change_å",
				unSavedChangeSingular: "1 ikke-gemt ændring",
				unSavedChangePlural: "ikke-gemte ændringer",
				shareStatus1: "ø_Tour is not saved_å",
				shareStatus2: "ø_Tour is shared publicly_å",
				shareStatus3: "ø_Tour is shared within the organization_å",
				shareStatus4: "ø_Tour is not shared_å",
				popoverDiscard: "Er du sikker på, at du vil slette nogle ikke-gemte ændringer?",
				yes: "Ja",
				no: "Nej",
				popoverLoseSave: "Ved at åbne viseren mister du eventuelle ikke-gemte ændringer",
				ok: "OK",
				popoverSaveWhenDone: "Glem ikke at gemme, når du er færdig",
				closeWithPendingChange: "Er du sikker på, at du vil bekræfte denne handling? Dine ændringer vil gå tabt.",
				gotIt: "OK",
				savingApplication: "Gemmer applikation",
				saveSuccess: "Applikation gemt med succes",
				saveError: "Lagring mislykkedes, prøv igen",
				saveError2: "Lagring mislykkedes pga. en ugyldig html-kode i et navn eller beskrivelse",
				saveError3: "ø_The title can't be empty_å",
				dragColorPicker: "Flyt mig rundt,<br />eller skift min farve",
				dataWarningExtent: "Du har data uden for webkortudstrækningen. Disse data vil ikke blive brugt som turpunkter. Du skal ændre kortudstrækningen, hvis du vil bruge dem.",
				dataWarningVisibi: "Dit Map Tour-lag er ikke synligt med den aktuelle webkortudstrækning. Bekræft, at dit Map Tour-lag vil være synligt med et %MAPSIZE% større kort.",
				dataWarningEdit: "Redigér webkort",
				dataWarningClose: "Luk",
				signIn: "Log ind med en konto på",
				signInTwo: "for at gemme applikationen.",
				switchBM: "ø_Change Basemap_å"
			},
			organizePopupJS: {
				messageStart: "Du har valgt at slette",
				messageSinglePoint: "ét turpunkt",
				messageMultiPoint: "turpunkter",
				messagePermantRemove: "Dette vil permanent fjerne",
				messageRecord: "post",
				messageRecordPlural: "poster",
				messageConfirm: "fra din database. Vil du fortsætte?",
				labelButtonShow: "Vis",
				labelButtonHide: "Skjul"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Dette vil slette billedet og miniaturen permanent",
				popoverDeleteWarningThumb: "Dette vil slette miniaturen permanent",
				popoverUploadingPhoto: "Overfører billede og miniaturebillede",
				popoverUploadingThumbnail: "Overfører miniaturebillede",
				popoverUploadSuccessful: "Overførsel lykkedes",
				popoverUploadError: "Overførsel mislykkedes, prøv igen",
				changePicAndThumb: "Redigér billede",
				changeThumb: "Redigér miniaturebillede",
				selectPic: "Redig\ér medier",
				selectThumb: "Redig\ér miniaturebillede",
				uploadPicAndThumb: "Anvend"
			},
			headerJS:{
				editMe: "Redig\ér mig!",
				templateTitle: "Indstil skabelontitel",
				templateSubtitle: "Indstil skabelonundertitel"
			},
			crossFaderJS:{
				setPicture: "Indstil billedtitel",
				setCaption: "Indstil billedtekst"
			},
			importPopup: {
				title: "Import\ér",
				prevBtn: "Tilbage",
				nextBtn: "Næste"
			},
			importPopupHome: {
				header: "Hvor er dine billeder lagret?"
			},
			onlinePhotoSharingCommon: {
				pictures: "billeder",
				videos: "videoer",
				disabled: "Dette objekt er blevet deaktiveret af administratoren",
				disabledPortal: "Dette objekt er deaktiveret på Portal for ArcGIS",
				header1: "ø_Your pictures must be shared publicly._å",
				header2: "ø_The import will be limited to the first %NB1% %MEDIA%._å",
				emptyDataset: "Fejl, der blev ikke fundet nogen billeder",
				footerImport: "Import\ér",
				selectAlbum: "Vælg et offentligt album",
				selectAlbum2: "Vælg et album",
				pleaseChoose: "Vælg",
				userLookup: "Slå op",
				userLookingup: "Slår op",
				csv: "Refereres til i en CSV-fil",
				advanced: "Avancerede indstillinger",
				advancedScratchLbl: "ø_Start a new Tour_å",
				advancedScratchTip: "ø_Create an empty Tour that you will be able populate manually using a wizard._å",
				advancedCSVLbl: "ø_Import Tour data from a CSV file_å",
				advancedCSVTip: "ø_Import your Tour content from a CSV file._å",
				advancedCommonTip: "ø_It requires that your images and videos are already online._å",
				select: "Foretag en markering",
				locUse: "ø_Use pictures geolocation_å",
				locExplain: "ø_You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location._å",
				locExplain2: "ø_You may not want to use videos location as they can be inherited from the user settings, resulting in all videos being at the same location._å"
			},
			viewFlickr: {
				title: "ø_Flickr import_å",
				header: "ø_Enter your Flickr user name and select a Photo Set or a Tag to be imported._å",
				userInputLbl: "Indtast et brugernavn",
				signInMsg2: "Bruger ikke fundet",
				selectSet: "Vælg et fotosæt",
				selectTag: "eller vælg et nøgleord",
				footerImportTag: "Import\ér det valgte nøgleord",
				footerImportSet: "Import\ér det valgte sæt"
			},
			viewFacebook: {
				title: "ø_Facebook import_å",
				header: "ø_Authenticate with your Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private._å",
				leftHeader: "Facebook-bruger",
				rightHeader: "Facebook-side",
				pageExplain: "En Facebook-side er et offentligt varemærke//produkt eller en celebritet ligesom <b>esrigis</b>. Du kan få sidenavnet efter den første \'\/\' i sidens URL.",
				pageInputLbl: "Indtast et sidenavn",
				lookupMsgError: "Side ikke fundet"
			},
			viewPicasa: {
				title: "ø_Picasa/Google+ import_å",
				header: "ø_Enter your email address or the ID of your Picasa or Google+ account._å",
				userInputLbl: "Indtast e-mail eller ID",
				signInMsg2: "Kontoen kunne ikke findes",
				howToFind: "ø_How to find a Picasa or Google+ account ID_å",
				howToFind2: "Kopier tal mellem første og anden \'\/\' på Picasa eller en G+-side"
			},
			viewCSV: {
				title: "ø_CSV import_å",
				uploadBtn: "Mark\ér eller slip en CSV-fil",
				resultHeaderEmpty: "CSV-filen er tom",
				resultHeaderSuccess: "Der er indlæst %NB_POINTS% punkter",
				resultHasBeenLimited: "Importen blev begrænset til de første %VAL1% punkter ud af %VAL2% for at overholde grænsen på %VAL3% punkter pr. tur",
				browserSupport: "Din browser understøttes ikke. Hvis du vil bruge en CSV-fil, skal du <a href='http://browsehappy.com/' target='_blank'>opgradere din browser</a> eller bruge ArcGIS.com-webkortviser (se Hjælp).",
				errorLatLng: "Der blev ikke fundet bredde- og længdegradsfelter. Mulige værdier for breddegrad er: <i>%LAT%</i> pg for længdegrad: <i>%LONG%</i>.",
				errorFieldsExplain: "Indlæsningen mislykkedes, de følgende påkrævede felter ikke blev fundet",
				errorFieldsName: "<b>Navn</b> mulige værdier er: %VAL%",
				errorFieldsDesc: "<b>Beskrivelse</b> mulige værdier er: %VAL%",
				errorFieldsUrl: "<b>Billed-URL</b> mulige værdier er: %VAL%",
				errorFieldsThumb: "<b>Miniature-URL</b> mulige værdier er: %VAL%",
				errorFields2Explain: "Indlæsningen mislykkedes, da CSV-filen ikke ikke bruger samme attributter som laget for følgende attributter",
				errorFields2Name: "<b>Navn</b> brug %VAL1% i stedet for %VAL2%",
				errorFields2Desc: "<b>Beskrivelse</b> brug %VAL1% i stedet for %VAL2%",
				errorFields2Url: "<b>Billed-URL</b> brug %VAL1% i stedet for %VAL2%",
				errorFields2Thumb: "<b>Miniature-URL</b> brug %VAL1% i stedet for %VAL2%",
				resultFieldsAll: "Alle attributter er importeret",
				resultFieldsNotAll: "Følgende attributter er ikke importeret, da de ikke eksisterer i kortlaget",
				resultFieldsNotAll2: "Følgende attributter er  importeret",
				footerNextBtnResult: "Import\ér til webkortet",
				footerProgress: "Import i gang",
				footerSucceed: "Import lykkedes. Indlæser"
			},
			viewYoutube: {
				title: "ø_Youtube import_å",
				header: "ø_Enter a YouTube user name to find publicly shared videos._å",
				pageInputLbl: "ø_Enter a Youtube user name_å",
				lookupMsgError: "Bruger ikke fundet",
				howToFind: "ø_How to find a Youtube user name_å",
				howToFind2: "Brugernavnet vises under videoer",
				found: "Fundet",
				noData: "Ingen offentlige videoer fundet"
			},
			viewGeoTag: {
				title: "ø_Select and locate your images/videos_å",
				header: "Klik eller tryk på de billeder, du vil importere, for at finde dem.",
				headerMore: "ø_Why aren't my images/videos geolocated?_å",
				headerExplain: "ø_If your pictures have a valid geolocation, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't store the geolocation EXIF metadata when you import pictures. Check Picasa/Flickr privacy settings to enable pictures geolocation import and usage by external application. You may have to reimport your existing pictures into Flickr/Picasa for the EXIF geolocation to be used.<br /><br />In Facebook, you have to go to each picture, click Edit and select the location._å",
				leftPanelTab1: "Skal findes",
				leftPanelTab2: "Fundet",
				clickOrTap: "Klik eller tryk på kortet for at finde",
				clearLoc: "ø_Clear locations_å",
				clickDrop: "Import\ér ikke",
				footerImport: "Import\ér",
				footerProgress: "Import i gang",
				footerSucceed: "Import lykkedes. Indlæser...",
				loading: "Indlæser",
				error: "ø_Pictures geolocation import failed, geolocations have been ignored._å"
			},
			initPopup: {
				title: "ø_Welcome to the Map Tour Builder_å",
				prevBtn: "Tilbage",
				nextBtn: "Næste"
			},
			initPopupHome: {
				header1: "ø_Where are your images or videos?_å",
				header2: "ø_This assistant will help you build a Map Tour from media already stored online or it will import them into your ArcGIS Online for Organizations account._å",
				title1: "ø_They are already online_å",
				title2: "ø_I need to upload my images_å",
				hostedFSTooltip: "ø_Use ArcGIS Online to host your images (doesn't support videos)._å",
				hostedFsNA: "ø_Only available for ArcGIS for Organizations Publisher and Administrator users_å",
				footer1: "Når du er færdig, skal du huske at dele din Map Tour med dit publikum gennem siden for applikationselementer.",
				footer3: "Download CSV-skabelonen",
				footer4: "\"Gem som\" hvis den ikke overføres",
				footer4bis: "ø_Use right click and \"Save as\" if download doesn't start_å",
				footer5: "ø_Learn more_å",
				footerProgress: "Oprettelse i gang",
				footerSucceed: "Oprettelse lykkedes. Indlæser..."
			},
			helpPopup: {
				title: "ø_Help_å",
				close: "Luk",
				tab1: {
					title: "Introduktion",
					div1: "ø_The Map Tour template is designed for presenting geographic information where there is a compelling photographic or media element to the story you want to tell._å",
					div2: "ø_The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets. <br /><br />Here's an example of the sort of application you can create:_å",
					div4: "ø_<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>._å",
					div42: "ø_To see examples of map tours that other users are creating, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visit the gallery</a> on the <a href='http://storymaps.esri.com/' target='_blank'>Story Maps website</a>. You can also follow us on Twitter at <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>._å",
					div5: "ø_We would love to hear from you! Whether you have a question, want to request a new feature, or think you've found a bug, please visit the <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>._å"
				},
				tab2: {
					title: "Data",
					div1: "Det vigtigste, du skal overveje, når du skal oprette en Map Tour, er hvor dine billeder skal lagres. En Map Tour kan bruge billeder, der er lagret på større fotodelingstjenester, webservere eller som vedhæftede filer på en featuretjeneste.",
					div1a: "Se det sidste afsnit på denne fane for at få oplysninger om understøttede formater og videoer.",
					div2: "Det interaktive builder-program indeholder to muligheder til håndtering af billeder i din Map Tour:",
					div3: "<ul><li>Du kan bruge <b>fotos, der allerede er online</b>, f.eks. billeder, der er gemt på et fotodelings-websted som Flickr, eller billeder, der er gemt på dit eget websted. Der vil være referencer til disse billeder i din Map Tour via deres URL\'er.</li><li>Du kan også <b>overføre billeder fra din computer</b> direkte til din Map Tour. Denne mulighed kræver, at du har et ArcGIS Online-abonnement, og at du har udgiver- eller administratorrettigheder, fordi der automatisk oprettes en \"hosted\" featuretjeneste til dig, hvor dine fotos gemmes som vedhæftninger.</li></ul>",
					div4: "Typiske brugerscenarier:",
					div4b: "<b>Dine billeder er ikke \"hosted\"</b> endnu, og du har et ArcGIS Online-abonnement: Det er dit bedste valg at benytte en \"hosted\" featuretjeneste. Ligesom på offentlige fotodelingstjenester vil vi optimere dine billeder med henblik på at oprette billeder, der indlæses hurtigt, og du får adgang til alle administrations- og datahåndteringsfunktionerne på ArcGIS-platformen.",
					div5: "<b>Du er ikke medlem af en organisation</b>: Du skal først overføre dine billeder til et fotodelings-websted eller til din egen webserver. Builder-programmet hjælper dig med at anvende disse billeder, der fortsat vil være \"hosted\" på deres oprindelige placering.",
					div6: "<b>Du vil gerne genbruge en eksisterende featuretjeneste,</b> som gemmer dine billeder som vedhæftede filer, eller som henviser til eksterne billeder: Se afsnittet med detaljerede oplysninger nedenfor.",
					div7: "<b>Du bruger en tidligere version</b> af Map Tour-skabelonen og har allerede en CSV-fil, der henviser til dine billeder og miniaturer: Du kan importere den og forfine dine data. Builder-programmet understøtter kun CSV-filer, der benytter længde- og breddegradsfelter. Adressebaserede CSV-filer kan fortsat benyttes via dit webkort (se nedenfor).",
					div8: "Import fra online fotodelingstjenester",
					div9: "Denne import-handling henviser til billeder, der allerede er \"hosted\" ved at gemme deres URL\'er i en samling af webkorttjenester. Billederne gemmes ikke på ArcGIS Online. Hvis du ikke kan få adgang til de \"hostede\" billeder, vil de ikke være tilgængelige i din Map Tour, og du får vist et billede med teksten \'Billedet er ikke tilgængeligt\'. Det afhænger af tjenesteudbyderen, om din Map Tour importerer navn, beskrivelse og placering for billederne. Disse attributter gemmes i webkortet, og eventuelle redigeringer af online-tjenesten vises ikke i Map Tour.",
					div10: "Lagring af billeder på en web-server",
					div11: "Hvis du vælger selv at \"hoste\" billederne, skal du manuelt oprette miniaturebilleder til dine billeder. Hvis du bruger billeder med fuld opløsning til miniaturebillederne, bliver de ikke gode. Vi anbefaler derfor, at du bruger en online fotodelingstjeneste eller en featuretjeneste til dette.",
					div12: "Brug af en eksisterende featuretjeneste eller shapefil",
					div13: "Alle punkt-featuretjenester og shapefiler kan bruges som Map Tour-datakilde. Du skal blot tilføje dem som et lag i dit webkort via ArcGIS.com-kortviseren. Hvis applikationen finder de forventede attributter i dine lag, vil alle builder-funktioner være tilgængelige.",
					div14: "ø_The possible values for fields name are (case insensitive):_å",
					div151: "Navn",
					div152: "Beskrivelse",
					div153: "Billede",
					div154: "Miniature",
					div155: "ø_Color_å ",
					div16: "ø_If the application doesn't find matching fields when using a feature service, the viewer will not work until you configure the fields to be used through the builder. CSV and shapefile layers added to the web map need to have all the required fields or the builder won't work._å",
					div162: "Når du anvender en featuretjeneste, der gemmer billeder som vedhæftede filer, <b>er det kun objekter med to vedhæftninger, der benyttes</b>. Den første vedhæftning definerer hovedbilledet, og den anden definerer miniaturen.",
					div17: "Billed- og miniaturefelterne er obligatoriske for featuretjenester uden vedhæftninger og valgfrie (men anbefalede) for featuretjenester med vedhæftninger. Hvis din tjeneste har vedhæftninger aktiveret, kan du overføre billeder som vedhæftede filer med builder-programmet. Hvis ikke, kan du kun redigere billed- og miniature-URL\'erne.",
					div172: "Billed- og miniaturefelterne vil, når de findes, altid blive brugt, og der vil ikke blive anmodet om featuretjenestens vedhæftninger.",
					div173: "Eksempel-CSV-filer og shapefiler kan overføres fra",
					div18: "Opretter en \"hosted\" featuretjeneste ud fra en CSV- eller shapefil",
					div19: "Når du opretter en \"hosted\" featuretjeneste på basis af en CSV- eller shapefil, er vedhæftninger ikke aktiveret som standard. Hvis du vil aktivere dem, skal du åbne featuretjenestens oplysningsside og klikke på den lille pil på lagsektionen for at få indstillingen vist. Map Tour\'en vil fortsat bruge de billeder og miniaturer, du har refereret til via attributter. Hvis du vil overføre dine billeder som  featuretjeneste-vedhæftninger, kan du gøre det vha. to knapper på billedpanelet (\"Redig\ér billede\" og \"Redig\ér miniature\").",
					div20: "Understøttede billedformater og videoer",
					div21: "Understøttede billedformater er: <b>.jpg, .jpeg, .png, .gif og .bmp</b>. Hvis dit medie ikke slutter med en af disse filtypenavne, vil Map Tour betragte mediet som en video, undtagen når du bruger en featuretjeneste (se nedenfor).",
					div22: "Map Tour-skabelonen indeholder ikke en videoafspiller, så du skal bruge den eksterne videoafspiller, som leveres af din foretrukne værtstjeneste for videoindhold (find indstillingen til indlejring af videoen, og kopi\ér den URL, der findes i den givne kode). Hvis du selv ønsker at \"hoste\" videoen, kan du oprette en HTML-side, der indeholder en videoafspiller som f.eks. <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Det interaktive builder-program indeholder ikke nogen dialogboks, som kan benyttes til at inkludere videoer, når du bruger featuretjenester med vedhæftninger, men det er muligt at gøre dette ved at redigere dine data uden for det interaktive builder-program. I ArcGIS-kortviseren vil dit medie blive betragtet som en video, hvis du redigerer billedfelterne, så de peger på en ekstern video og tilføjer en særlig parameter i slutningen af din URL (#isVideo).",
					div24: "Bemærk, at du fortsat skal have to gyldige vedhæftede billeder, ellers vil punktet ikke blive anvendt. Du kan ikke bruge videoer, når du benytter featuretjeneste-vedhæftninger uden billed- og miniaturefelter."
				},
				tab3: {
					title: "Tilpasning",
					div1: "Map Tour builder indeholder flere muligheder for tilpasning, der er tilgængelige via knappen INDSTILLINGER i toppanelet. Hvis du ikke kan finde den indstilling, du skal bruge, findes der også en version, der kan downloades til din webserver, hvor du kan bruge den til de indstillinger, du ønsker.",
					div2: "Vi anbefaler, at du bruger den \"hostede\" version, medmindre:",
					div3: "<li>Den ikke indeholder den UI-tilpasning, du ønsker, f.eks. brug af et baggrundsbillede til overskiften</li><li>Du er udvikler, og du ønsker at forbedre applikationen.</li>",
					div4: "Den overførbare version kan konfigureres via en webkort- eller en webkortapplikationsidentifikator. De primære brugssituationer er:",
					div41: "Du opretter din map tour med det interaktive builder-program i værtsmiljøet og konfigurerer skabelonen med et webkortapplikations-ID. De indstillinger, du har defineret med det interaktive builder-program, vil blive anvendt.",
					div42: "ø_You build your web map outside of the interactive builder and configure the template with the web map identifier. You will have to read the documentation to learn how to configure the template._å",
					div43: "Bemærk, at det interaktive builder-program er tilgængeligt i en version, der kan overføres, men at der er nogle tekniske begrænsninger for browsere, f.eks. Internet Explorer, der er ældre end version 10.",
					div5: "ø_To download the most recent version of the template and learn more about how to use it, visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>._å"
				},
				tab4: {
					title: "Tips",
					div0: "Understøttede browsere",
					div0a: "Map Tour-viewer-programmet understøttes af IE8+. Det interaktive builder-program understøttes af IE9+. Vi tester programmet i alle de store browsere, men hvis du kommer ud for vanskeligheder, anbefaler vi, at du bruger Chrome.",
					div0b: "Giv os gerne besked, hvis du kommer ud for vanskeligheder. I mellemtiden vil du, når du opretter din Map Tour ved hjælp af CSV-skabelonen, minimere din interaktion med builder-programmets grænseflade.",
					div1: "Billeder",
					div2: "ø_We recommend landscape orientation photos instead of portrait orientation. Photos with a 4:3 aspect ratio fits best. Portrait orientation images can be used, but on smaller screens like the iPad a lot of the photo may be obscured by the caption (text takes up more space when it is displayed in a tall area compared to a wide area). Although images of different sizes, shapes, and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour._å",
					div2a: "ø_We recommend a maximum image size of 1000 pixels wide x 750 pixels tall for the main pictures and 140x93 for the thumbnails._å",
					div3: "Formatering af din billedtekst vha. HTML-tags",
					div4: "Overskrifts- og billedtitlen/-teksten kan indeholde HTML-tags, der definerer formatering og links. For eksempel tilføjer denne kode et gult link:",
					div4a: "ø_Write a good subtitle for your tour_å",
					div4b: "ø_Take time to write a compelling subtitle for your tour. The subtitle is a good way to draw people into your tour and tell them what they will discover in it. It is also a good place to tell your audience the state or country that the tour is located in. For example don't assume that people know where the city or town in your tour is located. Your caption can also be formatted using HTML tags, such as including links. Don't make the caption too long though. In smaller browser windows or on the iPad it may not fit completely and be clipped. If you can't think of a good subtitle, leave it blank._å",
					div5: "Understøttende lag",
					div6: "Du kan tilføje flere understøttende lag, der giver yderligere kontekst til din Map Tour. Disse lag kan indeholde andre geografiske objekter, som du ønsker, at kortet skal vise som supplement til Map Tour-punkterne, såsom et undersøgelsesområde, en gå- eller kørerute, der forbinder dine tour-punkter osv. Map Tour-skabelonen viser disse supplerende supportlag vha. den symbologi, du angiver i webkortet, men pop-up-vinduerne er ikke tilgængelige.",
					div7: "Pas på, din tour ikke bliver for lang",
					div8: "Der er en begrænsning på 99 punkter pr. tour. De fleste Map Tours vil naturligvis være væsentligt kortere end dette. Publikum har som regel ikke lyst til at gå igennem alt for mange tour-punkter. Det er ikke sikkert, de finder dit emne lige så spændende, som du gør!",
					div9: "Se <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>detaljeret vejledning</a> for at få flere oplysninger.",
					div10: "Indlejringstilstand",
					div11: "Hvis du ønsker at indlejre skabelonen på et andet websted via en iframe, fjernes overskriften, hvis du tilføjer den valgfrie parameter \"&embed\" i slutningen af URL\'en. Du kan også benytte denne tilstand i den version, der kan overføres, ved at bruge konfigurationsfilen.",
					div12: "ø_Avoid using a narrow iFrame width that causes the map tour to switch to its responsive small screen touch-based layout. To maximize ease of use. When you embed a map tour, we always recommend still providing a link next to the embedded tour so that users can launch the tour full-screen._å" 
				},
				tab5: {
					title: "Udgivelse",
					div1: "ø_When you are done, don't forget to share your Map Tour with your audience through the SHARE button or the application item page in ArcGIS Online._å",
					div2a: "ø_Sharing the Tour through the builder_å",
					div2b: "ø_The SHARE button will update the application and webmap items. If your Tour data are stored in a Feature Service item, it will also be updated. If you have added others layers through ArcGIS.com map viewer, they won't be updated. This can result in the Tour not being shared as you expect. Items that already have the required (or more) privileges won't be updated._å",
					div2c: "ø_Sharing the Tour through ArcGIS Online_å",
					div2d: "ø_When you share the application through ArcGIS Online, it will if necessary ask you to update any dependent resources (web map, feature service, decoration layer) that aren’t shared in the same way. If the Map Tour is public and one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page._å",
					div3t: "ø_Feature Service security_å",
					div3a: "ø_If you are using a hosted feature service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges, even if you share the service publicly._å",
					div3t2: "ø_Before sharing your Tour with your audience_å",
					div3: "ø_Make sure the Tour works well when you are not signed in with your ArcGIS.com account. The URL you are going to use should not redirect to a login page or to the builder mode._å",
					div4: "ø_It is a good idea to see what your map tour looks like on an iPad held in landscape orientation to make sure it looks good on this popular device. This can help you see if your captions cover up too much of the pictures. It also lets you see if your subtitle fits and isn't so long that it gets clipped._å",
					div5a: "ø_Recommendation for search_å",
					div5b: "ø_To help people find your Map Tour if they search in ArcGIS Online, we recommend that you add the tag 'story map' into your map tour's application item page (not your web map's item page), along with tags such as the name of the state or province where the tour is located, the country name if it is outside the USA, and thematic tags like 'public art', 'tourist guide' or 'historic places'. These tags also help us at Esri to find cool new examples of tours we can showcase in our galleries and promote in social media. We also recommend that you upload a nice looking thumbnail graphic into your application item page, such as a small screenshot of the tour or one of the pictures from it. This picture is used automatically if your map tour is added into an ArcGIS Online gallery._å"
				}
			},
			share: {
				firstSaveTitle: "ø_Tour successfully saved_å",
				firstSaveHeader: "ø_Your Tour is now saved in ArcGIS Online. Please read the following answers to frequent questions._å",
				firstSaveA1: "ø_If you are not familiar with ArcGIS Online or want a shortcut to access the authoring interface, you can save the following link: %LINK1%_å",
				firstSaveA1bis: "ø_The Tour can also be found in your <a href='%LINK2%' target='_blank'>ArcGIS Online content folder</a>._å",
				firstSaveQ2: "ø_Is my Tour shared?_å",
				firstSaveA2: "ø_Currently your Tour is not shared. To share it, use the SHARE button._å",
				shareTitle: "ø_Share your Tour_å",
				sharePrivateHeader: "ø_Your Tour is not shared, would you like to share it?_å",
				sharePrivateBtn1: "ø_Share publicly_å",
				sharePrivateBtn2: "ø_Share with my Organization_å",
				sharePrivateProgress: "ø_Sharing in progress..._å",
				sharePrivateErr: "ø_Sharing failed, try again or_å",
				sharePrivateOk: "ø_Sharing updated successfully, loading..._å",
				sharePreviewAsUser: "ø_Preview_å",
				shareHeader1: "ø_Your Tour is <strong>publicly accessible</strong>._å",
				shareHeader2: "ø_Your Tour is accessible by your organization members (login is required)._å",
				shareLinkHeader: "ø_Share the Tour with your audience_å",
				shareLinkOpen: "ø_OPEN_å",
				shareQ1Opt1: "ø_How do I keep the Tour private?_å",
				shareQ1Opt2: "ø_How do I keep the Tour private or share it publicly?_å",
				shareA1: "ø_Use %SHAREIMG% on <a href='%LINK1%' target='_blank'>the application item page</a>. If you also want to unshare the webmap, use <a href='%LINK2%' target='_blank'>the webmap item page</a>._å",
				shareA1bis: "ø_If you also want to unshare the Feature Service, use <a href='%LINK1%' target='_blank'>the Feature Service item page</a>._å",
				shareQ2: "ø_How do I edit the Tour later?_å",
				shareQ2bis: "ø_How do I get back to the authoring interface?_å",
				shareA2div1: "ø_Save and reuse the following link %LINK1% or use <a href='%LINK2%' target='_blank'>the application item page</a>._å",
				shareA2div2: "ø_As the owner of the application, when you are signed in on ArcGIS.com, the application includes a button to open the interactive builder:_å",				
				shareQ3: "ø_Where is the data stored?_å",
				shareA3: "ø_The Tour configuration is stored in <a href='%LINK1%' target='_blank'>this webmap item</a> and <a href='%LINK2%' target='_blank'>this web application item</a>. If you have used Flickr, Picasa, Facebook or YouTube import, your images and videos remains stored there and aren't duplicated in ArcGIS Online._å"
			}
        }
    })
);
