define({
  root: ({
    layer: "試_Layer___驗",
    sort: "試_Sort by___驗",
    order: "試_Order___驗",
    desc: "試_Desc__驗",
    asc: "試_Asc__驗",
    loading: "試_loading&hellip;______驗",
    search: "試_Search___驗",
    searchPlaceholder: "試_Find reports_____驗",
    noResults: "試_No results____驗",
    ascending: "試_Ascending____驗",
    descending: "試_Descending____驗"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});