define({
  "tagHeaderText": "Etiketler",
  "expandGroupDescText": "Dahası",
  "shrinkGroupDescText": "Az",
  "layoutText": "Düzen",
  "signInText": "Oturum Aç",
  "signOutText": "Oturumu Kapat",
  "showNullValue": "Yok",
  "detailsDisplayText": "Ayrıntılar",
  "sortByText": "Şuna göre sırala:",
  "sortByViewText": "Görünümler",
  "sortByDateText": "Tarih",
  "sortByNameText": "Ad",
  "gridViewTitle": "Kılavuz görünümü",
  "listViewTitle": "Liste görünümü",
  "appHeaderTitle": "Giriş",
  "allText": "TÜMÜ",
  "orgText": "KRL",
  "grpText": "GRP",
  "groupLogoText": "Grup Logosu",
  "appTypeText": "Tür",
  "appOwnerText": "Sahip",
  "tryItButtonText": "Görünüm",
  "downloadButtonText": "İndir",
  "appDesText": "Açıklama",
  "reviewText": "Yorumlar",
  "itemDetailsLegendTab": "GÖSTERİM",
  "itemDetailsInfoTab": "BİLGİ",
  "tagsText": "Etiketler",
  "sizeText": "Boyut",
  "accessConstraintsText": "Erişim ve Kullanım Kısıtlamaları",
  "numberOfCommentsText": "Yorumlar",
  "numberOfRatingsText": "Derecelendirmeler",
  "numberOfViewsText": "Görünümler",
  "noResultsText": "Hiçbir sonuç bulunamadı.",
  "backToMapButtonText": "Harita",
  "showMoreResultsGalleryText": "Daha fazla sonuç göster",
  "clearBtnTitle": "Temizle",
  "addressSearchBtnTitle": "Adres Araması",
  "fullScreenBtnTitle": "Tam ekran",
  "noLegendText": "Gösterim yok",
  "sizeUnitKB": "KB",
  "sizeUnitMB": "MB",
  "itemUnavailableText": "Öğe bu cihazda kullanılamaz.",
  "title": {
    "settingsBtnTitle": "Ayarlar",
    "itemSearchBtnTitle": "Öğe Araması",
    "infoBtnTitle": "Bilgi",
    "sortByBtnTitle": "Şuna göre sırala:",
    "layoutBtnTitle": "Düzen",
    "signInBtnTitle": "Oturum Aç",
    "signOutBtnTitle": "Oturumu Kapat",
    "geolocationBtnTitle": "Coğrafi Konum",
    "ascendingSort": "Artan",
    "descendingSort": "Azalan",
    "viewBtnTitle": "ı_View__İ",
    "backButtonTitle": "ı_Back__İ"
  },
  "errorMessages": {
    "emptyGroup": "Yapılandırılan grup için sorgu uygulanabilecek veri yok.",
    "invalidSearch": "Hiçbir sonuç bulunamadı.",
    "invalidBasemapQuery": "Altlık haritası grubu alınamıyor.",
    "falseConfigParams": "Gerekli olan yapılandırma anahtarı değerleri boş ya da katman öznitelikleriyle tam olarak eşleşmiyor. Bu mesaj birkaç kez görüntülenebilir.",
    "invalidLocation": "Geçerli konum bulunamadı.",
    "invalidProjection": "Geçerli konum haritada tahmin edilemiyor.",
    "widgetNotLoaded": "Araçlar yüklenemedi.",
    "minfontSizeGreater": "Yapılandırma ayarlarındaki en küçük yazı tipi değeri, en büyük değerden büyük.",
    "layerNotFound": "Katmanlardan veri alınamıyor.",
    "unableToOpenItem": "Öğe açılamıyor.",
    "wmsSpatialReferenceError": "WMS katmanı mekansal başvurusu, haritanın mekansal başvurusu ile eşleşmiyor.",
    "noPublicItems": "Yapılandırılan grupta herhangi bir genel öğe yok ya da bu grupla henüz bir öğe paylaşılmamış.",
    "emptyUsernamePassword": "Kullanıcı Adı ve Şifre girin.",
    "noFullScreenSupport": "Geçerli tarayıcı tam ekran modunu desteklemiyor.",
    "notMemberOfOrg": "Bu kuruluşun üyesi değilsiniz"
  }
});