define({
    root: ({
        map: {
            error: "No se puede crear el mapa",
            views: "vistas."
        },
        report: {
            flag: "Marcar como inadecuado",
            error: "Error",
            success: "Marcado",
            loading: "Cargando&hellip;"
        },
        mapNotes:{
            notesUnavailable: "Descripción no disponible",
            bookmarks: "Marcadores",
            zoomTo: "Haz zoom a esta ubicación y obtén más información.",
            untitledNote: "Sin título"
        },
        social: {
            flickr: "Flickr",
            mediaLayers: "Capas de medios",
            mediaLayersDescription: "Mostrar contribuciones del público en el mapa.",
            flickrSettings: "Configuración de Flickr",
            twitter: "Twitter",
            twitterSettings: "Configuración de Twitter",
            twitterUser: "Cuenta de Twitter",
            twitterSignIn: "Iniciar sesión en Twitter",
            webcams: "Webcams.travel",
            instagram: "Instagram",
            instagramSettings: "Configuración de Instagram",
            igTime: "Cargados en los últimos días",
            youtube: "YouTube",
            youtubeSettings: "Configuración de YouTube",
            ytSettingsInfo: "Ve vídeos generados por el usuario, incluido el contenido profesional y de la red.",
            ytTime: "Cargados en el/la último/a",
            today: "Día",
            this_week: "Semana",
            this_month: "Mes",
            all_time: "Todo el tiempo",
            moreInfo: "Más información",
            searchTerms: "Términos de búsqueda",
            search: "Buscar",
            flSettingsInfo: "Devuelve los resultados que coinciden con el título, la descripción o las etiquetas de una foto.",
            twSettingsInfo: "Descubre lo que está sucediendo ahora mismo.",
            igSettingsInfo: "Instagram es una forma rápida, atractiva y divertida de compartir tu vida con tus amigos y tu familia.",
            advancedOperators: "Sugerencia: usa los <a target=\"_blank\" href=\"https://support.twitter.com/articles/71577-using-advanced-search\">operadores</a> para crear búsquedas avanzadas.",
            tweetsFilteredBy: "tweets filtrados por:",
            photosFilteredBy: "fotos filtradas por:",
            videosFilteredBy: "vídeos filtrados por:",
            twitterAccountStatus: "Habilita la capa de Twitter para ver tu estado."
        },
        general: {
            map: "Mapa",
            mapInfo: "Información del mapa",
            legend: "Leyenda",
            featured: "Ubicaciones destacadas",
            layers: "Capas",
            share: "Compartir",
            about: "Acerca de",
            find: "Código postal, ciudad, etc.",
            moreInfo: "Más información",
            dateModified: "Última modificación",
            noSearchResult: "No se ha encontrado ningún resultado",
            switchAccount: "Cambiar la cuenta",
            signIn: "Iniciar sesión",
            settings: "Configuración"
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});