define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Atidaryti kūrimo įrankį",
                "exitBuilderButtonText": "Uždaryti kūrimo įrankį",
                "enterBuilderModeHelpText": "Paleisti kūrimo režimą aplikacijai konfigūruoti",
                "builderModeHelpText": "Šablono kūrimo režimas",
                "webmapCaption": "Žemėlapis",
                "selectMapMessage": "Šiuo metu ${displaying} <b>${webmapTitle}</b><br/>Paspauskite Pasirinkti žemėlapį, kad pasirinktumėte kitą interneto žemėlapį",
                "loadMapMessage": "Šiuo metu pasirinktas <b>${webmapTitle}</b><br/>Paspauskite Įrašyti, kad naudotumėte šį interneto žemėlapį",
                "changeWebmap": "Pasirinkti žemėlapį",
                "saveButtonText": "Įrašyti",
                "webmapNextButtonText": "Kitas ->",
                "previousButtonText":"Ankstesnis",
                "layerLabelText": "Sluoksnis",
                "noLayerFoundText": "Sluoksnių nerasta",
                "selectLayer": "Pasirinkti sluoksnį",
                "applicationSettingText": "Aplikacijos nustatymai",
                "summaryAttrAscendingOrderTooltip": "Didėjimo tvarka",
                "onStartLabel": "Į_On Start_š",
                "selectVariableText": "Pasirinkite kintamąjį",
                "selectVariableDropdown": "Pasirinkite kintamąjį",
                "label":"Žymė",
                "sourceLinkText":"Šaltinio nuoroda",
                "selectSubVariableText":"Pasirinkite antrinius kintamuosius",
                "subVariablePanelButtonText":"ATLIKTA",
                "onButtonLabel":"Įjungta",
                "offButtonLabel":"Išjungta",
                "appSettingsSaveCloseButtonText": "ĮRAŠYTI IR UŽDARYTI",
                "appSettingsTitleText":"Aplikacijos pavadinimas",
                "appSettingsDescriptionText": "Aplikacijos aprašas",
                "appSetingsRendererAreaText":"Atvaizduojama sritis",
                "shareText":"Bendrinti",
                "basemapText":"Pagrindo žemėlapis",
                "basemapSelectionText":"Pagrindo žemėlapio pasirinkimas",
                "secondaryBasemapText":"Antrinis pagrindo žemėlapis",
                "defaultBasemapText": "Numatytasis pagrindo žemėlapis",
                "entireAreaButton": "Į_Entire Area_š",
                "entireAreaOnStartButton": "Į_Entire Area on start_š",
                "aboutPanel": "Į_About Panel_š",
                "legendPanel": "Į_Legend Panel_š",
                "layersPanel": "Į_Layers Panel_š",
                "dataConfigurationButtonText": "Duomenų konfigūravimas",
                "savingChangesMessage": "Įrašomi pakeitimai...",
                "nextButtonText": "Kitas",
                "prevButtonText": "Ankstesnis",
                "enterLabelText": "Įvesti žymę",
                "layerHelpTextMessage": "Šiai aplikacijai būtinas sluoksnis su skaitiniais laukais",
                "alertMessage": {
                    "resetVariableMessage": "Ar tikrai norite iš naujo nustatyti kintamąjį?",
                    "emptyAppTitleMessage": "Aplikacijos pavadinimas negali būti tuščia reikšmė",
                    "emptyDescriptionMessage": "Aprašas negali būti tuščia reikšmė",
                    "maxVariableSelection": "Negalite pasirinkti daugiau nei 25 antrinių kintamųjų",
                    "signInFail" : "Prisijungimas nepavyko",
                    "itemUpdateMessage": "Elementas atnaujintas",
                    "unsavedChangesMessage": "Neįrašyti pakeitimai",
                    "failMessage": "Nepavyko atnaujinti šio elemento",
                    "saveChangesAlert": "Ar norite įrašyti pakeitimus?",
                    "variableLabelValidation": "Kintamojo žymė negali būti TUŠČIA",
                    "subVariableLabelValidation": "Antrinio kintamojo žymė negali būti TUŠČIA"
                    }
            }
        }
    })
});