define(
	 ({
		header: {
			start: "한_start___빠",
			searchStories: "한_Search your stories________빠...",
			filter: "한_Filter___빠",
			sort: "한_Sort__빠",
			sortColon: "한_Sort___빠:",
			numResults: "한_Results: {{NUM_RESULTS}}________빠",
			sortBy: "한_Sort by___빠",
			dateModified: "한_Date modified_____빠",
			title: "한_Title___빠",
			type: "한_Type__빠",
			views: "한_Views___빠",
			errors: "한_Errors___빠",
			filterBy: "한_Filter by____빠",
			filterItems: "한_Filter Items_____빠",
			apps: "한_Apps__빠",
			sharing: "한_Sharing___빠",
			clearAll: "한_Clear all____빠",
			clearSearch: "한_Clears the search______빠",
			logOut: "한_Log Out___빠",
			mainQuote: "한_Storytelling is the most powerful way to put ideas into the world today_______________________빠.",
			quoteSource: "한_Robert McKee_____빠",
			checkYourStories: "한_Check Stories_____빠",
			createStory: "한_Create Story_____빠",
			totalStories: "한_Total stories: {{NUM_STORIES}}__________빠",
			noIssues: "한_All good___빠",
			userStories: "한_Stories of {{USER_NAME}}________빠",
			headerDisabledTooltip: "한_Please wait while we work some magic_____________빠...",
			notOnTouch: "한_Not available on touch devices__________빠",
		},
		deleteModal: {
			title: "한_Confirm Delete_____빠",
			warningText: "한_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________빠.",
			deleteText: "한_Delete___빠",
			cancel: "한_Cancel___빠"
		},
		loading: {
			loadingText: "한_Loading your stories________빠..."
		},
		cantFindStories: {
			whereAreStories: "한_Not seeing your story________빠?",
			notSeeExplanation: "한_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________빠.",
			faq: "한_FAQ__빠",
			followingStoriesToUpdate: "한_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________빠:",
			gettingStories: "한_Searching for stories created with early versions of our applications that need to be updated______________________________빠...",
			title: "한_Title___빠",
			typeOfStoryMap: "한_Type__빠",
			lastModified: "한_Last modified_____빠",
			allUpToDate: "한_No stories created with early versions of our applications need to be updated________________________빠.",
			updateAll: "한_Update All____빠",
			errorScanningForStories: "한_There was an error searching your stories______________빠.",
			close: "한_Close___빠",
			updates: "한_Updates___빠",
			updatingNumberOfNumber: "한_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________빠",
			updatingNumberOfNumberAlt: "한_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________빠",
			updateSucceeded: "한_Update succeeded______빠!",
			reloadingStories: "한_Reloading your stories_________빠...",
			errorUpdatingStories: "한_There was an error updating your stories_____________빠.",
			partialUpdateMessage: "한_Stories updated successfully: {{NUM_UPDATED}}_______________빠"
		},
		signIn: {
			signInTitle: "한_Sign in to Story Maps_______빠",
			signInTo: "한_Sign in with your existing ArcGIS Online account to_________________빠:",
			explanationOne: "한_Create compelling story maps to tell your stories________________빠.",
			explanationTwo: "한_Use your maps and data from ArcGIS Online in your story maps___________________빠.",
			explanationThree: "한_Manage your story maps and check the status of their content___________________빠.",
			dontHaveAccount: "한_Don't have an ArcGIS Online account? Sign up for a________________빠:",
			publicAccount: "한_Free non-commercial public account___________빠",
			orgAccount: "한_Free trial ArcGIS subscription__________빠",
			timeExpired: "한_Your sign-in expired. Sign in again to pick up where you left off_____________________빠.",
			apiDidntLoad: "한_Something isn't loading correctly. Try refreshing the page___________________빠.",
			needAccount: "한_Need an account______빠?",
			letsGo: "한_Let's go____빠!"
		},
		sharingLevel: {
			publicMessage: "한_Public___빠",
			privateMessage: "한_Private___빠",
			organization: "한_Organization_____빠",
			changedSharing: "한_Changed sharing level________빠.",
			unableToChange: "한_Unable to change sharing_________빠.",
			partOfMap: "한_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________빠.",
			storyPublicContentOrg: "한_Your story is public, so its content can't be shared only with your organization_________________________빠",
			storyPublicContentPrivate: "한_Your story is public, so its content can't be private_________________빠",
			mapOrg: "한_Sharing your map to your organization would break your story___________________빠",
			layerOrg: "한_Sharing your layer to your organization would break your story____________________빠",
			mapPrivate: "한_Making your map private would break your story_______________빠",
			layerPrivate: "한_Making your layer private would break your story_______________빠"
		},
		collectionList: {
			advocacy: "한_Advocacy and Outreach_______빠",
			architecture: "한_Architecture and Design________빠",
			conservation: "한_Conservation and Sustainability__________빠",
			culture: "한_Culture___빠",
			destinations: "한_Destinations and Tourism________빠",
			disasters: "한_Disasters and Recovery________빠",
			economy: "한_Economy and Development________빠",
			entertainment: "한_Entertainment_____빠",
			history: "한_History___빠",
			infrastructure: "한_Infrastructure_____빠",
			marketing: "한_Marketing____빠",
			nature: "한_Nature and Environment________빠",
			news: "한_News and Events______빠",
			oceans: "한_Oceans___빠",
			parks: "한_Parks and Recreation_______빠",
			people: "한_People and Society______빠",
			planning: "한_Planning and Analysis_______빠",
			publicArt: "한_Public Art____빠",
			science: "한_Science and Technology________빠",
			sport: "한_Sport___빠",
			travelogues: "한_Travelogues____빠"
		},
		types: {
			custom: "한_Custom___빠",
			notSpecified: "한_Type not specified______빠"
		},
		storyMap: {
			shared: "한_Shared___빠",
			saveFailed: "한_Error saving_____빠",
			numViews: "한_Views: {{NUM_VIEWS}}_______빠",
			editStory: "한_Edit Story____빠",
			viewLive: "한_View Live____빠",
			preview: "한_Preview___빠",
			deleteButton: "한_Delete___빠",
			modified: "한_Modified {{DATE}}______빠",
			summary: "한_Summary___빠",
			loading: "한_Loading____빠...",
			collapse: "한_collapse___빠",
			close: "한_close___빠",
			hide: "한_hide__빠",
			notAvailableWhenBroken: "한_Your story has issues below_________빠",
			cantBeDeleted: "한_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________빠",
			shareDialog: {
				title: "한_Share your story with the world___________빠!",
				notPublicWarning: "한_Your story is shared with your organization. Only members of your organization will be able to view it________________________________빠.",
				embedStory: "한_Embed your story______빠",
				shortLink: "한_Shortlink____빠",
				hideHeaderBar: "한_Hide header bar______빠",
				copied: "한_Copied___빠",
				small: "한_small___빠",
				medium: "한_medium___빠",
				large: "한_large___빠",
				custom: "한_custom___빠",
				widthAbbreviation: "한_w_빠",
				heightAbbreviation: "한_h_빠",
				emptyDimension: "한_Enter a dimension______빠.",
				seeExample: "한_Preview your embed______빠",
				removeHeader: "한_Hide application header________빠"
			},
			maps: {
				unableRetrieveTitle: "한_Unable to retrieve maps________빠",
				unableRetrieveDescription: "한_We weren't able to retrieve maps for this story map_________________빠."
			},
			images: {
				unableRetrieveTitle: "한_Unable to retrieve images_________빠",
				unableRetrieveDescription: "한_We weren't able to retrieve images for this story map_________________빠."
			},
			tags: {
				tags: "한_Tags__빠",
				collectionTags: "한_Subject___빠",
				selectASubject: "한_Select a subject______빠",
				save: "한_Save__빠",
				saved: "한_Saved___빠",
				errorSaving: "한_Error saving_____빠",
				tagTip: "한_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________빠."
			},
			submitToGallery: {
				gallerySubmission: "한_Story Maps Gallery______빠",
				canSubmitIf: "한_You can nominate your story to the gallery if it contains the following_______________________빠:",
				hasOwnImage: "한_Custom thumbnail______빠",
				chosenSubject: "한_A subject and some tags________빠",
				chosenSubjectAlt: "한_A {{SUBJECT}} and some tags_________빠",
				storyMapTopicSubject: "한_subject___빠",
				sharedPublicly: "한_Shared publicly______빠",
				noBrokenContent: "한_No broken content______빠",
				nominateToGallery: "한_Nominate to Gallery_______빠",
				comingSoon: "한_Coming soon_____빠!",
				submitted: "한_Submitted____빠",
				errorSubmitting: "한_Error submitting______빠",
				ourGallery: "한_The Story Maps gallery________빠",
				galleryTip: "한_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________빠."
			},
			placeholders: {
				noSummary: "한_No summary, click to add one__________빠."
			},
			errors: {
				cantDeleteStory: "한_Unable to delete story________빠.",
				unableToFind: "한_Unable to find content________빠",
				unableToRetrieve: "한_We weren't able to retrieve the content for this story map___________________빠."
			},
			socialSharing: {
				availableWhenPublic: "한_This option will be available when your story is public__________________빠"
			},
			dialog: {
				back: "한_Back__빠",
				close: "한_Close___빠",
				cancel: "한_Cancel___빠"
			},
			imagePicker: {
				changeDefault: "한_Change the default image________빠",
				changeImage: "한_Change thumbnail______빠",
				uploadImage: "한_Upload thumbnail______빠",
				chooseImage: "한_Choose thumbnail______빠",
				chooseAnImage: "한_Choose an Image______빠",
				notInIEVersion: "한_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________빠.",
				or: "한_Or__빠",
				uploadAnImage: "한_Upload an Image______빠",
				supportedFileTypes: "한_Supports .png, .jpg, .gif_________빠",
				imageSizeMessage: "한_Your image needs to be at least 286 px wide by 190 px tall___________________빠.",
				minimumDimensions: "한_Minimum: 286 x 190px_______빠",
				imagesLoading: "한_Loading images______빠...",
				noImages: "한_This story has no images________빠",
				errorLoading: "한_Unable to retrieve the images in this story______________빠",
				clickBelowTip: "한_Click the button below to upload an image______________빠.",
				dragAndDrop: "한_Drag and Drop_____빠",
				cropImage: "한_Crop Image____빠",
				saveImage: "한_Save Image____빠",
				save: "한_Save__빠",
				savingImage: "한_Saving your image_______빠...",
				saved: "한_Saved___빠!",
				errorSaving: "한_Unable to save your image_________빠.",
				skipAndCrop: "한_Skip and Crop for me_______빠",
				wrongFormat: "한_This file type is not supported___________빠.",
				noCropWarning: "한_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________빠."
			}
		},
		content: {
			media: {
				maps: "한_Maps__빠",
				images: "한_Images___빠",
				videos: "한_Videos___빠",
				webpages: "한_Webpages___빠",
				tags: "한_Tags__빠",
				gallery: "한_Gallery___빠"
			},
			headers: {
				status: "한_Status___빠",
				source: "한_Source___빠",
				name: "한_Name__빠",
				shared: "한_Shared___빠"
			},
			component: {
				mapTour: "한_Point Number_____빠",
				bullet: "한_Bullet___빠",
				tab: "한_Tab__빠",
				accordion: "한_Section___빠",
				mapJournal: "한_Section___빠"
			},
			titleType: {
				mapTour: "한_Caption___빠",
				mapJournal: "한_URL__빠",
				mapSeries: "한_URL__빠"
			},
			actions: {
				viewMap: "한_View Map___빠",
				editMap: "한_Edit Map___빠",
				fix: "한_Fix__빠",
				viewLayer: "한_View Layer____빠"
			},
			contentType: {
				mainStage: "한_main stage action______빠",
				sidePanel: "한_description____빠"
			},
			notification: {
				refreshExplanation: "한_Check your story again________빠",
				checking: "한_Checking____빠...",
				foundSomeIssues: "한_We found some issues_______빠",
				noIssuesFound: "한_No issues found______빠",
				storyPublic: "한_Your story is now public________빠",
				storyOrg: "한_Your story is now shared to your organization_______________빠",
				storyPrivate: "한_Your story is now private_________빠",
				mapPublic: "한_Your map is now public________빠",
				mapOrg: "한_Your map is now shared to your organization______________빠",
				mapPrivate: "한_Your map is now private________빠",
				layerPublic: "한_Your layer is now public________빠",
				layerOrg: "한_Your layer is now shared to your organization_______________빠",
				layerPrivate: "한_Your layer is now private_________빠",
				contentPublic: "한_Your content is now public_________빠",
				contentOrg: "한_Your content is now shared to your organization_______________빠",
				contentPrivate: "한_Your content is now private_________빠",
				storyAndContentPublic: "한_Your story and its content are now public_____________빠",
				storyAndContentOrg: "한_Your story and its content are now shared to your organization____________________빠",
				storyAndContentPrivate: "한_Your story and its content are now private______________빠",
				shareBulkPrompt: "한_Do you want to share your storyâ€™s content accordingly__________________빠?",
				layersPublic: "한_Some layers have also been shared publicly______________빠",
				layersOrg: "한_Some layers have also been shared with your organization__________________빠",
				layersPrivate: "한_Some layers have also been made private_____________빠",
				mapsPublic: "한_Some maps have also been shared publicly_____________빠",
				mapsOrg: "한_Some maps have also been shared with your organization_________________빠",
				mapsPrivate: "한_Some maps have also been made private____________빠",
				layersAndMapsPublic: "한_Some maps and layers have also been shared publicly________________빠",
				layersAndMapsOrg: "한_Some maps and layers have also been shared with your organization_____________________빠",
				layersAndMapsPrivate: "한_Some maps and layers have also been made private_______________빠",
				yes: "한_Yes__빠",
				no: "한_No__빠",
				premiumPublicSuccess: "한_Your premium content is now publicly accessible_______________빠",
				subscriptionPublicSuccess: "한_Your subscription content is now publicly accessible_________________빠"
			},
			errors: {
				publicDisabled: "한_Sharing publicly has been disabled by the Administrator__________________빠",
				noMapName: "한_Could Not Retrieve Map Name_________빠",
				notPublic: "한_NOT PUBLIC____빠",
				inaccessible: "한_INACCESSIBLE_____빠",
				deleted: "한_DELETED___빠",
				cantAccessVideo: "한_Could Not Access Video________빠",
				noStoriesFound: "한_We could not find any Story Maps in your content________________빠.",
				cantShowStories: "한_Unable to show your story maps. Please try again later__________________빠.",
				consolationSearch: "한_We couldn't find any stories__________빠.",
				notCompatibleWithBrowser : "한_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________빠.",
				pleaseUpdateBrowser: "한_Please update your browser_________빠.",
				searchTip: "한_Try and simplify it a bit_________빠.",
				consolationNoStories: "한_Welcome to My Stories________빠!",
				noStoriesTip: "한_To make your first story map, check out the Apps page_________________빠.",
				letsGo: "한_Let's Go___빠",
				cantChangeSharingLevel: "한_Unable to change sharing level__________빠",
				cantChangeSharingLevels: "한_Unable to change sharing levels__________빠",
				errorUpdatingTitle: "한_Error updating title_______빠",
				errorUpdatingSummary: "한_Error updating summary________빠",
				noEmptyTitle: "한_Title cannot be empty_______빠",
				cantUpdatePremiumContent: "한_Unable to update premium content___________빠",
				cantUpdateSubscriptionContent: "한_Unable to update subscription content____________빠",
				createFirstStory: "한_Create My First Story_______빠"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "한_Map has been deleted_______빠",
				layerHasBeenDeleted: "한_Layer has been deleted________빠",
				mapIsInaccessible: "한_Map is inaccessible_______빠",
				layerIsInaccessible: "한_Layer is inaccessible_______빠",
				mapNotYoursNotAccessible: "한_Map is owned by someone else and isn't accessible________________빠",
				layerServiceOkItemNot: "한_Layer was added as an item that is deleted or inaccessible__________________빠",
				layerNotYoursNotAccessible: "한_Layer is owned by someone else and isn't accessible________________빠",
				mapOthersSharedBelowLevel: "한_Map is not owned by you and is not public_____________빠",
				layerOthersSharedBelowLevel: "한_Layer is not owned by you and is not public______________빠",
				noMapNoDetails: "한_Without the map details, we can't tell you anything about the layers_____________________빠",
				mapIsPrivate: "한_Map is private_____빠",
				mapIsOrg: "한_Map is only shared in your organization_____________빠",
				layerIsPrivate: "한_Layer is private______빠",
				layerIsOrg: "한_Layer is only shared in your organization_____________빠",
				imageInaccessible: "한_This image is inaccessible_________빠",
				videoInaccessible: "한_This video is inaccessible_________빠",
				webpageInaccessible: "한_This web page is inaccessible__________빠",
				layerSecureService: "한_Layer is a secure service_________빠",
				mapSecureService: "한_Map is a secure service________빠",
				layerConsumesCredits: "한_Layer is premium content and consumes credits_______________빠",
				layerSubscriptionContent: "한_Layer is subscription content__________빠",
				mapConsumesCredits: "한_Map is premium content and consumes credits______________빠",
				mapSubscriptionContent: "한_Map is subscription content_________빠"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "한_We're not able to check this type of layer______________빠",
				cantScanThisType: "한_Layer is not a type of layer we can check_____________빠",
				webpageNotScanned: "한_Webpages are not checked for issues____________빠"
			},
			scanningErrors: {
				deletedMap: "한_Deleted content______빠",
				inaccessibleMap: "한_Inaccessible map content________빠",
				notYoursNotAccessible: "한_Content not owned by you and not public_____________빠",
				serviceOkItemNot: "한_Working layers but inaccessible items____________빠",
				someContentNotPublic: "한_Content not shared publicly_________빠",
				someContentPrivate: "한_Private content______빠",
				othersSharedBelowLevel: "한_Content not owned by you and not public_____________빠",
				premiumContent: "한_Premium content______빠",
				subscriptionContent: "한_Subscription content_______빠",
				secureService: "한_Secure services______빠",
				inaccessibleImage: "한_Inaccessible images_______빠",
				inaccessibleVideo: "한_Inaccessible videos_______빠",
				inaccessibleWebpage: "한_Inaccessible webpages_______빠"
			},
			scanningErrorTips: {
				deletedMapTip: "한_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________빠.",
				inaccessibleMapTip: "한_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________빠.",
				notYoursNotAccessibleTip: "한_Tip: Open the web map and remove the layer or map from the story_____________________빠.",
				serviceOkItemNotTip: "한_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________빠.",
				ignore: "한_Ignore___빠",
				fix: "한_Fix__빠",
				clickToShareOrg: "한_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________빠.",
				clickToSharePublic: "한_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________빠.",
				shareOrg: "한_Share to your org______빠",
				sharePublicly: "한_Share publicly_____빠",
				othersSharedBelowLevelTip: "한_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________빠.",
				secureServiceTip: "한_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________빠.",
				blogArticle: "한_here__빠",
				premiumContentTip: "한_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________빠.",
				premiumContentPublicTip: "한_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________빠.",
				subscriptionContentTip: "한_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________빠.",
				agolCredits: "한_ArcGIS Online credits_______빠",
				credits: "한_credits___빠",
				makePublic: "한_Make public____빠",
				confirm: "한_Confirm___빠",
				inaccessibleImageTip: "한_Tip: Provide the missing image or remove the reference to it___________________빠.",
				inaccessibleVideoTip: "한_Tip: Provide the missing video or remove the reference to it___________________빠.",
				inaccessibleWebpageTip: "한_Tip: Provide the missing web page or remove the reference to it____________________빠."
			},
			removeLayer: {
				title: "한_Fix Layer Issue______빠",
				layersWithIssue: "한_Layers with this issue: {{NUM_WITH_ISSUE}}______________빠",
				issueExplanation: "한_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________빠.",
				issueSolution: "한_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________빠:",
				editMap: "한_Edit Your Map_____빠",
				clickBelowWhenDone: "한_When you have finished editing, click the button below__________________빠:",
				rescanAndClose: "한_Rescan And Close______빠"
			},
			info: {
				ownedBy: "한_This item is owned by {{USER_NAME}}____________빠",
				unknownUser: "한_someone else_____빠",
				untitledSection: "한_(Untitled section)______빠",
				introRecord: "한_Introduction_____빠"
			},
			layers: {
				layersHeader: "한_Layers___빠",
				noLayers: "한_(No Layers)____빠",
				basemapParens: "한_(basemap)____빠"
			},
			images: {
				thumbnails: "한_Thumbnails____빠",
				thumbnail: "한_Thumbnail____빠",
				thumbnailParens: "한_(thumbnail)____빠"
			},
			general: {
				noTitle: "한_(no title)____빠",
				loading: "한_Loading____빠..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "한_sections___빠",
				secondTitle: "한_style___빠",
				secondValueA: "한_side panel____빠",
				secondValueB: "한_floating panel_____빠",
				thirdTitle: "한_maps__빠"
			},
			mapTour: {
				firstTitle: "한_tour points____빠",
				secondTitle: "한_style___빠",
				secondValueA: "한_integrated____빠",
				secondValueB: "한_three-panel____빠",
				thirdTitle: "한_basemap___빠",
				thirdValueLoading: "한_Loading____빠...",
				thirdValueUnknown: "한_unknown___빠"
			},
			mapSeries: {
				firstTitleA: "한_bullets___빠",
				firstTitleB: "한_sections___빠",
				firstTitleC: "한_tabs__빠",
				secondTitle: "한_style___빠",
				secondValueA: "한_bulleted___빠",
				secondValueB: "한_side accordion_____빠",
				secondValueC: "한_tabbed___빠",
				thirdTitle: "한_maps__빠"
			},
			swipeSpyglass: {
				firstTitle: "한_points of interest______빠",
				secondTitle: "한_style___빠",
				secondValueA: "한_swipe___빠",
				secondValueB: "한_spyglass___빠",
				thirdTitle: "한_maps__빠"
			}
		},
		progress: {
			checkingStories: "한_Checking your stories for issues____________빠...",
			stop: "한_Stop__빠",
			exit: "한_Exit__빠",
			dismiss: "한_Dismiss___빠",
			done: "한_Done___빠.",
			noStoriesWithIssuesLower: "한_No issues found______빠!",
			storiesErrorFree: "한_Looks like your stories are error-free____________빠",
			scanAllError: "한_Unable to scan -- we couldn't retrieve one or more of your stories_____________________빠",
			scanProgress: "한_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________빠",
			scanStopped: "한_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________빠",
			storiesWithIssues: "한_Stories with issues: {{NUM_STORIES}}____________빠"
		}
    })
);