define({
    root: ({
        "widgets": {
            "geoEnrichment": {
                "placeholder": {
                    "enterValue": "Mesafe gir",
                    "layerName": "Katman adını buraya gir"
                },
                "message": {
                    "analysisFailed": "Analiz yapılamadı.",
                    "errorOccurred": "Hata oluştu.",
                    "layerAdded": "Katman başarıyla eklendi. ",
                    "enrichLayerNameError": "\'Sonuç katmanı adı\' geçersiz karakterler içeremez " + "(<,>,#,%,:,\",?,&,+,/,\\).",
                    "creatingService": "Servis oluşturuluyor.. ",
                    "starting": "Başlangıç",
                    "performingAnalysis": "Analiz yapılıyor..",
                    "checkLayerName": "Katman adı kontrol ediliyor.. ",
                    "addingLayer": "Web haritasına katman ekleniyor ",
                    "layerNameExist": "Katman adı zaten var.",
                    "clickOnSave": " Uygulamayı yeniden yüklemek için \'Kaydet\' düğmesine tıklayın.",
                    "clickOnOk": " Yeniden denemek için \'Tamam\' düğmesine tıklayın.",
                    "enterNumbersOnly": "Girilen değerler geçerli değil",
                    "nofeatures": "Geçerli yayılımda detay yok",
                    "selectData": "Katmanı zenginleştirmek için veri seçin.",
                    "resetVariableMessage": "Değişkeni sıfırlamak istediğinizden emin misiniz?",
                    "emptyTextFieldLayerName": "Sonuç katmanı adı gir",
                    "createService":"Katman oluşturulmadı.",
                    "sharingLayer":"Katman paylaşılıyor..",
                    "updateItemFailed": "Güncelleme yapılamadı. Yeniden deneyin.",
                    "geoEnrichFailed": "Katman zenginleştirilemedi. Yeniden deneyin.",
                    "shareFailed": "Zenginleştirilen katman paylaşılamadı. Yeniden deneyin.",
                    "refreshServiceFailed": "Katman yenilenemedi. Yeniden deneyin.",
                    "layerJsonFailed": "Katman için JSON oluşturulamadı. Yeniden deneyin.",
                    "addToWebmapFailed": "Katman web haritasına eklenemedi. Yeniden deneyin.",
                    "bufferAreaHelpText": "Şundan daha küçük bir değer girin: ",
                    "invalidBufferInput": "Girilen değer geçerli değil.",
                    "emptyBufferInput": "Geçerli bir değer girin."
                },
                "populationText": "Nüfus",
                "housingText": "Hane",
                "businessText": "İş",
                "variableListText": " değişkenleri burada listelenir:",
                "countrySelectTitle": "1. Veri Konumunu Seç",
                "unitedStates": "Amerika Birleşik Devletleri",
                "global": "Global",
                "geoenrichDialogText": "Coğrafi Zenginleştirme Değişkenleri",
                "viewVariablestext": "Değişkenleri görüntüle",
                "backButtonText":"Geri",
                "customizeVariables": "Değişkenleri özelleştir",
                "resetVariables": "Sıfırla",
                "defineAreaTitle": "3. Zenginleştirilecek alanı tanımla",
                "currentMapExtent": "Geçerli harita yayılımını kullan",
                "enrichLayerName": "4. Sonuç katmanı adı",
                "lineDistanceText": "Çizgi Mesafesi",
                "drivingTime": "Sürüş Süresi",
                "enrichButtonText": "Katmanı Zenginleştir",
                "selectDataText": "2. Veri Seç",
                "showCreditsText": "Tanıtma yazısı göster",
                "variableCount": "Toplam değişken sayısı ",
                "totalRecords": "Toplam Kayıt:",
                "cost": "Maliyet:",
                "showCreditsDialogText": "Tanıtma Yazısı Göster",
                "nextButtonText": "Sonraki",
                "prevButtonText": "Önceki",
                "saveButtonText": "Kaydet",
                "ok": "Tamam"
            }
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
}); 