define({
    "root": ({
        "widgets": {
            "TemplateBuilder": {
                "enterBuilderButtonText": "Builder\'a Gir",
                "exitBuilderButtonText": "Builder\'dan Çık",
                "enterBuilderModeHelpText": "Uygulamayı yapılandırmak için Builder Mode\'a gir",
                "builderModeHelpText": "Builder Mode Şablonu",
                "webmapCaption": "Harita",
                "selectMapMessage": "Şu anda ${displaying} <b>${webmapTitle}</b><br/>Farklı bir web haritası seçmek için Harita seç öğesine tıklayın",
                "loadMapMessage": "Şu anda seçili olan <b>${webmapTitle}</b><br/>Bu web haritasını kullanmak için Kaydet\'e tıklayın",
                "changeWebmap": "Harita seç",
                "saveButtonText": "Kaydet",
                "webmapNextButtonText": "Sonraki ->",
                "previousButtonText":"Önceki",
                "layerLabelText": "Katman",
                "noLayerFoundText": "Katman Bulunamadı",
                "selectLayer": "Katman seç",
                "applicationSettingText": "Uygulama Ayarları",
                "summaryAttrAscendingOrderTooltip": "Artan",
                "onStartLabel": "ı_On Start_İ",
                "selectVariableText": "Değişken Seç",
                "selectVariableDropdown": "Değişken Seç",
                "label":"Etiket",
                "sourceLinkText":"Kaynak Bağlantı",
                "selectSubVariableText":"Alt Değişkenleri Seç",
                "subVariablePanelButtonText":"BİTTİ",
                "onButtonLabel":"Açık",
                "offButtonLabel":"Kapalı",
                "appSettingsSaveCloseButtonText": "KAYDET VE KAPAT",
                "appSettingsTitleText":"Uygulama Başlığı",
                "appSettingsDescriptionText": "Uygulama Açıklaması",
                "appSetingsRendererAreaText":"Canlandırılmış Alan",
                "shareText":"Paylaş",
                "basemapText":"Altlık Harita",
                "basemapSelectionText":"Altlık Haritası Seçimi",
                "secondaryBasemapText":"İkincil Altlık Haritası",
                "defaultBasemapText": "Varsayılan Altlık Haritası",
                "entireAreaButton": "ı_Entire Area_İ",
                "entireAreaOnStartButton": "ı_Entire Area on start_İ",
                "aboutPanel": "ı_About Panel_İ",
                "legendPanel": "ı_Legend Panel_İ",
                "layersPanel": "ı_Layers Panel_İ",
                "dataConfigurationButtonText": "Veri Yapılandırma",
                "savingChangesMessage": "Değişiklikler Kaydediliyor...",
                "nextButtonText": "Sonraki",
                "prevButtonText": "Önceki",
                "enterLabelText": "Etiket Gir",
                "layerHelpTextMessage": "Bu uygulama için sayısal alanları olan bir katman gereklidir",
                "alertMessage": {
                    "resetVariableMessage": "Değişkeni sıfırlamak istediğinizden emin misiniz?",
                    "emptyAppTitleMessage": "Uygulama başlığı boş olamaz",
                    "emptyDescriptionMessage": "Açıklama boş olamaz",
                    "maxVariableSelection": "25 alt değişkenden fazlasını seçemezsiniz",
                    "signInFail" : "Oturum Açılamadı",
                    "itemUpdateMessage": "Öğe Güncellendi",
                    "unsavedChangesMessage": "Kaydedilmemiş Değişiklikler",
                    "failMessage": "Öğe başarıyla güncellenemedi",
                    "saveChangesAlert": "Değişiklikleri kaydetmek istiyor musunuz?",
                    "variableLabelValidation": "Değişken etiketi BOŞ olamaz",
                    "subVariableLabelValidation": "Alt değişken etiketi BOŞ olamaz"
                    }
            }
        }
    })
});