define({
	header: {
		start: "Запуск",
		searchStories: "Поиск историй...",
		filter: "Фильтр",
		sort: "Сортировать",
		sortColon: "Сортировать:",
		numResults: "Результаты: {{NUM_RESULTS}}",
		sortBy: "Сортировать по",		
		dateModified: "Дата изменения",		
		title: "Название",
		type: "Тип",
		views: "Просмотров",
		errors: "Ошибки",
		filterBy: "Фильтр по",
		filterItems: "Фильтровать элементы",
		apps: "Приложения",
		sharing: "Общий доступ",
		clearAll: "Очистить все",
		clearSearch: "Очищает поиск",
		logOut: "Выход",
		mainQuote: "Карты-истории – самый эффективный способ воплотить свои идеи прямо сейчас.",
		quoteSource: "Роберт МакКи",
		checkYourStories: "Проверить истории",
		createStory: "Создать историю",
		totalStories: "Всего историй: {{NUM_STORIES}}",
		noIssues: "Всё хорошо",
		userStories: "Истории пользователя {{USER_NAME}}",
		headerDisabledTooltip: "Подождите, пока мы поколдуем...",
		notOnTouch: "Недоступно на сенсорных устройствах",		
	},
	deleteModal: {
		title: "Подтвердить удаление",
		warningText: "Вы уверены, что хотите удалить эту историю? Восстановить её будет невозможно.",
		deleteText: "Удалить",
		cancel: "Отменить" 
	},
	loading: {
		loadingText: "Загрузка историй..." 
	},
	cantFindStories: {
		whereAreStories: "Ваша история не видна?",
		notSeeExplanation: "В разделе Мои истории отображаются только карты-истории, созданные на ArcGIS Online с помощью приложений {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} и {{SWIPE_SPYGLASS}}. Более подробно см. {{FAQ}}.",
		faq: "Часто задаваемые вопросы",
		followingStoriesToUpdate: "Следующие истории, созданные в более ранних версиях наших приложений, надо обносить, чтобы они появились в Моих историях:",
		gettingStories: "Поиск историй, созданных в старых версиях наших приложений, которые надо обновить...",
		title: "Название",
		typeOfStoryMap: "Тип",
		lastModified: "Последние изменения",
		allUpToDate: "Не найдены истории, созданные в старых версиях наших приложений, которые надо обновить.",
		updateAll: "Обновить все",
		errorScanningForStories: "При поиске историй произошла ошибка.",
		close: "Закрыть",
		updates: "Обновления",
		updatingNumberOfNumber: "Обновление {{CURRENT_NUMBER}} из {{TOTAL}}",
		updatingNumberOfNumberAlt: "Обновление {{CURRENT_NUMBER}} / {{TOTAL}}",
		updateSucceeded: "Обновление выполнено успешно!",
		reloadingStories: "Повторная загрузка историй...",
		errorUpdatingStories: "При обновлении ваших историй произошла ошибка.",
		partialUpdateMessage: "Успешно обновлены истории: {{NUM_UPDATED}}" 
	},
	signIn: {
		signInTitle: "Вход в Story Maps",
		signInTo: "Войти с помощью своей учетной записи ArcGIS Online, чтобы:",
		explanationOne: "Создавать и компилировать свои карты-истории чтобы что-то рассказать.",
		explanationTwo: "Использовать собственные карты и данные из ArcGIS Online, чтобы рассказывать свои истории.",
		explanationThree: "Управлять своими картами-историями и проверять статус их содержимого.",
		dontHaveAccount: "Нет учётной записи ArcGIS Online? Зарегистрируйтесь, это:",
		publicAccount: "Бесплатная некоммерческая общедоступная учетная запись",
		orgAccount: "Бесплатная демо-подписка ArcGIS",
		timeExpired: "Срок действия вашего входа истёк. Войдите снова и продолжите с того места, где остановились.",
		apiDidntLoad: "Иногда оно может неверно загрузиться. Попробуйте обновить страницу.",
		needAccount: "Нужна учетная запись?",
		letsGo: "Приступим!" 
	},
	sharingLevel: {
		public: "Общедоступная",
		private: "Частная",
		organization: "Организация",
		changedSharing: "Изменен уровень доступа.",
		unableToChange: "Невозможно изменить уровень доступа.",
		partOfMap: "Этот элемент относится к карте. Чтобы изменить уровень доступа, надо изменить этот уровень для карты.",
		storyPublicContentOrg: "Карта-история общедоступная, поэтому нельзя открыть её ресурсы лишь для участников организации.",
		storyPublicContentPrivate: "Карта-история общедоступная, поэтому нельзя закрыть её ресурсы",
		mapOrg: "Открытие доступа для карты лишь в пределах организации испортит всю историю",
		layerOrg: "Открытие доступа для слоя лишь в пределах организации испортит всю историю",
		mapPrivate: "Закрытие доступа для карты испортит всю историю",
		layerPrivate: "Закрытие доступа для слоя испортит всю историю" 		
	},
	collectionList: [
		"Адвокаты и защита свидетелей",
		"Архитектура и дизайн",
		"Охрана природы и устойчивое развитие",
		"Культура",
		"Точки назначения и туризм",       
		"Чрезвычайные ситуации и восстановление",           
		"Экономика и развитие",
		"Развлечения",
		"История",
		"Инфраструктура",                  
		"Маркетинг",                        
		"Природа и окружающая среда",
		"Новости и события",
		"Океаны",                         
		"Парки и зоны отдыха",
		"Люди и общество",               
		"Планирование и анализ",
		"Публичное искусство",
		"Наука и технология",
		"Спорт",                           
		"Отчеты о путешествиях" 
	],
	types: {
		custom: "Настраиваемый",
		notSpecified: "Тип не указан" 
	},
	storyMap: {
		shared: "Опубликовано",		
		saveFailed: "Ошибка сохранения",
		numViews: "Видов: {{NUM_VIEWS}}",
		editStory: "Редактировать историю",
		viewLive: "Просмотр текущего",
		preview: "Просмотр",
		"delete": "Удаление",
		modified: "Изменено {{DATE}}",
		summary: "Итоговая информация",
		loading: "Загрузка...",		
		collapse: "свернуть",
		close: "закрыть",
		hide: "скрыть",
		notAvailableWhenBroken: "В истории обнаружены следующие проблемы",
		cantBeDeleted: "У истории включена защита от удаления, чтобы её отключить зайдите на страницу описания элемента на ArcGIS Online",
		shareDialog: {
		title: "Представьте свою историю всему миру!",
		notPublicWarning: "Доступ к истории предоставлен в пределах организации. Её видят только пользователи в пределах организации.",
		embedStory: "Включить вашу историю",
		shortLink: "Ссылка",
		hideHeaderBar: "Скрыть заголовок",
		copied: "Скопировано",
		small: "мелкий",
		medium: "средний",
		large: "крупный",
		custom: "пользовательское",
		widthAbbreviation: "w",
		heightAbbreviation: "h",
		emptyDimension: "Введите размер.",
		seeExample: "Предварительный просмотр включенного",
		removeHeader: "Скрыть заголовок приложения" 
		},		
		maps: {
		unableRetrieveTitle: "Невозможно получить карты",
		unableRetrieveDescription: "Мы не смогли получить карты для этой карты-истории." 
		},
		images: {
		unableRetrieveTitle: "Невозможно получить изображения.",
		unableRetrieveDescription: "Мы не смогли получить изображения для этой карты-истории." 
		},
		tags: {
		tags: "Теги",
		collectionTags: "Предмет",
		selectASubject: "Выбрать тему",
		save: "Сохранить",
		saved: "Сохранено",
		errorSaving: "Ошибка сохранения",
		tagTip: "Подсказка: по тегам вашу карту-историю можно найти в ArcGIS Online. Чем более релевантные теги, тем больше людей увидят вашу работу." 
		},
		submitToGallery: {
		gallerySubmission: "Галерея карт-историй",
		canSubmitIf: "Можете представить свою карту-историю для галереи, если там содержится следующее:",
		hasOwnImage: "Пользовательский образец",
		chosenSubject: "Тема и несколько тегов",
		chosenSubjectAlt: "{{SUBJECT}} и несколько тегов",
		storyMapTopicSubject: "Тема",
		sharedPublicly: "Она опубликована для всех",
		noBrokenContent: "Нет нарушенных ресурсов",
		nominateToGallery: "Представление в галерею",
		comingSoon: "Скоро!",
		submitted: "Отправлено",
		errorSubmitting: "Ошибка при отправке",
		ourGallery: "Галерея карт-историй",
		galleryTip: "{{THE_GALLERY}} представляет ряд лучших примеров карт-историй. Если выберут вашу историю, она будет добавлена через 10 дней после отправки. Мы не можем гарантировать добавление именно вашей истории по причине количества номинаций." 
		},
		placeholders: {
		noSummary: "Нет краткой информации. Щёлкните, чтобы добавить." 
		},
		errors: {
		cantDeleteStory: "Невозможно удалить историю.",
		unableToFind: "Не удалось найти содержание",
		unableToRetrieve: "Мы не смогли получить ресурсы для этой карты-истории." 		
		},
		socialSharing: {
		availableWhenPublic: "Эта опция станет доступной после открытия общего доступа к вашей истории" 
		},
		dialog: {
		back: "Назад",
		close: "Закрыть",
		cancel: "Отменить" 
		},
		imagePicker: {
		changeDefault: "Изменить изображение по умолчанию",
		changeImage: "Изменить образец",
		uploadImage: "Загрузить образец",
		chooseImage: "Выбрать образец",
		chooseAnImage: "Выбрать изображение",
		notInIEVersion: "Эта функция недоступна в Internet Explorer {{VERSION_NUMBER}}.",
		or: "Или",
		uploadAnImage: "Загрузите изображение",
		supportedFileTypes: "Поддерживаются .png, .jpg, .gif",
		imageSizeMessage: "Изображение должно быть хотя бы 286 пикселов в ширину и 190 в высоту.",
		minimumDimensions: "Минимум: 286 x 190px",
		imagesLoading: "Загрузка изображений...",
		noImages: "В этой истории нет изображений",
		errorLoading: "Не удалось получить изображения в этой истории",
		clickBelowTip: "Нажмите кнопку ниже, чтобы загрузить изображение.",
		dragAndDrop: "Перетаскивание",
		cropImage: "Обрезать изображение",
		saveImage: "Сохранить изображение",
		save: "Сохранить",		
		savingImage: "Сохранение изображения...",
		saved: "Сохранено!",
		errorSaving: "Не удается сохранить изображение.",
		skipAndCrop: "Пропустить и обрезать",
		wrongFormat: "Этот тип файлов не поддерживается.",		
		noCropWarning: "Изображение невозможно обрезать, но вы можете сохранить его как образец для вашей истории, используя исходные размеры ({{WIDTH_PIXELS}} х {{HEIGHT_PIXELS}}пкс)." 
		}
	},
	content: {
		media: {
		maps: "Карты",
		images: "Изображения",
		videos: "Видеоролики",
		webpages: "Веб-страницы",
		tags: "Теги",
		gallery: "Галерея" 
		},
		headers: {		
		status: "Состояние",
		source: "Источник",
		name: "Имя",
		shared: "Опубликовано" 
		},		
		component: {
		mapTour: "Номер точки",
		bullet: "Маркер",
		tab: "Закладка",
		accordion: "Секция",		
		mapJournal: "Секция" 
		},
		titleType: {
		mapTour: "Подпись",
		mapJournal: "URL",
		mapSeries: "URL" 
		},		
		actions: {
		viewMap: "Просмотр карты",
		editMap: "Редактировать карту",
		viewLayer: "Просмотреть слой" 		
		},
		contentType: {
		mainStage: "действие главной площадки",
		sidePanel: "боковая панель ресурсов" 
		},
		notification: {
		refreshExplanation: "Еще раз проверьте вашу историю",
		checking: "Проверка...",
		foundSomeIssues: "Мы нашли ряд проблем",
		noIssuesFound: "Проблем не найдено",
		storyPublic: "Теперь ваша история общедоступна",
		storyOrg: "Теперь ваша история доступна для организации",
		storyPrivate: "Теперь ваша история частная",
		mapPublic: "Теперь ваша карта общедоступна",
		mapOrg: "Теперь ваша карта доступна для организации",
		mapPrivate: "Теперь ваша карта частная",
		layerPublic: "Теперь ваш слой общедоступен",
		layerOrg: "Теперь ваш слой доступен для организации",
		layerPrivate: "Теперь ваш слой частный",
		contentPublic: "Теперь ваш ресурс общедоступен",
		contentOrg: "Теперь ваш ресурс доступен для организации",
		contentPrivate: "Теперь ваш ресурс частный",
		storyAndContentPublic: "Теперь ваша история и её ресурсы общедоступны",
		storyAndContentOrg: "Теперь ваша история и её ресурсы доступны для организации",
		storyAndContentPrivate: "Теперь ваша история и её ресурсы частные",
		shareBulkPrompt: "Хотите предоставить соответствующий уровень доступа к истории и её ресурсам?",
		yes: "Да",
		no: "Нет",
		premiumPublicSuccess: "Ваши премиум-ресурсы теперь общедоступны",
		subscriptionPublicSuccess: "Ресурсы вашей подписки теперь общедоступны" 
		},
		errors: {
		publicDisabled: "Общий доступ был отключен Администратором",
		noMapName: "Не удалось извлечь имя карты",
		notPublic: "НЕ ОБЩЕДОСТУПНО",
		inaccessible: "НЕДОСТУПНО",
		deleted: "УДАЛЕНО",
		cantAccessVideo: "Нет доступа к видео",
		noStoriesFound: "Нет ни одной карты-истории в ваших ресурсах.",
		cantShowStories: "Невозможно показать ваши карты-истории. Попробуйте позднее.",
		consolationSearch: "Мы не смогли найти никаких карт-историй.",
		notCompatibleWithBrowser : "Мои истории на поддерживаются в Internet Explorer до версии {{VERSION_NUMBER}}.",
		pleaseUpdateBrowser: "Пожалуйста, обновите ваш браузер.",
		searchTip: "Попробуйте и немного упростите.",
		consolationNoStories: "Добро пожаловать в Мои истории!",
		noStoriesTip: "Чтобы построить свою первую карту-историю, перейдите на страницу Приложения.",
		letsGo: "Приступим",		
		cantChangeSharingLevel: "Не удалось изменить уровень доступа",
		cantChangeSharingLevels: "Не удалось изменить уровни доступа",
		errorUpdatingTitle: "Ошибка при обновлении заголовка",
		errorUpdatingSummary: "Ошибка при обновлении краткой информации",
		noEmptyTitle: "Заголовок не может быть пустым",
		cantUpdatePremiumContent: "Невозможно обновить премиум-ресурсы",
		cantUpdateSubscriptionContent: "Невозможно обновить ресурсы подписки",
		createFirstStory: "Создать мою первую историю" 
		},
		tooltipErrors: {
		mapHasBeenDeleted: "Карта была удалена",
		layerHasBeenDeleted: "Слой был удален",
		mapIsInaccessible: "Карта недоступна",
		layerIsInaccessible: "Слой недоступен",		
		mapNotYoursNotAccessible: "Карта принадлежит кому-то другому и недоступна",
		layerNotYoursNotAccessible: "Слой {{LAYER_NAME}} принадлежит кому-то другому и недоступен",
		layerServiceOkItemNot: "Слой {{LAYER_NAME}} добавлен как удаленный или недоступный элемент",
		mapOthersSharedBelowLevel: "Карта вам не принадлежит, и к ней нет общего доступа",
		layerOthersSharedBelowLevel: "Слой {{LAYER_NAME}} вам не принадлежит, и к нему нет общего доступа",
		noMapNoDetails: "Без информации о карте мы ничего не можем вам сказать о слоях",
		mapIsPrivate: "Карта частная",
		mapIsOrg: "Доступ к карте открыт только в пределах организации",
		layerIsPrivate: "Слой {{LAYER_NAME}} частный",
		layerIsOrg: "Доступ к слою {{LAYER_NAME}} открыт только в пределах организации",
		imageInaccessible: "Это изображение недоступно",
		videoInaccessible: "Это видео недоступно",
		webpageInaccessible: "Эта веб-страница недоступна",
		layerSecureService: "Слой {{LAYER_NAME}} – защищённый-сервис",
		mapSecureService: "Карта – защищённый-сервис",
		layerConsumesCredits: "Слой {{LAYER_NAME}} – премиум-ресурс, потребляющий кредиты",
		layerSubscriptionContent: "Слой {{LAYER_NAME}} – ресурс подписки",
		mapConsumesCredits: "Карта – премиум-ресурс, потребляющий кредиты",
		mapSubscriptionContent: "Карта – ресурс подписки" 
		},
		tooltipWarnings: {
		cantScanThisTypeAlt: "У вас нет возможности выбрать этот тип слоя.",
		cantScanThisType: "Слой {{LAYER_NAME}} не соответствует типу, который вы можете выбрать",
		webpageNotScanned: "Веб-страницы не проверены на наличие проблем" 
		},
		scanningErrors: {
		deletedMap: "Ресурс удален",
		inaccessibleMap: "Недоступный ресурс карты",
		notYoursNotAccessible: "Ресурс вам не принадлежит и к нему нет общего доступа",
		serviceOkItemNot: "Рабочие слои включают недоступные элементы",
		someContentNotPublic: "К ресурсу нет общего доступа",
		someContentPrivate: "Частный ресурс",
		othersSharedBelowLevel: "Ресурс вам не принадлежит, и к нему нет общего доступа",
		premiumContent: "Премиум-ресурсы",
		subscriptionContent: "Ресурс подписки",
		secureService: "Защищенные сервисы",
		inaccessibleImage: "Недоступные изображения",
		inaccessibleVideo: "Недоступные видео",
		inaccessibleWebpage: "Недоступные веб-страницы" 			
		},
		scanningErrorTips: {
		deletedMapTip: "Подсказка: откройте веб-карту и удалите неисправные ресурсы, либо удалите веб-карту из истории.",
		inaccessibleMapTip: "Подсказка: откройте веб-карту и удалите неисправные ресурсы, либо удалите веб-карту из истории.",
		notYoursNotAccessibleTip: "Подсказка: откройте веб-карту и удалите слой или карту из истории",
		serviceOkItemNotTip: "Слои добавлены как недоступные или удаленные элементы. Слои являются рабочими, но это может повлиять на карту (всплывающие окна, символы).",
		ignore: "Игнорировать",
		fix: "Зафиксировать",
		clickToShareOrg: "Щёлкните кнопку, чтобы открыть доступ к ресурсам для организации, либо вручную измените все элементы, щёлкая кнопки публикации.",
		clickToSharePublic: "Щёлкните кнопку, чтобы открыть общий доступ к ресурсам, либо вручную измените все элементы, щёлкая кнопки публикации",
		shareOrg: "Опубликовать для организации",
		sharePublicly: "Общий доступ",
		othersSharedBelowLevelTip: "Подсказка: часть ресурсов истории принадлежит пользователю {{USER_NAME}}, и при просмотре вашей карты-истории не все смогут их увидеть.",		
		secureServiceTip: "Подсказка: удалите защищённый сервис из своей истории либо следуйте процедуре, которая описана {{HERE}}.",
		blogArticle: "здесь",
		premiumContentTip: "Ваша история содержит премиум-ресурсы, которые будут потреблять {{CREDITS}}, если сделать её общедоступной. Сделайте историю общедоступной и продолжайте, или удалите эти слои из истории.",
		premiumContentPublicTip: "Ваша история содержит премиум-ресурсы, которые будут потреблять {{CREDITS}}, если сделать общедоступной. Уточните, надо ли делать эти слои общедоступными, или удалите их из истории.",
		subscriptionContentTip: "Ваша история содержит ресурсы подписки, которые по умолчанию не общедоступны. Уточните, надо ли делать эти слои общедоступными (кредиты потребляться не будут), или удалите их из истории.",		
		agolCredits: "Кредиты ArcGIS Online",
		credits: "кредиты",
		makePublic: "Сделать общедоступным",
		confirm: "Подтвердить",
		inaccessibleImageTip: "Подсказка: предоставьте недостающее изображение или удалите ссылку на него.",
		inaccessibleVideoTip: "Подсказка: предоставьте недостающее видео или удалите ссылку на него.",
		inaccessibleWebpageTip: "Подсказка: предоставьте недостающую веб-страницу или удалите ссылку на неё." 
		},
		removeLayer: {
		title: "Исправление ошибки слоя",
		layersWithIssue: "Слои с ошибкой: {{NUM_WITH_ISSUE}}",
		issueExplanation: "Слой {{LAYER_NAME}} добавлен как удаленный или недоступный элемент. Слой является рабочим, но это может повлиять на карту (всплывающие окна, символы). Мы не можем сказать, был ли важен для вашей истории этот элемент.",
		issueSolution: "Чтобы исправить эту ошибку вы можете редактировать вашу карту, удалить слой, затем еще раз добавить слой к карте, используя следующий URL:",
		editMap: "Редактировать вашу карту",
		clickBelowWhenDone: "Когда закончите редактирование, щелкните кнопку ниже:",
		rescanAndClose: "Еще раз просмотреть и закрыть" 
		},		
		info: {
		ownedBy: "Этот элемент принадлежит пользователю {{USER_NAME}}",
		unknownUser: "кому-то другому",
		untitledSection: "(Раздел без названия)",
		introRecord: "Введение" 
		},		
		layers: {
		layersHeader: "Слои",
		noLayers: "(Нет слоев)",
		basemapParens: "(базовая карта)" 
		},
		images: {
		thumbnails: "Образцы",
		thumbnail: "Образец",
		thumbnailParens: "(образец)" 
		},
		general: {
		noTitle: "(нет заголовка)",
		loading: "Загрузка..." 
		}		
	},
	infographics: {
		mapJournal: {
		firstTitle: "разделы",
		secondTitle: "стиль",
		secondValueA: "боковая панель",
		secondValueB: "открепленная панель",
		thirdTitle: "карты" 
		},
		mapTour: {
		firstTitle: "точки тура",
		secondTitle: "стиль",
		secondValueA: "встроено",
		secondValueB: "трехпанельная",
		thirdTitle: "базовая карта",
		thirdValueLoading: "Загрузка...",
		thirdValueUnknown: "неизвестное" 
		},
		mapSeries: {		
		firstTitleA: "маркеры",
		firstTitleB: "разделы",
		firstTitleC: "закладки",
		secondTitle: "стиль",
		secondValueA: "маркированный",
		secondValueB: "гармошкой",
		secondValueC: "с закладками",
		thirdTitle: "карты" 
		},
		swipeSpyglass: {
		firstTitle: "точки интереса",
		secondTitle: "стиль",
		secondValueA: "swipe",
		secondValueB: "spyglass",
		thirdTitle: "карты" 
		}
	},
	progress: {
		checkingStories: "Проверка ваших историй на ошибки...",
		stop: "Остановить",
		exit: "Выйти",
		dismiss: "Отклонить",
		done: "Готово.",
		noStoriesWithIssuesLower: "Ошибок не найдено!",
		storiesErrorFree: "Похоже, с вашими историями всё в порядке",
		scanAllError: "Невозможно сканировать -- мы не можем получить одну или несколько историй",
		scanProgress: "{{NUM_SCANNED}} из {{NUM_TOTAL}}",
		scanStopped: "Сканировано историй: {{NUM_SCANNED}}, из них с ошибками: {{ISSUE_STORIES}}",
		storiesWithIssues: "Историй с ошибками: {{NUM_STORIES}}" 
	}	
});
