define(
	 ({
		header: {
			start: "начало",
			searchStories: "Поиск историй...",
			filter: "Фильтр",
			sort: "Сортировать",
			sortColon: "Сортировать:",
			numResults: "Результаты: {{NUM_RESULTS}}",
			sortBy: "Сортировать по",
			dateModified: "Дата изменения",
			title: "Заголовок",
			type: "Тип",
			views: "Просмотров",
			errors: "Ошибки",
			filterBy: "Фильтр по",
			filterItems: "Фильтровать элементы",
			apps: "Приложения",
			sharing: "Общий доступ",
			clearAll: "Очистить все",
			clearSearch: "Очищает поиск",
			logOut: "Выход",
			mainQuote: "Карты-истории – самый эффективный способ воплотить свои идеи прямо сейчас.",
			quoteSource: "Роберт МакКи",
			checkYourStories: "Проверить истории",
			createStory: "Создать историю",
			totalStories: "Всего историй: {{NUM_STORIES}}",
			noIssues: "Всё в порядке",
			userStories: "Истории пользователя {{USER_NAME}}",
			headerDisabledTooltip: "Подождите пока мы выполним некоторые манипуляции...",
			notOnTouch: "Недоступно на устройствах с тачскрином",
		},
		deleteModal: {
			title: "Подтвердить удаление",
			warningText: "Вы уверены, что вы хотите удалить эту историю? Это действие нельзя отменить.",
			deleteText: "Удалить",
			cancel: "Отмена"
		},
		loading: {
			loadingText: "Загрузка историй..."
		},
		cantFindStories: {
			whereAreStories: "Ваша история не видна?",
			notSeeExplanation: "В разделе Мои истории отображаются только карты-истории, созданные на ArcGIS с помощью приложений {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} или {{SWIPE_SPYGLASS}}. Для получения более подробной информации смотри {{FAQ}}.",
			faq: "Часто задаваемые вопросы",
			followingStoriesToUpdate: "Следующие истории, созданные в более ранних версиях наших приложений, следует обновить, чтобы они появились в Моих историях:",
			gettingStories: "Поиск историй, созданных в старых версиях приложений, которые следует обновить...",
			title: "Заголовок",
			typeOfStoryMap: "Тип",
			lastModified: "Последние изменения",
			allUpToDate: "Не найдено историй, созданных в старых версиях приложений, которые следует обновить.",
			updateAll: "Обновить все",
			errorScanningForStories: "При поиске историй произошла ошибка.",
			close: "Закрыть",
			updates: "Обновления",
			updatingNumberOfNumber: "Обновление {{CURRENT_NUMBER}} из {{TOTAL}}",
			updatingNumberOfNumberAlt: "Обновление {{CURRENT_NUMBER}} / {{TOTAL}}",
			updateSucceeded: "Обновление выполнено успешно!",
			reloadingStories: "Повторная загрузка историй...",
			errorUpdatingStories: "При обновлении ваших историй произошла ошибка.",
			partialUpdateMessage: "Успешно обновлено историй: {{NUM_UPDATED}}"
		},
		signIn: {
			signInTitle: "Вход в Story Maps",
			signInTo: "Войти с помощью своей учетной записи ArcGIS Online, чтобы:",
			explanationOne: "Создавать свои захватывающие карты-истории.",
			explanationTwo: "Использовать собственные карты и данные из ArcGIS Online, чтобы рассказывать свои истории.",
			explanationThree: "Управлять своими картами-историями и проверять статус их содержимого.",
			dontHaveAccount: "Нет учетной записи ArcGIS Online? Зарегистрируйтесь, чтобы получить:",
			publicAccount: "Бесплатная некоммерческая общедоступная учетная запись",
			orgAccount: "Бесплатная демонстрационная подписка ArcGIS",
			timeExpired: "Срок действия сеанса истек. Войдите снова и продолжите с того места, где остановились.",
			apiDidntLoad: "Загрузка произошла некорректно. Попробуйте обновить страницу.",
			needAccount: "Нужна учетная запись?",
			letsGo: "Приступим!"
		},
		sharingLevel: {
			publicMessage: "Общий",
			privateMessage: "Частный",
			organization: "Организация",
			changedSharing: "Изменен уровень доступа.",
			unableToChange: "Невозможно изменить уровень доступа.",
			partOfMap: "Этот элемент используется в карте. Чтобы изменить уровень доступа, надо изменить этот уровень для карты.",
			storyPublicContentOrg: "Карта-история общедоступная, поэтому нельзя открыть её ресурсы лишь для участников организации.",
			storyPublicContentPrivate: "Карта-история общедоступная, поэтому ее элементы не могут быть частными.",
			mapOrg: "Открытие доступа для карты лишь в пределах организации испортит всю историю",
			layerOrg: "Открытие доступа для слоя лишь в пределах организации испортит всю историю",
			mapPrivate: "Закрытие доступа для карты испортит всю историю",
			layerPrivate: "Закрытие доступа для слоя испортит всю историю"
		},
		collectionList: {
			advocacy: "Адвокаты и защита свидетелей",
			architecture: "Архитектура и дизайн",
			conservation: "Охрана природы и устойчивое развитие",
			culture: "Культура",
			destinations: "Достопримечательности и туризм",
			disasters: "Чрезвычайные ситуации и спасение",
			economy: "Экономика и развитие",
			entertainment: "Развлечения",
			history: "История",
			infrastructure: "Инфраструктура",
			marketing: "Маркетинг",
			nature: "Природа и окружающая среда",
			news: "Новости и события",
			oceans: "Океаны",
			parks: "Парки и зоны отдыха",
			people: "Люди и общество",
			planning: "Планирование и анализ",
			publicArt: "Искусство",
			science: "Наука и технология",
			sport: "Спорт",
			travelogues: "Отчеты о путешествиях"
		},
		types: {
			custom: "Пользовательские",
			notSpecified: "Тип не указан"
		},
		storyMap: {
			shared: "Общедоступные",
			saveFailed: "Ошибка сохранения",
			numViews: "Просмотров: {{NUM_VIEWS}}",
			editStory: "Редактировать историю",
			viewLive: "Просмотр истории",
			preview: "Предварительный просмотр",
			deleteButton: "Удалить",
			modified: "Изменено {{DATE}}",
			summary: "Краткая информация",
			loading: "Загрузка...",
			collapse: "свернуть",
			close: "закрыть",
			hide: "скрыть",
			notAvailableWhenBroken: "В истории обнаружены следующие проблемы",
			cantBeDeleted: "У истории включена защита от удаления. Чтобы её отключить, зайдите на страницу описания элемента в ArcGIS.",
			shareDialog: {
				title: "Представьте свою историю всему миру!",
				notPublicWarning: "Эта история доступна для организации. Только ее участники смогут ее просмотреть.",
				embedStory: "Встроить вашу историю",
				shortLink: "Ссылка",
				hideHeaderBar: "Скрыть заголовок",
				copied: "Скопировано",
				small: "мелкий",
				medium: "средний",
				large: "большой",
				custom: "пользовательский",
				widthAbbreviation: "ш",
				heightAbbreviation: "в",
				emptyDimension: "Введите размер.",
				seeExample: "Предварительный просмотр встраиваемого элемента",
				removeHeader: "Скрыть заголовок приложения"
			},
			maps: {
				unableRetrieveTitle: "Невозможно получить карты",
				unableRetrieveDescription: "Мы не смогли получить карты для этой карты-истории."
			},
			images: {
				unableRetrieveTitle: "Невозможно получить изображения.",
				unableRetrieveDescription: "Мы не смогли получить изображения для этой карты-истории."
			},
			tags: {
				tags: "Теги",
				collectionTags: "Тема",
				selectASubject: "Выбрать тему",
				save: "Сохранить",
				saved: "Сохранено",
				errorSaving: "Ошибка сохранения",
				tagTip: "Подсказка: теги нужны для того, чтобы можно было найти вашу историю. Чем более релевантные теги, тем больше людей увидят вашу работу."
			},
			submitToGallery: {
				gallerySubmission: "Галерея карт-историй",
				canSubmitIf: "Можете представить свою карту-историю для галереи, если там содержится следующее:",
				hasOwnImage: "Пользовательский образец",
				chosenSubject: "Тема и несколько тегов",
				chosenSubjectAlt: "{{SUBJECT}} и несколько тегов",
				storyMapTopicSubject: "subject",
				sharedPublicly: "Она опубликована для всех",
				noBrokenContent: "Ошибок нет",
				nominateToGallery: "Отправить в Галерею",
				comingSoon: "Скоро!",
				submitted: "Отправлено",
				errorSubmitting: "Ошибка при отправке",
				ourGallery: "Галерея карт-историй",
				galleryTip: "{{THE_GALLERY}} - это специально отобранные лучшие примеры карт-историй. Если вашу историю выберут, у вас будет 10 дней на подтверждение. В связи с количеством номинаций нет гарантий, что ваша история обязательно будет добавлена."
			},
			placeholders: {
				noSummary: "Нет краткой информации, щёлкните чтобы добавить."
			},
			errors: {
				cantDeleteStory: "Невозможно удалить историю.",
				unableToFind: "Не удалось найти ресурсы",
				unableToRetrieve: "Мы не смогли получить ресурсы для этой карты-истории."
			},
			socialSharing: {
				availableWhenPublic: "Эта опция станет доступной после открытия общего доступа к вашей истории"
			},
			dialog: {
				back: "Назад",
				close: "Закрыть",
				cancel: "Отмена"
			},
			imagePicker: {
				changeDefault: "Изменить изображение по умолчанию",
				changeImage: "Изменить значок",
				uploadImage: "Загрузить образец",
				chooseImage: "Выбрать образец",
				chooseAnImage: "Выбрать изображение",
				notInIEVersion: "Эта функция недоступна в Internet Explorer {{VERSION_NUMBER}}.",
				or: "Или",
				uploadAnImage: "Загрузите изображение",
				supportedFileTypes: "Поддерживаются .png, .jpg, .gif",
				imageSizeMessage: "Изображение должно быть хотя бы 286 пикселов в ширину и 190 в высоту.",
				minimumDimensions: "Минимум: 286 x 190px",
				imagesLoading: "Загрузка изображений...",
				noImages: "В этой истории нет изображений",
				errorLoading: "Не удалось получить изображения в этой истории",
				clickBelowTip: "Нажмите кнопку ниже чтобы загрузить изображение.",
				dragAndDrop: "Перетаскивание",
				cropImage: "Обрезать изображение",
				saveImage: "Сохранить изображение",
				save: "Сохранить",
				savingImage: "Сохранение изображения...",
				saved: "Сохранено!",
				errorSaving: "Не удается сохранить изображение.",
				skipAndCrop: "Пропустить и обрезать",
				wrongFormat: "Этот тип файлов не поддерживается.",
				noCropWarning: "Изображение невозможно обрезать, но вы можете сохранить его как образец для вашей истории, используя исходные размеры ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}} пкс)."
			}
		},
		content: {
			media: {
				maps: "Карты",
				images: "Изображения",
				videos: "Видеоролики",
				webpages: "Веб-страницы",
				tags: "Теги",
				gallery: "Галерея"
			},
			headers: {
				status: "Состояние",
				source: "Источник",
				name: "Имя",
				shared: "Общие"
			},
			component: {
				mapTour: "Номер точки",
				bullet: "Маркер",
				tab: "Закладка",
				accordion: "Секция",
				mapJournal: "Секция"
			},
			titleType: {
				mapTour: "Заголовок",
				mapJournal: "URL-адрес",
				mapSeries: "URL-адрес"
			},
			actions: {
				viewMap: "Просмотреть карту",
				editMap: "Редактировать карту",
				fix: "Зафиксировать",
				viewLayer: "Просмотреть слой"
			},
			contentType: {
				mainStage: "действие главной площадки",
				sidePanel: "описание"
			},
			notification: {
				refreshExplanation: "Еще раз проверьте вашу историю",
				checking: "Проверка...",
				foundSomeIssues: "Мы нашли ряд проблем",
				noIssuesFound: "Проблем не найдено",
				storyPublic: "Теперь ваша история общедоступна",
				storyOrg: "Теперь ваша история доступна для организации",
				storyPrivate: "Теперь ваша история доступна только вам",
				mapPublic: "Теперь ваша карта общедоступна",
				mapOrg: "Теперь ваша карта доступна для организации",
				mapPrivate: "Теперь ваша карта доступна только вам",
				layerPublic: "Теперь ваш слой общедоступен",
				layerOrg: "Теперь ваш слой доступен для организации",
				layerPrivate: "Теперь ваш слой доступен только вам",
				contentPublic: "Теперь ваш ресурс общедоступен",
				contentOrg: "Теперь ваш ресурс доступен для организации",
				contentPrivate: "Теперь ваш ресурс доступен только вам",
				storyAndContentPublic: "Теперь ваша история и её ресурсы общедоступны",
				storyAndContentOrg: "Теперь ваша история и её ресурсы доступны для организации",
				storyAndContentPrivate: "Теперь ваша история и её ресурсы доступны только вам",
				shareBulkPrompt: "Хотите предоставить соответствующий уровень доступа к истории и её ресурсам?",
				layersPublic: "Некоторые слои являются общедоступными.",
				layersOrg: "Некоторые слои доступны для организации.",
				layersPrivate: "Некоторые слои доступны только вам",
				mapsPublic: "Некоторые карты являются общедоступными.",
				mapsOrg: "Некоторые карты доступны для организации.",
				mapsPrivate: "Некоторые карты доступны только вам",
				layersAndMapsPublic: "Некоторые карты и слои являются общедоступными.",
				layersAndMapsOrg: "Некоторые карты и слои доступны для организации.",
				layersAndMapsPrivate: "Некоторые карты и слои доступны только вам",
				yes: "Да",
				no: "Нет",
				premiumPublicSuccess: "Ваши премиум-ресурсы теперь общедоступны",
				subscriptionPublicSuccess: "Ресурсы вашей подписки теперь общедоступны"
			},
			errors: {
				publicDisabled: "Общий доступ был отключен Администратором",
				orgDisabled: "Общий доступ в пределах организации был отключен Администратором",
				noMapName: "Не удалось получить имя карты",
				notPublic: "НЕ ОБЩЕДОСТУПНО",
				inaccessible: "НЕДОСТУПНО",
				deleted: "УДАЛЕНО",
				cantAccessVideo: "Нет доступа к видео",
				noStoriesFound: "Нет ни одной карты-истории в ваших ресурсах.",
				cantShowStories: "Не удалось показать ваши карты-истории. Повторите попытку позже.",
				consolationSearch: "Мы не смогли найти никаких карт-историй.",
				notCompatibleWithBrowser : "Мои истории на поддерживаются в Internet Explorer до версии {{VERSION_NUMBER}}.",
				pleaseUpdateBrowser: "Пожалуйста, обновите ваш браузер.",
				searchTip: "Попробуйте и немного упростите.",
				consolationNoStories: "Добро пожаловать в Мои истории!",
				noStoriesTip: "Чтобы построить свою первую карту-историю, перейдите на страницу Приложения.",
				letsGo: "Приступим",
				cantChangeSharingLevel: "Не удалось изменить уровень доступа",
				cantChangeSharingLevels: "Не удалось изменить уровни доступа",
				errorUpdatingTitle: "Ошибка при обновлении заголовка",
				errorUpdatingSummary: "Ошибка при обновлении краткой информации",
				noEmptyTitle: "Заголовок не может быть пустым",
				cantUpdatePremiumContent: "Невозможно обновить премиум-ресурсы",
				cantUpdateSubscriptionContent: "Невозможно обновить ресурсы подписки",
				createFirstStory: "Создать мою первую историю"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "Карта была удалена",
				layerHasBeenDeleted: "Слой был удален",
				mapIsInaccessible: "Карта недоступна",
				layerIsInaccessible: "Слой недоступен",
				mapNotYoursNotAccessible: "Карта принадлежит кому-то другому и недоступна",
				layerServiceOkItemNot: "Слой добавлен как удаленный или недоступный элемент",
				layerNotYoursNotAccessible: "Слой принадлежит кому-то другому и недоступен",
				mapOthersSharedBelowLevel: "Карта вам не принадлежит и к ней нет общего доступа",
				layerOthersSharedBelowLevel: "Слой вам не принадлежит и к нему нет общего доступа",
				noMapNoDetails: "Без информации о карте мы ничего не можем вам сказать про слои",
				mapIsPrivate: "Карта частная",
				mapIsOrg: "Доступ к карте открыт только в пределах организации",
				layerIsPrivate: "Слой частный",
				layerIsOrg: "Доступ к слою открыт только в пределах организации",
				imageInaccessible: "Это изображение недоступно",
				videoInaccessible: "Это видео недоступно",
				webpageInaccessible: "Эта веб-страница недоступна",
				layerSecureService: "Слой – защищённый-сервис",
				mapSecureService: "Карта – защищённый-сервис",
				layerConsumesCredits: "Слой – премиум-ресурс, потребляющий кредиты",
				layerSubscriptionContent: "Слой – ресурс, доступный только для подписки",
				mapConsumesCredits: "Карта – премиум-ресурс, потребляющий кредиты",
				mapSubscriptionContent: "Карта – ресурс, доступный только для подписки"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "У вас нет возможности выбрать этот тип слоя.",
				cantScanThisType: "Слой не соответствует типу, который вы можете выбрать",
				webpageNotScanned: "Веб-страницы не проверены на проблемы",
				ignoredIssue: "Вы проигнорировали ошибку данного слоя. Обновите страницу и ещё раз проверьте эту историю на наличие ошибки",
				ignoredIssueBuilder: "Вы проигнорировали ошибку данного слоя. Обновите конструктор и ещё раз проверьте на наличие ошибки"
			},
			scanningErrors: {
				deletedMap: "Ресурс удален",
				inaccessibleMap: "Недоступный ресурс карты",
				notYoursNotAccessible: "Ресурс вам не принадлежит и к нему нет общего доступа",
				serviceOkItemNot: "Рабочие слои включают недоступные элементы",
				someContentNotPublic: "К ресурсу нет общего доступа",
				someContentPrivate: "Частный ресурс",
				othersSharedBelowLevel: "Ресурс вам не принадлежит и к нему нет общего доступа",
				premiumContent: "Премиум-ресурсы",
				subscriptionContent: "Ресурс, доступный только в рамках подписки",
				secureService: "Защищенные сервисы",
				inaccessibleImage: "Недоступные изображения",
				inaccessibleVideo: "Недоступные видео",
				inaccessibleWebpage: "Недоступные веб-страницы"
			},
			scanningErrorTips: {
				deletedMapTip: "Подсказка: отредактируйте веб-карту и удалите неисправные ресурсы, либо удалите веб-карту из истории.",
				inaccessibleMapTip: "Подсказка: отредактируйте веб-карту и удалите неисправные ресурсы, либо удалите веб-карту из истории.",
				notYoursNotAccessibleTip: "Подсказка: отредактируйте веб-карту и удалите слой, либо удалите веб-карту из истории.",
				serviceOkItemNotTip: "Слои были добавлены как элементы, которые недоступны или удалены. Слои будут работать, но это может повлиять на внешний вид карты (всплывающие окна, символы).",
				ignore: "Игнорировать",
				fix: "Исправить",
				clickToShareOrg: "Щёлкните кнопку, чтобы открыть доступ к ресурсам для организации, либо вручную измените все элементы, щёлкая кнопки общего доступа.",
				clickToSharePublic: "Щёлкните кнопку, чтобы открыть общий доступ к ресурсам, либо вручную измените все элементы, щёлкая кнопки общего доступа.",
				shareOrg: "Опубликовать для организации",
				sharePublicly: "Общий доступ",
				othersSharedBelowLevelTip: "Подсказка: часть ресурсов истории принадлежит пользователю {{USER_NAME}}, и при просмотре вашей карты-истории не все смогут их увидеть.",
				secureServiceTip: "Подсказка: удалите защищённый сервис из своей истории либо следуйте процедуре, которая описана {{HERE}}.",
				blogArticle: "здесь",
				premiumContentTip: "В карте-истории содержатся премиум-ресурсы, которые потребляют {{CREDITS}} при публичном доступе. Сделайте историю общедоступной и продолжайте или удалите эти слои из истории.",
				premiumContentPublicTip: "В карте-истории содержатся премиум-ресурсы, которые потребляют {{CREDITS}} при публичном доступе. Подтвердите, что вы открываете для них общий доступ или удалите эти слои из истории.",
				subscriptionContentTip: "В карте-истории содержатся ресурсы подписки, которые по умолчанию недоступны публично. Подтвердите, что хотите сделать их доступными (кредиты списываться не будут) или удалите эти слои из истории.",
				credits: "кредиты",
				makePublic: "Сделать общедоступным",
				confirm: "Подтвердить",
				inaccessibleImageTip: "Подсказка: предоставьте недостающее изображение или удалите ссылку на него.",
				inaccessibleVideoTip: "Подсказка: предоставьте недостающее видео или удалите ссылку на него.",
				inaccessibleWebpageTip: "Подсказка: предоставьте недостающую веб-страницу или удалите ссылку на неё."
			},
			removeLayer: {
				title: "Исправление ошибки слоя",
				layersWithIssue: "Слои с ошибкой: {{NUM_WITH_ISSUE}}",
				issueExplanation: "Слой {{NUM_WITH_ISSUE}} был добавлен как элемент, который недоступен или удален. Слои будут работать, но это может повлиять на внешний вид карты (всплывающие окна, символы). Этот элемент может быть важным для всей истории.",
				issueSolution: "Чтобы исправить эту ошибку вы можете редактировать вашу карту, удалить слой, затем еще раз добавить слой к карте, используя следующий URL:",
				editMap: "Редактировать вашу карту",
				clickBelowWhenDone: "Когда закончите редактирование, щелкните кнопку ниже:",
				rescanAndClose: "Еще раз просмотреть и закрыть"
			},
			info: {
				ownedBy: "Этот элемент принадлежит пользователю {{USER_NAME}}",
				unknownUser: "кому-то другому",
				untitledSection: "(Раздел без названия)",
				introRecord: "Введение"
			},
			layers: {
				layersHeader: "Слои",
				noLayers: "(Нет слоев)",
				basemapParens: "(базовая карта)"
			},
			images: {
				thumbnails: "Образцы",
				thumbnail: "Образец",
				thumbnailParens: "(образец)"
			},
			general: {
				noTitle: "(нет заголовка)",
				loading: "Загрузка..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "разделы",
				secondTitle: "стиль",
				secondValueA: "боковая панель",
				secondValueB: "плавающая панель",
				thirdTitle: "карты"
			},
			mapTour: {
				firstTitle: "точки тура",
				secondTitle: "стиль",
				secondValueA: "встроено",
				secondValueB: "трехпанельная",
				thirdTitle: "базовая карта",
				thirdValueLoading: "Загрузка...",
				thirdValueUnknown: "неизвестный"
			},
			mapSeries: {
				firstTitleA: "bullets",
				firstTitleB: "sections",
				firstTitleC: "tabs",
				secondTitle: "стиль",
				secondValueA: "bulleted",
				secondValueB: "side accordion",
				secondValueC: "tabbed",
				thirdTitle: "карты"
			},
			swipeSpyglass: {
				firstTitle: "точки интереса",
				secondTitle: "стиль",
				secondValueA: "swipe",
				secondValueB: "spyglass",
				thirdTitle: "карты"
			},
			crowdsource: {
				firstTitle: "вклад",
				secondTitle: "стиль",
				secondValueA: "боковая панель",
				secondValueB: "перенос",
				thirdTitle: "базовая карта",
				thirdValueLoading: "Загрузка...",
				thirdValueUnknown: "неизвестный"
			}
		},
		progress: {
			checkingStories: "Проверка ваших историй на ошибки...",
			stop: "Стоп",
			exit: "Выйти",
			dismiss: "Отклонить",
			done: "Готово.",
			noStoriesWithIssuesLower: "Ошибок не найдено!",
			storiesErrorFree: "Похоже, с вашими историями всё в порядке",
			scanAllError: "Невозможно сканировать -- мы не можем получить одну или несколько историй",
			scanProgress: "{{NUM_SCANNED}} из {{NUM_TOTAL}}",
			scanStopped: "Сканировано историй: {{NUM_SCANNED}}, из них с ошибками: {{ISSUE_STORIES}}",
			storiesWithIssues: "Историй с ошибками: {{NUM_STORIES}}"
		},
		newStories: {
			newStoriesFound: "Похоже, вы только что создали новую историю.",
			includeStories: "Обновить истории",
			notWhileScanning: "Эта опция станет доступной после завершения проверки"
		}
    })
);
