define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "ł_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ą",
            selectFieldsText:"ł_Select Form Fields_ą",
            selectThemeText: "Wybierz motyw formularza",
            fieldLabelPlaceHolder: "Oznacz etykietą to pole",
            fieldDescPlaceHolder: "Stwórz opis tego pola",
            webmapText: "ł_1. Webmap_ą",
            layerText: "ł_2. Layer_ą",
            detailsText: "ł_3. Details_ą",
            fieldsText: "ł_4. Fields_ą",
            styleText: "ł_5. Style_ą",
            previewText: "ł_6. Preview_ą",
            publishText: "ł_7. Publish_ą",
            titleText: "Kreator formularzy GeoForm",
            descriptionText: "ł_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._ą",
            btnPreviousText: "Wstecz",
            btnNextText:"Dalej",
            webmapTabTitleText: "Wybierz mapę internetową",
            btnSelectWebmapText:"Zaznacz mapę internetową",
            layerTabTitleText: "Wybierz warstwę edytowalną",
            selectLayerLabelText:"Warstwa",
            selectLayerDefaultOptionText:"Wybierz warstwę",
            detailsTabTitleText:"Szczegóły formularza",
            detailTitleLabelText: "Tytuł",
            detailLogoLabelText: "Obraz logo",
            detailDescriptionLabelText: "Opis",
            fieldTabFieldHeaderText: "Pole",
            fieldTabLabelHeaderText: "Etykieta",
            fieldTabTypeHeaderText: "Typ",
            fieldTabDescriptionHeaderText: "Opis",
            previewApplicationText: "Podgląd aplikacji",
            saveApplicationText: "Zapisz aplikację",
            saveText: "Zapisz",
            toggleNavigationText: "ł_Toggle navigation_ą",
            formPlaceholderText: "ł_My Form_ą",
            imageLogoPlaceholderText: "ł_http://www.mysite.com/myimage.png_ą",
            shareBuilderInProgressTitleMessage: "ł_Publishing GeoForm_ą",
            shareBuilderProgressBarMessage:"ł_Please Wait..._ą",
            shareBuilderTitleMessage: "ł_Your GeoForm has been updated & published!_ą",
            shareBuilderTextMessage: "ł_You can start collecting information by sharing with others_ą",
            shareDialogFormText: "ł_Form Link_ą",
            geoformTitleText: "ł_Geo Form_ą",
            layerTabText: "ł_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ą",
            detailsTabText:"ł_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._ą",
            fieldsTabText:"ł_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ą",
            styleTabText: "ł_Style your GeoForm using the themes below based on your preference._ą",
            publishTabText: "ł_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ą"
        }
    })
);