define({
  root: ({
    layer: "ł_Layer___ą",
    sort: "ł_Sort by___ą",
    order: "ł_Order___ą",
    desc: "ł_Desc__ą",
    asc: "ł_Asc__ą",
    loading: "ł_loading&hellip;______ą",
    search: "ł_Search___ą",
    searchPlaceholder: "ł_Find reports_____ą",
    noResults: "ł_No results____ą",
    ascending: "ł_Ascending____ą",
    descending: "ł_Descending____ą"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});