define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Det valgte webkartet inneholder ingen gyldige lag å bruke. Legg til et redigerbart geoobjektslag i webkartet for å fortsette.",
            selectFieldsText:"Velg fra felter",
            selectThemeText: "Velg tema for skjema",
            fieldLabelPlaceHolder: "Merk dette feltet",
            fieldDescPlaceHolder: "Beskriv dette feltet",
            webmapText: "1. Webkart",
            layerText: "2. Lag",
            detailsText: "3. Detaljer",
            fieldsText: "4. Felter",
            styleText: "5. Stil",
            previewText: "6. Forhåndsvisning",
            publishText: "7. Publiser",
            titleText: "GeoForm Builder",
            descriptionText: "GeoForm er en konfigurerbar mal for skjemabasert dataredigering av en  <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>geoobjektstjeneste</a>. Dette programmet lar brukerne angi data via et skjema i stedet for et karts oppsprettvindu og samtidig utnytte kraften i <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>webkartet</a> og redigerbare geoobjektstjenester. Bruk denne byggeren til å tilpasse og legge ut GeoForm ved å følge trinnene til venstre.",
            btnPreviousText: "Forrige",
            btnNextText:"Neste",
            webmapTabTitleText: "Velg et webkart",
            btnSelectWebmapText:"Velg webkart",
            layerTabTitleText: "Velg redigerbart lag",
            selectLayerLabelText:"Lag",
            selectLayerDefaultOptionText:"Velg lag",
            detailsTabTitleText:"Skjemadetaljer",
            detailTitleLabelText: "Tittel",
            detailLogoLabelText: "Logobilde",
            detailDescriptionLabelText: "Beskrivelse",
            fieldTabFieldHeaderText: "Felt",
            fieldTabLabelHeaderText: "Etikett",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Beskrivelse",
            previewApplicationText: "Forhåndsvis applikasjon",
            saveApplicationText: "Lagre applikasjon",
            saveText: "Lagre",
            toggleNavigationText: "Veksle navigasjon",
            formPlaceholderText: "Mitt skjema",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "Publisere GeoForm",
            shareBuilderProgressBarMessage:"Vent litt...",
            shareBuilderTitleMessage: "Ditt GeoForm er oppdatert og publisert.",
            shareBuilderTextMessage: "Du kan begynne å samle informasjon ved å dele med andre",
            shareDialogFormText: "Skjemakobling",
            geoformTitleText: "GeoForm",
            layerTabText: "Dette er laget som GeoForm blir bygd fra. Laget må være en geoobjektstjeneste som er aktivert for redigering, med deletillatelser som egner seg for publikummet ditt.",
            detailsTabText:"Bruk boksene Skjemadetaljer nedenfor til å tilpasse tittelen, legge til en egen logo og gi en kort beskrivelse for GeoForm-publikummet ditt.",
            fieldsTabText:"Her kan du velge hvilke felter som skal være synlige for GeoForm-publikummet ditt, redigere merkene de får se og legge til en kort beskrivelse for hjelpe til med datainnskrivingen.",
            styleTabText: "Utform GeoForm med temaene nedenfor etter egne preferanser.",
            publishTabText: "Hvis du er ferdig med å tiilpasse GeoForm, lagrer du applikasjonen og begynner delingen med publikum. Du kan alltids gå tilbake til denne byggeren og fortsette tilpasningene på bakgrunn av tilbakemeldinger."
        }
    })
);