define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "å_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ø",
            selectFieldsText:"å_Select Form Fields_ø",
            selectThemeText: "Velg tema for skjema",
            fieldLabelPlaceHolder: "Merk dette feltet",
            fieldDescPlaceHolder: "Beskriv dette feltet",
            webmapText: "å_1. Webmap_ø",
            layerText: "å_2. Layer_ø",
            detailsText: "å_3. Details_ø",
            fieldsText: "å_4. Fields_ø",
            styleText: "å_5. Style_ø",
            previewText: "å_6. Preview_ø",
            publishText: "å_7. Publish_ø",
            titleText: "GeoForm Builder",
            descriptionText: "å_GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left._ø",
            btnPreviousText: "Forrige",
            btnNextText:"Neste",
            webmapTabTitleText: "Velg et webkart",
            btnSelectWebmapText:"Velg webkart",
            layerTabTitleText: "Velg redigerbart lag",
            selectLayerLabelText:"Lag",
            selectLayerDefaultOptionText:"Velg lag",
            detailsTabTitleText:"Skjemadetaljer",
            detailTitleLabelText: "Tittel",
            detailLogoLabelText: "Logobilde",
            detailDescriptionLabelText: "Beskrivelse",
            fieldTabFieldHeaderText: "Felt",
            fieldTabLabelHeaderText: "Etikett",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Beskrivelse",
            previewApplicationText: "Forhåndsvis applikasjon",
            saveApplicationText: "Lagre applikasjon",
            saveText: "Lagre",
            toggleNavigationText: "å_Toggle navigation_ø",
            formPlaceholderText: "å_My Form_ø",
            imageLogoPlaceholderText: "å_http://www.mysite.com/myimage.png_ø",
            shareBuilderInProgressTitleMessage: "å_Publishing GeoForm_ø",
            shareBuilderProgressBarMessage:"å_Please Wait..._ø",
            shareBuilderTitleMessage: "å_Your GeoForm has been updated & published!_ø",
            shareBuilderTextMessage: "å_You can start collecting information by sharing with others_ø",
            shareDialogFormText: "å_Form Link_ø",
            geoformTitleText: "å_Geo Form_ø",
            layerTabText: "å_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ø",
            detailsTabText:"å_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience._ø",
            fieldsTabText:"å_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ø",
            styleTabText: "å_Style your GeoForm using the themes below based on your preference._ø",
            publishTabText: "å_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ø"
        }
    })
);