define(
     ({
        map: {
            error: "Kan ikke opprette kart"
        },
        onlineStatus: {
            offline: "Du jobber nå frakoblet. Svar på skjemaene blir lagret lokalt til det kan opprettes en forbindelse til serveren.",
            reconnecting: "Kobler til på nytt&hellip;",
            pending: "${total} ventende redigering(er) blir sendt inn når nettverkstilkoblingen gjenopprettes."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Min organisasjon",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innhold",
                    favoritesLabel: "Mine favoritter"
                },
                title: "Velg webkart",
                searchTitle: "Søk",
                ok: "Ok",
                cancel: "Avbryt",
                placeholder: "Angi søkeord"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Min organisasjon",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innhold",
                    favoritesLabel: "Mine favoritter"
                },
                title: "Velg gruppe",
                searchTitle: "Søk",
                ok: "Ok",
                cancel: "Avbryt",
                placeholder: "Angi søkeord"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "å_Here is a link to a GeoForm_ø"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Northing",
            utm_easting: "Easting",
            utm_zone_number: "Sonenummer",
            geoFormGeneralTabText: "1. Skriv inn informasjon",
            locationInformationText: "2. Velg lokasjon",
            submitInformationText: "3. Fyll ut skjemaet",
            submitInstructions: "Legg til denne informasjonen i kartet.",
            myLocationText: "Gjeldende lokasjon",
            locationDescriptionForMoreThanOneOption: "å_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ø.",
            locationDescriptionForOneOption: "å_Specify the location for this entry by clicking/tapping the map or by using the following option_ø.",
            locationDescriptionForNoOption: "å_Specify the location for this entry by clicking/tapping the map_ø.",
            addressText: "Søk",
            geographic: "Bredde/lengde",
            locationTabText: "Lokasjon",
            locationPopupTitle: "Lokasjon",
            submitButtonText: "Send inn oppføring",
            submitButtonTextLoading: "Sender inn&hellip;",
            formValidationMessageAlertText: "Følgende felter må fylles ut:",
            selectLocation: "å_Please select a location for your submission_ø.",
            emptylatitudeAlertMessage: "Angi et ${openLink}breddegrad${closeLink}skoordinat.",
            emptylongitudeAlertMessage: "Angi et ${openLink}lengdegrad${closeLink}skoordinat.",
            shareUserTitleMessage: "Takk for bidraget!",
            entrySubmitted: "Oppføringen er sendt til kartet.",
            shareThisForm: "Del dette skjemaet",
            shareUserTextMessage: "Be andre om å bidra ved hjelp av følgende alternativer.",
            addAttachmentFailedMessage: "Kan ikke legge til vedlegg i laget",
            addFeatureFailedMessage: "Kan ikke legge til geoobjekt i laget",
            noLayerConfiguredMessage: "å_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ø.",
            placeholderLatitude: "Breddegrad (Y)",
            placeholderLongitude: "Lengdegrad (X)",
            latitude: "Breddegrad",
            longitude: "Lengdegrad",
            findMyLocation: "Finn meg",
            finding: "Lokaliserer&hellip;",
            backToTop: "Tilbake til toppen",
            addressSearchText: "Innsendelsen vil vises her. Du kan dra nålen for å korrigere lokasjonen.",
            shareModalFormText: "Skjemakobling",
            close: "Lukk",
            locationNotFound: "Finner ikke lokasjonen.",
            setLocation: "Angi lokasjon",
            find: "Finn adresse eller sted",
            attachment: "Vedlegg",
            toggleDropdown: "Aktiver/deaktiver rullegardinliste",
            invalidString: "å_Please enter valid value_ø.",
            invalidSmallNumber: "å_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ø.",
            invalidNumber: "å_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ø.",
            invalidFloat: "å_Please enter valid ${openStrong}floating point${closeStrong} value_ø.",
            invalidDouble: "å_Please enter valid ${openStrong}double${closeStrong} value_ø.",
            invalidLatLong: "å_Please enter valid latitude and longitude coordinates_ø.",
            invalidUTM: "å_Please enter valid UTM coordinates_ø.",
            invalidUSNG: "å_Please enter valid USNG coordinates_ø.",
            invalidMGRS: "å_Please enter valid MGRS coordinates_ø.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Velg&hellip;",
            applyEditsFailedMessage: "Beklager, vi kunne ikke sende inn. Prøv på nytt.",
            requiredFields: "Det finnes noen feil. Korriger feilene nedenfor.",
            requiredField: "(obligatorisk)",
            error: "Feil",
            textRangeHintMessage: "${openStrong}Hint:${closeStrong} Minimumsverdi ${minValue} og maksimumsverdi ${maxValue}",
            dateRangeHintMessage: "${openStrong}Hint:${closeStrong} Laveste dato ${minValue} og høyeste dato ${maxValue}",
            remainingCharactersHintMessage: "å_${value} characters remaining_ø"
        },
        builder: {
            invalidUser: "Beklager, du har ikke tillatelse til å se dette elementet",
            invalidWebmapSelectionAlert: "Det valgte webkartet inneholder ingen gyldige webkart du kan bruke. Legg till et redigerbart geoobjektslag i webkartet for å fortsette.",
            invalidWebmapSelectionAlert2: "Se ${openLink}Hva er en geoobjektstjeneste?${closeLink} hvis du vil ha mer informasjon.",
            selectFieldsText: "Velg fra felter",
            selectThemeText: "Velg tema for skjema",
            webmapText: "Webkart",
            layerText: "Lag",
            detailsText: "Detaljer",
            fieldsText: "Felter",
            styleText: "Stil",
            optionText: "Alternativer",
            previewText: "Forhåndsvisning",
            publishText: "Mangfoldiggjør",
            optionsApplicationText: "Alternativer",
            titleText: "Byggeverktøy",
            descriptionText: "å_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ø.",
            btnPreviousText: "Forrige",
            btnNextText: "Neste",
            webmapTabTitleText: "Velg et webkart",
            viewWebmap: "Se webkart",
            webmapDetailsText: "å_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ø",
            btnSelectWebmapText: "Velg webkart",
            btnSelectWebmapTextLoading: "Laster inn&hellip;",
            layerTabTitleText: "Velg redigerbart lag",
            selectLayerLabelText: "Lag",
            selectLayerDefaultOptionText: "Velg lag",
            detailsTabTitleText: "Skjemadetaljer",
            detailTitleLabelText: "Tittel",
            detailLogoLabelText: "Logobilde",
            descriptionLabelText: "å_Form Instructions & Details_ø",
            fieldDescriptionLabelText: "å_Help Text (optional)_ø",
            fieldTabFieldHeaderText: "Felt",
            fieldTabLabelHeaderText: "Etikett",
            fieldTabDisplayTypeHeaderText: "Vis som",
            fieldTabOrderColumnText: "å_Order_ø",
            fieldTabVisibleColumnText: "å_Enabled_ø",
            selectMenuOption: "Velg meny",
            selectRadioOption: "Alternativknapp",
            selectTextOption: "Tekst",
            selectDateOption: "å_Date Picker_ø",
            selectRangeOption: "å_Touch-Spinner_ø",
            selectCheckboxOption: "Avmerkingsboks",
            selectMailOption: "E-post",
            selectUrlOption: "URL",
            selectTextAreaOption: "å_Text Area_ø",
            previewApplicationText: "Forhåndsvis applikasjon",
            saveApplicationText: "Lagre applikasjon",
            saveText: "Lagre",
            toggleNavigationText: "Veksle navigasjon",
            formPlaceholderText: "Mitt skjema",
            shareBuilderInProgressTitleMessage: "Publisere GeoForm",
            shareBuilderProgressBarMessage: "Vent litt&hellip;",
            shareBuilderTitleMessage: "Elementet er lagret",
            shareBuilderTextMessage: "Du kan begynne å samle informasjon ved å dele med andre",
            shareModalFormText: "Skjemakobling",
            shareBuilderSuccess: "Ditt GeoForm er oppdatert og publisert.",
            geoformTitleText: "GeoForm",
            layerTabText: "Dette er laget som GeoForm blir bygd fra. Laget må være en geoobjektstjeneste som er aktivert for redigering, med deletillatelser som egner seg for publikummet ditt.",
            detailsTabText: "Bruk Skjemadetaljer-boksene nedenfor for å tilpasse tittelen, legge til en egen logo og gi en kort beskrivelse for GeoForm-publikumet ditt. I beskrivelsen kan du legge til koblinger til andre ressurser, kontaktopplysninger, og til og med sende publikumet ditt til et webkartprogram med alle dataene som er samlet inn med GeoForm.",
            fieldsTabText: "Her kan du velge hvilke felter som skal være synlige for GeoForm-publikummet ditt, redigere merkene de får se og legge til en kort beskrivelse for hjelpe til med datainnskrivingen.",
            styleTabText: "Utform GeoForm med temaene nedenfor etter egne preferanser.",
            publishTabText: "Hvis du er ferdig med å tilpasse GeoForm, lagrer du programmet og begynner delingen med publikum. Du kan alltid gå tilbake til dette byggeverktøyet og gjøre flere tilpasninger basert på tilbakemeldinger.",
            headerSizeLabel:"å_Header Size_ø",
            smallHeader: "Bruk liten overskrift",
            bigHeader: "å_Use Large Header_ø",
            pushpinText: "Kartnål",
            doneButtonText: "å_Save and Exit_ø",
            fieldTabPlaceHolderHeaderText: "Hint (valgfritt)",
            enableAttachmentLabelText: "å_${openStrong}Enable Attachments${closeStrong}_ø",
            enableAttachmentLabelHint: "å_You can enable/disable the attachments here_ø",
            attachmentIsRequiredLabelText: "å_${openStrong}Attachment Required${closeStrong}_ø",
            attachmentIsRequiredLabelHint: "å_If necessary, users can be required to enter an attachment_ø.",
            attachmentLabelText: "å_Attachment Button Label_ø",
            attachmentLabelHint: "å_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ø",
            attachmentDescription: "Beskrivelse av vedlegg",
            attachmentHint: "Du kan om nødvendig angi flere instruksjoner for vedlegg her.",
            jumbotronDescription: "å_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ø",
            shareGeoformText: "Del Geoform",
            shareDescription: "Delingspanelet gjør det enkelt for publikumet ditt å dele GeoForm med andre samarbeidsparter så snart de har sendt inn noe. Dette kan deaktiveres når som helst.",
            defaultMapExtent: "Standard kartutstrekning",
            defaultMapExtentDescription: "Kartet tilbakestilles til standardutstrekningen i webkartet etter innsending. Dette kan deaktiveres når som helst.",
            pushpinOptionsDescription: "Velg blant en lang rekke farger for kartnålen. Fargen bør være annerledes enn fargen på symbolene på kartet, slik at det blir enklere for brukerne å sette innsendingene på kartet.",
            selectLocationText: "Velg lokasjon etter",
            myLocationText: "Min lokasjon",
            searchText: "Søk",
            coordinatesText: "Breddegrads- og lengdegradskoordinater",
            usng: "USNG-koordinater",
            mgrs: "MGRS-koordinater",
            utm: "UTM-koordinater",
            selectLocationSDescription: "La brukere velge en lokasjon ved hjelp av disse metodene.",
            dragTooltipText:"å_Drag the field where you want it to appear_ø",
            showHideLayerText:"å_Show/Hide Layer_ø",
            showHideLayerHelpText:"å_You can configure the GeoForm to Show/Hide Layer_ø"
        }
    })
);