define(
	 ({
		header: {
			start: "ł_start___ą",
			searchStories: "ł_Search your stories________ą...",
			filter: "ł_Filter___ą",
			sort: "ł_Sort__ą",
			sortColon: "ł_Sort___ą:",
			numResults: "ł_Results: {{NUM_RESULTS}}________ą",
			sortBy: "ł_Sort by___ą",
			dateModified: "ł_Date modified_____ą",
			title: "ł_Title___ą",
			type: "ł_Type__ą",
			views: "ł_Views___ą",
			errors: "ł_Errors___ą",
			filterBy: "ł_Filter by____ą",
			filterItems: "ł_Filter Items_____ą",
			apps: "ł_Apps__ą",
			sharing: "ł_Sharing___ą",
			clearAll: "ł_Clear all____ą",
			clearSearch: "ł_Clears the search______ą",
			logOut: "ł_Log Out___ą",
			mainQuote: "ł_Storytelling is the most powerful way to put ideas into the world today_______________________ą.",
			quoteSource: "ł_Robert McKee_____ą",
			checkYourStories: "ł_Check Stories_____ą",
			createStory: "ł_Create Story_____ą",
			totalStories: "ł_Total stories: {{NUM_STORIES}}__________ą",
			noIssues: "ł_All good___ą",
			userStories: "ł_Stories of {{USER_NAME}}________ą",
			headerDisabledTooltip: "ł_Please wait while we work some magic_____________ą...",
			notOnTouch: "ł_Not available on touch devices__________ą",
		},
		deleteModal: {
			title: "ł_Confirm Delete_____ą",
			warningText: "ł_Are you sure you want to delete thisÂ story? You will not be able to recover it_________________________ą.",
			deleteText: "ł_Delete___ą",
			cancel: "ł_Cancel___ą"
		},
		loading: {
			loadingText: "ł_Loading your stories________ą..."
		},
		cantFindStories: {
			whereAreStories: "ł_Not seeing your story________ą?",
			notSeeExplanation: "ł_My Stories will only list story maps hosted in ArcGIS Online created with the {{STORY_MAP_TOUR}}, {{JOURNAL}}, {{MAP_SERIES}} and {{SWIPE_SPYGLASS}} applications. See our {{FAQ}} for more information_____________________________________________________________ą.",
			faq: "ł_FAQ__ą",
			followingStoriesToUpdate: "ł_The following stories created with early versions of our applications need to be updated for them to be listed in My Stories_______________________________________ą:",
			gettingStories: "ł_Searching for stories created with early versions of our applications that need to be updated______________________________ą...",
			title: "ł_Title___ą",
			typeOfStoryMap: "ł_Type__ą",
			lastModified: "ł_Last modified_____ą",
			allUpToDate: "ł_No stories created with early versions of our applications need to be updated________________________ą.",
			updateAll: "ł_Update All____ą",
			errorScanningForStories: "ł_There was an error searching your stories______________ą.",
			close: "ł_Close___ą",
			updates: "ł_Updates___ą",
			updatingNumberOfNumber: "ł_Updating {{CURRENT_NUMBER}} of {{TOTAL}}_____________ą",
			updatingNumberOfNumberAlt: "ł_Updating {{CURRENT_NUMBER}} / {{TOTAL}}_____________ą",
			updateSucceeded: "ł_Update succeeded______ą!",
			reloadingStories: "ł_Reloading your stories_________ą...",
			errorUpdatingStories: "ł_There was an error updating your stories_____________ą.",
			partialUpdateMessage: "ł_Stories updated successfully: {{NUM_UPDATED}}_______________ą"
		},
		signIn: {
			signInTitle: "ł_Sign in to Story Maps_______ą",
			signInTo: "ł_Sign in with your existing ArcGIS Online account to_________________ą:",
			explanationOne: "ł_Create compelling story maps to tell your stories________________ą.",
			explanationTwo: "ł_Use your maps and data from ArcGIS Online in your story maps___________________ą.",
			explanationThree: "ł_Manage your story maps and check the status of their content___________________ą.",
			dontHaveAccount: "ł_Don't have an ArcGIS Online account? Sign up for a________________ą:",
			publicAccount: "ł_Free non-commercial public account___________ą",
			orgAccount: "ł_Free trial ArcGIS subscription__________ą",
			timeExpired: "ł_Your sign-in expired. Sign in again to pick up where you left off_____________________ą.",
			apiDidntLoad: "ł_Something isn't loading correctly. Try refreshing the page___________________ą.",
			needAccount: "ł_Need an account______ą?",
			letsGo: "ł_Let's go____ą!"
		},
		sharingLevel: {
			publicMessage: "ł_Public___ą",
			privateMessage: "ł_Private___ą",
			organization: "ł_Organization_____ą",
			changedSharing: "ł_Changed sharing level________ą.",
			unableToChange: "ł_Unable to change sharing_________ą.",
			partOfMap: "ł_This item resides in a map. To change its sharing level, you must change the sharing level of the map________________________________ą.",
			storyPublicContentOrg: "ł_Your story is public, so its content can't be shared only with your organization_________________________ą",
			storyPublicContentPrivate: "ł_Your story is public, so its content can't be private_________________ą",
			mapOrg: "ł_Sharing your map to your organization would break your story___________________ą",
			layerOrg: "ł_Sharing your layer to your organization would break your story____________________ą",
			mapPrivate: "ł_Making your map private would break your story_______________ą",
			layerPrivate: "ł_Making your layer private would break your story_______________ą"
		},
		collectionList: {
			advocacy: "ł_Advocacy and Outreach_______ą",
			architecture: "ł_Architecture and Design________ą",
			conservation: "ł_Conservation and Sustainability__________ą",
			culture: "ł_Culture___ą",
			destinations: "ł_Destinations and Tourism________ą",
			disasters: "ł_Disasters and Recovery________ą",
			economy: "ł_Economy and Development________ą",
			entertainment: "ł_Entertainment_____ą",
			history: "ł_History___ą",
			infrastructure: "ł_Infrastructure_____ą",
			marketing: "ł_Marketing____ą",
			nature: "ł_Nature and Environment________ą",
			news: "ł_News and Events______ą",
			oceans: "ł_Oceans___ą",
			parks: "ł_Parks and Recreation_______ą",
			people: "ł_People and Society______ą",
			planning: "ł_Planning and Analysis_______ą",
			publicArt: "ł_Public Art____ą",
			science: "ł_Science and Technology________ą",
			sport: "ł_Sport___ą",
			travelogues: "ł_Travelogues____ą"
		},
		types: {
			custom: "ł_Custom___ą",
			notSpecified: "ł_Type not specified______ą"
		},
		storyMap: {
			shared: "ł_Shared___ą",
			saveFailed: "ł_Error saving_____ą",
			numViews: "ł_Views: {{NUM_VIEWS}}_______ą",
			editStory: "ł_Edit Story____ą",
			viewLive: "ł_View Live____ą",
			preview: "ł_Preview___ą",
			deleteButton: "ł_Delete___ą",
			modified: "ł_Modified {{DATE}}______ą",
			summary: "ł_Summary___ą",
			loading: "ł_Loading____ą...",
			collapse: "ł_collapse___ą",
			close: "ł_close___ą",
			hide: "ł_hide__ą",
			notAvailableWhenBroken: "ł_Your story has issues below_________ą",
			cantBeDeleted: "ł_This story has delete protection enabled, see its item page on ArcGIS Online to disable___________________________ą",
			shareDialog: {
				title: "ł_Share your story with the world___________ą!",
				notPublicWarning: "ł_Your story is shared with your organization. Only members of your organization will be able to view it________________________________ą.",
				embedStory: "ł_Embed your story______ą",
				shortLink: "ł_Shortlink____ą",
				hideHeaderBar: "ł_Hide header bar______ą",
				copied: "ł_Copied___ą",
				small: "ł_small___ą",
				medium: "ł_medium___ą",
				large: "ł_large___ą",
				custom: "ł_custom___ą",
				widthAbbreviation: "ł_w_ą",
				heightAbbreviation: "ł_h_ą",
				emptyDimension: "ł_Enter a dimension______ą.",
				seeExample: "ł_Preview your embed______ą",
				removeHeader: "ł_Hide application header________ą"
			},
			maps: {
				unableRetrieveTitle: "ł_Unable to retrieve maps________ą",
				unableRetrieveDescription: "ł_We weren't able to retrieve maps for this story map_________________ą."
			},
			images: {
				unableRetrieveTitle: "ł_Unable to retrieve images_________ą",
				unableRetrieveDescription: "ł_We weren't able to retrieve images for this story map_________________ą."
			},
			tags: {
				tags: "ł_Tags__ą",
				collectionTags: "ł_Subject___ą",
				selectASubject: "ł_Select a subject______ą",
				save: "ł_Save__ą",
				saved: "ł_Saved___ą",
				errorSaving: "ł_Error saving_____ą",
				tagTip: "ł_Tip: Tags help people find your story on ArcGIS Online. The more relevant the tags are, the higher the visibility your work will receive__________________________________________ą."
			},
			submitToGallery: {
				gallerySubmission: "ł_Story Maps Gallery______ą",
				canSubmitIf: "ł_You can nominate your story to the gallery if it contains the following_______________________ą:",
				hasOwnImage: "ł_Custom thumbnail______ą",
				chosenSubject: "ł_A subject and some tags________ą",
				chosenSubjectAlt: "ł_A {{SUBJECT}} and some tags_________ą",
				storyMapTopicSubject: "ł_subject___ą",
				sharedPublicly: "ł_Shared publicly______ą",
				noBrokenContent: "ł_No broken content______ą",
				nominateToGallery: "ł_Nominate to Gallery_______ą",
				comingSoon: "ł_Coming soon_____ą!",
				submitted: "ł_Submitted____ą",
				errorSubmitting: "ł_Error submitting______ą",
				ourGallery: "ł_The Story Maps gallery________ą",
				galleryTip: "ł_{{THE_GALLERY}} is a curated set of Story Maps that showcases some of the best examples. If your story is selected, it will be added within 10 days of your submission. Due to the quantity of nominations, we cannot promise that your story will be added_____________________________________________________________________________ą."
			},
			placeholders: {
				noSummary: "ł_No summary, click to add one__________ą."
			},
			errors: {
				cantDeleteStory: "ł_Unable to delete story________ą.",
				unableToFind: "ł_Unable to find content________ą",
				unableToRetrieve: "ł_We weren't able to retrieve the content for this story map___________________ą."
			},
			socialSharing: {
				availableWhenPublic: "ł_This option will be available when your story is public__________________ą"
			},
			dialog: {
				back: "ł_Back__ą",
				close: "ł_Close___ą",
				cancel: "ł_Cancel___ą"
			},
			imagePicker: {
				changeDefault: "ł_Change the default image________ą",
				changeImage: "ł_Change thumbnail______ą",
				uploadImage: "ł_Upload thumbnail______ą",
				chooseImage: "ł_Choose thumbnail______ą",
				chooseAnImage: "ł_Choose an Image______ą",
				notInIEVersion: "ł_This feature is not available in Internet Explorer {{VERSION_NUMBER}}______________________ą.",
				or: "ł_Or__ą",
				uploadAnImage: "ł_Upload an Image______ą",
				supportedFileTypes: "ł_Supports .png, .jpg, .gif_________ą",
				imageSizeMessage: "ł_Your image needs to be at least 286 px wide by 190 px tall___________________ą.",
				minimumDimensions: "ł_Minimum: 286 x 190px_______ą",
				imagesLoading: "ł_Loading images______ą...",
				noImages: "ł_This story has no images________ą",
				errorLoading: "ł_Unable to retrieve the images in this story______________ą",
				clickBelowTip: "ł_Click the button below to upload an image______________ą.",
				dragAndDrop: "ł_Drag and Drop_____ą",
				cropImage: "ł_Crop Image____ą",
				saveImage: "ł_Save Image____ą",
				save: "ł_Save__ą",
				savingImage: "ł_Saving your image_______ą...",
				saved: "ł_Saved___ą!",
				errorSaving: "ł_Unable to save your image_________ą.",
				skipAndCrop: "ł_Skip and Crop for me_______ą",
				wrongFormat: "ł_This file type is not supported___________ą.",
				noCropWarning: "ł_This image can't be cropped, but you can still save it as your story thumbnail with its original dimensions ({{WIDTH_PIXELS}} x {{HEIGHT_PIXELS}}px)______________________________________________ą."
			}
		},
		content: {
			media: {
				maps: "ł_Maps__ą",
				images: "ł_Images___ą",
				videos: "ł_Videos___ą",
				webpages: "ł_Webpages___ą",
				tags: "ł_Tags__ą",
				gallery: "ł_Gallery___ą"
			},
			headers: {
				status: "ł_Status___ą",
				source: "ł_Source___ą",
				name: "ł_Name__ą",
				shared: "ł_Shared___ą"
			},
			component: {
				mapTour: "ł_Point Number_____ą",
				bullet: "ł_Bullet___ą",
				tab: "ł_Tab__ą",
				accordion: "ł_Section___ą",
				mapJournal: "ł_Section___ą"
			},
			titleType: {
				mapTour: "ł_Caption___ą",
				mapJournal: "ł_URL__ą",
				mapSeries: "ł_URL__ą"
			},
			actions: {
				viewMap: "ł_View Map___ą",
				editMap: "ł_Edit Map___ą",
				fix: "ł_Fix__ą",
				viewLayer: "ł_View Layer____ą"
			},
			contentType: {
				mainStage: "ł_main stage action______ą",
				sidePanel: "ł_description____ą"
			},
			notification: {
				refreshExplanation: "ł_Check your story again________ą",
				checking: "ł_Checking____ą...",
				foundSomeIssues: "ł_We found some issues_______ą",
				noIssuesFound: "ł_No issues found______ą",
				storyPublic: "ł_Your story is now public________ą",
				storyOrg: "ł_Your story is now shared to your organization_______________ą",
				storyPrivate: "ł_Your story is now private_________ą",
				mapPublic: "ł_Your map is now public________ą",
				mapOrg: "ł_Your map is now shared to your organization______________ą",
				mapPrivate: "ł_Your map is now private________ą",
				layerPublic: "ł_Your layer is now public________ą",
				layerOrg: "ł_Your layer is now shared to your organization_______________ą",
				layerPrivate: "ł_Your layer is now private_________ą",
				contentPublic: "ł_Your content is now public_________ą",
				contentOrg: "ł_Your content is now shared to your organization_______________ą",
				contentPrivate: "ł_Your content is now private_________ą",
				storyAndContentPublic: "ł_Your story and its content are now public_____________ą",
				storyAndContentOrg: "ł_Your story and its content are now shared to your organization____________________ą",
				storyAndContentPrivate: "ł_Your story and its content are now private______________ą",
				shareBulkPrompt: "ł_Do you want to share your storyâ€™s content accordingly__________________ą?",
				layersPublic: "ł_Some layers have also been shared publicly______________ą",
				layersOrg: "ł_Some layers have also been shared with your organization__________________ą",
				layersPrivate: "ł_Some layers have also been made private_____________ą",
				mapsPublic: "ł_Some maps have also been shared publicly_____________ą",
				mapsOrg: "ł_Some maps have also been shared with your organization_________________ą",
				mapsPrivate: "ł_Some maps have also been made private____________ą",
				layersAndMapsPublic: "ł_Some maps and layers have also been shared publicly________________ą",
				layersAndMapsOrg: "ł_Some maps and layers have also been shared with your organization_____________________ą",
				layersAndMapsPrivate: "ł_Some maps and layers have also been made private_______________ą",
				yes: "ł_Yes__ą",
				no: "ł_No__ą",
				premiumPublicSuccess: "ł_Your premium content is now publicly accessible_______________ą",
				subscriptionPublicSuccess: "ł_Your subscription content is now publicly accessible_________________ą"
			},
			errors: {
				publicDisabled: "ł_Sharing publicly has been disabled by the Administrator__________________ą",
				noMapName: "ł_Could Not Retrieve Map Name_________ą",
				notPublic: "ł_NOT PUBLIC____ą",
				inaccessible: "ł_INACCESSIBLE_____ą",
				deleted: "ł_DELETED___ą",
				cantAccessVideo: "ł_Could Not Access Video________ą",
				noStoriesFound: "ł_We could not find any Story Maps in your content________________ą.",
				cantShowStories: "ł_Unable to show your story maps. Please try again later__________________ą.",
				consolationSearch: "ł_We couldn't find any stories__________ą.",
				notCompatibleWithBrowser : "ł_My Stories is not supported in Internet Explorer before version {{VERSION_NUMBER}}__________________________ą.",
				pleaseUpdateBrowser: "ł_Please update your browser_________ą.",
				searchTip: "ł_Try and simplify it a bit_________ą.",
				consolationNoStories: "ł_Welcome to My Stories________ą!",
				noStoriesTip: "ł_To make your first story map, check out the Apps page_________________ą.",
				letsGo: "ł_Let's Go___ą",
				cantChangeSharingLevel: "ł_Unable to change sharing level__________ą",
				cantChangeSharingLevels: "ł_Unable to change sharing levels__________ą",
				errorUpdatingTitle: "ł_Error updating title_______ą",
				errorUpdatingSummary: "ł_Error updating summary________ą",
				noEmptyTitle: "ł_Title cannot be empty_______ą",
				cantUpdatePremiumContent: "ł_Unable to update premium content___________ą",
				cantUpdateSubscriptionContent: "ł_Unable to update subscription content____________ą",
				createFirstStory: "ł_Create My First Story_______ą"
			},
			tooltipErrors: {
				mapHasBeenDeleted: "ł_Map has been deleted_______ą",
				layerHasBeenDeleted: "ł_Layer has been deleted________ą",
				mapIsInaccessible: "ł_Map is inaccessible_______ą",
				layerIsInaccessible: "ł_Layer is inaccessible_______ą",
				mapNotYoursNotAccessible: "ł_Map is owned by someone else and isn't accessible________________ą",
				layerServiceOkItemNot: "ł_Layer was added as an item that is deleted or inaccessible__________________ą",
				layerNotYoursNotAccessible: "ł_Layer is owned by someone else and isn't accessible________________ą",
				mapOthersSharedBelowLevel: "ł_Map is not owned by you and is not public_____________ą",
				layerOthersSharedBelowLevel: "ł_Layer is not owned by you and is not public______________ą",
				noMapNoDetails: "ł_Without the map details, we can't tell you anything about the layers_____________________ą",
				mapIsPrivate: "ł_Map is private_____ą",
				mapIsOrg: "ł_Map is only shared in your organization_____________ą",
				layerIsPrivate: "ł_Layer is private______ą",
				layerIsOrg: "ł_Layer is only shared in your organization_____________ą",
				imageInaccessible: "ł_This image is inaccessible_________ą",
				videoInaccessible: "ł_This video is inaccessible_________ą",
				webpageInaccessible: "ł_This web page is inaccessible__________ą",
				layerSecureService: "ł_Layer is a secure service_________ą",
				mapSecureService: "ł_Map is a secure service________ą",
				layerConsumesCredits: "ł_Layer is premium content and consumes credits_______________ą",
				layerSubscriptionContent: "ł_Layer is subscription content__________ą",
				mapConsumesCredits: "ł_Map is premium content and consumes credits______________ą",
				mapSubscriptionContent: "ł_Map is subscription content_________ą"
			},
			tooltipWarnings: {
				cantScanThisTypeAlt: "ł_We're not able to check this type of layer______________ą",
				cantScanThisType: "ł_Layer is not a type of layer we can check_____________ą",
				webpageNotScanned: "ł_Webpages are not checked for issues____________ą"
			},
			scanningErrors: {
				deletedMap: "ł_Deleted content______ą",
				inaccessibleMap: "ł_Inaccessible map content________ą",
				notYoursNotAccessible: "ł_Content not owned by you and not public_____________ą",
				serviceOkItemNot: "ł_Working layers but inaccessible items____________ą",
				someContentNotPublic: "ł_Content not shared publicly_________ą",
				someContentPrivate: "ł_Private content______ą",
				othersSharedBelowLevel: "ł_Content not owned by you and not public_____________ą",
				premiumContent: "ł_Premium content______ą",
				subscriptionContent: "ł_Subscription content_______ą",
				secureService: "ł_Secure services______ą",
				inaccessibleImage: "ł_Inaccessible images_______ą",
				inaccessibleVideo: "ł_Inaccessible videos_______ą",
				inaccessibleWebpage: "ł_Inaccessible webpages_______ą"
			},
			scanningErrorTips: {
				deletedMapTip: "ł_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ą.",
				inaccessibleMapTip: "ł_Tip: Open your web map and remove the broken content, or remove the web map from your story_____________________________ą.",
				notYoursNotAccessibleTip: "ł_Tip: Open the web map and remove the layer or map from the story_____________________ą.",
				serviceOkItemNotTip: "ł_Layers were added as items that are inaccessible or deleted. The layers are working, but this may affect your map (popups, symbology)_________________________________________ą.",
				ignore: "ł_Ignore___ą",
				fix: "ł_Fix__ą",
				clickToShareOrg: "ł_Click the button to share all this content to your organization, or change each item manually by clicking its sharing buttons_______________________________________ą.",
				clickToSharePublic: "ł_Click the button to share all this content publicly, or change each item manually by clicking its sharing buttons___________________________________ą.",
				shareOrg: "ł_Share to your org______ą",
				sharePublicly: "ł_Share publicly_____ą",
				othersSharedBelowLevelTip: "ł_Tip: Some of your story's content is owned by {{USER_NAME}}, and others who view your story may not be able to see it____________________________________ą.",
				secureServiceTip: "ł_Tip: Remove the secure service from your storyÂ or follow the procedure described {{HERE}}____________________________ą.",
				blogArticle: "ł_here__ą",
				premiumContentTip: "ł_Your story contains premium content that will consume {{CREDITS}} upon making it public. Make your story public and continue, or remove the layers from your story__________________________________________________ą.",
				premiumContentPublicTip: "ł_Your story contains premium content that will consume {{CREDITS}} when publicly available. Confirm to make these layers public or remove the layers from your story__________________________________________________ą.",
				subscriptionContentTip: "ł_Your story contains subscription content that is not publicly available by default. Confirm that you want to make these layers available (no credits will be consumed), or remove the layers from your story_______________________________________________________________ą.",
				agolCredits: "ł_ArcGIS Online credits_______ą",
				credits: "ł_credits___ą",
				makePublic: "ł_Make public____ą",
				confirm: "ł_Confirm___ą",
				inaccessibleImageTip: "ł_Tip: Provide the missing image or remove the reference to it___________________ą.",
				inaccessibleVideoTip: "ł_Tip: Provide the missing video or remove the reference to it___________________ą.",
				inaccessibleWebpageTip: "ł_Tip: Provide the missing web page or remove the reference to it____________________ą."
			},
			removeLayer: {
				title: "ł_Fix Layer Issue______ą",
				layersWithIssue: "ł_Layers with this issue: {{NUM_WITH_ISSUE}}______________ą",
				issueExplanation: "ł_The layer {{LAYER_NAME}} was added as an item that is inaccessible or deleted. The layer is working, but this may affect your map (popups, symbology). We cannot tell if the item was important to your story_______________________________________________________________ą.",
				issueSolution: "ł_To fix the issue, you can edit your map, remove the layer, and add the layer back to the map using the following URL____________________________________ą:",
				editMap: "ł_Edit Your Map_____ą",
				clickBelowWhenDone: "ł_When you have finished editing, click the button below__________________ą:",
				rescanAndClose: "ł_Rescan And Close______ą"
			},
			info: {
				ownedBy: "ł_This item is owned by {{USER_NAME}}____________ą",
				unknownUser: "ł_someone else_____ą",
				untitledSection: "ł_(Untitled section)______ą",
				introRecord: "ł_Introduction_____ą"
			},
			layers: {
				layersHeader: "ł_Layers___ą",
				noLayers: "ł_(No Layers)____ą",
				basemapParens: "ł_(basemap)____ą"
			},
			images: {
				thumbnails: "ł_Thumbnails____ą",
				thumbnail: "ł_Thumbnail____ą",
				thumbnailParens: "ł_(thumbnail)____ą"
			},
			general: {
				noTitle: "ł_(no title)____ą",
				loading: "ł_Loading____ą..."
			}
		},
		infographics: {
			mapJournal: {
				firstTitle: "ł_sections___ą",
				secondTitle: "ł_style___ą",
				secondValueA: "ł_side panel____ą",
				secondValueB: "ł_floating panel_____ą",
				thirdTitle: "ł_maps__ą"
			},
			mapTour: {
				firstTitle: "ł_tour points____ą",
				secondTitle: "ł_style___ą",
				secondValueA: "ł_integrated____ą",
				secondValueB: "ł_three-panel____ą",
				thirdTitle: "ł_basemap___ą",
				thirdValueLoading: "ł_Loading____ą...",
				thirdValueUnknown: "ł_unknown___ą"
			},
			mapSeries: {
				firstTitleA: "ł_bullets___ą",
				firstTitleB: "ł_sections___ą",
				firstTitleC: "ł_tabs__ą",
				secondTitle: "ł_style___ą",
				secondValueA: "ł_bulleted___ą",
				secondValueB: "ł_side accordion_____ą",
				secondValueC: "ł_tabbed___ą",
				thirdTitle: "ł_maps__ą"
			},
			swipeSpyglass: {
				firstTitle: "ł_points of interest______ą",
				secondTitle: "ł_style___ą",
				secondValueA: "ł_swipe___ą",
				secondValueB: "ł_spyglass___ą",
				thirdTitle: "ł_maps__ą"
			}
		},
		progress: {
			checkingStories: "ł_Checking your stories for issues____________ą...",
			stop: "ł_Stop__ą",
			exit: "ł_Exit__ą",
			dismiss: "ł_Dismiss___ą",
			done: "ł_Done___ą.",
			noStoriesWithIssuesLower: "ł_No issues found______ą!",
			storiesErrorFree: "ł_Looks like your stories are error-free____________ą",
			scanAllError: "ł_Unable to scan -- we couldn't retrieve one or more of your stories_____________________ą",
			scanProgress: "ł_{{NUM_SCANNED}} of {{NUM_TOTAL}}___________ą",
			scanStopped: "ł_Stories scanned: {{NUM_SCANNED}}, Stories with issues: {{ISSUE_STORIES}}_______________________ą",
			storiesWithIssues: "ł_Stories with issues: {{NUM_STORIES}}____________ą"
		}
    })
);