define(
     ({
        builder: {
            invalidWebmapSelectionAlert: "Den valda webbkartan innehåller inte någon giltigt lager som kan användas. Lägg till ett redigerbart geoobjektlager i webbkartan för att fortsätta.",
            selectFieldsText:"Välj formulärfält",
            selectThemeText: "Välj formulärtema",
            fieldLabelPlaceHolder: "Sätt etikett på fältet",
            fieldDescPlaceHolder: "Beskriv fältet",
            webmapText: "1. Webbkarta",
            layerText: "2. Lager",
            detailsText: "3. Information",
            fieldsText: "4. Fält",
            styleText: "5. Format",
            previewText: "6. Förhandsgranska",
            publishText: "7. Publicera",
            titleText: "GeoForm-byggverktyget",
            descriptionText: "GeoForm är en konfigurerbar mall för formulärbaserad dataredigering av en <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>geoobjekttjänst</a>. Med den här applikationen kan användare ange data via ett formulär i stället för genom kartans popupfönster och samtidigt använda funktionerna hos en<a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>webbkarta</a> tillsammans med redigerbara geoobjekttjänster. Använd det här byggverktyget om du vill anpassa och distribuera ditt GeoForm med hjälp av stegen till vänster.",
            btnPreviousText: "Föregående",
            btnNextText:"Nästa",
            webmapTabTitleText: "Välj en webbkarta",
            btnSelectWebmapText:"Välj webbkarta",
            layerTabTitleText: "Välj redigerbart lager",
            selectLayerLabelText:"Lager",
            selectLayerDefaultOptionText:"Välj lager",
            detailsTabTitleText:"Formulärinformation",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logobild",
            detailDescriptionLabelText: "Beskrivning",
            fieldTabFieldHeaderText: "Fält",
            fieldTabLabelHeaderText: "Etikett",
            fieldTabTypeHeaderText: "Typ",
            fieldTabDescriptionHeaderText: "Beskrivning",
            previewApplicationText: "Förhandsgranska applikation",
            saveApplicationText: "Spara applikation",
            saveText: "Spara",
            toggleNavigationText: "Växla navigering",
            formPlaceholderText: "Mitt formulär",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "Publicerar GeoForm",
            shareBuilderProgressBarMessage:"Vänta...",
            shareBuilderTitleMessage: "Ditt GeoForm har uppdaterats och publicerats!",
            shareBuilderTextMessage: "Du kan börja samla in information genom att dela med andra",
            shareDialogFormText: "Formulärlänk",
            geoformTitleText: "GeoForm",
            layerTabText: "Det är detta lager du bygger ditt GeoForm från. Lagret måste vara en geoobjekttjänst som är aktiverad för redigering med delningsbehörigheter lämpliga för din publik.",
            detailsTabText:"Använd rutorna för formulärinformation nedan för att anpassa titeln, lägga till en anpassad logo och ange en kort beskrivning för GeoForm-publiken.",
            fieldsTabText:"Här kan du välja vilka fält som ska visas för din GeoForm-publik, redigera vilka etiketter som ska visas och ange en kort beskrivning som underlättar datainmatningen.",
            styleTabText: "Formatera ditt GeoForm med de teman som finns nedan enligt dina önskemål.",
            publishTabText: "Om du är färdig med anpassningen av ditt GeoForm kan du spara programmet och börja dela det med din publik. Då kan alltid återgå till byggverktyget och fortsätta att anpassa det utifrån den återkoppling du får."
        }
    })
);