define({
  root: ({
    layer: "Å_Layer___ö",
    sort: "Å_Sort by___ö",
    order: "Å_Order___ö",
    desc: "Å_Desc__ö",
    asc: "Å_Asc__ö",
    loading: "Å_loading&hellip;______ö",
    search: "Å_Search___ö",
    searchPlaceholder: "Å_Find reports_____ö",
    noResults: "Å_No results____ö",
    ascending: "Å_Ascending____ö",
    descending: "Å_Descending____ö"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});