define(
     ({
        map: {
            error: "Det gick inte att skapa kartan"
        },
        onlineStatus: {
            offline: "Du arbetar just nu offline. Inskickade formulär sparas lokalt tills det går att ansluta till servern.",
            reconnecting: "Återansluter&hellip;",
            pending: "${total} väntande redigering(ar) skickas in när nätverksanslutningen har återupprättats."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innehåll",
                    favoritesLabel: "Mina favoriter"
                },
                title: "Välj webbkarta",
                searchTitle: "Sök",
                ok: "OK",
                cancel: "Avbryt",
                placeholder: "Ange sökterm"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innehåll",
                    favoritesLabel: "Mina favoriter"
                },
                title: "Välj grupp",
                searchTitle: "Sök",
                ok: "OK",
                cancel: "Avbryt",
                placeholder: "Ange sökterm"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Å_Here is a link to a GeoForm_ö"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Nordlig",
            utm_easting: "Östlig",
            utm_zone_number: "Zonnummer",
            geoFormGeneralTabText: "1. Ange information",
            locationInformationText: "2. Välj plats",
            submitInformationText: "3. Fyll i formulär",
            submitInstructions: "Lägg till den här informationen i kartan.",
            myLocationText: "Aktuell plats",
            locationDescriptionForMoreThanOneOption: "Å_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ö.",
            locationDescriptionForOneOption: "Å_Specify the location for this entry by clicking/tapping the map or by using the following option_ö.",
            locationDescriptionForNoOption: "Å_Specify the location for this entry by clicking/tapping the map_ö.",
            addressText: "Sök",
            geographic: "Lat/lon",
            locationTabText: "Plats",
            locationPopupTitle: "Plats",
            submitButtonText: "Skicka in bidrag",
            submitButtonTextLoading: "Skickar in&hellip;",
            formValidationMessageAlertText: "Följande fält krävs:",
            selectLocation: "Å_Please select a location for your submission_ö.",
            emptylatitudeAlertMessage: "Ange en ${openLink}latitud${closeLink}-koordinat.",
            emptylongitudeAlertMessage: "Ange en ${openLink}longitud${closeLink}-koordinat.",
            shareUserTitleMessage: "Tack för ditt bidrag!",
            entrySubmitted: "Ditt bidrag har lämnats in till kartan.",
            shareThisForm: "Dela det här formuläret",
            shareUserTextMessage: "Uppmana andra att bidra med följande alternativ.",
            addAttachmentFailedMessage: "Det gick inte att lägga till bilagan i lagret",
            addFeatureFailedMessage: "Det gick inte att lägga till geoobjektet i lagret",
            noLayerConfiguredMessage: "Å_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ö.",
            placeholderLatitude: "Latitud (Y)",
            placeholderLongitude: "Longitud (X)",
            latitude: "Latitud",
            longitude: "Longitud",
            findMyLocation: "Hitta mig",
            finding: "Lokaliserar&hellip;",
            backToTop: "Tillbaka till start",
            addressSearchText: "Ditt bidrag kommer att visas här. Du kan dra nålen för att korrigera platsen.",
            shareModalFormText: "Formulärlänk",
            close: "Stäng",
            locationNotFound: "Det gick inte att hitta platsen.",
            setLocation: "Ange plats",
            find: "Sök efter adress eller plats",
            attachment: "Bilaga",
            toggleDropdown: "Växla listmenyn",
            invalidString: "Å_Please enter valid value_ö.",
            invalidSmallNumber: "Å_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ö.",
            invalidNumber: "Å_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ö.",
            invalidFloat: "Å_Please enter valid ${openStrong}floating point${closeStrong} value_ö.",
            invalidDouble: "Å_Please enter valid ${openStrong}double${closeStrong} value_ö.",
            invalidLatLong: "Å_Please enter valid latitude and longitude coordinates_ö.",
            invalidUTM: "Å_Please enter valid UTM coordinates_ö.",
            invalidUSNG: "Å_Please enter valid USNG coordinates_ö.",
            invalidMGRS: "Å_Please enter valid MGRS coordinates_ö.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Välj&hellip;",
            applyEditsFailedMessage: "Ditt bidrag kan tyvärr inte lämnas in. Försök igen.",
            requiredFields: "Det förekommer några fel. Rätta till dem nedan.",
            requiredField: "(obligatoriskt)",
            error: "Fel",
            textRangeHintMessage: "${openStrong}Tips:${closeStrong} minsta värde ${minValue} och största värde ${maxValue}",
            dateRangeHintMessage: "${openStrong}Tips:${closeStrong} minsta datum ${minValue} och största datum ${maxValue}",
            remainingCharactersHintMessage: "Å_${value} characters remaining_ö"
        },
        builder: {
            invalidUser: "Du har tyvärr inte behörighet att visa det här objektet",
            invalidWebmapSelectionAlert: "Den valda webbkartan innehåller inte någon giltigt lager som kan användas. Lägg till ett redigerbart geoobjektlager i webbkartan för att fortsätta.",
            invalidWebmapSelectionAlert2: "Mer information finns i ${openLink}Vad är geoobjekttjänster?${closeLink}",
            selectFieldsText: "Välj formulärfält",
            selectThemeText: "Välj formulärtema",
            webmapText: "Webbkarta",
            layerText: "Lager",
            detailsText: "Information",
            fieldsText: "Fält",
            styleText: "Format",
            optionText: "Alternativ",
            previewText: "Förhandsgranska",
            publishText: "Publicera",
            optionsApplicationText: "Alternativ",
            titleText: "Byggverktyg",
            descriptionText: "Å_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ö.",
            btnPreviousText: "Föregående",
            btnNextText: "Nästa",
            webmapTabTitleText: "Välj en webbkarta",
            viewWebmap: "Visa webbkarta",
            webmapDetailsText: "Å_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ö",
            btnSelectWebmapText: "Välj webbkarta",
            btnSelectWebmapTextLoading: "Laddar&hellip;",
            layerTabTitleText: "Välj redigerbart lager",
            selectLayerLabelText: "Lager",
            selectLayerDefaultOptionText: "Välj lager",
            detailsTabTitleText: "Formulärinformation",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logobild",
            descriptionLabelText: "Å_Form Instructions & Details_ö",
            fieldDescriptionLabelText: "Å_Help Text (optional)_ö",
            fieldTabFieldHeaderText: "Fält",
            fieldTabLabelHeaderText: "Etikett",
            fieldTabDisplayTypeHeaderText: "Visa som",
            fieldTabOrderColumnText: "Å_Order_ö",
            fieldTabVisibleColumnText: "Å_Enabled_ö",
            selectMenuOption: "Valmeny",
            selectRadioOption: "Alternativknapp",
            selectTextOption: "Text",
            selectDateOption: "Å_Date Picker_ö",
            selectRangeOption: "Å_Touch-Spinner_ö",
            selectCheckboxOption: "Kryssruta",
            selectMailOption: "E-post",
            selectUrlOption: "URL",
            selectTextAreaOption: "Å_Text Area_ö",
            previewApplicationText: "Förhandsgranska applikation",
            saveApplicationText: "Spara applikation",
            saveText: "Spara",
            toggleNavigationText: "Växla navigering",
            formPlaceholderText: "Mitt formulär",
            shareBuilderInProgressTitleMessage: "Publicerar GeoForm",
            shareBuilderProgressBarMessage: "Vänta&hellip;",
            shareBuilderTitleMessage: "Objektet har sparats",
            shareBuilderTextMessage: "Du kan börja samla in information genom att dela med andra",
            shareModalFormText: "Formulärlänk",
            shareBuilderSuccess: "Ditt GeoForm har uppdaterats och publicerats!",
            geoformTitleText: "GeoForm",
            layerTabText: "Det är detta lager du bygger ditt GeoForm från. Lagret måste vara en geoobjekttjänst som är aktiverad för redigering med delningsbehörigheter lämpliga för din publik.",
            detailsTabText: "Använd rutorna för formulärinformation nedan för att anpassa titeln, lägga till en anpassad logo och ange en kort beskrivning för GeoForm-publiken. I beskrivningen kan du lägga till länkar till andra resurser, kontaktinformation och till och med visa publiken till ett webbkartprogram som innehåller alla data som har samlats in med GeoForm",
            fieldsTabText: "Här kan du välja vilka fält som ska visas för din GeoForm-publik, redigera vilka etiketter som ska visas och ange en kort beskrivning som underlättar datainmatningen.",
            styleTabText: "Formatera ditt GeoForm med de teman som finns nedan enligt dina önskemål.",
            publishTabText: "Om du är färdig med anpassningen av ditt GeoForm kan du spara programmet och börja dela det med din publik. Då kan alltid återgå till byggverktyget och fortsätta att anpassa det utifrån den återkoppling du får.",
            headerSizeLabel:"Å_Header Size_ö",
            smallHeader: "Använd liten rubrik",
            bigHeader: "Å_Use Large Header_ö",
            pushpinText: "Knappnål",
            doneButtonText: "Å_Save and Exit_ö",
            fieldTabPlaceHolderHeaderText: "Tips (valfritt)",
            enableAttachmentLabelText: "Å_${openStrong}Enable Attachments${closeStrong}_ö",
            enableAttachmentLabelHint: "Å_You can enable/disable the attachments here_ö",
            attachmentIsRequiredLabelText: "Å_${openStrong}Attachment Required${closeStrong}_ö",
            attachmentIsRequiredLabelHint: "Å_If necessary, users can be required to enter an attachment_ö.",
            attachmentLabelText: "Å_Attachment Button Label_ö",
            attachmentLabelHint: "Å_This is the text that will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ö",
            attachmentDescription: "Beskrivning av bilaga",
            attachmentHint: "Vid behov kan du ange ytterligare information om bilagor här.",
            jumbotronDescription: "Å_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ö",
            shareGeoformText: "Dela GeoForm",
            shareDescription: "Med delningspanelen är det enkelt för din publik att dela GeoForm med andra som har lämnat ett bidrag. Du kan inaktivera den när som helst.",
            defaultMapExtent: "Standardutbredning för karta",
            defaultMapExtentDescription: "Kartan återgår till standardutbredningen i webbkartan efter bidraget. Detta går att inaktivera när som helst.",
            pushpinOptionsDescription: "Välj mellan flera olika färger på kartans knappnål. Den bör skilja sig från kartans symbologi för att hjälpa användaren placera sitt bidrag på kartan",
            selectLocationText: "Välj plats enligt",
            myLocationText: "Min plats",
            searchText: "Sök",
            coordinatesText: "Latitud- och longitudkoordinater",
            usng: "USNG-koordinater",
            mgrs: "MGRS-koordinater",
            utm: "UTM-koordinater",
            selectLocationSDescription: "Låt användare välja en plats med de här metoderna.",
            dragTooltipText:"Å_Drag the field where you want it to appear_ö",
            showHideLayerText:"Å_Show/Hide Layer_ö",
            showHideLayerHelpText:"Å_You can configure the GeoForm to Show/Hide Layer_ö"
        }
    })
);