define(
     ({
        map: {
            error: "Det gick inte att skapa kartan"
        },
        onlineStatus: {
            offline: "Du arbetar just nu offline. Inskickade formulär sparas lokalt tills det går att ansluta till servern.",
            reconnecting: "Återansluter&hellip;",
            pending: "${total} väntande redigering(ar) skickas in när nätverksanslutningen har återupprättats."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innehåll",
                    favoritesLabel: "Mina favoriter"
                },
                title: "Välj webbkarta",
                searchTitle: "Sök",
                ok: "OK",
                cancel: "Avbryt",
                placeholder: "Ange sökterm"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innehåll",
                    favoritesLabel: "Mina favoriter"
                },
                title: "Välj grupp",
                searchTitle: "Sök",
                ok: "OK",
                cancel: "Avbryt",
                placeholder: "Ange sökterm"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Nordlig",
            utm_easting: "Östlig",
            utm_zone_number: "Zonnummer",
            geoFormGeneralTabText: "1. Ange information",
            locationInformationText: "2. Välj plats",
            submitInformationText: "3. Fyll i formulär",
            submitInstructions: "Lägg till den här informationen i kartan.",
            myLocationText: "Å_Current Location_ö",
            locationDescription: "Å_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ö",
            addressText: "Sök",
            geographic: "Å_Lat/Lon_ö",
            locationTabText: "Plats",
            locationPopupTitle: "Å_Location_ö",
            submitButtonText: "Å_Submit Entry_ö",
            submitButtonTextLoading: "Skickar in&hellip;",
            formValidationMessageAlertText: "Följande fält krävs:",
            selectLocation: "Välj en ${openLink}plats${closeLink} för ditt bidrag.",
            emptylatitudeAlertMessage: "Ange en ${openLink}latitud${closeLink}-koordinat.",
            emptylongitudeAlertMessage: "Ange en ${openLink}longitud${closeLink}-koordinat.",
            shareUserTitleMessage: "Tack för ditt bidrag!",
            entrySubmitted: "Å_Your entry has been submitted to the map._ö",
            shareThisForm: "Å_Share This Form_ö",
            shareUserTextMessage: "Å_Tell others to contribute using the following options._ö",
            addAttachmentFailedMessage: "Det gick inte att lägga till bilagan i lagret",
            addFeatureFailedMessage: "Det gick inte att lägga till geoobjektet i lagret",
            noLayerConfiguredMessage: "Oj! Här finns inget att se. Om du vill börja samla in formulärbidrag konfigurerar du GeoForm och väljer ett redigerbart geoobjekttjänstlager att använda.",
            placeholderLatitude: "Latitud (Y)",
            placeholderLongitude: "Longitud (X)",
            latitude: "Latitud",
            longitude: "Longitud",
            findMyLocation: "Å_Locate Me_ö",
            finding: "Lokaliserar&hellip;",
            backToTop: "Tillbaka till start",
            addressSearchText: "Ditt bidrag kommer att visas här. Du kan dra nålen för att korrigera platsen.",
            shareModalFormText: "Formulärlänk",
            close: "Stäng",
            locationNotFound: "Det gick inte att hitta platsen.",
            setLocation: "Å_Set Location_ö",
            find: "Å_Find address or place_ö",
            attachment: "Bilaga",
            toggleDropdown: "Växla listmenyn",
            invalidLatLong: "Ange giltiga koordinater för ${latLink}latitud${closeLink} och ${lngLink}longitud${closeLink}.",
            invalidUTM: "Ange giltiga ${openLink}UTM${closeLink}-koordinater.",
            invalidUSNG: "Ange giltiga ${openLink}USNG${closeLink}-koordinater.",
            invalidMGRS: "Ange giltiga ${openLink}MGRS${closeLink}-koordinater.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Välj&hellip;",
            applyEditsFailedMessage: "Ditt bidrag kan tyvärr inte lämnas in. Försök igen.",
            requiredFields: "Det förekommer några fel. Rätta till dem nedan.",
            requiredField: "Å_(required)_ö",
            error: "Fel",
            textRangeHintMessage: "Å_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ö",
            dateRangeHintMessage: "Å_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ö"
        },
        builder: {
            invalidUser: "Å_Sorry, you dont have permission to view this item_ö",
            invalidWebmapSelectionAlert: "Å_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ö",
            invalidWebmapSelectionAlert2: "Å_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ö",
            selectFieldsText: "Å_Select Form Fields_ö",
            selectThemeText: "Å_Select Form Theme_ö",
            webmapText: "Å_Webmap_ö",
            layerText: "Å_Layer_ö",
            detailsText: "Å_Details_ö",
            fieldsText: "Å_Fields_ö",
            styleText: "Å_Style_ö",
            optionText: "Å_Options_ö",
            previewText: "Å_Preview_ö",
            publishText: "Å_Publish_ö",
            optionsApplicationText: "Å_Options_ö",
            titleText: "Å_Builder_ö",
            descriptionText: "Å_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ö",
            btnPreviousText: "Å_Previous_ö",
            btnNextText: "Å_Next_ö",
            webmapTabTitleText: "Å_Select a Webmap_ö",
            viewWebmap: "Å_View webmap_ö",
            btnSelectWebmapText: "Å_Choose Webmap_ö",
            btnSelectWebmapTextLoading: "Å_Loading&hellip;_ö",
            layerTabTitleText: "Å_Select Editable Layer_ö",
            selectLayerLabelText: "Å_Layer_ö",
            selectLayerDefaultOptionText: "Å_Select Layer_ö",
            detailsTabTitleText: "Å_Form Details_ö",
            detailTitleLabelText: "Å_Title_ö",
            detailLogoLabelText: "Å_Logo Image_ö",
            descriptionLabelText: "Å_Help Text (optional)_ö",
            fieldTabFieldHeaderText: "Å_Field_ö",
            fieldTabLabelHeaderText: "Å_Label_ö",
            fieldTabDisplayTypeHeaderText: "Å_Display As_ö",
            selectMenuOption: "Å_Select Menu_ö",
            selectRadioOption: "Å_Radio Button_ö",
            selectTextOption: "Å_Text_ö",
            selectCheckboxOption: "Å_Checkbox_ö",
            selectMailOption: "Å_Email_ö",
            selectUrlOption: "Å_URL_ö",
            selectTextAreaOption: "Å_Textarea_ö",
            previewApplicationText: "Å_Preview Application_ö",
            saveApplicationText: "Å_Save Application_ö",
            saveText: "Å_Save_ö",
            toggleNavigationText: "Å_Toggle navigation_ö",
            formPlaceholderText: "Å_My Form_ö",
            shareBuilderInProgressTitleMessage: "Å_Publishing GeoForm_ö",
            shareBuilderProgressBarMessage: "Å_Please Wait&hellip;_ö",
            shareBuilderTitleMessage: "Å_Success! Item saved_ö",
            shareBuilderTextMessage: "Å_You can start collecting information by sharing with others_ö",
            shareModalFormText: "Å_Form Link_ö",
            shareBuilderSuccess: "Å_Your GeoForm has been updated & published!_ö",
            geoformTitleText: "Å_Geo Form_ö",
            layerTabText: "Å_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ö",
            detailsTabText: "Å_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._ö",
            fieldsTabText: "Å_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ö",
            styleTabText: "Å_Style your GeoForm using the themes below based on your preference._ö",
            publishTabText: "Å_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ö",
            smallHeader: "Å_Use Small Header_ö",
            pushpinText: "Å_Push pin_ö",
            doneButtonText: "Å_View Application Item_ö",
            fieldTabPlaceHolderHeaderText: "Å_Hint (optional)_ö",
            attachmentLabelText: "Å_Attchment Label_ö",
            attachmentLabelHint: "Å_Tell users what type of file to attach._ö",
            attachmentDescription: "Å_Attachment Description_ö",
            attachmentHint: "Å_If necessary, you can provide additional attachment instructions here._ö",
            jumbotronDescription: "Å_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ö",
            shareGeoformText: "Å_Share Geoform_ö",
            shareDescription: "Å_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._ö",
            defaultMapExtent: "Å_Default Map Extent_ö",
            defaultMapExtentDescription: "Å_The map will reset to the default extent in your web map after submission - this can be disabled at any time._ö",
            pushpinOptionsDescription: "Å_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ö",
            selectLocationText: "Å_Select Location By_ö",
            myLocationText: "Å_My Location_ö",
            searchText: "Å_Search_ö",
            coordinatesText: "Å_Latitude & Longitude Coordinates_ö",
            usng: "Å_USNG Coordinates_ö",
            mgrs: "Å_MGRS Coordinates_ö",
            utm: "Å_UTM Coordinates_ö",
            selectLocationSDescription: "Å_Allow users to select a location using these methods._ö"
        }
    })
);