define({
  "tagHeaderText": "Tagi",
  "expandGroupDescText": "Vairāk",
  "shrinkGroupDescText": "Mazāk",
  "layoutText": "Izkārtojums",
  "signInText": "Pierakstīties",
  "signOutText": "Izrakstīties",
  "showNullValue": "Nav pieejams",
  "detailsDisplayText": "Detaļas",
  "sortByText": "Kārtot pēc",
  "sortByViewText": "Skati",
  "sortByDateText": "Datums",
  "sortByNameText": "Nosaukums",
  "gridViewTitle": "Režģa skats",
  "listViewTitle": "Saraksta skats",
  "appHeaderTitle": "Mājas",
  "allText": "VISS",
  "orgText": "ORG",
  "grpText": "GRP",
  "groupLogoText": "Grupas logotips",
  "appTypeText": "Tips",
  "appOwnerText": "Īpašnieks",
  "tryItButtonText": "Skats",
  "downloadButtonText": "Lejupielāde",
  "appDesText": "Apraksts",
  "reviewText": "Komentāri",
  "itemDetailsLegendTab": "LEĢENDA",
  "itemDetailsInfoTab": "INFORMĀCIJA",
  "tagsText": "Tagi",
  "sizeText": "Lielums",
  "accessConstraintsText": "Piekļuves un izmantošanas ierobežojumi",
  "numberOfCommentsText": "Komentāri",
  "numberOfRatingsText": "Novērtējumi",
  "numberOfViewsText": "Skati",
  "noResultsText": "Nav atrasti rezultāti.",
  "backToMapButtonText": "Karte",
  "showMoreResultsGalleryText": "Rādīt vairāk rezultātu",
  "clearBtnTitle": "Notīrīt",
  "addressSearchBtnTitle": "Adreses meklēšana",
  "fullScreenBtnTitle": "Pilnekrāna režīms",
  "noLegendText": "Bez leģendas",
  "sizeUnitKB": "KB",
  "sizeUnitMB": "MB",
  "itemUnavailableText": "Šajā ierīcē vienība nav pieejama.",
  "title": {
    "settingsBtnTitle": "Iestatījumi",
    "itemSearchBtnTitle": "Vienības meklēšana",
    "infoBtnTitle": "Informācija",
    "sortByBtnTitle": "Kārtot pēc",
    "layoutBtnTitle": "Izkārtojums",
    "signInBtnTitle": "Pierakstīties",
    "signOutBtnTitle": "Izrakstīties",
    "geolocationBtnTitle": "Ģeoizvietojums",
    "ascendingSort": "Pieaugoši",
    "descendingSort": "Dilstošā secībā",
    "viewBtnTitle": "ķ_View__ū",
    "backButtonTitle": "ķ_Back__ū"
  },
  "errorMessages": {
    "emptyGroup": "Konfigurētajā grupā nav nekādu datu, lai veiktu vaicājumu.",
    "invalidSearch": "Nav atrasti rezultāti.",
    "invalidBasemapQuery": "Nevar iegūt pamatkaršu grupu.",
    "falseConfigParams": "Nepieciešamās konfigurācijas atslēgas vērtības ir vai nu nulle, vai tām nav tiešas atbilstības slāņa atribūtiem. Šis ziņojums var tikt rādīts vairākas reizes.",
    "invalidLocation": "Pašreizējais izvietojums nav atrasts.",
    "invalidProjection": "Nevar projektēt pašreizējo izvietojumu kartē.",
    "widgetNotLoaded": "Neizdevās ielādēt logrīkus.",
    "minfontSizeGreater": "Minimālā fonta lieluma vērtība konfigurācijas iestatījumos ir lielāka par maksimālo vērtību.",
    "layerNotFound": "Nevar iegūt datus no slāņiem.",
    "unableToOpenItem": "Nevar atvērt vienību.",
    "wmsSpatialReferenceError": "WMS slāņa telpiskā atsauce neatbilst kartes telpiskajai atsaucei.",
    "noPublicItems": "Konfigurētajā grupā nav nevienas publiskas vienības vai arī ar šo grupu pagaidām nav kopīgota neviena vienība.",
    "emptyUsernamePassword": "Lūdzu, ievadiet lietotājvārdu un paroli.",
    "noFullScreenSupport": "Pašreizējā pārlūkā pilnekrāna režīms nav atbalstīts.",
    "notMemberOfOrg": "Jūs neesat šīs organizācijas dalībnieks"
  }
});